### PR TITLE
[csharp] Fixed enum values with whitespace

### PR DESCRIPTION
**Pull request by devhl-labs**
Fixes https://github.com/OpenAPITools/openapi-generator/issues/4954

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
please rebase when you've time. thank you.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
samples not up-to-date: https://github.com/OpenAPITools/openapi-generator/actions/runs/5862947099/job/15895644976?pr=16316

looks like this change impact ruby and c++ generators as well.

**Comment by wing328** [comment]
For the C++ changes:
```diff
 void Enum_Test::setEnumInteger(int32_t value)
 {
-    static const std::array<int32_t, 2> allowedValues = {
-        1, -1
+    static const std::array<int32_t, 1> allowedValues = {
+        1
     };
```
looks like `-1` is removed even though it's not a duplicate.

**Comment by devhl-labs** [comment]
The value is not a duplicate but the name must be.

**Comment by devhl-labs** [comment]
image
image

The problem is that the cpp and ruby generators are producing the same for these two enums even though the values are different.

image


Above is the issue I am trying to fix. In C#, the second and third options here are producing the same enum name. If we prefer, when an enum name is reused, I can just append a number to the subsequent appearances.

**Comment by devhl-labs** [comment]
This was changed. Instead of removing enums whose name has already been used, I now just append a number to the subsequent appearances, and only in C# generator. Without this change, Duplicatevalue would appear twice and the C# would not compile.

image

**Pull request merged**
