### PR TITLE
[core][general] Add metadata file tracking to aid in "Golden Tests" regeneration

### PR DESCRIPTION
**Pull request by jimschubert**
Discussed this with @Fjolnir-Dvorak as a way to simplify his #4030.

This adds a `FILES` file under the metadata directory in the generated directory.

The idea is that we could use this to allow for automatic "clean" of generated sources to avoid issues where file renames or stale files require manual cleanup.

cc @OpenAPITools/generator-core-team 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
```
Running ./bin/swift5-petstore-readOnlyProperties.sh (output to /dev/null)
--
4750 | [main] ERROR o.o.c.config.CodegenConfigurator - ./bin/swift5-petstore-readonlyProperties.json (No such file or directory)
4751 | [main] ERROR o.o.c.config.CodegenConfigurator - ./bin/swift5-petstore-readonlyProperties.json (No such file or directory)
4752 | Exception in thread "main" java.lang.RuntimeException: Unable to deserialize config file: ./bin/swift5-petstore-readonlyProperties.json
4753 | at org.openapitools.codegen.config.CodegenConfigurator.readDynamicSettings(CodegenConfigurator.java:146)
4754 | at org.openapitools.codegen.config.CodegenConfigurator.fromFile(CodegenConfigurator.java:82)
4755 | at org.openapitools.codegen.cmd.Generate.execute(Generate.java:267)
4756 | at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
4757 | at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
4758 | Running ./bin/swift5-petstore-result.sh (output to /dev/null)
```
That's the issue reported by Drone.io CI.

I couldn't repeat the issue locally and I don't see any changes to ./bin/swift5-petstore-readonlyProperties.json in this PR ....

**Comment by jimschubert** [comment]
@wing328 yeah I didn't touch that file or anything to do with deserialize logic. Drone sometimes gets into some state that I can't clear (probably bad cache).

**Comment by wing328** [comment]
Minor suggestion: what about adding 1 or 2 lines (starting with # to indicate it's a comment) explaining what `FILES` does?

**Comment by jimschubert** [comment]
@wing328 I don't think adding a comment is necessary here. The filename and contents are pretty self explanatory. We can document online if people require more details.

**Comment by wing328** [comment]
The actual error in Drone.io CI is 
```
Running ./bin/cpp-qt5-petstore.sh (output to /dev/null)
Exception in thread "main" java.lang.IllegalArgumentException: 'other' is different type of Path
    at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:429)
    at java.base/sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
    at org.openapitools.codegen.DefaultGenerator.lambda$generate$3(DefaultGenerator.java:1074)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
    at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
    at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
    at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
    at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1073)
    at org.openapitools.codegen.cmd.Generate.execute(Generate.java:431)
    at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
    at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
ERROR!! FAILED TO RUN ./bin/cpp-qt5-petstore.sh
```

I can now repeat the issue in the master.

Does the error message give you any clue on why `./bin/cpp-qt5-petstore.sh failed to run?

**Pull request merged**
