### PR TITLE
Fix 18089: Fail to do model_validate in the deserialization if the object inherited via AllOf

### PR DESCRIPTION
**Pull request by zishunwei**
Fix issue https://github.com/OpenAPITools/openapi-generator/issues/18089

We are referring the mustache template to generate the model files https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model_generic.mustache#L285 and reading the data stored in `allVars` to generated the codes in model files.

The cause of this issue is now the `allVars` of the generating model only stores the vars/properties in the parent model (_typeName in my example shown in https://github.com/OpenAPITools/openapi-generator/issues/18089), but missing the vars/properties of the generating model itself (nameA, nameB in my example shown in https://github.com/OpenAPITools/openapi-generator/issues/18089). It will cause failing to do the deserialization due to the lack of the vars/properties in `model_validate`.

By my triaging, now we are doing `m.allVars = new ArrayList<>();` if using AllOf and supporting Inheritance, will remove the the vars/properties of the generating model itself stored before. IMO we should have all vars/properties data including those of the parent model and itself both in `allVars`, then it can be generated by the template and pass the `model_validate` in deserialization.

In this change, I remove this line and keep the vars/properties data in `m.allVars` added before in `m.allVars`. Meanwhile, `m.allVars = m.vars` is a shallow copy, causing changing the value of  `m.allVars` will change the value of `m.vars` meanwhile as not expected, so did a packaging here to avoid this.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by zishunwei** [comment]
Hi @multani @fa0311 @krjakbrjak @tomplus @cbornet, could you please review this PR since it is targeting Python? Thanks! also cc: @wing328

**Comment by wing328** [comment]
can you please resolve the merge conflicts when you've time?

**Comment by wing328** [comment]
>  if using AllOf and supporting Inheritance

are you referring to supporting inheritance in allOf without using discriminator?

**Comment by wing328** [comment]
please try the suggestion in https://github.com/OpenAPITools/openapi-generator/issues/18089#issuecomment-2028773494 to start with

**Pull request closed without merging**
