### PR TITLE
Add listFromJson method to fix #4887

### LINKED ISSUE #4887: [BUG][DART] Method listFromJson isn't defined on array of enums
### Description

When I define inside an object a property that is an array of enums, the generated code call a method `listFromJson` that is not defined inside the enum model causing build problems.

##### openapi-generator version

```bash
➜ openapi-generator version
4.2.2
```
##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
    title: RetroShare OpenApi wrapper
    version: 0.0.1
    description: RetroShare OpenApi wrapper generated using Doxygen documentation
    license:
        name: AGPLv3
servers:
    - url: http://127.0.0.1:9092/
    
paths:
    /jsonApiServer/version:
        post:
            summary: blahblah             
            responses:
                '200':
                    description: >
                            return: 
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FileChunksInfo'

components:      
    schemas:
        FileChunksInfo:
            type: object
            properties:
                chunks:
                    type: array
                    items:
                        $ref: '#/components/schemas/ChunkState'
        ChunkState:
            type: integer
            enum:
                
                    - 0
                    - 1
                    - 2
                    - 3
            x-enum-varnames:
                
                    - CHUNK_OUTSTANDING
                    - CHUNK_ACTIVE
                    - CHUNK_DONE
                    - CHUNK_CHECKING
```

##### Command line used for generation

```bash
➜ openapi-generator generate -i definition.yml -g dart -o openapi-dart-retroshare-api-wrapper
```

##### Steps to reproduce

Just copy the .yml definition and run the command. 

After the code is generated be sure that all the dependencies are installed. I us VSCodium with Dart extension for that. 

Once all installed you will see a build error on lib/model/file_chunks_info.dart.

```dart
  FileChunksInfo.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    chunks = (json['chunks'] == null) ?
      null :
      ChunkState.listFromJson(json['chunks']);
  }
```

Where `listFromJson` is not defined on `ChunkState` model.

##### Related issues/PRs

Maybe related to https://github.com/OpenAPITools/openapi-generator/issues/2567

##### Suggest a fix

Should the nums have the method `listFromJson`?

### PR DESCRIPTION
**Pull request by selankon**
Fix #4887

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09) @athornz (2019/12) @amondnet (2019/12)

**Comment by wing328** [comment]
We'll merge it over the weekend if there's no feedback from anyone.

**Comment by nickmeinhold** [comment]
Awesome work with the issue and repro steps!  You've set everything up to make it easy to add a test for this to the CI - would you be up for that?  No worries if not, I can add a new issue to create tests for this and some other recent PRs.

**Comment by selankon** [comment]
Thanks (: 
I'm mot sure of how to create the tests, maybe if you do it I can check the code an learn it for the future for future PR. Meanwhile I'm little busy now...

**Comment by wing328** [comment]
I'll merge it over the weekend. Sorry for taking a bit long.

**Pull request merged**
