### PR TITLE
Fix issue deserializing to nullptr

### PR DESCRIPTION
**Pull request by dan-drl**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
This addresses bug #3374. In the test json provided for this bug, there is an edge case that allows null pointers to occur. The edge case occurs because the value property is both nullable:true and required.

@ravinikam @stkrwork @fvarose @etherealjoy @MartinDelille

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR. For your upcoming PRs, I would suggest creating a new branch for the change.

**Comment by wing328** [comment]
@dan-drl thanks for the PR, which has been included in the 4.1.0 release: https://twitter.com/oas_generator/status/1160000504455319553

**Comment by TomerJLevy** [comment]
Hi,

In 'openapi-generator/samples/client/petstore/cpp-restsdk/client/ModelBase.cpp':

You should use:

> utility::datetime ModelBase::dateFromJson(const web::json::value& val)
> {
>     return val.is_null() ? utility::datetime::from_string(utility::conversions::to_string_t("NULL"), utility::datetime::ISO_8601) : utility::datetime::from_string(val.as_string(), utility::datetime::ISO_8601);
> }

instead of:

> utility::datetime ModelBase::dateFromJson(const web::json::value& val)
> {
>     return val.is_null() ? utility::datetime::from_string(L"NULL", utility::datetime::ISO_8601) : utility::datetime::from_string(val.as_string(), utility::datetime::ISO_8601);
> }

Because 'string_t' may be std::string or std::wstring and it fails to compile if std::string

**Comment by etherealjoy** [comment]
@TomerJLevy 
Thanks for pointing this out, do you wish to make a contribution by creating a new PR for this?
Or we can take this snippet and make a PR.

**Comment by TomerJLevy** [comment]
Fix - commit 2c95d10

**Comment by wing328** [comment]
@dan-drl thanks again for the PR. When you've time, can you please contact me via the email address in my Github profile?

**Pull request merged**
