### PR TITLE
Fix wrong matching between yaml enum value starting with a digit and its Java code (JavaJaxrs/resteasy)

### LINKED ISSUE #1051: [Java][jaxrs-resteasy] wrong matching between yaml enum value starting with a digit and its java code
##### Description

A yaml enum value like _5GMM_ is translated into java enum value __5GMM_.
Because of that, the supported value at runtime is now __5GMM_ which doesn't match the yaml definition.

##### openapi-generator version

3.2.3

##### OpenAPI declaration file content or url

In file TS29518_Namf_Communication.yaml
```yaml
# line 1510
    N1MessageClass:
      type: string
      enum:
          - "5GMM"
          - "SM"
          - "LPP"
          - "SMS"
```

Then the generated java source code for enum N1MessageClass is :
```java
package org.openapitools.model;

import java.util.Objects;
import java.util.ArrayList;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.validation.constraints.*;
public enum N1MessageClass {
    _5GMM, SM, LPP, SMS
}
```

##### Command line used for generation

```
java -jar ./openapi-generator-cli-3.2.3.jar generate -i TS29518_Namf_Communication.yaml -g jaxrs-resteasy -o generated-files
```

##### Steps to reproduce

Please unzip the attached file and type the command (see above) in the directory where files are stored.
Looks for the generated java enum N1MessageClass file in the generated-files directory.
A copy of the generated source files is available under the generated-files.sav folder. 

[issue.zip](https://github.com/OpenAPITools/openapi-generator/files/2388104/issue.zip)

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Cherry-picking https://github.com/OpenAPITools/openapi-generator/pull/1065

Credits go to @tnmtechnologies 

To fix #1051

cc @bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

### CODE REVIEW

**Comment by cbornet** [comment]
I think Jackson is already configured globally to ser/deser enums as String. So JsonValue and JsonCreator are not needed.

**Comment by wing328** [comment]
> The JavaJaxrs/resteasy/enumOuterClass.mustache and
JavaJaxrs/resteasy/enumClass.mustache files were not inline with those
in JavaJaxrs directory.

@cbornet thanks for reviewing the change. According to @tnmtechnologies , the fix was copied from `JavaJaxrs` directory.

**Comment by cbornet** [comment]
I don't think this applies to the Java client gens

**Comment by cbornet** [comment]
More precisely, I think the JaxRS Jackson should be configured like the Java client and the JsonValue/JsonCreator removed. Not the opposite...

**Comment by wing328** [comment]
👌 

Closing it as there's no update for a while.

**Pull request closed without merging**
