### PR TITLE
Resolve #3775 - Allow configuring User-Agent via maven plugin + update readme

### LINKED ISSUE #3775: [REQ] Allow configuring User-Agent in 'openapi-generator-maven-plugin'
Allow configuring User-Agent in 'openapi-generator-maven-plugin' to override default User-Agent.

Example of usage:
```
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <!-- RELEASE_VERSION -->
    <version>4.1.1</version>
    <!-- /RELEASE_VERSION -->
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <generatorName>java</generatorName>
                <configOptions>
                   <sourceFolder>src/gen/java/main</sourceFolder>
                </configOptions>
                <httpUserAgent>${project.artifactId}/${project.version}</httpUserAgent>
            </configuration>
        </execution>
    </executions>
</plugin>
```

### PR DESCRIPTION
**Pull request by MartinHatas**
Allow configuring User-Agent via maven plugin + update readme

Fixes #3775

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by MartinHatas** [comment]
Thank you. Done.

**Comment by jmini** [comment]
Thank you for your contribution!

**Comment by l3ender** [comment]
How is this feature used when generating clients using the CLI? Thank you!

**Pull request merged**
