### PR TITLE
Fix multi-part binary array form parameters for Spring Boot and Spring Cloud templates

### LINKED ISSUE #3139: [BUG] [Spring] Generated API interface treats multipart arrays as a single file
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generated API interface for multipart arrays contains a single MultipartFile instead of a list. Besides any MultipartFile argument should have @RequestPart annotation instead of @RequestParam.

##### openapi-generator version

Tested with 4.0.0 version of https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin

##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: MultipartFile test
paths:
  /multipart-array:
    post:
      tags:
        - multipart
      description: MultipartFile array test
      operationId: multipartArray
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '204':
          description: Successful operation
  /multipart-single:
    post:
      tags:
        - multipart
      description: Single MultipartFile test
      operationId: multipartSingle
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '204':
          description: Successful operation
```

##### Command line used for generation

Maven plugin was used:
```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>${openapi-generator-maven-plugin.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${basedir}/src/main/resources/multipart.yaml</inputSpec>
                <generatorName>spring</generatorName>
                <modelPackage>org.openapi.test.model</modelPackage>
                <apiPackage>org.openapi.test.api</apiPackage>
                <library>spring-cloud</library>
                <generateSupportingFiles>false</generateSupportingFiles>
                <generateApiTests>false</generateApiTests>
                <configOptions>
                    <interfaceOnly>true</interfaceOnly>
                    <dateLibrary>java8</dateLibrary>
                    <java8>true</java8>
                    <booleanGetterPrefix>is</booleanGetterPrefix>
                    <useBeanValidation>true</useBeanValidation>
                    <useTags>true</useTags>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

##### Steps to reproduce

Generate MultipartApi interface using the plugin configuration listed above. Both multipartArray and multipartSingle methods contains a single MultipartFile parameter with @RequestParam annotation.

##### Suggest a fix

Looks like the mustache template formParams.mustache ignores arrays.

### PR DESCRIPTION
**Pull request by rbrincke**
Multi-part binary array strings as outlined in #3139 resulted in `MultipartFile` rather than `List<MultipartFile>`. This PR attempts to resolve this by adjusting the templates for Spring Boot and Spring Cloud. Changes to these templates include:

- wrap contents in `List` where appropriate
- use defined `description` rather than a hard-coded one
- use defined `RequestPart` name rather than hard-coded one

Two tests have been added: one for `spring-boot` and one for `spring-cloud`.

Resolve #3139

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog  @lwlee2608

### CODE REVIEW

**Comment by rbrincke** [comment]
Please note that the runner logs a warning when using the defined `.yml` snippet ("Could not compute datatypeWithEnum from ...", `org.openapitools.codegen.DefaultCodeGen#4684`). From the history of commits it is unclear to me what is going on there, and the generated code seems to be fine. I am completely new to this code base, so it would be helpful if someone else could provide further explanation as to whether this is harmful, and if so, what needs to be fixed to make it go away.

**Comment by sun9999** [comment]
I think the related changes should also apply to the following file:
modules/openapi-generator/src/main/resources/JavaSpring/apiDelegate.mustache line 53.

**Comment by rbrincke** [comment]
I've run the code generator against the file locally to check, and you are right. I've fixed that one as well, and have added test coverage for it.

Because the `description` is now picked up, a lot of the samples have changed as a result of having run `bin/spring-all-petstore`. This makes the PR look much bigger than it actually is.

**Comment by wing328** [comment]
Merge conflicts resolved via https://github.com/OpenAPITools/openapi-generator/pull/4616/commits/69cb1ce22338b42ceca76cbb924cfdbbb7a66456. All tests passed.

**Pull request merged**
