### PR TITLE
Define content type only if the body is not empty

### PR DESCRIPTION
**Pull request by romanblack1**
Content type is now only defined if the body is not empty. It used to define empty bodies and the default "application/json." This satisfies the request OpenAPITools#8116. This change aims to change the python client only.

I ran the desired commands on Git Bash without errors, but I am still new to this so I might have missed a step somewhere, let me know if there is anything I missed.

### CODE REVIEW

**Comment by wing328** [comment]
Please update the samples via item3 in the PR checklist: https://github.com/OpenAPITools/openapi-generator/blob/master/.github/PULL_REQUEST_TEMPLATE.md so that the CI can test the change.

**Comment by romanblack1** [comment]
> Please update the samples via item3 in the PR checklist: https://github.com/OpenAPITools/openapi-generator/blob/master/.github/PULL_REQUEST_TEMPLATE.md so that the CI can test the change.

How do I make the results of the Git Bash visible to you? Are there files to change/commit to?

**Comment by wing328** [comment]
Yes please commit the changes in the sample as well.

**Comment by romanblack1** [comment]
I have updated the samples folder.

**Comment by wing328** [comment]
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)

**Pull request merged**
