### PR TITLE
[Kotlin][Multiplatform] Upgrade Kotlin to version 1.6.0

### PR DESCRIPTION
**Pull request by tkirshboim**
### PR Description

- The PR upgrades the Kotlin version used by the Kotlin Multiplatform template to version 1.6.0.
- Ktor is upgraded to version 1.6.4, the [the recommended version to use](https://kotlinlang.org/docs/releases.html#release-details) with Kotlin 1.6.0. 

Upgrading to 1.6.0 was [deliberately avoided](https://github.com/OpenAPITools/openapi-generator/pull/10900#discussion_r753263348) in #10900 because Jetpack Compose was not compatible with Kotlin 1.6.0. This issue is now resolved because Jetpack Compose can be used with Kotlin 1.6.0 when using [Compose compiler version 1.1.0-beta04](https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.1.0-beta04).  

This change was validated in KMM demo project that uses this branch to generate the petstore sample code and Jetpack Compose: https://github.com/Airthings/openapi-multiplatform-multi-module/commit/050f0862b6575ea34deb4e3ca2c4321527a587b2 

#### CCs
Kotlin technical committee:
@jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by 4brunu** [comment]
Hey, thanks for creating this PR.
Since the jetpack compose stable is still using kotlin 1.5.32, maybe we should wait a bit more to merge this PR?
What do you think?

**Comment by tkirshboim** [comment]
> Since the jetpack compose stable is still using kotlin 1.5.32, maybe we should wait a bit more to merge this PR? What do you think?

@4brunu That's a good point. I'm using the beta version, but I'm fine with waiting if you prefer.

**Comment by 4brunu** [comment]
The PR looks good to me, but I would prefer for that jetpack compose stable version to adopt 1.6.0, and then we could merge this PR.
Is it ok to you?

**Comment by 4brunu** [comment]
Nice, by the way, thanks for creating some PRs to the kotlin multiplatform generator 👍

**Pull request merged**
