### PR TITLE
[Gradle] Modernize Gradle plugin build configuration by moving to Gradle-7.4.2 and Kotlin DSL

### PR DESCRIPTION
**Pull request by saschpe**
The Gradle version currently in use is very (very) outdated and does not work with Java 12 or later, thus making it hard to contribute to the project. The OpenAPI Generator Gradle plugin already uses Kotlin code and interacts with Gradle's Kotlin DSL. Therefore, porting the project configuration itself to Gradle Kotlin DSL simplifies project configuration. It also provides better IntelliJ hinting and built-time type-safety.

### Breaking Changes

I took the liberty and got rid of the Sonatype Gradle plugin. Publishing to OSS SonaType can be done entirely with the bundled `maven-publish` Gradle. Continuous SNAPSHOT version publishing to any repository (`~/.m2/repository` or remote) is very much a Maven thing. Developers can `./gradlew publishToMavenLocal` directly when improving on the generator or it's Gradle plugin.

However, the *close* and *release* steps on SonaType are now manual tasks. Thus, a new release needs a person to do this final step. If this isn't an option, I could look into bringing back the old behavior as well.

### Other remarks

I kept the Kotlin code cleanup in the plugin itself separate from the build configuration changes and could submit another MR. Those changes could probably get merged faster. 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.0.1) (patch release), `6.1.x` (breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
> However, the close and release steps on SonaType are now manual tasks. Thus, a new release needs a person to do this final step.

I prefer not to do it manually. 

Can we automate it or bring back the old behaviour somehow?

Thanks.

**Comment by saschpe** [comment]
Sure, I'll look into it tomorrow.

**Comment by erichaagdev** [comment]
@saschpe did you ever look into bringing back the old behavior for close and release steps? If not and you don't plan to, would you mind if I take over this PR? I already branched from these changed and [started upgrades to Gradle 7.5.1](https://github.com/erichaagdev/openapi-generator/tree/gradle-modernize).

I see [io.github.gradle-nexus.publish-plugin](https://github.com/gradle-nexus/publish-plugin) which is meant as a replacement for [de.marcphilipp.nexus-publish](https://github.com/marcphilipp/nexus-publish-plugin) and [io.codearte.nexus-staging](https://github.com/Codearte/gradle-nexus-staging-plugin/) and is from the same authors.

@wing328 I also wonder why a Gradle plugin is being published to Sonatype rather than just the Gradle Plugin Portal? Do you know the answer?

In its current state this PR [will break releasing in Travis](https://github.com/OpenAPITools/openapi-generator/blob/d74c49b93d610f12b50ffcf7290bff39a5e0f67b/.travis.yml#L154) as `publishPluginMavenPublicationToNexusRepository` and `publishMavenJavaPublicationToNexusRepository` are still being referenced so this will have to be addressed.

I'd love to help out but I'm not familiar with publishing artifacts to Sonatype.

**Comment by saschpe** [comment]
Sure :-)

**Pull request closed without merging**
