### PR TITLE
Use JDK17 images in Dockerfile

### PR DESCRIPTION
**Pull request by wing328**
Use [amazoncorretto:17.0.8-alpine3.18](https://hub.docker.com/layers/library/amazoncorretto/17.0.8-alpine3.18/images/sha256-6e6f780411eae55e8dcb59391aa09dd778f0fa2c896f9c218961fdb7da52f485?context=explore) which has 0 vulnerabilities.

a follow-up PR to https://github.com/OpenAPITools/openapi-generator/pull/17007

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
Did a push to `latest` to ensure builds publishing to multiple platforms without issues: https://hub.docker.com/layers/openapitools/openapi-generator-cli/latest/images/sha256-5c24bd1a16120b65fab9f8ecf346fa8b073f71af407b794e270c9afab2a3e4bd?context=explore

**Comment by daveset** [comment]
@wing328 this switch to an Alpine-based image is failing to find bash:
```
 $ docker pull openapitools/openapi-generator-cli
Using default tag: latest
latest: Pulling from openapitools/openapi-generator-cli
96526aa774ef: Already exists 
40fc2491c1b6: Pull complete 
5343336bf20e: Pull complete 
9f8c878f941c: Pull complete 
Digest: sha256:2e2398f2ee5e95d57090254a5f00efa3302dbedbc4de3d355564a70cd63bc140
Status: Downloaded newer image for openapitools/openapi-generator-cli:latest
docker.io/openapitools/openapi-generator-cli:latest

$ docker run --rm openapitools/openapi-generator-cli:latest
env: can't execute 'bash': No such file or directory
```

It needs  `RUN apk add --no-cache bash` added to the Dockerfiles.

I'll add that if there are downstream projects that use `openapitools/openapi-generate-cli` as a base image in their own dockerfiles, this could be a breaking change since it was previously using a debian-based image (apt install vs. apk add).

**Comment by wing328** [comment]
thanks for pointing it out.

just reverted the change. i'll file another one and include a test to catch the issue moving forward.

**Comment by wing328** [comment]
@daveset I've filed https://github.com/OpenAPITools/openapi-generator/pull/17139 and add a test.

Please take a look when you've time. Thank you.

**Pull request merged**
