### PR TITLE
Add x-go-custom-tag to go-server generator

### PR DESCRIPTION
**Pull request by andrewkav**
### PR checklist

- [x ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (3.3.x), `4.0.x`. Default: `master`.
- [ x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

The PR adds possibility to include custom tags into generated models
as described in https://github.com/OpenAPITools/openapi-generator/issues/1145

@antihax  @bvwells  @grokify

### CODE REVIEW

**Comment by wing328** [comment]
@andrewkav as discussed, you may consider using the following to make the line a little bit shorter:
```
{{#vendorExtensions.x-go-custom-tag}} {{{.}}}{{/vendorExtensions.x-go-custom-tag}}
```

**Comment by andrewkav** [comment]
@wing328  I've updated the PR. Also added the same for `go` and `go-gin` generators to make it consistent.

**Comment by wing328** [comment]
@andrewkav thanks for the enhancement, which has been merged into master.

cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09)

**Comment by zhangbanger** [comment]
Question about this - how would one reference the `baseName` in the yaml definition itself? For purposes of using the property name, or say a camelized version, as part of the custom tag?

**Pull request merged**
