### PR TITLE
[PYTHON] Issue #2028 - additionalProperties support

### LINKED ISSUE #2028: [BUG] [PYTHON] additionalProperties not supported
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generated Python clients do not have the ability to access the additional properties of models with `additionalProperties` defined. The only ones that can be accessed are those that are explicitly defined in the model and the rest are ignored. In contrast, the generated Java models extend HashMap when `additionalProperties` are defined and they can get accessed by Map#get(String).

##### openapi-generator version

4.0.0

##### OpenAPI declaration file content or url

```yaml
  Element:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
      name:
        type: "string"
    additionalProperties:
      type: "object"
```
Full specification: https://github.com/Open-MBEE/mms/blob/develop/mms-ent/repo-amp/src/main/amp/web/mms/mms.swagger.yaml

##### Command line used for generation

```shell
java -jar /path/to/openapi-generator-cli.jar generate -i /path/to/mms.swagger.yaml -l python -o ~/tmp
```

##### Steps to reproduce

Inspecting the generated `Element.py` file after executing the command above with the specification above. There is also a usage of `additionalProperties` in the Petstore API that exhibits the same behavior.

##### Related issues/PRs

Clone of issue made and fixed in `swagger-api/swagger-codegen`: https://github.com/swagger-api/swagger-codegen/issues/8075

##### Suggest a fix

I believe that the additional properties can be stored in a dict, analogously to how they are handled in Java.

### PR DESCRIPTION
**Pull request by ivan-gomes**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fixes #2028. Adapted from accepted PR https://github.com/swagger-api/swagger-codegen/pull/8414. 

@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess

### CODE REVIEW

**Comment by wing328** [comment]
@ivan-gomes thanks for the PR but the Travis CI reports the following errors:
```
======================================================================
ERROR: Failure: NameError (name 'Animal' is not defined)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/.tox/py27/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/.tox/py27/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/test/test_mixed_properties_and_additional_properties_class.py", line 17, in <module>
    import petstore_api
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/petstore_api/__init__.py", line 20, in <module>
    from petstore_api.api.another_fake_api import AnotherFakeApi
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/petstore_api/api/__init__.py", line 6, in <module>
    from petstore_api.api.another_fake_api import AnotherFakeApi
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/petstore_api/api/another_fake_api.py", line 20, in <module>
    from petstore_api.api_client import ApiClient
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/petstore_api/api_client.py", line 26, in <module>
    import petstore_api.models
  File "/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python/petstore_api/models/__init__.py", line 24, in <module>
```

Full log: https://travis-ci.org/OpenAPITools/openapi-generator/builds/486718967

Would you please take a look?

Also please run `./bin/python-petstore-all.sh` to update the Python samples for asyncio and tornado

**Comment by spacether** [comment]
@ivan-gomes what's the status on this PR?
Do you still want to merge it?

The python-experimental generator now supports additional properties.
ample tests:
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python-experimental/test/test_additional_properties_object.py
- https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python-experimental/tests/test_deserialization.py#L380

**Comment by spacether** [comment]
@ivan-gomes thank you for this PR.
I am working on cleaning up old python PRs.
Do you still want to merge this?
If so, can you resolve the test failures?
If not, can you close it?

**Comment by ivan-gomes** [comment]
Closed in favor of https://github.com/OpenAPITools/openapi-generator/pull/2049.

**Pull request closed without merging**
