### PR TITLE
[TypeScript] typescript-axios: Added possibility to add custom axios instance.

### PR DESCRIPTION
**Pull request by sruehl**
This comes in handy if you want to use mocks in tests.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This PR adds the possibility to supply a custom axios instance to the typescript-axios clients.
This then can be used to supply a axios mock adapter in unit-tests: `const mock = new MockAdapter(axiosInstance, { delayResponse: 600 })`.
To test this feature a simple test-case has been added which just supplies the global axios instance.

*Updated remark (2018/10/22):* One thing we could do different is to supply the instance via configuration or constructor parameter so one doesn't need to supply the instance on every call.

cc: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09)

### CODE REVIEW

**Comment by wing328** [comment]
@nicokoenig does the enhancement look good to you?

**Comment by sruehl** [comment]
One thing we could do different is to supply the instance via configuration or constructor parameter so one doesn't need to supply the instance on every call.

**Comment by sruehl** [comment]
One thing we could do different is to supply the instance via configuration or constructor parameter so one doesn't need to supply the instance on every call.

**Comment by sruehl** [comment]
One thing we could do different is to supply the instance via configuration or constructor parameter so one doesn't need to supply the instance on every call.

**Comment by sruehl** [comment]
One thing we could do different is to supply the instance via configuration or constructor parameter so one doesn't need to supply the instance on every call.

**Comment by sruehl** [comment]
One thing we could do different is to supply the instance via configuration or constructor parameter so one doesn't need to supply the instance on every call.

**Comment by sruehl** [comment]
One thing we could do different is to supply the instance via configuration or constructor parameter so one doesn't need to supply the instance on every call.

**Comment by sruehl** [comment]
One thing we could do different is to supply the instance via configuration or constructor parameter so one doesn't need to supply the instance on every call.

**Comment by nicokoenig** [comment]
@sruehl @wing328 Looks good to me! 🔥

**Comment by nicokoenig** [comment]
@sruehl @wing328 Looks good to me! 🔥

**Comment by nicokoenig** [comment]
@sruehl @wing328 Looks good to me! 🔥

**Comment by nicokoenig** [comment]
@sruehl @wing328 Looks good to me! 🔥

**Comment by nicokoenig** [comment]
@wing328 @sruehl Look good to me 👍🔥

**Comment by nicokoenig** [comment]
@wing328 @sruehl looks good to me 👍🔥

**Comment by sruehl** [comment]
I just added a alignment to fetch regarding the custom instance but somehow my comment, my commit and everything else doesn't appear here? github bug? last commit should be: `typescript-axios: aligned to fetch API for custom instance` 07c5b30

**Comment by sruehl** [comment]
I just added a alignment to fetch regarding the custom instance but somehow my comment, my commit and everything else doesn't appear here? github bug? last commit should be: `typescript-axios: aligned to fetch API for custom instance` 07c5b30

**Comment by sruehl** [comment]
Ok time to clean up this PR a bit: https://blog.github.com/2018-10-21-october21-incident-report/ :)

**Comment by sruehl** [comment]
@nicokoenig could you recheck after my c7e4f7d commit? I updated the api according to the fetch example so its more consistent. Due to the github outage we had a race-condition.

**Comment by wing328** [comment]
@sruehl quick question if you don't mind. Is it correct to say that your change is backward-compatible (non-breaking change) as you just added an optional parameter to the API method signature?

**Comment by nicokoenig** [comment]
@sruehl I will give it a try when I am in the office tomorrow. 

@wing328 I will validate backward compatibility with our project, once I am in the office again.

👍

**Comment by sruehl** [comment]
@wing328 yep that's the idea (the supplied instance is optional).

**Comment by nicokoenig** [comment]
@sruehl @wing328 works like a charme! ✔️

**Comment by wing328** [comment]
@nicokoenig thanks for the review.

@sruehl thanks for the enhancement.

**Comment by wing328** [comment]
@sruehl thanks for the PR, which is included in the v3.3.2 release: https://twitter.com/oas_generator/status/1057649626101112832

**Pull request merged**
