### PR TITLE
fix: ensure models that have variables that contain a complexType of `time.Time` import the `time` module

### PR DESCRIPTION
**Pull request by madpah**
This PR includes a fix for issue #14403.

Generated models in Go were missing the import for the `time` module in some circumstances due to how the check for `DateTime` variables was being handled for Lists or Lists of Objects.

FYI @antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5

Prior to this change, the following OpenAPI schema generated incomplete and invalid Go code:

```
components:
  schemas:
    MyRequestDTO:
      properties:
        emailAndCommitDateMap:
          additionalProperties:
            items:
              format: date-time
              type: string
            type: array
          type: object
      type: object
    MyResponseDTO:
      properties:
        something:
          type: string
  securitySchemes:
    BasicAuth:
      scheme: basic
      type: http
info:
  title: Test Schema
  version: 1.0.0
openapi: 3.0.1
paths:
  /my-api:
    post:
      operationId: myOperation
      parameters:
      - in: query
        name: publicId
        schema:
          type: string
      - in: query
        name: repositoryUrl
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyRequestDTO'
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponseDTO'
          description: default response
      tags:
        - A Tag
security:
- BasicAuth: []
tags:
- name: A Tag
```

After this PR, valid code is generated and can be compiled by `go`.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by martin-mfg** [comment]
The bitrise build is failing because bitrise tries to merge your branch into the `8.0.x` branch of openapi-generator. See the line "- branch_dest: 8.0.x" near the top of the bitrise logs. I assume bitrise used `8.0.x` there because you had briefly set the target branch of this PR to `8.0.x`. You could try triggering a new bitrise build and see if it merges to the `master` branch this time. E.g. by pushing a new commit to this PR or by opening a new PR with your changes.

**Comment by madpah** [comment]
Thanks @martin-mfg - pushed a small whitespace change to re-trigger actions.

**Comment by wing328** [comment]
I wonder if you can add a test in modules/openapi-generator/src/test/resources/3_0/go/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml and regenerate the samples so that CI can verify the change?

**Comment by madpah** [comment]
@wing328 - test added and samples updated as requested.

**Comment by wing328** [comment]
CI failed: https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/27490/workflows/2daacdd9-6e9b-4d09-ac27-3ea4ba557966/jobs/87100

can you please take a look ?

**Comment by madpah** [comment]
Taking a look @wing328 - but this looks un-related to my change - however will dive into it.

**Comment by madpah** [comment]
Think it's resolved @wing328 if you can approve the other workflows please.

**Comment by wing328** [comment]
CC 
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

**Pull request merged**
