### PR TITLE
Add support for java.time.Instant for java generators

### PR DESCRIPTION
**Pull request by stijnkoopal**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran ./bin/spring-mvc-petstore-j8-instant.sh` 
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

We are using `java.time.Instant` as Date(Time) type for all our backend services. Currently we achieve this by using a custom `dateLibrary` and custom `typeMappings` and `importMappings`. This is suboptimal however.

`java.time.Instant` is a valid type for code generation if you are using UTC timestamps only. Hence, this PR.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by stijnkoopal** [comment]
Fair point, fixed!

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

**Comment by cbornet** [comment]
It's really easy to switch from an OffsetDateTime to an Instant. Do we really need an option for this ? Also note that Jackson will only accept "Z" format for Instant which doesn't comply with RFC3339

**Comment by stijnkoopal** [comment]
Well, we use Instant throughout our service-2-service APIs since most of your business logic, data storage, and data exchange should be in UTC. As you say, it is easy to use Instant by the following configuration:
```
configOptions = [
        dateLibrary: "custom",
        java8: true,
        jsr310: true
    ]
    typeMappings = [
        "DateTime": "Instant"
    ]
    importMappings = [
        Instant: "java.time.Instant"
    ]`
```

However then we need to have this in most of our services, hence I thought I would add it to the source.

**Comment by cbornet** [comment]
Have you tried using OffsetDateTime directly ? It represents a time in UTC timezone with a ZoneOffset and it's really easy to convert it to/from an Instant.
```java
OffsetDateTime dt = OffsetDateTime.now();
Instant instant = dt.toInstant();
dt = instant.atOffset(ZoneOffset.UTC);
```

**Comment by tomdevroomen** [comment]
I've seen the PR and I have to agree with @stijnkoopal having a config value for using java.time.Instant would be beneficial.
Wether OffsetDateTime and Instant conversion would be easy isn't the goal of this PR, it would add extra code to a codebase to do the conversion.
With this config option this wouldn't be needed.

**Comment by cbornet** [comment]
You can already use typeMappings and importMappings if you really want Instant. Have you tried it ?

**Comment by stijnkoopal** [comment]
Yeah, that was the thing we were trying to avoid. We'll choice the way of configuration.

**Pull request closed without merging**
