### PR TITLE
Issue 11401 - report correctly the parameters with the deep object specification

### PR DESCRIPTION
**Pull request by parvit**
Hi all,
this change addresses the issue mentioned in https://github.com/OpenAPITools/openapi-generator/issues/11401 and it should report correctly the parameters with the deep object specification.

Commits cherry-picked from previous branch to be based on current master

### CODE REVIEW

**Comment by parvit** [comment]
@wing328 Here's the update PR you requested.

**Comment by wing328** [comment]
can you please update the samples ?

https://github.com/OpenAPITools/openapi-generator/actions/runs/3391716534/jobs/5637208273

also I believe you've tested it locally, right? 

Can you post the test result as well?

**Comment by parvit** [comment]
I'll need to update the mustache files first as now they don't generate correct code anymore.

**Comment by wing328** [comment]
take your time. just let me know when it's ready. i'll review over the weekend or next week.

have a nice weekend.

**Comment by parvit** [comment]
Just a quick question:
image

Could you indicate how to make the "time" import generate in "model_one_of_primitive_types.go" ?

**Comment by wing328** [comment]
is it related to this change? https://github.com/OpenAPITools/openapi-generator/pull/13833/files#diff-a5fc9752c935154ba9de07c3a6cfae9e6a6fac95418980719164ea4026de7b69L653

**Comment by wing328** [comment]
again please make sure this PR is created from the latest master.

**Comment by parvit** [comment]
@wing328 master branch has the same issue, i've created a PR for that fix.

**Comment by parvit** [comment]
@wing328 Were you able to check the change?

**Comment by parvit** [comment]
ok but after i do it please give it priority for merging

Il Ven 18 Nov 2022, 17:47 William Cheng ***@***.***> ha
scritto:

**Comment by parvit** [comment]
@wing328 the update is done

**Comment by wing328** [comment]
I did a test and got the following in tcpdump:

> 10:05:53.342677 IP localhost.52060 > localhost.http: Flags [P.], seq 3718:4248, ack 6277, win 6281, options [nop,nop,TS val 3234621852 ecr 4289403119], length 530: HTTP: GET /v2/fake/deep_object_test?inputOptions[F1]=1&inputOptions[F2]=teststring&inputOptions[F3]=null&inputOptions[id]=1&inputOptions[name]=TestCat&test_pet[F1]=1&test_pet[F2]=teststring&test_pet[F3]=null&test_pet[id]=1&test_pet[name]=Test&test_pet[photoUrls]=http%3A%2F%2Flocalhost&test_pet[tags][F1]=1&test_pet[tags][F2]=teststring&test_pet[tags][F3]=null&test_pet[tags][id]=2&test_pet[tags][name]=tag1 HTTP/1.1

What are those F1, F2, F3 ?

Here is a test I added to pet_api_test.go

```go
// test deep object query parameter and verify via tcpdump
func TestDeepObjectQuery(t *testing.T) {

	newPet := (sw.Pet{Id: sw.PtrInt64(12830), Name: "gopher",
		PhotoUrls: []string{"http://1.com", "http://2.com"}, Status: sw.PtrString("pending"),
		Tags: []sw.Tag{{Id: sw.PtrInt64(1), Name: sw.PtrString("tag2")}}})
	newCategory := (sw.Category{Id: sw.PtrInt64(12830), Name: "cat"})
    configuration := sw.NewConfiguration()
    apiClient := sw.NewAPIClient(configuration)
    r, err := apiClient.FakeApi.TestQueryDeepObject(context.Background()).TestPet(newPet).InputOptions(newCategory).Execute()
	if err != nil {
        // for sure this will fail as the endpoint is fake
	}
	if r.StatusCode != 200 {
		t.Log(r)
	}
}
```

Can you please also include it in your PR so that we've a test ready for testing next time? 

Thanks again for the PR.

**Comment by parvit** [comment]
The names come fomr the data in the test i already made in fake_api_test.go
```go
func TestQueryDeepObject(t *testing.T) {
	req := client.FakeApi.TestQueryDeepObject(context.Background())

	var id = int64(1)
	var idTag1 = int64(2)
	var nameTag1 = "tag1"
	req = req.TestPet(sw.Pet{
		Id: &id,
		Name: "Test",
		PhotoUrls: []string{ "http://localhost" },
		Tags: []sw.Tag{
			{
				Id: &idTag1,
				Name: &nameTag1,
				AdditionalProperties: map[string]interface{}{
					"F1": 1,
					"F2": "teststring",
					"F3": nil,
				},
			},
		},
		AdditionalProperties: map[string]interface{}{
			"F1": 1,
			"F2": "teststring",
			"F3": nil,
		},
	})
	var idcat = int64(1)
	req = req.InputOptions(sw.Category{
		Id: &idcat,
		Name: "TestCat",
		AdditionalProperties: map[string]interface{}{
			"F1": 1,
			"F2": "teststring",
			"F3": nil,
		},
	})

	r, _ := req.Execute()

	var expectedDeepObjectURL = testScheme + "://" + testHost + deepObjectURL

	assert.Equal(t,
		expectedDeepObjectURL,
		r.Request.URL.String() )
}
```

Do you think your other test is also required to be included? Seems to be the same test

**Comment by wing328** [comment]
Thanks for the explanation 👍 . I can confirm in my end the result is good.

**Pull request merged**
