### PR TITLE
[python-nextgen] use Any as type for free form object

### PR DESCRIPTION
**Pull request by tomplus**
This PR changes type for "object" from Dict[str, Any] to Any which is more convenient for such loosely defined attributes.

Thanks.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11)  @arun-nalla (2019/11) @spacether (2019/11) @krjakbrjak (2023/02) @wing328

### CODE REVIEW

**Comment by spacether** [comment]
Why is Any more accurate than Dict[strip, Any]?

**Comment by tomplus** [comment]
If I define a model with _object_ properties without a detailed specification I'll get something like this:

```
my_atrr: Optional[Dict[str, Any]]
```

and now it's not possible to assign my object:

```
class MyClass:
    pass

obj = MyClass()

MyModel(my_attr=obj)

> pydantic.error_wrappers.ValidationError
>   is not a valid dict (type=type_error.dict)
```

**Comment by spacether** [comment]
What is the json schema definition for a with object properties without a detailed specification?

**Comment by tomplus** [comment]
For example: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml#L1928

**Comment by spacether** [comment]
You mean when a property or items schema has only the definition {type: object}?

**Comment by tomplus** [comment]
Yes, in such case.

**Comment by spacether** [comment]
Does your example work if MyClass inherits from pydantic BaseModel?

**Comment by tomplus** [comment]
Yes, it does.

**Comment by spacether** [comment]
So why not have your class use that base model? The context here is pydantic or python std lib json types so your inputs must use one of those two. A standard python class does not do that.

**Comment by tomplus** [comment]
I wasn't aware of this requirement - if type is "object", the object must inherit from BaseModel.
It causes problems when it's not my class but an external one.

**Comment by spacether** [comment]
Type object json schema means that the input must be a dict or subclass BaseModel which is pydantic's version of an object model. If you made it allow in Any, it would inaccurately describe that None or int should be allowed in. External object classes should subclass BaseModel, right @wing328?

**Pull request closed without merging**
