### PR TITLE
[Qt][C++] Updated cpp-qt5-client doc

### PR DESCRIPTION
**Pull request by basyskom-dege**
Added missing security feature support in the documentation

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Added missing security feature support for the cpp-qt5-generator.

PING @wing328  @etherealjoy

### CODE REVIEW

**Comment by basyskom-dege** [comment]
Will this change be overwritten in the future since i just changed it over the [Website](https://openapi-generator.tech/docs/generators/cpp-qt5-client)?

**Comment by wing328** [comment]
@basyskom-dege thanks for the PR. You will need to update https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppQt5ClientCodegen.java#L41-L45 instead. Let us know if you need any help.

**Comment by basyskom-dege** [comment]
changed on Java-level. Should be fine now.

**Comment by wing328** [comment]
FYI  @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

**Pull request merged**
