### PR TITLE
[kotlin-server][jaxrs-spec] default value examples

### PR DESCRIPTION
**Pull request by stephan-strate**
Provided some examples for #16455.

Its kinda weird, that the names of `@PathParam("")` disappear. Can't really tell why. But what you can see is, that for the enum and integer default values not `""` is added. For the enum it is not compilable, the integer compiles, but fails at runtime.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (7.0.1 - patch release), `7.1.x` (minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by stephan-strate** [comment]
@wing328 any idea how to fix that?

**Comment by wing328** [comment]
@stephan-strate if we put double quote on integer/numeric values, that should fix the problem right?

`@DefaultValue(3)` =>`@DefaultValue("3")`

**Comment by stephan-strate** [comment]
> @stephan-strate if we put double quote on integer/numeric values, that should fix the problem right?
> 
> `@DefaultValue(3)` =>`@DefaultValue("3")`

Yes, as far as I understand all values need to be strings

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/16563 to fix the issue. Please take a look when you've time.

**Comment by stephan-strate** [comment]
Fixed by #16563

**Pull request closed without merging**
