### PR TITLE
Spring codegen - fix equals and hashCode methods for byte array and binary

### LINKED ISSUE #1448: [spring] equals and hashCode for models with array type []
##### Description

equals() and hashCode() are not generated correctly for generatorName _spring_ and library _spring-boot_.
It uses Objects.equals() to compare primitive arrays.

The same model generated with generatorName _java_ and library _resttemplate_ uses Arrays.equals(), which ist correct.

##### openapi-generator version

3.3.2

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.0
info:
  version: "1"
  title: "Test Api"

servers:
  - url: "localhost:8282"

paths:

  /test:
    post:
      operationId: "doTest"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'

      responses:
        200:
          description: "Ok"
        400:
          description: "Bad Request"
        500:
          description: "Internal Server Error"


components:
  schemas:

    Test:
      type: object
      required:
        - name
        - stream
      properties:
        name:
          type: string
        stream:
          description: "byte array with binary data"
          type: string
          format: byte
```

##### Command line used for generation

Used pom.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.test</groupId>
    <artifactId>my-test</artifactId>
    <version>1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>4.3.10.RELEASE</version>
        </dependency>

        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
            <version>5.2.5.FINAL</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.9.4</version>
        </dependency>

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.21</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.7</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <!-- Swagger config START -->
            <plugin>
                <!-- fuer das Generieren aus dem swagger....yaml file-->
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>3.3.2</version>
                <dependencies>
                    <dependency>
                        <groupId>org.openapitools</groupId>
                        <artifactId>openapi-generator-maven-plugin</artifactId>
                        <version>3.3.2</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>buildSwagger</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>src/main/resources/swagger.yaml</inputSpec>

                            <generatorName>spring</generatorName>
                            <library>spring-boot</library>

                            <generateApis>true</generateApis>
                            <generateApiTests>false</generateApiTests>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModels>true</generateModels>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateSupportingFiles>true</generateSupportingFiles>

                            <environmentVariables>
                                <supportingFiles>
                                    ApiClient.java,ApiException.java,ApiOriginFilter.java,ApiResponseMessage.java,HomeController.java,NotFoundException.java,SwaggerDocumentationConfig.java,RFC3339DateFormat.java,OAuth.java,ApiKeyAuth.java,HttpBasicAuth.java,Authentication.java
                                </supportingFiles>
                            </environmentVariables>

                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <useBeanValidation>true</useBeanValidation>
                                <performBeanValidation>true</performBeanValidation>
                                <modelPackage>com.test.model</modelPackage>
                                <apiPackage>com.test.api</apiPackage>
                                <sourceFolder>/src/main/java</sourceFolder>
                                <implFolder>/src/main/java</implFolder>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

##### Steps to reproduce

Create project with given pom file and put swagger.yaml to src/main/resources

### PR DESCRIPTION
**Pull request by ccoltx**
Fixes #1448

Binary and Byte Arrays
* should be compared using Arrays.equals(...)
* their hash code generated using Arrays.hashCode(...)

Spring codegen has been updated and the Tests updated.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](x) beforehand.

- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

### CODE REVIEW

**Comment by ccoltx** [comment]
This pull request is ready to be reviewed, can someone please take a look?

**Comment by ccoltx** [comment]
Can one of the maintainers  please have a look at this! 
@bbdouglas @sreeshas @jfiala  @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

**Comment by ccoltx** [comment]
Any update?

**Review by Zomzog — APPROVED** [review]
LGTM

**Pull request merged**
