### PR TITLE
Define content type if and only if the body is not empty

### PR DESCRIPTION
**Pull request by romanblack1**
Addresses the same issue (#8116) as the PR (#9766), but in the ruby client.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
cc @cliffano (2017/07) @zlx (2017/09) @autopp (2019/02)

**Comment by wing328** [comment]
Travis CI failed with the following errors:
```
Bundled gems are installed into `./vendor/bundle`

An error occurred while loading spec_helper.
Failure/Error: require 'petstore/api/another_fake_api'

SyntaxError:
  /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/ruby-faraday/lib/petstore/api/another_fake_api.rb:89: syntax error, unexpected end-of-input, expecting keyword_end
# ./lib/petstore.rb:66:in `require'
# ./lib/petstore.rb:66:in `<top (required)>'
# ./spec/spec_helper.rb:14:in `require'
# ./spec/spec_helper.rb:14:in `<top (required)>'
No examples found.


Finished in 0.00003 seconds (files took 0.23442 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (bundle-test) on project RubyPetstoreFaradayClientTests: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (bundle-test) on project RubyPetstoreFaradayClientTests: Command execution failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
```

Can you please take a look?

Ref: https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds/232524856

**Comment by romanblack1** [comment]
We believe we have fixed the bug that causes the error you've mentioned, but it looks like the build is still failing due to some unrelated reason. Can you take a look?

**Comment by wing328** [comment]
Looks like we need to update the tests as well. I'll do it after merging this PR. 
```
Failures:
  1) Petstore::ApiClient#select_header_content_type works
     Failure/Error: expect(api_client.select_header_content_type(nil)).to eq('application/json')
       expected: "application/json"
            got: nil
       (compared using ==)
     # ./spec/api_client_spec.rb:162:in `block (3 levels) in <top (required)>'
Finished in 1.04 seconds (files took 0.26268 seconds to load)
258 examples, 1 failure, 3 pending
Failed examples:
rspec ./spec/api_client_spec.rb:161 # Petstore::ApiClient#select_header_content_type works
```


Thanks again for the enhancement.

**Pull request merged**
