### PR TITLE
revert swagger-parser upgrade

### PR DESCRIPTION
**Pull request by ctreatma**
This addresses #17554 by downgrading `swagger-parser` to the version that was used in the 7.1.0 release of `openapi-generator`.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ctreatma** [comment]
@wing328 I think it would be good to get a test in place using the sample schema @ttrubinov shared in https://github.com/swagger-api/swagger-parser/issues/2037 so that we can proactively catch this when the parser is upgraded in the future.  What's the best place to put a test like that?  I've only added language-specific tests so far, but this isn't a language-specific issue.

**Comment by wing328** [comment]
shall we try upgrading to 2.1.20 which was released 4 days ago to see if the issue persists?

**Comment by ctreatma** [comment]
> shall we try upgrading to 2.1.20 which was released 4 days ago to see if the issue persists?

As I understand it, the swagger-parser folks didn't start looking into this bug until after 2.1.20 was cut; setting that aside, though, it would still be helpful to have tests somewhere in this repo to protect against this bug, and those tests would tell us if 2.1.20 or a later version of swagger parser has fixed the issue.  Is there a good place to put a test that isn't really specific to a particular language?  Or is the best approach to just add a test for this bug in the go client generator tests?

**Comment by wing328** [comment]
Ok. make senses.

> Or is the best approach to just add a test for this bug in the go client generator tests?

please add a test in the go client generator: modules/openapi-generator/src/test/java/org/openapitools/codegen/go/GoClientCodegenTest.java

please also merge the latest master into your branch as i've fixed the docker test failure in the latest master

**Comment by wing328** [comment]
PR merged. please add a test later when you've time. thank you 🙏

**Pull request merged**
