### PR TITLE
[cpp-restbed-server] make the restbed SERVER generator more extensible

### PR DESCRIPTION
**Pull request by f18m**
RestBed server code is currently unusable. This MR makes it more extensible by giving the users a chance to setup shared pointers to the restbed::Resource and customize them before they get published into RestBed.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by f18m** [comment]
Hi @wing328 ,
that's not a problem for me (the fact the commits are not linked to my github account I mean).. is fixing this aspect something required to have the PR accepted ? :)

**Comment by f18m** [comment]
Hi @wing328 ,
I have fixed the problem by validating the email address used in the commits I did originally... now github recognizes them as belonging to my account!

**Comment by wing328** [comment]
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

cc @stkrwork as well (the author of the c++ restbed generator)

**Comment by f18m** [comment]
> cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @MartinDelille (2018/03) @muttleyxd (2019/08)
> 
> cc @stkrwork as well (the author of the c++ restbed generator)

ping :)

I would like to develop other patches for this c++ restbed generator as I started using it in a few of my projects but I'd really like to understand first if there is interest in these patches or not :)

**Comment by wing328** [comment]
If no more feedback on this PR, I'll merge it on coming Wed.

**Review by muttleyxd — APPROVED** [review]

**Comment by muttleyxd** [comment]
Sorry for late review, but I've been a bit busy recently. Changes look fine for me, definitely a big improvement :+1:

**Comment by wing328** [comment]
@muttleyxd no need to apologize. We're all busy :) . Appreciate your review.

**Pull request merged**
