### PR TITLE
[Kotlin] Fix parse error when using custom field names with @Json

### PR DESCRIPTION
**Pull request by keijumt**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
To parse a model using custom fields, KotlinJsonAdapterFactory needs to be added to moshi's Adapter. 
- Fix parse error when using custom field names with @Json
- Fix to use isEmpty method for string length verification

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by ackintosh** [comment]
I just reran the CI job. > Shippable TIMEOUT

**Comment by karismann** [comment]
should fix #2961

**Comment by keijumt** [comment]
@karismann 
#2961 is solved by adding KotlinJsonAdapterFactory to adapter of Moshi.
I think that there is no problem because I added KotlinJsonAdapterFactory after adding CustomTypeAdapter, What do you think of it?

**Comment by karismann** [comment]
> 
> 
> @karismann
> #2961 is solved by adding KotlinJsonAdapterFactory to adapter of Moshi.
> I think that there is no problem because I added KotlinJsonAdapterFactory after adding CustomTypeAdapter, What do you think of it?

i think your change is ok and fix #2961 , that's what i would mean

**Comment by keijumt** [comment]
@karismann 
I understand, Thanks.

**Comment by wing328** [comment]
@keijumt thanks again for your contribution, which has been included in the v4.0.1 release (https://twitter.com/oas_generator/status/1135534738658062336)

**Pull request merged**
