### PR TITLE
[ruby] Support aliasing of API keys

### PR DESCRIPTION
**Pull request by zippolyte**
Adds support for API key aliasing as it's done in Go, Java and python:

- #4940
- #4966
- #6469

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by zippolyte** [comment]
cc @cliffano (2017/07) @zlx (2017/09) @autopp (2019/02)

**Comment by zippolyte** [comment]
cc @wing328 @jimschubert, this is very similar to the other PRs you reviewed, please have a look 🙂 🙇

**Comment by wing328** [comment]
Restarted the failed CI job. Let's see how that goes.

**Comment by wing328** [comment]
Travis CI tests passed via https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/752969100

**Comment by zippolyte** [comment]
Thanks for the merge 🙇 !

**Pull request merged**
