### PR TITLE
[dart-dio][client] Allow passing progress callbacks through client methods.

### PR DESCRIPTION
**Pull request by adg-mh**
Dio supports using callbacks to report send/recv progress. This PR adds the ability to pass those callbacks as parameters to api method.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @nickmeinhold (2019/09) @athornz (2019/12) @amondnet (2019/12)

### CODE REVIEW

**Comment by wing328** [comment]
@adg-mh Am I understanding correctly that this PR introduces breaking changes as the method signature has been changed?

(perfectly fine to have breaking changes and we apply proper labels to this PR indicating this PR includes breaking changes without fallbacks)

**Comment by athornz** [comment]
@wing328 

The new arguments in the api methods are optional, so it shouldn't be a breaking change.

**Comment by wing328** [comment]
@athornz 👌 thanks for the explanation.

**Comment by wing328** [comment]
I'll merge the PR on Friday if no one has further feedback on this PR.

**Pull request merged**
