### PR TITLE
[Swift] Minor improvements to swift 5 generator

### PR DESCRIPTION
**Pull request by wing328**
cc @4brunu 

- rename to Swift5ClientCodegen to conform to other generators' naming
- mark the generator as beta
- minor code format change
- update samples

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by 4brunu** [comment]
Can you please install or upgrade SwiftLint and generate the samples again?
`brew install swiftlint && brew upgrade swiftlint`

**Comment by 4brunu** [comment]
Should the section [overview](https://github.com/OpenAPITools/openapi-generator/blob/master/README.md#overview) on the readme also be updated?

**Comment by wing328** [comment]
Already installed swiftlint:
```
$ swiftlint help
Available commands:

   analyze         [Experimental] Run analysis rules
   autocorrect     Automatically correct warnings and errors
   generate-docs   Generates markdown documentation for all rules
   help            Display general or command-specific help
   lint            Print lint warnings and errors (default command)
   rules           Display the list of rules and their identifiers
   version         Display the current version of SwiftLint
```

**Comment by wing328** [comment]
> Should the section overview on the readme also be updated?

Done via dbf07331a7

**Comment by 4brunu** [comment]
That's weird, because it's not formatting the code. 
Could you check which version do you have installed?
The last one is 0.38.0

**Comment by wing328** [comment]
Updated swiftlint and samples via https://github.com/OpenAPITools/openapi-generator/pull/4910/commits/4e903a8383e923c1c12b118878e0d5ba7462de94

**Comment by 4brunu** [comment]
Thanks 👍 For me this is ready to merge

**Comment by vegemanis** [comment]
@wing328 could you tell me why this is marked as Beta? Considering using this, but nervous about the beta status 🙂

**Comment by wing328** [comment]
@vegemanis for new generators, we usually mark it as "beta" to start with and we'll consider upgrade it to "stable" when the generator stabilizes.

**Comment by vegemanis** [comment]
any existing concerns then or is this just procedural? Is there a list of requests for swift 5 that you're working off of?

**Comment by 4brunu** [comment]
Just procedural, and to give to community an opportunity to review it and improve it if necessary.
But I'm using it in production without issues.

**Comment by vegemanis** [comment]
Thanks @4brunu! Very helpful.

**Comment by Exey** [comment]
4.3.0 still have warning in Model.swift at line 48

> Cast from 'Dictionary<AnyHashable, Any>.Element' (aka '(key: AnyHashable, value: Any)') to unrelated type '(String, String)' always fails

Please fix it

**Pull request merged**
