### PR TITLE
[dart][dio][built_value] Fix missing serializer factory builders for …

### PR DESCRIPTION
**Pull request by kuhnroyal**
…additionalProperties

Refactor the addition of custom serializer factories.
Should fix https://github.com/OpenAPITools/openapi-generator/issues/6951
Should fix https://github.com/OpenAPITools/openapi-generator/issues/10465

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

CC @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

### CODE REVIEW

**Comment by ahmednfwela** [comment]
does dart-dio-next also have this?

**Comment by kuhnroyal** [comment]
> does dart-dio-next also have this?

It is only in dart-dio-next.

**Comment by ahmednfwela** [comment]
oh I was wondering why I wasn't reproducing this and I forgot I fixed it in my version

https://github.com/Bdaya-Dev/openapi-generator/blob/bdaya_master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioNextClientCodegen.java#L527

and apparently https://github.com/OpenAPITools/openapi-generator/issues/10189 is still not solved ?

**Review by josh-burton — APPROVED** [review]

**Comment by kuhnroyal** [comment]
@ahmednfwela We already have the handling for response and parameter types, I just improved it to handle nullability.
This PR mainly adds it for schemas using `additionalProperties`.

**Comment by kuhnroyal** [comment]
@jaumard This probably also fixes https://github.com/OpenAPITools/openapi-generator/issues/10465, can you check that please.

**Comment by ahmednfwela** [comment]
but why is `additionalProperties` relevant here ? should `type` and `items.type` and be enough ?
is there a case where `additionalProperties` can contain additional type info ?

**Comment by kuhnroyal** [comment]
See https://github.com/OpenAPITools/openapi-generator/issues/6951#issuecomment-871403754
This results in a `BuildList<BuildMap<String, JsonObject?>>` and there is no builder factory for the map generated atm., only for the list. `additionalProperties` can lead to nested containers and that is where `built_value` fails to generate the serializer builders.

This can also be a `BuildList<BuildMap<String, int?>>` for example.

**Comment by ahmednfwela** [comment]
yes, but why check for `additionalProperties` instead of items ?

**Comment by kuhnroyal** [comment]
Well for normal properties this is automatically generated.

**Comment by ahmednfwela** [comment]
I see now what you mean, but this is not recursive, so it won't solve `BuildList<BuildList<BuildMap<String, JsonObject?>>>` for example, right ?

**Comment by kuhnroyal** [comment]
Correct

**Pull request merged**
