### PR TITLE
[PHP] Fix deserialize ApiException as a Model

### LINKED ISSUE #756: [PHP] Bug deserialize default responses as a Model
##### Description

I'm generating clients that make use of `default` responses for other HTTP codes (implying an error). It's defined as a Model (code, message) in `definitions` in the swagger file.

```yaml
...
  responses:
    '200':
      description: pet response
      schema:
        type: array
        items:
          $ref: '#/definitions/Pet'
    default:
      description: error payload
      schema:
        $ref: '#/definitions/ErrorModel'
...
```

After generating the client API with openapi-generator, when catching an `ApiException`, the deserialized response object `ApiException::responseObject` is empty (it is an an instance of `ErrorModel` as expected, but with no content).

##### openapi-generator version

2.3.0

##### OpenAPI declaration file content or url

[gist: minimal swagger.json example](https://gist.github.com/ymilin/74a804dc5130dfda2c2c6ed349f22865)

##### Command line used for generation

```
java -jar bin/openapi-generator-cli.jar generate -i swagger.json \
  -l php \
  -o build/ \
  --git-user-id "vendor" \
  --git-repo-id "ws-clients" \
  -DpackagePath=.,srcBasePath=lib,variableNamingConvention=camelCase,invokerPackage="MyCie\\Service",apiTests=false,apiDocs=false,modelTests=false,modelDocs=false
```

##### Steps to reproduce

With the generated client: 
- try to make a request for a non-existing pet
- Expect `$e->getResponseObject()` to be a fully hydrated instance of ErrorModel
- Got an empty instance of ErrorModel instead

```php
$petApi = new PetApi();

try {
  $pet = $api->getPetById(123);
  ...
} catch (ApiException $e) {
  $errorModel = $e->getResponseObject();
  print_r($errorModel); // empty ErrorModel
}
```

##### Suggest a fix/enhancement

I checked the generated code and the bug seem to be located in the `catch` part of the `{{operationId}}WithHttpInfo` methods:

```php
try {
    ...
} catch (ApiException $e) {
    switch ($e->getCode()) {
        case 200:
            $data = ObjectSerializer::deserialize(
                $e->getResponseBody(),
                '\MyCie\Service\Model\Pet',
                $e->getResponseHeaders()
            );
            $e->setResponseObject($data);
            break;
        default:
            $data = ObjectSerializer::deserialize(
                $e->getResponseBody(), // <-- works with json_decode($e->getResponseBody())
                '\MyCie\Service\Model\ErrorModel',
                $e->getResponseHeaders()
            );
            $e->setResponseObject($data);
            break;
    }
    throw $e;
}
```

We can see that there is a specific test for this in the `try` part of same function in the `api.mustache` file, line 184

https://github.com/swagger-api/swagger-codegen/blob/616f8c17cfb7c44a3ccf7b6d55fb26ec6280213f/modules/swagger-codegen/src/main/resources/php/api.mustache#L184-188

So a possible fix would be doing something similar when deserializing for `ApiException` objects.

### PR DESCRIPTION
**Pull request by ymilin**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

When defining `default` responses (`ApiException`) as a Schema Object in Swagger declaration files, the current implementation cannot `deserialize` the Model properly into `ApiException::$responseObject`.

Added a check for `$returnType` and `json_decode` appropriately (same logic as the try part of same function for success responses)

fix #756

### CODE REVIEW

**Comment by ymilin** [comment]
@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko

**Comment by ymilin** [comment]
Please note that this is a port of a PR from [swagger-codegen#7968](https://github.com/swagger-api/swagger-codegen/pull/7968)

This PR takes account of previous code reviews and takes another approach:
- Move `json_decode` statements from api methods to the `ObjectSerializer::deserialize` method as it knows the data type and is already handling each cases separately.
- Add tests to not `json_decode` on recursive calls of `ObjectSerializer::deserialize`

I successfully tested this PR against multiple response types (`Model`, `Model[]`, `map[string, int[]]`, `array[int]`, `bool`, ...) with correct deserialisation of ApiException as a model.

**Comment by ackintosh** [comment]
I've added [a fix for the "petstore-security-test" sample](https://github.com/OpenAPITools/openapi-generator/pull/757/commits/1a94badc24733ad491bc422eaabd16f69ff7fc57).
(It is a fault from https://github.com/OpenAPITools/openapi-generator/pull/681 , sorry 💦 )

**Comment by ackintosh** [comment]
https://app.shippable.com/github/OpenAPITools/openapi-generator/runs/2088/1/console
>  There are uncommitted changes in working tree after execution of 'bin/ensure-up-to-date'
>  Perform git diff
>  diff --git a/samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php b/samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
>  index 340735ea2..ff500e699 100644
>  --- a/samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
>  +++ b/samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/AnotherFakeApi.php
>  @@ -154,9 +154,6 @@ class AnotherFakeApi
>                           $content = $responseBody; //stream goes to serializer
>                       } else {
>                           $content = $responseBody->getContents();
>.-                        if ('\OpenAPI\Client\Model\Client' !== 'string') {
>.-                            $content = json_decode($content);
>.-                        }
>                      }

@ymilin Could you run [/bin/openapi3/php-petstore.sh](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/openapi3/php-petstore.sh)?

**Comment by ymilin** [comment]
@ackintosh Thanks, just added a new commit.

**Pull request merged**
