### PR TITLE
Fix logic of `getNullableType` of csharp server and client.

### PR DESCRIPTION
**Pull request by frankyjuang**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

[nullable is default to false](https://github.com/frankyjuang/openapi-generator/pull/new/fix-default-nullable). Also fix non-nullable guid type and tests.

Related to https://github.com/OpenAPITools/openapi-generator/issues/2269, https://github.com/OpenAPITools/openapi-generator/pull/2528, https://github.com/OpenAPITools/openapi-generator/pull/2529

@wing328 
@jimschubert 
@mandrean

### CODE REVIEW

**Comment by wing328** [comment]
Appveyor (C#) tests failed. Please review the test result here: https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/26423049

**Comment by frankyjuang** [comment]
@wing328 tests fixed! thansk

**Comment by wing328** [comment]
@frankyjuang thanks for the PR, which has been included in the 4.1.0 release: https://twitter.com/oas_generator/status/1160000504455319553

**Comment by wing328** [comment]
## Upgrade Note

To make a property nullable in OpenAPI/Swagger spec 2.0, please use `x-nullable: true`

**Pull request merged**
