### PR TITLE
Add additional reserved words for java and csharp

### PR DESCRIPTION
**Pull request by jwenger100**
### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc 

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

@mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)

### CODE REVIEW

**Comment by wing328** [comment]
@jwenger100 Thanks for the PR. Can you please run `./bin/utils/export_docs_generators.sh` to update the doc?

**Comment by wing328** [comment]
FYI. Recently, we've added new options to allow users map property, parameter, model name: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#name-mapping

I hope you will find these new features useful in your use cases.

**Comment by wing328** [comment]
FYI @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

**Comment by wing328** [comment]
FYI. documentation updated via https://github.com/OpenAPITools/openapi-generator/commit/6a8039c672284ef7ebce5527663b15059b6b1ece

**Comment by martin-mfg** [comment]
Hi @wing328 and others, I think a good long-term solution would be to add some code that adds every entry from `instantiationTypes`, `typeMapping` and `languageSpecificPrimitives` to `reservedWords`. What do you think?

If you agree, I would create a PR to implement this. Should I target only the Java-based generators then and let maintainers of other generators judge the idea and implement it in their generators themselves? Or should I directly implement it on a higher level so that it applies automatically to all generators?

**Comment by wing328** [comment]
thanks for the suggestion. let me think about it and get back to you after the v7.0.0 release.

**Comment by wing328** [comment]
@jwenger100 what do you mean by `API names`? Do you mean method name (based on operationId)?

**Comment by wing328** [comment]
@martin-mfg please go ahead to submit a PR assuming it doesn't need a lot of work.

(I'm not against the idea at all. With the mapping option, users can fallback to whatever they want if needed)

**Pull request merged**
