### PR TITLE
Use Liberapay for donation fix #238

### LINKED ISSUE #238: Migrate/mirror to Gitlab
Since Microsoft is buying Github, it might be the time to think about a migration (or at least a mirror) to https://about.gitlab.com/

I use the community edition at work and it is awesome! (continuous integration in particular).

Any thought about this?

- [x] Mirror to Gitlab
- [ ] Automate Gitlab mirroring
- [ ] Set-up Gitlab CI

### PR DESCRIPTION
**Pull request by MartinDelille**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Simple link to the Liberapay team account for OpenAPITools.

@wing328 Could you could ping the other founding members? I don't have the list yet.

### CODE REVIEW

**Comment by MartinDelille** [comment]
@wing328 Any update on this? The team is created. People interested by receiving donation by this service can be added to it! Feel free to ask if you want more details.

**Comment by wing328** [comment]
@MartinDelille let's have a quick chat on this via IM.

**Comment by MartinDelille** [comment]
Blocked by https://github.com/OAI/OpenAPI-Style-Guide/issues/14

**Comment by jimschubert** [comment]
With the introduction of GitHub's "Sponsor" link, I think this can be closed out.

**Pull request closed without merging**
