### PR TITLE
feat: Support useSingleRequestParameter feature for java microprofile…

### LINKED ISSUE #17071: [REQ] Wrap method parameters into object for Java-Microprofile rest client generation
### Is your feature request related to a problem? Please describe.

I have endpoints which has multiple mandatory and non mandatory parameters and it's always difficult to pass all the params while calling the method. I see `useSingleRequestParameter` feature is implemented already for some java client code generation like jersey2, jersey3 etc but it's not implemented for microprofile client generation.

## Describe the solution you'd like

We could make use of `useSingleRequestParameter` feature and wrap all the @XXXParams into @BeanParam and call the operations in a simple manner. Like,
`List<PetStore> listPetStores(@HeaderParam String apiKey, @HeaderParam String sessionId, @PathParam String param1, @QueryParam param2, String requestBody);` this could be transformed to `List<PetStore> listPetStores(@BeanParam ListPetStoreRequest listPetStoreRequest, String requestBody);`

It's complex to pass header params all the time, instead this could be done at one place like a `ClientRequestFilter`.

Now if this method is changed as,

1. `List<PetStore> listPetStores(@BeanParam ListPetStoreRequest listPetStoreRequest, String requestBody);`
2. `
public class ListPetStoreRequest {
private @HeaderParam String apiKey;
private @HeaderParam String sessionId;
private @PathParam String param1;
private @QueryParam String param2;
}
`
3. `ListPetStoreRequest request = ListPetStoreRequest.newInstance().param1("test1").param2("test2");`
4. Method call will be simplified as, `listPetStores(request, body);`

## Describe alternatives you've considered

One alternative is to override the api mustache template and provide a custom implementation, as and when needed.
But this template has to maintained and shared to every service which wants to use it.

### PR DESCRIPTION
**Pull request by vickymicky**
Fixes #17071 

This PR adds support for useSingleRequestParameter feature in the Microprofile library for the Java client.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by vickymicky** [comment]
Requesting java technical committee @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @martin-mfg to review and share feedback

**Comment by wing328** [comment]
the CI test failed: https://github.com/OpenAPITools/openapi-generator/actions/runs/6893847530/job/18808178939?pr=17072

can you please take a look when you've time?

**Comment by vickymicky** [comment]
@wing328 Thanks for the review, I figured what is the issue. I will fix it soon.

**Comment by vickymicky** [comment]
@wing328 , I have made the necessary changes, Could you please check again ?

**Comment by wing328** [comment]
CI failure: https://github.com/OpenAPITools/openapi-generator/actions/runs/6919170451/job/18823252969?pr=17072

please take a look when you've time (you may need to manually purge the test folder in the new sample folder)

please also merge the latest master into your branch and regenerate the samples.

**Comment by vickymicky** [comment]
@wing328 I took the latest code and ran the generation again. Could you please check again now ?

**Comment by vickymicky** [comment]
@wing328 , I had some issue with respect to author name in the commit message, I have fixed it. And I will take the latest code once the changes are good.

**Comment by wing328** [comment]
@vickymicky thanks for the PR, which has been merged.

**Comment by vickymicky** [comment]
Thanks for the review and support @wing328

**Pull request merged**
