### PR TITLE
[cpprestsdk] Add localVar prefix to parameterized functions variables in cpprestsd…

### PR DESCRIPTION
**Pull request by Jauler**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Proposed solution for #660 rename local variables to have prefix localVar in api-source.mustache.
Petstore api source files has hanged so I am adding them into the same commit.

@ravinikam @stkrwork @fvarose @etherealjoy @martindelille

### CODE REVIEW

**Comment by etherealjoy** [comment]
@stkrwork 
Do you have comments? If not we can go ahead and merge.

**Comment by stkrwork** [comment]
why the localVar word? why not something like __ instead?

**Comment by wing328** [comment]
`localVar` (or `local_var_`) => it's a prefix we use in other languages as well, e.g. C#, Java, Ruby, Python, etc

**Comment by wing328** [comment]
@Jauler thanks for the enhancement, which is included in the v3.2.2 stable release: https://twitter.com/oas_generator/status/1032252335131512832

**Pull request merged**
