### PR TITLE
fix for operation defination containing ref schema

### PR DESCRIPTION
**Pull request by ngp-star**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

fix for the issue https://github.com/OpenAPITools/openapi-generator/issues/6484
PR is against the master branch.

### CODE REVIEW

**Comment by ngp-star** [comment]
@wing328 
is there any updates on this PR?

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by ngp-star** [comment]
@wing328 
yeah sure can you please guide on this? so that my commit will be linked to my git hub account.

**Comment by ngp-star** [comment]
@wing328 
I have modified the email address for this particular commit by following the link Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account . what you shared.

previously my email was :

Author: ngp-star <ngp@ngp-a01.vmware.com>

now it's changed to Author: ngp-star <ngp@vmware.com>

now it should be fine I think, can you please confirm?

**Comment by ngp-star** [comment]
@wing328 
are there any updates on this?

**Comment by ngp-star** [comment]
@wing328 
is there any update on this PR?

**Comment by wing328** [comment]
@ngp-star thanks for the PR, which has been merged into master.

**Comment by ngp-star** [comment]
> @ngp-star thanks for the PR, which has been merged into master.

@wing328 
you are welcome

**Comment by ngp-star** [comment]
@wing328 
is it possible to see my name in contributors link what you shared?.https://github.com/OpenAPITools/openapi-generator/graphs/contributors

**Pull request merged**
