### PR TITLE
[rust-server] Implement stack for Context

### PR DESCRIPTION
**Pull request by bjgill**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. @frol @farcaller 

### Description of the PR

This PR adds a `SwaggerService` trait that makes it much easier to compose multiple middlewares. This single common trait means that middlewares need less boilerplate. This change has been prompted by our experiences with an internal authentication middleware.

This PR also renames `auth::Server` to `context::AddContext`, to make the purpose clearer. Given that this is a breaking change (albeit a pretty trivial rename, as the example integration shows), I don't know if I should be filing this against `master` or `3.2.x`...

See https://github.com/Metaswitch/swagger-rs/pull/36 for the associated `swagger-rs` changes.

Thanks to @jngorman, the original contributor of this commit.

### CODE REVIEW

**Comment by jmini** [comment]
Changed base branch: `3.2.0-SNAPSHOT` is now on `master` branch

**Comment by wing328** [comment]
@bjgill when you've time, I wonder if you can resolve the merge conflicts and then I'll merge it into master (3.2.0)

**Comment by bjgill** [comment]
Thanks. Now rebased and awaiting CI.

**Comment by bjgill** [comment]
CI all passed. Happy to get merged when you're ready.

**Pull request merged**
