### PR TITLE
Export models package when using withSeparateModelsAndApi flag

### PR DESCRIPTION
**Pull request by calvinwyoung**
This is a minor tweak to the `typescript-axios` generator that makes sure the `models` package gets exported when the `withSeparateModelsAndApi` flag is set to `true`.

This resolves issue #6423 

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### CODE REVIEW

**Comment by calvinwyoung** [comment]
@macjohnny This PR only affects the generated output when the `withSeparateModelsAndApi` flag is `true`. It looks like the `typescript-axios` samples were generated with `withSeparateModelsAndApi` set to `false`, which means this PR wouldn't have any impact on the output. How would you prefer we handle this?

**Comment by macjohnny** [comment]
Ok, then there is no need to re-generate.
Somehow the CI still fails. Could you please merge the most recent master?

**Comment by calvinwyoung** [comment]
I just merged from the most recent master, but the CI is still failing for some reason. Unfortunately it looks like a few of the other recent PRs are also failing. What's the best way forward?

**Comment by macjohnny** [comment]
can you merge the most recent master again?

**Comment by calvinwyoung** [comment]
Done, although unfortunately it looks like there's still some sort of checksum error with Yarn.

**Comment by macjohnny** [comment]
@calvinwyoung please re-generate the samples, ,as a newline is added

**Comment by calvinwyoung** [comment]
@macjohnny Ah yes you're right, I do see now that there's a sample that covers this case. I just updated all of the `typescript-axios` samples and pushed again. It looks like there were a bunch of updates unrelated to this PR, but I guess it'd be good to get everything updated anyway.

**Comment by wing328** [comment]
Samples updated via https://github.com/OpenAPITools/openapi-generator/pull/6873/commits/91653fe47eb3f8c07cef95f6f9df203175379fe7. All tests passed.

**Pull request merged**
