### PR TITLE
[C][Client] Support SSL client authentication for the c client

### PR DESCRIPTION
**Pull request by ityuhui**
The PR https://github.com/OpenAPITools/openapi-generator/pull/5140 has supported SSL server authentication, now this PR will support SSL client authentication.

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@wing328 @zhemant @michelealbano

### CODE REVIEW

**Comment by michelealbano** [comment]
You were faster than me! I was preparing a similar PR, but I was still studying how to support self-signed certificates.

I saw you set up properties CURLOPT_SSLCERT, CURLOPT_SSLKEY and CURLOPT_CAINFO. I like it, but maybe there are other properties that are important?
- CURLOPT_KEYPASSWD: this is the one I care more about
- CURLOPT_SSLKEYTYPE, CURLOPT_SSLENGINE and CURLOPT_SSLCERTTYPE: anyway, the defaults are already reasonable
- CURLOPT_CAPATH: I still have to verify if it can be used to self-signed certificate. Does it work that way?

**Comment by ityuhui** [comment]
1. If user sets a password for the private key. CURLOPT_KEYPASSWD is required. But I do not use this in my case. You can submit the PR after this PR.

2. The default value of CURLOPT_SSLKEYTYPE, CURLOPT_SSLENGINE and CURLOPT_SSLCERTTYPE are OK. We can provide the options in future.

3. Yes.  CURLOPT_CAPATH can work. I use this feature. And if sslConfig_t->insecureSkipTlsVerify is set to 1,  CURLOPT_CAPATH  will not take effect.

**Comment by michelealbano** [comment]
1. Ok, I will provide a patch for CURLOPT_KEYPASSWD.

2. I think we don't need to do that. It is normal that, if a developer has a very niche use case, he will do his own code customization.

3. Good to know. I look forward to play with self-signed certificates using your code.

Bottom line: the PR is ready to be merged.

**Comment by ityuhui** [comment]
Hi @wing328 

This PR is ready to merge.

**Pull request merged**
