### PR TITLE
Add Go echo server codegen

### PR DESCRIPTION
**Pull request by ph4r5h4d**
This is the first draft for go-echo-server codegen for OpenAPI-codegen. the purpose is that we are internally using Go Echo, and we needed to create this codegen. Still, I thought that it might be worth sharing it with everyone.  
Related issue: https://github.com/OpenAPITools/openapi-generator/issues/9093

I'm not a Java guru, and I mostly used go-gin-codegen codes to build this new codegen, and it's a bit opinionated.

Kindly let me know what needs to be done so we can merge this PR.

@antihax  @grokify  @kemokemo  @jirikuncar 
Kindly let me know what needs to be improved.

### CODE REVIEW

**Comment by kemokemo** [comment]
@ph4r5h4d
Thank you so much for your PR! 😄  It looks nice.
I'm very happy about this PR because I also used [echo](https://github.com/labstack/echo) for my company's internal web service and like it.  
I like [echo](https://github.com/labstack/echo) as well as [gin](https://github.com/gin-gonic/gin).

I have confirmed that the generated `go-echo-server`'s code builds, runs, and works as a container.
It looks good, but there are a few things I would like to discuss. Can you please see the following?

## `golint ./...` reports some issues

I feel that it would be better to add comments for methods exported in the package, so that issues reported by the golint tool can be resolved. What do you think?

## docker run

This may be a problem only in my macOS environment. I had to add the `-p` flag when running the docker container.  
How about in your environment?

- (I can not access to this app) `docker run --rm -it openapi`
- (I can access to this app) `docker run --rm -p 8080:8080 -it openapi`

**Comment by ph4r5h4d** [comment]
I'll take a look into the items you've mentioned and will issue an update by the end of the week.
Thank you for putting time into testing this PR.

**Comment by ph4r5h4d** [comment]
Can you kindly check again and see if everything is fine?

**Comment by wing328** [comment]
Overall it looks good to start with 👍 

I'll merge this and file another PR with minor enhancements.

Thanks for the new generator!

**Pull request merged**
