### PR TITLE
Aspnetcore Generator - New pocoModels parameter for POCO models

### PR DESCRIPTION
**Pull request by knom**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

FYI: @mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti 

Added a new parameter for the C# ASPNETCORE generators.
So that you generate POCO Models -- aka. models that don't include IEquatable methods and the operators.
This is highly appreciated by some DEVs, who like to use slim POCO classes - and not have the extra methods and operators there.

### CODE REVIEW

**Comment by knom** [comment]
I've modified the author according to the links - and repushed.

@wing328 is this better now?

**Comment by wing328** [comment]
Looks good.

**Comment by wing328** [comment]
Will try to run some tests and get it merged by this weekend.

**Comment by wing328** [comment]
Tested locally and the result is good.

I've merged https://github.com/OpenAPITools/openapi-generator/pull/12900 to add some tests in the CI (Github workflow)

**Pull request merged**
