### PR TITLE
feat(r): Added handling exception with ApiException class and better documentation

### PR DESCRIPTION
**Pull request by Ramanth**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
1. Enhanced the exception handling with ApiException class and using the "rlang" package 
2. Added the roxygen tags to generate the documentation and added a script to generate the ".Rd" files using the comments into the "man" folder in the package directory.
3. Added comments for better understanding to the deserialize method raised in the previous PR

@wing328  please review the changes.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by Ramanth** [comment]
@wing328 please hold reviewing this one as im having few more changes to make this non-breaking change

**Comment by Ramanth** [comment]
@wing328  this PR is ready now . Please review the changes and merge if good. Thanks.

**Comment by wing328** [comment]
@Ramanth thanks for the PR. Testing via https://travis-ci.org/namsor/namsor-r-sdk2/builds/552799310. Let's see how it goes.

**Comment by Ramanth** [comment]
@wing328 Is this good to merge?

**Comment by wing328** [comment]
Yup, did another check and no more question from me :)

**Pull request merged**
