### PR TITLE
Update Spring example with jakarta validation dependency

### PR DESCRIPTION
**Pull request by Philzen**
Spring Boot 2.2 switched many `javax.*`-packages to jakarta, as per 

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#jakarta-ee-dependencies

Changing the example POM to align with this change to avoid introducing two conflicting versions of the same namespace into a project.

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by Philzen** [comment]
BTW – i realized https://github.com/OpenAPITools/openapi-generator/blob/v7.0.1/modules/openapi-generator-maven-plugin/examples/java-client.xml uses a newer version for swagger-annotations, namely 1.6.3 – while the spring example still uses 1.5.8.

1. Should this be harmonized as well?
2. What about 1.6.11 – which seems the [most recent one from the 1.x branch](https://mvnrepository.com/artifact/io.swagger/swagger-annotations) – has that been tested for compatibility?

**Comment by Philzen** [comment]
Could not test the springfox-swagger update as – so far – our projects don't need them, however from reading their documentation the 3.x version seems to be the way to go and is compatible with the Spring Boot Version in the examples: https://github.com/springfox/springfox#migrating-from-existing-2x-version

**Comment by wing328** [comment]
I've merged https://github.com/OpenAPITools/openapi-generator/pull/16720. Do you still need this?

happy to reopen this PR if needed

**Comment by Philzen** [comment]
@wing328 Thanks! #16720 clarified a lot for me b/c i was already wondering whether 

```xml
         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
```

wouldn't be the better choice here – as it will transitively handle exactly the `jakarta.` vs. `javax.` confusion.

**Pull request closed without merging**
