### PR TITLE
[typescript-rxjs] add rxjs 7 support

### PR DESCRIPTION
**Pull request by denyo**
This PR adds support for rxjs 7 (https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md) which introduces some breaking interface changes but brings both better minification and improved performance.

Also type imports are refactored to type-only imports.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### CODE REVIEW

**Comment by macjohnny** [comment]
@denyo thanks for your contribution. would there be a possibility to support RxJS 7 in a backwards compatible way? maybe introduce an option or version flag, similar to https://github.com/OpenAPITools/openapi-generator/blob/c4b98041391a0a94e1d668addac0e6de6bf2a25b/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L121?

**Comment by macjohnny** [comment]
@denyo ping

**Comment by denyo** [comment]
@macjohnny I won't get the chance to make it backwards compatible.
Therefore I would suggest to change the target branch to the next major version.

**Comment by macjohnny** [comment]
@wing328 what is your opinion here? should we break the existing rxjs generator, or should we create a new rxjs7 generator?

**Comment by TiFu** [comment]
Quick question: Why does this PR affect 4,359 files? Looks like some unrelated commits have been included.

**Comment by macjohnny** [comment]
@TiFu I guess this is because of the changed target branch

**Comment by trumbitta** [comment]
@macjohnny would it possible to release this as is and let people stuck with rxjs 6 (rxjs 8 is coming) just point to an old version of the generator by themselves?

**Comment by Polm1** [comment]
Following 👀

**Comment by macjohnny** [comment]
According to https://github.com/OpenAPITools/openapi-generator#11---compatibility, we can have breaking changes only for a major release.
If an option is introduced, we can also habe it for the current minor or patch release

**Comment by macjohnny** [comment]
@denyo can you rebase onto the 6.0 branch to avoid the unrelated changes?

**Comment by jopelle1** [comment]
I opened a new PR fixing this one https://github.com/OpenAPITools/openapi-generator/pull/11364 : 
- Rebased on 6.0x
- Implemented option to switch to rxjs 7

**Comment by denyo** [comment]
@macjohnny done.

For everyone else waiting, this is the docker image built from this branch: [denyo/openapi-generator-cli:6.0.0-test](https://hub.docker.com/repository/docker/denyo/openapi-generator-cli/general)

**Comment by macjohnny** [comment]
I would suggest to close this PR in favor of https://github.com/OpenAPITools/openapi-generator/pull/11364, which we could have in 5.4, and thus avoid merge conflicts in the future.
Any objections?

**Comment by denyo** [comment]
> I would suggest to close this PR in favor of #11364, which we could have in 5.4, and thus avoid merge conflicts in the future. Any objections?

The only concern I have is that complexity will increase in the generator with every new version of rxjs, especially within templates, e.g. by adding a toggle or extending the flag for every version and at the same time users need to update their flags/toggles, too. 

From a user's perspective I would expect to get the latest version by default and have an opt-in for older versions if I really wanna be backwards compatible. At least this is what I am used to.

However the philosophy of this project might be different.

**Comment by macjohnny** [comment]
@denyo we can remove the rxjs<7 support for the 6.0 release, which is an easy thing to do an removes the complexity in the template

**Comment by macjohnny** [comment]
since the next release will be 6.0.0, lets merge this PR

**Pull request merged**
