### PR TITLE
Fix StrictSpec param name for maven

### LINKED ISSUE #3070: [BUG][JAVA] Maven Plugin `CodeGenMojo.strictSpecBehavior` does not match parameter name 'strictSpec'
##### Description

The maven plugin does not work for version 4.0.* because the `strictSpecBehavior` field does not match it's parameter name `strictSpec`. It seems maven ignores the name specified in the annotation and just uses reflection to look for a field that has the same name as the parameter.

```
[ERROR] Failed to execute goal org.openapitools:openapi-generator-maven-plugin:4.0.1:generate (default) on project test-client: Unable to parse configuration of mojo org.openapitools:openapi-generator-maven-plugin:4.0.1:generate for parameter strictSpec: Cannot find 'strictSpec' in class org.openapitools.codegen.plugin.CodeGenMojo -> [Help 1]
```

##### openapi-generator version

4.0.*

##### OpenAPI declaration file content or url
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java#L248

```java
/**
 * To treat a document strictly against the spec.
 */
@Parameter(name = "strictSpec", property = "openapi.generator.maven.plugin.strictSpec", required = false)
private Boolean strictSpecBehavior;
```

##### Steps to reproduce

Try to generate a client with the maven plugin above version 4.0.*.

```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>4.0.1</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <generatorName>java</generatorName>
                <configOptions>
                   <sourceFolder>src/gen/java/main</sourceFolder>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

##### Suggest a fix

Simply fix the field name.

```java
/**
 * To treat a document strictly against the spec.
 */
@Parameter(name = "strictSpec", property = "openapi.generator.maven.plugin.strictSpec", required = false)
private Boolean strictSpec;
```

### PR DESCRIPTION
**Pull request by Zomzog**
Must fix #3070

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

@wing328
@jimschubert
@cbornet
@ackintosh
@jmini

### CODE REVIEW

**Comment by wing328** [comment]
@Zomzog thanks for the PR but I think we should normalize the name to `strictSpecBehavior` instead?

Ref: https://github.com/OpenAPITools/openapi-generator/search?q=strictSpecBehavior&unscoped_q=strictSpecBehavior

**Comment by Zomzog** [comment]
Ok, I will do that, but it will be a breaking change for the maven plugin.

**Comment by wing328** [comment]
Please hold on ....

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/3071 may have fixed it

**Comment by Zomzog** [comment]
Ok, I close this one.

**Pull request closed without merging**
