### PR TITLE
Setup GitHub Codespaces

### PR DESCRIPTION
**Pull request by snebjorn**
This adds support for [GitHub Codespaces](https://docs.github.com/en/codespaces). It's pretty much a GitHub flavored Gitpod.

image

@wing328
@jimschubert
@cbornet
@jmini
@etherealjoy
@spacether

### CODE REVIEW

**Comment by snebjorn** [comment]
I got it working with a headless chromium so now it can also run JS/TS tests 🚀 

I also setup a running petstore. But it doesn't seem that anything is using it so I've commented it out again. Should someone need it they can just activate it again.

**Comment by wing328** [comment]
cc @joschi  as well who added Gitpod support to this repo previously

@joschi have you tried Github Codespaces? which one do you prefer?

**Comment by snebjorn** [comment]
Gitpod is probably looking into `devcontianer.json` support
- https://github.com/gitpod-io/gitpod/issues/7721

Then users can spin up containers where ever they please :)

**Comment by joschi** [comment]
> @joschi have you tried Github Codespaces? which one do you prefer?

I have played around with GitHub codespaces a little bit. In the end it's similar (almost identical) to what Gitpod is offering.

What I like better in Gitpod is that it also works with local IDEs, i. e. VSCode Desktop or any IDE based on IntelliJ IDEA: https://www.gitpod.io/docs/references/ides-and-editors/intellij


> cc @joschi as well who added Gitpod support to this repo previously

@wing328 I think you still have to add the [Gitpod.io GitHub App](https://github.com/apps/gitpod-io/) to this repository for the [prebuilds](https://www.gitpod.io/docs/configure/projects/prebuilds) to work, like I did with [openapi-diff](https://github.com/OpenAPITools/openapi-diff#readme). 😉

Original PR: https://github.com/OpenAPITools/openapi-generator/pull/12508

**Comment by snebjorn** [comment]
> What I like better in Gitpod is that it also works with local IDEs, i. e. VSCode Desktop or any IDE based on IntelliJ IDEA: https://www.gitpod.io/docs/references/ides-and-editors/intellij

Github Codespaces support local IDEs.
I'm currently using the setup from this PR to develop my recent PRs in VSCode on my local machine.

**Pull request merged**
