### PR TITLE
Specify source encoding in java/kotlin sample poms templates

### PR DESCRIPTION
**Pull request by cghislai**
Add the `<project.build.sourceEncoding>` property in some templates, so that the sample tests can be run independently of the host default file encoding.

This is an attempt to fix the circlesci builds that fail when generating the samples. See https://app.circleci.com/jobs/github/OpenAPITools/openapi-generator/29795?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link for a recent example: 
```
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/spring-mvc-j8-async/src/main/java/org/openapitools/api/FakeApi.java:308: error: unmappable character for encoding ANSI_X3.4-1968
[ERROR] * Fake endpoint for testing various parameters  ?????????  ???????????????????????????  ?????? ?????? ?????????
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-8-openjdk-amd64/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/spring-mvc-j8-async/target/site/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :spring-mvc-server-j8-async
```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by cghislai** [comment]
@lwlee2608 @yutaka0m can you have a look? thanks!

**Comment by cghislai** [comment]
@jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) can someone check this out? thanks!

**Comment by wing328** [comment]
@cghislai can you please resolve the merge conflicts? then please PM me via Slack and I'll merge accordingly. Thanks.

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/12088

**Comment by cghislai** [comment]
@wing328 thanks missed this.

**Pull request closed without merging**
