### PR TITLE
Erlang Server – cowboy return types improvements

### PR DESCRIPTION
**Pull request by NelsonVides**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
Not sure if mentioning, as they unfortunately haven't been fully active 🥲  However, tagging @wing328, as you helped me out with https://github.com/OpenAPITools/openapi-generator/pull/19465 🙂 

---

I've been using this generator further in more complex code, submitting some fixes I've been discovering over my previous overhaul.

### CODE REVIEW

**Comment by NelsonVides** [comment]
@wing328, if the previous tech committee would agree, maybe I could candidate myself to be a part of it? I don't know how it works and what I'd need to do, but I've essentially become the maintainer of the full rewrite 😄

**Comment by wing328** [comment]
yes please add yourself to the Erlang technical committee in the project's readme

**Comment by NelsonVides** [comment]
Added, thank you :)

**Comment by wing328** [comment]
when you've time this week or next, can you please PM me via Slack?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Pull request merged**
