### PR TITLE
[Slim] Distinction between basicBasic and basicBearer authentication

### PR DESCRIPTION
**Pull request by chawax**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

I changed the `SlimRouter.mustache` template to distinguish between basic and bearer authentications. Then I change the regex depending on that.

### CODE REVIEW

**Comment by wing328** [comment]
@chawax thanks for the PR. I'd a quick look and the PR looks good to me

cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

**Comment by wing328** [comment]
Please run `./bin/php-slim-server-petstore.sh` to update the Petstore samples.

**Comment by ybelenko** [comment]
@chawax Thanks for the contributing! I'm working on new Slim4 generator which is based on current Slim3. I'll transfer this changes into new generator too.

**Comment by chawax** [comment]
> Please run `./bin/php-slim-server-petstore.sh` to update the Petstore samples.

Mmh ... Do I have to install Maven to run this ? Is there another way to do this ? Don't want to "polluate" my Mac ...

**Comment by wing328** [comment]
You can use maven wrapper, e.g. ./mvnw clean package

**Comment by chawax** [comment]
> You can use maven wrapper, e.g. ./mvnw clean package

OK, thanks ! I just updated the samples.

**Comment by wing328** [comment]
@chawax thanks for the PR, which has been merged into master.

For your upcoming PRs, I would recommend creating a separate branch for the change.

**Comment by wing328** [comment]
@chawax thanks for the PR, which has been included in the v4.1.1 release: https://twitter.com/oas_generator/status/1165944867391860737

**Pull request merged**
