### PR TITLE
[BUG] [CPP-UE4] Fix unique items list codegen

### LINKED ISSUE #12742: [BUG][CPP-UE4] Missing support for arrays with unique items
##### Description

At the moment UE4-CPP generator creates invalid output for arrays with unique items (i.e. 'sets'). Instead of making them TSet (or TArray), it generates type 'Set' with `#include "Set.h"` (this code does not compile).

##### openapi-generator version

master / 6.0.1

##### OpenAPI declaration file content

```yaml
type: array
items:
  type: integer
uniqueItems: true
```

##### Command line used for generation

`openapi-generator generate -i openapi.yml -g cpp-ue4 -o result`

##### Steps to reproduce

Run generation for UE4 with OpenAPI specification containing array with unique items (see schema and command line above).

##### Related issues/PRs

There are some of similar issues for other languages/generators, but it not so helpful.

##### Suggest a fix/enhancement

We need to add `TSet` type mapping for 'set' value type. 
https://github.com/OpenAPITools/openapi-generator/blob/4d947a1c4579a73c7350ea55153d33ef76ba5d89/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppUE4ClientCodegen.java#L182

### PR DESCRIPTION
**Pull request by madrazzl3**
Added support for unique items lists for UE4 code generator.

@wing328 @Kahncode

Testcase for testing: https://gist.github.com/madrazzl3/e9333e9404ac48467bac142388b0b05d

Fix #12742

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.0.1) (patch release), `6.1.x` (breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by madrazzl3** [comment]
Generated code

Before:

```cpp
#include "Set.h" 
// there is no 'Set.h' both in UE4 stdlib and C++ stdlib

...

TOptional<Set> SetExample;
```

After:

```cpp
TOptional<TSet<FString>> SetExample;
```

**Comment by wing328** [comment]
@madrazzl3 are you ok with this PR?

If yes, we can merge it so that it will be included in the v6.0.1, which will be released soon.

**Comment by madrazzl3** [comment]
> @madrazzl3 are you ok with this PR?
> 
> If yes, we can merge it so that it will be included in the v6.0.1, which will be released soon.

Yes, it's all good. Let's ship it.

**Comment by wing328** [comment]
Sorry I mean to ask/tag @Kahncode

**Comment by Kahncode** [comment]
This looks good, thanks for the PR!

**Pull request merged**
