### PR TITLE
[REQ] Java Microprofile REST Client Template

### PR DESCRIPTION
**Pull request by turkeylurkey**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This pull request is an update of #3787. It provides implementation for feature request #2272 .

cc
@wing328 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by turkeylurkey** [comment]
Thanks for the tip, @wing328 . I updated the commit.

**Comment by wing328** [comment]
```
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java:	        if (codegenModel.imports.contains("ApiModel")) {
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java:	            // Remove io.swagger.annotations.ApiModel import
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java:	            codegenModel.imports.remove("ApiModel");
modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java:	        }
Java files contain tab '\t'. Please remove it and try again.
```

Please use 4-space instead of tabs.

**Comment by turkeylurkey** [comment]
@wing328 , Java files contain tabs is fixed. Should I check in the generated files flagged in circleci?

**Comment by wing328** [comment]
No worry. I'll take care of the update.

**Comment by wing328** [comment]
Tested locally and the result is good.

**Comment by wing328** [comment]
@turkeylurkey may I know if you've a Twitter account? We'll tag you in a tweet to promote the new feature.

**Comment by turkeylurkey** [comment]
No, I don't have a Twitter account, thanks for thinking of it.

**Comment by turkeylurkey** [comment]
@wing328 you could tag the Twitter account @OpenLibertyIO and/or the tag #MicroProfile.

**Comment by yeekangc** [comment]
@turkeylurkey is contributing on behalf of https://github.com/OpenLiberty/ for the Eclipse MicroProfile and Open API communities.  If you wouldn't mind tagging us i.e. @OpenLibertyIO and @MicroProfileIO in your tweet, @wing328, that will be great.

Thank you.

**Comment by ind1go** [comment]
I see there seems to be an option of `disableMultipart` in the mustache files, is there a way I can control that to get rid of the (unused) CXF imports?

**Comment by stefanorg** [comment]
hi @ind1go, have you found a solution to get rid of the cxf imports?

**Comment by ind1go** [comment]
> hi @ind1go, have you found a solution to get rid of the cxf imports?

@stefanorg I have! This is the required incantation (using the Maven `openapi-generator-maven-plugin`).

```xml
<configuration>
    <additionalProperties>
        <additionalProperty>disableMultipart=true</additionalProperty>
    </additionalProperties>
</configuration>```

**Comment by stefanorg** [comment]
ok, thanks.

--
Stefano Corallo



Il giorno mar 26 mag 2020 alle ore 11:11 Ben Cox <notifications@github.com>
ha scritto:

**Pull request merged**
