### PR TITLE
Add postProcessFile, implement in Go generators to run gofmt

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- Add postProcessFile to process each file generated by OpenAPI Generator
- Implement `postProcessFile` in Go generators to run `gofmt -w` on each Go file
- move `ensure-up-to-date` check to CircleCI

cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07)

cc @OpenAPITools/generator-core-team

### CODE REVIEW

**Comment by wing328** [comment]
@jimschubert the change simply adds a new function and users won't be affected. (there's no change to the existing method signatures)

**Comment by wing328** [comment]
@jimschubert Given that next release is 3.3.0, we can do that.

**Comment by jimschubert** [comment]
@wing328 when you add a new method, doesn't that break users who have written custom generators? Or will the JVM automatically pick up the new changes in the interface and DefaultCodegen,  allowing those custom generators to continue working?

**Comment by wing328** [comment]
@jimschubert right, in the worst case, it will break the usage depending on how the user customizes the project.

Now it's targetting 3.3.0 (current master)

**Comment by jmini** [comment]
Travis error is not related to this change, it was fixed with dd35acdb92486a96c214dd7e1bcef51e02f93809

**Pull request merged**
