### PR TITLE
[Rust] [Server] New generator bases on Axum

### PR DESCRIPTION
**Pull request by linxGnu**
This PR adds new Rust server generator which bases on [Axum 0.7](https://crates.io/crates/axum). Majority of code logic bases on `rust-server` generator with following changes:
- Generating `Axum` router instead
- AnyOf/OneOf is supported partially using `serde_json::value::RawValue`. User are free to deserialize the payload into sub-schema type on demand.
  - Noted: `discriminator` is not supported at the moment
- `multipart/form-data` is delegated. User can process [Multipart](https://docs.rs/axum/latest/axum/extract/struct.Multipart.html) efficiently by their own backend
  - Some use-cases:
     - ETL on-the-fly
     - Streaming upload to S3 (instead of writing the file to disk using TempFile / reading the whole file into memory)
- By default, `response serialization` will not block runtime executor (using `tokio::task::spawn_blocking`), e.g. return (huge) time-series data in json
- By default, `request validation` will not block runtime executor, e.g. validate big request body using regex
- Having options to let user:
   - Disable request validator
   - Allow blocking call of `request validation`
   - Allow blocking call of `response serialization`
- `XML` wireformat is not supported
- `Auth*` is not supported

Integration tested:
- multipart-v3
- openapi-v3
- ops-v3
- petstore
- petstore-with-fake-endpoints-models-for-testing
- ping-bearer-auth-v3

Kindly cc Rust committee @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10) to review. Thank you.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
can you please update `.github/workflows/samples-rust.yaml` as well with the new sample folder so that the CI can test it moving forward?

**Comment by linxGnu** [comment]
Hi @wing328 I addressed your comment. PTAL

**Comment by wing328** [comment]
cc 
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10)

**Comment by wing328** [comment]
LGTM. Let's give it a try.

**Pull request merged**
