### PR TITLE
[Swift 5] Fix missing `parentVars` in Swift 5 generator

### PR DESCRIPTION
**Pull request by pallzoltan**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request - @4brunu

### CODE REVIEW

**Comment by pallzoltan** [comment]
Not sure why Shippable and circleci don't pass, I've used `master` as base. Any ideas?

**Comment by 4brunu** [comment]
@pallzoltan can you please close and reopen this PR to restart the CI jobs to see if now it passes?

**Comment by wing328** [comment]
Restarted both. Let's see how that goes.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by 4brunu** [comment]
This PR seems not to break anything, but it's too specific, and I don't know very well this part so it's hard for me to review it.
Does it looks good to you @wing328?

**Comment by pallzoltan** [comment]
Thanks @wing328, added my personal email address as author.

**Comment by wing328** [comment]
@pallzoltan can you please share a spec (minimal) to reproduce the issue?

**Comment by pallzoltan** [comment]
It's in the linked bug report: https://github.com/OpenAPITools/openapi-generator/issues/9243

**Comment by wing328** [comment]
Right. Sorry that I missed it. Will use it to test the fix.

**Comment by wing328** [comment]
I did some tests using the spec you provided and noticed the following difference:

```diff
--- a/OpenAPIClient/Classes/OpenAPIs/Models/ClassC.swift
+++ b/OpenAPIClient/Classes/OpenAPIs/Models/ClassC.swift
@@ -10,12 +10,18 @@ import AnyCodable
 
 public struct ClassC: Codable, Hashable {
 
+    public var propertyA: String?
+    public var propertyB: String?
     public var propertyC: String?
 
-    public init(propertyC: String? = nil) {
+    public init(propertyA: String? = nil, propertyB: String? = nil, propertyC: String? = nil) {
+        self.propertyA = propertyA
+        self.propertyB = propertyB
         self.propertyC = propertyC
     }
     public enum CodingKeys: String, CodingKey, CaseIterable {
+        case propertyA
+        case propertyB
         case propertyC
     }
 
@@ -23,6 +29,8 @@ public struct ClassC: Codable, Hashable {
 
     public func encode(to encoder: Encoder) throws {
         var container = encoder.container(keyedBy: CodingKeys.self)
+        try container.encodeIfPresent(propertyA, forKey: .propertyA)
+        try container.encodeIfPresent(propertyB, forKey: .propertyB)
         try container.encodeIfPresent(propertyC, forKey: .propertyC)
     }

```

According to the spec (which is still 2.0 btw), is Class A supposed to be the parent of Class B, which should be the parent of Class C (since I found those `discriminator` property in the spec)?

If that's the case, then I don't think the auto-generated class C should directly contain propertyA, propertyB.

OpenAPI Generator provides better support for allOf and inheritance for OpenAPI 3.0 spec so I would recommend you to migrate to 3.0 spec instead for your use cases.

**Comment by pallzoltan** [comment]
Hmm, that's probsbly a problem in the templates then. Looking at `swift5/modelObject.mustache`, it goes through `{{#allVars}}` (line 10-30). I'll try fixing the template and updating the PR to avoid redeclaration of the parent's properties.

**Comment by wing328** [comment]
> Hmm, that's probably a problem in the templates then. Looking at swift5/modelObject.mustache, it goes through {{#allVars}} (line 10-30)

Before this change, the master generates Class C with only one property `propertyC` so looks like it's doing the right thing to not include other properties in the parent.

What's your expect output?

**Comment by pallzoltan** [comment]
Expected output is `ClassC` having one property `propertyC`, but inheriting from `ClassB`. I simply need the inheritance model working. 
Master right now will generate inheritance correctly only if the inheritance chain is 2 classes long (`ClassA`, `ClassB: ClassA`), but adding `ClassC` to this chain will end up with badly generated `ClassC`.

**Comment by wing328** [comment]
Ah ok. Still would recommend to start the work from OpenAPI 3.0 spec as we've been improving allOf, inheritance support and haven't tested with OpenAPI 2.0 spec for these enhancements since some of these new features are only available in the 3.0 spec.

**Comment by pallzoltan** [comment]
Couple of things: 
1) This PR is supposed to fix setting the `parentVars` and `emptyvars` in the codegen model, which was wrongly generated.
2) The mustache templates for Swift models are (imho) wrong. I can submit another PR with the templates we use, but let's please keep these two issues separate.
3) In the bug report ticket I've added v3 spec, as you requested.

Here's how this branch's base (old `master`) generated the objects:
```
- ClassA: NSObject	- defines: propertyA
- ClassB: NSObject	- defines: propertyA, propertyB
- ClassC: NSObject	- defines: propertyC
```
And here's the output with the fix:
```
- ClassA: NSObject	- defines: propertyA
- ClassB: NSObject	- defines: propertyA, propertyB
- ClassC: NSObject	- defines: propertyA, propertyB, propertyC
```
With the templates I have, I get the following structure generated:
```
- ClassA: NSObject	- defines: propertyA
- ClassB: ClassA	        - inherits: propertyA, defines: propertyB
- ClassC: NSObject	- inherits: propertyA, propertyB, defines: propertyC
```

**Comment by daberni** [comment]
Anything one can help with?

the generated structure described is the ideal result of how it should be? sure the constructor/init calls should be included properly too so inherited properties get passed along the inheritance tree correctly

**Comment by 4brunu** [comment]
Can someone please create a sample project to check the changes created by this PR?

**Comment by 4brunu** [comment]
Any news on this?

**Comment by wing328** [comment]
closing this as there's no update

**Review by iDevPro — COMMENTED** [review]
Try to apply this patch to Swift6 generator :)
```
nerator: Compilation failure: Compilation failure: 
[ERROR] /Users/pavel/Developer/GIT/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift6ClientCodegen.java:[1256,33] name clash: postProcessAllModels(java.util.Map<java.lang.String,java.lang.Object>) in org.openapitools.codegen.languages.Swift6ClientCodegen and postProcessAllModels(java.util.Map<java.lang.String,org.openapitools.codegen.model.ModelsMap>) in org.openapitools.codegen.DefaultCodegen have the same erasure, yet neither overrides the other
[ERROR] /Users/pavel/Developer/GIT/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift6ClientCodegen.java:[1255,6] method does not override or implement a method from a supertype
[ERROR] /Users/pavel/Developer/GIT/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift6ClientCodegen.java:[1257,75] incompatible types: java.util.Map<java.lang.String,java.lang.Object> cannot be converted to java.util.Map<java.lang.String,org.openapitools.codegen.model.ModelsMap>
[ERROR] /Users/pavel/Developer/GIT/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift6ClientCodegen.java:[1273,77] incompatible types: java.util.Map<java.lang.String,java.lang.Object> cannot be converted to java.util.Map<java.lang.String,org.openapitools.codegen.model.ModelsMap>
[ERROR] /Users/pavel/Developer/GIT/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift6ClientCodegen.java:[1281,74] incompatible types: java.util.Map<java.lang.String,java.lang.Object> cannot be converted to java.util.Map<java.lang.String,org.openapitools.codegen.model.ModelsMap>
```

**Comment by 4brunu** [comment]
Hi @iDevPro this change was never merged into the Swift5 generator.
Does this fix your problem?
Thanks

**Comment by iDevPro** [comment]
> Hi @iDevPro this change was never merged into the Swift5 generator. Does this fix your problem? Thanks

I can't build project yet... because I suppose that code will be changed for new variant of openapi-generator :)

**Pull request closed without merging**
