### PR TITLE
[python] add socket_options to configuration for the rest client

### PR DESCRIPTION
**Pull request by meadsteve**
This PR adds a property to the configuration object for the generated code rest client called socket_options. This property is passed down into urllibs3's ProxyManager/PoolManager as addition_pool_args. This extra key word argument should be picked up by the underlying HTTPConnection objects.

This enables consumers of the generated client to configuring the underlying connection if needed. In my specific use case I need this to set some keepalive settings for the connections.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @spacether

### CODE REVIEW

**Comment by spacether** [comment]
closing and re-opening to kick off ci again

**Comment by spacether** [comment]
@meadsteve this looks great, thank you!
Would you be willing to add a test asserting that the socket options are being used  by the PoolManager?
We have had features which have stopped working because no tests were ever written verifying that a feature existed, and someone tweaked code and broke something.
A good place to put a test like this would be in [this folder](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/openapi3/client/petstore/python-experimental/tests_manual).

**Comment by meadsteve** [comment]
Thanks. The tests sound good but I wasn't sure where to start so thanks for the suggestion.
The build still looks like it's failing but I'm not sure it's something I've done?

**Comment by spacether** [comment]
Yup, that CI error is unrelated to your PR; please ignore it.

**Comment by meadsteve** [comment]
@spacether I've added a test to cover this in python_experimental. I couldn't see any existing structure to do this for the non experimental python. Let me know if there's anything else you'd expect to see before this gets merged.

**Review by spacether — APPROVED** [review]
This looks great!
Thank you for the PR and for adding the tests!

**Pull request merged**
