### PR TITLE
[Ruby] Fix typo in description

### PR DESCRIPTION
**Pull request by jirikuncar**
Simple typo in Ruby client.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

--
cc @cliffano (2017/07) @zlx (2017/09) @autopp (2019/02)

### CODE REVIEW

**Comment by autopp** [comment]
@jirikuncar Thanks for PR!
Cound you run `bin/ruby-client-petstore.sh` and `bin/openapi3/ruby-client-petstore.sh` to update samples and commit changes?

**Comment by jirikuncar** [comment]
I can try. It would be nice if the CI creates a patch and submits a PR.

**Comment by wing328** [comment]
No worry. I'll update the samples after merging this PR.

Thanks for the PR.

**Comment by wing328** [comment]
@jirikuncar thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Pull request merged**
