### PR TITLE
Fix csharp-netcore enum var name underscore and space handling

### LINKED ISSUE #8212: [BUG][chsarp-netcore] Underscores and spaces aren't handled properly in enum var names
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Using underscores or spaces in enum member values does not produce the correct PascalCase output, which would be expected.

##### openapi-generator version

Reproduces with both 4.3.1 and master

##### OpenAPI declaration file content or url

A model declaration along these lines will produce issues
```json
"SomeEnum": {
  "title": "Lorem Ipsum",
  "description": "Lorem ipsum", 
  "enum": [
    "foo_bar",
    "bar baz"
  ]
}
```

##### Generation Details

Not relevant.

##### Steps to reproduce

Generate code for any spec with the kind of model described above.
It will produce an enum with members named `Foobar` and `Barbaz` instead of the expected `FooBar` and `BarBaz`.

##### Related issues/PRs

I will open a PR with a fix and unit tests in a moment.

##### Suggest a fix

See above.

### PR DESCRIPTION
**Pull request by sbergen**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Fixes #8212 

It seems I do not have the required permissions to perform the last step in the checklist.

### CODE REVIEW

**Comment by wing328** [comment]
cc @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02)

**Comment by sbergen** [comment]
@wing328 Thanks for adding those mentions! I found the instructions a bit unclear here, as I'm used to using the Reviewers feature for requesting review, and assumed that was the expected method also here. Perhaps something like this could be clearer?
> If your PR is targeting a particular programming language, @mention the technical committee members, so they are more likely to review the pull request.

**Comment by wing328** [comment]
| If your PR is targeting a particular programming language, @mention the technical committee members, so they are more likely to review the pull request.

Looks good to me. I wonder if you can submit a PR to revise the wording when you've time.

**Comment by wing328** [comment]
@sbergen thanks for the fix and the adding the tests.

**Pull request merged**
