### PR TITLE
Fix Java Feign client's parameter request name

### PR DESCRIPTION
**Pull request by wing328**
To fix https://github.com/OpenAPITools/openapi-generator/issues/3295

cherrypick https://github.com/OpenAPITools/openapi-generator/pull/3300

Credit: @stephanpelikan

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### CODE REVIEW

**Comment by ChristianCiach** [comment]
This completely broke our client because the param names inside the `@Param` and `@RequestLine` annotations do not match anymore (feign client).

Before (works):

```
  @RequestLine("GET /polling/events?tenant_id={tenantId}")
  @Headers({
    "Accept: application/json",
  })
  Events pollEvents(@Param("tenantId") String tenantId);
```

After (broken):
```
  @RequestLine("GET /polling/events?tenant_id={tenantId}")
  @Headers({
    "Accept: application/json",
  })
  Events pollEvents(@Param("tenant_id") String tenantId);
```

**Comment by RasPelikan** [comment]
It seems you're right: At https://github.com/OpenFeign/feign in section "Interface Annotations" the @RequestLine annotation is explained as used before. But this in conflict to x-www-form-urlencoded properties (see my origin issue https://github.com/OpenAPITools/openapi-generator/issues/3295).

There are two possibilities:
1. adopt the @RequestLine annotation value to "?tenant_id={tenant_id}" (which would be easy to do)
2. use tenantId and tenant_id depending on  it is query parameter or not (which is more complicated)

I think it depends on whether parameter names are compatible to template names regarding the characters which can be used (see https://tools.ietf.org/html/rfc6570). But since x-www-form-urlencoded properties do not have two different "names" (a property name and a template name) it seems the feign framework assumes that they are compatible because Param annotation are also used for them. 

I can provide a fix for (1). If (2) is prefered one of the OpenAPI should provide the patch.

@wing328: I also sometimes suffer by breaking changes. I can provide you a hot fix which can be applied on top of the current release-version.

**Comment by stephanpelikan** [comment]
It seems you're right: At https://github.com/OpenFeign/feign in section "Interface Annotations" the @RequestLine annotation is explained as used before. But this in conflict to x-www-form-urlencoded properties (see my origin issue #3295).

There are two possibilities:

1. adopt the @RequestLine annotation value to "?tenant_id={tenant_id}" (which would be easy to do)
1. use tenantId and tenant_id depending on it is query parameter or not (which is more complicated)

I think it depends on whether parameter names are compatible to template names regarding the characters which can be used (see https://tools.ietf.org/html/rfc6570). But since x-www-form-urlencoded properties do not have two different "names" (a property name and a template name) it seems the feign framework assumes that they are compatible because Param annotation are also used for them.

I can provide a fix for (1). If (2) is prefered one of the OpenAPI should provide the patch.

@wing328: I also sometimes suffer by breaking changes. I can provide you a hot fix which can be applied on top of the current release-version.

**Comment by RasPelikan** [comment]
@wing328: Maybe you can clone this as a workaround:
https://github.com/stephanpelikan/openapi-codegen-fixes

Hints:
- I implemented solution (1) 
- I could not test the change since I have no setup ready. If it does not work then let me know.

**Comment by RasPelikan** [comment]
@wing328: Maybe you can clone this as a workaround:
https://github.com/stephanpelikan/openapi-codegen-fixes

Hints:
- I implemented solution (1)
- I could not test the change since I have no setup ready. If it does not work then let me know.

**Comment by stephanpelikan** [comment]
@wing328: Maybe you can clone this as a workaround:
https://github.com/stephanpelikan/openapi-codegen-fixes

Hints:

- I implemented solution (1)
- I could not test the change since I have no setup ready. If it does not work then let me know.

**Comment by stephanpelikan** [comment]
sorry for the confusing updates on this thread: I messed up my github-accounts in my browsers :-|

**Pull request merged**
