### PR TITLE
#18031 Fix: added middleware adding for authorization methods [php-slim4]

### LINKED ISSUE #18031: [BUG] When generating stub for slim4, auth is not loaded thus not working
##### Description

When running `openapi-generator-cli generate -i example-openapi.yaml -g php-slim4 -o includes/lib/test_api_slim4` with any type of security supported, the Abstract class for Authentication is generated (`AbstractAuthenticator`) and instructions are also in readme, but the class will never be loaded.

##### openapi-generator version

7.3.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Library API
  version: 1.0.0
  description: This API allows clients to manage and access books in a library.
servers:
  - url: /wsbai/api/v1
    description: Production server
components:
  securitySchemes:
    # BearerAuth:
    #   type: http
    #   scheme: bearer
    #   bearerFormat: JWT
    # ApiKeyAuth:
    #   type: apiKey
    #   in: header       # can be "header", "query" or "cookie"
    #   name: X-API-KEY  # name of the header, query parameter or cookie
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the book.
        title:
          type: string
          description: The title of the book.
        author:
          type: string
          description: The author of the book.
        isbn:
          type: string
          description: The International Standard Book Number.
        publishedDate:
          type: string
          format: date
          description: The publication date of the book.
      required:
        - id
        - title
        - author
        - isbn
        - publishedDate
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
paths:
  /books:
    get:
      summary: List all books
      operationId: listBooks
      tags:
        - Books
      responses:
        '200':
          description: An array of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Add a new book
      operationId: addBook
      tags:
        - Books
      requestBody:
        description: Book to add to the library
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /books/{bookId}:
    get:
      summary: Get a book by ID
      operationId: getBookById
      tags:
        - Books
      parameters:
        - name: bookId
          in: path
          required: true
          description: ID of the book to return
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A single book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

security:
  - basicAuth: []
```

##### Steps to reproduce

1. run `openapi-generator-cli generate -i example-openapi.yaml -g php-slim4 -o includes/lib/test_api_slim4` with openapi spec I sent
2. Implement simple response for listBooks (example)
3. It will always load without checking any access

### PR DESCRIPTION
**Pull request by mvarchdev**
In php-slim4 - The authorization types are picked, just they are not added to routes middlewares, this PR fixes that.
fix: added middleware adding for authorization methods, added unauthorized handler to authorization abstract, fixes #18031

Tested with real application, working.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by mvarchdev** [comment]
I saw that there is already PR #12939 for this, but it is quite old and does not effectively solves issue.

**Comment by mvarchdev** [comment]
found some bug and some other bugs in environment setting, fixed also that

**Comment by mvarchdev** [comment]
@jebentier @renepardon @ybelenko

**Comment by wing328** [comment]
thanks for the PR. let's give it a try

cc @ybelenko

**Pull request merged**
