### PR TITLE
StringUtils functions

### PR DESCRIPTION
**Pull request by rienafairefr**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

As part of "Separation of Concerns" project and #842 I felt that the place for _camelize_, _underscore_, or _dashize_ are not in the DefaultCodegen, they should be moved to a class in org.openapitools.codegen.utils, and then each language would have its own use for these static functions

I also extracted the escapeSpecialCharacters method of DefaultCodegen to a static method _escape_ in StringUtils, looks better to me but that's not a mandatory part IMO

### CODE REVIEW

**Comment by jmini** [comment]
Can you please merge `master` into this PR?

**Comment by rienafairefr** [comment]
Done :+1:

**Comment by wing328** [comment]
I tried to use the web-based interface to resolve the merge conflicts but failed. I'm working on a fix by pulling the branch locally.

**Comment by wing328** [comment]
@rienafairefr can you please take another look to ensure my change didn't mess up your PR? Sorry for the inconvenience.

**Comment by rienafairefr** [comment]
OK I'll look at that when I get some time 👍

**Comment by rienafairefr** [comment]
Your merge looks fine :+1: 
Re-looking at it, because this removes some public methods in `DefaultCodegen` this is a breaking change, shouldn't this be targeted to 4.0 ? I could easily reinstate the public methode, `@Deprecate` them while delegating to StringUtils inside each, then that wouldn't break any public thing, and could go in 3.2.3 . Your call, I guess

**Comment by wing328** [comment]
> @Deprecate them while delegating to StringUtils inside each, then that wouldn't break any public thing, and could go in 3.2.3.

I think that's more preferable by using @Deprecate to mark those methods to be deprecated later.

**Comment by rienafairefr** [comment]
Done, they're deprecated now. A bit ugly to have to call with the fully qualified org.openapitools.codegen.utils.StringUtils.* name (as long as the methods are not removed, the names clash), but it seems to work. Might be cleaner to rename the methods.

**Comment by wing328** [comment]
If no one has further feedback, I'll merge it tomorrow.

**Pull request merged**
