### PR TITLE
[OCaml] Code generation fixes

### PR DESCRIPTION
**Pull request by MisterDA**
The bugs were discovered using the Docker spec.

The Lwt module has functions that might shadow parameters, and all the functions we use from `Lwt` are in `Lwt.Infix` too.

    File "src/apis/image_api.ml", line 13, characters 69-72:
    13 |     let uri = Request.maybe_add_query_param uri "all" string_of_bool all in
                                                                              ^^^
    Error: This expression has type 'a t list -> 'a list t
           but an expression was expected of type bool option
           
ref #9787 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@cgensoul

### CODE REVIEW

**Comment by wing328** [comment]
Tests are ok:
```
➜  ocaml git:(MisterDA-ocaml-fixes) eval $(opam env)
➜  ocaml git:(MisterDA-ocaml-fixes) dune build
```

**Comment by MisterDA** [comment]
Thanks for merging!
Please note that this PR doesn't completely fix the OCaml codegen, there's still one bug listed [here](https://github.com/OpenAPITools/openapi-generator/issues/9787#issuecomment-1130075426).

**Comment by wing328** [comment]
FYI. I've merged https://github.com/OpenAPITools/openapi-generator/pull/12477 to fix the installation instruction.

For https://github.com/OpenAPITools/openapi-generator/issues/9787#issuecomment-1130075426, is that still an issue with the latest master (we fixed some issue recently with the inline model resolver) ?

**Comment by MisterDA** [comment]
> For https://github.com/OpenAPITools/openapi-generator/issues/9787#issuecomment-1130075426, is that still an issue with the latest master (we fixed some issue recently with the inline model resolver) ?

They probably fixed earlier issues with OCaml codegen (thanks for that!), but this last one is still present with latest master (129fd0ad5c95b8de90ba5a6350de725a12019071).

**Pull request merged**
