### PR TITLE
[kotlin][client] Add Jackson as serialization library

### PR DESCRIPTION
**Pull request by herveDarritchon**
This PR add Jackson support as a serialization library for Kotlin Client.

It is a follow up of issue [Kotlin] Support gson for serialization in addition to moshi and it is based on discussion of my issue #3414 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by herveDarritchon** [comment]
I don't understand pipeline is failing on python tests which are not updated by this PR ?

**Comment by herveDarritchon** [comment]
Hi, if anyone can help me with fixing the pipeling, big appreciate

**Comment by wing328** [comment]
I've pushed 2 commits to update the samples and documentation so as to fix the CI build failure. Let's see how it goes.

**Comment by wing328** [comment]
FYI. Filed https://github.com/OpenAPITools/openapi-generator/pull/5438 to include it in the CI tests.

**Comment by wing328** [comment]
@herveDarritchon thanks for the PR, which has been included in the 4.3.0 release: https://twitter.com/oas_generator/status/1243455743937789952

**Pull request merged**
