### PR TITLE
fix(typescript-nodejs): update package json dependencies

### LINKED ISSUE #15492: [BUG][typescript-nestjs] Install and build fail with current dependencies
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When creating a new API Client with the typescript-nestjs generator, the dependencies on package.json make it so the `npm install` and `npm run build` commands do not work out of the box.

##### openapi-generator version

6.5

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_1/petstore.yaml

##### Generation Details

openapi-generator generate -i modules/openapi-generator/src/test/resources/3_1/petstore.yaml -g typescript-nestjs -o ./client-generation --additional-properties=npmName=petstore --skip-validate-spec

##### Steps to reproduce

Run the generator as stated above, then go into the folder and run `npm install`

The following error will appear:
image

After fixing this issue by updating rxjs to version 7.1, the install happens correctly, but when running `npm run build`, a few errors pop up:

image

These can be fixed by added `@nestjs/axios` to the package.json. But then, we get one last error:

image

Which can be fixed by updating the @types/node version.

##### Suggest a fix

I'll create a PR and link it.

### PR DESCRIPTION
**Pull request by lucasheim**
Fixes #15492 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx  @macjohnny  @topce  @akehir  @petejohansonxo @amakhrov  @davidgamero  @mkusaka

### CODE REVIEW

**Comment by andrefbsantos** [comment]
👍

**Review by TiFu — COMMENTED** [review]
LGTM! 

Let's see what CI says :)

**Review by macjohnny — COMMENTED** [review]
Please update the generated samples

**Comment by macjohnny** [comment]
@Dorbash you can clone this PR and re-generate the samples

**Comment by wing328** [comment]
Samples updated via https://github.com/OpenAPITools/openapi-generator/pull/15493/commits/f89bac7d409b26303c73f86dfac45c0bb84486f3

**Review by macjohnny — CHANGES_REQUESTED** [review]

**Comment by wing328** [comment]
@Dorbash can you please pull the latest and update the samples again? Just included a change/fix from @macjohnny

**Comment by wing328** [comment]
Updated samples again. Let's see how that goes.

**Comment by wing328** [comment]
circleci node 4 failure not related to this change (already fixed in master)

**Pull request merged**
