### PR TITLE
[typescript] Add `importFileExtension` option to support ECMAScript module resolution

### LINKED ISSUE #14333: [REQ] New typescript-generator option to set file extension for ECMAScript module resolution
### Is your feature request related to a problem? Please describe.

I'm trying to generate a pure ESM package (`type: "module"`) using [ESM in Node.js](https://www.typescriptlang.org/docs/handbook/esm-node.html), but the Typescript generators generate relative imports without file extensions (e.g. `import * as runtime from "../runtime"`) while [Node.js requires file extensions for ESM imports](https://nodejs.org/api/esm.html#mandatory-file-extensions) (`import * as runtime from "../runtime.js"`)

## Describe the solution you'd like

* The `typescript` generator already has an internal option `extensionForDeno`, which is set to `.ts` when `platform` is `deno`. I suggest renaming `extensionForDeno` to `importFileExtension` and making it a public option.
* The other typescript generators does not have such an option, so it may have to be added to those, if needed

I can try putting together a PR for this, but would like to gather some feedback about whether it's a good idea first.

## Describe alternatives you've considered

* <s>It's possible to generate a valid ESM package by setting `moduleResolution: "node"` (CommonJS for internal module resolution) and `module: "ESNext"`, but this will fail if we add additional dependencies to the generated package that aren't CommonJS compatible.</s>

* Instead of adding a new option `importFileExtension`, derive the file extension from some other option:
  * From `platform`? If we add a new value like `node-esm`. The problem is that there are several different extensions that can potentially be used (`.js`, `.mjs`, `.tjs` etc.) and users may have different preferences.
  * Perhaps a new option `moduleResolution` with values `node` and `node16` inspired by TypeScript?

### PR DESCRIPTION
**Pull request by danmichaelo**
[Node.js ECMAScript module resolution](https://nodejs.org/api/esm.html) requires file extensions for relative imports. Typescript also conforms to this requirement when using the new [`nodenext` module resolution setting](https://www.typescriptlang.org/docs/handbook/esm-node.html).

File extension support was already added to the Typescript(experimental) generator for Deno in #6732. The current PR generalizes the `extensionForDeno` parameter into `importFileExtension` and makes it user configurable, so users can set it to `.js` for a pure ESM package or `.mjs` for a dual package.

The current PR only adds the option to `TypeScriptClientCodegen`, which seems to be the new generator if I understand it right, but if the PR is accepted, I'd like to try adding it to `AbstractTypeScriptClientCodegen` as well in a separate PR, to support `typescript-fetch` and friends.

fixes #14333

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka

### CODE REVIEW

**Review by macjohnny — APPROVED** [review]
Thanks for your contribution

**Comment by avrelaun** [comment]
Thank you for this PR, adding support for typescript-fetch would be nice :+1:

**Comment by florianbepunkt** [comment]
Support for the typescript axios generator would be nice as well.

**Comment by coeing** [comment]
@danmichaelo Would it be possible to move the `importFileExtension` property to `AbstractTypeScriptClientCodegen`? This would make it available in other typescript code generators, like `typescript-fetch` and `typescript-axios` as well.

**Pull request merged**
