### PR TITLE
Don't include read-only properties in Python examples.

### PR DESCRIPTION
**Pull request by therve**
When using a schema with read-only fields as API inputs, Python
generates examples for those: this excludes them.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by therve** [comment]
@taxpon @frol @mbohlool  @cbornet @kenjones-cisco @tomplus @Jyhess @arun-nalla @spacether 🙇

**Comment by spacether** [comment]
@therve these example should only be omitted when sending data to the server, right?
One could get back a readonly property or instance, right?

**Comment by therve** [comment]
> @therve these examples should only be omitted when sending data to the server, right?
> One could get back a readonly property or instance, right?
> Our tooling does not currently autogen mock responses but if we did in the future one would need to be aware of this.

Right if we ever generate response code this would need to be changed.

**Review by spacether — APPROVED** [review]
Looks good; thank you for your PR!

**Pull request merged**
