### PR TITLE
typescript-angular: spaceDelimited fix for parameters (#5630)

### PR DESCRIPTION
**Pull request by LPCmedia**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by LPCmedia** [comment]
@amakhrov let me know.

**Comment by macjohnny** [comment]
this is in conflict with https://github.com/OpenAPITools/openapi-generator/pull/5000 by @DavidBiesack 

@jimschubert we should stick to #5000, right?

**Comment by LPCmedia** [comment]
all good for me. Let me know if I can do something to help as #5000 is not building at the moment.

**Comment by jimschubert** [comment]
Yeah, we should stick to what's defined in the spec. Collection format is ssv in 2.0 and replaced with a style parameter in 3.x (see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#style-values). The change in this PR would mix the two concepts.

**Comment by LPCmedia** [comment]
@jimschubert  should I work off #5000 to ensure the build passes or it that something imminent ?

**Pull request closed without merging**
