### PR TITLE
#80: ensure typescript samples are up to date

### PR DESCRIPTION
**Pull request by macjohnny**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

ensure typescript samples are up to date, see https://github.com/OpenAPITools/openapi-generator/issues/80#issuecomment-402126069

cc @jmini

### CODE REVIEW

**Comment by macjohnny** [comment]
@jmini are there any plans to ignore changes to the `VERSION` file?

**Comment by jmini** [comment]
@macjohnny: 
In our `samples/` folder? this was discussed in #245. My opinion is that this is useful information (feel free to continue the discussion there - reopen if necessary).
If you do not want to generate it for your project, I think that there is an option to not generate metadata files.

**Comment by macjohnny** [comment]
@jmini 
> In our `samples/` folder?

yes, I think it is cumbersome needing to re-generate all samples when the version number is updated

**Comment by jmini** [comment]
> yes, I think it is cumbersome needing to re-generate all samples when the version number is updated

This is made as part of the "Prepare next version PR" (see 9511586 for an example), you do not have to care about this.

Having the `.VERSION` file in samples has several benefits:

* understanding the state of a samples. We used it a lot during migration to `3.0.0`.
* seeing outdated samples, sorting samples by versions

**Comment by macjohnny** [comment]
@jmini ok, so then it should be fine.

**Comment by jmini** [comment]
After merge of #363 the merge conflicts needs to be solved, sorry about this (this will happen less and less when the samples stays up-to-date with each PR)

**Comment by macjohnny** [comment]
@jmini no problem, I will update the samples tomorrow and try to fix the `typescript-node` test that fails with the updated samples

**Comment by macjohnny** [comment]
@jmini could you please merge this? all checks pass, except for (unrelated) outdated samples:
- `samples/client/petstore/java/webclient/docs/FakeApi.md`
- `samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/api/FakeApi.java`
- `samples/openapi3/client/petstore/php/OpenAPIClient-php/lib/Api/PetApi.php`
- `samples/client/petstore/java/webclient/docs/FileSchemaTestClass.md` (new file)
- `samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/model/FileSchemaTestClass.java`

would you mind updating these files in a separate PR?

**Comment by jmini** [comment]
> would you mind updating these files in a separate PR?
I think @wing328 just did that in #478

**Comment by jmini** [comment]
I have merged `master` into your PR.

**Comment by macjohnny** [comment]
@jmini @wing328 thanks! The CI checks now pass.

**Pull request merged**
