### PR TITLE
[Java] Fix missing underscores for PascalCase enum values #4837

### PR DESCRIPTION
**Pull request by renatomameli**
Resolves: #4837

Addresses an issue with the conversion of enum values to valid variable names. When the enum value is a string and contains multiple words without separators (e.g., `TestCase`), underscores between the words were previously missing (e.g., "TESTCASE").

To address this issue, the existing `underscore` method is now applied to the value before all characters are converted to uppercase letters. The underscore method converts CamelCase to SCREAMING_SNAKE_CASE while preserving the case of individual words (e.g., `TestCase` becomes `TEST_CASE`)

Corresponding tests have been added.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by renatomameli** [comment]
@lwlee2608 @martin-mfg

**Comment by renatomameli** [comment]
@wing328 samples updated

**Comment by wing328** [comment]
thanks for the PR, which has been merged.

**Comment by wing328** [comment]
For those who need to fallback to previous naming convention, please use the enum name mapping option: https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping

**Comment by jpfinne** [comment]
An other workaround is `x-enum-varnames` in the contract.

https://openapi-generator.tech/docs/templating/#all-generators-core

Still a PITA to have such a change in a minor version

**Comment by frodeo** [comment]
Is there a way to revert back to the old behavior, for instance by setting a configuration parameter? I think this is a bad change. If you want underscores in the enums then you can put them into the swagger instead. The suggested "workarounds" are not really workarounds since we build the code using general pipelines and don't want to hardcode any manual mappings.

**Comment by MojoQ** [comment]
One should really not introduce undocumented breaking changes with minor versions...

**Comment by T3rm1** [comment]
Please revert this change asap. Who is responsible for this and could do it? This even introduces more bugs, e.g. "B2B" is now translated to "B2_B".

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/19630 to add the option `enumPropertyNaming` (MACRO_CASE, legacy) so that one can set it to `legacy` for fallback.

Please give it a try when you've time.

About including breaking changes with fallbacks in minor releases, please refer to the FAQ for more information: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#can-you-explain-how-the-releases-are-versioned

**Comment by MojoQ** [comment]
Thank you, William, both for the proposed fix (which I will test as soon as
I get planning approval) and the hint regarding the FAQ. I was not aware of
that! :)
Still it would be nice to mention these breaking changes in the Release
Notes :) I hope we can agree on that :)

Am Mo., 25. Nov. 2024 um 09:16 Uhr schrieb William Cheng <
***@***.***>:

**Comment by wing328** [comment]
In the release note (minor releases), there's a link to a list of breaking changes with fallbacks 

e.g. https://github.com/OpenAPITools/openapi-generator/releases/tag/v7.7.0

**Comment by martin-mfg** [comment]
> I've filed #19630 to add the option `enumPropertyNaming` (MACRO_CASE, legacy) so that one can set it to `legacy` for fallback.
> 
> Please give it a try when you've time.

It seems the link is wrong and the new PR is actually https://github.com/OpenAPITools/openapi-generator/pull/20172.

**Comment by wing328** [comment]
if your use cases didn't work before and after this PR (#18594), then please use enum name mapping option instead (`enumNameMappings`) for the time being.

https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping

**Comment by MojoQ** [comment]
Hey, @wing328 !
I tested the fix and it works perfectly well for me. Thanks a lot! Is there a planned release date for 7.11.0? Or could you give me a rough estimation?

> In the release note (minor releases), there's a link to a list of breaking changes with fallbacks
> 
> e.g. https://github.com/OpenAPITools/openapi-generator/releases/tag/v7.7.0
Thank you. I certainly should read more documentation before making such remarks :)
Sorry for that! 
Thanks a lot for your fix! I really appreciate your work!
BR Mojo

**Pull request merged**
