### PR TITLE
[typescript-rxjs] drop unneeded function wrapping 

### PR DESCRIPTION
**Pull request by denyo**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
This PR removes unneeded wrapping functions within api controllers.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)

### CODE REVIEW

**Comment by macjohnny** [comment]
@denyo btw. can you remind we why there is this separation `get...()` and `get...Raw()`?

**Comment by denyo** [comment]
@macjohnny I am not really sure. I just took what was already there in `typescript-fetch` which this generator is based on. 

The only thing that I can think of and which happened to me in my current project is that you need the raw xhr response in order to extract a certain header (e.g. for pagination). 
I was able to achieve this by extending the `BaseAPI`'s `protected request()` by `ResponseOpts`:
```
protected request<T>(reqOpts: RequestOpts, resOpts?: ResponseOpts): Observable<T> {
...
    if (resOpts && resOpts.response === 'raw') {
        return res as any as T;
    } else {
        return res.response as T;
    }
...
}
```

In the api controller I then have something like
```
private loginUsingPOSTRaw(requestParameters: LoginUsingPOSTRequest, responseOptions?: ResponseOpts): Observable<AjaxResponse> {
    ...
    return this.request<AjaxResponse>({
        ...
    }, responseOptions);
}

loginUsingPOST(requestParameters: LoginUsingPOSTRequest): Observable<MachineOperatorDto>
loginUsingPOST(requestParameters: LoginUsingPOSTRequest, responseOptions: ResponseOpts): Observable<AjaxResponse>

loginUsingPOST(requestParameters: LoginUsingPOSTRequest, responseOptions?: ResponseOpts): Observable<any> {
    return this.loginUsingPOSTRaw(requestParameters, responseOptions);
}
```

And where ever I call this function with `{ response: 'raw' }` I can then extract a header with `res.xhr.getResponseHeader(SOME_KEY)`.

I did these modifications manually. So they aren't part of the generator as of now.

**Comment by macjohnny** [comment]
ok, but currently there is no difference between the two, right?

**Comment by denyo** [comment]
Yes, right now they have the same signature and the public one is calling the private `RAW` one.

**Comment by denyo** [comment]
It looks like in the `typescript-fetch` client this was used to unwrap the response promise and have the right type since promises don't support generics? If thats the case I can simplify this client.

**Comment by macjohnny** [comment]
> It looks like in the typescript-fetch client this was used to unwrap the response promise and have the right type since promises don't support generics? If thats the case I can simplify this client.

sounds reasonable, with rxjs, the flow is straight-forward and nicely typed

**Comment by denyo** [comment]
There we go.

**Pull request merged**
