### PR TITLE
Fix on PR: #888 RFC: [go] define "any-type" schema as an empty interface in generated go code.

### PR DESCRIPTION
**Pull request by mattiabertorello**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
Fix issue point out here: https://github.com/OpenAPITools/openapi-generator/pull/888#discussion_r212615913

@wing328 @ashanbrown @eclipse1985
@antihax (2017/11) @bvwells (2017/12) @grokify (2018/07)

### CODE REVIEW

**Comment by wing328** [comment]
@mattiabertorello what about using `--type-mapping object="interface{}"` instead?

if it works, we can add this mapping to the Abstract Go class.

**Comment by eclipse1985** [comment]
> @mattiabertorello what about using `--type-mapping object="interface{}"` instead?
> 
> if it works, we can add this mapping to the Abstract Go class.

@wing328 Actually seems that with this parameter the generations works pretty good even without adding the mapping to the Abstract Go class. Can you confirm?

**Comment by wing328** [comment]
If it works, we can hard code the mapping in the Abstract Go class rather than supplying this everytime via --type-mapping when running the generator.

**Comment by eclipse1985** [comment]
Looks very good to me, but we see that at this [commit](https://github.com/OpenAPITools/openapi-generator/commit/4664c07034fac99cfb6354fae6301d85f4f96810) it was already changed in the past from `interface{}` to `map[string]interface{}`. But if you confirm that is ok on your side we fix it exactly as you said.

**Comment by wing328** [comment]
This is already done: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java#L133

Please give the latest master a try.

Closing this PR for the time being.

**Pull request closed without merging**
