### PR TITLE
Regenerate samples and docs

### PR DESCRIPTION
**Pull request by tkirshboim**
It seems that the samples and docs were not fully regenerated in a recents changes (maybe #10995 #11094 among others ?) .
This PR updates the samples and regenerates the docs.

CCing: @wing328 @4brunu 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by tkirshboim** [comment]
Tests are failing, so making this a draft for now.

**Comment by wing328** [comment]
Let me take a look ...

**Comment by wing328** [comment]
Don't see any changes to samples/docs using the latest master
```sh
# START SCRIPT: ./bin/utils/export_generator.sh typescript-redux-query
Executed /Users/williamcheng/Code/openapi-generator2/bin/utils/export_docs_generators.sh successfully!
Starting /Users/williamcheng/Code/openapi-generator2/bin/utils/copy-to-website.sh ...
# START SCRIPT: ./bin/utils/export_generator.sh typescript-rxjs
# START SCRIPT: ./bin/utils/export_generator.sh wsdl-schema
# START SCRIPT: /Users/williamcheng/Code/openapi-generator2/bin/utils/copy-to-website.sh
Wrote /Users/williamcheng/Code/openapi-generator2/docs/conduct.md
Wrote /Users/williamcheng/Code/openapi-generator2/docs/contributing.md
Executed /Users/williamcheng/Code/openapi-generator2/bin/utils/copy-to-website.sh successfully!
Starting /Users/williamcheng/Code/openapi-generator2/bin/utils/export_generators_readme.sh ...
# START SCRIPT: /Users/williamcheng/Code/openapi-generator2/bin/utils/export_generators_readme.sh
Wrote /Users/williamcheng/Code/openapi-generator2/docs/generators.md
Executed /Users/williamcheng/Code/openapi-generator2/bin/utils/export_generators_readme.sh successfully!
Git working tree is clean
➜  openapi-generator2 git:(master) git log | head
fbb61658dfbcc2c1f5087511b0f74756553791ad [kotlin][client] rename ApiInfrastructureResponse to ApiResponse (#11094)
3247903caacb6ad139a8ebebfdc5110e8608e831 [kotlin][client] update request exceptions (#11065)
0236f84c1156c4aa03027c861221cf6389c35479 [kotlin-client] Allowing vendor types for json (#10758)
cee5f7591241956b946263855caf8c4eb18e6470 Feat adds content and header properties to CodegenResponse (#11046)
c94d2b2331fe851c79d86e2cfae6a036de5f1ce5 [swift5] Fix missing case for FormDataEncoding#encode (#11064)
550c0781dca1505762e8348f7b692d751b28c766 [okhttp-gson-next-gen] new option for error object (#10995)
b755ae288afe9b4d23de14e72ff6dc7735686690 [Python] Add option to select/detect content-type. (#10978)
347b75a024452d8fbdfc3864084d2f613004d7ca Fixes paramName and dataType for request body anyType parameters (#11075)
c9410447019068af88971143b979d4ec02b8ac17 [swift5][client] allow request cancellation and authentication flow to work together (#11019)
2ff6f833e2f9dc6885f73375e0adc9e17d504a0f add more tests for oneOf (#11068)
```

**Comment by tkirshboim** [comment]
@wing328 
I must have had something wrong with my local configuration. Sorry about that!

**Comment by wing328** [comment]
No problem. Let us know if you need any help.

**Pull request closed without merging**
