### PR TITLE
remove fixme by setting param to final and creating local variable fo…

### PR DESCRIPTION
**Pull request by smasala**
General refactoring:
- remove fixme by setting param to final and creating local variable for sanitising model name

@wing328 @macjohnny

### CODE REVIEW

**Comment by wing328** [comment]
cc TS technical committee: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07)

**Comment by akehir** [comment]
Looks good, shouldn't have an impact on the generated code, as far as I understand it.

**Comment by akehir** [comment]
And @macjohnny already merged 💃

**Comment by wing328** [comment]
@smasala thanks for the PR, which has been included in the 4.1.0 release: https://twitter.com/oas_generator/status/1160000504455319553

**Pull request merged**
