### PR TITLE
[rust][reqwest] support binary type for download

### PR DESCRIPTION
**Pull request by ThomasVille**
fix https://github.com/OpenAPITools/openapi-generator/issues/18117

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ThomasVille** [comment]
I created a PR with the same code as https://github.com/OpenAPITools/openapi-generator/pull/18682 to see which tests are failing in the CI.

**Comment by ThomasVille** [comment]
The CI needs approval to run, but I can run the tests locally.

**Comment by DDtKey** [comment]
Let's update the branch and mark the PR as ready for review? 

I've described my opinion in the issue: https://github.com/OpenAPITools/openapi-generator/issues/18117#issuecomment-2482814212

**Comment by wing328** [comment]
@DDtKey thanks for the feedback.

Did you test the change locally? e.g.

```
git checkout -b ThomasVille-rust_binary_type_support master
git pull https://github.com/ThomasVille/openapi-generator.git rust_binary_type_support
```

and the build the CLI JAR by running `mvn clean package` (or using maven wrapper included in this repo)

**Comment by ThomasVille** [comment]
@wing328 I ran these commands:
```
git clone git@github.com:OpenAPITools/openapi-generator.git
cd openapi-generator/
git checkout -b ThomasVille-rust_binary_type_support master
git pull https://github.com/ThomasVille/openapi-generator.git rust_binary_type_support
./mvnw clean package
```

And here is the result [clean-run.txt](https://github.com/user-attachments/files/17904875/clean-run.txt).

It looks like everything succeeded.

So I synced my fork with the upstream repo and rebased my branch on master. So the PR should now contain the latest changes from master.

**Comment by DDtKey** [comment]
As far as I understand there is an endpoint with files response:
At least this file has been regenerated: `samples/client/petstore/rust/reqwest/petstore-awsv4signature/src/apis/testing_api.rs`  - which is correct, it used to be `std::path::PathBuf` which is wrong one.

```rs
pub fn tests_file_response_get(configuration: &configuration::Configuration, ) -> Result<reqwest::blocking::Response, Error<TestsFileResponseGetError>> {
```

**Comment by ThomasVille** [comment]
@wing328 As said by @DDtKey, there's already an endpoint in the petstore test spec to test binary return type [here](https://github.com/OpenAPITools/openapi-generator/blob/326f100f0e4e50f569f43fbceaa5448b407fa8f9/modules/openapi-generator/src/test/resources/3_0/rust/petstore.yaml#L602C1-L614C31): `/tests/fileResponse`.

For instance, this endpoint generates [this code](https://github.com/OpenAPITools/openapi-generator/blob/3755f3c4ba4e97f50d8fa36c7a56c307a821e3db/samples/client/petstore/rust/reqwest/petstore/src/apis/testing_api.rs#L33) in the `reqwest` target:
```rs
pub fn tests_file_response_get(configuration: &configuration::Configuration, ) -> Result<reqwest::blocking::Response, Error<TestsFileResponseGetError>> {
```

Did you think about something else that I didn't understand?

**Comment by wing328** [comment]
OK. Thanks for the info. I missed that.

Happy to merge this one. Thanks again for the PR

**Pull request merged**
