### PR TITLE
Fix issue with useBeanValidation

### PR DESCRIPTION
**Pull request by UnklePig**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

The useBeanValidation was not being set correctly in certain instances. In particular, when the default was set to true, in several languages it was impossible to set it to false. In addition, the help message was always saying the default was false, even when it was actually true - which could be confusing.

This fix has updated the CliOption class to add a method for assigning a default value when creating a boolean CliOption and called this from various places to ensure that the default is set correctly. It also modifies the code for the languages that were failing so that setting the value to false is handled correctly.

### CODE REVIEW

**Comment by wing328** [comment]
@UnklePig Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by UnklePig** [comment]
@wing328 Thanks for letting me know.  I believe I have fixed it up now.  Let me know if there are still problems.

**Comment by wing328** [comment]
@UnklePig looks good now. I've resolved the merge conflicts via https://github.com/OpenAPITools/openapi-generator/pull/160/commits/7c835ccc6856c77bc83bc5c5443c9d368535bdd3.

Please review and let me know if you spot any issue.

**Comment by UnklePig** [comment]
@wing328  Looks good to me

**Pull request merged**
