### PR TITLE
[JAVA][SPRING][2195] added missing getter for enum value

### LINKED ISSUE #2195: [BUG][JAVA-Spring] Enum without value getter
##### Description

Generated enum class is missing getter for it's value. Is there any option with which I can turn on getter generation? Method toString is sufficient for String enums, but if I want numbered values it's annoying to convert values between different types.

##### openapi-generator version

3.3.4 openapi-generator-maven-plugin

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    QueueStatus:
      type: integer
      enum:
        - 1
        - 10
        - 100
        - 1000
      x-enum-varnames:
        - EDITABLE
        - DELETABLE
        - LOCK
        - SPECIAL
```

##### Command line used for generation

`mvn clean install`

##### Generated output class
```java
public enum QueueStatus {
  
  EDITABLE(1),
  
  DELETABLE(10),
  
  LOCK(100),
  
  SPECIAL(1000);

  private Integer value;

  QueueStatus(Integer value) {
    this.value = value;
  }

  @Override
  @JsonValue
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static QueueStatus fromValue(String text) {
    for (QueueStatus b : QueueStatus.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}
```

### PR DESCRIPTION
**Pull request by bilak**
fixes #2195

### CODE REVIEW

**Comment by wing328** [comment]
@bilak please update the samples so that the CIs can test the change. Let me know if you need help on that.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

**Comment by bilak** [comment]
@wing328 yes please guid me through update. Lastly when I did it, it failed on some parts.

**Comment by wing328** [comment]
@bilak can you leave me a message via https://gitter.im so that I can share the steps with you?

**Comment by bilak** [comment]
@wing328 what is wrong here please? Do I need to regenerate something? I've just rebased on master.

**Comment by bilak** [comment]
@wing328 can this get to 4.x please?

**Comment by wing328** [comment]
I restart the CircleCI job. Let's see if all the tests pass.

**Comment by bilak** [comment]
@wing328 waht's wrong here? I've executed `./bin/spring-all-petstore.sh` but it looks like there is another configuration.

**Comment by macjohnny** [comment]
@bilak there are some problems with your PR. Please have a look at the result of the CI: https://circleci.com/gh/OpenAPITools/openapi-generator/8868?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by bilak** [comment]
@macjohnny can you help me with those? I don't understand what's wrong there. `Could not write request: no suitable HttpMessageConverter found for request type [org.openapitools.model.Pet] and content type [application/json]`

**Comment by macjohnny** [comment]
I think this is the relevant message:
```
2019-09-10 07:17:49.237  WARN 15046 --- [nAPIPetstore-10] .c.j.MappingJackson2HttpMessageConverter : Failed to evaluate Jackson serialization for type [class org.openapitools.model.Order]: com.fasterxml.jackson.databind.JsonMappingException: Problem with definition of [AnnotedClass org.openapitools.model.Order$StatusEnum]: Multiple 'as-value' properties defined ([method org.openapitools.model.Order$StatusEnum#toString(0 params)] vs [method org.openapitools.model.Order$StatusEnum#getValue(0 params)])
2019-09-10 07:17:49.243  WARN 15046 --- [nAPIPetstore-10] .c.j.MappingJackson2HttpMessageConverter : Failed to evaluate Jackson serialization for type [class org.openapitools.model.Order]: com.fasterxml.jackson.databind.JsonMappingException: Problem with definition of [AnnotedClass org.openapitools.model.Order$StatusEnum]: Multiple 'as-value' properties defined ([method org.openapitools.model.Order$StatusEnum#toString(0 params)] vs [method org.openapitools.model.Order$StatusEnum#getValue(0 params)])
[ERROR] Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.119 s <<< FAILURE! - in org.openapitools.api.StoreApiTest
```

**Comment by bilak** [comment]
well I don't understand what's wrong there. The parameter of enum is String so the `getValue` is correct and returns string. Don't understand why jackson complains about those methods.

**Comment by macjohnny** [comment]
it is because there are two `@JsonValue` annotated methods of the enum:
https://github.com/OpenAPITools/openapi-generator/blob/97b3581e66fb03030fa40ace055acb889fe24c8f/samples/client/petstore/spring-cloud-async/src/main/java/org/openapitools/model/Order.java#L48-L57

I think similar to
https://github.com/OpenAPITools/openapi-generator/blob/bc6c94d412ab62b8c4352eef8d7ece758e827ec2/modules/openapi-generator/src/main/resources/Java/modelEnum.mustache#L35-L45
it the `@JsonValue` annotation should be removed from the `toString()` method.

@jmini do you agree?

**Comment by bilak** [comment]
@macjohnny does the last bug has something common with spring? I see problem in `okhttp-gson`

**Comment by macjohnny** [comment]
all tests in the CI pass, so we should wait for a review by the technical committee

**Pull request merged**
