### PR TITLE
WIP: Ruby faraday client

### PR DESCRIPTION
**Pull request by meganemura**
**🚧under construction 🚧**

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

Implementation of #1422.

### CODE REVIEW

**Comment by wing328** [comment]
@meganemura thanks for the PR. Do you need help with the implementation? Let us know.

**Comment by dkliban** [comment]
@meganemura Are you planning to continue this work?

**Comment by wing328** [comment]
@dkliban did you have a chance to test it? If you can list out things that need improvement, we can work together on those items.

**Comment by dkliban** [comment]
@wing328 I tried generating a client from this PR and was able to generate a client, however, the Gem spec file needs is specifying the dependencies incorrectly. I will investigate this next. 

I rebased this PR against the master branch without problems. Then I ran into https://github.com/OpenAPITools/openapi-generator/issues/3335 when generating a Ruby client this time. So I think 3335 is not a language specific bug.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/3405

**Pull request closed without merging**
