### PR TITLE
[C#] [aspnetcore] Option to have files as IFormFile instead of Stream

### PR DESCRIPTION
**Pull request by lindgrenfredrik**
Added option to aspnetcore generator to have it generate file data type as IFormFile instead of Stream

fix: #2398

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [NA] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
Added new script bin/aspnetcore-binary.sh

- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc
@mandrean 
@jimschubert 
@frankyjuang 
@shibayan 

Question: Do I need to merge the sample output from the test script into the repo as well?

### CODE REVIEW

**Comment by wing328** [comment]
@lindgrenfredrik thanks for the PR. What about using the `typeMapping` option directly instead?

**Comment by lindgrenfredrik** [comment]
@wing328 if you mean the command line option like: --type-mappings file=Microsoft.AspNetCore.Http.IFormFile

First I wasn't aware of that command line option.
Second, it doesn't seem to work right since it looses the . in the mapping

**Comment by lindgrenfredrik** [comment]
Adding both Type mapping and import mapping made it possible to generate without this change.

Command line options:
--type-mappings file=IFormFile --import-mappings IFormFile=Microsoft.AspNetCore.Http.IFormFile"

Hence this change is not needed as same result can be achieved with command line options.
Though perhaps documentation should be updated to include this as a example in some manner

**Comment by jmnbo-iscteiulpt** [comment]
> Adding both Type mapping and import mapping made it possible to generate without this change.
> 
> Command line options:
> --type-mappings file=IFormFile --import-mappings IFormFile=Microsoft.AspNetCore.Http.IFormFile"
> 
> Hence this change is not needed as same result can be achieved with command line options.
> Though perhaps documentation should be updated to include this as a example in some manner

Won't this just make all files as IFormFile?
I tried this option but it changes both uploads and downloads to IFormFile and I believe there is no way to send a IFormFile from .net backend to a frontend

**Comment by lindgrenfredrik** [comment]
Yes options make both upload and download be IFormFile
Code does that to, so there is no difference there.

If IFormFile is used as type in the SwaggerResponse/Produces Swagger UI reports correct schema type of string($binary)
While if type in SwaggerResponse/Produces is current Stream type return schema indicates:
System.IO.Stream{
canRead	boolean
readOnly: true
canSeek	boolean
readOnly: true
canTimeout	boolean
readOnly: true
canWrite	boolean
readOnly: true
length	integer($int64)
readOnly: true
position	integer($int64)
readTimeout	integer($int32)
writeTimeout	integer($int32)
}

Current template sets return value in Controllers to IActionResult so change between Stream and IFormFile only has impact on "documentation" part atm and as such doesn't limit from sending Valid return type to still allow download

Though if developers look at documentation in the generated code they will probably question the return value since  even if the return such a Type it fails.

So the correct solution would probably be to have different type listed for Results (i.e. FileResult as example given by SwashBuckle indicates https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/fefe65217c24a7194c0588a2d430a8952ed791b2/test/WebSites/Basic/Controllers/FilesController.cs) and update input parameter to be IFormFile instead since at least Kestrel setup of dotnet core can't handle file upload as Stream

**Comment by wing328** [comment]
> Though perhaps documentation should be updated to include this as a example in some manner

Agreed with you the documentation can be improved.

**Pull request closed without merging**
