### PR TITLE
[Typescript] Generate oneOf schemas as type unions

### PR DESCRIPTION
**Pull request by joscha**
#19027 + latest `master` + revert of #19481, see https://github.com/OpenAPITools/openapi-generator/pull/19027#issuecomment-2321328018

reverts #19481
closes #19027

### CODE REVIEW

**Review by macjohnny — APPROVED** [review]

**Comment by simon-abbott** [comment]
This change breaks `allOf` unions, they don't generate discriminator information at all.

**Comment by joscha** [comment]
@ksvirkou-hubspot would you mind having a look at https://github.com/OpenAPITools/openapi-generator/issues/19868 by any chance, please?

**Comment by joscha** [comment]
@simon-abbott can you produce a pull request with a fixture that shows the breakage or link me to some code showing what it should be vs. what it is right now? Maybe we can work together to try and solve this one?

**Comment by ksvirkou-hubspot** [comment]
> @ksvirkou-hubspot would you mind having a look at #19868 by any chance, please?

This issue occurs because the schema described doesn't include a discriminator. Without a discriminator, it's challenging to ascertain which object the API returns. I'm uncertain about the best course of action in this scenario. I could either throw an exception or return a JSON object. 
Currently, I'm reviewing other generators to understand their approach to this situation.
Do you have any idea?

**Comment by ksvirkou-hubspot** [comment]
@joscha  let's discuss it in [the issue](https://github.com/OpenAPITools/openapi-generator/issues/19868).

**Pull request merged**
