### PR TITLE
[Typescript-Angular] Fix: #10182

### LINKED ISSUE #10182: [BUG][TYPESCRIPT/ANGULAR] Using wrong keyword in generated AngularService (localVarHeaders instead of headers)
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

Since the use of Version 5.2.1 (last Version used before was 5.0.0) we encounter a issue with the generation of Angular Service code. 
According to this [https://github.com/OpenAPITools/openapi-generator/pull/10091](https://github.com/OpenAPITools/openapi-generator/pull/10091) variables have been renamed for the generation of the Angular - Services. 

Unfortunately on Line https://github.com/OpenAPITools/openapi-generator/commit/664aa2d946236ce327cf56256947baeb68f828e4#diff-7de15eed36eb15ed45aef205826063248eaddf2b11511db6a4bb2679c2aca851R361 there seemed to went something wrong. 
The property "headers" which is part of the HTTPClient Options has also been renamed instead of the value. 
This should stay headers. 

This will cause a compilation error in angular and won't work as header information is not submitted. 

So the code should be: 
``` 
{
    ...
    headers: localVarHeaders,
   ...
}
```

But unfortunately the code generated is:

``` 
{
      ...
      localVarHeaders: localVarHeaders,
      ...
}
```

##### openapi-generator version

I am using the `"@openapitools/openapi-generator-cli": "2.3.10"` with `version-manager 5.2.1`. 
Reverting to Version 5.0.0 in the version-manager works. 

##### OpenAPI declaration file content or url

You may use the example schema to regenerate the issue: https://petstore.swagger.io/v2/swagger.json.

##### Generation Details

Can be generated with the following line: 

`        openapi-generator-cli generate -i https://petstore.swagger.io/v2/swagger.json -g typescript-angular -o src/app/swagger --type-mappings=object=any --skip-validate-spec`

##### Steps to reproduce

0. Create an Angular App
1. Install openapi-cli. `https://www.npmjs.com/package/@openapitools/openapi-generator-cli`
2. Set version in openapitools.json to 5.2.1
Here is my example: 

```
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.2.1"
  }
}
```

3. Generate Services for angular as described above
`        openapi-generator-cli generate -i https://petstore.swagger.io/v2/swagger.json -g typescript-angular -o src/app/swagger --type-mappings=object=any --skip-validate-spec`
4. Use petService via Dependency Injection in app.component.ts

5. Try compiling. `npm run start`
The pet.service.ts will cause a compilation error because localVarHeaders is not a known key for the httpClient options.

##### Related issues/PRs

No related issue found yet. 

##### Suggest a fix

[https://github.com/OpenAPITools/openapi-generator/commit/664aa2d946236ce327cf56256947baeb68f828e4#diff-7de15eed36eb15ed45aef205826063248eaddf2b11511db6a4bb2679c2aca851R361](https://github.com/OpenAPITools/openapi-generator/commit/664aa2d946236ce327cf56256947baeb68f828e4#diff-7de15eed36eb15ed45aef205826063248eaddf2b11511db6a4bb2679c2aca851R361)
So the code should be: 
``` 
{
    ...
    headers: localVarHeaders,
   ...
}
```

But unfortunately the code generated is:

``` 
{
      ...
      localVarHeaders: localVarHeaders,
      ...
}
```

Thanks for any comment on this issue. 
Best regards
Schmitda

### PR DESCRIPTION
**Pull request by JohnTraDolta**
@amakhrov I can see you are a technical committee, correct me if i am wrong
As descriped in #10182 the refactoring in issue #10020 broke the outcome of the generated code. Here is a fix, as suggsted by @Schmitda.

fixes #10182

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by amakhrov** [comment]
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

**Comment by amakhrov** [comment]
PR that introduced the regression: https://github.com/OpenAPITools/openapi-generator/pull/10091

**Review by amakhrov — COMMENTED** [review]
Thanks @JohnTraDolta . The fix looks good.
But there are a lot of unrelated changes in the PR, which I believe should be reverted.


On a separate note, I'm wondering how come we missed the issue originally. I thought we have full tests for typescript-angular, that actually try to compile the generated code. Perhaps I was wrong

**Comment by macjohnny** [comment]
@amakhrov unfortunately the tests were disabled:
https://github.com/OpenAPITools/openapi-generator/pull/8023#event-4913436544

**Review by macjohnny — APPROVED** [review]
LGTM
Thanks for the fix!

**Pull request merged**
