### PR TITLE
[Go][client] Re-add deleted model template files

### PR DESCRIPTION
**Pull request by bkabrda**
This line was mistakenly omitted when moving go-experimental to go and now the go generator doesn't generate any models at all. This PR fixes that issue.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07)

### CODE REVIEW

**Comment by wing328** [comment]
@bkabrda thanks for the fix. I've restarted the failed CI job. Let's see how that goes.

I'll see what we can do to catch a similar issue moving forward.

**Comment by bkabrda** [comment]
@wing328 I think the easiest way to catch such an issue would be having an option to remove all the generated files in a `samples/` directory before running the generation. That way you'd see locally after regenerating samples that all model files are missing.

**Comment by wing328** [comment]
> I think the easiest way to catch such an issue would be having an option to remove all the generated files in a samples/ directory before running the generation

Thanks for the suggestion. We (core team) were actually having a discussion on similar options a few weeks ago.

**Comment by jirikuncar** [comment]
The problem with removing samples directory is that it includes hand written tests.

**Comment by bkabrda** [comment]
@jirikuncar that's where the `.openapi-generator/FILES` file should help, as it lists all the files generated on the last pass. The script for generating `samples/` could use that to remove generated files, but not tests.

**Pull request merged**
