### PR TITLE
[csharp] Mark optional fields in generated client properties as nullable

### LINKED ISSUE #4816: [BUG][C#] Should use nullable types for non-required properties
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The C# generators currently generate model classes using non-nullable types for properties which are not required, which can't represent instances where those properties are not present.

##### openapi-generator version

v4.0.0 and later

##### OpenAPI declaration file content or url

<details>
<summary>Example OpenAPI 3.0.2 document</summary>

```yaml
openapi: '3.0.2'
info:
  title: non-required property example
  version: '1.0.0'
components:
  schemas:
    DateRange:
      description: A possibly open-ended date range.
      type: object
      properties:
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
      required:
      - start
paths:
  /date-ranges:
    get:
      operationId: getDateRanges
      responses:
        default:
          description: Get date ranges
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DateRange'
    post:
      operationId: addDateRange
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DateRange'
      responses:
        '201':
          description: Success
```
</details>

Note that `end` is not declared `nullable: true` because `end` is never `null` in the JSON produced or consumed by the API.  It is either a date string, or not present.

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -g csharp-netcore -i openapi.yaml -o generated`

##### Steps to reproduce

1.  Ensure the API returns at least one open-ended range (i.e. a `DateRange` object without an `end` property).
2.  Call `GetDateRanges` and note that `End` for the open-ended range is `DateTime(1900-01-01)`, which is problematic since it is indistinguishable from `"end":"1900-01-01"` and likely violates the constraint that `End` is not before `Start`.
4.  Note that there is no way to call `AddDateRange` with an open-ended range, since `End` will always have a value.

##### Related issues/PRs

The regression occurred between v3.0.2 and v4.0.0.  Bisect says the first bad commit is 3744273312 (`v4.0.0`), so I'm obviously doing something wrong.  (Maybe `cli` is using published `core` of same version, rather than locally-built version?)  Advice on how to bisect would be appreciated.

The issue was also discussed in https://github.com/OpenAPITools/openapi-generator/issues/3725#issuecomment-545039145.

##### Suggest a fix

I believe nullable types should be used for properties which are either `nullable` or not `required`, since `null` in C# is a reasonable representation of both JSON properties which are `null` and properties which are not present.

Thanks for considering,
Kevin

### PR DESCRIPTION
**Pull request by ryanisaacg**
Resolves #4816

Mark all optional properties of in the generated C# client as nullable, with the `?`marker. For reference types, this enables C# 8's nullable reference types feature which is a nice bonus.

For value types, this fixes an issue with optional values. By default, an optional integer will be expressed as an `int` in C# with `EmitDefaultValue = false`. This means that a value of `0` is used to indicate the property is absent, which prevents actually indicating "set this value to 0". This PR emits an `int?`, which uses `null` to indicate absence. `0` can now be properly expressed.

This change seems like a breaking change, unless it's put behind some kind of generator flag. I'm perfectly happy to add a generator flag or try to retarget this PR to the `8.0.x` branch, whichever would be better.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mandrean @shibayan @Blackclaws @lucamazzanti @iBicha

### CODE REVIEW

**Comment by devhl-labs** [comment]
This is an improvement, so I don't object, but I think it is a work around. The better fix is to use wrap not required properties and parameters in a struct to track whether or not it was set ie  `var foo = new Optional<int?>();`  This allows you to explicitly set things to 0 and null. If the value was never set (as tracked by the Optional struct), then serializing should not add the property to the output. I already implemented this in generichost https://github.com/OpenAPITools/openapi-generator/pull/16810 but it is not a small change.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/18258 to set primitive types to nullable.

**Comment by ryanisaacg** [comment]
I'm no longer working on the project that prompted this PR and an alternative was merged, so I'll close it.

**Comment by wing328** [comment]
@ryanisaacg that's ok. Thanks again for the PR. All the best to your projects.

**Pull request closed without merging**
