### PR TITLE
[BUG] HandlebarsEngineAdapter.java failed to use custom FieldValueResolver causing IllegalAccessException for maps 

### PR DESCRIPTION
**Pull request by WouterBaeyens**
The old MY_FIELD_VALUE_RESOLVER.INSTANCE is equivalent to FieldValueResolver.INSTANCE, which is assigned `new FieldValueResolver();` so our custom class was never used.

This should improve https://github.com/OpenAPITools/openapi-generator/issues/510 somewhat, and finally properly applies the suggestion from https://github.com/jknack/handlebars.java/issues/940#issuecomment-1083817905

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@WouterBaeyens thanks for the PR

would it be possible to add a test or 2 in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/templating/HandlebarsEngineAdapterTest.java ?

**Comment by WouterBaeyens** [comment]
I added the test and did a little bit of clean-up as well.
- I have split off `AccessAwareFieldValueResolver` 
  - It keeps the format aligned with the usage of the INSTANCE singleton
  - It enables us in test-methods like `HandlebarsEngineAdapterTest` to test using the resolver actually active in the code.
- I re-ordered the `MethodValueResolver` to take priority. 
  - This is what was suggested by the maintainers of the handlebars repo
  - Map, JavaBean, Method, Value order makes more sense. i.e. getKey() > key() > key especially after the introduction of records is more logical over getKey() > key > key().

@wing328 let me know if you feel the tests are insufficient or further discussion is warranted. I realize I've slightly increased the scope of my change, but with increased understanding I've become pretty confident on the logical order of the resolvers.

**Comment by WouterBaeyens** [comment]
ping @wing328 
Are the changes too complex to review with limited time-resources? 
If you want I can revert the subsequent changes and create a follow-up mr for those. 
I would like to help make handlebars a viable alternative and fixing partial templates is I think a requirement to do this.

Maybe there are people specific to handlebars I could tag instead?

**Comment by wing328** [comment]
thanks for the PR. let's give it a try

**Pull request merged**
