### PR TITLE
fix #8755 [BUG] Java (jersey2) ApiClient debug cannot be enabled

### LINKED ISSUE #8755: [BUG] Java (jersey2) ApiClient debug cannot be enabled
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
 
The generated client code for java (using jersey) has a bug. You cannot enable debug for the client requests. When setting debug to true `setDebugging(true)` the setter has a side-effect of also recreating the httpClient by calling `buildHttpClient()`. The call to `buildHttpClient()` is desirable but the method contains an if block which prevents the call to `getDefaultClientConfig()` if it is already set favouring the existing config. 
``` java
// use the default client config if not yet initialized
if (clientConfig == null) {
    clientConfig = getDefaultClientConfig();
}
```
Unfortunately this skips enabling the debug settings which is set within the `getDefaultClientConfig()` method. 

I will prepare a PR which removes this check resulting in the creation of a new `clientConfig` on each call to `buildHttpClient()` which I believe is the intended outcome.

##### openapi-generator version

openapi-generator v5.0.0+

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

##### Generation Details

-g java
--additional-properties=library=jersey2

java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java --additional-properties=library=jersey2 -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o ~/tmp/java-client-test

##### Steps to reproduce

run the command above

##### Suggest a fix

I'm preparing a PR which will remove the check

```java
if (clientConfig == null) {
        clientConfig = getDefaultClientConfig();
}
```

### PR DESCRIPTION
**Pull request by tomred-net**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by tomred-net** [comment]
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)
--

Change to Java Jersey2 ApiClient mustache

**Comment by tomred-net** [comment]
Is this possible to be considered for `5.1.X` ? I cannot find a branch with that name so I have targetted `master`.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Current master is for the upcoming 5.1.0 release.

**Comment by wing328** [comment]
Please also run these to update the samples
```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```

so that the CI can test the change.

**Comment by tomred-net** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

resolved - author updated

**Comment by tomred-net** [comment]
> Please also run these to update the samples
> 
> ```
> ./mvnw clean package 
> ./bin/generate-samples.sh
> ./bin/utils/export_docs_generators.sh
> ```
> 
> so that the CI can test the change.

rebased with master and updated samples

**Comment by tomred-net** [comment]
> Current master is for the upcoming 5.1.0 release.

Thank you for your help

**Comment by wing328** [comment]
Sorry we missed it in the 5.1.0 release. We'll include it in the 5.1.1 release instead.

**Pull request merged**
