### PR TITLE
[typescript-axios] Fix model property naming

### PR DESCRIPTION
**Pull request by aiven-hh**
The property names in typescript-axios models were using formatted names instead of baseName and the template has no mapping to original baseName so this PR introduces a fix by:
* removing MODEL_PROPERTY_NAMING option from typescript-axios generator as this was never supported
* using baseName in model properties wrapped with `''` for now to support at least all characters except '

This should fix https://github.com/OpenAPITools/openapi-generator/issues/9524.

Also adds fake petstore example to be able verify these changes at least by eye, see `samples/client/petstore/typescript-axios/builds/test-petstore/api.ts` and `SpecialModelName` interface as an example.

In addition adds typing for options that was typed as any before.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by aiven-hh** [comment]
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

**Review by macjohnny — APPROVED** [review]
LGtM

**Comment by macjohnny** [comment]
@aiven-hh can you please resolve merge the latest master and re-generate the samples?

**Comment by aiven-hh** [comment]
Rebased, all major changes still in the first commit. New sample and `./mvnw clean package && ./bin/generate-samples.sh` changes in the second commit and `./mvnw clean package && ./bin/utils/export_docs_generators.sh` in the third commit.

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by macjohnny** [comment]
@aiven-hh thanks for your contribution. One minir thing: if the model property name contains a dot, it is still converted to underscore

**Comment by wing328** [comment]
Looks like this breaks the build:
```
Run `npm audit` for details.

> typescript-fetch-test@1.0.0 build
> tsc

../../builds/with-npm-version/api.ts(287,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(331,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(372,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(414,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(451,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(490,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(542,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(594,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(949,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(982,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1016,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1051,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1254,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1290,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1326,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1361,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1395,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1439,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1469,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
../../builds/with-npm-version/api.ts(1508,77): error TS2339: Property 'query' does not exist on type 'AxiosRequestConfig'.
npm ERR! code 2
npm ERR! path /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/typescript-axios/tests/default
npm ERR! command failed
npm ERR! command sh -c npm install ../../builds/with-npm-version && npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2021-10-02T06_31_56_428Z-debug.log
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (npm-install) on project TypeScriptAxiosPestoreClientTests: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (npm-install) on project TypeScriptAxiosPestoreClientTests: Command execution failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
```

Ref: https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds/238968898

Can you please take a look when you've time?

**Comment by aiven-hh** [comment]
@wing328 Hmm, the change exposed another bug in the original templates, the generated code uses options.query when axios does not actually use `query` for query params but `params`.

**Comment by aiven-hh** [comment]
@macjohnny are you sure? If you check the original example here: https://github.com/OpenAPITools/openapi-generator/blob/026dd8d5f883b5ca12ccab3145f631f9e3065109/modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml#L1797-L1803 and the generated sample https://github.com/OpenAPITools/openapi-generator/blob/026dd8d5f883b5ca12ccab3145f631f9e3065109/samples/client/petstore/typescript-axios/builds/test-petstore/api.ts#L1556-L1569 it looks fine to me.

**Comment by macjohnny** [comment]
@aiven-hh would you like to provide a fix? Or should we first revert the PR?

**Comment by aiven-hh** [comment]
Whatever you prefer, I can send the fix pr in a few minutes after I verify the fix.

**Comment by aiven-hh** [comment]
@macjohnny the fix is now in https://github.com/OpenAPITools/openapi-generator/pull/10512

**Pull request merged**
