### PR TITLE
Allow Java apache-httpclient users to supply additional HTTP headers per call

### PR DESCRIPTION
**Pull request by JigarJoshi**
https://github.com/OpenAPITools/openapi-generator/issues/11788

### CODE REVIEW

**Comment by JigarJoshi** [comment]
> @JigarJoshi thanks for the PR. For other Java clients, we use something called "defaultHeaders" in ApiClient.java:
> 
> https://github.com/OpenAPITools/openapi-generator/blob/60dcf8613f6b75b606757c4a991fe018ad10ee99/samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ApiClient.java#L51
> 
> https://github.com/OpenAPITools/openapi-generator/blob/955aadc2845381371c1f768328fc85e9eec2b047/samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java#L90



> @JigarJoshi thanks for the PR. For other Java clients, we use something called "defaultHeaders" in ApiClient.java:
> 
> https://github.com/OpenAPITools/openapi-generator/blob/60dcf8613f6b75b606757c4a991fe018ad10ee99/samples/client/petstore/java/vertx/src/main/java/org/openapitools/client/ApiClient.java#L51
> 
> https://github.com/OpenAPITools/openapi-generator/blob/955aadc2845381371c1f768328fc85e9eec2b047/samples/client/petstore/java/webclient/src/main/java/org/openapitools/client/ApiClient.java#L90

Thanks @wing328 - I have a requirement where I need to be able to pass header per API call differently. I am aware of defaultHeaders unfortunately that mechanism will not work for me.

**Comment by wing328** [comment]
I think you can do something like:

```java
ApiClient apiClient1 = new ApiClient();
apiClient1.setDefaultHeader(...);
PetApi petApi1 = new PetApi(apiClient1);
petApi1.doSomething();

ApiClient apiClient2 = new ApiClient();
apiClient2.setDefaultHeader(...);
PetApi petApi2 = new PetApi(apiClient2);
petApi2.doSomething();
```

It's less straightforward than your approach but I think it should meet your requirement.

**Comment by JigarJoshi** [comment]
> I think you can do something like:
> 
> ```java
> ApiClient apiClient1 = new ApiClient();
> apiClient1.setDefaultHeader(...);
> PetApi petApi1 = new PetApi(apiClient1);
> petApi1.doSomething();
> 
> ApiClient apiClient2 = new ApiClient();
> apiClient2.setDefaultHeader(...);
> PetApi petApi2 = new PetApi(apiClient2);
> petApi2.doSomething();
> ```
> 
> It's less straightforward than your approach but I think it should meet your requirement.

That will work and I believe I can share the underlying HttpClient instance, that will avoid the re-initialization of connection pool. I still think passing header as parameter is cleaner. 

What do you think?

**Comment by wing328** [comment]
I'm not against another way to pass headers to API calls. Just shared how we did it in other Java clients and tried to make things consistent.

Let's give your approach a try.

I'll tested locally with the updated samples and merge if no issue found.

**Comment by wing328** [comment]
I tested locally with the updated samples but got the following errors:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/UserApi.java:[62,26] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/UserApi.java:[132,41] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/UserApi.java:[202,40] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/UserApi.java:[272,26] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/UserApi.java:[498,26] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/UserApi.java:[563,26] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[69,29] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[411,38] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[482,39] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[645,38] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[778,34] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[867,35] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[960,46] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[1031,32] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/FakeApi.java:[1115,50] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/PetApi.java:[64,22] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/PetApi.java:[135,25] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/PetApi.java:[435,25] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/PetApi.java:[507,33] error: incompatible types: unexpected return value
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java/apache-httpclient/src/main/java/org/openapitools/client/api/StoreApi.java:[61,27] error: incompatible types: unexpected return value

```

Can you please take a look when you've time?

To update the samples, please follow step 3 in the PR checklist: https://github.com/OpenAPITools/openapi-generator/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by martin-mfg** [comment]
Hi @wing328, I adressed the problem you mentioned in #14929. Please have a look there.

**Comment by borsch** [comment]
closing this since similar change already merged in https://github.com/OpenAPITools/openapi-generator/pull/14929

**Pull request closed without merging**
