### PR TITLE
add OAuth2 to typescript template

### PR DESCRIPTION
**Pull request by ksvirkou-hubspot**
Fixes https://github.com/OpenAPITools/openapi-generator/issues/9465

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ksvirkou-hubspot** [comment]
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov

**Review by macjohnny — APPROVED** [review]
LGTM
This could be extended to accept a function as well, so the token is evaluated for each request, but this can be done in a separate PR

**Comment by ksvirkou-hubspot** [comment]
> LGTM
> This could be extended to accept a function as well, so the token is evaluated for each request, but this can be done in a separate PR

Sounds reasonable
 let's do that in next PRs

**Comment by ksvirkou-hubspot** [comment]
What is plan for merging ?
@macjohnny

**Comment by macjohnny** [comment]
Waiting for the build to succeed

**Review by TiFu — APPROVED** [review]
LGTM as well! Thank you for the PR!

**Comment by bodograumann** [comment]
Iinm, this duplicates the BasicBearer authentication.
Shouldn’t OAuth2 instead implement the authentication token flow and retrieve a token from the authentication server?
Feels like this is misunderstanding the semantics of the security definitions. :-/

**Pull request merged**
