### PR TITLE
[rust-server] Resolve clippy warnings

### PR DESCRIPTION
**Pull request by siketyan**
This pull request edits rust-server template to resolve all of clippy warnings I confirmed. At the latest master branch, clippy is failing because it is affected by `-Dwarnings` flags implied in .cargo/config that is also generated by rust-server variant themselves.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Would you please review this PR?
@frol @farcaller @richardwhiuk @paladinzh

### CODE REVIEW

**Comment by wing328** [comment]
cc @jacob-pro who has recently done some works on the Rust generators.

**Comment by wing328** [comment]
Rust clients, servers are tested in Travis: https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L1143

the commands for testing can be found in pom.xml in the sample folders. e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/rust/reqwest/petstore/pom.xml#L36

**Comment by siketyan** [comment]
So should I add executions of cargo clippy to the pom.xml of rust-server sample?

**Comment by wing328** [comment]
@siketyan yes please, we'll see how that goes.

**Comment by siketyan** [comment]
Added clippy execution to the integration-test chain, could you please take a look? @jacob-pro @wing328 

Actually .cargo/config under sub directories in workspace are not used at this time, so I copied one of them to the workspace root directory (samples/server/petstore/rust-server) to enforce cargo to use flags specified in the config.

Also I noticed the compilation of examples/server finishes with some 'unused-mut' warnings on macOS, so added `#[allow(unused_mut)]` to avoid that.

**Comment by wing328** [comment]
Travis CI tests: https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds/255780525

let's see how that goes.

**Comment by siketyan** [comment]
@wing328 ci/circleci: node0 only failed but it looks a temporary network issue. Could you please rerun the workflow?

**Comment by wing328** [comment]
for circle ci failure, we can ignore it as it's not related to this change.

travis ci tests passed.

let's give this PR a go.

**Comment by wing328** [comment]
I tested rust-server locally but got:
```
error: unknown lint: `clippy::derive_partial_eq_without_eq`
 --> output/multipart-v3/src/lib.rs:3:10
  |
3 | #![allow(clippy::derive_partial_eq_without_eq, clippy::blacklisted_name)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D unknown-lints` implied by `-D warnings`

error: unknown lint: `clippy::derive_partial_eq_without_eq`
 --> output/no-example-v3/src/lib.rs:3:10
  |
3 | #![allow(clippy::derive_partial_eq_without_eq, clippy::blacklisted_name)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D unknown-lints` implied by `-D warnings`

error: unknown lint: `clippy::derive_partial_eq_without_eq`
 --> output/ping-bearer-auth/src/lib.rs:3:10
  |
3 | #![allow(clippy::derive_partial_eq_without_eq, clippy::blacklisted_name)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D unknown-lints` implied by `-D warnings`

error: unknown lint: `clippy::derive_partial_eq_without_eq`
 --> output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs:3:10
  |
3 | #![allow(clippy::derive_partial_eq_without_eq, clippy::blacklisted_name)]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D unknown-lints` implied by `-D warnings`

error: could not compile `ping-bearer-auth` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `no-example-v3` due to previous error
error: could not compile `multipart-v3` due to previous error
error: could not compile `petstore-with-fake-endpoints-models-for-testing` due to previous error
```

Can you please take a look when you've time?

command: `mvn integration-test -f samples/server/petstore/rust-server/pom.xml`

**Comment by jacob-pro** [comment]
@wing328 According to https://rust-lang.github.io/rust-clippy/master/ it looks like `derive_partial_eq_without_eq` was only added in Rust 1.63.0.

When I tested this I got the same error as you, but after running `rustup update`, those errors have gone away (although I am now getting different errors such as `needless-borrow`)

One thing you might want to do at a project level is define a fixed MSRV (Minimum Supported Rust Version) which we use as the standard to test these by. Because otherwise what can happen is code is passing the tests, and then you run your build system at a later date and it is now failing, because new clippy lints have been added.

**Pull request merged**
