### PR TITLE
[cpp-qt5-client] Fix qt5.15 check

### PR DESCRIPTION
**Pull request by MartinDelille**
The Qt 5.15 check doesn't works: it checked again Qt 5.21.0 (my mistake by the way). This PR fix it.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@ravinikam @stkrwork @etherealjoy @muttleyxd

### CODE REVIEW

**Review by etherealjoy — APPROVED** [review]

**Comment by wing328** [comment]
```
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client/client_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fPIC -Wall -Wno-unused-variable -fPIC -Wall -Wno-unused-variable   -fPIC -std=c++14 -o CMakeFiles/client.dir/PFXCategory.cpp.o -c /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client/PFXCategory.cpp
[ 18%] Building CXX object client/CMakeFiles/client.dir/PFXHelpers.cpp.o
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client/client_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fPIC -Wall -Wno-unused-variable -fPIC -Wall -Wno-unused-variable   -fPIC -std=c++14 -o CMakeFiles/client.dir/PFXHelpers.cpp.o -c /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client/PFXHelpers.cpp
[ 22%] Building CXX object client/CMakeFiles/client.dir/PFXHttpFileElement.cpp.o
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client/client_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fPIC -Wall -Wno-unused-variable -fPIC -Wall -Wno-unused-variable   -fPIC -std=c++14 -o CMakeFiles/client.dir/PFXHttpFileElement.cpp.o -c /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client/PFXHttpFileElement.cpp
[ 27%] Building CXX object client/CMakeFiles/client.dir/PFXHttpRequest.cpp.o
cd /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client && /usr/bin/g++-5  -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client -I/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build/client/client_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork  -fPIC -Wall -Wno-unused-variable -fPIC -Wall -Wno-unused-variable   -fPIC -std=c++14 -o CMakeFiles/client.dir/PFXHttpRequest.cpp.o -c /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp
/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/client/PFXHttpRequest.cpp:62:29: error: missing binary operator before token "("
 #if QT_VERSION >= QT_VERSION(5, 15, 0)
                             ^
client/CMakeFiles/client.dir/build.make:117: recipe for target 'client/CMakeFiles/client.dir/PFXHttpRequest.cpp.o' failed
make[2]: Leaving directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build'
make[2]: *** [client/CMakeFiles/client.dir/PFXHttpRequest.cpp.o] Error 1
CMakeFiles/Makefile2:164: recipe for target 'client/CMakeFiles/client.dir/all' failed
make[1]: *** [client/CMakeFiles/client.dir/all] Error 2
make[1]: Leaving directory '/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/cpp-qt5/build'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (pet-test) on project CppQt5PetstoreClientTests: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (pet-test) on project CppQt5PetstoreClientTests: Command execution failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
```

The build failed with the above error message. Can you please take a look when you've time?

Ref: https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/759208641

**Comment by MartinDelille** [comment]
Fixed here: bf5778d

**Review by muttleyxd — APPROVED** [review]

**Comment by MartinDelille** [comment]
I don't know why the job failed: https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/759220550

**Comment by wing328** [comment]
CircleCI tests passed via https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/8894/workflows/ef3abdaf-4d0d-4744-8f69-fbec54bb2dfe/jobs/22478

**Pull request merged**
