### PR TITLE
[kotlin-spring] Support model objects and date-time query params

### LINKED ISSUE #8080: [BUG][KOTLIN-SPRING] When using models in query params, the RequestParam should not be generated
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

You can encapsulate multiple query parameters in models that are easier to handle on the code side.
Spring supports this by using a Bean (data class in kotline) as the parameter type and *leaving out* the `@RequestParam` annotation.

*kotlin-spring*-generator does generate the `@RequestParam` annotation also for models, resulting in an endpoint that does not work. If I modify the generated code and remove the annotation, everything works as expect. Note that the *spring*-generator correctly leaves the annotation out.

##### openapi-generator version

All versions, verified with latest master (033d985cf738) via docker

##### OpenAPI declaration file content or url

Example spec where parameters `parameterOne` and `parameterTwo` should be encapsulated in the `Filter` model:
```yaml
openapi: 3.0.0
info:
  version: '1'
  title: kotlin-spring openapi generator bug example
tags:
  - name: test
    description: test API
paths:
  /test:
    get:
      tags:
        - test
      summary: Endpoint should take both filter parameters in one model
      operationId: test
      parameters:
        - name: filter
          in: query
          description: filter parameters
          required: false
          schema:
            $ref: '#/components/schemas/Filter'
      responses:
        '200':
          description: successful operation
components:
  schemas:
    Filter:
      title: Filter parameters
      type: object
      properties:
        parameterOne:
          type: integer
          format: int64
        parameterTwo:
          type: string
```
##### Generation Details

I reproduced this with the example being in `/tmp/kotlin-spring-bug.yaml` and running the CLI via docker
```
docker run --rm -v /tmp/kotlin-spring-out:/out -v /tmp/kotlin-spring-bug.yaml:/tmp/apispec.yml openapitools/openapi-generator-cli:latest generate -g kotlin-spring -i /tmp/apispec.yml -o /out
```

##### Actual output

The file `/tmp/kotlin-spring-out/src/main/kotlin/org/openapitools/api/TestApi.kt` contains this code:

```kotlin
    fun test( @RequestParam(value = "filter", required = false) filter: Filter?): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
```

which doesn't correctly map the parameters `parameterOne` and `parameterTwo`, but will always be called with `filter` being `null`.

##### Expected output
An endpoint without the `@RequestParam` annotation, simply:

```kotlin
    fun test(filter: Filter): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
```
Spring will correctly create an instance of `Filter` with `parameterOne` and `parameterTwo` being mapped.

##### Suggest a fix
Leave out the `@RequestParam` annotation when generating the endpoint for query params being models.
The *spring*-generator handles models as query params correctly.

### PR DESCRIPTION
**Pull request by sburnicki**
These commits add support for two things:
 * fix #8080 by only generating `@RequestParam` annotation, if the query param is not a model.
 * add support for parsing date and date-time parameters (corresponds to #2053 in java/spring, applies also for kotlin/spring)

I added test cases adopted from the java spring codegen, which had the same issues (see linked issues and PRs in #8080) and tested the changes locally.

#### Tests for model object params
Generate code based on one of the existing examples before the PR:
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g kotlin-spring \
  -i modules/openapi-generator/src/test/resources/3_0/objectQueryParam.yaml \
  -o /tmp/openapi/8080/ \
  --skip-validate-spec
```
and make `/tmp/openapi/8080/src/main/kotlin/org/openapitools/api/PonyApi.kt` return the following:
```
return ResponseEntity(pageQuery, HttpStatus.OK)
```
also modify the return type and test to compile. After running `mvn spring-boot:run`, you can query via curl:
```
curl -X GET \
  'http://localhost:8080/pony?offset=1&limit=2' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache'
```
which won't return anything, as `pageQuery` is `null`.

After this PR, run the same steps again. Executing the curl command will correctly return `{"offset":1,"limit":2}`, since 
spring was able to parse the parameters as a valid `pageQuery` object.

#### Steps for date-time params
Same procedure as above:
Generate code for `src/test/resources/3_0/issue_2053.yaml`:
```sh
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g kotlin-spring \             
  -i modules/openapi-generator/src/test/resources/3_0/issue_2053.yaml \
  -o /tmp/openapi/datetime/ \
  --skip-validate-spec
```
Test with curl:
```sh
curl -vX GET \
  'http://localhost:8080/elephants?startDate=2020-12-22' \               
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache

curl -vX GET \
  'http://localhost:8080/zebras?startDateTime=2020-12-22T08:00:12.345Z' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache'
```
Both requests fail with HTTP 400, since Spring cannot parse the parameters.

After the PR, repeat the same steps, both requests will return HTTP 501 (not implemented) and not fail anymore.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Please review:
@jimschubert (2017/09), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

### CODE REVIEW

**Comment by sburnicki** [comment]
I added another commit that adds date/date-time support to this PR, as opening a separate PR would immediately result in a merge conflict, since both commits modify the one-line file `modules/openapi-generator/src/main/resources/kotlin-spring/queryParams.mustache`

**Comment by sburnicki** [comment]
I re-pushed the commits since circleci failed to download dependencies last time.
Can in the meantime somebody give feedback on the contents of the PR?

**Comment by wing328** [comment]
I'll try to test it out later this week. Thanks for the PR.

**Comment by sburnicki** [comment]
Thanks. The labels do not make sense in my opinion, as it neither adds a new generator, nor is it related to ktorm?

**Comment by wing328** [comment]
Fixed the label.

**Comment by sburnicki** [comment]
Any news on this?

**Comment by wing328** [comment]
@sburnicki sorry we're busy with v5.1.0 release (which was published recently).

Can you please resolve the merge conflicts and PM me via Slack when this PR is ready for another review? Thanks.

ref: https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by MaksimMyshkin** [comment]
When this fix will be merged? We had to use java version of spring generator to get around of this bug(( Using kotlin generator is preferable as produced dto's has nullable/notnullable types. Maybe you need some help?

**Comment by sburnicki** [comment]
I also used workarounds since this wasn't merged and then forgot about this PR. I didn't notice the update from wing328 to be honest.

I'm quite busy at the moment and have no idea when I will be able to pick up the work.
@MaksimMyshkin If you have some time, feel free to resolve the merge conflicts to get this merged. Tests should be in place.

**Comment by MaksimMyshkin** [comment]
How can I fix conflict in foreign fork? Only option that I see is to make new fork, move all changes there and crate new PR)

**Comment by sburnicki** [comment]
I gave you access to my fork, it's not used for anything else anyway.

**Comment by MaksimMyshkin** [comment]
Done 😉

**Comment by sburnicki** [comment]
@wing328 This seems to be ready then :)

**Comment by wing328** [comment]
I'll try to review and test tomorrow. Thanks again for the PR.

**Comment by zipper2110** [comment]
@wing328 how is it going then? The build doesn't seem to work for reasons not related to the PR itself. Would be happy to see this merged.

**Comment by wing328** [comment]
Tested locally and didn't spot issues related to this change. Found an issue with the auto-generated test file thought. Will file a PR to fix it separately.

Thanks again for the PR and sorry for the delay in reviewing.

**Pull request merged**
