### PR TITLE
[Java][Spring][1975] Add OAuth2 Preauthorize annotations based on scope

### LINKED ISSUE #1975: [REQ] Spring Server generators should allow for adding OAuth2 Preauthorize annotations based on scope
Using OAuth JWT scopes and Spring Security's PreAuthorize annotation requires the PreAuthorize annotation to be on the same method as the Mapping related annotation.

With the current generators (Java/Kotlin), the Mapping annotation is in generated code, so manually adding the PreAuthorize annotation can't be done without modifying generated code.

It would be good if the generator had a flag for Spring Security, and would then leverage the OAuth2 security settings to add @PreAuthorize() annotations to the Controller class methods with the Mapping related annotations.

This is dependent on #392 being corrected first.

### PR DESCRIPTION
**Pull request by ersinciftci**
Fixes #1975 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by ersinciftci** [comment]
@wing328 @cbornet I tried to make the PreAuthorize import conditional but failed, any help would be appreciated.

**Comment by cbornet** [comment]
I think this doesn't work if there's multiple securities defined for an operation (eg. Oauth + basic).

**Comment by ersinciftci** [comment]
@cbornet I just tested with an OpenAPI spec that has both OAuth2 and Basic, and seems to be working, because it has `{{#isOAuth}}` so I think the extra Basic security item doesn't affect it. But I can't figure out for what use case the tests are failing.

**Comment by cbornet** [comment]
What I mean is that an endpoint that has both basic and oauth should be accessible by basic OR oauth. Here I think if you try to access by basic auth, the pre-authorization will fail and you will be rejected.

**Comment by wing328** [comment]
> I think this doesn't work if there's multiple securities defined for an operation (eg. Oauth + basic).

@cbornet good catch. I think such a case rarely occurs (based on my experience dealing with issues reported to this repo). We can document it as a known issue for the time being and work on it when there's a demand to fix it.

**Comment by Walliee** [comment]
I just stumbled here trying to find `@PreAuthorize` support in OpenAPI Generator. 
I am looking to avoid custom templates in our project and I think this feature would get us there. 
 
Anything I can do to help?

**Comment by ersinciftci** [comment]
Hi @Walliee , sorry I didn't have much time recently, your help would be greatly appreciated. 

Firstly, not sure if the tests are failing because of the use case @cbornet mentioned, so that's pending some investigation (though @wing328 mentioned that we can ignore that use case for now, we still need to fix the tests). 

One other thing is this change would fail for people that don't use Spring Security because it imports a class from there, so maybe this should be a configuration that people can turn on (like addPreAuthorize = true).

Thanks

**Comment by Walliee** [comment]
Yes; of course. The pointers you gave make sense. Thanks!

@nhomble and I looked at this briefly today and looks like we can handle bearer auth too. We’ll hopefully have a PR out tomorrow.

**Comment by nhomble** [comment]
Awesome stuff @ersinciftci, we are still polishing a little bit (and I need to regen the samples), but here is a [sneak peak](https://github.com/nhomble/openapi-generator/tree/gh-1975)

**Comment by ersinciftci** [comment]
@nhomble looks great! `useSpringSecurity` sounds much better than `addPreAuthorize` :)

**Comment by ersinciftci** [comment]
@nhomble looks much better than this one, thanks! (I'm closing this one)

**Pull request closed without merging**
