### PR TITLE
Avoid generating uncompilable response body in Spring's API template

### LINKED ISSUE #2186: [BUG][Java][Spring] error: constant string too long
With a large enough data model the Java-Spring server generator produces example responses with a string that is too long for the Java compiler.
It's not exceeding the size of a string allowed by the JVM, but the size of a string constant the compiler handles.

```java
 default ResponseEntity<ResponseObject> restMethod(@ApiParam(value = "A Parameter",required=true) @PathVariable("parameter") String parameter) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{ [A large example json string response that breaks the Java compiler] }");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
```

Was generated using openapi-generator-maven-plugin 3.3.4.
Settings:
```xml
<configOptions>
	<sourceFolder>${generated-sources-java-path}</sourceFolder>
	<interfaceOnly>true</interfaceOnly>
	<java8>true</java8>
	<dateLibrary>java8</dateLibrary>
	<useBeanValidation>true</useBeanValidation>
	<performBeanValidation>true</performBeanValidation>
</configOptions>
<generatorName>spring</generatorName>
```

Potentially similar to the swagger codegen issue: https://github.com/swagger-api/swagger-codegen/issues/9055

Is an example response needed?
Failing that: Could it be broken into a StringBuilder (or at worst just string concatenation)? Or maybe loaded from a resource file?

### PR DESCRIPTION
**Pull request by smasset**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

If definitions start to get complicated, example response bodies can exceed Java compiler's limit for constant strings.

This PR addresses this issue by introducing and using two new lambdas to remove any unnecessary whitespace and (if still needed) to split the constant string into smaller compilable parts using a StringBuilder to merge them back again.

Fixes #2186

### CODE REVIEW

**Comment by smasset** [comment]
CCing Java technical committee for review : @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog

**Comment by smasset** [comment]
Just pushed updated samples

**Comment by smasset** [comment]
@wing328, as discussed, here's the PR porting swagger-api/swagger-codegen#8691 to openapi-generator

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

**Comment by smasset** [comment]
Is there anything missing in the PR ?
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) cc @wing328

**Comment by wing328** [comment]
@smasset thanks for the PR and my apologies for taking so long to review this change.

Let's go with this enhancement in the upcoming release.

**Comment by smasset** [comment]
Great news.
@wing328, although the code definitely is tagged as part of 4.2.1 release, it doesn't appear in the release notes. I think the PR is missing the 4.2.1 milestone.

**Comment by wing328** [comment]
@smasset thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Pull request merged**
