### PR TITLE
[dart] Cleanup and OAS3 support

### PR DESCRIPTION
**Pull request by kuhnroyal**
* cleanup old docs across all dart generators
* regenerate all tests
* cleanup .gitignore
* minor formatting improvements in dart-dio
* unified integration-test layout for dart/dart-dio generators
* add generation and integration-tests for OAS3 petstore to dart/dart-dio
* add generation and integration-tests for OAS3 petstore-with-fake-api to dart/dart-dio

**Explicitly not adding the new integration tests for petstore-with-fake-api to the master POM. They do not work but having them allows for quickly iterating on open issues without breaking existing basic OAS2/OAS3 petstore examples. Instead they should be run manually until everything is fixed.**

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

**TODO:**
- [x] Verify new inline objects are correct, they seem to be unused
- [x] Fix compile errors in dart regarding File/MultipartFile
- [x] Fix tests for POST/PUT operations that now return `200` with content

### CODE REVIEW

**Comment by kuhnroyal** [comment]
The new inline objects in OAS3 are caused by the PetAPI update with FormData operations.

**Comment by kuhnroyal** [comment]
Don't think we can generate a useful `fromJson` function for these inline objects that contain a `MultipartFile` property.
Best would be to somehow skip these inline request body models from being generated in the first place.

**Comment by kuhnroyal** [comment]
CC @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12)

**Comment by kuhnroyal** [comment]
@wing328 This should be ready, CircleCI seems to have failed with some sort of timeout, maybe you can restart the step.

**Comment by kuhnroyal** [comment]
Not clear whats happening in CircleCI, seems to be related to some scala artifacts.

**Comment by wing328** [comment]
> The new inline objects in OAS3 are caused by the PetAPI update with FormData operations. The same models are generated for java/kotlin etc. and are also unused. Why?

These models are generated due to how form parameters are defined in OAS3. Usually these are not used.

We'll revise accordingly given that it causes confusion to users.

```
[main] INFO  o.o.codegen.DefaultGenerator - Model inline_object (marked as unused due to form parameters) is generated due to the system property skipFormModel=false (default)
```

One way to prevent these from being generate is to set the `skipFormModel` option.

**Pull request merged**
