### PR TITLE
[PYTHON] generate code based on pydantic v2

### PR DESCRIPTION
**Pull request by fa0311**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Review by multani — APPROVED** [review]
Running the tests in `samples/openapi3/client/petstore/python-aiohttp` goes from:

```
148 passed, 2 skipped, 2100 warnings
```

to:

```
148 passed, 2 skipped, 60 warnings
```

and I don't see any Pydantic v2 warnings anymore :clap:

**Comment by wing328** [comment]
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @krjakbrjak (2023/02)

**Comment by wing328** [comment]
tested locally and all those pydantic warnings are gone 👍

**Comment by jakubno** [comment]
It's caused by
```python
    __properties = ["sessionID"]

    @classmethod
    def from_dict(cls, obj: dict) -> Session:
        """Create an instance of Session from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Session.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError(
                    "Error due to additional fields (not defined in Session) in the input: "
                    + obj
                )

        _obj = Session.model_validate(
            {
                "sessionID": obj.get("sessionID"),
            }
        )
        return _obj
```

It worked in https://github.com/OpenAPITools/openapi-generator/pull/16655

**Comment by multani** [comment]
> I am receiving ` TypeError: argument of type 'ModelPrivateAttr' is not iterable`
> 
> It's caused by
> 
> ```python
>         # raise errors for additional fields in the input
>         for _key in obj.keys():
> >           if _key not in cls.__properties:
> E           TypeError: argument of type 'ModelPrivateAttr' is not iterable
> ```

@jakubno do you have an OpenAPI example where this happens?

This was changed in https://github.com/OpenAPITools/openapi-generator/pull/16624 but I think we missed a branch that was not covered by the tests.

**Comment by jakubno** [comment]
I will create minimal example and create issue

**Comment by multani** [comment]
Yep, that's what I did in the branch that was covered by the tests :+1:

**Comment by fa0311** [comment]
If you test this, you need to set the `disallowAdditionalPropertiesIfNotPresent` to true.
https://github.com/fa0311/openapi-generator/blob/e2f249ba35e2da2f9936efaf5434068238cfc68c/bin/configs/python.yaml#L8

**Comment by wing328** [comment]
NOTE: for users who still prefer using pydantic v1 in v7.1.0 release, they can use the `python-pydantic-v1` client generator.

**Pull request merged**
