### PR TITLE
Introduce changes necessary for Dart 3.0.0/Flutter 3.10.0

### PR DESCRIPTION
**Pull request by noordawod**
Recent versions of the Dart SDK have tightened the rules for which objects can be sent across isolates (see https://api.dart.dev/stable/3.0.0/dart-isolate/SendPort/send.html and https://github.com/dart-lang/sdk/commit/67683c39).

Bottom line: It's not possible to send an arbitrary class instance across isolates anymore, this may cause a crash when `deserializeAsync` is called from an isolate different from the isolate used to call the API operation: https://github.com/flutter/flutter/issues/126520

This pr introduces the following changes:

1. Add a new function `decodeAsync` to decode a JSON, suitable to be called from an isolate.
2. Expose `ApiClient._deserialize` (as `ApiClient.fromJson`) so that users can call it after decoding the JSON on an isolate.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh bin/configs/dart-*
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

### CODE REVIEW

**Comment by ahmednfwela** [comment]
Can this wait until https://github.com/OpenAPITools/openapi-generator/pull/14346 and https://github.com/OpenAPITools/openapi-generator/pull/15485 land ?

**Comment by noordawod** [comment]
For sure, @ahmednfwela. Got an eta?

**Comment by ahmednfwela** [comment]
it's currently blocked by https://github.com/OpenAPITools/openapi-generator/issues/10189 waiting for a fix soon

**Comment by konnic** [comment]
@noordawod thanks for opening the PR! 

After upgrading to Flutter 3.10.1 I discovered that I'm blocked by the dart2 generator, because my generated Dart API client pub depends on `intl: "^0.17.0"`, while the Flutter SDK now depends on `intl: "^0.18.0"`. So if I'm not mistaken this should be adjusted in the `pubspec.mustache:19` file? 

This was also reported in this issue: https://github.com/OpenAPITools/openapi-generator/pull/15510

When running `flutter pub get` this is my output:
````
Resolving dependencies...
Because myapp depends on core_api from path which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because myapp depends on intl ^0.18.0, version solving failed.
exit code 1
````

**Comment by noordawod** [comment]
> @noordawod thanks for opening the PR!
> 
> After upgrading to Flutter 3.10.1 I discovered that I'm blocked by the dart2 generator, because my generated Dart API client pub depends on `intl: "^0.17.0"`, while the Flutter SDK now depends on `intl: "0.18.0"`. So if I'm not mistaken this should be adjusted in the `pubspec.mustache:19` file?
> 
> This was also reported in this issue: #15510
> 
> When running `flutter pub get` this is my output:
> 
> ```
> Resolving dependencies...
> Because myapp depends on core_api from path which depends on intl ^0.17.0, intl ^0.17.0 is required.
> So, because myapp depends on intl ^0.18.0, version solving failed.
> exit code 1
> ```

You could override the dependency and enforce a specific version, I do it:

```yaml
dependency_overrides:
  intl: "^0.18.0"
```

**Comment by noordawod** [comment]
> Can this wait until #14346 and #15485 land ?
> 
> because after these 2 PRs we will have an infrastructure to test this code similar to this https://github.com/OpenAPITools/openapi-generator/tree/master/samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests

What do you think about doing it the other way around? Merging this first and then the other 2 pr's? Seems to me that the latter two might take a while...

**Comment by ahmednfwela** [comment]
yes we can do that but,can you create a separate issue to track the needed tests?

**Comment by noordawod** [comment]
> yes we can do that but,can you create a separate issue to track the needed tests?

I need help with that :| I never wrote tests… Would you like to help?

**Comment by ahmednfwela** [comment]
it's ok after the new PR I will write the tests

**Comment by noordawod** [comment]
Bump :)

**Pull request merged**
