### PR TITLE
Replace Gradle Enterprise references with Develocity

### PR DESCRIPTION
**Pull request by jprinet**
Replace Gradle Enterprise references with Develocity

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by jprinet** [comment]
cc @wing328

**Comment by martin-mfg** [comment]
Hi @jprinet,
since this PR was merged the [Travis builds](https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds) are failing.
This seems to be the relevant error:
```
[ERROR] Extension com.gradle:common-custom-user-data-maven-extension:2.0 or one of its dependencies could not be resolved: Could not find artifact com.gradle:common-custom-user-data-maven-extension:jar:2.0 in google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/)
```
Do you have an idea why this happens?

**Comment by wing328** [comment]
ran out of travis free credits, i'll request more. thanks for pointing it out

**Comment by wing328** [comment]
@jprinet @martin-mfg about the travis build errors, I've merged to revert the extension version back to 1.x for the time being (and travis ci build passed) before we've time to look into the issue and come up with a fix

**Comment by jprinet** [comment]
Interesting, I'll take a look

**Comment by jprinet** [comment]
My understanding is that the Google mirror does not have the dependency:
https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds/271877075#L609

Not sure how your repositories are configured on Travis but my guess is that Maven Central is not defined as the dependency can be found in there:
https://mvnrepository.com/artifact/com.gradle/common-custom-user-data-maven-extension/2.0

Can you confirm my assumption? If yes I see 2 options for the resolution:
- Have Google repo fetching the artifact
- Configure Maven central as a source repo in Travis

**Comment by wing328** [comment]
looks like this is a similar issue: https://github.com/checkstyle/checkstyle/issues/7444

and it contains a PR with a fix

**Comment by jprinet** [comment]
Makes sense, although this artifact was published a while ago.
Will you then switch to the Maven central repo?

**Comment by wing328** [comment]
> Have Google repo fetching the artifact

that's one way to do it but I've no idea how

**Comment by jprinet** [comment]
me neither

**Comment by wing328** [comment]
i'll give it a try with the fix mentioned in https://github.com/checkstyle/checkstyle/issues/7444 this weekend (or next)

**Pull request merged**
