### PR TITLE
spring api.mustache: fix unhandledException

### LINKED ISSUE #6182: [BUG][Java][Spring] Unhandled exception ignored
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The option to add unhandledException is ignored when skipDefaultInterface is set to true. This behaviour is obvious by inspecting line 132 of the [api.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/api.mustache).

##### openapi-generator version
4.3.0

##### Steps to reproduce

1. Generate Spring server code from any specification with unhandledException=true. Observe how the default interface methods have 'throws Exception' declared.
2. Generate Spring server code from any specification with unhandledException=true and skipDefaultInterface=true. Observe how the interface methods don't have 'throws Exception' declared.

##### Related issues/PRs

The PR that added the option. https://github.com/OpenAPITools/openapi-generator/pull/2482

##### Suggest a fix

I suggest moving the parameter outside of the skipDefaultInterface block so that the 2 options are independent. @jimschubert mentioned on Slack that this could affect people that unknowingly have unhandledException set to true, and skipDefaultInterface set to true also, which is correct to some extent, but having an exception thrown in the interface does not force the implementation to throw it too, so the change is definitely backwards compatible.

### PR DESCRIPTION
**Pull request by NaridaL**
Fixes #6182

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by NaridaL** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

That's fine. 

I ran 

```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```

but that touches > 40 files, mostly just changing "/" to "\", so that doesn't seem like a sensible commit. Do we need any other changes?

**Comment by NaridaL** [comment]
@wing328 Can this be merged?

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/11580

**Pull request closed without merging**
