### PR TITLE
fix removing dollar sign for name sanitization

### PR DESCRIPTION
**Pull request by Joshix-1**
String#replaceAll uses RegEx. In RegEx the $ matches the end.
So `name.replaceAll("$", "");` doesn't remove the dollar sign instead it does nothing.
The correct way to do it would be to use `String#replace` which doesn't treat the first argument as RegEx.

### CODE REVIEW

**Comment by wing328** [comment]
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

cc @spacether

**Comment by Joshix-1** [comment]
@spacether where should I add these tests?

**Comment by spacether** [comment]
How about adding them in:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonNextgenClientCodegenTest.java
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/php/PhpClientCodegenTest.java
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/protobuf/ProtobufSchemaCodegenTest.java
And in Java test of any other generators that you update. I think I have covered your current ones.

**Comment by wing328** [comment]
merged via https://github.com/OpenAPITools/openapi-generator/pull/16301

**Comment by wing328** [comment]
FYI. we added the name mapping feature to many generators and you may find it useful in your use cases: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#name-mapping

**Pull request closed without merging**
