### PR TITLE
Fix generation of default array values for kotlin client

### PR DESCRIPTION
**Pull request by Rattenkrieg**
Additional fixes for #10865 

Currently, a request containing default value for an array would break kotlin generation yielding `java.lang.ClassCastException`
> java.lang.String cannot be cast to com.fasterxml.jackson.databind.node.ArrayNode

The problem lies in swagger dependency that doesn't handle default values for arrays as java arrays rather passing it as string like `["value1"]`. [This](https://github.com/swagger-api/swagger-parser/blob/v2.0.31/modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java#L796) is the line that feeds string value to our `schema`. Simple spec below works fine reproducing the issue.
In this PR I decided to skip such string values as I don't see jackson parser being wired in `AbstractKotlinCodegen`, however if maintainers decide that parsing such strings is really something nice to have, I could hack on this PR further.

```yaml
  /foo/bar:
    post:
      operationId: UpdateBar
      consumes:
        - multipart/form-data
      parameters:
        - name: values
          in: formData
          required: false
          type: array
          items:
            type: string
            enum:
              - value1
              - value2
          default:
            - value1
    responses:
        "200":
          description: "Success."
```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

### CODE REVIEW

**Comment by wing328** [comment]
can you please follow step 3 to update the samples so that the CI can test the change?

https://github.com/OpenAPITools/openapi-generator/runs/7978226559?check_suite_focus=true

**Comment by Rattenkrieg** [comment]
@wing328 thanks for pointing out, I'm pretty sure I did it before but somehow it ended being committed without `ByteArrayAdapter.kt`. Should work now.

**Comment by Rattenkrieg** [comment]
Some [weird code](https://github.com/OpenAPITools/openapi-generator/pull/13243/files#diff-fefa4acce967b421891ef5e4bf2ad6924258cd96bad905823ca39ece2ad099f7R206) was generated for okhttp 3 and 4. Looking into it.

**Comment by Rattenkrieg** [comment]
It appears there is a [_bug_](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache#L192) in okhttp templates or some upstream code: `".value"` is being added after `paramName` when `isEnum` set to true. This happens even if type of `paramName` being collection containing enum values. So I guess there has to be some combination of `isEnum` and `isContainer` conditionals. I'm not that proficient in mustache templating so I guess better I could do is to open a dedicated issue. For sake of this PR I've changed values in api spec from list of enums to list of strings.

**Review by 4brunu — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
