### PR TITLE
[suggestion] Gradle plugin input file instead of input string

### PR DESCRIPTION
**Pull request by stefankoppier**
Suggestion: deprecate inputSpec and replace it with inputFile. The difference is that inputFile is of type File instead of String. File plays more nicely with Gradle built-ins, like rootDir and layout. 

This reduces the need for some complexity in some cases, e.g. `layout.buildDirectory.file("spec.yaml").map { it.asFile.absolutePath }` to `layout.buildDirectory.file("spec.yaml")` while staying relatively simple for existing String paths `x` by wrapping the string in the built-in `file(x)`.

Currently just a draft PR, as it is not complete: tests and documentation is missing. Merely for discussion purpose atm.

Resolves https://github.com/OpenAPITools/openapi-generator/issues/17380, although I personally wouldn't consider it a bug.

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by stefankoppier** [comment]
@wing328 when you have the time, could you give this a look and give your opinion?

**Comment by wing328** [comment]
the input can be a URL, right?

**Comment by wing328** [comment]
also maven plugin uses the same name and we want to make it consistent across plugins (maven, sbt, etc) if possible

**Comment by stefankoppier** [comment]
> the input can be a URL, right?

It could, but it has similar issues as string. You would need to map the Gradle methods to a URL, instead of a String. Why do you ask? :)

**Comment by stefankoppier** [comment]
> also maven plugin uses the same name and we want to make it consistent across plugins (maven, sbt, etc) if possible

I agree. If you support the general idea of the PR, I will include that in the final PR.

**Comment by wing328** [comment]
> deprecate inputSpec and replace it with inputFile.

because the new name `inputFile` kinda suggests it only works with file only 

instead of deprecating inputSpec, what about adding another option "inputFile" instead?

if later most people prefer inputFile, we can then mark inputSpec as deprecated.

**Pull request closed without merging**
