### PR TITLE
Add isEnumRef, isEnumOrRef to CodegenProperty

### PR DESCRIPTION
**Pull request by wing328**
To address the bug that `isEnum` is not set properly when the enum is a reference (instead of an inline schema) in a codegen property, I've added `isEnumRef` and also `isEnumOrRef` mustache tags to provide a migration path to address the issue.

Why not simply just fix it like https://github.com/OpenAPITools/openapi-generator/pull/9526? We appreciate the fix but the problem is that it impacts lots of generators and some output won't even compile/work any more: https://gist.github.com/wing328/d8ef17e0b884ea821f2c7a1218ab368f

`isEnumRef` is set to true if the it's a $ref and the $ref is an enum.
`isEnumOrRef` is set to true if `isEnumRef` or `isEnum` is set to true

I've updated `r` templates to use `isEnumOrRef` and there's no change in the output.

I've updated `powershell` templates to use `isEnumOrRef`, which results in a fix.  

Some tests in this PR comes from  https://github.com/OpenAPITools/openapi-generator/pull/13389 (credit @rivancic)

After this PR is merged, users can update the template and/or generator accordingly to ensure the output works using `isEnumOrRef` or `isEnumRef` and of course we welcome PRs to apply these fix upstream in this official repo.

Related PRs/issues:
- https://github.com/OpenAPITools/openapi-generator/pull/9526
- https://github.com/OpenAPITools/openapi-generator/issues/5676
- https://github.com/OpenAPITools/openapi-generator/pull/13389
- https://github.com/LukeMarlin/openapi-generator/pull/1

cc @aymanbagabas @questionableque @snowe2010 @oszust002 @rivancic @flowstef  @LukeMarlin 
 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @OpenAPITools/generator-core-team

### CODE REVIEW

**Review by 4brunu — APPROVED** [review]
Looks good to me, and I think it's a good solution that doesn't break all the generators 👍

**Comment by devhl-labs** [comment]
Consider finding all isEnum and replace with something like isEnum_Deprecated then properly fix isEnum. This would make it obvious to mustache authors there is something wrong with the enum property they are using.

**Comment by wing328** [comment]
@devhl-labs to be clear, `isEnum` will not be deprecated as there are generators that need a way to tell if the enum is defined inline.

**Comment by devhl-labs** [comment]
I'm not suggesting you deprecate isEnum.

> To address the bug that isEnum is not set properly when the enum is a reference 

This says that the current _implementation_ is bugged, so deprecate that bugged version. Then make 'new' isEnum (which can still be called isEnum since the bugged version was renamed) which is fixed. Also, there is isInnerEnum which is true for inline enums.

The benefit here is that templates using the bugged version will be very obvious, plus isEnum can be true for all enums as you would expect.

**Comment by snowe2010** [comment]
From a software engineering perspective I agree with @devhl-labs. Do it right, now, or you'll be stuck with some decision that might not be best for the codebase, will result in confusion among contributors, will result in tech debt, and doesn't really solve the underlying issue.

From a consumer perspective. I don't care which as long as it gets fixed 😂

**Comment by wing328** [comment]
Thanks for all the feedback.

We definitely want to fix the issue and there were already several attempts (PRs) from the community before to fix it but no one has the time to fix all the generators (at least 10+) impacted by the fix. 

We can leave this PR opened and ask the community to fix the generator one by one but this will result in a lot of overhead (e.g. rebase) and it will become a giant PR that is hard to review and work on so I would rather update the default codegen with `isEnumRef`, `isEnumOrRef` and let the community of each generator to update the templates accordingly.

**Comment by devhl-labs** [comment]
I dont understand your concern. The current bugged isEnum can remain in the
code exactly as it is today in master, just under a different name. That
can be done with a search and replace to change the name. Then add back
isEnum that works correctly.

The proposed solution here leaves isEnum in a bugged state (and not obvious
that it is bugged) and adds seemingly unecessary enum properties. isEnum
and isInnerEnum should be all that is needed (plus isEnum_Deprecated for
the current bugged implementation of isEnum).

But I've made my point so I'll leave you to it here.

**Comment by aymanbagabas** [comment]
I agree with @devhl-labs, isEnum is the bugged one and should be fixed. Replacing the current isEnum with isEnum_Deprecated and fixing the actual bug is the right approach to me.

**Pull request merged**
