### PR TITLE
Add operations servers for csharp-netcore

### LINKED ISSUE #10639: [BUG][csharp-netcore] Path level servers overrides are ignored
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Path level servers overrides are ignored. Using the provided sample both `https://api.pet.com/v2` and `https://api.user.com/v2` are not included within the generated SDK. This is an issue with all specs tested.

##### OpenAPI declaration file content or url
[openapi-test.yaml.zip](https://github.com/OpenAPITools/openapi-generator/files/7376272/openapi-test.yaml.zip)

```yaml
servers:
- url: https://api.root.com/v3
# ... 
paths:
  /pet:
    servers:
      - url: https://api.pet.com/v2
   # ...
   /user:
    servers:
      - url: https://api.user.com/v2
```

##### Generation Details
`openapi-generator-cli generate -g csharp-netcore -i openapi-test.yaml -o sdk-test`

##### Steps to reproduce
1. Generate the SDK using the provided spec.
2. Verify that the generated SDK ignores servers defined within paths.

##### Related issues/PRs
Related issue from 2018 with a different SDK https://github.com/OpenAPITools/openapi-generator/issues/1694.

##### Suggest a fix
Servers defined within paths should be used for those paths which have been defined.

### PR DESCRIPTION
**Pull request by hamermike**
Add operation (path) level server support for csharp-netcore.

Resolves #10639 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mandrean, @shibayan, @Blackclaws, @lucamazzanti

### CODE REVIEW

**Comment by wing328** [comment]
The CI Appveyor (ran manually) reported the following errors:
```
C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Api\PetApi.cs:line 853
   at Org.OpenAPITools.Api.PetApi.DeletePet(Int64 petId, String apiKey, Int32 operationIndex) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Api\PetApi.cs:line 802
   at Org.OpenAPITools.Test.PetApiTests.Dispose() in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools.Test\Api\PetApiTests.cs:line 374
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
  Failed Org.OpenAPITools.Test.PetApiTests.TestArrayOfString [29 ms]
  Error Message:
   System.InvalidOperationException : Invalid index 0 when selecting the server. Must be less than 0.
  Stack Trace:
     at Org.OpenAPITools.Client.Configuration.GetServerUrl(IList`1 servers, Int32 index, Dictionary`2 inputVariables) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Client\Configuration.cs:line 753
   at Org.OpenAPITools.Client.Configuration.GetOperationServerUrl(String operation, Int32 index, Dictionary`2 inputVariables) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Client\Configuration.cs:line 733
   at Org.OpenAPITools.Client.Configuration.GetOperationServerUrl(String operation, Int32 index) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Client\Configuration.cs:line 719
   at Org.OpenAPITools.Client.ApiClient.Exec[T](RestRequest req, RequestOptions options, IReadableConfiguration configuration) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Client\ApiClient.cs:line 431
   at Org.OpenAPITools.Client.ApiClient.Delete[T](String path, RequestOptions options, IReadableConfiguration configuration) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Client\ApiClient.cs:line 823
   at Org.OpenAPITools.Api.PetApi.DeletePetWithHttpInfo(Int64 petId, String apiKey, Int32 operationIndex) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Api\PetApi.cs:line 853
   at Org.OpenAPITools.Api.PetApi.DeletePet(Int64 petId, String apiKey, Int32 operationIndex) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Api\PetApi.cs:line 802
   at Org.OpenAPITools.Test.PetApiTests.Dispose() in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools.Test\Api\PetApiTests.cs:line 374
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
```

Can you please take a look when you've time?

Full log: https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/41925874

**Comment by hamermike** [comment]
I've made a change to resolve the reported error. When running locally without modifying the tests I receive an error from the API `Error calling AddPet: {"code":405,"type":"unknown"}`. This same error occurs when making a request to the API via Postman. Please let me know if the tests are outdated or I'm doing something wrong.

**Comment by wing328** [comment]
Looks like there are still issues:
```
   Org.OpenAPITools.Client.ApiException : Error calling AddPet: {"code":500,"type":"unknown","message":"something bad happened"}
  Stack Trace:
     at Org.OpenAPITools.Api.PetApi.AddPetWithHttpInfo(Pet pet) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Api\PetApi.cs:line 734
   at Org.OpenAPITools.Api.PetApi.AddPet(Pet pet) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Api\PetApi.cs:line 670
   at Org.OpenAPITools.Test.Api.PetApiTestsV2..ctor() in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools.Test\Api\PetApiTestsV2.cs:line 52
  Failed Org.OpenAPITools.Test.Api.PetApiTestsV2.GetPetByIdAsync_GivenNotExistentId_ThrowsApiException [1 ms]
  Error Message:
   Org.OpenAPITools.Client.ApiException : Error calling AddPet: {"code":500,"type":"unknown","message":"something bad happened"}
  Stack Trace:
     at Org.OpenAPITools.Api.PetApi.AddPetWithHttpInfo(Pet pet) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Api\PetApi.cs:line 734
   at Org.OpenAPITools.Api.PetApi.AddPet(Pet pet) in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Api\PetApi.cs:line 670
   at Org.OpenAPITools.Test.Api.PetApiTestsV2..ctor() in C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools.Test\Api\PetApiTestsV2.cs:line 52
  Failed Org.OpenAPITools.Test.Api.PetApiTestsV2.AddPetAsync_GivenExistentId_UpdateThePet [1 ms]
  Error Message:
   Org.OpenAPITools.Client.ApiException : Error calling AddPet: {"code":500,"type":"unknown","message":"something bad happened"}
````

Ref: https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/42487770

**Comment by wing328** [comment]
To test it locally, please run the petstore server: https://github.com/OpenAPITools/openapi-generator/wiki/Integration-Tests#how-to-add-integration-tests-for-new-petstore-samples

**Comment by wing328** [comment]
Resolved merge conflicts and tests passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/43184726

Filed https://github.com/OpenAPITools/openapi-generator/pull/12090 instead. Closing this one.

**Pull request closed without merging**
