### PR TITLE
handle composed schemas in InlineModelResolver

### PR DESCRIPTION
**Pull request by rienafairefr**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.

### Description of the PR

`InlineModelResolver` wasn't handling the composedschema case correctly or even at all, with this PR it can transform inline models like this:

```    
ComposedModel:
  allOf:
  - $ref: '#/components/schemas/Model'
  - type: object
    properties:
      prop:
       type: string
```
into
```    
ComposedModel:
  allOf:
  - $ref: '#/components/schemas/Model'
  - $ref: '#/components/schemas/ComposedModel_allOf'
ComposedModel_allOf:
  type: object
    properties:
      prop:
        type: string
```
this might help for handling correctly allOf/anyOf/oneOf, even in the case of the presence of inline model

### CODE REVIEW

**Comment by ackintosh** [comment]
@rienafairefr Could you please merge master to resolve the conflict?

**Comment by wing328** [comment]
UPDATE: add new files via https://github.com/OpenAPITools/openapi-generator/pull/2112/commits/e29cf137be18cf03aa24b8d1de750a997e502409

**Comment by cvgaviao** [comment]
Could someone explain me the benefits of creating a new synthetic schema into the openapi model when using a no-multiple-inheritance languages, as java? 
Maybe I'm wrong, but it will just create two practically equal classes with different names and practically will doubled the size of the api jar.

**Comment by chameleon82** [comment]
@richardwhiuk  Is any way to not generate `allOf` models as those models not used in Api and there is no benefit to have it in most projects?

**Comment by wing328** [comment]
There's a bug in this implementation when "type: object" is not specified in the inline schema definition and I've filed https://github.com/OpenAPITools/openapi-generator/pull/5992 to fix it. The local test result is good.

**Comment by wing328** [comment]
To skip those model generation of inline schema in allOf, please add those models to .openapi-generator-ignore so that these files won't be generated.

**Comment by wing328** [comment]
@rienafairefr first of all thanks for the PR but we've feedbacks from our users that they do prefer the old behavior to not generate the inline model separately.

I'll file a PR to roll back the change. Let me know if you've any concerns, especially regarding your use case.

**Pull request merged**
