### PR TITLE
[core] GeneratorSettings, WorkflowSettings, and cleanup in CodegenConfigurator

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This is general enhancements as part of the [Separation of Concerns](https://github.com/OpenAPITools/openapi-generator/projects/5) project, and is work toward moving things to a Core package (#845). In doing so, my goal is to separate conceptual responsibilities of our internal implementations.

This PR leaves `CodegenConfigurator` as an "entrypoint" to configuring internals. There's still some work to be done to simplify that interface so we may remove redundant code from CLI, Maven Plugin, Gradle Plugin, and openapi-generator-online (which duplicates much of `CodegenConfigurator` in `Generator.java`).

A potentially minor breaking change, I've removed all getters from `CodegenConfigurator`. The caller already knows the properties being set on this type, and any evaluation should be done after calling `toClientOptInput` or the new `toContext`.

This PR introduces two new types: `GeneratorSettings` and `WorkflowSettings`. These are intentionally immutable, which will aid in testing once they are applied to a generator instance (generator authors can evaluate input settings against modified settings to validate any transformations done in the generator). These types are separate so we can clearly differentiate between those settings defining the _what_ (generator outputs) versus the _how_ (the workflow taken to generate outputs). 

As part of creating these new Settings types and moving to make `CodegenConfigurator` more SOLID, I've also introduced a `DynamicSettings` type which handles the deserialization of those settings which were previously considered `CodegenConfigurator`.  Now, `CodegenConfigurator` is simply orchestrating how we configure everything in preparation for generation.  `DynamicSettings` doesn't live in the Core module because it relies on Jackson JSON, and there's technically no need for this to live in a user-consumable module (users can just set additional properties directly); loading the config from file is application-specific.

While focusing on this settings cleanup, I wanted to rename `GeneratorProperties` to avoid confusion with `GeneratorSettings`.  The intention is that `GeneratorSettings` are those settings which are applied to a generator (an instance of `CodegenConfig`). `GeneratorProperties`, on the other hand, is a way to access System properties and modify them on a thread local to avoid race conditions during CI or other workflows… so I've opted to rename this to `GlobalSettings`. `GlobalSettings` will therefore be anything that can be considered outside the responsibility of a generator or its workflow (e.g. `debugModels` could be set as a System Property and used by either). We recently had a report of `-D` options not making it down to swagger-parser (see #2706), and this is because the CLI has a custom argument of `-D` which can easily be confused as the Java property `-D`. In this PR, I've added a deprecation warning with instructions to stop using the `-D` argument to `generate` and move this option to System properties. If we find that something like `-DdebugModels` or other supported "system properties" currently cause conflicts elsewhere, we may want to add a new `global-settings` option. I didn't do this in this PR because it seemed like a little too much for a single change.

### CODE REVIEW

**Comment by jimschubert** [comment]
cc @OpenAPITools/generator-core-team I've filed this to hit master since the changes shouldn't be "public api" (CodegenConfigurator getters and `GeneratorProperties` rename). Everything in this PR should have a pretty clear workaround.

**Comment by jimschubert** [comment]
@OpenAPITools/generator-core-team
@OpenAPITools/openapi-generator-collaborators 

I'm looking for feedback about whether this should target master or the 4.1.0 branch.

Working through all usages of `-D` in scripts, I've found that they were being used as a shortcut for `--additional-properties`. I don't think this was ever an intended use case. I still think we'd need to get rid of the `-D` argument to the generate command because it's easily confused with the `-D` argument to java for setting system properties.  I'd considered adding a `-P` short name for `--additional-properties`, which I think would more clearly indicate that these are properties rather than defined system properties.

Any thoughts one way or another?

**Comment by wing328** [comment]
> I'm looking for feedback about whether this should target master or the 4.1.0 branch.

My take is 4.1.0 branch as it's a breaking change with fallbacks

**Comment by wing328** [comment]
>  I'd considered adding a -P short name for --additional-properties

Good idea for a short name. What about `-p` (lower case) instead as all the other short names are lower case too?

**Comment by jimschubert** [comment]
I've updated the target to the 4.1.x branch and added the `-p` option as a shortcut for `--additional-properties`. I've also regenerated samples.

**Comment by jimschubert** [comment]
I've submitted a final commit, there were a couple of objc scripts which passed on my machine but failed on Shippable with the same syntax (? This is probably an IFS expansion issue).

Builds are passing now. Sorry for the tons of file changes.

**Comment by wing328** [comment]
## Upgrade Note

`-D` to pass generator options has been deprecated. Please use `--additional-properties` instead, for example, from:
```
ags="$ags -DprojectName=Petstore --model-package Samples.Petstore"
```
to
```
ags="$ags --additional-properties projectName=Petstore --model-package Samples.Petstore"
```

**Pull request merged**
