### PR TITLE
fix: ExampleGenerator correctly generates allOf composed schemas

### LINKED ISSUE #17497: [BUG] [ExampleGenerator] Generated examples from Composed schema types are `null` (allOf, oneOf, anyOf...)
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating an example for a model defined as a composite schema, such as:

__Current _(undesired)_ behavior:__

Consider the following schema:
```yaml
components:
  schemas:
    ExampleSchema:
      type: object
      properties:
        example_schema_property:
          type: string
          example: example schema property value
    ExampleComposedSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/ExampleSchema'
        - type: object
          properties:
            example_schema_property_composed:
              type: string
              example: example schema property value composed
```

I'd expect the generated example to look like:

```json
{
  "example_schema_property": "example schema property value",
  "example_schema_property_composed": "example schema property value composed"
}
```

However, it currently generates the following:
```json
null
```

__Why is this behavior happening?__

It's because only examples and properties are being supported right now:
https://github.com/OpenAPITools/openapi-generator/blob/a5d3fb4f601e4bced19f39cb6d82799a71531282/modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java#L349-L363

The message

```java
// TODO log an error message as the model does not have any properties 
```

is wrong because composed schema may exist.

##### openapi-generator version

master a5d3fb4f601e4bced19f39cb6d82799a71531282

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
paths:
  /generate_from_response_schema_with_composed_model:
    get:
      operationId: generateFromResponseSchemaWithComposedModel
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleComposedSchema'
components:
  schemas:
    ExampleSchema:
      type: object
      properties:
        example_schema_property:
          type: string
          example: example schema property value
    ExampleComposedSchema:
      type: object
      allOf:
        - $ref: '#/components/schemas/ExampleSchema'
        - type: object
          properties:
            example_schema_property_composed:
              type: string
              example: example schema property value composed
```

##### Generation Details

Run ExampleGeneratorTest.java

##### Steps to reproduce

Apply to following patch:

```patch
Subject: [PATCH] Add failing test case to ExampleGenerator for composed schema
---
Index: modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml b/modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml
--- a/modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml	(revision a5d3fb4f601e4bced19f39cb6d82799a71531282)
+++ b/modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml	(date 1703875535793)
@@ -53,7 +53,7 @@
                   example: primitive types example value
   /generate_from_response_schema_with_model:
     get:
-      operationId: generateFromResponseSchemaWithArrayOfPrimitiveTypes
+      operationId: generateFromResponseSchemaWithModel
       responses:
         '200':
           description: successful operation
@@ -61,6 +61,16 @@
             application/json:
               schema:
                 $ref: '#/components/schemas/ExampleSchema'
+  /generate_from_response_schema_with_composed_model:
+    get:
+      operationId: generateFromResponseSchemaWithComposedModel
+      responses:
+        '200':
+          description: successful operation
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/ExampleComposedSchema'
 components:
   schemas:
     StringSchema:
@@ -72,3 +82,12 @@
         example_schema_property:
           type: string
           example: example schema property value
+    ExampleComposedSchema:
+      type: object
+      allOf:
+        - $ref: '#/components/schemas/ExampleSchema'
+        - type: object
+          properties:
+            example_schema_property_composed:
+              type: string
+              example: example schema property value composed
Index: modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java b/modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java
--- a/modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java	(revision a5d3fb4f601e4bced19f39cb6d82799a71531282)
+++ b/modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java	(date 1703875564840)
@@ -146,6 +146,35 @@
                 mediaTypeKeys
         );
 
+        assertEquals(1, examples.size());
+        assertEquals("application/json", examples.get(0).get("contentType"));
+        assertEquals(String.format(Locale.ROOT, "{%n  \"example_schema_property\" : \"example schema property value\"%n}"), examples.get(0).get("example"));
+        assertEquals("200", examples.get(0).get("statusCode"));
+    }
+
+    @Test
+    public void generateFromResponseSchemaWithComposedModel() {
+        OpenAPI openAPI = TestUtils.parseFlattenSpec("src/test/resources/3_0/example_generator_test.yaml");
+
+        new InlineModelResolver().flatten(openAPI);
+
+        ExampleGenerator exampleGenerator = new ExampleGenerator(openAPI.getComponents().getSchemas(), openAPI);
+        Set<String> mediaTypeKeys = new TreeSet<>();
+        mediaTypeKeys.add("application/json");
+        List<Map<String, String>> examples = exampleGenerator.generateFromResponseSchema(
+                "200",
+                openAPI
+                        .getPaths()
+                        .get("/generate_from_response_schema_with_composed_model")
+                        .getGet()
+                        .getResponses()
+                        .get("200")
+                        .getContent()
+                        .get("application/json")
+                        .getSchema(),
+                mediaTypeKeys
+        );
+
         assertEquals(1, examples.size());
         assertEquals("application/json", examples.get(0).get("contentType"));
         assertEquals(String.format(Locale.ROOT, "{%n  \"example_schema_property\" : \"example schema property value\"%n}"), examples.get(0).get("example"));
```

##### Suggest a fix

Will open a PR soon

### PR DESCRIPTION
**Pull request by acouvreur**
Changes the previous behavior of generating `null` examples for composed schemas.

Fixes #17497

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/7359334417/job/20183801747?pr=17499

thanks for the PR. please update the samples as well.

**Review by acouvreur — COMMENTED** [review]
I will do a quick refactor to traverse the schema properties so I don't repeat the block three times

**Review by acouvreur — COMMENTED** [review]
I've also added support for `oneOf` and `anyOf` using the first available and valid schema.

Maybe we could generate multiple examples in this case but it would be too much work and refactor.

**Comment by acouvreur** [comment]
Rebased to master to be up to date with all samples

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
looks good. let's give it a try

thanks again for the PR

**Pull request merged**
