### PR TITLE
[Spring] Do not set contextPath for spring-boot

### PR DESCRIPTION
**Pull request by cbornet**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

This fixes https://github.com/swagger-api/swagger-codegen/issues/5244

### CODE REVIEW

**Comment by wing328** [comment]
@jmini I simply used the Github web-based GUI to resolve the merge conflicts (to keep both import statements).

I didn't touch those `properties` files though.

**Comment by wing328** [comment]
I'll update the samples in a separate PR.

**Comment by wing328** [comment]
I've run ./bin/spring-all-petstore.sh but git diff doesn't show any change.

The following files are not added to the project:
```
samples/server/petstore/spring-mvc-j8-async/src/main/resources/openapi.properties
samples/server/petstore/spring-mvc-j8-localdatetime/src/main/resources/openapi.properties
samples/server/petstore/spring-mvc/src/main/resources/openapi.properties
```

I'll include these files in my next PR.

**Comment by jmini** [comment]
I am not saying that my `bin/ensure-up-to-date` script introduced by #80 is absolutely correct it might be improved.

But merging a PR with a failed check is a bad idea. Now all PR integrating this commit are failing.

@wing328: please fix that! Having a red CI is really wrong.
I also did not manage to reproduce this locally... In case of emergency like this, we can also remove the spring scripts from the list of checked generators (remove this line: https://github.com/OpenAPITools/openapi-generator/blob/9b8602311e98e92d0095629ebc9dd7185fbf7255/bin/ensure-up-to-date#L15 )

**Comment by jmini** [comment]
> I'll include these files in my next PR.

Follow up PR to add the files: #168

**Pull request merged**
