### PR TITLE
[elm] Allow setting base path for each request

### LINKED ISSUE #1290: [elm] Add possibility to override basePath
##### Description

Generating the client for elm takes the current url as the basePath and gives no possibility to override it.

This is absolutely OK when an external API is used. But generating the client for a project which is shipped together with the API has always localhost in it. This should be customizable with the current URL under which the project is served.

##### openapi-generator version

v3.3.1

##### OpenAPI declaration file content or url

Not a specific one.

##### Command line used for generation

generate -i http://localhost/swagger/v1/swagger.json -g elm -o /generated

##### Steps to reproduce

1. Have a swagger.json file
2. Generate the elm client with the command above
3. Open one of the Request files
4. See the basePath is localhost and cannot be overriden or passed in.

### PR DESCRIPTION
**Pull request by trenneman**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Allow setting your own `basePath` for each request instead of using the one from your OpenAPI spec.

Fixes #1290. @wing328 can you review?

### CODE REVIEW

**Comment by wing328** [comment]
@trenneman you may want to add the feature without introducing another option as other clients (e.g. Ruby, C#, PHP, etc) allow setting the base path (e.g. change it to localhost:8080 for development) by default

**Comment by trenneman** [comment]
@wing328 Elm is a purely functional language. It has no classes, dependency injection or global state and also no typeclasses (it is designed to be very explicit about what you want). I therefore think passing it as a parameter (after adding a flag) makes the most sense.

**Comment by wing328** [comment]
@trenneman thanks for the explanation. Let's go with your enhancement.

**Comment by pecigonzalo** [comment]
@eriktim Im not sure I understand how this is intended to be used, how do we pass the new base path?

**Comment by eriktim** [comment]
@pecigonzalo if you generate the code using the flag `--additional-properties=elmEnableCustomBasePaths=true` each request function takes an additional parameter `baseUrl : String`.

**Comment by pecigonzalo** [comment]
Thanks a lot for the explanation, that works!

**Pull request merged**
