### PR TITLE
[rust-server] Restore newtype and XML support

### LINKED ISSUE #1590: [rust-server] Loss of opaque names for simple types
##### Description
I am trying to wrap a primitive type such as a `string` with an `opaqueWrapper`. This is correctly rendered using swagger, but OpenAPI 'sees through' the wrapper and the underlying primitive type appears in the method signatures of the resulting generated code. 

##### openapi-generator version
current master

##### OpenAPI declaration file content or url
```yaml
definitions:
  request:
    type: object
    required:
      - opaque
    properties:
      opaque:
        $ref: '#/definitions/opaqueWrapper'

opaqueWrapper:
  type : string
  description: A string in an opaque format.
```

### PR DESCRIPTION
**Pull request by bjgill**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. @frol @farcaller 

### Description of the PR

As part of the migration from swagger-codegen to openapi-generator, the `rust-server` generator lost support for newtypes (e.g. `pub struct OuterString(String)`). Partly as a consequence, XML support was also broken.

This PR undoes the change made by the default generator to unwrap references. This restores the old behaviour of `rust-server`.

I've added in a sample to verify the XML behaviour. We've also successfully used this branch to generate a Rust client for one of our services currently migrating from swagger-codegen to openapi-generator.

This will be my final PR to openapi-generator on behalf of @metaswitch. I am leaving the company at the end of the year. @rjw2 will be taking over my role in handling upstream contributions

Fixes #1590

### CODE REVIEW

**Comment by bjgill** [comment]
Hmm. It looks as if https://github.com/OpenAPITools/openapi-generator/pull/1296 may have broken this PR (I was working off master from early November).

**Comment by bjgill** [comment]
Indeed - this patch relies on having the original type wrappers for arrays available, so that we can hang XML-handling code off them. It looks as if https://github.com/OpenAPITools/openapi-generator/pull/1296/files#diff-bd1652e990ffe227072a5c8908fd3054R442 is stripping out those wrappers, and hence breaking this PR.

I'm not immediately sure how to handle. This stripping happens early enough in openapi-generator that I can't see an easy way of working around it.

**Comment by wing328** [comment]
> I'm not immediately sure how to handle. This stripping happens early enough in openapi-generator that I can't see an easy way of working around it.

@bjgill What about setting the `generateAliasAsModel` option to `true`?

**Comment by bjgill** [comment]
Interesting. I was unaware of that option. I don't know what it is, but it certainly sounds promising.

In any case, I'm probably not going to have time to look at this PR in the near future. I'm happy to leave for another week or two in case someone else wants to pick this work up. Otherwise, I'll close this PR.

**Pull request closed without merging**
