### PR TITLE
[C][Client] Support progress function of libcurl

### PR DESCRIPTION
**Pull request by ityuhui**
Hi @wing328 @zhemant @michelealbano

This is a feature enhancement.
libcurl has a mechanism of progress callback function. 
https://curl.se/libcurl/c/CURLOPT_XFERINFOFUNCTION.html
That can be used to do some operation ( e.g. display download/upload progress information ) when the transfer is in progress. 
This PR introduces this feature into c client.

It also can be used to stop an endless http(s) request. The detail can be found at https://github.com/kubernetes-client/c/pull/39 

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Please merge the latest master into this branch, which should fix the CI failures.

**Comment by ityuhui** [comment]
> Please merge the latest master into this branch, which should fix the CI failures.

Sure. I will do it.

**Comment by ityuhui** [comment]
Hi @wing328 

I have merged (git rebase upstream/master) the master code on yesterday evening. But ci/circleci: build still failed. 
Are you sure the latest code has fixed the CI failure ?

**Comment by wing328** [comment]
Looks like https://repo.maven.apache.org:443 was throttling our connections as the project is too active.

```
Nov 23, 2020 1:42:39 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection reset
Nov 23, 2020 1:42:39 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
Nov 23, 2020 1:42:39 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection reset
Nov 23, 2020 1:42:39 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
Nov 23, 2020 1:42:39 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection reset
Nov 23, 2020 1:42:39 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
```

Just restarted the circleci job. Let's see how that goes.

**Comment by wing328** [comment]
CircleCI tests passed via https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/7126/workflows/6196c76a-817f-4cd4-9f4f-2ed359b52266/jobs/20610

**Comment by ityuhui** [comment]
Thank you @wing328

**Pull request merged**
