### PR TITLE
fix maven repo for openapi-generator-cli

### PR DESCRIPTION
**Pull request by adamdecaf**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

The current repository 403's and returns an untrusted certificate.

https://repo1.maven.apache.org/maven2

### CODE REVIEW

**Comment by adamdecaf** [comment]
This applies to all branches. I can cherry-pick and PR to the others if y'all want.

**Comment by wing328** [comment]
@adamdecaf thanks for the PR but I don't get the errors you mentioned. Here is what I got:
```
[INFO] --- maven-dependency-plugin:2.9:get (default-cli) @ openapi-generator-project ---
[INFO] Resolving org.openapitools:openapi-generator-cli:jar:3.3.1
Downloading from sonatype-snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/3.3.1/openapi-generator-cli-3.3.1.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/openapitools/openapi-generator-cli/3.3.1/openapi-generator-cli-3.3.1.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/openapitools/openapi-generator-cli/3.3.1/openapi-generator-cli-3.3.1.jar (17 MB at 941 kB/s)
[WARNING] destination/dest parameter is deprecated: it will disappear in future version.
[INFO] Copying /Users/williamcheng/.m2/repository/org/openapitools/openapi-generator-cli/3.3.1/openapi-generator-cli-3.3.1.jar to /Users/williamcheng/Code/graphql-generator/bin/utils/openapi-generator-cli-3.3.1.jar
```

(the warning is not related)

About other branches, we sync the changes from master to 3.x and 4.x branches regularly (so don't worry about it :) )

**Comment by adamdecaf** [comment]
Do you have the jar cached in `~/.m2` ?

**Comment by adamdecaf** [comment]
```
$ mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T11:33:14-07:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
```

**Comment by wing328** [comment]
@adamdecaf I used https://www.sslshopper.com/ssl-checker.html, which shows 
https://repo1.maven.apache.org/maven2 having the following issues: 
> None of the common names in the certificate match the name that was entered (repo1.maven.apache.org). You may receive an error when accessing this site in a web browser

and confirm the one you provided is all good.

Thanks for the fix 👍

**Comment by wing328** [comment]
@adamdecaf  thanks for the PR, which is included in the v3.3.2 release: https://twitter.com/oas_generator/status/1057649626101112832

**Pull request merged**
