### PR TITLE
Fix selection of unnecessary form parameter models

### LINKED ISSUE #10254: [BUG] [JAVA] [SPRING] [MVC] Generating code is referencing a generated model class which is not created [BIS]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm facing the exact same issue as https://github.com/OpenAPITools/openapi-generator/issues/405 but in version 5.x.y.
When using multipart/form-data, referenced models are not generated.

It works well with 4.3.1.
##### openapi-generator version

5.0.0, 5.2.0
##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.2'
...
paths:
  '/workflows':
    post:
      operationId: create
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/xxx'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa'

...
components:
  schemas:
    yyy:
          type: object
          properties:
            zzz:
              type: object
              properties:
                name:
                  $ref: '#/components/schemas/name'
                mode:
                  $ref: '#/components/schemas/mode'
            documents:
              type: array
              items:
                type: string
                format: binary
          required:
            - zzz
            - documents
          additionalProperties: false

```

##### Generation Details
```xml
<plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>5.0.0</version>
                <executions>
                    <execution>
                        <id>server</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/contract/${project.artifactId}.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelNameSuffix>DTO</modelNameSuffix>
                            <configOptions>
                                <title>MyOrg</title>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                                <library>spring-mvc</library>
                                <useTags>false</useTags>
                                <serializableModel>true</serializableModel>
                                <swaggerDocketConfig>true</swaggerDocketConfig>
                                <delegatePattern>true</delegatePattern>
                                <dateLibrary>java8</dateLibrary>
                                <apiPackage>myorg.controllers</apiPackage>
                                <modelPackage>myorg.model</modelPackage>
                                <invokerPackage>myorg.invoker</invokerPackage>
                                <useOneOfInterfaces>true</useOneOfInterfaces>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

##### Steps to reproduce
Generate and check that models xxxDTO and deep object (zzzDTO, modeDTO) are not generated

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/405

### LINKED ISSUE #12036: [BUG] [SPRING] Model class is not generated if it is included only in multipart/form-data object
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generator does not generate model classes that used in `multipart/form-data` object.
Please see https://github.com/RamazanYapparov/multipart-demo repository with reproducible example.

##### openapi-generator version

5.4.0

##### OpenAPI declaration file content or url

https://github.com/RamazanYapparov/multipart-demo/blob/master/src/main/resources/server.yml

##### Generation Details

https://github.com/RamazanYapparov/multipart-demo/blob/master/pom.xml#L58-L78

###### Steps to reproduce in prepared project

- clone https://github.com/RamazanYapparov/multipart-demo
- run `./mvnw clean compile`
- result: compilation failure

###### Steps to reproduce from scratch

- create OpenAPI 3 spec containing the following:
  - two objects defined in `components.schemas`
  - first one is some `Payload` object with any set of fields
  - the second one is some `Upload` object with one field being a `$ref` to the first object and the second field being binary string
  - POST operation with `requestBody` consuming `multipart/form-data`
  - `requestBody` schema should be a `$ref` to `Upload` object
- run `openapi-generator` with provided schema  using `spring` generator
- result: `Payload` class is not generated

##### Related issues/PRs

Did not find anything related

### LINKED ISSUE #14461: [BUG] Compilation errors occured if set multipart/type in requestBody
#### Bug Report Checklist

- [ v] Have you provided a full/minimal spec to reproduce the issue?
- [ v] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ v] Have you searched for related issues/PRs?
- [ v] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Compilation errors occured if set multipart/type in requestBody:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project drones-openfeign-api: Compilation failure: Compilation failure: 
[ERROR] /opanapicheck/drones-openfeign-api/target/generated-sources/openapi/src/main/java/com/tech/drones/oa/api/FacadeApi.java:[8,32] package com.tech.drones.oa.model does not exist
[ERROR] /opanapicheck/drones-openfeign-api/target/generated-sources/openapi/src/main/java/com/tech/drones/oa/api/FacadeApi.java:[62,25] cannot find symbol
[ERROR]   symbol:   class Medication
[ERROR]   location: interface com.tech.drones.oa.api.FacadeApi
[ERROR] /opanapicheck/drones-openfeign-api/target/generated-sources/openapi/src/main/java/com/tech/drones/oa/api/FacadeApi.java:[51,95] cannot find symbol
[ERROR]   symbol:   class Medication
[ERROR]   location: interface com.tech.drones.oa.api.FacadeApi
[ERROR] -> [Help 1]
```

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

https://gist.github.com/tbw777/d74e13d3da95b2b314c0d338a66dfa46

##### Generation Details

https://gist.github.com/tbw777/18f0077e8c3da0dc3834a2f836fe1006

##### Steps to reproduce

mvn clean compile

##### Related issues/PRs

not found

##### Suggest a fix

dont have

### LINKED ISSUE #14681: [Bug] [Java] [Webclient] Missing models
##### Description
When generating client code for Java and with subtemplate webclient, some important models are left out, making the compilation fail.
Snippet from the Maven output:
```
[ERROR] COMPILATION ERROR :                                                                                             
[INFO] -------------------------------------------------------------                                                    
[ERROR] /C:/dev/openapi-test/src/main/java/org/openapitools/client/api/DraftsApi.java:[7,37] cannot find symbol         
  symbol:   class DraftAPIMultipart                                                                                     
  location: package org.openapitools.client.model                                                                       
[ERROR] /C:/dev/openapi-test/src/main/java/org/openapitools/client/api/DraftsApi.java:[11,37] cannot find symbol        
  symbol:   class DraftProductMultipart                                                                                 
  location: package org.openapitools.client.model                                                                        
etc.
```

##### openapi-generator version
Tested with 6.3.0 and the latest master

##### OpenAPI declaration file content or url
https://gist.github.com/fcnjd/9ab449158cc51d29b1379c80896e062f
I'm sorry for the big file size, but it's the original documentation as provided by IBM.

##### Command line used for generation

openapi-generator-cli generate -g java --library webclient -i IBM_API_Connect_Platform_-_Provider_API-2.0.0.yaml

##### Steps to reproduce
Run the above CLI command, and then do a mvn clean compile and you'll see the errors.

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/14461

##### Suggest a fix/enhancement
A fix is to use SmartBears online tool Swagger Hub, which doesn't have the error, but isn't suitable for my current usecase.

### PR DESCRIPTION
**Pull request by martin-mfg**
fix #12036, fix #14461, fix #14681, fix #10254, which all report the same problem. Possibly there are more such issues.

## Problem
For `application/x-www-form-urlencoded` and `multipart/form-data` parameters, the model class of the form parameter is not needed and thus (correctly) not generated. But if the form parameter has any property with a non-primitive type, a model class for this property *is* needed and should be generated. But it is currently not generated.

## Solution
The filtering of form model classes happens in `ModelUtils.getSchemasUsedOnlyInFormParam`. This method uses `visitOpenAPI` to iterate through all models. It then skips generation of all models for which the associated mime-type `t` is always `application/x-www-form-urlencoded` or `multipart/form-data`.
So to fix the described problem, I changed the internals of `visitOpenAPI` to set `t` to a mime-type only for those models that are used by a *parameter*, but not for those models that are used as *properties* of parameters.
This does not have any side effects on callers of `visitOpenAPI` other than `getSchemasUsedOnlyInFormParam`. Because the other two callers of `visitOpenAPI` do not use the value of the mime-type `t` in any way.

## Test Inputs
[This gist](https://gist.github.com/martin-mfg/2829d5390bf638ce6cd27aea103a733a) contains a simple OpenAPI v3 spec that demonstrates the described problem, as well as a v2 spec that does the same.

## Questions
- [This comment](https://github.com/OpenAPITools/openapi-generator/issues/405#issuecomment-405808009) sounds to me like there are cases where the changes of my PR are not preferable. I didn't find such a use case though. If I missed something, please let me know.

- While working on this issue I noticed that  OpenAPI Generator doesn't support MapSchemas and ArraySchemas for `application/x-www-form-urlencoded` and `multipart/form-data` parameters. Because [DefaultCodegen.fromRequestBodyToFormParameters](https://github.com/OpenAPITools/openapi-generator/blob/ec835fbd948cf1223c1d899c2859019cef4653a9/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L6903C35-L6903C66) doesn't support them. This method contains a warning for MapSchemas:  
  ```java
  if (ModelUtils.isMapSchema(propertySchema)) {
	  LOGGER.error("Map of form parameters not supported. Please report the issue to https://github.com/openapitools/openapi-generator if you need help.");
	continue;
  }
  ```
  Although this warning is triggered if a *property* of the form parameter is of type MapSchema, I think it was intended to be triggered if the form parameter itself is of type MapSchema. I could fix this and also add a similar warning for ArraySchema. Would that make sense?

---------------

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (7.0.1 - patch release), `7.1.x` (minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)

### CODE REVIEW

**Comment by wing328** [comment]
> I could fix this and also add a similar warning for ArraySchema.

yes please

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by martin-mfg** [comment]
> > I could fix this and also add a similar warning for ArraySchema.
> 
> yes please

done

**Comment by wing328** [comment]
> https://github.com/OpenAPITools/openapi-generator/issues/405#issuecomment-405808009 sounds to me like there are cases where the changes of my PR are not preferable. I didn't find such a use case though. If I missed something, please let me know.

I tested your change locally and looks good too far. Let's go with this fix. If users report issues related to this change, we'll take another look.

**Pull request merged**
