### PR TITLE
[WIP] [Elm] Fix elm code generation for array type request param

### PR DESCRIPTION
**Pull request by sayanarijit**
Enclose array values inside `()`.

e.g.

From:

```elm
getArticles : Maybe List ArticleCategory -> Api.Request ()
```

To:

```elm
getArticles : Maybe (List ArticleCategory) -> Api.Request ()
```

Fixes: https://github.com/OpenAPITools/openapi-generator/issues/7889

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by sayanarijit** [comment]
cc @eriktim

**Comment by sayanarijit** [comment]
Ok It generates `Maybe (List ArticleCategory) -> Api.Request ()` but we actually need `Maybe (List Api.Data.ArticleCategory) -> Api.Request ()`. i.e. `isModel` for the item should be true.

**Comment by sayanarijit** [comment]
After a lot of experiments, trials and errors, finally https://github.com/OpenAPITools/openapi-generator/pull/7890/commits/81c0bdc8b8c2b89be690f7334294788654818295 works. But it works around the issue that `isEnum` is often set to `false` for sum type data.

**Comment by sayanarijit** [comment]
Not yet fixed.

It generates:

```elm
module Api.Request.Default exposing
    ( getArticles
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


getArticles : Maybe (List Api.Data.ArticleCategory) -> Api.Request ()
getArticles category_query =
    Api.request
        "GET"
        "/articles"
        []
        [ ( "category", Maybe.map (String.join "," << List.map stringFrom) category_query ) ]
        []
        Nothing
        (Json.Decode.succeed ())
```

**Comment by Erudition** [comment]
That looks fixed to me!

**Comment by sayanarijit** [comment]
I think there are still some edge cases. However, I think those are easily avoidable. Due to poor time management skills, I'm not able to continue working on this PR, hence closing this. Feel free to take over though.

**Pull request closed without merging**
