### PR TITLE
Introduce optional weight function for commands and other improvements

### PR DESCRIPTION
**Pull request by jfacorro**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- Optional weight function that returns how a relative value of how often a command should be run.
- Add an arity 1 function to all proper generators so that for JSON-like generated values some fields can be overridden.
- Only add `Body` and `ContentType` for endpoints where a body is allowed.
- Move syntactic sugar helper functions to header file and `setup` & `cleanup` to the `_statem.erl` file.

### CODE REVIEW

**Comment by wing328** [comment]
@jfacorro thanks for the PR. Do you mind updating the subject line and description with a bit more information on what the PR does?

**Comment by jfacorro** [comment]
> @jfacorro thanks for the PR. Do you mind updating the subject line and description with a bit more information on what the PR does?

Sorry about that. I opened the PR and then forgot to update these things. Thank you for reminding me 😄.

**Comment by wing328** [comment]
@jfacorro no worries. Thanks again for the contribution 👍

**Comment by wing328** [comment]
@jfacorro thanks for the contribution, which has been included in the 4.0.0-beta release: https://twitter.com/oas_generator/status/1079727020374806529.

Happy New Year and looking forward to more collaboration and contributions in 2019!

**Pull request merged**
