### PR TITLE
[Java] option for the prefix of boolean getters

### PR DESCRIPTION
**Pull request by jmini**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
Java: @bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

### Description of the PR

This PR adds a new option to all java generators (java client, jaxrs server, spring, …): `booleanGetterPrefix`

This new option influence the name of the getter generated for a boolean property in a model.

Example values for `booleanGetterPrefix`: 

* `is`: default value in `3.0.x`.
* `get`: new default value starting with `3.1.0`

With following OAS3 (extract):

```yaml
components:
  schemas:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        status:
          type: string
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
```

Generated code with `is` value:

```java
  public Boolean isComplete() {
    return complete;
  }
```

With `get` value:

```java
  public Boolean getComplete() {
    return complete;
  }
```

This was also discussed in:

* swagger-api/swagger-codegen#7261
* swagger-api/swagger-codegen#7764
* swagger-api/swagger-codegen#7638
* ...

### CODE REVIEW

**Comment by jmini** [comment]
@cbornet: yes current change is as minimal as possible (no impact on the generated code).
Modifying the default value can be made in a follow up PR.

**Comment by jmini** [comment]
I have pushed some more commits to change the default value.

I also think that it is important for our users to have a short list of the breaking changes in a major/minor release.

I have started [`docs/migration-guide.adoc`](https://github.com/jmini/openapi-generator/blob/6fca5f5aa0d863fbe9ec013448c5f4f24206397d/docs/migration-guide.adoc) to list all breaking changes of a release.

**Comment by jmini** [comment]
@macjohnny and @cbornet (you were both interested by the feature in a previous conversation), any additional feedback on this?

I would like to merge this, but until now nobody gave it a try.

**Comment by jmini** [comment]
Input @cbornet:

> We need the `getXXX()` getter because of the Java Beans spec : http://www.oracle.com/technetwork/articles/javaee/spec-136004.html
> `isXXX()` is for `boolean`, not for `Boolean`

**Comment by cbornet** [comment]
At paragraph 8.3 :smile:

**Comment by alex-spicer** [comment]
Does this apply to other languages too? Or is this just java? jaxrs-jersey I still see isX getter.
Any forced flag to help here?

**Comment by wing328** [comment]
The enhancement is made to the abstract java codegen class, which should cover all java generators.

Maybe the mustache template needs to be updated. Welcome PR to plot the enhancement form Java client mustache/generator to JAX-RS templates/generators.

**Pull request merged**
