### PR TITLE
[java] No @NotNull annotation for readOnly (required) attributes

### LINKED ISSUE #5026: [Spring-java] required readonly attribute generate not null field
Hi All,
regard required, readOnly and writeOnly open api specification report:

If a readOnly or writeOnly property is included in the required list, required affects just the relevant scope – responses only or requests only. That is, read-only required properties apply to responses only, and write-only required properties – to requests only.

so if i declare a field required and read-only means that in the request that field should be empty.

example with this yam:

    Poll:
      title: Poll
      type: object
      description: A poll is an election, or a survey of people's opinions to ask inside the platform
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Unique Identifier of a Poll
-------
openapigenerator generate the class with id not null

  @JsonProperty("id")
  private Long id;

  @NotNull
    public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

What happen if i run my code and  i perform a post with an empty id ? Spring raise bad request but it is not correct.  For openapi specification  read-only required properties apply to responses only and not for the request.
I think that openapi generator should generate @NotNull only for writeOnly property

### PR DESCRIPTION
**Pull request by daniel-sc**
fixes #5026

This duplicates #5960 (which was stale because of missing feedback/updates from creator).

@bbdouglas  @sreeshas @jfiala  @lukoyanov @cbornet @jeff9finger @karismann  @Zomzog  @lwlee2608 @nmuesch 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by daniel-sc** [comment]
Hi @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch
Could anyone please review this? 
I'm happy to update the PR if some things don't match expectations.

**Comment by feech** [comment]
138 files have changed! and mostly of them just formatting.
I am not a reviewer but you made everything to slow down the process.

**Comment by daniel-sc** [comment]
@feech this is because of the _required_ re-generation of docs (`./bin/utils/export_docs_generators.sh`) - together with the ([known](https://github.com/groue/GRMustache/issues/46)) issue that newline can not be controlled well with mustache.. 

(if you ask me, this shows why the general best practice is _not_ to version control generated content - but of course others might have more insights for this specific repository!)

**Comment by daniel-sc** [comment]
Hi @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch 
Anyone up for a review and/or feedback?
I'd be happy to resolve the merge conflicts that appeared in the meantime, but only if there is some reasonable expectation on this getting merged ;-)

**Pull request merged**
