### PR TITLE
Release docker images for ARM64

### PR DESCRIPTION
**Pull request by odidev**
- Added language to python for arm64 so that python3.6 virtual environment is created in arm64 and phpenv global' to 7.2.31 is used for arm64 and code is added to install deno for arm64 and to build the jar of this package mvn clean install and mvn verify command is used for arm64.
- Added separate tag for arm64 in docker tag command.
- Replaced java:8-jre-alpine with openjdk:8-jre-alpine to build image for arm64.

### CODE REVIEW

**Comment by wing328** [comment]
@odidev can you please resolve the merge conflicts when you've time? Thank you.

**Comment by odidev** [comment]
I have rebased the code and resolved the merge conflict. Please review and let me know if any changes are required.

**Comment by wing328** [comment]
@odidev let me review and take it from here. Thanks again for the PR.

**Comment by wing328** [comment]
@odidev can you please PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by wing328** [comment]
@odidev thanks again for the PR. I've filed https://github.com/OpenAPITools/openapi-generator/pull/9246 using `docker buildx` instead

**Comment by wing328** [comment]
Done. Please give https://hub.docker.com/layers/openapitools/openapi-generator-cli/latest/images/sha256-9d1841f31f3067d626befca537019f688917267122b580a18699873617d1b688?context=explore a try to see if it works for you.

**Pull request closed without merging**
