### PR TITLE
Fix call to TestCase.assertEqual()

### PR DESCRIPTION
**Pull request by Ichimonji10**
`TestCase.assertEquals()` does not exist.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Blocks: #19068

Ping Python tech committee members: @cbornet @tomplus @krjakbrjak @fa0311 @multani

**Comment by Ichimonji10** [comment]
Per https://devguide.python.org/versions/, Python 3.7 is EOL, so I will assume that those test failures can be ignored unless told otherwise. #19092 may be of interest.

**Review by multani — APPROVED** [review]
`assertEquals` was removed in 3.12: https://docs.python.org/3/whatsnew/3.12.html#id3

Thanks for the cleanup!

**Comment by multani** [comment]
Maybe we should test against 3.12 also ...

**Comment by Ichimonji10** [comment]
I re-opened #19092. I can cherry-pick that commit onto this PR if desired.

**Pull request merged**
