### PR TITLE
Add gRPC Protobuf schema generator

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

For https://github.com/OpenAPITools/openapi-generator/issues/3806

### CODE REVIEW

**Comment by wing328** [comment]
To try the new generator, please follow 3 simple steps below:

1. Download the Java JAR (https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.1.2-SNAPSHOT/openapi-generator-cli-4.1.2-20190830.062328-26.jar)

2. Rename the JAR as "openapi-generator-cli.jar"

3. Run the following command to generate an OCaml API client for the Petstore API (https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml):

Mac/Linux:

- java -jar openapi-generator-cli.jar generate -g grpc-schema -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -o /var/tmp/grpc-schema/

Windows:

- java -jar openapi-generator-cli.jar generate -g ocaml -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -o C:\tmp\grpc-schema

If you've any feedback or question, please let us know by opening a new [issue](https://github.com/OpenAPITools/openapi-generator/issues/new)

**Comment by evandrix** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.1.2-SNAPSHOT/openapi-generator-cli-4.1.2-20190904.113123-33.jar

503 Service Temporarily Unavailable

**Comment by evandrix** [comment]
> To convert OpenAPI spec (v2, v3) to gRPC, Protobuf definitions in 3 steps, please follow 3 simple steps below:
> 
> 1. Download the Java JAR (https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.1.2-SNAPSHOT/openapi-generator-cli-4.1.2-20190904.113123-33.jar)
> 2. Rename the JAR as "openapi-generator-cli.jar"
> 3. Run the following command to generate an gRPC, Protobuf definitions for the Petstore API (https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml):
> 
> Mac/Linux:
> 
> * java -jar openapi-generator-cli.jar generate -g grpc-schema -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -o /var/tmp/grpc-schema/
> 
> Windows:
> 
> * java -jar openapi-generator-cli.jar generate -g grpc-schema -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -o C:\tmp\grpc-schema
> 
> If you've any feedback or question, please let us know by opening a new [issue](https://github.com/OpenAPITools/openapi-generator/issues/new)

`wget -qc --no-check-certificate "https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.1.2-SNAPSHOT/openapi-generator-cli-4.1.2-20190904.113123-33.jar" -O "openapi-generator-cli.jar"` instead

**Comment by wing328** [comment]
@evandrix thanks for sharing the tips to skip certification validation.

**Comment by wing328** [comment]
Renamed the generator from `grpc-schema` to `protobuf-schema` via #3864

**Comment by kivan-mih** [comment]
@wing328 Is there a way to convert the other way: from grpc to open-api?

**Comment by wing328** [comment]
@wing328 sorry that's not supported.

**Comment by TheWayYouMakeMeFeel** [comment]
@wing328 Hi, I noticed that this feature does not support enum's convertion, do you have a plan adding this feature?

**Comment by wing328** [comment]
@TheWayYouMakeMeFeel no plan from me at the moment. Would you have time to contribute or the enhancement or sponsor the work?

**Pull request merged**
