### PR TITLE
fix require var logging, don't matchGenerated if allOf skipped

### PR DESCRIPTION
**Pull request by robstoll**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

<hr/>

I have the feeling this PR template is outdated:
1. I ran the tho sh files and got a lot of changes even though I clearly have not touched anything related so that such a change would be justified. Either the previous PR did not generate it or there is another issue (that's why I have not included the changes in the PR). 
2. PR templates states "master is an upcoming 7.1.0 minor release" => I would like to address it to 7.3.x according to <https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches> there should be a 7.3.x branch but I cannot find it => hence I have targeted master in the hope this targets 7.3.0

### CODE REVIEW

**Comment by robstoll** [comment]
pushed the re-generated pieces so that CI hopefully passes

**Comment by wing328** [comment]
can you please merge the latest master into your branch? i think some samples have already been updated in the master.

**Comment by robstoll** [comment]
looks like it, I rebased on master

**Comment by wing328** [comment]
lgtm. thanks for the PR.

**Pull request merged**
