### PR TITLE
[Qt5] Emit signal when api has finished processing all pending work

### LINKED ISSUE #8864: [REQ] [Qt5] Emit a generic signal anytime an api call is completed
The current callback in the API interface emits signals specific to the API, for example

```
    if (worker->error_type == QNetworkReply::NoError) {
        emit createUsersWithArrayInputSignal();
        emit createUsersWithArrayInputSignalFull(worker);
    } else {
        emit createUsersWithArrayInputSignalE(error_type, error_str);
        emit createUsersWithArrayInputSignalEFull(worker, error_type, error_str);
    }
```

From the outside we can then connect to these signals

The API has different signals per function call.

I would like to be able to know if the API did "any work" not just some "specific work"

For example I would add a signal called ```void workDone()```

```
    if (worker->error_type == QNetworkReply::NoError) {
        emit createUsersWithArrayInputSignal();
        emit createUsersWithArrayInputSignalFull(worker);
    } else {
        emit createUsersWithArrayInputSignalE(error_type, error_str);
        emit createUsersWithArrayInputSignalEFull(worker, error_type, error_str);
    }

    emit workDone();
```

```
    if (worker->error_type == QNetworkReply::NoError) {
        emit createUsersWithListInputSignal();
        emit createUsersWithListInputSignalFull(worker);
    } else {
        emit createUsersWithListInputSignalE(error_type, error_str);
        emit createUsersWithListInputSignalEFull(worker, error_type, error_str);
    }

    emit workDone();
```

and this would be added to ALL of the callback functions. From the outside then we could connect to know if the API class has done anything yet without needing to connect to a whole bunch of individual signals

This would be trivial for me to add so I wanted to open it up for discussion before just adding a PR

### PR DESCRIPTION
**Pull request by xconverge**
fixes #8864

This is discussed in more detail in that issue. Nice and clean idea @etherealjoy I am trying to take some of the burden of test/etc for this issue. I tested it for a few cases and it works great!

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @MartinDelille (2018/03) @muttleyxd (2019/08)

### CODE REVIEW

**Comment by etherealjoy** [comment]
@xconverge 
Were you able to verify if the solution worked for your use case?

**Comment by etherealjoy** [comment]
@wing328 
Any Idea why Travis failed, even though added changes do not interfere with the tests, does this happen time to time?

**Review by MartinDelille — APPROVED** [review]

**Comment by etherealjoy** [comment]
@xconverge 
Might need to rebase after #8899 is merged due to failed tests.

**Comment by xconverge** [comment]
> 
> 
> @xconverge
> Might need to rebase after #8899 is merged due to failed tests.

thanks, done. It is definitely a bit alarming as a first time contributor to see all sorts of failing stuff that is unrelated to what you did, so glad to see it being fixed, thanks!

**Review by etherealjoy — APPROVED** [review]

**Comment by xconverge** [comment]
Thanks for your help/work @etherealjoy, @MartinDelille, and @basyskom-dege 

I love when I can selfishly add things to help myself, that also can benefit others! I will keep an eye out as the next release comes to make sure things go smoothly, but my wishlist is empty now!

**Comment by wing328** [comment]
@xconverge thanks for the PR, which has been included in the v5.1.0 release: https://twitter.com/oas_generator/status/1373636654024380423

**Pull request merged**
