### PR TITLE
[Java][Spring][#2901] remove unused import from spring template

### LINKED ISSUE #2901: remove unused import org.openapitools.jackson.nullable.JsonNullable from generated model
#### Bug Report Checklist

- [ X] Have you provided a full/minimal spec to reproduce the issue?
- [ X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ X] What's the version of OpenAPI Generator used?
- [ X] Have you search for related issues/PRs?
- [X ] What's the actual output vs expected output?
- [X ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
When I generate the model there  is an unused import  org.openapitools.jackson.nullable.JsonNullable; in every single DTO. It forces me to add a dependency.

		<dependency>
		    <groupId>org.openapitools</groupId>
		    <artifactId>jackson-databind-nullable</artifactId>
		    <version>0.1.0</version>
		</dependency>

Unfortunately this dependency must be approved in the company so the model is unusable.

Is there any way to get rid of this unused import? Configuration is below:

			<plugin>
			    <groupId>org.openapitools</groupId>
			    <artifactId>openapi-generator-maven-plugin</artifactId>
			    <version>4.0.0</version>
			    <executions>
			        <execution>
			            <goals>
        			        <goal>generate</goal>
        			    </goals>
            			<configuration>
					<inputSpec>${maven.multiModuleProjectDirectory}/api/target/generated/swagger-api-spec/swagger.json</inputSpec>	
						<language>spring</language>
						<library>spring-boot</library>
						<model-name-prefix>Cqrs</model-name-prefix>
						<modelPackage>com.anthem.specialty.provider.springapi.model</modelPackage>
						<apiPackage>com.anthem.specialty.provider.springapi.api</apiPackage>
						<invokerPackage>com.anthem.specialty.provider.springapi.invoker</invokerPackage>
            			    <skipValidateSpec>true</skipValidateSpec>
						<generateSupportingFiles>true</generateSupportingFiles>
						<supportingFilesToGenerate>
							ApiApi.java,ApiApiControler.java,ApiUtil.java
						</supportingFilesToGenerate>
            			    <configOptions>
						<sourceFolder>src/gen/java/main</sourceFolder>
						<java8>false</java8>
						<dateLibrary>java8</dateLibrary>
						<interfaceOnly>false</interfaceOnly>
						<groupId>com.company</groupId>
						<artifactId>${project.artifactId}</artifactId>
						<artifactVersion>${project.version}</artifactVersion>
            		    		</configOptions>
            			</configuration>
		        	</execution>
			    </executions>
			</plugin>	

##### openapi-generator version

			    <groupId>org.openapitools</groupId>
			    <artifactId>openapi-generator-maven-plugin</artifactId>
			    <version>4.0.0</version>

##### OpenAPI declaration file content or url

probably convenient enhancement

##### Command line used for generation

maven plugin

##### Steps to reproduce

run the maven clean install

##### Related issues/PRs

a few similar issues

##### Suggest a fix

provide a mechanism to remove unused imports

### PR DESCRIPTION
**Pull request by bilak**
closes #2901

### CODE REVIEW

**Comment by bilak** [comment]
@wing328 is it possible to add this pr to upcoming release?

**Comment by bilak** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

**Comment by jimschubert** [comment]
This will break the JavaSpring templates… for example:

* https://github.com/OpenAPITools/openapi-generator/blob/0fca90133ce097f987098e6121936c0ffcb210a8/modules/openapi-generator/src/main/resources/JavaSpring/nullableDataType.mustache#L1
* https://github.com/OpenAPITools/openapi-generator/blob/87727de079095a920bc928f6dee33091340484bd/modules/openapi-generator/src/main/resources/Java/pojo.mustache#L59

Maybe a good way around this, since the template modified in this PR is used by multiple library options which apparently provide their own build scripts… would be to fully qualify the occurrences of JsonNullable (change `JsonNullable` to `org.openapitools.jackson.nullable.JsonNullable`).

@cbornet does that seem like a valid fix to get the import out of the shared template?

For anyone affected by this in an already released version, you can create a new directory with a single file called `model.mustache` and the contents of this PR's fix:

```
package {{package}};

import java.util.Objects;
{{#imports}}import {{import}};
{{/imports}}
{{#serializableModel}}
import java.io.Serializable;
{{/serializableModel}}
{{#useBeanValidation}}
import javax.validation.Valid;
import javax.validation.constraints.*;
{{/useBeanValidation}}
{{#performBeanValidation}}
import org.hibernate.validator.constraints.*;
{{/performBeanValidation}}
{{#jackson}}
{{#withXml}}
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
{{/withXml}}
{{/jackson}}
{{#withXml}}
import javax.xml.bind.annotation.*;
{{/withXml}}
{{^parent}}
{{#hateoas}}
import org.springframework.hateoas.ResourceSupport;
{{/hateoas}}
{{/parent}}

{{#models}}
{{#model}}
{{#isEnum}}
{{>enumOuterClass}}
{{/isEnum}}
{{^isEnum}}
{{>pojo}}
{{/isEnum}}
{{/model}}
{{/models}}
```

During generation, pass the new folder to the template directory option for your tool:

* CLI: `-t`
* gradle plugin: `templateDir`
* maven plugin: `templateDirectory` 

The generator should fall back to embedded templates for any not found in the target directory.

**Comment by starwarsjk** [comment]
Hi @jimschubert , 

What about solution like this?
`{{#isNullable}}import org.openapitools.jackson.nullable.JsonNullable;{{/isNullable}}`

@jmini  @cbornet  does this looks like a valid solution?

**Comment by RockyMM** [comment]
To be honest looks fine to me.

**Comment by jimschubert** [comment]
Following up for visibility… 

> What about solution like this?
> `{{#isNullable}}import org.openapitools.jackson.nullable.JsonNullable;{{/isNullable}}`

This would be an excellent option, and users can do this for any version of the tool by extending the templates.

Since this PR would be a breaking change and that hasn't been addressed, I think we'll move forward with #6154 as this would accomplish the same while also moving us toward more vanilla output by default (without the JSON Nullable library).

**Comment by jimschubert** [comment]
Thanks again for the PR. We've merged #6154 so the issue should be addressed in a way that allows for both scenarios.

**Pull request closed without merging**
