### PR TITLE
[rust client] upgrade reqwest crate to 0.11

### PR DESCRIPTION
**Pull request by typester**
This p-r upgrades the reqwest crate to 0.11.

reqwest 0.11 uses tokio 1.0 and it should be totally preferable for most of tokio users.
Also, since 0.11 make multipart support optional, I added it to the features list.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by typester** [comment]
@frol @farcaller @richardwhiuk @paladinzh

**Comment by wing328** [comment]
Thanks for the PR. I don't think it's a breaking change so I'll re-target the PR to master instead.

**Comment by wing328** [comment]
Looks like your PR is based on 5.1.x so I'll keep it that way to avoid merging those sample update (5.1.x) changes back in current master.

I'll merge this and cherry-pick the change into master instead.

**Comment by typester** [comment]
@wing328 No, I would say that this p-r includes a breaking change.

`reqwest 0.11` depends on `tokio 1.0`, while `reqwest 0.10` and earlier depends on `tokio 0.2`.
And `tokio 1.0` and `0.2` cannot be used at the same time unless you use a compatibility layer such as `tokio_compat`.

If the current user is in the `tokio 0.2` codebase, it would be less confusing to continue to use `reqwest 0.10` for this library as well.

That's why I did this p-r for 5.1.x.

**Comment by wing328** [comment]
@typester thanks for the explanation. Let's keep this targeting 5.1.x

**Comment by wing328** [comment]
Travis tests passed via https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/758662988

**Comment by wing328** [comment]
@typester thanks for the PR, which has been included in the v5.1.0 release: https://twitter.com/oas_generator/status/1373636654024380423

**Pull request merged**
