### PR TITLE
[asciidoc] add form params and authorization headers (#4467)

### PR DESCRIPTION
**Pull request by man-at-home**
### PR checklist

- [ x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`,
- [x ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@wing328 @jimschubert @cbornet @ackintosh @jmini @etherealjoy

issue by @mgwoj.

### CODE REVIEW

**Comment by mgwoj** [comment]
Thank you @man-at-home  for the prompt response with fixes.

I have verified your change and I have some doubts.
The security section is defined as
```json
  "security": [
    {
      "bearerAuth": []
    }
  ]
```

but in the generated `index.adoc` file it is
```
== Access

*  *HTTP Basic* Authentication 

```

which is not the same. I think it should be like

```
== Access

*  *Bearer* Authentication 

```

**Comment by mgwoj** [comment]
The request body parameters seems to be fine now.

**Comment by man-at-home** [comment]
honestly the access/authentication is not in my scope for know.

Unfortunately the other docs generators  have no good template for it, so I copied from perl/ruby client mustache template blindly.

Please keep in mind that for know the access section is only a simple main section, 
no auth information on the individual operation is shown.

(any help on this is appreciated of course)

**Comment by mgwoj** [comment]
Now it is generating 
```adoc
== Access


* *Bearer* Authentication 
```

which is sufficient at this moment. Thank you for providing a quick fix.

**Comment by man-at-home** [comment]
ok => ready to merge.

**Comment by wing328** [comment]
@man-at-home thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Pull request merged**
