### PR TITLE
Scala Cask oneOf support

### PR DESCRIPTION
**Pull request by aaronp**
Scala Cask: This PR adds support for using union-types for oneOf requests.

It also updates some scala libraries in the SBT build and addresses a potential name conflict in the generated
code ('errors' has been renamed).

Local regressions tests have been added to cover these cases which are not part of this PR

### PR checklist
 
- [x ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by aaronp** [comment]
As ever, thanks again @wing328  in advance for your time on these PRs. In this case, I look to be getting a spurious Typescript failure ... not sure how to address that?

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/11727815511/job/32669799075?pr=20051

please ignore that for the time being

**Comment by aaronp** [comment]
> https://github.com/OpenAPITools/openapi-generator/actions/runs/11727815511/job/32669799075?pr=20051
> 
> please ignore that for the time being

Ok - thanks. Are merges paused until that's resolved, or can we merge into a broken build for other generators?

**Comment by wing328** [comment]
thanks for the PR

please update https://github.com/OpenAPITools/openapi-generator/blob/master/bin/configs/scala-cask-petstore.yaml

with a new `modules/openapi-generator/src/test/resources/3_0/scala-cask/petstore.yaml` (copied of petstore.yaml) and add some schemas to test oneOf

**Comment by aaronp** [comment]
> thanks for the PR
> 
> please update https://github.com/OpenAPITools/openapi-generator/blob/master/bin/configs/scala-cask-petstore.yaml
> 
> with a new `modules/openapi-generator/src/test/resources/3_0/scala-cask/petstore.yaml` (copied of petstore.yaml) and add some schemas to test oneOf

Excellent shout! Many thanks ... done 👍

**Comment by wing328** [comment]
nice. let's give it a try

**Comment by wing328** [comment]
CI failure fixed via https://github.com/OpenAPITools/openapi-generator/commit/85f711236c9bb1b3a94719c556f41f2ce2b1382d

**Comment by aaronp** [comment]
William, you are an absolute star!

**Pull request merged**
