### PR TITLE
[csharp-netcore] made Validate public.

### PR DESCRIPTION
**Pull request by GregTheMad**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Fix for: https://github.com/OpenAPITools/openapi-generator/issues/10408

@mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti

### CODE REVIEW

**Comment by Blackclaws** [comment]
Hold on, shouldn't they work anyway? Its explicitly implementing an interface. 

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation

Therefore public is not necessary and you can validate it when casting it to IValidatableObject

**Comment by GregTheMad** [comment]
As there is no second interface that has a `Validate()` signature there is no need for explicitly implementing the interface. The opposite actually, hiding interfaces like this, and then requiring a cast every time you use it, seems like bad practice.

**Comment by Blackclaws** [comment]
Yeah, I get your point. I don't have any issue with the change, and I see no reason to keep the method private.

**Comment by wing328** [comment]
@GregTheMad thanks for the contribution, which has been merged into master.

**Pull request merged**
