### PR TITLE
replacing caTools dependency with base64enc

### PR DESCRIPTION
**Pull request by Ramanth**
Replacing caTools with base64enc library
As the caTools has recently upgraded to new version and it is now not available for R versions less than 3.6.1, which is causing installation errors of the R generator on lower R versions.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@wing328  @saigiridhar21

### CODE REVIEW

**Comment by wing328** [comment]
@Ramanth thanks for the PR. Please update the following as well:

https://github.com/OpenAPITools/openapi-generator/blob/ad009180dda867f37e6809c779ae829c167c4425/modules/openapi-generator/src/main/resources/r/description.mustache#L13

https://github.com/OpenAPITools/openapi-generator/blob/6cf58afdc5592198db28d1342be399e7130f31f7/modules/openapi-generator/src/main/resources/r/README.mustache#L29

https://github.com/OpenAPITools/openapi-generator/blob/0cb921251d139a0a0d3e75d4cceb38af4ec54fbb/samples/client/petstore/R/test_petstore.bash#L17

**Comment by wing328** [comment]
CI tests failed:
```
R lib directory: /home/circleci/R
mkdir: cannot create directory ‘/home/circleci/R’: File exists
Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
  cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
Warning message:
package ‘jsonlite’ is not available (for R version 3.4.4) 
Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
  cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
Warning message:
package ‘httr’ is not available (for R version 3.4.4) 
Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
  cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
Warning message:
package ‘testthat’ is not available (for R version 3.4.4) 
Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
  cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
Warning message:
package ‘R6’ is not available (for R version 3.4.4) 
Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
  cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
Warning message:
package ‘base64enc’ is not available (for R version 3.4.4) 
Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
  cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
Warning message:
package ‘rlang’ is not available (for R version 3.4.4) 
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘petstore’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘petstore_1.0.0.tar.gz’

* using log directory ‘/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/R/petstore.Rcheck’
* using R version 3.4.4 (2018-03-15)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using option ‘--no-manual’
* checking for file ‘petstore/DESCRIPTION’ ... OK
* this is package ‘petstore’ version ‘1.0.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... ERROR
Package required but not available: ‘base64enc’

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE

Status: 1 ERROR
See
  ‘/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/R/petstore.Rcheck/00check.log’
for details.

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (nose-test) on project RPetstoreClientTests: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```


Can you please take a look? Does it run without issues locally in your machine?

**Comment by Ramanth** [comment]
> CI tests failed:
> 
> ```
> R lib directory: /home/circleci/R
> mkdir: cannot create directory ‘/home/circleci/R’: File exists
> Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
>   cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
> Warning message:
> package ‘jsonlite’ is not available (for R version 3.4.4) 
> Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
>   cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
> Warning message:
> package ‘httr’ is not available (for R version 3.4.4) 
> Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
>   cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
> Warning message:
> package ‘testthat’ is not available (for R version 3.4.4) 
> Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
>   cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
> Warning message:
> package ‘R6’ is not available (for R version 3.4.4) 
> Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
>   cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
> Warning message:
> package ‘base64enc’ is not available (for R version 3.4.4) 
> Warning: unable to access index for repository http://cran.revolutionanalytics.com/src/contrib:
>   cannot open URL 'http://cran.revolutionanalytics.com/src/contrib/PACKAGES'
> Warning message:
> package ‘rlang’ is not available (for R version 3.4.4) 
> * checking for file ‘./DESCRIPTION’ ... OK
> * preparing ‘petstore’:
> * checking DESCRIPTION meta-information ... OK
> * checking for LF line-endings in source and make files and shell scripts
> * checking for empty or unneeded directories
> * building ‘petstore_1.0.0.tar.gz’
> 
> * using log directory ‘/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/R/petstore.Rcheck’
> * using R version 3.4.4 (2018-03-15)
> * using platform: x86_64-pc-linux-gnu (64-bit)
> * using session charset: UTF-8
> * using option ‘--no-manual’
> * checking for file ‘petstore/DESCRIPTION’ ... OK
> * this is package ‘petstore’ version ‘1.0.0’
> * package encoding: UTF-8
> * checking package namespace information ... OK
> * checking package dependencies ... ERROR
> Package required but not available: ‘base64enc’
> 
> See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
> manual.
> * DONE
> 
> Status: 1 ERROR
> See
>   ‘/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/R/petstore.Rcheck/00check.log’
> for details.
> 
> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (nose-test) on project RPetstoreClientTests: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> ```
> 
> Can you please take a look? Does it run without issues locally in your machine?

it worked on my local and i have checked on 3.5.3 and 3.6.1.
I dont think this change should effect installation of other packages

**Comment by wing328** [comment]
```
* checking package dependencies ... ERROR
Package required but not available: ‘base64enc’
```

looks like it couldn't find the `base64enc` package somehow

**Comment by Ramanth** [comment]
Rscript -e "install.packages('base64enc', repos='$REPO', lib='$R_LIBS_USER')"
This should install the packae, not sure what is getting missed here..

**Comment by Ramanth** [comment]
updated the cran REPO from http://cran.revolutionaryanalytics.com to https://cloud.r-project.org, as i observed the earlier url is failing when used with install.packages command

**Comment by Ramanth** [comment]
@wing328 looks like the checks are passing now.

**Pull request merged**
