### PR TITLE
[JAVA] Use specified data type in enum's fromValue instead of string

### PR DESCRIPTION
**Pull request by bilak**
When working with enums, specifically on web layer, it's better to create enum with target data type instead of string.

### CODE REVIEW

**Comment by wing328** [comment]
@bilak please update the samples so that the CIs can test the change. Let me know if you need help on that.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

**Comment by wing328** [comment]
CircleCI reports the following errors:
```
Tests run: 199, Failures: 0, Errors: 0, Skipped: 7

[ERROR] COMPILATION ERROR : 
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/EnumTest.java:[181,56] incompatible types: java.lang.String cannot be converted to java.lang.Integer
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/EnumTest.java:[232,55] incompatible types: java.lang.String cannot be converted to java.lang.Double
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project petstore-okhttp-gson: Compilation failure: Compilation failure:
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/EnumTest.java:[181,56] incompatible types: java.lang.String cannot be converted to java.lang.Integer
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/EnumTest.java:[232,55] incompatible types: java.lang.String cannot be converted to java.lang.Double
```

**Comment by wing328** [comment]
@bilak I've resolved the issue via https://github.com/OpenAPITools/openapi-generator/pull/2347/commits/66b95d9829f924342cc932ca2db0e237da757676

Please take a look to see if my fix looks good to you.

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) as the fix impacts Java generators (including Spring)

**Comment by bilak** [comment]
I was looking at it and it seems to be ok. 👍

**Comment by wing328** [comment]
@bilak I'll merge after the shippable tests pass

**Comment by jeff9finger** [comment]
👍Great feature!

**Pull request merged**
