### PR TITLE
Add string replace function for C generator

### PR DESCRIPTION
**Pull request by zhemant**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

I have written a replace function to replace basename with parameter name in C Generator

### CODE REVIEW

**Comment by zhemant** [comment]
I will make the changes required for camelcase and spaces. The code you mentioned about goto and in, is replaced completely. Please check the commit @
26fb087 for new code.

**Comment by PowerOfCreation** [comment]
Thank you @zhemant 

Please make smaller commits in the future, it is really hard to see all the changes when one commit has hundreds of lines in changes and makes multiple different changes.

**Comment by wing328** [comment]
About code format/style, we can later leverage `ClangFormat` to format the source code 

Ref: https://clang.llvm.org/docs/ClangFormat.html

**Comment by PowerOfCreation** [comment]
I did use "uncrustify in the past, but if you prefer ClangFormat then we can use that as well.

Uncrustify: http://uncrustify.sourceforge.net/

**Comment by wing328** [comment]
@PowerOfCreation we can support both and let the user choose which one they want to use.

**Comment by wing328** [comment]
The elm issue reported by Travis is not related to this PR.

**Pull request merged**
