### PR TITLE
[Java][Spring] fix one of

### PR DESCRIPTION
**Pull request by Orachigami**
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/2906
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/5381
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/8647
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/8860
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/9601
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/9981

Added tests `oneOfModelsGeneration` for Java Spring and Java Client which iterate through several specs with OneOf usage cases and check that OneOf models are generated and subtypes implement generated models. Java Client test also creates a cartesian product of specs and client libraries for regress tests.

### How inline OneOf models generation is fixed

Added `x-deduction` and `x-deduction-model-names` for `vendorExtensions`. These extensions are used to generated Jackson annotation when the discriminator cannot be used. The discriminator uses the specific field value for deserialization decisions. However, according to the https://swagger.io/specification#discriminator-object first example, `oneOf` can be used without the discriminator object. This case can be handled with Jackson recently added `JsonTypeInfo.Id.DEDUCTION` option. `DEDUCTION` option forces Jackson to make deserialization decisions according to the available fields in the payload and Models which implement `oneOf` interface/class.

### ToDo

* Polymorphic primitives deserialization

### Example output screenshots

<details>
  <summary>Output examples</summary>

<table>
  <tr>
    <th>Specification usage</th>
    <th>OneOf code</th>
    <th>Model code</th>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
   <tr>
      <td></td>
      <td><br></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

</details>

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

### CODE REVIEW

**Comment by wing328** [comment]
@Orachigami thanks for the PR but looks like this PR contains commits not authored by you.

To resolve this, I wonder if you can file a new PR by cherry-picking the commits that belongs to you instead?

Let me know if you need help.

**Comment by rgranadosd** [comment]
Already tested but It isn't working for my example, it doesn't generate the correct classes, in fact, it generates what is currently generating which is classes that don't implement an interface

**Comment by Orachigami** [comment]
@rgranadosd could you please share with me an example with the incorrect output?

**Comment by Orachigami** [comment]
@wing328, it seems that I didn't understand you correctly. My original PR was #10286 against master. [In this thread](https://github.com/OpenAPITools/openapi-generator/pull/10392#pullrequestreview-753724361) , you asked me to:
> Can you please submit a PR against this branch with the suggested fix?

So I recreated PR against `jburgess-spring_fix_5381_jb`. As a result, diff against `master` shows commits from the original `jburgess-spring_fix_5381_jb` branch too.

I will rebase my branch to look like before merge with `jburgess-spring_fix_5381_jb`.

**Comment by Orachigami** [comment]
Moved to https://github.com/OpenAPITools/openapi-generator/pull/10463 as @wing suggested

**Pull request closed without merging**
