### PR TITLE
feat(swift5): allow to swift build in linux

### PR DESCRIPTION
**Pull request by gierschv**
This PR adds the import of FoundationNetworking to the swift 5 templates so we can build the generated code in linux machines & CI.

I noticed that Alamofire recently released to added the linux as well, so it's great to be able to test in our linux CI if the generated code actually builds and has no syntax error (that happens sometimes).

```bash
docker run --rm -v $(pwd):/app -it swift:5.7-jammy bash -c "cd /app/samples/client/petstore/swift5/alamofireLibrary && swift build"

[...]
Build complete! (16.33s)
```

I'm not sure if this project have any Linux CI process to test the generated code, but we could add those `swift build` if any

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@gierschv thanks for the PR. I wonder if you've time to setup a github workflow to test the Swift 5 petstore sample(s) similar to `.github/workflows/samples-php8.yaml`

This can help ensure the swift client built on linux as well as part of this PR.

**Comment by gierschv** [comment]
@wing328 Sure, done!

I tried adding the CI for the other samples on OSX, but ran into some issues importing CoreServices and stuff around mime types (e.g. `UTTypeCreatePreferredIdentifierForTag`) that seems to be proprietary on OSX/iOS - and looks like they need to have probably XCode installed. 
This code looks also a [bit deprecated since iOS 15](https://stackoverflow.com/questions/69540672/ios15-uttype-deprecations-for-url-extension), but new replacing code had the same build issue without XCode.

I ended up only sticking with adding AlamoFire in the CI that have the platform support for Linux. To be honest that's what we use and is more stable.

**Comment by gierschv** [comment]
@wing328 Sure, done!

I tried adding the CI for the other samples on OSX, but ran into some issues importing CoreServices and stuff around mime types (e.g. `UTTypeCreatePreferredIdentifierForTag` in URLSessionImplementations.swift) that seems to be proprietary on OSX/iOS - and looks like they need to have probably XCode installed. This code looks also a [bit deprecated since iOS 15](https://stackoverflow.com/questions/69540672/ios15-uttype-deprecations-for-url-extension), but the new replacing code had the same build issue without XCode.

I ended up only sticking with adding AlamoFire in the CI that have the platform support for Linux.

**Comment by gierschv** [comment]
Trying another CI config for the rest of the clients on OSX, looks the first are correctly building (slower than linux runners).

**Comment by gierschv** [comment]
@wing328 I think we are good to merge. The swift5 samples are now built on OSX + `swift5/alamofireLibrary` that is also built on ubuntu: https://github.com/OpenAPITools/openapi-generator/actions/runs/5794631894?pr=15060

Except `swift5/vaporLibrary` that I didn't put in the CI config for now as this doesn't even `swift build` for me on my macbook (on master or on this PR). That could be for another PR to fix this client implementation later if needed.

**Comment by wing328** [comment]
Agreed that issue has nothing to do with this PR.

Thanks for the PR, which has been merged.

Have a nice weekend.

**Pull request merged**
