### PR TITLE
[java] implement #18032 add builder pattern to java client and spring generator

### PR DESCRIPTION
**Pull request by wing328**
based on https://github.com/OpenAPITools/openapi-generator/pull/18648

Fix https://github.com/OpenAPITools/openapi-generator/issues/18032. Add a new configOptions: generateBuilders to java client and spring generators

The name of the option is the same as in JavaJAXSRSSpecServerCodeGen.

Spring + lombok: generateBuilders + generateConstructorWithAllArgs configOptions can be used instead of lombok.

The builder is not created when lombok.Data is configured (issue with fluent setters not generated)

Improve generation of no args constructor.
Also minor fix for the generateConstructorWithAllArgs and Lombok.AllArgsConstructor (there was some typos)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)
Java Spring | @cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg (2023/08)

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. let's give it a try

**Comment by jpfinne** [comment]
@wing328   The builder option is missing from the 7.6.0 release notes.  
Is that on purpose because it is not production ready?

**Comment by wing328** [comment]
just updated it to highlight this change as well.

(the release notes are only the highlight, not the full list of changes)

**Comment by kevin1chun** [comment]
@wing328 is this available in `java-webclient` as well?

**Comment by jpfinne** [comment]
@kevin1chun I'm the main contributor of this feature.
I've not done tests with java-webclient.  Nevertheless, the WebClient generator shares the same JavaCodeGen and pojo.mustache as the Resttemplate generator. So I would say yes, this is available for you.

Feedbacks are welcome

**Comment by kevin1chun** [comment]
Thanks @jpfinne 
I've successfully integrated the builders into my java-webclient codegen.
It is much cleaner now :)

**Comment by laurentperez** [comment]
Hi

How would you pass the option in the command below ? Both do not produce builder code.

```
java -jar openapi-generator-cli.jar generate -g java -i xxxxx.json --additional-properties=generateBuilders=true -o .

java -jar openapi-generator-cli.jar generate -g java -i xxxx.json -p generateBuilders=true -o 
```

**Comment by jpfinne** [comment]
@laurentperez

You need to add a space after additional-properties:
```
java -jar openapi-generator-cli.jar generate -g java -i xxx.jason -o gen --additional-properties  generateBuilders=true --library resttemplate
``` 
Even if the code is in AbstractJavaCodeGen, not all libraries are tested with the bulder.
resttemplate, native, spring have a pojo.mustache containing these lines:
```
{{#generateBuilders}}
  {{>javaBuilder}}
{{/generateBuilders}}
```
See end of https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/native/pojo.mustache

If you want to the builder in the default java library, you need to take a copy of https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pojo.mustache
and to add the 3 lines with the builder partial.

This can be done with the template customization.  See https://openapi-generator.tech/docs/templating/

**Pull request merged**
