### PR TITLE
Fix: Remove spec 3 references keys in imports for TypeScript

### PR DESCRIPTION
**Pull request by smasala**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
Sanitizes model names by removing `anyOf` and `oneOf` spec reference keys in model imports.

Fixes: https://github.com/OpenAPITools/openapi-generator/issues/1913

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)
--

### CODE REVIEW

**Comment by smasala** [comment]
Override names - requires: https://github.com/OpenAPITools/openapi-generator/pull/2046

**Comment by smasala** [comment]
@wing328 don't think we are going to be able to create a sensible `anyOf|oneOf` implementation with the current template injection methodology... see file changes. Output:

```typescript
import { FirstRuleDefinition | SecondRuleDefinition } from './firstRuleDefinitionSecondRuleDefinition';

export interface CustomRule { 
    ruleId?: string | null;
    definition?: FirstRuleDefinition | SecondRuleDefinition | null;
}
```

This we need to approach this in a new manner.
The imports needs to be an array and the `types` shouldn't be manipulated with strings to get the desires output.

**Comment by wing328** [comment]
Let's have another chat in the coming week when you've time.

**Comment by smasala** [comment]
@wing328 updated the solution. Works for TS

**Comment by macjohnny** [comment]
@smasala could you please fix the merge conflicts?

**Comment by macjohnny** [comment]
@smasala the CI is failing, can you have a look at it?

**Comment by AlexanderSchiff** [comment]
Hello, is there any chance you could release this to the NPM package? as a minor release? Thanks! @wing328 @macjohnny

**Comment by macjohnny** [comment]
this will be released in 4.1.0, probably this week

**Pull request merged**
