### PR TITLE
[csharp] Library upgrade fix

### PR DESCRIPTION
**Pull request by Bouillie**
- Added a target framework: v4.5.2
- Added additionnal properties for each library dependency. The versions and target frameworks for these libraries are now defined in one place in CSharpClientCodegen rather than in multiple separate .mustache files.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @mandrean @jimschubert @frankyjuang @shibayan

### CODE REVIEW

**Comment by Bouillie** [comment]
cc @wing328 
I've found a strange piece of code you added to the bin/csharp-petstore.sh script back in 2018 (commit: 0d913e6801e0): 

`REM restore csproj file
echo "restore csproject file: CI\samples.ci\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj"
copy /b/v/y CI\samples.ci\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools.Test\`

After generating the csharp project, it overwrites the test project file with another one (which causes the compilation error here). I'm not familiar with the structure of the project, so before modifying those scripts, I wanted to ask what you thought was the best thing to do:
- Remove this command from the scripts.
- Replace the project file in the CI directory with an updated one.

In the meantime, I'll just commit the fixed samples, but if we don't take action, the next sample generation will break again.

**Comment by wing328** [comment]
The tests (C#) are restored from `CI\samples.ci` since the tests have been purged/erased many times before.

Please update the C# test files under `CI\samples.ci` as well.

**Comment by Bouillie** [comment]
tests failed on typescript-angular-v7-provided-in-root

**Comment by wing328** [comment]
I've restarted the job. Let's see how it goes.

**Pull request merged**
