### PR TITLE
[Java] Make it possible to disable generation of swagger annotations

### LINKED ISSUE #8719: Make it possible to disable generation of swagger annotations
We are using openapi-generator-maven-plugin to generate Java classes from swagger files. We are not using swagger but Spring rest template + jackson for triggering REST services. 

Code generation works great but unfortunately openapi-generator-maven-plugin always includes swagger annotations in the code. In order for being able to compile the code we have to use the com.google.code.maven-replacer-plugin:replacer maven plugin to get rid of the annoations - otherwise the code does not compile since we don't have any swagger dependencies included (and also can't add them for technical reasons).

Would be great if there would be an option to disable the generation of the annotations since we don't need them.

This is the workaround we are using

```
<plugin>
	<groupId>com.google.code.maven-replacer-plugin</groupId>
	<artifactId>replacer</artifactId>
	<executions>
		<execution>
			<id>removeUnusedAnnotationImports</id>
			<phase>process-resources</phase>
			<goals>
				<goal>replace</goal>
			</goals>
			<configuration>
				<basedir>${project.basedir}</basedir>
				<includes>
					<include>target/generated-sources/openapi/**/*.java</include>
				</includes>
				<regex>false</regex>
				<replacements>
					<replacement>
						<token>import io.swagger.annotations.ApiModel;</token>
						<value />
					</replacement>
					<replacement>
						<token>import io.swagger.annotations.ApiModelProperty;</token>
						<value />
					</replacement>
				</replacements>
			</configuration>
		</execution>
		<execution>
			<id>removeUnusedAnnotations</id>
			<phase>process-resources</phase>
			<goals>
				<goal>replace</goal>
			</goals>
			<configuration>
				<basedir>${project.basedir}</basedir>
				<includes>
					<include>target/generated-sources/openapi/**/*.java</include>
				</includes>
				<replacements>
					<replacement>
						<token>@ApiModel.*\)</token>
						<value />
					</replacement>
				</replacements>
			</configuration>
		</execution>
	</executions>
</plugin>				
```

### PR DESCRIPTION
**Pull request by baurchanu**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Closes #8719 Added 'swaggerAnnotations' option for disabling generation of swagger annotations for 'java' generator

### CODE REVIEW

**Comment by baurchanu** [comment]
Hi, could someone review the PR? The logic of changes is quite simple: I just added a new 'swaggerAnnotations' option to 'java' generator (for back compatibility default is true), and wrapped usages of swagger-annotations  in all templates in 'modules/openapi-generator/src/main/resources/Java' directory, so I assume that it shouldn't take a lot of time to check.

cc @wing328

**Comment by michielboekhoff** [comment]
We would love to see this implemented too!

**Review by AbstractCoderX — APPROVED** [review]
Looks ok

**Comment by baurchanu** [comment]
@wing328 

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

**Comment by alwaysbemark** [comment]
Any progress with this? Would be nice to see this completed.

**Comment by baurchanu** [comment]
@alwaysbemark I'm still waiting for a review. Looks like the java technical committee does not have active members at the moment

**Comment by baurchanu** [comment]
@wing328

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

**Comment by okohub** [comment]
This is very cool. I just wanted to "up" this PR :)

**Comment by Jojal** [comment]
Same for me, this is a great feature, just want to "up" too.

**Comment by typetetris** [comment]
Please review and merge this! Also facing this issue!

**Comment by baurchanu** [comment]
See https://github.com/OpenAPITools/openapi-generator/pull/12422

**Comment by mgohin** [comment]
Nice, I hope it'll be reviewed faster than this one haha :)

**Pull request closed without merging**
