### PR TITLE
[csharp-netcore] HttpClient/Set TimeoutException to inner exception in case of timeout

### PR DESCRIPTION
**Pull request by TORISOUP**
**What is the issue**

- When a timeout occurs due to Configuration.Timeout, a TaskCanceledException is thrown, but this can not distinguish upstream whether it is a manual cancellation or a timeout.

**Correction details**

Changed to TimeoutException is thrown when a timeout occurs due to configuration.Timeout.

**How to validate the work**

- Set an extremely small value (e.g., 1 ms) in configuration.Timeout and execute the communication in production.
- At this time, check that a TimeoutException is thrown and the process is aborted.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mandrean
@shibayan 
@Blackclaws 
@lucamazzanti

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR.

cc @KrzysztofLabus-RDX as well

**Comment by devhl-labs** [comment]
Consider using InnerException so you can return the timeout exception and the task cancelled exception.

**Comment by TORISOUP** [comment]
I' ll change it so the base is a TimeoutException and the inner side is a TaskCanceledException.

**Comment by TORISOUP** [comment]
The same discussion was going on over at .NET Runtime.
I think I will change the TimeoutException to one wrapped in a TaskCancellationException to match this one.

https://github.com/dotnet/runtime/issues/21965
https://github.com/dotnet/runtime/pull/2281

**Comment by TORISOUP** [comment]
I fixed it so that it would be in the same format as .NET Runtime.

**Comment by wing328** [comment]
looks like the build failed:

```
C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Model\ObjectWithDeprecatedFields.cs(149,21): warning CS0612: 'ObjectWithDeprecatedFields.Bars' is obsolete [C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Model\ObjectWithDeprecatedFields.cs(151,50): warning CS0612: 'ObjectWithDeprecatedFields.Bars' is obsolete [C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Client\ApiClient.cs(537,31): error CS1729: 'TaskCanceledException' does not contain a constructor that takes 3 arguments [C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient-httpclient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
Build FAILED.

```
can you please take a look when you've time?

ref: https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/45309197

**Comment by wing328** [comment]
tests passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/46164487

**Comment by wing328** [comment]
cc @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05)

**Pull request merged**
