### PR TITLE
[Java][native] Properly encode exploded query params in url

### LINKED ISSUE #4808: [BUG] [JAVA] Using an object to pass query params ends up using the toString of that class
##### Description

When specifying the query parameters for an endpoint as an object and generate a Java SDK using openapi-generator-cli, it will actually use the class's toString as the query parameter values instead. For example, here is a sample config I have for openapi  version 3.

```
paths:
  /my_endpoint:
    get:
      tags:
        - "MyEndpoint"
      operationId: "getMyEndpoint"
      parameters:
        - in: query
          name: queryParams
          explode: true
          schema:
            type: object
            properties:
              to:
                type: string
              from:
                type: string
```

After generating the java SDK and make a request like so:

```
QueryParams queryParams = new QueryParams();
queryParams.setTo("Person");
MyEndpointSuccessResponse result = apiInstance.getMyEndpoint(queryParams);
```

The request is received by my endpoint, but this is what the query params look like:
`{"query_params"=>"class QueryParams {\n    to: Person\n    from: null\n}"}`

##### openapi-generator version

4.2.1-SNAPSHOT

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate
-i ./local/swagger.yaml
-g java
-o ./local/java
-c ./local/config.json
```

### PR DESCRIPTION
**Pull request by sorin-florea**
Fixes #4808 by properly setting exploded query params

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @wing328

### CODE REVIEW

**Comment by wing328** [comment]
> Do you think this can be released in a patch version as we and others need it?

Sorry I don't think so. You will need to wait for v6.0.0 release or use the customized templates for the time being.

**Comment by Hollerweger** [comment]
I tested with 6.0.0-beta and I sill see the same issue with not exploded params in query url.
eg,;
`http://localhost:54795/client?pageable=class%20Pageable%20%7B%0A%20%20%20%20page%3A%200%0A%20%20%20%20size%3A%201%0A%20%20%20%20sort%3A%20ASC%0A%20%20%20%20sortBy%3A%20null%0A%7D`
instead of 
`http://localhost:54795/client?size=1&page=1`

```
openapi: 3.0.3
paths:
  /client:
    get:
      tags:
        - client
      summary: Get list of Clients
      operationId: getClients
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '202':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientPage'
components:
  schemas:
    Pageable:
      type: object
      properties:
        page:
          type: integer
          default: 0
          minimum: 0
        size:
          type: integer
          default: 20
          minimum: 1
        sort:
          type: string
          enum:
            - ASC
            - DESC
          default: "ASC"
        sortBy:
          type: string
```

**Comment by sorin-florea** [comment]
@Hollerweger This is a because the parameter is defined by `$ref`. I have [this PR](https://github.com/OpenAPITools/openapi-generator/pull/11864) that addresses the issue.

**Comment by Hollerweger** [comment]
Thanks @sorin-florea !
Is there any workaround to define the paging parameters in a object to reference as query parameters in current 5.x.x release?

**Pull request merged**
