### PR TITLE
[C++][Pistache] Do not use JSON for primitive types in request body

### PR DESCRIPTION
**Pull request by muttleyxd**
# PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@ravinikam @stkrwork @etherealjoy @MartinDelille 

### Description of the PR
Request body can contain any input, simple strings, CSV text or something else.

I have specified my request body like this:
```yaml
    requestBody:
      content:
        text/csv:
          schema:
            type: string
```

Is it possible to check for content type of request body in Mustache template?

Current behavior is to parse request's body as if it's json. This causes any request to fall into 400 bad request exception branch, which means user provided handlers aren't executed at all.

### CODE REVIEW

**Comment by etherealjoy** [comment]
@muttleyxd 
Thanks for the PR.
There was no change in the samples code when you ran the shell script, right?

**Comment by muttleyxd** [comment]
@etherealjoy 
It looks like it, I made myself sure twice and it doesn't change samples.
```
$ git symbolic-ref --short HEAD
pistache-body-not-always-json
$ mvn clean install
(...) #long log here
$ ./bin/cpp-pistache-server-petstore.sh
(...) #again a lot of text
$ git status
On branch pistache-body-not-always-json
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   samples/server/petstore/cpp-pistache/.openapi-generator/VERSION

$ git diff
diff --git a/samples/server/petstore/cpp-pistache/.openapi-generator/VERSION b/samples/server/petstore/cpp-pistache/.openapi-generator/VERSION
index 479c313e87..83a328a922 100644
--- a/samples/server/petstore/cpp-pistache/.openapi-generator/VERSION
+++ b/samples/server/petstore/cpp-pistache/.openapi-generator/VERSION
@@ -1 +1 @@
-4.0.3-SNAPSHOT
\ No newline at end of file
+4.1.0-SNAPSHOT
\ No newline at end of file  
```

VERSION has changed, but I don't know whether that's an useful change to commit.

Maybe samples should be extended to include some body parameters with various types (though I don't have a plan for it now)

**Comment by etherealjoy** [comment]
Ok, then no need to cmmit.

**Comment by etherealjoy** [comment]
CI Issues not related to PR

**Comment by wing328** [comment]
@muttleyxd thanks for the PR, which has been included in the 4.1.0 release: https://twitter.com/oas_generator/status/1160000504455319553

**Pull request merged**
