### PR TITLE
[Java] [Native] Add response body to exception message

### PR DESCRIPTION
**Pull request by MosheElisha**
Concatenate the response body to the exception message in case of unsuccessful response.

Implement the simple approach described in issue #8759

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by MosheElisha** [comment]
@bgong-mdsol @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch @spacether @jimschubert mentioning the Java technical committee.

@wing328 I have implemented the simple approach as we discussed.

Please review. Thanks in advance.

**Comment by agilob** [comment]
Can you add a test for it?

**Comment by MosheElisha** [comment]
> Can you add a test for it?

@agilob Sure. I am familiar with tests that verify the template was generated as expected (e.g., `JavaClientCodegenTest`) but I felt that because there is no condition in the template, the generated samples are enough for that.

Are there tests that test the client functionality so I can test the thrown exception? I would be happy to add a test there.
If not, please let me know what kind of test you are looking for and where is best to add them.

Thanks!

**Comment by agilob** [comment]
I was thinking about test of `createApiException` to make sure it returns the format you expect with data you expect. Templates evolve quite fast and that behaviour you added here might change or seem irrelevant to future contributors.

**Comment by MosheElisha** [comment]
> I was thinking about test of `createApiException` to make sure it returns the format you expect with data you expect. Templates evolve quite fast and that behaviour you added here might change or seem irrelevant to future contributors.

@agilob Sure. Where can I add such a test? The code of `createApiException` is only in the template and auto generated in samples files so I'm not sure how to create such a test. Can you point me to a place where similar tests already exist?

**Comment by agilob** [comment]
Some of the samples will be generated to directories with pre-existing manually written code which simply imports generated code and tests it. Unfortunately it's not easy to find them (or I dont know how) so I delete all generated code eg. `samples/` directory, regenerate all samples and check `git status` for which files were removed but not regenerated... If no such sample exists, you can add a new directory with tests inside generated sample project.

I've seen this approach to testing in typescript and we do it in Dart.

**Comment by MosheElisha** [comment]
Thanks, @agilob . I was unable to find such tests for Java. To create such a test for Java, I believe I need to make the generated code available as a maven module before I can create a test that uses it.

@wing328 Please advise.

**Review by agilob — APPROVED** [review]

**Comment by wing328** [comment]
Agreed it's not easy to test. Let's go with what you've so far.

**Comment by Gama11** [comment]
There's another method that creates API exceptions in this template (`getApiException()` within the `asyncNative` block). It seems like you forgot to update its message to the new format?

**Comment by MosheElisha** [comment]
> There's another method that creates API exceptions in this template (`getApiException()` within the `asyncNative` block). It seems like you forgot to update its message to the new format?

Yes, I missed that. Thank you. I don't have the time to do it now. If it is important for you, please go ahead. Thanks.

**Comment by Gama11** [comment]
I created a follow-up PR here, along with a bit of cleanup and also adding the status code to the exception message: #9825

**Pull request merged**
