### PR TITLE
make typescript-fetch code compatiable with nodejs environment

### PR DESCRIPTION
**Pull request by duxiaofeng-github**
`window` should not be used in typescript-fetch because `window` does not exist under node js environment.

According to https://github.com/OpenAPITools/openapi-generator/pull/3326, `fetch` is globally defined in both browser and nodejs.

So we just need to simply use `fetch`.

Also I found out why the `fetch` function need to bind `window` again in the old code.

Because when the `fetch` function passed by the `fetchApi` getter, the `fetch` function will lose its context(window) and cause an error 'Fetch TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation'.

So, **DO NOT** pass the `fetch` function by the `fetchApi` getter, call `fetch` directly wherever it needs to be executed.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@duxiaofeng-github thanks for the PR.

cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

**Review by amakhrov — APPROVED** [review]
Nice catch! Thanks for the fix

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by momesana** [comment]
> LGTM

https://www.youtube.com/watch?v=rR4n-0KYeKQ

The PR broke our code due to fetchApi() not taking in account that the property may be undefined.

**Comment by wing328** [comment]
@duxiaofeng-github have you reviewed https://github.com/OpenAPITools/openapi-generator/pull/10216, which has been merged into master, to see if that fixes the issue you just reported?

**Comment by duxiaofeng-github** [comment]
@wing328 well, my mistake, #10216 should fix @momesana 's issue

**Pull request merged**
