### PR TITLE
[Slim] Models constructor

### PR DESCRIPTION
**Pull request by ybelenko**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
New model template generates file like:
```php
class Animal
{

    /** @var string $className */
    private $className;

    /** @var string $color (optional) Default 'red' */
    private $color = 'red';

    /**
     * Animal constructor
     *
     * @param string $className
     * @param string|null $color (optional) Default 'red'
     */
    public function __construct(
        $className,
        $color = 'red'
    ) {
        $this->className = $className;
        $this->color = $color;
    }

    /**
     * Alternative static class constructor
     *
     * @param mixed[]|null $data Associated array of property values initializing the model
     * @throws InvalidArgumentException when $data doesn't contain required constructor arguments
     * @example $animal = Animal::createFromObject([ 'className' => 'foobar' ]);
     *
     * @return Animal
     */
    public static function createFromObject(array $data = null)
    {
        if ($data['className'] === null) {
            throw new InvalidArgumentException("'className' can't be null");
        }
        $className = $data['className'];
        $color = (isset($data['color'])) ? $data['color'] : 'red';
        return new Animal(
            $className,
            $color
        );
    }
}
```

### Why that way and not another

**Why I think that `private $className` and `private $color` is better than single `$container` from PHPClient codegen:**
1. It's more common and expected for developers, more descriptive, you can say what properties exists with a quick look
2. Most of time developer needs to query database and map result to related model class. For this case there is [PDOStatement::fetchObject()](http://php.net/manual/en/pdostatement.fetchobject.php). Other database drivers(mysqli) has similar methods too.
3. I've quickly checked popular ORMs. [Eloquent](https://laravel.com/docs/5.1/eloquent) have builtin generator to produce models and doesn't follow approuch from this PR. [Doctrine](https://www.doctrine-project.org/) however, creates similar models, example [User.php](https://github.com/1ma/Slim-Doctrine-Demo/blob/master/src/Domain/User.php). The last one [Atlas](http://atlasphp.io/) claims own persistence models with optional fallback to domain models. That domain models looks similar to that PR, example [Map From Persistence To Domain](http://atlasphp.io/cassini/orm/domain.html#1-1-11-5)
4. PhpSymfonyCodegen already produces that kind of [models](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/server/petstore/php-symfony/SymfonyBundle-php/Model/User.php) and it looks like a stable implementation, correct me if I'm wrong

**Why I've added both traditional and associative array constructor in the same class:**
1. I cannot choose one, so I've decided to add `createFromObject` static method when you want to parse JSON and get new model instance as result. I like classic constructor with arguments list more, but I understand that sometimes it doesn't fit.
2. With classic constructor you can see required and optional variables right away.

### Unresolved question to discuss
I can't say for sure that force user to set required arguments is a good idea. I mean sometimes you receive messy JSON object without required fields, if you'll try to parse it via `createFromObject` method your code will die with uncatched exception. From another point, it's very usefull during development to notice missed properties instantly. 
PHPClient throws exceptions when you're trying to set property with setter method, but it gives no exceptions within constructor even if you don't provide any props at all. It doesn't make sense to me. :confused: 
**The question is, should we split arguments to required and optional and throw exceptions right from constructor method OR set all arguments optional and validates them silently with special method `valid()` only when user ask for it?**

### Issues found in process
1. Parser optionalVars.hasMore in models, #710 :bug: 
2. [Slim] Security samples script fails, #734

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh

### CODE REVIEW

**Comment by ackintosh** [comment]
> Why I think that `private $className` and `private $color` is better than single `$container` from PHPClient codegen:

My understanding that why PHPClient uses `$container` is, to make implementing [ArrayAccess](http://php.net/manual/ja/class.arrayaccess.php) interface easy. So `private $className, private $color` is good if the models of Slim doesn't need to implement ArrayAccess. 👍

**Comment by ybelenko** [comment]
> My understanding that why PHPClient uses `$container` is, to make implementing ArrayAccess interface easy. So `private $className, private $color` is good if the models of Slim doesn't need to implement ArrayAccess. +1

@ackintosh Btw, why do you need ArrayAccess in ClientSDK? For HttpGuzzle? Give as an example, when ArrayAccess is convenient.

And you didn't answered to main question:
> **The question is, should we split arguments to required and optional and throw exceptions right from constructor method OR set all arguments optional and validates them silently with special method valid() only when user ask for it?**

**Comment by wing328** [comment]
> @ackintosh Btw, why do you need ArrayAccess in ClientSDK? For HttpGuzzle? Give as an example, when ArrayAccess is convenient.

My understanding is that it's more like preference. Consider the following object definition:
```
  AnimalFarm:
    type: array
    items:
      $ref: '#/definitions/Animal'
```

How would you generate that in your proposed model generation?

**Comment by ybelenko** [comment]
> How would you generate that in your proposed model generation?

Now I see your point. Hmm... Isn't it breaks programming basics? Nobody think about model object as an Array. I can imagine more ridiculous example:
```yaml
definitions:
  Currency:
    type: string
    enum:
      - usd
      - eur
      - gbp
```
And there is no way to create working model for example above. It doesn't have properties it's property by itself. As fallback solution I can do:
```php
class AnimalFarm implements ArrayAccess {}
```
for models which is arrays, but I don't know what to do with silly `Currency` example and others.

**Comment by ybelenko** [comment]
@wing328 
Know what's even more funny? I've used Slim codegen a lot, and I didn't use models at all. I mean I didn't even think that they useful. I've enhanced APIs and middlewares, request validation, authentication, even UnitTests was my primary goal... but models. 

Models very useful for client SDK, no doubts, because you don't know how request object looks like. I would say in most cases you don't even read documentation for API when there is SDK. But when you're provider of API and develop server, then you perfectly know models and properties. In this case I would change `AnimalFarm` definition to object which is more friendly to use. I would change it, because I can and I don't want to create headaches to myself :smile:

**Comment by ybelenko** [comment]
Well, I don't see any way, beside to add generator options to customize models. That's what I think is minimal set of options for models:

### `modelProperties`
Possible values:
* `privateVars` - generate private var for every model prop, eg `private $color = 'red'`
* `protectedVars` - generate protected var for every model prop, eg `protected $color = 'red'`
* `publicVars` - generate public var for every model prop, eg `public $color = 'red'` 
* `protectedContainer` - PHPClient generator way. Generate single `protected $container = []` var for all props
* `none` - don't generate properties

Default: `privateVars`

### `modelConstructorArguments`
Possible values: 
* `listRequiredAndOptional` - generate constructor with list of required and optional arguments. PHP throws error when required aguments of constructor not provided
* `listAllOptional` - generate constructor with list of optional arguments. All of them are optional. This way you can create new instance of model without props and assign them afterwards and not get any PHP errors
* `singleOptionalObject` - PHPClient generator approach. `public function __construct(array $data = null)`
* `none` - don't generate constructor. Can't imagine any real example, but maybe somebody needs it

Default: `listRequiredAndOptional`

### `modelSettersAndGetters`
Possible values: 
* `magicMethods` - `__set` and `__get` PHP magic methods to prevent creating of 100 of setters 
* `gettersAndSetters` - PHPClient approach, create setter and getter function for every prop
* `none` - don't generate setters at all. User can choose `'modelProperties': 'publicVars'` and assign them directly without any methods, or you can set them via constructor only

Default: `magicMethods`

### `modelThrowExceptions`
Possible values:
* `inConstructor` - generated model throws `InvalidArgumentException` when constructor required arguments are invalid or `null`
* `inValidMethod` - generated model throws `Exception` within `valid` public method
* `inSetters` - generated model throws `InvalidArgumentException` when value assigned to required prop is invalid or `null`
* `inConstructorAndSetters` - `inConstructor` and `inSetters` both options applied
* `none` - don't throw exceptions in models

Default: `inValidMethod`

### `modelJsonSerialization`
Possible values:
* `objectSerializer` - use PHPClient `ObjectSerializer` class for models serialization in `jsonSerialize` method
* `jsonMapper` - use [jsonmapper](https://github.com/cweiske/jsonmapper) package for models serialization in `jsonSerialize` method
* `custom` - my own implementation of `jsonSerialize` method, don't know how to call it yet(maybe this option is useless, user can set `none` value and implement own method in mustache)
* `none` - don't generate `jsonSerialize` method

Default: `objectSerializer`

cc @ackintosh

**Comment by ybelenko** [comment]
Doesn't make sense to enhance outdated Slim version anymore. New models will be added to Slim4 generator after launch #3658.

**Pull request closed without merging**
