### PR TITLE
[go-server] update comment

### PR DESCRIPTION
**Pull request by wing328**
a follow up PR to https://github.com/OpenAPITools/openapi-generator/pull/18304/files

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by lwj5** [comment]
Hi @wing328 this doesn't fit the spec. If you look at the files changes on GitHub it does not say generated file

**Comment by wing328** [comment]
ah ok. can you please share the URL to the go spec?

**Comment by wing328** [comment]
i've filed another PR to remove the duplicated line instead: https://github.com/OpenAPITools/openapi-generator/pull/18320/

**Comment by wing328** [comment]
closing this one as i trust that you guys are correct about the requirement in the go spec

**Comment by lwj5** [comment]
I'm out now, but the author's PR first post has the link

**Comment by wing328** [comment]
found it

```
To convey to humans and machine tools that code is generated, generated source should have a line that matches the following regular expression (in Go syntax):

^// Code generated .* DO NOT EDIT\.$
```

**Pull request closed without merging**
