### PR TITLE
[TypeScript-Angular] Add AuthService example to  README.md

### LINKED ISSUE #6086: [REQ] TypeScript Angular README.md add example with authentication service
### Is your feature request related to a problem? Please describe.

Many Angular applications will have an authentication service that manages the API access tokens. Consider the following example, where the ApiModule's `forRoot()` method is used to set the API configuration (basePath, accessToken, etc.) for the application:

```TypeScript
// configuring providers
import { ApiModule, Configuration, ConfigurationParameters } from 'YOUR_API';

export function apiConfigFactory (): Configuration => {
  const params: ConfigurationParameters = {
    // set configuration parameters here.
  }
  return new Configuration(params);
}

@NgModule({
    imports: [ ApiModule.forRoot(apiConfigFactory) ],
    declarations: [ AppComponent ],
    providers: [],
    bootstrap: [ AppComponent ]
})
export class AppModule {}
```

However, in this example, it's not possible to access the `AuthService` already in Angular's AppModule and update the accessToken as soon as the `AuthService` updates it. Similar to what is mentioned in https://github.com/swagger-api/swagger-codegen/issues/5996#issue-240845000.

## Describe the solution you'd like

We should add an example based on [kewur's answer](https://github.com/swagger-api/swagger-codegen/issues/5996#issuecomment-316396326) to the README.md of generated API libraries for Angular/TypeScript.

## Describe alternatives you've considered

n/a

## Additional context

I have a PR ready that adds this example to `README.md`, will link it to this issue.

### PR DESCRIPTION
**Pull request by dennisameling**
Closes #6086 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by dennisameling** [comment]
adding technical committee @amakhrov @petejohansonxo @akehir @topce @macjohnny @Vrolijkx @kenisteward @sebastianhaas @taxpon @TiFu

**Comment by wing328** [comment]
@dennisameling thanks for the PR, which has been included in the v4.3.1 release: https://twitter.com/oas_generator/status/1258057660974329861

**Comment by pbn4** [comment]
Hey just a quick question. What should I do in a case where my AuthService is actually a part of ApiModule?

**Comment by macjohnny** [comment]
@pbn4 this would be a circular dependency. I suggest to generate a separate npm package containing only the `AuthService`

**Pull request merged**
