### PR TITLE
Add packageName configuration to maven

### LINKED ISSUE #2428: [BUG] packageName ignored by maven plugin
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

packageName not used by maven plugin, infrastructure is genereted in default package.

##### openapi-generator version

3.2.2 and 4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url
Maven config
```
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<executions>
    <execution>
        <goals>
            <goal>generate</goal>
        </goals>
        <configuration>
            <inputSpec>${project.basedir}/src/main/resources/swagger.json</inputSpec>
            <generatorName>kotlin</generatorName>
            <configOptions>
                <sourceFolder>src/gen/kotlin/main</sourceFolder>
            </configOptions>
            <packageName>bzh.zomzog.utils</packageName>
            <generateSupportingFiles>true</generateSupportingFiles>
        </configuration>
    </execution>
</executions>
```

##### Command line used for generation

mvn clean install

##### Steps to reproduce

Generate a kotlin client with custom packageName

##### Suggest a fix

Add support of packageName to maven plugin

### PR DESCRIPTION
**Pull request by Zomzog**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Add packageName configuration to maven for Kotlin client generation.

Must fix #2428

@jimschubert @dr4ke616

### CODE REVIEW

**Comment by jimschubert** [comment]
Thanks for the PR. I've skimmed it and it looks good. I'll need to look into unrelated CI failures before merge.

**Comment by wing328** [comment]
@jimschubert I've left a comment in https://github.com/OpenAPITools/openapi-generator/issues/2428#issuecomment-473611246.

If that works, I think we can skip this PR.

**Comment by jimschubert** [comment]
@wing328 Having read that linked issue, I still agree with the approach in this PR. I think we'll also want to add `packageName` as a global option, as I don't think the concern applies only to Kotlin.

Looking at the top-level generators options:

```
openapi-generator-cli generate
                [(-a <authorization> | --auth <authorization>)]
                [--additional-properties <additional properties>...]
                [--api-package <api package>] [--artifact-id <artifact id>]
                [--artifact-version <artifact version>]
                [(-c <configuration file> | --config <configuration file>)]
                [-D <system properties>...]
                [(-g <generator name> | --generator-name <generator name>)]
                [--git-repo-id <git repo id>] [--git-user-id <git user id>]
                [--group-id <group id>] [--http-user-agent <http user agent>]
                (-i <spec file> | --input-spec <spec file>)
                [--ignore-file-override <ignore file override location>]
                [--import-mappings <import mappings>...]
                [--instantiation-types <instantiation types>...]
                [--invoker-package <invoker package>]
                [--language-specific-primitives <language specific primitives>...]
                [--library <library>] [--log-to-stderr]
                [--model-name-prefix <model name prefix>]
                [--model-name-suffix <model name suffix>]
                [--model-package <model package>]
                [(-o <output directory> | --output <output directory>)]
                [--release-note <release note>] [--remove-operation-id-prefix]
                [--reserved-words-mappings <reserved word mappings>...]
                [(-s | --skip-overwrite)] [--skip-validate-spec]
                [(-t <template directory> | --template-dir <template directory>)]
                [--type-mappings <type mappings>...]
```

We have invoker, model, and api packages which can be passed as global configurations. From a user's perspective it would be weird to pass a base package name in a different manner.

I don't believe all generators handle those package options in the same way, so I feel like options for consistency would be to either move model/api/invoker package configuration _out_ of globals or to add `packageName` to globals. Like the globals that exist today, users can still apply the settings via additionalProperties.

If we do go with this approach, we'll want to also add to the Gradle plugin.

**Comment by Zomzog** [comment]
So what is your preferred choice?

**Comment by jimschubert** [comment]
I raised the question with the core team, and was waiting for a response.

For reference, I tested this locally with two maven files:

## go-gin-addl.xml

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.openapitools</groupId>
    <artifactId>go-gin-addl-project</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>sample-project</name>
    <url>http://maven.apache.org</url>
    <build>
        <plugins>
            <!-- activate the plugin -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.0.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <!-- specify the swagger yaml -->
                            <inputSpec>${project.basedir}/swagger.yaml</inputSpec>
                            <generatorName>go-gin-server</generatorName>
                            <output>${project.build.directory}/generated-sources/addl</output>

                            <additionalProperties>
                                <additionalProperty>packageName=jimschubert</additionalProperty>
                            </additionalProperties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

* build with `mvn -f go-gin-addl.xml compile`
* inspect `target/generated-sources/addl/go/api_pet.go`
* `packageName` is set as expected


## go-gin-global.xml

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.openapitools</groupId>
    <artifactId>go-gin-global-project</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>sample-project</name>
    <url>http://maven.apache.org</url>
    <build>
        <plugins>
            <!-- activate the plugin -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.0.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <!-- specify the swagger yaml -->
                            <inputSpec>${project.basedir}/swagger.yaml</inputSpec>
                            <generatorName>go-gin-server</generatorName>
                            <output>${project.build.directory}/generated-sources/global</output>
                            <packageName>jimschubert</packageName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```


* build with `mvn -f go-gin-global.xml compile`
* inspect `target/generated-sources/global/go/api_pet.go`
* `packageName` is set as expected

---

To address the concern about global options not being used by all generators, I've opened #2556 for further discussion.

I'll go ahead and merge this, then make any additional changes to the CLI and Gradle Plugin.

**Comment by q3769-patientpoint** [comment]
I just tried 7.8.0 for Java code gen (Native). The pacakgeName has no effect in or outside configOptions element. Only way to change the base package is using apiPackage/modelPackage/invokerPackage elements inside the configOptions element.

**Pull request merged**
