### PR TITLE
Rust reqwest/api_mustache Missing api Vec in parameter

### PR DESCRIPTION
**Pull request by JRAndreassen**
@frol / @farcaller  / @richardwhiuk / @paladinzh 

Fixed parameters of Array type in "rust/reqwest/api.mustache"

the following definition:
```yaml
        - description: Secret Mode. Mandatory for 'Node-Locked' licensing model.
          in: formData
          items:
            default: PREDEFINED
            enum:
              - PREDEFINED
              - CLIENT
            type: string
          name: nodeSecretMode
          required: false
          type: array

```
Fix for api_mustache ignoring Array's in parameters...
error[E0599]: no method named `join` found for reference `&str` in the current scope
   --> src\apis\product_module_api.rs:110:62
    |
110 |             form_params.insert("nodeSecretMode", param_value.join(",").to_string());
    |                                                              ^^^^ method not found in `&str`
Not using #isListContainer in parameters

Fixed for both standard and "vendorExtensions.x-group-parameters=true"
and compiles under both

### CODE REVIEW

**Comment by wing328** [comment]
@JRAndreassen thanks for the PR. Please run the following to update the samples so that the CI can verify the result:
```
./bin/generate-samples.sh ./bin/configs/rust-reqwest-petstore*
```

(On Windows, please install Git bash to run the above)

**Comment by JRAndreassen** [comment]
I've fixed the errors I can, and run the script.
I saw a couple of other places where there are [supportAsync: "false"], but did not change them...

There are errors in the build that I'm not sure how to fix...
```
# START SCRIPT: /home/circleci/OpenAPITools/openapi-generator/bin/utils/export_generators_readme.sh
Wrote /home/circleci/OpenAPITools/openapi-generator/docs/generators.md
Executed /home/circleci/OpenAPITools/openapi-generator/bin/utils/export_generators_readme.sh successfully!
UNCOMMITTED CHANGES ERROR
```
I tried to run the "ensure-up-to-date", but it fails locally
```
$ bin/utils/ensure-up-to-date
# START SCRIPT: bin/utils/ensure-up-to-date
...
[pool-1-thread-16] Generating elm (outputs to C:\Development\Tools\openapi-generator\samples\openapi3\client\elm)?
[pool-1-thread-30] Generation failed: (RuntimeException) Could not process model 'mammal'.Please make sure that your schema is correct!
java.lang.RuntimeException: Could not process model 'mammal'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:472)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:923)
        at org.openapitools.codegen.cmd.GenerateBatch$GenerationRunner.run(GenerateBatch.java:215)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.openapitools.codegen.DefaultCodegen.addProperties(DefaultCodegen.java:2174)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1999)
        at org.openapitools.codegen.languages.AbstractJavaCodegen.fromModel(AbstractJavaCodegen.java:978)
        at org.openapitools.codegen.languages.JavaClientCodegen.fromModel(JavaClientCodegen.java:680)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1166)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:467)
        ... 5 more
ERROR: One or more generators failed to generate. Halting ensure-up-to-date scripts.
```

Thoughts ?

  JR

**Comment by JRAndreassen** [comment]
@frol / @farcaller / @richardwhiuk / @paladinzh
While I'm waiting for the CI...

I have a couple of things I'd like to change / add to the rust/reqwest client...
1) Split the API methods into:
    - {{{operationId}}}_setparameters(builder, ...) 
         -- Set all parameters
    - {{{operationId}}}(config, ...) 
       -create builder
       - call setparams
       - execute
2) "vendorExtensions.x-group-parameters"
    - add interface to make it more "map" like..   
         - Add ability to set by name: params.Set(name, value)
3) Add "vendorExtensions.x-derive-?" for struct/enum for adding derived methods
4) Add "vendorExtensions.x-api_trait" that generates Trait for API methods
5) Generate #[tests] based on examples in spec file

**Comment by wing328** [comment]
For the errors, I'll take a look in the coming week.

For the suggestions, please open an issue to start the discussion and for tracking purpose.

**Comment by wing328** [comment]
All CI tests passed.

Are the following files added manually?

- samples/client/petstore/rust/reqwest/petstore-async/src/apis/client.rs
- samples/client/petstore/rust/reqwest/petstore/src/apis/client.rs

If yes, what's the purpose of these files?

**Comment by JRAndreassen** [comment]
Hi...
I did not add those...
They must be generated or left-overs from a previous generation..
Sorry
  JR

**Comment by wing328** [comment]
@JRAndreassen No need to sorry. Let me investigate.

**Comment by wing328** [comment]
Tested manually and no compilation issue found: https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/724698912

**Pull request merged**
