### PR TITLE
[java] fixed pojo template for nullable fields

### PR DESCRIPTION
**Pull request by valmoz**
Related to https://github.com/OpenAPITools/openapi-generator/issues/12549 this PR modifies the template to be able to manage also JSON fields explicitly set to null (not only omitted field case).

It uses Gson's "isJsonNull" method to check this case, instead of only checking if the key isn't present.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.0.1) (patch release), `6.1.x` (breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
can you please update the samples so that the CI can verify the result?

**Comment by wing328** [comment]
@valmoz what error did you get?

**Comment by valmoz** [comment]
@wing328 I was able to run it. It seems that my maven kept using the wrong version of Java.

**Comment by valmoz** [comment]
@bbdouglas @sreeshas  @jfiala @lukoyanov @cbornet @jeff9finger  @karismann  @Zomzog @lwlee2608

**Comment by vlauciani** [comment]
up 🙏

**Comment by vlauciani** [comment]
Waiting the merge, I built a docker image with this PR:
- https://hub.docker.com/r/vlauciani/openapi-generator-cli-pr12630

it works very well! 

Thank you @valmoz

**Comment by JamesBarnes88** [comment]
up 🙏

**Comment by wing328** [comment]
@valmoz thanks for the PR, which has been merged.

**Pull request merged**
