### PR TITLE
Fix #6899 - python-flask now uses the pre-existing getter/setter validators

### LINKED ISSUE #6899: [BUG] python-flask ignores missing required fields, and values that don't match enum
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

`python-flask` does not raise errors when required fields are missing, or they don't match a value in an enum.

##### openapi-generator version

```
openapi-generator-cli 5.0.0-SNAPSHOT
  commit : 068ad02
  built  : 2020-07-02T17:04:18Z
```

##### OpenAPI declaration file content or url

```yaml
---
swagger: "2.0"
info:
  description: "API for demonstrating unit test bug"
  version: "1.0.0"
  title: "MWE"
host: "example.com"
basePath: "/v1"
schemes:
- "http"
paths:
  /example:
    post:
      description: "sample call"
      operationId: "sample_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "201":
          description: "pending"
          schema:
            $ref: "#/definitions/example-post-response"
definitions:
  example-post-response:
    type: "object"
    required:
    - "user"
    properties:
      user:
        type: "string"
        example: "User A"
        description: "The user who initiated the request"
        enum:
        - "User B"
        - "User A"
```

##### Command line used for generation

```
docker run --rm \
    -v $PWD:/local \
    openapitools/openapi-generator-cli \
    generate \
    -i /local/mwe.yaml \
    -g python-flask \
    -o /local/out-mwe \
    --package-name example
```    

##### Steps to reproduce

1. Generate the code
2. Modify `example/controllers/default_controller.py`. Replace `do some magic` to instead return `ExamplePostResponse()`
3. `pip install -e output_dir`
4. Run `python -m example`
5. in another terminal run `curl http://localhost:8080/v1/example -d "param1=value1&param2=value2" -X POST -v`
6. Note what's logged in both terminals
7. Retry, but with `ExamplePostResponse(user='value not in enum')`

**expected behavior**

At step 5 the server code should fail to instantiate `ExamplePostResponse()`, because required field `user` is missing.
It should catch this error and return 5XX to curl.

At step 7 the server should fail to instantiate `ExamplePostResponse()` because the field `user` has a value that's not in the enum. It should catch this error and return 5XX to the curl.

**actual behavior**

No error thrown at step 5 or 7. The server returns a non-compliant payload. (Also the HTTP 200 status is not one allowed in the spec.)

##### Related issues/PRs

* [unit tests fail out of the box because required arguments are not included](https://github.com/OpenAPITools/openapi-generator/issues/6885)

* someone added [something to do with enums in flask](https://github.com/OpenAPITools/openapi-generator/commit/12a85bb09d9e8a68bb6c39929d11ec8972b18321). The version I'm using doesn't include that part, but it looks like it provides something you could use, but isn't used automatically out of the box.

##### Suggest a fix

Something like:

```
for each field:
   if field is required and field is not specified:
      raise ValueError
   if field is an enum, and value not in enum:
      raise ValueError
```
Add that here: 

https://github.com/OpenAPITools/openapi-generator/blob/850c958d83b32de9f2274349ef3a111631fd938a/modules/openapi-generator/src/main/resources/python-flask/model.mustache#L62

### PR DESCRIPTION
**Pull request by mdavis-xyz**
Fixes #6899 

Previously, the `python-flask` template had getter and setter functions, which validate that required arguments are passed, and enum values are in the list of accepted options etc.

But these functions were never actually called, because of a one line typo. They were circumvented.

Ideally I'd like to write a unit test to check that if you try to instantiate a model without a required argument, or with an unaccepted enum, that the instantiation fails. But I'm not familiar with how to add tests to this project. 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.: @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)
@wing328

### CODE REVIEW

**Comment by mdavis-xyz** [comment]
The ci/circleci build has failed.

I can't see what went wrong unless I grant CircleCI permission to read and write *all* repositories under my Github profile. I'm not going to do that. Can someone tell me what the error was?

**Comment by Jakesterwars** [comment]
`No cache is found for key: source-v1-pull/6911-ffd96fe1da6b1a90709a78a787d99d4b21408cf2
No cache is found for key: source-v1-pull/6911-
Found a cache from build 17459 at source-v1-
Size: 2.9 GiB
Cached paths:
  * /home/circleci/OpenAPITools/openapi-generator/vendor/bundle
  * /home/circleci/virtualenvs
  * /home/circleci/.m2
  * /home/circleci/.ivy2
  * /home/circleci/.bundle
  * /home/circleci/.go_workspace
  * /home/circleci/.gradle
  * /home/circleci/.cache/bower
  * /home/circleci/OpenAPITools/openapi-generator/.git
  * /home/circleci/.stack
  * /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/haskell-http-client/.stack-work
  * /home/circleci/R

Downloading cache archive...
Unarchiving cache...

Failed to unarchive cache

Error untarring cache: Error extracting tarball /tmp/cache181416927 :  gzip: stdin: unexpected end of file tar: Unexpected EOF in archive tar: Unexpected EOF in archive tar: Error is not recoverable: exiting now : exit status 2`

Failed at a cache state. I also have one open that failed that step and a few others that have recent PRs have failed with the same.

**Comment by mdavis-xyz** [comment]
Ok. That looks like it's unrelated to my change. Phew.

**Comment by wing328** [comment]
The circleci issue (cache) has been fixed in the master. Please pull the latest into your branch by running
```
git pull https://github.com/OpenAPITools/openapi-generator master
```

**Comment by mdavis-xyz** [comment]
Ok, done. All tests pass now.

**Comment by pkucmus** [comment]
Any chance this will be included in a release soon?

**Comment by pkucmus** [comment]
Just tested the thing. It breaks the `from_dict` functionality.
In `util.deserialize_model` there is a:
```
instance = klass()
```
which fails on your version

**Comment by mdavis-xyz** [comment]
Ah, I have seen that `klass()` error before. I was trying to reproduce it from the master branch. That explains way.

When I look at that `klass()` line, I don't see why it should work. We're instantiating a model which may have required values, by passing in no values. That doesn't seem right.

It's not the case that the model class is supposed to be instantiated with no args, then have the args manually populated later, and then have verification after that. If that was the case, we wouldn't have issue #6899 .

Can someone explain how this architecture is meant to work?

**Comment by pkucmus** [comment]
This whole model and base model logic is very redundant, I made a template that generates a Pydantic scheme and Pydantic does the rest. I cant do Java so there is no way for me to deliver that here officially. 
But at this point python-flask generator and from the looks of it other python generators are maybe not broken but not usable.

**Comment by pkucmus** [comment]
Here are my changes is someone is willing to see this to the end, I can't since my lack of Java knowledge: https://github.com/OpenAPITools/openapi-generator/compare/master...pkucmus:fastapi-pydantic?expand=1

**Review by spacether — APPROVED** [review]
This looks great, thank you for your PR!

**Comment by ColeMurray** [comment]
Can we clarify why this was merged with known bugs? 

This breaks existing functionality anywhere `.from_dict` is used as highlighted by @pkucmus.

**Comment by spacether** [comment]
Sorry, I missed that this broke functionality. I missed the comment and all tests passed. Shall we revert it?

**Comment by spacether** [comment]
I am sorry about that. Just reverted this commit in master branch. If someone wants this fix please submit a new PR and fix to_dict

**Pull request merged**
