### PR TITLE
[JAVA][bugfix] Fix OpenAPITools#17757 - Include minimum and maximum values in arrays…

### PR DESCRIPTION
**Pull request by MarBode**
Fixes [17757](https://github.com/OpenAPITools/openapi-generator/issues/17757)

I have adjusted the evaluation of whether the minimum and maximum for numbers in arrays is included or excluded. If exclusiveMinimum is true, inclusive should be false in the annotation.

Technical Committee Java

@cachescrubber @welshm @MelleD @atextor @manedev79 @javisst @borsch @banlevente @Zomzog @martin-mfg

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by MarBode** [comment]
This is the minimal and fastest fix to get the "Kuh vom Eis". I can imagine that there should be a solution which uses also the [beanValidationCore.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/beanValidationCore.mustache#L24), but i did not dig not deeper into the stuff as it is my first contact with the code.

**Review by martin-mfg — APPROVED** [review]
looks good to me

Thank you for the PR!

**Comment by MelleD** [comment]
> This is the minimal and fastest fix to get the "Kuh vom Eis". I can imagine that there should be a solution which uses also the [beanValidationCore.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/beanValidationCore.mustache#L24), but i did not dig deeper into the stuff as it is my first contact with the code.

What I understand is that you have solved it for bean validation in containers like List, Set etc., but not for the "normal" simple bean validation on attribute the problem still exists.

**Comment by MarBode** [comment]
> you have solved it for bean validation in containers like List, Set etc., but not for the "normal" simple bean validation on attribute the problem still exists.

not sure what you mean, but on objectes with a "normal" type like Integer, BigDecimal ... i mean the generated code is correct as then the [beanValidationCore.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/beanValidationCore.mustache#L24) is used, which prints `inclusive = false`, when `exclusiveMinimum` is true

**Pull request merged**
