### PR TITLE
[c++ pistache server] Support basic query handling

### LINKED ISSUE #257: [pistache-server] (C++ stub) - Optional type unknown - compile failed
##### Description

I tried to follow the [OpenAPI V3 tutorial](https://app.swaggerhub.com/help/tutorials/openapi-3-tutorial) but as soon as my openapi file uses the "Query parameters " my generated C++ code does not compile anymore. 

See 

      parameters:
        - name: limit
          in: query
          description: Limits the number of items on a page
          schema:
            type: integer
        - name: offset
          in: query
          description: Specifies the page number of the artists to be displayed
          schema:
            type: integer

Compile command line and error looks like : 

      g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/api/DefaultApi.o api/DefaultApi.cpp
      In file included from api/DefaultApi.cpp:13:0:
      api/DefaultApi.h:72:36: error: ‘Optional’ does not name a type
           virtual void artists_get(const Optional<int32_t> &limit, const Optional<int32_t> &offset, Pistache::

My g++ version is 5.4.0 running on Gnome UBuntu 16.04

Is there any g++ version requirement or something I missed ?

##### openapi-generator version
v3.0.0

##### OpenAPI declaration file content or url

The openapi file is the one posted [here](https://app.swaggerhub.com/help/tutorials/openapi-3-tutorial#creating-an-api-parameters)
See **Parameters** (sorry, the URL seems to be not fully handled)

##### Command line used for generation

      openapi-generator-cli.sh generate -i ../../api-ms1/openapi.yaml -g cpp-pistache-server -c ./config.json -o .

##### Steps to reproduce
Just generate and compile the code

Compile line is almost the standard one :

      g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/api/DefaultApi.o api/DefaultApi.cpp

##### Related issues/PRs
n/a

##### Suggest a fix/enhancement
No additional information

### LINKED ISSUE #638: [C++][Pistache-server] (Type string - format binary) are not well handled - compilation failed
##### Description

The use of a _[type string, format binary]_ inside a body generates a miscalled method \<string\>::fromJson(). 

The method generated is as below (see the call to _newItem.fromJson_)
```
void Body::fromJson(nlohmann::json& val)
{
    if(val.find("binaryDataN2Information") != val.end())
    {
        if(!val["binaryDataN2Information"].is_null())
        {
            std::string newItem;
            newItem.fromJson(val["binaryDataN2Information"]);
            setBinaryDataN2Information( newItem );
        }
    }  
}
```

The compilation error looks like :

```
model/Body.cpp: In member function ‘virtual void com::bcom::amf::microservice::server::ms1::model::Body::fromJson(nlohmann::json&)’:
model/Body.cpp:59:21: error: ‘std::__cxx11::string {aka class std::__cxx11::basic_string<char>}’ has no member named ‘fromJson’
             newItem.fromJson(val["binaryDataN2Information"]);
                     ^
```

##### openapi-generator version

3.1.2-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Check wrong generation of a body containing string/binary type
servers:
  - url: http://localhost:8080
paths:
  /check:
    post:
      summary: see title
      tags:
        - Non UE N2 Message Transfer
      operationId: NonUeN2MessageTransfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: # Request parts
                binaryDataN2Information:
                  type: string
                  format: binary
        required: true
      responses:
        '200':
          description: Non UE N2 Message Transfer successfully initiated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/content'
        default:
          description: Unexpected error


components:
  schemas:
    Bytes:
      format: byte
      type: string

    Content:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/Bytes'
```

```json
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Check wrong generation of a body containing string/binary type"
  },
  "servers": [
    {
      "url": "http://localhost:8080"
    }
  ],
  "paths": {
    "/check": {
      "post": {
        "summary": "see title",
        "tags": [
          "Non UE N2 Message Transfer"
        ],
        "operationId": "NonUeN2MessageTransfer",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "binaryDataN2Information": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Non UE N2 Message Transfer successfully initiated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/content"
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Bytes": {
        "format": "byte",
        "type": "string"
      },
      "Content": {
        "type": "object",
        "properties": {
          "type": {
            "$ref": "#/components/schemas/Bytes"
          }
        }
      }
    }
  }
}
```

##### Command line used for generation

Generate :
```
openapi-generator-cli.sh generate -i ./openapi.yaml -g cpp-pistache-server -c ./config.json -o .
```

Compile :
```
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/model/Body.o model/Body.cpp
```

##### Steps to reproduce

Generate & compile

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

Not sure what we are supposed to do :/

### LINKED ISSUE #768: [C++][Pistache-server] Query parameter Type is not well handled (if not string)
##### Description

When the OpenApi file describes a parameter inside the query, the generator produces the corresponding  code with a wrong type handled (if the current type is not string, for example integer).

The generated **handler** for the query looks like :
```
void Stair1Api::check_query_param_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // **** limit is a Optional<std::string> ****
    auto limit = request.query().get("limit");
    
    try {
      // **** API method is called but the first param should be  Optional<int32_t> ****
      this->check_query_param(limit, response);

    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }
}
```

The  generated _check_query_param_ method prototype looks like :
```
virtual void check_query_param(const Pistache::Optional<int32_t> &limit, Pistache::Http::ResponseWriter &response) = 0;
```

But the **handler** described above call this method with a wrong argument (string instead of int32_t)

The error looks like :
```
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/api/Stair1Api.o api/Stair1Api.cpp
api/Stair1Api.cpp: In member function ‘void com::bcom::amf::microservice::server::ms1::api::Stair1Api::check_query_param_handler(const Pistache::Rest::Request&, Pistache::Http::ResponseWriter)’:
api/Stair1Api.cpp:61:46: error: no matching function for call to ‘com::bcom::amf::microservice::server::ms1::api::Stair1Api::check_query_param(Pistache::Optional<std::__cxx11::basic_string<char> >&, Pistache::Http::ResponseWriter&)’
       this->check_query_param(limit, response);
                                              ^
In file included from api/Stair1Api.cpp:13:0:
api/Stair1Api.h:68:18: note: candidate: virtual void com::bcom::amf::microservice::server::ms1::api::Stair1Api::check_query_param(const Pistache::Optional<int>&, Pistache::Http::ResponseWriter&)
     virtual void check_query_param(const Pistache::Optional<int32_t> &limit, Pistache::Http::ResponseWr
                  ^
api/Stair1Api.h:68:18: note:   no known conversion for argument 1 from ‘Pistache::Optional<std::__cxx11::basic_string<char> >’ to ‘const Pistache::Optional<int>&’
../rules.mk:55: recipe for target 'obj/api/Stair1Api.o' failed

```

##### openapi-generator version

Current master : 3.2.1-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Check query parameter
  description: A simple API to illustrate OpenAPI concepts

servers:
  - url: http://localhost:8080

paths:
  /stair1:
    get:
      description: blabla
      operationId: check_query_param
      tags:
        - Stair1
      parameters:
        - name: limit
          in: query
          description: Limits the number of items on a page
          schema:
            type: integer
      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        default:
          description: unexpected error
```

##### Command line used for generation

Generate :
```
openapi-generator-cli.sh generate -i ./openapi.yaml -g cpp-pistache-server -c ./config.json -o .
```

Compile :
```
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/api/Stair1Api.o api/Stair1Api.cpp
```

##### Steps to reproduce

Generate & Compile

##### Related issues/PRs
#257 

##### Suggest a fix/enhancement

The **handler** method should convert the string read into the appropriate type before calling the API method

### PR DESCRIPTION
**Pull request by etherealjoy**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- Add  helpers for primitive de-serialization
- Remove warnings due to unneeded commas
- Deserialize basic types in queries
- Add dependencies chain for external libraries
- Fixes wrong parameter passed to API Handler
- Splitted the serialization of primitive types which are not handled by the json library

Fixes #257 
Fixes #768 
Fixes #638
@stkrwork @MartinDelille @wing328 @fvarose @ravinikam

### CODE REVIEW

**Comment by etherealjoy** [comment]
@CyrilleBenard
Could you please check if the above items are solved?

**Comment by CyrilleBenard** [comment]
Confirmed, #257 #638 and #768  are fixed with this PR :+1:

**Comment by CyrilleBenard** [comment]
I wonder why you use the Pistache::Some method, could you explain in few words ? (just to improve my knowledge)

**Comment by wing328** [comment]
@etherealjoy thanks again for the PR, which is included in the v3.3.0 minor release: https://twitter.com/oas_generator/status/1046941449609068544

**Pull request merged**
