### PR TITLE
[Rust] Adds UUID support from 'uuid' crate for better compile-time checks

### PR DESCRIPTION
**Pull request by taufik-rama**
Hello :wave: 

I've some changes regarding Rust codegen.
Currently I uses UUID for one of the value, and I think it would be nice if we can get this functionality merged, since `uuid` crate support should already be pretty stable (it's already 1.0), and it provides better compile-time check than plain `String` value

I base this changes from my previous PR on #12409 since it fixes the bug on UUID handling, which is needed here

I don't have much experience on current Java/Mustache codebase :sweat_smile:, so any review/feedback is appreciated

Before
```rust
// Single parameter
#[derive(Clone, Debug, Default)]
pub struct UsersDeleteParams {
    pub id: Option<String>,
    // ...
}

// Multi parameter
pub async fn users_delete(configuration: &configuration::Configuration, id: Option<&str> /* ... */ ) { /* ... */ }
```

After
```rust
// Single parameter
#[derive(Clone, Debug, Default)]
pub struct UsersDeleteParams {
    pub id: Option<Uuid>,
    // ...
}

// Multi parameter
pub async fn users_delete(configuration: &configuration::Configuration, id: Option<Uuid> /* ... */ ) { /* ... */ }
```

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @paladinzh

### CODE REVIEW

**Comment by wing328** [comment]
@taufik-rama thanks for the PR. Can you please resolve the merge conflicts when you've time?

**Comment by taufik-rama** [comment]
@wing328 how would I update the generated samples version?

It seems that I got `6.0.0-SNAPSHOT` version when I tried to update the `samples`, which trips up the CI check which currently generates `6.1.0-SNAPSHOT` version

```diff
diff --git a/samples/server/petstore/rust-server/output/no-example-v3/.openapi-generator/VERSION b/samples/server/petstore/rust-server/output/no-example-v3/.openapi-generator/VERSION
index 5f68295f..66672d4e 100644
--- a/samples/server/petstore/rust-server/output/no-example-v3/.openapi-generator/VERSION
+++ b/samples/server/petstore/rust-server/output/no-example-v3/.openapi-generator/VERSION
@@ -1 +1 @@
-6.0.0-SNAPSHOT
\ No newline at end of file
+6.1.0-SNAPSHOT
\ No newline at end of file
```

I generated the samples using
```shell
$ ./bin/generate-samples.sh bin/configs/rust-*
```

**Comment by wing328** [comment]
@taufik-rama thanks for the PR. I don't think we need another option.

If the string type has the format "uuid", then we can do it in typeMappings: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java#L169

If you change that line to map `UUID` to `uuid::Uuid`, would that meet your requirement?

**Comment by taufik-rama** [comment]
I've moved the PR to #12895 with that changes, seems to still be working fine for my usecase

**Pull request closed without merging**
