### PR TITLE
[Python] Add 'supportLargeModel' tag to handle unusually large OAS data type

### LINKED ISSUE #4600: [BUG][Python] "SyntaxError: more than 255 arguments" when a data type has 255 or more properties
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The Python model.mustache template generates a \_\_init\_\_ function. The function arguments are the properties defined in the data type. However, because the OpenAPI spec does not set a max limit for the number of properties in a data type, this means a data type could have a list of 300 properties. But until version 3.7, python functions cannot have more than 255 arguments. 
The generated python code will fail with a syntax error:
```
SyntaxError: more than 255 arguments
```
Note that as a comparison point, Java also has a limit of 255 function arguments, but the generated Java class does not exhibit a similar problem. The Java constructor is not generated with a long list of arguments.

##### openapi-generator version

4.2.1

##### OpenAPI declaration file content or url

I don't think a OAS content sample is needed. It's obvious from the mustache template that the generated __init__ function could have more than 255 arguments:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model.mustache#L60

##### Steps to reproduce

1) Create a OpenAPI spec with a data type that has 255 or more properties (possibly from "inherited" classes using allOf
2) Run the Python code generator. In the generated model file, the \_\_init\_\_ method will have more than 255 arguments.
3) Try to execute the SDK using Python 3.6 or earlier. The python interpreter will report a syntax err. With python 3.7 and above, the python interpreter will execute without error.

##### Suggest a fix

One workaround is to use Python 3.7 or above. However, several Linux distributions do not support 3.7 yet, so it may be operationally complex to require SDK users to install Python 3.7.
Another workaround is to ensure that OAS data types should not have more than 254 arguments, which is a good idea anyway. The first argument of \_\_init\_\_ is "self", hence 254. This could be documented in the wiki. Having caveats in the wiki would be helpful.
A fix would be to remove the arguments from the \_\_init\_\_ function, but this will break backward compatibility.

### PR DESCRIPTION
**Pull request by sebastien-rosset**
This PR fixes #4600 by introducing a new **supportLargeModel** tag. Some languages have limitations such as max 255 arguments per function (Java, Python < 3.7) or 256 arguments (Eiffel).

This can be a problem for some of the generated code when the OAS data types are unusually large. For example, the Python model.mustache template generates a __init__ function. The function arguments are the properties defined in the data type. However, because the OpenAPI spec does not set a max limit for the number of properties in a data type, this means a data type could have a list of 300 properties. But until version 3.7, python functions cannot have more than 255 arguments.

This PR includes modifications for Python, and potentially in the future it could be done for other languages. This is because every language has its own set of limits.
If the code generator is invoked without the supportLargeModel tag, the generator is exactly the same as before. This ensures this does not break any backward compatibility.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by spacether** [comment]
@sebastianhaas what quantity of arguments are you talking about?
How many of them are required vs optional?
The python-experimental generator passes optional arguments using the kwargs input here:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_init_properties.mustache#L1
So if using it is a possibility, it could reduce the likelihood that you would hit that argument count max
If they were all required, then the python-experimental generator would not solve your problem

**Comment by sebastien-rosset** [comment]
> @sebastien-rosset what quantity of arguments are you talking about?
In one specific OAS spec, I have seen 266 properties. This is a long list of BIOS tokens, where each BIOS token is modeled as a property.

> How many of them are required vs optional?
Most of the arguments are optional.

> The python-experimental generator passes optional arguments using the kwargs input here:
> https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_init_properties.mustache#L1
> So if using it is a possibility, it could reduce the likelihood that you would hit that argument count max
> If all of your arguments are required, then the python-experimental generator will not solve your problem.

This will work for me.

> 
> Also, can you `Copy the Python technical committee to review the pull request` per the PR checklist?

Sure, will do.

**Comment by sebastien-rosset** [comment]
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess @slash-arun @spacether

**Comment by spacether** [comment]
> > @sebastien-rosset what quantity of arguments are you talking about?
> 
> In one specific OAS spec, I have seen 266 properties. This is a long list of BIOS tokens, where each BIOS token is modeled as a property.
> 
> > How many of them are required vs optional?
> 
> Most of the arguments are optional.
> 
> > The python-experimental generator passes optional arguments using the kwargs input here:
> > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_init_properties.mustache#L1
> > So if using it is a possibility, it could reduce the likelihood that you would hit that argument count max
> 
> Yes, that will work. In fact, for other reasons, I am finding out the "python" code generator won't work for me anyway, in particular because it does not handle allOf and discriminators properly. I am assuming most of these enhancements would go in the "python-experimental" area.
> 
> > If all of your arguments are required, then the python-experimental generator will not solve your problem.
> 
> This will work for me, most of the arguments are optional.
> 
> > Also, can you `Copy the Python technical committee to review the pull request` per the PR checklist?
> 
> Sure, will do.

@sebastien-rosset if you need composed schema support for oneOf/anyOf, python-experimental will support it soon per https://github.com/OpenAPITools/openapi-generator/pull/4446

**Comment by sebastien-rosset** [comment]
> @sebastien-rosset if you need composed schema support for oneOf/anyOf, python-experimental will support it soon per #4446

Yes, I am watching this PR, this is great. There is also the related #4454.

**Pull request closed without merging**
