### PR TITLE
feat(rust,client): remove Default derives for structs as per #10845

### PR DESCRIPTION
**Pull request by SorenHolstHansen**
This removes the `Default` derive from #10432 which was a breaking change (see #10845 for a discussion).
This could be added again under a flag, but for now I have removed it as it also lead to compilation issues (see https://github.com/OpenAPITools/openapi-generator/pull/10720#issuecomment-1030671612)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10)

### CODE REVIEW

**Comment by wing328** [comment]
@SorenHolstHansen can you please merge the latest master into your branch and update the samples? Thanks.

https://github.com/OpenAPITools/openapi-generator/actions/runs/5278058007/jobs/9572835468?pr=15856

**Comment by SorenHolstHansen** [comment]
> @SorenHolstHansen can you please merge the latest master into your branch and update the samples? Thanks.
> 
> https://github.com/OpenAPITools/openapi-generator/actions/runs/5278058007/jobs/9572835468?pr=15856

On it

**Comment by SorenHolstHansen** [comment]
@wing328 I have merged master in now

**Comment by wing328** [comment]
can you please update the samples again? 

https://github.com/OpenAPITools/openapi-generator/actions/runs/5290703096/jobs/9588493282?pr=15856

**Comment by wing328** [comment]
samples updated via https://github.com/OpenAPITools/openapi-generator/pull/15856/commits/6d17c26f52d63330f6a96931754b443f0431becf and all tests passed

**Comment by SnGmng** [comment]
Why introduce a breaking change without adding a simple feature flag for it?
The `Default` trait was in this library for 2 (!) years.
Did you consider that reverting such breaking change that was in this library for so long, **is a breaking change itself**?

My whole codebase depended on the `Default` trait. How should i migrate? 

- I cant add the `Default` trait myself because only traits defined in the current crate can be implemented for types defined outside of the crate using the generated api
- Manually writing a wrapper type that implements `Default` for each model defeats the whole purpose of code generation
- Manually specifing all the default values looks really ugly. Example:

Before this PR:
```rust
let result = openapi::apis::file_api::api_v1_files_get(
    &configuration,
    ApiV1FilesGetParams {
        ids: file_ids,
        ..Default::default()
    },
).await?;
```
After this PR:
```rust
let result = openapi::apis::file_api::api_v1_files_get(
    &configuration,
    ApiV1FilesGetParams {
        ids: file_ids,
        page: None,
        page_size: None,
        owner_id: None,
        bucket_id: None,
        is_encoding: None,
        storage_file_period_id: None,
        storage_file_period_mime: None,
        storage_file_period_file_type: None,
        storage_file_period_is_analized: None,
        storage_file_period_is_encoding: None,
        storage_file_period_encoder: None,
        storage_file_period_media_analysis_period_duration: None,
        storage_file_period_media_analysis_period_has_audio: None,
        storage_file_period_media_analysis_period_has_video: None,
        storage_file_period_media_analysis_period_audio_codec_name: None,
        storage_file_period_media_analysis_period_audio_bitrate: None,
        storage_file_period_media_analysis_period_audio_sample_rate_hz: None,
        storage_file_period_media_analysis_period_video_width: None,
        storage_file_period_media_analysis_period_video_height: None,
        storage_file_period_media_analysis_period_video_codec_name: None,
        storage_file_period_media_analysis_period_video_fps: None,
        storage_file_period_media_analysis_period_video_bitrate: None,
        storage_file_period_image_analysis_period_width: None,
        storage_file_period_image_analysis_period_height: None,
        storage_file_period_image_analysis_period_quality: None,
        storage_file_period_image_analysis_period_format: None,
        storage_file_period_image_analysis_period_compression: None,
        storage_file_period_image_analysis_period_color_space: None,
        storage_file_period_encoded_from: None,
        storage_file_period_is_original: None,
        storage_file_period_total_requests: None,
        storage_file_period_replica_period_id: None,
        storage_file_period_replica_period_storage_path: None,
        storage_file_period_replica_period_server_id: None,
        storage_file_period_replica_period_server_host: None,
        storage_file_period_replica_period_server_region: None,
        storage_file_period_replica_period_server_country_code: None,
        storage_file_period_replica_period_state: None,
        storage_file_period_replica_period_deletion_sceduled: None,
        storage_file_period_replica_period_file_name: None,
        storage_file_period_replica_period_bytes_out: None,
        storage_file_period_replica_period_bytes_in: None,
        storage_file_period_replica_period_requests_from: None,
        storage_file_period_replica_period_requests_to: None,
        storage_file_period_replica_period_http_success_status_codes: None,
        storage_file_period_replica_period_http_client_error_status_codes: None,
        storage_file_period_replica_period_http_server_error_status_codes: None,
        sort: None,
        sort_direction: None,
    },
)
.await?;
```

**Pull request merged**
