### PR TITLE
[Kotlin][Bug] Added open, external and internal as reserved keywords for kotlin

### PR DESCRIPTION
**Pull request by nxtstep**
Added `open`, `external` and `internal` as reserved keywords for kotlin.

As a follow-up on https://github.com/OpenAPITools/openapi-generator/issues/5689 and https://github.com/OpenAPITools/openapi-generator/pull/5221

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mention the [technical committee]
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

### CODE REVIEW

**Comment by 4brunu** [comment]
Thank you for opening this PR.
Could you please run those commands and commit the changes?
```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```

**Comment by nxtstep** [comment]
> Thank you for opening this PR.
> Could you please run those commands and commit the changes?
> 
> ```
> ./mvnw clean package 
> ./bin/generate-samples.sh
> ./bin/utils/export_docs_generators.sh
> ```

@4brunu thanks for looking into this one. I did run these command before and have committed these changes arising from it. However it did break the build in equal fashion 🤷 

I'll revert and we'll see if that brings anything 👀

**Comment by 4brunu** [comment]
@nxtstep sorry, but could you please just commit the changes related to kotlin and revert the other ones?

**Comment by 4brunu** [comment]
Looks good to me 👍 
CI failure is not related to this PR.

**Comment by nxtstep** [comment]
> Looks good to me 👍
> CI failure is not related to this PR.

Alrighty, any estimates on when we can see this deployed - as our team kind of needs it yesterday 😬

**Comment by 4brunu** [comment]
> Alrighty, any estimates on when we can see this deployed - as our team kind of needs it yesterday 😬

You can create a jar locally with the command `./mvw package` in your machine and use the jar directly.
Check the multiple installation options in the readme.
https://github.com/OpenAPITools/openapi-generator#1---installation

**Comment by 4brunu** [comment]
@wing328 for me this PR is ready to merge 👍

**Comment by nxtstep** [comment]
> You can create a jar locally with the command ./mvw package in your machine and use the jar directly.
Check the multiple installation options in the readme.
https://github.com/OpenAPITools/openapi-generator#1---installation

I appreciate that, but what about the rest of the 🗺️ ? 😉

**Comment by 4brunu** [comment]
We definitely want to merge this and making this changes available to everyone.
This was just a temporary solution for you while this isn't merged and released.

**Pull request merged**
