### PR TITLE
[BUG] [KOTLIN] Fix default value generation for Kotlin Strings

### PR DESCRIPTION
**Pull request by ahcub**
https://github.com/OpenAPITools/openapi-generator/issues/5772

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc: @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

### CODE REVIEW

**Comment by ahcub** [comment]
@wing328 hi, sorry for tagging, but I thought I can ask your help in merging this PR.
the fix is really simple and at the same time is quite important I believe since it will allow usage of the default variables in the kotlin server generator from openapi spec.

please let me know if you have any additional questions.
the details of the bug and proposed solution are in the description of #5772 GH issue

**Comment by 4brunu** [comment]
Hey, could you please run `./mvnw package && ./bin/kotlin-client-all.sh && ./bin/kotlin-server-petstore.sh && ./bin/kotlin-springboot-petstore-all.sh && ./bin/kotlin-vertx-server-petstore.sh` to update the pet store projects, and commit the changes? Thanks

**Comment by ahcub** [comment]
> ./mvnw package && ./bin/kotlin-client-all.sh && ./bin/kotlin-server-petstore.sh && ./bin/kotlin-springboot-petstore-all.sh && ./bin/kotlin-vertx-server-petstore.sh

added, though, there are no actual code changes, only formatting is slightly different

**Comment by ahcub** [comment]
@4brunu please let me know if the PR looks good now

**Comment by ahcub** [comment]
anyone 🙏

**Comment by 4brunu** [comment]
Did you test this in your local project?
It looks good to me, but it would be nice to see the changes applied in the pet projects, but it looks the pet projects don't have usages related to this.

**Comment by ahcub** [comment]
the change is safe, I know that the reporter of a bug has this change running for a local project, and it works like a charm

**Comment by sylvainmoindron** [comment]
I know the merge is done but i wanted to ask a question before submitting a new bug.
`toDefaultValue`  seems to be used only by the kotlin-spring templates (i could'nt find other usage).
in those template {{{defaultValue}}} is used in the spring annitation resulting to code like `@ApiParam(value = "indicateur de facture/avoir, parc duo, toutes valeur (facture/duo/all)", defaultValue = ""all"")` throwing the following error `An annotation argument must be a compile-time constant`

**Comment by sylvainmoindron** [comment]
in the templates it seem to have two variables  `{{{defaultValue}}}` used in the spring annotation and `{{{defaultvalue}}}` (no camel case here) used in the kotlin code

**Comment by sylvainmoindron** [comment]
I submitted a PR #6101 for my problem

**Comment by wing328** [comment]
@ahcub thanks for the PR, which has been included in the v4.3.1 release: https://twitter.com/oas_generator/status/1258057660974329861

**Pull request merged**
