### PR TITLE
[feat] add zapier response middleware

### PR DESCRIPTION
**Pull request by a-wallen**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by a-wallen** [comment]
closes https://github.com/OpenAPITools/openapi-generator/issues/19300

**Comment by a-wallen** [comment]
cc @valmoz, @emajo

**Comment by a-wallen** [comment]
any idea why https://github.com/OpenAPITools/openapi-generator/pull/19733/commits/0ce2ef7a1ae9c18fb2de4294d59cbaa4ad8a461c is in this (even after this PR landed: https://github.com/OpenAPITools/openapi-generator/pull/19670)

**Comment by wing328** [comment]
> any idea why https://github.com/OpenAPITools/openapi-generator/commit/0ce2ef7a1ae9c18fb2de4294d59cbaa4ad8a461c is in this? (even after this PR landed: https://github.com/OpenAPITools/openapi-generator/pull/19670)

my guess is that you created a new branch based on the branch containing https://github.com/OpenAPITools/openapi-generator/commit/0ce2ef7a1ae9c18fb2de4294d59cbaa4ad8a461c

**Comment by wing328** [comment]
you may want to create a new PR by cherry-picking commits

**Comment by a-wallen** [comment]
I'm closing this since https://github.com/OpenAPITools/openapi-generator/pull/19760 contains a clean branch with the changes + regenerated samples. 

@wing328 I saw that you opened https://github.com/OpenAPITools/openapi-generator/pull/19746 which does the same thing. You got my LGTM if you want to reopen that and land it instead,

**Pull request closed without merging**
