### PR TITLE
[swift5]: support arrays in multipart/form-data

### PR DESCRIPTION
**Pull request by kalinjul**
For an API POST request with content type "multipart/form-data" and an parameter of type: array, the generated Implementations for Swift (Alamofire/UrlsessionImplementation) would crash. 
As array parameters are simply put inside a multipart/form-data request as multiple entries with same key, this PR adds a for loop when we encounter an array.

A bit hard to see in the github diff: I only added 
```swift
for v in (v as? Array ?? [v]) {
```
in both implementations.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@4brunu: mentioning you for review although @wing328 reviewed my last swift PR.

### CODE REVIEW

**Comment by kalinjul** [comment]
I fixed the error on bitrise ci, but now ci/circleci: node3 failed with a timeout which i don't think i have any influence on.
Could we retry?

**Comment by 4brunu** [comment]
I have restarted CI, let's see if now it passes.

**Comment by kalinjul** [comment]
Hmm i don't see anything i could do...  circleci has a timeout, bitrise couldn't download some a dependency.
If you have any idea whether this can be my code's fault, please let me know :)

**Comment by 4brunu** [comment]
Did you tested this in your project?
With this change, we don't support dictionary yet, right?
Would it be hard to support dictionaries?

**Comment by wing328** [comment]
Restarted bitrise.io and the build passed.

CircleCI node 3 failure cannot be ignored.

**Comment by 4brunu** [comment]
The errors in `ci/circleci: node3` seems related to JavaScript tests, I think it's not related to this PR, or is it?

```
Running tests...

Running 2 test files...


dist/isomorphic-fetch.test.js:

 ❌ Isomorphic Fetch > GET-Request
      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
        at createTimeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:243195)
        at Ty.Gg._timeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:259145)
        at node_modules/@web/test-runner-mocha/dist/autorun.js:1:257217

 ❌ Isomorphic Fetch > POST-Request
      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
        at createTimeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:243195)
        at Ty.Gg._timeoutError (node_modules/@web/test-runner-mocha/dist/autorun.js:1:259145)
        at node_modules/@web/test-runner-mocha/dist/autorun.js:1:257217

Chromium: |██████████████████████████████| 2/2 test files | 10 passed, 2 failed

Finished running tests in 4.6s with 2 failed tests.
```

**Comment by kalinjul** [comment]
> Did you tested this in your project? With this change, we don't support dictionary yet, right? Would it be hard to support dictionaries?

Yes, i tested this in my project. OpenApi Generator generates array parameters, so i added the array case. For dictionaries, i guess we would need some flag in the generator? Do you mean passing a dict as single parameter or instead of all the single parameters for a multipart query?

I still don't know what i can do about the javascript timeouts...

**Comment by 4brunu** [comment]
I think the CI failure is not related, but let's wait to see the opinion of @wing328.

Maybe we can add support for dictionaries once someone needs it.

**Comment by kalinjul** [comment]
Tests are green now after rebasing to master

**Review by 4brunu — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
