### PR TITLE
Something in the dependencies changed. This switch is no longer needed.

### PR DESCRIPTION
**Pull request by Drezil**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Implemented fix for https://github.com/OpenAPITools/openapi-generator/issues/1849

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by Drezil** [comment]
Oh. Forgot to add that email-address to my profile. Fixed now. Thanks for the notice.

**Comment by wing328** [comment]
cc @jonschoning @algas

**Comment by wing328** [comment]
Build passed locally:
```
➜  haskell-servant git:(Drezil-master) stack test
openapi-petstore-0.1.0.0: configure (lib)
Configuring openapi-petstore-0.1.0.0...
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
openapi-petstore-0.1.0.0: build (lib)
Preprocessing library for openapi-petstore-0.1.0.0..
Building library for openapi-petstore-0.1.0.0..
[1 of 2] Compiling OpenAPIPetstore.Types ( lib/OpenAPIPetstore/Types.hs, .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/OpenAPIPetstore/Types.o )
[2 of 2] Compiling OpenAPIPetstore.API ( lib/OpenAPIPetstore/API.hs, .stack-work/dist/x86_64-osx/Cabal-2.2.0.1/build/OpenAPIPetstore/API.o )
openapi-petstore-0.1.0.0: copy/register
Installing library in /Users/williamcheng/Code/openapi-generator/samples/server/petstore/haskell-servant/.stack-work/install/x86_64-osx/lts-12.18/8.4.4/lib/x86_64-osx-ghc-8.4.4/openapi-petstore-0.1.0.0-HC9DnrEnAtD3ME0hmTe0rs
Registering library for openapi-petstore-0.1.0.0..
```

**Pull request merged**
