### PR TITLE
Add List & ClassVar to always import typing modules

### PR DESCRIPTION
**Pull request by dcermak**
With c6e9a4e1ae87793dda3b251e38b7fe6d636863b9 the __typing class variable got added to the Python models. However, that commit did not properly add the `ClassVar` and `List` imports to, at least not in all conditions. This results in broken models where the imported Model breaks as the type hint is undefined.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @krjakbrjak @wing328

### CODE REVIEW

**Comment by wing328** [comment]
cc @cbornet (2017/09) @tomplus (2018/10) @krjakbrjak (2023/02) @fa0311 (2023/10) @multani (2023/10)

**Comment by wing328** [comment]
> However, that commit did not properly add the ClassVar and List imports to, at least not in all conditions. This results in broken models where the imported Model breaks as the type hint is undefined.

thanks for the PR. can you please share a spec to reproduce the issue?

**Comment by dcermak** [comment]
> > However, that commit did not properly add the ClassVar and List imports to, at least not in all conditions. This results in broken models where the imported Model breaks as the type hint is undefined.
> 
> thanks for the PR. can you please share a spec to reproduce the issue?

certainly:
```bash
podman run --pull=always --rm -v $(pwd):/local:Z \
                                 docker.io/openapitools/openapi-generator-cli generate \
                                   -i https://src.opensuse.org/swagger.v1.json \
                                   -g python --library asyncio -o /local/ \
                                   -p packageName=py_gitea_opensuse_org \
                                   --git-repo-id py-gitea-opensuse-org \
                                   --git-user-id dcermak \
                                   --additional-properties=packageVersion=$(curl https://src.opensuse.org/swagger.v1.json | jq '.info.version'|sed 's/"//g')

flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
```


The second command causes plenty of errors of the form:
```
./py_gitea_opensuse_org/models/access_token.py:38:19: F821 undefined name 'ClassVar'
    __properties: ClassVar[List[str]] = ["id", "name", "scopes", "sha1", "token_last_eight"]
                  ^
./py_gitea_opensuse_org/models/activity.py:49:19: F821 undefined name 'ClassVar'
    __properties: ClassVar[List[str]] = ["act_user", "act_user_id", "comment", "comment_id", "content", "created", "id", "is_private", "op_type", "ref_name", "repo", "repo_id", "user_id"]
```

**Comment by wing328** [comment]
I saw some fixes (merged) related to that earlier. Have you tried the latest master (docker image or CLI for example) to see if the issue still persists?

**Comment by dcermak** [comment]
Yes, I ran the above code before posting this comment.

**Comment by fa0311** [comment]
I have confirmed that the relevant error occurs when isAdditionalProperties is False.
However, I am getting unnecessary imports when the model is oneOf, anyOf, or Enum, can that be fixed?

**Comment by dcermak** [comment]
> However, I am getting unnecessary imports when the model is oneOf, anyOf, or Enum, can that be fixed?

Yes, should be fixed now

**Comment by wing328** [comment]
Can you please resolve the merge conflicts when you've time? Thank you.

**Comment by fa0311** [comment]
This may have been fixed in a recent change (#16802).

**Comment by dcermak** [comment]
It looks like #16802 fixed the underlying issue

**Pull request closed without merging**
