### PR TITLE
Samples for aspnetcore seperate model projects

### PR DESCRIPTION
**Pull request by knom**
Added a CI build and sample generators for #13024

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Adding @wing328

### CODE REVIEW

**Comment by wing328** [comment]
```
--- a/samples/server/petstore/aspnetcore-6.0-project4Models/.openapi-generator/FILES
+++ b/samples/server/petstore/aspnetcore-6.0-project4Models/.openapi-generator/FILES
@@ -1,4 +1,3 @@
-.openapi-generator-ignore
 Org.OpenAPITools.sln
 README.md
 build.bat
Perform git status
HEAD detached at pull/1[30](https://github.com/OpenAPITools/openapi-generator/runs/7591334046?check_suite_focus=true#step:6:31)44/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   samples/server/petstore/aspnetcore-6.0-project4Models/.openapi-generator/FILES

no changes added to commit (use "git add" and/or "git commit -a")v
```

can you please update the sample again?

ref: https://github.com/OpenAPITools/openapi-generator/runs/7591334046?check_suite_focus=true

**Comment by knom** [comment]
@wing328 all done!

**Comment by wing328** [comment]
I tried to build the solution locally but got the following errors:
```
/Users/williamcheng/Code/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj: Error NU1105: Unable to find project information for '/Users/williamcheng/Code/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore. (NU1105) (Org.OpenAPITools)
```

Are you able to build the solution in your environment?

**Comment by knom** [comment]
wow.. that is a catch. 👍of course I tried to build but not on Linux.. will try to repro. Holen Sie sich Outlook für Android

**Comment by wing328** [comment]
OK. 

FYI. I'm using Visual Studio for Mac 8.10.25

**Comment by knom** [comment]
Weird..

@wing328 - this is my outcome, which is some WARNINGS, but 0 ERRORS.

```
  Determining projects to restore...
  Restored /home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj (in 1.34 sec).
  Restored /home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj (in 1.34 sec).
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Order.cs(162,21): warning CS8073: The result of the expression is always 'true' since a value of type 'DateTime' is never equal to 'null' of type 'DateTime?' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Order.cs(193,25): warning CS8073: The result of the expression is always 'true' since a value of type 'DateTime' is never equal to 'null' of type 'DateTime?' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj]
  Org.OpenAPITools.Models -> /home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/bin/Debug/net6.0/Org.OpenAPITools.Models.dll
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs(9,18): warning CS1591: Missing XML comment for publicly visible type or member 'InputFormatterStream' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs(11,16): warning CS1591: Missing XML comment for publicly visible type or member 'InputFormatterStream.InputFormatterStream()' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs(17,33): warning CS1591: Missing XML comment for publicly visible type or member 'InputFormatterStream.CanReadType(Type)' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs(27,52): warning CS1591: Missing XML comment for publicly visible type or member 'InputFormatterStream.ReadRequestBodyAsync(InputFormatterContext)' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
  Org.OpenAPITools -> /home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/bin/Debug/net6.0/Org.OpenAPITools.dll

Build succeeded.

/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Order.cs(162,21): warning CS8073: The result of the expression is always 'true' since a value of type 'DateTime' is never equal to 'null' of type 'DateTime?' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Order.cs(193,25): warning CS8073: The result of the expression is always 'true' since a value of type 'DateTime' is never equal to 'null' of type 'DateTime?' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs(9,18): warning CS1591: Missing XML comment for publicly visible type or member 'InputFormatterStream' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs(11,16): warning CS1591: Missing XML comment for publicly visible type or member 'InputFormatterStream.InputFormatterStream()' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs(17,33): warning CS1591: Missing XML comment for publicly visible type or member 'InputFormatterStream.CanReadType(Type)' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Formatters/InputFormatterStream.cs(27,52): warning CS1591: Missing XML comment for publicly visible type or member 'InputFormatterStream.ReadRequestBodyAsync(InputFormatterContext)' [/home/knom/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
    6 Warning(s)
    0 Error(s)

Time Elapsed 00:00:15.97
```

**Comment by knom** [comment]
@wing328 
Trying to debug the issues...
Does that file exist in your local FS?

```
/Users/williamcheng/Code/openapi-generator/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj
```

thx.

**Comment by wing328** [comment]
The file is there:
```
openapi-generator4 git:(knom-aspnetcore-model-package2) ls -l samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj
-rw-r--r--  1 williamcheng  staff  1133 Aug  5 00:33 samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj
```

and the error message is
```
/Users/williamcheng/Code/openapi-generator4/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools/Org.OpenAPITools.csproj: Error NU1105: Unable to find project information for '/Users/williamcheng/Code/openapi-generator4/samples/server/petstore/aspnetcore-6.0-project4Models/src/Org.OpenAPITools.Models/Org.OpenAPITools.Models.csproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore. (NU1105) (Org.OpenAPITools)
```

(I did another test in a different folder and still got the same result)

**Comment by knom** [comment]
Ah.. I get it..
I forgot to add it in the SLN file..
which Visual Studio Mac seems to use...

**Comment by knom** [comment]
@wing328 please retry.

And maybe also try w. build.sh?

**Comment by wing328** [comment]
Confirmed no longer seeing the issue with the latest.

`build.sh` also works.

**Pull request merged**
