### PR TITLE
[kotlin] Recognize more json media types in response

### PR DESCRIPTION
**Pull request by sheepdreamofandroids**
Instead of matching the mediatype against "application/json" it now matches with "application/*json" so vendor specific json mediatypes like "application/vnd.shopping.cart.v2+json" will also be recognized and deserialized. It doesn't map mediatypes to different models.
This would accept malformed mediatypes as well but that doesn't seem harmful.
I'm using a similarly patched template in a project.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
    @jimschubert
    @dr4ke616
    @karismann
    @Zomzog
    @andrewemery
    @4brunu
    @yutaka0m

### CODE REVIEW

**Comment by sheepdreamofandroids** [comment]
I don't think the failure in AppVeyor is related to my changes.

**Comment by 4brunu** [comment]
Hi, thanks for opening this PR.
The CI failure is not related to this PR.
I have no experience vendor specific json media types, so it's hard for me to review it.
Looking at the code it makes sense, and I understand the reasoning behind it.
Did you tested this with any vendor specific json media type?

**Comment by sheepdreamofandroids** [comment]
Hi @4brunu . My only experience with vendor specific mediatypes is an in-house api using one.

There is some documentation here: https://www.rfc-editor.org/rfc/rfc6838.html#section-4.2.8 which suggests that the used condition should work. Alternatively maybe even only checking for a "/json" or "+json" suffix would be enough. But I prefer another PR if that is ever necessary.

This PR is actually a subset of the changes we made to the templates that are running in production here. The other changes are about the same change for the request body and sending requests fully asynchronous. Those will be separate PR's.

**Comment by sheepdreamofandroids** [comment]
I see that I made a mistake when copying some of the changes. 
I'll create a new PR that corrects those.

**Pull request closed without merging**
