### PR TITLE
3.1.2 patch release

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.2.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by jmini** [comment]
Checked merged PRs without milestone => added where missing.

**Comment by jmini** [comment]
Merge `master` into `3.2.x` before this PR to be sure to have everything. I will redo it after the release. to create the "Prepare release 3.2.0 PR".

**Comment by jmini** [comment]
Tag `v3.1.2` created and pushed.
Publish @wing328's release notes: https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.1.2

**Comment by jmini** [comment]
Follow up PR https://github.com/OpenAPITools/openapi-generator/pull/651

**Comment by jmini** [comment]
Status:

```
$ ruby bin/utils/release_checkout.rb 3.1.2
Running checkout on OpenAPI Generator release 3.1.2
Checking homebrew forumla ... [ERROR]
> https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/openapi-generator.rb not yet updated with https://search.maven.org/remotecontent?filepath=org/openapitools/openapi-generator-cli/3.1.2/openapi-generator-cli-3.1.2.jar
Checking openapi-generator JAR ... [OK]
Checking openapi-generator-cli JAR ... [OK]
Checking openapi-generator-maven-plugin JAR ... [OK]
Checking openapi-generator-gradle-plugin JAR ... [ERROR]
> http://central.maven.org/maven2/org/openapitools/openapi-generator-gradle-plugin/3.1.2/openapi-generator-gradle-plugin-3.1.2.jar not found
Checking openapi-generator-online JAR ... [OK]
Checking openapi-generator-project pom.xml ... [OK]
Checking openapi-generator README.md ... [OK]
Checking openapi-generator-online docker ... [OK]
Checking openapi-generator-cli docker ... [OK]
```

**Comment by jmini** [comment]
Removed `3.2.x`, all PR for this branch are now for master

**Comment by jmini** [comment]
Merged `master` into `4.0.x`.

**Comment by jmini** [comment]
Gradle plugin is published on `sonatype - releases` repository: [openapi-generator-gradle-plugin - 3.1.2](https://oss.sonatype.org/content/repositories/releases/org/openapitools/openapi-generator-gradle-plugin/3.1.2/)
```
https://oss.sonatype.org/content/repositories/releases/
```

I hope it will appear on Maven Central soon.

@wing328 has opened a PR for homebrew: Homebrew/homebrew-core#30488

**Comment by wing328** [comment]
UPDATE: https://github.com/Homebrew/homebrew-core/pull/30488 has been merged.

**Comment by jmini** [comment]
Closed milestone [3.1.2](https://github.com/OpenAPITools/openapi-generator/milestone/9)

**Comment by jmini** [comment]
Gradle plugin was copied to maven central.

```
$ ruby bin/utils/release_checkout.rb 3.1.2
Running checkout on OpenAPI Generator release 3.1.2
Checking homebrew forumla ... [OK]
Checking openapi-generator JAR ... [OK]
Checking openapi-generator-cli JAR ... [OK]
Checking openapi-generator-maven-plugin JAR ... [OK]
Checking openapi-generator-gradle-plugin JAR ... [OK]
Checking openapi-generator-online JAR ... [OK]
Checking openapi-generator-project pom.xml ... [OK]
Checking openapi-generator README.md ... [OK]
Checking openapi-generator-online docker ... [OK]
Checking openapi-generator-cli docker ... [OK]
```

Release 3.1.2 is now good!

**Pull request merged**
