### PR TITLE
Clean up file output handling

### PR DESCRIPTION
**Pull request by jimschubert**
This attempts to normalize all generators to use OS agnostic
File.separator.

It also fixes a bug in some areas in code where we replace "." in full file
output path with File.separator. We should only be modifying directory
names we own, and should avoid modifying anything that can be provided
by a user.

It would probably be better to use Paths.get(…).toString() in all cases.

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by jimschubert** [comment]
This should fix #1834.

**Comment by jimschubert** [comment]
@wing328 no problem. I've fixed merge conflicts.

To repro #1834, you can use `-o some.dir` on master and supporting files will write to `some.dir` while model/apis will write to `some/dir`. This was all in AbstractJavaCodegen.java.  Other files were normalization of `File.separator` and usually moving parens so we didn't modify the user-specified `outputFolder` value.

**Comment by ackintosh** [comment]
https://travis-ci.org/OpenAPITools/openapi-generator/builds/478650968?utm_source=github_status&utm_medium=notification

It seems the issue that fixed in #1863 occurs again. 👀

**Comment by wing328** [comment]
and here are the errors reported by Travis (and other CIs):
```
[ERROR] Tests run: 520, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 11.875 s <<< FAILURE! - in TestSuite
[ERROR] apiFileFolder(org.openapitools.codegen.java.AbstractJavaCodegenTest)  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.AssertionError: expected [/User/open.api.tools/source.folder/org/openapitools/codegen/api] but found [/User/open.api.tools/source/folder/org/openapitools/codegen/api]
	at org.openapitools.codegen.java.AbstractJavaCodegenTest.apiFileFolder(AbstractJavaCodegenTest.java:167)
[ERROR] apiTestFileFolder(org.openapitools.codegen.java.AbstractJavaCodegenTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: expected [/User/open.api.tools/test.folder/org/openapitools/codegen/api] but found [/User/open.api.tools/test/folder/org/openapitools/codegen/api]
	at org.openapitools.codegen.java.AbstractJavaCodegenTest.apiTestFileFolder(AbstractJavaCodegenTest.java:176)
[ERROR] modelFileFolder(org.openapitools.codegen.java.AbstractJavaCodegenTest)  Time elapsed: 0.001 s  <<< FAILURE!
java.lang.AssertionError: expected [/User/open.api.tools/source.folder/org/openapitools/codegen/model] but found [/User/open.api.tools/source/folder/org/openapitools/codegen/model]
	at org.openapitools.codegen.java.AbstractJavaCodegenTest.modelFileFolder(AbstractJavaCodegenTest.java:194)
[ERROR] modelTestFileFolder(org.openapitools.codegen.java.AbstractJavaCodegenTest)  Time elapsed: 0 s  <<< FAILURE!
java.lang.AssertionError: expected [/User/open.api.tools/test.folder/org/openapitools/codegen/model] but found [/User/open.api.tools/test/folder/org/openapitools/codegen/model]
	at org.openapitools.codegen.java.AbstractJavaCodegenTest.modelTestFileFolder(AbstractJavaCodegenTest.java:185)
```

**Comment by jimschubert** [comment]
Sorry about that. I merged in master to fix the file conflicts and it introduced another path replacement and groupings ended up shifting during merge.

I'm currently needing to push to remote in order to have tests run, because after evaluating the Guava issue with Android Gradle Plugin, the test suite locks up on my machine.

**Comment by jimschubert** [comment]
Last commit should fix the shippable issue for Windows.  I have concerns that a user on Windows would never provide a path like `/Users/jim/path` and require a `/` replacement to `\`. Considering `/` is an invalid path character in Windows I think this is fine from a testing perspective. However, most generators _don't_ do this, so we may want to either update this universally across all generators or do it in DefaultGenerator before using these values.

**Comment by jimschubert** [comment]
As mentioned above, and discussed in chat, I've used `Paths.get` at the point of writing files to cover 
normalization of path for all generators.

This resolves an issue, for instance when you do `Paths.get("C:/Users/jim/mypath")` on Windows in any generator, we expect to write to `C:\Users\jim\mypath`. This should also handle normalizing filenames with spaces in all operating systems.  Using `Paths.get` will also expose a better exception for invalid path characters, which should help us to track down issues with path characters a little better in the future.

**Pull request merged**
