### PR TITLE
Fix #8890 (part 2) in every JaxRS pom.mustache templates

### LINKED ISSUE #8890: [BUG] Jaxrs-Jersey produces server that doesn't compile + doesn't handle parent tag in pom.xml correctly
##### Description

I've been testing out `openapi-generator` but have come up against a few issues, which I've repro'd using the petstore example found at  https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml. I've been trying out server generation by running `openapi-generator generate -i petstore.yaml -g jaxrs-jersey -o server`, but have encountered the following issues:
1. After generation, when I run `mvn clean package jetty:run` as instructed by the generated README, I get the following compilation error:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] ~/repos/OpenAPI-Specification/examples/v3.0/server/src/gen/java/org/openapitools/api/ApiResponseMessage.java:[3,33] package javax.xml.bind.annotation does not exist
[ERROR] ~/repos/OpenAPI-Specification/examples/v3.0/server/src/gen/java/org/openapitools/api/ApiResponseMessage.java:[5,27] package javax.xml.bind.annotation does not exist
[ERROR] ~/repos/OpenAPI-Specification/examples/v3.0/server/src/gen/java/org/openapitools/api/ApiResponseMessage.java:[45,6] cannot find symbol
  symbol:   class XmlTransient
  location: class org.openapitools.api.ApiResponseMessage
```
2. If I run the generation step with `openapi-generator generate -i petstore.yaml -g jaxrs-jersey -o server --additional-properties=parentArtifactId=parent-artifact,parentGroupId=parent-group,parentVersion=1.0-SNAPSHOT`, then I don't see any `parent` tag in the generated `pom.xml` (as expected after reading the docs at https://openapi-generator.tech/docs/generators/jaxrs-jersey/). This is also true with the `jaxrs-resteasy` generator (where, again, the docs at https://openapi-generator.tech/docs/generators/jaxrs-resteasy/ say it's an available option).

##### openapi-generator version
```
> openapi-generator version
5.0.1
```

##### OpenAPI declaration file content or url

Repro'd with the petstore example:
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

##### Generation Details

`openapi-generator generate -i petstore.yaml -g jaxrs-jersey -o server` & `openapi-generator generate -i petstore.yaml -g jaxrs-jersey -o server --additional-properties=parentArtifactId=parent-artifact,parentGroupId=parent-group,parentVersion=1.0-SNAPSHOT`

##### Steps to reproduce

Run the above generation commands from inside https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0.

##### Related issues/PRs

n/a

##### Suggest a fix

Unsure

### PR DESCRIPTION
**Pull request by scali**
Fix #8890 (only part 2 of the issue)

- At first glance : I apply the change only in Jaxrs-Jersey pom.mustache template
- After a closer look : I apply the change to every JaxRS pom.mustache templates

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet  @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by scali** [comment]
Should I cancel this PR and make a new one with the updated commits ?

**Comment by scali** [comment]
I've tried another solution : I've added the email address used in the commit so that the contibution sould be linked to my github account

**Comment by wing328** [comment]
LGTM. Will update the samples in another commit

**Pull request merged**
