### PR TITLE
[dart][dart-dio-next] Authentication fixes and improvements

### LINKED ISSUE #9906: [BUG] [Dart-dio] Basic Auth not working
##### Description

The generated Basic Auth Interceptor does not work when defining basic auth as authentication scheme according to https://swagger.io/docs/specification/authentication/basic-authentication/

The interceptor looks for authInfo with type 'basic' 
`getAuthInfo(options, 'basic');`
while the requests are generated like this:
```
'secure': <Map<String, String>>[
          {
            'type': 'http',
            'name': 'basicAuth',
          },
```
##### openapi-generator version

5.1.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
...
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
```

##### Generation Details
Generated for dart-dio-next, should be the same for dart-dio.
`openapi-generator generate -i api.json -g dart-dio-next -c config.json -o . --skip-validate-spec`

##### Steps to reproduce

Generate Code with basic Auth, call `setBasicAuth('basicAuth','username', 'password' )`, send a request.

##### Suggest a fix

Match type in BasicAuthInterceptor and in generated requests.

### PR DESCRIPTION
**Pull request by kuhnroyal**
Fixes #9906

* update http mock test library
* correctly map authentication by type and scheme
* add new authentication interceptor for `bearer` scheme - this currently does the same as the OAuth interceptor
* add tests for all authentication types except OAuth
* use temporary test library branch until new fixes and features get merge there

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

CC @swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)

### CODE REVIEW

**Comment by kuhnroyal** [comment]
This is ready for reviews. Just waiting for an updated release of the mock library but other than that I expect no more changes.

**Review by jaumard — APPROVED** [review]
Looks good to me :)

**Review by agilob — APPROVED** [review]
Looks good

**Comment by kuhnroyal** [comment]
Updated the mock library after its release. Should be good to merge once it builds.

**Pull request merged**
