### PR TITLE
[Python] Allow models to have properties of type self

### PR DESCRIPTION
**Pull request by spacether**
This updates the python-experimental generator to allow a model to have properties of type self.
An example model is a Player which stores an enemyPlayer also of type player.

See this use case example:
```
  Player:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      enemyPlayer:
        type: object
        $ref: '#/components/schemas/Player'
```
And our python code demonstrating that it works:
```
        jim = petstore_api.Player(
            name="Jim",
            enemy_player=petstore_api.Player(name="Sam")
        )
```
This was fixed by converting class.openapi_types into a class method, which prevents the openapi_types code from being run at import time.
We also removed the module name from the dataType of the property if the property in self's model.

### Test Verification
A test has been added demonstrating that this works at https://github.com/spacether/openapi-generator/blob/issue_4885_allow_self_properties/samples/client/petstore/python-experimental/test/test_player.py#L32

If merged, this will resolve:
https://github.com/OpenAPITools/openapi-generator/issues/4885

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Python technical-committee:
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) @spacether (2019/11)

@ethan92429

### CODE REVIEW

**Comment by ethan92429** [comment]
@spacether I just ran into another issue using this PR. It is in the resolution of the discriminator. If a model specifies that it is a grandchild of the base model, the discriminator for that grandkid won't be found because the client only looks in the discriminators of the base. The way around this would be to specify _every_ subtype possible, which would be extraordinarily ugly for a large tree that inherits all from one main type (a common pattern for my company). Instead, I think the client should recursively search the discriminator tree to find the correct type. Specifically, [here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/python-experimental/model_utils.mustache#L594) we should look for a match recursively down the discriminator tree. Would that still honor the OAS?

**Comment by spacether** [comment]
@ethan92429 I won't know until I see an example of your use case. Can you create and share a sample spec?

**Comment by ethan92429** [comment]
Example spec: 
```YAML
components:
  schemas:
    Animal:
      type: object
      required:
      - pet_type
      properties:
        type_key:
          type: string
      mapping:
        pet: '#/components/schemas/Pet'
    Pet:
      type: object
      properties:
        type_key:
          type: string
      discriminator:
        propertyName: type_key
        mapping:
          cat: '#/components/schemas/Cat'
    Cat:
      type: object
      properties:
        type_key:
          age: number
```
Now if the client tries to deserialize something that looks like {'type_key' : 'cat'} and it is known to be of type 'Animal',  it will just not find the correct discriminated class (the Cat class). To work correctly, it would need to recursively search through all the discriminators of Pet as well. However, I'm not sure this is supported in OAS... Is the right way to solve this by making all my discriminators class-specific? For instance, changing 'type_key' to 'animal_type_key' and 'pet_type_key', respectively? That way an instnance of a Cat would specify both  'animal_type_key' and 'pet_type_key'... Thoughts?

**Comment by ethan92429** [comment]
@spacether an example of code that would support this behavior: https://github.com/ethan92429/openapi-generator/commit/ffff978a691d6db10b4f9d7bdb483f78e745fa69

**Comment by spacether** [comment]
Thank you for making that sample. It looks like this issue is unrelated to properties of type self. To help us fix it can you please post it as a new issue?
Should Cat allOf inherit Pet? Shoiuld Pet allOf inherent Animal? Why not combine the Pet and Animal classes?

**Comment by ethan92429** [comment]
Yes - all inherit Animal and Cat inherits Pet. This is just the simplest example I could come up with to illustrate the issue - the spec that I'm using is 77,000 lines of JSON, so posting that wouldn't have been helpful :-) . There are many, many examples of this type of inheritance in our codebase. In our homegrown clients, we have a single 'discriminator mapping' dictionary that can relate _any_ of our type mapping key values to their respective type. This way we flatten the type graph and achieve good performance. It would be really neat if there was some way to support this use case. I can write up an issue, but TBH, I'm not sure what the right solution is...

**Comment by spacether** [comment]
Your posted diff is the right solution. I understand your use case better now. Let's move the discussion there or to an issue if you make it. Either is good.

**Comment by ethan92429** [comment]
#4912 is the issue I posted. Moving discussion there.

**Pull request merged**
