### PR TITLE
[C] Optimize memory usage when printing JSON

### PR DESCRIPTION
**Pull request by zhemant**
This PR change `cJSON_Print` function with `cJSON_PrintUnformatted` allowing to create unindented json. This reduces the over number of characters required to create a json payload and by that memory allocated.

Also updated the samples.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by zhemant** [comment]
@ityuhui  @michelealbano

**Comment by ityuhui** [comment]
It's great that reduce the memory usage but I think at the same time, debugging becomes a bit inconvenient. e.g. Users need to format/beautify the json string themselves.

**Comment by wing328** [comment]
agreed with @ityuhui use cases.

**Review by aimhighrana — APPROVED** [review]
Good fix ,

**Comment by zhemant** [comment]
> It's great that reduces the memory usage but I think at the same time, debugging becomes a bit inconvenient. e.g. Users need to format/beautify the json string themselves.

You mean you add custom prints in the code or on wire? In our code we dont have prints, otherwise we could add probably debug flag to just print the json beautified and other times handle normally, the debug operation would be expensive since we will reparse the body and print again. But I imagine this would be only in case of debugging and not during regular operations.
On wire, I dont think there should be any issue, since wireshark already parses the json.

Could you please clarify in your use case, have you added custom prints or at what point do you mean debugging?

**Comment by ityuhui** [comment]
My use case is, printing a json string at a break point when using `gdb` to debug a program containing this library. 
e.g. Sometimes I want to see the content of the object:

```
p (char *) object->temporary
```

**Comment by wing328** [comment]
@zhemant what about adding an option like useJsonUnformatted, which default to false to start with?

I can see some users prefer unformatted JSON while others want the current output.

**Comment by zhemant** [comment]
@wing328 could you help me, where you do mean we use `useJsonUnformatted`, I am thinking of all possible options.

- if i use macro or inline function then either I will have to create another file or put the same code in multiple files. But using something like macro or inline function would allow to use both function by recompiling with different flags.
- Alternatively if we have some option from codegenerator. I am not sure of this

**Comment by wing328** [comment]
merged via https://github.com/OpenAPITools/openapi-generator/pull/18072 instead

**Pull request closed without merging**
