### PR TITLE
corrected handling of "isPrimitiveType" for FormParameters

### PR DESCRIPTION
**Pull request by aronkankel**
pull request for issue https://github.com/OpenAPITools/openapi-generator/issues/17699

corrected handling of "isPrimitiveType" for FormParameters

### CODE REVIEW

**Comment by aronkankel** [comment]
The check
OpenAPI Generator / Samples up-to-date (pull_request) 
failed.

Because of my change in the mustache-template, the generated sample changed too. Should I file a PR for change of the sample in samples/client/others/csharp-complex-files/src/Org.OpenAPITools/Api/MultipartApi.cs?

**Comment by wing328** [comment]
please include the sample update in this PR.

**Comment by aronkankel** [comment]
@wing328 I fixed the samples and updated this PR.

**Comment by wing328** [comment]
cc 
@mandrean (2017/08) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)

**Comment by wing328** [comment]
windows tests passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/49055939

**Pull request merged**
