### PR TITLE
Recreate petstore samples

### PR DESCRIPTION
**Pull request by roxspring**
Recreated samples using latest master to get a clean baseline ahead of #4454.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by roxspring** [comment]
Note that there are no code or input changes here, just running `*-petstore.sh`. Presumably CI breakages are due to existing state of master 😢 

Not targeting a particular programming language... does that mean I should tag the core team for review? @wing328 @jimschubert @cbornet @ackintosh @jmini @etherealjoy

**Comment by jimschubert** [comment]
@roxspring I've opened and reviewed a few PRs this weekend, and the only thing I've found is that I was missing elm-format locally. I pinged the core team recommending that we remove language specific formatters from these scripts.

Master is currently green, and other PRs are green. The amount of changes in this PR is unexpected, and in some cases (like the bash client) the changes aren't valid. Can you rebase master, rebuild the project, then run `bin/utils/ensure-up-to-date` again?

**Comment by jimschubert** [comment]
For example, branching off current master you should see only the following for the bash client:

```diff
diff --git a/samples/client/petstore/bash/.openapi-generator/VERSION b/samples/client/petstore/bash/.openapi-generator/VERSION
index c3a2c7076f..d168f1d8bd 100644
--- a/samples/client/petstore/bash/.openapi-generator/VERSION
+++ b/samples/client/petstore/bash/.openapi-generator/VERSION
@@ -1 +1 @@
-4.2.0-SNAPSHOT
\ No newline at end of file
+4.2.1-SNAPSHOT
\ No newline at end of file
diff --git a/samples/client/petstore/bash/petstore-cli b/samples/client/petstore/bash/petstore-cli
index 17891dc77b..de7efc9b69 100755
--- a/samples/client/petstore/bash/petstore-cli
+++ b/samples/client/petstore/bash/petstore-cli
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+
 # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 # !
 # ! Note:
@@ -9,6 +10,7 @@
 # !
 # !
 # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+
 #
 # This is a Bash client for OpenAPI Petstore.
 #
```

There shouldn't be any Dockerfile or README changes in that client. There are similar issues with the other generators in the change list. The reason there are changes in this generator on master is because it's not included in our `ensure-up-to-date` script, which runs on every PR/master/branch build in CI.  However, `R` is included in the validation script for which there should be no changes in master and there are changes in this PR.

I pulled your PR and I see that you have changes from yesterday (your master was 5 commits before previous master), which makes the changes in this PR more odd to me.  Could you try the following from the repo root and see how it goes?

```
mvn install -am -Dmaven.javadoc.skip=true
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar batch  --includes-base-dir `pwd` --fail-fast  -- bin/ci/*
```

The batch command is a new one I've added recently in an attempt to speed up CI. I'm currently evaluating it before documenting and suggesting it in place of the `ensure-up-to-date` script.

**Comment by wing328** [comment]
About `bin/utils/ensure-up-to-date`, it does not cover all languages/scripts under ./bin/ (intentionally) as some generators (e.g. actionscript) are barely supported. Those are being actively worked on by the community are added to ensure the samples are up-to-date and there are tests to run against the petstore samples. 

@roxspring did you run `./bin/run-all-petstore` to update all samples for this PR?

**Comment by roxspring** [comment]
Thanks for the prompt feedback @jimschubert. Have installed `elm-format` and am now playing with `bin/utils/ensure-up-to-date` and the alternative you suggested... hopefully it'll mean I can close this MR and focus on #4454 which I was trying to work on anyway :)

**Comment by wing328** [comment]
> and the only thing I've found is that I was missing elm-format locally. I pinged the core team recommending that we remove language specific formatters from these scripts.

I set that up to ensure the file post-processing works as expected and also make it easier for the creator of the Elm client generator to review the change.

**Comment by roxspring** [comment]
@wing328 I was running all the bin/*-petstore.sh and bin/openapi/*-petstore.sh scripts before. Hadn't come across `bin/utils/ensure-up-to-date` or `bin/run-all-petstore` - seems they run a more targeted subset. Perhaps the `bin/` directory needs a dedicated README of it's own to guide noobs around!

@jimschubert the alternate command seems to work well, and quickly, once `bin/ci/php-symfony-petstore.json` is modified to not reference you're home directory! Once adopted, it'd be particularly nice to be able to run from a maven goal and have the whole build/test cycle from a maven one-liner.

I'll close this MR down and focus on #4454.

**Comment by jimschubert** [comment]
@roxspring dang. Nice catch on the symfony config issue. As you can imagine, creating those JSON configs was quite a task (I ended up writing a tool to parse the bash scripts). I'll fix that one later today and check to make sure I haven't referenced my home directory elsewhere.

**Comment by jimschubert** [comment]
Also, excellent suggestion on the Maven goal! I'll have to play around with it to understand how to invoke the CLI built by the current mvn build.

**Comment by jimschubert** [comment]
Fixed my user path via #4470.

**Pull request closed without merging**
