### PR TITLE
[C++ server] Adjust the names (script, sample folder, generator) to lang option

### PR DESCRIPTION
**Pull request by ackintosh**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Related issue: https://github.com/OpenAPITools/openapi-generator/issues/138
Related PR: https://github.com/OpenAPITools/openapi-generator/pull/220

This PR prefixes the scripts/sample folders/generators with cpp- to avoid users/contributors be confused.

### CODE REVIEW

**Comment by ackintosh** [comment]
[Technical Committee](https://github.com/openapitools/openapi-generator/#members-of-technical-committee): @ravinikam  @stkrwork  @fvarose @etherealjoy  @martindelille

 🙏

**Comment by etherealjoy** [comment]
Looks fine to me.

**Comment by stkrwork** [comment]
what about the other files? some of them still write to the wrong folders

**Comment by wing328** [comment]
@stkrwork I'll file a PR to clean it up tomorrow. Thanks for the reminder.

**Comment by ackintosh** [comment]
Sorry for missing the scripts. 💦

**Pull request merged**
