### PR TITLE
[swift4] Add swift package manager and update dependencies

### PR DESCRIPTION
**Pull request by 4brunu**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @d-date (2018/03)

### Description of the PR

This PR add's support for Swift Package Manager, update dependencies and fixes https://github.com/OpenAPITools/openapi-generator/issues/4057

### CODE REVIEW

**Comment by 4brunu** [comment]
cc: @wing328 can you please take a look at this? CI is failing but I think it's not related to this PR.

**Comment by 4brunu** [comment]
After merging master to this branch, it's now passing all the tests.
Can someone please look a this? 
Thanks 🙂

**Comment by wing328** [comment]
Let me run the test locally tomorrow. There were issues before due to XCode upgrade in my side.

**Comment by 4brunu** [comment]
Thanks 🙂

**Comment by wing328** [comment]
Tests passed locally:
```
All tests
Test Suite SwaggerClientTests.xctest started
DateFormatTests
    ✓ testCodableAlwaysResultsInUTCEncodedDate (0.276 seconds)
    ✓ testEncodeToJSONAlwaysResultsInUTCEncodedDate (0.001 seconds)
PetAPITests
    ✓ test1CreatePet (1.254 seconds)
    ✓ test2GetPet (0.444 seconds)
    ✓ test3DeletePet (0.331 seconds)
StoreAPITests
    ✓ test1PlaceOrder (0.449 seconds)
    ✓ test2GetOrder (0.414 seconds)
    ✓ test3DeleteOrder (0.330 seconds)
    ✓ testDownloadProgress (0.403 seconds)
UserAPITests
    ✓ testLogin (0.451 seconds)
    ✓ testLogout (0.332 seconds)
    ✓ testPathParamsAreEscaped (0.000 seconds)


Executed 12 tests, with 0 failures (0 unexpected) in 4.686 (4.691) seconds

```

**Pull request merged**
