### PR TITLE
[Php] Exclude query params when they're not required

### PR DESCRIPTION
**Pull request by ksvirkou-hubspot**
Exclude query params when they're not required
```json
{
    "name": "archived",
    "in": "query",
    "description": "Whether to return only results that have been archived.",
    "required": false,
    "style": "form",
    "explode": true,
    "schema": {
        "type": "boolean",
        "default": false
    }
}
```
if archived is empty 
`https://api.*.com/crm/v3/objects/contacts`

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ksvirkou-hubspot** [comment]
@jebentier @dkarlovi @mandrean @jfastnacht @ybelenko @renepardon

**Comment by wing328** [comment]
```
Perform git status
HEAD detached at pull/12120/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   samples/client/petstore/php/OpenAPIClient-php/lib/Api/FakeApi.php
	modified:   samples/client/petstore/typescript-fetch/builds/default-v3.0/models/UserType.ts
```

Reported by https://github.com/OpenAPITools/openapi-generator/runs/5992057816?check_suite_focus=true

For the typescript sample, it has been updated in the master. Please merge the latest master into your branch.

**Comment by ybelenko** [comment]
@ksvirkou-hubspot could you add a few tests? You've added new `$required` argument to `toQueryValue` method, it should be covered.

**Comment by ksvirkou-hubspot** [comment]
> [Php] Convert boolean value for query string #11880

Hi
Will do

**Comment by ksvirkou-hubspot** [comment]
I ve just fixed samples and added tests
Could you merge it?
@ybelenko @wing328

**Review by ybelenko — APPROVED** [review]
@nadar does it look ok to you too? This changes might be related to deepObject serialization feature.

**Comment by atanasiuk-hubspot** [comment]
Hey team, any updates on merging this?

**Comment by wing328** [comment]
Just merged. Thanks @ksvirkou-hubspot for the PR.

**Comment by nadar** [comment]
Hey @ybelenko, sorry i never saw this one. But as along as it does not break your unit tests, this should not affect the deep object serialization.

**Pull request merged**
