### PR TITLE
Implement useAbstractionForFiles for webclient library

### PR DESCRIPTION
**Pull request by iyzana**
This pull-request extends https://github.com/OpenAPITools/openapi-generator/pull/6912 by providing an implementation of the new `useAbstractionForFiles` flag for the webclient library.
The original issue was https://github.com/OpenAPITools/openapi-generator/issues/6715 . I left a comment on that ticket mentioning that the functionality would be nice to have for the webclient as well.
In this PR I mostly just adapted the changes that were necessary for the resttemplate to work for the webclient.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

### CODE REVIEW

**Comment by iyzana** [comment]
I'm not sure why the circleci build is still failing

**Comment by wing328** [comment]
@iyzana can you please resolve the merge conflicts when you've time? We'll look into the CI issue later if it's still failing.

**Comment by iyzana** [comment]
rebased

**Comment by wing328** [comment]
Pushed https://github.com/OpenAPITools/openapi-generator/pull/7567/commits/f9a86147c4470a4feb8ff0cd644cfdb20c0996cc to fix CI failures. Let's see how that goes.

**Comment by MosheElisha** [comment]
@noako when you update the [java.md docs](https://github.com/OpenAPITools/openapi-generator/blame/master/docs/generators/java.md#L60) as part of #8549 , please consider mentioning that the useAbstractionForFiles is also supported for webclient library.

**Pull request merged**
