### PR TITLE
[kotlin] Add fix for wrongly encoded backticks for reserved words when generating kotlin-spring server code

### PR DESCRIPTION
**Pull request by martinvisser**
Added a fix for double escaped reserved words in `kotlin-spring` generator.

This fixes https://github.com/OpenAPITools/openapi-generator/issues/14026

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by martinvisser** [comment]
@wing328 I hope I fixed it, thanks for letting me know! That's the problem of working for a client and having global git config I guess.

**Comment by wingsofovnia** [comment]
Can we expect this to be in anytime soon? I've encounter the same issue, very annoying.

**Comment by wing328** [comment]
Did some tests locally and the fix looks good.

I found some other minor other issues and will file another PR to address those instead.

**Comment by wing328** [comment]
FYI. Filed https://github.com/OpenAPITools/openapi-generator/pull/16270 with minor fixes

**Pull request merged**
