### PR TITLE
Add name in various cases in property, parameter names

### PR DESCRIPTION
**Pull request by wing328**
Add name in various cases (e.g. pascal, lower, etc) in property, parameter names

for those using `nameInCamelCase ` in the templates, please switch to `nameInPascalCase` instead.

fyi @OpenAPITools/generator-core-team 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@devhl-labs after this PR, I will file another one to clean up the use of lambda to camelize names in the C# mustache templates.

**Comment by ratoaq2** [comment]
@zapodot @wing328 
it seems this change broke generation for JavaClientCodeGen:

```
      "Alert" : {
        "required" : [ "alertType", "inProgress" ],
        "type" : "object",
        "properties" : {
          "alertIdentifier" : {
            "type" : "string",
            "description" : "Alert identifier",
            "example" : "some text"
          },
          "errors" : {
            "type" : "array",
            "description" : "Errors for Alert of type Error",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            },
            "example" : null
          },
          "warnings" : {
            "type" : "array",
            "description" : "Warnings for Alert of type Warning",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            },
            "example" : null
          },
          "information" : {
            "type" : "array",
            "description" : "Information for Alert ",
            "items" : {
              "$ref" : "#/components/schemas/ErrorDetail"
            },
            "example" : null
          },
          "authorizationDetails" : {
            "$ref" : "#/components/schemas/AuthorizationDetails"
          },
          "alertType" : {
            "type" : "string",
            "description" : "Alert Type",
            "example" : "AlertType$ERROR",
            "_enum" : [ "AlertType$ERROR", "AlertType$WARNING", "AlertType$INFO", "AlertType$IN_PROGRESS", "AlertType$TO_APPROVE" ]
          },
          "inProgress" : {
            "type" : "boolean",
            "description" : "In progress Alert",
            "example" : true
          }
        }
      }
```

Now I get 3 identical methods for 3 different properties:
```
  public Alert addItem(ErrorDetail errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  public Alert addItem(ErrorDetail warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

  public Alert addItem(ErrorDetail informationItem) {
    if (this.information == null) {
      this.information = new ArrayList<>();
    }
    this.information.add(informationItem);
    return this;
  }
```

**Comment by wing328** [comment]
are you using customized templates?

**Comment by ratoaq2** [comment]
Please ignore my comment. It seems the issue is maven plugin.

That output was generated with org.openapitools:openapi-generator-maven-plugin 7.4.0

Using 7.5.0 seems to be working fine now.

Sorry for that

**Comment by wing328** [comment]
@ratoaq2 that's ok :)

**Pull request merged**
