### PR TITLE
[DART] Add homepage option to pubspec.yaml

### PR DESCRIPTION
**Pull request by harsimranmaan**
package validation fails when trying to publish to pub.dev. A homepage/repository field is required to be set in pubspec.yaml.

See: https://dart.dev/tools/pub/pubspec
Blocking https://github.com/bigpanther/trober/pull/108 via https://github.com/bigpanther/trober/pull/108/checks?check_run_id=2275335010. (using a hack at the moment to set the homepage url out of band)

cc: @kuhnroyal

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
Good catch, would you mind also adding the `authors` and updating the dart-dio template as well.

```yaml
homepage: '{{{pubHomepage}}}'
authors:
  - '{{{pubAuthor}}} <{{{pubAuthorEmail}}}>'
```

After that please run the commands in the PR description for the build to succeed.
Thanks!

**Comment by harsimranmaan** [comment]
Unfortunately, I am not able to run the commands on my local machine as I don't/can't have the desired pre-reqs installed locally and the docker scripts are not compatible with arm64.

**Comment by kuhnroyal** [comment]
I'll add this in another PR then based on your commit.

**Comment by kuhnroyal** [comment]
I created a new PR with your changes and generated samples + some tweaks. This one can be closed.

**Comment by harsimranmaan** [comment]
Closed in favor of https://github.com/OpenAPITools/openapi-generator/pull/9201

**Pull request closed without merging**
