### PR TITLE
Fixed problem with non-ref-enums which were handled like ref-enums

### LINKED ISSUE #15476: [BUG][python-nextgen] Cannot handle query parameters with non-ref enums
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

https://github.com/OpenAPITools/openapi-generator/pull/15278 does not seem to work correctly.

The below schema creates the function signature, one of them an enum, the other a string:

```py
query_param_with_named_enum : QueryParamEnum, query_param_without_named_enum : StrictStr
```

But still tries to access both values with `.value`:

```py
        # process the query parameters
        _query_params = []
        if _params.get('query_param_with_named_enum') is not None:  # noqa: E501
            _query_params.append(('queryParamWithNamedEnum', _params['query_param_with_named_enum'].value))

        if _params.get('query_param_without_named_enum') is not None:  # noqa: E501
            _query_params.append(('queryParamWithoutNamedEnum', _params['query_param_without_named_enum'].value))
```

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: ""
  version: ""
paths:
  /test/endpoint:
    get:
      parameters:
        - name: queryParamWithNamedEnum
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/QueryParamEnum'
        - name: queryParamWithoutNamedEnum
          in: query
          required: true
          schema:
            type: string
            enum:
              - ValueA
              - ValueB
      responses:
        200:
          description: OK
components:
  schemas:
    QueryParamEnum:
      type: string
      enum:
        - ValueC
        - ValueD
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/15133
https://github.com/OpenAPITools/openapi-generator/pull/15278

##### Suggest a fix

Short-term: Do not use `.value` on raw string.

Long-term: Restrict the allowed values for non-ref enums somehow, maybe with a custom model or the [literal type](https://docs.pydantic.dev/latest/usage/types/#literal-type). This might be breaking for some users.

### PR DESCRIPTION
**Pull request by dlange-hima**
The three attributes are not set correctly:
`public boolean isEnum; // true if the enum is defined inline`
`public boolean isInnerEnum; // Enums declared inline will be located inside the generic model, changing how the enum is referenced in some cases.`
`private boolean isEnumRef; // true if it's a reference to an enum`

I changed the code so that the return value from ModelUtils.getReferencedSchema is compared against its original parameter to see if a ref is actually resolved.

To close #15476

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@dlange-hima thanks for the fix. Do you have a spec to help reproduce the issue? I'll use it to run some tests.

**Comment by dlange-hima** [comment]
@wing328 Happy to help :). I adjusted one existing testcase, which expected all three parameters as 'true', which was wrong I believe.

Thanks to @robertschweizer, who posted this in his issue (I adjusted the names a little):

```
openapi: 3.0.1
info:
  title: ""
  version: ""
paths:
  /test/endpoint:
    get:
      parameters:
        - name: queryParamWithRef
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/QueryParam'
        - name: queryParamInline
          in: query
          required: true
          schema:
            type: string
            enum:
              - ValueA
              - ValueB
      responses:
        200:
          description: OK
components:
  schemas:
    QueryParam:
      type: string
      enum:
        - ValueC
        - ValueD
```
If you take this spec and run the python client generator before my change, it generates the following code in default_api.py
```
        if _params.get('query_param_with_ref') is not None:  # noqa: E501
            _query_params.append(('queryParamWithRef', _params['query_param_with_ref'].value))

        if _params.get('query_param_inline') is not None:  # noqa: E501
            _query_params.append(('queryParamInline', _params['query_param_inline'].value))
```
For query_param_inline there is no ".value".

**Comment by dlange-hima** [comment]
I'm not really sure, why one of the tests failed.
As far as I can interpret the output, I'm not sure wether my change is related or if the test system has hickups

**Comment by wing328** [comment]
the CI failure is not related to this change. please ignore it for the time being.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
LGTM

**Pull request merged**
