### PR TITLE
Fix Go generation of `type: object` inside anyOf

### LINKED ISSUE #13166: [BUG] Go Code Generator do not strip out {} in oneOf
##### Description

The _GoClientCodeGen.java_ do incorrectly render the typeToName.  The problem seems to be in 

```java
private String typeToName(String content) {
        content = content.trim().replace("[]", "array_of_");
        content = content.trim().replace("[", "map_of_");
        content = content.trim().replace("]", "");
        return camelize(content);
    }
```

where the content is (in my case) `map[string]interface{}` and the curly braces are not stripped.

##### openapi-generator version

Version 6.0.1

##### OpenAPI declaration file content or url

```yaml
DataPoint:
  oneOf:
    - type: object
    - type:
      $ref: '#/SimpleDataPoint'
SimpleDataPoint:
  properties:
    v:
      type: number
    t:
      type: integer
  required:
    - v
    - t
```

Will generate the following struct where the `MapmapOfStringinterface{}` occurs.

```go
type DataPoint struct {
	SimpleDataPoint *SimpleDataPoint
	MapmapOfStringinterface{} *map[string]interface{}
}
```

(🎃As a **sidenote**, the `anyOf` (mustache template) will never even try to use _#lambda.type-to-name_ and therefore instead it will render the `map[string]interface{} *map[string]interface{}`.)

##### Steps to reproduce

generate the above snippet

##### Suggest a fix

Just replace `{}` with empty `string` before `camelize`.

### PR DESCRIPTION
**Pull request by ashb**
Without this the generated code contains `{}` in the field name which is invalid.

Fixes #13166

Previously generated code:

```go
// IncidentData - struct for IncidentData
type IncidentData struct {
	ArrayOfMapmapOfStringinterface{} *[]map[string]interface{}
	MapmapOfStringinterface{} *map[string]interface{}
}
```

After

```go
// IncidentData - struct for IncidentData
type IncidentData struct {
	ArrayOfMapmapOfStringAny *[]map[string]interface{}
	MapmapOfStringAny *map[string]interface{}
}
```

Example input spec:

```json
{
  "components": {
    "schemas": {
          "IncidentData": {
            "oneOf": [
              {
                "items": {
                  "type": "object"
                },
                "type": "array"
              },
              {
                "type": "object"
              },
              {
                "type": "null"
              }
            ],
            "title": "Incident Data"
          }
    }
  },
  "info": {
    "title": "Test",
    "version": "0.1.0"
  },
  "openapi": "3.0.2",
  "paths": {
    "/": {
      "get": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/IncidentData"
                }
              }
            },
            "description": "Successful Response"
          }
        }
      }
    }
  }
}
```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5

### CODE REVIEW

**Comment by wing328** [comment]
What about adding a test schema/model in modules/openapi-generator/src/test/resources/3_0/go/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml and regenerate the samples?

**Comment by leonheldattoradex** [comment]
Any updates on this topic? @wing328, can you provide me with more detailed instructions about adding the tests? I'd really like to get this fix merged.

**Comment by wing328** [comment]
tested locally and the result is good. will add tests in another PR

**Comment by wing328** [comment]
FYI. added tests via 6518932ccfd

**Comment by leonheldattoradex** [comment]
Grand! Many thanks, @wing328!

**Pull request merged**
