### PR TITLE
Better inline model resolver to handle inline schema in array item

### PR DESCRIPTION
**Pull request by wing328**
Better inline model resolver to handle inline schema in array item and recursively look for inline models/schemas to flatten.

cc @OpenAPITools/generator-core-team 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by spacether** [comment]
Per a chat that @wing328 and I had, this will convert a number of models that were defined inline in python-experimental into separate component models that are referenced. So code will keep working, there will be additional models that store the schema definition. 
In the future (my goal is to do it in the 6.0.0 release) I will add a PR that allows the user to choose whether to have the inline model resolver be on or off for python-experimental.

**Comment by claudiachua** [comment]
Hi there, I'm using V6.0.0, was wondering if there's anyway to turn off inline schema naming for arrayItemSuffix? 
E.g. remove having '_inner' from generated files.

**Comment by spacether** [comment]
If you removed the `_inner` won't there be a naming collision?

**Comment by wing328** [comment]
@claudiachua in the log (output), there's a hint on how to map the inline schema name to something else. Please take a look to see if that helps.

**Comment by claudiachua** [comment]
Hi @wing328 , as I'm still very new to this, could you please provide an example of how I can use --inline-schema-name-mappings in CLI

**Comment by claudiachua** [comment]
@spacether there wasn't a naming collision issue in v5.4 and no `_inner` suffix was added. I'm guessing that it was the additional check that if ArraySchema was an also objectSchema before adding the suffix.

**Pull request merged**
