### PR TITLE
Replace deprecated Gradle properties

### PR DESCRIPTION
**Pull request by jgosmann**
We noticed two properties in the Gradle build files that were reported as deprecated. This PR replaces them with the new names.

* destinationDir -> destinationDirectory (scheduled to be removed in Gradle 9.0)
* archiveName -> archiveFileName (removed in Gradle 8.0)

Cp. https://docs.gradle.org/current/userguide/upgrading_version_7.html

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@jgosmann thanks for the PR. Does it mean we drop the support for Gradle 7.x?

**Comment by jgosmann** [comment]
I think this does not affect support for Gradle 7.x.

* We are still using Gradle 7.x and did the replacements already in the clients we've generated without encountering a problem. However, the affected places seem to be only relevant when targeting Android, which we do *not*.
* At least the 7.3 documentation of [`AbstractCompile`](https://docs.gradle.org/7.3/javadoc/org/gradle/api/tasks/compile/AbstractCompile.html) and [`AbstractArchiveTask`](https://docs.gradle.org/7.3/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html) already lists the deprecations and replacements.

btw: I amended the commit because I was a bit too eager with the replacements. Hopefully, this makes all tests pass again.

**Comment by wing328** [comment]
CI tests failure not related to this change.

**Comment by wing328** [comment]
@jgosmann thanks for the explanation. I did some tests locally and the result is good so we can merge this.

FYI. I also spotted another warning but I think we can deal with that with another PR instead:

```
> Configure project :
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main for more details.
        at build_8n2n0lmixavm552r5h1hubo3n$_run_closure8.doCall(/Users/williamcheng/Code/openapi-generator7/samples/client/petstore/java/okhttp-gson-group-parameter/build.gradle:99)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

```

**Pull request merged**
