### PR TITLE
[swift5] Fix #8511 (request closure not being called)

### LINKED ISSUE #8511: [BUG][swift5] Closure isn't called anymore in latest snapshot with default configuration
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

This project showcases a weird error where callback closure is not called.

- This happens with the default library selected (URLSession). With Alamofire, everything is fine.
- In the 5.0.0 stable version, the error is not happening
- Snapshot Commit: 90ed1290fafe08306283f9acb74650e5b8d19302 from 2020-01-22
- Tested with Xcode 12.3 (12C33) on macOS Catalina 10.15.7 (19H15)
- Try switching the generator from snapshot to stable pod in `Podfile` to see the change.

##### openapi-generator version

5.0.1-snapshot (commit 90ed1290fafe08306283f9acb74650e5b8d19302)

##### OpenAPI declaration file content or url

See test-project: https://github.com/fl034/Test-OAS

##### Generation Details

- Swift5 with defaults

##### Steps to reproduce

Run sample project

##### Related issues/PRs

Nothing found

##### Suggest a fix

- The issue seems to be in `URLSessionImplementations.swift` in line 137. `self` seems to be deallocated immediately, because it’s weak. 
- When I remove `[weak self]` it works again. But this isn’t the root of the problem, since the stable version also has `[weak self]`

### PR DESCRIPTION
**Pull request by fl034**
Fixes #8511 

Self got deallocated due to `[weak self]` and no other strong references. 
Because of that, request closures wouldn't be called anymore.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by fl034** [comment]
@4brunu

**Comment by 4brunu** [comment]
I think you can delete it, and run pod install again.

**Comment by 4brunu** [comment]
Looks good to me 👍

**Comment by 4brunu** [comment]
Could you just run `pod install` on `samples/client/test/swift5/default/TestClientApp/` to recreate the `podfile.lock`?

**Comment by fl034** [comment]
Done! Sorry, it was late yesterday :D @4brunu

**Comment by 4brunu** [comment]
Sure, take your time 🙂 
Could you fix the merge conflict with the master branch?

**Comment by fl034** [comment]
@4brunu I don#t get the conflict, since in the latest master commit the directory `samples/client/test` is not existing. Therefore the file can't be conflicting, right?

**Comment by 4brunu** [comment]
Sorry for my confusion, you are right, the sample project in `samples/client/test/swift5/default/TestClientApp` was deleted.
Could you please delete the file?

**Comment by 4brunu** [comment]
@wing328 this PR is ready to merge, the CI is failing, but it's not related to this PR.

**Pull request merged**
