### PR TITLE
[Go] add generateMarshalJSON key for additional-properties settings

### PR DESCRIPTION
**Pull request by kokoichi206**
I added generateMarshalJSON (boolean) as a setting for additional-properties.
By default, it is set to true. However, if explicitly set to false, it will not implement the MarshalJSON using ToMap.

This PR is related to #16948.
I kindly ask for your review.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

**Comment by kokoichi206** [comment]
@wing328 
I'm experiencing a failed test (ci), but I'm not quite sure of the cause.If you know, I'd appreciate your help.
When I executed the following command, which should be run on Node0 in CI/circle_parallel.sh, on my local machine, I got a similar error:

``` sh
./mvnw --no-snapshot-updates --quiet verify -Psamples.circleci.others -Dorg.slf4j.simpleLogger.defaultLogLevel=error
```

However, even after checking out the master branch, initializing the dependencies, and executing it again, I got the same error.

I'm not even sure if the changes I made this time are related to the issue.
If you have any ideas or information, I'd appreciate it if you could let me know.

<details><summary>Got Error (my local machine)</summary>

``` sh
[ERROR] PetApiTest.PetApi should find pets by status  Time elapsed: 0.001 s  <<< ERROR!
org.openapitools.client.core.ApiError: (301) Unexpected response code. Content : HttpEntity.Strict(text/html,134 bytes total)

null
java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at java.base/java.util.ArrayDeque.pop(ArrayDeque.java:594)
        at com.gradle.maven.scan.extension.test.listener.junit4.Junit4TestListener.a(SourceFile:183)
        at com.gradle.maven.scan.extension.test.listener.junit4.Junit4TestListener.c(SourceFile:98)
        at com.gradle.maven.scan.extension.test.listener.junit4.Junit4TestListener.testRunFinished(SourceFile:81)
        at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
        at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:63)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)

[ERROR] Test mechanism :: null
[ERROR] Errors: 
[ERROR] PetApiTest.PetApi should add and fetch a pet
[ERROR]   Run 2: PetApiTest.PetApi should add and fetch a pet » Api (301) Unexpected response c...
[ERROR]   PetApiTest.PetApi should find pets by status » Api (301) Unexpected response c...
[ERROR]   PetApiTest.PetApi should update a pet » Api (301) Unexpected response code. Co...
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project scala-akka-petstore-client: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/kokoichi/ghq/github.com/kokoichi206/openapi-generator/samples/client/petstore/scala-akka/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] ExecutionException There was an error in the forked processTest mechanism :: null
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException There was an error in the forked processTest mechanism :: null
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:513)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:460)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:301)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:249)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
[ERROR]         at com.gradle.maven.cache.extension.d.c.a(SourceFile:26)
[ERROR]         at com.gradle.maven.cache.extension.d.n.a(SourceFile:23)
[ERROR]         at com.gradle.maven.cache.extension.d.h.a(SourceFile:28)
[ERROR]         at com.gradle.maven.cache.extension.d.m.a(SourceFile:27)
[ERROR]         at com.gradle.maven.cache.extension.d.a.c(SourceFile:115)
[ERROR]         at com.gradle.maven.cache.extension.d.a.a(SourceFile:61)
[ERROR]         at com.gradle.maven.cache.extension.d.e.a(SourceFile:27)
[ERROR]         at com.gradle.maven.cache.extension.d.l.a(SourceFile:17)
[ERROR]         at com.gradle.maven.cache.extension.d.d.a(SourceFile:42)
[ERROR]         at com.gradle.maven.cache.extension.d.b.a(SourceFile:26)
[ERROR]         at com.gradle.maven.cache.extension.d.f$1.run(SourceFile:35)
[ERROR]         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(SourceFile:29)
[ERROR]         at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(SourceFile:26)
[ERROR]         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(SourceFile:66)
[ERROR]         at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(SourceFile:59)
[ERROR]         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(SourceFile:157)
[ERROR]         at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(SourceFile:59)
[ERROR]         at org.gradle.internal.operations.DefaultBuildOperationRunner.run(SourceFile:47)
[ERROR]         at com.gradle.maven.cache.extension.d.f.a(SourceFile:31)
[ERROR]         at com.gradle.maven.cache.extension.d.k.a(SourceFile:65)
[ERROR]         at com.gradle.maven.cache.extension.h.b.lambda$createProxy$0(SourceFile:65)
[ERROR]         at com.sun.proxy.$Proxy74.execute(Unknown Source)
[ERROR]         at com.gradle.maven.scan.extension.internal.d.a.executeMojo(SourceFile:114)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:299)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:963)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:296)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:52)
[ERROR]         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:161)
[ERROR]         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:73)
[ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked processTest mechanism :: null
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:675)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:118)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:447)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:423)
[ERROR]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[ERROR]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 
[ERROR] -> [Help 1]
```

</details>

**Comment by wing328** [comment]
I don't think it's related to your change. Just restarted the failed tests and let's see how that goes.

**Comment by wing328** [comment]
LGTM. I'll add a test or two in another PR after merging this one.

**Comment by kokoichi206** [comment]
Thank you!
I look forward to working with you again!

**Comment by wing328** [comment]
UPDATE: filed https://github.com/OpenAPITools/openapi-generator/pull/16993 to add a test to cover the new option

**Pull request merged**
