### PR TITLE
[typescript-fetch] Add initOverrides 

### LINKED ISSUE #4851: [REQ] Support AbortController in Typescript-Fetch
### Is your feature request related to a problem? Please describe.

The Fetch API supports attaching a signal, and using that to abort requests. This is particularly helpful when building SPAs which background a lot of requests, and the user navigates to an area of the app where some requests are no longer useful. It improves performance for the user if we can cancel pending requests so newer requests can execute sooner.

## Describe the solution you'd like

Currently, this is what generated code looks like when using single param

```
async methodName(requestParameters: RequestType): Promise<ResponseType> {...}
interface RequestType {
  fieldName1: FieldType1;
  fieldName2: FieldType2;
}
```

Support either of these two methods
```
async methodName(requestParameters: RequestType, abortController?: AbortController): Promise<ResponseType> {...}
interface RequestType {
  fieldName1: FieldType1;
  fieldName2: FieldType2;
}
```

or 

```
async methodName(requestParameters: RequestType): Promise<ResponseType> {...}
interface RequestType {
  fieldName1: FieldType1;
  fieldName2: FieldType2;
  abortController: AbortController;
}
```

This library seems to be commonly used for this purpose - https://github.com/mysticatea/abort-controller

## Describe alternatives you've considered

I can't think of an alternative.

## Additional context

None.

### PR DESCRIPTION
**Pull request by badsyntax**
Fixes #4851

You can now pass in fetch initOverrides per request.

This change is mainly to add support for request cancellation (via AbortSignal), for example:

```js
const controller = new AbortController();
const signal = controller.signal;

usersApi.getUser({ id: userId }, { signal });
```

About the target branch, it's not clear to me if i should be targeting master, but I guess this change can be released as a patch release as it's non-breaking. 

@TiFu  @taxpon  @sebastianhaas  @kenisteward @Vrolijkx  @macjohnny  @topce @akehir @petejohansonxo @amakhrov 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by macjohnny** [comment]
@badsyntax thanks for your contribution!

**Comment by badsyntax** [comment]
Thanks for the merge @macjohnny I have just noticed an issue though, see: 

https://github.com/OpenAPITools/openapi-generator/blob/e2ff39d3e3501977d01f8dcf13fbae2a0337b0eb/samples/client/petstore/typescript-fetch/builds/multiple-parameters/apis/PetApi.ts#L139

I believe this should be a syntax error due to double commas (', ,')

I will follow up with another PR very shortly to fix this. Apologies for not spotting this.

**Comment by badsyntax** [comment]
@macjohnny I've submitted a fix here: https://github.com/OpenAPITools/openapi-generator/pull/10101

**Comment by simPod** [comment]
@badsyntax I'm at 5.3.1 and the runtime fetch generates still like `protected async request(context: RequestOpts): Promise<Response> {`

How do I make it `protected async request(context: RequestOpts, initOverrides?: RequestInit): Promise<Response> {
`?

**Comment by badsyntax** [comment]
@simPod try delete the existing output dir first, as the generator won't overwrite existing files

**Comment by simPod** [comment]
@badsyntax I do it before each run of `generate`

**Comment by badsyntax** [comment]
@simPod are you using a custom template perhaps?

**Comment by simPod** [comment]
Oh you're so right. Thanks!

**Pull request merged**
