### PR TITLE
Better "Any Type" support

### PR DESCRIPTION
**Pull request by wing328**
- Better "Any Type" support by introducing "AnyType", which is mapped to "oas_any_type_not_mapped" by default.
- minor fix to isFreeFormObject check
- removed commented code

cc @OpenAPITools/generator-core-team 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by mwilby** [comment]
Just noticed you did not add

```python
        typeMapping.put("AnyType", "object");
```

to `PythonAbstractConnexionServerCodegen`. Don't know if it matters.

**Comment by wing328** [comment]
@mwilby please file a PR with the suggested change. 

I didn't map it in all generators as part of this PR.

(uses can use --type-mappings to custom "AnyType" mapping type)

**Comment by briceburg** [comment]
This PR caused a regression in the java generator;

```
.../generated/openapi-client/src/main/java/com/cofense/platform/openapi/client/model/OperationResult.java:20: error: cannot find symbol
import com.cofense.platform.openapi.client.model.oas_any_type_not_mapped;
                                                ^
  symbol:   class oas_any_type_not_mapped
  location: package com.cofense.platform.openapi.client.model
```

there is no related `oas_any_type_not_mapped` class under the model package.

**Comment by martinfoersterling** [comment]
In JavaClientCodegenTest, I wonder how the change from
        Assert.assertEquals(cm1.getParent(), "HashMap<String, Object>");
to
        Assert.assertEquals(cm1.getParent(), "HashMap<String, oas_any_type_not_mapped>");
should ever work. How should this weird "oas_any_type_not_mapped" amount to "any type"?

**Comment by gtsystem** [comment]
Any update on this issue?

**Comment by phillipuniverse** [comment]
This also caused a regression in the Javascript generator where all models attempt to import an `AnyType` that does not exist. 

> I didn't map it in all generators as part of this PR.
> (users can use --type-mappings to custom "AnyType" mapping type)

Frankly, I think that this ended up breaking a large number of generators since they did not have this mapping already. Doesn't every single generator need to have this mapping to work with free form objects like this?

```
components:
  SomeCustomData:
    type: object
    description: 'Custom data for Shipment'
    additionalProperties: {}
```

**Comment by phillipuniverse** [comment]
@briceburg @gtsystem it appears that the Java codegen issues were resolved in https://github.com/OpenAPITools/openapi-generator/pull/6246 available in 5.0.0-beta and 5.0.0-beta2.

**Pull request merged**
