### PR TITLE
[aspnetcore] Minor code cleanups.

### PR DESCRIPTION
**Pull request by A-Joshi**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Mostly cosmetic code refactoring to make the code more readable - as per [2285](https://github.com/OpenAPITools/openapi-generator/issues/2285)
- Make classModifier, operationModifier and buildTarget enums
- Enhance CliOption class to hold value - it reduces boilerplat code.
- Add ASP.Net Core 2.2 (no changes to generated code - since it is pretty much backward compatible with 2.1).

### CODE REVIEW

**Comment by wing328** [comment]
@A-Joshi thanks for the PR but seems like the rebase fails. Do you mind filing a new PR based on the latest master by cherry-picking the commits that belong to you?

**Comment by A-Joshi** [comment]
will do that but do want to understand why it fails. I am doing the
following to rebase:

origin  https://github.com/ihsmarkitoss/openapi-generator.git (fetch)
origin  https://github.com/ihsmarkitoss/openapi-generator.git (push)
upstream        https://github.com/OpenAPITools/openapi-generator.git
(fetch)
upstream        https://github.com/OpenAPITools/openapi-generator.git (push)

git checkout master
git fetch upstream
git merge upstream/master
git push

git checkout feature/aspnetcore_async
git rebase master
git pull
git push

Do you see anything wrong with that?

**Comment by A-Joshi** [comment]
Created cleaned up new PR [2436](https://github.com/OpenAPITools/openapi-generator/pull/2436)

**Comment by A-Joshi** [comment]
Created new PR with conflicts etc. cleaned up [2436](https://github.com/OpenAPITools/openapi-generator/pull/2436)

**Pull request closed without merging**
