### PR TITLE
[ci] Move openapi-generator build/docs/samples to github actions

### PR DESCRIPTION
**Pull request by kuhnroyal**
I think this should be the next step for migration to Github actions.
This will give faster and explicit feedback on
* build failures related to generator/plugins
* failing unit tests related to generator/plugins
* outdated docs
* outdated samples

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@wing328 I think this looks like a good start.
I tested samples/docs failure here: https://github.com/OpenAPITools/openapi-generator/actions/runs/864880847

For unit test reports to work, the `openapi-generator-test-results.yaml` has to be available on the default branch.

**Comment by kuhnroyal** [comment]
Not sure if there is some Java doc generation somewhere, I didn't find anything. If so, that should probably go here as well.

**Comment by wing328** [comment]
> Not sure if there is some Java doc generation somewhere, I didn't find anything. If so, that should probably go here as well.

Don't recall that off the top of my head.

**Comment by wing328** [comment]
@kuhnroyal the change looks good 👍 

FYI @OpenAPITools/generator-core-team

**Pull request merged**
