### PR TITLE
java-springcloud: No dependency management if parent overridden

### LINKED ISSUE #3230: [BUG] [SPRING-CLOUD] Remove dependency management tag
In the generated pom of spring cloud a dependency management tag is inserted by the template, although the parent pom is overwritten. Normally the parent pom already defines dependency management. For this reason, version conflicts can occur

Possible solutions are:
1. Introduce new boolean flag in the config
2. Dependendcy management is not inserted as soon as the parent pom is overwritten.

Are there any other solutions?

### PR DESCRIPTION
**Pull request by SirWayne**
If a separate parent pom is specified, there should be no depdendency management

fixes #3230

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

### Description of the PR

If a separate parent pom is specified, there should be no depdendency management, because that can lead to version conflicts

### CODE REVIEW

**Comment by SirWayne** [comment]
@macjohnny @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @wing328 

Is there any objection to merge this?
If this is into the next release, it would make a lot easier for us.
Thank you

**Comment by jmini** [comment]
CircleCI for the `master` branch after this merge (commit https://github.com/OpenAPITools/openapi-generator/commit/b20118b87c705b8f0f9ef6968aa75bfb61bdc67a) is failing:
https://circleci.com/gh/OpenAPITools/openapi-generator/8135#tests/containers/2

Because the samples were not correctly update:

```diff
diff --git a/samples/client/petstore/spring-cloud-async/pom.xml b/samples/client/petstore/spring-cloud-async/pom.xml
index b14446583f..db09f2e259 100644
--- a/samples/client/petstore/spring-cloud-async/pom.xml
+++ b/samples/client/petstore/spring-cloud-async/pom.xml
@@ -66,5 +66,10 @@
             <artifactId>spring-boot-starter-test</artifactId>
             <scope>test</scope>
         </dependency>
+        <dependency>
+            <groupId>org.hibernate.validator</groupId>
+            <artifactId>hibernate-validator</artifactId>
+            <version>6.0.16.Final</version>
+        </dependency>
     </dependencies>
 </project>
```

This might be because of concurrent merges

**Comment by jmini** [comment]
Pushed as commit https://github.com/OpenAPITools/openapi-generator/commit/fae073874b3f1a5350f4e31c4168c7d97b8921be

**Comment by macjohnny** [comment]
@jmini thanks for the updated samples.

**Pull request merged**
