### PR TITLE
[#19947] add parameter 'useURLSearchParams' to use JS build-in UrlSearchParams, instead of deprecated npm lib 'querystring'

### LINKED ISSUE #19947: [REQ] [JavascriptClientCodegen] Deprecated npm lib 'querystring'
### Is your feature request related to a problem? Please describe.

The JavaScript Client Codegen still generates code with the deprecated npm lib ['querystring'](https://www.npmjs.com/package/querystring). However, JavaScript has already built-in functions and does not need the deprecated library anymore.

### Describe the solution you'd like

I'd like to have the option to use plain JavaScript and no deprecated third-party dependencies.

### PR DESCRIPTION
**Pull request by tobifb**
Fixes #19947 

- Added a new parameter 'useURLSearchParams' to the JavaScript Client Codegen
- If set to true, the deprecated npm ['querystring'](https://www.npmjs.com/package/querystring) is not generated anymore in the javascript code. Instead we use [UrlSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), which is a built-in function of javascript.
- If set to false, the old behavior is still generated.
- Default value is 'false'

Additional tests:
- manual testing with openapi-generator-cli additional properties and configuration file

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@CodeNinjai @frol @cliffano

### CODE REVIEW

**Comment by wing328** [comment]
@tobifb thanks for the PR

what about simply replacing the deprecated lib without an option?

from what I understand, this is not a breaking change (even without the option)

**Comment by wing328** [comment]
tested the option with updated samples via https://github.com/OpenAPITools/openapi-generator/pull/20002

and the result is good

i'll file another PR to make this option enabled by default

thanks again for the PR

**Comment by wing328** [comment]
To fallback, set `useURLSearchParams` to false, e.g. `--additional-properties useURLSearchParams=true` in the CLI

**Comment by tobifb** [comment]
Sorry for the late reply. Thanks for the changes!

**Pull request merged**
