### PR TITLE
Readonly properties for Swift 5

### LINKED ISSUE #6046: [REQ][SWIFT5] Readonly properties on struct models
### Is your feature request related to a problem? Please describe.

Structs support immutability after initialization. Immutable data types, particularly value types like structs, encourage functional programming practices. By reducing shared mutable state inherit in objects with mutable properties, using immutable value types makes it less likely that UI appears out of sync with an application's data. 

## Describe the solution you'd like

Swift4/5 structs, when built without Objective-C compatibility, rather than declaring their properties with the `var` keyword, can use `private(set) var` keywords to make them only be mutated by the struct's initializer.

This solution could be enabled through an additional property that defaults to false.

## Describe alternatives you've considered

The `let` keyword for properties on structs cannot be combined with default values. So, to keep the syntax consistent between properties that have default values and those that don't, use `private(set) var` instead.

### PR DESCRIPTION
**Pull request by iliaskarim**
Resolves #6046 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

CC: @jgavris @ehyche @Edubits @jaz-ah @4brunu

### CODE REVIEW

**Comment by 4brunu** [comment]
Thanks for submitting this PR.
Looks good to me 👍

**Comment by 4brunu** [comment]
Just one question, is there any reason why you choose ‘private(set) var’ instead of ‘let’?

**Comment by iliaskarim** [comment]
> Just one question, is there any reason why you choose ‘private(set) var’ instead of ‘let’?

Good question, it's because `private(set) var` works for properties with default values whereas `let` does not, it will generate a build error.

**Comment by 4brunu** [comment]
You are right, good catch, thanks for explaining it.
For me this can be merged 👍

**Pull request merged**
