### PR TITLE
[PHP] Include microseconds in serialized date-time

### PR DESCRIPTION
**Pull request by hinrik**
FYI @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @ybelenko, @renepardon

### CODE REVIEW

**Comment by wing328** [comment]
CI failed with the following error:
```
........F........................................................ 65 / 69 ( 94%)
....                                                              69 / 69 (100%)
Time: 1.6 seconds, Memory: 10.00 MB
There was 1 failure:
1) OpenAPI\Client\DateTimeSerializerTest::testDateTimeSanitazion
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'1973-04-30T17:05:00.000+02:00'
+'1973-04-30T17:05:00+02:00'
/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/php/OpenAPIClient-php/tests/DateTimeSerializerTest.php:20
```

Can we make the datetime format configurable similar to what we've done in other languages?

e.g. C# client: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Client/Configuration.cs#L338

**Comment by ackintosh** [comment]
I think making the format configurable is good idea. It could be available with adding the format into ObjectSerializer's static property.

```php
ObjectSerializer::setDateTimeFormat(\DateTime::RFC3339_EXTENDED);
```

**Comment by ackintosh** [comment]
https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/28988450
> fatal: unable to access 'https://github.com/wing328/swagger-samples/': Failed to connect to github.com port 443: Timed out

@wing328 Could you retry the job?

**Comment by wing328** [comment]
@hinrik thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Pull request merged**
