### PR TITLE
Fixes object serialization when there is an inline array property which contains a refed enum

### PR DESCRIPTION
**Pull request by spacether**
Fixes object serialization when there is an inline array property which contains a refed enum 
The problem was that when we convert the object model to a dict, we were not correctly handling the list of ModelSimple instances.
My code update fixes that.

@cgfarmer4 this should fix the bug that you filed

Tests:
- test added showing instantiation of the model with the array property works
- api serialization/deserialization test added

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by cgfarmer4** [comment]
Hi @spacether - heads up, I just ran `latest-release` from docker for `python` and this seems to be doing the thing again.

` initial_products=[Products('assets')],` ends up as `{'value': Assets} in JSON`

**Comment by spacether** [comment]
What git hash is latest release from? We have a live test in master showing that this is fixed there.

**Comment by spacether** [comment]
Can you please reopen your issue with more details?

**Comment by cgfarmer4** [comment]
Oof sorry. User error. I will be on the look out for `5.0.1`.

**Comment by spacether** [comment]
Phew, scared me

**Pull request merged**
