### PR TITLE
Dart (Jaguar) client generator

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

As discussed with @jaumard, I've cherry-picked his commit (a1e50a6) to add Dart (Jaguar) client generator to this project (OpenAPI Generator)

### CODE REVIEW

**Comment by wing328** [comment]
@jaumard as requested, I've cherry-picked 2fbf92e4d9d119750e6407a40e4fc02a792506ef into this PR (after resolving the merge conflicts)

**Comment by wing328** [comment]
Merged https://github.com/OpenAPITools/openapi-generator/pull/1009 into this branch.

**Comment by wing328** [comment]
cc @ircecho @swipesight for review

**Comment by jaumard** [comment]
Just notice a bug in Jaguar, need to fix and update the deps in this PR, should be done today and doesn't change the rest of the PR. Just dependency bump

**Comment by wing328** [comment]
@jaumard I've updated the pom to include the following in the Travis CI build:
```
                <module>samples/client/petstore/dart-jaguar/openapi</module>
                <module>samples/client/petstore/dart-jaguar/flutter_petstore/openapi</module>
```

The good thing is that the build is green and I'm able to trigger a failure by manually breaking the code.

**Comment by jaumard** [comment]
Nice !!! So I didn't do that much shit :p lol

**Comment by wing328** [comment]
@jaumard thanks for your awesome contribution.

If no question from @ircecho @swipesight , I'll merge it into master tomorrow.

**Comment by wing328** [comment]
@jaumard thanks for the PR, which has been merged into master.

We'll send out a tweet to promote the new generator and tag your twitter account (https://twitter.com/jaumard)

**Comment by jaumard** [comment]
No problem ! Thanks a lot for your help on this !

**Comment by wing328** [comment]
Tweet: https://twitter.com/oas_generator/status/1040537944296046592

Please retweet to help promote the new generator

**Pull request merged**
