### PR TITLE
[Php] Convert boolean value for query string (Configuration)

### PR DESCRIPTION
**Pull request by ksvirkou-hubspot**
This PR creates an property in configuration "booleanFormatForQueryString"
User can set the format for conversation of boolean to the query string
user can set int (param=1 or param=0) or string (param=true or param=false)
int is default format because [guzzle/psr7](https://github.com/guzzle/psr7) converts boolean to int (param=1 or param=0)

example of use
```php
$config = new Configuration();
$config->setBooleanFormatForQueryString(Configuration::BOOLEAN_FORMAT_STRING);
$config::setDefaultConfiguration($config);

$api = new APIClass($client, $config);
```

it will fix https://github.com/OpenAPITools/openapi-generator/issues/11683

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ksvirkou-hubspot** [comment]
@jebentier , @dkarlovi , @mandrean , @jfastnacht , [@ybelenko](https://github.com/ybelenko) , @renepardon

**Comment by ksvirkou-hubspot** [comment]
Any updates?
@ybelenko @wing328

**Comment by wing328** [comment]
I'm ok with it. If no further feedback/question for this PR, I'll merge it tomorrow.

Thanks for the PR.

**Review by ybelenko — APPROVED** [review]

**Comment by ybelenko** [comment]
Just checked locally under php 8.1.6:
```console
vendor/bin/phpunit tests/ObjectSerializerTest.php
PHPUnit 9.5.20

................................................................. 65 / 65 (100%)


Time: 00:00.087, Memory: 6.00 MB

OK (65 tests, 76 assertions)
```
The code looks fine. 👍

**Pull request merged**
