### PR TITLE
Adding retries option to override default value 3 of urllib3

### PR DESCRIPTION
**Pull request by chowmean**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Adding retries option to override the default value of urllib which is 3. This will give option to control number of retries for any request.

### CODE REVIEW

**Comment by wing328** [comment]
@chowmean thanks for the PR. Can you please also update the Python Petstore samples by running the shell scripts (./bin/python*) or batch files under (bin\windows\python*) ?

**Comment by wing328** [comment]
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

**Comment by chowmean** [comment]
> @chowmean thanks for the PR. Can you please also update the Python Petstore samples by running the shell scripts (./bin/python*) or batch files under (bin\windows\python*) ?

Ran the ensure_upto_date which runs all the scripts. I guess that is fine? @wing328

**Comment by wing328** [comment]
Yup, and all tests passed 👍

**Pull request merged**
