### PR TITLE
[FEAT][TYPESCRIPT-ANGULAR] Add configurationPrefix option

### LINKED ISSUE #4101: [REQ][typescript-angular] Option to rename ApiModule and Configuration
### Is your feature request related to a problem? Please describe.

Generated angular client module will always be called `ApiModule`. 
The module also exposes a `Configuration` object which also cannot be renamed.

This isn't great when multiple generated clients are needed in a single project.

## Describe the solution you'd like

I'd like an Config Option for typescript-angular that can configure the `Module` and `Configuration` prefix. 

Option | Description | Values | Default
-- | -- | -- | --
modulePrefix | The prefix of the file and class of the generated module (\<prefix>.module.ts and `class <prefix>Module`). |   | Api
configuraionPrefix | The prefix of the file and class of the generated configuration object (\<prefix>Configuration.ts and `class <prefix>Configuration`). |   | null

**Note** _the names are in the default fileNaming: camelCase format, but kebab-case should also be supported_

### PR DESCRIPTION
**Pull request by sorohan**
Allow the `Configuration` (and `ConfigurationParameters`) APIs to be created unique by specifying a `configurationPrefix`.

This resolves #4101.

### CODE REVIEW

**Comment by sorohan** [comment]
@macjohnny I'd appreciate your feedback on this one. It's the missing half of #7498 

I think it will conflict with the [other PR](https://github.com/OpenAPITools/openapi-generator/pull/7725) I have open, but obviously I can rebase it after that one is merged.

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by jcimoch** [comment]
When it will be available in 5.x release?

**Comment by macjohnny** [comment]
@jcimoch see https://github.com/OpenAPITools/openapi-generator/milestone/20

**Comment by jcimoch** [comment]
@macjohnny  you mean when all items will be finalized? won't be there any more beta release including this?

**Comment by macjohnny** [comment]
@jcimoch a release is over-due. Also, not all items need to be completed. According to the release schedule there should be a another beta.

**Pull request merged**
