### PR TITLE
[Java][jaxrs-spec] Fix #13444 enumUnknownDefaultCase true now returns correctly in fromValue

### LINKED ISSUE #13444: [BUG][jaxrs-spec] enumUnknownDefaultCase not deserialized
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

using the jaxrs-spec (and probably other jaxrs) generator the  'enumUnknownDefaultCase' property is not working correctly:
altough the additional enum value is created, the value is not used in the deserialization of the enum

###### Expected Output
````java
  @JsonCreator
  public static ColorDto fromValue(String value) {
    for (ColorDto b : ColorDto.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }
````
###### Actual Output
````java
  @JsonCreator
  public static ColorDto fromValue(String value) {
    for (ColorDto b : ColorDto.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
````

##### openapi-generator version

6.1.0

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 2.0.0
  title: test
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      responses:
        '200':
          description: OK
components:
  schemas:
    Color:
      type: string
      enum: [RED, BLUE, GREEN]
```

##### Generation Details

using the openapi-maven-generator plugin with configOption
````
<enumUnknownDefaultCase>true</enumUnknownDefaultCase>
````

##### Steps to reproduce

generate code

##### Related issues/PRs

In https://github.com/OpenAPITools/openapi-generator/issues/11886 the same problem was fixed for the 'java' generator

##### Suggest a fix

in 'modelEnum.class', 'enumClass.mustache' and 'enumOuterClass.mustache' in resources/JavaJaxRs **and all subfolders**:

replace
````
{{#isNullable}}return null;{{/isNullable}}{{^isNullable}}throw new IllegalArgumentException("Unexpected value '" + value + "'");{{/isNullable}}
````

with 
````
{{#isNullable}}return null;{{/isNullable}}{{^isNullable}}{{#enumUnknownDefaultCase}}{{#allowableValues}}{{#enumVars}}{{#-last}}return {{{name}}};{{/-last}}{{/enumVars}}{{/allowableValues}}{{/enumUnknownDefaultCase}}{{^enumUnknownDefaultCase}}throw new IllegalArgumentException("Unexpected value '" + value + "'");{{/enumUnknownDefaultCase}}{{/isNullable}}
````

### PR DESCRIPTION
**Pull request by DeaneOC**
This fixes #13444 and now deserializes correctly by returning `UNKNOWN_DEFAULT_OPEN_API`when `enumUnknownDefaultCase` is set to true.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

Contributed on behalf of the [@opencastsoftware](https://github.com/opencastsoftware) open source team. :wave:

### CODE REVIEW

**Comment by lmller** [comment]
what's the status here? What's missing for this to be merged (except the conflicts).
I would really like this to be fixed ❤️

**Comment by rpauesov** [comment]
Waiting for?

**Comment by gijsdh** [comment]
Can we get this moving forward?

**Comment by wing328** [comment]
filed https://github.com/OpenAPITools/openapi-generator/pull/18910 with resolved merge conflicts

will merge if all tests pass

**Pull request closed without merging**
