### PR TITLE
Add Micronaut server generator

### PR DESCRIPTION
**Pull request by andriy-dmytruk**
### Description
Adds server implementation using [Micronaut framework](https://micronaut.io/).

Changes to folder structure in the `modules/open-api-generator/src/main/resources/java-micronaut folder` in order to retain some common client and server features and splitting others - (`common`, `client`, `server`) folders.

### Tasks
- [x] Added generator class
- [x] Registered class in SPI file `modules/openapi-generator/src/main/resources/META-INF/services/org.openapitools.codegen.CodegenConfig`, verified that build does not fail `./mvnw clean package`
- [x] Added test class in `modules/openapi-generator/src/test`
- [x] Created config  `./bin/configs/java-micronaut-server.yaml`
- [x] Generated samples with `./bin/generate-samples.sh`, verified that all test pass with `./mvnw package integration-test -P "java-micronaut-client,java-micronaut-server,-openapi-generator`
- [x] Generated docs `./bin/utils/export_docs_generators.sh`

### Mentions
* Openapi generator core team member @wing328
* Micronaut creator @graemerocher
* Openapi generator Java Technical committee: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch

### CODE REVIEW

**Comment by nyilmaz** [comment]
@andriy-dmytruk tested with this pr, found 2 issues, 

1. in those files:

params/beanValidation.mustache
model/beanValidation.mustache

`@Email` annotation should be proceeded with a single space, otherwise code is generated like;

`@EmailString`


2. controller.mustache has unused import:

`import io.micronaut.http.client.annotation.Client;`

**Comment by andriy-dmytruk** [comment]
@nyilmaz Thanks for the info. I will make corrections accordingly.

**Comment by pbthorste** [comment]
This is a very interesting PR - what is needed to get it merged ?

**Comment by wing328** [comment]
Tested locally and the result is good.

**Pull request merged**
