### PR TITLE
Nullable subschemas

### LINKED ISSUE #12838: [BUG] [Engine] InlineModelResolver creates weird named duplicate inline models and there is no way to turn it off
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

InlineModelResolver introduced a critical regression bug for nullable objects in OpenAPI schema

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or URL

https://github.com/OpenAPITools/openapi-generator/pull/12237

modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java

##### Generation Details

Let's say we have an object defined in my OpenAPI 3.0.3 schema
```
    LoginPasswordlessResponse:
      type: object
      properties:
        user:
          allOf:
          - $ref: '#/components/schemas/BaseUser'
          nullable: true
        token:
          type: string
          nullable: true
```

Before this PR, the OpenAPI generator will link `LoginPasswordlessResponse.user` to `BaseUser` without creating a redundant inline model.

But now it will create a new model called `LoginPasswordlessResponse_user`

```
[main] INFO  o.o.codegen.InlineModelResolver - Inline schema created as LoginPasswordlessResponse_user. To have complete control of the model name, set the `title` field or use the inlineSchemaNameMapping option (--inline-schema-name-mapping in CLI).
```

And I cannot overwrite it with `--inline-schema-name-mappings` option because if I overwrite `LoginPasswordlessResponse_user` with `BaseUser `the whole openapi generator will just break due to duplicate model names.

(and by the way you missed the ending "s" in the log output, which is very misleading. I spend hours on figuring out why --inline-schema-name-mapping is an invalid option, turns out it should be --inline-schema-name-mappings)

##### Steps to reproduce

Shown above

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/12237

### PR DESCRIPTION
**Pull request by mrginglymus**
Fixes #12838 in the same way #13303 by not generating a new inline model if the _only_ difference is in `readOnly` or, now,  `nullable`.

### CODE REVIEW

**Comment by mrginglymus** [comment]
Ah, this appears to have a wider effect than anticipated.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by mrginglymus** [comment]
Hi @wing328 I think that's fixed now?

**Comment by mrginglymus** [comment]
Hi @wing328 anything more needed from me on this?

**Comment by C0deZLee** [comment]
@wing328 Can we get this MR merged?

**Comment by C0deZLee** [comment]
Checking on this again, could we please merge this in?

**Comment by C0deZLee** [comment]
@wing328 
I'm sure I'm not the only one blocked by the bug this PR fixes for almost over a year and cannot upgrade to OpenAPI 6+, could we please merge this in? 
Thank you very much!

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
Sorry for the delay in reviewing this fix. We can accept this for the time being and moving forward we'll likely the move the fix to OpenAPI Normalizer, which will be introduced by https://github.com/OpenAPITools/openapi-generator/pull/14172.

**Comment by mrginglymus** [comment]
thanks @wing328 - the normalizer looks like a much more sensible approach going forward

**Pull request merged**
