### PR TITLE
[python] chore: Move all hand-written python client tests to one folder

### PR DESCRIPTION
**Pull request by robertschweizer**
### Things that annoy me about the current setup

* There is no clear way of installing or running all Python client tests at once during local development
* Hand-written test code is mixed with generated test code
  * Generated test stubs are not updated during generation (I think because they have been manually modified).
* It is hard to see which hand-written tests already exist
* Some hand-written tests are duplicated, while they should use pytest parametrization to be concise and maintainable

### Proposed solution

This PR

* ..runs all Python client tests in one CI job, in one venv (per Python version)
  * This simplifies local installation of test dependencies + running of the tests
* ..moves all hand-written (manual) tests to one folder
  * This makes duplication more obvious/less likely
  * Several client samples can now be covered with little duplication using parametrization
  * Generated stubs can be regenerated, because hand-written tests are fully separate from them

See separate commits, they should help review a lot. I'm ignoring the pydantic-v1 client, I expect it to be removed soon anyway.

I'm super happy about feedback on this. I don't know if this is a good solution, but I was wondering what could be a good way of making the location of test code more obvious.

Python server samples + tests might join this setup eventually (the fastapi server and Python client should have very similar pydantic models for example).

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@cbornet (2017/09) @tomplus (2018/10) @krjakbrjak (2023/02) @fa0311 (2023/10) @multani (2023/10) @wing328

### CODE REVIEW

**Comment by robertschweizer** [comment]
Any thoughts, maybe @wing328  or @multani?

**Comment by multani** [comment]
Hey @robertschweizer , I tried to take a look at this pull requests (total diff + individual diff) but I didn't really manage to follow what you wanted to do here.

I understand you changed the generated package/project name, but I couldn't really follow afterwards.

Could you guide me a bit more into the change?

**Comment by robertschweizer** [comment]
Thanks for checking it out @multani! I updated the PR description with some motivation, maybe that helps to understand what I'm trying to do.

**Comment by wing328** [comment]
personally i prefer the current way. maybe I just get used to running these tests separately.

i'l let you guys (python contributors, technical committee) decide which way to test moving forward.

**Comment by multani** [comment]
Thanks @robertschweizer!

Note that my comments are a completely subjective, and I'm not authoritative on this topic.

> ### Things that annoy me about the current setup
> 
> * There is no clear way of installing or running all Python client tests at once during local development
> * Hand-written test code is mixed with generated test code    
> * Generated test stubs are not updated during generation (I think because they have been manually modified).
> * It is hard to see which hand-written tests already exist
> * Some hand-written tests are duplicated, while they should use pytest parametrization to be concise and maintainable

I agree all of this could be improved :+1: 

> ### Proposed solution
> 
> * ..runs all Python client tests in one CI job

Personally, I would keep the CI in separated jobs:

* If each job only runs for its specific client (like it was before) this should decrease the overall time of the CI.
* It should also be easier to spot problems as the job should indicate directly which client(s) is (are) buggy. Having all the clients in the same job serializes the tests and makes errors harder to spot IMO.

> * [...] , in one venv (per Python version)

I personally don't think this is a good idea on the long run: I see most of the clients as being kind of independent from each other and by bundling them, there may be in conflict (now or future) and/or between the dependencies; this could be all avoided if they run in separated venvs.

>   * This simplifies local installation of test dependencies + running of the tests

I think it should still be possible, if you resort to a bit more of shell scripting in the 2 new shell scripts you introduced: if you loop over the folders (both at installation time and and while running the tests), you should get both the isolation I mentioned above and a simpler way to run all the tests at the same time.

> * ..moves all hand-written (manual) tests to one folder
>   * This makes duplication more obvious/less likely
>   * Several client samples can now be covered with little duplication using parametrization
>   * Generated stubs can be regenerated, because hand-written tests are fully separate from them

I don't really have a good proposition for that at the moment, beside making it clearer in the generated output which ones are autogenerated and which ones are not.

Another possibility would be to use the generated clients as *libraries* into a sub-folder of a "project" and move the hand-written tests into the "project", calling the generated client library.

Something like this:

* `project-using-openapigenerator/`
  * `pyproject.toml`
  * ...
  * `openapi_client/`: The OpenAPI client that we currently autogenerate
    * `tests/`: the automatically generated tests, generated by the generator
    * ...
  * `tests/`: the folder to store the hand-written tests
    * `test_client.py`: one of the hand-written test, that runs `import openapi_client.xxx`

This would require:

* to create a new "project" folder for each clients
* change the generator configuration to generate the clients as a subfolder into the "project" folder
* configure the "project" folder to be a real Python package that can import the client
* move the hand-written tests into a `tests` subfolder of the *project* folder

It would provide the missing separation between generated/hand-written worlds while keeping all the relevant tests next to what they are testing, at the expense of a slightly deeper / complex folder hierarchy.

**Comment by robertschweizer** [comment]
Thanks for your feedback @multani, @wing328, and the detailed explanation of your concerns!

I understand the concern that we will have different client versions that cannot be installed in the same venv: We already have that situation for the two currently-supported Pydantic versions. There is no way to write a test that's parametrized to cover different generated clients without a common venv, and tests will be copied a lot.

I like your proposal a lot for separating hand-written from generated tests while keeping separate client folders and venvs. It could be done using Hatch envs, so different venvs wouldn't need to be managed for local test execution.

I opened https://github.com/OpenAPITools/openapi-generator/pull/17509 for the uncontroversial part of this PR.

**Pull request closed without merging**
