### PR TITLE
[go-experimental] Fix oneOf generation of primitive types

### PR DESCRIPTION
**Pull request by zippolyte**
Given the following spec 
```yaml
components:
  schemas:
    Something:
      type: object
      oneOf:
        - $ref: '#/components/schemas/One'
        - $ref: '#/components/schemas/Two'
        - $ref: '#/components/schemas/Three'
    One:
      type: string
    Two:
      type: integer
    Three:
      type: object
      properties:
        foo:
          type: integer
```
The go-experimental generator would generate the following struct

```go
type Something struct {
        string *string
        int32  *int32
        Three  *Three
}
```

This fails because the field names `int32` and `string` are reserved keywords.

I fixed it by Capitalizing the field name, but let me know if you think there is a better way to do this.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by zippolyte** [comment]
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07)

**Comment by sebastien-rosset** [comment]
There is a way to specify that some string values are keywords:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java#L63

That list is used by [escapeReservedWord](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientExperimentalCodegen.java#L125) to escape words that are reserved keywords.

**Comment by zippolyte** [comment]
Yeah in the openAPI model, the `oneOf` attribute is an array that contains the list of types composing the `oneOf`, so it's on purpose that it doesn't go through that escaping function I believe.

I didn't want to go into the generator code to change the openAPI model, so I thought of this solution instead.

It also has the benefit of making all fields of the `oneOf` struct exported by capitalizing, so it's more consistent too.

**Comment by zippolyte** [comment]
apparently it's valid go now: https://play.golang.org/p/7BypWiBfakf

**Pull request closed without merging**
