### PR TITLE
[JAVA] - fix BUG 14233 code gen support multiple accept headers where one is default json/application

### PR DESCRIPTION
**Pull request by Breus**
This issue aims to fix [issue 14233](https://github.com/OpenAPITools/openapi-generator/issues/14233). 
This would change some default behavior that multiple accept type headers are now also supported when one of them is the default accept header ("application/json").

For any other list of "produces" (which will be accept headers for the client), this already worked correctly, but there was this oddly looking immediate break whenever one of them is "application/json" which I removed in this PR.

@wing328 the original code was contributed by you quite a while ago. Was this early break for "application/json" intentional and if so, what is its purpose? 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.

- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)

**Note**: By default, the newly introduced flag `onlyUseDefaultMediaTypeForAcceptHeaderIfSet` is set to true so the behavior stays the same, which makes it a backward compatible change. Only when additional property `ONLY_USE_DEFAULT_MEDIA_TYPE_FOR_ACCEPT_HEADER_IF_SET` is set to false, all accept headers will be included if the default media type is one of the produces content types.

- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
  
 PR only targets Java language, technical committee is: @lwlee2608 @Zomzog @karismann @jeff9finger @cbornet (among others)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by Breus** [comment]
Thanks for notifying @wing328: I've updated the author and commiter to be linked to my Github account, instead.

**Comment by Breus** [comment]
@wing328 @lwlee2608 @Zomzog @karismann @jeff9finger @cbornet anyone of you that could please take a look at this PR?

**Comment by martin-mfg** [comment]
LGTM.
Maybe we can even change the default value of `onlyUseDefaultMediaTypeForAcceptHeaderIfSet` from true to false. I.e. use all specified "Accept" values by default. What do you think, @wing328?

The failing test seems to be a temporary hickup. As you can see [here](https://github.com/martin-mfg/openapi-generator/pull/29), all tests are green when running them again.

**Comment by Breus** [comment]
Thanks @martin-mfg, I also think we should change the default but I just wanted to make sure I didn't introduce anything backward-incompatible. Let me know if I can change the default and/or should remove the feature flag.

**Comment by WannabeSoftwareEngineer** [comment]
we are also blocked by this.

**Comment by wing328** [comment]
thanks again for the PR. one concern is there are too many options in the generator.

What about adding the feature without the option as part of this PR as it should work for existing users?

If users later report issues with edge cases, we can add back the option for fallback if needed.

**Comment by wing328** [comment]
please also merge the latest master of the official openapi-generator to your branch so as to trigger all the CI workflows to test the change.

**Comment by Breus** [comment]
@wing328 

> What about adding the feature without the option as part of this PR as it should work for existing users?

Agreed! Feature option is and added by default, in line what @martin-mfg also mentioned. Seems to be the correct behavior anyways.

> please also merge the latest master of the official openapi-generator to your branch so as to trigger all the CI workflows to test the change.

Done! However, workflows on this repository seem to be quite unstable looking at the master branch. To be sure everything works I've built the project locally and ran the Java tests which are all green.

**Comment by Breus** [comment]
@wing328 Can this be merged, please?

**Comment by WannabeSoftwareEngineer** [comment]
@wing328 
It would be highly appreciated if you or a member of the core team could spend some time to examine this pull request

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/7466526684/job/20411483247?pr=15245

can you please update the samples to address the CI failure?

**Comment by wing328** [comment]
merged and updated the samples

sorry for the delay in reviewing.

**Pull request merged**
