### PR TITLE
fix(typescript-axios): adds support for anyOf in typescript-axios generator

### PR DESCRIPTION
**Pull request by vpishuk**
Added support to render `anyOf` schemas into typescript-axios generator.
In scope of this MR the following files were modified/added:
-  `modules/openapi-generator/src/main/resources/typescript-axios/model.mustache` extended so it renders modelAnyOf template in case model contains `anyOf` declaration
- `modules/openapi-generator/src/main/resources/typescript-axios/modelAnyOf.mustache` a template to render models that contain `anyOf` declaration. It follows the same pattern as `oneOf` and `allOf` declarations.

Exmple of schema that had an issue:
```
{
    "type": "object",
    "anyOf": [
        {
            "additionalProperties": false,
            "required": ["type"],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["audience"]
                },
                "uid": {
                    "type": "string"
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "name": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        {
            "additionalProperties": false,
            "required": ["type"],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["creative"]
                },
                "uid": {
                    "type": "string"
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "media_type": {
                            "type": "string",
                            "enum": ["video", "banner"]
                        }
                    }
                }
            }
        },
        {
            "additionalProperties": false,
            "required": ["type"],
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["set"]
                },
                "uid": {
                    "type": "string"
                },
                "attributes": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "set_type": {
                            "type": "string",
                            "enum": ["geo.set.postal_code"]
                        },
                        "created_at": {
                            "type": "string"
                        },
                        "updated_at": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    ]
}

```

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by vpishuk** [comment]
@macjohnny, would you mind to take a look at this change?

**Comment by CNLHC** [comment]
Glad to see someone working on this feature.

@vpishuk  Maybe you can change this [line](https://github.com/vpishuk/openapi-generator/blob/d8bed4228d8b0aa5e5f0c12b4485d20c7310505c/modules/openapi-generator/src/main/resources/typescript-axios/api.mustache#L27) to make this change also works when the `withSeparateModelsAndApi` is false.

PS. I am not the maintainer, I am a user interested in the `anyOf` feature.

**Comment by macjohnny** [comment]
@vpishuk thanks for your contribution

can you add a new configuration similar to https://github.com/OpenAPITools/openapi-generator/blob/028b38d43b2bb1004e3feed39a25e73e697f452f/bin/configs/typescript-fetch-allOf-readonly.yaml#L3, using e.g. https://github.com/OpenAPITools/openapi-generator/blob/028b38d43b2bb1004e3feed39a25e73e697f452f/modules/openapi-generator/src/test/resources/3_0/anyOf.yaml#L1?

also, I think https://github.com/OpenAPITools/openapi-generator/pull/14241#issuecomment-1351407597 makes sense

**Comment by devgertschi** [comment]
Any updates on that fix/improvement?

**Comment by simllll** [comment]
@spacether can you look at this? thanks

**Comment by spacether** [comment]
Sorry, nope. I am no longer a team member of this project.

**Comment by simllll** [comment]
@vpishuk why did you close this issue?

**Comment by vpishuk** [comment]
> @vpishuk why did you close this issue? Is it solved differently?

I don't have time to fix it now...

**Comment by hananurrehman** [comment]
@vpishuk this is issue is still affecting typescript libraries. Can you look into this or suggest us any other approach?

**Comment by vpishuk** [comment]
@hananurrehman Unfortunately, I'm too busy at this time...

**Comment by hananurrehman** [comment]
@vpishuk I can understand. But on my side we're in the middle of a lengthy process of reworking our infrastructure. Could it be possible for you to refer this to any of your colleagues?

**Pull request closed without merging**
