### PR TITLE
[TYPO] [WEBCLIENT] Issue 7425: Fixed comments that referred to RestTemplate.

### LINKED ISSUE #7425: [TYPO] [Java] Comment in webclient ApiClient.mustache refers to RestTemplate
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

A comment in webclient ApiClient.mustache refers to RestTemplate. 

##### openapi-generator version

5.0.0-beta2

##### Steps to reproduce

See lines 146-149 in the [webclient ApiClient.mustache template](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache)

```java
 /**
    * Build the RestTemplate used to make HTTP requests.
    * @return RestTemplate
    */
public static WebClient buildWebClient(ObjectMapper mapper) {
...
}
```

##### Related issues/PRs

None that I found.

##### Suggest a fix

```java
 /**
    * Build the WebClient used to make HTTP requests.
    * @return WebClient
    */
public static WebClient buildWebClient(ObjectMapper mapper) {
...
}
```

### PR DESCRIPTION
**Pull request by dtiller**
Corrected comments that referred to RestTemplate instead of WebClient in libraries/webclient/ApiClient.mustache and libraries/webclient/pom.mustache. Resolves #7425.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@wing328 Here's the PR I promised.

### CODE REVIEW

**Comment by wing328** [comment]
@dtiller thanks for the PR. Can you please run the following to update the samples as well (to fix CircleCI failure)?
```
./bin/generate-samples.sh bin/configs/java*
```

(For Windows users, please run the script in Git BASH)

**Comment by dtiller** [comment]
Done and pushed. I didn't think it was needed because it made no changes to compilable code or output.

**Comment by wing328** [comment]
Updated the samples via https://github.com/OpenAPITools/openapi-generator/pull/7445/commits/06424e078593c2b7c0214fb26ec14ab7d43a6d78. Let's see if that fixes the CI failure.

**Review by wing328 — APPROVED** [review]
All tests passed after updating the samples. Thanks for the fix.

**Pull request merged**
