### PR TITLE
[cpp-ue4] Fix generated code not compiling when using unique array items

### PR DESCRIPTION
**Pull request by roseatromero**
Currently if the `"uniqueItems": true,` is present in the schema for array items, the generated code does not compile due to lack of support for TSet container

```cpp
0>GenericApiOperations.cpp(151): Error C2672 : 'CollectionToUrlString_multi': no matching overloaded function found
0>Helpers.h(203): Reference  : could be 'FString ::CollectionToUrlString_multi(const TArray<T,FDefaultAllocator> &,const TCHAR *)'
0>GenericApiOperations.cpp(151): Reference  : 'FString ::CollectionToUrlString_multi(const TArray<T,FDefaultAllocator> &,const TCHAR *)': could not deduce template argument for 'const TArray<T,FDefaultAllocator> &' from 'const TSet<FString,DefaultKeyFuncs<InElementType,false>,FDefaultSetAllocator>'
0>        with
0>        [
0>            InElementType=FString
0>        ]
```

This PR adds a template that correctly combines the URL parameters for associative container TSet and fixes the compilation issue.

Testing:

Based on the following schema:
```json
"schema": {
    "pattern": "^[^/\\\\]*$",
    "uniqueItems": true,
    "type": "array",
    "items": {
      "type": "string"
    }
  }
```
I verified in the debugger that the URL parameters were added

### CODE REVIEW

**Comment by roseatromero** [comment]
Tagging @Kahncode for visibility

**Comment by Kahncode** [comment]
Hello @roseatromero thanks for the change. 

I feel like this is perhaps a more ambitious direction than I would have taken. Perhaps less correct, but I would have handled "set" as TArray. But I don't understand where the set comes from here, your schema has clearly an Array, so why does it translate to TSet? 

Anyway the change I would suggest is in the file CppUE4ClientCodegen.java to change 
`  typeMapping.put("set", "TSet");`
to 
`  typeMapping.put("set", "TArray");`
as TArray can contain a set of elements after all.

**Comment by roseatromero** [comment]
> Hello @roseatromero thanks for the change.
> 
> I feel like this is perhaps a more ambitious direction than I would have taken. Perhaps less correct, but I would have handled "set" as TArray. But I don't understand where the set comes from here, your schema has clearly an Array, so why does it translate to TSet?
> 
> Anyway the change I would suggest is in the file CppUE4ClientCodegen.java to change ` typeMapping.put("set", "TSet");` to ` typeMapping.put("set", "TArray");` as TArray can contain a set of elements after all.

[TSet ](https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/ProgrammingWithCPP/UnrealArchitecture/TSet/) is an associative rather than a sequence container, that guarantees the items stored inside are unique - hence why it's correctly generated to use it when `uniqueItems` is set to true. With `TArray` there could be duplicates in the generated URL params, which is not what the API is expecting according to the schema.

**Comment by Kahncode** [comment]
Yes of course, it's less correct. What I'm wondering though is how that will be handled if it was body parameters. As far as I can see in the generated files TSet was not handled at all. This is why I mentioned that going for proper support for sets is a more ambitious change. In this case I'd suggest you test more cases, at least body parameters, and support the TSet fully as it is a valuable improvement.

In any case this is a good change as it is and it looks fine to me.

**Comment by wing328** [comment]
ci failure not related to this change.

**Comment by wing328** [comment]
@roseatromero thanks for the PR, which has been merged.

@Kahncode thanks for reviewing the change.

**Comment by wing328** [comment]
@roseatromero can you please PM me via Slack when you've time next week?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Pull request merged**
