### PR TITLE
[java][vertx] moved HttpStatusException (vertx internal) to HttpException (public)

### PR DESCRIPTION
**Pull request by seanbrown-com**
Vertx has moved HttpStatusException (vertx internal) to HttpException (public)

https://github.com/vert-x3/wiki/wiki/4.1.0-Deprecations-and-breaking-changes#iovertxextwebhandlerimplhttpstatusexception

This is a breaking change in vertx, so this is a priority fix. The changes can be tested by adding the plugin to a Java project and building with vertx-core and vertx-web on the current version, 4.2.4.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

NOTE: A similar PR is at https://github.com/OpenAPITools/openapi-generator/pull/10299, but author has been inactive and has not addressed issues with the PR mentioned by @wing328 .

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
I got the following when trying to compile the vertx server samples:
```
[ERROR]   symbol:   class HttpException
[ERROR]   location: class org.openapitools.vertxweb.server.api.PetApiImpl
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/PetApiImpl.java:[40,40] cannot find symbol
[ERROR]   symbol:   class HttpException
[ERROR]   location: class org.openapitools.vertxweb.server.api.PetApiImpl
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/PetApiImpl.java:[44,40] cannot find symbol
[ERROR]   symbol:   class HttpException
[ERROR]   location: class org.openapitools.vertxweb.server.api.PetApiImpl
[ERROR] /Users/williamcheng/Code/openapi-generator/samples/server/petstore/java-vertx-web/src/main/java/org/openapitools/vertxweb/server/api/PetApiImpl.java:[48,40] cannot find symbol
[ERROR]   symbol:   class HttpException
[ERROR]   location: class org.openapitools.vertxweb.server.api.PetApiImpl
```

Does it work for you locally?

**Comment by seanbrown-com** [comment]
> 

What are you using to compile locally? I had to update my pom.xml with the new versions of vertx packages (4.2.4)...

**Comment by wing328** [comment]
>  I had to update my pom.xml with the new versions of vertx packages (4.2.4)...

Can you please update the pom.mustache file as part of the PR?

**Comment by seanbrown-com** [comment]
> > I had to update my pom.xml with the new versions of vertx packages (4.2.4)...
> 
> Can you please update the pom.mustache file as part of the PR?

@wing328 Done... I think this is the correct file.

**Comment by wing328** [comment]
I think it should be this one instead: modules/openapi-generator/src/main/resources/JavaVertXWebServer/supportFiles/pom.mustache 

I updated it locally and confirmed the fix. I'll update it after merging your PR into master

**Pull request merged**
