### PR TITLE
[kotlin-server][jaxrs-spec] treat parameters with a default value as non-null

### PR DESCRIPTION
**Pull request by exaV**
Without this change parameters with a default value as described here https://swagger.io/docs/specification/describing-parameters/ would be treated as nullable. With this change they are now correctly marked as non-null.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by exaV** [comment]
@jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m I'm pinging you  because you're listed as kotlin maintainers.

**Comment by exaV** [comment]
@jimschubert could you please have a look at this MR? It is a small change and non-breaking.

**Comment by exaV** [comment]
rebased onto openapitools/master

**Comment by exaV** [comment]
@wing328 hi I got no response from Kotlin maintainers for a month. Could you help getting this merged?

The change is really quite simple:
I changed the condition for a nullable type from 
`{{^required}}?{{/required}} ` to `{{^defaultValue}}{{^required}}?{{/required}}{{/defaultValue}}` meaning if neither defaultvalue nor required must exist on a property for it to get a nullable type. This is a backwards compatible change because non-null types are assignable to their nullable counterparts.

**Comment by wing328** [comment]
I think we need to consider `nullable: true` as well. I'll file another PR to fix that and add a test.

**Comment by wing328** [comment]
@exaV sorry for the delay in merging this PR as there are too many PRs pending review.

**Comment by wing328** [comment]
FYI. I've filed https://github.com/OpenAPITools/openapi-generator/pull/16265 to fix the default value (e.g. `""available""` instead of `"avaialble"`), add nullable support, and add tests.

**Pull request merged**
