### PR TITLE
[PHP] Fix group parameters in WithHttpInfo method

### LINKED ISSUE #2945: [BUG][PHP] x-group-parameters with bad/weird behavior
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

A generated method is called with a list of parameters instead of a single parameter bag.

```php
public function getBookCollectionWithHttpInfo($associative_array)
{
    $request = $this->getBookCollectionRequest($associative_array['page'], $associative_array['items_per_page'], $associative_array['pagination']);
    ...
}

protected function getBookCollectionRequest($associative_array)
{
    // unbox the parameters from the associative array
    $page = array_key_exists('page', $associative_array) ? $associative_array['page'] : null;
    $items_per_page = array_key_exists('items_per_page', $associative_array) ? $associative_array['items_per_page'] : null;
    $pagination = array_key_exists('pagination', $associative_array) ? $associative_array['pagination'] : null;
    ...
}
```

EXPECTED 

```php
public function getBookCollectionWithHttpInfo($associative_array)
{
    $request = $this->getBookCollectionRequest($associative_array);
    ...
}

```

##### openapi-generator version

4.0.1-SNAPSHOT

##### OpenAPI declaration file content or url

```json
{
  "basePath": "/",
  "info": {
    "description": "Test API v3",
    "title": "TestAPI",
    "version": "1.0.7"
  },
  "paths": {
    "/api/book": {
      "get": {
        "operationId": "getBookCollection",
        "parameters": [
          {
            "description": "The collection page number",
            "in": "query",
            "name": "page",
            "required": false,
            "type": "integer"
          },
          {
            "description": "The number of items per page",
            "in": "query",
            "name": "itemsPerPage",
            "required": false,
            "type": "integer"
          },
          {
            "description": "Enable or disable pagination",
            "in": "query",
            "name": "pagination",
            "required": false,
            "type": "boolean"
          }
        ],
        "produces": [
          "application/ld+json",
          "application/json",
          "text/html"
        ],
        "responses": {
          "200": {
            "description": "bookcollection response",
            "schema": {
              "type": "string"
            }
          }
        },
        "summary": "",
        "tags": [
          "book"
        ],
        "x-group-parameters": true
      }
    }

  },
  "security": [
    {
      "apiKey": []
    }
  ],
  "securityDefinitions": {
    "apiKey": {
      "description": "Value for the X-AUTHENTICATION-TOKEN header",
      "in": "header",
      "name": "X-AUTHENTICATION-TOKEN",
      "type": "apiKey"
    }
  },
  "swagger": "2.0"
}

```

  -->

##### Command line used for generation

```
docker run --rm --user $(id -u):$(id -g) -v ${PWD}:/local \
    openapitools/openapi-generator-cli generate \
        --git-user-id "USER" \
        --git-repo-id "test-client-lib" \
        --release-note "Test Service Client Library" \
        -g php \
        -o /local/${SWAGGER_CLIENT_PATH} \
        -i /local/${SWAGGER_SERVICE}/config/packages/api_platform/swagger/api.json \
        -c /local/${SWAGGER_SERVICE}/config/packages/api_platform/swagger/generator.json
```

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

To fix #2945

### CODE REVIEW

**Comment by ypereirareis** [comment]
Hi, your fix seens ok to me !
Thanks for your reactivity. :smiley: 

Is there a binary or docker image for this PR so I can test it and give you some feedback ?

Bye.

**Comment by wing328** [comment]
> Is there a binary or docker image for this PR so I can test it and give you some feedback ?

Unfortunately, pulling the branch and building the JAR locally is the only way.

**Comment by ypereirareis** [comment]
Ok I can do this easily with a docker image if you give me the process or command line and requirements to build the JAR. I can build it (build a Makefile or so) and give you my work after that so  you can add it in the project for future PRs.

**Comment by wing328** [comment]
Let's have the PHP technical committee review it before merging it into master.

cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) ❤️, @ybelenko (2018/07), @renepardon (2018/12)

**Comment by wing328** [comment]
@ypereirareis the fix has been merged into master. Please try it later when the docker image/JAR snapshot version is available.

**Comment by ypereirareis** [comment]
Good job !! Thanks :+1: :+1: :+1: :+1: :+1:

**Comment by ypereirareis** [comment]
I tested the latest docker image, and everything is ok now. Your fix fixed my bug. Thanks !!!

**Pull request merged**
