### PR TITLE
Decommission NodeJS server generator

### PR DESCRIPTION
**Pull request by wing328**
- Decommission nodejs server generator as the underlying dependencies are no longer maintained (and only worked with OAS v2)

FYI. @YishTish

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by jimschubert** [comment]
Is there another node server implementation we're moving to? If we support OpenAPI 2.0 still, I'm confused why we'd remove a generator supporting only OpenAPI 2.0 rather than displaying a warning?

**Comment by wing328** [comment]
There's a `nodejs-express-server` generator added a while ago.

**Comment by wing328** [comment]
It simply won't even work with OAS v2 spec.

**Comment by jimschubert** [comment]
@wing328 thanks for the quick clarification, I had misunderstood when the express generator was added that it was merged into this one and I thought the PR was removing all node.js support.

**Comment by wing328** [comment]
@jimschubert no problem. All questions are good questions :)

**Pull request merged**
