### PR TITLE
Typescript Angular 2: Make service suffix configurable

### PR DESCRIPTION
**Pull request by tomvangreen**
## PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
In earlier versions of the typescript-angular (2) swagger-codegen / openapi-generator, the suffix of the generated api servies was Api. This has been changed to Service in order to conform to angular naming guidelines. 

For our project it makes sense that we can chose a different prefix in order to avoid naming collisions. For this I introduced 2 configuration parameters. `serviceSuffix` and `serviceFileSuffix`.

Service suffix is used as a suffix in the generated class name. Service file suffix is used as suffix in the file name (before the .ts extensions).

Technical comitee typescript: @TiFu, @taxpon, @sebastianhaas, @kenisteward, @Vrolijkx, @macjohnny 
#234

### CODE REVIEW

**Comment by kenisteward** [comment]
What do you meant by naming collisions? What problems are you getting that
can't be resolve with

Import { service as another name } from '@myscope/service'

**Comment by tomvangreen** [comment]
We are doing aliasing now, but we have a lot of services that exist in the api and have a counter part that we have written ourselves, which uses the same name (I know, this is not optimal, but we inherited this code base). Aliasing comes with some disadvantages. Auto import in IDE's does not work so well, as you anyway need to manually alias it after the import (and not aliasing it comes with the danger that you see you have a FooService, but you don't know if it comes from the api or is a service we built). Additionally we can never be sure by just looking at the class, if it is now a service or an api, because it might be that somebody forgot to alias the service.

Additionally, I really like to have the distinction between generated and self written serviecs. Having this api suffix makes it clear (without having to consult the import statement) on what exactly we are looking at. Honestly I was a bit bummed when the suffix has been changed from api to service.

All in all, it would make our lifes a bit easier and let us concentrate on the real work ;)

**Comment by kenisteward** [comment]
Yeah you are right in thinking we changed the generator from API to service
in order to be more confirming to angular standards.

It is unfortunate, that you have the situation on your hands and we
appreciate the PR!

I'll look into this more when I am at a computer but if you are solely
changing names I should be able to approve this pretty quickly

**Comment by kenisteward** [comment]
@tomvangreen did you regenerate the samples and got no changes?

**Comment by tomvangreen** [comment]
You're welcome for the pull request, wasn't too much work.

I would be happy if you could check that I did not break anything. I tried to implement the change in a non breaking manner (meaning you should have an identical output when you don't supply the new config parameters), but I would feel better if you could validate that before merging back.

**Comment by tomvangreen** [comment]
I reran the angular tests (on windows with the script typescript-angular-petstore-all.bat ) and the only thing that has changed is the VERSION file in the .openapi-generator folder.

**Comment by kenisteward** [comment]
As long as you have generated it using another rname for your own personal
uses that should be enough of a test .

**Comment by macjohnny** [comment]
@tomvangreen could you please merge the most recent master into your branch to re-trigger the CircleCI tests?

**Comment by macjohnny** [comment]
> ...it looks like it is unrelated to my changes.

@tomvangreen absolutely, it usually is due to some rate-limits for artifact downloads from other locations. Usually re-triggering the CircleCI build solves the issue. You can also manually do that by closing and re-opening your PR

**Comment by macjohnny** [comment]
@tomvangreen now it was the Shippable build that ran into the same issue...

**Comment by tomvangreen** [comment]
@macjohnny What can I do about that? Should I wait a day and close and reopen again?

**Comment by macjohnny** [comment]
@tomvangreen yes, so far I don't know of a better solution

**Comment by macjohnny** [comment]
other PRs face the same problem, see e.g. https://github.com/OpenAPITools/openapi-generator/pull/289#issuecomment-399060429

**Comment by wing328** [comment]
The `rust-server` can be ignored (commented out in the master for the time being):
```
   Compiling petstore_api v1.0.0 (file:///home/travis/build/OpenAPITools/openapi-generator/samples/server/petstore/rust-server)
error: lint unused_doc_comment has been renamed to unused_doc_comments
 --> examples/server_lib/mod.rs:6:5
  |
6 |     error_chain!{}
  |     ^^^^^^^^^^^^^^
  |
  = note: `-D renamed-and-removed-lints` implied by `-D warnings`
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: lint unused_doc_comment has been renamed to unused_doc_comments
 --> examples/server_lib/mod.rs:6:5
  |
6 |     error_chain!{}
  |     ^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: lint unused_doc_comment has been renamed to unused_doc_comments
 --> examples/server_lib/mod.rs:6:5
  |
6 |     error_chain!{}
  |     ^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: lint unused_doc_comment has been renamed to unused_doc_comments
 --> examples/server_lib/mod.rs:6:5
  |
6 |     error_chain!{}
  |     ^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 4 previous errors

error: Could not compile `petstore_api`.
warning: build failed, waiting for other jobs to finish...
```

**Comment by wing328** [comment]
@kenisteward @macjohnny thanks for reviewing the change.

@tomvangreen thanks for the PR. For your upcoming PRs, I would suggest creating a branch as per git best practices.

**Comment by tomvangreen** [comment]
@wing328 You're welcome, in the end the change should make my live easier in multiple projects, so I'm happy to help. I messed up with the branch. I did the change first for swagger codegen and then I wanted to port the changes to openapi codegen and forgot to create the branch in this repo. I try to keep that in mind for future pull requests.

**Pull request merged**
