### PR TITLE
fix: use config basePath instead of the class context basePath

### PR DESCRIPTION
**Pull request by sahanatroam**
fixes https://github.com/OpenAPITools/openapi-generator/issues/8176

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by sahanatroam** [comment]
@macjohnny could you help understand why the build is failing?

**Comment by wing328** [comment]
For the CircleCI failure, can you please merge the latest master into your branch as we've fixed that issue in the master already?

**Comment by sahanatroam** [comment]
@wing328 that didn't quite work, unsure what the issue might be here. Are you able to help?

**Comment by wing328** [comment]
```
Dec 15, 2020 3:59:06 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection reset
Dec 15, 2020 3:59:06 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.5:add-source (scala-compile-first) on project openapi-scala-client: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.1.5:add-source failed: Plugin net.alchim31.maven:scala-maven-plugin:3.1.5 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.scala-lang:scala-library:jar:2.9.2, com.typesafe.sbt:incremental-compiler:jar:0.12.1, org.scala-lang:scala-compiler:jar:2.9.2: Could not transfer artifact org.scala-lang:scala-library:jar:2.9.2 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/scala-lang/scala-library/2.9.2/scala-library-2.9.2.jar from central failed: Connection reset -> [Help 1]
[ERROR] 
```
Due to throttling as this project is too active, I'll restart the job an hour later to see if we've any luck.

**Review by macjohnny — APPROVED** [review]
LGTM

**Pull request merged**
