### PR TITLE
[Dart-dio] Add basic integration testing and fix compile errors

### PR DESCRIPTION
**Pull request by kuhnroyal**
This PR adds a basic integration test to the Dart-dio generator.
There are no real tests for the moment but OpenApi test templates are added which generate empty test cases. Running these empty test cases at least ensures that the generated code compiles.

The PR also fixes 2 compile errors that are now catched due to the tests.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@josh-burton I have added a some integration testing and fixed 2 compile errors. One caused by the inline enum support.
Can you try to run this on your side and maybe try with one of your other PRs rebased on this?
```
./mvnw package
./bin/generate-samples.sh bin/configs/dart-dio.yaml
./mvnw integration-test -f samples/client/petstore/dart-dio/pom.xml
```

**Comment by kuhnroyal** [comment]
CC @ircecho @swipesight @jaumard @amondnet This should be good to go as an initial starting point for integration tests for dart-dio. However these don't run automatically. What is the process there?

**Comment by kuhnroyal** [comment]
@wing328 Mentioning you cause you merged all the last Dart PRs.
@agilob FYI, please review if you can spare the time.

**Comment by wing328** [comment]
Can you please add the following line to https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L1352 so that the CI will run the tests as part of the build?
```
                <module>samples/client/petstore/dart-dio</module>
```

**Comment by wing328** [comment]
@kuhnroyal thanks for the PR to add test coverage for the petstore dart-dio client 👍

**Pull request merged**
