### PR TITLE
[Java] allow to skip default toString, equals and hashCode

### PR DESCRIPTION
**Pull request by borsch**
Allow to skip default `toString`, `equals` and `hashCode`. Related issue: https://github.com/OpenAPITools/openapi-generator/issues/8210

### PR checklist
 
- [+] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [+] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [+] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [+] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [+] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [+] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
@borsch thanks for the PR. What about using customized template (CLI option: `-t`) ?

**Comment by borsch** [comment]
@wing328 yes, it's possible to use options, but it's required to maintain template by your own and keep it up-to date when you change version of generator. Also in my case I have both: separate DTOs for backend and DTOs for client libraries(both java) and this brings two separate templates

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

**Comment by wing328** [comment]
> |skipDefaultEqualsAndHashCode|Skip default equals and hashCode(won't be generated)| |false|
|skipDefaultToString|Skip default toString(won't be generated)| |false|

I think using customised templates is the right solution here. What if there's another use case to skip only Equals but not hashCode? We need another option? If we're going this direction, we will need an option for every single functions in the auto-generated model files, which does not seem feasible.

Customized templates are not hard to maintain if doing it right. Ping me if you need tips on using it to meet this particular requirement.

**Comment by dgamboav** [comment]
> > |skipDefaultEqualsAndHashCode|Skip default equals and hashCode(won't be generated)| |false|
> > |skipDefaultToString|Skip default toString(won't be generated)| |false|
> 
> I think using customised templates is the right solution here. What if there's another use case to skip only Equals but not hashCode? We need another option? If we're going this direction, we will need an option for every single functions in the auto-generated model files, which does not seem feasible.
> 
> Customized templates are not hard to maintain if doing it right. Ping me if you need tips on using it to meet this particular requirement.

Hi William,

Nice to meet you, I'm investigating how to implement customized templates for skip default ToString behavior by using openapi-generator-gradle-plugin:5.1.0 Java, could you recommend some specific documentation? Thank you!

**Comment by AnnKont** [comment]
> > |skipDefaultEqualsAndHashCode|Skip default equals and hashCode(won't be generated)| |false|
> > |skipDefaultToString|Skip default toString(won't be generated)| |false|
> 
> I think using customised templates is the right solution here. What if there's another use case to skip only Equals but not hashCode? We need another option? If we're going this direction, we will need an option for every single functions in the auto-generated model files, which does not seem feasible.
> 
> Customized templates are not hard to maintain if doing it right. Ping me if you need tips on using it to meet this particular requirement.

Hi William @wing328 , I'm searching how to skip default ToString, Equals and HashCode by using openapi-generator-gradle-plugin:4.2.3 Java, could you help me with it?

**Comment by wing328** [comment]
So basically one needs to use customized templates to remove those functions they don't need. In CLI, the option is `-t`, e.g. `-t /var/tmp/customize_templates`. More info in https://github.com/OpenAPITools/openapi-generator/blob/master/docs/templating.md

**Pull request closed without merging**
