### PR TITLE
Use bin/cpp-qt5-petstore.json

### PR DESCRIPTION
**Pull request by MartinDelille**
This PR use the new ``--config`` option in the `bin/cpp-qt5-petstore.sh` script.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@ravinikam @stkrwork @etherealjoy @muttleyxd @jimschubert

### CODE REVIEW

**Comment by wing328** [comment]
No worry. Let me try to fix it.

**Comment by wing328** [comment]
Fixed via 96bbab98a4

We'll find a better way to catch such issue moving forward.

**Comment by MartinDelille** [comment]
I would be cool to have a job that launch the generating scripts, check if they fails and check if there is some diff with `git diff --exit-code`.

Is there an issue about it or shall I create it?

**Comment by wing328** [comment]
We've that in the CI already but the problem with missing config file is that the codegen process still proceeds with default config and completes successfully (exit status code: 0) so it's hard to catch.

We'll instead throw a Runtime exception similar to what we've done for other file input.

**Comment by jimschubert** [comment]
@wing328 we should explicitly reference the root directory. Many of our scripts rely on the original execution path.

**Comment by wing328** [comment]
> Many of our scripts rely on the original execution path.

That's what it's from day 1 I started contributing to this project. Agreed with your suggestion but it will be a lot of work that I would rather suggest spend on other tasks with higher priority instead.

**Pull request merged**
