### PR TITLE
[java] JAX-RS jersey3

### PR DESCRIPTION
**Pull request by sullis**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by sullis** [comment]
This is a draft.  What do you think? @wing328

**Comment by sullis** [comment]
What do you think? @wing328

**Comment by wing328** [comment]
@sullis thanks for the PR. I tested with the following command:
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g jaxrs-jersey --library jersey3 -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/jaxrs/
```
But the code doesn't compile.

Does it work for your locally?

**Comment by wing328** [comment]
FYI. Tested again but got the following errors:
```
[ERROR] /private/tmp/jaxrs/src/main/java/org/openapitools/api/impl/UserApiServiceImpl.java:[43,12] cannot find symbol
[ERROR]   symbol:   class Response
[ERROR]   location: class org.openapitools.api.impl.UserApiServiceImpl
[ERROR] /private/tmp/jaxrs/src/main/java/org/openapitools/api/impl/UserApiServiceImpl.java:[48,150] cannot find symbol
[ERROR]   symbol:   class SecurityContext
[ERROR]   location: class org.openapitools.api.impl.UserApiServiceImpl
[ERROR] /private/tmp/jaxrs/src/main/java/org/openapitools/api/impl/UserApiServiceImpl.java:[48,12] cannot find symbol
[ERROR]   symbol:   class Response
[ERROR]   location: class org.openapitools.api.impl.UserApiServiceImpl
[ERROR] /private/tmp/jaxrs/src/main/java/org/openapitools/api/impl/UserApiServiceImpl.java:[53,32] cannot find symbol
[ERROR]   symbol:   class SecurityContext
[ERROR]   location: class org.openapitools.api.impl.UserApiServiceImpl
[ERROR] -> [Help 1]

```

**Comment by prolez** [comment]
Hi!

What's the progress of this PR?

Cdt

**Comment by wing328** [comment]
@prolez please submit a new PR baesd on this one when you've time.

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/16676

**Pull request closed without merging**
