### PR TITLE
[Swift4] Use CodeableHelper's dateformatter in encode() if configured

### PR DESCRIPTION
**Pull request by manhhavu**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Update Swift4's CodeableHelper to use configured dateformatter in **encode()** method, the same as its **decode()**. 

Opened issue:  #982 

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @d-date (2018/03)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by manhhavu** [comment]
@wing328 : Thanks for the suggestion. I've added the email I used for PR as my secondary email in my Github account (as suggested in [the FAQ](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account)). Let me know if there are any other issues.

**Comment by wing328** [comment]
Here is the test result:
```
▸ Test execute Succeeded
All tests
Test Suite SwaggerClientTests.xctest started
PetAPITests
    ✓ test1CreatePet (2.201 seconds)
    ✓ test2GetPet (0.525 seconds)
    ✓ test3DeletePet (0.587 seconds)
StoreAPITests
    ✓ test1PlaceOrder (0.687 seconds)
    ✓ test2GetOrder (0.557 seconds)
    ✓ test3DeleteOrder (0.764 seconds)
    ✓ testDownloadProgress (0.497 seconds)
UserAPITests
    ✓ testLogin (0.464 seconds)
    ✓ testLogout (0.448 seconds)
    ✓ testPathParamsAreEscaped (0.000 seconds)
```

**Comment by wing328** [comment]
@manhhavu thanks again for the PR, which is included in the v3.3.0 minor release: https://twitter.com/oas_generator/status/1046941449609068544

**Pull request merged**
