### PR TITLE
Bugfix of #11173: go-server get param typecasting if variable enum of string

### PR DESCRIPTION
**Pull request by kellrott**
PR in response to #11173 

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
@antihax 
@grokify 
@kemokemo 
@jirikuncar
@ph4r5h4d

### CODE REVIEW

**Comment by wing328** [comment]
Can you please resolve the merge conflicts when you've time?

**Comment by Wooulf** [comment]
Will we have this fix in the next version?

**Comment by skando-sony** [comment]
I crave for this feature. Will this be fixed soon?

**Comment by lwj5** [comment]
I'll take a look at this and see if the changes apply to the current updates

**Comment by lwj5** [comment]
@kellrott will you be able to update the PR. There has been massive changes in the way we parse objects.

If you do not have the time, let me know. I can open another PR to fix it

**Comment by icubbon** [comment]
I believe this is resolved with https://github.com/OpenAPITools/openapi-generator/pull/16781 which has been merged.

**Pull request closed without merging**
