### PR TITLE
Add result in 500 status code

### PR DESCRIPTION
**Pull request by Gmtstephane**
Hi, in the Go server, we can only have Status code 200 or 500 wether our implementation function return an error or not.

In case or error (err!=nil), the server write the status code 500 without any messages .

```
result, err := c.service.AddPet(*pet)
	if err != nil {
		w.WriteHeader(500)
		return
	}	
	EncodeJSONResponse(result, nil, w)
```

In many cases, their can be several types of error in our implementation, and i wouldlike to return the  error message to the client.
I suggest to Encode the response with the result variable, with the statuscode 500, which will let us write responses in case of error.

```
        if err != nil {
		statusCode := 500
		EncodeJSONResponse(result, &statusCode, w)
		return
	}

```

@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07) @wing328 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by Gmtstephane** [comment]
Still no review ? 
It's been a week and it's quiet a problem.

Thanks

**Comment by kemokemo** [comment]
Hi @Gmtstephane . Thank you for your PR.

> I would like to return the error message to the client.

I agree with you. In order to achieve this, I felt it is better to include the content of `error` in the content to be returned. (I think a lot of implementation styles in the golang return an empty struct or nil if there is an error. So I don't think returning a `result` will often give us useful information.)

Maybe not so good, but how about doing the following, for example?

```go
EncodeJSONResponse(err.Error(), &statusCode, w)
```

or

```go
EncodeJSONResponse(fmt.Sprintf("result: %v, error: %v", result, err), &statusCode, w)
```

On the other hand, from a security point of view, I am concerned about the security risk of returning the contents of the error message to the client, which would normally be written to the log, because it makes the internal implementation predictable.
However, this point can be worked out on the endpoint implementation side, so it may not be as much of a problem as it should be.

@antihax @grokify @bkabrda @wing328
What do you all think?

**Comment by Gmtstephane** [comment]
> I agree with you. In order to achieve this, I felt it is better to include the content of `error` in the content to be returned. (I think a lot of implementation styles in the golang return an empty struct or nil if there is an error. So I don't think returning a `result` will often give us useful information.)

Well i think you are right, it's better to return the error message. I just designed my api to return it as the result, by doing 
`return err.Error(),err` in the implementation, that is why.

Every solution is good to me, as long as we can read the error on the client side.

In my case i am cascading Api: 
 Client 1 make a request to server 1, wich make a request to a server 2 , and then the server 1 respond to the client. In case of error 500 and without any messages, their is no way from the client to know the type of error and it's location.

Thanks for you reply @kemokemo

**Comment by kemokemo** [comment]
@Gmtstephane 
Thank you. It gave me more specifics and an idea of how to use it. That kind of usage would work well.

----
(This is not the main topic of this issue, and it is my personal opinion.)
If you want to find out where errors are occurring in multiple services, I think it would be better to use Prometheus or Elastic Stack to allow the server side administrator to quickly find out what is going on, rather than just from what the client receives.

**Comment by Gmtstephane** [comment]
Still nothing new ?

I added a commit which change the result with the error content.

**Comment by kemokemo** [comment]
I don't think there's a problem if the `service`'s endpoint function is implemented keeping in mind that the returned error content will be passed to the client side as well. I'm OK with this change.

**Comment by Gmtstephane** [comment]
Ok,
I do not know who is able to accept and merge this PR so i allow myself to ping you all.
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07) @wing328

Thanks

**Comment by wing328** [comment]
@Gmtstephane can you please resolve the merge conflicts when you've time? I'll take a look this week when I can find the time.

**Comment by wing328** [comment]
Looks like the master already contains a similar enhancement/fix:

```diff
<<<<<<< HEAD
        EncodeJSONResponse(err.Error(), &result.Code,{{#addResponseHeaders}} result.Headers,{{/addResponseHeaders}} w)
=======
        statusCode := 500
        EncodeJSONResponse(result, &statusCode, w)
>>>>>>> Add result in 500 status code
```

Closing this one for the time being. Can reopen if needed

**Pull request closed without merging**
