### PR TITLE
[java][Okhttp] replace okhttp-gson with okhttp-gson-nextgen

### PR DESCRIPTION
**Pull request by wing328**
- replace okhttp-gson with okhttp-gson-nextgen, which provides better implementations of oneOf, anyOf (breaking changes)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### CODE REVIEW

**Comment by melloware** [comment]
@wing328 we are upgrading from 5.3.4 to 6.0.0 BETA and this change has broken our exception handling.  Particularly in `api.mustache` we had to remove this catch block and our code works again.  We aren't sure what you are trying to do in this catch block.

```js
catch (ApiException e) {
            e.setErrorObject(localVarApiClient.getJSON().getGson().fromJson(e.getResponseBody(), new TypeToken<{{{errorObjectType}}}{{^errorObjectType}}{{{returnType}}}{{/errorObjectType}}>(){}.getType()));
            e.setErrorObjectType(new GenericType<{{{errorObjectType}}}{{^errorObjectType}}{{{returnType}}}{{/errorObjectType}}>(){});
            throw e;
        }
```

**Comment by melloware** [comment]
This is what we get with 6.0.0-BETA:
```java
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
    at com.google.gson.Gson.fromJson(Gson.java:1003)
    at com.google.gson.Gson.fromJson(Gson.java:956)
    at com.google.gson.Gson.fromJson(Gson.java:905)
```

- Generated client tries to find errorObjectType, in the catch block but cannot. Defaults to the return type which is List<Object>
- Bad Request made on endpoint with expected return type of List<Object>
- Response comes back 400 with ApiError object in body
- Since client defaulted to List<Object> as the error type it attempts to use gson to parse the returned ApiError as a List<Object> resulting in error above

**Comment by wing328** [comment]
Thanks for trying out the beta version and the error details. Let me look into it later this week.

can you also share how the response is defined in the spec for that particular endpoint?

**Comment by melloware** [comment]
Yep so first here is what we had to do to make it work:

**Generated client code:**

```java
catch (ApiException e) {
            e.setErrorObject(localVarApiClient.getJSON().getGson().fromJson(e.getResponseBody(), new TypeToken<List<PlannedAnalysis>>(){}.getType()));
            e.setErrorObjectType(new GenericType<List<PlannedAnalysis>>(){});
            throw e;
        }
```
**What it should be:**

```java
catch (ApiException e) {
            e.setErrorObject(localVarApiClient.getJSON().getGson().fromJson(e.getResponseBody(), new TypeToken<ApiError>(){}.getType()));
            e.setErrorObjectType(new GenericType<ApiError>(){});
            throw e;
        }
```

And here is how our OpenAPI endpoint is defined in our code:

```java
	@GetMapping("/")
	@ApiResponses(value = {
		@ApiResponse(responseCode = "200", description = "Planned Analysis found", content = {
							@Content(mediaType = MediaType.APPLICATION_JSON_VALUE, array = @ArraySchema(schema = @Schema(implementation = PlannedAnalysis.class))) }),
		@ApiResponse(responseCode = "404", description = "Planned Analysis does not exist", content = {
							@Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = ApiError.class)) })
	@Operation(summary = "Find Planned Analysis by study guid AND planned analysis name", security = {
		@SecurityRequirement(name = ApplicationConfiguration.BEARER) })
	public ResponseEntity<List<PlannedAnalysis>> findPlannedAnalysisByStudyGuidAndName(
			@Parameter(description = "The study guid", required = true) @RequestParam("studyGuid") @GUID @NotEmpty String studyGuid,
			@Parameter(description = "The name of the Planned Analysis, optional") @RequestParam("plannedAnalysisName") Optional<String> plannedAnalysisName) {
		return plannedAnalysisService.getByPlannedAnalysisNameAndStudyGuid(studyGuid, plannedAnalysisName);
	}
```

Our main response returns `<List<PlannedAnalysis>>` but when we get errors we return a singular `ApiError.class` but the template is assuming its a LIST response not a singular

**Comment by wing328** [comment]
@melloware thanks again for the details.

I've file https://github.com/OpenAPITools/openapi-generator/pull/12131. Can you please give it a try to see if it fixes the issue?

**Comment by melloware** [comment]
Tested and verified your new versions work in our scenarios!

**Pull request merged**
