### PR TITLE
[Kotlin][Spring] useSpringBoot3 and useJakartaEe support for Spring Boot 3

### PR DESCRIPTION
**Pull request by martinformi**
@jimschubert Please, have a look at my first PR in this repository. It was quite straightforward and more or less copied logic from Java spring generator and adjusted templates. Tests verifies if jakarta package is used when `useSpringBoot3` configuration value is set to true.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by martinformi** [comment]
Please, let me know how to fix the CI jobs.

**Comment by jlengrand** [comment]
Hey @martinformi, is it correct that this PR is quite literally doing the same work as this one ? https://github.com/OpenAPITools/openapi-generator/pull/14369.

Given that the other one has been reviewed already, would you please consider merging the work and / or closing this one?

**Comment by jlengrand** [comment]
Putting @parenko in the loop

**Comment by martinformi** [comment]
:-/ I should have looked up if there is already a PR for that. My bad, please let's merge the other one. Looks better. Thank you.

**Comment by parenko** [comment]
I have used this PR as inspiration in #14369 to be similar with Java generator.

**Comment by parenko** [comment]
@martinformi , I think you can close your PR.

**Pull request closed without merging**
