### PR TITLE
feat: [JAVA] [resttemplate] [#13146] added support for abstract file

### PR DESCRIPTION
**Pull request by LubomirS**
…in operation response for rest template

Implements feature https://github.com/OpenAPITools/openapi-generator/issues/13146

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608

### CODE REVIEW

**Comment by LubomirS** [comment]
Hi @wing328, I see this error in one of CicleCI tests, could you please rerun it?
```
Isomorphic Fetch > GET-Request
      Error: Timeout of 2000ms exceeded.
```

**Comment by wing328** [comment]
cc bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

**Comment by wing328** [comment]
I did some tests locally but got the following errors:
```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project openapi-java-client: Compilation failure
[ERROR] /private/tmp/scala-resttemplate/src/test/java/org/openapitools/client/api/PetApiTest.java:[49,35] incompatible types: org.springframework.core.io.Resource cannot be converted to java.io.File
```

Looks like the auto-generated API test files need to be updated as well?

**Comment by LubomirS** [comment]
> I did some tests locally but got the following errors...

I get successful build locally on my branch and all checks in this PR look good as well. I am not sure about the error you are getting.
> Looks like the auto-generated API test files need to be updated as well?

I don't see any scala resttemplate autogenerated files anywhere. Could you point me to the specific test which is failing in your local build?

**Comment by wing328** [comment]
Please run this command:
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g  java --library resttemplate -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/resttemplate/ --additional-properties useAbstractionForFiles=true
```
and test the output in `/tmp/resttemplate`
(please ignore the scala prefix as I was testing scala clients before reviewing your PR)

**Comment by LubomirS** [comment]
> and test the output in /tmp/resttemplate
Thanks, I did that, and in the generated PetApi.java client there is no method that returns org.springframework.core.io.Resource, however there is one which accepts it as a parameter. That might be a problem if you expect File in your PetApiTest. However, this is a change from a different issue, https://github.com/OpenAPITools/openapi-generator/pull/7567

**Comment by wing328** [comment]
Thanks for the explanation. Didn't realize that issue was caused by another PR instead. We'll merge this one.

If you can help us fix that issue with another PR, that would be great.

Otherwise, I'll try to take a look later this week and come up with a PR.

**Pull request merged**
