### PR TITLE
[ruby] Fix generation when generateAliasAsModel is enabled

### PR DESCRIPTION
**Pull request by zippolyte**
Attempt at implementing proper code generation of alias models for map and arrays in the ruby-client.
Previously the class were being generated like so:

```ruby
class Alias < null <InnerType>
...
end
```

I am by no means a ruby expert, so I'd absolutely love some feedback on this. I added a config for a pet store using specifically this feature to check that the generated code looks good, make sure to have a look 😄 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @cliffano (2017/07) @zlx (2017/09) @autopp (2019/02)

### CODE REVIEW

**Comment by zippolyte** [comment]
Bump. cc @OpenAPITools/generator-core-team

It's pretty blocking as we can't use local template patches, and we'd rather avoid having to rely on a custom build from a fork.

**Comment by zippolyte** [comment]
Bump. cc @jimschubert  @wing328 

It's pretty blocking as we can't use local template patches, and we'd rather avoid having to rely on a custom build from a fork.

Thanks 🙇

**Comment by jimschubert** [comment]
@zippolyte Circle CI had failed. I've restarted, but I think it can be merged when done. Thanks for bumping.

**Comment by zippolyte** [comment]
Just rebased on master to try and see if the CI passes

**Comment by zippolyte** [comment]
Hmm not sure what this failure is about 😞

**Review by jimschubert — APPROVED** [review]
LGTM

**Comment by jimschubert** [comment]
@zippolyte thanks for the rebase. It looks like Circle CI just crapped out in the middle of the run. Your changes look good, so we'll merge and fix-forward if Circle breaks in master.

**Pull request merged**
