### PR TITLE
php-laravel, enum models, nullable and default values

### PR DESCRIPTION
**Pull request by aghajani**
+ support for enum models & separating mustache templates for enums and generics
+ extract property 'type' and 'default value' from a #ref to an enum model
+ support for `PascalCase` naming convention for PHP generators
+ use a default value for known basic types when they are not nullable
+ use 'null' as default value for nullable types when they do not specify the default value
+ use defined constant path as enum default value when found

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee] @sgadouar @wing328

### CODE REVIEW

**Comment by aghajani** [comment]
cc @renepardon

**Comment by wing328** [comment]
Thanks for the PR. I've resolved the merge conflicts and filed https://github.com/OpenAPITools/openapi-generator/pull/12480 instead.

**Comment by aghajani** [comment]
Ok, long time before anyone reviews or responds 😁

**Comment by renepardon** [comment]
> Ok, long time before anyone reviews or responds 😁

Sorry, just saw it. Receive way too many mails 🥴

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/12480

Thanks @aghajani  for the PR.

@renepardon no problem. We're all busy :)

**Pull request closed without merging**
