### PR TITLE
[Documentation] Add instructions to build the javascript client module

### PR DESCRIPTION
**Pull request by jdorel**
### PR checklist

I am not sure the unchecked box apply for documentation, please correct me if I am wrong.

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This is a simple documentation PR to add the `npm run build` in the documentation (which was not required previously.

### CODE REVIEW

**Comment by karismann** [comment]
@jdorel  thanks for the PR, may i ask you to locally run `./bin/javascript-petstore-all.sh  `  to commit the update samples with your changes ?

**Comment by jdorel** [comment]
I ran the `./bin/javascript-petstore-all.sh`, but nothing was modified. Here is the result: https://pastebin.com/raw/gaDtnUt4

**Comment by wing328** [comment]
@jdorel did you run `mvn clean package -DskipTests` first before updating the samples?

**Comment by jdorel** [comment]
My bad, I forgot to `git checkout` ... 🤦

**Comment by jimschubert** [comment]
I've made a clarification to the PR template via #2819.

**Pull request merged**
