### PR TITLE
[Typescript] Enums generation

### PR DESCRIPTION
**Pull request by ksvirkou-hubspot**
https://github.com/OpenAPITools/openapi-generator/issues/14569
### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ksvirkou-hubspot** [comment]
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka

**Review by TiFu — COMMENTED** [review]
LGTM!

Would this be a breaking change? 
Before assignments like `let enumVar: Enum = "C"` worked. Does this still work now?

If it doesn't, I would consider this a breaking change which to my understanding should be filed against 7.0.x.

@TS Committee: Any opinions on this?

**Comment by ksvirkou-hubspot** [comment]
> LGTM!
> 
> Would this be a breaking change? Before assignments like `let enumVar: Enum = "C"` worked. Does this still work now?
> 
> If it doesn't, I would consider this a breaking change which to my understanding should be filed against 7.0.x.
> 
> @ts Committee: Any opinions on this?

It is a breaking change as I understand 
`let enumVar: Enum = Enum.Option1`

**Comment by akehir** [comment]
I'm not sure why we need to cast the enum options to `any`, ie:  `{{name}} = <any> {{{value}}}{{^-last}},{{/-last}}`

In any case, with the `any` cast in the enum it shouldn't be breaking - but I'm not sure if with or without the breaking change (ie. with or without the any cast) is better.

**Comment by ksvirkou-hubspot** [comment]
> LGTM!
> 
> Would this be a breaking change? Before assignments like `let enumVar: Enum = "C"` worked. Does this still work now?
> 
> If it doesn't, I would consider this a breaking change which to my understanding should be filed against 7.0.x.
> 
> @ts Committee: Any opinions on this?

It is a breaking change. I've just checked it.

**Comment by akehir** [comment]
If it's a braking change anyways, then I don't think we need to include the `any` cast in the generated enum, or why is it there?

**Comment by ksvirkou-hubspot** [comment]
> If it's a braking change anyways, then I don't think we need to include the `any` cast in the generated enum, or why is it there?

I've just removed `<any>`.

**Comment by akehir** [comment]
@ksvirkou-hubspot : We should change the target branch to 7.0.

Also, I'm not sure if in certain cases the old handling would be preferred (generating a type instead of an enum) - and if we should have a setting to allow for the (old) handling as well. Maybe someone else from the @ts Committee has an opinion on this?

Other than that, the PR looks goot to me.

**Comment by ksvirkou-hubspot** [comment]
> @ksvirkou-hubspot : We should change the target branch to 7.0.
> 
> Also, I'm not sure if in certain cases the old handling would be preferred (generating a type instead of an enum) - and if we should have a setting to allow for the (old) handling as well. Maybe someone else from the @ts Committee has an opinion on this?
> 
> Other than that, the PR looks goot to me.

Do you mean [7.0.x branch](https://github.com/OpenAPITools/openapi-generator/tree/7.0.x)?
@akehir

**Comment by TiFu** [comment]
Not sure tbh. `mvn clean package` works on my machine with the `7.0.x` branch :/ including the download for `spring-boot-dependencies` from `sonatype.org`

**Comment by ksvirkou-hubspot** [comment]
Could you check [this PR](https://github.com/OpenAPITools/openapi-generator/pull/14663), please?
There is an error in the test but it is unrelated.
@TiFu

**Comment by ksvirkou-hubspot** [comment]
Have you checked it by any chance?
@TiFu

**Comment by TiFu** [comment]
Done & merged #14663. 

Will close this PR accordingly.

**Pull request closed without merging**
