### PR TITLE
[Bug] fix: use length to check for default return media type

### LINKED ISSUE #15011: [BUG] Typescript mustache default content-type is not used
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using typescript generator (mustache) there is this check to default to content-type json.
https://github.com/OpenAPITools/openapi-generator/blob/d24ae6b27ab467868bc8d956d72bdf57b58e0198/modules/openapi-generator/src/main/resources/typescript/model/ObjectSerializer.mustache#L197-L201

And all code is being generated by calling this function with either explicit types OR `getPreferredMediaType([])`

where if provided with check of `(!mediaTypes) it always is false. So defaulting is not happening.

Please find reproducer in typescript [playground](https://www.typescriptlang.org/play?target=99#code/FAehGMHsDsGdIDYFMB0DIHMAUGkBcAFAJyQDMkiSATAWSSoEsBDAFQE8AHJAOSQHcsAbQC6ASlHAocRKnTZchEuUr06jVpyRCxE4KBAACAMoMAthwQNSDegYXEyFamubsuB0gFdo4PAxgGAEZICOh8wAYGwF4+fgH2Sk6q9K6aWKYpGlywAFwGAIKUTGwAPLB4RAzQGAB8onnlldUGAN4RkQYgAFRdBeBQRIzNeJAGAPL5RgYAzAZ8SAawABaQnghUBlRkTGt4BiMGAFbw0AZdIO2RUvDIaJhYAIQZ6m5IsBIdBlYGj8+p2aJWpdPgYSHhPERTgAiJgcCwMcBMOLQEDHGBQgDcwIAvsC8EsiJA+AZoPwDABRSiQIhYKHcGALSCkfZLBYYBgANyQpz+TH2mlgBiYJEWnjh1Lw9DyUIMAGoDLzXrAUIdIFVaQAaAxQ8RY3HRby+fynBKOFS0TKvXgCRUCvKFIjFMoVKq1eqLF3NNqfbq9fL9alDDD7UYTKazeaLFZrDZbUg7BB7A5o07nYHXGR3bC27JobkYfEGAC8RYMAAYPh1vulLQK89VCyXy4DvSDImCIdDYfDEcjUSdMTi8QSiSSyZTCTS6QyDEyWWzOdyFZl+dkhSLYGKOBKpdq5cuXnXVeqoVqdaI9cAgA)

##### Generation Details

main branch

##### Suggest a fix

I think this should be the change:
```
  if (!mediaTypes) {
        return "application/json";
    }
```
to
```
   if (mediaTypes.length == 0) {
        return "application/json";
    }
```

### PR DESCRIPTION
**Pull request by mstruebing**
as `mediaTypes` is an array of strings and an required argument it will never be undefined when we can rely on the typesystem. However, it can be zero length(`[]`) and in this case we would throw.

* Closes #15011

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx  @macjohnny @topce  @akehir @petejohansonxo @amakhrov  @davidgamero  @mkusaka 

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by TiFu** [comment]
Thanks for the PR! Change looks good to me.

Could you please re-generate the samples?

**Comment by mstruebing** [comment]
@TiFu could you help me to do that?
I've tried: 

```
./bin/generate-samples.sh ./bin/configs/typescript-*
```

But get:

```
Error: Unable to access jarfile /home/maex/projects/contrib/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar
```

Which is true as this file is not present on my file system. How do I generate that `jar` file?

**Comment by mstruebing** [comment]
@TiFu I've updated the examples.

**Review by WassimBenzarti — APPROVED** [review]

**Review by macjohnny — APPROVED** [review]
LGTM

**Pull request merged**
