### PR TITLE
[typescript-fetch] Allow to generate client without runtime checks

### PR DESCRIPTION
**Pull request by acote-coveo**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

I tried to use the typescript-fetch client with a spec that use union and saw that the types were good but the serialization/deserialization wasn't working pretty well.

## The main problems are:

- Lack of information about oneOf (it only contains a list of data types. A datatype can be `OneType` or `Array<Type1 | Type2 | string | boolean>`) 
- Difficulty to implement imports due to the nested levels of typing.

### Example of what was badly generated

Below, we have a list of `oneOf` data types to map. Thus, to serialize them, we call `dataType[ToJson]`. We then end up with something like `boolean | AdvancedGenerateQueryFieldParameter` **ToJson**

```typescript
export function ToIncludeParametersToJSON(value?: ToIncludeParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fields': value.fields === undefined ? undefined : ((value.fields as Array<any>).map(string | AdvancedQueryFieldParametersToJSON)),
        'summary': boolean | AdvancedGeneratedQueryFieldParameterToJSON(value.summary),
        'excerpt': boolean | AdvancedGeneratedQueryFieldParameterToJSON(value.excerpt),
        'highlighting': HighlightingSettingsToJSON(value.highlighting),
    };
}
```

## Simple solution

A bit like what has been done with the Axios client,I added a flag that allows to generate a client without any runtime checks.

So we simplify the client to only generate the interfaces and cast the input/output to these.
For a small effort, we now are able to have a simple client that compiles.

On a subsequent pull request, I would like to address the problem of unions by also providing serialization/deserialization (runtime checks).

### CODE REVIEW

**Comment by acote-coveo** [comment]
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

**Comment by acote-coveo** [comment]
If anyone can tell me if that's normal but the Java11 tests failed on `drone` and I can't see the results for circle ci

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by macjohnny** [comment]
@acote-coveo thanks for your contribution

**Comment by ffMathy** [comment]
This doesn't work for me. Has it regressed?

**Comment by macjohnny** [comment]
@ffMathy did you set the `withoutRuntimeChecks` option?

**Pull request merged**
