### PR TITLE
Remove bvwells from Go technical committee

### PR DESCRIPTION
**Pull request by bvwells**
Remove bvwells from Go technical committee. Sadly I don't get much time these days to contribute towards the project so thought it was best to remove myself. Want to say a big thanks for being such a welcoming project and to @wing328 for all your help!

### CODE REVIEW

**Comment by jimschubert** [comment]
@bvwells life can be like that sometimes, and additional pings could add time and stress. If things change, please do reach back out. Thanks!

**Comment by bvwells** [comment]
Thanks @jimschubert, will do!

**Comment by wing328** [comment]
@bvwells thanks for all your contributions. We wouldn't have gone this far without you. All the best to your future endeavors.

**Comment by bvwells** [comment]
Thanks @wing328! All the best for the future!

**Pull request merged**
