### PR TITLE
[csharp] Move nullable reference types switch to abstract

### PR DESCRIPTION
**Pull request by devhl-labs**
Moving the nullable reference types switch from aspnet generator to abstract so all csharp can use it.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mandrean @frankyjuang @shibayan @Blackclaws @wing328

### CODE REVIEW

**Comment by wing328** [comment]
@devhl-labs thanks for the PR as always.

Do we also need to update the mustache templates to actually use the option (the mustache tag)?

In other words, if we move the option to the C# abstract class, we need to make sure all C# generators that inherit the abstract generator properly support the option. Otherwise, we can only add the option to individual generators to start with.

**Comment by devhl-labs** [comment]
Yes, it would have to be handled by each set of template files. If we don't put it in the abstract, then we are removing the option for users to use their own custom templates to handle this option for generators that don't support it yet.

**Comment by Blackclaws** [comment]
I think that, technically, there is no need to actually change any part of the templates aside from the csproj files to use this. The reason is that with nullable reference types you simply change the post process function to treat every type as nullable and voila you get a nullable reference annotation for each type that is optional

**Comment by devhl-labs** [comment]
I can add it to the csproj files later today.

**Comment by wing328** [comment]
> I think that, technically, there is no need to actually change any part of the templates aside from the csproj files to use this.

Yes, that what I meant, e.g. https://github.com/OpenAPITools/openapi-generator/pull/9620/files#diff-b62dd64c4e02abc058c477127e8c9c85250c66b616d6683c9ee143470bcf2cd9R10

**Comment by devhl-labs** [comment]
Im tracking i just didnt get to it today.

**Comment by devhl-labs** [comment]
Aspnetcore was already handled.  Skipped dotnet-core2 because it's deprecated. Skipped nancyfx because the framework itself is deprecated as far as I can tell.  Added to csharp-netcore.

**Comment by wing328** [comment]
Can you please resolve the merge conflicts when you've time?

**Comment by devhl-labs** [comment]
Done

**Comment by devhl-labs** [comment]
I see drone had an unrelated error. Is that why app veyor failed?

**Comment by wing328** [comment]
AppVeyor tests passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/39524940

**Pull request merged**
