### PR TITLE
[Golang] generate embedded structs and set supportsInheritance to true

### PR DESCRIPTION
**Pull request by sebastien-rosset**
This PR addresses #4606: generate embedded Go structs to model the class inheritance hierarchy.

I am a new contributor to OpenAPITools, so before I continue with a full PR or abandon the work, can I get feedback to determine if leveraging the "supportsInheritance" attribute is the right thing to do for golang? If yes, should there be a flag to control whether or not the generated structs should be flat or use embedded structs? I know the PR is not complete, I just want to know if this is headed in the right direction.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by sebastien-rosset** [comment]
@antihax  @bvwells  @grokify  @kemokemo  @bkabrda

**Comment by sebastien-rosset** [comment]
If someone forgets to run the shell scripts under ./bin, are the CI jobs supposed to catch the problem and fail the tests? I am asking because this PR passed the tests, but subsequently I found out there are additional scripts under ./bin/openapi3, which presumably I have to run.
```
./bin/go-*
./bin/openapi3/go-*
```

**Comment by sebastien-rosset** [comment]
The generated go code does not compile for a reason that seems unrelated to my PR.
```
$ cd samples/openapi3/client/petstore/go-experimental/go-petstore
$ go build
./model_nullable_class.go:27:29: syntax error: unexpected [, expecting semicolon or newline or }
./model_nullable_class.go:234:56: syntax error: unexpected [ after top level declaration
./model_nullable_class.go:236:19: syntax error: unexpected [ after top level declaration
./model_nullable_class.go:244:50: syntax error: mixed named and unnamed function parameters
./model_nullable_class.go:246:19: syntax error: unexpected [ at end of statement
./model_nullable_class.go:249:2: syntax error: non-declaration statement outside function body
./model_nullable_class.go:262:56: syntax error: unexpected [, expecting comma or )
./model_nullable_class.go:267:64: syntax error: unexpected [ after top level declaration
./model_nullable_class.go:269:19: syntax error: unexpected [ after top level declaration
./model_nullable_class.go:277:58: syntax error: mixed named and unnamed function parameters

**Comment by antihax** [comment]
Catching up on this one. Go does not support inheritance so I am trying to understand what this is going to end up as?

**Comment by sebastien-rosset** [comment]
> Catching up on this one. Go does not support inheritance so I am trying to understand what this is going to end up as?

I'm going to run the scripts in the bin directory and commit to show the proposed diff. The properties of the "parent" are defined in a separate go struct, and the go structs are embedded.

OpenAPI allOf/anyOf/oneOf is not necessarily implemented with the traditional "inheritance" construct of a programming language. In the case of golang, I am suggesting to use embedded structs. The benefits are:
1) Avoid having large, flattened structs
2) Avoid repeating the same set of properties across many structs, especially when there is a complex OpenAPI model with both breadth and depth of the "allOf" hierarchy.

A related problem is that currently, it's not possible to have collections of heterogeneous classes (#4559). This particular PR is not address the heterogeneous collection problem.

**Comment by bkabrda** [comment]
@sebastien-rosset so what is the problem with having large flattened structures and repeating the same set of properties across many structs? To me, when the code is generated it doesn't matter too much when it's slightly larger.
I'm not against doing this change assuming you help me better understand the motivation behind it.

**Comment by sebastien-rosset** [comment]
> @sebastien-rosset so what is the problem with having large flattened structures and repeating the same set of properties across many structs? To me, when the code is generated it doesn't matter too much when it's slightly larger.
> I'm not against doing this change assuming you help me better understand the motivation behind it.

Sure, here are some considerations:

* Ability to use polymorphic type substitution, e.g. https://play.golang.org/p/hlFnRJAomJ0
For example, this makes it possible to iterate over a collection of heterogeneous elements, and more generally to execute algorithms that can leverage type substitution. 
* SDK Code is easier to read and understand. Properties are not repeated, sometimes hundreds of times with large OpenAPI specs.
* Smaller footprint in generated code. In our case, we have small embedded devices, where 10KB can make a difference. I've measured a 10% to 20% decrease in code size depending on the input OpenAPI spec.
* It's easier to track SDK changes when the model changes. If the generated SDK is committed to git and the model changes in the parent type, the number of files that change is smaller. For example, if one property is added to a parent type and there are 100 sub-types, that would cause one change versus 101 changes.

Potentially there could be a golang configuration parameter to specify whether or not to flatten. In general, inheritance and composition are useful constructs, but if you want to support both flat and inheritance, it shouldn't be too hard to make this configurable (although too much configurability is sometimes not so good).

**Comment by sebastien-rosset** [comment]
It looks like toInstantiationType(Schema property) must be overridden in src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java. The default implementation from the superclass does not work in the case that "additionalProperties" is set.

**Comment by sebastien-rosset** [comment]
Mistakenly deleted branch, re-opening as https://github.com/OpenAPITools/openapi-generator/pull/4934

**Comment by mariuspavelnistor** [comment]
Hi Sebastien. So let me understand , I run go-experimental-pestore.sh, but it seems this will not generate go-server models and it uses 'go-experimental' target. So it seems there is no way to generate go-server models now with embedded structures using this feature ?

**Comment by sebastien-rosset** [comment]
> Hi Sebastien,
> 
> I couldn't make it work when having multiple allOf . It seems it embeds only the first structure.
> 
> schemas:
> RangeBase:
> allOf:
> - $ref: 'common.yaml#/components/schemas/EnableBase'
> - $ref: 'common.yaml#/components/schemas/CommonRangeBase'
> - $ref: 'common.yaml#/components/schemas/DutRangeBase'

Yes, that is true, currently the go template only works with the first `allOf` reference. The code generator has support for `parent` and allParents. The template would have to be extended to support allParents.

The relevant codegen code is:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java#L36,L40

And the relevant go template is:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/model_simple.mustache#L3-L12

**Comment by sebastien-rosset** [comment]
Also, can you clarify if you are asking about the client side or server side? The PR I submitted was for the client side, not for the server side.

**Comment by mariuspavelnistor** [comment]
I use it for server side.

**Comment by sebastien-rosset** [comment]
> I use it for server side but the generated code is not different.

Then my recommendation is to take #4934 as a starting point and apply it to the go server generator. Is this something you could do?

**Comment by mariuspavelnistor** [comment]
I will give a try.  One more thing I don't understand is why did you use discriminator to decide  embedding the parent into child ?  The thing is we have external yamls and it's difficult to change them. Can I change the code to avoid using this field ? Is it difficult to do it ?

I did a trick like this to avoid that field but I still need to change the yaml 

    CommonRangeBase:
      type: object
      discriminator:
        propertyName: CommonRangeBase      
      properties:
        id:
          type: string
          x-id: true
          x-auto: "increment"
        count:
          type: integer
          x-auto: default(1)
      required: [id,count]

**Comment by sebastien-rosset** [comment]
> I will give a try. One more thing I don't understand is why did you use discriminator to decide embedding the parent into child ? The thing is we have external yamls and it's difficult to change them. Can I change the code to avoid using this field ? Is it difficult to do it ?
> 
> I did a trick like this to avoid that field but I still need to change the yaml
> 
> ```
> CommonRangeBase:
>   type: object
>   discriminator:
>     propertyName: CommonRangeBase      
>   properties:
>     id:
>       type: string
>       x-id: true
>       x-auto: "increment"
>     count:
>       type: integer
>       x-auto: default(1)
>   required: [id,count]
> ```

Support for embedded structs in go was one of my first PRs in openapi-generator, I wanted to minimize the changes. The OpenAPI specification has a section about inheritance, unfortunately it's not very precise and therefore it causes some controversy, which I didn't want to go into.
My recommendation is to add a go-specific CLI option that controls whether `allOf` $ref children are generated as a flat data structure or go embedded structs. This will mean people who want to keep the flat structure have control. The default would be "flat".

**Pull request closed without merging**
