### PR TITLE
[Java] Fix serialized name of discriminator in JSON.mustache

### PR DESCRIPTION
**Pull request by sebastien-rosset**
This PR has a fix for #4671. The JSON.mustache template should use "propertyBaseName" tag instead of "propertyName". The "propertyBaseName" tag is the name of the serialized property, whereas "propertyName" is the Java variable name.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by sebastien-rosset** [comment]
Question: should I augment the test OAS spec to include unusual discriminator property names, similar to https://gist.github.com/sebastien-rosset/f32f0abea11416bf82175577b48c251e#file-vehicles-yaml-L116?

**Comment by sebastien-rosset** [comment]
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608

**Comment by sebastien-rosset** [comment]
I'm not sure why the UT failed. That seems unrelated to my PR:
```
> open_api_petstore@1.0.0 test /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/javascript-es6
> mocha --require @babel/register --recursive
module.js:550
    throw err;
    ^
Error: Cannot find module './src/data'
    at Function.Module._resolveFilename (module.js:548:15)

**Comment by sebastien-rosset** [comment]
Also, independent of the PR, I see the following message in the UT logs:
```
found 33 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by wing328** [comment]
> Also, independent of the PR, I see the following message in the UT logs:

Good catch. Can you please open an issue to track it?

**Comment by wing328** [comment]
@sebastien-rosset thanks for the fix, which has been merged into master.

**Comment by sebastien-rosset** [comment]
> > Also, independent of the PR, I see the following message in the UT logs:
> 
> Good catch. Can you please open an issue to track it?

sure, will do

**Comment by sebastien-rosset** [comment]
> > Also, independent of the PR, I see the following message in the UT logs:
> 
> Good catch. Can you please open an issue to track it?

I have opened #4868. Unfortunately I can't find the location in the circleCI output where this message is printed. I am looking for a way to download all output in a single file.

**Pull request merged**
