### PR TITLE
[go-server][go-gin] Add auto-generated go.sum file

### PR DESCRIPTION
**Pull request by wing328**
- Add auto-generated go.sum file

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

**Comment by lwj5** [comment]
go.sum will be different for different router selected for go-server.

Is there any benefit of generating  be go.sum instead of getting the user to generate it using the go cmd?

**Comment by wing328** [comment]
My use case is related to docker which won't work without the go.sum file and docker users may not have go installed in their environment.

**Comment by wing328** [comment]
> go.sum will be different for different router selected for go-server.

We can handle that in the mustache template. I actually did try with different router but got the same go.sum so looks like I did something in my test locally.

**Comment by lwj5** [comment]
this is my go.sum, generated with chi router

```
github.com/go-chi/chi/v5 v5.0.3 h1:khYQBdPivkYG1s1TAzDQG1f6eX4kD2TItYVZexL5rS4=
github.com/go-chi/chi/v5 v5.0.3/go.mod h1:DslCQbL2OYiznFReuXYUmQ2hGd1aDpCnlMNITLSKoi8=
```

**Comment by wing328** [comment]
> Would generating the go.sum in docker be an acceptable idea? since it has the go runtime.

Ideally but `go mod tidy` only works with go 1.18.

Do you know the preferred way to generate go.sum with go 1.19?

Currently, to repeat the issue, just run `docker build samples/server/petstore/go-api-server` and you should get some errors.

**Pull request closed without merging**
