### PR TITLE
Add support for controlling output of OpenAPI Generator version in generated files

### PR DESCRIPTION
**Pull request by l3ender**
### Overview

This PR implements the feature request described in https://github.com/OpenAPITools/openapi-generator/issues/17681. It adds a global property/flag (`hideGeneratorVersion`) which is used to control whether the OpenAPI Generator version is outputted into generated files.

The default value for the new property is `true`, meaning the generator version detail will **not** be added to generated files. This seemed like the least impacting way to do make the change.

Therefore, the PR:
* Adds OpenAPI version to codegen types (if property is configured) which did not previously add this information to generated files.
* Any codegen types which previously added OpenAPI version to generated files now only show that information if the property is configured.

Resolves https://github.com/OpenAPITools/openapi-generator/issues/17681.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@l3ender thanks for the PR.  Please kindly put the work on hold for the time being as it's changing 1000+ files.

Can you please PM me to discuss this further vis Slack tomorrow (Tue) or Wed? https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

My timezone is +0800 (Hong Kong)

**Comment by l3ender** [comment]
Recapping the offline discussion with @wing328, the version will not be added behind an option. If users want to control the output differently, they can customize/override the default templates.

**Comment by wing328** [comment]
thanks for the PR, which has been merged.

I'll file another PR to make some minor improvements.

have a nice weekend

**Comment by wing328** [comment]
update: removed generator name option sample and config via f61b7c2aa43

**Comment by l3ender** [comment]
Thanks for all the help with this, @wing328!

If you find in the future the desire to revisit the approach of controlling generator version output with an option, please let me know! If it's not a big deal to have to regenerate all samples for each version upgrade, then no worries.

Thanks again!

**Comment by rearl** [comment]
Pity you didn't add the property/flag (`hideGeneratorVersion`) in the end. We would like to have this option as we check in our CI/CD pipeline which files have changed and only build modules with changed files and dependants. If the content of the generated files have not changed with a new version of the this plugin, there is no need to build this module (and dependants). Putting the generator version into the generated files causes unnecessary build.
Any chance you add the property/flag in a next version?

**Comment by wing328** [comment]
@rearl for your use case, I've filed https://github.com/OpenAPITools/openapi-generator/pull/18170 so that you can set `generatorVersion` to `Custom` or something else to avoid changes during version upgrade.

**Pull request merged**
