### PR TITLE
goserver - Allow to specify headers to add to the response

### PR DESCRIPTION
**Pull request by randomswdev**
This pull request is intended to provide the capability to specify headers to include in the response.

This is needed, for example, to allow a REST API to redirect the client to a new URL (using the Location header).

This pull request includes also the changes in the pull request https://github.com/OpenAPITools/openapi-generator/pull/8144

@antihax @grokify @kemokemo @bkabrda

### CODE REVIEW

**Comment by randomswdev** [comment]
@wing328 I rebased also this one that is a followon of PR https://github.com/OpenAPITools/openapi-generator/pull/8144

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by randomswdev** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
Thanks for let me know. I fixed the commits.

**Comment by wing328** [comment]
If I understand correctly, it's a breaking change. I'll merge it into a branch named go-server-response-headers to start with and add an option to selectively enable this enhancement so that we can merge it into master for next release 5.1.1 (no breaking changes allowed)

**Pull request merged**
