### PR TITLE
[Typescript] Fix generated type for files

### PR DESCRIPTION
**Pull request by HappyFeedFriends**
description problem in: https://github.com/OpenAPITools/openapi-generator/issues/12744

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR. Can you please follow step 3 in the PR checklist to update the samples?

cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

**Comment by HappyFeedFriends** [comment]
> Thanks for the PR. Can you please follow step 3 in the PR checklist to update the samples?
> 
> cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

yep, done

**Comment by HappyFeedFriends** [comment]
@wing328 hey

I hope my PR didn't get lost in the pile? =)

**Review by macjohnny — APPROVED** [review]
LGTM

**Pull request merged**
