### PR TITLE
[Kotlin][Client] Add new option to enable nullable required fields

### LINKED ISSUE #4651: [BUG][Kotlin] required yet nullable schema properties are not optional in generated models
##### Description
Some schemas have required but nullable properties in our open API specification. These are mapped to non-optional in the generated models.

##### openapi-generator version

4.2.0

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
Foo:
      type: object
      required: [name]
      nullable: false
      properties:
        name:
          type: string
          nullable: true
...
```
##### Related issues/PRs

Similar issue in Java: https://github.com/OpenAPITools/openapi-generator/issues/4530

##### Suggest a fix/enhancement

Not sure if I miss something else. I think the only thing missing is a question mark at the very end of
the template "data_class_req_var.mustache".
```mustache
...{{#isNullable}}?{{/isNullable}}
```

### PR DESCRIPTION
**Pull request by Mordag**
Fixes #4651.

- consumes the OpenApi 3.0 nullable field definition; if defined, even required fields will be nullable.
- required-nullable fields won't have a default value. The field is still required to exist - only it's value is null.
- added new kotlin-client sample to show the nullable-field changes
  - in the model "Pet" the field "name" is now nullable. In the yaml it is defined as a required nullable field.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10)

### CODE REVIEW

**Comment by Mordag** [comment]
I am not certain why the circleci is failing. Maybe someone can help me with that?

**Comment by wing328** [comment]
@Mordag thanks for the PR. I don't think we need another option "allowRequiredAsNullable" for nullable.

If the OpenAPI spec/doc has nullable defined, then the template should use nullable accordingly.

**Comment by Mordag** [comment]
@wing328 I removed the option but my git client messed up the git history for this PR. I will try to fix or will simply open new PR if I don't find a quick solution.

**Comment by Mordag** [comment]
@wing328 My git client is making some wired stuff. I will open a new PR for you to start fresh. Sorry about that.

**Pull request closed without merging**
