### PR TITLE
[PS] better code format, vendor extension naming

### PR DESCRIPTION
**Pull request by wing328**
- better code format
- vendor extension naming

cc @Ghufz 

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by ybelenko** [comment]
Unfortunately PHP `7.2.15` isn't enough for latest Symfony and Laravel. Both requires `^7.2.5`
https://packagist.org/packages/symfony/framework-bundle
https://packagist.org/packages/laravel/framework

**Comment by wing328** [comment]
Then 7.2.15 should meet the requirement (15 > 5), right?

**Comment by ybelenko** [comment]
You're right. I'm confused. Maybe it was different `dist` in my previous PRs, not `dist: xenial`. Xenial environment doesn't contain preinstalled PHP versions higher than 7.2, but it's not a big deal until 30 Nov 2020.

**Comment by wing328** [comment]
👌 let's deal with it later after the image installs with a newer version of php

**Pull request merged**
