### PR TITLE
[PHP] New client generator php-dt

### PR DESCRIPTION
**Pull request by Articus**
Added **php-dt** - new client generator for PHP language. Generated client is lightweight and extensible, relies on [Data Transfer](https://github.com/Articus/DataTransfer) for handling request/response content and complies with [PSR-7](https://www.php-fig.org/psr/psr-7), [PSR-11](https://www.php-fig.org/psr/psr-11), [PSR-17](https://www.php-fig.org/psr/psr-17) and [PSR-18](https://www.php-fig.org/psr/psr-18).

This PR also makes `php-mezzio-ph` description in README.md up-to-date - I hope that is ok to make this micro update together with  adding information about new generator.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon

### CODE REVIEW

**Comment by Articus** [comment]
I am at loss what to do with failing Maven plugin and Gradle plugin tests :[ PR does not touch them, error message from CI is a bit confusing and worst of all - build of poms for both plugins fails in my local development environment even if I take code from master. Could anyone please help to investigate these failed CI jobs?

**Comment by wing328** [comment]
Please ignore those maven, gradle plugin issues as that happens with the master branch as well.

**Comment by wing328** [comment]
@Articus thanks for the new generator. Looks good to me to include in the upcoming release to get feedback from our users.

**Comment by prochac** [comment]
@wing328 is there any new generator policy, or just more == better? Do we need a generator in upstream that's build on top of library with 7 stars?
https://github.com/Articus/DataTransfer
@Articus no hard feelings, I just think that this splits PHP ecosystem and makes confusion.

**Comment by Articus** [comment]
@prochac , it seems you missed the main part - compliance with [PSR-7](https://www.php-fig.org/psr/psr-7), [PSR-11](https://www.php-fig.org/psr/psr-11), [PSR-17](https://www.php-fig.org/psr/psr-17) and [PSR-18](https://www.php-fig.org/psr/psr-18). "No hard feelings", but if these PHP standards mean nothing to you, maybe count stars for corresponding repositories - https://github.com/php-fig/http-message , https://github.com/php-fig/container , https://github.com/php-fig/http-factory , https://github.com/php-fig/http-client ?

**Pull request merged**
