### PR TITLE
[dart] cleanup documentation

### PR DESCRIPTION
**Pull request by tiffmaelite**
* fix hierarchy level
* align wording across generators

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

### CODE REVIEW

**Review by kuhnroyal — COMMENTED** [review]
I don't think we need the anchor tags. Github adds these automatically.

**Comment by tiffmaelite** [comment]
> I don't think we need the anchor tags. Github adds these automatically.

The generated code does not have to be hosted on GitHub.

So, given that it is not part of the markdown standard, it is possible that the section headings are rendered without an auto-generated unique id by some code hosting platforms, and as a result that these headings cannot be accessed via anchor links in a predictable way which would needed to generate documentation with links to these sections of the README.

Moreover, even if it seems that at least [GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#section-links), [GitLab](https://docs.gitlab.com/ee/user/markdown.html#header-ids-and-links), [Visual Studio Code Server](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops&viewFallbackFrom=vsts#anchor-links), SourceForge and BitBucket do include an auto-generated id for section headings, they are not guaranteed to all generate the same ID for a given header title. I could not find documentation about how these IDs are generated for all of them.

However, the rest of the documentation produced by the dart generators do not contain any explicit anchor elements.
So I'll remove the anchor elements I added despite the fact that https://github.com/OpenAPITools/openapi-generator/blob/961980f284362077042fb89f6afe41d7b866e5af/modules/openapi-generator/src/main/resources/dart2/api_doc.mustache#L86 and https://github.com/OpenAPITools/openapi-generator/blob/961980f284362077042fb89f6afe41d7b866e5af/modules/openapi-generator/src/main/resources/dart/libraries/dio/api_doc.mustache#L76 contain anchor links to the specific authorization sections.

**Comment by kuhnroyal** [comment]
Yea I just looked at 2 random other generators and didn't see any manual tags, my comment was meant more as a question :) Thanks!

**Review by kuhnroyal — APPROVED** [review]

**Comment by tiffmaelite** [comment]
> Yea I just looked at 2 random other generators and didn't see any manual tags, my comment was meant more as a question :) Thanks!

Initially I had done a big change in all generators and then decided to split it up into multiple PRs (one per language) when I saw the amount of affected files, so that's where the thing came from.
You were correct in suggesting that just adding these few links in the overall doc as part of this PR do not make sense.

Thanks to your comment, I reviewed my other PRs to other generators as well, and simplified some of them by keeping only the wording harmonization and hierarchy level fix where needed ;)

I guess that if someone has problems with links in the generated doc an issue will be raised, and it will be the right time to add anchor links in a bunch of places.

**Review by agilob — APPROVED** [review]

**Review by ahmednfwela — APPROVED** [review]

**Pull request merged**
