### PR TITLE
Elixir: fix broken connection token authorization middleware

### PR DESCRIPTION
**Pull request by tobbbles**
Correctly types the arguments for the Tesla.Middleware.Headers module on the token authorization. As you can see in [the example here](https://hexdocs.pm/tesla/Tesla.html#client/2) the Headers middleware options are a list of key-value pairs. 

This looks to be a regression introduced in https://github.com/OpenAPITools/openapi-generator/pull/12775 as a typo, as the stringdoc shows the correct structure.

Relevant issue https://github.com/ory/sdk/issues/285

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (7.0.1 - patch release), `7.1.x` (minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mrmstn

### CODE REVIEW

**Comment by tobbbles** [comment]
I'm not sure why 5 new models are generated with `5.2.1-SNAPSHOT`, i did a clean install and regenerated through the scripts.

**Comment by wing328** [comment]
Did you make the change based on the latest master (7.0.1-SNAPSHOT)?

**Comment by wing328** [comment]
Also cc [@halostatue](https://github.com/halostatue)

**Comment by tobbbles** [comment]
> Did you make the change based on the latest master (7.0.1-SNAPSHOT)?

Fixed now, there was some obscurity in my local build environment

**Comment by mrmstn** [comment]
LGTM, Thanks for noticing and providing the fix right away 😀!

**Pull request merged**
