### PR TITLE
feat(adapter): add BigDecimal kotlin support

### PR DESCRIPTION
**Pull request by codymikol**
this allows the kotlin client generator to support
BigDecimal values

This was originally created by @kuFEAR in their own branch, but a PR wasn't made into this project. 
I hope you don't mind me making the PR for you, I happen to need this for my own project.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:

  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. - [x] 

Kotlin

@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

### CODE REVIEW

**Comment by 4brunu** [comment]
Hey, thanks for your contribution 👍 
One question, does OpenAPI generates the types `BigDecimal` and `BigInteger`?
Thanks

**Comment by kuFEAR** [comment]
it works if you add `typeMappings.set(mapOf("double" to "BigDecimal"))` in configuration

**Comment by 4brunu** [comment]
If I'm understanding what you are saying, it's possible to change the `typeMappings`?
I didn't knew this feature.

But by default it doesn't generate `BigDecimal` from what I understood.

If by default the generator doesn't generate `BigDecimal`, I'm not sure if this makes sense to add this adapters to the default configuration.
Because if you use a custom types, you can add custom adapters via `Serializer.moshiBuilder.add(...)`

Also this PR adds the `BigDecimal` and `BigInteger` adapters, but it doesn't add them to `Serializer.moshiBuilder`.

I'm not sure whats the right move here, let's here the other technical committee members.

**Comment by codymikol** [comment]
> If I'm understanding what you are saying, it's possible to change the `typeMappings`?
> I didn't knew this feature.
> 
> But by default it doesn't generate `BigDecimal` from what I understood.
> 
> If by default the generator doesn't generate `BigDecimal`, I'm not sure if this makes sense to add this adapters to the default configuration.
> Because if you use a custom types, you can add custom adapters via `Serializer.moshiBuilder.add(...)`
> 
> Also this PR adds the `BigDecimal` and `BigInteger` adapters, but it doesn't add them to `Serializer.moshiBuilder`.
> 
> I'm not sure whats the right move here, let's here the other technical committee members.

That was actually supposed to be in there, I let it slip through after rebasing, just pushed it in now. Thanks for catching that!

**Comment by wing328** [comment]
@codymikol can you please resolve the merge conflicts when you've time?

**Comment by codymikol** [comment]
> @codymikol can you please resolve the merge conflicts when you've time?

I'll take a look tomorrow

**Comment by codymikol** [comment]
@wing328 sorry for the delay

**Comment by wing328** [comment]
Updated the samples via https://github.com/OpenAPITools/openapi-generator/pull/8880/commits/093d63ba95f76fa754647a709da891f1fa2120da. Let's see if all the tests pass.

**Comment by codymikol** [comment]
Thanks wing 👍

**Comment by Djaler** [comment]
Hi! Is there a reason why you serialize BigDecimal as strings?
Because when spec contains `"type": "number"`, I expect to see a number in JSON, not a string containing number.
Same thing is defined in documentation: https://swagger.io/docs/specification/v3_0/data-models/data-types/#numbers `Note that strings containing numbers, such as “17”, are considered strings and not numbers.`

**Pull request merged**
