### PR TITLE
[kotlin][client] add support for coroutines with OkHttp

### PR DESCRIPTION
**Pull request by 4brunu**
This PR adds support for coroutines with OkHttp http client.

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

### CODE REVIEW

**Comment by wing328** [comment]
I did some tests locally and found the following errors:
```
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :compileKotlin
e: /Users/williamcheng/Code/openapi-generator/samples/openapi3/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/apis/FakeApi.kt: (504, 183): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Array<String>?
e: /Users/williamcheng/Code/openapi-generator/samples/openapi3/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/apis/FakeApi.kt: (504, 209): Unresolved reference: collectionDelimiter
e: /Users/williamcheng/Code/openapi-generator/samples/openapi3/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (136, 21): Type inference failed: Cannot infer type parameter V in inline operator fun <K, V> MutableMap<K, V>.set(key: K, value: V): Unit
None of the following substitutions
receiver: MutableMap<String, List<String>>  arguments: (String,List<String>)
receiver: MutableMap<String, String>  arguments: (String,String)
can be applied to
receiver: MutableMap<String, List<String>>  arguments: (String,String)

e: /Users/williamcheng/Code/openapi-generator/samples/openapi3/client/petstore/kotlin-jvm-okhttp4-coroutines/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (138, 21): Type inference failed: Cannot infer type parameter V in inline operator fun <K, V> MutableMap<K, V>.set(key: K, value: V): Unit
None of the following substitutions
receiver: MutableMap<String, List<String>>  arguments: (String,List<String>)
receiver: MutableMap<String, String>  arguments: (String,String)
can be applied to
receiver: MutableMap<String, List<String>>  arguments: (String,String)
```

Does it work for you locally in your machine?

**Comment by 4brunu** [comment]
You are right, thanks for pointing this!
I submitted a commit and now it's working.
One thing that we could improve in the kotlin generator is to let the CI build the kotlin samples in each PR, like the Swift samples do at the moment. 
What do you think on this?

**Comment by wing328** [comment]
> One thing that we could improve in the kotlin generator is to let the CI build the kotlin samples in each PR, like the Swift samples do at the moment.

I prefer to consolidate samples if possible.

Swift also has too many test spec that can be consolidated into 1 or 2. I'll PM later on this.

**Comment by 4brunu** [comment]
Ok 👍 
Could we address those issues in different PRs, to unlock this one?

**Comment by wing328** [comment]
Yes, let's do that in a separate PR.

Let me test this again and merge if no issue found.

**Pull request merged**
