### PR TITLE
[TS] replace line comment with block comment

### LINKED ISSUE #4539: [REQ] //eslint-disable should be /* eslint-disable */
When using the generated typescript-fetch client i allways get warnings in my console telling 
me I have unused vars in my generated clients. Therefore i had a look and it is true. There are unused vars. But there is also a //eslint-disable comment at the top of the file. The Problem is that eslint requrires a different format for disables. 

I tested it by just replacing //eslint-disable with /* eslint-disable */ and voilà the warning is gone.

I would recommend to change //eslint-disable into /* eslint-disable */

### PR DESCRIPTION
**Pull request by sreichi**
eslint requires you to use a block comment for ignoring whole files

this pull request fixes #4539 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@TiFu  @taxpon  @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce  @akehir

### CODE REVIEW

**Comment by sreichi** [comment]
I encountered some problems when generating the new samples. When running the scripts in ./bin and ./bin/openapi3 the generated code not only different when comparing the comments. Could maybe someone tell me what i did wrong?

**Comment by macjohnny** [comment]
dont use the `openapi3` scripts

**Comment by macjohnny** [comment]
thanks for your PR

**Comment by macjohnny** [comment]
please run https://github.com/OpenAPITools/openapi-generator/blob/master/bin/typescript-fetch-petstore-all.sh and commit the changed samples

**Comment by sreichi** [comment]
@macjohnny thanks a lot for your help!

**Comment by wing328** [comment]
@sreichi thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Pull request merged**
