### PR TITLE
Re-implementation of Apex client code gen

### PR DESCRIPTION
**Pull request by muenzpraeger**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Re-implementation of Apex client library, finalized TODOs from PR #692 

@wing328

### CODE REVIEW

**Comment by wing328** [comment]
@muenzpraeger the change looks good to me (but I'm no expert in Apex)

**Comment by wing328** [comment]
@muenzpraeger can you please share with me how to perform a compile test for the [Apex Petstore client](https://github.com/OpenAPITools/openapi-generator/tree/d8ec6b2003fff89b0cc30d8dfd6baaff059daabd/samples/client/petstore/apex)?

We can then set that up in the CI to ensure the client compiles after changes to Apex generator or templates.

**Comment by muenzpraeger** [comment]
The compile would need an active Salesforce environment, as the compile happens in cloud, not locally.

**Comment by muenzpraeger** [comment]
The source would need to be pushed to an ephemeral environment, like in this config:

https://github.com/trailheadapps/easy-spaces/blob/b74d3dbaa7b2e3ff59af46185fd3c81a8df90b32/.circleci/config.yml#L73

**Comment by wing328** [comment]
For the CI setup, let's work on that later.

If no further question/feedback, I'll merge this into master in an hour or so.

**Pull request merged**
