### PR TITLE
[Dart] Make dependency on intl package less strict

### PR DESCRIPTION
**Pull request by wiesnery**
The hard reuirement of `intl: '^0.18.0'` limits current and future update behavior.
It is recommended by the flutter team to depend on `intl: any` instead.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

### CODE REVIEW

**Review by ahmednfwela — APPROVED** [review]

**Review by ahmednfwela — APPROVED** [review]

**Review by sbu-WBT — APPROVED** [review]

**Comment by wiesnery** [comment]
@ahmednfwela @sbu-WBT Thanks for the quick review cycle! Can you also merge the PR?

**Comment by ahmednfwela** [comment]
@wing328

**Comment by aviadkam** [comment]
@wiesnery 
What do you say about doing the same for http package? I am having trouble with other packages that require a higher minimal version of http package.

**Comment by wiesnery** [comment]
@aviadkam 
current version of http is: [1.2.1](https://pub.dev/packages/http) why are we that far behind?
Starting with version 1.0.0 dart 3 is required - not sure if this would be too much of a breaking change.

As there don't seem to be any documented API changes we could go from `'>=0.13.0 <0.14.0'` to: `>=0.13.0 <2.0.0`
If we do that we should proceed with the collections package as well from `'^1.17.0' to `'>=1.17.0 <2.0.0` as this dependency blocks upgrading often. -> Maybe we could event eliminate the dependency as these are only convenience functions, right?
What do you think?
Maybe we should open up a new issue for each of them.

**Comment by aviadkam** [comment]
For `http` `>=0.13.0 <2.0.0` is a good idea
for `collection`, I think we can also do `>=1.17. <2.0.0`. It will take time to make it to `2.0.0`. The functionality is fundamental, and I hope it will not break.

Another thought - If `intl` is `any`, maybe we can put all as `any`? Or just restrict the minimal version?
The generator must be as open as possible because it builds the SDK.

**Comment by wiesnery** [comment]
As far as I understood the `intl` dependency, it is required to have it because of some provider it brings but there is no real API access. This however is different to `http` and `collection` so I would not go for `any` in this case. Open ok but we don't have any compile-time check if the project really works with other dependency versions. So I would recommend using the above specified dependency range.
Do you want to file the PR? @aviadkam?

**Comment by wiesnery** [comment]
you can finde the PR for http, collection and meta here https://github.com/OpenAPITools/openapi-generator/pull/18952

**Comment by aviadkam** [comment]
> you can finde the PR for http, collection and meta here #18952

Thank you very very much!!

**Pull request merged**
