### PR TITLE
[Android][Volley] Build fixes

### PR DESCRIPTION
**Pull request by valpackett**
These changes were required to make generated Volley code build with current Android SDK.

@jaz-ah

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

can you please run the following to update the samples?

```
 ./bin/generate-samples.sh ./bin/configs/unmaintained/android-*
```

(you may need to run it twice if there are new files)

**Comment by valpackett** [comment]
Done

**Comment by wing328** [comment]
looks good.

if you run gradle build under `samples/client/petstore/android/volley/` and `samples/client/petstore/android/httpclient/`, do the build pass without issue?

**Comment by valpackett** [comment]
Well.. it didn't without modifications as there was the `compileSdkVersion is not specified` nonsense caused by the `android-maven-gradle-plugin` not being compatible with the new… version of Gradle itself I assume? and that option was enabled in the samples. That plugin was [abandoned](https://github.com/dcendents/android-maven-gradle-plugin) because the functionality is now part of the standard Android plugin itself.

I was a bit afraid to break backwards compatibility or whatever but since we're in `unmaintained/` territory apparently anyway (…as if the outdated versions of everything weren't a hint, heh) I went ahead and updated all the Gradle stuff, replacing that plugin and the manual source jar task with the current standard way of configuring publishing. Now the samples just build out of the box with current Android Studio.

**Comment by wing328** [comment]
>That plugin was [abandoned](https://github.com/dcendents/android-maven-gradle-plugin) because the functionality is now part of the standard Android plugin itself.

thanks for the PR, which has been merged.

would appreciate if you can file another PR to remove it as it's been abandoned.

**Comment by valpackett** [comment]
> would appreciate if you can file another PR to remove it as it's been abandoned.

That's what was already included in the latest revision! :)

> replacing that plugin and the manual source jar task with the current standard way of configuring publishing

https://github.com/OpenAPITools/openapi-generator/blob/989a79811a5cae2b10e07e6c4d5261af3da1e39d/modules/openapi-generator/src/main/resources/android/libraries/volley/build.mustache#L80-L92

**Comment by wing328** [comment]
I see 👍

**Comment by wing328** [comment]
when you've time, can you please PM me via Slack?

**Comment by wing328** [comment]
btw, it would be nice to have Github workflow to test the Android petstore clients similar to https://github.com/OpenAPITools/openapi-generator/blob/master/.github/workflows/samples-java-client-jdk11.yaml for Java Petstore clients.

**Comment by valpackett** [comment]
yeah. Sorry, I'm not really personally interested in picking this up, just fixing all the issues a company that hired me has encountered with their generated client libraries..

**Comment by wing328** [comment]
no need to sorry

let's say if someone else have time to contribute the workflow

thanks again for the PR

**Pull request merged**
