### PR TITLE
[dart] Improve content-type handling

### LINKED ISSUE #9334: [BUG][dart-dio-next] Generator uses url encoded contentType even if the server content type requires application/json
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm using Asp.Net Core Swashbuckle to generate openapi scheme for my backend. The backend supports multiple content-type variants of `application/json`. But generated code uses url encoded content type instead of application/json.

Here's generated code output which picks first match which is "application/json-patch+json". 

```dart
contentType: [
  'application/json-patch+json',
  'application/json',
  'text/json',
  'application/_*+json',
].first
```

But then Did checks if content-type is `application/json` then uses json encoding but if it isn't, it uses url encoding and my server returns **HTTP 415 Unsupported Media Type** status.

##### openapi-generator version

**5.1.0**

##### OpenAPI declaration file content or url

The OpenAPI declaration that caused this issue was used for private api. So I couldn't share it here.

##### Suggest a fix

1. Overriding content-type header using command line options provided to generator CLI
2. Updating `contentType` matching part to choose most suitable match rather than first one

### PR DESCRIPTION
**Pull request by kuhnroyal**
* fixes #9334
* superseeds #9454
* use `prioritizedContentTypes` in the same way `JavaClientCodegen` does
* move `application/json` to the front if it exists
* don't do anything if it is multi-part or url-encoded as for this the first content-type already needs to match
* log warning if an unsupported content-type is first after prioritizing
* remove some unused code blocks from dio generators

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

CC @swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@TheMisir Do you mind testing this for your use-case?

**Comment by TheMisir** [comment]
> @TheMisir Do you mind testing this for your use-case?

Do I have a chance to test this without having to clone & re-building the project?

**Comment by kuhnroyal** [comment]
> > @TheMisir Do you mind testing this for your use-case?
> 
> Do I have a chance to test this without having to clone & re-building the project?

I don't think so, can't find the artifacts anywhere.

**Comment by TheMisir** [comment]
> @TheMisir Do you mind testing this for your use-case?

Yes it works. But why don't you directly generating code as `contentType: 'value'` instead of `contentType: ['value'].first`?

**Comment by kuhnroyal** [comment]
> > @TheMisir Do you mind testing this for your use-case?
> 
> Yes it works.
> 
> But why don't you directly generating code as `contentType: 'value'` instead of `contentType: ['value'].first`? If in the end, only the first value will be used on runtime, so what's the point of writing like `[...].first`? Maybe I'm missing something.

I am not sure this is possible in the template but I will check. In any case, they are now correctly ordered in a way that works.

**Comment by TheMisir** [comment]
> I am not sure this is possible in the template but I will check

In my implementation, I introduced a vendorExtensions called `x-content-type` for that purpose.

But yeah, they are correctly ordered now.

**Comment by kuhnroyal** [comment]
@TheMisir I changed this to use only the first content-type.

**Review by josh-burton — APPROVED** [review]

**Pull request merged**
