### PR TITLE
[Java][Jersey2] revert configurable javax package for javax.net

### PR DESCRIPTION
**Pull request by borsch**
Small fix to address this comment https://github.com/OpenAPITools/openapi-generator/pull/14310#discussion_r1059522238

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Review by welshm — APPROVED** [review]

**Review by parenko — APPROVED** [review]
Yes, this three imports exist outside of Jakarta EE.

**Comment by cemo** [comment]
Is there an expected release soon? I have checked milestones but it seems it is already passed.

**Comment by wing328** [comment]
we've some more PRs that we would like to include in the upcoming v6.3.0 release

we should be able to cut a release by the end of this month.

**Comment by fostiguy** [comment]
@wing328 Do we know when is the release 6.3.0 gonna be ready ?

**Pull request merged**
