### PR TITLE
[C][Client] Always send integer or boolean query parameters to the API server 

### PR DESCRIPTION
**Pull request by ityuhui**
@wing328 @zhemant @michelealbano

When the query parameters in a API request is type of "integer" or "boolean",  if its value is `0` or `false`, the current code does not send the query parameter to the API server. 

e.g.
```c
    if (gracePeriodSeconds)    <--- if gracePeriodSeconds == 0, the below code will be ignored.
    {
        keyQuery_gracePeriodSeconds = strdup("gracePeriodSeconds");
        valueQuery_gracePeriodSeconds = calloc(1,MAX_NUMBER_LENGTH);
        snprintf(valueQuery_gracePeriodSeconds, MAX_NUMBER_LENGTH, "%d", gracePeriodSeconds);
        keyPairQuery_gracePeriodSeconds = keyValuePair_create(keyQuery_gracePeriodSeconds, valueQuery_gracePeriodSeconds);
        list_addElement(localVarQueryParameters,keyPairQuery_gracePeriodSeconds);
    }
```

This PR changes the code to:

```c
    if (1) // Always send integer parameters to the API server 
    {
        keyQuery_gracePeriodSeconds = strdup("gracePeriodSeconds");
        valueQuery_gracePeriodSeconds = calloc(1,MAX_NUMBER_LENGTH);
        snprintf(valueQuery_gracePeriodSeconds, MAX_NUMBER_LENGTH, "%d", gracePeriodSeconds);
        keyPairQuery_gracePeriodSeconds = keyValuePair_create(keyQuery_gracePeriodSeconds, valueQuery_gracePeriodSeconds);
        list_addElement(localVarQueryParameters,keyPairQuery_gracePeriodSeconds);
    }
```

This issue comes from https://github.com/kubernetes-client/c/issues/158

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@ityuhui thanks for the PR.

What about creating another spec (e.g. modules/openapi-generator/src/test/resources/2_0/c/petstore.yaml) and add some fake endpoints with integer, boolean query parameters to ensure the output compiles without issue?

**Comment by ityuhui** [comment]
Sure. I'll do it.

**Comment by ityuhui** [comment]
Build the sample successfully.

```bash
~/openapi-generator/samples/client/petstore/c/build# make
Scanning dependencies of target openapi_petstore
[  6%] Building C object CMakeFiles/openapi_petstore.dir/src/list.c.o
[ 13%] Building C object CMakeFiles/openapi_petstore.dir/src/apiKey.c.o
[ 20%] Building C object CMakeFiles/openapi_petstore.dir/src/apiClient.c.o
[ 26%] Building C object CMakeFiles/openapi_petstore.dir/external/cJSON.c.o
[ 33%] Building C object CMakeFiles/openapi_petstore.dir/model/object.c.o
[ 40%] Building C object CMakeFiles/openapi_petstore.dir/model/api_response.c.o
[ 46%] Building C object CMakeFiles/openapi_petstore.dir/model/category.c.o
[ 53%] Building C object CMakeFiles/openapi_petstore.dir/model/order.c.o
[ 60%] Building C object CMakeFiles/openapi_petstore.dir/model/pet.c.o
[ 66%] Building C object CMakeFiles/openapi_petstore.dir/model/tag.c.o
[ 73%] Building C object CMakeFiles/openapi_petstore.dir/model/user.c.o
[ 80%] Building C object CMakeFiles/openapi_petstore.dir/api/PetAPI.c.o
[ 86%] Building C object CMakeFiles/openapi_petstore.dir/api/StoreAPI.c.o
[ 93%] Building C object CMakeFiles/openapi_petstore.dir/api/UserAPI.c.o
[100%] Linking C shared library libopenapi_petstore.so
[100%] Built target openapi_petstore
```

**Comment by wing328** [comment]
LGTM. 

CircleCI failure not related to this change.

**Pull request merged**
