### PR TITLE
Add jersey2-experimental to Java client generator

### PR DESCRIPTION
**Pull request by wing328**
- different implementations of oneOf
- other minor improvements
- use `x-one-of-name` instead of `x-oneOf-name`
- support primitive types (e.g string) in oneOf/anyOf

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
This change adds support for primitive types in oneOf/anyOf schemas but it's breaking the python-experimental tests.

Can someone please help take a look at the error log to see if that's expected?

https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/678539087

cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @slash-arun (2019/11) @spacether (2019/11)

**Comment by spacether** [comment]
@wing328 this change breaks python-experimental because python-experimental overrides fromModel. My suggestion on how to fix this is to break apart the code inside fromModel into separate pieces, call the correct pieces at both locations.
If you need any help understanding the python-experimental code please let me know.
The python-experimental code is shaped like this because we store validations and enums on primitive models. The python-experimental code was put in place before codegenModel was capable of storing this information.

If python experimental sees a primitive model, it converts it to an object model with one value with the type of the primitive model. Another solution would be to rework python-experimental to stop doing this CodegenModel transformation  if CodegenModel is now able to store enums and validations assuming type = string/int/float/dict/array etc. But that is a more difficult bigger change.

**Comment by wing328** [comment]
Fixed the issue by not adding primitive types to allOf (which should compose of schemas/models only)

**Comment by wing328** [comment]
All tests passed

**Pull request merged**
