### PR TITLE
fix: [typescript-angular] incorrect import when model starts with number

### LINKED ISSUE #13201: [BUG][typescript-angular] Incorrect import or filename when model starts with a number
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
  - Issue is still present in master https://github.com/snebjorn/openapi-gen-bug/tree/master/output-master/import-bug
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When a model have an invalid starting character it'll be prefixed with `Model`. However this prefixing isn't consistent everywhere.

For example this schema:
```json
"schemas": {
  "foo": {
    "type": "object",
    "properties": {
      "first": {
        "anyOf": [{ "type": "number" }, { "type": "string" }],
        "title": "1st"
      }
    }
  }
}
```
Generates this model:
```ts
// filename: 1st.ts
export interface Model1st { 
}
```
But it'll be imported like so:
```ts
import { Model1st } from './model1st';
```

**NOTE:** The filenames doesn't match.

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/snebjorn/openapi-gen-bug/master/import-bug.json
```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "",
    "version": ""
  },
  "paths": {
    "/Foos": {
      "get": {
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/foo"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "foo": {
        "type": "object",
        "properties": {
          "first": {
            "anyOf": [{ "type": "number" }, { "type": "string" }],
            "title": "1st"
          }
        }
      }
    }
  }
}
```

##### Generation Details

```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i https://raw.githubusercontent.com/snebjorn/openapi-gen-bug/master/import-bug.json \
   -g typescript-angular \
   -o output-master/import-bug
```

##### Steps to reproduce

1. Clone https://github.com/snebjorn/openapi-gen-bug
2. Run `yarn install`
3. Run `yarn gen`
4. Observe import error in https://github.com/snebjorn/openapi-gen-bug/blob/ad3851d72b3a9bfe8bc49604730d013e03813b73/output-6.0.1/import-bug/model/foo.ts#L12

##### Related issues/PRs

None found.

##### Suggest a fix

Either the filename should also have the prefix or the import statement shouldn't use the prefix.
Care should be taken as the filename format can be changed via the `fileNaming` parameter.

https://openapi-generator.tech/docs/generators/typescript-angular/

fileNaming | Naming convention for the output files: 'camelCase', 'kebab-case'.
-- | --

### PR DESCRIPTION
**Pull request by snebjorn**
Fixes #13201 see bug report for details about the issue

To validate the work run the OpenApi spec provided in the bug report.
Then check that `/output-folder/model/foo.ts` have the correctly path to import the `Model1st` interface. It should be `from './model1st';`

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

### CODE REVIEW

**Comment by snebjorn** [comment]
I ran these with Git BASH (I'm on windows)
```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```
But it turned all `/` into `\` and other issues. Seems there's an issue with the scripts on windows.

**Comment by marinus-suniram** [comment]
I think this is breaking imports if you specify a modelNameSuffix. It adds the suffix to the package.

Before 
`import { AuthorizationTokenDTO } from '../model/authorization-token';`

After 
`import { AuthorizationTokenDTO } from '../model/authorization-token-dto';`

**Comment by macjohnny** [comment]
@snebjorn can you take a look at this?

**Comment by snebjorn** [comment]
@marinus-suniram modelNameSuffix is not a valid argument to the typescript-angular generator.
See https://openapi-generator.tech/docs/generators/typescript-angular/

**Comment by marinus-suniram** [comment]
@snebjorn The issue is also on **modelSuffix**

The issue is that import file path now also contains the suffix. The class name **AuthorizationTokenDTO** is correct but the path **../model/authorization-token-dto**  is incorrect. The path should not contain the modelSuffix **-dto**.

**Pull request merged**
