### PR TITLE
[cpp-qt-client] Fix and refactor CMakeLists.txt  

### LINKED ISSUE #11371: [BUG] CMakeLists.txt gernerated by  cpp-qt-client is missing Qt5:.Gui dependency / linking
#### Bug Report Checklist
tried with Qt5.14, Qt5.15, with gcc7 under Linux / ubunut 20.04

- [ ] What's the actual output vs expected output?
CMake should build, but fails with QDesktopServices.h can not be found. This header depens on Qt5:Gui which is not listed/linked in the autogernated CMakeLists.txt 

##### openapi-generator version
5.3.1

##### Suggest a fix
add
find_package(Qt5 COMPONENTS Gui REQUIRED)
and Qt5::Gui  under target_link_libraries in the generated CMakeLists.txt

### PR DESCRIPTION
**Pull request by Thaulino**
This is my first pull request here - sorry if something does not fit to the rules 

### Description

Changed: Always add Qt5::Gui to build, needed because {{prefix}}Oauth.h is always part of the build
Added: find_package for OpenSSL, should be done prior target_link_libraries

### Tests that have been done :
(ubuntu) 
install deps (reference #11371 ): 
sudo apt install -y --no-install-recommends qt5-default 
run code generator:
java -jar openapi-generator-cli-5.4.0.jar generate -t cpp-qt-templates -i petstore.json -g cpp-qt-client -o petstore
run cmake:
cmake -S petstore -B petstore/build

(windows)
run code generator:
java -jar openapi-generator-cli-5.4.0.jar generate -t cpp-qt-templates -i petstore.json -g cpp-qt-client -o petstore
run cmake:
cmake -S petstore -B petstore/build
 
### Issue
fixes #11371 

### technical commitee
@muttleyxd
@etherealjoy
@wing328 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by Thaulino** [comment]
Sorry i somehow reverted unintentionally the commit. 
Now i reverted the revert -.-
maybe it is possible to cherrypick the first commit

**Comment by wing328** [comment]
> maybe it is possible to cherrypick the first commit

@Thaulino thanks for the PR. Feel free to submit a new PR by cherry-picking the first commit. Let me know if you need any help.

**Comment by wing328** [comment]
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

**Comment by Thaulino** [comment]
@wing328  i created a new pr (#11967)

**Pull request closed without merging**
