### PR TITLE
[Csharp] Bugfix: Updated all C# templates ToJson method not to conflict reference withmodel properties

### PR DESCRIPTION
**Pull request by Havunen**
This PR fixes an issue where model contains property called "Formatting" or "JsonConvert" build fails to conflicting reference.
I tested opening generated sample projects in Visual Studio 2019 and compiled them.

The error being fixed:
```
Error CS1061	'Model' does not contain a definition for 'Indented' and no accessible extension method 'Indented' accepting a first argument of type 'Model' could be found (are you missing a using directive or an assembly reference?)

```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by Havunen** [comment]
@mandrean @frankyjuang @shibayan Please review, it seems I cannot assign for review, option is grayed out in Github

**Comment by Havunen** [comment]
I dont understand how this circle ci failure is related to my change. 

[ERROR] Plugin org.springframework.boot:spring-boot-maven-plugin:2.2.9.RELEASE or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.springframework.boot:spring-boot-maven-plugin:jar:2.2.9.RELEASE: Could not transfer artifact org.springframework.boot:spring-boot-maven-plugin:pom:2.2.9.RELEASE from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]

@wing328

**Comment by wing328** [comment]
Pushed https://github.com/OpenAPITools/openapi-generator/pull/8087/commits/816be3763dae2c1b2deeb16d063fbffa57cbe5ff to update the samples.

**Review by wing328 — APPROVED** [review]
LGTM

**Pull request merged**
