### PR TITLE
[csharp] massively improve csharp templates code

### PR DESCRIPTION
**Pull request by filipe-silva**
Improved apiclient.mus to keep it dry, sharing a single exec with Action<> delegate. 
Improved api.mus to keep it dry, used chain constructors, kept RequestOptions in a single method, set configuration POCO with alias directive and moved fqn types to using directive for cleaner code.
Removed 'this' from variables/props that are redundant.
Fixed incompatible framework, System.Web, used on .NET 6.0 and above.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mandrean @shibayan @Blackclaws @lucamazzanti @iBicha

### CODE REVIEW

**Comment by filipe-silva** [comment]
Added issue #16989 according to contributing readme.

**Comment by wing328** [comment]
thanks for the PR.

can you please update the tests (java unit tests) as well?

```
[ERROR] Failures: 
[ERROR]   CSharpClientDeepObjectTest.deepObject:70 expected:<2> but was:<1>
[ERROR] Tests run: 1997, Failures: 1, Errors: 0, Skipped: 0
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project openapi-generator: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/circleci/OpenAPITools/openapi-generator/modules/openapi-generator/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
```

ref: https://circleci.com/gh/OpenAPITools/openapi-generator/81692

**Comment by filipe-silva** [comment]
> thanks for the PR.
> 
> can you please update the tests (java unit tests) as well?
> 
> ```
> [ERROR] Failures: 
> [ERROR]   CSharpClientDeepObjectTest.deepObject:70 expected:<2> but was:<1>
> [ERROR] Tests run: 1997, Failures: 1, Errors: 0, Skipped: 0
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project openapi-generator: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /home/circleci/OpenAPITools/openapi-generator/modules/openapi-generator/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> ```
> 
> ref: https://circleci.com/gh/OpenAPITools/openapi-generator/81692

Sure, I can give a go, which IDE do you use?
I currently only have VSCode, but I don't use it for JAVA

**Comment by filipe-silva** [comment]
> thanks for the PR.
> 
> can you please update the tests (java unit tests) as well?
> 
> ```
> [ERROR] Failures: 
> [ERROR]   CSharpClientDeepObjectTest.deepObject:70 expected:<2> but was:<1>
> [ERROR] Tests run: 1997, Failures: 1, Errors: 0, Skipped: 0
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0:test (default-test) on project openapi-generator: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /home/circleci/OpenAPITools/openapi-generator/modules/openapi-generator/target/surefire-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
> ```
> 
> ref: https://circleci.com/gh/OpenAPITools/openapi-generator/81692

All done, test now run OK

imagem

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by filipe-silva** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

Thanks for the heads up, I think it's working. I just added a secondary email.

**Comment by wing328** [comment]
can you please update the samples when you've time?

https://github.com/OpenAPITools/openapi-generator/actions/runs/6799047830/job/18529721203?pr=16990

**Comment by wing328** [comment]
i've merged the latest master into your branch and filed https://github.com/OpenAPITools/openapi-generator/pull/17097.

Some CI tests (C# related) failed. Can you please take a look when you've time?

**Comment by filipe-silva** [comment]
> i've merged the latest master into your branch and filed #17097.
> 
> Some CI tests (C# related) failed. Can you please take a look when you've time?

Hi, I've regenerated the samples and everything seems to be ok, can you resolve the conflicts?

**Comment by filipe-silva** [comment]
> > , can you resolve the conflicts?
> 
> please merge latest master into your branch and regenerate the samples to resolve the merge conflicts
> 
> i'll try to put other c# related PRs on hold for the time being.

Hi, terribly sorry, it completely slipped my mind, because of the holidays starting.

I did the pull and merge, there are no conflitcs as of now.

**Comment by wing328** [comment]
can you pls update the samples when you've time?

https://github.com/OpenAPITools/openapi-generator/actions/runs/7685681970/job/20945052863?pr=16990

**Comment by wing328** [comment]
your last commit includes changes to lots of files not originally included in this PR (likely the rebase wasn't done correctly)

can you please PM me via Slack so that I can help you out?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by filipe-silva** [comment]
> your last commit includes changes to lots of files not originally included in this PR (likely the rebase wasn't done correctly)
> 
> can you please PM me via Slack so that I can help you out?
> 
> https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

Hi (after a lot of time, sorry) so the rebase was getting pretty difficult at the time.
I choose another approach. I've done a new branch, up to date with master and redid my changes.
I'll be closing this PR and opening a new one, since i did a new branch.

**Pull request closed without merging**
