### PR TITLE
[csharp-netcore] Add "WithHttpInfo" variant methods in api_doc

### PR DESCRIPTION
**Pull request by prajon84**
Those methods are useful for us because we need to retrieve information from the headers but they were not documented. This addresses that, no code change.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by prajon84** [comment]
@wing328 @mandrean  @frankyjuang @shibayan @Blackclaws  @lucamazzanti @jfeltesse-mdsol

**Review by jfeltesse-mdsol — APPROVED** [review]

**Comment by wing328** [comment]
Can you please resolve the merge conflicts when you've time? Then I'll merge.

**Comment by wing328** [comment]
Some samples are not yet up-to-date. I'll do it after merging this PR.
```
--- a/samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/DefaultApi.md
+++ b/samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/DefaultApi.md
@@ -52,7 +52,7 @@ This returns an ApiResponse object which contains the response data, status code
 ```csharp
 try
 {
-    ApiResponse<InlineResponseDefault> response = apiInstance.FooGetWithHttpInfo();
+    ApiResponse<FooGetDefaultResponse> response = apiInstance.FooGetWithHttpInfo();
     Debug.Write("Status Code: " + response.StatusCode);
     Debug.Write("Response Headers: " + response.Headers);
     Debug.Write("Response Body: " + response.Data);
Perform git status
HEAD detached at pull/12323/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   samples/client/others/csharp-netcore-complex-files/docs/MultipartApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-ConditionalSerialization/docs/DefaultApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/docs/apis/DefaultApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0/docs/apis/DefaultApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-netstandard2.0/docs/apis/DefaultApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-httpclient/docs/DefaultApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-net47/docs/DefaultApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClient-net5.0/docs/DefaultApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClient/docs/DefaultApi.md
	modified:   samples/client/petstore/csharp-netcore/OpenAPIClientCore/docs/DefaultApi.md
```

Ref: https://github.com/OpenAPITools/openapi-generator/runs/6672862466?check_suite_focus=true

**Comment by wing328** [comment]
FYI. Samples updated via f043602151d

**Pull request merged**
