### PR TITLE
[typescript-rxjs] Prints out the parameter name in throwIfNullOrUndefined

### PR DESCRIPTION
**Pull request by jtvd78**
This updates `throwIfNullOrUndefined` to take in & print the name of the parameter being checked. This PR in response to this comment [here](https://github.com/OpenAPITools/openapi-generator/pull/4250#discussion_r415219054).

The signature of `throwIfNulllOrUndefined` was changed to make `nickname` non-optional, but based on `apis.mustache` the param will never be undefined. Granted, the change is breaking, but this is also merging into 5.0.x. I considered removing the other deprecated exports in `runtime.mustache` (since this is merging into 5.0.x), but I figured I would not in this PR and ask for opinions about that here. 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### CODE REVIEW

**Comment by macjohnny** [comment]
cc @denyo

**Comment by jtvd78** [comment]
@wing328 why the close?

**Comment by macjohnny** [comment]
Ping @wing328

**Comment by TiFu** [comment]
Possibly because the 5.0.x branch has been deleted?

**Comment by macjohnny** [comment]
@jtvd78 please open a new PR against master

**Comment by jtvd78** [comment]
@macjohnny https://github.com/OpenAPITools/openapi-generator/pull/6368

**Pull request closed without merging**
