### PR TITLE
[kotlin] implement serializable data classes (fix #8317)

### LINKED ISSUE #8317: [BUG] kotlin-spring does not generate Serializable models
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

According to the documentation, the model serialization feature should be available for `kotlin-spring`
https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/kotlin-spring.md

But the `serialization` properties don't have an impact on the generated code.

The mustache templates show that the serialization interface is only added for `kotlin-server` and `kotlin-client`.
Is this a bug in the code or in the documentation?

Spring itself uses Jackson to serialize the objects returned from the server. 
But we would also cache some of the generated models in a distributed cache (HazelCast), which requires the object to be Serializable.

##### openapi-generator version

5.0.0

##### Generation Details

Maven Plugin configuration:
```xml
        <plugin>
          <groupId>org.openapitools</groupId>
          <artifactId>openapi-generator-maven-plugin</artifactId>
          <version>5.0.0</version>
          <executions>
            <execution>
              <id>generate-kotlin-spring</id>
              <configuration>
                <apiPackage>my.project.web.api</apiPackage>
                <generateApiTests>false</generateApiTests>
                <generateSupportingFiles>false</generateSupportingFiles>
                <generatorName>kotlin-spring</generatorName>
                <modelPackage>my.project.model</modelPackage>
                <skipValidateSpec>false</skipValidateSpec>
                <configOptions>
                  <basePackage>my.project</basePackage>
                  <exceptionHandler>false</exceptionHandler>
                  <enumPropertyNaming>UPPERCASE</enumPropertyNaming>
                  <interfaceOnly>false</interfaceOnly>
                  <serviceInterface>true</serviceInterface>
                  <sourceFolder>src/main/kotlin</sourceFolder>
                </configOptions>
                <additionalProperties>serializableModel=true</additionalProperties>
                <inputSpec>api.yml</inputSpec>
              </configuration>
            </execution>
          </executions>
        </plugin>
```

### PR DESCRIPTION
**Pull request by LucasKuhlemann**
Implement `java.io.Serializable` in kotlin data classes for `kotlin-spring` generator when `serializableModel` option is enabled.

Fixes #8317.

These existing samples clearly show the effect of this change, as they have `serializableModel` already set to true:
- kotlin-springboot
- kotlin-springboot-3
- kotlin-springboot-modelMutable
- kotlin-springboot-source-swagger1
- kotlin-springboot-source-swagger2
- kotlin-springboot-springfox

See the added `Serializable` interface on all generated models for those samples, as well as the `serialVersionUID` constant in each data class.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by LucasKuhlemann** [comment]
cc
@jimschubert (2017/09) [❤️](https://www.patreon.com/jimschubert), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)

**Comment by LucasKuhlemann** [comment]
Could someone please review this?

**Comment by 4brunu** [comment]
Hi, can you please take a look at CI that is failing?
```
Perform git status
HEAD detached at pull/18386/merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   samples/client/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/model/Category.kt
	modified:   samples/client/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/model/ModelApiResponse.kt
	modified:   samples/client/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/model/Order.kt
	modified:   samples/client/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/model/Pet.kt
	modified:   samples/client/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/model/Tag.kt
	modified:   samples/client/petstore/kotlin-spring-cloud/src/main/kotlin/org/openapitools/model/User.kt
```
and another one
```
* What went wrong:
Execution failed for task ':bootJar'.
> Error while evaluating property 'mainClass' of task ':bootJar'
   > Failed to calculate the value of task ':bootJar' property 'mainClass'.
3 actionable tasks: 3 executed
      > Main class name has not been configured and it could not be resolved
```

**Comment by LucasKuhlemann** [comment]
@4brunu Thanks for checking, and sorry for the late reaction.

I fixed the issue with uncommitted changes in the samples files, but I'm not sure about the second problem you pointed out. Where do you see this, or how could I try to reproduce this problem?

**Comment by 4brunu** [comment]
CI is failing, here is the link.
https://github.com/OpenAPITools/openapi-generator/actions/runs/9234395104/job/25415874312?pr=18386

**Comment by LucasKuhlemann** [comment]
@4brunu Seems the issue has been fixed by someone else on the master branch, the CI no longer fails.

**Review by 4brunu — APPROVED** [review]

**Pull request merged**
