### PR TITLE
[REQ][JAVA]: Assign collections to null by default

### PR DESCRIPTION
**Pull request by sonalidhome**
in auto-generated POJO
 - Updated the template to assign Java collection to null by default
   and instantiate when required.
 - Updated the model classes

This resolves issue #5707

Java Technical Committee
@bbdouglas
@sreeshas
@jfiala
@lukoyanov
@cbornet
@jeff9finger
@karismann
@Zomzog
@lwlee2608
@bkabrda

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
@sonalidhome thanks for the PR.

I remember there was a discussion (issue) on this and the solution is to use `nullable` to determine whether the default is null or empty array list.

**Comment by sonalidhome** [comment]
Thank you @wing328 for the details. 
Currently, we are using the 4.0.1 version of OpenAPI in our project. Nullable is not working in this version. 
I tried this in the OpenAPI master branch and it is working as expected. I was going over issues and PRs, I am not able to locate the exact version in which this change has been added. Can you please let me know if you have some info about this?

**Comment by sonalidhome** [comment]
@wing328 I am now trying to perform `nullable: true` to a collection, it is **not working** in master/ v4.2.0/ v4.0.1  versions. 
Please suggest a solution to this. If not, I'll rebase my PR.

**Comment by sonalidhome** [comment]
@wing328 The description in https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schemaNullable says  A true value adds "null" to the allowed type specified by the type keyword, only if a type is explicitly defined within the same Schema Object. 
This is not mentioning to assign null by default to the collections.

**Comment by wing328** [comment]
please pull the latest master, we've merged PRs to better handle this and add an option for fallback.

**Pull request closed without merging**
