### PR TITLE
Add .t in spec generation of Elixir structs

### PR DESCRIPTION
**Pull request by carrascoacd**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

I'm unable to run the `generate-samples.sh` due to an error when generating the JAR file:

```
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.5:report (jacoco-site) on project openapi-generator: An error has occurred in JaCoCo report generation. Error while creating report: null: EOFException -> [Help 1]
``` 

cc/ @mrmstn

### CODE REVIEW

**Comment by mrmstn** [comment]
Hi @carrascoacd, thank you very much for your PR

Sadly, the error doesn't say a lot to me :/

Have you tried `./run-in-docker.sh ./bin/generate-samples.sh bin/configs/elixir.yaml` to generate the examples?

**Comment by wing328** [comment]
Updated samples via https://github.com/OpenAPITools/openapi-generator/pull/8159/commits/2ab4cebaca2cb24544559e4ae3d77b07f1d1ecf3

**Comment by carrascoacd** [comment]
@mrmstn I was able to update the `Petstore` as you said using Docker. Maybe we can improve the contribution guidelines in order to add that step.

The outputs from the last comments from @wing328 are ok. Many thanks!

**Comment by carrascoacd** [comment]
I think that the deserialization is not right, see [this](https://github.com/OpenAPITools/openapi-generator/pull/8159/files#diff-4d96b8e1eb5c9d59af92527eb821c223c25285bdbbafeff3bdec2afd610eb861R44)

It should expect the struct, not the type if I'm right.

**Comment by wing328** [comment]
>     |> deserialize(:"anytype_1", :struct, OpenapiPetstore.Model.Map.t, options)

What does the correct code look like?

**Comment by carrascoacd** [comment]
Let's see this example:
```elixir
defmodule Pet do
  @type t :: %Pet{name: String.t()}

  defstruct [:name]
end
```
```sh
iex(0)> struct(Pet.t)
** (UndefinedFunctionError) function Pet.t/0 is undefined or private
    Pet.t()
iex(1)> struct(Pet)
%Pet{name: nil}
```

It should be:  `|> deserialize(:"anytype_1", :struct, OpenapiPetstore.Model.Map, options)`

**Comment by carrascoacd** [comment]
I was reviewing this, and I think that the problem is the `isPrimitiveType` which is returning `true` for `Map` when it should return `false` since it is a primitive type. @mrmstn could you help me to understand why it happens?

There is some coupling between the spec definition and the type definition somewhere.

**Comment by mrmstn** [comment]
Hi @carrascoacd, sorry for my late replay. 
I need to look into it a little bit further.

In the mean time, could you explain a little bit, what you're trying to fix with this issue?
What was the "trigger" for this PR?

**Comment by mrmstn** [comment]
image
`org/openapitools/codegen/DefaultCodegen.java:3380`

Thanks for the tip with the primitiv types. It looks like the `anytype_*`  and map are handled differentially .. 

I'm investigating a little bit more, just wanted to let you know I'm on it and see your problem :) - so there is no need for an answer on my question

**Comment by mrmstn** [comment]
@carrascoacd since I'm only in the tech comitee I can't write to your branch, so I created a PR https://github.com/carrascoacd/openapi-generator/pull/1

After that, every thing looks good to me and hopefully @wing328 can merge this fix

**Comment by carrascoacd** [comment]
Ok many thanks for taking a look @mrmstn

**Comment by carrascoacd** [comment]
@mrmstn helped me with this and we merged the changes from https://github.com/carrascoacd/openapi-generator/pull/1 into this branch. I think we are good to merge now :) @wing328

**Review by mrmstn — APPROVED** [review]

**Comment by wing328** [comment]
Pushed https://github.com/OpenAPITools/openapi-generator/pull/8159/commits/260feb5be495310800052588c7f55bcf10f654f5 to fix the CircleCI failure. Will merge if all tests pass.

**Comment by wing328** [comment]
```
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  mime 1.5.0
  poison 3.1.0
  tesla 1.4.0
All dependencies are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (test) @ ElixirPetstoreClientTests ---
...

Finished in 0.5 seconds
3 tests, 0 failures

Randomized with seed 420535
```
Tested locally and the result is good.

**Pull request merged**
