### PR TITLE
Use golang's provided method names (gin)

### PR DESCRIPTION
**Pull request by kkirsche**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
This commit modifies the gin template for the router to leverage the http constants for method types as defined by RFC 7231 section 4.3. These are documented on:

https://golang.org/pkg/net/http/#pkg-constants

This removes the need for the `strings` dependency and does not require any new dependencies, as `net/http` is already imported.

### CODE REVIEW

**Comment by kkirsche** [comment]
Technical Committee:

@antihax @bvwells @grokify @kemokemo

**Comment by wing328** [comment]
Can you please run `./bin/go-gin-petstore-server.sh` or the coresponding batch file under bin\windows to update the Go Gin Petstore samples?

**Comment by kkirsche** [comment]
Is there a guide for the java dependency stuff? I try to avoid java whenever possible, so I'm not sure how to get it's basic stuff setup:

```
 ~/git/java/openapi-generator/bin >> patch-1 $ ./go-gin-petstore-server.sh
# START SCRIPT: ./go-gin-petstore-server.sh
./go-gin-petstore-server.sh: line 25: mvn: command not found
Removing files and folders under samples/server/petstore/go-gin-api-server
Error: Unable to access jarfile ./modules/openapi-generator-cli/target/openapi-generator-cli.jar
```

**Comment by kkirsche** [comment]
That worked once I removed the corporate proxy from the path, not sure if it's not proxy aware or if our proxies are blocking this type of traffic.

Updated and pushed, thank you for your help with that, @wing328

**Comment by wing328** [comment]
@kkirsche thanks again for your contribution, which has been included in the v4.0.1 release (https://twitter.com/oas_generator/status/1135534738658062336)

**Pull request merged**
