### PR TITLE
fix(golang): make sure xml.Encoder is closed

### PR DESCRIPTION
**Pull request by adamdecaf**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

/cc @lwj5

### CODE REVIEW

**Comment by adamdecaf** [comment]
The `.Close()` method [was added in Go 1.20](https://tip.golang.org/doc/go1.20#encoding/xml), so OpenAPI probably needs to support older versions? Do you go back to Go 1.18?

**Comment by wing328** [comment]
thanks for the PR. CI failed with errors: https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/24812/workflows/5e1fba49-7f46-4b8e-83f7-723066699134/jobs/73874

please take a look when you've time.

**Comment by adamdecaf** [comment]
That CI job runs on `go version go1.18 linux/amd64` and `.Close()` was added in Go 1.20

```
go-petstore/client.go:561:36: enc.Close undefined (type *xml.Encoder has no field or method Close)
```

How long does OpenAPI support older versions of Go?

**Comment by lwj5** [comment]
My opinion is that it should be supported until the version is EOL

**Comment by wing328** [comment]
https://endoflife.date/go

let's target Go 1.19

**Comment by adamdecaf** [comment]
I've pushed a fix for older versions of Go. When a newer version of Go is used to compile code after generation it will call `Encoder.Close()`, which is announced and the default for Go +1.20.

**Pull request merged**
