### PR TITLE
in case of defined status codes > 299 switch will have no effect. issue 7788

### PR DESCRIPTION
**Pull request by kruegge82**
…described in issue 7788

so we get only an error if statusCode is not defined AND not between 200 and 299

https://github.com/OpenAPITools/openapi-generator/issues/7788

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Review by deluxetom — APPROVED** [review]

**Comment by kruegge82** [comment]
have i anything todo for implement into the master branch or wil it implemented with next version?

**Comment by wing328** [comment]
@kruegge82 thanks for the PR

please follow step 3 to update the samples so that CI can verify the change

**Review by kruegge82 — COMMENTED** [review]
im not sure which step 3? i have not change files after PR...

**Comment by wing328** [comment]
cc 
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

**Comment by kruegge82** [comment]
have i anything more todo?

**Comment by kruegge82** [comment]
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12) @deluxetom 

i have anything more todo? i ask because the PR is not merged with master branch...

**Comment by wing328** [comment]
tested the change locally and looks good.

thanks for the PR

sorry for the delay as we're short-handed in reviewing PRs from the community

**Pull request merged**
