### PR TITLE
Fix isEnum for referenced enums

### PR DESCRIPTION
**Pull request by aymanbagabas**
Fixes: https://github.com/OpenAPITools/openapi-generator/issues/5676
Referenced enums are now properly marked as isEnum = true

https://github.com/OpenAPITools/openapi-generator/issues/5676

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by aymanbagabas** [comment]
@4brunu I stumbled into this while working on a generated Swift5 project where an enum reference path parameter wouldn't use its own `.rawValue` because `isEnum` is not set to `true`. Saw the PR and figured the fix is only `property.isEnum = true;`.

**Comment by 4brunu** [comment]
Since this is a change in DefaultCodegen.java, I ask @wing328 to help review this change.

**Comment by wing328** [comment]
Thanks for the fix. Looks like at least one unit test needs to be updated accordingly:

```
[ERROR] Tests run: 1442, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 42.728 s <<< FAILURE! - in TestSuite
[ERROR] embeddedEnumArrayTest(org.openapitools.codegen.kotlin.spring.KotlinSpringServerCodegenTest)  Time elapsed: 2.883 s  <<< FAILURE!
java.lang.IllegalStateException: 
Compilation error. Details:
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:34:38: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("BLACK") bLACK("BLACK"),
                                     ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:36:34: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("RED") rED("RED"),
                                 ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:38:40: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("ORANGE") oRANGE("ORANGE"),
                                       ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:40:40: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("YELLOW") yELLOW("YELLOW"),
                                       ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:42:36: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("BLUE") bLUE("BLUE"),
                                   ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:44:38: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("GREEN") gREEN("GREEN");
                                     ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:54:38: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("BLACK") bLACK("BLACK"),
                                     ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:56:34: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("RED") rED("RED"),
                                 ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:58:40: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("ORANGE") oRANGE("ORANGE"),
                                       ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:60:40: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("YELLOW") yELLOW("YELLOW"),
                                       ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:62:36: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("BLUE") bLUE("BLUE"),
                                   ^
/tmp/test4964982098317715006/zz/yyyy/model/xxxx/NoEmbeddedEnumArray.kt:64:38: error: type mismatch: inferred type is String but NoEmbeddedEnumArray.Colors was expected
        @JsonProperty("GREEN") gREEN("GREEN");
                                     ^
	at org.openapitools.codegen.kotlin.spring.KotlinSpringServerCodegenTest.embeddedEnumArrayTest(KotlinSpringServerCodegenTest.java:45)
[ERROR] Failures: 
[ERROR]   KotlinSpringServerCodegenTest.embeddedEnumArrayTest:45 » IllegalState Compilat...
[ERROR] Tests run: 1442, Failures: 1, Errors: 0, Skipped: 0
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project openapi-generator: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/OpenAPITools/openapi-generator/modules/openapi-generator/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M3:test (default-test) on project openapi-generator: There are test failures.
```

Ref: https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/771708149

**Comment by questionablequestion** [comment]
Do we have any news on this? I believe issue #9897 I have would be solved with fix above.

**Comment by snowe2010** [comment]
Been two years now since the original issue (https://github.com/OpenAPITools/openapi-generator/issues/5676), is there any movement on this? Anything we can do to push it along? If setting `isEnum` to true causes issues in other generators it seems like those generators need to be fixed, right? An explanation of what exactly the `_enum` array vs the `allowedValues` array is would also probably help this move along as well.

**Comment by oszust002** [comment]
Hey, any update on this? This is preventing from usage of enums without manually creating some code and doing import mappings and api replacements

**Comment by rivancic** [comment]
> @wing328 this fix actually causes a lot of problems where the referenced schema doesn't have the correct concrete dataType and `isEnum` causes the templates to redefine the enums as inlines with the wrong dataType. I tested this with the Swift generator, can't confirm the others.

It's the same with JavaSpring. The templates have to be adapted to distinguish between inline Enum (isEnum==true && isString==true) and referenced enum schema.

Anyway I think as a base we should take those changes from @LukeMartin https://github.com/LukeMarlin/openapi-generator/pull/1 or start from scratch.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/13880 to offer a way to fix the issue. Please review when you guys have time.

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/13880

**Pull request closed without merging**
