### PR TITLE
[Go] uses sanitized model name instead of the name

### LINKED ISSUE #18632: [BUG] [Go] Go SDK breaks for parent schema names with special character(._)
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

While generating Go SDK with OpenAPI Generator, if a composite schema's parent schema contains names with special characters (. _) and a discriminator is defined on the parent schema, Go SDK fails because the sanitized name of the parent model is not used in the composite schema model.

##### openapi-generator version

Latest version(7.5.0)

##### OpenAPI declaration file content or url

```
openapi: 3.0.0
info:
  title: Test
  version: 1.0.0
paths: {}
components:
  schemas:
    FinalItem:
      type: object
      allOf:
        - $ref: '#/components/schemas/Base.Item'
        - $ref: '#/components/schemas/AdditionalData'
    Base.Item:
      type: object
      properties:
        title:
          type: string
        type:
          type: string
          enum:
            - FINAL
          example: FINAL
      discriminator:
        propertyName: type
        mapping:
          FINAL: '#/components/schemas/FinalItem'
      required:
        - title
        - type
    AdditionalData:
      type: object
      properties:
        prop1:
          type: string
        quantity:
          type: integer
          format: int32
          example: 1
          minimum: 1
        unitPrice:
          type: number
          format: double
          example: 9.99
          minimum: 0.0
        totalPrice:
          type: number
          format: double
          example: 9.99
          minimum: 0.0
      required:
        - sku
        - quantity
        - unitPrice
        - totalPrice
```

##### Generation Details

```
mvn clean install
java -jar openapi-generator-cli-7.5.0.jar generate -i example.yaml -g go -o gosdk
```

##### Steps to reproduce

Generate the Go SDK with the specified spec file and observe that the parent schema model name in the composite schema model is not sanitized.

Actual Parent model file
```
type BaseItem struct {
	Title string `json:"title"`
	Type string `json:"type"`
}
```

Actual Composite model file
when referring to the parent schema Base.Item which is not sanitized name, it leads to failure of generated SDK, Instead of referring to sanitized name(BaseItem) of parent model
```
type FinalItem struct {
	Base.Item
	Prop1 *string `json:"prop1,omitempty"`
	Quantity int32 `json:"quantity"`
	UnitPrice float64 `json:"unitPrice"`
	TotalPrice float64 `json:"totalPrice"`
}
```

Expected model definition in Composite schema model file.
```
type FinalItem struct {
	BaseItem
	Prop1 *string `json:"prop1,omitempty"`
	Quantity int32 `json:"quantity"`
	UnitPrice float64 `json:"unitPrice"`
	TotalPrice float64 `json:"totalPrice"`
}
```

##### Suggest a fix

In following file, when checking for parent model for composite schema, specify to use parentmodel.classname instead of parentmodel.name
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/model_simple.mustache

Following changes are suggested along with line numbers
```
6	{{#parentModel.name}}
7	{{^isArray}}
8		{{{parentModel.classname}}}
9	{{/isArray}}
10	{{#isArray}}
11		Items {{{parentModel.classname}}}
12	{{/isArray}}
13	{{/parentModel.name}}
```

### PR DESCRIPTION
**Pull request by vvb**
Fixes #18632 

@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5 @wing328 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. please add the new folder to https://github.com/OpenAPITools/openapi-generator/blob/master/CI/circle_parallel.sh#L45 so that circleci will test it moving forward.

**Comment by wing328** [comment]
you will need to add a pom.xml as well in the new folder (by copying it from another go sample folder and modify it a bit)

**Comment by vvb** [comment]
> you will need to add a pom.xml as well in the new folder (by copying it from another go sample folder and modify it a bit, e.g. new artifactId)

done.

**Comment by wing328** [comment]
lgtm. thanks for the PR

**Pull request merged**
