### PR TITLE
Engine param in maven plugin.

### PR DESCRIPTION
**Pull request by azizamaan**
### PR checklist

- [-] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)
Engine param for maven plugin.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
What about naming it as "templatingEngineName" or "templatingEngine" instead?

cc @jimschubert

**Comment by azizamaan** [comment]
> What about naming it as "templatingEngineName" or "templatingEngine" instead?
> 
> cc @jimschubert

Keeping consistent with command line args. If you insist I will change.

**Comment by wing328** [comment]
> Keeping consistent with command line args. If you insist I will change.

Ok. That's a valid point.

**Comment by azizamaan** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

seems I fixed it, check once :)

**Comment by wing328** [comment]
> seems I fixed it, check once :)

Yup, looks good now.

**Comment by jimschubert** [comment]
This looks good to me, but will need the plugin's README updated with the new option.

**Comment by wing328** [comment]
Filed https://github.com/OpenAPITools/openapi-generator/pull/3025

**Comment by wing328** [comment]
@azizamaan thanks again for your contribution, which has been included in the v4.0.1 release (https://twitter.com/oas_generator/status/1135534738658062336)

**Pull request merged**
