### PR TITLE
Feat/jetbrains http client

### PR DESCRIPTION
**Pull request by jlengrand**
This PR is currently a WIP, in order to get feedback on it.

This PR adds (basic) support for the [Jetbrains HTTP Client](https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html). I intend, with your permission, to be the owner of that generator in the future.

For a given OpenAPI file, the current generator creates a HTTP request for each endpoint, with variable parameters where necessary. It also supports Content-Type headers.

For the 3.0 Petstore, you can find the generated [README](https://github.com/jlengrand/openapi-generator/blob/feat/jetbrains-http-client/samples/client/petstore/jetbrains/http/client/README.md) as well as one of the generated [API Files](https://github.com/jlengrand/openapi-generator/blob/feat/jetbrains-http-client/samples/client/petstore/jetbrains/http/client/Apis/PetApi.http#addpet).

This PR currently lacks tests, and I also want to add minimal support for additional headers as well before it gets merged. 

With the newly released [Jetbrains HTTP Client CLI](https://blog.jetbrains.com/idea/2022/12/http-client-cli-run-requests-and-tests-on-ci/), I believe this generator can be useful to quickly generate full testing landscape for project APIs, and potentially include them as part of automated CI as well.
You can find a list of features that I want to add in the longer run over [here](https://github.com/jlengrand/openapi-generator/issues).

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by jlengrand** [comment]
Can someone help with this? I tried locally but I don't see any change that should be committed?

**Comment by jlengrand** [comment]
Remove what I said, it's ready to be merged!

**Comment by wing328** [comment]
@jlengrand I think this looks good to start with.

Do you know if there's any easy way to test the auto-generated output in the CI (e.g. Github workflow)?

**Comment by wing328** [comment]
can you please resolve the merge conflicts when you've time?

will try to include it in the upcoming v6.3.0 release

**Comment by jlengrand** [comment]
When is that? Wanted to look at creating some tests as you requested

**Comment by jlengrand** [comment]
Alright @wing328 I fixed the conflicts, and also added the generator in the README which I had forgotten

**Comment by piotrkpaul** [comment]
Hello @jlengrand, thanks for the great work! Are you considering payload generation for this one?

**Pull request merged**
