### PR TITLE
[Python] Fix incorrectly capitalized mustache identifier in apis template

### PR DESCRIPTION
**Pull request by harmony7**
This tiny PR fixes the spelling of an identifier that was incorrectly cased in a mustache template. The fix only affects a comment in the output, so it will make no runtime difference when consuming a generated client.

In the Ruby generator, the package name is available as `{{packageName}}`, but in `src/main/resources/python/__init__apis.mustache`, it was being referenced as `{{packagename}}`.
This produced incorrect output such as:

```ruby
# In order to avoid this, import only the API that you directly need like:
#
#   from .api.my_api import MyApi
```
(note the missing package name)

The corrected output:
```ruby
# In order to avoid this, import only the API that you directly need like:
#
#   from my_package.api.my_api import MyApi
```

cc @cliffano @zlx @autopp

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by harmony7** [comment]
Hi, the CI is giving problems in the "samples up-to-date" step.

The details reveal a problem with a completely unrelated file, so I don't think this is a problem on my end. Can someone check the status of this for me? thanks.

**Comment by wing328** [comment]
> Hi, the CI is giving problems in the "samples up-to-date" step.

I've fixed that in the master. 

Your PR looks good. Thanks for that.

**Comment by wing328** [comment]
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @spacether (2019/11) ❤️

**Comment by harmony7** [comment]
Yes of course this is Python.  I got confused I guess, have been using different generators one after the other.

Thanks for the approval and merge, cheers =)

**Pull request merged**
