### PR TITLE
Adds exceptions module to python clients

### PR DESCRIPTION
**Pull request by spacether**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

### Description of the PR

- This PR adds an exceptions module for the python2 + python3 client generators.
- All raised exceptions now inherit from a parent OpenApiException class
- This is a non-breaking change, exceptions also inherit from KeyError etc as their base class
- This PR is a feature addition which is needed for https://github.com/OpenAPITools/openapi-generator/pull/2049 ([Python] add additionalProperties support, Option2)

### CODE REVIEW

**Comment by wing328** [comment]
@spacether when you've time, can you please resolve the merge conflicts?

**Comment by spacether** [comment]
@wing328 the merge conflicts have been resolved
The CicleCI error is not caused by my diff. It is
```
Results :

Failed tests:   testCreateAndGetPetAsync(org.openapitools.client.api.PetApiTest)

Tests run: 238, Failures: 1, Errors: 0, Skipped: 6

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12:test (default-test) on project petstore-okhttp-gson: There are test failures.
```
Are we good to merge?

**Comment by wing328** [comment]
I've restarted the job. Let's see how it goes.

**Comment by wing328** [comment]
All tests passed 👍

**Pull request merged**
