### PR TITLE
[csharp] massively improve csharp templates code

### PR DESCRIPTION
**Pull request by filipe-silva**
massively improve csharp templates code

improved apiclient.mustache to keep it dry, sharing a single exec with Action<> delegate.
improved api.mustache to keep it dry, used chain constructors, kept RequestOptions in a single method, set configuration with alias directive
moved fqn types to using directive for cleaner code
removed 'this' from variables/props that are redundant
fix CSharpClientDeepObjectTest code is now DRY so count must only be one

Note:
This is a PR based on #16990 with resolved merge conflicts, and up to date with master

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mandrean  @shibayan  @Blackclaws  @lucamazzanti  @iBicha @wing328

### CODE REVIEW

**Comment by wing328** [comment]
please PM me via Slack when you've time. thanks

**Comment by devhl-labs** [comment]
Your additions to ApiClient.mustache use tabs. The rest of the document and all the other mustache templates use spaces. This is a regular comment instead of a review because my browser tends to freeze looking at large diffs :(

**Comment by wing328** [comment]
Please instead submit a small PR for each enhancement or bug fix so that it can be reviewed and merged more easily.

**Comment by wing328** [comment]
and looks like some of these enhancements were already done in the latest master: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp/modelGeneric.mustache#L401

my suggestion is to file new smaller PRs based on the latest master and we can get these merged quicker to keep the ball rolling.

**Pull request closed without merging**
