### PR TITLE
[dart][dio] add dateLibrary options ( core, timemachine )

### PR DESCRIPTION
**Pull request by amondnet**
This pr adds `dateLibrary` option and simple [test](https://github.com/amondnet/openapi-generator/blob/3c7889a9544d597c569b963b6ed72f9ae994ee6c/modules/openapi-generator/src/test/java/org/openapitools/codegen/dartdio/DartDioModelTest.java#L102) to `dart-dio` generator. 
`dateLibrary` has two options.

- core : `dart:core`, (default), not handled properly `date`, `date-time` format; https://github.com/OpenAPITools/openapi-generator/issues/2696  I will make a new PR on this. 
- timemachine: [time_machine](https://pub.dev/packages/time_machine)

If `dateLibrary` is `timemachine`,

**input**
```yaml
openapi: 3.0.0
info:
  contact:
    email: amond@amond.net
  description: test
  title: test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DateContainer'
          description: OK

components:
    schemas:
      DateContainer:
        type: object
        properties:
          date:
            format: date
            type: string
```

 **output**

```dart
import 'package:time_machine/time_machine.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'date_container.g.dart';

abstract class DateContainer
    implements Built<DateContainer, DateContainerBuilder> {
  @nullable
  @BuiltValueField(wireName: 'date')
  LocalDate get date;

  // Boilerplate code needed to wire-up generated code
  DateContainer._();

  factory DateContainer([updates(DateContainerBuilder b)]) = _$DateContainer;
  static Serializer<DateContainer> get serializer => _$dateContainerSerializer;
}
``` 

@ircecho  @swipesight @jaumard @nickmeinhold

--

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Please run the following to update the doc as well
```
"./bin/utils/export_docs_generators.sh"
"./bin/utils/copy-to-website.sh"
"./bin/utils/export_generators_readme.sh
```

**Comment by amondnet** [comment]
@wing328 I have updated the documentation.

**Comment by nickmeinhold** [comment]
Thanks @amondnet!

So guys I don’t use this generator or know much about it.

Personally I think we should be working toward a single dart generator with options rather than continuing to diverge.  I respect that others have different opinions but that is where I want to be spending my limited time rather than trying to stay on top of the different generators.

I’m wondering if, rather than getting silence from the technical committee, @wing328 what do you think about asking @athornz and @amondnet if they want to be the technical committee for the dart-dio generator (and would you guys want to?). 

Thanks, sorry I'm not more help.

**Comment by athornz** [comment]
@nickmeinhold I'm happy to be added to the committee for dart dio.

**Comment by amondnet** [comment]
@nickcmaynard Yes, I would like to join the committee.

**Comment by wing328** [comment]
Add @athornz, @amondnet to Dart technical committee via #4800 as both have at least 3 merged PRs for Dart generators.

Thanks for joining us to help move the project forward.

**Comment by hungify** [comment]
This issue is persisting in the latest version.
https://github.com/OpenAPITools/openapi-generator/issues/15182#issuecomment-2780166171

<details>
<summary>Details</summary>

> Any updates? I'm having a problem, as [@AAkira](https://github.com/AAkira) mentioned. I tried to change the template, but it didn't work, and I also switched to `timemachine` instead of `core`, but it caused an error.
> 
> ```
> Could not generate `fromJson` code for `shipDate`.
> To support the type `OffsetDateTime` you can:
> * Use `JsonConverter`
>   https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
> * Use `JsonKey` fields `fromJson` and `toJson`
>   https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
>   https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
> package:apiService/src/model/order.dart:79:25
>    ╷
> 79 │   final OffsetDateTime? shipDate;
> ```
> 
> I found a `date.mustache` file, but I’m unsure how to use it.
> 
> ```
> /// A gregorian calendar date generated by
> /// OpenAPI generator to differentiate
> /// between [DateTime] and [Date] formats.
> class Date implements Comparable<Date> {
>   final int year;
> 
>   /// January is 1.
>   final int month;
> 
>   /// First day is 1.
>   final int day;
> 
>   Date(this.year, this.month, this.day);
> 
>   /// The current date
>   static Date now({bool utc = false}) {
>     var now = DateTime.now();
>     if (utc) {
>       now = now.toUtc();
>     }
>     return now.toDate();
>   }
> 
>   /// Convert to a [DateTime].
>   DateTime toDateTime({bool utc = false}) {
>     if (utc) {
>       return DateTime.utc(year, month, day);
>     } else {
>       return DateTime(year, month, day);
>     }
>   }
> 
>   @override
>   int compareTo(Date other) {
>     int d = year.compareTo(other.year);
>     if (d != 0) {
>       return d;
>     }
>     d = month.compareTo(other.month);
>     if (d != 0) {
>       return d;
>     }
>     return day.compareTo(other.day);
>   }
> 
>   @override
>   bool operator ==(Object other) =>
>       identical(this, other) ||
>       other is Date &&
>           runtimeType == other.runtimeType &&
>           year == other.year &&
>           month == other.month &&
>           day == other.day;
> 
>   @override
>   int get hashCode => year.hashCode ^ month.hashCode ^ day.hashCode;
> 
>   @override
>   String toString() {
>     final yyyy = year.toString();
>     final mm = month.toString().padLeft(2, '0');
>     final dd = day.toString().padLeft(2, '0');
> 
>     return '$yyyy-$mm-$dd';
>   }
> }
> 
> extension DateTimeToDate on DateTime {
>   Date toDate() => Date(year, month, day);
> }
> ```
</details>

**Pull request merged**
