### PR TITLE
[Typescript][Fetch] Fix bugs with new typescript-fetch generator

### LINKED ISSUE #1535: [typescript-fetch] (4.0.X) Missing queryParameters initialization
##### Description

Testing out the updated generator from PR #569 and I noticed an issue where I have multiple authentication requirements for an API endpoint (logical AND - both required) for an API key via query parameter and via an Authorization header. The generated code places both in correctly, however, for endpoints where I otherwise have no other query parameters (e.g. the authentication method is the only one), the variable `queryParameters` is never defined and its not passed in to the request.

##### openapi-generator version

4.0.0-20181118.115720-41

##### OpenAPI declaration file content or url (partial)

```yaml
swagger: "2.0"

paths:
  "/admin/users/{id}/clearTokens":
    post:
      operationId: "users.clear_tokens"
      responses:
        204:
          description: Success
      parameters:
        - in: path
          name: id
          required: true
          type: string
      security:
        - google_id_token: []
          api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  google_id_token:
    authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth"
    flow: "implicit"
    type: "oauth2"
```

Generated Code excerpt:

```typescript
async usersClearTokensRaw(requestParameters: UsersClearTokensRequest): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling usersClearTokens.');
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            queryParameters["key"] = this.configuration.apiKey("key"); // api_key authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            if (typeof this.configuration.accessToken === 'function') {
                headerParameters["Authorization"] = this.configuration.accessToken("google_id_token", []);
            } else {
                headerParameters["Authorization"] = this.configuration.accessToken;
            }
        }

        const response = await this.request({
            path: `/admin/users/{id}/clearTokens`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
        });

        return new runtime.VoidApiResponse(response);
    }
```

##### Command line used for generation

 openapi-generator generate -i openapi.yaml -l typescript-fetch -c es6.json -o ./typescript-api/ 

##### Steps to reproduce

1. Use the provided yaml excerpt above to generate a client with the provided command line
2. Buggy code generated

##### Related issues/PRs

PR #569 

##### Suggest a fix/enhancement

Template variable `#hasQueryParams` should be set to true if an authentication method required for that endpoint uses query parameters.

### LINKED ISSUE #1546: [typescript-fetch] (4.0.X) Model parameter uses string type when format: date
##### Description

The typescript-fetch generator defines models with type: string/format: date as type string, but serializes/deserializes the value as a Date

##### openapi-generator version

openapi-generator-cli-4.0.0-20181126.024631-44

##### OpenAPI declaration file content or url

```yaml
swagger: "2.0"

paths:
  "/config":
    get:
      operationId: "config.get"
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/SiteConfiguration"

definitions:
  SiteConfiguration:
    description: "Site configuration"
    type: object
    properties:
      maxReportingDate:
        type: string
        format: date
      minReportingDate:
        type: string
        format: date
```
Generated Code (excerpt):

```typescript
export interface SiteConfiguration {
    /**
     * 
     * @type {string}
     * @memberof SiteConfiguration
     */
    maxReportingDate?: string;
    /**
     * 
     * @type {string}
     * @memberof SiteConfiguration
     */
    minReportingDate?: string;
}

export function SiteConfigurationFromJSON(json: any): SiteConfiguration {
    return {
        'maxReportingDate': !exists(json, 'maxReportingDate') ? undefined : new Date(json['maxReportingDate']),
        'minReportingDate': !exists(json, 'minReportingDate') ? undefined : new Date(json['minReportingDate']),
    };
}
```

##### Command line used for generation

openapi-generator generate -i openapi.yaml -l typescript-fetch -c es6.json -o ./typescript-api/

##### Steps to reproduce

1. Use the provided yaml excerpt above to generate a client with the provided command line
2. Buggy code generated

##### Related issues/PRs

PR #569

##### Suggest a fix/enhancement

Add additional resolution for Date or DateTime formatted strings in `getTypeDeclaration` [here](https://github.com/OpenAPITools/openapi-generator/blob/4.0.x/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java#L123)

### LINKED ISSUE #1547: [typescript-fetch] (4.0.X) Missing required parameter in <Model>FromJSON
##### Description
When there is a composition of multiple models, the generated typescript code does not add the required parameters of the extended type in the generated `FromJSON` function.

##### openapi-generator version
openapi-generator-cli-4.0.0-20181126.024631-44

##### OpenAPI declaration file content or url
```yaml
swagger: "2.0"
info:
  title: "Combined Test"

paths:
  "/get/Combined":
    get:
      summary: Retrieve List of Combined
      operationId: "get.Combined"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Combined"

definitions:         
  Simple:
    type: object
    required:
      - Name
    properties:
      Name:
        type: string
  Combined:
    allOf:
      - $ref: "#/definitions/Simple"
      - type: object
        properties:
          Occupation:
            type: string
```

Generated Code (excerpt):

```typescript
export interface Simple {
    /**
     * 
     * @type {string}
     * @memberof Simple
     */
    name: string;
}

export interface Combined extends Simple {
    /**
     * 
     * @type {string}
     * @memberof Combined
     */
    occupation?: string;
}

export function CombinedFromJSON(json: any): Combined {
    return {
        'occupation': !exists(json, 'Occupation') ? undefined : json['Occupation'],
    };
}
```

Compiler throws an error since its missing the required `name` parameter

##### Command line used for generation

openapi-generator generate -i openapi.yaml -l typescript-fetch -c es6.json -o ./typescript-api/

##### Steps to reproduce

1. Use the provided yaml excerpt above to generate a client with the provided command line
2. Buggy code generated

##### Related issues/PRs

PR #569

##### Suggest a fix/enhancement

Not sure - any suggestions on how to tackle this would be appreciated and I can add it to PR #1545 

Looking at the debugModels export for the provided yaml definition, it seems that `parentVars` is an empty list for model `Combined` which could have been used to add additional required params to the function. Alternatively, the `allVars` template variable could be used over the `vars` variable in this block as it contains all potential params?

### LINKED ISSUE #1561: [typescript-fetch] (4.0.X) format: date parameters should not include time component
##### Description

Currently, when a request is generated via the typescript-fetch client, type: string/format:date parameters include a time component when it should not.

##### openapi-generator version

openapi-generator-cli-4.0.0-20181126.024631-44

##### OpenAPI declaration file content or url

```yaml
swagger: "2.0"
info:
  title: "Simple Test"

paths:
  "/get/Simple":
    get:
      summary: Retrieve List of Simple
      operationId: "get.Simple"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Simple"

definitions:         
  Simple:
    type: object
    required:
      - Name
    properties:
      Date:
        type: string
        format: date
```

Output:

```ts
import { exists } from '../runtime';
/**
 * 
 * @export
 * @interface Simple
 */
export interface Simple {
    /**
     * 
     * @type {Date}
     * @memberof Simple
     */
    date?: Date;
}

export function SimpleFromJSON(json: any): Simple {
    return {
        'date': !exists(json, 'Date') ? undefined : new Date(json['Date']),
    };
}

export function SimpleToJSON(value?: Simple): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'Date': value.date === undefined ? undefined : value.date.toISOString(),
    };
}
```
##### Command line used for generation

openapi-generator generate -i openapi.yaml -l typescript-fetch -c es6.json -o ./typescript-api/

##### Steps to reproduce

1. Use the provided yaml excerpt above to generate a client with the provided command line
2. Buggy code generated

##### Related issues/PRs

PR #569

##### Suggest a fix/enhancement

Update template to take substring of ISO date to only include the date portion when format: date

### LINKED ISSUE #1565: [typescript-fetch] (4.0.X) enums in API generator template missing
##### Description

The model mustache template takes into account enums, the api template does not and incorrectly sets the datatype to the enum values.

##### openapi-generator version

openapi-generator-cli-4.0.0-20181126.024631-44

##### OpenAPI declaration file content or url
```yaml
swagger: "2.0"
info:
  title: "Simple Test"

paths:
  "/get/Simple":
    get:
      summary: Retrieve List of Simple
      operationId: "get.Simple"
      parameters:
        - in: query
          name: animal
          type: string
          enum:
            - Cat
            - Dog
            - Tiger
      responses:
        200:
          description: OK
```

Generated code (excerpt):
```ts
export interface GetSimpleRequest {
    animal?: 'Cat' | 'Dog' | 'Tiger';
}
```

##### Command line used for generation

openapi-generator generate -i openapi.yaml -l typescript-fetch -c es6.json -o ./typescript-api/

##### Steps to reproduce

1. Use the provided yaml excerpt above to generate a client with the provided command line
2. Buggy code generated

##### Related issues/PRs

PR #569

##### Suggest a fix/enhancement

Update the api mustache template to follow the same enum logic as the model template.

### PR DESCRIPTION
**Pull request by someone1**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
Fixes multiple issue with the update typescript-fetch generator

- fix #1535 - always initialize the `queryParameters` variable
- fix #1546 - use parameter type `Date` when a string is formatted as `date` or `date-time`
- fix #1547 - use allVars template variable for serializing/deserializing models. Pay attention to readOnly parameters.
- fix #1561 - omit time component when serializing parameters with format: date
- Update tsconfig.json to include `"moduleResolution" : "node",` option
- fix #1565 - add enums found in api operations

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)

### CODE REVIEW

**Comment by wing328** [comment]
LGTM

cc @place1

**Comment by someone1** [comment]
May as well leave this open for a few days - I'm running into more issues as I try and update my application using the new generator.

**Comment by someone1** [comment]
I've finished converting my internal application using the new generator and so I think this PR is done. There is one remaining issue regarding `allOf` compositions (mentioned in #1563) which I think is being handled in #1360 that I wrote a post-processing script to fix until it gets resolved.

If there are any issues with the changes I made, please let me know if I can adjust them to meet the roadmap/goals/direction of the project!

**Comment by wing328** [comment]
@someone1 thanks for the contribution, which has been included in the 4.0.0-beta release: https://twitter.com/oas_generator/status/1079727020374806529.

Happy New Year and looking forward to more collaboration and contributions in 2019!

**Pull request merged**
