### PR TITLE
[BUG] [C++][Pistache] cpp-pistache-server generating API include unde…

### PR DESCRIPTION
**Pull request by mlebihan**
…fined "Object.h" (#2769)

Should handle Object.h, AnyType.h correctly. Set.h also tested.

   - #include Object.h removed and replaced by a typeMapping.put(object, nlohmann::json) like suggested in other issues
   - object had an invalid syntax: ':' instead of '::' in types with namespace
   - extra include of #include nlohmann/json.h removed when there's already #include <nlohmann/json.hpp>
   - nlohmann::json is excluded from model namespace

Tested with custom petstore played, with suggested openapi specs coming from issues #2769, #10266, #14234

   ```bash
   rm -rf samples/server/petstore/cpp-pistache-everything/ && ./bin/generate-samples.sh ./bin/configs/cpp-pistache-server-cpp-pistache-everything.yaml  && cd samples/server/petstore/cpp-pistache-everything/ && mkdir build && cd build && cmake .. && cmake --build . --parallel
   ```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR.

suggestion (optional): what about adding a github work under ./github/worfklows to test `samples/server/petstore/cpp-pistache-everything` to ensure the output compiles? (or do it in another PR instead)

**Comment by wing328** [comment]
please commit the new files in samples/server/petstore/cpp-pistache-everything/  when you've time

**Comment by mlebihan** [comment]
- I've sent the content of `samples/server/petstore/cpp-pistache-everything`.

- I didn't find a `cpp-pistache` workflow in the `.github/workflows` folder to take it for example to create a workflow for `cpp-pistache-everything`. If would be safer if I can start from it.

But they are others issues to correct in the C++ pistache generator, and I continue correcting them using `samples/server/petstore/cpp-pistache-everything` for that. I wish its yaml to carry the most different declarations it can.

As soon I will have enough knowledge to declare a workflow for it, I will, when submitting a next PR.

**Comment by wing328** [comment]
please update the new sample one more time: https://github.com/OpenAPITools/openapi-generator/actions/runs/8933887779/job/24547007194?pr=18553

**Comment by mlebihan** [comment]
`./bin/utils/ensure-up-to-date`  returns "_Git working tree is clean_" locally now.

**Comment by wing328** [comment]
thanks for the PR. let's give it a try

**Pull request merged**
