### PR TITLE
fix: improve inline objects naming by adding the path to the name

### LINKED ISSUE #4399: [REQ] Name inline object types based on context instead of `InlineResponseDefault*`
### Is your feature request related to a problem? Please describe.

When, using the `jaxrs-cxf-client` generator, an OpenApi specification has inline definition for a request / response type a Java class name is generated based on an ordinal number. Example:
```
    public InlineResponseDefault22 doSomethingAwesome(InlineObject21 body);
```

## Describe the solution you'd like

I'd like inline objects to be named based on context (the `operationId` or endpoint name) prefixed with their function like `DoSomethingAwesomeRequest` instead of `InlineObject21` and `DoSomethingAwesomeResponseOK` instead of `InlineObject21`.

## Describe alternatives you've considered

Anything predictable would be fine, because the current method breaks any references if the API gets some additions (even endpoints added - a non-breaking change - can move ordinal numbers around).

## Additional context

Generally I want the code generation repeated any time (to follow upstream API changes). If existing references to `InlineObject21` break, updating will be an hurdle.

### PR DESCRIPTION
**Pull request by simllll**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Right now all InlineObjects are just named InlineObject1,2,3... this improves the naming for the requestBody and response where this happens the most (at least in our setup). In case there is no title, it adds the current path to the inline object. This improves the output a lot and also ensures more consistency between api client generations. Everytime there is a new endpoint, the inline object enumration was different, now it stays consistent, regardless if there is an endpoint added, modified or removed.

fixes #4399

This apparoch could probably applied to more places where resolveModelName is used.

### CODE REVIEW

**Comment by wing328** [comment]
FYI. We're working on refactoring the inline model resolver and will take this PR into consideration.

(still our recommended approach is to use `title` for complete control of the model name)

**Comment by simllll** [comment]
@wing328 With this change, a lot of client files get regenerated and also renamed. I tried to clean (remove) the samples directory and re-generate all clients, but then a lot of files actually get changed that are unrelated (e.g. opennapi-generator-ignore and package.jsons etc..), also some files are not re-generated at all? What's the best way to approach this?

**Comment by wing328** [comment]
@simllll I suggest you put this PR on hold for the time being until we review and decide the naming strategy of the inline model as part of the upcoming 6.0.0 release. Thanks again for the PR.

**Comment by simllll** [comment]
Thanks for the response,
The problem is I also I have no influcience on the yaml files, therefore I have no full control over the "title".

Just saw your comment, I good, I will rebase it so that the changes are easier to say and drop the regeneration of clients for now. Thanks for your work, let me know If I can do anything to get this changes pushed forward :)

**Comment by wing328** [comment]
@simllll I got that answer/reply a lot. My suggestion is to give it a try by asking them (the owner) to update the spec (yaml/json) file accordingly.

No matter what naming strategy we come up with, it won't meet everyone's requirement.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/12237 to allow users mapping inline schema name to whatever they want. Can you please review and let us know if you've any feedback?

**Comment by wing328** [comment]
Please pull the latest master as there's been a few enhancements related to the inline model resolver

**Comment by simllll** [comment]
Thanks @wing328 , haven'tn seen your comments till today. Just stumpled upon the same issue again, will look into it. But my first guess is that it will not really resolve my issue if I have to specify the mapping manually?
The issue is that the content of e.g. "inline_object_2" is completey different with a new version of swagger file. So first it's e.g. bird, second time it's cat. My approach uses the real context of it, which would solve the issue of reassigning a "new" name ot the generated class/file each time.

**Comment by simllll** [comment]
Interesting, just update dto 6.0.1 ..didn't change any paramteres: but naming is now waaaaayyy better :) So seems to work for me!

**Pull request closed without merging**
