### PR TITLE
[Go] Allow to use custom middleware

### PR DESCRIPTION
**Pull request by kuskoman**
This is a PR in response to my issue #7390. I need a way to create a custom authentication method (which is specific to a single cloud provider), however current code seems to make modifications to auth methods pretty hard (at least I did not find a way to provide custom header with dynamic value).
In this PR I allowed to do pretty much everything with http request, since I considered it an easy way to provide as many integrations as possible.

Since I am not sure if it's the expected way to fix these issues and I ran into some problems compiling this library I did not run all required scripts, but I am willing to once somebody approves the direction of proposed changes.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@antihax @grokify @kemokemo @bkabrda

### CODE REVIEW

**Comment by wing328** [comment]
> I need a way to create a custom authentication method (which is specific to a single cloud provider)

Which cloud provider is that?

There's an option to generate AWS v4 signature: `withAWSV4Signature`

**Comment by kuskoman** [comment]
@wing328 [HyperOne](https://www.hyperone.com/)
Basically I need to generate JWT using data from file every time I am trying to make request

**Comment by ad-m** [comment]
Tests for this PR are currently pass. What can we do to move forward this PR?

**Comment by fredericosilva** [comment]
@kuskoman could you squash it? it will simplify the review process :)

**Comment by ad-m** [comment]
@houqp I have notice that your recently changed files affted by this PR. Could you provide any comments and review for that PR?

**Review by houqp — APPROVED** [review]
LGTM

**Review by FilipZajdel — APPROVED** [review]
It seems OK to me.

**Review by Galatros — APPROVED** [review]
In my opinion it's ok.

**Comment by wing328** [comment]
Thanks for all the review. The PR has been merged.

**Pull request merged**
