### PR TITLE
[rust][codegen] Add support for the  `chrono`, `url`, `uuid` crates in the 'rust' generator.

### PR DESCRIPTION
**Pull request by aspenluxxxy**
Add support for the [chrono](https://crates.io/crates/chrono), [url](https://crates.io/crates/url), and [uuid](https://crates.io/crates/uuid) crates in the `rust` codegen.

* `DateTime` and `date` are mapped to `chrono::DateTime<Utc>` and `chrono::Date<Utc>`, respectively.
* `UUID` is mapped to `UUID:Uuid`.
* `URI` is mapped to `URL::Url`.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)

### CODE REVIEW

**Comment by aspenluxxxy** [comment]
Dunno what happened with CircleCLI?

**Comment by wing328** [comment]
Just pushed https://github.com/OpenAPITools/openapi-generator/pull/7368/commits/9fba28fdb396ec3a91f141c3acfe1e973e377f83. Let's see if that fixes the CI failure.

**Comment by aspenluxxxy** [comment]
Thanks. Although I would like to do some revisions on this, but would they best wait til after this PC?

Such as changing the options to something like `time=chrono`/`time=std`, `uuid=string`/`uuid=uuid-crate`, `url=string`/`url=uri-crate`, and maybe stuff like `bytes=vec`/`bytes=bytes-crate`?

**Comment by wing328** [comment]
@aspenluxxxy thanks for the PR. The type mapping setting can be overridden/changed via `typeMappings` or `--type-mappings` options. Have you tried that?

Ref: https://openapi-generator.tech/docs/usage/#type-mappings-and-import-mappings

**Comment by aspenluxxxy** [comment]
Hm, how would I add multiple type mappings, in a JSON file passed to `-c`?

**Comment by wing328** [comment]
Please try something like `--type-mappings=A=B,C=D,E=F` to map multiple type

For uuid, URL, I think we can update the default mapping in Rust client generator directly. Please feel free to submit a new PR or update this PR.

**Comment by aspenluxxxy** [comment]
type-mappings worked, thanks!

**Pull request closed without merging**
