### PR TITLE
Skip model generation if it's a top-level map or array

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Skip model generation if it's a top-level "additionalProperties' (an alias to "additionalProperties")

Closes https://github.com/OpenAPITools/openapi-generator/issues/391

cc @OpenAPITools/generator-core-team

### CODE REVIEW

**Comment by etherealjoy** [comment]
@wing328 
It worked very well apparently.
This issue #922 is solved in this case
But it generated the inline ref to array model as `AmfUpdateEventSubscriptionItem_inner` and the following log is generated
```
[main] INFO  o.o.codegen.DefaultGenerator - Model AmfUpdateEventSubscriptionItem not 
generated since it's an alias to array (without property)
```
I think here is a matter of choice how we want to do for alias, if we use `refname` or `inner`

However it does apply this behavior when the alias is part of a model like here #1251

We can do this as a next steps.
Thanks a lot of the update.

**Comment by wing328** [comment]
@etherealjoy thanks for the review.

cc @OpenAPITools/generator-core-team

**Comment by etherealjoy** [comment]
Fixes #397/#922

**Comment by etherealjoy** [comment]
I have a regression here with #391 :(
go client does not build.

**Comment by wing328** [comment]
@etherealjoy I'll take a look tomorrow to see if I can hunt down the bugs

**Comment by etherealjoy** [comment]
I will test it and let you know

**Comment by etherealjoy** [comment]
Fixes #397 #391

**Comment by etherealjoy** [comment]
@wing328 
Also solves #397 #922

**Comment by wing328** [comment]
I pushed another fix and got the following (different) code snippet for `fromJson` method when using the spec in #1273 
```cpp
void UeContext::fromJson(const nlohmann::json& val)
{
    {
        m_Groups.clear();
        if(val.find("groups") != val.end())
        {
            for( auto& item : val["groups"] )
            {
                m_Groups.push_back(item);

            }
        }
    }

}
```

Please give it another try when you've time.

**Comment by etherealjoy** [comment]
@wing328 
This is nice, I compiled it successfully.

**Comment by trenneman** [comment]
Fixes #1465 as well!

**Comment by wing328** [comment]
If no further feedback on this PR, I'll merge this on coming Monday.

**Comment by CyrilleBenard** [comment]
> 
> 
> I pushed another fix and got the following (different) code snippet for `fromJson` method when using the spec in #1273
> 
> ```c++
> void UeContext::fromJson(const nlohmann::json& val)
> {
>     {
>         m_Groups.clear();
>         if(val.find("groups") != val.end())
>         {
>             for( auto& item : val["groups"] )
>             {
>                 m_Groups.push_back(item);
> 
>             }
>         }
>     }
> 
> }
> ```
> 
> Please give it another try when you've time.

I still got this kind of wrong generated code with current master (3.3.4) :/

**Comment by etherealjoy** [comment]
This is correct
```
std::vector<std::string> m_Groups;

m_Groups.clear();
if(val.find("groups") != val.end())
{
      for( auto& item : val["groups"] )
      {
            m_Groups.push_back(item);         
      }
}
```

```yaml
    UeContext:
      type: object
      properties:
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupId'

    GroupId:
      type: string
```

**Comment by CyrilleBenard** [comment]
Oh sorry I omitted _m_Groups_ was a _string_. I got the same kind of issue when _m_Groups_ is a type defined by a model class. I'm going to reproduce the issue in a small context usage and will open another bug issue.

**Comment by etherealjoy** [comment]
@CyrilleBenard 
OK, please do.
Could just then be specific to the generator.

**Pull request merged**
