### PR TITLE
[Rust] Add support for reqwest-middleware when using reqwest

### PR DESCRIPTION
**Pull request by whirm**
Add support for [reqwest-middleware](https://github.com/TrueLayer/reqwest-middleware) (only when async support is enabled). 

With this, one can easily add middleware which add features like tracing or retries to the client requests:

```rust
use petstore_async::apis::configuration::Configuration;
use reqwest::Identity;
use reqwest_middleware::ClientBuilder;
use reqwest_tracing::TracingMiddleware;

let config = Configuration {
        client: ClientBuilder::new(reqwest::ClientBuilder::new().build()?)
            .with(TracingMiddleware::default())
            .build(),
        ..Configuration::default()      
    }
```

Not sure if this would be considered a breaking change or not as it changes the Configuration struct signature. Let me know if I need to retarget the PR.

@frol,  @farcaller,  @richardwhiuk, @paladinzh,  @jacob-pro: Pinging you as requested on the PR template :)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by jacob-pro** [comment]
I'm a little bit concerned about making this a mandatory extra dependency - especially a crate which appears relatively new / small in popularity...

What do you think about putting this behind an optional feature flag instead?

**Comment by whirm** [comment]
Fair enough. I'll give it a shot.

**Comment by whirm** [comment]
@jacob-pro I'd say it's ready now.

**Comment by jacob-pro** [comment]
Looks good to me 👍  - @wing328 should be able to review ?

**Comment by wing328** [comment]
The build is successful locally:

```
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.11
   Compiling reqwest-middleware v0.1.6
   Compiling petstore-reqwest-async-middleware v1.0.0 (/Users/williamcheng/Code/openapi-generator4/samples/client/petstore/rust/reqwest/petstore-async-middleware)
warning: unused variable: `file`
   --> reqwest/petstore-async-middleware/src/apis/pet_api.rs:507:9
    |
507 |     let file = params.file;
    |         ^^^^ help: if this is intentional, prefix it with an underscore: `_file`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: `petstore-reqwest-async-middleware` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 5m 53s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:56 min
[INFO] Finished at: 2022-11-11T18:16:30+08:00
[INFO] ------------------------------------------------------------------------
```

Will try to add tests to the CI in a separate PR.

Thanks again for the enhancement.

**Comment by wing328** [comment]
FYI. I've filed https://github.com/OpenAPITools/openapi-generator/pull/13990 to add tests in CI.

**Pull request merged**
