### PR TITLE
[csharp] use full qualified name to fix cases where generated code doesn't build

### LINKED ISSUE #16123: [BUG][C#] Should use fully-qualified class name for models
##### Description

I have exactly the same issue as this: https://stackoverflow.com/questions/59692538/ambiguous-reference-error-in-openapi-generated-c-sharp-code

I have a model class called Environment and using the csharp-netcore generator this causes compile errors due to the ambiguous reference.

I could not see this listed as a bug for OpenAPI Generator.

There is an open issue for Swagger codegen https://github.com/swagger-api/swagger-codegen/issues/2630 as mentioned.

Error is:

Api\EnvironmentApi.cs(1053,173): error CS0104: 'Environment' is an ambiguous reference between 'Org.OpenAPITools.Model.Environment' and 'System.Environment'

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "CloudData",
    "version": "1.0"
  },
  "paths": {
    "/api/v1/environments": {
      "get": {
        "tags": [
          "Environment"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Environment"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Environment"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Environment"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Environment"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Environment"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Environment"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Environment"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Environment"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Environment"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Environment"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/environments/{id}": {
      "get": {
        "tags": [
          "Environment"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Environment"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Environment"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Environment"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Environment"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Environment"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/Environment"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/Environment"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      },
      "delete": {
        "tags": [
          "Environment"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Environment": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "name": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "apiKey",
        "description": "JWT Token issued for your account using Bearer scheme.",
        "name": "Authorization",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "Bearer": [ ]
    }
  ]
}
```

##### Generation Details

npm i @openapitools/openapi-generator-cli
npx openapi-generator-cli generate -i swagger.json -g csharp-netcore -o output

##### Steps to reproduce

cd output
dotnet build

##### Related issues/PRs

https://stackoverflow.com/questions/59692538/ambiguous-reference-error-in-openapi-generated-c-sharp-code
https://github.com/swagger-api/swagger-codegen/issues/2630

##### Suggest a fix

C# generator should be changed to use fully qualified class names.

### PR DESCRIPTION
**Pull request by gturri**
This fixes #16123

The issue is that when a spec defines an entity with a name like `TimeZone`, the generated code does not build because it yields an ambiguous reference to either our entity or `System.TimeZone`.
That commit fixes it by adding the namespace in front of the entity name.
However, it adds the suffix only if need, ie: if we consider that the http call will return an `Object` or a `string`, then adding our package namespace would break the generated code. That commit hence ensures it does not do that.

To test this patch I:

* created that spec file

```
openapi: 3.0.3
info:
 title: test
 version: v0.1
 description: test
paths:
 /api/path1: # This path makes sure we fix our issue, because it would yield C# code that does not build without this commit
  get:
   responses:
    '200':
      description: ok
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/TimeZone'
 /api/path2: # This path leads to C# code that manipulates an Object. This ensure I don't break support of that case.
  get:
   responses:
    '200':
      description: ok
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/ObjectIsh'
 /api/path3: # This path leads to C# code that manipulates a string. This ensure I don't break support of that case.
  get:
   responses:
    '200':
      description: ok
      content:
       application/json:
        schema:
         $ref: '#/components/schemas/StringIsh'
components:
  schemas:
   TimeZone:
    type: object
    properties:
      someField:
       type: array
       items:
         type: string
   ObjectIsh:
    type: object
   StringIsh:
    type: string
```

I then generate C# code from this spec:

    java -jar openapi-generator-cli.jar generate --generator-name csharp --input-spec spec.yaml --output out

and then I build the generated code:

    dotnet build Org.OpenAPITools.sln

Expected behavior: the C# build is successful.
Actual behavior: without this commit the build fails. With this commit it succeeds

Ping @mandrean , @shibayan , @Blackclaws , @lucamazzanti , @muttleyxd 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by gturri** [comment]
ok, non regression checks show I missed the case where an endpoint returns a List. I'm looking into it.

**Comment by gturri** [comment]
bam, all green this time

**Comment by devhl-labs** [comment]
I think any generated code should only be using fully qualified references to avoid collisions, though I am not sure directly changing the return type is the way to do it. I also addressed this but abandoned that PR after comments. Here was the PR I sent previously. https://github.com/OpenAPITools/openapi-generator/pull/16178

**Comment by gturri** [comment]
It's true that I'm only addressing the case of the return types (because it's what I encountered) and that using fully qualified names more generally would be even better.

Thanks for the link to your PR. 
I'm not sure I understand: why was it abandoned?

I mean: I just had a quick look and I'm not sure I completely understand the patch (in particular I'm not sure I understand the introduction of `x-fully-qualified-return-type"`, but I guess it's a detail: if it was a more general fix, what were the reasons to not merge it?

**Comment by gturri** [comment]
Closing because according to the recent comments on https://github.com/OpenAPITools/openapi-generator/issues/16123 it is not something that will be accepted

**Pull request closed without merging**
