### PR TITLE
Update swift samples

### PR DESCRIPTION
**Pull request by d-date**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

Update swift3 / swift4 samples to pass CI.

Before merge this PR, we should fix codegen to adopt Swift method syntax. This violation cause compile error.
- [x] Swift method should be started with lower case or under score, not started with number literal.

### CODE REVIEW

**Comment by d-date** [comment]
@wing328 Could you check my comment first and try to fix it?

>  Swift method should be started with lower case or under score, not started with number literal.

**Comment by wing328** [comment]
> @wing328 Could you check my comment first and try to fix it?

Sure let me look into that

**Comment by wing328** [comment]
@d-date I've pushed https://github.com/OpenAPITools/openapi-generator/pull/738/commits/265a2b805d9f08993375f8bb8f8e3d1ed250409c to address that. Please take a look.

**Comment by d-date** [comment]
@wing328 You can merge it after passing CI

**Comment by wing328** [comment]
@d-date thanks. I'll take another look tomorrow.

**Pull request merged**
