### PR TITLE
PR for ability to easily debug newly created codegen classes.

### PR DESCRIPTION
**Pull request by jason-henriksen**
### PR checklist

- [ X ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ X ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ X ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ N/A ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Adds a unit test to the meta command generated code.  Running that unit test under the debugger causes the cli code to be run under the debugger which makes the debug experience of working on a new codegen library much easier to work with and enhance.

### CODE REVIEW

**Comment by jason-henriksen** [comment]
OK.  I think I'm doing something wrong where I need to update the target samples with the new code so that the uncommitted changes thing doesn't flag.  Originally, I thought I wasn't supposed to commit the generated sample code.   I'll take another stab at this soon.

**Comment by jason-henriksen** [comment]
This PR addresses the issue:  https://github.com/OpenAPITools/openapi-generator/issues/2222

It is also a fixed attempt at the work in this PR: https://github.com/OpenAPITools/openapi-generator/pull/2221
( 2221 is the same thing, so it could be closed. )

**Comment by jason-henriksen** [comment]
@jimschubert @ackintosh 
For your review.   Thank you for taking a look at it.
- Jason

**Comment by ackintosh** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/2388/commits/bb8472c46d820d7ecadf532c31a67d6db595dd82
Yes, it was the reason why CI failed. 👍

**Comment by jimschubert** [comment]
@jason-henriksen thank you for this contribution, which will help to improve the workflow for the community!

**Pull request merged**
