### PR TITLE
[swift4] update Alamofire from 4.7.0 to 4.9.0

### PR DESCRIPTION
**Pull request by 4brunu**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

According to the last checkbox I think I should tag you, sorry if I'm wrong, first contribution...
@jgavris @ehyche @Edubits @jaz-ah @d-date

This PR fixes https://github.com/OpenAPITools/openapi-generator/issues/2300 by updating the version of alomofire in podspec and cartfile.

### CODE REVIEW

**Comment by wing328** [comment]
@4brunu thanks for the PR. The CI failure is not related to this PR.

**Comment by wing328** [comment]
Tested locally and the tests passed:
```
DateFormatTests
    ✓ testCodableAlwaysResultsInUTCEncodedDate (0.079 seconds)
    ✓ testEncodeToJSONAlwaysResultsInUTCEncodedDate (0.001 seconds)
PetAPITests
    ✓ test1CreatePet (0.673 seconds)
    ✓ test2GetPet (0.391 seconds)
    ✓ test3DeletePet (0.318 seconds)
StoreAPITests
    ✓ test1PlaceOrder (0.336 seconds)
    ✓ test2GetOrder (0.353 seconds)
    ✓ test3DeleteOrder (0.338 seconds)
    ✓ testDownloadProgress (0.699 seconds)
UserAPITests
    ✓ testLogin (0.835 seconds)
    ✓ testLogout (0.333 seconds)
    ✓ testPathParamsAreEscaped (0.000 seconds)


Executed 12 tests, with 0 failures (0 unexpected) in 4.357 (4.362) seconds
2019-10-01 15:53:40.523 xcodebuild[8807:1726130] [MT] IDETestOperationsObserverDebug: 397.368 elapsed -- Testing started completed.
2019-10-01 15:53:40.523 xcodebuild[8807:1726130] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
2019-10-01 15:53:40.523 xcodebuild[8807:1726130] [MT] IDETestOperationsObserverDebug: 397.368 sec, +397.368 sec -- end
▸ Test execute Succeeded
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

```

**Comment by wing328** [comment]
I'll run swiftlint in another PR to reformat the code.

**Comment by wing328** [comment]
@4brunu thanks for the PR. Given that my local test result is good, let's go with what you've changed so far.

**Comment by wing328** [comment]
@4brunu if you plan to submit more PRs for Swift, please install swiftlint locally in your machine.

ref: https://github.com/realm/SwiftLint

**Comment by 4brunu** [comment]
@wing328 thanks 👍

**Pull request merged**
