### PR TITLE
Get Response Content examples

### LINKED ISSUE #14169: [BUG] Examples defined in Response Content are not available
##### Description

During the code generation the `examples` from the Response Content are ignored:

```yaml
        '201':
          description: 'Created OK'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/coordinates'
              examples:
                Example Amsterdam coordinates:
                  value:
                    lat: 52.377956
                    long: 4.897070
```

In the file above the `Example Amsterdam coordinates` is not made available to the Mustache templates

##### openapi-generator version

v6.3.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by gcatanese**
Fix #14169

This PR makes sure the `examples` defined in Response Content are made available to the Mustache templates

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by superplan** [comment]
Does this fix also work for arrays? Here is an example which maybe can be added to a unit test:

```yaml
responses:
  '200':
    description: Successful response
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
            required:
              - stringProperty
              - booleanProperty
            properties:
              stringProperty:
                type: string
                description: key
              booleanProperty:
                type: boolean
                description: value
          example:
            - stringProperty: "foo"
              booleanProperty: true
            - stringProperty: "bar"
              booleanProperty: false
```

**Comment by gcatanese** [comment]
> Does this fix also work for arrays? Here is an example which maybe can be added to a unit test:
> 
> ```yaml
> responses:
>   '200':
>     description: Successful response
>     content:
>       application/json:
>         schema:
>           type: array
>           items:
>             type: object
>             required:
>               - stringProperty
>               - booleanProperty
>             properties:
>               stringProperty:
>                 type: string
>                 description: key
>               booleanProperty:
>                 type: boolean
>                 description: value
>           example:
>             - stringProperty: "foo"
>               booleanProperty: true
>             - stringProperty: "bar"
>               booleanProperty: false
> ```

Thanks @superplan for the input. I have only fixed the issue when `examples` (multiple) are defined but not picked up. I was waiting for feedback from the maintainers on this PR before addressing other scenarios (like array).

**Comment by superplan** [comment]
That sounds good! 
Just a short notice, I don't mean to digress: for array objects examples are not picked up at all, at least not in Java-Spring. Your solution might actually be the basis to also fix this array problem. So far I only tried to modify the mustache templates by using the `@ExampleObject`-Annotation, but it didn't work. Maybe this is due to CodegenMediaType.examples? I'm also eager to her from the maintainers with regards to your PR!

**Comment by wing328** [comment]
please merge the latest master to this branch to resolve the merge conflicts.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team as the changes impact default codegen, etc

**Comment by gcatanese** [comment]
@wing328 @superplan Closing as it is superseded by PR #14336 14336

**Pull request closed without merging**
