### PR TITLE
[Rust] Derive more traits

### PR DESCRIPTION
**Pull request by borsboom**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This adds some common standard traits to the generated models:

* For structs and complex enums, adds `Clone`.
* For simple enums, adds `Clone`, `Copy`, `Eq`, `Ord`, `PartialOrd`, `Hash`.

These end up coming in really handy for client code.

/cc @frol @farcaller @bjgill @richardwhiuk

### CODE REVIEW

**Comment by bjgill** [comment]
I've not looked closely, but does this work when the enum contains `f64` or similar that doesn't work with `Ord` or `Eq`?

**Comment by borsboom** [comment]
I don't believe the "simple" enums that get these traits will ever contain other types.  The enum values are generated as
```
#[serde(rename = "{{{value}}}")]
{{name}},
```
so these are just a simple list of names that don't contain anything else.

**Comment by bcourtine** [comment]
I agree that having "Cloneable" models can be usefull.

I often add the derivation after generating client code.

**Comment by wing328** [comment]
CircleCI failure not related to this PR.

**Comment by wing328** [comment]
@borsboom Looks like there's no further feedback. Thanks for the PR.

**Comment by wing328** [comment]
@borsboom thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Comment by Snazzie** [comment]
Eq and Hash doesnt get generated anymore.

**Pull request merged**
