### PR TITLE
upgrade okhttp-gson and google-api-client to junit5

### PR DESCRIPTION
**Pull request by thorstenhirsch**
PR for okhttp-gson and google-api-client of #18470

### CODE REVIEW

**Comment by thorstenhirsch** [comment]
This error is http://petstore.swagger.io/ blocking circle-ci again.

**Comment by wing328** [comment]
i've restarted the job. let's see how that goes

(circleci uses a local petstore server with updated host table in the vm)

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/9009746571/job/24758770345?pr=18618

please update samples too.

**Comment by wing328** [comment]
please have a look at https://github.com/OpenAPITools/openapi-generator/actions/runs/9019579968/job/24782776638?pr=18618 when you've time

**Comment by wing328** [comment]
merged via https://github.com/OpenAPITools/openapi-generator/pull/18668 instead

**Pull request closed without merging**
