### PR TITLE
[BUG] C# Aspnetcore Adding Name property for header parameters

### PR DESCRIPTION
**Pull request by lance-yuan-igt**
This defect is similar to https://github.com/OpenAPITools/openapi-generator/pull/8826. https://github.com/OpenAPITools/openapi-generator/pull/8826 fixed for path and form parameters in the aspnetcore generator not having the Name= Property set on the attributes but missed header parameters. Missing those results in errors when generating server code from specs that have parameters with underscores or hyphens in their header name.

This PR address the issue #16275 
I have tested the fix locally and now the header parameters can have hyphens or underscores and they will be correctly mapped to the Action methods

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. can you please follow step 3 in the PR checklist to update the samples so that the CI can verify the change?

https://github.com/OpenAPITools/openapi-generator/actions/runs/5915988919/job/16073256078?pr=16360

**Comment by lance-yuan-igt** [comment]
Sorry for not following the instructions completely. This is first time I make changes here.
I did run both scripts and committed/pushed the changes. There're more than 600 files changed, is that normal?

**Comment by wing328** [comment]
> There're more than 600 files changed, is that normal?

I don't think so. Are you using git bash?

I've pushed some commits to update samples and docs. All tests passed. Thanks for the PR.

**Comment by lance-yuan-igt** [comment]
Yes, I used git bash in Windows 10.
Thanks a lot for correcting them for me.

**Pull request merged**
