### PR TITLE
Add check for list size before attempting to set last element field value

### LINKED ISSUE #546: [Java][Spring] Server codegen gradle task fails when operation only has header parameters, and generator has implicitHeaders=true
##### Description

Gradle codegen task fails with IndexOutOfBoundException. This is caused when the generator task has the additional parameter of _implicitHeaders = true_ and the operation in the api yaml specification file only has header parameters.

##### openapi-generator version

3.0.3

##### OpenAPI gradle task specification (partial)
```yml
swagger: '2.0'
paths:
  /account-info:
    get:
      tags:
      - Account
      summary: Get the account information
      operationId: getAccountInfo
      parameters:
      # HEADERS
      - $ref: '#/parameters/userIdTokenHeaderParam'
      - $ref: '#/parameters/clientIdHeaderParam'
      - $ref: '#/parameters/languageHeaderParam'
      responses:
        200:
          description: Account Info
          schema:
            $ref: '#/definitions/Account'
          headers:
            cache-control:
              type: string
              description: Caching rules
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        403:
          $ref: '#/responses/Forbidden'
        500:
          $ref: '#/responses/UnexpectedError'
```

##### Gradle task specification for generation

```
openApiGenerate {
    ...
    generatorName = 'spring'
    additionalProperties = [
        ...
        'interfaceOnly'     : 'true',
        'java8'             : 'true',
        'delegatePattern'   : 'true',
        'implicitHeaders'   : 'true',
        'useTags'           : 'true',
//        'useOptional'       : 'true', // bug in codegen prevents using this with delegatePattern=true
//        'async'             : 'true', // Only use if necessary (defaults to CompletableFuture for java8, Future for java<8)
//        'responseWrapper'   : 'CompletableFuture',
    ]
}
```

##### Suggest a fix/enhancement

Add check for list size before setting last element value

Class: _org.openapitools.codegen.languages.SpringCodegen_
Original method:

```
private void removeHeadersFromAllParams(List<CodegenParameter> allParams) {
        if(allParams.isEmpty()){
            return;
        }
        final ArrayList<CodegenParameter> copy = new ArrayList<>(allParams);
        allParams.clear();

        for(CodegenParameter p : copy){
            if(!p.isHeaderParam){
                allParams.add(p);
            }
        }
        allParams.get(allParams.size()-1).hasMore =false;
    }
```

Suggested fix:
```
private void removeHeadersFromAllParams(List<CodegenParameter> allParams) {
        if(allParams.isEmpty()){
            return;
        }
        final ArrayList<CodegenParameter> copy = new ArrayList<>(allParams);
        allParams.clear();

        for(CodegenParameter p : copy){
            if(!p.isHeaderParam){
                allParams.add(p);
            }
        }
        if (!allParams.isEmpty()) {
            allParams.get(allParams.size()-1).hasMore =false;
        }
    }
```

### PR DESCRIPTION
**Pull request by jason-cohen**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

fix #546 

FYI @JFCote

### CODE REVIEW

**Comment by jason-cohen** [comment]
Shippable error doesn't seem to be related to the PR:
```[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.15.v20160210:start (start-jetty) on project spring-mvc-j8-localdatetime: Failure: ShutdownMonitorThread already started -> [Help 1]```

**Comment by wing328** [comment]
@jason-cohen yup, it's not related.

**Comment by wing328** [comment]
@jason-cohen thanks for the fix, which has been merged into master.

**Comment by JFCote** [comment]
@jason-cohen Thanks for your contribution!

**Pull request merged**
