### PR TITLE
Added jackson as supported serialization library for retrofit2

### PR DESCRIPTION
**Pull request by gf-smtzgr**
To close #7435 

This adds support for jackson as serialization library to the retrofit2 java generator. Basically this seems already mostly supported by the general java classes/templates as an option. Apparently it is just explicitly excluded and lacks the jackson configuration example file. This PR adds the file (copied from variants that already support jackson) and otherwise relies on the java model files already supporting this option. Usage of jackson should only be a question of setting serialzationLibrary to jackson (e.g. in the maven config). 
Note: The steps below were executed but did not generate additional files to add. 
Note: I'm aware of the existing PR https://github.com/OpenAPITools/openapi-generator/pull/7435 . This PR basically provides equivalent functionality, but supports the standard option for jackson support and is based on the most recent master version. Therefore I assume that PR can be closed should this one be accepted.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks); 
  -> *master* as I assume support for an already existing configuration parameter is non-breaking. 
  **Note**: if you want to be pedantic you could consider it a breaking change as it can change behavior in the following scenario: If a project currently has jackson as serialization library configured with retrofit2 this would automatically be switched to gson and gson support would be generated. With this change the configuration of such a project would not be overridden, but instead jackson support would be generated now as configured; however, a project configuring jackson as serialization library and then relying on the fallback to gson seems misconfigured on the project's side in the first place. However, feel free to redirect the PR if you feel that level of change is not wanted in master branch.
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. Since this is a java targeting change: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @martin-mfg

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. I did a test with `java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/java2323 --library retrofit2 --additional-properties serializationLibrary=jackson` but the output won't compile, e.g. :

```
[ERROR]   location: class org.openapitools.client.model.User
[ERROR] /private/tmp/java/src/main/java/org/openapitools/client/model/User.java:[210,4] cannot find symbol
[ERROR]   symbol:   class JsonInclude
[ERROR]   location: class org.openapitools.client.model.User
```

Can you please take a look when you've time?

**Comment by gf-smtzgr** [comment]
Replicated the issue. Working on fixing the imports and the ApiClient template. I will let you know when I'm done or need assistance.

**Comment by wing328** [comment]
can you please resolve the merge conflicts when you've time?

**Comment by gf-smtzgr** [comment]
@wing328 Fixed the merge issues and updated the dependency handling. Note that the PR now also slightly changes the playws26 sample: It removes some gson dependencies (those seem unused to me, at least I could compile the generated sample) and shifts the others a bit around. the playws26 support already included jackson but now the respective dependencies are grouped together and controlled separately with the "jackson" flag. Please take a look whether this is acceptable now - assuming the test pipelines run through.

**Comment by wing328** [comment]
can you please resolve it one more time and PM me via Slack when it's done?

thanks again for the PR.

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by gf-smtzgr** [comment]
I just pushed a fix for the issues introduce with the merge. That should also solve what you noticed. And sorry, but have no Slack account yet.

**Comment by wing328** [comment]
I tested with both gson and jackson serialization library. mvn works fine but gradle build results in error in both tests.

Can you please take a look when you've time?

**Comment by gf-smtzgr** [comment]
Ah, sorry, not very familiar with gradle and didn't try that. I've updated the gradle dependencies to match the last changes I did to the maven ones. Now retrofit2 example compiles for me via gradle both with jackson and with the default. However this adds the jackson-databind dependency and the javax.ws.rs:javax.ws.rs-api dependency in some of the retrofit/play gradle projects where they were apparently not needed before and I'm not sure why (perhaps some other dependency brought them along there?)

**Comment by gf-smtzgr** [comment]
I tried to compile the other affected samples and most of them do compile, except for retrofit2-play26 - where I get this error
```
> Task :compileJava FAILED
/home/smetzger/dev/openapi-generator-my-fork/samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/Play26CallFactory.java:138: error: method does not override or implement a method from a supertype
        @Override
        ^
Note: /home/smetzger/dev/openapi-generator-my-fork/samples/client/petstore/java/retrofit2-play26/src/main/java/org/openapitools/client/Play26CallFactory.java uses or overrides a deprecated API.
```
but that occurs with or without my change and seems to refer to the 'Call' parent class. So that sample might be outdated with regard to the retrofit Call class in general?

**Comment by gf-smtzgr** [comment]
Tried the same sample on master branch and get the same error so that's likely an issue independent of this MR... (could also be my jvm, not sure which you use for the tests) let me know if you disagree or anything else needs addressing.

**Pull request merged**
