### PR TITLE
[K6] Enhancement: Make operationId accessible inside requests

### PR DESCRIPTION
**Pull request by JasonMejane**
- Add the operationId to the request to make it accessible in template in K6ClientGenerator.java
- Add example in comment in script.mustache

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Visiblity @mostafa

### CODE REVIEW

**Comment by agilob** [comment]
What does it do?

No changes in the sample project?

**Comment by mostafa** [comment]
Hey @JasonMejane,

thanks for your contribution! Please update the example test script by regenerating the samples, as also mentioned by @agilob.

**Comment by JasonMejane** [comment]
@mostafa @agilob I updated the sample script, thanks for pointing it out :)

The operationId is really helpful to create named functions in a client, instead of groups. So this change helps ones who would like to use their own template instead of the default one to generate a client, whitout the need to create a custom k6 client, providing the operationId to be used if needed.

**Comment by mostafa** [comment]
@JasonMejane Perfect! Thank you. 🙏

**Pull request merged**
