### PR TITLE
[C][Client] Use int* as int or bool type function parameter

### PR DESCRIPTION
**Pull request by ityuhui**
@wing328 @zhemant (2018/11) @michelealbano (2020/03)

As discusseded in https://github.com/kubernetes-client/c/issues/209, this PR uses `int*` as int or bool type function parameter.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ityuhui** [comment]
@wing328 
Since no one objects to this change, can you merge this PR ?
The change will be tested/used by kubernetes C client. So if it breaks some feature, we can find it soon.

**Comment by zhemant** [comment]
Hi @ityuhui ,
Sorry for late reply.
I only see changes to api files and not in model files. Do I see this correct? I believe if we are making these changes then they should be for complete client even for model. Because the error that you are facing is true in the case of the model as well.

**Comment by ityuhui** [comment]
Yes. This PR only changes api files.

Actually they (api files and model files) are different problems although the solution is same (use `int *` for `int` or `boolean` data types).

This PR only changes "query parameters" in HTTP request header.  It does not relate with any model and will resovle the problem of sending request. e.g. https://github.com/kubernetes-client/c/issues/209

For issues related to model files such as https://github.com/kubernetes-client/c/issues/193 (Fetch some models from API server), I will provide another PR next to create/remove `int/boolean` fields in models.

**Comment by wing328** [comment]
let's try with what you'e so far.

**Pull request merged**
