### PR TITLE
[codegen] Fix 'super.HashCode' for oneOf and allOf Implementations

### PR DESCRIPTION
**Pull request by jburgess**
This fixes various client and server generators which use `allOf` and `discriminator` patterns as identified in https://github.com/OpenAPITools/openapi-generator/issues/5587

This error occurs as the `hasVars` boolean is not set for models which contain extension patterns. This fix simply sets the boolean at the end of code generation bases on the existence of variables after post-processing these special object types.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608  @bkabrda

### CODE REVIEW

**Comment by jburgess** [comment]
@wing328 I am hoping you can provide a recommendation. This PR consists of a one line change to the `DefaultCodegen.java`. I ran the `run_all_petstore` from the PR checklist and this added a slew of changes to this PR. These all appear to be related to the version bump from 4.3.0-SNAPSHOT to 4.3.1-SNAPSHOT. I would have expected these changes to already be present. Can you provide a recommendation to slim down this PR to only the relevant changes? Thanks in advance!

**Comment by wing328** [comment]
@jburgess please revert the changes related to run-all-petstore script as it should be run by the CIs only.

Please run `./bin/utils/ensure-up-to-date` instead.

**Comment by wing328** [comment]
Looks like you're including commits not authored by you in this PR (due to rebase?)

I would suggest you file a new PR from the latest master instead.

**Comment by jburgess** [comment]
Thanks @wing328. Opened https://github.com/OpenAPITools/openapi-generator/pull/5830

**Pull request closed without merging**
