### PR TITLE
[Java] use Files.createTempFile instead

### PR DESCRIPTION
**Pull request by wing328**
- use Files.createTempFile instead to avoid potential security issues.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

### CODE REVIEW

**Review by spacether — APPROVED** [review]
Looks good to me

**Comment by Sarangan0219** [comment]
Hi wing328, 

Currently we are using openapi-generator 4.3.1, and when downloading JAVA SDK for endpoints with PDF files, we couldn't observe any temporary files in `/tmp` or` var/tmp ` folder. Could you please tell me how we can reproduce this issue ?

**Comment by wing328** [comment]
please try the latest stable version v5.3.1 instead and open a new issue for tracking if you need help from the community.

**Comment by Sarangan0219** [comment]
yes with stable version v5.3.1 we have no issues. I just want to analyze this issue in my environment with the previous versions. Could you please let me know the steps to reproduce this in previous versions ?

**Comment by wing328** [comment]
the issue was reported by a user and he didn't provide details on how exactly he uncovered the issue.

**Pull request merged**
