### PR TITLE
[php-slim4] Follow PDS skeleton

### PR DESCRIPTION
**Pull request by ybelenko**
I don't like that `index.php` not in `public` folder. It's also great opportunity to follow [php-pds/skeleton](https://github.com/php-pds/skeleton) pattern.

I don't know where should be put generated source files, not in `bin` I think and neither in `src`. So I didn't change generated library files location for a time being(still in `lib` folder).

I've checked build locally, no errors.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

```console
$  composer test && composer phpcs
> phpunit
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

IIIIIIIIIIIIIIIIIIIIIIII.III.IIIIIII.IIIIIII.III.IIIIIIIII.....  63 / 112 ( 56%)
.................................................               112 / 112 (100%)

Time: 00:00.116, Memory: 8.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 112, Assertions: 137, Incomplete: 53.
> phpcs
........................... 27 / 27 (100%)


Time: 1.68 secs; Memory: 12MB
```

cc @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @renepardon

### CODE REVIEW

**Comment by ybelenko** [comment]
I've committed `tiny-cpp` generator changes for someone else since CI got complaints on this.

```console
16dc954b6f (HEAD -> php_slim4_pds_skeleton, origin/php_slim4_pds_skeleton) Fix CI missed tiny-cpp docs update
 docs/generators.md          | 1 +
 docs/generators/tiny-cpp.md | 2 +-
 2 files changed, 2 insertions(+), 1 deletion(-)
```

**Comment by ybelenko** [comment]
cc Slim4 team member @l0gicgate

App config will be changed significantly in coming PRs, do you have any suggestions about folders structure?

**Comment by ybelenko** [comment]
I have about 5 finished PRs to submit after this merge.

**Comment by ybelenko** [comment]
There was a merge conflict, so I've rebased on latest `master`. No real changes in the PR itself.

**Comment by ybelenko** [comment]
@wing328 It's just a folder relocation, can we proceed with this PR? `test` renamed to `tests` and `index.php` to `public/index.php`.

**Comment by wing328** [comment]
@ybelenko let's get this into the upcoming v5.3.0 (breaking changes with fallbacks) and get feedback from our users.

**Pull request merged**
