### PR TITLE
[cpp-restbed-server] Allow to implement validation of input data for enumerations

### PR DESCRIPTION
**Pull request by f18m**
This MR modifies the MODEL C++ source code to throw an exception whenever trying to set an unsupported enum value inside the model class, instead of silently dropping the set() command.

This is consistent with the usage for the c++ restbed server of Boost::ptree which already throws exceptions in case of invalid data type translations (see https://www.boost.org/doc/libs/1_74_0/boost/property_tree/exceptions.hpp)

With this MR the caller can detect invalid JSON/schema provided as input to the REST APIs just by catching std::runtime_error exceptions. A possible improvement would be introducing a custom class for such exceptions...

### CODE REVIEW

**Comment by f18m** [comment]
Ping on this PR...

**Comment by f18m** [comment]
Should I regen the petstore example files?

**Comment by f18m** [comment]
Hi @wing328 ,
Since you already handled the MR https://github.com/OpenAPITools/openapi-generator/pull/7679 about the restbed server can you have a look at this MR as well?
thanks!

**Comment by etherealjoy** [comment]
> Should I regen the petstore example files?
Do you have changes if you regen, if so please commit them too. Changes seems OK

**Comment by f18m** [comment]
> > Should I regen the petstore example files?
> 
> Do you have changes if you regen, if so please commit them too. Changes seems OK

done now!

**Comment by etherealjoy** [comment]
@stkrwork @etherealjoy @muttleyxd @ravinikam @MartinDelille

**Review by etherealjoy — APPROVED** [review]

**Review by muttleyxd — APPROVED** [review]

**Comment by etherealjoy** [comment]
@wing328

**Pull request merged**
