### PR TITLE
[WIP] Escape import with underscore in go-experimental client

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

https://github.com/OpenAPITools/openapi-generator/pull/3634 for go-experimental

cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07)

### CODE REVIEW

**Comment by wing328** [comment]
CircleCI failed with the following errors:
```
--- PASS: TestDeleteUser (0.00s)
PASS
ok  	_/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/go	0.514s
# _/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/go-experimental/go-petstore
go-petstore/api_fake.go:19:2: imported and not used: "reflect"
FAIL	_/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/go-experimental [build failed]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (go-test) on project GoExperimentalPetstore: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
```

**Comment by bkabrda** [comment]
Hmm, not sure where the `reflect` import is coming from. Let me have a look at that.

**Comment by bkabrda** [comment]
Right, the problem is that commit 94d4e0cfac90964b82962f74d9f320171a22e278 did the change in `AbstractGoCodegen.java` to add the `reflect` import and did the relevant changes in go templates, but not in go-experimental templates. So first you're going to have to do the same change in go-experimental client templates and then rebase this PR on top of this, that should make tests of this PR pass.

**Comment by wing328** [comment]
Ah ok. I completely forgot about that change. Let me sync it to go-experimental this weekend.

**Comment by wing328** [comment]
Done via https://github.com/OpenAPITools/openapi-generator/pull/3659/commits/570af49b0a728c9d1ba7ccf62e3ff1276afa21af

**Comment by wing328** [comment]
The Travis CI failure is not related to this PR

**Pull request merged**
