### PR TITLE
Generate fully qualified parameters in cpp-pistache-server (Fix #15078)

### LINKED ISSUE #15078: [BUG] Description
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The status parameter in the following specification is an enum string. It refers to the Status schema in the components section. The generated method for get_sessions is:

```C++
virtual void get_sessions(const std::optional<Status> &status, Pistache::Http::ResponseWriter &response) = 0;
```

While it is expected to be:

```C++
virtual void get_sessions(const std::optional<org::openapitools::server::model::Status> &status, Pistache::Http::ResponseWriter &response) = 0;
```

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Foo
  version: '1.0'
paths:
  /sessions:
    get:
      operationId: get_sessions
      parameters:
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/Status'
      responses:
        '200':
          description: OK
components:
  schemas:
    Status:
      type: string
      enum:
        - running
        - terminated
```

##### Generation Details

```bash
openapi-generator generate -g cpp-pistache-server -i foo.yaml
```

##### Suggest a fix

I think the following line should be changed to prepend the namespace to the data type:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java#L303

### PR DESCRIPTION
**Pull request by shayan-eftekhari**
By using param.getSchema().dataType instead of param.dataType, I made sure that the final generated code for query parameters are fully qualified. Examples:
- std::optional&lt;org::openapitools::server::model::Status&gt;
- std::optional&lt;std::vector&lt;std::string&gt;&gt;

Fix #15078
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@ravinikam @stkrwork @etherealjoy @martindelille @muttleyxd

### CODE REVIEW

**Comment by shayan-eftekhari** [comment]
Dear technical committee @ravinikam @stkrwork @etherealjoy @MartinDelille @muttleyxd ,

It seems one check is failed but I don't understand what's wrong. Could you please give me some hint?

**Comment by wing328** [comment]
@shayan-eftekhari thanks for the PR. 

I notice that this PR has 23 commits but only 1 line of change. Is that expected? Just want to ensure the PR contains all the changes/fixes.

**Comment by shayan-eftekhari** [comment]
@wing328 thanks for the comment.
I created a fork two years ago, made some changes, then I created PRs and those changes are already merged.
I don't know why those commits are still visible in the new PR!
But yes, this is only a small one-line fix!

**Review by muttleyxd — APPROVED** [review]

**Comment by muttleyxd** [comment]
Sorry for late review, looks good to me

**Comment by wing328** [comment]
@shayan-eftekhari can you please submit a new PR based on the latest master? looks like the code has quite some changes after you filed the PR.

Thank you.

**Pull request closed without merging**
