### PR TITLE
python: fix typing for API responses

### PR DESCRIPTION
**Pull request by multani**
The `*_with_http_info` methods, instead of returning a generic ApiResponse object now return the actual object the method relates to.

The type returned is the same as the methods that call the `*_with_http_info` methods.
The documentation also reflects the correct type.

To simplify the template generation, the return type information is generated in the Java generator code.

@wing328
@krjakbrjak
@fa0311

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by fa0311** [comment]
How do I get response headers?

**Comment by multani** [comment]
> How do I get response headers?

Ah yes, I'll change the type to an Union :+1:

**Comment by fa0311** [comment]
typing supports generics type
https://docs.python.org/ja/3/library/typing.html#generics

**Comment by fa0311** [comment]
The current `api/*py` may need to be significantly revamped as it is not suited for giving type hints.

**Comment by multani** [comment]
> The current `api/*.py` may need to be significantly revamped as it is not suited for giving type hints.

Do you have any specific ideas in mind already?

**Comment by fa0311** [comment]
> Do you have any specific ideas in mind already?

No.

**Comment by robertschweizer** [comment]
The goal of this PR is to have correct type annotations for the case that `_return_http_data_only=True`, right?

I think outside users are not supposed to set this flag, but rather use the plain client methods (not the `_with_http_info` methods) in order to get only the response object. So for users of the generated client, this PR makes the type annotations actually more complex.

A nicer solution could be to remove the `_return_http_data_only` flag and always return `ApiResponse.data` in the plain client methods. That would always cause the construction of `ApiResponse`, but that has no logic, so it should be cheap. Type annotations and docstrings would be shorter and thus more user-friendly.

**Comment by multani** [comment]
Thanks @fa0311 and @robertschweizer for the suggestions, I'll take a look at how to proceed.

From my understood, it would be better to:

* Remove `_return_http_data_only` completely
* Transform the `_with_http_info` methods to return a simpler answer, like only `ApiResponse` with the data inside
* Have the "normal" methods (not the `_with_http_info` ones) to return the high-level type

This could also simplify the `ApiClient` class: at the moment, the deserialization to high-level types is done in this class. If I implement the above, this means:

* `ApiClient` always returns `ApiResponse`s
* The deserialization to high-level types moves closer to where the types are actually used

This may require larger changes in `APiClient` to achieve this and removing `response_types_map` from there. I'll take a look.

**Comment by multani** [comment]
So, I made good progress on this, but this is also getting more complicated.

I created an issue to discuss about these changes, outside of this pull request: https://github.com/OpenAPITools/openapi-generator/issues/16788

I will push my last changes in this pull request: it has most of what I discuss in https://github.com/OpenAPITools/openapi-generator/issues/16788 except the new `ApiRequest` I mentioned: instead, most of the code is duplicated for now (hence, why I think we would need this).

There are still several mypy issues, but I think they are simpler to tackle after that:

* There are multiple `ApiResponse` classes defined, and they don't have the same interface.
* Some methods return `Optional[Foo]` instead of `Foo` as currently typed.

I haven't checked the rest yet.

**Pull request closed without merging**
