### PR TITLE
[Python] Commenting supportsInheritance is enabling the model properties inhe…

### PR DESCRIPTION
**Pull request by narenandu**
@wing328 

CC'ing [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee): @taxpon @frol @mbohlool @cbornet @kenjones-cisco to review the pull request if your PR is targeting python programming language.

### Description of the PR

It is kind of counter intuitive, but setting `supportsInheritance = true` is failing to get the properties from the parent when a child model inherits. Didn't dive deep in to the actual base class for the code generation, but commenting out the line from `PythonClientCodegen.java` fixed the issue.

This solves the reported issues
- https://github.com/OpenAPITools/openapi-generator/issues/453 (@poli-granot)
- https://github.com/OpenAPITools/openapi-generator/issues/623 (@emreakca)

There could be multiple reasons since I didn't go to the root cause
- First that there is no `AbstractPyCodegen.java`, which might/might not tackle the issue
- Second, we **don't know** if other code gen for other languages are working since, they also are using `supportsInheritence = true` in their generation code. Just to quote a few
    -  `AbstractJavaCodegen` (@bbdouglas @JFCote @sreeshas @jfiala  @lukoyanov  @cbornet  @jeff9finger )
    - ` JavascriptClientCodegen` (@CodeNinjai @frol @cliffano)
    - `CSharpClientCodegen` / `AbstractCSharpCodegen.java` (@mandrean @jimschubert)
    - `AbstractKotlinCodegen` (@jimschubert @dr4ke616)

### CODE REVIEW

**Comment by narenandu** [comment]
I confirm that if I set `supportsInheritence = true` in `GoClientCodegen.java`, it breaks the inheritance of model properties from a model's parent

**Comment by wing328** [comment]
@narenandu first of all, thanks for the PR. I agree the inheritance/composition in Python client needs some enhancements/fixes.

I've filed https://github.com/OpenAPITools/openapi-generator/pull/1360 with better support for inheritance/composition. I wonder if you can give it a try to see if it works better for your use case.

**Comment by wing328** [comment]
@narenandu #1360 has been merged into master. Can you please give it another try?

**Comment by wing328** [comment]
Closing this PR for the time being. Will reopen if needed

**Pull request closed without merging**
