### PR TITLE
[aspnetcore] Add TypeConverter for enum string conversion

### PR DESCRIPTION
**Pull request by frankyjuang**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

If enum is used in query string, it can't be parsed with `EnumMember`. Add `TypeConverter` to utilize json.net. https://github.com/OpenAPITools/openapi-generator/issues/3513

@wing328 
@jimschubert 
@mandrean

### CODE REVIEW

**Comment by jimschubert** [comment]
Thanks for the PR.  I think we'll need to also consider using a TypeConverter to fix this issue, because this rename will:

1. Be a breaking change for those who regenerate (with the library option)
2. The enum suffix exists because of the order of suboptimal course out there. This rename will cause issue, for instance, with code written as `Pet.PetEnum`.

**Comment by frankyjuang** [comment]
@jimschubert changed to TypeConverter. Thanks!

**Comment by jimschubert** [comment]
Tested with the steps in the issue linked in the description and it appear to work as expected now. Valid enum returns a 200 (after modifying the generated controller to return 200 with empty body). Sending a request for an invalid enum value result in a 400 with body:

```
{
  "errors": {
    "param": [
      "The input was not valid."
    ]
  },
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "0HLOU0ROUFHK9:00000003"
}
```

Looks good! Thanks for fixing this issue!

**Comment by jimschubert** [comment]
@frankyjuang Thanks again for the bug fix! Just wanted to let you know this is part of the recent [4.1.1](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.1.1) release.

**Pull request merged**
