### PR TITLE
Python client docstring

### PR DESCRIPTION
**Pull request by bflaton**
Update of [PR 10331](https://github.com/OpenAPITools/openapi-generator/pull/10331) which was reverted because some tests were failing. This PR also includes fixes for those tests.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by bflaton** [comment]
As indicated by the PR checklist, mentioning the technical committee.. sorry if i misunderstood and now spam you all ;-)

@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess @arun-nalla @spacether

**Comment by spacether** [comment]
@bflaton can you rebase this on master?
https://github.com/OpenAPITools/openapi-generator/pull/10354
just landed which turns python testing back on in circleci.

**Comment by spacether** [comment]
re-triggering circleci because it hit a concurrency limit :(

**Comment by bflaton** [comment]
sorry spacether, didn't see your comment, but branch was one commit behind again, so performed another merge to trigger build as well

**Comment by bflaton** [comment]
@spacether do you still want me to make some changes? Or would you care to try another merge ;-) No conflicts with master right now, but if you want i can always eagerly merge master.

**Review by spacether — APPROVED** [review]
Looks good to me, thanks for your PR!

**Comment by plague006** [comment]
Heya,
How many times have you guys heard this before... "This change broke my weird workflow".
Well today that weird workflow is mine.
I updated openapi-generator and things started breaking.

I use an oauth2 with pkce authentication flow for my tools, and sometimes the authentication token expires before the tool has finished running. So, I put a refresh attempt into a function that handles errors in my API calls. The problem I have is that I would put the token into api.endpoint.api_client.configuration.access_token which no longer exists because api.endpoint is actually a method.

I was wondering if anybody has a suggestion on how I might easily reach the api_client from the method that is being passed.

```
def try_cs_call(
    endpoint: Any,
    *args: Any,
    _raise_exception: bool = True,
    _retries: int = 2,
    **kwargs: Any,
) -> Any:
    """Safely call an API endpoint.

    Args:
        endpoint (Any): endpoint to call
        _raise_exception (bool): Whether to raise an exception on fail or not. Defaults to True.

    Returns:
        Any: returns any type of response model
    """
    response = None
    for _ in range(_retries):
        try:
            response = endpoint(*args, **kwargs)
            cs_response_check(response, _raise_exception)
            break
        except UnauthorizedException:
            logger.debug("Access token expired, attempting refresh..")
            config = endpoint.api_client.configuration
            config.access_token = config.keycloak_client.get_oauth_token()
        except sbcs.ApiException as exc:
            endpoint_name = endpoint.settings["operation_id"]
            print(f"Exception when calling {endpoint_name}: {exc}\n")
            sys.exit()
    else:
        raise UnauthorizedException("CS refused authorization")
    return response
```

**Pull request merged**
