### PR TITLE
[DART-DIO] [GENERATOR] Make header params with dynamic types

### PR DESCRIPTION
**Pull request by syky27**
Otherwise this will generate code which is not compile-able. Like this:

```dart
        Future<Response<List<StockItemProjectionDirect>>>getAllStockItems(Store storeId,{ int xXChunkNumber,int xXChunkSize,StockItemRequestFilterDto stockItemRequestFilterDto,CancelToken cancelToken, Map<String, String> headers, ProgressCallback onSendProgress, ProgressCallback onReceiveProgress,}) async {

        String _path = "/api/store/{storeId}/stock".replaceAll("{" r'storeId' "}", storeId.toString());

        Map<String, dynamic> queryParams = {};
        Map<String, String> headerParams = Map.from(headers ?? {});
        dynamic bodyData;

        headerParams[r'XX-Chunk-Number'] = xXChunkNumber;
        headerParams[r'XX-Chunk-Size'] = xXChunkSize;
```

See how the func recieves int argument which then assignes into a string... last 2 lines

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@syky27 Can you check the boxes and cc the technical committee so maybe this can get merged.

**Comment by kuhnroyal** [comment]
The `Map<String, String> headers` parameter should also become `Map<String, dynamic> headers`.

**Comment by syky27** [comment]
@amondnet could you please review?

**Comment by syky27** [comment]
Ok then, calling maintainers, can someone review?
@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12) @noordawod @sbu-WBT @josh-burton

**Comment by noordawod** [comment]
If we do this for `dart-dio`, then we should do it for other `dart` templates to be consistent. So I suggest the author to visit those and make the same changes, shouldn't be that difficult.

**Review by josh-burton — APPROVED** [review]

**Comment by agilob** [comment]
@wing328 can we get this merged please?

**Comment by syky27** [comment]
@agilob  I think it waits on implementing these changes into all dart templates to be consistent, as @noordawod pointed out. I will try to take a look on those this week...

**Comment by agilob** [comment]
Dont force yourself if you dont want to

**Comment by syky27** [comment]
@agilob  it is not about if I want, it is about the time I have available ;)

**Comment by kuhnroyal** [comment]
This should be merged. The Dart2 client doesn't share much with the Dart-dio client except the language. Besides that, as far as I can see the Dart2 client doesn't even expose the headers as parameters.

**Comment by kuhnroyal** [comment]
@syky27 Can you rebase this please, I really don't think there are any changes needed in the normal dart generator. I am sure we can get this merged.

**Comment by kuhnroyal** [comment]
This needs a new rebase/merge. Otherwise I have the same changes in #8191

**Comment by wing328** [comment]
I've tried to merge the latest master into the branch via https://github.com/OpenAPITools/openapi-generator/pull/6915/commits/ce4f33bf5a10d42fb93fae04362386d0ab10bf2d. Let's see how that goes.

**Comment by kuhnroyal** [comment]
Looks like it can be merged.

**Comment by wing328** [comment]
CircleCI failure not related to this change.

**Pull request merged**
