### PR TITLE
[BUG][PYTHON] Do not set Content-Type for GET, HEAD or DELETE requests

### LINKED ISSUE #9831: [BUG][PYTHON] Content-Type: application/json on GET(also HEAD,DELETE) requests
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The same problem as #476, #1061 is also occurring in Python.

The Python generator makes the default `Content-Type` `application/json` for all HTTP methods (including `GET`, `HEAD` and `DELETE`), whereas there should never be a `Content-Type` set for `GET`, `HEAD` and `DELETE`.

This causes a problem with other tools/servers that insist that `GET`, `HEAD` and `DELETE` requests do not have a `Content-Type` (as per the OpenAPI 3 specification).

An example of the problem is when using [Prism](https://github.com/stoplightio/prism) as a [validation proxy](https://meta.stoplight.io/docs/prism/docs/guides/03-validation-proxy.md).  

[Prism rejects any `GET` request that has a `Content-Type`](https://github.com/stoplightio/prism/issues/1408#issuecomment-690948020).

[Here is an example of the problem manifesting itself](https://github.com/agilepathway/gauge-openapi-example/pull/28/checks?check_run_id=2888606052#step:13:18).

##### openapi-generator version

`master` 969cea8 (21 June, 2021) and latest release at time of filing this issue [v5.1.1](https://github.com/OpenAPITools/openapi-generator/releases/tag/v5.1.1)

Not a regression, this is a long-standing issue.

##### OpenAPI declaration file content or url

Any GET, HEAD or DELETE request generated from any OpenAPI spec via the [Python generator](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/python).

##### Generation Details

Standard [Python config](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/configs/python.yaml)

##### Steps to reproduce

1. Start with any OpenAPI3 spec e.g. the Petstore example at https://editor.swagger.io/
2. Generate Python client code for the spec using the [standard Python generator](https://openapi-generator.tech/docs/generators/python)
3. Look at the generated `rest.py` e.g. in the [standard sample in this repo](https://github.com/OpenAPITools/openapi-generator/blob/969cea8ce10cb9d012c3936fb377d631c0d044c9/samples/openapi3/client/petstore/python/petstore_api/rest.py#L141) and see that the `Content-Type` defaults to `application/json` for all HTTP methods (including `GET`, `HEAD` and `DELETE`), rather than there being no `Content-Type` for `GET`, `HEAD` and `DELETE`.

##### Related issues/PRs

#476, #1061, #5941, #6167

##### Suggest a fix

The fix looks straightforward and I am happy to submit a PR.

Proposed fix is to amend the [rest.mustache](https://github.com/OpenAPITools/openapi-generator/blob/969cea8ce10cb9d012c3936fb377d631c0d044c9/modules/openapi-generator/src/main/resources/python/rest.mustache#L132-L133) so that the `Content-Type` is left unset for `GET`, `HEAD` and `DELETE` requests, e.g.

```
if method in ['POST', 'PUT', 'PATCH', 'OPTIONS']:
  if 'Content-Type' not in headers:
    headers['Content-Type'] = 'application/json'
```

instead of the existing

```
if 'Content-Type' not in headers:
    headers['Content-Type'] = 'application/json'
```

### PR DESCRIPTION
**Pull request by johnboyes**
This commit ensures that the Python generator no longer sets a default 
`Content-Type` of`application/json` for `GET`, `HEAD` and `DELETE` 
requests.

Fixes #9831

Related issues/PRs: #476, #1061, #5941, #6167

Having the `Content-Type` set for these requests was causing issues with
other tools which insist that GET, HEAD and DELETE requests do not have
a Content-Type (as per the OpenAPI 3 specification).

An example of the problem that this commit fixes is when using
[Prism][1] as a [validation proxy][2].

[Prism rejects any GET request that has a Content-Type][3].

Here is [an example of the problem manifesting itself][4].

To validate the fix in this commit:

1. Start with any OpenAPI3 spec e.g. the Petstore example at
https://editor.swagger.io/
2. Generate Python client code for the spec
3. Look at the generated `rest.py` e.g. in the [standard sample in this
repo][5] and see that the `Content-Type` defaults to `application/json`
for all HTTP methods (including `GET`, `HEAD` and `DELETE`), rather than
there being no `Content-Type` for `GET`, `HEAD` and `DELETE`.

cc @taxpon, @frol, @mbohlool, @cbornet, @kenjones-cisco, @tomplus, @Jyhess, @arun-nalla, @spacether

[1]: https://github.com/stoplightio/prism
[2]: https://meta.stoplight.io/docs/prism/docs/guides/03-validation-proxy.md
[3]: https://github.com/stoplightio/prism/issues/1408#issuecomment-690948020
[4]: https://github.com/agilepathway/gauge-openapi-example/pull/28/checks?check_run_id=2888606052#step:13:18
[5]: https://github.com/OpenAPITools/openapi-generator/blob/969cea8ce10cb9d012c3936fb377d631c0d044c9/samples/openapi3/client/petstore/python/petstore_api/rest.py#L141

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by johnboyes** [comment]
Hi, is anyone able to take a look at this, please? 🙏🏻 
@taxpon, @frol, @mbohlool, @cbornet, @kenjones-cisco, @tomplus, @Jyhess, @arun-nalla, @spacether

**Comment by wing328** [comment]
@johnboyes thanks for the PR. My understanding is that it shouldn't set a default content-type header at all. I think that's how other clients (e..g ruby, php, C#, etc) set the content-type at the moment: no default and set the content-type only if it's provided in the spec.

**Comment by johnboyes** [comment]
Hi @wing328, that's my understanding too, and that's what this PR is for.  This PR means that there will no longer be a default content-type header set.

**Comment by johnboyes** [comment]
Hi @wing328, thanks for the comment.  If that's the case, I propose to treat that (not setting a default `content-type` header for _any_ type of request) as a subsequent separate issue, if you agree?  Reasoning being that all of the related issues/PRs to this one (#476, #1061, #5941, #6167) all specifically mention `GET`, `HEAD` and `DELETE` requests only, and I'm wary of this PR having unexpected side-effects if it grows in scope - especially as the PR as is fixes a genuine, current issue.  Thoughts?

**Comment by wing328** [comment]
Updated the samples (as mentioned in the 3rd item in the PR checklist). Let's see if the CI tests pass.

**Comment by wing328** [comment]
Travis CI (including the python tests) was not run since this project has run out of free build credits.

I tested it locally but got the following errors:

```
        try:
            # For `POST`, `PUT`, `PATCH`, `OPTIONS`, `DELETE`
            if method in ['POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE']:
                # Only set a default Content-Type for POST, PUT, PATCH and OPTIONS requests
                if (method != 'DELETE') and ('Content-Type' not in headers):
                    headers['Content-Type'] = 'application/json'
                if query_params:
                    url += '?' + urlencode(query_params)
>               if re.search('json', headers['Content-Type'], re.IGNORECASE):
E               KeyError: 'Content-Type'

petstore_api/rest.py:148: KeyError
```

To run the petstore server locally, please refer to https://github.com/OpenAPITools/openapi-generator/wiki/Integration-Tests#how-to-add-integration-tests-for-new-petstore-samples

**Comment by johnboyes** [comment]
> I tested it locally but got the following errors:

Thanks @wing328, I was able to recreate the error locally too (thanks to your helpful comments, which helped me work out how to update the samples properly and to run the integration tests locally).  I have fixed the error and also updated the samples in e846404 - very grateful if you can take another look, please.

**Comment by wing328** [comment]
Tested locally and the result is good:
```
============================= 159 passed in 4.65s ==============================
___________________________________ summary ____________________________________
  py3: commands succeeded
  congratulations :)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:22 min
[INFO] Finished at: 2021-07-07T11:01:49+08:00
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
