### PR TITLE
[csharp][generichost] Implement not required nullable properties

### PR DESCRIPTION
**Pull request by devhl-labs**
Fixes https://github.com/OpenAPITools/openapi-generator/issues/16520

Breaking change without fallback due to changing the order of model properties. Not required, nullable, and any values with a default now at the end of the model's signature since the user does not have to provide anything for those properties.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
as discussed if the users prefer the old(existing) order of the parameters, we will create `csharp-deprecated` as the fallback.

**Comment by wing328** [comment]
appveyor tests passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/48448381

**Comment by SDP190** [comment]
Wow @devhl-labs thank you so much for this so valuable and important feature! I see it really was a lot of work! Very useful and much appreciated!

Has this been released already to npm?

**Comment by devhl-labs** [comment]
Probably, but i am not familiar with that.

**Pull request merged**
