### PR TITLE
[csharp] Add option for nullable reference types 

### PR DESCRIPTION
**Pull request by devhl-labs**
@mandrean  @frankyjuang  @shibayan @Blackclaws 

The PR adds an option for nullable reference types. Template creators will have to decide to implement it if they choose.

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by devhl-labs** [comment]
There are other things id like to do but this or is a prerequisite. My other prs will either be updated or closed.

**Comment by devhl-labs** [comment]
@mandrean @frankyjuang @shibayan @Blackclaws @wing328  
Can I get a merge here? Nothing here should affect the current generators as they don't use the option.

**Comment by Blackclaws** [comment]
LGTM, we should have this option in one way or another @wing328

**Comment by Blackclaws** [comment]
Actually you could even move the support for parsing the option up to the abstract csharp codegen since that is where the flag is stored.

**Comment by devhl-labs** [comment]
Moved the parsing of the option to the abstract.

**Comment by Blackclaws** [comment]
@wing328 LGTM, drone build unrelated to changes, circle ci for some reason timed out?

In general I think the nullable reference types can be referenced in the method where it actually uses the nullableTypes list. That way you don't have to add single types to the list but just treat everything as nullable if nullable reference types  is set. But that can be an enhancement after merging.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/9620 instead.

**Pull request closed without merging**
