### PR TITLE
[java] Apply additionalModelTypeAnnotations on enums

### LINKED ISSUE #6055: [BUG] [Spring] [Java] additionalModelTypeAnnotations not applied to enums
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Option `additionalModelTypeAnnotations` isn't applied to enums.

##### openapi-generator version

4.3.0

##### OpenAPI declaration file content or url

```yaml
swagger: "2.0"
info:
    title: Book
    version: 1.0.0
paths:
    /books:
        get:
            summary: Get books
            responses:
                200:
                    description: Successful response
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/Book'
definitions:
    Book:
        description: Book
        type: object
        properties:
            type:
                $ref: '#/definitions/BookType'
    BookType:
        description: Book type
        type: string
        enum:
            - HARDCOVER
            - PAPERBACK
            - ELECTRONIC
```

##### Command line used for generation

    generate -g spring -p additionalModelTypeAnnotations=@Foo,hideGenerationTimestamp=true
    generate -g java -p additionalModelTypeAnnotations=@Foo,hideGenerationTimestamp=true

##### Steps to reproduce

Generate the code and see the following:

Book.java:

```java
...
/**
 * Book
 */
@ApiModel(description = "Book")
@Foo

public class Book   {
  ...
}
```

BookType.java

```java
/**
 * Book type
 */
public enum BookType {
  ...
}
```

### PR DESCRIPTION
**Pull request by agilob**
Fixes #6055

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

### CODE REVIEW

**Comment by agilob** [comment]
circleci is failing as it finds new changes after generation, but all changes are whitespace

**Comment by alimac87** [comment]
@agilob, just a thought: in enumClass.mustache and enumOuterClass.mustache could you remove the newline between the end of comment "*/"
and "{{>additionalModelTypeAnnotations}}" to avoid the whitespace changes (and blank lines) in generated files?

e.g. in https://github.com/OpenAPITools/openapi-generator/pull/7539/files#diff-758d6dce1a3e4c52e3e30bff17da160f line 3 would read:
`*/{{>additionalModelTypeAnnotations}}`

**Comment by agilob** [comment]
This time I'm going to take readability of mustache files over extra whitespace in generated code (which you shouldnt modify anyway?)

With your changes it looks even worse :P

image

**Comment by alimac87** [comment]
Yep fair point - I thought I'd tested this and seen the generated code include a new line between the "*/" and "@", but I must have been mistaken.

**Comment by UnleashSpirit** [comment]
Is there no potentiel side effect adding annoation targeted for classes on enums ?
 I often use
```
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
```
But on enums, strange no ?
The @lombok.Builder will end iwth "Cannot instantiate the type EnumCategorie"

**Pull request closed without merging**
