### PR TITLE
[JAVA]: Fix unknown property error for gradle build

### PR DESCRIPTION
**Pull request by HeneryHawk**
If i generate a client for java with the library native, i get the following error when i try to build the client via `./gradlew assemble`.

```
/build.gradle' line: 53
Could not set unknown property 'classifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.
```

This error can also be reproduced if you use the native Java echo_api client sample.
According to the gradle documentation, the `classifier` property was removed with the update to Gradle 8.x
See: https://docs.gradle.org/current/userguide/upgrading_version_7.html#abstractarchivetask_api_cleanup

@bbdouglas @Zomzog @lwlee2608 @martin-mfg

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by martin-mfg** [comment]
Hi @HeneryHawk, thanks for the PR!

May I ask you to apply the same fix for other Java libraries besides `native` as well?

**Comment by HeneryHawk** [comment]
Hi @martin-mfg

yes I can do that but can we postpone this to a later PR? We would need the adaptions for `native` asap...

Regards

**Comment by wing328** [comment]
@HeneryHawk thanks for the PR.

totally ok to have a separate PR to address similar issue in other build.gradle files.

i'm able to repeat the issue by adding gradle build tests for java native petstore samples via https://github.com/OpenAPITools/openapi-generator/pull/19951

will get that one merged after merging your fix so that this issue is covered moving forward.

**Comment by wing328** [comment]
UPDATE: merged https://github.com/OpenAPITools/openapi-generator/pull/19951 to add tests and sync pom.xml & build.gradle (to fix an issue when `useJakartaEe` is eanbled)

**Pull request merged**
