### PR TITLE
Fix - Provides a default value for optional init parameters

### PR DESCRIPTION
**Pull request by alessiozurru**
[SWIFT] - The idea is to manage In a more efficiently way the creation of init methods of model objects providing a default nil value for optional parameters.

This is a trivial change to modelObject.mustache template and could be helpful to create Model objects more simply, in particular when they have many parameters. 
In addition we could avoid possible compilation error for projects that are switching from swagger-codegen tool which provided an init with empty parameters.

With this change we simply provide the '= nil' default value for all params that are optionals

@jgavris  @ehyche  @Edubits  @jaz-ah  @4brunu 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by 4brunu** [comment]
@alessiozurru Thanks for this PR.
Could you please run `./mvnw package && ./bin/generate-samples.sh` and commit the changes?
Thanks

**Comment by alessiozurru** [comment]
@4brunu I already done it but there are not changes to commit.
It's not ok?

**Comment by 4brunu** [comment]
@alessiozurru Thanks, it was just to make sure 👍 
Looks good to me this PR, it was something that I also wanted.

**Pull request merged**
