### PR TITLE
[swift5] new flag: return Data instead of Void

### LINKED ISSUE #13597: [REQ] support follow redirects in swift libraries
### Is your feature request related to a problem? Please describe.

We have an API that uses ETags to implement a simple caching mechanism for large image data. We are requesting with the ETag of the locally cached image data in the request header and a response is either 
- 302 with a Location redirect header redirecting the client to the blob storage with an updated ETag in the response header
- or 304 not modified, indicating that the locally cached data in the client (as indicated by the ETag) is not outdated and can still be used. 

Currently two things are preventing this to work with the generator:
1. The generated APIs for responses that define redirects will currently be generated with a `Void` return type. Both URLSession and Alamofire libraries currently **already follow** the redirect URL from the location header, however the data that is being retrieved is being discarded by always mapping to Void. 
2. Successful status code range is currently hardcoded for both URLSession and Alamofire implementations to `200..< 300`. both 302 and 304 are treated as failure and the image data can not be returned to the caller

## Describe the solution you'd like

For solving problem 1. I propose to change the return type to `Data` for redirect responses and pass the returned Data. This should probably sit behind a new generator flag to stay backwards compatible. 
For solving problem 2. I propose to add the configuration option for changing the successful status code range. This can also be useful for other use cases beyond the scope of follow redirects, that's I would propose to add this in a separate PR

## Describe alternatives you've considered

I don't think there are many other options currently other than changing the API spec and directly returning image data instead of sending Location redirects headers. However for our project this is not possible

## Additional context

Bildschirmfoto 2022-10-05 um 08 18 10

### PR DESCRIPTION
**Pull request by Jonas1893**
As explained in #13597 the generated API Clients already follow Location redirects, however data returned by redirected location is always being discarded by mapping to Void. This PR implements a new generator flag `returnDataInsteadOfVoid` which controls whether the response Data is always returned instead of being discarded. 

With both this change and [13598](https://github.com/OpenAPITools/openapi-generator/pull/13598) in place, swift5 generator now supports APIs that rely on follow redirects.  

This PR closes #13597 

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. -> @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

### Declaration
The program was tested solely for our own use cases, which might differ from yours.

### Link to provider information
https://github.com/mercedes-benz

### CODE REVIEW

**Comment by wing328** [comment]
> This PR implements a new generator flag returnDataInsteadOfVoid which controls whether the response Data is always returned instead of being discarded.

@Jonas1893 thanks for the PR. Should the API return data or void based on the openapi spec instead of using an option flag? 

Just want to avoid one more option if possible.

**Comment by Jonas1893** [comment]
> > This PR implements a new generator flag returnDataInsteadOfVoid which controls whether the response Data is always returned instead of being discarded.
> 
> @Jonas1893 thanks for the PR. Should the API return data or void based on the openapi spec instead of using an option flag?
> 
> Just want to avoid one more option if possible.

@wing328 I thought about this as well and came to the conclusion that it is better to implement it this way. Feel free to share your thoughts if you have a different opinion. My reasoning is:

1. I am not sure whether it is possible to easily derive this information from the spec right now. What we would need from generator would be something like an `{{#hasRedirectResponse}}` flag indicating that the only 'successful' responses defined in the spec for an endpoint is/are redirects. What status code range is treated as a successful response code can be configured as well (implemented in swift5 templates) and this information is not available yet in generator which computes `hasRedirectResponse` (or at least: I don't know how to do it) Even if it would be possible, I think a lot of logic would be required to make this happen
2. If we decide to implement this without a flag it would be a breaking change and no longer eligible for v6.*.*

**Comment by Jonas1893** [comment]
Hi @wing328 sorry for being a pain. Is there any update on this? 
cc @4brunu

**Comment by Jonas1893** [comment]
Hey @wing328 @4brunu anything I can do to help getting this merged? I think it would be a valuable addition, otherwise follow-redirect use cases are currently not possible with the swift5 generator

**Comment by 4brunu** [comment]
@Jonas1893 how do you imagine this without a new flag? Always returning void?

**Comment by Jonas1893** [comment]
> @Jonas1893 how do you imagine this without a new flag? Always returning void?

Hi @4brunu Without a flag we would always return the response `Data` which normally will be empty for most APIs without returnType and only non-zero bytes for APIs where we follow the location redirect.
As I believe for most APIs without returnType the response data is not interesting for the caller I would rather implement this behind the opt-in flag. 

As @wing328 mentioned it would be the best if generator could decide whether to use `Void` or `Data`, only using `Data` when there is no explicit returnType but a location redirect response detected. But I don't know how we could do this currently as I don't see a way to decide in the template whether the only possible response is a location redirect. If there is a way I am happy to implement it this way without the flag but then I would need some guidance

**Comment by wing328** [comment]
> But I don't know how we could do this currently as I don't see a way to decide in the template whether the only possible response is a location redirect. If there is a way I am happy to implement it this way without the flag but then I would need some guidance

@Jonas1893 are you looking for something like https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/api.mustache#L357-L394 ?

Would that meet your requirement you can check for 301 http response code in particular?

**Comment by Jonas1893** [comment]
> > But I don't know how we could do this currently as I don't see a way to decide in the template whether the only possible response is a location redirect. If there is a way I am happy to implement it this way without the flag but then I would need some guidance
> 
> @Jonas1893 are you looking for something like https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/api.mustache#L357-L394 ?
> 
> Would that meet your requirement you can check for 301 http response code in particular?

Not quite as I understand this is not an aggregation ("Does the responses contain a 3xx response or not") but behaves more like a loop over all responses. Also I would not be able to check for 301 / 302 / 307 / 308 specifically but only for the 3xx range. 

The problem I see is that even if we managed to do this somehow for the right status codes (hard to tell which are even the "right" status codes) and only if a location header is present (I don't think we can check this in the templates) people might still want this behavior for other status codes than the ones we specifically designed it for as well. That's why I would personally rather go with the global setting.

**Comment by wing328** [comment]
> Also I would not be able to check for 301 / 302 / 307 / 308 specifically but only for the 3xx range.

there's also a `is3xx` mustache tag available.

> people might still want this behavior for other status codes than the ones we specifically designed it for as well

If I understand correctly, the requirement is to able to get the response body (in string) for further processing due to change/implementation in the backend.

What about using the `WithHttpInfo` approach?

In other clients, e.g. Java ,Ruby, for every method (operationId), there's a corresponding `WithHttpInfo` method added. For example, if the method is `getPetById`, then a method named `getPetByIdWithHttpinfo` will be created as well and it will return an object called ApiResponse, which stores the HTTP status code, headers and body so that developers have full access to the HTTP response.

Would that meet your requirement?

**Comment by 4brunu** [comment]
Maybe it's easier to use the  `execute` method on the `RequestBuilder` that returns a `Response` with everything that you need, and now there is even as async method for `execute`.

**Comment by Jonas1893** [comment]
> Maybe it's easier to use the `execute` method on the `RequestBuilder` that returns a `Response` with everything that you need, and now there is even as async method for `execute`.

Yes, that's better thank you for this hint I forgot about this change. Then we do not need this adoption at all! :)

**Pull request closed without merging**
