### PR TITLE
Java: OneOf support and change models name if it is the same as nativ…

### PR DESCRIPTION
**Pull request by catarinacds**
…e java classes #4515

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Please use 4-space instead of tab and looks like this change breaks some of the tests:
```
[ERROR] Failures: 
[ERROR]   DefaultCodegenTest.testComposedSchemaOneOfWithProperties:284 expected [3] but found [2]
[ERROR]   DefaultGeneratorTest.testRefModelValidationProperties:123 expected [/^\\d{3}-\\d{2}-\\d{4}$/] but found [null]
[ERROR]   JavaInheritanceTest.javaInheritanceWithRequiredAttributesOnComposedObject:177 expected [true] but found [false]
[ERROR]   TypeScriptNodeModelTest.mappedFromModelTest:281 expected [ApiResponse] but found [ApiResponseModel]
[ERROR] Tests run: 859, Failures: 4, Errors: 0, Skipped: 0
```

Can you please have a look at https://github.com/OpenAPITools/openapi-generator/pull/4785 as well, which also aims to add oneOf support to the Java client?

**Comment by bkabrda** [comment]
@catarinacds could you please provide an example of what generated code looks like with your change? Something along the lines of https://github.com/OpenAPITools/openapi-generator/pull/4785#issuecomment-572561450 (the first code block has an example spec, the second code block an actual example that would get generated by implementation in my PR and the third code block is something that I was considering but eventually didn't implement, so please disregard that).

It'd be nice to be able to compare both of the implementations. I'd love to do a code review to see the different cases/approaches that our implementations can/can't cover, but it's hard to review your PR as the actual code is a bit lost in between the code style changes that probably your IDE did. Could you potentially provide a version of your PR stripped from the code style changes for easier review? Thanks!

**Comment by wing328** [comment]
@catarinacds when you've time, can you please PM me via https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM ?

**Comment by wing328** [comment]
@catarinacds thanks again for the PR. We've added better oneOf support to `jersey2`, `native` of the Java client generator. Please give these a try to see if it meets your requirement.

Closing this one for the time being.

**Pull request closed without merging**
