### PR TITLE
[Go][Client] Use configured Scheme and Host in requests

### LINKED ISSUE #2943: [BUG][Golang][Client] Configured Scheme is ignored by generated methods
##### Description

The Go client library takes a configurable `Scheme`, but it then doesn't use it when making client requests.

##### openapi-generator version

`v4.0.0` via https://hub.docker.com/r/openapitools/openapi-generator-cli/

##### Command line used for generation

```
docker run --rm -v $(pwd):/local openapitools/openapi-generator-cli:v4.0.0 generate --package-name api -i /local/swagger.json -g go -o /local/api
```

##### Steps to reproduce

Attempt to make a request using a Go client generated with `v4.0.0`.

##### Related issues/PRs

None

##### Suggest a fix

This should be reasonably easy to fix, simply adding a case for the Scheme like there is for the host in `prepareRequest`:
https://github.com/OpenAPITools/openapi-generator/blob/18b66ed28c7a2c783e7c4e3c81f1817ec3cabf4f/modules/openapi-generator/src/main/resources/go/client.mustache#L278

### PR DESCRIPTION
**Pull request by johanbrandhorst**
Previously we were simply setting the Host header and completely ignoring the configured scheme.

Fixes #2943

### CODE REVIEW

**Comment by johanbrandhorst** [comment]
@wing328

**Comment by johanbrandhorst** [comment]
:thinking: sorry, I thought you had to trigger the CI builds somehow, but they just appeared.

**Comment by johanbrandhorst** [comment]
@wing328 looks like an unrelated error, how do you want to proceed?

**Comment by johanbrandhorst** [comment]
Fixed the test failure again :grimacing:

**Comment by wing328** [comment]
Looks good to me

cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09)

**Pull request merged**
