### PR TITLE
Fix default response

### PR DESCRIPTION
**Pull request by wing328**
Fix `isDefault` mustache tag in the response

which impacts the following generators and I've updated the template accordingly:
- elm: @eriktim (2018/09)
- scala-akka: @clasnake (2017/07), @jimschubert (2017/09) ❤️, @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)
- php-symfony: @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) ❤️, @ybelenko (2018/07), @renepardon (2018/12)

cc @OpenAPITools/generator-core-team 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by ybelenko** [comment]
@wing328 21 hours for review, really? :smile:
I guess you didn't update php-slim4 samples because I use `{{#isDefault}}` in https://github.com/OpenAPITools/openapi-generator/blob/8689625af33b60acc0e182d7e3c9153f29346aad/modules/openapi-generator/src/main/resources/php-slim4-server/SlimRouter.mustache#L76

Can't check it because latest master doesn't compile on my side:
```shell
[INFO] Reactor Summary for openapi-generator-project 5.0.0-SNAPSHOT:
[INFO] 
[INFO] openapi-generator-project .......................... SUCCESS [  2.025 s]
[INFO] openapi-generator-core ............................. SUCCESS [ 13.007 s]
[INFO] openapi-generator (core library) ................... FAILURE [  5.907 s]
[INFO] openapi-generator (executable) ..................... SKIPPED
[INFO] openapi-generator (maven-plugin) ................... SKIPPED
[INFO] openapi-generator-gradle-plugin (maven wrapper) .... SKIPPED
[INFO] openapi-generator-online ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.665 s
[INFO] Finished at: 2020-06-12T11:55:26+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project openapi-generator: Failed to copy full contents from /Users/ybelenko/Sites/openapi-generator/modules/openapi-generator/src/main/resources/java-pkmst/enumClass.mustache to /Users/ybelenko/Sites/openapi-generator/modules/openapi-generator/target/classes/java-pkmst/enumClass.mustache -> [Help 1]
```

My latest commit:
```shell
8689625af3 (HEAD -> master, upstream/master) Fix default response (#6625)
```

**Comment by ybelenko** [comment]
Now build does compile, don't know why it didn't work. There are changes in Slim4 samples folder like:
```diff
$  git diff samples/server/petstore/php-slim4/lib/SlimRouter.php
diff --git a/samples/server/petstore/php-slim4/lib/SlimRouter.php b/samples/server/petstore/php-slim4/lib/SlimRouter.php
index 4588e17fd5..6052fa0b97 100644
--- a/samples/server/petstore/php-slim4/lib/SlimRouter.php
+++ b/samples/server/petstore/php-slim4/lib/SlimRouter.php
@@ -61,7 +61,7 @@ class SlimRouter
             'userClassname' => 'AnotherFakeApi',
             'operationId' => 'call123TestSpecialTags',
             'responses' => [
-                'default' => [
+                '200' => [
                     'code' => 200,
                     'message' => 'successful operation',
                     'jsonSchema' => '{
```

**Comment by wing328** [comment]
@ybelenko There was an issue with `isDefault` which is fixed by this PR. Another PR is pending this one so sorry for the short notice.

So the Slim router must have the `default` specified in order to work?

**Comment by ybelenko** [comment]
> So the Slim router must have the `default` specified in order to work?

Not really, but it helpfull for Mock feature.

**Pull request merged**
