### PR TITLE
Fix typo useDefaultRoutng to useDefaultRouting

### PR DESCRIPTION
**Pull request by Doxoh**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@mandrean , @jimschubert 

### Description of the PR
Fix the typo of commit 94c583b

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by Doxoh** [comment]
@wing328 no the commit is linked to my GitHub Account

**Comment by wing328** [comment]
I don't think so. If you look at https://github.com/OpenAPITools/openapi-generator/pull/3488/commits, it should have shown your Github profile pic if the Github account is linked correctly to the commit.

**Comment by Doxoh** [comment]
If I open it, it does.

grafik

**Comment by wing328** [comment]
Now it's showing correctly in my end too.

**Comment by wing328** [comment]
The Travis CI failure is not related to this PR.

**Pull request merged**
