### PR TITLE
[Go] Prefix enum number with _ 

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

To fix https://github.com/OpenAPITools/openapi-generator/issues/520

The test result looks good:
```
package openapi
type Bits string

// List of Bits
const (
        _32BIT Bits = "32bit"
        _64BIT Bits = "64bit"
)
```

cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07)

### CODE REVIEW

**Comment by bvwells** [comment]
Looks good to me!

**Comment by wing328** [comment]
@bvwells thanks for the quick review.

(the shippable CI failure has been fixed in the master)

**Comment by siddharthist** [comment]
Might be good to add the test you wrote above to a regression test suite somewhere.

**Comment by wing328** [comment]
@siddharthist good idea. May I know if you've time to help contribute a test case for that? We can show you some good starting points.

**Comment by siddharthist** [comment]
@wing328 My project has switched away from using openapi-generator. I appreciate your response to my issues!

**Comment by wing328** [comment]
@siddharthist No problem at all 👌 thanks for reporting the issue and reviewing the PR.

We'll add the test later.

**Pull request merged**
