### PR TITLE
Updated the HTML2 Doc Curl Examples to provide sample Request Body & Query Param examples.

### PR DESCRIPTION
**Pull request by Kraust**
Addressed the issue in #9384 where query strings in curl examples were not displaying their example values.
I also refactored the code out so that the curl example into its own mustache file, and provided the request body examples as well.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvn clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by Kraust** [comment]
Note: I would have assumed samples/documentation/html2/index.html would have been generated by this change, but it doesn't seem like the sample was modified despite the fact I ran generate_samples.sh.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
> Note: I would have assumed samples/documentation/html2/index.html would have been modified by this change, but it doesn't seem like the sample was modified despite the fact I ran generate_samples.sh.

Don't worry. We'll take a look.

**Comment by Kraust** [comment]
Hopefully that fixes that for you, thanks.

**Comment by wing328** [comment]
Yup, looks good now. Commits are correctly linked.

**Pull request merged**
