### PR TITLE
Fix missing import for JsonTypeName for jersey2

### PR DESCRIPTION
**Pull request by christian0101**
Fix missing import for JsonTypeName for jersey2. Similar to https://github.com/OpenAPITools/openapi-generator/issues/8157 , but for jersey 2 and `array` type.

Example spec: https://github.com/christian0101/openapi-gen-alias-type-bug 

This PR is to fix the jersey2 library, however it would make sense to fix this in a more sophisticated way. The template is correct at the Java level, but the library overwrites it and causes the issue.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608

### CODE REVIEW

**Comment by wing328** [comment]
@christian0101 thanks for the PR. Can you please share a spec to reproduce the issue?

I tested with the spec in https://github.com/OpenAPITools/openapi-generator/issues/8157 but couldn't repeat the issue.

**Comment by christian0101** [comment]
@wing328 thank you for checking this. https://github.com/christian0101/openapi-gen-alias-type-bug . It is the `Subjects` model. 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project openapi-gen-alias-type-bug: Compilation failure: Compilation failure: 
[ERROR] /Users/cristian/git_repos/openapi-gen-alias-type-bug/target/generated-sources/openapi/src/main/java/org/example/service/v1/model/Subjects.java:[31,1] error: cannot find symbol
[ERROR]   symbol: class JsonTypeName
[ERROR] /Users/cristian/git_repos/openapi-gen-alias-type-bug/target/generated-sources/openapi/src/main/java/org/example/service/v1/model/Person.java:[45,34] error: cannot find symbol
[ERROR]   symbol:   class ArrayList
[ERROR]   location: class Person
```

**Comment by wing328** [comment]
Let's start with 
```
          "subjects": {
            "oneOf": [
              { "$ref": "#/components/schemas/subjects" },
              { "$ref":"#/components/schemas/subject" }
            ]
```

What does the payload looks like? 

I suspect the schema definition may not be correctly describing the payload.

**Comment by christian0101** [comment]
I updated the schema to be more clear. https://github.com/christian0101/openapi-gen-alias-type-bug/blob/main/src/main/resources/swagger.json#L61 

Example responses

https://github.com/christian0101/openapi-gen-alias-type-bug/blob/main/src/main/resources/exampleResponseRawSubjects.json 

https://github.com/christian0101/openapi-gen-alias-type-bug/blob/main/src/main/resources/exampleResponseFormattedSubjects.json

**Comment by borsch** [comment]
@christian0101 I've fixed this import under https://github.com/OpenAPITools/openapi-generator/pull/14474 . Could you please check if latest release 6.3.0 works for you?

**Comment by christian0101** [comment]
> @christian0101 I've fixed this import under #14474 . Could you please check if latest release 6.3.0 works for you?

Thank you, @borsch . The issue seems to be fixed with version 6.3.0.

**Pull request closed without merging**
