### PR TITLE
[csharp-dotnet2] REMOVED

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Removes C# 2.0 support. See #116

Per [Microsoft Product Lifecycle](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=.NET%20Framework&Filter=FilterNO), support for .NET Framework 2.0 ended in 2011:

> Support for .NET Framework 2.0 ended on July 12, 2011. .NET 3.5 SP1 is the only supported service pack level after this date. We strongly encourage customers to migrate to .NET Framework 3.5 SP1. For more information, please visit the .NET Framework Support Lifecycle Policy FAQ https://support.microsoft.com/help/17455

cc @OpenAPITools/openapi-generator-core-team @mandrean (2017/08), @jimschubert (2017/09)

### CODE REVIEW

**Comment by etherealjoy** [comment]
Finally :)

**Comment by wing328** [comment]
I think the main use case of .net 2.0 is for Unity and there's a discussion about refactoring/rewriting it: https://github.com/OpenAPITools/openapi-generator/issues/853.

(I did talk to some users before and they said the output (C# .net 2.0 client) is functional)

**Comment by jimschubert** [comment]
I might be wrong, but I believe Unity was up to C# 4.0 in 2016 or 2017.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/2804 to add a warning instead.

**Comment by jimschubert** [comment]
I didn't realize the generator was never "deprecated" after discussion in #116. I'll keep this open and apply a 5.0.0 target once that milestone is created.

**Comment by wing328** [comment]
@jimschubert I believe we can close this one, right?

**Comment by jimschubert** [comment]
@wing328 yeah, we can just redo it for a 5.0.0 release.

**Pull request closed without merging**
