### PR TITLE
style(elixir): use 'API' instead of 'Api' in auto-generated API modules

### PR DESCRIPTION
**Pull request by efcasado**
### Description

Suggested fix for https://github.com/OpenAPITools/openapi-generator/issues/19779.

@mrmstn, not sure if you will agree or find this contribution valuable. I couldn't find any old issue or discussion referring to this particular "issue", but I understand this topic may have already been discussed in the past and there might be good reasons why you settled for the current implementation.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
looks like this is a breaking change?

you can use customized templates (e.g. -t via CLI) for the time being

**Comment by efcasado** [comment]
> looks like this is a breaking change?

It certainly is! My bad. I've just updated the base branch to `8.0.x`.

> you can use customized templates (e.g. -t via CLI) for the time being

Thanks! Wasn't aware of this feature 🙏

**Comment by mrmstn** [comment]
Hi @efcasado,

Thank you for the PR! I appreciate your initiative, but I’d prefer not to change or start a discussion about the naming of the Api namespace at this time.

Happy Hacktoberfest! 🎉

**Comment by mrmstn** [comment]
Hi @efcasado,

I took a look at your issue during lunch, and your reasoning makes sense. However, from a readability perspective, a module named in all uppercase is a bit hard on the eyes—though that's just a personal preference and doesn’t impact the change itself. To be honest, I don't have a strong opinion on this topic.

@wing328, it would be great if you could weigh in and make the final decision as the third vote.

I've reopened this PR so we don't lose track of it.

**Comment by mrmstn** [comment]
@efcasado in the mean time, could you please also commit/push the updated samples as described in the checklist?

**Comment by yordis** [comment]
Recently, I had to finally merge an ADR, so engineers are discouraged from discussing the topic unless they are incredibly passionate and want to provide quantifiable evidence: https://straw-hat-team.github.io/adr/adrs/6819030042/README.html.

I appreciate https://github.com/christopheradams/elixir_style_guide. It is another opinion, nothing more.
Opinion that makes the code-gen even more complicated because if people want to maintain consistency, they will require extra configuration around known acronyms; for example:

- OpenapiPetstore.API.XmlModel vs `OpenapiPetstore.API.XMLModel`

Otherwise, the rule is already broken.

Aside from that, the biggest concern here is that we will introduce breaking changes and allow people to opt in.

I do not see a value after 8+ years in Elixir; that is just another opinion.

**Comment by mrmstn** [comment]
Hi @yordis,

Thank you for sharing your thoughts and your ADR on this matter. I completely agree with your perspective and believe it makes sense to follow this approach.

With your input, I consider this the third vote in favor of not changing the naming convention for acronyms. As a result, I will go ahead and close this PR.

Thanks again for your contribution!

**Pull request closed without merging**
