### PR TITLE
Update to reset httpRepsonse.Body

### PR DESCRIPTION
**Pull request by nmische**
… such that is available to client consumers via the returned httpResponse variable.

@antihax @grokify @kemokemo @bkabrda

Addresses https://github.com/OpenAPITools/openapi-generator/issues/4799

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by nmische** [comment]
@antihax @grokify @kemokemo @bkabrda: Thoughts on this enhancement?

Also, I'm not sure what the problem is with the circleci build, so any help there would be appreciated.

**Comment by wing328** [comment]
@nmische I've fixed the CI failure by updating the samples.

I wonder if you can review https://github.com/OpenAPITools/openapi-generator/pull/7041 as well since that PR seems to address similar issues.

**Comment by nmische** [comment]
@wing328: Thank you for the help with the CircleCI build!

I see a few challenges with #7041. First it doesn't really address the issue this PR seeks to address, which is that the returned response.Body can't be used to read the raw API response with the currently generated client. In #7041 this still appears to be an issue, while this PR re-sets the response.Body such that it can be re-read to access the raw response. (This can be very useful when debugging scenarios where the upstream API has returned malformed JSON.)

Second, #7041 it changes the generated client's API in that it requires the caller to ensure they close the request body. With the currently generated client, and the update proposed in this PR, closing the request body is done by the generated client code. Thus users could update to the client generated by the templates in this PR and not have to change any of their existing code.

**Comment by Gmtstephane** [comment]
I agree, this PR is more appropriate than my own #7041

**Comment by wing328** [comment]
@Gmtstephane thanks for the review

@nmische thanks for the PR, which has been merged into master.

When you've time, I wonder if you can make the same enhancement to the go-experimental client generator: https://github.com/OpenAPITools/openapi-generator/blob/a7ccc4addd95de3505c946dfdc0d51f281975f38/modules/openapi-generator/src/main/resources/go-experimental/api.mustache#L285

**Comment by nmische** [comment]
@wing328: I'm happy to update the go-experimental client generator as well. I should be able to get to that later this week or early next.

**Pull request merged**
