### PR TITLE
[JAVA][Rest-assured] add more informations about operations

### PR DESCRIPTION
**Pull request by viclovsky**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

* Add swagger annotations to client
* Set default baseReqSpec and baseContextConsumer in ApiClient

See also the description bellow: https://github.com/OpenAPITools/openapi-generator/pull/#issuecomment-413194142

A first version of this PR (using a context class) can be found here: https://github.com/OpenAPITools/openapi-generator/pull/751

### CODE REVIEW

**Comment by viclovsky** [comment]
@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

**Comment by viclovsky** [comment]
Hello, @jmini 

The main idea is to have ability to get constants from API specification inside client. Constants such as tages, notes, summary etc. 
Rest-assured is mostly client for testing. Tests often has integration with test report such as [Allure](https://github.com/allure-framework/allure2) for instance. Test report has detailed information about tests run results, curl arguments, command line etc. And this information is usefull for managers, testers and other team members. 
Constants are necessary to fill report easier. 
The other thing is that with сonstants we are able to do such things as: grouping tests by tags or make some logs with summaries. 

Initially I've made it via public static final constants, but it wasn't convenient to be honest: a lot of constants. So the second solution was adding Context class which combines constants (tags etc.) and special Listener class. See [PR](https://github.com/OpenAPITools/openapi-generator/pull/815). But to my mind it was complicating of client.
The final version is to use swagger-annotation and aspects for dealing with tags etc in client.  

If you have any idea how I can improve or make it easy it will be very helpfull.

**Comment by jmini** [comment]
Thank you for the clarification.

It is a little sad to use a `swagger-core` version that is made for OpenAPI v2, but for the moment there is no template that creates annotations using a `swagger-core` version compatible with OpenAPI v3.

We can improve this in the future.

---

I hope you did understood correctly the reasoning behind my question: I think it is important to have some context behind changes made with a PR.

I took the liberty to update the PR description and the title.

**Comment by jmini** [comment]
Follow up PR: #822

**Pull request merged**
