### PR TITLE
[cpp-restsdk] add support for AnyType

### PR DESCRIPTION
**Pull request by aminya**
Add support for AnyType. The code generated now includes AnyType although the the files are missing. This fixes the issue by adding an implementation. 

Fixes https://github.com/OpenAPITools/openapi-generator/issues/16476

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by aminya** [comment]
@ravinikam @stkrwork @etherealjoy @martindelille @muttleyxd Tagging the C++ committee as per request.

**Review by muttleyxd — APPROVED** [review]

**Comment by wing328** [comment]
@aminya thanks for the PR. Should any type be simply mapped to `std::any` in C++ ?

https://en.cppreference.com/w/cpp/utility/any

**Comment by aminya** [comment]
> @aminya thanks for the PR. Should any type be simply mapped to `std::any` in C++ ?
> 
> https://en.cppreference.com/w/cpp/utility/any

In the context of Restcpp SDK, `std::any` is not something that is supported directly. The any data type used in Restcpp is `json::value` that represents any JSON value.

**Comment by wing328** [comment]
Thanks for the explanation.


Can you please run `mvn integration-test -f samples/client/petstore/cpp-restsdk/client/pom.xml` locally?

I got some errors related to line 12 in AnyType.h (No such file or directory)

**Comment by aminya** [comment]
@wing328 Thanks for testing. I have fixed the issue. I was using the source folder path instead of the header folder path for `AnyType.h`

**Comment by wing328** [comment]
tested locally and the result is good

thanks for the PR

**Pull request merged**
