### PR TITLE
[Python] Add "servers" support in path, operation

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- Added "servers" support in path, operation
- Tested locally to ensure the servers defined in operation override those defined in path

Dependency: https://github.com/OpenAPITools/openapi-generator/pull/2048

cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

### CODE REVIEW

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team as the change covers default codegen

**Comment by spacether** [comment]
This PR had a typo in it in api.mustache line 89:
```
if int(kwags.get('_host_index')) < 0 or int(kawgs.get('_host_index')) >= len(local_var_hosts):
```
kwags does not exist, it should have been kwargs.
My PR: https://github.com/OpenAPITools/openapi-generator/pull/4906
will fix it when it is merged

**Comment by droidrcc** [comment]
Hi @wing328,

Is this available for all the other languages? It looks like generated Java clients, doesn't handle overridden servers into paths.

**Comment by wing328** [comment]
Can you try the latest master with the `jersey2` library in the Java client generator?

**Comment by droidrcc** [comment]
> Can you try the latest master with the `jersey2` library in the Java client generator?

Thanks @wing328. 

Tested with `openapi-generator-cli-5.0.0-beta2` and `jersey2` library in a generated java clients and worked. It doesn't seem to be the case with java and `okhttp-gson` library.

**Pull request merged**
