### PR TITLE
Update surefire to newer version 3.0.0

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@martin-mfg after updating surefire plugin to the latest stable version 3.0.0, `mvn clean package` shows some failed tests, e.g.

```
[main] INFO  com.tngtech.archunit.core.PluginLoader - Detected Java version 1.8.0_312
[ERROR] Tests run: 1994, Failures: 1, Errors: 0, Skipped: 18, Time elapsed: 80.97 s <<< FAILURE! - in TestSuite
[ERROR] org.openapitools.codegen.DefaultCodegenTest.testAnySchemaWithIneffectiveConstraints  Time elapsed: 0.029 s  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<0> but was:<9>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.Assert.assertEquals(Assert.java:241)
	at org.openapitools.codegen.DefaultCodegenTest.testAnySchemaWithIneffectiveConstraints(DefaultCodegenTest.java:4347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR] Failures: 
[ERROR]   DefaultCodegenTest.testAnySchemaWithIneffectiveConstraints:4347 expected:<0> but was:<9>
```

ref: https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/23130/workflows/044f5eea-87de-4734-acb5-d30fdf0be5bd/jobs/65494

I'm able to repeat the issue locally.

Do you have any clue why these tests failed? 

Thanks for your time taking a look at this matter.

**Comment by martin-mfg** [comment]
Hi,
the tests added in #14759 are not thread-safe. And apparently the new surefire version handles parallel test execution differently in some way, so that the missing thread-safety now becomes a problem where I wasn't a problem before.

The tests are not thread-safe because they all access [the same logger instance](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java#L62).

The problem can be solved by adapting the [pom.xml](https://github.com/OpenAPITools/openapi-generator/blob/65af7bf1d8f10c40b033eca87fdfe2847c1914ed/pom.xml#L176) a bit:
```diff
                 <version>${maven-surefire-plugin.version}</version>
                 <configuration>
                     <printSummary>true</printSummary>
-                    <parallel>classes</parallel>
-                    <threadCountClasses>3</threadCountClasses>
+                    <forkCount>3</forkCount>
                     <useSystemClassLoader>false</useSystemClassLoader>
                     <junitArtifactName>none:none</junitArtifactName>
                     <testNGArtifactName>org.testng:testng</testNGArtifactName>
```
This will execute the parallel tests in separate JVMs. see [documentation](https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html)

When testing this locally, I do however get this error:
```
[ERROR] Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.7:report (jacoco-site) on project openapi-generator: An error has occurred in JaCoCo report generation.: Error while creating report: malformed input around byte 0 -> [Help
 1]
```

JaCoCo is supposed to be compatible with forkCount >= 1 and I couldn't figure out what the problem here is.

An alternative solution could be to rewrite the tests from #14759 in a thread-safe way, although I'm not sure what would be a good approach to doing this.

**Comment by martin-mfg** [comment]
@wing328
Actually the mentioned JaCoCo problems might occur only on my local machine. I tested my discussed changes via CircleCI, and it looks good. i.e. no JaCoCo problems and no https://github.com/OpenAPITools/openapi-generator/pull/14759 tests failing. Only some unrelated python and typescript failures. :-)
[tested changes](https://github.com/OpenAPITools/openapi-generator/compare/surefire-update...martin-mfg:openapi-generator:issue15321-surefire)
[test results](https://github.com/martin-mfg/openapi-generator/pull/4)

**Comment by wing328** [comment]
looks like https://github.com/OpenAPITools/openapi-generator/pull/15407 fixed it. Will use that PR instead.

**Pull request closed without merging**
