### PR TITLE
[kotlin-client] Add support okhttp3 and Android 4.x

### PR DESCRIPTION
**Pull request by 4brunu**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04)

This PR adds support for Add support okhttp3 and Android 4.x and fixes https://github.com/OpenAPITools/openapi-generator/issues/4007

### CODE REVIEW

**Comment by wing328** [comment]
@4brunu thanks for the PR. What about naming the option as "library" instead to make it more consistent with other generators (e.g. Java, Ruby) when it comes to supporting more than 1 HTTP library?

**Comment by 4brunu** [comment]
@wing328 it's done, I also rerun the tests and the pet projects 🙂

**Comment by wing328** [comment]
@4brunu sorry I was not clear. I mean something like https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RubyClientCodegen.java#L146-L154

**Comment by wing328** [comment]
and for Java client: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java#L149-L161

**Comment by 4brunu** [comment]
Hi, I was trying to do the changes but now the generator with the pet projects it's not working.
I tried to look at the code but I can't find what's wrong.
Maybe renaming jvm to jvm-okhttp3 and jvm-okhttp4?

Here is the [commit](https://github.com/4brunu/openapi-generator/commit/7190a8047aaffc2c0e6088ae02fdc0e6939c64dd) and the logs.
It looks like it can't find a file.
Can you please take a look at it?
Because I don't know what's wrong :S

<details>
  <summary>Log</summary>
# START SCRIPT: bin/kotlin-client-okhttp3.sh
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: kotlin (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'kotlin' is considered stable.
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] INFO  o.o.c.l.AbstractKotlinCodegen - Environment variable KOTLIN_POST_PROCESS_FILE not defined so the Kotlin code may not be properly formatted. To define it, try 'export KOTLIN_POST_PROCESS_FILE="/usr/local/bin/ktlint -F"' (Linux/Mac)
[main] INFO  o.o.c.l.AbstractKotlinCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/models/ApiResponse.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/ApiResponse.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/models/Category.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/Category.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/models/Order.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/Order.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/models/Pet.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/Pet.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/models/Tag.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/Tag.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/models/User.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/User.md
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.DefaultCodegen - Multiple MediaTypes found, using only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.DefaultCodegen - Multiple MediaTypes found, using only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in content, returning only the first one
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/PetApi.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/PetApi.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/StoreApi.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/src/main/kotlin/org/openapitools/client/apis/UserApi.kt
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/docs/UserApi.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/README.md
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/build.gradle
[main] INFO  o.o.codegen.AbstractGenerator - writing file /Users/bruno.coelho/Developer/openapi-generator/samples/client/petstore/kotlin-okhttp3/settings.gradle
[main] ERROR o.o.codegen.AbstractGenerator - kotlin-client/infrastructure/ApiClient.kt.mustache (No such file or directory)
[main] ERROR o.o.codegen.AbstractGenerator - kotlin-client/infrastructure/ApiClient.kt.mustache (No such file or directory)
[main] ERROR o.o.codegen.AbstractGenerator - can't load template kotlin-client/infrastructure/ApiClient.kt.mustache
[main] ERROR o.o.codegen.AbstractGenerator - can't load template kotlin-client/infrastructure/ApiClient.kt.mustache
Exception in thread "main" java.lang.RuntimeException: Could not generate supporting file 'SupportingFile:
	templateFile: infrastructure/ApiClient.kt.mustache
	folder: src/main/kotlin/org/openapitools/client/infrastructure
	destinationFilename: ApiClient.kt
'
	at org.openapitools.codegen.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:751)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:930)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:408)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
Caused by: java.lang.RuntimeException: can't load template kotlin-client/infrastructure/ApiClient.kt.mustache
	at org.openapitools.codegen.AbstractGenerator.readTemplate(AbstractGenerator.java:122)
	at org.openapitools.codegen.DefaultGenerator.getFullTemplateContents(DefaultGenerator.java:941)
	at org.openapitools.codegen.templating.MustacheEngineAdapter.compileTemplate(MustacheEngineAdapter.java:51)
	at org.openapitools.codegen.DefaultGenerator.generateSupportingFiles(DefaultGenerator.java:723)
	... 3 more
cp: CI/samples.ci/client/petstore/kotlin-okhttp3/pom.xml: No such file or directory
</details>

Can you please check the [commit](https://github.com/4brunu/openapi-generator/commit/7190a8047aaffc2c0e6088ae02fdc0e6939c64dd) to see if this is was you had in mind?

Since kotlin has the concept of jvm and multiplatform library, I'm not sure if it works nice to have a jvm-okhttp4 and jvm-okhttp3.
What do you think?

**Comment by wing328** [comment]
> Maybe renaming jvm to jvm-okhttp3 and jvm-okhttp4?

Sounds good to me

**Comment by wing328** [comment]
> Can you please check the commit to see if this is was you had in mind?

I'll try to find some time to review later today.

**Comment by wing328** [comment]
Can you please push https://github.com/4brunu/openapi-generator/commit/7190a8047aaffc2c0e6088ae02fdc0e6939c64dd to this branch/PR when you've time? Easy for me to try to it and figure out what's wrong.

**Comment by 4brunu** [comment]
@wing328 done. thanks for helping 👍

**Comment by wing328** [comment]
@4brunu I've figured out the reason and got a "workaround' to make with all 3 different library settings. Please PM tomorrow (Thur) via Slack when you've tim.

Slack channel: https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by 4brunu** [comment]
Thanks for the help, now it's working 🙂 
The CI is failing, but I took a look at the logs and I think this is not related to the changes in this PR.
Please let me know if there any more changes required to merge this PR.
Thanks 👍

**Comment by 4brunu** [comment]
Don't merge this branch! After doing some more tests, It's not working.

**Comment by 4brunu** [comment]
@wing328 the Serialisation and Parcelable/Parcelize features stop working.

When migrating to library it stoped working... 
Here was working https://github.com/OpenAPITools/openapi-generator/pull/4008/commits/7190a8047aaffc2c0e6088ae02fdc0e6939c64dd and after that it's nor working.

Here is a screenshot that shows what's wrong in the models.
Screenshot 2019-10-03 at 14 36 15

The generator is not generating the imports and `@Json(name = "...")`

Do you have any idea why?

**Comment by 4brunu** [comment]
@wing328 sorry for the spam...
I updated the test case to have the correct output.
This way is very simple to test issue.
You checkout this branch, run the following command `sh bin/kotlin-client-all.sh` and in your git, you shouldn't see any change.
If you see any change (you will) that's the issue that shouldn't happen.
Thanks 🙂

**Comment by 4brunu** [comment]
@wing328 Sorry for all of this, but it's now fixed.
I removed a flag jvm -> true that was still necessary that I thought that wasn't, and that tah was used in some places.
But now with the last commit https://github.com/OpenAPITools/openapi-generator/pull/4008/commits/5b9dc22a86245e3bd14f4b4772601b859c1b305a everything is working again.
For me this can now be merged.

**Comment by wing328** [comment]
CI failure not related to this PR.

**Pull request merged**
