### PR TITLE
[Dart] Convert `DioError` to `DioException`

### PR DESCRIPTION
**Pull request by Rexios80**
The class `DioError` has been deprecated in favor of `DioExcption`

https://pub.dev/packages/dio/changelog#520

This command didn't run on my machine: `./bin/utils/export_docs_generators.sh`

@jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Review by ahmednfwela — APPROVED** [review]

**Comment by wing328** [comment]
@Rexios80 thanks for the PR. Can you please take a look at the CI failure when you've time?

https://github.com/OpenAPITools/openapi-generator/actions/runs/5201409315/jobs/9393144388?pr=15783

**Comment by Rexios80** [comment]
@wing328 It seems to be a dependency resolution issue. The workflow uses Dart `2.15.0` which is probably too old to resolve all sub-dependencies. Should we update it? If so what version should we update it to?

**Comment by wing328** [comment]
Dart 2.15.0 was released on Dec 2021: https://dart.dev/guides/language/evolution#dart-215

With this change, we completely drop Dart 2.15.0 support? What's the minimum version the auto-generated Dart SDK will support in the upcoming v7.0.0 release?

Is everyone ok with that?

I can't seem to find EOL of Dart releases. If anyone has the info, Please share.

cc @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

**Comment by ahmednfwela** [comment]
It's not a problem with dart version, it's just for some reason pulling dio 5.0.0 as can be seen here
https://github.com/OpenAPITools/openapi-generator/actions/runs/5201409315/jobs/9393144388?pr=15783#step:7:876

this is because you forgot to change the dio version in the test project here, since it doesn't get auto generated
https://github.com/OpenAPITools/openapi-generator/blob/113cf9db40ea6c4405d70a87b763636b1ddf334c/samples/openapi3/client/petstore/dart-dio/petstore_client_lib_fake_tests/pubspec.yaml#LL13C3-L13C6

**Comment by kuhnroyal** [comment]
@Rexios80 Can you please bump dio to 5.2.1 - (5.2.0+2) does actually not exist - see my PR here: https://github.com/cfug/dio/pull/1861

Also, with this change we do drop support for dio < 5.2.0 so we need to raise it in the `pubspec.mustache` template.


@wing328 This will still support Dart 2.15

**Comment by kuhnroyal** [comment]
@Rexios80 I think you need to regenerate samples with the new dio version

**Comment by kuhnroyal** [comment]
@wing328 Can you please approve?

**Review by kuhnroyal — APPROVED** [review]

**Comment by wing328** [comment]
CI tests still failed: https://github.com/OpenAPITools/openapi-generator/actions/runs/5254958800/jobs/9516265653?pr=15783

please take another look when you've time.

**Comment by kuhnroyal** [comment]
Yea not all samples seem to be up-to-date.
@Rexios80 Please run `./bin/generate-samples.sh bin/configs/dart*` again and see if there are any changes.

**Comment by Rexios80** [comment]
There weren't any changes. I already ran `./bin/generate-samples.sh bin/configs/dart-*` which I think caught them all

The files the tests are complaining about don't contain any references to `DioError` (in fact the entire root project doesn't) so I'm not exactly sure what's going on.

**Comment by kuhnroyal** [comment]
There are probably new changes on the master branch which you need to merge into your branch before.

**Review by amondnet — APPROVED** [review]

**Comment by wing328** [comment]
can you please run the script to regenerate the samples one more time?

https://github.com/OpenAPITools/openapi-generator/actions/runs/5266780237/jobs/9543293287?pr=15783

**Comment by wing328** [comment]
updated samples via https://github.com/OpenAPITools/openapi-generator/pull/15783/commits/e2480460d93223673f9dc1e832c83824a2d38a7c

let's see how that goes

**Pull request merged**
