### PR TITLE
[dart-dio-next] Removes dioLibrary option

### PR DESCRIPTION
**Pull request by josh-burton**
As there is no longer a fork of the dio library this option can be removed
#10305

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela

### CODE REVIEW

**Review by kuhnroyal — APPROVED** [review]

**Comment by wing328** [comment]
The Dart 2.1.0 tests failed: https://github.com/OpenAPITools/openapi-generator/runs/4415838129?check_suite_focus=true

Can you please take a look when you've time?

**Comment by ahmednfwela** [comment]
@wing328 looks like a typical maven timeout

**Comment by wing328** [comment]
Yup, I restarted it but no luck. Will give it another try tomorrow.

**Comment by wing328** [comment]
@josh-burton can you please resolve the merge conflicts when you've time? Then I'll merge. Thanks.

**Pull request merged**
