### PR TITLE
Improved Elixir Code Generation

### PR DESCRIPTION
**Pull request by halostatue**
Mostly addresses #12731, but I consider this to be incomplete (yet still complete enough for review), because there are still some compiler warnings (due to duplicate `@docs` specifications). However, those compiler warnings are best handled by *changing* how the Tesla client is created, and I didn’t want to introduce that change at the same time as these other changes, which reduce the number of warnings from hundreds to one in the pet store example for Elixir.

- Bumped minimum Elixir version to 1.10 instead of 1.6. There are behaviours deprecated since Elixir 1.9 (June 2019) and desired behaviours implemented since Elixir 1.10 (`Application.compile_env/2` instead of `Application.get_env/2`).
- Bumped the minimum version of Tesla to 1.4 instead of 1.2.
- Added a default `.formatter.exs` file so that `mix format` can be run in the generated codebase.
- Added `atom` and `env_var` lambdas for Mustache to generate *cleaner* code (this is the major source of warning reduction).
- Updated `config.exs.mustache` and added `runtime.exs.mustache` to bring configuration up to modern Elixir form.
- Fixed a Language Server Warning
- Regenerated the `openapi_petstore` example code based on all of the above changes.
- Addresses #12484 since we were already making similar changes.

I have made this PR against `master`, because *although* it drastically changes the output of the Elixir output, the generated code will bet *better* for adoption within the Elixir community. We can retarget it as appropriate, but I do not believe that this change should wait until the release of 7.0.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.0.1) (patch release), `6.1.x` (breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by halostatue** [comment]
@mrmstn

**Comment by mrmstn** [comment]
@halostatue 
Oh, wow, that looks fantastic!

I'm currently on holiday so I won't be able to test out your changes in detail but the PetStore looks pretty great with the new changes 😁 

I also love the lambda function approach! I once tried to fixe the atom warning issue with another approach (but wasn't happy with it, so it didn't make it) so your solution is probably the most elegant as it can get 😁!

**Comment by wing328** [comment]
@halostatue thanks for the PR.

@mrmstn thanks for the review.

I ran the tests locally but got the following errors:
```
== Compilation error in file lib/openapi_petstore/model/name.ex ==
** (SyntaxError) lib/openapi_petstore/model/name.ex:15:5: unexpected token: ":" (column 5, code point U+003A)
    |
 15 |     :123Number
    |     ^
    (elixir 1.13.4) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  33.057 s
[INFO] Finished at: 2022-07-01T14:05:14+08:00
[INFO] ------------------------------------------------------------------------
```

To run the test, please excute `mvn integration-test -f samples/client/petstore/elixir/pom.xml`

( you will need to run the petstore server locally: https://github.com/OpenAPITools/openapi-generator/wiki/Integration-Tests)

**Comment by halostatue** [comment]
That’s an easy fix to make with the regex pattern. In that case, it should definitely be quoted. I’ll push up a change.

I’m using `./run-in-docker.sh` for *everything*, so I’m not sure what would be needed to do in order to run the integration tests with that.

**Comment by halostatue** [comment]
@wing328 the latest commit is has some details in the commit message. I’m lifting them here, because I believe that the changes may be slightly controversial.

Improve regex (again), remove files not generated

- The previous commit resulted in a number of warnings that were still present and so I played with the regular expression. This did not solve the problem, but the resulting regular expression is *much* better than the previous one, so I'm keeping it.

- The problem was that the configuration (`bin/configs/elixir.yaml`) is generated using a 3.0 input spec:

  ```yaml
  inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
  ```

  Which means that there were 16 files committed which were no longer being generated. When I tested with the 2.0 input spec:

  ```yaml
  inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
  ```

  The files were generated again. I *believe* that the correct change here is to switch back to the 2.0 input spec, as it tests more code generation, but I wanted to check in before I did this.

  The following files are deleted:

  - `elixir/lib/openapi_petstore/model/additional_properties_any_type.ex`
  - `elixir/lib/openapi_petstore/model/additional_properties_array.ex`
  - `elixir/lib/openapi_petstore/model/additional_properties_boolean.ex`
  - `elixir/lib/openapi_petstore/model/additional_properties_integer.ex`
  - `elixir/lib/openapi_petstore/model/additional_properties_number.ex`
  - `elixir/lib/openapi_petstore/model/additional_properties_object.ex`
  - `elixir/lib/openapi_petstore/model/additional_properties_string.ex`
  - `elixir/lib/openapi_petstore/model/big_cat.ex`
  - `elixir/lib/openapi_petstore/model/big_cat_all_of.ex`
  - `elixir/lib/openapi_petstore/model/inline_response_default.ex`
  - `elixir/lib/openapi_petstore/model/special_model_name.ex`
  - `elixir/lib/openapi_petstore/model/type_holder_default.ex`
  - `elixir/lib/openapi_petstore/model/type_holder_example.ex`
  - `elixir/lib/openapi_petstore/model/xml_item.ex`
  - `elixir/pom.xml`
  - `elixir/test/pet_test.exs`

  In the interim, I have removed those files from the commit.

**Comment by wing328** [comment]
We need the following for tests:
```
elixir/pom.xml
elixir/test/pet_test.exs
```

I added these backs and the result is good:
```
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  earmark_parser 1.4.26
  ex_doc 0.28.4
  makeup 1.1.0
  makeup_elixir 0.16.0
  makeup_erlang 0.1.1
  mime 1.6.0
  nimble_parsec 1.2.3
  poison 3.1.0
  tesla 1.4.3
All dependencies are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (test) @ ElixirPetstoreClientTests ---
You have configured application :open_api_petstore in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :open_api_petstore exists or remove the configuration.

...

Finished in 0.6 seconds (0.00s async, 0.6s sync)
3 tests, 0 failures

Randomized with seed 331006
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.360 s
[INFO] Finished at: 2022-07-03T17:25:57+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by wing328** [comment]
FYI. Added back test files via 72b4189f76a

**Pull request merged**
