### PR TITLE
Enable enumPropertyNaming for java generators

### LINKED ISSUE #18987: [REQ][Java][Server][Spring]  Add support for enumPropertyNaming config option in spring server generator
### Is your feature request related to a problem? Please describe.

The **enumPropertyNaming** config option is not supported by the Spring server generator, and all enum properties are generated in upper-case. Having an enum with lower-case properties in the API definition causes the following problem:

- In GET requests, the client has to send enum values in upper-case because the server uses Enum.valueOf(String) to create an enum instance from request parameters. The valueOf method expects enum values in upper-case.
- In POST requests, the client has to send enum values in lower-case because the server uses a generated fromValue method to create an enum instance from the request body. The fromValue method expects enum values in lower-case.

## Describe the solution you'd like

Implementation of the enumPropertyNaming option and setting it to the value 'original' (as in the Kotlin server) would resolve this problem. The generator would generate all enum properties as defined, without changing them to upper-case.

## Additional context

The workaround for this problem is to implement a custom type converter for the enum, which uses the generated fromValue method instead of the enum's valueOf. This converter will be used instead of the default converter for request parameters. However, this is only a workaround for the problem.

### LINKED ISSUE #19066: [BUG] Incorrect ENUM generation
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

ENUM is being generated with additional "_" character when there's a number on the ENUM name.

##### openapi-generator version

Issue started on 7.7.0, works fine on 7.7.6.

##### OpenAPI declaration file content or url

Example ENUM attribute in the YAML spec:

```
        myAttribute:
          description: this is a ENUM            
          type: string
          enum:
          - MOVE2STOCK
          - MOVE2SHELF
          - KEEP
```

##### Generation Details

Java 17, Gradle build.

##### Steps to reproduce

Add ENUM attribute to the spec that has numbers in the attribute name.
Generate java model using openapi generator 7.7.0.
Look into the source code generated, the ENUM attribute names will have an "_" after the number.

For example:

```
  public enum MyAttributeEnum {
    MOVE2_STOCK("MOVE2STOCK"),
    MOVE2_SHELF("MOVE2SHELF"),
    KEEP("KEEP"),
```

### PR DESCRIPTION
**Pull request by vad-systems**
Copied the enumPropertyNaming functionality from the Kotlin generator, with some adjustments to make it compliant with the current implementation of the `enumPropertyNaming=UPPERCASE` default case. Most notably, this implementation handles a few further special cases and is more lenient on stripping e.g. a leading underscore.

Users experiencing a change in naming when upgrading to a >=7.7 version should be able to use the `enumPropertyNaming=original` to restore the prior behaviour.

Pending:
- [ ] ~Test cases and samples~
- [x] Local check against cases broken on 7.6 -> 7.7 upgrade
- [x] Explicit test cases for the cases that changed between 7.6 and 7.7
- [x] Validate new `original` implementation restores old behaviour to a reasonable extent

Could potentially fix #19066 and resolve #18987 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.8.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by jpfinne** [comment]
It is good to have this option in the java generators.

I don't like the name original because it will not mean anything in the future. Maybe ALPHANUMERIC_UPPERCASE or UPPERCASE_WITHOUT_UNDERSCORE?

I wonder about he option camelCaseDollarSign. Should it be used as well for enum names?

**Comment by jpfinne** [comment]
I like the distinction between UPPERCASE/SCREAMING_SNAKE_CASE.
It would solve the legacy issue

**Comment by martin-mfg** [comment]
Hi @vad-systems, thanks for the PR!

For some `getEnumPropertyNaming()` values, the implementation tries to skip calling `toVarName`. This causes some inconsistencies between the different `getEnumPropertyNaming()` values. E.g. sometimes "\_\_\_" is transformed to "U" (or "u"), sometimes it stays unchanged: "\_\_\_".
Also, by skipping `toVarName`, we skip [resolving name mappings](https://github.com/OpenAPITools/openapi-generator/blob/0e763b096ebe35908868ebf2555732b90677a732/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L866).
It might be better to always call `toVarName`, and change `toVarName` so that it takes `getEnumPropertyNaming()` into consideration. Does that make sense?

**Comment by martin-mfg** [comment]
I have created [this commit](https://github.com/OpenAPITools/openapi-generator/commit/a33cfbcd95793d921250e2a3f84a62fa2026e8d0) to show how the adaptions could be done. This commit covers only the "original" enumPropertyNaming value, and it might be missing some edge cases. But it should be a good starting point.

Does this resolve the issues you mentioned? If not, could you give a concrete example what problems are coming up?

**Comment by wing328** [comment]
thanks for the PR.

I've filed https://github.com/OpenAPITools/openapi-generator/pull/19630 to add the option (MACRO_CASE, legacy)

please give it a try when you've time.

**Comment by martin-mfg** [comment]
> I've filed #19630 to add the option (MACRO_CASE, legacy)
> 
> please give it a try when you've time.

It seems the link is wrong and the new PR is actually https://github.com/OpenAPITools/openapi-generator/pull/20172.

**Comment by wing328** [comment]
updated the comment. thanks for pointing it out.

**Comment by wing328** [comment]
update: PR merged. please give it a try with the latest master or snapshot version.

closing this one for the time being

**Comment by jrxap** [comment]
@wing328 why was this PR not approved and  merged ?

**Pull request closed without merging**
