### PR TITLE
[typescript] Fix: any type (8 liner PR)

### PR DESCRIPTION
**Pull request by lwj5**
1 line change to fix Anytype in TS client.

Regenerated all samples but no changes.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### CODE REVIEW

**Review by amakhrov — COMMENTED** [review]
Thanks @lwj5 !
I'm currently looking at the earlier fix for other TS generate that addresses the same problem: https://github.com/OpenAPITools/openapi-generator/pull/6335/files#diff-e07b04e9dd1e4acea6c1d994fd38512f06fa272ca70e4bca3e8d9126e74e5ca0R167

It looks like in addition to the type mapping, that PR also removes `any` from composite type, thus avoiding things like `MyModel & any` in common use cases (which in TS is the same as `any` - hence unnecessarily loosens types).

Any thoughts about doing the same here?

**Comment by lwj5** [comment]
@amakhrov yes I noticed #6335 as well. When I opened the TS generator I saw that those changes were already there, but this line was missed out.

**Comment by lwj5** [comment]
p.s. checking again I released `AllOf` is missed out as well. Added that in.

**Review by amakhrov — APPROVED** [review]
Thanks!
It looks good to me.
Maybe also consider adding some tests?

**Comment by lwj5** [comment]
Sure, done :)

**Comment by wing328** [comment]
`modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java` also has this line of fix but TypeScriptClient codegen class doesn't extends `AbstractTypeScriptClientCodegen.java` at the moment.

In the future we may consider extending TypeScriptClient class with `AbstractTypeScriptClientCodegen`

**Pull request merged**
