### PR TITLE
Fix empty body in java apache client

### PR DESCRIPTION
**Pull request by wing328**
Send empty body instead of `null` when the http request body is not provided.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### CODE REVIEW

**Comment by jenspopp** [comment]
This fix causes "random" timeouts and errors if big objects are transferred. I have a special test case creating a random String with 100MB converting it to byte[] and byte[] to String to test encoding issues. Besides a very bad performance penalty (Test takes 3-5 min instead of 2) I get random errors:

com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: was expecting closing quote for a string value
in ApiClient.deserialize(ApiClient.java:745)

And on server side:

Failed to handle request: java.io.IOException: java.io.IOException: Failed to write
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveOutputStream.write(ResteasyReactiveOutputStream.java:225)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2171)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment2(UTF8JsonGenerator.java:1485)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment(UTF8JsonGenerator.java:1432)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegments(UTF8JsonGenerator.java:1315)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:511)
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:41)


I assume that if the "wrong" random String is generated it will cause the Scanner to fail. I hit the issue about ever 2nd to 3rd run with scanner, have never had it without. Additionally the small buffer size in scanner seems to make it slow in the large stream use case.

**Comment by wing328** [comment]
I wonder if you can try to patch the client with other ways to convert stream into string as mentioned in https://stackoverflow.com/questions/309424/how-do-i-read-convert-an-inputstream-into-a-string-in-java and see one works flawlessly in your use cases.

**Comment by jenspopp** [comment]
Hi, did only the ByteArrayOutputStream test each with ca. 100MB String and byte[] (json encoded). It was only one run, so no "statistics". Since Scanner of Java 17 has about the Performance of BAOS in both Java 11 and 17 I assume there was some fix done on Scanner. There is also some impact on the performance depending on the TLS encryption. But that might also be due to the setup, server running in docker container on same machine as the client.

Scanner:
Java 17.0.6.10:
https
convert took: 4819 ms
convert took: 6233 ms

http
convert took: 1893 ms
convert took: 1551 ms

Java 11.0.18.10
https
convert took: 79221 ms
convert took: 113911 ms

http
convert took: 81560 ms
convert took: 116759 ms

ByteArrayOutputStream (8)

Java 17.0.6.10:
https
convert took: 4542 ms
convert took: 5721 ms

http
convert took: 1496 ms
convert took: 1400 ms

Java 11.0.18.10
https
convert took: 4430 ms
convert took: 5849 ms

http
convert took: 1905 ms
convert took: 1626 ms

**Comment by wing328** [comment]
@jenspopp fyi. there's a PR to update httpclient version from 4.x to 5.x. Not sure if that will fix the issue you encountered: https://github.com/OpenAPITools/openapi-generator/pull/14673

**Comment by jenspopp** [comment]
Hi, thanks. I will try that out, once it is in the official release. For now I have a working solution, since we anyhow patch some templates (UTF8 issue with Apache, takes default if not explicitly set), some issue with read only values in inheritance and others.

**Comment by wing328** [comment]
fyi. we've merged #14673. you can give the snapshot version a try .(links in the project's readme)

**Pull request merged**
