### PR TITLE
Fix undefined object in Python model __copy__ template

### PR DESCRIPTION
**Pull request by tuanchien**
Implements the recommended fix for issue #10856, a Python client bug in the mustache template that causes model copies to fail due to trying to return an undefined object.

Changes the template for the `__copy__` method to return `cls.__new__(cls, **self.__dict__)` instead of `new_cls.__new__(cls, **self.__dict__)`

Tagging Python committee:
@taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess @arun-nalla @spacether

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by spacether** [comment]
Closing and re opening to kick off ci

**Comment by tuanchien** [comment]
@spacether I've rebased the latest master onto this branch and re-run bin/generate-samples.sh

Might need you to rerun the tests. The failures for node0,1,2 look related to the CI servers.

**Comment by tuanchien** [comment]
@spacether Rebased again off master today. All tests passing.

**Review by spacether — APPROVED** [review]
Looks great, thank you for the PR!

**Pull request merged**
