### PR TITLE
[WIP] Add Julia client generator (beta)

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

For https://github.com/OpenAPITools/openapi-generator/issues/782

TODO:
- use camel case for file names
- replace "Swagger" with "OpenAPI" in the templates
- add style guide to contributing guideline: https://docs.julialang.org/en/v0.6.2/manual/style-guide/

cc @log0ymxm, @tanmaykm

To Julia pet store samples, please run `./bin/julia-petstore.sh` or `bin\windows\julia-petstore.bat`

### CODE REVIEW

**Comment by binarycrayon** [comment]
Just checking in, this is never merged to master?

**Comment by sa-** [comment]
Appears so

**Comment by PeterBaker0** [comment]
Any word on this? We may have a use case where a julia generator would be helpful.

**Comment by wing328** [comment]
@PeterBaker0 may I know if you've time to contribute the generator (based on this branch) or sponsor the community to create one (based on this one or create a new one from scratch) ?

**Comment by PeterBaker0** [comment]
@wing328 potentially - just curious about the status of the branch you have made here. It looks you finished a beta version of the generator? Was this working/complete? If so, what would be the next steps to get this merged/approved? If 80% of the work has been done there's no point starting from scratch.

**Comment by wing328** [comment]
I'm no expert in Julia and never test the output. It's based on works from others.

Feel free to give it a try. if you think it's not a starting point and better create this from scratch, then please feel free to do so.

**Comment by wing328** [comment]
closed via #14520

**Comment by wing328** [comment]
For those who are looking for a Julia client/server generator, please refer to the PR https://github.com/OpenAPITools/openapi-generator/pull/14520 instead, which has been merged and included in openapi-generator v6.3.0 :https://twitter.com/oas_generator/status/1620828275001167873

**Pull request closed without merging**
