### PR TITLE
[kotlin][client] add option to support non-ascii headers in okhttp

### LINKED ISSUE #20330: [BUG][Kotlin] java.lang.IllegalArgumentException: Unexpected char when using non-ascii chars in headers
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

ApiClient throws an exception when building request with header value that contains non-ascii characters. In our case this is uploaded file name.

##### openapi-generator version

7.10.0

##### OpenAPI declaration file content or url

Any spec with header parameters

##### Generation Details

Generator: kotlin
Library: jvm-okhttp4 (default)

##### Steps to reproduce

Try to fill header value with non-ascii string.

##### Related issues/PRs

Similar issue for java client: https://github.com/OpenAPITools/openapi-generator/issues/9053

##### Suggest a fix

Okhttp `Headers.Builder` has a `addUnsafeNonAscii` method. We should add an option to use this method for specific clients.

### PR DESCRIPTION
**Pull request by Djaler**
Fixes #20330

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@Djaler thanks for the PR.

Do we need an option for this change? In other words, using the non ascii method should work for both ascii and non ascii input, right?

**Comment by Djaler** [comment]
Guy from okhttp said `Please use only ASCII characters in your headers. If you are interoperaring with a system that incorrectly uses other characters, use addUnsafeNonAscii() on Headers.Builder.` https://github.com/square/okhttp/issues/6347#issuecomment-717887822

**Comment by Djaler** [comment]
So, technically, we can enable this by default, but I don't sure that we should

**Comment by wing328** [comment]
I see. thanks for the explanation. 

we can go with what you've so far

thanks again for the PR

**Pull request merged**
