### PR TITLE
[python] Issue 13997 fix pass in model instances to new

### PR DESCRIPTION
**Pull request by spacether**
[python] Issue 13997 fix pass in model instances to new
This PR is synonymous with https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/82

@Linux13524
With my update, this test code passes when the models from the issue were generated:
```
ev = event.Event(name="test", properties={"name": "test"})
er = event_request.EventRequest(event=ev)
self.assertEqual(
    er,
    {
        'event': {
            'name': 'test',
            'properties': {'name': 'test'}
        }
    }
)
```

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by OmarBouslama** [comment]
Hello
Thank you for the fix. When is the next tag planned with this fix included ?

**Comment by spacether** [comment]
Not sure, whenever @wing328 decides to do a release

**Comment by OmarBouslama** [comment]
ok, we would really appreciate a new release soon if this is possible. In fact this issue is blocking us from generating (and updating old SDKs) SDKs with the lastest openapi-generator

**Comment by spacether** [comment]
If you need this sooner, how about using this release?
https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/releases/tag/1.0.4

**Comment by OmarBouslama** [comment]
what is the difference between openapi-generator and [openapi-json-schema-generator](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator) ?

**Comment by spacether** [comment]
openapi-json-schema-generator contains the python generator only and the project's goals and histor are described in its readme here: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator#5---about-us

**Pull request merged**
