### PR TITLE
[Java] Fix #14276 Java Templates uses jakarta or javax package if useJakartaEe is enabled 

### LINKED ISSUE #14276: [Java][resttemplate] Update spring-web to the latest 6.x
Update spring-web to the latest 6.x, which requires updating ApiClient.java and more to address the compilation errors.

If anyone wants to fix this, please reply to let me know. Thank you.

### PR DESCRIPTION
**Pull request by parenko**
This PR (re)introduces `useJakartaEe` additional property to support generation of jakarta or java package in Java templates.
A new sample `resttemplate-jakarta` uses `useJakartaEe` and runs without compilation errors.

The java template for `resttemplate` library uses with enabled option `useJakartaEe` currently latest spring-web 6.0.3 version.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Java | @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)
-- | --

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by parenko** [comment]
@wing328, thank you for bringing this to my attention. Also the reference was helpful :)

**Comment by wing328** [comment]
LGTM. Will try to enhance the tests after merging this PR.

**Comment by wing328** [comment]
@parenko I got errors below when running `mvn integration-test -f samples/client/petstore/java/resttemplate-jakarta/pom.xml`

```
[ERROR]   symbol:   class MultiValueMap
[ERROR]   location: class org.openapitools.client.auth.OAuth
[ERROR] /Users/williamcheng/Code/openapi-generator8/samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/auth/OAuth.java:[19,74] cannot find symbol
[ERROR]   symbol:   class HttpHeaders
[ERROR]   location: class org.openapitools.client.auth.OAuth
[ERROR] /Users/williamcheng/Code/openapi-generator8/samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/auth/OAuth.java:[19,100] cannot find symbol
[ERROR]   symbol:   class MultiValueMap
[ERROR]   location: class org.openapitools.client.auth.OAuth
[ERROR] /Users/williamcheng/Code/openapi-generator8/samples/client/petstore/java/resttemplate-jakarta/src/main/java/org/openapitools/client/api/PetApi.java:[32,2] cannot find symbol
[ERROR]   symbol: class Component
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

can you please take a look when you've time?

**Comment by wing328** [comment]
cc @borsch

**Comment by parenko** [comment]
@wing328 , do you still get this error with following command?
`mvn clean integration-test -U -f samples/client/petstore/java/resttemplate-jakarta/pom.xml`

**Comment by wing328** [comment]
same error

are you able to to repeat the issue locally?

I'm using JDK 11
```
openjdk version "11.0.13" 2021-10-19
```

**Comment by parenko** [comment]
I used JDK 17. run without errors.

[Spring Framework states following](https://docs.spring.io/spring-framework/docs/current/reference/html/overview.html#overview):
> As of Spring Framework 6.0, Spring requires Java 17+.

**Comment by wing328** [comment]
Ok. Will add a test with JDK17 in the workflow.

**Comment by borsch** [comment]
@parenko @wing328 for rest-template & webclient when we use Spring 6, then we have to use java 17. Please fix `maven-compiler-plugin` in pom.xml when `useJakartaEE=true`

**Comment by parenko** [comment]
@borsch @wing328 correction is in #14360

**Comment by wing328** [comment]
merged. thanks for the quick action.

**Pull request merged**
