### PR TITLE
[ASP.NET Core]Switch registry to MCR for dotnet images

### PR DESCRIPTION
**Pull request by etherealjoy**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
Switch dotnet image registry to MCR to pull latest sha for dotnet tags

Please see
https://github.com/dotnet/announcements/issues/101

https://devblogs.microsoft.com/dotnet/net-core-container-images-now-published-to-microsoft-container-registry/

@jimschubert @wing328

### CODE REVIEW

**Comment by etherealjoy** [comment]
I reverted 2.0 `Dockerfile`. It is no longer maintained by MS.
Please see here 
https://devblogs.microsoft.com/dotnet/net-core-2-0-will-reach-end-of-life-on-september-1-2018/

**Comment by jimschubert** [comment]
@etherealjoy can you elaborate on

> Switch dotnet image registry to MCR to pull latest sha for dotnet tags

The announcement says that floating tags will continue to be serviced on Docker Hub, which would suggest these tags will continue to be updated while Microsoft supports the image. I agree with pulling directly from the MCR to avoid synchronization issues, but I want to understand what may consorting may lead to other issues.

**Comment by etherealjoy** [comment]
Latest sha arrives on mcr first from what I observe. So latest images are available always.
And mcr is served by region based MS CDN.

**Comment by jimschubert** [comment]
Thanks. That's what I assumed. I just wanted to make sure I wasn't missing something additional (if, for example, an issue was raised for Dockerfile implementations before this change).

**Pull request merged**
