### PR TITLE
[REQ] Java Microprofile REST Client Template

### PR DESCRIPTION
**Pull request by patricktiu**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This PR provides implementation for feature request #2272.

cc
@bbdouglas  @sreeshas @jfiala @lukoyanov @cbornet  @jeff9finger  @karismann (2019/03) @Zomzog

### CODE REVIEW

**Comment by wing328** [comment]
@patricktiu instead of creating another generator for Java client, what about adding Microprofile support to the existing Java client generator via the `library` option?

```
	library
	    library template (sub-template) to use (Default: okhttp-gson)
	        jersey1 - HTTP client: Jersey client 1.19.x. JSON processing: Jackson 2.8.x. Enable Java6 support using '-DsupportJava6=true'. Enable gzip request encoding using '-DuseGzipFeature=true'. IMPORTANT NOTE: jersey 1.x is no longer actively maintained so please upgrade to 'jersey2' or other HTTP libaries instead.
	        jersey2 - HTTP client: Jersey client 2.25.1. JSON processing: Jackson 2.8.x
	        feign - HTTP client: OpenFeign 9.x or 10.x. JSON processing: Jackson 2.8.x. To enable OpenFeign 10.x, set the 'feignVersion' option to '10.x'
	        okhttp-gson - [DEFAULT] HTTP client: OkHttp 3.x. JSON processing: Gson 2.8.x. Enable Parcelable models on Android using '-DparcelableModel=true'. Enable gzip request encoding using '-DuseGzipFeature=true'.
	        retrofit - HTTP client: OkHttp 2.x. JSON processing: Gson 2.x (Retrofit 1.9.0). IMPORTANT NOTE: retrofit1.x is no longer actively maintained so please upgrade to 'retrofit2' instead.
	        retrofit2 - HTTP client: OkHttp 3.x. JSON processing: Gson 2.x (Retrofit 2.3.0). Enable the RxJava adapter using '-DuseRxJava[2]=true'. (RxJava 1.x or 2.x)
	        resttemplate - HTTP client: Spring RestTemplate 4.x. JSON processing: Jackson 2.8.x
	        webclient - HTTP client: Spring WebClient 5.x. JSON processing: Jackson 2.9.x
	        resteasy - HTTP client: Resteasy client 3.x. JSON processing: Jackson 2.8.x
	        vertx - HTTP client: VertX client 3.x. JSON processing: Jackson 2.8.x
	        google-api-client - HTTP client: Google API client 1.x. JSON processing: Jackson 2.8.x
	        rest-assured - HTTP client: rest-assured : 4.x. JSON processing: Gson 2.x. Only for Java8
	        native - HTTP client: Java native HttpClient. JSON processing: Jackson 2.9.x. Only for Java11+
```

**Comment by proubatsis** [comment]
Hi @wing328,

This change was based on the Java CXF Client as it is very similar to our needs. It is its own generator as opposed to being a library as part of the Java client. Are all new Java client generators supposed to be a treated as a library going forward?

**Comment by jmini** [comment]
> Are all new Java client generators supposed to be a treated as a library going forward?

@proubatsis:
No but it would ease the maintenance.
`Java CXF Client` not really maintained in comparison to the Java Client Generator.

**Comment by patricktiu** [comment]
I will try to refactoring the code into the Java client

**Comment by turkeylurkey** [comment]
@wing328 , I have a question about the many libraries supported by the Java generator. In this pull request the specialized generator creates a very limited number of files. Using the Java generator quite a few more files are created. Is there any attempt to create only the files absolutely needed or do the libraries of the Java generator create some extra files even if they do not need them?

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/4713

**Pull request closed without merging**
