### PR TITLE
[KotlinClient] okhttp: don't set default values for parameters

### LINKED ISSUE #12531: [BUG] [Kotlin-client] Handling default value of enum parameter
OpenAPIGenerator 6.0.0 produces incorrect kotlin code for a enum parameter with default value.

https://gist.github.com/joethehoff/7373e4b91b57531df6dc15162803f095

The generator produces following code:
```java
@Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun workOrdersGet(color: Color_workOrdersGet? = blue) : Unit {...}

    /**
     * enum for parameter color
     */
     enum class Color_workOrdersGet(val value: kotlin.String) {
         @Json(name = "blue") blue("blue"),
         @Json(name = "red") red("red"),
         @Json(name = "yellow") yellow("yellow"),
         @Json(name = "black") black("black")
     }

```
The kotlin compiler produces the error message:
Unresolved reference: blue

The generator configuration:
```xml
<configuration>
    <inputSpec>${project.basedir}/api/work-api.json</inputSpec>
    <generatorName>kotlin</generatorName>
    <generateApiTests>false</generateApiTests>
    <generateModelTests>false</generateModelTests>
    <apiPackage>xxx.controller</apiPackage>
    <modelPackage>xxx.gen.model</modelPackage>
    <apisToGenerate>WorkOrderServiceV2</apisToGenerate>
    <skipValidateSpec>true</skipValidateSpec>
    <configOptions>
        <enumPropertyNaming>camelCase</enumPropertyNaming>
    </configOptions>
    <additionalProperties>interfaceOnly</additionalProperties>
</configuration>
```

### PR DESCRIPTION
**Pull request by leonfau**
The kotlin client should not set optional default values for parameters. Optional values should be null by default. This results in errors for default enums like in Issue #12531.
fix #12531
@jimschubert , @dr4ke616 , @karismann , @Zomzog , @andrewemery , @4brunu , @yutaka0m 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by 4brunu** [comment]
Instead of removing this functionality, I would prefer to fix it.

**Comment by leonfau** [comment]
Hi @4brunu, thanks for your work!
I removed it, because in my opinion the client should not set the default values. I would prefer that the server is responsible to set the defaults, if no value is provided.

**Comment by 4brunu** [comment]
Hey, do you have a sample spec that show's this problem? Thanks

**Comment by leonfau** [comment]
Hi, with this example (https://gist.github.com/leonfau/5a4bc31c7b7321f53f31ce153777014a) it creates the following invalid code
`    fun findPetsByStatus(status: Status_findPetsByStatus = available) : kotlin.collections.List<Pet> {`

`available` can't be resolved.

**Comment by wing328** [comment]
can you please resolve the merge conflicts? 

other client generators do not set the default value for parameter. it only shows the default value in the docstring so i think it's ok to remove it from the kotlin client generator.

**Comment by 4brunu** [comment]
Since https://github.com/OpenAPITools/openapi-generator/pull/13404 was merge, I think this PR is no longer needed, because the issue with enum with default values is not fixed.
Can we close this one?

**Comment by wing328** [comment]
👌 let's close this

@leonfau please submit a new one if you still want your change to get reviewed and merged.

**Pull request closed without merging**
