### PR TITLE
Add `BearerAuthInterceptor` to `dart-dio` library exports

### PR DESCRIPTION
**Pull request by dickermoshe**
The `BearerAuthInterceptor` is missing from the generated library exports.
The other interceptors are included, so If we are exporting them, then it should be all or none

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by dickermoshe** [comment]
Yes.

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/6722183660/job/18271600240?pr=16960

looks like the samples are not yet updated

**Comment by dickermoshe** [comment]
You're right, I ran it on `dickermoshe/master` instead of `dickermoshe/patch-1`.
I'll do that now.

**Comment by dickermoshe** [comment]
@wing328 Please approve

**Comment by SkylL3r** [comment]
Any update on this PR ?

**Comment by wing328** [comment]
merged via https://github.com/OpenAPITools/openapi-generator/pull/19111

**Pull request closed without merging**
