### PR TITLE
[Kotlin Server] Update Ktor to latest version; move config to kts

### PR DESCRIPTION
**Pull request by e5l**
- Update the Ktor version in the Kotlin Server template to 2.3.12
- Migrate Ktor gradle configuration to Kotlin Script

technical committee: @stefankoppier

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

cc 
@dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)

**Comment by wing328** [comment]
shall we keep modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/build.gradle.mustache as some users may still prefer build.gradle (e.g. they've customized it with additional dependencies only available in their environment) ?

**Comment by e5l** [comment]
Hey @wing328, thank you for the notice.

According to our stats, less than 0.5% of users use the Groovy script, so we're considering it a legacy and not recommending it for new projects. (We can still add it if necessary.)

By the way, in Ktor support, we received feedback about the generator's confusing naming: while it's named Kotlin, it generates a Ktor server. At the same time, people are struggling to find the Ktor generator in the list. Could you tell me if we can rename it with the deprecation cycle?

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/11111807665/job/31270994762?pr=19727

can you please take a look when you've time?

**Comment by e5l** [comment]
Hey @wing328, thanks for the check.
It looks like the Gradle version was outdated.

Bumped to the latest. Could you please check?

**Comment by wing328** [comment]
@e5l please review the errors when you've time

maybe update gradle to 7.x instead which is still supported (not yet EOL)

**Comment by e5l** [comment]
Let me try to fix the errors first! It would be nice if we manage to have the latest one :)

**Comment by wing328** [comment]
>  It would be nice if we manage to have the latest one :)

not against using the latest version

but we usually test with old versions (not yet EOL) as well to ensure it still works with the auto-generated code

**Comment by e5l** [comment]
Sure, let me try to stick with the latest 7.* minor so

**Comment by e5l** [comment]
Force pushed an update to Gradle 7.3. Could you check?

**Comment by e5l** [comment]
Some samples are using 6.* API, let me update them

**Comment by e5l** [comment]
Fixed, please check it out

**Comment by e5l** [comment]
Bump to fix: https://github.com/gradle/gradle/issues/24390

**Comment by wing328** [comment]
what about filing a separate PR just to update Ktor to latest version and we can merge that one first?

**Comment by e5l** [comment]
Sure, done!

**Comment by wing328** [comment]
https://app.circleci.com/pipelines/gh/OpenAPITools/openapi-generator/31893 

that can be ignored

if no one has further feedback, i'll merge it tomorrow (Fri)

thanks again for the PR

**Comment by e5l** [comment]
No problem! Feel free to add me to the Kotlin reviewers if you need volunteers :)

**Comment by wing328** [comment]
> No problem! Feel free to add me to the Kotlin reviewers if you need volunteers :)

Sure, will do. Thanks for joining us 👍

**Comment by wing328** [comment]
> According to our stats, less than 0.5% of users use the Groovy script, so we're considering it a legacy and not recommending it for new projects. (We can still add it if necessary.)

I'm totally ok to decommission it but my guess is that there will be users who still prefer it.

If that occurs, we can add it back.

**Comment by wing328** [comment]
> By the way, in Ktor support, we received feedback about the generator's confusing naming: while it's named Kotlin, it generates a Ktor server. At the same time, people are struggling to find the Ktor generator in the list. Could you tell me if we can rename it with the deprecation cycle?

it's named `kotlin-server`: https://github.com/OpenAPITools/openapi-generator/blob/7f899dff97e57ea31353fd3e6c65f072a0da8b27/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinServerCodegen.java#L163

**Pull request merged**
