### PR TITLE
upgrade swagger-parser to latest version

### LINKED ISSUE #18429: [BUG] openapi-generator 7.5.0 is no longer able to resolve local $refs
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In openapi-generator 7.5.0, swagger-parser was upgraded to 2.1.19.  The same upgrade was done previously in openapi-generator 7.2.0 where it broke the generator's ability to resolve relative refs: https://github.com/OpenAPITools/openapi-generator/issues/17554.

The behavior described in the linked issue for 7.2.0 has been reintroduced in 7.5.0.  At some point, tests were added in an attempt to protect against breaking changes in parser upgrades, but those tests either didn't run or they didn't fail.

##### Suggest a fix

Previously the swagger-parser upgrade was reverted.  There are now a couple swagger-parser releases after 2.1.19 (the latest release is 2.1.22) and it's possible one of those releases includes a fix for the ref resolution issue, but if the tests that cover parser upgrades aren't working, it's harder to tell if the upstream issue was fixed.

### PR DESCRIPTION
**Pull request by ctreatma**
This upgrades swagger-parser to the latest release.  In manual testing, this upgrade restored the generator's ability to resolve external references in OpenAPI specs.

Fixes #18429 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR.

i'm looking into the gradle test issues

updating gradle to latest 7.x and 8.x didn't help as shown in https://github.com/OpenAPITools/openapi-generator/pull/18300

i'll try to contact Gradle team to see if they can help.

**Comment by ctreatma** [comment]
Tests are still failing with this error.  It could be a gradle bug but it feels like something else; note that the jackson version in the error message is `2.17.0`, but this PR updates from `2.15.3` to `2.16.2`.  I don't know where the `2.17.0` requirement is coming from.

```
Test: Test method openApiGenerate should reuse configuration cache[0](8.1.1)(org.openapitools.generator.gradle.plugin.GenerateTaskConfigurationCacheTest) produced standard out/err: java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file D:\a\openapi-generator\openapi-generator\modules\openapi-generator-gradle-plugin\build\tmp\test\work\.gradle-test-kit\caches\jars-9\970b4f5233619a1f72a6b180050ad4b0\jackson-core-2.17.0.jar.
```

**Comment by ctreatma** [comment]
Found some additional places to upgrade gradle versions and all checks are passing now.  @wing328 could you take a look?

**Comment by wing328** [comment]
nice 👍 

i'll take another later today

**Comment by wing328** [comment]
looks good. let's give it a try

**Comment by wing328** [comment]
saw the following in travis ci:
```
e: /home/travis/build/OpenAPITools/openapi-generator/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt: (746, 28): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

``
full log: https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds/270381537

can you please take a look when you've time?

**Pull request merged**
