### PR TITLE
[php-symfony] Update model_variables.mustache

### PR DESCRIPTION
**Pull request by Starkmann**
Recursive validate non primitive objects

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) ❤️, @ybelenko (2018/07), @renepardon (2018/12)

**Comment by ybelenko** [comment]
Did you update samples? Weird, no changes in samples at all.

**Comment by wing328** [comment]
Tested locally by  making `category` a required property, I got the following (partial result):
```diff
     /**
-     * @var OpenAPI\Server\Model\Category|null
+     * @var OpenAPI\Server\Model\Category
      * @SerializedName("category")
+     * @Assert\NotNull()
+     * @Assert\Valid()
      * @Assert\Type("OpenAPI\Server\Model\Category")
      * @Type("OpenAPI\Server\Model\Category")
      */
```

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/11810 has been merged to support Symfony 6. Please give it a try and let us know if you've any feedback or question.

**Pull request merged**
