### PR TITLE
[php][DefaultCodegen.java] Fix invalid enum const names

### PR DESCRIPTION
**Pull request by githubERIK**
@jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @ybelenko, @renepardon

Fix https://github.com/OpenAPITools/openapi-generator/issues/1475

### CODE REVIEW

**Comment by githubERIK** [comment]
The initial failing tests show that some enum number variable names were converted (-1.2 ENUM_NUMBER_MINUS_1_DOT_2) previously as well. The new changes added prefix `N` to the non-converted enum numbers and affected some of those previously converted variables too.

**Comment by githubERIK** [comment]
How is it possible that some enum `1` is transformed to `ENUM_INTEGER_1` while some numeric enums just stay the same?

**Comment by githubERIK** [comment]
Reverted add-N-prefix changes with https://github.com/OpenAPITools/openapi-generator/pull/3524/commits/aa36b80d9dc2d82c81aecddae8985b36a4ca1616 and https://github.com/OpenAPITools/openapi-generator/pull/3524/commits/d07efac2008644697b5edcf64842daa71a8efbb0.

The new approach, however, does not affect the clients which means that the changed method `toEnumVarName` is not called.

**Comment by githubERIK** [comment]
It seems to be a good idea to debug the generated jar and start with a breakpoint in DefaultCodegen and then perform "Step Into" when "importPath→OpenAPI\Client\Model.EnumTest" appears.

Screenshot 2019-08-09 at 10 20 29


and then see what happens with outerEnumInteger

```
    Enum_Test:
      type: object
      required:
        - enum_string_required
      properties:
        enum_string:
          type: string
          enum:
            - UPPER
            - lower
            - ''
        enum_string_required:
          type: string
          enum:
            - UPPER
            - lower
            - ''
        enum_integer:
          type: integer
          format: int32
          enum:
            - 1
            - -1
        enum_number:
          type: number
          format: double
          enum:
            - 1.1
            - -1.2
        outerEnum:
          $ref: '#/components/schemas/OuterEnum'
        outerEnumInteger:
          $ref: '#/components/schemas/OuterEnumInteger'
        outerEnumDefaultValue:
          $ref: '#/components/schemas/OuterEnumDefaultValue'
        outerEnumIntegerDefaultValue:
          $ref: '#/components/schemas/OuterEnumIntegerDefaultValue'
```

**Comment by githubERIK** [comment]
The final approach: change `postProcessModelsEnum` in DefaultCodegen.java to prevent adding enum variable names that are numbers. If number is detected, add a prefix `NUMBER_`.

Generated all samples by executing shell scripts in bin and bin/openapi3 folders.

**Comment by ybelenko** [comment]
Is this PR is still relevant or it should be closed?

**Comment by asabramo** [comment]
Hi guys,
I see this issue was reported 2 years ago.
When I use the latest:
swagger-codegen-cli-3.0.20.jar generate -l php -i api.yaml -o generated_api

I'm still seeing this issue, which means I can't use the files as they are generated - I have to add another step manually, which beats the purpose.

Oddly enough, when I use the version that the Jetbrains plugin retrieves automatically (https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.3/swagger-codegen-cli-3.0.3.jar) , the enum problem doesn't exist (but then there's another bug - BigDecimal instead of float). 

Is there a version where both issues are fixed?
Is there any workaround for the enum issue?
Thanks,
Assi

**Comment by ybelenko** [comment]
@asabramo It seems that you're talking about `Swagger Codegen` which is different project. More information you can read at: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md

About bug itself, I don't know whether it fixed or not. Maybe we should add part of the spec from related issue to samples and check PHP syntax of generated models with `phplint` package during CI.

**Pull request closed without merging**
