### PR TITLE
typescript-angular: Angular 10 support

### PR DESCRIPTION
**Pull request by patst**
Fixes https://github.com/OpenAPITools/openapi-generator/issues/7036

* Change default Angular Version to 10
* Update libraries for Angular 10
* Samples for Angular 10
* Samples for angular 9 for backwards compatibility

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### CODE REVIEW

**Comment by patst** [comment]
@macjohnny thanks for taking a look at it. 
Can you give me a hint how to fix the broken circle ci build? 

I ran
``` 
 ./bin/generate-samples.sh ./bin/configs/typescript-angular-v9-* 
 ./bin/generate-samples.sh ./bin/configs/typescript-angular-v10-* 
```

locally and committed the changes but this does not seem to help

**Comment by macjohnny** [comment]
Maybe the scripts need to be run on a unix system

**Comment by lwensveen** [comment]
> Maybe the scripts need to be run on a unix system

I presume he ran it in Git bash, which shouldn't differ from unix?

**Comment by patst** [comment]
> > Maybe the scripts need to be run on a unix system
> 
> I presume he ran it in Git bash, which shouldn't differ from unix?

I ran it on my Mac and in a Ubuntu docker container as well. Both resulted in now changes

**Comment by macjohnny** [comment]
Looking at e.g. https://github.com/patst/openapi-generator/blob/b860af74ce31c00f5fb35283b2526efc4100423d/samples/client/petstore/typescript-angular-v7-not-provided-in-root/builds/default/.openapi-generator/FILES the /./ seems to be present, too. I don‘t know why this happens, but you could also just edit the files manually and commit them to have the CI pass

**Comment by macjohnny** [comment]
@patst thanks for your contribution

**Pull request merged**
