### PR TITLE
[HttpBasicAuth] Use positive isBasicBasic tag instead of negative isBasicBearer

### PR DESCRIPTION
**Pull request by sebastien-rosset**
For HTTP basic auth, many mustache templates use a convention to negate the isBasicBearer tag, i.e. the case for HTTP basic auth is the negation of isBasicBearer. The problem is this only works when there are two possible HTTP auth, 1) basic auth and 2) bearer token. To support more http auth methods, we should stop using the negation of "isBasicBearer".

```
...
{{^isBasicBearer}}
   // do stuff for HTTP basic authentication
{{/isBasicBearer}}
{{#isBasicBearer}}
   // do stuff for bearer authentication
{{/isBasicBearer}}
....
```

I am proposing that instead, we change the templates as follows:
```
{{#isBasicBasic}}
   // do stuff for HTTP basic authentication
{{/isBasicBasic}}
{{#isBasicBearer}}
   // do stuff for bearer authentication
{{/isBasicBearer}}
....
```

I started making the change for Javascript. If that seems a reasonable change to reviewers, I can make the change everywhere.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by sebastien-rosset** [comment]
This should fix #5025

**Comment by sebastien-rosset** [comment]
See also #4993, #4959 and #4958, support for HTTP signature in core codegen, Python and golang.

**Comment by sebastien-rosset** [comment]
@richardwhiuk , can you comment on this line: https://github.com/OpenAPITools/openapi-generator/blame/master/modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache#L453

Logically, the test is "if OAuth2 and NOT BasicBearer". Can this be replaced with a positive test? The problem with not "BasicBearer" is that when new HTTP auth methods are added, this will still match the (NOT BasicBearer) clause, and that's probably not what you want.

**Comment by richardwhiuk** [comment]
@sebastien-rosset I think that code is fine - it's just trying to eliminate a double match on Bearer being generated.

**Pull request merged**
