### PR TITLE
[php-symfony] Set required PHP version to ^7.2.5

### PR DESCRIPTION
**Pull request by ybelenko**
Update PHP client package and PHPUnit to meet PHP 7.2 version.
Related issue #6522

Test results from `samples/server/petstore/php-symfony/SymfonyBundle-php`:
```console
$ vendor/bin/phpunit
PHPUnit 8.5.5 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 9:
  - Element 'testsuite': The attribute 'name' is required but missing.

  Test results may not be as expected.


[info] Matched route "open_api_server_pet_addpet".

(...)

53) OpenAPI\Server\Model\UserTest::testPropertyUserStatus
This test did not perform any assertions

/Users/ybelenko/Sites/openapi-generator/samples/server/petstore/php-symfony/SymfonyBundle-php/Tests/Model/UserTest.php:135

OK, but incomplete, skipped, or risky tests!
Tests: 62, Assertions: 9, Risky: 53.
```
and with PHPUnit 9:
```console
$ vendor/bin/phpunit
PHPUnit 9.2.2 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 9:
  - Element 'testsuite': The attribute 'name' is required but missing.

  Test results may not be as expected.


[info] Matched route "open_api_server_pet_addpet".

(...)

53) OpenAPI\Server\Model\UserTest::testPropertyUserStatus
This test did not perform any assertions

/Users/ybelenko/Sites/openapi-generator/samples/server/petstore/php-symfony/SymfonyBundle-php/Tests/Model/UserTest.php:135

OK, but incomplete, skipped, or risky tests!
Tests: 62, Assertions: 9, Risky: 53.
```

This PR won't pass Travis CI, because root `.travis.yml` of this repo configured to PHP 7.1 https://github.com/OpenAPITools/openapi-generator/blob/ebcce674197b0bea1772d1a3074acf0c10650b60/.travis.yml#L88

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @renepardon 
cc @reznikartem as last Symfony contributor
cc @FlaverSaver as person who asked for Symfony 5 support

### CODE REVIEW

**Comment by ybelenko** [comment]
I'm not satisfied with the result. I guess it will be better to install latest Symfony application from scratch and then apply mustaches. I'm marking this as draft.

I'm highly motivated to include it in `5.0.0` major release.

**Comment by ybelenko** [comment]
I'm working on Symfony migration right now and I have a few questions to contributors how understands framework very well. 
1. What type of build we should use, there are minimal `skeleton` and `website-skeleton`.
2. I've created new fresh installation with command `composer create-project symfony/website-skeleton my_project_name`. And there are many files under `var/cache/dev` folder, do we need to recreate them in generator?
3. What's the difference between `Symfony Flex` and `Symfony 5` itself?
4. API interfaces looks useless right now as soon as controllers responsible for all processes like validation, serialization etc. What is the purpose of API interfaces in current implementation?

And general notices:
1. New Symfony version recommends to store config for each package in `config/packages` folder. This configs should be commited, but current root repo `.gitignore` contains `packages/` rule which excludes these files from a codebase.
2. @wing328 should we upgrade generator or create new one `php-symfony5`?

**Comment by ybelenko** [comment]
```bash
your-project/
├── assets/
├── bin/
│   └── console
├── config/
│   ├── bundles.php
│   ├── packages/
│   ├── routes.yaml
│   └── services.yaml
├── public/
│   └── index.php
├── src/
│   ├── ...
│   └── Kernel.php
├── templates/
├── tests/
├── translations/
├── var/
└── vendor/
```
Maybe somebody can explain new framework files structure.

**Comment by ybelenko** [comment]
I'm closing this PR, because creating new generator `php-symfony5` seems more reasonable.

**Comment by dkarlovi** [comment]
@ybelenko did you start work on the `php-symfony5` generator?

**Comment by ybelenko** [comment]
@dkarlovi Yes, I'll push it today with `WIP` label. I made just a few commits, so we don't have a big progress over there.

**Pull request closed without merging**
