### PR TITLE
[Kotlin-client] Fix null assignation to header/query param map

### PR DESCRIPTION
**Pull request by armandmgt**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fixes compilation error caused by nullable value assignation to non-nullable values in headers map.

### CODE REVIEW

**Comment by armandmgt** [comment]
As discussed here #3722, the integration tests of the kotlin client still fail (they are commented out for shippable to pass)

**Comment by wing328** [comment]
@armandmgt thanks for the PR. Let me review shortly...

**Comment by wing328** [comment]
I've uncommented the shippable tests for kotlin clients (updated samples) and the tests (compilation) passed: https://app.shippable.com/github/OpenAPITools/openapi-generator/runs/10182/1/console

**Comment by wing328** [comment]
I'll file a separate PR to enable the kotlin tests with updated samples.

**Comment by wing328** [comment]
Filed https://github.com/OpenAPITools/openapi-generator/pull/3751

**Comment by wing328** [comment]
@armandmgt thanks for the PR, which has been included in the v4.1.1 release: https://twitter.com/oas_generator/status/1165944867391860737

**Pull request merged**
