### PR TITLE
typescript-fetch: fix return type of primitive value

### LINKED ISSUE #2870: [BUG][typescript-fetch] Typescript error in generated code for endpoint returning type boolean
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? 4.0.0-beta3 from npm
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating the typescript api client, the generated client has type errors for any methods returning a boolean.

```typescript
export class UserApi extends runtime.BaseAPI {

    async userEmailExistsRaw(requestParameters: UserEmailExistsRequest): Promise<runtime.ApiResponse<boolean>> {
        if (requestParameters.email === null || requestParameters.email === undefined) {
            throw new runtime.RequiredError('email','Required parameter requestParameters.email was null or undefined when calling userEmailExists.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/1.0/users/userExists/{email}`.replace(`{${"email"}}`, encodeURIComponent(String(requestParameters.email))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    async userEmailExists(requestParameters: UserEmailExistsRequest): Promise<boolean> {
        const response = await this.userEmailExistsRaw(requestParameters);
        return await response.value();
    }
}
```

The return statement from `userEmailExistsRaw` has error:

```
Type 'TextApiResponse' is not assignable to type 'ApiResponse<boolean>'.
  Types of property 'value' are incompatible.
    Type '() => Promise<string>' is not assignable to type '() => Promise<boolean>'.
      Type 'Promise<string>' is not assignable to type 'Promise<boolean>'.
        Type 'string' is not assignable to type 'boolean'.ts(2322)
```
##### openapi-generator version
4.0.0-beta3 from npm

##### OpenAPI declaration file content or url
```yaml
---
swagger: '2.0'
info:
  description: Operations related to the API
  version: '1.0'
  title: API
host: api.example.com
basePath: "/"
tags:
- name: User
  description: All apis relating to Users
schemes:
- http
- https
produces:
- application/xml
- application/json
paths:
  "/api/1.0/users/userExists/{email}":
    get:
      tags:
      - User
      operationId: userEmailExists
      parameters:
      - name: email
        in: path
        description: email
        required: true
        type: string
      responses:
        '200':
          description: Successfully retrieved result!
          schema:
            type: boolean
  "/api/1.0/users/id/{id}":
    get:
      tags:
      - User
      summary: Get specific User by id
      operationId: findUserById
      parameters:
      - name: id
        in: path
        description: id
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: Successfully retrieved result!
          schema:
            "$ref": "#/definitions/UserDto"
definitions:
  UserDto:
    type: object
    required:
    - id
    - email
    - firstName
    - lastName
    properties:
      id:
        type: integer
        format: int64
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    title: UserDto

```

##### Command line used for generation

```openapi-generator generate --additional-properties supportsES6=true -i ./openapi.yaml -g typescript-fetch -o out/typescript-fetch```

##### Steps to reproduce
Save yaml to `openapi.yaml` in current directory and run the command above.

##### Suggest a fix
Since `true` and `false` are both valid json responses, should the return statement simple be `return new runtime.JSONApiResponse(response);` (This also satisfies the typechecker)

### LINKED ISSUE #3709: [BUG] [typescript-fetch] Correctly handle number response
When generating code from a path like this:
```yaml
    get:
      operationId: getSlider
      description: Gets the slider value
      responses:
        200:
          description: Successfully returned slider location
          content:
            application/json:
              schema:
                type: number
                format: float
```

A type checking error is encountered:
```
Type 'TextApiResponse' is not assignable to type 'ApiResponse<number>'.
  Types of property 'value' are incompatible.
    Type '() => Promise<string>' is not assignable to type '() => Promise<number>'.
      Type 'Promise<string>' is not assignable to type 'Promise<number>'.
        Type 'string' is not assignable to type 'number'.  TS2322

    77 |         });
    78 | 
  > 79 |         return new runtime.TextApiResponse(response);
       |         ^
    80 |     }
    81 | 
    82 |    /**
```

Suggest adding a response handler, something like this to `runtime.ts`:
```js
export class NumberApiResponse {
    constructor(public raw: Response) { }

    async value() {
        const rawText = await this.raw.text();
        const response = JSON.parse(rawText);
        if (typeof response !== 'number') {
            // this check might be unnecessary
            throw new Error(`Expected response of type 'number', got ${rawText}`)
        }
        return response;
    };
}
```

### PR DESCRIPTION
**Pull request by ffMathy**
Fixes #3709 
Fixes #2870.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by ffMathy** [comment]
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07)

**Comment by macjohnny** [comment]
@ffMathy thanks for the PR. 
please re-generate the samples with https://github.com/OpenAPITools/openapi-generator/blob/master/bin/typescript-fetch-petstore-all.sh and commit them

**Comment by ffMathy** [comment]
How can I run this file on Windows?

**Comment by macjohnny** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/master/bin/windows/typescript-fetch-petstore-all.bat

**Comment by ffMathy** [comment]
Running it produced no differences in the pet API code. That makes sense, since the pet API doesn't have any endpoints returning booleans or numbers.

**Comment by ffMathy** [comment]
Actually, scratch that. It should indeed produce a difference, but it doesn't. Any ideas?

**Comment by macjohnny** [comment]
according to the CI (https://circleci.com/gh/OpenAPITools/openapi-generator/9216#tests/containers/2) there should be changes.
please run `mvn clean package` before re-generating the samples.

**Comment by ffMathy** [comment]
`mvn clean package` helped! Thanks.

**Comment by ffMathy** [comment]
Thanks for merging!

How long until this is available on NPM?

**Comment by macjohnny** [comment]
It will be included in the next release, so probably next week.

**Comment by wing328** [comment]
@ffMathy thanks for the PR, which has been included in the v4.1.3 release: https://twitter.com/oas_generator/status/1180123829626003456

**Pull request merged**
