### PR TITLE
Import Go package with leading underscore

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

To fix https://github.com/OpenAPITools/openapi-generator/issues/3485

Tested locally with `url`, `http`, `ioutil` and `context` as required parameters.

cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07)

### CODE REVIEW

**Comment by bkabrda** [comment]
IIUC this tries to address the problem by using more "obscured" version of the words - so technically if someone used a query parameter `_context`, this would still fail. I guess there's a low enough probability of getting in that situation that I'm 👍  (as I don't see any better solution other than obscuring the import names even more, e.g. `_openapiGeneratorImportContext`, but I guess that's too far fetched).

So overall, 👍 from me.

**Comment by wing328** [comment]
> so technically if someone used a query parameter _context, this would still fail.

Very good point. My understanding is that the query (and other forms of) parameter names are sanitized to conform to Go variable naming convention so the leading understood will be removed.

I did a test locally with `_context` and confirmed no variable naming conflict but I'm happy to take another look if you can repeat the issue.

**Comment by bkabrda** [comment]
I can't reproduce such an issue, so you're right, it's ok like this 👍 

Could you please add the same modification to the go-experimental client to keep them in sync as much as possible? Thanks!

**Comment by wing328** [comment]
> Could you please add the same modification to the go-experimental client to keep them in sync as much as possible? Thanks!

Sure I can do it later this week.

**Comment by wing328** [comment]
I will also add more test cases in a separate PR.

**Comment by wing328** [comment]
FYI. Added more test cases via https://github.com/OpenAPITools/openapi-generator/pull/3640

**Pull request merged**
