### PR TITLE
[JAVA] Add missing dependencies in templates

### LINKED ISSUE #20073: [BUG][JAVA] Dependencies missing for some Java libraries / configs
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In #20011 we noticed that a lot of the Java libraries using the `useReflectionEqualsHashCode` config are missing the commons-lang3 dependency in their pom template. I also noticed the mutiny dependency missing in one of the poms for the microprofile library.

##### openapi-generator version

7.9.0

##### Steps to reproduce

e.g. update the java-feign sample with `useReflectionEqualsHashCode: true`, regenerate samples and run `mvn integration-test -f samples/client/petstore/java/feign/pom.xml`

##### Suggest a fix

The missing dependencies should be added to the pom templates and the samples should be updated/added so this is covered in the future. It might also be worth looking for more such cases of dependencies missing.

### PR DESCRIPTION
**Pull request by DielN**
Fixes #20073

- [x] Add commons-lang3 dependency for libraries supporting `useReflectionEqualsHashCode`
- [x] Add mutiny dependency for microprofile 3.0 pom
- [ ] maybe find other missing dependencies for certain configs -> deferred

I can't really test the sbt files since I'm not familiar with that, gradle maybe. Not sure if the CI tests those or only uses maven?

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by DielN** [comment]
The feign-no-nullable generated samples contain some swagger stuff which causes errors for me. But this is not caused by me, since even on the latest master this happens. The sample has just never been in the CI. I added it since I added the `useReflectionEqualsHashCode` to it.

Is this caused by some manual samples? If I delete the directory and completely regenerate it, those files are not there. 
It also works if I add `swagger1AnnotationLibrary: true` to the config AND add the imports for the annotations to the model template because those are missing in the generated models (probably a bug).
What's the right approach to handle this? Just remove the swagger annotations from those files? Whatever those manual samples test, I don't think the annotations are needed for that.

**Comment by wing328** [comment]
@DielN thanks for the PR. Is this PR ready for review? 

We will release v7.10.0 soon so wondering if we can include this one.

**Comment by DielN** [comment]
There are quite some more dependencies which are missing in the poms and especially the gradle / sbt files (e.g. hibernate validator), but I'm not sure when I'll find time for it so let's just merge this one & I'll do the others separately if/when I find time

**Comment by DielN** [comment]
forgot to mention the people for review :) 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

**Pull request merged**
