### PR TITLE
make it easier to specify triggers for Zapier

### PR DESCRIPTION
**Pull request by a-wallen**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.

> closes https://github.com/OpenAPITools/openapi-generator/issues/18813

- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)

> this is a non breaking change

- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

> @valmoz @emajo

### CODE REVIEW

**Comment by a-wallen** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/18814/commits/d2412b600d20bc676ce50065c791836963260f95 and https://github.com/OpenAPITools/openapi-generator/pull/18814/commits/049d9809bb6b7fc69681ca9f863b26b5a29ae2af should probably be dropped since they just change '/' to '\'.

**Comment by wing328** [comment]
can you please resolve the merge conflicts when you've time?

I will then try to update the samples.

**Comment by a-wallen** [comment]
@wing328 done

**Comment by a-wallen** [comment]
@wing328

**Comment by wing328** [comment]
@a-wallen sorry for the delay. I was busy with other works and just pushed an important fix to openapi-generator-cli

just reopened this PR

**Comment by wing328** [comment]
Just filed https://github.com/OpenAPITools/openapi-generator/pull/19638 with updated samples.

will merge if no one else has further feedback

closing this one

thanks again for the PR

**Pull request closed without merging**
