### PR TITLE
Fix package declaration #7122

### LINKED ISSUE #7122: [BUG] Package declaration problem in openapi-generator module
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Noticed this problem after importing project into IDE - test class **TypeScriptClientCodegenTest** has package declaration "org.openapitools.codegen.typescript.fetch", but is located in "/openapi-generator/src/test/java/org/openapitools/codegen/typescript/" folder.

##### openapi-generator version

5.0.0-beta

##### OpenAPI declaration file content or url

N/A

##### Generation Details

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

N/A

##### Suggest a fix

Fix package declaration.

### PR DESCRIPTION
**Pull request by typhoon2k**
To close #7122 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by typhoon2k** [comment]
It seems that the failure is not related to the change performed here (maybe something expected to happen from time to time?).

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
> It seems that the failure is not related to the change performed here (maybe something expected to happen from time to time?).


Restarted the job and all tests pass

**Comment by typhoon2k** [comment]
@wing328 , thanks!
Commit author fixed.

**Pull request merged**
