### PR TITLE
fix api key in query 

### PR DESCRIPTION
**Pull request by ksvirkou-hubspot**
https://github.com/OpenAPITools/openapi-generator/issues/9475

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ksvirkou-hubspot** [comment]
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by ksvirkou-hubspot** [comment]
What is plan for merging ?
@macjohnny

**Comment by macjohnny** [comment]
Waiting for the build to succeed

**Review by TiFu — APPROVED** [review]
LGTM as well. Thank you for the PR!

CirceCLI failure seems to be unrelated - 

```go: downloading github.com/gorilla/mux v1.7.3
?   	github.com/GIT_USER_ID/GIT_REPO_ID	[no test files]
?   	_/home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/go-gin-api-server	[no test files]
go go: unknown command
Run 'go help' for usage.
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (go-get) on project GoEchoServer: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :GoEchoServer```

**Comment by ksvirkou-hubspot** [comment]
> LGTM as well. Thank you for the PR!
> 
> CirceCLI failure seems to be unrelated -
> 
> ```
> ?   	github.com/GIT_USER_ID/GIT_REPO_ID	[no test files]
> ?   	_/home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/go-gin-api-server	[no test files]
> go go: unknown command
> Run 'go help' for usage.
> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (go-get) on project GoEchoServer: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :GoEchoServer```
> ```

I 've just checked code one more time 
it seems unrelated

**Pull request merged**
