### PR TITLE
[dart-dio][client] Handle x-www-form-urlencoded form data

### PR DESCRIPTION
**Pull request by adg-mh**
`x-www-form-urlencoded` form data is not handled (only multipart is).
This PR adds this missing handling.

You can see an example of this issue in the existing sample client [here](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/dart-dio/lib/api/pet_api.dart#L255) where `name` and `status` are not passed through to the request.

@ircecho @swipesight @jaumard @nickmeinhold @athornz @amondnet

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by adg-mh** [comment]
Looks like bitrise bombed out (seems to affect other PRs as well). Assuming there's nothing else I need to do with that/it won't block merging?

**Comment by adg-mh** [comment]
@wing328 @athornz Is there anything blocking this?

**Comment by jaumard** [comment]
@adg-mh might need a rebase to fix conflicts

**Comment by adg-mh** [comment]
It was just the `VERSION` file, so should be good to go now. thanks.

**Comment by wing328** [comment]
@adg-mh thanks for the PR, which has been included in the v4.3.1 release: https://twitter.com/oas_generator/status/1258057660974329861

**Pull request merged**
