### PR TITLE
[PowerShell] Support multiple types in Accept header

### PR DESCRIPTION
**Pull request by condorcorde**
This is an enhancement for generated PowerShell clients.

In generated functions, there is the possibility to choose multiple Accept headers in the variable $LocarVarAccepts, but only one is selected to be sent in the HTTP request. Alas, sometimes there is the need to specify multiple MIME types, for example when downloading a document without knowing in advance the format of the response (which is a sign of badly designed APIs).

This change adds the parameter -Multiple to the function SelectHeaders. When choosing it (for the Accept header) all the types in the parameter $Headers will be returned.

The change does not affect the behaviour of endpoint functions that specify a single value in the variable $LocalVarAccepts.

However, this source function has been modified to specify multiple values
~~~
        # HTTP header 'Accept' (if needed)
        $LocalVarAccepts = @('application/octet-stream', 'application/json;charset=UTF-8')
~~~

The generated request is

~~~
GET /api/3/reports/194/history/1724/output HTTP/1.1
Host: [...]
Authorization: [...]
Accept: application/octet-stream, application/json; charset=UTF-8
User-Agent: Mozilla/5.0 (Macintosh; Darwin 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64; en-CH) PowerShell/7.4.1
Accept-Encoding: gzip, deflate, br
Connection: close
~~~

(@wing328)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
the CI tests failed: https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/49093496

can you please take a look when you've time?

**Comment by wing328** [comment]
to run petstore test server locally, please refer to https://github.com/OpenAPITools/openapi-generator/wiki/Integration-Tests

**Comment by condorcorde** [comment]
From what I can see in the code the function Get-PSOrderById is defining two MIME types for the accept header in line 198 of samples/client/petstore/powershell/src/PSPetstore/Api/PSStoreApi.ps1:
~~~
 $LocalVarAccepts = @('application/xml', 'application/json')
~~~
The effect of adding the  parameter "-Multiple" is that both will be put in the Accept: header. The previous behaviour would have selected only 'application/json'.

I have not run the petstore server, so I am not sure of how it reacts when receiving two MIME types, but given the error in the response it does not send back something parseable with Convert-FromJSON.

The petstore code was likely supposed to test the previous behaviour, i.e. that only JSON MIME types would be passed to the server.

**Comment by condorcorde** [comment]
...or possibly the server side was build from the same specs openapi.yaml which says that both format are accepted, and the server has sent back a response in XML format because it was the first it found.

~~~
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: successful operation
~~~

**Comment by condorcorde** [comment]
Does this mean that SelectHeaders with -Multiple should reorder the input array and put JSON MIME types first?

**Comment by wing328** [comment]
> Does this mean that SelectHeaders with -Multiple should reorder the input array and put JSON MIME types first?

Yes, I would say so for backward compatibility.

**Comment by wing328** [comment]
powershell tests passed via https://github.com/OpenAPITools/openapi-generator/pull/17806

**Pull request merged**
