### PR TITLE
Fix names of pre- and post- scripts for building libcurl

### PR DESCRIPTION
**Pull request by ahmedyarub**
I forgot to add the extension to the optional scripts in my previous PR.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@zhemant  @ityuhui  @michelealbano

### CODE REVIEW

**Comment by ityuhui** [comment]
I'm OK with the change itself.
But I think https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/c/CMakeLists.txt changes too. Could you please re-generate the sample and commit this file ?
The command is:
```shell
./bin/generate-samples.sh ./bin/configs/c.yaml
```

**Comment by ahmedyarub** [comment]
> I'm OK with the change itself.
> But I think https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/c/CMakeLists.txt changes too. Could you please re-generate the sample and commit this file ?
> The command is:
> 
> ```shell
> ./bin/generate-samples.sh ./bin/configs/c.yaml
> ```

I did try doing that but it's explicitly ignored. I'd have to remove the file from ignore list, regenerate the sample including the CMake scripts, and then add new pre and post scripts to make the example work with our new scripts structure. Do you want me to do that?

**Comment by ityuhui** [comment]
No need add new pre and post scripts.

Just re-generate the CMakeLists.txt

Maybe need clean the cache:

```shell
mvn clean
rm -rf ./samples/client/petstore/c
./bin/generate-samples.sh ./bin/configs/c.yaml
```

**Comment by ahmedyarub** [comment]
> No need add new pre and post scripts.
> 
> Just re-generate the CMakeLists.txt
> 
> Maybe need clean the cache:
> 
> ```shell
> mvn clean
> rm -rf ./samples/client/petstore/c
> ./bin/generate-samples.sh ./bin/configs/c.yaml
> ```

I did run that command but CMakeLists.txt was not modified since it’s in the ignore list. The samples generating script explicitly mentioned that. Do you want me to remove it from the ignore list?

**Comment by ityuhui** [comment]
Yes.
But do you try `rm -rf ./samples/client/petstore/c`, I think this command should delete file `.openapi-generator-ignore`

**Comment by ityuhui** [comment]
I tried it by myself (delete `./samples/client/petstore/c` and re-generate the sample) and found there are many changes that have not updated for some times.
```
        modified:   samples/client/petstore/c/.openapi-generator-ignore
        modified:   samples/client/petstore/c/.openapi-generator/FILES
        modified:   samples/client/petstore/c/.openapi-generator/VERSION
        modified:   samples/client/petstore/c/CMakeLists.txt
        deleted:    samples/client/petstore/c/build-and-test.bash
        deleted:    samples/client/petstore/c/pom.xml
        deleted:    samples/client/petstore/c/unit-tests/manual-PetAPI.c
        deleted:    samples/client/petstore/c/unit-tests/manual-StoreAPI.c
        deleted:    samples/client/petstore/c/unit-tests/manual-UserAPI.c
        deleted:    samples/client/petstore/c/unit-tests/manual-order.c
        deleted:    samples/client/petstore/c/unit-tests/manual-user.c
```
 
Hi @ahmedyarub
I suggest removing "CMakeLists.txt" from ".openapi-generator-ignore" and only re-generate CMakeLists.txt, keep other files unchanged.

cc @wing328

**Comment by zhemant** [comment]
@ahmedyarub Thank you for the PR!

@ityuhui @ahmedyarub The cmakelists was in gitignore because there were some hardcore dependencies that were lost when we re-create cmakelists. If there are no such dependiences anymore, then we can remove the cmakelists.txt from the gitignore.

When you regenerate please check if it compiles pet store without any problem and probably if you have any other API then that too.

**Comment by ityuhui** [comment]
Considering this is a previsous issue, only changing "CMakeLists.txt" is not a best solution.

I suggest merging this PR now (This PR is OK to me).

And I will log a new defect to trace this issue and try to deliver it with a better solution in future. @zhemant @wing328

**Review by ityuhui — APPROVED** [review]

**Comment by zhemant** [comment]
Okay lets do that as a part of another PR

**Review by zhemant — APPROVED** [review]

**Comment by ahmedyarub** [comment]
Thank you guys. I can fix that in a future PR. I hope that you can merge this soon since it is a blocker for another one.

**Pull request merged**
