### PR TITLE
Prepare 3.0.1 release

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### PR for previous release:

https://github.com/OpenAPITools/openapi-generator/pull/190

### Description of the PR

- added a bash script to update files with ease
- updated files with new version 3.0.1

### CODE REVIEW

**Comment by jmini** [comment]
@wing328:  Version is not updated in `CI/pom.xml.shippable` is that on purpose?

---

With b32673199cb43307d5d1a247453ea3b4fbc6baa6 I have modified the Shippable pom to build the root pom and its modules. This is something that is not specific to this release and that can be kept with `3.0.2-SNAPSHOT`

**Comment by jmini** [comment]
Because of such diffs:

```diff
--- a/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApi.java
+++ b/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApi.java
@@ -1,5 +1,5 @@
 /**
- * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.1-SNAPSHOT).
+ * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.1).
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
```

And for `VERSION` files (see ):

```diff
diff --git a/samples/server/petstore/springboot-beanvalidation/.openapi-generator/VERSION b/samples/server/petstore/springboot-beanvalidation/.openapi-generator/VERSION
index ad121e834..13d683ccb 100644
--- a/samples/server/petstore/springboot-beanvalidation/.openapi-generator/VERSION
+++ b/samples/server/petstore/springboot-beanvalidation/.openapi-generator/VERSION
@@ -1 +1 @@
-3.0.1-SNAPSHOT
\ No newline at end of file
+3.0.1
\ No newline at end of file
```

I have commented out `bin/ensure-up-to-date` in 522d0dcfba049a9fe9797e28209ddc7ac95296ad

**Comment by wing328** [comment]
This will close https://github.com/OpenAPITools/openapi-generator/issues/259

**Comment by jmini** [comment]
When release is OK we can move forward with https://github.com/OpenAPITools/openapi-generator/pull/280

**Comment by jimschubert** [comment]
@jmini do you mean to link to #285? This PR is 280.

**Comment by jmini** [comment]
Edited, thank you.

**Pull request merged**
