### PR TITLE
[BUG][dart-dio-next] Add if check before breaking loop

### LINKED ISSUE #9334: [BUG][dart-dio-next] Generator uses url encoded contentType even if the server content type requires application/json
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm using Asp.Net Core Swashbuckle to generate openapi scheme for my backend. The backend supports multiple content-type variants of `application/json`. But generated code uses url encoded content type instead of application/json.

Here's generated code output which picks first match which is "application/json-patch+json". 

```dart
contentType: [
  'application/json-patch+json',
  'application/json',
  'text/json',
  'application/_*+json',
].first
```

But then Did checks if content-type is `application/json` then uses json encoding but if it isn't, it uses url encoding and my server returns **HTTP 415 Unsupported Media Type** status.

##### openapi-generator version

**5.1.0**

##### OpenAPI declaration file content or url

The OpenAPI declaration that caused this issue was used for private api. So I couldn't share it here.

##### Suggest a fix

1. Overriding content-type header using command line options provided to generator CLI
2. Updating `contentType` matching part to choose most suitable match rather than first one

### PR DESCRIPTION
**Pull request by TheMisir**
This PR ensures that generator first looks if consumer contains any of the supported media types ("application/json", "application/x-www-form-urlencoded", "multipart/form-data").

If it does generator sets first one to 'x-content-type' parameter. Otherwise 'x-content-type' parameter value will be either the first consumer's media type (same behavior as previously generator but the whole thing is happening on generator side instead of doing `[ ... ].first`) or default value which is "application/json" (also same as old behavior).

Fixes #9334. Please check the issue for more details.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. - @kuhnroyal

### CODE REVIEW

**Comment by TheMisir** [comment]
> Did you regenerate the samples? If so, this would mean we don't have this case in the samples or we use it differently in the templates.

I tried building samples but when I run `./mvnw clean package` command, building generator-core failed (which I have not touched in this PR).


https://user-images.githubusercontent.com/29130291/118040769-0c193b80-b383-11eb-80c6-d3301e458090.mp4

End of the logs:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for openapi-generator-project 5.2.0-SNAPSHOT:
[INFO]
[INFO] openapi-generator-project .......................... SUCCESS [  3.087 s]
[INFO] openapi-generator-core ............................. FAILURE [  8.075 s]
[INFO] openapi-generator (core library) ................... SKIPPED
[INFO] openapi-generator (executable) ..................... SKIPPED
[INFO] openapi-generator (maven-plugin) ................... SKIPPED
[INFO] openapi-generator-gradle-plugin (maven wrapper) .... SKIPPED
[INFO] openapi-generator-online ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.666 s
[INFO] Finished at: 2021-05-13T00:06:55+04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.12.2:spotbugs (spotbugs) on project openapi-generator-core: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.12.2:spotbugs failed: Java returned: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :openapi-generator-core
```

**Comment by TheMisir** [comment]
Seems like related to https://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete

**Comment by TheMisir** [comment]
> Did you regenerate the samples? If so, this would mean we don't have this case in the samples or we use it differently in the templates.

I just did, but maybe the samples might not contain my case.

**Comment by TheMisir** [comment]
@kuhnroyal can you please review the changes?

**Comment by kuhnroyal** [comment]
This looks pretty good, I have just fixed some CI problems on master, can you please rebase and see if it goes green.

**Comment by TheMisir** [comment]
> can you please rebase and see if it goes green.

I rebased, but checks still fails.

**Comment by kuhnroyal** [comment]
I think this can be closed and is superseded by #9517

**Comment by TheMisir** [comment]
> I think this can be closed and is superseded by #9517

Sure.

**Comment by kuhnroyal** [comment]
Thank you for your input on this!

**Pull request closed without merging**
