### PR TITLE
[C#][netcore] minor code improvement

### PR DESCRIPTION
**Pull request by wing328**
- minor code improvement (remove blank lines, avoid using `var`, etc)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05)

### CODE REVIEW

**Comment by Blackclaws** [comment]
Why are you avoiding the use of var? Its actually encouraged in cases where its just duplicating information.

**Comment by wing328** [comment]
> Why are you avoiding the use of var? Its actually encouraged in cases where its just duplicating information.

It's based on suggestions from VS: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008

Here are some more info: https://softwareengineering.stackexchange.com/questions/339321/is-microsoft-discouraging-the-use-of-var-in-c-vs2017

**Comment by Blackclaws** [comment]
I think its a style question mostly. For me the default settings in Rider prefer ```var``` over actual type names. 

I don't care a lot about this since its in generated code mostly.

**Comment by devhl-labs** [comment]
It's just preference. I almost never use var. I've seen some who only use it. Your first link mentions only using it if the type is obvious. I'm indifferent on the change. The spacing on the other hand is a good change. I don't like using brackets for single line if statements, but that is another preference. It takes too much vertical real estate.

**Comment by wing328** [comment]
Valid points. In general, we recommend users to use code formatters/linters to massage the code in whatever style they want as the default output won't meet everyone's requiremnets

**Pull request merged**
