### PR TITLE
[golang] Regenerate all go samples 

### PR DESCRIPTION
**Pull request by etherealjoy**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Related to #3975

Running these still produce diffs

```shell
./bin/go-experimental-petstore.sh  && ./bin/go-gin-petstore-server.sh \
 && ./bin/go-petstore-server.sh && ./bin/go-petstore.sh && ./bin/go-petstore-withxml.sh
```

```shell
./bin/openapi3/go-experimental-petstore.sh && ./bin/openapi3/go-gin-petstore-server.sh \
&& ./bin/openapi3/go-petstore-server.sh && ./bin/openapi3/go-petstore.sh
```

cc @OpenAPITools/generator-core-team

### CODE REVIEW

**Comment by wing328** [comment]
@etherealjoy thanks for the PR. I've thought about adding Go experimental client to the ensure-up-to-date script but not sure if it's a good idea.

Given that the outdated samples may cause confusion, let's add these scripts (that you just ran in this PR) to ./bin/utils/ensure-up-to-date.sh so that the CI will ensure these samples are up-to-date.

**Comment by etherealjoy** [comment]
@wing328 
There is a mismatch with the signature due to the `apikeys` holding a map. 
But I ran the test locally after updating the test case and they are all good now. 
Just some outdated test case that is all.

**Comment by etherealjoy** [comment]
> Given that the outdated samples may cause confusion, let's add these scripts (that you just ran in this PR) to ./bin/utils/ensure-up-to-date.sh so that the CI will ensure these samples are up-to-date.

I will update the PR to add these to the script.

**Comment by etherealjoy** [comment]
@wing328 
Should I add the up until not checked in files for `go-experimental` in the `openapi3` samples as well?

**Pull request merged**
