### PR TITLE
[DART2] A couple of bug fixes

### PR DESCRIPTION
**Pull request by noordawod**
The current implementation has a couple of problems and this pr addresses them:

1) Change `fromJson(value)` to accept a `dynamic value`.
2) Encode non-String header values using `parameterToString()` method.
3) Changed `fromJson()` to a static function, will not instantiate a new object when json == null.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12) @wing328 @sbu-WBT @agilob

### CODE REVIEW

**Comment by noordawod** [comment]
Unsure why the tests are failing, the change wasn't that big...
Pointers, @sbu-WBT @agilob @wing328 ?

**Comment by sbu-WBT** [comment]
I think the failing CIs are not from this PR.
The changes seem to be good

**Comment by noordawod** [comment]
Ahh, passing at last :) Ready for scrutiny guys!

**Comment by agilob** [comment]
LGTM

**Comment by noordawod** [comment]
The pr still has on conflicts with base branch, so bumping up for tlc @wing328 :)

**Pull request merged**
