### PR TITLE
[go-experimental] Use builder pattern for requests

### PR DESCRIPTION
**Pull request by zippolyte**
Implement builder pattern to construct requests and pass all parameters. Similar construct as #4666 

The motivation for this is to keep a client that will stay backward compatible in case some required parameters become optional which is not a breaking change in itself, but with the current implementation, it would change the method signature, thus introducing a breaking change in the client upon new generation.

Only path parameters are always required and any change would break the API itself, which is why I left them in the function signature. 
cf https://swagger.io/specification/#parameterObject:
> Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. 

Additionally, this removes the use of the `antihax/optional` module for query parameters, as we don't need the explicit null functionality here. 
cf https://github.com/OpenAPITools/openapi-generator/issues/522#issuecomment-523896869

Any feedback/suggestion would be much appreciated.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07)

### CODE REVIEW

**Comment by antihax** [comment]
I recall there was a situation where we may need to specify path, qs, or body parameters as you could have a query or path parameter with the same name as a body parameter, etc.

The other projects using a builder pattern (Peal notably iirc) would specify this. @wing328 is this something to consider in this new design? I will see if i can find the example.

**Comment by zippolyte** [comment]
Hmm that seems fair. 
I would argue though that the current approach would have that name clash problem too, since the different kinds of parameters in either the method signature, or the Opts object.

I actually remember having encountered this in our own specs, we had a path parameter that was name `foo_bar` and the endpoint accepted a body parameter of type `FooBar`. It resulted in a method like `test(fooBar string, fooBar FooBar)` so the code did not compile, and we just decided to change the name of the path parameter

**Comment by antihax** [comment]
It does, but so do many of the other clients in other languages. The solution i had seen (i thought was the perl version, but not anymore) was to use something like:
```
client.Function
   .BodyParameters(name, id)
   .FormParameters(name, pet);
```

**Comment by zippolyte** [comment]
The problem with this one is that it still has the problem of generating client that are cannot be backward compatible when for example a body parameter is added in the API.

This is the main problem I am trying to solve with the approach in that PR.

**Comment by zippolyte** [comment]
After giving more thought to this, I think the name clashing issue is not too big a problem anyway. It's easily fixable in the specification itself by changing the names of your path parameters for example, and there even is a `x-codegen-request-body-name` extension for the specific case of the body param name.
As you said also, it looks like things have been refactored away from the separation of parameter types.
With that said, what's your opinion on the approach I'm trying to take to solve the backward compatibility issue, while also retaining a decent UX ?

Also @wing328 or @jimschubert, I'm not too sure what's going on with the circleCI tests, can you advise here ?

Thanks all !

**Comment by wing328** [comment]
I've pushed a fix to the master. Please merge the latest master into this branch to resolve the build error. Sorry for the inconvenience caused.

**Comment by jimschubert** [comment]
AppVeyor looks like an unrelated issue with sockets closing in the C# client test.

**Comment by zippolyte** [comment]
Bumping, @antihax do you have any other feedback regarding this ?

**Comment by jimschubert** [comment]
I've skimmed this quickly (I'm by no means a Go expert), and I think it looks good.

I wonder if we should target the 4.3.x branch because it'll break existing client code (see diff on tests).

**Comment by zippolyte** [comment]
Yeah it will definitely break existing code. I felt like I could given this is the experimental template, but happy to target 4.3.x then.

**Comment by wing328** [comment]
@zippolyte for go-experimental (but not other generators), it's ok to have breaking changes in the master.

**Comment by jimschubert** [comment]
Awesome. Then yeah we can merge if there are no other concerns.

**Comment by zippolyte** [comment]
@jimschubert OK to merge then ?

**Comment by jimschubert** [comment]
Yeah, since it's been almost a week with no other concerns from contributors I think it's good to go.

**Comment by zippolyte** [comment]
Thanks for merging ! 🙇

**Pull request merged**
