### PR TITLE
Kotlin collection type

### PR DESCRIPTION
**Pull request by absimas**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
Swagger spec file contains only array types thus it is always the preferred choice when converting to kotlin. Allow specifying which collection type to convert to.

@jimschubert @dr4ke616

### CODE REVIEW

**Comment by absimas** [comment]
I don't quite understand your comment on the default.

Current default is array and this code doesn't change that, thus this is not a breaking change.

**Comment by absimas** [comment]
Oh unless you meant the default for `list` which indeed was `kotlin.collections.List`.

**Comment by jimschubert** [comment]
@absimas yes, sorry for the confusion. For a non-breaking change we would want array and list to remain the same default type until the next major release.

I haven't tested if this PR still works with type mappings (another way users can modify these defaults), so I (or someone else) need to test that before merge.

**Comment by wing328** [comment]
Tested with both `array` and `list`, and the output compiles without issues.

**Comment by wing328** [comment]
@absimas thanks for the PR, which has been included in the v3.3.4 release: https://twitter.com/oas_generator/status/1068772409795207168

**Pull request merged**
