### PR TITLE
New Javascript flowtyped generator

### PR DESCRIPTION
**Pull request by jaypea**
As discussed in swagger-api/swagger-codegen#5733 there is no generator which outputs Javascript which is properly flow typed and easy to use with React.

Here is it now.

Is is based on the Typescript Fetch Generator, so differs from the other Javascript Generators in code and architecture.

Simply adding flow annotations didn't work with the current js es6 code.

The code is written in ES6 with flow syntax. In order to use it as a library in your react app, it comes with a npm build script to transpile it into node.js and browser compatible es5 syntax with additional .js.flow for flow to use the types properly.

steps to use this client as a npm library:

create yourself a new folder and repo for the client sdk
generate client with java -jar swagger-codegen-cli-2.3.1.jar generate -i swagger.json -l javascript-flowtyped -o 
npm install
NODE_ENV=production npm run build
git add .
git commit -m 'update sdk version'
git tag v
git push && git push --tags
in your react app do:
npm install #v
import { * as api } from 'client-sdk-package'
if you want to generate the api directly inside your client-app you can do so. just import the files from the generated src then. these are pure es6 with flow types and need to be transpiled like you would do with the other code.

this is a copy of my changes in swagger-api/swagger-codegen#8101 without adjustments to this new project.
@wing328 please advise how to proceed with this PR

### CODE REVIEW

**Comment by wing328** [comment]
@jaypea thanks for the PR. I'll work with you on this after the 3.0.0 stable release (due today)

**Comment by jimschubert** [comment]
@jaypea I've added the WIP label.

@wing328 this is tagged for 3.0.1 (going out tomorrow). We may want to tag only at minor versions, just to make it easier to maintain milestones.

**Comment by wing328** [comment]
@jaypea I've pushed a few commits for enhancements:
- add JS flowtype samples
- setup CI to catch errors thrown by `npm run build`
- minor wording changes.

There are other enhancements (day 2 requirement) that I'll open an "issue" (ticket) for tracking.

If these changes look good to you, we can merge it into master and ask other JS developers to try it out.

**Comment by jaypea** [comment]
@wing328 all looking good. thanks for taking care.

**Comment by mlersch** [comment]
@jaypea i have problems implementing the generated lib, because of a missing implementation example in the generated README.md ... can you please give me a hint. when i get it working i would provide a update to the codegen's ... Thanks

**Pull request merged**
