### PR TITLE
[PHP] Username checks #1408

### PR DESCRIPTION
**Pull request by jfastnacht**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Trying to fix the issue #1408 . Intermediate result, WIP. 

Had some problems with the test under Windows 8.1, so it might need a little more than the usual review.

@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon

### CODE REVIEW

**Comment by wing328** [comment]
> Sometimes the builds are breaking on incomprehensible, random points. Things should be fixed, but this PR goes further than only #1408.

Yup, especially weekend as we saw issues downloading dependencies from time to time. Restarting the job (close and reopen the PR) usually fixes the problem

**Comment by jfastnacht** [comment]
> Restarting the job (close and reopen the PR) usually fixes the problem

I didn't knew that you can restart it this way, thanks.

**Comment by wing328** [comment]
@jfastnacht is this PR ready for review? If yes, I'll remove WIP from the label and the title.

**Comment by jfastnacht** [comment]
@wing328 tbh, this PR is a mess, because it changes much more than the initial issue states. Not sure if this would be okay anyways, otherwise I'll break it up into seperate issues and PRs.

**Comment by wing328** [comment]
@jfastnacht I'd a look and I think it's acceptable as your fix is essentially just one line: https://github.com/OpenAPITools/openapi-generator/pull/1892/files#diff-076573ccfdac2ab5af4dc1813e5ccee3R584

**Pull request merged**
