### PR TITLE
[Dart 2] Add support for Dart 2

### PR DESCRIPTION
**Pull request by swipesight**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@ircecho
### Description of the PR

Added an config option for Dart 2.

### CODE REVIEW

**Comment by wing328** [comment]
@swipesight thanks for the PR. Is it correct to say that this will break users using Dart 1.x? Shall we add an option e.g. `supportDart2`?

I believe most Dart developers should still be using Dart 1.x as Dart 2.0.0 (stable version) was only released yesterday/today.

**Comment by swipesight** [comment]
How about adding a new generator for Dart2?

**Comment by wing328** [comment]
@swipesight that's one way to do it but I would a prefer a single generator for Dart if Dart 1.x and Dart 2.x are not very different.

I believe Dart2 can still use Dart 1.x library, right? In other words, we don't need to update the dependency.

**Comment by swipesight** [comment]
@wing328 I'll see if I can add an option for Dart2.

**Comment by wing328** [comment]
@swipesight 👌 let me know if you need any help.

Python flask generator has something similar: `supportPython2` option: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFlaskConnexionServerCodegen.java#L43

Search for supportPython2 or SUPPORT_PYAHON2 will reveal how the option is implemented in that file.

Hope this helps.

**Comment by swipesight** [comment]
@wing328 I have added an option for Dart 2.

**Comment by wing328** [comment]
@swipesight I tried to add Dart2 petstore samples to the Travis build but it reports the following error:
```
Resolving dependencies...
The current Dart SDK version is 2.0.0.
Because petstore_client depends on openapi from path which requires SDK version <2.0.0, version solving failed.
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (pub-get) on project Dart2PetstoreClientTests: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

Would you please take a look when you've time?

Basically, the test runs the following in the folder `samples/client/petstore/dart2/petstore/`:
```sh
pub get
pub build test
```

**Comment by swipesight** [comment]
@wing328 Sure, I'll check out later.

**Comment by Henge9** [comment]
This PR solves version issues when upgrading to latest flutter version.

**Comment by wing328** [comment]
@swipesight I've pushed 7d2edf4 to move the Dart2 petstore test to the end as some records created by the Dart2 petstore tests are invalid (e.g. status not set probably). I'll follow up with you later to fix those test cases.

If the CI tests are green, I'll merge this PR into master

**Comment by swipesight** [comment]
@win328 I'll fix these tests and then send another PR.

**Comment by wing328** [comment]
@swipesight thanks! We'll send out a tweet to promote the awesome Dart2 support you added.

Do you have a Twitter account? If yes, we'll tag you in our tweet (https://twitter.com/oas_generator)

If you need help fixing the tests, please let me know.

**Comment by swipesight** [comment]
@wing328 Thanks! Here is my twitter[https://twitter.com/swipesight](url)

**Comment by wing328** [comment]
Set Dart2 as the default via https://github.com/OpenAPITools/openapi-generator/pull/949

**Pull request merged**
