### PR TITLE
[Kotlin-Spring] Fix properties default value

### PR DESCRIPTION
**Pull request by cbornet**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jimschubert (2017/09) heart, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

### CODE REVIEW

**Review by wing328 — APPROVED** [review]
LGTM

**Comment by sticreations** [comment]
Hi, Sadly this introduced a new Bug when generating default Enum Values. 

The name of the generated Enum is for example "TemperatureZone", the generated Code for the default value is
**`   @field:JsonProperty("temperature_zone") var temperatureZone: OutboundZone.TemperatureZone? = TemperatureZoneEnum.NONE
**

The default value seems to get the classname wrong.

**Comment by sigand** [comment]
It seems to also so something to default values for strings. Generated code does not compile
`    @field:JsonProperty("exampleProperty") val exampleProperty: kotlin.String? = &quot;example&quot;,
`

**Comment by sigand** [comment]
Having played around in the code, neither bug above is due to this PR

**Pull request merged**
