### PR TITLE
[BUG] [typescript] Duplicate parameter's names (rename options to _options and config to _config)

### PR DESCRIPTION
**Pull request by ksvirkou-hubspot**
fixes https://github.com/OpenAPITools/openapi-generator/issues/9425

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ksvirkou-hubspot** [comment]
@TiFu  @taxpon @sebastianhaas  @kenisteward @Vrolijkx  @macjohnny  @topce  @akehir  @petejohansonxo @amakhrov

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by matrix4123** [comment]
This bug seems to still exist in the typescript-axios generator. I am guessing we need to make similar changes across all of the typescript-* generators?

**Comment by ksvirkou-hubspot** [comment]
> This bug seems to still exist in the typescript-axios generator. I am guessing we need to make similar changes across all of the typescript-* generators?

This bug was fixed only for typescript generator but it wasn't fixed for typescript-axios generator.

**Comment by matrix4123** [comment]
> > This bug seems to still exist in the typescript-axios generator. I am guessing we need to make similar changes across all of the typescript-* generators?
> 
> This bug was fixed only for typescript generator but it wasn't fixed for typescript-axios generator.

Thanks for reply, I'll see if I can make a fix! 👍🏼

**Comment by teddybee** [comment]
I have jut run into the issue with typescript-axios generator. There is a generated function param name: "options" and the AxiosRequestConfig param is also "options" so the typescript compiler is freaking out.

**Pull request merged**
