### PR TITLE
[php] fix @implements annotations in PHP client

### PR DESCRIPTION
**Pull request by IonBazan**
This PR fixes invalid `@implements` annotations for PHP classes. This is because Model classes should not be generic while current implementation requires users to provide types, which are not known to them (see https://github.com/onfido/api-php-client/issues/26).

This is only reported when using PHPStan with `checkGenericClassInNonGenericObjectType: true` - https://phpstan.org/blog/generics-in-php-using-phpdocs

image

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by IonBazan** [comment]
Tagging:
- @jebentier 
- @dkarlovi (I think you edited these files recently)
- @mandrean
- @jfastnacht 
- @ackintosh
- @ybelenko 
- @renepardon
to help review this PR

**Comment by wing328** [comment]
PHP CI tests passed via https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds/251563191

**Comment by wing328** [comment]
@IonBazan thanks for the PR, which has been merged into the master. Do you know if there's any way (e.g. command) to detect these kind of issues in the annotations?

**Comment by IonBazan** [comment]
Hi @wing328 thanks for merging! The problem was detected using PHPStan with `checkGenericClassInNonGenericObjectType: true`, when using an API generated with this tool so I'd say it's best to check that during code review as model classes should not be generic.

**Comment by wing328** [comment]
@IonBazan thanks for the info. will try to add it to the CI later to cover issue like this moving forward.

**Pull request merged**
