### PR TITLE
[PHP-Symfony] Encurage Symfony 5 bundle directory structure best practices

### LINKED ISSUE #13022: [REQ] [PHP-Symfony] Encurage Symfony 5 bundle directory structure best practices
### Is your feature request related to a problem? Please describe.

When working with the PHP-Symfony Generator, the output was not as i expected. Especially because there was already a PR who updated the generator to PHP 8.1 and Symfony 5: #11810 

I wish it to be more like explained here: https://symfony.com/doc/current/bundles/best_practices.html#directory-structure

## Describe the solution you'd like

Refactor the code of `PhpSymfonyServerCodegen.java`.

## Describe alternatives you've considered

Add an generator config option that enables the Symfony 5 directory structure.

## Additional context

Already started a PR: #13014

### PR DESCRIPTION
**Pull request by lukadschaak**
Update the PHP-Symfony Generator (`PhpSymfonyServerCodegen`). Move files to different directories. Fix #13022 

I did not change the directory of the `services.yaml` yet, because that would mean a change to the mustage: Bundle.mustache would get a `getPath` method with `return \dirname(__DIR__);` which would change the bundle directory to the root. If this is wanted let me know.

Because this is PHP: @jebentier , @dkarlovi , @mandrean , @jfastnacht , @ybelenko , @renepardon 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by lukadschaak** [comment]
update samples and fullfill the last step of the PR checklist.

**Comment by lukadschaak** [comment]
I know, 4 years are a long time, but is there no interest by one of the members of the PHP technical committee to review this?
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

**Comment by wing328** [comment]
@lukadschaak thanks for the PR. can yo please PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by wing328** [comment]
Tested locally and the build passed: 
```
[debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse".

[debug] Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest".

[debug] Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest".

SSSSSSSSSSSSSSSSSSSS.SSS.SS.SSSSSS.SSSSSS.SS.SSSSSSSS.........    62 / 62 (100%)

Time: 00:09.205, Memory: 26.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 62, Assertions: 21, Skipped: 47.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.392 s
[INFO] Finished at: 2022-09-08T22:44:17+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by wing328** [comment]
As discussed, this change may be breaking:

> If you use the php-symfony generator and never changed one of the generated files, then MAYBE the changes from the PR will not break your code.
Also, the most changes regards the usage of the generator option srcBasePath . Only if you use that one files will be moved.
Also if you are using an older version of Symfony like 4.4 (current LTS of Symfony is 5.4 and stable is 6.1 ) this changes like likely break your application.

(credit: @lukadschaak)

If that happens, we may add options to remediate the situation.

**Comment by wing328** [comment]
cc @plotbox-io, @dmetzner, @BenjaminHae, @Cubid who recently made enhancements to the PHP symfony generator.

**Comment by wing328** [comment]
If there's no further feedback, we'll merge it this weekend.

**Review by dmetzner — APPROVED** [review]

**Pull request merged**
