### PR TITLE
[Ruby] Auto recreate directories in Ruby samples

### PR DESCRIPTION
**Pull request by autopp**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. @cliffano (2017/07) @zlx (2017/09) @autopp (2019/02)

### Description of the PR

In order to guarantee update of sample for Ruby client (`samples/client/petstore/ruby`), `bin/ruby-client-petstore.sh` will purge `lib`, `doc`, `spec`.

Related PR: #2264

### CODE REVIEW

**Comment by wing328** [comment]
@autopp thanks for the PR, which has been merged into master.

I wonder if you can do the same to the Ruby Petstore batch file for Windows.

**Comment by autopp** [comment]
@wing328 Oops, I forgot about of `.bat`. I'll try it soon.

**Comment by autopp** [comment]
@wing328 Sorry, I don't have a development environment for Windows, so I can(t can't fix `.bat`. 😢 
I'll create a issue instead

**Comment by wing328** [comment]
@autopp no worries. I'll take care of it later when I've time.

**Pull request merged**
