### PR TITLE
[Extensions][Go][Java] Test x-auth-id-alias

### PR DESCRIPTION
**Pull request by jirikuncar**
Adds tests for go-experimental to test `x-auth-id-alias` extension.

Based on discussion in #6469.

- Go test file: https://github.com/OpenAPITools/openapi-generator/pull/6642/files#diff-8e0352a3f9f1548beef9453992b7719d

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07) @kemokemo (2018/09) @bkabrda (2019/07)

### CODE REVIEW

**Comment by jirikuncar** [comment]
cc @wing328 🙇‍♂️

**Comment by jirikuncar** [comment]
cc @jimschubert 🙇‍♂️

**Comment by jimschubert** [comment]
Tests are always welcome! Changes to java-jersey2 went in this past week, so I had to regenerate samples. But all looked good.

**Comment by jirikuncar** [comment]
Thank you @jimschubert

**Pull request merged**
