### PR TITLE
refactor: erefactor/AutoRefactor - Annotation

### PR DESCRIPTION
**Pull request by cal101**
AutoRefactor cleanup 'AnnotationCleanUp' applied by erefactor:

Simplifies annotation uses:
- empty parentheses will be removed from annotations,
- single members named "value" will be removed from annotations and
only the value will be left.

For AutoRefactor see https://github.com/JnRouvignac/AutoRefactor
For erefactor see https://github.com/cal101/erefactor

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

### CODE REVIEW

**Comment by cal101** [comment]
@wing328 Moin. (Means Hi ;-) Shall I try to split cleanup pull requests on sub project boundaries? What would be some computable criterium to detect the relevant sub project?

**Comment by wing328** [comment]
No. I think this is fine. Will review.

**Comment by wing328** [comment]
Quick question: what's the license for `erefactor` (https://github.com/cal101/erefactor)?

I assume its license is open-source friendly but would like to confirm as I only see a readme in that repo.

**Comment by cal101** [comment]
I never thought about the license on the changes itself.
I added an FAQ entry to erefactor readme to make clear, that erefactor does not claim any rights on the changes.

Which technical committee members shall I address future PRs to if any at all? The Java ones as here?

Do you have plans on reviving/applying the formatter that's configured in the POM file?
I can add that as a erefactor cleanup option and provide a PR on the changes if you like.

There are some cleanups that need a formatting step after application so having a usable formatter is nice to have.

There are some cleanups that depend more on project policy or style and may not fit or maybe 
are unwanted for OpenAPI.
I plan to make PRs for them at some time and you are totally free to say "No thanks, we prefer to do it differently."
OK for you?
IMO it's helpful to see the impact of some cleanup instead of just talking about its effect.

If PRs can't be rebased automatically the cleanups can be re-applied on the head, just tell me in the comments.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
@cal101 thanks for the explanation and the change looks good to me.

**Comment by wing328** [comment]
CircleCI failure not related to this change.

**Pull request merged**
