### PR TITLE
[JAVA] Update Gradle in generated Java projects from 2.14.1 to 6.0.1

### LINKED ISSUE #4535: [REQ] [JAVA] Update Gradle used in generated projects
### Is your feature request related to a problem? Please describe.
The version of Gradle used in generated Java projects is ~3 years out of date, but more importantly Gradle has changed dramatically in that time. The syntax used has evolved and the features available have improved. Using the current version in the generated projects (Gradle 2) is extremely limiting when it comes to adding things by overriding the templates.

## Describe the solution you'd like

Upgrade Gradle to the latest version feasible

## Describe alternatives you've considered

- Work around the issues outside of the generated project (works but it sucks)
- Upgrade Gradle in templates and override the old version (works but doesn't help community)

### PR DESCRIPTION
**Pull request by tobymurray**
Resolves #4535

Updated the Gradle version used in the generated Java client projects, as well as the samples. For my own use case (using OkHttp), the generated Java jar works without any changes, but I have no customizations in my `build.gradle` that may cause issues. 

So far as I can tell, Gradle is backwards compatible in the capacity it's used within these Java projects. With that said, this does _not_ update the Gradle build script files to what would be more idiomatic of current Gradle, as I'm hoping the smaller the change the less contentious it is. A logical follow up of this would be to update e.g. `build.gradle.mustache` to reflect some of changes Gradle has made in the last few years.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
> but I have no customizations in my build.gradle that may cause issues.

If the user customize build.gradle template, it should be within their expectation the upgrade may not work.

**Comment by tobymurray** [comment]
I added 32a9c0c to reconcile the only case where a java project overrides the default Gradle wrapper, but I don't understand this bitrise CI failure. I don't think it's related to the work in this PR, or if it is I'm not clear how.

**Comment by wing328** [comment]
Tested locally and the result is good. Thanks for the contribution.

**Comment by wing328** [comment]
@tobymurray thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Pull request merged**
