### PR TITLE
[scala-sttp] fix enumeration operator constant name collision

### PR DESCRIPTION
**Pull request by bgong-mdsol**
This PR fixes the issue [#10187](https://github.com/OpenAPITools/openapi-generator/issues/10187)

Here is the openapi spec that can be used to reproduce the issue and verify the fix. 
  ```
openapi: 3.0.3
info:
  title: The comparison operator
  version: '1.0'
paths:
  /state:
    get:
      operationId: getReport
      responses:
        '200':
          description: get Report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reports'
components:
  schemas:
    Reports:
      properties:
        name:
          type: string
        expression:
          items:
            $ref: '#/components/schemas/Condition'
          type: array
    Condition:
      example:
        variable: variable
        operator: =
        comparison_value: comparison_value
      properties:
        variable:
          type: string
        comparison_value:
          type: string
        operator:
          description: The comparison operator.
          enum:
          - =
          - '!='
          - '>'
          - <
          - '>='
          - <=
          type: string
      type: object
  ```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@chameleon82 @clasnake @jimschubert @shijinkui @ramzimaalej @Bouillie @wing328 @jfeltesse-mdsol @jcarres-mdsol

### CODE REVIEW

**Comment by chameleon82** [comment]
Hi @bgong-mdsol,
Thank you for the PR. 
Wondered if you could provide actual use case for those enums. Would it be better to use named enums like 'LESS_OR_EQUALS_THAN` in the first place rather than `"<="`?

**Comment by jfeltesse-mdsol** [comment]
@chameleon82 the sample openapi file is an excerpt of an API that one of the many services our organization manages provides. This is a valid openapi file and as such the generator should support such edge cases, however questionable the API design may seem.

**Comment by agilob** [comment]
Could you add tests for the changes?

**Comment by jfeltesse-mdsol** [comment]
@chameleon82 @agilob can you have a look at the tests that were added in that last commit? 🙇

**Comment by wing328** [comment]
The CircleCI failure is not related to this PR. If you merge latest master into this branch, it should resolve it.

**Comment by bgong-mdsol** [comment]
@[wing328](https://github.com/wing328) Sorry for late reply, I have merged latest master into this branch, thanks

**Pull request merged**
