### PR TITLE
[FIX][csharp-netcore] fixed anyOf/oneOf generating non-compilable code (null-coalescing operator on enum)

### LINKED ISSUE #13384: [BUG][csharp-netcore] anyOf/oneOf generates non-compilable code (null-coalescing operator on enum)
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
AnyOf/OneOf with an enum will generate non-compilable C# code (using null coalescing operator on an enum):
For instance with a oneof parameter schema:
```json
"schema": {
  "oneOf": [
	{
	"title": "firstEnum",
	"enum": [
		"one",
		"two"
	  ]
	},
	{
	"title": "secondEnum",
	"type": "integer",
	"enum": [
		"0",
		"1"
	]
	}
  ]
}
```
Incorrect code:
```csharp
        /// <summary>
        /// Initializes a new instance of the <see cref="MyOperationAParameter" /> class
        /// with the <see cref="FirstEnum" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of FirstEnum.</param>
        public MyOperationAParameter(FirstEnum actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyOperationAParameter" /> class
        /// with the <see cref="SecondEnum" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SecondEnum.</param>
        public MyOperationAParameter(SecondEnum actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }
```
Expected output:
```csharp
        /// <summary>
        /// Initializes a new instance of the <see cref="MyOperationAParameter" /> class
        /// with the <see cref="FirstEnum" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of FirstEnum.</param>
        public MyOperationAParameter(FirstEnum actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyOperationAParameter" /> class
        /// with the <see cref="SecondEnum" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SecondEnum.</param>
        public MyOperationAParameter(SecondEnum actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }
```

##### openapi-generator version
6.0.1

##### OpenAPI declaration file content or url

anyOf/oneOf with an enum.
See in Description.

##### Steps to reproduce

generate csharp-netcore project with any specification file containing similar anyOf/oneOf.

##### Suggest a fix

I'll reference this in fix PR.

### PR DESCRIPTION
**Pull request by Ikelio**
Fixes #13384

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti

### CODE REVIEW

**Comment by Ikelio** [comment]
Can we rerun the tests pls ? I can't see a reason for the csharp netcore .mustache changes to create a timeout during typescript tests.

**Comment by wing328** [comment]
@Ikelio thanks for the PR. Can we add the test spec mentioned in the issue to the csharp test spec so that we've this case covered moving forward?

```
"schema": {
  "oneOf": [
	{
	"title": "firstEnum",
	"enum": [
		"one",
		"two"
	  ]
	},
	{
	"title": "secondEnum",
	"type": "integer",
	"enum": [
		"0",
		"1"
	]
	}
  ]
}
```

**Comment by Ikelio** [comment]
@wing328 yes, where should I do that ?

**Comment by C0DK** [comment]
can we bump this?

**Comment by wing328** [comment]
@Ikelio can you please resolve the merge conflicts when you've time?

**Comment by wing328** [comment]
@C0DK would you like to sponsor @Ikelio to give this PR a higher priority?

**Comment by wing328** [comment]
@Ikelio  I tested with the latest master and can no longer repeat the issue (code compiles)

Can you please test with v7.0.1 to see if this fix is still needed? Thanks.

**Pull request closed without merging**
