### PR TITLE
[kotlin][client] update dependencies [WIP]

### PR DESCRIPTION
**Pull request by 4brunu**
This PR updates the dependencies in the gradle file of the kotlin client.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
cc @jimschubert (2017/09), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11)

**Comment by jimschubert** [comment]
Looks good to me so far. I've labeled WIP so it's more clear (I almost missed it in the title). I believe you can also open a draft PR which would prevent accidental merges while in-progress.

**Comment by 4brunu** [comment]
@jimschubert Oh, I didn't remind about the draft, thanks for the suggestion 👍 
By the way, I'm fighting the kotlintest library when updating it.
With versions "io.kotlintest:kotlintest-runner-junit5:3.1.4" and bellow all the unit tests pass.
With versions "io.kotlintest:kotlintest-runner-junit5:3.1.5" and above some the unit tests fail.
Do you have an idea why?

**Comment by jimschubert** [comment]
@4bruno sorry, just getting caught up on some older issues...

I'm not sure why that would fail. It's possible a regression in that newer build. I would suggest sticking to io.kotlintest:kotlintest-runner-junit5:3.1.4 for now. It's reasons like those that we update closer to minor version (breaking change with fallback). If a user generates models/tests and this upgrade causes their tests to fail, that's a breaking change.

**Comment by 4brunu** [comment]
@jimschubert looks good to me, I will close this PR 👍

**Pull request closed without merging**
