### PR TITLE
Use LinkedHashMap for deterministic iteration order

### PR DESCRIPTION
**Pull request by Yilinwang**
The tests `org.openapitools.codegen.kotlin.AbstractKotlinCodegenTest#convertModelName`, `org.openapitools.codegen.kotlin.AbstractKotlinCodegenTest#convertVarName` and `org.openapitools.codegen.DefaultCodegenTest#verifyXDiscriminatorValue` can fail due to a different iteration order of HashMap. The failures are as follows:
```
java.lang.AssertionError: expected [PonyGreaterThanEqualGreaterThanEqual] but found [PonyGreaterThanOrEqualToEqualGreaterThanOrEqualToEqual]
    at org.openapitools.codegen.kotlin.AbstractKotlinCodegenTest.convertModelName(AbstractKotlinCodegenTest.java:123)

java.lang.AssertionError: expected [ponyGreaterThanEqualGreaterThanEqual] but found [ponyGreaterThanOrEqualToEqualGreaterThanOrEqualToEqual]
    at org.openapitools.codegen.kotlin.AbstractKotlinCodegenTest.convertVarName(AbstractKotlinCodegenTest.java:136)

java.lang.AssertionError: Lists differ at element [0]: daily != sub-obj expected [daily] but found [sub-obj]
    at org.openapitools.codegen.DefaultCodegenTest.verifyXDiscriminatorValue(DefaultCodegenTest.java:1351)
```

The specification about HashMap says that "this class makes no guarantees as to the order of the map; in particular, it does not guarantee that the order will remain constant over time". The documentation is here for your reference: https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html

The fix is to change it to a LinkedHashMap so that the iteration order remains stable and the failure will not occur any more. In this way, the test will be more stable.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Tests failed. Please refer to https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/744096190 for more information.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team as it's impacting the default codegen class.

**Comment by cbornet** [comment]
LGTM

**Comment by Yilinwang** [comment]
Thanks for replying. Changed the author but not sure if it works properly.
Also, not sure what caused the failures. I think maybe it's `generate-sample.sh`? After running `generate-sample.sh` I did local tests and passed, any suggestion?

**Comment by wing328** [comment]
Thanks for the PR. Sorry for the delay in reviewing the change.

I've resolved the merge conflicts and filed https://github.com/OpenAPITools/openapi-generator/pull/12230 instead.

**Pull request closed without merging**
