### PR TITLE
[R] Add authentication support, minor ApiClient refactor

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- Renamed `response` to `ApiResponse`
- Added authentication support
- Fixed "testthat.R" location
- Updated NAMESPACE with ApiClient, ApiResponse
- Removed userAgent from API class
- Updated ApiClient constructor to use optional arguments

### CODE REVIEW

**Comment by Ramanth** [comment]
Hi, The toJSONString() method throwing error when user passes only few parameters to the model class.
This happens when there are few non-mandatory parameters which are not required to be passed and in that case, for non-primitive type parameters the serialization is failing.

Can someone let me know if there is a way to handle it or is it planned to be released soon?

**Details:**
Error is being thrown at the below line in the model files generated from the mustache
`paste(unlist(lapply(self$`{{{baseName}}}`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE))), collapse=",")`

where the self${{baseName}} is NULL (as the parameter is not mandatory, i didnt assign it), so the above line is throwing an error when trying to apply toJSON() on the NULL object.

Please let us know if this will be fixed or any approach i can follow to overcome this.
Thanks in advance.

Regards,
Ramanth.

**Comment by wing328** [comment]
@Ramanth thanks for reporting the issue. It would be nice if you can share more details on how to reproduce the issue via https://gist.github.com or other channels.

**Comment by Ramanth** [comment]
@wing328 i have created a sample code describing the issue. hope that would be helpful. let me know if you need any clarity.
https://gist.github.com/Ramanth/9a96e73600853c3407a96205ec47daa4
Thanks

**Comment by Ramanth** [comment]
@wing328  please find the sample code shared to demonstrate how i am encountering the error. Hope this would be helpful. let me know if you need any more info.
https://gist.github.com/Ramanth/af6a24af0765275aad87b788458d14b2
Thanks.

**Pull request merged**
