### PR TITLE
[java/resttemplate] Generate valid code if no Authentication implementations present

### PR DESCRIPTION
**Pull request by jonfreedman**
Take the logic used to decide which instances to add to the authentications map and re-use to not import classes or offer non-functional util methods

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog

### CODE REVIEW

**Comment by wing328** [comment]
@jonfreedman thanks for the PR. Look like the change will results in duplicated import `org.openapitools.client.auth.ApiKeyAuth`:
```diff
--- a/samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
+++ b/samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
@@ -59,12 +59,12 @@ import java.util.Map.Entry;
 import java.util.TimeZone;
 
 import org.openapitools.client.auth.Authentication;
-import org.openapitools.client.auth.HttpBasicAuth;
-import org.openapitools.client.auth.HttpBearerAuth;
+
+import org.openapitools.client.auth.ApiKeyAuth;
 import org.openapitools.client.auth.ApiKeyAuth;
+import org.openapitools.client.auth.HttpBasicAuth;
 import org.openapitools.client.auth.OAuth;
```

**Comment by jonfreedman** [comment]
Can you please check the population of the authentications map, if there's a duplicate import I guess there must be a duplicate put too?
If that's the case do you think it's better to add more variables like hasOAuthMethods instead?

**Comment by wing328** [comment]
Yes, we have `{{#hasOAuthMethods}} ... {{/hasOAuthMethods}}`, e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/pom.mustache#L221

**Comment by jonfreedman** [comment]
Yep I saw that one, but would also need hasBasicAuthMethods, hasTokenAuthMethods etc. which I assume don't exist yet?

**Comment by wing328** [comment]
> but would also need hasBasicAuthMethods, hasTokenAuthMethods etc. which I assume don't exist yet?

Can you please add hasBasicAuthMethods, hasTokenAuthMethods, etc as part of this PR?

**Comment by jonfreedman** [comment]
I can give it a go - can you point me in the right direction?

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/9323cad06ba7a42dee3219f5349f516b201860fa/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java#L1276 is a good starting point.

And then add similar checks in https://github.com/OpenAPITools/openapi-generator/blob/9323cad06ba7a42dee3219f5349f516b201860fa/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java#L842

**Comment by wing328** [comment]
Closing this as there's no update. Please open a new one when you've time.

Thanks again for the PR.

**Pull request closed without merging**
