### PR TITLE
WIP Minimal maven->gradle evaluation

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Evaluating what it would take to convert from maven to gradle. See #200

### CODE REVIEW

**Comment by jmini** [comment]
What about `openapi-generator-maven-plugin` ? I have the feeling that your current conversion is not creating a valid maven plugin out of the source code.

We need to apply a gradle plugin to replace the fact that the maven project is a `<packaging>maven-plugin</packaging>`. Something like https://plugins.gradle.org/plugin/com.liferay.maven.plugin.builder (or an other one, I just did a quick google search).

**Comment by jimschubert** [comment]
@jmini thanks for doing a search for that.

I expect this PR to take some time (a week or more). It will not only need to update maven -> gradle build scripts, but also CI scripts, hard-coded build outputs in all samples scripts (around 400 scripts, mostly search/replace but need to be visually checked), Docker scripts, etc.  Looking at our CI scripts, I see some areas for various improvements which I'll probably do as a part of this PR.

Do you think it would be helpful if I create a TODO list for tracking items as I find them, and as I finish them up? This way we can track my progress.

**Comment by jmini** [comment]
I am really glad you start this. I imagine this will be a lot of work.

Maybe you can put your TODO list directly in the issue #200. This way I can see if I have additional ideas. 

I also would like to test from time to time. I will wait until you tell that there is something that is ready to be tested locally.

**Comment by jimschubert** [comment]
This is on hold, pending investigation/research on issues with deploying from Travis CI to Sonatype via gradle.

**Comment by jimschubert** [comment]
Travis deploys have cleaned up. But I'm closing this since I'd basically need to redo it at this point.

**Pull request closed without merging**
