### PR TITLE
[Perl] Update _test.mustache templates to use done_testing

### PR DESCRIPTION
**Pull request by bmodotdev**
This is to address bug report #14921. 

When running `prove -l` on the Perl petstore samples, several tests report "Looks like you planned 2 tests but ran 1" or "Bad plan". Below are my steps:
```
$ perlbrew use perl-5.36.0
$ perlbrew upgrade-perl
$ perlbrew clean
$ perl -E'say $]'
5.036003

$ sudo apt install openjdk-17-jre maven
$ ./mvnw clean package
$ /bin/rm samples/client/petstore/perl/t/*Test.t
$ ./bin/generate-samples.sh ./bin/configs/perl.yaml
$ cpanm Class::Accessor Test::Exception Test::More Log::Any LWP::UserAgent URI::Query Module::Runtime DateTime Module::Find Moose::Role JSON
$ cd samples/client/petstore/perl/
$ prove -l
# Looks like you planned 2 tests but ran 1.
t/AdditionalPropertiesClassTest.t ......................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests
# Looks like you planned 2 tests but ran 1.
t/AllOfWithSingleRefTest.t .............................
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/2 subtests
# Looks like you planned 2 tests but ran 1.
t/AnimalTest.t .........................................

[... etc ...]
```
The full output is available in my gist [prove1.txt](https://gist.github.com/bmodotdev/6b1500655b3271ad3489b262ab6c3b1f#file-prove1-txt) 

Given the generative/dynamic nature of this project, I believe using [Test::More::done_testing](https://metacpan.org/pod/Test::More#done_testing) is sufficient. I've updated `modules/openapi-generator/src/main/resources/perl/object_test.mustache` and`modules/openapi-generator/src/main/resources/perl/api_test.mustache` to use `done_testing()`. My fixup commit includes the results of the next steps I took:
```
$ /bin/rm samples/client/petstore/perl/t/*Test.t
$ ./bin/generate-samples.sh ./bin/configs/perl.yaml
$ cd samples/client/petstore/perl/
$ prove -l
t/AdditionalPropertiesClassTest.t ...................... ok
t/AllOfWithSingleRefTest.t ............................. ok
t/AnimalTest.t ......................................... ok

[... etc ...]

#   Failed test 'use WWW::OpenAPIClient::Object::TestInlineFreeformAdditionalPropertiesRequest;'
#   at t/TestInlineFreeformAdditionalPropertiesRequestTest.t line 28.
#     Tried to use 'WWW::OpenAPIClient::Object::TestInlineFreeformAdditionalPropertiesRequest'.
#     Error:  Can't locate WWW/OpenAPIClient/Object/AnyType.pm in @INC (you may need to install the WWW::OpenAPIClient::Object::AnyType module) (@INC contains: lib /home/user/git/openapi-generator/samples/client/petstore/perl/lib /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.3/x86_64-linux-thread-multi /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.3 /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/5.36.3/x86_64-linux-thread-multi /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/5.36.3 /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.1/x86_64-linux-thread-multi /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.1 /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.0 /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl) at lib/WWW/OpenAPIClient/Object/TestInlineFreeformAdditionalPropertiesRequest.pm line 33.
# BEGIN failed--compilation aborted at lib/WWW/OpenAPIClient/Object/TestInlineFreeformAdditionalPropertiesRequest.pm line 33.
# Compilation failed in require at t/TestInlineFreeformAdditionalPropertiesRequestTest.t line 28.
# BEGIN failed--compilation aborted at t/TestInlineFreeformAdditionalPropertiesRequestTest.t line 28.
# Looks like you failed 1 test of 1.
t/TestInlineFreeformAdditionalPropertiesRequestTest.t ..
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/UserApiTest.t ........................................ ok
t/UserTest.t ........................................... ok

Test Summary Report
-------------------
t/TestInlineFreeformAdditionalPropertiesRequestTest.t (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
Failed test:  1
Non-zero exit status: 1
Files=57, Tests=64,  7 wallclock secs ( 0.07 usr  0.04 sys +  6.02 cusr  0.83 csys =  6.96 CPU)
Result: FAIL
```

The full output is available in my gist [prove2.txt](https://gist.github.com/bmodotdev/6b1500655b3271ad3489b262ab6c3b1f#file-prove2-txt).

Note this error is present before my changes, so at least this is an increase in tests passing, but not 100%. I am still wrapping my head around how this project works, so I am not yet familiar enough to fix this "AnyType.pm" error. Indeed, there is no WWW/OpenAPIClient/Object/AnyType.pm module. I noticed [docs/generators/perl.md](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/perl.md) has a table of "Data Type Features" which "AnyType" is marked as :x:. Maybe there is some config option to disable this unimplemented type? Anyway, I will open an additional issue regarding this error (here #17650).

Open to any suggestions or docs to dig further into the issue.

Thank you for the awesome project :smile: 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. [perl] @wing328 @yue9944882

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. can you please update the perl samples one more time?

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by bmodotdev** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

Woops, I was signing with my GitLab email. I had to force-push to resign.

> thanks for the PR. can you please update the perl samples one more time?
I have done this in my last fixup.

Let me know if you would prefer me to squash. I assume GitHub merge has autosquash for fixup commits.

**Comment by wing328** [comment]
no need to squash. we will do it when merging your PR.

**Pull request merged**
