### PR TITLE
[haskell-http-client] regen samples

### PR DESCRIPTION
**Pull request by jonschoning**

### CODE REVIEW

**Comment by wing328** [comment]
@jonschoning shall we add the following to [./bin/utils/ensure-up-to-date](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/utils/ensure-up-to-date#L33) to ensure the haskell-http-client samples are always up-to-date?
```
./bin/haskell-http-client-petstore.sh
```

**Comment by jonschoning** [comment]
Actually the example app for haskell-http-client is built against the `OAS3` yaml file instead of the OAS2 yaml file, so due to that, I would be ok with adding `bin/openapi3/haskell-http-client-petstore.sh` to ensure-up-todate (if we only wanted the OAS2 input file e.g. `bin/haskell-http-client-petstore.sh` then i'd have to fix the example app in the sample folder to use types from the OAS2 input yaml file)

**Comment by wing328** [comment]
Feel free to use scripts in `bin/openapi3/scripts`, e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/bin/utils/ensure-up-to-date#L27

**Comment by jonschoning** [comment]
done

**Pull request merged**
