### PR TITLE
[Ruby] Fix regualr expression in error message (#2069)

### LINKED ISSUE #2069: [BUG] Generated Ruby client contains syntax errors when pattern of properties includes single-quote
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When `pattern` includes odd number of single quotes, the generated Ruby client code contains syntax errors.

##### openapi-generator version

```
$ java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar version
4.0.0-SNAPSHOT

$ git log --oneline -n 1
0b66fa5c82 (HEAD -> master, origin/master, origin/HEAD) add servers to path, operation (#2048)
```

##### OpenAPI declaration file content or url

See: https://gist.github.com/autopp/e707d5d2ec36f7cfe6a3950d76d54b6f#file-swagger-yml

The point to notice in this example is that `'` is included in the pattern constraint of the property `y` of the model `x`.

##### Command line used for generation

```
$ java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate --skip-validate-spec -g ruby -o /tmp/gem -i 'https://gist.githubusercontent.com/autopp/e707d5d2ec36f7cfe6a3950d76d54b6f/raw/0ca732fa77402c3dcbb735e41eb5f6e5bc58462d/swagger.yml'
```

##### Steps to reproduce

1. Run the above command to generate client code for Ruby.
1. Run `ruby -c /tmp/gem/lib/openapi_client/models/x.rb` to check syntax of the generated model code.
1. Get errors in `lib/openapi_client/models/x.rb`:
   ```
   /tmp/gem/lib/openapi_client/models/x.rb:51: syntax error, unexpected '.'
   ...ust conform to the pattern /'/.')
   ...                              ^
   /tmp/gem/lib/openapi_client/models/x.rb:60: syntax error, unexpected ')'
   ...y.nil? && @y !~ Regexp.new(/'/)
   ...                              ^
   /tmp/gem/lib/openapi_client/models/x.rb:68: syntax error, unexpected '.'
   ...ust conform to the pattern /'/.'
   ...                              ^
   /tmp/gem/lib/openapi_client/models/x.rb:206: unterminated string meets end of file
   /tmp/gem/lib/openapi_client/models/x.rb:206: syntax error, unexpected end-of-input, expecting keyword_end
   ```

##### Related issues/PRs

#2067

##### Suggest a fix

`escapeText` of `RubyClientCodegen` seems to escape for double-quote string literals only. However, the corresponding template uses a single quote string.
I think it is difficult for the generator to determine whether the expansion destination is a single-quote string or a double-quote string. Instead, I think that it is better to unify it with a double-quote string in the template.

### PR DESCRIPTION
**Pull request by autopp**
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Fix #2069.

- To correctly embedding the regualr expression into error message, it's changed to string interpolation.
- Unnecessary invocation of `Regexp.new` is deleted. (`Regexp.new(/.../)` -> `/.../`)

### CODE REVIEW

**Comment by wing328** [comment]
@autopp thanks for the PR. If my memory serves me well, the reason of using `Regexp.new` is that not all pattern specified in the spec follows the `/.../` pattern.

**Comment by autopp** [comment]
@wing328 Thanks for review!

> If my memory serves me well, the reason of using `Regexp.new` is that not all pattern specified in the spec follows the `/.../` pattern.

I thought that all patterns follow the `/.../` because all patterns are processed by [`toRegularExpression`](https://github.com/OpenAPITools/openapi-generator/blob/804b589/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRubyCodegen.java#L150-L152) and [`addRegularExpressionDelimiter`](https://github.com/OpenAPITools/openapi-generator/blob/804b589/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L4062-L4072).

In any case, since this is not directly related to the purpose of this PR, I will remove it once.
If it really is OK to remove this, I will re-submit Issue and PR.

**Comment by wing328** [comment]
@autopp let me try to dig out the discussion by this weekend. Then we can decide whether to proceed with this PR or not. Stay tuned.

**Comment by autopp** [comment]
@wing328 I rebased.

**Comment by autopp** [comment]
@wing328  Oh, I'm sorry...I fixed it before I saw your reply 😢 
We can set it back again if necessary, so leave it until the weekend.

**Comment by wing328** [comment]
@autopp that's ok bro.

**Comment by ackintosh** [comment]
https://travis-ci.org/OpenAPITools/openapi-generator/builds/492733373?utm_source=github_status&utm_medium=notification
> The job exceeded the maximum time limit for jobs, and has been terminated.

I've restarted the job. 😉

**Comment by autopp** [comment]
@ackintosh Thanks!
Looking at the recent Travis's build history, it seems that there are many things that have exceeded the time limit.
I think it would be nice to parallelize the job of Travis with Build stage, for example.
https://docs.travis-ci.com/user/build-stages/
(Because I am not familiar with CI jobs, this may be misplaced.)

**Comment by autopp** [comment]
@wing328 How shall we do this PR after all?
If it takes time to check the necessity of `Regexp.new`, I think that it is possible to merge in this state once.

**Comment by wing328** [comment]
@autopp let's go with what you've at the moment. We can always update the templates to handle more edge cases.

**Comment by autopp** [comment]
@wing328 Thanks!

**Pull request merged**
