### PR TITLE
New python-fastapi generator

### PR DESCRIPTION
**Pull request by krjakbrjak**
Added a new python generator of a server stub for [FastAPI](https://fastapi.tiangolo.com/).

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)

### CODE REVIEW

**Comment by krjakbrjak** [comment]
#8697

**Comment by wing328** [comment]
Looks good to start with. I'll create a PR make some minor enhancements to the generator after merging this PR.

**Comment by wing328** [comment]
@krjakbrjak I've filed https://github.com/OpenAPITools/openapi-generator/pull/9622 for minor improvements. Please take a look when you've time.

Please PM me via https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM to have a quick chat on this new generator. Thanks.

**Comment by AdityaMayukhSom** [comment]
Is there any plans to provide an option for delegate pattern for this generator? My usecase would be to generate the API routes and models and publish them as a package instead, so to not modify any code generated by the generator. Currently I know the apis folders includes the base classes that needs to be implemented, but the generated code structure contains many other files such as docker compose setup, tests and an impl directory, is there any workarounds for this available?

**Pull request merged**
