### PR TITLE
Fix spring child constructor missing parent params

### LINKED ISSUE #15796: [BUG][JAVA] Java Spring generator fails to generate working models with multiple inheritance layers
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Hello everyone,

I'm currently upgrading from OpenAPI Generator v5.4.0 to v6.6.0 and I've run into an issue with schemas that define multiple levels of inheritance using two separate discriminators. It seems that for models that have more than one level of inheritance depth the generated Java classes are a bit broken. There are two issues that I have encountered:
- Child classes don't have all required parameters needed to pass to the parents in the constructor which results in compilation errors. 
```java
public class Poodle extends Dog {

  private String hairType;

  /**
   * Default constructor
   * @deprecated Use {@link Poodle#Poodle(String)}
   */
  @Deprecated
  public Poodle() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public Poodle(String type) {
    super(race, type); <- race parameter is not a constructor param for the Poodle class nor it is a field of this class
  }
}

public class Dog extends Pet {

  private Integer tails;

  private String race;

  /**
   * Default constructor
   * @deprecated Use {@link Dog#Dog(String, String)}
   */
  @Deprecated
  public Dog() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public Dog(String race, String type) {
    super(type);
    this.race = race;
  }
}
```
- Grandparent class has too many mappings using @JsonSubTypes. It seems that JsonSubTypes are generated for all classes that inherit from the grandparent class instead only for the explicitly configured classes using the `mapping` property in the `discriminator`. I would expect only the first two mappings to appear (`CAT` and `DOG`). Parent classes have their @JsonSubTypes set properly.
```java
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Cat.class, name = "CAT"),
  @JsonSubTypes.Type(value = Dog.class, name = "DOG"),
  @JsonSubTypes.Type(value = Labrador.class, name = "Labrador"),
  @JsonSubTypes.Type(value = MaineCoon.class, name = "MaineCoon"),
  @JsonSubTypes.Type(value = Persian.class, name = "Persian"),
  @JsonSubTypes.Type(value = Poodle.class, name = "Poodle")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-06-09T14:33:49.208185800+02:00[Europe/Warsaw]")
public class Pet {

  private String name;

  private String type;

  /**
   * Default constructor
   * @deprecated Use {@link Pet#Pet(String)}
   */
  @Deprecated
  public Pet() {
    super();
  }

  /**
   * Constructor with only required parameters
   */
  public Pet(String type) {
    this.type = type;
  }
}
```

Using v5.4.0 JsonSubTypes are properly set
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = Cat.class, name = "CAT"),
  @JsonSubTypes.Type(value = Dog.class, name = "DOG"),
})
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-06-09T14:40:51.917945+02:00[Europe/Warsaw]")
public class Pet   {

  @JsonProperty("name")
  private String name;

  @JsonProperty("type")
  private String type;
}
```

I'm able to circumvent the first issue using `--additional-properties=generatedConstructorWithRequiredArgs=false` as a workaround although it would be nice to have all the constructors. Second one is something that I could not work out. 

##### openapi-generator version

I'm using version 6.6.0, previously I've used 5.4.0 and this structure worked as expected.

##### OpenAPI declaration file content or url

[Yaml](https://gist.github.com/Kustosh/0a03c534dfc9fd57e2a57c9eef1a045f)

##### Generation Details

Generated using openapi generator gradle plugin 

##### Related issues/PRs

#15148

### LINKED ISSUE #16797: [BUG] OpenAPIGenerator v7.0.1 and v6.6.0 is unable to generate a child class's constructor that could be constructed successfully with v6.0.1
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

OpenAPIGenerator v7.0.1 and v6.6.0 is unable to generate a child class's constructor that could be constructed successfully with v6.0.1
We were using this .yaml snippet to define a response type:

    ListTimesheetsResponse:
      description: The response for listing timesheets
      allOf:
        - $ref: '#/components/schemas/SuccessPagingResponseV1'
        - type: object
          description: |
            The list of timesheets
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/Timesheet'

using v7.0.1 and v6.6.0 generated code as such:

    @Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-10-11T21:11:03.837084888Z[Etc/UTC]")
    public class ListTimesheetsResponse extends SuccessPagingResponseV1 {
    
      @Valid
      private List<@Valid Timesheet> data;
    
      public ListTimesheetsResponse() {
        super();
      }
    
      /**
       * Constructor with only required parameters
       */
      public ListTimesheetsResponse(String responseType, Boolean success) {
        super(pageInfo, responseType, success);
      }

As shown in the code, the **pageInfo** variable used in the constructor is neither defined nor passed in as a parameter anywhere.

While using v6.0.1 generates the valid code.

##### openapi-generator version
v7.0.1 and v6.6.0

##### OpenAPI declaration file content or url
included in description

This is the definition of the parent class for reference:

    SuccessPagingResponseV1:
      description: |
        Another base success response
      allOf:
        - $ref: '#/components/schemas/SuccessResponseV1'
      properties:
        pageInfo:
          description: Information on the page of data contained in the response.
          $ref: '#/components/schemas/ResponsePagingInfoV1'
      required:
        - pageInfo
      

##### Steps to reproduce
Set up the repository and simply run `mvn clean install`, such error would be prompted:
`[ERROR] /Users/tegee/talech/git/microservices/ts_service/target/generated-sources/src/main/java/com/talech/platform/microservicecommons/controller/dto/ListTimesheetsResponse.java:[46,10] error: pageInfo has private access in SuccessPagingResponseV1`

### PR DESCRIPTION
**Pull request by dabdirb**
to fix #16797 
to fix #15796

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

i  just fix this issue on spring, i suppose this issue also impact other java projects. the root cause should be in DefaultCodegen.java updateModelForComposedSchema().  @wing328  i think you are the best people to figure out why the "required" is wrong.

### CODE REVIEW

**Comment by wing328** [comment]
cc @cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg (2023/08)

**Comment by wing328** [comment]
Thanks for the PR.

> i just fix this issue on spring, i suppose this issue also impact other java projects. the root cause should be in DefaultCodegen.java updateModelForComposedSchema()

I've no idea either. I'll try to take a look later.

How urgent is this fix?

**Comment by dabdirb** [comment]
Current fix just as a workaround patch, I think you can postpone the merge.
I need about 1 week to dive into legacy code, to figure out the root cause for all java models.

**Comment by dabdirb** [comment]
narrow down the bug range, in DefaultCodegen.java, addProperties() not add all properties

**Comment by dabdirb** [comment]
@martin-mfg i found https://github.com/OpenAPITools/openapi-generator/pull/16992  also fix this issue, i will rollback my change on DefaultCodegen.java, only kept an error log check.
@wing328  this pull request only add UT cases and error log.

**Review by martin-mfg — APPROVED** [review]

**Comment by wing328** [comment]
please resolve the merge conflicts when you've time

heads-up: https://github.com/OpenAPITools/openapi-generator/pull/18238 also touches the spring codegen test file.

cc @OpenAPITools/generator-core-team

**Comment by dabdirb** [comment]
The code already in master branch, by @martin-mfg, so after catch up merge, change line is 0.

**Comment by martin-mfg** [comment]
> The code already in master branch, by @martin-mfg, so after catch up merge, change line is 0.

for reference, the corresponding PR is #17490.

I don't remember why I included your changes in my PR, but it looks like a mistake to me. Sorry for that!

**Pull request closed without merging**
