### PR TITLE
Support net8 in aspnetcore

### PR DESCRIPTION
**Pull request by ReallyLiri**
Adding support for net8.0 (and 7.0) in aspnetcore generator.

Tagging @iBicha for C#

### CODE REVIEW

**Comment by wing328** [comment]
@ReallyLiri thanks for the PR

can you please copy .github/workflows/samples-dotnet6-server.yaml to create another workflow for donet8 ?

**Comment by ReallyLiri** [comment]
> @ReallyLiri thanks for the PR
> 
> can you please copy .github/workflows/samples-dotnet6-server.yaml to create another workflow for donet8 ?

Done :)

**Comment by ReallyLiri** [comment]
I see generated code doesn't compile, will check

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/9871790259/job/27260628583?pr=19051 not caused by this PR (should already been fixed in the master)

**Comment by wing328** [comment]
cc 
@mandrean (2017/08) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)

**Comment by wing328** [comment]
thanks for the PR. let's get it merged so that we can get some feedback from our users.

**Pull request merged**
