### PR TITLE
fix: [typescript-angular] duplicate export of request params when `useSingleRequestParameter`

### LINKED ISSUE #13200: [BUG][typescript-angular] Multiple tags and `useSingleRequestParameter` cause duplicate export
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
  - Issue is still present in master https://github.com/snebjorn/openapi-gen-bug/tree/master/output-master/export-bug
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Defining operations with multiple tags leads to duplicate export.

https://github.com/snebjorn/openapi-gen-bug/blob/ad3851d72b3a9bfe8bc49604730d013e03813b73/export-bug.json#L19

> Module './tag1.service' has already exported a member named 'FoosParam1BarsGetRequestParams'. Consider explicitly re-exporting to resolve the ambiguity. ts(2308)

`FoosParam1BarsGetRequestParams` is declared in both these places:
- https://github.com/snebjorn/openapi-gen-bug/blob/ad3851d72b3a9bfe8bc49604730d013e03813b73/output-6.0.1/export-bug/api/tag1.service.ts#L27
- https://github.com/snebjorn/openapi-gen-bug/blob/ad3851d72b3a9bfe8bc49604730d013e03813b73/output-6.0.1/export-bug/api/tag2.service.ts#L27

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/snebjorn/openapi-gen-bug/master/export-bug.json
```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "",
    "version": ""
  },
  "paths": {
    "/Foos/{Param1}/Bars": {
      "parameters": [
        {
          "name": "Param1",
          "in": "path",
          "required": true,
          "description": "",
          "schema": { "type": "string" }
        }
      ],
      "get": {
        "tags": ["Tag1", "Tag2"],
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    }
  }
}
```

##### Generation Details

```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i https://raw.githubusercontent.com/snebjorn/openapi-gen-bug/master/export-bug.json \
   -g typescript-angular \
   -o output-master/export-bug \
   -p=useSingleRequestParameter=true
```

##### Steps to reproduce

1. Clone https://github.com/snebjorn/openapi-gen-bug
2. Run `yarn install` 
3. Run `yarn gen`
4. Observe export error in https://github.com/snebjorn/openapi-gen-bug/blob/master/output-6.0.1/export-bug/api/api.ts

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/7519

##### Suggest a fix

Prefix with their tag as to avoid duplicate exports.

### PR DESCRIPTION
**Pull request by snebjorn**
Fixes #13200 see bug report for details about the issue

To validate the work run the OpenApi spec provided in the bug report. Remember to set `useSingleRequestParameter` as described in #13200.
Then check that there are no duplicate export errors in `/output-folder/api/api.ts`

The fix was to prefix the RequestParameter interface with the classname which it looks like the option `prefixParameterInterfaces` controls. However the generator `typescript-angular` doesn't have a `prefixParameterInterfaces` option. It appears to be bad copy/paste.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

### CODE REVIEW

**Comment by snebjorn** [comment]
I ran these with Git BASH (I'm on windows)
```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```
But it turned all `/` into `\` and other issues. Seems there's an issue with `export_docs_generators.sh` on windows.

**Comment by snebjorn** [comment]
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

Sorry to pester, but can I do something to help this getting reviewed(merged?

**Comment by macjohnny** [comment]
@snebjorn thanks for your contribution

can you also add a config in https://github.com/OpenAPITools/openapi-generator/tree/master/bin/configs with the `useSingleRequestParameter` and some test run similar to https://github.com/OpenAPITools/openapi-generator/blob/2a8ea162d72fee839580bb75a08874fa26f92d5d/pom.xml#L1214? this would prevent future issues.

moreover, can you think of a backwards-compatible way of fixing this issue?

**Comment by snebjorn** [comment]
Think I got a test added. Not sure of what to call the files or folders.

I'll have to get back to you on the non-backwards-compatible solution.

**Comment by snebjorn** [comment]
@macjohnny while investigating a backwards compatible solution I found this piece of code that is supposed to ensure unique operationIds

https://github.com/OpenAPITools/openapi-generator/blob/6665d069830c2e71c12b447cfb26a7eeb70c9ce6/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L5338-L5346

however it only ensures unique operation ids within the same tag.
According to the [OpenAPI Spec 2.0+](https://swagger.io/specification/v2/) the operationId must be unique among all operations described in the API.

> # operationId
>
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

The duplicate export problem is caused by `operationId` not being unique in the generated `CodegenOperation` objects. 
https://github.com/OpenAPITools/openapi-generator/blob/6665d069830c2e71c12b447cfb26a7eeb70c9ce6/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L32
However `operationId` is not duplicated in the source yaml specification.

I'm a bit out of my depth here. 
Is the correct fix to ensure all `CodegenOperation` objects have a unique `operationId`? If so where would be the appropriate place to do so? `addOperationToGroup` doesn't seem like it's the right place as it seems to be grouping operations.

**Comment by macjohnny** [comment]
@snebjorn thanks for your analysis

@wing328 what is the general approach to ensure unique operation ids even if multiple tags are used?

**Comment by SarochaL** [comment]
May I asked when will this bug be fixed ?

**Comment by snebjorn** [comment]
We're waiting for feedback from @wing328. If there's a bug with `operationId` I guess a change can be labeled a bug fix and be released in the current v6.1.
Otherwise it'll have to go into v7 as the current fix is a breaking change.

Furthermore... @macjohnny what's going on with the failing CircleCI Pipeline?
> Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.

I don't think I broke that.

**Comment by macjohnny** [comment]
@wing328 ping

@snebjorn can you merge the most recent master? Maybe it will work again

**Comment by snebjorn** [comment]
> can you merge the most recent master? Maybe it will work again

@macjohnny do I need a CircleCI account? I seem to get this error on all my PRs.

**Comment by macjohnny** [comment]
> do I need a CircleCI account? I seem to get this error on all my PRs.

I don't know. @wing328 do you know?

**Comment by snebjorn** [comment]
Found another PR with the same issue https://github.com/OpenAPITools/openapi-generator/pull/13381

**Comment by snebjorn** [comment]
@macjohnny @wing328 found the solution to 
image

I had to sign in to Circle CI using my GitHub account. This isn't explained anywhere.
It's unfortunate that an account on Circle CI have to be created for PR checks to run. Can't GitHub workflows run everything? It certainly would lowers barrier to entry.

**Comment by TiFu** [comment]
@snebjorn Works for me without signing in 
image

Anyhow, looks to me like the issue is the following line in `pom.xml`:

`                <module>samples/client/others/typescript-angular/typescript-angular-v14-use-single-request-parameter</module>`

as the error on CirceCi suggests that this module does not exist (see below). I would suggest to double check that the relevant XML is also added in this PR. 

```
ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.openapitools:openapi-generator-project:6.1.1-SNAPSHOT (/home/circleci/OpenAPITools/openapi-generator/pom.xml) has 1 error
[ERROR]     Child module /home/circleci/OpenAPITools/openapi-generator/samples/client/others/typescript-angular/typescript-angular-v14-use-single-request-parameter/pom.xml of /home/circleci/OpenAPITools/openapi-generator/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
```

**Comment by snebjorn** [comment]
@TiFu thanks for taking a look. However the failing test isn't the issue. I just haven't fixed it as I'm waiting for feedback on https://github.com/OpenAPITools/openapi-generator/pull/13262#issuecomment-1239494946
Once I have the needed info I can proceed to fix the code and tests accordingly 😄

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/issues/13200#issuecomment-1684844228

**Pull request closed without merging**
