### PR TITLE
Added server variable support

### PR DESCRIPTION
**Pull request by TiFu**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

See #793 

I implemented a solution similar to `authMethods` in supportingFiles JSON (see generated json below).

Spec: https://gist.github.com/TiFu/0934b362f25c66bc2b758f33e15520fc
Generated Supporting Files JSON: https://gist.github.com/TiFu/919a8888837e4e24fd32a05dc8d289f9

Generated under the root object (use `-DdebugSupportingFiles` to print the full mustache template used):

```
 "servers" : [ {
    "url" : "http://petstore.swagger.io:{port}/{basePath}",
    "description" : "The production API server",
    "variables" : [ {
      "name" : "port",
      "defaultValue" : "8443",
      "enumValues" : [ "8443", "443" ]
    }, {
      "name" : "basePath",
      "defaultValue" : "v2"
    } ]
  }, {
    "url" : "http://petstore.swagger.io",
    "description" : "The production API server",
    "variables" : [ ]
  } ],
```
# Question

Do I have to regenerate any samples? This is a non-breaking change because I only added a new property to the JSON (which is passed to mustache) for supportingFiles.

CC @wing328  @jmini

### CODE REVIEW

**Comment by wing328** [comment]
@TiFu agreed with you that it's a non-breaking change and there's no need to regenerate the samples as the test spec does not have anything related to server variables at the moment.

I'll review later today and let you know if I've any question.

**Comment by jmini** [comment]
> Can you share some insight about how this is used?
> Do you plan to update some generator/template to make usage of this new value?

See https://github.com/OpenAPITools/openapi-generator/issues/793#issuecomment-412903449

**Comment by TiFu** [comment]
I'm working on merging the TS generators into one generator at the moment. 

My plan is to generate configurable server objects:

```
class BaseServer<T> {
           public constructor(private url: string, private variables: T) {
        
            }
            public set(variable: keyof T, value: string) {
                 this.variables[variable] = value;
            }
}

let devServer = new Server(""http://petstore.swagger.io:{port}/{basePath}"", { "port": string, "basepath": string });
```
The server objects are  passed to the different operations (either via a default config object or as an argument in the method call for the operation):

```
let petApi = new PetAPI();
petApi.addPet("myPet", devServer);
```

**Comment by wing328** [comment]
@TiFu for the suggested use case (TS), what about passing `devServer` during object instantiation of `PetAPI` instead?

```
let devPetApi = new PetAPI(devServer);
devPetApi.addPet("myPet");

let petApi = new PetAPI(); // default to prod server
petApi.addPet("myPet");
```

**Comment by TiFu** [comment]
@wing328 that's probably a better idea - the implementation I currently had in mind for the ts generators actually uses a configuration object for the APIs which contains more parameters than just the server (e.g. authMethods configured with the necessary credentials e.g. api key)

**Comment by wing328** [comment]
> uses a configuration object for the APIs which contains more parameters than just the server (e.g. authMethods configured with the necessary credentials e.g. api key)

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore-security-test/typescript-fetch/configuration.ts seems to be a good starting point.

**Comment by wing328** [comment]
If no further question/feedback on this PR, I'll merge it over the weekend.

**Comment by wing328** [comment]
@TiFu thanks for the enhancement, which is included in the v3.2.2 stable release: https://twitter.com/oas_generator/status/1032252335131512832

**Pull request merged**
