### PR TITLE
[python] change Private attr to Class vars

### PR DESCRIPTION
**Pull request by fa0311**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by multani** [comment]
@fa0311 in https://github.com/OpenAPITools/openapi-generator/pull/16655/, you completely removed `__properties`, would it make sense to do the same instead?

I'm asking because using `.defaults` is a bit of a hack and it doesn't play well with type checking and I was looking for a way to remove it.

I wanted to replace it by [`cls.model_json_schema()["properties"].keys()`](https://docs.pydantic.dev/2.3/api/base_model/#pydantic.main.BaseModel.model_json_schema), which would return the same, but if we can actually remove all of this, it would even be better.

**Comment by wing328** [comment]
@fa0311 thanks for the PR. I've filed https://github.com/OpenAPITools/openapi-generator/pull/16690 to add tests covering disallowAdditionalPropertiesIfNotPresent set to true and could repeat the issue.

**Comment by fa0311** [comment]
@multani I have come up with a good idea to fix this.
Replace `cls.__properties.default` with `cls.model_fields.keys()` and remove `__properties`.

(However, `__discriminator_property_name.default` and `__discriminator_value_class_map.default` remain unresolved.)

**Comment by multani** [comment]
> Replace `cls.__properties.default` with `cls.model_fields.keys()` and remove `__properties`.

This won't work out of the box: `cls.model_field` contains the names of the fields as they appear in the class definition, but not their "aliased" names.

This will break several tests, you can check.

On the other hand, `cls.model_json_schema()["properties"].keys()` contains actually the aliased names.

**Comment by multani** [comment]
@fa0311 Maybe this could actually help: https://docs.pydantic.dev/latest/concepts/models/#automatically-excluded-attributes

**Comment by fa0311** [comment]
@multani 
> @fa0311 Maybe this could actually help: https://docs.pydantic.dev/latest/concepts/models/#automatically-excluded-attributes

I was just looking at that myself.
It looks very good

**Comment by fa0311** [comment]
A type hint is added to `__properties` and `List` becomes a reserved word.

**Review by multani — APPROVED** [review]
Yes, this is the good fix :bow:

**Comment by wing328** [comment]
FYI. Samples updated via https://github.com/OpenAPITools/openapi-generator/pull/16687/commits/738af45beb1a437438a71cdea09440615a065377

**Comment by wing328** [comment]
Tests added via https://github.com/OpenAPITools/openapi-generator/pull/16690

**Pull request merged**
