### PR TITLE
Fix oneOf discriminator mapping leak when used directly inside allOf

### PR DESCRIPTION
**Pull request by impl**
There are two ways that discriminators can be used: with `oneOf` or `anyOf`, explicitly, alongside the definition of their respective schemas; or with `allOf`, in which case a discriminator defined in a parent schema may be implicitly inherited by any other schema that includes it.

The code generator correctly handles both of those cases, except when an explicit ("closed") `oneOf` is used directly inside an unrelated `allOf` composite schema. In this situation, the `allOf` leaks into the discriminator mappings for the `oneOf` schema.

This change checks whether a schema for which a discriminator is being created is a `oneOf`/`anyOf` and skips the "open" `allOf` check that follows if so.

Without this change, in the included test cases, the discriminator mapping would also include `Pet`.

This is particularly important for generators that support `useOneOfDiscriminatorLookup`, as they will try to assign to fields of the `oneOf` schema type that don't exist.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@impl thanks for the PR.

cc @OpenAPITools/generator-core-team

**Comment by impl** [comment]
Hi @wing328! I just rebased this against latest `master` to resolve the outstanding merge conflicts. Sorry for the delay on updating it!

**Comment by wing328** [comment]
Thanks for the PR.

Next week when you've time, can you please PM me via Slack? 

My timezone is +0800 (Hong Kong)

**Comment by impl** [comment]
Hi all,

Just wanted to follow up on this PR. I've tried to reach out a few times and haven't gotten a response. Is this something you're interested in fixing? If not, we'll close this and maintain a fork with the patch applied.

Thanks!

**Pull request closed without merging**
