### PR TITLE
[kotlin][client] define kotlin coroutines context

### PR DESCRIPTION
**Pull request by 4brunu**
Initially when kotlin coroutines support was introduced in https://github.com/OpenAPITools/openapi-generator/pull/6362, there was no coroutines context defined, this PR fixes that.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

### CODE REVIEW

**Comment by richardklint** [comment]
@4brunu Any reason why you choose `= withContext(Dispatchers.IO) {` over `= coroutineScope {`?

Just ran into an issue where my existing Context is not getting passed down which causes various issues for me.

**Comment by 4brunu** [comment]
@richardklint Yes, I choose withContext(Dispatchers.IO) to make sure that the work done inside this method is not performed in the main thread.
Imagine you call this method from a coroutines that is using the context of the main thread, we should use a diferent context IO in this case, to avoid performing IO work in the main thread.
In Android this even throws an error.

Can you elaborate a bit more on the problem you are having and create a sample project to show the issue?

**Comment by richardklint** [comment]
@4brunu Perhaps this is just my inexperience with coroutines but my app is using coroutines internally to call multiple apis at the same time in a non blocking way and I've added https://github.com/Kotlin/kotlinx.coroutines/tree/master/integration/kotlinx-coroutines-slf4j in order to preserve context across the children for logging purposes. However when entering one of these functions, it loses all context due to it not inherenting the previous context like `coroutineScope` would.

**Comment by 4brunu** [comment]
Hi @richardklint, your use case seams like an advanced one and honestly I don't know the answer to it.
If you find any solution and want to submit a PR with it, I'm glad to help review it.

**Pull request merged**
