### PR TITLE
[maven] Introduce addTestCompileSourceRoot

### LINKED ISSUE #6119: [REQ] [Maven] Introduce addTestCompileSourceRoot
### Is your feature request related to a problem? Please describe.

I have to use `build-helper-maven-plugin` or fiddle around with `maven-compiler-plugin` when I am generating only for test execution (phase `generate-test-sources`) because there is only `addCompileSourceRoot` but no `addTestCompileSourceRoot` parameter.

## Describe the solution you'd like

Introduce `addTestCompileSourceRoot` in analogy to `addTestCompileSourceRoot`.

## Describe alternatives you've considered

`build-helper-maven-plugin`

## Additional context

n/a

### PR DESCRIPTION
**Pull request by famod**
Resolves #6119

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

### CODE REVIEW

**Comment by famod** [comment]
@jimschubert & @wing328 Any chance to get this into 4.3.1? Seems pretty "un-risky" to me.

**Comment by jimschubert** [comment]
Sorry about the close/reopen (accidentally clicked the button).

I'm wondering if you could add this new property to the README.md at `modules/openapi-generator-maven-plugin/README.md`? Is this parameter common enough knowledge in the Maven community, or would it require an example? I ask because I've never seen the mutual exclusion of these two properties before.

**Comment by famod** [comment]
> Sorry about the close/reopen (accidentally clicked the button).

No worries, I stopped counting the times it happened to me.
 
> I'm wondering if you could add this new property to the README.md at `modules/openapi-generator-maven-plugin/README.md`?

Sure! Somehow I was under the impression that the documentation is generated (mvn site).

> Is this parameter common enough knowledge in the Maven community, or would it require an example? I ask because I've never seen the mutual exclusion of these two properties before.

Personally I'd say proper documentation of the parameter in `README.md` should suffice.
The mutual exclusion is indeed a bit special. The alternatives to that would be much more complicated/effortful:
- detect the phase the execution is bound to and dependening on that set regular source root or test source root
- introduce a new mojo for usage in a test phase and "statically"  use test source root

The latter could be done with a base mojo that contains like 95% of the code.

**Comment by jimschubert** [comment]
@famod thanks for the explanation of the mutual exclusion. Maybe the plugins I'd studied before were optimistic about being used correctly. I personally prefer the error and clear error message.

The plugin docs, unfortunately, aren't part of our generated docsite. We just link directly to the README in GitHub as the official documentation.

If you don't get a chance to add the parameter, I can do it in a separate commit.

**Comment by famod** [comment]
README updated!

**Comment by famod** [comment]
Sorry, had to remove a superfluous space char.

**Pull request merged**
