### PR TITLE
fix #17258 - use model class only if it is generated

### LINKED ISSUE #17258: [BUG] [Java] 7.1.0 generates broken APIs for models consisting only of additionalProperties
##### Description

Updating the `openapi-generator-maven-plugin` to `7.1.0` breaks all APIs which use models consisting only of additionalProperties. It looks like model generation is skipped for those models, however the API still uses them, and they're also beneficial for the code in general since they serve as an anti-corruption layer.

##### openapi-generator version

7.1.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: bug
  version: 1.0.0

paths:
  /test:
    post:
      responses:
        default:
          description: dummy response
          content:
            application/json:
              schema:
                type: object
      requestBody:
        description: additional properties only
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestRequestBody'
      operationId: getQuestionnaire

components:
  schemas:
    TestRequestBody:
      type: object
      description: A schema consisting only of additional properties
      additionalProperties: true
```

##### Generation Details

```xml
            <!-- OpenAPI code generators -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.1.0</version>
                <executions>
                    <execution>
                        <id>test</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/openapi/openapi-bug.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <configOptions>
                                <library>spring-boot</library>
                                <interfaceOnly>true</interfaceOnly>
                                <serializableModel>true</serializableModel>
                                <useSpringBoot3>true</useSpringBoot3>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
##### Steps to reproduce

Generate the provided api-specification using the provided configuration.

The generator logs:

`[INFO] Model TestRequestBody not generated since it's a free-form object`

while the generated DefaultApi.java class uses:

```java
default ResponseEntity<Object> getQuestionnaire(
        @Parameter(name = "TestRequestBody", description = "additional properties only") @Valid @RequestBody(required = false) TestRequestBody testRequestBody
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }
```

which doesn't compile, since the `TestRequestBody` class wasn't generated.

##### Related issues/PRs

-

##### Suggest a fix

Don't skip generation of free-form objects. There's a reason why the api-specification uses a separate schema with title to define the model, instead of using an inline object.

### PR DESCRIPTION
**Pull request by martin-mfg**
fix #17258 by using the request body model class only if it is being generated.
I also added a new endpoint to the relevant input specifications for testing.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [   ] ~~If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.~~

### CODE REVIEW

**Comment by martin-mfg** [comment]
test failures are unrelated and will be fixed by #17479

**Comment by wing328** [comment]
thanks for the PR. just merged https://github.com/OpenAPITools/openapi-generator/pull/17479

can you please merge the latest master into branch and let the CIs test the change again?

cc @OpenAPITools/generator-core-team

**Comment by martin-mfg** [comment]
done :)

**Comment by wing328** [comment]
thanks for the PR.

also tested locally to confirm the fix.

**Comment by jorgerod** [comment]
I have created this issue for fix the bug
- https://github.com/OpenAPITools/openapi-generator/issues/17580

**Pull request merged**
