### PR TITLE
[php-ze-ph][php-mezzio-ph] Migration from Zend to Laminas and corresponding generator rename

### PR DESCRIPTION
**Pull request by Articus**
As [we discussed in June](https://github.com/OpenAPITools/openapi-generator/issues/6522#issuecomment-643822732) code generated with `php-ze-ph` requires a huge dependency update because [all Zend packages were moved to new organization - Laminas](https://getlaminas.org/blog/2020-03-09-transferring-zf-to-laminas.html). This PR solves this issue:
* `php-ze-ph` templates were updated to use "fresh" packages (composer.json and namespaces in PHP code)
* `php-ze-ph` generator renamed to `php-mezzio-ph` (Mezzio is a new name for Zend Expressive)
* common code moved to [separate library](https://github.com/Articus/OpenAPIGeneratorCommon-PHP) and covered with tests :)

CC @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Pushed 5eface69 to update samples. Let's see if that fixes the CI failure.

**Comment by Articus** [comment]
Thanks!

I used `modules/openapi-generator/src/test/resources/2_0/petstore.yaml` to regenerate content for https://github.com/Articus/openapi-generator/tree/php-ze-ph-migration/samples/server/petstore/php-mezzio-ph and
`modules/openapi-generator/src/test/resources/3_0/petstore.yaml` to regenerate content for https://github.com/Articus/openapi-generator/tree/php-ze-ph-migration/samples/openapi3/server/petstore/php-mezzio-ph 
Guess I used wrongs specification files :[

Circle CI build still failed though :(

**Comment by wing328** [comment]
> I used modules/openapi-generator/src/test/resources/2_0/petstore.yaml to regenerate content for https://github.com/Articus/openapi-generator/tree/php-ze-ph-migration/samples/server/petstore/php-mezzio-ph and
modules/openapi-generator/src/test/resources/3_0/petstore.yaml to regenerate content for https://github.com/Articus/openapi-generator/tree/php-ze-ph-migration/samples/openapi3/server/petstore/php-mezzio-ph
Guess I used wrongs specification files :[

For new generators, we only need OpenaAPI 3.0 test/sample files so please remove the samples for OAS 2.0 spec.

**Comment by wing328** [comment]
CircleCI tests passed via https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/7676/workflows/69f023c4-7815-441a-b663-7c73c6d4e14e/jobs/21205

**Comment by wing328** [comment]
Tested locally and the installation works fine.

**Pull request merged**
