### PR TITLE
Various fixes for JS (ES6) generator

### PR DESCRIPTION
**Pull request by delenius**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

1. Don't use property initializers

The ES6 Javascript generator used property initializers, as
described [here](https://tc39.github.io/proposal-class-public-fields/).

This is not standard ES6. In particular, create-react-app chokes on it
(see [this issue](https://github.com/swagger-api/swagger-codegen/issues/8024),
which is fixed by this commit).

This commit instead reverts back to using prototypes, as in the non-es6
JS generator.

2. Add missing pom.xml files

This allows us to run `mvn integration-test` in these folders.

3. Add missing double-quotes around enum field names.

This avoids errors due to fields that contain illegal characters.

4. Fix support for multiple inheritance

The previous implementation was broken. I added static "initialize"
methods, which supports multiple inheritance.

5. Comment out some broken tests.

There were tests for OuterBoolean etc, which are not generated
as part of index.js in the generated petstore clients. Hence, these
tests threw an error. The actual tests were already commented out
anyway. I just commented out one more line to avoid an error.

6. Remove some empty lines in generates JS files.

7. Fixed doubly generated superclass initializer calls.

8. Fixed missing single quotes in returnType in the generated "Api" classes.

The es6 and promise-es6 integration tests now pass (they didn't before).

Furthermore, the generated clients now work with create-react-app (see [this open swagger-codegen issue](https://github.com/swagger-api/swagger-codegen/issues/8024)).

Copying JS technical committee: @CodeNinjai  @frol  @cliffano

### CODE REVIEW

**Comment by wing328** [comment]
@delenius thanks for the fixes and enhancements. What about including the the JS Petstore ES6 clients in the Travis test by adding the folders to https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L861 so that the CI will run the tests for us moving forward?

**Comment by delenius** [comment]
@wing328 , sure! A couple of questions:

- Should I add them both under `profiles`, and also under `modules`?
- Should the `env` variable under the profile be `javascript` for all variants? I don't know what this does.

**Comment by wing328** [comment]
> Should I add them both under profiles, and also under modules?

Yes

> Should the env variable under the profile be javascript for all variants? I don't know what this does.

I don't think it's used but plesae still set it to javascript for consistency.

**Comment by wing328** [comment]
> BTW, item (7) in this PR may need more discussion. Previously, the model classes generated calls to superclass constructors, e.g. in Cat.js you would get

I would suggest going with your approach to move forward with this PR.

**Comment by delenius** [comment]
Ok, did that, rebased against latest master, and rebuilt the samples.

**Comment by wing328** [comment]
If no one has further feedback/question on this PR, I'll merge it into master over the weekend.

**Pull request merged**
