### PR TITLE
Add operation level servers support for java okhttp-gson client

### LINKED ISSUE #10847: [BUG][java] Path level servers overrides are ignored
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178)

##### Description

Path level servers overrides are ignored. Using the provided sample both https://api.pet.com/v2 and https://api.user.com/v2 are not included within the generated SDK. This is an issue with all specs tested.

##### OpenAPI declaration file content or url

[openapi-test.yaml.zip](https://github.com/OpenAPITools/openapi-generator/files/7528439/openapi-test.yaml.zip)

```yaml
servers:
- url: https://api.root.com/v3
# ... 
paths:
  /pet:
    servers:
      - url: https://api.pet.com/v2
   # ...
   /user:
    servers:
      - url: https://api.user.com/v2
```

##### Generation Details

`openapi-generator-cli generate -g java -i openapi-test.yaml -o sdk-test`

##### Steps to reproduce

1. Generate the SDK using the provided spec.
2. Verify that the generated SDK ignores servers defined within paths.

##### Related issues/PRs

Copy of issue #10639 for the `csharp-netcore` generator 

##### Suggest a fix

Servers defined within paths should be used for those paths which have been defined.

### PR DESCRIPTION
**Pull request by ajrice6713**
Add operation level server support for Java okhttp-gson http client 

Closes #10847 

At the API level - user can specify a custom base URL. If no custom base url is specified, the API selects the 1st path level server (if any), unless a different host index is specified. If no operation level servers are defined, the http request is built using the spec default server url. 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch

### CODE REVIEW

**Comment by wing328** [comment]
LGTM. We'll add a test or 2 later when we update the samples to use OAS 3.0 spec.

**Comment by Philipp-Borchert-ISH** [comment]
Hi @wing328 / @ajrice6713 - this caused breaking changes in generated code (ApiClient::buildCall/buildRequest etc) - furthermore the necessary code migration is a bit odd because the new parameter for these methods is not documented in the generated javadoc.
Just two remarks:

1. Shouldn't this have been part of 5.4.x instead of patch 5.3.1? That's how I interpret https://openapi-generator.tech/docs/release-summary/ at least
2. Maybe javadoc for the baseUrl should be added, it seems to be optional/nullable

**Comment by ajrice6713** [comment]
Hey @Philipp-Borchert-ISH 

Can you provide the error snippet of whats broken in the buildCall function? It wasnt intended to be breaking (and worked in my testing) 😢

**Comment by Philipp-Borchert-ISH** [comment]
Hi @ajrice6713, I'm referring to a "breaking" API change, not a bug in your code :-) 
Specifically the "baseUrl" parameter has been added on multiple public methods, which breaks compatibility with code accessing these methods. I reckon that shouldn't be allowed in patch releases, hence the question to William.

**Comment by wing328** [comment]
@Philipp-Borchert-ISH very good question. From what I understand, a developer shouldn't be calling these `buildSomething` methods directly and therefore when they use a newer version of the Java SDK generated with this particular enhancement (PR), they shouldn't need to update their code and it should work as usual.

Do you mind elaborating a bit more on your use cases that require calling these `buildSomething` method directly?

**Comment by Philipp-Borchert-ISH** [comment]
Hi @wing328, we're using them primarily in artificial test cases to generate "bad" requests to validate server side error handling in our APIs - so it's probably an edge case. 

> a developer shouldn't be calling these buildSomething methods directly 

I guess this is a bit of a tricky situation - the generated clients the developers "should" be using are exposing getters/setters and a constructor including the ApiClient class, so right now it is not obvious to developers (both providing + consuming SDKs) that they should not actually use it. Other classes / interfaces in the same package - e.g. ApiCallback or ApiException - are essential to the generated API clients as well. I think it would be beneficial for the future to have a clear distinction between "this is public -> it's an API" vs. "this should not be public -> shouldn't be visible" (visible as in access modifier).

Thx for the quick feedback btw!

**Pull request merged**
