### PR TITLE
Fix Swift4 and Swift3 template comment

### PR DESCRIPTION
**Pull request by marumemomo**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Swift4 and Swift3 client has error when examples `contentType=*/*` 

```swift
    /**
     - POST /fake/outer/string
     - Test serialization of outer string types
     - examples: [{contentType=*/*, example=null}]
     - parameter body: (body) Input string as post body (optional)
     - returns: RequestBuilder<String> 
     */
    open class func fakeOuterStringSerializeWithRequestBuilder(body: String? = nil) -> RequestBuilder<String> {
        let path = "/fake/outer/string"
        let URLString = PetstoreClientAPI.basePath + path
        let parameters = body?.encodeToJSON()

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = PetstoreClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
```

Add Comment `///`

```swift
    /**
///  - POST /fake/outer/string
///  - Test serialization of outer string types
///  - examples: [{contentType=*/*, example=null}]
///  - parameter body: (body) Input string as post body (optional)
///  - returns: RequestBuilder<String> 
     */
    open class func fakeOuterStringSerializeWithRequestBuilder(body: String? = nil) -> RequestBuilder<String> {
        let path = "/fake/outer/string"
        let URLString = PetstoreClientAPI.basePath + path
        let parameters = body?.encodeToJSON()

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<String>.Type = PetstoreClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
```

### CODE REVIEW

**Comment by wing328** [comment]
cc @jgavris @ehyche  @Edubits @jaz-ah @d-date for review.

**Comment by wing328** [comment]
@marumemomo you're right. I will see if I can find a way to escape it.

**Comment by wing328** [comment]
@marumemomo what about removing the example instead? Other client generators do not include the example in the code documentation either. I would suggest remove it or moving it to the auto-genrated markdown documentation instead (if there's one).

**Comment by marumemomo** [comment]
@wing328 LGTM 😄

**Comment by wing328** [comment]
@marumemomo if you submit another PR to remove example from the docstring, I'm happy to approve and merge.

**Comment by marumemomo** [comment]
@wing328 Thank you for suggesting. I submitted another PR #61 . I am happy that you will reviewer 😄

**Comment by wing328** [comment]
Closed via #61

**Pull request closed without merging**
