### PR TITLE
#2503: fix out-of-memory issue with nested objects with arrays with maxItems set

### LINKED ISSUE #2503: [BUG] [JavaScript] java.lang.OutOfMemoryError on simple OpenAPI file
##### Description

Using the following OpenAPI file below, the following error occurs:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:207)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsString(TextBuffer.java:404)
	at com.fasterxml.jackson.core.io.SegmentedStringWriter.getAndClear(SegmentedStringWriter.java:83)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:999)
	at io.swagger.v3.core.util.Json.pretty(Json.java:24)
	at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:1627)
	at org.openapitools.codegen.languages.JavascriptClientCodegen.fromModel(JavascriptClientCodegen.java:842)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2437)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1021)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:944)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:516)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:902)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:368)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:60)
```

##### openapi-generator version

This happens both in `openapi-generator-cli-4.0.0-20190325.151629-451.jar` and `openapi-generator-cli-3.3.4.jar`. 

##### OpenAPI declaration file content or url

```yaml
swagger: '2.0'
info:
  version: "1.0"
  title: DEV-2369

# ===============================================================================
# Paths
# ===============================================================================

paths:

  /users/responders:

    get:
      operationId: getUserResponderList
      summary: Gets a list of Responder objects
      responses:
        '200':
          description: A list of Responder objects
          schema:
            $ref: '#/definitions/ResponderList'
        '500':
          $ref: '#/responses/InternalServerError'
        default:
          $ref: '#/responses/TotallyUnexpectedResponse'

  /responders:

    post:
      operationId: createResponder
      parameters:
        - name: responder
          in: body
          required: true
          schema:
            $ref: '#/definitions/ResponderCreate'
      responses:
        '201':
          description: A Responder object
          schema:
            $ref: '#/definitions/Responder'
        '400':
          $ref: '#/responses/BadRequest'
        '500':
          $ref: '#/responses/InternalServerError'
        default:
          $ref: '#/responses/TotallyUnexpectedResponse'


# ===============================================================================
# Definitions
# ===============================================================================

definitions:

  ID:
    type: integer
    format: int64
    readOnly: true

  Reviewer:
    type: object
    properties:
      name:
        type: string
        maxLength: 100

  SuccessfulBugFix:
    type: object
    properties:
      reviewers:
        type: array
        minItems: 0
        maxItems: 100
        uniqueItems: true
        items:
          $ref: '#/definitions/Reviewer'

  ResponderProfileCreate:
    type: object
    properties:
      successfulBugFixes:
        type: array
        minItems: 0
        maxItems: 100
        uniqueItems: true
        items:
          $ref: '#/definitions/SuccessfulBugFix'

  ResponderProfile:
    type: object
    properties:
      successfulBugFixes:
        type: array
        minItems: 0
        maxItems: 100
        uniqueItems: true
        items:
          $ref: '#/definitions/SuccessfulBugFix'

  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string


  User:
    type: object
    properties:
      id:
        $ref: '#/definitions/ID'

  Responder:
    type: object
    properties:
      id:
        $ref: '#/definitions/ID'
      responderProfile:
        $ref: '#/definitions/ResponderProfile'

  # Used only for the creation of a new Responder
  ResponderCreate:
    type: object
    properties:
      responderProfile:
        $ref: '#/definitions/ResponderProfileCreate'

  ResponderList:
    type: object
    required:
      - items
    properties:
      items:
        type: array
        minItems: 0
        maxItems: 1000
        uniqueItems: true
        items:
          $ref: '#/definitions/Responder'



# ===============================================================================
# Responses
# ===============================================================================

responses:

  InternalServerError:
    description: An unexpected error occured.
    schema:
      $ref: '#/definitions/Error'
  BadRequest:
    description: Bad request; could not perform requested operation.
  EntityDoesNotExist:
    description: Entity does not exist.
  TotallyUnexpectedResponse:
    description: A totally unexpected response
```

##### Command line used for generation

`java -jar ./openapi-generator-cli-3.3.4.jar generate -i ../openapi.yaml -l javascript --additional-properties usePromises=true --additional-properties useES6=false -o ./javascript/`

also:
`java -jar ./openapi-generator-cli-4.0.0-20190325.151629-451.jar generate -i ../openapi.yaml -g javascript -o ./javascript/`

also:
`java -jar ./openapi-generator-cli-4.0.0-20190325.151629-451.jar generate -i ../openapi.yaml -g javascript --additional-properties usePromises=true --additional-properties useES6=false -o ./javascript/`

##### Steps to reproduce

1. Save the OpenAPI spec into a file called `openapi.yaml`.
2. Run either of the commands above.

##### Related issues/PRs

None that I am aware of.

##### Suggest a fix

Not sure.

### PR DESCRIPTION
**Pull request by macjohnny**
fix out-of-memory issue with nested objects with arrays with maxItems set by limiting to max. 5 example items

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
fixes #2503

### CODE REVIEW

**Comment by macjohnny** [comment]
cc @wing328 (2015/07) ❤️
@jimschubert (2016/05) ❤️
@cbornet (2016/05)
@ackintosh (2018/02) ❤️
@jmini (2018/04)

**Comment by macjohnny** [comment]
Note: I will updated the example once the core team agrees to this change.

**Comment by jimschubert** [comment]
I think this is a good approach. Is the OOME an indicator of a poorly-written or potentially problematic openapi document? That is, should we warn if we reset he nesting count to 5?

**Comment by macjohnny** [comment]
I think a warning is not necessary, since as a user I don‘t expect my example to be filled to the max with maxItems array items

**Comment by macjohnny** [comment]
Moreover, I don‘t think think this is a problem with the spec, since nesting is allowed and it could also happen with only one nesting level and maxItems=1000000

**Comment by jimschubert** [comment]
Good points. Yeah I think this approach works, then.

**Comment by macjohnny** [comment]
@jimschubert would you mind approving the PR then?

**Pull request merged**
