### PR TITLE
[cpp-qt-client] CMake build system improvements

### PR DESCRIPTION
**Pull request by srgbtl**
- Use {{packageName}} for client library name
- Support library installation using cmake
- Use Qt6 if available

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@ravinikam @stkrwork @etherealjoy @martindelille @muttleyxd

### CODE REVIEW

**Comment by wing328** [comment]
@srgbtl thanks for the PR.

May I know if you've tested the change in multiple platforms?

**Comment by srgbtl** [comment]
> @srgbtl thanks for the PR.
> 
> May I know if you've tested the change in multiple platforms?

I have tested the change on Mac and Linux only.

**Comment by wing328** [comment]
@srgbtl I tested your PR in my linux box with `mvn integration-test -f samples/client/petstore/cpp-qt/pom.xml` but got the following errors:

```
[INFO] --- exec-maven-plugin:1.2.1:exec (pet-test) @ CppQt5PetstoreClientTests ---
cmake: /usr/local/lib/libcurl.so.4: no version information available (required by cmake)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wing328/Code/openapi-generator/samples/client/petstore/cpp-qt/build
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[  4%] Automatic MOC for target CppQtPetstoreClient
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[  4%] Built target CppQtPetstoreClient_autogen
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 78%] Built target CppQtPetstoreClient
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[ 82%] Linking CXX executable cpp-qt5-petstore
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/ld: CMakeFiles/cpp-qt5-petstore.dir/PetStore/main.cpp.o: in function `PetApiTests::PetApiTests()':
main.cpp:(.text._ZN11PetApiTestsC2Ev[_ZN11PetApiTestsC5Ev]+0x24): undefined reference to `vtable for PetApiTests'
/usr/bin/ld: CMakeFiles/cpp-qt5-petstore.dir/PetStore/main.cpp.o: in function `StoreApiTests::StoreApiTests()':
main.cpp:(.text._ZN13StoreApiTestsC2Ev[_ZN13StoreApiTestsC5Ev]+0x24): undefined reference to `vtable for StoreApiTests'
/usr/bin/ld: CMakeFiles/cpp-qt5-petstore.dir/PetStore/main.cpp.o: in function `UserApiTests::UserApiTests()':
main.cpp:(.text._ZN12UserApiTestsC2Ev[_ZN12UserApiTestsC5Ev]+0x24): undefined reference to `vtable for UserApiTests'
/usr/bin/ld: CMakeFiles/cpp-qt5-petstore.dir/PetStore/main.cpp.o: in function `PetApiTests::~PetApiTests()':
main.cpp:(.text._ZN11PetApiTestsD2Ev[_ZN11PetApiTestsD5Ev]+0x13): undefined reference to `vtable for PetApiTests'
/usr/bin/ld: CMakeFiles/cpp-qt5-petstore.dir/PetStore/main.cpp.o: in function `StoreApiTests::~StoreApiTests()':
main.cpp:(.text._ZN13StoreApiTestsD2Ev[_ZN13StoreApiTestsD5Ev]+0x13): undefined reference to `vtable for StoreApiTests'
/usr/bin/ld: CMakeFiles/cpp-qt5-petstore.dir/PetStore/main.cpp.o: in function `UserApiTests::~UserApiTests()':
main.cpp:(.text._ZN12UserApiTestsD2Ev[_ZN12UserApiTestsD5Ev]+0x13): undefined reference to `vtable for UserApiTests'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cpp-qt5-petstore.dir/build.make:135: cpp-qt5-petstore] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/cpp-qt5-petstore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

```

Can you please take a look when you've time? Thanks again for the PR.

**Comment by MartinDelille** [comment]
We could maybe use a github action to check sample build on modification. Using conan for Qt or other C++ dependencies could really make it simple to configure.

**Comment by MartinDelille** [comment]
Done here: https://github.com/OpenAPITools/openapi-generator/pull/14566

**Comment by wing328** [comment]
tested locally and the result is good:
```
Config: Using QtTest library 5.12.8, Qt 5.12.8 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.3.0)
PASS   : UserApiTests::initTestCase()
QDEBUG : UserApiTests::createUserTest() got a request body
PASS   : UserApiTests::createUserTest()
QDEBUG : UserApiTests::createUsersWithArrayInputTest() got a request body
PASS   : UserApiTests::createUsersWithArrayInputTest()
QDEBUG : UserApiTests::createUsersWithListInputTest() got a request body
PASS   : UserApiTests::createUsersWithListInputTest()
QDEBUG : UserApiTests::deleteUserTest() Error happened while issuing request :  "Error transferring http://petstore.swagger.io/v2/user/rambo - server replied: Not Found, "
PASS   : UserApiTests::deleteUserTest()
QDEBUG : UserApiTests::getUserByNameTest() Error happened while issuing request :  "Error transferring http://petstore.swagger.io/v2/user/johndoe - server replied: Not Found, {\"code\":1,\"type\":\"error\",\"message\":\"User not found\"}"
PASS   : UserApiTests::getUserByNameTest()
QDEBUG : UserApiTests::loginUserTest() "{\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1675179520569\"}"
PASS   : UserApiTests::loginUserTest()
PASS   : UserApiTests::logoutUserTest()
QDEBUG : UserApiTests::updateUserTest() got a request body
PASS   : UserApiTests::updateUserTest()
PASS   : UserApiTests::cleanupTestCase()
Totals: 10 passed, 0 failed, 0 skipped, 0 blacklisted, 117ms
********* Finished testing of UserApiTests *********
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.135 s
[INFO] Finished at: 2023-01-31T07:38:40-08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by MartinDelille** [comment]
I can't see the qt sample action working here.

**Pull request merged**
