### PR TITLE
Thesaloncorp patch 1

### PR DESCRIPTION
**Pull request by thesaloncorp**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Where there is no response, this causes an error:
TypeError: Cannot read property 'status' of undefined

To reproduce, make a request to an API that doesn't exist.

### CODE REVIEW

**Comment by thesaloncorp** [comment]
@CodeNinjai (2017/07) @frol (2017/07) @cliffano (2017/07)

**Comment by wing328** [comment]
When you've time, please ping me via https://gitter.im (ID: wing328) to discuss the fix.

**Comment by wing328** [comment]
You will need to update the mustache template instead of the samples. Ping me if you need any help.

**Comment by wing328** [comment]
Closing this as there's no update.

**Pull request closed without merging**
