### PR TITLE
[Python] deserialize enum json response (fix #17789)

### LINKED ISSUE #17789: [BUG][PYTHON] Python client can't deserialize string enum response
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generated python clients can't deserialize a response that was defined as string with possible values specified as an enum.

It ends up calling a non-existing from_dict method on the enum class.

- Template for the enum: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model_enum.mustache
- from_dict called here: [https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cf[…]openapi-generator/src/main/resources/python/api_client.mustache](https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cfedaa14709a56a/modules/openapi-generator/src/main/resources/python/api_client.mustache#L754)
- coming from __deserialize here: [https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cf[…]openapi-generator/src/main/resources/python/api_client.mustache](https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cfedaa14709a56a/modules/openapi-generator/src/main/resources/python/api_client.mustache#L440)

So basically: if there is a response for an api endpoint defined as string enum, the client assumes it has to be a dict or similar after json decoding, because it is defined as a model class and then tries to call a non-existing from_dict method. From dict doesn't make any sense anyway, as the response value in JSON is a string. For other enums it could be other basic types.

##### openapi-generator version

7.1.0, 7.2.0 and 7.3.0-SNAPSHOT

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.3
info:
  title: test api
  version: 1.0.0-SNAPSHOT
paths:
  /status:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    Status:
      enum:
        - NEW
        - SCHEDULED
        - RUNNING
      type: string
```

##### Generation Details

I used openapi-generator-maven-plugin, only setting the generateSourceCodeOnly option, but should be the same with the cli.

##### Steps to reproduce

1. Create a rest endpoint returning an string enum value as json (probably the same with other enums)
2. Create a python client with the openapi generator for the specs of (1.) (or the provided example)
3. Call the endpoint using the client -> crashes with
```
[undefined]AttributeError: from_dict
.venv\Lib\site-packages\pydantic\_internal\_validate_call.py:113: in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
src\test_client\api\test_internal_api.py:4389: in restore_status_specific_storage
    return self.api_client.response_deserialize(
src\test_client\api_client.py:314: in response_deserialize
    return_data = self.deserialize(response_text, response_type)
src\test_client\api_client.py:390: in deserialize
    return self.__deserialize(data, response_type)
src\test_client\api_client.py:429: in __deserialize
    return self.__deserialize_model(data, klass)
src\test_client\api_client.py:731: in __deserialize_model
    return klass.from_dict(data)
```

##### Suggest a fix

Should Enums be handled in [api_client.mustache](https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cfedaa14709a56a/modules/openapi-generator/src/main/resources/python/api_client.mustache#L754)?

### PR DESCRIPTION
**Pull request by joeka**
Fixes #17789

Added deserialization of enums for json responses in the python api_client template.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
@tomplus @krjakbrjak @fa0311 @multani

### CODE REVIEW

**Review by multani — COMMENTED** [review]
Would you be able to add a test to make sure this is fixed and don't introduce regressions in the future?

**Comment by joeka** [comment]
I hope the test is ok like that. Without the change from this PR the test fails like this:
```
FAILED                        [ 58%]
tests\test_manual.py:121 (TestManual.testStringEnum)
self = <tests.test_manual.TestManual testMethod=testStringEnum>

    def testStringEnum(self):
        api_instance = openapi_client.BodyApi()
    
        # Test string enum response
>       api_response = api_instance.test_echo_body_string_enum(StringEnumRef.SUCCESS)

test_manual.py:126: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
..\..\..\..\..\.venv\lib\site-packages\pydantic\validate_call_decorator.py:58: in wrapper_function
    return validate_call_wrapper(*args, **kwargs)
..\..\..\..\..\.venv\lib\site-packages\pydantic\_internal\_validate_call.py:81: in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
..\openapi_client\api\body_api.py:2244: in test_echo_body_string_enum
    return self.api_client.response_deserialize(
..\openapi_client\api_client.py:315: in response_deserialize
    return_data = self.deserialize(response_text, response_type)
..\openapi_client\api_client.py:391: in deserialize
    return self.__deserialize(data, response_type)
..\openapi_client\api_client.py:434: in __deserialize
    return self.__deserialize_model(data, klass)
..\openapi_client\api_client.py:738: in __deserialize_model
    return klass.from_dict(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <enum 'StringEnumRef'>, name = 'from_dict'

    def __getattr__(cls, name):
        """
        Return the enum member matching `name`
    
        We use __getattr__ instead of descriptors or inserting into the enum
        class' __dict__ in order to support `name` and `value` being both
        properties for enum members (which live in the class' __dict__) and
        enum members themselves.
        """
        if _is_dunder(name):
            raise AttributeError(name)
        try:
            return cls._member_map_[name]
        except KeyError:
>           raise AttributeError(name) from None
E           AttributeError: from_dict

C:\Python39\lib\enum.py:429: AttributeError
```

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Review by multani — APPROVED** [review]
Looks good to me :+1: 

I also checked that the new code is called by the new test.

**Comment by joeka** [comment]
thanks :)

**Comment by multani** [comment]
@joeka can you regenerate all the sample files and fix the failing check?

**Comment by joeka** [comment]
done

**Review by multani — APPROVED** [review]

**Comment by wing328** [comment]
TS build errors not related to this change.

**Pull request merged**
