### PR TITLE
[csharp][netcore] Update type "String" to "string" for consistent type

### PR DESCRIPTION
**Pull request by prajon84**
This PR is for removing inconsistent use of type "String" and "string" by updating "String" to "string"

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@Blackclaws @lucamazzanti @wing328 @shibayan @jfeltesse-mdsol

### CODE REVIEW

**Comment by wing328** [comment]
@prajon84 thanks for the PR. What about following the advise in this SO: https://stackoverflow.com/a/7077/677735 ?

> As far as guidelines, it's generally recommended to use string any time you're referring to an object.

> Likewise, I think it's generally recommended to use String if you need to refer specifically to the class.

**Comment by lucamazzanti** [comment]
Good PR, I also wanted to start removing coding style warnings and hints.
Personally I would have done the same thing. William's proposal is a further improvement.

Visual Studio changes everything like in your PR.
- https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0049

Resharper has two different hints: 
- https://www.jetbrains.com/help/resharper/2021.1/BuiltInTypeReferenceStyle.html
- https://www.jetbrains.com/help/resharper/2021.1/BuiltInTypeReferenceStyleForMemberAccess.html

The default setup is the VS one, so it shows the hints also on the static cases like String.Format().

But if you setup on Resharper che second hint as CLR preference, then the fix applied on the entire project will exclude the static cases.You can setup that coding sintax rule locally, not so usefull, or on the project itself.

We can add an .editorconfig file in the project to commit this code sintax preferences.
This is also useful for the nexts emprovements.
We can do that directly on that PR or on another one in the future.

The .editorconfig content for that change will be this:
- https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0049#dotnet_style_predefined_type_for_member_access

```
[*]

# Microsoft .NET properties
dotnet_style_predefined_type_for_member_access = false:suggestion
```

**Comment by prajon84** [comment]
> @prajon84 thanks for the PR. What about following the advise in this SO: [stackoverflow.com/a/7077/677735](https://stackoverflow.com/a/7077/677735) ?

Seems like that was old guidance. 
> It appears that the guidance in this area may have changed, as StyleCop now enforces the use of the C# specific aliases.

**Comment by devhl-labs** [comment]
`string` is the way it is normally written. It's very odd to see `String`. I don't think we should set .editorconfig. We should just satisfy all the code hints in vanilla Visual Studio.

**Comment by wing328** [comment]
Can you please follow the instructions in the PR checklist item 3 to update the samples?

**Comment by prajon84** [comment]
@wing328: I have updated the samples for `bin/configs/csharp-netcore*` and pushed the commit. But, the `ci/circleci:build` and `continuous-integration/appveyor/pr` build are still failing. Any ideas?

**Comment by wing328** [comment]
Appveyor tests passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/39666876

**Pull request merged**
