### PR TITLE
[python] Remove post_params and body from OPTIONS request

### PR DESCRIPTION
**Pull request by slash-arun**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

Options should not have body or post_params

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before .
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by slash-arun** [comment]
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

cc: @wing328

**Comment by slash-arun** [comment]
I think this build is failing because docker pull swagger/petstore is resulting in 503

**Comment by spacether** [comment]
> I think this build is failing because docker pull swagger/petstore is resulting in 503

Yup, I am seeing that too on my PR. Locally running `docker pull swaggerapi/petstore` results in:
```
Using default tag: latest
Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by wing328** [comment]
There were docker outages.

Your PR looks good so I'll merge it. (and python petstore samples are tested by Travis)

**Pull request merged**
