### PR TITLE
[java][client] Fix regression in Java XML serialization. Fixes #4014

### LINKED ISSUE #4014: [BUG][JAVA][XML] Java generator with withXml option produces duplicate XML properties
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating a Java POJO using "withXml" option the `@XmlElement` ends up above `public static final String SERIALIZED_NAME_%` constant, which in turn marks this constant as an XML property. On the other hand, `@XmlAccessorType` is set to `FIELD`, which in turn marks the field, thus producing duplicated definition of the property.

Example:

    /**
     * ValidTakeoverProfilesProfile
     */
    @javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-10-01T16:24:48.053+02:00[Europe/Prague]")
    @XmlRootElement(name = "ValidTakeoverProfilesProfile")
    @XmlAccessorType(XmlAccessType.FIELD)
    
    public class ValidTakeoverProfilesProfile {
      @XmlElement(name = "profileName") // this marks the constant below as a property
      public static final String SERIALIZED_NAME_PROFILE_NAME = "profileName";
      @SerializedName(SERIALIZED_NAME_PROFILE_NAME)
      private String profileName; // this becomes a property since XmlAccessorType is FIELD

The outcome is that produced model is not usable for Spring app, as there are multiple properties with a same name inside single class.

##### openapi-generator version

4.1.2

After some investigation, version 4.1.0 result produces usable model for my use case.

##### OpenAPI declaration file content or url

Complete Maven example is here, with JUnit test: https://github.com/RockyMM/openapi-modelgen-test

##### Command line used for generation

    mvn clean test

##### Steps to reproduce

Use the following options to generate the model from YAML

                            <generatorName>java</generatorName> 
                            <generateApis>false</generateApis>
                            <generateSupportingFiles>true</generateSupportingFiles>
                            <generateModelTests>false</generateModelTests>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <skipValidateSpec>true</skipValidateSpec>
                            <supportingFilesToGenerate>pom.xml</supportingFilesToGenerate>
                            <additionalProperties>
                                <additionalProperty>java8=true</additionalProperty>
                                <additionalProperty>dateLibrary=java8</additionalProperty>
                                <additionalProperty>jackson=false</additionalProperty>
                                <additionalProperty>withXml=true</additionalProperty>
                            </additionalProperties>

##### Related issues/PRs

Could not find any.

##### Suggest a fix

In my perspective, in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/pojo.mustache

both `gson` and `jackson` sections above a property **must** come above `withXml` sections. This could solve the issue.

Either this, or I am doing something very very wrong and missing some obvious thing.

### PR DESCRIPTION
**Pull request by bkabrda**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

CC @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

### Description of the PR

Fixes regression reported in #4014.

@RockyMM since the current test cases don't cover this, could you try to grab this patch and verify that it fixes the regresssion? Thanks!

### CODE REVIEW

**Comment by RockyMM** [comment]
I have two points:

1) this change needs to be propagated to all pojo.mustache in other Java-based generators :( (I was expecting some inheritance, but seems it needs to be copied manually to JAX-RS, Spring and the likes)

2) this segment

    {{#jackson}}
    public static final String JSON_PROPERTY_{{nameInSnakeCase}} = "{{baseName}}";
    {{/jackson}}

also needs to be moved up.

**Comment by bkabrda** [comment]
So I moved the jackson's `JSON_PROPERTY_*` declaration as well, which should solve the second point. I honestly have no idea why this is a problem in all the other pojo templates, as I didn't touch them in my original PR that seemed to have caused this. Perhaps the issues with these were caused by different PRs?

**Comment by bkabrda** [comment]
I think the commit 1ab7b9ceb686d0c600581a08aca6af03bbef81be might have broken the other POJOs. I can try to fix that, but I'd prefer not mixing it with this PR, as the offending commits are different and this PR is for java clients.

**Comment by RockyMM** [comment]
Hm, in commit 1ab7b9ceb686d0c600581a08aca6af03bbef81be I checked the sample of Animal.java in "withXml" resttemplate example and it looked fine. So it might be that this is all the fix that we need.

It's interesting that when you've moved the jacksons `JSON_PROPERTY_*` that the generated samples also changed. I'm just getting a hold in this project so everything is new to me 😄 

This means it is possible to write some automated tests for this so this won't appear again. Like check what is marshalled, and what is unmarsahlled and compare. I could help with this next week, but I think it is not really a show-stopper for the time being.

Update: I just saw #689 - I think it's very good idea. 👍

**Comment by wing328** [comment]
> This means it is possible to write some automated tests for this so this won't appear again. Like check what is marshalled, and what is unmarsahlled and compare. I could help with this next week, but I think it is not really a show-stopper for the time being.

Yes, we welcome additional unit tests to ensure this issue won't happen again.

**Comment by wing328** [comment]
@RockyMM thanks for reviewing the fix.

**Pull request merged**
