### PR TITLE
[PHP-SYMFONY] Support BackedEnum for enum ref (16846)

### PR DESCRIPTION
**Pull request by loicconan**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

**Comment by loicconan** [comment]
Hello
I saw that my PR does not pass phpunit tests.

This is cause of auto generated file [samples/server/petstore/php-symfony/SymfonyBundle-php/Tests/Model/EnumStringModelTest.php](https://github.com/loicconan/openapi-generator/blob/a7e36b4d49d3a4c3b51a03639ccad12146e774b2/samples/server/petstore/php-symfony/SymfonyBundle-php/Tests/Model/EnumStringModelTest.php#L61) line 61.

As we can see on the [phpunit documentation](is declared "final" and cannot be doubled) :

> Enumerations (enum) are final classes and therefore cannot be doubled. readonly classes cannot be extended by classes that are not readonly and therefore cannot be doubled.

So I need to edit this auto generated sample.
But when I change [the mustache file in source](https://github.com/loicconan/openapi-generator/blob/php_symfony_backed_enum/modules/openapi-generator/src/main/resources/php-symfony/testing/model_test.mustache) and re build the project, that doesn't change the sample.

I checked, this is working when I do it with openapi generator cli and custom template white -t option.

What I'm doing wrong please ? (Sorry I'm a beginner contributor of this project)

Thx

**Comment by loicconan** [comment]
Phpunit didn't pass. I fixed it.

**Comment by wing328** [comment]
@loicconan can you please take another look when you've time?

```
There was 1 error:

1) OpenAPI\Server\Model\EnumStringModelTest::testTestClassExists
Error: Typed property OpenAPI\Server\Model\EnumStringModelTest::$object must not be accessed before initialization
```

ref: https://github.com/OpenAPITools/openapi-generator/actions/runs/6575244536/job/18214218454?pr=16847

**Comment by loicconan** [comment]
> @loicconan can you please take another look when you've time?
> 
> ```
> There was 1 error:
> 
> 1) OpenAPI\Server\Model\EnumStringModelTest::testTestClassExists
> Error: Typed property OpenAPI\Server\Model\EnumStringModelTest::$object must not be accessed before initialization
> ```
> 
> ref: https://github.com/OpenAPITools/openapi-generator/actions/runs/6575244536/job/18214218454?pr=16847

Hello @wing328 I fixed it.

**Comment by wing328** [comment]
thanks for the fix, which has been merged.

**Pull request merged**
