### PR TITLE
Refactor and use some Java 7 features

### PR DESCRIPTION
**Pull request by bjgill**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. @frol @farcaller - this is not primarily targeting Rust, but does make some changes to the Rust-server generator.

### Description of the PR

I'm now revisiting openapi-generator with a bit more Java expertise than I had a few months ago. There are a few things in the Rust generator that seem worthy of refactoring.

Also, I've recently discovered `Objects.equals` and `Objects.hash` - see https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html. These helpers, introduced in Java 7, vastly reduce the amount of boilerplate required to implement the `equals` and `hashcode` methods. If this PR gets accepted, I'll have a go at giving the same treatment to a bunch of other classes with similar/worse quantities of boilerplate.

### CODE REVIEW

**Comment by bjgill** [comment]
The CI failure looks to be unrelated and pre-existing. I think https://github.com/OpenAPITools/openapi-generator/pull/2224 is the fix.

**Comment by bjgill** [comment]
Also, I've noticed that we are already using `Objects` elsewhere. So I'm going to go ahead and do the full refactor here...

**Comment by bjgill** [comment]
...and complete. As far as I can tell, the only remaining classes using the old style are now in the Android client, which I don't know enough about to want to touch. 

Note - I performed the refactoring manually, using Sublime's regex-based find/replace mechanism. This gives me reasonable confidence that I've not missed/duplicated/etc any of the parameters in the various functions.

There's a chance that switching from our hand-rolled implementation to using `Objects.hash` might give us a small performance boost.

This is now ready for review/merging.

**Comment by wing328** [comment]
The CI failures are not related to this change

**Pull request merged**
