### PR TITLE
[BUG][PYTHON][MUSTACHE] Generic-model validation for enum (single element) fixes

### PR DESCRIPTION
**Pull request by jkaliszuk**
Issue - https://github.com/OpenAPITools/openapi-generator/issues/17274

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
the CI tests failed: https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/26910/workflows/be55bfd3-54ee-4bb1-8afc-81bd51d923ea/jobs/84323

can you please take a look when you've time?

**Comment by wing328** [comment]
cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)

**Comment by jkaliszuk** [comment]
I will try to look this week. Maybe You have some suggestions what would did wrong?

**Comment by robertschweizer** [comment]
> I will try to look this week. Maybe You have some suggestions what would did wrong?

The error is a wrong indent in some of the model classes, .e.g `enum_arrays.py`:

```
    from petstore_api.models.enum_arrays import EnumArrays
E     File "/home/circleci/OpenAPITools/openapi-generator/samples/openapi3/client/petstore/python/petstore_api/models/enum_arrays.py", line 44
E       raise ValueError("must be one of enum values ('>=', '$')")
E           ^
E   IndentationError: expected an indented block
```

**Comment by wing328** [comment]
already fixed in the master using set so closing this one

**Pull request closed without merging**
