### PR TITLE
Add support for global token based auth for k6 script generation

### PR DESCRIPTION
**Pull request by aakash-dev-maersk**
### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

The changes in this PR address the following issue ticket:
https://github.com/OpenAPITools/openapi-generator/issues/19288

This is to add Global token based auth (basic and bearer) for k6 script generation

```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
security:
  - basicAuth: []
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      security:
        - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```

```javascript
import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://api.example.com/v1";
const TOKEN = "TOKEN_VALUE_HERE";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/users", () => {

        // Request No. 1: 
        {
            let url = BASE_URL + `/users`;
            let params = {
                headers: {
                    "Authorization": `Basic ${TOKEN}`, "Accept": "application/json"
                }
            };
            let request = http.get(url, params);

            check(request, {
                "A JSON array of user names": (r) => r.status === 200
            });
        }
    });

}
```

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

cc @mostafa

**Review by mostafa — APPROVED** [review]
LGTM! I just have a question:

what happens if an endpoint is not authenticated? That is, the security schema is ignored for an endpoint?

**Comment by aakash-dev-maersk** [comment]
> what happens if an endpoint is not authenticated? That is, the security schema is ignored for an endpoint?

```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
security:
  - basicAuth: []
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      security:
        - basicAuth: []
  /public-info:
    get:
      summary: Returns public information.
      description: This endpoint does not require authentication.
      responses:
        "200":
          description: Public information
          content:
            application/json:
              schema:
                type: object
                properties:
                  info:
                    type: string
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```
Hi, let me take this openAPI spec as a sample, when I run the generator on this, following output is received
      
```javascript
import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://api.example.com/v1";
const TOKEN = "TOKEN_VALUE_HERE";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/users", () => {

        // Request No. 1: 
        {
            let url = BASE_URL + `/users`;
            let params = {
                headers: {
                    "Authorization": `Basic ${TOKEN}`, "Accept": "application/json"
                }
            };
            let request = http.get(url, params);

            check(request, {
                "A JSON array of user names": (r) => r.status === 200
            });
        }
    });

    group("/public-info", () => {

        // Request No. 1: 
        {
            let url = BASE_URL + `/public-info`;
            let params = {
                headers: {
                    "Authorization": `Basic ${TOKEN}`, "Accept": "application/json"
                }
            };
            let request = http.get(url, params);

            check(request, {
                "Public information": (r) => r.status === 200
            });
        }
    });

}
```

Since the global security param was given as basic auth it's added to all the paths, let me know if this seems fine or the behaviour should be endpoint specific, thanks. @mostafa

**Comment by aakash-dev-maersk** [comment]
> I think public endpoint should exclude auth if auth is explicitly disabled for it (even if enabled globally).

Thanks for the feedback, I researched on this a bit and noted that when global auth is defined and nothing is mentioned at path level, global auth should be applicable. Whereas when global auth is defined but you specifically give the security param empty at path level in that case no auth should be added. I am posting the yaml below for the cases I am mentioning.

I have made the code changes and pushed the changes with yaml. please review and let me know @mostafa 

```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
security:
  - basicAuth: []
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      security:
        - basicAuth: []
  /public:
    get:
      summary: Returns public information.
      description: This endpoint does not require authentication.
      responses:
        "200":
          description: A JSON object with public information
          content:
            application/json:
              schema:
                type: object
      security: []
  /private:
    get:
      summary: Returns private information.
      description: This endpoint requires global security settings.
      responses:
        "200":
          description: A JSON object with private information
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```
For the yaml above this should be the generated test file

```javascript
import http from "k6/http";
import { group, check, sleep } from "k6";

const BASE_URL = "http://api.example.com/v1";
const TOKEN = "TOKEN_VALUE_HERE";
// Sleep duration between successive requests.
// You might want to edit the value of this variable or remove calls to the sleep function on the script.
const SLEEP_DURATION = 0.1;
// Global variables should be initialized.

export default function() {
    group("/users", () => {

        // Request No. 1: 
        {
            let url = BASE_URL + `/users`;
            let params = {
                headers: {
                    "Authorization": `Basic ${TOKEN}`, "Accept": "application/json"
                }
            };
            let request = http.get(url, params);

            check(request, {
                "A JSON array of user names": (r) => r.status === 200
            });
        }
    });

    group("/public", () => {

        // Request No. 1: 
        {
            let url = BASE_URL + `/public`;
            let request = http.get(url);

            check(request, {
                "A JSON object with public information": (r) => r.status === 200
            });
        }
    });

    group("/private", () => {

        // Request No. 1: 
        {
            let url = BASE_URL + `/private`;
            let params = {
                headers: {
                    "Authorization": `Basic ${TOKEN}`, "Accept": "application/json"
                }
            };
            let request = http.get(url, params);

            check(request, {
                "A JSON object with private information": (r) => r.status === 200
            });
        }
    });

}
```

**Review by mostafa — APPROVED** [review]
LGTM! Thanks for your contribution! :tada:

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/10455494492/job/29104028113?pr=19348

please update the sample and i will then merge it

**Comment by aakash-dev-maersk** [comment]
> https://github.com/OpenAPITools/openapi-generator/actions/runs/10455494492/job/29104028113?pr=19348
> 
> please update the sample and i will then merge it

I have updated the samples. @wing328

**Pull request merged**
