### PR TITLE
[kotlin][jvm-retrofit2] Update templates

### LINKED ISSUE #7591: [BUG][kotlin][jvm-retrofit2] unnecessary nullable type of OkHttpClient / small fix in docstring
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

1. unnecessary nullable type of OkHttpClient

In the function `createService()` of generated `infrastructure/ApiClient.kt` file, the variable `usedClient` has nullable type.
But here it should be NonNullable.

`Retrofit.Builder.client()` receives `OkHttpClient` instance, and checks it is NonNull.
スクリーンショット 2020-10-04 19 39 55

So in IDE such as AndroidStudio, an error occurs.
スクリーンショット 2020-10-04 16 46 36

The actual output
```kt
fun <S> createService(serviceClass: Class<S>): S {
    var usedClient: OkHttpClient? = null
    this.okHttpClient?.let { usedClient = it } ?: run {usedClient = clientBuilder.build()}
    return retrofitBuilder.client(usedClient).build().create(serviceClass)
}
```

The expected output
```kt
fun <S> createService(serviceClass: Class<S>): S {
    val usedClient: OkHttpClient = this.okHttpClient ?: clientBuilder.build()
    return retrofitBuilder.client(usedClient).build().create(serviceClass)
}
```

2. small fix in docstrings

In the generated API files, the indent of the docstrings is irregular.

The actual output
```kt
interface PetApi {
    /**
     * Add a new pet to the store
     * 
     * Responses:
     *  - 405: Invalid input
     * 
     * @param body Pet object that needs to be added to the store 
    * @return [Call]<[Unit]>
     */
    @POST("pet")
    fun addPet(@Body body: Pet): Call<Unit>

...
}
```

The expected output
```kt
interface PetApi {
    /**
     * Add a new pet to the store
     * 
     * Responses:
     *  - 405: Invalid input
     * 
     * @param body Pet object that needs to be added to the store 
     * @return [Call]<[Unit]>
     */
    @POST("pet")
    fun addPet(@Body body: Pet): Call<Unit>

...
}
```

##### openapi-generator version

master (61b543f03d)

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml

(it is described in [2 - Getting Started](https://github.com/OpenAPITools/openapi-generator#table-of-contents))

##### Generation Details

```sh
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
-i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml \
-g kotlin --library jvm-retrofit2 -o kotlin-retrofit2-client -t modules/openapi-generator/src/main/resources/kotlin-client
```

##### Steps to reproduce

Run the above command-line

##### Suggest a fix

I will submit a PR.

### PR DESCRIPTION
**Pull request by warahiko**
Close #7591 

- Update `usedClient` to be non-null
- Fix indent of return tag
- Trim trailing whitespace
  - I found some whitespace that may not be needed and removed them, but if we need them, I will revert the commit

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

This is my first contribution to OSS, and if I have any mistakes, please tell me:)

### CODE REVIEW

**Comment by warahiko** [comment]
I found this PR was partly duplicated (#7556), so please close if you don't need this PR.

**Comment by alexfacciorusso** [comment]
> I found this PR was partly duplicated (#7556), so please close if you don't need this PR.

I think your PR is still relevant regarding the comments and spaces fixes. I think they might be both merged by merging mine first for the Retrofit client change and then yours after updating it

**Comment by alexfacciorusso** [comment]
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) Sorry to ping you again is there any change to be made to get this merged? It might benefit a lot of users imho

**Comment by 4brunu** [comment]
Looks good to me 👍

**Comment by jimschubert** [comment]
Thanks!

**Comment by warahiko** [comment]
Thank you for reviewing and merging!

**Pull request merged**
