### PR TITLE
[Dart][Client] Fix default value of enum variables

### PR DESCRIPTION
**Pull request by lchwe**
Classes that have enums properties with a default required value are initialized with a String value, rather than using the enum values, so the dart client fails to compile unless this is manually fixed.

For example, I get the following generated:
`AppointmentStatusEnum status = "open";`

while I should be getting instead:
`AppointmentStatusEnum status = AppointmentStatusEnum._internal("open");`

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12)

### CODE REVIEW

**Comment by szotp** [comment]
Hi, this is slightly offtopic, but do you have any array of enums in your scheme? It seems to be completely broken currently, instead of `List<ExampleDefinitionExampleEnum>` it generates `ExampleDefinitionExampleEnumArrayEnum`.

**Comment by lchwe** [comment]
@szotp I don't think I have that issue

**Comment by wing328** [comment]
@lchwe can you try to merge the latest master of the official repo into this branch to see if that fixes the CI failures?

I wanted to do it for you but don't have the right to modify your branch.

**Comment by lchwe** [comment]
@wing328 nice, all green now!

**Comment by wing328** [comment]
@lchwe I did a test manually with a top-level enum definition in the spec and here is what I got (partial code):
```dart
part of openapi.api;

class ModelStatus {
  /// The underlying value of this enum member.
  final String value;

  const ModelStatus._internal(this.value);

  /// pet status in the store
  static const ModelStatus available_ = ModelStatus._internal(&quot;available&quot;);
  /// pet status in the store
  static const ModelStatus pending_ = ModelStatus._internal(&quot;pending&quot;);
  /// pet status in the store
  static const ModelStatus sold_ = ModelStatus._internal(&quot;sold&quot;);

  static List<ModelStatus> get values => const [
        available_,
        pending_,
        sold_,
      ];
```

Are those `&quot;` expected?

**Comment by lchwe** [comment]
@wing328 , weird. It should not be `&quot;`, it should just be normal quotes (ie. ""). Must be because the `defaultValue` has the triple curly braces. It's weird because, it was already like that before i made the change and i never got `&quot;` before. So I'm pretty sure using double curly braces on `defaultValue` would fix the issue

**Comment by lchwe** [comment]
@wing328 thanks for the help btw!

**Comment by wing328** [comment]
Agreed triple curly braces should not result in those HTML-escaped output. Likely a mistake in my end when testing the change.

**Pull request merged**
