### PR TITLE
Add auth token refresh to csharp

### PR DESCRIPTION
**Pull request by BryanAldrich**
This adds a simple change to the AuthToken and TokenResponse code to allow for automatic refreshes. (I didn't test the refresh_token since I don't have one of those super handy).

Split off from #20233.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by BryanAldrich** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

Thanks, since I had to fix all that, I hit my mistake.. shh. nobody will know. (i'll fix the other PR I made as well..)

**Comment by wing328** [comment]
can you please review the build failure when you've time?

https://github.com/OpenAPITools/openapi-generator/actions/runs/12152223145/job/33889068846?pr=20234

**Comment by BryanAldrich** [comment]
Sorry i've had all these build failures, this is my first time working with this project, first time working with java since 2004 (yes, 20 years). I've scripted up checks on my side to prevent this again.

**Comment by wing328** [comment]
@BryanAldrich no problem. thanks for the PR.

the appveyor tests passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/51126886

**Comment by wing328** [comment]
PR merged. Let's give it a try.

Have a nice weekend

**Pull request merged**
