### PR TITLE
Fix JavaSpring clientConfiguration's @ConditionalOnProperty import

### PR DESCRIPTION
**Pull request by vedantchokshi**
In #16011, the `@ConditionalOnProperty` import was moved to only the under the `hasOAuthMethods` section of the template. From looking at the mustache template for generating the client config, `@ConditionalOnProperty` import is required for all authentication methods and not just the OAuth. This PR moves the import to the `hasAuthMethods` section so the import is generated for all the types of authentication.

This bug has been raised in #16625.

@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg (2023/08) can you guys take a look at this small change? Please let me know if I have missed anything as this is my first change to the project. Thank you!

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by MelleD** [comment]
Looks good, but there should be new generated classes for e.g. basic auth or not?
If not we should add a test file for that fix

**Comment by vedantchokshi** [comment]
> Looks good, but there should be new generated classes for e.g. basic auth or not? If not we should add a test file for that fix

Hi @MelleD - Thanks for taking look so quickly! Not sure what you mean by `but there should be new generated classes for e.g. basic auth or not?`. I don't think there's different generated classes. I think different methods are just rendered based on the type of authentication. 

Happy to add some tests. I'll have a look on where to add them but if you have an specific ones in mind then please let me know.

**Comment by MelleD** [comment]
Off course we have examples directly from yamls
See
"You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example ./bin/generate-samples.sh bin/configs/java*."

So there should be a difference e.g. fpr basic auth there should be a missing import

**Comment by wing328** [comment]
I am able to repeat the issue and confirm the fix locally. Will add a test in another PR.

**Pull request merged**
