### PR TITLE
[kotlin] [bugfix] [maven-plugin]: prevent ClassCastException with boolean config options

### PR DESCRIPTION
**Pull request by janweinschenker**
This change will prevent a ClassCastException during execution of the generator maven plugin. 

When executed as maven plugin, boolean config options have the type java.lang.Boolean. When executed as CLI generator boolean config options have the type java.lang.String. Before this fix, only the latter case could be handled properly and the first case caused a ClassCastException.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. @wing328

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR. I tested locally but still got the same error:
```
[ERROR]
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
    at org.openapitools.codegen.languages.AbstractKotlinCodegen.processOpts (AbstractKotlinCodegen.java:437)
    at org.openapitools.codegen.languages.KotlinClientCodegen.processOpts (KotlinClientCodegen.java:144)
    at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties (DefaultGenerator.java:196)
    at org.openapitools.codegen.DefaultGenerator.generate (DefaultGenerator.java:913)
    at org.openapitools.codegen.plugin.CodeGenMojo.execute (CodeGenMojo.java:727)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
```

I may have done something wrong locally. Does the fix work for you locally in your machine?

**Comment by wing328** [comment]
Can you please also add a test in https://github.com/OpenAPITools/openapi-generator/blob/master/.travis.yml#L140 ?

**Comment by janweinschenker** [comment]
I build my fork of openapi-generator locally with `mvn clean install` and the used the maven plugin with version 4.2.1-SNAPSHOT. It worked correctly. 

But of course, you are right, there needs to be a reproduceable unit test. I will add one or more as needed.

**Comment by wing328** [comment]
For tests, I mean adding the following:
```
mvn clean compile -f modules/openapi-generator-maven-plugin/examples/kotlin.xml
```

to https://github.com/OpenAPITools/openapi-generator/blob/master/.travis.yml#L140

**Comment by janweinschenker** [comment]
Will this do?

**Comment by wing328** [comment]
@janweinschenker  thanks for the PR, which has been included in the v4.2.1 release: https://twitter.com/oas_generator/status/1195339336922759168

**Pull request merged**
