### PR TITLE
[Java][okhttp-gson] Refactor handling of 'number' types in oneOf

### LINKED ISSUE #16166: [BUG] BigDecimal not imported in 7.0.0
##### Description
Client generation from that API:

```
		"parameters": [
			{
				"name": "amount",
				"in": "path",
				"required": true,
				"schema": {
					"type": "number"
				}
			},
```
full 'get' definition: https://github.com/OlliL/moneyjinn-server/blob/master/moneyjinn-server/src/main/resources/openapi/moneyflow/paths/SearchMoneyflowsByAmount.json

Is generated as:
```
  public SearchMoneyflowsByAmountResponse searchMoneyflowsByAmount(BigDecimal amount, String dateFromStr, String dateTilStr) throws ApiException {
    return this.searchMoneyflowsByAmount(amount, dateFromStr, dateTilStr, Collections.emptyMap());
  }
```

**But**: BigDecimal is not imported! The file can't be compiled:

```
MoneyflowControllerApi.java:[288,68] cannot find symbol
  symbol:   class BigDecimal
  location: class org.laladev.moneyjinn.hbci.backend.api.MoneyflowControllerApi
MoneyflowControllerApi.java:[303,68] cannot find symbol
  symbol:   class BigDecimal
  location: class org.laladev.moneyjinn.hbci.backend.api.MoneyflowControllerApi
```

##### openapi-generator version

7.0.0-beta generates this error.
6.6.0 works fine!

##### generator configuration

```
<configuration>
	<inputSpec>${project.basedir}/../moneyjinn-server/src/main/resources/openapi.json</inputSpec>
	<generatorName>java</generatorName>
	<apiPackage>org.laladev.moneyjinn.hbci.backend.api</apiPackage>
	<modelPackage>org.laladev.moneyjinn.hbci.backend.model</modelPackage>
	<skipOperationExample>true</skipOperationExample>
	<configOptions>
		<library>apache-httpclient</library>
		<sourceFolder>src/gen/java/main</sourceFolder>
		<useJakartaEe>true</useJakartaEe>
		<openApiNullable>false</openApiNullable>
		<useTags>true</useTags>
	</configOptions>
</configuration>
````

### PR DESCRIPTION
**Pull request by karzang**
This PR improves the handling of `number` datatypes used in `oneOf` by removing a previous workaround which treated `BigDecimal` as a `languagePrimitiveType`.

This PR fixes #16166 since treating `BigDecimal` as a primitive results in, the generator not adding any imports for it. Instead this change provides separate handling of `number` datatypes in the `oneof_model.mustache` template.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by karzang** [comment]
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02)

@wing328

**Comment by welshm** [comment]
Change looks fine to me - but it's targeting Java Client and OK HTTP - not Spring. Looks like we don't have a Java Client technical committee though

**Review by welshm — APPROVED** [review]

**Comment by wing328** [comment]
@karzang thanks for the PR. Can you please add a fake endpoint with parameter type `number` so as to catch the issue moving forward?

e.g. from the issue
```
		"parameters": [
			{
				"name": "amount",
				"in": "path",
				"required": true,
				"schema": {
					"type": "number"
				}
			},
```

**Comment by wing328** [comment]
tested locally to confirm the fix. will file a PR to add a test after merging this PR

**Pull request merged**
