### PR TITLE
Fixes isFreeFormObject detection

### PR DESCRIPTION
**Pull request by spacether**
We have a bug in master branch where this schema:
```
    A:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/B'
```
Is incorrectly interpreted as FreeFormObject when it should be a MapSchema
Per our java documentation a schema is FreeForm if:
```
A free form object is an object (i.e. 'type: object' in a OAS document) that:
1) Does not define properties, and
2) Is not a composed schema (no anyOf, oneOf, allOf), and
3) additionalproperties is not defined, or additionalproperties: true, or additionalproperties: {}.
```
Schema A does not satisfy requirement 3. Requirement 3 only allows additionalproperties  values of null, true, and empty object {}. We have {$ref: '#/components/schemas/B'} which is different.

This PR fixes that bug by making sure that when we are in isFreeFormObject we check to see that a ref does not exist in additionalProperties.
- A test has been added demonstrating that the above model is generated with our updated code
- If merged, this PR will fix https://github.com/OpenAPITools/openapi-generator/issues/7372#issuecomment-689776396
 

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by keymone** [comment]
if i understand correctly, the error is in `modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java`, so it should be affecting all languages. why did i only get the exception in python-experimental?

**Comment by keymone** [comment]
otherwise the fix looks good, thanks for addressing this so quickly!

**Comment by spacether** [comment]
> if i understand correctly, if the error is in `modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java` then it should be affecting all languages. why did i only get the exception in python-experimental?

So there are two issues at play with why the error is seen in python-experimental and not other generators.
1. Is schema A seen as a FreeFormObject? In master branch yes it is incorrectly classified as FreeFormObject rather than MapSchema. That means that it will not be generated.
2. python-experimental post processes all models to make sure that their imports are formatted correctly for python. Because schema A was not generated, [this line ](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientExperimentalCodegen.java#L432)throws a null pointer exception. This only happens in python-experimental because we are post processing all models (whether or not they are generated, and we hit some data where a value that we are trying to grab is null). If other generators were trying to get the "models" value in the schema A model they will also hit this exception. They don't do this same iteration, or they handle the null condition.

That's why it is only seen in python-experimental.

**Review by wing328 — APPROVED** [review]
LGTM

**Pull request merged**
