### PR TITLE
[kotlin-spring] Move Jackson annotation from field to getter

### PR DESCRIPTION
**Pull request by juherr**
In some cases, Jackson will duplicate entries when the annotation is on the field.
The behavior is expected, see https://github.com/FasterXML/jackson-databind/issues/1609

Also, a similar issue exists on the java generator: https://github.com/OpenAPITools/openapi-generator/issues/5705

Ping @jimschubert

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR. Please follow step 3 in the PR checklist to update the samples so that the CI can verify the change.

cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

**Comment by juherr** [comment]
@wing328 Thanks for the reminder. Step 3, done.

**Comment by 4brunu** [comment]
I don't have much experience with jackson, but I think we already merge something similar to kotlin client.

**Comment by jigarshah** [comment]
Is there a reason this is not merged ? quite simple solution to strange api spec (not invalid).

**Comment by 4brunu** [comment]
@juherr could you please fix the conflicts? Thanks

**Comment by volsusdev** [comment]
Hi @juherr, thanks for this fix. Would it be possible to get it merged?

**Comment by juherr** [comment]
@volsusdev PR rebased

**Comment by volsusdev** [comment]
Thanks a lot @juherr. Who is able to merge it, maybe @wing328?

**Review by 4brunu — APPROVED** [review]

**Comment by volsusdev** [comment]
Awesome, thank you guys. Looking forward for the next release including this fix 🙂

**Pull request merged**
