### PR TITLE
static access to normalizeMediaType in typescript object serializer

### LINKED ISSUE #20201: [BUG][typescript] Cannot read properties of undefined (reading 'normalizeMediaType')
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

using TypeScript generated APIs I run into:

```shell
Cannot read properties of undefined (reading 'normalizeMediaType')
TypeError: Cannot read properties of undefined (reading 'normalizeMediaType')
    at getPreferredMediaType ([...]\models\ObjectSerializer.ts:269:54)
```

when looking at [the code](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/others/typescript/encode-decode/build/models/ObjectSerializer.ts#L265), the problem seems pretty obvious. as far as I am concerned, `this` does not exist in a `static` method. that is the point of being static, isn't it? having no reference to an object.

##### openapi-generator version

7.10.0 of `org.openapitools:openapi-generator-maven-plugin`. using the `typescript` generator.

##### OpenAPI declaration file content or url

not relevant imo. can be reproduced using [petstore API](https://petstore.swagger.io/).

##### Generation Details

in the `build` section of `pom.xml` the following is contained.

```xml
<plugin>
                        <groupId>org.openapitools</groupId>
                        <artifactId>openapi-generator-maven-plugin</artifactId>
                        <configuration>
                            <configOptions>
                                <oas3>true</oas3>
                                <useTags>true</useTags>
                            </configOptions>
                            <generatorName>typescript</generatorName>
                            <output>${generator.output.dir}</output>
                        </configuration>
                        <executions>
                            <execution>
                                <id>generate-registration-resource</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>generate</goal>
                                </goals>
                                <configuration>
                                    <inputSpec>${maven.multiModuleProjectDirectory}/specs/${api.registration-controller.v2.file}</inputSpec>
                                    <output>${generator.output.dir}/registration</output>
                                </configuration>
                            </execution>
```

##### Steps to reproduce

if _really_ required I can create a reproducer. but the bug is pretty logical imo.

I have applied the proposed fix locally, recompiled the library (without _regenerating_ the API) and everything went just fine.

##### Related issues/PRs

-

##### Suggest a fix

update the [`ObjectSerializer.ts`](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/others/typescript/encode-decode/build/models/ObjectSerializer.ts#L265) to this:

```typescript
        const normalMediaTypes = mediaTypes.map(ObjectSerializer.normalizeMediaType);
```

instead of

```typescript
        const normalMediaTypes = mediaTypes.map(this.normalizeMediaType);
```

### PR DESCRIPTION
**Pull request by bbortt**
accessing `normalizeMediaType` should be done static in `ObjectSerializer`, as described in https://github.com/OpenAPITools/openapi-generator/issues/20201.

fix applies only to the `typescript` generator.

closes #20201 if accepted as solution by maintainers.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc: @joscha

### CODE REVIEW

**Review by joscha — APPROVED** [review]
`ObjectSerializer` is in the `*` import, yes? I haven't actually checked. Intent LGTM

**Comment by joscha** [comment]
@macjohnny @wing328 I'll need one of you for approving workflows and then merging this, please.

**Comment by joscha** [comment]
@macjohnny did you check `ObjectSerializer` is in there? I wasn't actually sure and was hoping for the CI to tell us 👯

**Comment by macjohnny** [comment]
> @macjohnny did you check `ObjectSerializer` is in there? I wasn't actually sure and was hoping for the CI to tell us 👯 

it is in the very same file, its the class that is defined in that file

**Comment by joscha** [comment]
> it is in the very same file, its the class that is defined in that file

I looked and must have scrolled past it :-/ Thank you!

**Comment by bbortt** [comment]
> it is in the very same file, its the class that is defined in that file

sorry for my late answer, I was out of office for lunch. that is correct. the method is a static method of this very class.

thanks for your quick doing guys!

**Pull request merged**
