### PR TITLE
[Swift 5] remove old swift sample

### PR DESCRIPTION
**Pull request by 4brunu**
This old sample is not used anymore.
So this PR removes it.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

### CODE REVIEW

**Comment by 4brunu** [comment]
The build is failing because in the bitrise CI, we are using the configuration file in the bitrise console, instead of the bitrise.yml file in the repository.

I updated the bitrise.yml, but it's not having effect because of what I described.

I found this guide on how to use the bitrise.yml in the repository.
https://devcenter.bitrise.io/tips-and-tricks/use-bitrise-yml-from-repository/

The main advantage, is that for example in this PR, I need to change the build settings, and I can do it directly in this PR.

@wing328 what do you think? Could we start to use the bitrise.yml file in the repository?

Thanks

**Comment by wing328** [comment]
> @wing328 what do you think? Could we start to use the bitrise.yml file in the repository?

Agreed. I couldn't find a way before. Let's coordinate later today or this week to make this change so that we can use bitrise.yml from the repository instead.

**Comment by 4brunu** [comment]
Hey @wing328,
Any news on this? 🙂 
Can I help?
Thanks

**Comment by wing328** [comment]
Just merged it and update bitrise.yml config in the CI provider.

**Comment by 4brunu** [comment]
Thanks

**Comment by wing328** [comment]
@4brunu but looks like it breaks the build. Please take a look when you've time. I've PM'd you the details via Slack.

**Pull request merged**
