### PR TITLE
[Kotlin][Multiplatform] Fix Enum Generation 

### LINKED ISSUE #10902: [BUG] Kotlin multiplatform, Kotlinx Serialization, Error while generating enum classes
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

## Description

Openapi generator produce enum classes with error while using kotlinx.serialization

## Version

> Gradle plugin "org.openapi.generator"
> 5.3.0

**Gradle version 7.0.0-bin**

## OpenAPI declaration file content or url

```yml
---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths: {}
components:
  schemas:
    Foo:
      description: "Enum class Foo"
      enum:
        - Foo
        - Bar
      type: string
```

## Generation Details

```kts
tasks.register("generateKotlinClient", org.openapitools.generator.gradle.plugin.tasks.GenerateTask::class) {
    generatorName.set("kotlin")
    library.set("multiplatform")
    inputSpec.set("$rootDir/{NAME_YML_FILE}.yml")
    outputDir.set("$buildDir/generated")
}
```

## Steps to reproduce

> ./gradlew clean generateKotlinClient

## Output vs Expected Output

Output
```
@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import kotlinx.serialization.*

@Serializable(with = Foo.Serializer::class)
enum class Foo(val value: kotlin.String) {

    @SerialName(value = "Foo")
    foo("Foo"),

    @SerialName(value = "Bar")
    bar("Bar");

    override fun toString(): String = value

    companion object {
        fun encode(data: Any?): kotlin.String? = if (data is Foo) "$data" else null

        fun decode(data: Any?): Foo? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
```

which results with
```
@Serializable(with = Foo.Serializer::class)
```

however, I would expect
```
@Serializable
```

When trying to build with the output by generated **build.gradle.kts** in the $buildDir/generated, I am catching error by task **compileKotlinJs**
>  Task :compileKotlinJs FAILED
> \build\generated\src\commonMain\kotlin\...\models\Foo.kt: (31, 22): An annotation argument must be a compile-time constant
> \build\generated\src\commonMain\kotlin\...\models\Foo.kt: (31, 26): Unresolved reference: Serializer

### PR DESCRIPTION
**Pull request by tkirshboim**
### PR Description

Fixes #10902 

- Fix broken generation of enum classes by removing unnecessary template code that broke the compilation of the generated code.

#### Reproducing the issue

To validate that this PR fixes the issue you should first reproduce the issue. This can be done on the `master` branch by generating the `kotlin-multiplatform` template code with the `petstore-with-fake-endpoints-models-for-testing.yaml` API spec, and then trying to compile the generated code:
```
./bin/generate-samples.sh bin/configs/kotlin-multiplatform.yaml -- -i modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
./mvnw integration-test -f samples/client/petstore/kotlin-multiplatform/pom.xml
```

The test fails due to several compilation errors. The errors that are relevant for the purpose of this PR, as reported in #10902 , can be observed in `OuterEnum.kt` and `EnumClass.kt`:
```
[redacted]
e: ./openapi-generator/samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/models/EnumClass.kt: (31, 32): Unresolved reference: Serializer
[redacted]
e: ./openapi-generator/samples/client/petstore/kotlin-multiplatform/src/commonMain/kotlin/org/openapitools/client/models/OuterEnum.kt: (31, 32): Unresolved reference: Serializer
``` 

To validate that this PR fixes the issue, checkout this PR's code and re-run the two commands from above. The compile errors in `OuterEnum.kt` and `EnumClass.kt` are no longer present.

#### CCs
Kotlin technical committee: @jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

Reporter of #10902 : @Qbit982

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by 4brunu** [comment]
Hey @tkirshboim, thanks for opening this PR.
Could you please run the following PR to generate the sample projects?
```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```
Thanks

**Comment by tkirshboim** [comment]
> Hey @tkirshboim, thanks for opening this PR. Could you please run the following PR to generate the sample projects?
> 
> ```
> ./mvnw clean package 
> ./bin/generate-samples.sh
> ```
> 
> Thanks

@4brunu Thanks for the prompt response.
I've ran these commands and there are no local changes to commit when they've completed. This is probably because `modules/openapi-generator/src/test/resources/2_0/petstore.yaml` does not contain the enum definitions that cause the `enum_class.mustache` template to be used. This is the reason why I used `petstore-with-fake-endpoints-models-for-testing.yaml` to validate that the issue is resolved.

**Comment by 4brunu** [comment]
I see.
Did you test this in your local local project? Is it working?

**Comment by tkirshboim** [comment]
> I see. Did you test this in your local local project? Is it working?

@4brunu Yes. I was experiencing the same issue as #10902 and this change resolved the issue. The project compiled again and worked as expected with this change.

**Comment by 4brunu** [comment]
Thanks, looks good to me 👍

**Pull request merged**
