### PR TITLE
[bugfix][dart-dio-next] Fix condition bug in dart-dio-next OauthInterceptor

### PR DESCRIPTION
**Pull request by DevAtHeart**
There was a bug in OAuthInterceptor of dart-dio-next where it would never handle any request because of a condition that could never be true.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela

### CODE REVIEW

**Review by jaumard — APPROVED** [review]

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by DevAtHeart** [comment]
Thank you for the hint! 🙈 Fixed!

**Review by agilob — APPROVED** [review]

**Comment by agilob** [comment]
Would be nice if this was tested too

**Comment by wing328** [comment]
@DevAtHeart looks like the sample is not up-to-date. Can you please update the samples? (step 3 in the PR checklist)

Let us know if you need any help.

**Comment by DevAtHeart** [comment]
Should be fixed now.

**Comment by kuhnroyal** [comment]
Yea looks correct but please revert the changes to the README. This seems to be caused by Windows separators.

**Comment by wing328** [comment]
> Yea looks correct but please revert the changes to the README. This seems to be caused by Windows separators.

I'll update that after merging this PR into master

**Comment by DevAtHeart** [comment]
Sorry for the README, I keep telling git to use unix line separators... 🙄

**Pull request merged**
