### PR TITLE
[node-express-server] template-only change to fix use of 'airbnb-base' ESLint plugin

### LINKED ISSUE #7843: [BUG][node-express-server] .eslintrc.json extends "airbnb" but should be "airbnb-base"
##### Description

The `.eslintrc.json` generated from `eslintrc.mustache` attempts to extend the `airbnb` config plugin. This is incompatible with the `eslint-config-airbnb-base` included as a dev dependency in the `package.json` generated by `package.mustache`.  ESLint generates an error: `Cannot find module 'eslint-config-airbnb'`.

##### openapi-generator version

Discovered on `stable 4.3.1`, confirmed on `master`. Looks like it was introduced in `4.3.0` by https://github.com/OpenAPITools/openapi-generator/pull/5675.

##### OpenAPI declaration file content or url

Reproduced with the Petstore demo example at [https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml](https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml)

##### Command line used for generation

```
java -jar ~/dev/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
    --generator-name nodejs-express-server \
    --input-spec https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
    --output build/
```

##### Steps to reproduce

1. Clone the repo, and build with `mvn clean install`
2. Run the `generate` command above
3. Run ESLint on the generated `expressServer.js`: `npx eslint expressServer.js` or `yarn run eslint expressServer.js`

__Note:__ Once this issue is fixed, ESLint finds some errors that I consider out of scope of this issue — but after this is fixed, it is at least able to run.

##### Related issues/PRs

I searched but didn't  find any. 

##### Suggest a fix/enhancement

**This is a simple fix:** Updating `eslintrc.mustache` to extend `airbnb-base` resolves this.

It makes sense to stick with `eslint-config-airbnb-base`, which "provides Airbnb's base JS .eslintrc (without React plugins)" (quoting eslint-config-airbnb-base's [description](https://www.npmjs.com/package/eslint-config-airbnb-base)).

I'm working on a PR.

### PR DESCRIPTION
**Pull request by MatthewEppelsheimer**
CC-ing Node/JavaScript technical committee: @CodeNinjai, @frol, @cliffano.

Closes #7843.

To validate, please see the steps to reproduce in #7843.

I believe re-generating Petstore samples isn't needed for this change — no results with `grep -R airbnb samples/client/petstore/*` — but I'm not sure I understand this correctly. I ran `./bin/generate-samples.sh bin/configs/typescript-node*` and `./bin/generate-samples.sh bin/configs/javascript*` just to be sure and got "success" messages.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by MatthewEppelsheimer** [comment]
I'm new here and don't have much context for those 👆🏻 failing checks, but neither of them seem related to the change.  If I need to address either of them somehow, I could use some pointers. 😺

**Comment by wing328** [comment]
@MatthewEppelsheimer thanks for the PR. CI failure not related to this change.

**Comment by wing328** [comment]
cc @YishTish

**Comment by wing328** [comment]
Appveyor failure not related to this change

**Pull request merged**
