### PR TITLE
fix incorrect generic type in go-server codegen template

### PR DESCRIPTION
**Pull request by dimavt**
typo in https://github.com/OpenAPITools/openapi-generator/pull/15185 introduces this build error if you use bool params in your spec:
```
*hidden*: cannot use parseBool (value of type func(param string) (bool, error)) as type ParseString[float32] in argument to WithParse[float32]
``` 
This PR fixes typo
 

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by dimavt** [comment]
Hey @wing328 @rledisez ! Latest change introduces build errors in my pipelines could you help me finish this PR ?

**Comment by wing328** [comment]
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

**Comment by lwj5** [comment]
@dimavt yes there indeed is a typo. Have you tested on your document with the fix?

**Comment by wing328** [comment]
circielci tests do not seem to related to this PR.

**Comment by wing328** [comment]
tested locally and the output compiles without issues. will add a test in another PR.

```diff
--- a/samples/server/petstore/go-api-server/go/api_user.go
+++ b/samples/server/petstore/go-api-server/go/api_user.go
@@ -203,7 +203,15 @@ func (c *UserAPIController) LoginUser(w http.ResponseWriter, r *http.Request) {
        query := r.URL.Query()
        usernameParam := query.Get("username")
        passwordParam := query.Get("password")
-       result, err := c.service.LoginUser(r.Context(), usernameParam, passwordParam)
+       booleanTestParam, err := parseBoolParameter(
+               query.Get("boolean_test"),
+               WithParse[bool](parseBool),
+       )
+       if err != nil {
+               w.WriteHeader(500)
+               return
+       }
+       result, err := c.service.LoginUser(r.Context(), usernameParam, passwordParam, booleanTestParam)
        // If an error occurred, encode the error with the status code
        if err != nil {

```

**Comment by wing328** [comment]
Filed and merged https://github.com/OpenAPITools/openapi-generator/pull/15563 to add a test covering this issue moving forward.

**Pull request merged**
