### PR TITLE
[core] Allow using lists as globalProperty in config files

### PR DESCRIPTION
**Pull request by kuhnroyal**
This allows for config files of this sort:

```yaml
globalProperties:
  skipFormModel: true
  apiTests: false
  modelTests: false
  supportingFiles: ''
  models:
    - Pet
    - Dog
    - User
  apis:
    - UserApi
```

This is much easier to use than comma separated strings, especially for large lists (I have 50+ models out of 100+)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
@wing328 @GORA-SAG Do you guys think this is useful? I am using this for a while now in my projects with lots of classes and it really makes it a lot easier to configure.

**Comment by GORA-SAG** [comment]
@kuhnroyal this is really cool and easy to configure and helpful in cases which involves more classes. typically in that situation providing it in a config file is more easy as we can't provide everything in command line, but for automation kind of stuff which involves some dynamic model changes then the fix that i have done will be helpful. ultimately it's depends on the use case.

**Comment by wing328** [comment]
@kuhnroyal looks good 👍 

To be clear, it's the config file supplied via `-c` (not a separate config file), right?

**Comment by kuhnroyal** [comment]
@wing328 Yes, the existing config file that gets passed to the CLI with `-c`. Where should this be documented?

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
@kuhnroyal let's go with what you suggest in this PR 👍

**Pull request merged**
