### PR TITLE
[BUG][Ada] Incorrect client Ada code generated

### LINKED ISSUE #7594: [BUG][Ada] Incorrect client Ada code generated
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The Ada client generator generates incorrect code:

* when a `FreeFormObject` is used,
* when several path parameters are used

##### openapi-generator version

5.0.0-SNAPSHOT.

##### OpenAPI declaration file content or url

A partial example of URL with two path parameters:

```yaml
paths:
  '/converter/{format}/{target}':
    post:
      tags:
        - converter
      summary: Convert a text from one format to another
      description: ''
      operationId: convert
      parameters:
        - name: format
          in: path
          description: The source Wiki format
          required: true
          schema:
            type: string
            enum:
              - html
              - markdown
              - dotclear
              - creole
              - mediawiki
        - name: target
          in: path
          description: The target Wiki format
          required: true
          schema:
            type: string
```

##### Generation Details

* The code generator generates the same index number for both path parameters (we can access only the first path parameter!!!)
* The `FreeFormObject` generates code that does not compile.

##### Steps to reproduce

I'm using the following command:

```
openapi-generator generate --generator-name ada -i file.yaml --additional-properties projectName=todos --model-package Todos -o .
```

##### Suggest a fix

I'll submit a pull to fix the above :-)

### PR DESCRIPTION
**Pull request by stcarrez**
- Fix the identification of path parameters
- Fix the model and client to support FreeFormObject

To fix #7594

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by codymikol** [comment]
You might want to do `git commit --amend --no-edit && git push -f` The circle CI build timed out for me as well and just needed to be rerun

**Comment by wing328** [comment]
Pushed https://github.com/OpenAPITools/openapi-generator/pull/7596/commits/765c7bf80661dc212bde59a3cdac7bbb6e103d8f to fix the CI failure. Let's see how that goes.

**Comment by wing328** [comment]
@codymikol FYI. Another way is to close and reopen the PR to trigger all the CI jobs.

**Comment by wing328** [comment]
I know how to fix the CI failures. Will do it later this week.

**Comment by wing328** [comment]
@stcarrez Not sure why but I couldn't fix the issue in your branch. I've created https://github.com/OpenAPITools/openapi-generator/pull/7719 instead.

**Comment by stcarrez** [comment]
@wing328, thanks for the integration!  I'm closing this pull request since you integrated it.

**Pull request closed without merging**
