### PR TITLE
feat(rust): support ability to disable boxed models in client

### PR DESCRIPTION
**Pull request by DDtKey**
Add new additional property `avoidBoxedModels` which can be configured to avoid `Box<..>` of models.
(alternative could be `boxModels` that defaults to `true`)

It's very nice to have such config, because it doesn't make a lot of sense for really simple models.

Also it fixes undesired boxes for non-models in `oneOf` generation (followup after #17915 & particularly https://github.com/OpenAPITools/openapi-generator/pull/17915#issuecomment-1957744381). E.g: [before this PR](https://github.com/OpenAPITools/openapi-generator/blob/6e113842cf2f35e90e9dc13c124fbb65fadbb7c5/samples/client/others/rust/hyper/oneOf-array-map/src/models/fruit.rs#L16-L17) - and [after](https://github.com/OpenAPITools/openapi-generator/blob/6bfec20d651ab39bfb7013223805b45f7e6adac8/samples/client/others/rust/hyper/oneOf-array-map/src/models/fruit.rs#L15-L18)

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@frol @farcaller @richardwhiuk @paladinzh @jacob-pro cc @wing328

### CODE REVIEW

**Comment by DDtKey** [comment]
cc @RobbieMcKinstry this PR removes unnecessary `Box`es for non-models in `Enum`s.
And moreover, allows you to disable boxes at all by an additional property `avoidBoxedModels`.

**Comment by RobbieMcKinstry** [comment]
You rule! Very cool, thank you very much! ❤️

**Comment by DDtKey** [comment]
I rebased this one onto master branch, because #17915 has been merged. 
So now it's ready to review!

**Comment by DDtKey** [comment]
@wing328 sorry for direct mentioning, but just wondering if it's possible to incorporate this change as part of `7.4.0`? 

It's a good addition to already merged #17915 and should compatible with existed behavior because of default value of the new property.

**Comment by wing328** [comment]
lgtm. thanks for the PR. let's give it a try

**Pull request merged**
