### PR TITLE
[python-experimental] implement `in` operator for model classes

### PR DESCRIPTION
**Pull request by keymone**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Allow to check for attribute presence in model using `in` operator.

Unless I'm missing something, right now the only way to correctly get an attribute which may not be present is this:

    try:
        attr_value = instance.attr_name
    except ApiAttributeError:
        attr_value = None

which is quite cumbersome.

@spacether

### CODE REVIEW

**Review by spacether — APPROVED** [review]
Thank you for the PR. This looks great!

**Comment by keymone** [comment]
@spacether relevant question - is there value in raising an exception instead of returning `None` for access of legit attribute that doesn't have value? now that it's possible to test for presence of an attribute, it's easy to differentiate between that and legit `None` value.

code i want to simplify is this:

    value = instance.attr if 'attr' in instance else None
    if value is not None:
        # do something

with default `None` it's just be:

    if instance.attr is not None:
        # do something

thoughts?

**Comment by spacether** [comment]
In my opinion there is value. Attributes can be nullable which is different than being unset.
Let's say
attribute_a has value None if we access it we should get None
Now let's say attribute a is unset if we try to access it directly with model.attribut_a we should get some kind of exception. This lets us differentiate between these use cases.

**Comment by spacether** [comment]
If you want this functionality why not ad a default missing input argument to getattt in ModelNormal and ModelComposd? That would make it work like python dict.get.
Then one could do model.get(param_name, default_value_if_missing)

**Comment by keymone** [comment]
> Now let's say attribute a is unset if we try to access it directly with model.attribute_a we should get some kind of exception. This lets us differentiate between these use cases.

we definitely can differentiate in both cases via exception or by using `'attr' in instance`, i just think that using exceptions for that leads to more complex code than necessary. it is much more often that one needs to react to `None` value regardless if it was set or the attribute is missing, than to differentiate between set and unset `None`.

> Then one could do model.get(param_name, default_value_if_missing)

yes, that's another method i want to add, but it would be nice if using attributes directly was more convenient. right now i have to wrap in try/except way too much :(

> Why not use model._data_store.get(name)?

i don't think all attributes are in there? required attributes seem to be in model.__dict__ directly.

**Comment by spacether** [comment]
> i don't think all attributes are in there? required attributes seem to be in model.__dict__ directly.

The attribute that are not in _data_store is data about the class or the composed instance.
I think that all payload key value pairs are in _data_store.

**Pull request merged**
