### PR TITLE
[php] Handle \SplFileObject before primitive(to avoid php8 settype() error)

### PR DESCRIPTION
**Pull request by 77web**
Hi, I ran into a settype() error in php8 when ObjectSerializer deserializes "file" in OpenAPI into "\SplFileObject" in PHP.
languageSpecificPrimitives are passed to settype()  in ObjectSerializer::deserialize(), though SplFileObject cannot be passed to settype() function in php8. settype() only accepts real primitives: "bool", "boolean", "int", "integer", "float", "double", "string", "array", "object", "null".
So SplFileObject should be handled before primitive handler, just the same as \DateTime.

@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ybelenko** [comment]
That's obviously a bug. Give me few more days to reproduce issue and test on local machine.

**Comment by ybelenko** [comment]
@77web please make sure you ticked **Allow edits and access to secrets by maintainers** checkbox since I might need to push my additional changes to your branch.

**Comment by 77web** [comment]
@ybelenko Thank you! I confirmed "Allow edits by maintainers" has a check :smile:

**Comment by ybelenko** [comment]
There was the same error with PHP 7.4(bug has been reproduced). I've added few unit tests and pushed new samples to pass CI. @77web let me know if you satisfied with the result so I can merge.

```console
vendor/bin/phpunit tests/ObjectSerializerTest.php

PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

...                                                                 3 / 3 (100%)

Time: 00:00.043, Memory: 6.00 MB

OK (3 tests, 13 assertions)
```

**Review by ybelenko — APPROVED** [review]

**Comment by 77web** [comment]
@ybelenko Thanks a lot!! It seems ok for me!🙇

**Pull request merged**
