### PR TITLE
[BUG] Change default value for header parameter

### LINKED ISSUE #15989: [BUG] Header default value set to "null"
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When not specified the default value of a string header is set to `"null"`

##### openapi-generator version

7.0.0-SNAPSHOT

##### OpenAPI declaration file content or URL

Example of header without default value
```yaml
      parameters:
        - description: Custom HTTP header
          name: Custom-Header
          in: header
          schema:
            type: string

```

during the code generation the default value of the property is retrieved from the Schema default value. When the default is not defined the CodeGen returns a string with `"null"`

### PR DESCRIPTION
**Pull request by gcatanese**
Fix #15989 

When a property has no default value the string `"null"` is used as default.

This PR changes the `getPropertyDefaultValue` for strings from `"null"` to `""` (empty string)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
this fix is mainly for the postman collection generator, right?

if that's the case, I don't think we should update default codegen.

What about overriding the method in postman collection generator instead?

**Comment by gcatanese** [comment]
Yes, that's an option but this applies to all generators IMO. When a parameter has no default the default codegen provides `"null"` string as default, for each type. Event for strings the default `"null"` is not a great option.
Looking at the comments in the [code](https://github.com/OpenAPITools/openapi-generator/blob/85df55b20e2af75e2ce35f3f8e2286bc31e1af7e/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2210)  it looks to me they are supposed to be addressed at some point.

My suggestion would be to return `null` instead of the `"null"` string for each type. That's better as it respects the OpenAPI specs (if it doesn't specify a default value why would we generate one?) and let the generators decide what to do.
Let me know what you think, I can refactor in this way (return null) or go for the custom Postman fix.

**Comment by wing328** [comment]
> Looking at the comments in the [code](https://github.com/OpenAPITools/openapi-generator/blob/85df55b20e2af75e2ce35f3f8e2286bc31e1af7e/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2210) it looks to me they are supposed to be addressed at some point.

The comment simply said the code block is to illustrate how to handle default value for different type so that generators can override this method easily.

> When a parameter has no default the default codegen provides "null" string as default, for each type

The default codegen was created primarily for java client/server generators so it won't meet the requirement of generators in different languages. That's why generators should override `toDefaultValue` instead.

> This PR changes the getPropertyDefaultValue for strings from "null" to "" (empty string)

I don't think the header parameter should default to "" (empty string) in most generators as the default header will now become 
```
x-just-a-header: 
```
as opposed to simply omitting the header in the HTTP request.

Updating something in default codegen requires lots of tests and reviews and in this case I would suggest simply overriding `toDefaultValue` to meet your requirement in the postman collection generator.

**Comment by wing328** [comment]
FYI. I've fled https://github.com/OpenAPITools/openapi-generator/pull/16003 to clean up the code a bit to avoid confusions.

**Comment by gcatanese** [comment]
@wing328 thanks for the clarifications. 

The issue is that the default value `"null"` does not omit the header, and instead send
```
x-just-a-header: "null"
```
I thought that would be an issue for most generators.

Anyway, I followed your suggestion and dealt with this within the Postman generator, please see the changes.

**Pull request merged**
