### PR TITLE
[BUG] [Java] Invalid code generation for oneof types.

### LINKED ISSUE #18517: [BUG] [Java] Invalid code generation for oneof types.
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
The generator generated an invalid java class when generating a client for the github api definition.

##### openapi-generator version
v7.5.0 (docker image: [openapitools/openapi-generator-cli:v7.5.0](https://hub.docker.com/layers/openapitools/openapi-generator-cli/v7.5.0/images/sha256-55ff6454b7e169a2de206539ab4c9ac480770f373480a9e5e5891319e5f81491?context=explore))
Note the docker image "latest" was also tested and has the same issue.

##### OpenAPI declaration file content or url
https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
line **35245** seems to be the issue:
```json
"payload": {
    "oneOf": [
        {
            "type": "object",
            "additionalProperties": true
        },
        {
            "type": "string",
            "description": "JSON payload with extra information about the deployment.",
            "default": ""
        }
    ]
}
```
This generated a class that doesn't compile (ReposCreateDeploymentRequestPayload.java).
Compiling the generated project using "gradle build" causes 6 compiler errors, all within this one class.
For example the following method is generated:
```java
/**
 * Get the actual instance of `Map<String, Object>`. If the actual instance is not `Map<String, Object>`,
 * the ClassCastException will be thrown.
 *
 * @return The actual instance of `Map<String, Object>`
 * @throws ClassCastException if the instance is not `Map<String, Object>`
 */
public Map<String, Object> getMap<String, Object>() throws ClassCastException {
    return (Map<String, Object>)super.getActualInstance();
}
```
Other errors include invalid field names (containing ``Map<String, Object>``) or calls like ``Map<String, Object>.class``
```java
final TypeAdapter<Map<String, Object>> adapterMap<String, Object> = gson.getDelegateAdapter(this, TypeToken.get(Map<String, Object>.class));
```
See gradle error logs:
https://gist.github.com/Bethibande/4d0c2e925daff40572bcb3cee44d6ed7

##### Generation Details / Steps to reproduce
This can be reproduced on Windows with Docker (WSL) using the following two commands:
```shell
docker run --rm -v "%CD%:/local" openapitools/openapi-generator-cli:v7.5.0 generate -i https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json -g java -o /local/out/java
docker run --rm -v "%CD%:/local" -w /local/out/java gradle:8.7.0-jdk17 gradle build
```

##### Suggest a fix

1. Remove ``<``, ``,, `` and ``>`` from field and method names resulting in names like ``getMapStringObject`` or ``adapterMapStringObject``
2. Change TypeToken creation for Map types from ``TypeToken.get(Map<String, Object>.class)`` to ``TypeToken.getParameterized(Map.class, String.class, Object.class)`` or ``new TypeToken<Map<String, Object>>() {}``, see Gson documentation for [TypeToken](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html)

### PR DESCRIPTION
**Pull request by Bethibande**
Fixes #18517, Gradle builds work again using the test file: https://gist.github.com/Bethibande/c97b0b64e3dc284c056c02fbf3778a9b

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR.

can you please add a test model (oneOf with map as sub schema) in `modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml`?

**Comment by Bethibande** [comment]
Going to add the unit-tests later.

**Comment by wing328** [comment]
when you've time, can you please add a unit test or 2 in https://github.com/OpenAPITools/openapi-generator/blob/c80075bc2ee24634a5124a52d3088d11b6b13719/samples/client/petstore/java/okhttp-gson/src/test/java/org/openapitools/client/JSONTest.java ? (which contains many examples on unit testing the models)

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/8920607680/job/24599035459?pr=18544

please update the samples and add new files

**Comment by wing328** [comment]
thanks for the PR, which has been merged.

https://github.com/OpenAPITools/openapi-generator/actions/runs/9016604828/job/24773787312 fixed via eec30f2cdac

**Comment by cambiph** [comment]
This issue also impacts jersey3.
I have the following config:
```                    
                    <execution>
                        <id>mock-server</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/static/public/jamesdbloom-mock-server-openapi-5.15.x-swagger.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <modelPackage>be.fgov.minfin.dad2.taf.datasetup.mockserver.model</modelPackage>
                            <apiPackage>be.fgov.minfin.dad2.taf.datasetup.mockserver.api</apiPackage>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <modelNameSuffix>DTO</modelNameSuffix>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <library>jersey3</library>
                                <useJakartaEe>true</useJakartaEe>
                                <useSingleRequestParameter>true</useSingleRequestParameter>
                            </configOptions>
                        </configuration>
                    </execution>
```

The following classes are generated incorrectly: Body, KeyToValue, BodyWithContentType and SchemaType
For example Body:
```
    /**
     * Get the actual instance of `Map<String, Object>`. If the actual instance is not `Map<String, Object>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Map<String, Object>`
     * @throws ClassCastException if the instance is not `Map<String, Object>`
     */
    public Map<String, Object> getMap<String, Object>() throws ClassCastException {
        return (Map<String, Object>)super.getActualInstance();
    }
```

The method signature should be:
```
 public Map<String, Object> getMap() throws ClassCastException {
```
without <String, Object>

**Pull request merged**
