### PR TITLE
[scala][templates] java 8 dates support

### PR DESCRIPTION
**Pull request by chameleon82**
Java 8 `LocalDate` for `OpenApi date` and `OffsetDateTime` for `OpenApi date-time` types support.
Additional property `dateLibrary` with `joda` and `java8` options added. Default to `joda`.
 
I believe `joda` should be deprecated regarding to official joda recommendation (https://www.joda.org/joda-time/) and switched by default to `java8` date library for all java based languages. 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

UPD: `java8` is a default option for all scala templates with fallback `joda` supported option

@clasnake @jimschubert @shijinkui @ramzimaalej

### CODE REVIEW

**Comment by chameleon82** [comment]
Breaking changes as Serializer extracted to separate class `DatesSerializers` and can break clients which  use invoiker with non-default parameters.

**Comment by chameleon82** [comment]
As part of https://github.com/OpenAPITools/openapi-generator/issues/5401

**Comment by chameleon82** [comment]
dateLibrary option moved to AbstractScala to support all abstract scala based templates.
two options present:
`joda` - default
`java8` - should it be renamed to `jsr-310` ?
for legacy `http-client` dateLibrary explicitly defined as `legacy`. is that unobvious as that option will not be present in cli option list?

**Comment by chameleon82** [comment]
@wing328 @jimschubert `scalaz` project fixed, but wont compile https://circleci.com/gh/OpenAPITools/openapi-generator/13311?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
seems test was running with `java-7-openjdk`, but as generated project has scala version `2.11.8` it should be run with `java-8` ( https://www.scala-lang.org/download/2.11.8.html ) 
could you help to adjust this test?

**Comment by wing328** [comment]
Please remove this line https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L1388

**Comment by wing328** [comment]
> I believe joda should be deprecated regarding to official joda recommendation (https://www.joda.org/joda-time/) and switched by default to java8 date library for all java based languages.

The upcoming release is 4.3.0, which can include breaking changes with fallback. What about setting `java8` as the default option instead?

**Comment by chameleon82** [comment]
@wing328 i've updated to `java8` by default. `joda` is a fallback option 
and `legacy` option available only for deprecated `http-client` by default, which, i believe will be removed in `5.0.0`
https://github.com/OpenAPITools/openapi-generator/pull/5291/files#diff-62e3a15550247bb6a76bdc7745faa850R45

**Pull request merged**
