### PR TITLE
Move Java Spring Springfox ApiIgnore under conditions

### PR DESCRIPTION
**Pull request by fvlad**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by fvlad** [comment]
@wing328 thanks for the tip, fixed

**Comment by fvlad** [comment]
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

**Comment by fvlad** [comment]
Please review
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

**Comment by fvlad** [comment]
Guys, any feedback? Please review.
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

**Comment by alwaysbemark** [comment]
@fvlad Any news on merging this? Anything I could do to help? This could be extremely useful to do away with the Springfox imports in a Spring project.
Just to call it out - there could be cases where the import is generated twice, but that should be okay. Thank you!

**Comment by fvlad** [comment]
@alwaysbemark I would be happy to merge but I don't have permissions and there is no feedback from the reviewers.
Guys can you help? @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

**Comment by fvlad** [comment]
Tried a different approach, by removing imports and just referencing a full path to @springfox.documentation.annotations.ApiIgnore annotation. This way we avoid duplicates in imports.
Also rebased on the latest master.

**Comment by alwaysbemark** [comment]
@wing328 Perhaps? This PR looks extremely small and unharmful and will save many unnecessary megabytes in JARs. Is there anything else that needs to be done for this PR? Thank you very much!

**Comment by wing328** [comment]
Will review later today or this week. Sorry for the delay as there are too many PRs pending review.

**Comment by wing328** [comment]
Tested locally and the result is good.

**Comment by wing328** [comment]
@fvlad sorry for the delay. The PR has been merged and will be included in the upcoming v5.3.0 release due in early Oct

**Pull request merged**
