### PR TITLE
Kotlin client multiple enums

### PR DESCRIPTION
**Pull request by andrewemery**
Fix for https://github.com/OpenAPITools/openapi-generator/issues/3917.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by andrewemery** [comment]
@wing328 Thanks, but you can probably close this issue now.

This fix was also included in https://github.com/OpenAPITools/openapi-generator/pull/3900

**Comment by wing328** [comment]
@andrewemery ah I thought you undo those changes in #3900 and filed a separate PR instead.

**Comment by andrewemery** [comment]
@wing328 Thanks. I kept the fix in because it touched that part of the template, but I raised a separate pull request because I assumed https://github.com/OpenAPITools/openapi-generator/pull/3900 would take much longer to get merged.

**Comment by wing328** [comment]
@andrewemery that's ok. (I wasn't clear to begin with).

Do you have a Twitter account? We'll tag you in a tweet to promote the multi-platform client.

**Comment by andrewemery** [comment]
@wing328 No, but thank you for asking.

**Pull request closed without merging**
