### PR TITLE
[maven] mark Mojo threadSafe=true + fix concurrency issue in CodegenConfigurator

### LINKED ISSUE #5862: [BUG] openapi-generator-maven-plugin is not marked as threadSafe
##### Description

Building a Maven multimodule project in parallel (e.g. `mvn -T2 ...`) that uses `openapi-generator-maven-plugin` yields the following warning for each plugin execution:
```
[2020-04-08T13:59:47.119Z] [WARNING] *****************************************************************
[2020-04-08T13:59:47.119Z] [WARNING] * Your build is requesting parallel execution, but project      *
[2020-04-08T13:59:47.119Z] [WARNING] * contains the following plugin(s) that have goals not marked   *
[2020-04-08T13:59:47.119Z] [WARNING] * as @threadSafe to support parallel building.                  *
[2020-04-08T13:59:47.119Z] [WARNING] * While this /may/ work fine, please look for plugin updates    *
[2020-04-08T13:59:47.119Z] [WARNING] * and/or request plugins be made thread-safe.                   *
[2020-04-08T13:59:47.119Z] [WARNING] * If reporting an issue, report it against the plugin in        *
[2020-04-08T13:59:47.119Z] [WARNING] * question, not against maven-core                              *
[2020-04-08T13:59:47.119Z] [WARNING] *****************************************************************
[2020-04-08T13:59:47.119Z] [WARNING] The following plugins are not marked @threadSafe in some-module:
[2020-04-08T13:59:47.119Z] [WARNING] org.openapitools:openapi-generator-maven-plugin:4.2.3
[2020-04-08T13:59:47.119Z] [WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[2020-04-08T13:59:47.119Z] [WARNING] *****************************************************************
```

##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

not relevant

##### Command line used for generation

`mvn clean install -T2` (example)

##### Steps to reproduce

Build a multimodule project taht is using `openapi-generator-maven-plugin` in parallel.

##### Related issues/PRs

n/a

##### Suggest a fix

Add `threadSafe=true` to `@Mojo`: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-maven-plugin/src/main/java/org/openapitools/codegen/plugin/CodeGenMojo.java#L73
This _assumes_ that the plugin does handle concurrent invocations (form different modules) without concurrency issues!

### PR DESCRIPTION
**Pull request by famod**
Fixes #5862.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

---

The change to `CodegenConfigurator` looks more than it really is. I just pulled out everything that is related to actually _parse_ the file into a `synchronized` method to resolve the following concurrency issue: https://github.com/OpenAPITools/openapi-generator/issues/5862#issuecomment-611023874

I must say though, that the existing approach to mutate a singleton `ObjectMapper` seems rather dodgy.

Before my change, I was able to provoke the issue in my current project (which I am not allowed to share) after max. 30 mins via:
```
time while mvn -T2 openapi-generator:generate@generate-code -pl moduleA,moduleB -Dopenapi-generator-maven-plugin.version=4.3.1-SNAPSHOT; do :; done
```
After my change I stopped the loop after 2 hours.

### CODE REVIEW

**Comment by famod** [comment]
Sorry, wrong user in commit message. Fixed via force push.

**Comment by jimschubert** [comment]
Thanks for contributing this fix.

Unfortunately, I don't think this is a solution for the bug you've linked from. It looks like you're generating from one module (moduleA) and then in the same build you're trying to compile the generated code (moduleB). The reason the code in your PR would work is because you're locking on a static call and blocking your `generate` phase. This doesn't address thread-safety, really, but rather makes this operation blocking and kinda defeats the existing usage in multi-threaded applications.

`CodegenConfigurator` is already thread-safe, as `ObjectMapper` instances are guaranteed to be thread-safe if configured before use, and no state on this `fromFile` is shared between threads. `CodegenConfigurator` has been used in our [`batch` command](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/GenerateBatch.java#L143) since around October or November 2019.

Can you revert the change to synchronize within CodegenConfigurator and provide a full example to better evaluate whether CodegenMojo can be made to be thread-safe for your use case?

**Comment by famod** [comment]
@jimschubert 

> It looks like you're generating from one module (moduleA) and then in the same build you're trying to compile the generated code (moduleB).

I should have added more context:
- moduleA is generating _and compiling_ code from its own api.json (let's call it apiA.json)
- moduleB is generating _and compiling_ code from its own api.json (let's call it apiB.json)
- _both_ modules use a JSON `configFile` from yet another module (where exactly that file resides is not really important, IMO), I even guess each module could use its _own_ JSON `configFile` and the problem would still arise

So, both module have their individual generation and compilation. Compilation does not actually contribute to the problem because the bug can be triggered (sooner or later) by just executing the openapi-plugin (concurrenty in the two modules). This does not involve compilation at all.

> `CodegenConfigurator` is already thread-safe, as `ObjectMapper` instances are guaranteed to be thread-safe if configured before use, and no state on this `fromFile` is shared between threads. 

AFAICS, yes and no.
Yes, `ObjectMapper` instances can and should be used concurrently for reading/parsing, _once such an instance is fully configured!_ See also JavaDoc of `ObjectMapper`:

>  * Mapper instances are fully thread-safe provided that ALL configuration of the
>   * instance occurs before ANY read or write calls. If configuration of a mapper instance
>   * is modified after first usage, changes may or may not take effect, and configuration
>   * calls themselves may fail.

But `CodegenConfigurator` _is_ (potentially) mutating the configuration of the singleton `ObjectMapper` it gets from `Json.mapper()` by registering modules.
`CodegenConfigurator` bit:
```java
            if (FilenameUtils.isExtension(configFile, new String[]{"yml", "yaml"})) {
                mapper = Yaml.mapper();
            } else {
                mapper = Json.mapper();
            }

            if (modules != null && modules.length > 0) {
                mapper.registerModules(modules);
            }

            mapper.registerModule(new GuavaModule());
```
`io.swagger.v3.core.util.Json` bit:
```java
    private static ObjectMapper mapper;

    public static ObjectMapper mapper() {
        if (mapper == null) {
            mapper = ObjectMapperFactory.createJson();
        }
        return mapper;
    }
```

This can happen concurrently, or to be more specific: In my case thw slower thread seems to modify the mapper while the first, faster thread already tries to read the file.

> provide a full example to better evaluate whether CodegenMojo can be made to be thread-safe for your use case?

I can try to come up with a sample project.
In the beginning I tried to reproduce the problem with a unit test but failed. Concurrency problems are often hard to provoke.

**Comment by jimschubert** [comment]
I see, modifying the mapper is not ideal here. It would be better to use the copy operation and create a new instance of the desired mapper, especially since this method allows passing multiple additional modules.

If you'd like, I can make that change so we can avoid the thread lock. But, I'd still be interested in seeing a minimal full repro. I've run the batch operation on all generators hundreds of times with my configuration at 24 threads. I'd like to profile and understand why you can repro this with 2 threads through the Maven plugin while others and myself haven't had issues by other means to rule out any other issues with Maven being multi-threaded. For instance, we should see this issue in the Gradle Plugin with parallel builds if it's causing issue in Gradle. Also, although the SBT plugin is new, I've run it numerous times without issue, but I'm not sure if my SBT configuration is threaded... it's also only a single project.

**Comment by famod** [comment]
I was able to reproduce the problem with a unit test:
```java
package org.openapitools.codegen.config;

import java.util.stream.IntStream;

import org.openapitools.codegen.config.CodegenConfigurator;
import org.testng.annotations.Test;

public class CodegenConfiguratorParallelTest {

    @Test
    public void test() {
        final String file = "src/test/resources/sampleConfig.json";

        IntStream.range(0, 10).parallel()
            .forEach(i -> {
                System.out.println(i + ": " + Thread.currentThread().getId());
                CodegenConfigurator.fromFile(file);
            });
    }
}
```
Just add this test to `modules/openapi-generator/src/test/java/org/openapitools/codegen/config` and run it until the error strikes:
```
while mvn jacoco:prepare-agent@jacoco-initialize surefire:test@default-test -Dtest=CodegenConfiguratorParallelTest -Djacoco.skip; do :; done
```
This optimized command just executes surefire (and jacoco because I could not figure out how to set `@{argLine}` to an empty string).
You can add `-f modules/openapi-generator` if calling running from root.

After some time the loop should break and the error should be logged. This may take more than 10 minutes!

**Comment by jimschubert** [comment]
@famod thanks, I'll see if I can repro with that test as well.

Here's a diff which _should_ resolve without any locks and also fixes an additional bug where non-lowercase filenames would result in yaml being parsed as JSON (sorry, saw this while looking at this code with a critical eye).

```diff
diff --git a/modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java b/modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
index f7e17bd8e2..840790ed4c 100644
--- a/modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
+++ b/modules/openapi-generator/src/main/java/org/openapitools/codegen/config/CodegenConfigurator.java
@@ -124,13 +124,13 @@ public class CodegenConfigurator {
         return null;
     }
 
-    private static synchronized DynamicSettings readDynamicSettings(String configFile, Module... modules) {
+    private static DynamicSettings readDynamicSettings(String configFile, Module... modules) {
         ObjectMapper mapper;
 
-        if (FilenameUtils.isExtension(configFile, new String[]{"yml", "yaml"})) {
-            mapper = Yaml.mapper();
+        if (FilenameUtils.isExtension(configFile.toLowerCase(Locale.ROOT), new String[]{"yml", "yaml"})) {
+            mapper = Yaml.mapper().copy();
         } else {
-            mapper = Json.mapper();
+            mapper = Json.mapper().copy();
         }
 
         if (modules != null && modules.length > 0) {

```

Would you mind trying the above diff on your branch to see if it resolves?

**Comment by famod** [comment]
Error after > 11 mins:
image

**Comment by famod** [comment]
> Would you mind trying the above diff on your branch to see if it resolves?

Sure! First I actually wanted to use `copy()` myself but I was under the impression that this would not suffice, but I cannot remember why.

Btw, the above screenshot is from a Windows 10 machine with Git Bash but the problem first occured on our Jenkins running on CentOS7.

**Comment by jimschubert** [comment]
I appreciate it. I bumped the parallel count to 50 and I ran for 18 minutes with my diff and T24 (which shouldn't make a difference here, as it should just do parallel work in the test), and had no issue. My machine completes the full build in ~5s, so that's quite a few executions of parallel runs. I'll rerun without the diff and see how long it takes to repro.

**Comment by jimschubert** [comment]
ok I've run my diff for 45 minutes and your code for about 30 minutes, and neither failed. I bumped the max thread from 10 to 100 in your test and removed synchronized on your branch and the build fails immediately.

Your concerns about `.copy()` were probably the additional memory. Most folks are likely running similar scenarios to yours; up to a handful of one-off compilations and then the process is terminated. However, there are a few other places that openapi-generator is being used (APIs, SaaS, IDE plugins). For those cases, I'd rather increase the memory a little and trigger GC than lock one or more threads with synchronization.

If you're willing to apply the diff and verify the multi-threaded functionality in your build, I'd like to get this into 4.3.1.

I really appreciate you not only discovering this issue, but digging in to find a fix, and for being open to suggestions and testing.

**Comment by famod** [comment]
You are welcome!

I'll try `copy()` later today.

If you have no objections, I'd keep the new private method (without `synchronized`) as this improves readability, IMO.

PS: Besides more memory consumption the copy-solution will probably spend a few more CPU cycles initially:

> Although configuration is shared, cached serializers and deserializers are NOT shared, which means that the new instance may be re-configured before use; meaning that it behaves the same way as if an instance was constructed from scratch.

But I do think `copy()` is the best option.

**Comment by famod** [comment]
I pushed the copy-solution. I aborted the test loop after one hour.

**Comment by famod** [comment]
Travis CI build is green (the status here is outdated) and Bitrise hit a timeout. No idea why.

**Comment by famod** [comment]
@jimschubert is there anything left to do for me?

**Comment by jimschubert** [comment]
@famod fixes should be good. I won't have chance to evaluate until the weekend, though. Been too busy at work this week to allow for much extracurricular open source, unfortunately.

**Comment by jimschubert** [comment]
cc @OpenAPITools/generator-core-team This looks good to me. If there are no objections to this approach, I'll merge either tonight or tomorrow.

**Comment by wing328** [comment]
@famod thanks for the PR, which has been included in the v4.3.1 release: https://twitter.com/oas_generator/status/1258057660974329861

**Pull request merged**
