### PR TITLE
Fixed Readonly Docs for python

### PR DESCRIPTION
**Pull request by psav**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by psav** [comment]
@Jyhess - Can you take a look at this - I had some trouble building the project with SELinux enabled, perhaps you can tell me if it's necessary here?

**Comment by wing328** [comment]
@psav I'll take care of the CircleCI failure later by updating the samples.

Thanks for the fix.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/4102 to update the samples and fix the same issue in other templates.

**Comment by wing328** [comment]
cc Python technical committee: @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

**Pull request merged**
