### PR TITLE
[rust]: Remove unmaintained samples and specs

### PR DESCRIPTION
**Pull request by jacob-pro**
This removes the unmaintained samples and specs for the Rust client which are no longer automatically built.

The 2 test cases, TypeTesting and fileResponse have been merged into the main Rust spec (`modules/openapi-generator/src/test/resources/3_0/rust/petstore.yaml`).

See slack thread: https://openapi-generator.slack.com/archives/CLSB0U0R5/p1660567811900359?thread_ts=1660508979.486299&cid=CLSB0U0R5

The `rust-reqwest-petstore-async` and `rust-reqwest-petstore-awsv4signature` have also been changed to use the rust specific spec.

I have added a unit test for the TypeTesting case, currently in `reqwest/petstore`. Of the 4 different samples I am not sure if this is the correct one to put this test in? 

An obsevation concerning the  fileResponse test, it looks to me like the generated code for file download is completely broken, for both reqwest and hyper, since they are both attempting to deserialize the response as JSON! So this will need to be fixed separately. Edit: already reported here: https://github.com/OpenAPITools/openapi-generator/pull/9021

Another observation is that despite being configured with `supportAsync: "false"`, the hyper client generator is producing asynchronous code (using futures)... Two issues here: Hyper doesn't have a blocking API, so this combination shouldn't be allowed. The generated code should be using the more modern async syntax rather than directly returning Futures

cc: @wing328 @spacether

### CODE REVIEW

**Comment by wing328** [comment]
cc @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)

**Comment by wing328** [comment]
CI (travis) reported the following issues:
```
   Compiling tokio v0.1.22
   Compiling cookie_store v0.7.0
   Compiling hyper v0.12.36
   Compiling hyper-tls v0.3.2
   Compiling reqwest v0.9.24
   Compiling petstore-reqwest v1.0.0 (/home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/rust/reqwest/petstore)
error[E0463]: can't find crate for `petstore_reqwest_async`
 --> reqwest/petstore/tests/type_testing.rs:1:1
  |
1 | extern crate petstore_reqwest_async;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
For more information about this error, try `rustc --explain E0463`.
error: could not compile `petstore-reqwest` due to previous error
warning: build failed, waiting for other jobs to finish...
```

can you please take a look when you've time?

**Comment by jacob-pro** [comment]
Ah that's because I moved the file from reqwest/pestore-async to request/petstore. 

> I have added a unit test for the TypeTesting case, currently in reqwest/petstore. Of the 4 different samples I am not sure if this is the correct one to put this test in?

Please can you confirm if this was the correct one / how you choose which samples to put tests in?

Also is there a link to the CI - I was expecting to see test failures show up in Github 😕 ?

**Comment by wing328** [comment]
All tests passed via https://app.travis-ci.com/github/OpenAPITools/openapi-generator/builds/254592504

**Pull request merged**
