### PR TITLE
 [Java][Spring] fix unhandledException not working in combination with…

### LINKED ISSUE #4393: [BUG][SPRING] unhandledException not working in combination with skipDefaultInterface
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When I use the optional configuration unhandledException=true in combination with skipDefaultInterface=true the exception is not thrown in the interface.

##### openapi-generator version

4.2.0

###### Actual
```java
Mono<ResponseEntity<TransactionModel>> updateTransaction(@ApiParam(value = "",required=true) @PathVariable("transactionId") Long transactionId,@ApiParam(value = "the transaction to be updated"  )  @Valid @RequestBody Mono<TransactionModel> transactionModel, ServerWebExchange exchange);
```

###### Expected
```java
Mono<ResponseEntity<TransactionModel>> updateTransaction(@ApiParam(value = "",required=true) @PathVariable("transactionId") Long transactionId,@ApiParam(value = "the transaction to be updated"  )  @Valid @RequestBody Mono<TransactionModel> transactionModel, ServerWebExchange exchange) throws Exception;
```

##### Command line used for generation

```xml
<generatorName>spring</generatorName>
<modelNameSuffix>Model</modelNameSuffix>
<configOptions>
  <sourceFolder>src/gen/java/main</sourceFolder>
  <unhandledException>true</unhandledException>
  <interfaceOnly>true</interfaceOnly>
  <skipDefaultInterface>true</skipDefaultInterface>
  <java8>true</java8>
  <dateLibrary>java8</dateLibrary>
  <booleanGetterPrefix>is</booleanGetterPrefix>
  <reactive>true</reactive>
</configOptions>
```

### PR DESCRIPTION
**Pull request by daberni**
Fixes #4393 JavaSpring template by taking configuration options `skipDefaultInterface` and `unhandledException` into account simultaneously properly.

`unhandledException` is no longer dependent on `skipDefaultInterface` as it is applicable to all java versions and implementations independent from abstract classes, interfaces or interfaces with default implementations.

Added additional samples to verify this change and existing samples didn't get touched by it:

e.g.
```
ResponseEntity<Void> addPet(@ApiParam(value = "Pet object that needs to be added to the store" ,required=true )  @Valid @RequestBody Pet body);
```
becomes
```
ResponseEntity<Void> addPet(@ApiParam(value = "Pet object that needs to be added to the store" ,required=true )  @Valid @RequestBody Pet body) throws Exception;
```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @nmuesch the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by daberni** [comment]
failed circleci build shouldn't be related to the current changes

**Comment by SimonErm** [comment]
Can i do anything to help getting this PR merged?

**Comment by daberni** [comment]
Updated everything again, maybe someone can have a quick look at this small fix?

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

**Comment by daberni** [comment]
everything green again.

**Comment by borsch** [comment]
Hi @daberni 
You probably missing some git commits/pushes, because as for now I can see only new sample. No changes to generator itself

**Comment by daberni** [comment]
Thanks for the hint @borsch. Did a rebase today and it looks like someone else already made this fix, and I didn't notice this during conflict resolution.

Feel free to keep the sample for verification in the future, or decline if it isn't necessary.

I guess maintainers could close the referenced issue then, but don't know when this was actually fixed.

**Comment by wing328** [comment]
@daberni thanks for the PR. We'll include the sample in the Github workflow tests for the Spring generator.

**Pull request merged**
