### PR TITLE
[dart][dart-dio] Add built_value date support w/o timemachine

### PR DESCRIPTION
**Pull request by kuhnroyal**
Fixes https://github.com/OpenAPITools/openapi-generator/issues/9095

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
CC @swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)

**Comment by jannikrh** [comment]
While testing the generator and thereby this PR, I noticed two problems. The first one is directly related to the extension. The second one might be a separate issue for which I can open a new issue.

1. In the file `serializers.dart` the import for the new Date class is missing.
```
import 'package:trainer_api/src/model/date.dart';
```
Which leads to the following errors.
```
error - Undefined name 'Date' - lib\src\serializers.g.dart:34:59 - undefined_identifier
error - The name 'Date' isn't a type so it can't be used as a type argument - lib\src\serializers.g.dart:35:33 - non_type_as_type_argument
```

2. When using a pure `type: object` the import `package:built_value/json_object.dart;` for the `JsonObject` is missing.

**Comment by kuhnroyal** [comment]
Do you have an example spec or repro?
The date import should not be needed since the date serializer is added, not sure.

Please create a new issue for 2. and CC me.

**Comment by jannikrh** [comment]
The problem occurs in this basic example. With `flutter analyze`, the missing import is noticeable. In this case, `import 'model/date.dart';` needs to added to `serializers.dart`.

```
error - Undefined name 'Date' - lib\src\serializers.g.dart:12:59 - undefined_identifier
error - The name 'Date' isn't a type so it can't be used as a type argument - lib\src\serializers.g.dart:13:33 - non_type_as_type_argument
```

```
openapi: 3.0.1
info:
  version: 1.0.0
  title: Trainer
paths:
  /test:
    get:
      responses:
        '200':
          description: Groups
          content:
            application/json:
                schema:
                  type: array
                  items:
                    type: object
                    required:
                      - uuid
                      - name
                      - dates
                    properties:
                      uuid:
                        type: string
                        format: uuid
                      name:
                        type: string
                        example: Group A
                      trainingDates:
                        type: array
                        description: Training dates
                        items:
                          type: string
                          format: date
                          
```

**Comment by kuhnroyal** [comment]
I see, an array of dates.

**Comment by kuhnroyal** [comment]
1. should be fixed

**Comment by kuhnroyal** [comment]
Shippable failure is unrelated.

**Comment by kuhnroyal** [comment]
Looking for reviews

**Comment by wing328** [comment]
All tests passed.

**Pull request merged**
