### PR TITLE
upgrade openapi poms and codegen tests to junit5

### PR DESCRIPTION
**Pull request by thorstenhirsch**
PR for openapi poms and codegen tests of #18470

### CODE REVIEW

**Comment by wing328** [comment]
lgtm. thanks for the PR

cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
outdated doc updated via 98f9c07bc45

**Comment by wing328** [comment]
@thorstenhirsch can you please PM me via Slack about this PR when you've time?

**Comment by wing328** [comment]
UPDATE: I've reverted this change via https://github.com/OpenAPITools/openapi-generator/pull/18786 (merged) in the latest master as due to the upgrade, all testng tests were skipped silently (even though there are failed assertions)

I tried various solutions to run both junit5 and testng in the same project but no luck.

My take is to migrate junit4 tests to testng as it would be easier to maintain this project with just one testing framework.

**Comment by Philzen** [comment]
@wing328 

> all testng tests were skipped silently

i was about to ask about this behavior on slack, as i got the same hunch

> I've reverted this change via https://github.com/OpenAPITools/openapi-generator/pull/18786 (merged) in the latest master

that made me a bit sad when i saw it – as i had the silent hope we'd planning to transition to Junit5 rather than TestNG (oh how i miss the `@TempDir` annotation which would make many tests so much more concise!) ... also, consumers of v7.6.0 maybe missing the junit5 generation capability that @thorstenhirsch just introduced...

> I tried various solutions to run both junit5 and testng in the same project but no luck.

I've tried around a little more and after what felt an eternity was finally successful following https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html#How_to_run_TestNG_tests_within_the_JUnit_Platform (using `org.junit.support:testng-engine`)

I was even able to remove the junit4 dependency from the classpath for good, so one will not be bothered by the `org.junit.*` stuff in autocompletion (so now there's only two `@Test` annotations` to choose from instead of three).

See #18790

**Pull request merged**
