### PR TITLE
[elm] fix code generation for nullable types

### PR DESCRIPTION
**Pull request by KMahoney**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

The code generation for nullable types put a parenthesis in the wrong place and added a default value on to the encoder. This fixes both issues.
@eriktim

### CODE REVIEW

**Comment by eriktim** [comment]
Thanks for the PR @KMahoney. Can you please provide a small example OpenAPI spec showing the issue.

**Comment by KMahoney** [comment]
Sure: https://gist.github.com/KMahoney/937b9b7910ebb8fdb7288bcb8ec6b7e3
On master, produces:
```
decoder : Decoder Example
decoder =
    Decode.succeed Example
        |> required "example" (Decode.nullable Decode.int) Nothing



encode : Example -> Encode.Value
encode model =
    Encode.object
        [ ( "example", Maybe.withDefault Encode.null (Maybe.map Encode.int) model.example )

        ]
````

**Comment by eriktim** [comment]
Thanks for the example. Your fix indeed repairs this. However, it breaks the case when the field is not required but nullable. Can you try surrounding the `{{{defaultValue}}}` you removed with `{{^required}}..{{/required}}`?

P.S. I am working on a better test spec file, so I've added this case as well.

**Comment by KMahoney** [comment]
@eriktim Ok, I think that does it. I updated the gist with a more comprehensive test.

**Comment by eriktim** [comment]
@KMahoney looks good now. Thanks for fixing this!

@wing328 can you poke the CircleCI build?

**Comment by wing328** [comment]
CircleCI failure not related to this PR.

**Comment by wing328** [comment]
@KMahoney thanks for the PR, which has been included in v4.2.0 release: https://twitter.com/oas_generator/status/1189824932345069569

**Pull request merged**
