### PR TITLE
Add DELETE with body to kotlin client

### LINKED ISSUE #4046: [REQ] Kotlin Client should support DELETE with body
### Is your feature request related to a problem? Please describe.

[RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.5) allow for the inclusion of a body in a DELETE request, but generated kotlin clients ([as seen here](https://github.com/OpenAPITools/openapi-generator/blob/e5a0d183744c3a7d331b77af4d451ff36cc3da16/samples/client/petstore/kotlin/bin/org/openapitools/client/infrastructure/ApiClient.kt#L98)) will not send a body.

## Describe the solution you'd like

Respect the request body and send it with the delete request.

The following code will fix the line in the generated client.
```kotlin
RequestMethod.DELETE -> Request.Builder().url(url).delete(requestBody(body, contentType))
```

### PR DESCRIPTION
**Pull request by oharaandrew314**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jimschubert @dr4ke616 @karismann @Zomzog

### Description of the PR

Closes #4046

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by oharaandrew314** [comment]
@wing328 Thanks, I added the email to my account.  Now the commits are recognized as me.

I updated the sample that circle CI complained about.  Hopefully we're good to go after that.

**Comment by oharaandrew314** [comment]
It would appear that all recent travis builds are failing.  Seems to be a broken dependency for valgrind.

**Comment by oharaandrew314** [comment]
Re-opening to re-run builds.  Seems like travis might be fixed now.

**Comment by wing328** [comment]
The travis issue has been fixed in the master so don't worry about it.

**Comment by wing328** [comment]
@oharaandrew314 thanks for the PR, which has been included in v4.2.0 release: https://twitter.com/oas_generator/status/1189824932345069569

**Pull request merged**
