### PR TITLE
[python-flask] adopt python3.5+ syntax

### LINKED ISSUE #16377: [REQ] Improve python-flask code syntax
### Is your feature request related to a problem? Please describe.

The generated code still has traces of the python2.7 support, for example, when `six` is used.

## Describe the solution you'd like

Fully adopt the EOL of python2.7 and start using modern python syntax. It could also mean to start using type hints, dataclasses, etc...

## Additional context

We are starting to automate python syntax evolution tool [pyupgrade](https://github.com/asottile/pyupgrade) in our projects, and while it helps the generated code look "less dated", it becomes a extra step in the code generation, slowing the process. 

By maintaining the template syntax, we will have the same result but with a better process.

### PR DESCRIPTION
**Pull request by anis-campos**
removing some residual python2 code, since it is not supported anymore, like:
- no need for `six` anymore
- no need for encoding utf8 in top file
- remove `object` inheritance in base model
- remove absolute import `__future__`

resolve #16377

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
FYI. I've filed https://github.com/OpenAPITools/openapi-generator/pull/16321 to add better pydantic support in the python fastapi generator. Do you think python-flask generator also needs similar enhancement (python flask generator does not use pydantic at the moment if I remember correctly) ?

**Comment by anis-campos** [comment]
> FYI. I've filed #16321 to add better pydantic support in the python fastapi generator. Do you think python-flask generator also needs similar enhancement (python flask generator does not use pydantic at the moment if I remember correctly) ?

I'm not a user of pydantic, we generally use marshmallow and dataclasses in our projects, so I can't really tell the pros and cons, but I will look up to it, it may do some good for us.

However, I'm not sure that adding support for pydantic in the flask generator at this point is really wise. IMO, I would rather have it in another generator, or alternatively, it should be a choice at generation time, not sure how it would pan out, but what is that it would be a breaking change for those already using it.

**Comment by wing328** [comment]
thanks for the feedback. we won't add it to the python flask generator for the time being.

**Comment by wing328** [comment]
LGTM. Thanks for the PR.

FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @krjakbrjak (2023/02)

**Pull request merged**
