### PR TITLE
Add optional parameter for request body

### LINKED ISSUE #16971: [REQ] [SPRING] Generator do not respect Optional for not required RequestBody
### Is your feature request related to a problem? Please describe.

Spring supports optional RequestBody just like the Query Parameter. However, this is currently not implemented, even if Optional is set as a configuration in the parameter.

### PR DESCRIPTION
**Pull request by MelleD**
The PR set not required request body as Optionals for Spring.
Spring supports Optional for request body same like in DTOs or in QueryParams.
This is a breaking change that is not backwards compatible.

Fix #16971

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the`master` 
- [x] If your PR is targeting a particular programming language, @mention the [technical committee]
@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09)

### CODE REVIEW

**Comment by wing328** [comment]
> This is a breaking change that is not backwards compatible.

Thanks for the PR. Shall we consider this a bug fix instead?

**Comment by wing328** [comment]
Not related to this PR but can you have a quick look at https://github.com/OpenAPITools/openapi-generator/pull/16945 when you've time? Thanks.

**Comment by MelleD** [comment]
> Thanks for the PR. Shall we consider this a bug fix instead?

Yes why not I have no strong opinion on that :)

**Comment by MelleD** [comment]
> #16945

I looked into this PR. We currently not using this stubs and interfaces. So not much experience on that.

We use interface only with spring-cloud

**Comment by wing328** [comment]
> We use interface only with spring-cloud

With that PR, my guess is that you don't need the interfaceOnly option any more, right?

**Pull request merged**
