### PR TITLE
[Java][Fix #3952] jackson-databind-nullable version variable Gradle Incompatibility #3952

### LINKED ISSUE #3952: [BUG][Java][client] jackson-databind-nullable version variable Gradle Incompatibility
##### Description

When generating a Java Client library, the `jackson-databind-nullable` version parameter (`jackson-databind-nullable-version`) used in `build.gradle.mustache` contains dashes instead of underscores. This results in an error during a Gradle build:

```
(((jackson - databind) - nullable) - version) is a binary expression, but it should be a variable expression
```

The dashes for this version parameter should be replaces with underscores. [Example file with error](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/build.gradle.mustache)

Gradle Version 5.3.1

##### openapi-generator version

OpenAPI Generator Version 4.1.2

##### Command line used for generation
      java8: true,
      dateLibrary  : "java8",
      useTags: true,
      library: "feign",
      feignVersion: "10.x"

### PR DESCRIPTION
**Pull request by gurumeditator**
### Description of the PR

Removed the dashes from gradle version variables (`jackson-databind-nullable-version`) and replaced with underscores (`jackson_databind_nullable_version`)

See #3952 

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by gurumeditator** [comment]
@wing328 thanks for taking the time to reach out on this. I believe I have made the correction.

**Comment by jmini** [comment]
Maybe I missed something, but this PR does not fix the problem at the root: in the mustache templates.

**Comment by wing328** [comment]
@jmini good catch. I missed it.

@gurumeditator please update the templates with another PR when you've time.

**Comment by gurumeditator** [comment]
Thanks @jmini. Not sure how I missed not including this in the PR. @wing328 updated in #4148

**Comment by wing328** [comment]
@jburgess thanks for the PR, which has been included in v4.2.0 release: https://twitter.com/oas_generator/status/1189824932345069569

**Pull request merged**
