### PR TITLE
[Elixir] Deserialize responses based on status code

### PR DESCRIPTION
**Pull request by mrmstn**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.  cc: @wing328 

### Description of the PR
First of all, sorry if I might made some chaos. I branched this PR from the great work of @yknx4. I'm hoping the change history will look a little bit better after PR https://github.com/OpenAPITools/openapi-generator/pull/2326 was merged.

With this PR the generated elixir client will be able deserialize a response based on the given statuscodes including the ability to match on a default response in case none of the give codes matches (https://swagger.io/docs/specification/describing-responses/)

This PR stops descriptions and doc parts from beeing escaped by mustache and will pin poison to `~> 3.0.0` since poison `4.0.0` doesn't seems to work right now (I haven't investigated anything)

based on https://github.com/OpenAPITools/openapi-generator/pull/2326
closes https://github.com/OpenAPITools/openapi-generator/issues/2334

### CODE REVIEW

**Comment by yknx4** [comment]
Thank you very much for keeping the work on this 👍

**Comment by mrmstn** [comment]
@wing328 could you also merge this PR tomorrow (Wed) ? After https://github.com/OpenAPITools/openapi-generator/pull/2326

**Comment by wing328** [comment]
@mrmstn 👌

**Comment by wing328** [comment]
@mrmstn when you've time, I wonder if you can help resolve the merge conflicts.

**Comment by mrmstn** [comment]
@wing328 this should do the trick, the diff looks good to me now, let's see what the CI says

**Comment by DanielaIvanova** [comment]
@wing328 @mrmstn 
Hi guys! I need these changes in my project, so, i would like to know when this PR will be approved and merged so i could continue working on it. I appreciate the work that you have done here.

**Comment by wing328** [comment]
Just merged the PR into master.

Thanks for the contribution from @mrmstn

**Pull request merged**
