### PR TITLE
Csharp/anyof oneof mixed primitive object parse error

### PR DESCRIPTION
**Pull request by ForgeRubenAguilar**
Deserialization fails for C# client models using anyOf/oneOf with json primitive/array types. Triages #16686 

This is the current workaround we're using with just the templates, but afaik this will produce uncompilable code if the template needs to generate a ctor with `Object` args.

Rather than feeding everything to JObject which will fail for primitives/array json tokens. It uses a switch to deserialize the token appropriate to its json token type. The property setter does validation on the typing, though the types will be wrong for non-string types as JsonReader gives Int64s and Doubles back regardless of the json typing, which doesn't jive with the generated C# type validation in the setter.

I added the repro to issue data, but I was unsure where those tests would live. I saw mention of CI tests. Would that cover the in language generation?

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
FYI @mandrean (2017/08) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05) @iBicha (2023/07)

**Comment by wing328** [comment]
Thanks for the PR.

Please add tests to the test spec and update test file to cover the issues moving forward.

test file: samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools.Test/JSONComposedSchemaTests.cs

test spec: modules/openapi-generator/src/test/resources/3_0/csharp/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml

**Comment by ForgeRubenAguilar** [comment]
@wing328 This should be ready now. Added some tests around the anyOf/oneOf round trip json serialization to samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools.Test/JSONComposedSchemaTests.cs

This solution only covers primitives. Covering enums will require more work around logic in the template building the json deserializer.

**Comment by wing328** [comment]
Some CI tests failed. Can you please take a look when you've time?

For https://github.com/OpenAPITools/openapi-generator/actions/runs/6503860025/job/17710059790?pr=16706, you will need to update `./bin/utils/test_file_list.yaml` ?

**Comment by wing328** [comment]
thanks for the PR. closed via https://github.com/OpenAPITools/openapi-generator/pull/17986

**Pull request closed without merging**
