### PR TITLE
[Python] Generated class methods without self parameter

### LINKED ISSUE #12559: [BUG] [PYTHON] Generated class methods without self parameter
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating the Python client code the class methods do not have `self` parameter

##### openapi-generator version

Occurring with v6.0.1-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  description: API with post endpoint
  termsOfService: n/a
  title: API spec
  version: "12"
servers:
- url: http://localhost:8080
tags:
- name: Modifications
paths:
  /postEndpoint:
    get:
      operationId: postEndpoint
      parameters:
      - explode: true
        in: query
        name: options
        required: false
        schema:
          $ref: '#/components/schemas/Options'
        style: deepObject
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: OK
components:
  schemas:
    Options:
      properties:
        a:
          format: date-time
          nullable: true
          type: string
        b:
          format: date-time
          nullable: true
          type: string
        c:
          items:
            type: string
          type: array
      type: object
```

##### Generation Details

Generated with

```
java -jar openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i openapi.yaml \
   -g python \
    -p packageName=checkout \
    -o src
```

##### Steps to reproduce

Run the command above

##### Related issues/PRs

See #12560

### PR DESCRIPTION
**Pull request by gcatanese**
@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @spacether (2019/11)

Updated mustache template to include `self` parameter in the generated class methods

Fix #12559 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.0.1) (patch release), `6.1.x` (breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by spacether** [comment]
This PR broke the python CI tests at https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/17735/workflows/76098453-90a9-4ea3-92d1-4f7225826300/jobs/40652
Please fix them

**Review by spacether — CHANGES_REQUESTED** [review]
This PR broke the python CI tests ad https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/17735/workflows/76098453-90a9-4ea3-92d1-4f7225826300/jobs/40652
please fix them

**Comment by gcatanese** [comment]
> This PR broke the python CI tests at https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/17735/workflows/76098453-90a9-4ea3-92d1-4f7225826300/jobs/40652 please fix them

Hi @spacether I am able to reproduce the error locally running `make test` but I cannot figure out (after updating the samples) why the discriminator method misses the `self` parameter. Can you please help out and share some insights/leads? I am happy to have a look (and learn) but I am stuck right now. Thanks.

**Comment by spacether** [comment]
A self argument is not needed per the cached property decorator. Why are you adding it? If anything it should be a classmethod or staticmethod. But again that decorator negates the need for an input arg.

**Comment by gcatanese** [comment]
@spacether ok, thanks for clarifying. The generated model doesn't compile (missing self parameter in `discriminator`, etc..). How can I address this without updating the generation (mustache template)?

**Comment by spacether** [comment]
Updating the mustache templates is the only way to add self cls etc parameters

> The generated model doesn't compile
Can you please explain this? The currently generated code runs fin in cpython. What flavor of python are you running our generated code it?

**Comment by gcatanese** [comment]
> Updating the mustache templates is the only way to add self cls etc parameters
> 
> > The generated model doesn't compile
> 
> Can you please explain this? The currently generated code runs fin in cpython. What flavor of python are you running our generated code it?

I use PyCharm on Apple Mac, using the default Python SDK (which I believe is cpython implementation)

**Comment by spacether** [comment]
So then it works as is and the python code is interpreted, not compiled. Why make this change? It is breaking functionality. These self and cls less methods are using a decorator which doesn't require those inputs.

**Comment by gcatanese** [comment]
> So then it works as is and the python code is interpreted, not compiled. Why make this change? It is breaking functionality. These self and cls less methods are using a decorator which doesn't require those inputs.

Thanks @spacether. Isn't the `self` parameter always needed in a class method? The generated code doesn't compile in PyCharm (with a clear syntax error) but maybe I am missing something here. I am closing the PR now, will leave the issue open for a little white to see if anyone else has the same problem.

**Comment by spacether** [comment]
Self is needed for class methods that require instance info. Classmethods require a cls input. The cached_property decorator makes a self or cls input unneeded:
```
class cached_property(object):
    # this caches the result of the function call for fn with no inputs
    # use this as a decorator on function methods that you want converted
    # into cached properties
    result_key = '_results'

    def __init__(self, fn):
        self._fn = fn

    def __get__(self, instance, cls=None):
        if self.result_key in vars(self):
            return vars(self)[self.result_key]
        else:
            result = self._fn()
            setattr(self, self.result_key, result)
            return result
```
If one wanted to, one could convert cached_property decorated methods into methods decorates with:
@property and @classmethod like python-experimental does:
```
@classmethod
@property
@functools.cache
def _composed_schemas(cls):
```
But to do that, one would need to upgrade the python version to 3.9 or higher.

**Pull request closed without merging**
