### PR TITLE
[Java] Add support for m2e-integration to be capable of using

### PR DESCRIPTION
**Pull request by andreas-eternach**
OpenApi-generation from within eclipse (#509)

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. Not sure if it works by just copying the rp here like this: @jeff9finger

### Description of the PR

This PR contains M2E-Integration so that the code generation can be run in eclipse

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by andreas-eternach** [comment]
Thnk you for the hint, indeed i would like to update the PR. 

I am familiar with git and know how to rebase / amend, but not familliar with PRs.

Do i need to open a new PR to get the author-information into the system or can i just change the master-branch in my copy and the PR will be aligned automatically ?

> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Looks like you're using tab for indentation. Please use 4-space instead

**Comment by andreas-eternach** [comment]
Closing this request, going to issue a new one.

**Pull request closed without merging**
