### PR TITLE
allow check for path parameters in matrix style

### LINKED ISSUE #16330: [REQ] Allow mustache templates to support matrix parameters
### Is your feature request related to a problem? Please describe.

In a customer project we need to generate server and client side code for APIs containing matrix parameters. Although the parameter style "matrix" is available as a variable in mustache, there is no corresponding boolean variable to check for this value (in contrast to `isDeepObject` for example). Since there is no logic allowed in templates, it is not possible to define a custom template in order to support matrix parameters. 

## Describe the solution you'd like

It would be very helpful if the mustache parameter context would contain a boolean value to check if a certain parameter is a path variable of style "matrix", much like it is already possible to check for style "deepObject". The changes required to add this value would be very small, I already created a suitable PR.

## Describe alternatives you've considered

A rather dirty workaround would be to generate java code that does this comparsion during runtime (resulting in code like `if ("matrix".equals("matrix"))`), but this is pretty ugly and does not work generating annotations in server code.

### PR DESCRIPTION
**Pull request by mkresse**
Fixes #16330 by adding a boolean variable  `isMatrix` to mustache parameter context. This allows custom template code like:

    {{#isPathParam}}{{#isMatrix}}@MatrixParam{{/isMatrix}}{{^isMatrix}}@PathParam{{/isMatrix}}

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
can you please also add a test or two to cover the new flag?

**Comment by mkresse** [comment]
@wing328, thanks for your very quick reply. Also thanks for your hint regarding the author - just fixed that with a force push. I also added a simple unit test for the new flag, I hope this is sufficient.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Pull request merged**
