### PR TITLE
[PHP] ensure rewound guzzle response body

### LINKED ISSUE #4541: [BUG] [PHP] no data in container due to `$responseBody->getContents()`
## Bug Report Checklist ##

- :ballot_box_with_check: Have you provided a full/minimal spec to reproduce the issue?
- :ballot_box_with_check: Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- :ballot_box_with_check: What's the version of OpenAPI Generator used?
- :ballot_box_with_check: Have you search for related issues/PRs?
- :ballot_box_with_check: What's the actual output vs expected output?

##### Description #####

The method `GuzzleHttp\Psr7\Stream::getContents` will not reset the stream to position 0.
So, when u are using middleware to intercept the response (eg guzzle profiler), getContents will return a empty value. As a consequence the data in the model container will be empty.pty.

##### openapi-generator version

 v4.2.1

##### OpenAPI declaration file content or url

https://gist.github.com/cjprinse/4c5b5e2f5065fc3c24f0829c7448e640

##### Command line used for generation

```bash
npx openapi-generator generate -g php -o bundles/src/Etrias/Bundles/WarehouseBundle/Connector -i ~/swagger.json --skip-validate-spec --invoker-package=Etrias\\\\Bundles\\\\WarehouseBundle\\\\Connector\\\\lib
```

##### Suggest a fix

Use `GuzzleHttp\Psr7\Stream::__toString` instead of `GuzzleHttp\Psr7\Stream::getContents()`

### PR DESCRIPTION
**Pull request by ro0NL**
fixes #4541

for reference https://github.com/guzzle/psr7/blob/19e510056d8d671d9d9e25dc16937b3dd3802ae6/src/Stream.php#L90-L109

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
@ro0NL thanks for the PR. Looks like this change is backward-compatible, which means it should be targetting the master branch?

**Comment by ro0NL** [comment]
@wing328 .. wait `master` is lowest? i.e. `4.2.x`?

**Comment by wing328** [comment]
master is the next stable release (4.2.3)

**Comment by wing328** [comment]
I just changed it and noticed a lot of changes.

I would recommend you file a new PR instead and only update PHP client samples. Let us know if you need help on that.

**Comment by ro0NL** [comment]
@wing328 done.

**Pull request merged**
