### PR TITLE
[Spring][server] oneOf Interface for Spring Boot

### LINKED ISSUE #5381: [BUG] [spring][server] oneOf Polymorphism support for spring boot
##### Description

Currently, openapi-generator doesn't support `oneOf`. It currently generates the following broken code, outputting `UNKNOWN_BASE_TYPE` rather than `Pet` for the example below.
The code is broken with or without the `discriminator` in the Spec.

```java
    default ResponseEntity<Void> _petsPost(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE) {
        return petsPost(UNKNOWN_BASE_TYPE);
    }
```

##### openapi-generator version
`pom.xml`
```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>4.2.3</version>
    <executions>
        <execution>
            <id>generate</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <generatorName>spring</generatorName>
                <generateSupportingFiles>true</generateSupportingFiles>
                <configOptions>
                    <sourceFolder>src/gen/java/main</sourceFolder>
                    <library>spring-boot</library>
                    <java8>true</java8>
                    <interfaceOnly>true</interfaceOnly>
                    <skipDefaultInterface>false</skipDefaultInterface>
                    <delegatePattern>true</delegatePattern>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

##### OpenAPI Spec
`api.yaml`
```yaml
openapi: "3.0.2"
info:
  version: 1.0.0
  title: Polymorphism
paths:
  /pets:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
              discriminator:
                propertyName: pet_type
      responses:
        '200':
          description: created
components:
  schemas:
    # Parent
    Pet:
      type: object
      required:
        - pet_type      
      properties:
        pet_type:
          type: string
        eats:
          type: string
      discriminator:
        propertyName: pet_type
    # Child 1
    Dog:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Dog`
          properties:
            bark:
              type: boolean
    # Child 2
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Cat`
          properties:
            climbs:
              type: boolean
```

##### Steps to reproduce

* create a `pom.xml` with openapi-generator-maven-plugin 4.2.3
* create `api.yaml` file above
* `mvn clean compile`
* see broken code under target directory `\target\generated-sources\openapi\src\gen\java\main\org\openapitools\api\PetsApi.java`

##### Related issues/PRs

This bug is related to the Server side Java code (SpringBoot)
@bkabrda has already merged PR for client Jackson Client side: https://github.com/OpenAPITools/openapi-generator/pull/5120

##### Suggest a fix

Try apply client side fix from https://github.com/OpenAPITools/openapi-generator/pull/5120 to server side.

### PR DESCRIPTION
**Pull request by jburgess**
This implements `OneOf` interfaces for the Java Spring library. Merges #5661 (@alexsuperdev) and #6589 (@rfecher) and refreshes against the main branch.

Fixes #5381 and #15 (for Spring)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

### CODE REVIEW

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team as the change impacts default codegen.

**Comment by jburgess** [comment]
@wing328 can I get you to re-run the CI? Looks like a transient dependency download error.

**Comment by guluevruslan** [comment]
@wing328, hi.
Could these changes be included into the patch for version 4.3.1?

**Comment by saurcery** [comment]
hi @jburgess @wing328 any update on this :)
is this slated for any milestone/patch release ?

**Comment by rj93** [comment]
any news on this? @OpenAPITools/generator-core-team

**Comment by tim-hilt** [comment]
Also would love to have this functionality!

**Comment by tim-hilt** [comment]
@jburgess thanks for your work so far! Really excited for what happens next!

**Comment by wing328** [comment]
@jburgess thanks again for the PR and sorry for the delay in reviewing as there're too many PRs.

Please resolve the merge conflicts and I'll review later this week.

**Comment by wing328** [comment]
FYI. I've resolved the merge conflicts and filed https://github.com/OpenAPITools/openapi-generator/pull/10392 instead.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/11650

**Pull request closed without merging**
