### PR TITLE
[C][Client] Fix enum function names not matching headers in the model…

### LINKED ISSUE #17510: [BUG] [C] Inconsistent function naming for enum string conversions
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating code containing enums we get functions to convert to/from a string. However the function name and the prototype are different.

In item_resource.c
```
char* valueitem_resource_ToString(simple_api_item_resource_VALUE_e value) {
    char* valueArray[] =  { "NULL", "value1", "value2" };
    return valueArray[value];
}
```
In item_resource.h
```
char* item_resource_value_ToString(simple_api_item_resource_VALUE_e value);
```
I would expect them to have the same names. We have instead just been patching the output.

##### openapi-generator version

Tested with 6.6.0 originally but reproduced on 7.2.0 and master (8b5b5a74c33).

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: Simple API
  version: 1.0.0
servers:
- url: /
paths:
  /{id}:
    get:
      summary: Get item
      description: |-
        Gets the item.
      parameters:
      - name: id
        in: path
        description: |-
          Gets the specific item in the form of xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        required: true
        schema:
          type: string
      - name: content
        in: query
        schema:
          type: string
          enum:
            - all
            - subset
      responses:
        '200':
          $ref: '#/components/responses/GetItem'
components:
  schemas:
    ItemResource:
      type: object
      properties:
        value:
          type: string
          enum:
            - value1
            - value2
    GetItemResult:
      type: object
      properties:
        key:
          $ref: '#/components/schemas/ItemResource'
      description: |-
        Representation of an item
  responses:
    GetItem:
      description: |-
        Representation of an item returned
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetItemResult'
```

##### Generation Details

```
java -jar ../openapi-generator-cli-7.2.0.jar generate -g c  --additional-properties=prependFormOrBodyParameters=true -o out -i ../simple.yaml
```

##### Steps to reproduce

1. Generate the C client with the above command line and the provided spec
2. Observe the incorrect code output in `out/model/item_resource.(c/h)`

##### Related issues/PRs

I have looked through all the issues marked with [C] and can't see any duplicates. I also can't find any open PRs attempting to fix this.

##### Suggest a fix

I think this is the fix but I don't know if it's complete or if it will break anything else. I'll try and make a PR one I work out how to do that.
```
diff --git a/modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache b/modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
index 1cb6759f7ad..98bbfd37998 100644
--- a/modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
+++ b/modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache
@@ -77,12 +77,12 @@ end:
     {{^isContainer}}
     {{^isModel}}
     {{#isEnum}}
-char* {{name}}{{classname}}_ToString({{projectName}}_{{classVarName}}_{{enumName}}_e {{name}}) {
+char* {{classname}}_{{name}}_ToString({{projectName}}_{{classVarName}}_{{enumName}}_e {{name}}) {
     char* {{name}}Array[] =  { "NULL"{{#allowableValues}}{{#values}}, "{{.}}"{{/values}}{{/allowableValues}} };
     return {{name}}Array[{{name}}];
 }
 
-{{projectName}}_{{classVarName}}_{{enumName}}_e {{name}}{{classname}}_FromString(char* {{name}}){
+{{projectName}}_{{classVarName}}_{{enumName}}_e {{classname}}_{{name}}_FromString(char* {{name}}){
     int stringToReturn = 0;
     char *{{name}}Array[] =  { "NULL"{{#allowableValues}}{{#values}}, "{{.}}"{{/values}}{{/allowableValues}} };
     size_t sizeofArray = sizeof({{name}}Array) / sizeof({{name}}Array[0]);
@@ -101,12 +101,12 @@ char* {{name}}{{classname}}_ToString({{projectName}}_{{classVarName}}_{{enumName
     {{#items}}
     {{^isModel}}
     {{#isEnum}}
-char* {{name}}{{classname}}_ToString({{projectName}}_{{classVarName}}_{{enumName}}_e {{name}}) {
+char* {{classname}}_{{name}}_ToString({{projectName}}_{{classVarName}}_{{enumName}}_e {{name}}) {
     char *{{name}}Array[] =  { "NULL"{{#allowableValues}}{{#values}}, "{{.}}"{{/values}}{{/allowableValues}} };
     return {{name}}Array[{{name}} - 1];
 }
 
-{{projectName}}_{{classVarName}}_{{enumName}}_e {{name}}{{classname}}_FromString(char* {{name}}) {
+{{projectName}}_{{classVarName}}_{{enumName}}_e {{classname}}_{{name}}_FromString(char* {{name}}) {
 }
 
-{{projectName}}_{{classVarName}}_{{enumName}}_e {{name}}{{classname}}_FromString(char* {{name}}) {
+{{projectName}}_{{classVarName}}_{{enumName}}_e {{classname}}_{{name}}_FromString(char* {{name}}) {
     int stringToReturn = 0;
     char *{{name}}Array[] =  { "NULL"{{#allowableValues}}{{#values}}, "{{.}}"{{/values}}{{/allowableValues}} };
     size_t sizeofArray = sizeof({{name}}Array) / sizeof({{name}}Array[0]);
@@ -629,7 +629,7 @@ fail:
     {
     goto end; //Enum
     }
-    {{name}}Variable = {{name}}{{classname}}_FromString({{{name}}}->valuestring);
+    {{name}}Variable = {{classname}}_{{name}}_FromString({{{name}}}->valuestring);
     {{/isString}}
     {{/isEnum}}
     {{^isEnum}}
```

### PR DESCRIPTION
**Pull request by bookerdj**
… template

- fixes #17510

This changes the template for the body to match the template for the header. I have also regenerated the sample code.
I don't know where to begin with testing this but I'm willing to learn if I could be pointed in the right direction!

@zhemant 
@ityuhui
@michelealbano

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by bookerdj** [comment]
I'm working on an additional fix in the same files that fixes the default value for enums being set to -1 in the create function.
Wondering if it's worth packaging it all up into one PR or keeping them separate.

**Review by ityuhui — APPROVED** [review]
LGTM

**Comment by ityuhui** [comment]
> I'm working on an additional fix in the same files that fixes the default value for enums being set to -1 in the create function. Wondering if it's worth packaging it all up into one PR or keeping them separate.
> 
> #17513

I recommend not packaging it (changing the default value for enums) into this PR so that this PR is focused on fixing bugs with inconsistent function declarations and definitions.

**Review by zhemant — APPROVED** [review]
Lgtm

**Pull request merged**
