### PR TITLE
fix: [typescript-angular] `.join` does not exist on type `Set`

### LINKED ISSUE #11782: [BUG] [typescript-angular] join does not exist on type Set
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?

##### Description

When having `uniqueItems: true"` in the yaml the generated typescript code has an error : `Property 'join' does not exist on type 'Set<XXXX>'.ts(2339)
`

The error does not happen when using `--type-mappings=set=Array`.

##### openapi-generator version

5.3.1

##### OpenAPI declaration file content or url

```yaml
servers:
  - url: http://localhost/api
    description: Local development environment
paths:

  /tools/in-zones:
    get:
      operationId: GetToolsInMultipleZone
      tags:
        - Tools
      summary: ...
      description: ...
      parameters:
        - name: zoneIds
          in: query
          description: ...
          required: true
          style: form
          explode: false
          schema:
            type: array
            minLength: 1
            maxLength: 100
            uniqueItems: true
            items:
              $ref: '#/components/schemas/ZoneIdSchema'
      responses:
        '200':
          description: OK
          headers:
            X-Request-ID:
              $ref: '#/components/headers/X-Request-ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolsCollectionResponseSchema'
        '400':
          description: Bad Request
          headers:
            X-Request-ID:
              $ref: '#/components/headers/X-Request-ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorSchema'
```

### PR DESCRIPTION
**Pull request by snebjorn**
Fixes #11782 see bug report for details about the issue

To validate the work run
```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i https://raw.githubusercontent.com/snebjorn/openapi-gen-bug/master/join-bug.json \
   -g typescript-angular \
   -o output-master/join-bug
```
and check that all `.join` calls in a service (`api/default.service.ts`) are valid typescript. Meaning that it no longer calls `.join` directly on a `Set`.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

### CODE REVIEW

**Comment by snebjorn** [comment]
I ran these with Git BASH (I'm on windows)
```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```
But it turned all `/` into `\` and other issues. Seems there's an issue with the scripts on windows.

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by snebjorn** [comment]
> Thanks for your contribution Can you please re-generate the samples?

I have the above mentioned issue when running the scripts. Not sure what is going on. Any suggestions?

**Comment by macjohnny** [comment]
Hmm ok so there seems to be an issue with the windows scripts.
Can you run in in WSL?

**Comment by snebjorn** [comment]
@macjohnny I managed to generate the relevant stuff using WSL.

However
```
./bin/generate-samples.sh
```
threw this
```
[[pool-1-thread-8] Generation failed for python-experimental: (RuntimeException) Could not generate model 'AdditionalPropertiesClass'
java.lang.RuntimeException: Could not generate model 'AdditionalPropertiesClass'
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:563)
pool-1-thread-4 at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:912)
        at org.openapitools.codegen.cmd.GenerateBatch$GenerationRunner.run(GenerateBatch.java:232)
] Generating python     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 (outputs to    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
/mnt/d/Users/me/Source/openapi-generator/samples/openapi3/client/features/dynamic-servers/python  at java.base/java.lang.Thread.run(Thread.java:833)
)…Caused by: com.github.jknack.handlebars.HandlebarsException: model.handlebars:3:3: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @6fa4fbe3
    model.handlebars:3:3

        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at com.github.jknack.handlebars.context.FieldValueResolver$FieldMember.setAccessible(FieldValueResolver.java:150)
        at com.github.jknack.handlebars.context.MemberValueResolver.cache(MemberValueResolver.java:82)
        at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:54)
        at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve(Context.java:199)
        at com.github.jknack.handlebars.internal.path.PropertyPath.eval(PropertyPath.java:52)
        at com.github.jknack.handlebars.Context$PathExpressionChain.next(Context.java:361)
        at com.github.jknack.handlebars.Context$PathExpressionChain.eval(Context.java:381)
        at com.github.jknack.handlebars.Context.get(Context.java:618)
        at com.github.jknack.handlebars.internal.Partial.override(Partial.java:253)
        at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:226)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
        at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:125)
        at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:113)
        at org.openapitools.codegen.templating.HandlebarsEngineAdapter.compileTemplate(HandlebarsEngineAdapter.java:92)
        at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1058)
        at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1045)
        at org.openapitools.codegen.DefaultGenerator.generateModel(DefaultGenerator.java:402)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:554)
        ... 5 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @6fa4fbe3
        ... 29 more
```

and this
```
# START SCRIPT: ./bin/utils/export_generator.sh wsdl-schema
```
got stuck and wouldn't continue. So had to abort it.

**Pull request merged**
