### PR TITLE
[cwiki] Path parameter generation fix for split rows

### PR DESCRIPTION
**Pull request by Jakesterwars**
Using the cwiki documentation generator will create the path parameters table correctly except for each row after the initial will be spit up. This is due to where the mustache template is placing the header for the path parameters.

Example json spec:
`{
  "openapi": "3.0.0",
  "info": {
    "title": "test",
    "version": "1.0",
    "description": "test",
    "contact": {
      "name": "asd",
      "url": "asd",
      "email": "asd@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "tags": [
    {
      "name": "test"
    }
  ],
  "paths": {
    "/test/{id}/{testing}/{pathing}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "id",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "testing",
          "in": "path",
          "required": true
        },
        {
          "schema": {
            "type": "string"
          },
          "name": "pathing",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "operationId": "testPathing",
        "description": "asd"
      }
    }
  },
  "components": {
    "schemas": {}
  }
}`

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by Jakesterwars** [comment]
I'm getting some cache issues on build preventing me from progressing.

**Comment by Jakesterwars** [comment]
@jhitchcock

**Comment by Jakesterwars** [comment]
@wing328 Sorry for the ping, but this error is happening on not just mine or but other PRs. Do you possible know of a fix or did we by chance mess something up in our clone?

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by Jakesterwars** [comment]
Thanks for letting me know. I forgot I changed over my account name and such after I did this PR. I'll fix it when I can soon.

**Comment by wing328** [comment]
@Jakesterwars thanks for the PR, which has been merged into master.

**Pull request merged**
