### PR TITLE
Fix test on Windows

### PR DESCRIPTION
**Pull request by devhl-labs**
Fixes https://github.com/OpenAPITools/openapi-generator/issues/19924

@joscha Pinging author of these tests for awareness

Here are the logs produced by ./mvnw clean package

[ERROR] Failures:
[ERROR] org.openapitools.codegen.DefaultCodegenTest.testExecutePostProcessor
[ERROR]   Run 1: DefaultCodegenTest.testExecutePostProcessor:755 expected [true] but found [false]
[ERROR]   Run 2: DefaultCodegenTest.testExecutePostProcessor:755 expected [true] but found [false]
[ERROR]   Run 3: DefaultCodegenTest.testExecutePostProcessor:755 expected [true] but found [false]
[INFO]
[INFO]
[ERROR] Tests run: 3214, Failures: 1, Errors: 0, Skipped: 4

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by joscha** [comment]
Can we find an execution that works for both windows and *nix or add an if/else in the test for the system instead of commenting it out?

**Comment by devhl-labs** [comment]
I don't expect to troubleshoot this anytime soon but if you want to send a pr ill tell you if it works for me. Otherwise we should comment it out until we fix it.

**Comment by joscha** [comment]
Can you execute the commands behind call 2 and 3 on Windows and let me know what they yield, please? I do not have access to Windows unfortunately.

Agree with the CI step on Windows. I was under the impression this is something we do already.

**Comment by devhl-labs** [comment]
They are all false.
image

**Comment by joscha** [comment]
Is there no `echo` on modern windows anymore maybe? I think this needs Windows to debug it.

**Comment by wing328** [comment]
@devhl-labs are you using JDK 21 (which is not tested as part of the workflow since -DskipTests is required at the moment to build the project under JDK21)?

**Comment by wing328** [comment]
We do have workflow to test on windows: https://github.com/OpenAPITools/openapi-generator/blob/master/.github/workflows/windows.yaml

`mvn clean pacakge` also works fine in my Windows box (JDK17)

**Comment by devhl-labs** [comment]
I fixed it

**Review by joscha — APPROVED** [review]
Thank you.

**Pull request merged**
