### PR TITLE
Make release script cross-compatible between Mac and Linux

### PR DESCRIPTION
**Pull request by cbornet**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

I tested on Linux. Can someone test on Mac ?

### CODE REVIEW

**Comment by jmini** [comment]
Tested on mac. Ok for me.

**Comment by jmini** [comment]
@cbornet: thank you for your fix and thank you for having merged this.

This project is using "Squash and merge" policy: https://github.com/OpenAPITools/openapi-generator/wiki/Pull-Request-Checklist#merge-the-pull-request. Try to use this option next time.

**Comment by cbornet** [comment]
There's only one commit. Why should I squash ?

**Comment by cbornet** [comment]
No, I mean when there's a single commit in a PR a simple merge is exactly the same as a "squash and merge"

**Comment by cbornet** [comment]
Or is it because "squash and merge" adds the PR number in the commit title ? Then I understand the value and I'll use it for sure next time.

**Pull request merged**
