### PR TITLE
[ruby] Make File Downloads Threadsafe

### PR DESCRIPTION
**Pull request by dawson-conway**
https://github.com/OpenAPITools/openapi-generator/issues/16796

This makes the ApiClient threadsafe in ruby. I definitely need help testing this and following the process.

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by dawson-conway** [comment]
@cliffano (2017/07) @zlx (2017/09) @autopp (2019/02)

**Comment by wing328** [comment]
please update the samples so that the CI can verify the change:

https://github.com/OpenAPITools/openapi-generator/actions/runs/6577707103/job/17937746453?pr=16876

let me know if you need any help.

**Comment by wing328** [comment]
the change looks good.

about testing the file download, can you please PM me via Slack when you've time?

**Comment by wing328** [comment]
circleci failure not related to this change

**Comment by wing328** [comment]
FYI https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/echo_api/python/test/test_manual.py#L110 is how we test it in the Python Echo API client.

We need to add a similar test for the Ruby client.

**Pull request merged**
