### PR TITLE
[Spring] openapi-generator generates an incorrect stub for types named "Resource"

### PR DESCRIPTION
**Pull request by jburgess**
This fixes https://github.com/OpenAPITools/openapi-generator/issues/1680 and https://github.com/OpenAPITools/openapi-generator/issues/1888. It is based on work by @ErikGrimes. 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

### CODE REVIEW

**Comment by jburgess** [comment]
@wing328 Any help on this? The circleci fails with UNCOMMITTED CHANGES ERROR. I have run  `./bin/utils/ensure-up-to-date --batch` before commit `a0e4207` and the  output reported clean: Git working tree is clean . Any ideas on how to fix this? I would like to get this into `4.3.1`

**Comment by wing328** [comment]
@jburgess I'll take a look tomorrow instead as it's pretty late here...

**Comment by wing328** [comment]
I've updated the samples via https://github.com/OpenAPITools/openapi-generator/pull/5855/commits/179136f2267d61fd9d02973ee6092514059b1636.

Restarted all the CI jobs. Let's see how it goes.

(there was a github outage earlier causing the build to fail)

**Comment by jburgess** [comment]
@wing328 Thank you for all of your help on this! I was hesitant to update and commit the samples based on guidance in the update scripts.

**Comment by jburgess** [comment]
Any help on getting this reviewed and into `4.3.1`?

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

@wing328

**Comment by Frontrider** [comment]
This is the one issue we have right now. When can we expect it to be fixed?

**Comment by maddingo** [comment]
Unfortunately, this fix didn't make it into 4.3.1. I tried to resolve the merge conflicts, but gave up. There are a lot og changes that apply to the documentation. And then some in the PHP code/tests. Since this bug only concerns Spring, is it really necessary to add code for other languages as well?

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/8178

**Pull request closed without merging**
