### PR TITLE
[typescript-fetch] add bearer token support

### PR DESCRIPTION
**Pull request by ken210**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This PR is a follow-up of https://github.com/OpenAPITools/openapi-generator/pull/3090
Unfortunately I messed up that branch's history, so I opened another PR including the changes suggested by @macjohnny and @wing328 

This PR aims to add support for Bearer authentication token to typescript-fetch generator.
This PR is inspired by: https://github.com/mrvdot/openapi-generator/commit/82f409cd24c1a1ef621eb7cad46beaa316f7e955

### CODE REVIEW

**Comment by ken210** [comment]
CC: @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @nicokoenig @topce

**Comment by macjohnny** [comment]
please perform the following steps to generate up-to-date samples:
* merge most recent master into your branch
* `mvn clean`
* `mvn package`
* `bin/typescript-fetch-petstore-all.sh`

**Comment by ken210** [comment]
@macjohnny Thank you for your prompt review.

I performed all the steps you asked the pushed the branch again.

Thanks.

**Comment by macjohnny** [comment]
@mrvdot your change https://github.com/mrvdot/openapi-generator/commit/82f409cd24c1a1ef621eb7cad46beaa316f7e955 will be available in the official openapi generator release.

**Comment by macjohnny** [comment]
@wing328 can you trigger the CI tests again?

**Comment by wing328** [comment]
The CircleCI error is not related to this PR. I'm working on a fix for that (Go generator)

**Comment by wing328** [comment]
Thanks again for the PR, which has been included in the v4.0.2 release: https://twitter.com/oas_generator/status/1141610197766426626

**Comment by macjohnny** [comment]
@romansattler would you like to file a pr to fix this?

**Comment by hello-brsd** [comment]
I fixed it in #3323

**Pull request merged**
