### PR TITLE
[Kotlin][Multiplatform] Add missing JVM dependency

### PR DESCRIPTION
**Pull request by krzema12**
This dependency was accidentally removed in PR #9755 where we switched
from `build.gradle` to `build.gradle.kts`.

Symptom of this dependency missing (not making this change):

```
12:28:25.021 [DefaultDispatcher-worker-6] ERROR Application - Unhandled: GET - <redacted>
java.lang.ExceptionInInitializerError: null
        at com.dynatrace.teamsmanager.infrastructure.ApiClient$client$2.invoke(ApiClient.kt:38)
...
Caused by: java.lang.IllegalStateException: Failed to find HTTP client engine implementation in the classpath: consider adding client engine dependency. See https://ktor.io/clients/http-client/engines.html
        at io.ktor.client.HttpClientJvmKt.<clinit>(HttpClientJvm.kt:42)
```

which contains a clear message hinting what's wrong.

----

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Technical committee:
@jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

People working on the previous change (#9755):
@837 @wing328

### CODE REVIEW

**Comment by 4brunu** [comment]
Actually comparing the two files, it seems that there are a lot of missing dependencies.
Is this the only one that is missing?

**Comment by krzema12** [comment]
@4brunu good point. However I have a possibility to test only the JVM target in the multiplatform project, hence I'm limiting the changes to what I can test. It's the most popular target, so IMO it still make sense to make this simple change and tackle others later.

**Comment by 4brunu** [comment]
Could you please add the remaining one's without testing?

**Comment by krzema12** [comment]
I checked the dependencies and in fact nothing more seems to be missing. One may think that e.g. `implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-js:$coroutines_version"` is missing from `jsMain`, however in the newer versions of Gradle and Kotlin, it's enough to specify `implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$coroutines_version"` in `commonMain` and it will automatically add dependencies on platform-specific libraries. It's also why `implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutines_version"` is not needed for `jvmMain`.

**Comment by 4brunu** [comment]
@837 @DevSrSouza could you please help to review this PR?
Is there any more missing dependencies for other targets?
Thanks

**Comment by 4brunu** [comment]
Thanks 👍

**Pull request merged**
