### PR TITLE
Updated README.mustache template for the Erlang server generator

### PR DESCRIPTION
**Pull request by iri**
Code not changed.

Changes made to the Erlang server generator's user instruction template ("README.mustache" file):

1. Corrected the argument in section 4.1 of the user instructions (number 4.1 is from the old version of the "README.mustache" file).
Second argument of openapi_server:start/2, for the generated Erlang code must now be in a different format than proposed in the instructions (see lines 13-16 of the "server.mustache" file). Initially, I tried to follow instructions but the server failed to start. I discovered that the argument format did not match the server's expectations, causing the port number not to be passed to cowboy:start_clear/3. This has now been fixed in the new version of template.

2. Reviewed and updated the text of the user instructions to remove any ambiguities.

3. Tested the user instructions for accuracy and completeness.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

please follow step 3 to update the samples as well.

cc @NelsonVides

**Comment by iri** [comment]
> please follow step 3 to update the samples as well.

I soon will do one more commit to fix markdown issue in "README.mustache". And then will regenerate the erlang-server sample again.

**Comment by NelsonVides** [comment]
It looks like a better readme than the previously available one, but maybe it's not how I'd do it, as I don't really like modifying auto-generated files. For the record, I'd leave the generated code into either a separate dependency from a separate repository, or a separate app in an umbrella repository.

Nevertheless, this is still good progress, it at least presents a tutorial that actually works, so very cool! The only thing I'd add is a notice that the modified files will be overridden next time the API is generated, so we could use the `.openapi-generator-ignore` if we want to.

**Comment by wing328** [comment]
samples updated via https://github.com/OpenAPITools/openapi-generator/pull/20138/commits/38bb4bc643ca0405b049bae2df349343d00acdf2

**Pull request merged**
