### PR TITLE
[csharp-netcore] Generic Host: Add 'this.' in front of property names in ctor of generated Models

### PR DESCRIPTION
**Pull request by justM4D**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by devhl-labs** [comment]
It's not required, so I'm not sure why we would want the this keyword before a property name. If it's just for clarity, the casing should be enough. Also, just so you're aware, I have two big PRs ready to be merged that will make big improvements, just waiting on someone to click merge.

**Comment by justM4D** [comment]
Without adding casing modifiers, the casing of the names is the same (see my command line and config in the Issue), thus VS is throwing a warning:
image

It still compiles, but the resulting objects are all nulled, since the ctor doesn't actually assign any values to the properties.


Generally properties should start with uppercase, yes, but this is what the generator gives me with a basic configuration, which should produce working code imho.

Using "this." should be unambigous and doesn't break anything, as far as I know (it's used in the Equals and GetHashCode functions as well).


I did see your big PR, but I didn't find the two changes I made, so my client code actually works, so I created my own PRs.

**Comment by devhl-labs** [comment]
The issue is not the lack of `this.` it's that the casing is wrong. I probably have that fixed in a pending PR, so lets hold this for now to avoid the conflict.

**Comment by justM4D** [comment]
Alright, I can live with a modified local template until then.

**Pull request closed without merging**
