### PR TITLE
[Slim4] Add array support to Data Mocker

### PR DESCRIPTION
**Pull request by ybelenko**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

`mockArray` method added to interface and implemented class. Mocker creates smallest arrays(single item when possible) to avoid huge JSON responses.

Related to #3545

### How to test

1. Checkout into feature branch
```shell
$ git checkout -b ybelenko-slim_data_mocker_array master
$ git pull https://github.com/ybelenko/openapi-generator.git slim_data_mocker_array
```
2. Generate new Slim4 samples and go to just created build
```shell
$ mvn clean package
$ bin/php-slim4-server-petstore.sh
$ cd samples/server/petstore/php-slim4
```
3. Start Composer installation and run unit tests
```shell
$ composer install
$ composer test
$ composer phpcs
```

cc @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @renepardon

### CODE REVIEW

**Comment by ybelenko** [comment]
I've made a small example of what do we have right now:
```php
<?php
require __DIR__ . '/vendor/autoload.php';

use OpenAPIServer\Mock\OpenApiDataMocker as Mocker;
$mocker = new Mocker();
$data = [
    'Integer from 1 to 100' => $mocker->mockInteger(null, 1, 100),
    'Float from -3 to 3' =>  $mocker->mockNumber(null, -3, 3),
    'String 10 chars' => $mocker->mockString(null, 10, 10),
    'Boolean' =>  $mocker->mockBoolean(),
    'Array of strings' => $mocker->mockArray(
        [
            'type' => 'string',
            'maxLength' => 20,
        ]
    ),
];
echo json_encode($data, JSON_PRETTY_PRINT);
```
output:
```json
{
    "Integer from 1 to 100": 89,
    "Float from -3 to 3": -1.1508,
    "String 10 chars": "Lorem ipsu",
    "Boolean": false,
    "Array of strings": [
        "Lorem ipsum dol"
    ]
}
```

**Comment by wing328** [comment]
> Start Composer installation and run unit tests

What about adding these steps to the CI tests in a separate PR?

I only saw tests for php-slim but not php-slim4 in the CI.

**Comment by ybelenko** [comment]
> > Start Composer installation and run unit tests
> 
> What about adding these steps to the CI tests in a separate PR?
> 
> I only saw tests for php-slim but not php-slim4 in the CI.

Where I should add them? I didn't know that CI runs any tests from samples.

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/server/petstore/php-slim/pom.xml is a good starting point. You will need to add a similar file for slim4 (you will need to use a different artifact ID)

then add another line similar to https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L1050 in pom.xml

**Pull request merged**
