### PR TITLE
Fix the `built` field on `--version` output

### PR DESCRIPTION
**Pull request by SalvatoreT**
The `git.build.time` field is not currently being included, so it's output is bad.

**Before**

```
openapi-generator-cli 7.2.0-SNAPSHOT
  commit : bbd0ce3
  built  : -999999999-01-01T00:00:00+18:00
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

**After**

```
openapi-generator-cli 7.2.0-SNAPSHOT
  commit : bbd0ce3
  built  : 2023-12-04T16:18:11-08:00
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

Closes https://github.com/OpenAPITools/openapi-generator/issues/17313

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by SalvatoreT** [comment]
Hey @wing328 and @spacether, this should 🤞🏼 be a quick and easy review.

**Comment by wing328** [comment]
thanks for the PR but it was removed intentionally for gradle build cache: https://github.com/OpenAPITools/openapi-generator/pull/15332

**Comment by SalvatoreT** [comment]
@wing328, can you share how to replicate the build cache issue? I updated my PR to invoke the git plugin later which might help.

**Comment by SalvatoreT** [comment]
Hey @wing328, sorry this fell off my radar. When you get a chance could you please share how to replicate the build cache issue?

🤞🏼 I think/hope moving the git plugin invocation to the `prepare-package` phase addresses the cache issue.

**Pull request closed without merging**
