### PR TITLE
Add support for dumping request and response in Go generated clients

### PR DESCRIPTION
**Pull request by dnaeon**
The following change adds a new configuration setting, which
controls whether clients want to dump the HTTP request and response.

Useful when debugging API calls and clients.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by dnaeon** [comment]
CC @antihax, @bvwells, @grokify, @kemokemo, @bkabrda

**Comment by wing328** [comment]
@dnaeon thanks for the PR. What about using a logger (e.g. https://github.com/google/logger) instead?

**Comment by dnaeon** [comment]
Hey @wing328, 

I've tested it with a logger first, but the results weren't pretty, that's why I've left it using just `fmt.Println`.

**Comment by antihax** [comment]
This should really be done with middleware, not in the client directly. Is the a reason it cant be?

**Comment by wing328** [comment]
> I've tested it with a logger first, but the results weren't pretty, that's why I've left it using just fmt.Println.

Can you please elaborate?

**Comment by wing328** [comment]
FYI. For other clients (e.g. Ruby), we also use a logger for debugging purpose.

**Comment by dnaeon** [comment]
> > I've tested it with a logger first, but the results weren't pretty, that's why I've left it using just fmt.Println.
> 
> Can you please elaborate?

@wing328 Here's one example.

https://play.golang.org/p/o5LE9R5iCpj

Basically the timestamp of the logger is attached to just the first line of the output, which makes it less pretty, IMO.

Also, I found `fmt.Println` to be less distractive for my use cases, but I can switch that over to a logger, if you think that's better.

> This should really be done with middleware, not in the client directly. Is there a reason it cant be?

@antihax That should work I guess. Can you point me to an example middleware I can lookup?

Thanks!

**Comment by antihax** [comment]
Here is an example of two chained middleware for the API client.
Setup of the chain `LimitedTransport` and `APICacheTransport`.
https://github.com/antihax/evedata/blob/master/internal/apicache/apicache.go#L50

Here are the implementations:
https://github.com/antihax/evedata/blob/master/internal/apicache/limitedTransport.go
https://github.com/antihax/evedata/blob/master/internal/apicache/transport.go#L20

You would create another of these that would dump the request, then a second to dump the response.

In the case here you would do something like this:

```
func (t *DumpTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	reqb, _ := httputil.DumpRequest(req, true)
	res, err:= t.Transport.RoundTrip(req)
	resb, _ := httputil.DumpRequest(res, true)
        ... log the request and response ...
	return res, err
}```

**Comment by wing328** [comment]
> Basically the timestamp of the logger is attached to just the first line of the output, which makes it less pretty, IMO.

What about putting a "\n" at the beginning of the log?

**Comment by dnaeon** [comment]
> Here is an example of two chained middleware for the API client.
> Setup of the chain `LimitedTransport` and `APICacheTransport`.
> https://github.com/antihax/evedata/blob/master/internal/apicache/apicache.go#L50
> 
> Here are the implementations:
> https://github.com/antihax/evedata/blob/master/internal/apicache/limitedTransport.go
> https://github.com/antihax/evedata/blob/master/internal/apicache/transport.go#L20
> 
> You would create another of these that would dump the request and response.
> 
> In the case here you would do something like this:
> 
> ```
> func (t *DumpTransport) RoundTrip(req *http.Request) (*http.Response, error) {
> 	reqb, _ := httputil.DumpRequest(req, true)
> 	res, err:= t.Transport.RoundTrip(req)
> 	resb, _ := httputil.DumpResponse(res, true)
>         ... log the request and response ...
> 	return res, err
> }
> ```

@antihax Thanks, that would work.


> > Basically the timestamp of the logger is attached to just the first line of the output, which makes it less pretty, IMO.
> 
> What about putting a "\n" at the beginning of the log?

@antihax, @wing328 I'll leave it to you whether it's worth merging this PR considering that we can have the same thing done with either a middleware or custom transport.

**Comment by wing328** [comment]
@dnaeon the debug flag in other clients can be used not only for dumping request/response but also other troubleshooting (e.g. object serialization, etc).

so if you're using a logger with the debug flag, I'll be happy to merge this into master.

**Comment by dnaeon** [comment]
> @dnaeon the debug flag in other clients can be used not only for dumping request/response but also other troubleshooting (e.g. object serialization, etc).
> 
> so if you're using a logger with the debug flag, I'll be happy to merge this into master.

@wing328, I can take care of updating the PR.

Which logger you'd prefer to have as part of the implementation?

https://github.com/google/logger or the builtin `log.Logger`?

**Comment by wing328** [comment]
Please start with the built-in one. Thanks


在 2019年11月23日週六 下午3:49，Marin Atanasov Nikolov <notifications@github.com> 寫道：

**Comment by dnaeon** [comment]
@wing328 just pushed a new commit which uses `log.Logger`.

**Comment by wing328** [comment]
@dnaeon thanks for the PR, which looks good to me.

**Comment by wing328** [comment]
@dnaeon when you've time, I wonder if you can file the same PR for `go-experimental` generator as well. Thank you.

**Comment by dnaeon** [comment]
@wing328 Sure, here it is #4649

**Pull request merged**
