### PR TITLE
[ci] Build kotlin samples via github

### PR DESCRIPTION
**Pull request by kuhnroyal**
First try to run Kotlin samples via Github.
- [ ] `kotlin-json-request-string` now seems to require Android to be build
- [ ] `kotlin-multiplatform` has no `test` task so it doesn't work with the current matrix

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@kuhnroyal thanks for the PR.

For the following:
```
 kotlin-json-request-string now seems to require Android to be build
 kotlin-multiplatform has no test task so it doesn't work with the current matrix
```

Let's comment out them out for the time being.

**Comment by kuhnroyal** [comment]
What about the kotlin tests in `samples/openapi3/client`?

**Comment by kuhnroyal** [comment]
@wing328 This should be good for now, there are some python failures on master.
Should we remove the maven profile for these kotlin samples?

**Comment by wing328** [comment]
Travis CI not related to this change.

I'll review and clean up the pom.xml later. Thanks for the PR 👍

**Pull request merged**
