### PR TITLE
[kotlin-spring] add support for the delegate pattern

### LINKED ISSUE #2526: [REQ] Kotlin Spring Server Generator: adopt the pattern used by Java Spring Server generator
Currently, the Kotlin Spring Server generator produces a Controller that calls a 'delegate' service. The controller code assumes that the delegate service will either return successfully, OR throw an exception. 

This means no custom validation of input or pre-processing can be performed in the Controller class, AND that the service MUST use exception handling for all error situations.

The Java Spring server generator creates a Controller interface that has an `_` prefixed method for the RequestMapping and parameter annotations and then calls a method that has a default implementation. This method makes no assumptions about the result as it returns a ResponseEntity.

The server code then inherits the interface, and overrides the method. This allows the Controller to do request data validation and formatting as well as not be forced to use Exceptions for error handling.

@dr4ke616 Would you be open to an update to the Kotlin spring Server generator that utilizes this pattern rather than the existing one?

It obviously would be a breaking change for anyone using the generator now.

If not, then I'll have to decide if I submit a new one, or merely create a custom one, or continue using the Java one. Don't like the latter option as it means I don't get the benefit of nullability being properly generated in model objects and Controller functions.

### PR DESCRIPTION
**Pull request by massimosiani**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

Fixes #2526 by introducing the delegatePattern option. The resulting output is the kotlin version of the Java code. Please notice that the reactive option is not supported yet, as I'm not confident with coroutines.

No drawback compatibility issue should arise.

cc @dr4ke616.

### CODE REVIEW

**Comment by massimosiani** [comment]
Hi!
Can I do anything for this PR?

**Comment by wing328** [comment]
cc Kotlin tech committee: @jimschubert (2017/09), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04)
--

**Comment by wing328** [comment]
@massimosiani thanks for the PR and sorry for taking so long to review as there are too many PRs submitted for this project.

I tested the new feature with petstore but got the following errors:
```
➜  kotlin-springboot gradle build

> Task :compileKotlin FAILED
e: /private/tmp/samples/server/petstore/kotlin-springboot/src/main/kotlin/org/openapitools/api/PetApi.kt: (187, 68): Type mismatch: inferred type is Resource? but MultipartFile was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
1 actionable task: 1 executed

```

Does it work for you locally in your machine?

**Comment by massimosiani** [comment]
Hi @wing328, I fully understand and please forgive me, I forgot to thank you for your amazing work.

The code works in a project of mine, I'll check it against the petstore example very soon and come back to you.

**Comment by massimosiani** [comment]
@wing328 I just rebased on master and everything was fine. Here you are my versions:

$ gradle -v

------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_232 (Eclipse OpenJ9 openj9-0.17.0)
OS:           Mac OS X 10.15.1 x86_64

Anything wrong?
I see that Shippable is failing with a weird error, is it anything on my side?
Thanks.

**Comment by wing328** [comment]
Restarted the shippable job. Let's see how it goes.

**Comment by wing328** [comment]
I did a test with petstore spec but got the following errors when compiling the code:
```
[ERROR] /private/tmp/kotlin-spring2/src/main/kotlin/org/openapitools/api/PetApi.kt: (125, 68) Type mismatch: inferred type is Resource? but MultipartFile was expected
[ERROR] /private/tmp/kotlin-spring2/src/main/kotlin/org/openapitools/api/PetApiDelegate.kt: (5, 8) Unresolved reference: io
[ERROR] /private/tmp/kotlin-spring2/src/main/kotlin/org/openapitools/api/StoreApiDelegate.kt: (4, 8) Unresolved reference: io
[ERROR] /private/tmp/kotlin-spring2/src/main/kotlin/org/openapitools/api/UserApiDelegate.kt: (4, 8) Unresolved reference: io
```

Does it work for you locally?

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g kotlin-spring -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -o /tmp/kotlin-spring2/ --additional-properties delegatePattern=true
```

**Comment by massimosiani** [comment]
@wing328 you were right, I should have checked more carefully. I checked that the generated code now compiles.
However, the generated project does not start, but this is another problem that I think should be fixed in a separate PR.

**Comment by wing328** [comment]
@massimosiani no worry. I'll give it another try tomorrow and merge if no issue found.

Agreed with filing a separate PR for another issue.

**Comment by wing328** [comment]
Tested again and no longer encounter the issue. Thanks for the enhancement

**Comment by wing328** [comment]
@massimosiani thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Pull request merged**
