### PR TITLE
[Dart] generate from complex schema, class and field name sanitation 

### LINKED ISSUE #7588: [Dart] Use resources/3_0/petstore.yaml in dart2 generators
Simple as that, move dart generators to use more complex schema from openapi 3.0.
New files are more complex and expose new bugs in Dart.

### PR DESCRIPTION
**Pull request by agilob**
### PR checklist
1. Generate code from more complex schema
2. Delete samples that were used before previous input schema (2 and 3 versions ago)

Current sample produces code that doesn't compile, but at least it gives us a target and exposes issues directly

Closes #7588

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by agilob** [comment]
@noordawod the code generated in `samples/client/petstore/dart2/petstore_client_lib_fake_endpoints/`  is quite complex and it sets new target for dart-openapi compatibility. The code currently doesn't compile, so at least we know what's next to do in dart generator :)

**Comment by noordawod** [comment]
@agilob let me know if you need some help ;)

**Comment by agilob** [comment]
circle ci doesnt use docker images?

```
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packagecloud.io trusty InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4E6910DFCB68C9CD

W: Failed to fetch https://packagecloud.io/circleci/trusty/ubuntu/dists/trusty/InRelease  

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  dart
0 upgraded```

**Comment by noordawod** [comment]
No idea...

**Comment by noordawod** [comment]
@agilob 
What I found from previous experience with CircleCI is that it barfs occasionally without any particular reason. So I suggest you to try rerunning the build. This is true also for other projects that I run on CircleCI.

**Comment by wing328** [comment]
I think you will need to move `samples/client/petstore/dart2/petstore/pom.xml` to the new location instead of deleting it.

**Comment by wing328** [comment]
One more thing: please update pom.xml and replace the old dart petstore location with the new one.

**Comment by agilob** [comment]
done

**Comment by wing328** [comment]
Looks like there are some issues with the dart2 petstore client as reported by the CirclecCI (partial result below):
```
  lib/api/another_fake_api.dart:28:30: Error: Expected '{' before this.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                               ^^^^^^^^^^^^^^^^^^^^^^^
  lib/api/another_fake_api.dart:28:29: Error: Operator '%' should have exactly one parameter.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                              ^
  lib/api/another_fake_api.dart:79:3: Error: A method declaration needs an explicit list of parameters.
  Try adding a parameter list to the method declaration.
    Future<Client> 123test@$%SpecialTags(Client client) async {
    ^^^^^^
01:32 +0 -56: loading test/tag_test.dart [E]                                                                                                                                                           
  Failed to load "test/tag_test.dart":
  Unable to spawn isolate: lib/api/another_fake_api.dart:28:3: Error: A method declaration needs an explicit list of parameters.
  Try adding a parameter list to the method declaration.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
    ^^^^^^
  lib/api/another_fake_api.dart:28:20: Error: Expected '{' before this.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                     ^^^
  lib/api/another_fake_api.dart:28:20: Error: Expected a class member, but got '123'.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                     ^^^
  lib/api/another_fake_api.dart:28:23: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
  Try adding the name of the type of the variable or the keyword 'var'.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                        ^^^^
  lib/api/another_fake_api.dart:28:23: Error: Expected ';' after this.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                        ^^^^
  lib/api/another_fake_api.dart:28:29: Error: Operator declarations must be preceded by the keyword 'operator'.
  Try adding the keyword 'operator'.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                              ^
  lib/api/another_fake_api.dart:28:29: Error: A method declaration needs an explicit list of parameters.
  Try adding a parameter list to the method declaration.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                              ^
  lib/api/another_fake_api.dart:28:30: Error: Expected '{' before this.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                               ^^^^^^^^^^^^^^^^^^^^^^^
  lib/api/another_fake_api.dart:28:29: Error: Operator '%' should have exactly one parameter.
    Future<Response> 123test@$%SpecialTagsWithHttpInfo(Client client) async {
                              ^
  lib/api/another_fake_api.dart:79:3: Error: A method declaration needs an explicit list of parameters.
  Try adding a parameter list to the method declaration.
    Future<Client> 123test@$%SpecialTags(Client client) async {
    ^^^^^^
01:32 +0 -56: Some tests failed.                                                                                                                                                                       
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (pub-test) on project Dart2PetstoreClientTests: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :Dart2PetstoreClientTests
```

Ref: https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/6672/workflows/43411d7e-0154-48ac-94c1-42c137e74f3e/jobs/20138

**Comment by agilob** [comment]
It required dart names to be sanitized as names cant start with number and contain special charts. Added code for that. Complex dart code still doesnt compile well as the spec contains classes that are dart-code classes like Map and List. I've handled List but run of time today to take care of Map<>

**Comment by agilob** [comment]
@wing328 pls

**Comment by wing328** [comment]
Sorry we were busy with the v5.0.0-beta3 release before. Can you please ping me via Slack when you've time as I still see some issues with the Dart clients in the CI?

**Comment by kuhnroyal** [comment]
I just saw this PR, I have some similar work done here https://github.com/kuhnroyal/openapi-generator/tree/feature/dart/advanced, trying to reuse `specialCharReplacements` from `DefaultCodegen` and also escaping variable names, operationIds and so on. Maybe you can take a look and see if we can merge efforts.

**Comment by agilob** [comment]
> Maybe you can take a look and see if we can merge efforts.

Can you open a PR from my branch targeting my branch?

**Comment by kuhnroyal** [comment]
It currently seems unrealistic to generate the full fake-api for both dart and dart-dio, there are just way to many compile errors. I have solved most but the branch just gets way too big.
Instead I took a step back and started with the simple petstore example and did some cleanup. I think this is a better baseline for complex schema support.
See https://github.com/OpenAPITools/openapi-generator/pull/8085

**Comment by noordawod** [comment]
Nice changes @agilob !

**Comment by agilob** [comment]
Hopefully all tests pass now and we can stop duplicating efforts on the same problems.

**Comment by kuhnroyal** [comment]
I really doubt it, the whole dart package doesn't compile. Your integration tests fail with several compile errors.
besides that you have deleted all the existing integration tests from `samples/client/petstore/dart2/petstore/test/..`. They were not empty but actually contained non-generated integration tests.

**Comment by agilob** [comment]
>I really doubt it

You doubt that this will prevent people duplicating efforts or tests will pass?

When the tests fail, it's a good place to start if you want to help pushing this forward. In this moment it's a positive sign when something new breaks, means previous problem has been fixed and we're heading toward another detail of specification to implement. I purposely chosen the most complex spec file so it can highlight all problems and instead caring about whitespaces or variable name in generated code, contributors can pick up the next failing thing.

If you don't want to help, we can always make a few incompatible versions of this generator. Of course everybody wins in that case.

**Comment by kuhnroyal** [comment]
I have spent the better part of this and last week on getting this to work. I have a lot of it solved but the PR is gonna get so big that nobody can actually review it. I suggest to start small with the basic 3.0 petstore example. This already doesn't compile so its a good start to get that working and then iterate on.

Afterwards we can iterate on the fake-api without adding the integration tests to the master POM, as long as no existing tests for the simple petstore break this should be fine.

**Comment by agilob** [comment]
> have spent the better part of this and last week on getting this to work

Why havent you committed any fixes?

**Comment by kuhnroyal** [comment]
I linked you one of my branches here: https://github.com/kuhnroyal/openapi-generator/tree/feature/dart/advanced
It already fixes escaping, naming clashes, decimal support, int/double based enums, set support and there is still so much to go that I stopped and took a step back to start with the smaller version and then cherrypick small bits.

**Comment by agilob** [comment]
Cool, looks like you're ahead of this branch :)

**Pull request closed without merging**
