### PR TITLE
[cpp-qt-client] Fix CMakeLists.txt.mustache and CMakeLists.txt for Qt5 (fix #17712)

### LINKED ISSUE #17712: [BUG] [cpp-qt] Unable to run cmake and use Qt5 anymore
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am unable to run the generator after updating to a newer version (7.2.0) and using Qt5. I didn't change anything about my Qt installation, just the openapi-generator version, and ran into failures. (I also upgraded CMake just to be sure).

I set CMAKE_PREFIX_PATH before running like this (to set my Qt version):

```
export CMAKE_PREFIX_PATH=C:\\Qt\\5.15.16\\msvc2019_64\\lib\\cmake
cmake  ../src/client/
```

I get this:

```
-- Building for: Visual Studio 17 2022
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Selecting Windows SDK version 10.0.20348.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.38.33134.0
-- The CXX compiler identification is MSVC 19.38.33134.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) at CMakeLists.txt:5 (find_package):
  Policy CMP0084 is not set: The FindQt module does not exist for
  find_package().  Run "cmake --help-policy CMP0084" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Qt3 (missing: QT_QT_LIBRARY QT_INCLUDE_DIR
  QT_MOC_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindQt3.cmake:213 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/Program Files/CMake/share/cmake-3.28/Modules/FindQt.cmake:160 (include)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!

```

If I add `find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core Network Gui)` back in, all works fine and generates

@MartinDelille do you remember why in https://github.com/OpenAPITools/openapi-generator/pull/14968 this line was removed?

### PR DESCRIPTION
**Pull request by MartinDelille**
I put back find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core Network Gui) although I'm not sure it is needed.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by xconverge** [comment]
LGTM

https://doc.qt.io/qt-6/cmake-qt5-and-qt6-compatibility.html#supporting-older-qt-5-versions

```
Here we let find_package(<PackageName>...) try to find first Qt 6, and if that fails Qt 5, under the name QT. If either of them is found, find_package will succeed, and the CMake variable QT_VERSION_MAJOR will be defined to either 5 or 6.
```

I think it is necessary, I dont have QT_VERSION_MAJOR set anywhere else in my environment so it needs to get somehow (or have instructions to set it)

**Comment by xconverge** [comment]
I wonder if `set(CMAKE_AUTOMOC ON)` is also needed? Did you compile this and actually link to the client? I had issues doing that (the linking to it portion).

https://cmake.org/cmake/help/latest/prop_tgt/AUTOMOC.html

I am just scanning https://github.com/OpenAPITools/openapi-generator/pull/14968/files#diff-2d2195b5a09c4d07e171b27db4b8d42b9969ce158c5458afa2118c2e9db44bed for changes

**Comment by MartinDelille** [comment]
No I indeed have linker error locally. What I don't understand is why do we need to require Qt in the client since we do it in the consumer [CMakeLists.txt](https://github.com/OpenAPITools/openapi-generator/pull/14968/files#diff-86e77485416e3a39fa2bc1054040ce6e4472c828faeadcff573f10de5716ac77R8). Isn't it a problem to add it two times ? I admit I have limitation regarding best cmake practice here.

**Comment by xconverge** [comment]
I don't think it is a problem because we are dynamic linking and automoc should just fix it. It worked for me for months before 🤷‍♂️

**Comment by MartinDelille** [comment]
I restored `set(CMAKE_AUTOMOC ON)` but I still have unlink issue locally with Qt5:

```java
ld: Undefined symbols:
  qt_qFindChildren_helper(QObject const*, QString const&, QMetaObject const&, QList<void*>*, QFlags<Qt::FindChildOption>), referenced from:
      QList<test_namespace::PFXHttpRequestWorker*> QObject::findChildren<test_namespace::PFXHttpRequestWorker*>(QString const&, QFlags<Qt::FindChildOption>) const in libCppQtPetstoreClient.a[10](PFXPetApi.cpp.o)
  qHash(QJsonObject const&, unsigned int), referenced from:
      test_namespace::qHash(test_namespace::PFXObject const&, unsigned int) in libCppQtPetstoreClient.a[10](PFXPetApi.cpp.o)
  qHash(QString const&, unsigned int), referenced from:
      QHash<QString, QHashDummyValue>::findNode(QString const&, unsigned int*) const in libCppQtPetstoreClient.a[10](PFXPetApi.cpp.o)
  QArrayData::deallocate(QArrayData*, unsigned long, unsigned long), referenced from:
      QTypedArrayData<unsigned short>::deallocate(QArrayData*) in main.cpp.o
      QTypedArrayData<char>::deallocate(QArrayData*) in PetApiTests.cpp.o
  QArrayData::shared_null, referenced from:
      QArrayData::sharedNull() in PetApiTests.cpp.o
  QByteArray::fromBase64(QByteArray const&), referenced from:
      test_namespace::fromJsonValue(QByteArray&, QJsonValue const&) in libCppQtPetstoreClient.a[14](PFXHelpers.cpp.o)
  QByteArray::reallocData(unsigned int, QFlags<QArrayData::AllocationOption>), referenced from:
      QByteArray::reserve(int) in PetApiTests.cpp.o
      QByteArray::detach() in libCppQtPetstoreClient.a[16](PFXHttpFileElement.cpp.o)
  QByteArray::clear(), referenced from:
      test_namespace::fromStringValue(QString const&, QByteArray&) in libCppQtPetstoreClient.a[14](PFXHelpers.cpp.o)
      test_namespace::PFXHttpRequestWorker::execute(test_namespace::PFXHttpRequestInput*) in libCppQtPetstoreClient.a[15](PFXHttpRequest.cpp.o)
...
```

**Comment by wing328** [comment]
let's give it a try and include this in the v7.3.0 release

**Pull request merged**
