### PR TITLE
[PHP] Add gitignore to AbstractPhpCodegen

### PR DESCRIPTION
**Pull request by ybelenko**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

After conversation with @ackintosh we've agreed that we need to remove PHP related rules from root `.gitignore`. All PHP codegens should produce own `.gitignore` by default.

What I did:
1. Added `.gitignore` to supportingFiles in `AbstractPhpCodegen`
2. Grabbed minimal `.gitignore` for each PHP codegen from this [repo](https://github.com/github/gitignore)
3. Noticed broken path in Silex security script. Check 27fb8ba
4. Added few rules from root `.gitignore` to local Symfony `.gitignore`. Check a20e201

About `composer.lock`. I think, it does make sense to commit `composer.lock` in server implementations and do opposite in client SDK.

This PR is big and serious, so I can wait while all PHP codegens will be properly checked.

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh

### CODE REVIEW

**Comment by wing328** [comment]
Shippable CI reports the following issue:
```
 ./bin/utils/ensure-up-to-date
# START SCRIPT: ./bin/utils/ensure-up-to-date
IMPORTANT: this script should be run by the CI (e.g. Shippable) to ensure that the 'samples/' folder is up to date.
Please press CTRL+C to stop or the script will continue in 5 seconds.
UNCOMMITTED CHANGES ERROR
There are uncommitted changes in working tree after execution of 'bin/ensure-up-to-date'
Perform git diff
Perform git status
HEAD detached from FETCH_HEAD
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	samples/openapi3/client/petstore/php/OpenAPIClient-php/.gitignore

nothing added to commit but untracked files present (use "git add" to track)
Please run 'bin/utils/ensure-up-to-date' locally and commit changes (UNCOMMITTED CHANGES ERROR)

```

Please run `./bin/utils/ensure-up-to-date` and use `git add samples/openapi3/client/petstore/php/OpenAPIClient-php/.gitignore` to add the new files.

**Comment by ybelenko** [comment]
@wing328 Done. But I think we need to wait response from another PHP collaborators.

**Comment by wing328** [comment]
As discussed, I suggested adding a "Ref" to give credit the "source", e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/R/.gitignore#L1

**Comment by wing328** [comment]
If no one has further feedback, I'll merge this PR into master tomorrow (Friday)

**Pull request merged**
