### PR TITLE
#1506 Bump Zone.js to remove warnings when using angular >=6.

### LINKED ISSUE #1506: [typescript-angular] outdated zone.js@^0.7.6 peer dependency
##### Description

Using the generated client for a new angular 6 application will lead into this warning:
```
npm WARN my.lib requires a peer of zone.js@^0.7.6 but none is installed. You must install peer dependencies yourself.
```

##### openapi-generator version

3.3.3

##### Command line used for generation

```
java -jar openapi-generator.jar generate \
                    --skip-validate-spec \
                    --input-spec XXXX  \
                    --generator-name typescript-angular \
                    --output YYY \
                    --invoker-package ZZZ \
                    --additional-properties snapshot=false \
                    --additional-properties supportsES6=true \
                    --additional-properties modelPropertyNaming=camelCase \
                    --additional-properties ngVersion=6.1.1 \
                    --additional-properties withInterfaces=true \
                    --additional-properties providedInRoot=true \
                    --additional-properties useRxJS6=true
```

##### Suggest a fix/enhancement

I tried the generated client using Zone.js 0.8.26 and so far everything works fine. But I don't know the internals of it and when zone.js is really used. So I can't suggest a blind update to 0.8.xx. Furthermore I haven't found any compatibility notes between 0.7.xx and 0.8.xx.

### PR DESCRIPTION
**Pull request by d0x**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)
### Description of the PR

Fixed #1506 . Bump Zone.js peer dependency. Angular 6 and 7 is using Zone.js 0.8.26. I tested zone.js 0.8.26 in our environment with Angular 6.

Since it shouldn't break anything, the current master branch is correct, or?

@Committee: I used the syntax  `^0.7.6 || ^0.8.26` to support a wider range of angular versions. What do you think about this?

And why `./bin/typescript-angular-petstore-all.sh` doesn't put this syntax into the generated package.jsons?

### CODE REVIEW

**Comment by macjohnny** [comment]
I think the zone.js dependency could be removed from the `peerDependencies`, since it will be included in angular projects anyway.

**Comment by d0x** [comment]
@macjohnny ok, what do you suggest?

Should I remove the zonejs dependencies since we already depend on `angular/http`?

And regarding the change on angular2/4 samples, what should I do there? I just regenerated all the angular samples with `^0.7.6 || ^0.8.26`. That shouldn't be a problem for angular2/4. Do you agree? We don't have a switch to deliver different templates for different angular versions.
image

**Comment by macjohnny** [comment]
@d0x I suggest to remove the `peerDependency` on `zone.js`. Concerning the 2/4 compatibility, I think `^0.7.6 || ^0.8.26` is a good option, as the dependency will be given by angular anyway, so npm will find the zone.js version that matches all constraints

**Comment by d0x** [comment]
Ok, I think we have it then.

I removed it and regenerated the templates.

**Comment by wing328** [comment]
@d0x thanks for the PR, which has been included in the v3.3.4 release: https://twitter.com/oas_generator/status/1068772409795207168

**Pull request merged**
