### PR TITLE
[R client] Use %f instead of %d in sprintf format for numerics

### PR DESCRIPTION
**Pull request by bmordue**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This is a small fix for JSON serialization using `sprintf` of 'numeric' types in R that is already in `swagger-codegen`: 
Relevant issue: https://github.com/swagger-api/swagger-codegen/issues/8531

cc @andypetrella

Note: running the sample generation script `./bin/openapi3/r-petstore.sh` has added new files.

### CODE REVIEW

**Comment by bmordue** [comment]
Hmm. This PR passed 3/4 checks: Shippable failed with some kind of build error unrelated to this change.
I force-pushed the same file changes, but with an edited commit message, just to retrigger the build checks. (It looks like I can't manually retrigger a failed job on Shippable or CircleCI without repo write access).
Second time, 3/4 checks passed: CircleCI failed this time, again I believe unrelated to my change.

So all 4 checks have passed for this PR, but not at the same time.

**Comment by bmordue** [comment]
@wing328 any thoughts about the failing build (timed out)?

**Comment by wing328** [comment]
@bmordue there's a merged PR improving R's model: https://github.com/OpenAPITools/openapi-generator/pull/3099

Please check it out.


```
             {{#isNumeric}}[%d]{{/isNumeric}}{{^isNumeric}}[%s]{{/isNumeric}}{{#hasMore}},{{/hasMore}}
```

I think we need to keep %d for integer and long using for example `{{#isInteger}} ... {{/isInteger}}`

**Comment by bmordue** [comment]
@wing328 That's great, thanks for pointing that out.

**Pull request closed without merging**
