### PR TITLE
Support for discriminator.mapping

### PR DESCRIPTION
**Pull request by 0v1se**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Basic support for discriminator.mapping and support for jackson generator for polymorphic types with custom mapping.

### CODE REVIEW

**Comment by jmini** [comment]
Thank you a lot!

---

Have you the possibility to update the `samples/` folder? 
You need to:

* run `mvn verify` locally
* run the scripts (`bin/*.sh`) to update the java clients.
* add the changes to this PR.

---

I will perform some tests locally, but on the first look, it looks very good to me.

**Comment by 0v1se** [comment]
@jmini, ok
found some bugs, will fix and update

**Comment by 0v1se** [comment]
@jmini, fixed bugs
also, it seems there was bug for gson generator: no discriminator field was specified in https://github.com/daonomic/openapi-generator/blob/a0fe6bca8839e69dbd0b22ab910db06a3a27474d/samples/client/petstore/java/okhttp-gson-parcelableModel/src/main/java/org/openapitools/client/JSON.java#L63

**Comment by 0v1se** [comment]
@jmini did you check the code?

**Comment by jmini** [comment]
Yes I did, it looks good to me. I was wondering if the change can be added to the `3.1.x` stream (`master` branch) or if we need to do it for the `3.2.x` stream (`3.2.x` branch).

The replacement of `io.swagger.v3.oas.models.media.Discriminator` with `DiscriminatorCodegen` used in `CodegenModel` and in `CodegenOperation` is not an API break from a template point of view.

Technically speaking, if people are extending the `Codegen` classes (to support their own generator for example) then they might get compile error...

**Comment by 0v1se** [comment]
@jmini `3.2.x` looks good to me

also, did you notice I changed `CodegenDiscriminator`?
I removed `CodegenDiscriminator.MappedModel`. It currently doesn't hold `CodegenModel`, but only its name.
I think, it's enough for code generation (may be I'm wrong). At least, it's enough for Java.

**Comment by jmini** [comment]
Follow up: I have created a small PR for the documentation of this feature: #587

**Pull request merged**
