### PR TITLE
[Java] adds snapshotVersion CLI option and uses API version as artifactVersion by default

### PR DESCRIPTION
**Pull request by pablolazaro**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): ~~`master`, `3.4.x`,~~`4.0.x`. Default: `master`.
-  [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas 
@JFCote 
@sreeshas 
@jfiala  
@lukoyanov 
@cbornet  
@jeff9finger 

### Description of the PR

This PR contains two simple new features:

- If no artifactVersion is provided in additional properties, version from API specification is used. If none of them is provided then fallbacks to default version (1.0.0)
- Adds a snapshotVersion CLI option to build artifact version as SNAPSHOT ({version}+"-SNAPSHOT")

### CODE REVIEW

**Comment by wing328** [comment]
I've retargeted the PR for master instead of 4.0.x branch.

Can you please resolve the merge conflicts when you've time? Let me know if you need any help.

**Comment by pablolazaro** [comment]
Hi @wing328, thank you for your attention.

I've resolved the merge conflicts, please let me know if anything is wrong.

Best regards.

**Comment by pablolazaro** [comment]
I fixed the tests but now CircleCI fails and says "Please run 'bin/utils/ensure-up-to-date' locally and commit changes". I've done this and have pushed the changes but it still failing.

Do I should revert these last changes?

**Comment by wing328** [comment]
@pablolazaro I've updated the samples via https://github.com/OpenAPITools/openapi-generator/pull/2033/commits/84b4f5dc573575697bde688d37b1c754e7bfd3d0. Let's see how it goes.

**Comment by wing328** [comment]
@pablolazaro thanks again for the PR. Have you considered adding "-SNAPSHOT" to the `artifactVersion` directly instead of introducing another option?

**Comment by pablolazaro** [comment]
Hey @wing328, thank you for your time, I'm seeing that all check have been passed.

It's an interesting question, let me try to explain why I considered to have separate options for version and snapshot version.

Usually in your API definitions you don't have "snapshot" versions. You would probably have a closed released version in your master branches and a potential-release version (the next version of master branch) in your development branches. In order to publish an artifact generated from development branches it's nice to mark it as "snapshot", therefore, you can use the "snapshot" option in your CI when you're generating an artifact from these kind of branches to create the POM with a SNAPSHOT version. When you're releasing a new version you can skip the option to use the API version as artifact version.

Let me know if it has sense.

**Comment by wing328** [comment]
Thanks for the explanation. Let's go with this one.

Eventually, we may want to sunset some options in the Java-related generators and use additionalProperties or customized templates instead but that not likely going to happen until 5.x/6.x release.

**Comment by pablolazaro** [comment]
Thanks for the merge. I hope to keep contributing as much as a I can :)

**Pull request merged**
