### PR TITLE
[Go] Change primitive file type to os.File and prevent unknown response type error

### PR DESCRIPTION
**Pull request by DouglasDwyer**
This PR addresses issue #11965, which causes an unknown response type error to occur during file download, by switching the primitive data type of files in Go from `*os.File` to `os.File`. Because the client API template checks for a `**os.File` type when attempting to decode an HTTP response, and the target file response type is `***os.File`, the correct response type is not found and an error is returned. By switching to using `os.File`, double pointers are eliminated and file download works.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.0.1) (patch release), `6.1.x` (breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @antihax @grokify @kemokemo @jirikuncar @ph4r5h4d

### CODE REVIEW

**Comment by icubbon** [comment]
Nice work! There is a failing unit test in the Go Petstore Sample Client area.
```
# github.com/OpenAPITools/openapi-generator/samples/client/petstore/go/go-petstore
go-petstore/api_pet.go:1119:30: invalid operation: requiredFileLocalVarFile != nil (mismatched types os.File and nil)
go-petstore/api_pet.go:1120:27: cannot use requiredFileLocalVarFile (type os.File) as type io.Reader in argument to ioutil.ReadAll:
	os.File does not implement io.Reader (Read method has pointer receiver)
```

Additionally, do you know where the changes to `/` and `\` came from in https://github.com/OpenAPITools/openapi-generator/pull/12685/commits/1699f8da8fe3d31a085a941e031a853b5074e53b?

**Comment by DouglasDwyer** [comment]
@icubbon, thanks for the review. I guess I missed the required/not required distinction, so that's a good catch. I've corrected the issue.
Regarding the difference in file separators (`\` versus `/`), they arise when I run the Maven cleaning and sample generating SH scripts. I had this same issue in PR #12682, but I never got information on how to proceed with fixing it. I am running the generation scripts with Git Bash on Windows 11.

**Comment by DouglasDwyer** [comment]
I went ahead and regenerated the samples on Linux. This seems to have fixed the file separator issue, so I hope that we can move forward with the changes :)

Out of curiosity, might I ask why we currently generate samples locally, before making a PR? I am sure there is a good reason, but it seems to me that generating the samples and docs as part of the CI/CD pipeline here on GitHub would simplify the PR submission process and avoid issues like these.

**Comment by wing328** [comment]
The samples can show the exact change to the auto-generated code, which makes the review much easier.

Without that, it's hard to visual the change.

**Comment by icubbon** [comment]
@DouglasDwyer It looks like there a couple of examples that need to get re-generated. Thanks!
```
-// SetPropTest gets a reference to the given map[string]*os.File and assigns it to the PropTest field.
-func (o *MapOfFileTest) SetPropTest(v map[string]*os.File) {
+// SetPropTest gets a reference to the given map[string]os.File and assigns it to the PropTest field.
+func (o *MapOfFileTest) SetPropTest(v map[string]os.File) {
```

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/14046

**Pull request closed without merging**
