### PR TITLE
[java] Intro openApiNullable property to enable/disable OpenAPI Jackson Nullable library

### LINKED ISSUE #2901: remove unused import org.openapitools.jackson.nullable.JsonNullable from generated model
#### Bug Report Checklist

- [ X] Have you provided a full/minimal spec to reproduce the issue?
- [ X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ X] What's the version of OpenAPI Generator used?
- [ X] Have you search for related issues/PRs?
- [X ] What's the actual output vs expected output?
- [X ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
When I generate the model there  is an unused import  org.openapitools.jackson.nullable.JsonNullable; in every single DTO. It forces me to add a dependency.

		<dependency>
		    <groupId>org.openapitools</groupId>
		    <artifactId>jackson-databind-nullable</artifactId>
		    <version>0.1.0</version>
		</dependency>

Unfortunately this dependency must be approved in the company so the model is unusable.

Is there any way to get rid of this unused import? Configuration is below:

			<plugin>
			    <groupId>org.openapitools</groupId>
			    <artifactId>openapi-generator-maven-plugin</artifactId>
			    <version>4.0.0</version>
			    <executions>
			        <execution>
			            <goals>
        			        <goal>generate</goal>
        			    </goals>
            			<configuration>
					<inputSpec>${maven.multiModuleProjectDirectory}/api/target/generated/swagger-api-spec/swagger.json</inputSpec>	
						<language>spring</language>
						<library>spring-boot</library>
						<model-name-prefix>Cqrs</model-name-prefix>
						<modelPackage>com.anthem.specialty.provider.springapi.model</modelPackage>
						<apiPackage>com.anthem.specialty.provider.springapi.api</apiPackage>
						<invokerPackage>com.anthem.specialty.provider.springapi.invoker</invokerPackage>
            			    <skipValidateSpec>true</skipValidateSpec>
						<generateSupportingFiles>true</generateSupportingFiles>
						<supportingFilesToGenerate>
							ApiApi.java,ApiApiControler.java,ApiUtil.java
						</supportingFilesToGenerate>
            			    <configOptions>
						<sourceFolder>src/gen/java/main</sourceFolder>
						<java8>false</java8>
						<dateLibrary>java8</dateLibrary>
						<interfaceOnly>false</interfaceOnly>
						<groupId>com.company</groupId>
						<artifactId>${project.artifactId}</artifactId>
						<artifactVersion>${project.version}</artifactVersion>
            		    		</configOptions>
            			</configuration>
		        	</execution>
			    </executions>
			</plugin>	

##### openapi-generator version

			    <groupId>org.openapitools</groupId>
			    <artifactId>openapi-generator-maven-plugin</artifactId>
			    <version>4.0.0</version>

##### OpenAPI declaration file content or url

probably convenient enhancement

##### Command line used for generation

maven plugin

##### Steps to reproduce

run the maven clean install

##### Related issues/PRs

a few similar issues

##### Suggest a fix

provide a mechanism to remove unused imports

### PR DESCRIPTION
**Pull request by Patouche**
Close #2901 

Add a additional property to prevent adding the dependency `org.openapitools:jackson-databind-nullable:jar` in the classpath. As explained on #2901, this dependency may be forbidden in some company.

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Copy to technical committee for review Java code generation : @bbdouglas / @sreeshas / @jfiala / @lukoyanov /  @cbornet / @jeff9finger / @karismann / @Zomzog / @lwlee2608 / @bkabrda

### CODE REVIEW

**Comment by Patouche** [comment]
Hi here !

Any chance for a review or any other feedback ? If you disagree with changes made in this PR, I can correct them and update the PR or close the PR if you think it completely useless.

I can also rebase the PR if you wish.

Thanks a lot,
Patouche

**Comment by macjohnny** [comment]
@bbdouglas / @sreeshas / @jfiala / @lukoyanov / @cbornet / @jeff9finger / @karismann / @Zomzog / @lwlee2608 / @bkabrda Please review

**Comment by jimschubert** [comment]
Just wanted to point out that William requested @Patouche to ping him on Slack so we can move this PR forward. I like the approach in the PR to optionally remove `jackson-databind-nullable`. It would be nice if this became the default and we stick with readily available serialization libraries without extra dependencies.

**Comment by Patouche** [comment]
Hi @jimschubert ,

Sorry for the delay - I have other priorities this last days.
I just registered on the openapi-generator slack and ping @wing328 as he ask me to. Hope this will move this PR forward.

Thanks for the reminder,
Patouche

**Comment by jimschubert** [comment]
I've resolved merge conflicts. I think this ready to merge as long as the concerns @wing328 raised in Slack are addressed.

**Comment by Patouche** [comment]
Thanks @jimschubert . Yes, I already did it last week but there was some new conflicts the next day.
I will ping @wing328 one more time on slack.

Thanks a lot.

**Review by wing328 — APPROVED** [review]

**Comment by lostiniceland** [comment]
microprofile is still generating this unused import. no config-option available there

**Pull request merged**
