### PR TITLE
[Cpp][Qt][Client] Fix CMakeLists.txt, Qt::Gui, Find_Package(OpenSSL)

### LINKED ISSUE #11371: [BUG] CMakeLists.txt gernerated by  cpp-qt-client is missing Qt5:.Gui dependency / linking
#### Bug Report Checklist
tried with Qt5.14, Qt5.15, with gcc7 under Linux / ubunut 20.04

- [ ] What's the actual output vs expected output?
CMake should build, but fails with QDesktopServices.h can not be found. This header depens on Qt5:Gui which is not listed/linked in the autogernated CMakeLists.txt 

##### openapi-generator version
5.3.1

##### Suggest a fix
add
find_package(Qt5 COMPONENTS Gui REQUIRED)
and Qt5::Gui  under target_link_libraries in the generated CMakeLists.txt

### PR DESCRIPTION
**Pull request by Thaulino**
Note replacement of : #11950

### Description

Changed: Always add Qt5::Gui to build, needed because {{prefix}}Oauth.h is always part of the build
Added: find_package for OpenSSL, should be done prior target_link_libraries

### Tests that have been done :
(ubuntu) 
install deps (reference #11371 ): 
sudo apt install -y --no-install-recommends qt5-default 
run code generator:
java -jar openapi-generator-cli-5.4.0.jar generate -t cpp-qt-templates -i petstore.json -g cpp-qt-client -o petstore
run cmake:
cmake -S petstore -B petstore/build

(windows)
run code generator:
java -jar openapi-generator-cli-5.4.0.jar generate -t cpp-qt-templates -i petstore.json -g cpp-qt-client -o petstore
run cmake:
cmake -S petstore -B petstore/build
 
### Issue
fixes #11371 

### technical commitee
@wing328 
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @MartinDelille (2018/03) @muttleyxd (2019/08)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by MartinDelille** [comment]
I'd like to add the same kind check for qmake but I wondered how to disable oauth?

When generating the example (which you should do to make this PR happy), the Qt5::Gui is indeed present.

**Review by MartinDelille — CHANGES_REQUESTED** [review]
Generate the sample code.

**Review by muttleyxd — APPROVED** [review]
Looks okay for me

**Review by MartinDelille — APPROVED** [review]

**Comment by Thaulino** [comment]
@wing328, @muttleyxd , @MartinDelille  Is there anything left to do for me ?

**Comment by wing328** [comment]
Tested locally and the result is good:
```
PASS   : UserApiTests::deleteUserTest()
QDEBUG : UserApiTests::getUserByNameTest() Error happened while issuing request :  "Error transferring http://petstore.swagger.io/v2/user/johndoe - server replied: Not Found, {\"code\":1,\"type\":\"error\",\"message\":\"User not found\"}"
PASS   : UserApiTests::getUserByNameTest()
QDEBUG : UserApiTests::loginUserTest() "{\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1652607683824\"}"
PASS   : UserApiTests::loginUserTest()
PASS   : UserApiTests::logoutUserTest()
QDEBUG : UserApiTests::updateUserTest() got a request body
PASS   : UserApiTests::updateUserTest()
PASS   : UserApiTests::cleanupTestCase()
Totals: 10 passed, 0 failed, 0 skipped, 0 blacklisted, 111ms
********* Finished testing of UserApiTests *********
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:46 min
[INFO] Finished at: 2022-05-15T17:41:23+08:00
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
