### PR TITLE
Switches python-experimental in as the primary python client

### PR DESCRIPTION
**Pull request by spacether**
Switches python-experimental in as the primary python client
The below generators have been renamed
- python-experimental -> python
- python -> python-prior

And the status of the python generator (old python-experimental) has been changed from experimental to stable.
- That means that changes to the python generator must now follow semvar (breaking changes without fallback must happen in major releases)
- Previously when it was experimental status, breaking changes without fallback were allowed in any release

### Upgrading To The New `python` Client
Please check the generated README.md It includes a migration guide on what needs to change when using the latest python client.

### Breaking change with fallback
If users prefer to use the old client, they can change their generation to use `python-prior` rather than `python`

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. let me review over the weekend.

**Comment by wing328** [comment]
As discussed, the goal of this PR is to replace `python` generator with the `python-experimental` generator, which is ready for production usage according to @spacether . This will allow more openapi-generator users to migrate to it more easily (if they decide to) as part of the v6.2.0 minor release.

Given that `python-experimental` contains breaking changes, users can fallback to `python-prior` after this PR if they prefer not to upgrade at the moment for whatever reasons.

After the PR, the future development of `python` and `python-prior` (which follow a JSON schema focused design) will be moved to a new project named "openapi-json-schema-generator" under https://github.com/jsonschematools. Anyone wants to contribute a client/server generator with a focus on JSON schema should contribute to "openapi-json-schema-generator" (which will be created after the v6.2.0 release).

At the same time, @wing328 is leading an effort to create a new Python client generator based on the design of other popular clients in this project such as Java, C#, PHP, Ruby and more to make the overall developer experience more consistent. The goal is to have the new Python client generator replacing/sunsetting all existing python client generators in the `openapi-generator` project at the moment for easier maintenance.

**Comment by EltonChou** [comment]
> As discussed, the goal of this PR is to replace `python` generator with the `python-experimental` generator, which is ready for production usage according to @spacether . This will allow more openapi-generator users to migrate to it more easily (if they decide to) as part of the v6.2.0 minor release.

When will the v6.2.0 to be released? Any roadmap?

**Comment by spacether** [comment]
One clarification, python-prior will not be moved to the new project. It has flaws that are not fixable and that are fixed in python-experimental.

Some of them are
- one payload is stored in multiple class's instances in python-prior which has a failure mode of instances disagreeing on property values. python only stores one instance
- python-prior uses python naming for properties which mutates payload keys, which can break oneOf/anyOf/allof/not composition. python uses spec naming and does not mutate payloads

**Comment by wing328** [comment]
FYI. @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
UPDATE: Included this PR in v6.2.0 release. For feedback/question/issue related to the refactored `python` client generator, please open a ticket via https://github.com/OpenAPITools/openapi-json-schema-generator/issues/new/

**Pull request merged**
