### PR TITLE
Update swagger parser to 2.0.19

### PR DESCRIPTION
**Pull request by wing328**
Update swagger parser to 2.0.19

Ref: https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.19

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @OpenAPITools/generator-core-team

### CODE REVIEW

**Comment by wing328** [comment]
Reported by Drone.io: 
```

[main] INFO  o.o.c.config.CodegenConfigurator -
--
120 | VERBOSE MODE: ON. Additional debug options are injected
121 | - [debugOpenAPI] prints the OpenAPI specification as interpreted by the codegen
122 | - [debugModels] prints models passed to the template engine
123 | - [debugOperations] prints operations passed to the template engine
124 | - [debugSupportingFiles] prints additional data passed to the template engine
125 | [ERROR] Error fetching link: /drone/src/modules/openapi-generator/drone/src/modules/openapi-generator-cli/target/apidocs. Ignored it.
126 | + /bin/bash bin/utils/test-fake-petstore-for-all.sh
127 | # START SCRIPT: bin/utils/test-fake-petstore-for-all.sh
128 | [OAS 2.0] Executed ada successfully!
129 | ERROR: Failed to run ada
130 | java -jar ./modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml -g ada -o /tmp/openapi-generator-test-fake-petstore/3.0/ada
```

Running the command manually outputs the following:
```
java -jar ./modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml -g ada -o /tmp/openapi-generator-test-fake-petstore/3.0/ada
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 30
Errors: 
	-attribute .servers. invalid url : http://{server}.swagger.io:{port}/v2
	-attribute .servers. invalid url : https://localhost:8080/{version}
Warnings: 
	-attribute .servers. invalid url : http://{server}.swagger.io:{port}/v2
	-attribute .servers. invalid url : https://localhost:8080/{version}

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:474)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:501)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:418)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

the errors/warning do not make sense to me as it's valid according to the spec. Here is an example from the spec:
```
servers:
- url: https://{username}.gigantic-server.com:{port}/{basePath}
  description: The production API server
  variables:
    username:
      # note! no enum here means it is an open value
      default: demo
      description: this value is assigned by the service provider, in this example `gigantic-server.com`
    port:
      enum:
        - '8443'
        - '443'
      default: '8443'
    basePath:
      # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
      default: v2
```

Looks like an issue with Swagger Parser 2.0.18 to me.

**Comment by jimschubert** [comment]
@wing328 one difference that I see is the spec has strings for all variables where we have integers for the port enums.

**Comment by jimschubert** [comment]
Yes, Server Variable Object requires strings for the enum:

> An enumeration of string values to be used if the substitution options are from a limited set.

We should add a recommends output, because the parser error is not clear at all.

**Comment by wing328** [comment]
Got the same error using string instead of integer for port number.

**Comment by wing328** [comment]
Testing with the following provided in the official spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#server-object-example:

```yaml
servers:
- url: https://{username}.gigantic-server.com:{port}/{basePath}
  description: The production API server
  variables:
    username:
      # note! no enum here means it is an open value
      default: demo
      description: this value is assigned by the service provider, in this example `gigantic-server.com`
    port:
      enum:
        - '8443'
        - '443'
      default: '8443'
    basePath:
      # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
      default: v2
```

I got the same error:
```
Errors: 
	-attribute .servers. invalid url : https://{username}.gigantic-server.com:{port}/{basePath}
```

**Comment by jimschubert** [comment]
I think we should update our enums to be strings.

The error you're seeing presented is a bug in swagger-parser. It check for a valid URL here: https://github.com/swagger-api/swagger-parser/blob/ee9d1a6659fc732cf7798f8778a374fc99a5d34a/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L410
by converting a URL to a URI (which the templated server contents are invalid). Some templated server inputs are invalid also at the URL level. See for example (includes server template from swagger-api/swagger-parser#1043):

```
jshell> import java.net.URL

jshell> String input = "https://{username}.gigantic-server.com:{port}/{basePath}"
input ==> "https://{username}.gigantic-server.com:{port}/{basePath}"

jshell> URL url = new URL(input);
|  java.net.MalformedURLException thrown: Error at index 0 in: "{port}"
|        at URL.<init> (URL.java:661)
|        at URL.<init> (URL.java:523)
|        at URL.<init> (URL.java:470)
|        at (#3:1)

jshell> String input = "https://some-{placeholder}.example.com"
input ==> "https://some-{placeholder}.example.com"

jshell> URL url = new URL(input);
url ==> https://some-{placeholder}.example.com

jshell> url.toURI()
|  java.net.URISyntaxException thrown: Illegal character in authority at index 8: https://some-{placeholder}.example.com
|        at URI$Parser.fail (URI.java:2915)
|        at URI$Parser.parseAuthority (URI.java:3249)
|        at URI$Parser.parseHierarchical (URI.java:3160)
|        at URI$Parser.parse (URI.java:3116)
|        at URI.<init> (URI.java:600)
|        at URL.toURI (URL.java:1018)
|        at (#6:1)

```

**Comment by jmini** [comment]
I have filed:
https://github.com/swagger-api/swagger-parser/issues/1329

**Comment by jimschubert** [comment]
@jmini thanks! I had to drop off right after posting what I found.

**Comment by wing328** [comment]
UPDATE: upgrade to 2.0.19 and all tests passed.

cc @OpenAPITools/generator-core-team

**Pull request merged**
