### PR TITLE
[Java][RestTemplate] remove wrong Null Check 

### LINKED ISSUE #3480: [BUG] Description
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue? **The problem is easily seen by inspection of the generated sample code or the mustache files**
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))? **N/A**
- [X] What's the version of OpenAPI Generator used? **4.0.3**
- [X] Have you search for related issues/PRs? **Yes**
- [X] What's the actual output vs expected output? **Described below**
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The ApiClient class introduced by the java **resttemplate** generator will not pass a SpotBugs validation.

At https://github.com/OpenAPITools/openapi-generator/blob/3785165e079de8f36f3baf774897feb1065576ba/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L622
 a check for returnType == null is performed, after the returnType variable was already dereferenced at
https://github.com/OpenAPITools/openapi-generator/blob/3785165e079de8f36f3baf774897feb1065576ba/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L614

##### openapi-generator version

4.0.3

##### OpenAPI declaration file content or url

**N/A**

##### Related issues/PRs

Related issue is https://github.com/OpenAPITools/openapi-generator/issues/33 , which could catch the problem during the build.

##### Suggest a fix

The fix is simply to remove the null check at line 622, as it cannot be reached due to the NPE would would happen on line 614.

### PR DESCRIPTION
**Pull request by tjnet**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

I just wanted to fix #3480 .

But I'm a newbie. 
I'm new to this. Is this correct?
Please review in your free time.

#### How to test 

I ran following command and commit changed files.

- mvn verify
- bin/java-petstore-resttemplate.sh
- bin/java-petstore-resttemplate-withxml.sh

### CODE REVIEW

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

**Comment by wing328** [comment]
@tjnet thanks for the fix, which looks good to me. I'll merge it on Monday if no one has further feedback on this PR.

cc @gmcelhoe who reported the bug.

**Comment by wing328** [comment]
@tjnet thanks for the PR, which has been merged into master.

**Comment by tjnet** [comment]
@wing328  tnanks  for your review! 😃

**Comment by wing328** [comment]
@tjnet thanks for the PR, which has been included in the 4.1.0 release: https://twitter.com/oas_generator/status/1160000504455319553

**Pull request merged**
