### PR TITLE
[Kotlin] Remove kotlin-reflect dependency when not needed

### PR DESCRIPTION
**Pull request by adamkaplan**
Removes un-unsed kotlin-reflect dependency when the combination of network and serialization library do not require it.
- When not using `ok-http3` or `ok-http4`
- **and**
  - not using `moshi`
  - _or_ using `moshi` with `moshiCodeGen=true`

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
@adamkaplan thanks for the PR, which sounds like a backward compatible change to me. Shall we target this change to the current master instead?

**Comment by wing328** [comment]
Please run `./bin/kotlin-client-all.sh` to update Petstore samples so that CIs can test and verify the change.

**Comment by adamkaplan** [comment]
@wing328 Sounds good. I’ll resubmit to 4.3.0.

Also, I did run the test update script in my second commit 3eda0c4 but it generated VERSION files with 4.3.0 in them. Not clear why that was...

**Comment by 4brunu** [comment]
Why is this PR targeting 5.0.x?
I thinks this doesn't introduce a breaking change, so I think it can target master.
What do you think?

Another question is that this PR is committing a lot of temporary files under build directory.
Could you please remove them?

**Comment by adamkaplan** [comment]
See #5502

**Pull request closed without merging**
