### PR TITLE
[GO] Fix value formatting in url with slices

### PR DESCRIPTION
**Pull request by darkrift**
This is to fix the client generation problem related to #14798 where url value ends up being `reflect.Value+value` instead of their real value.

@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d @lwj5

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by darkrift** [comment]
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

Could I get a review for this and add this to the next releases ? Is there anything missing in the PR ?

I don't think the node3 build failures is directly related to this change, but I may be wrong. Could you point me in the right direction if it is linked to my changes ?

**Comment by wing328** [comment]
thanks for the PR. will try to review this weekend and get it merged

**Comment by ppbaena** [comment]
Hi @wing328, 
Is there any update here? It looks like everything is almost ready to review and merge. 
It would be great to use the upstream solution for this. 
Please, let me know if I can help some way. 
Thanks!

**Comment by wing328** [comment]
circleci tests passed via https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/24493/workflows/7418e43a-ff72-4ed8-965a-a1d2d11bba05

**Pull request merged**
