### PR TITLE
[GROOVY] update client generator to a stable version

### PR DESCRIPTION
**Pull request by karismann**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.

### Description of the PR

- update groovy version and dependencies
- update gradle version
- change the unmaintened http request library (http-builder) to a forked library : http-builder-ng
- add a README
- handle form and body params (was TODO)
- remove a useless specific parameter (configPackage)
- fix handling path parameters (see postProcessOperationsWithModels method in codeGen class)
- remove deprecated annotation (Mixin)
- add CI test on petApi

### CODE REVIEW

**Comment by karismann** [comment]
@wing328   https://circleci.com/gh/OpenAPITools/openapi-generator/6480#tests/containers/1  is-it possible to have a detail of the error of the CI test for one of my news groovy test  ?  I can't reproduce it locally

```
openapitools.PetApiTest > testUpdateOnePetWithForm FAILED
    junit.framework.AssertionFailedError at PetApiTest.groovy:90

4 tests completed, 1 failed
:test FAILED
```

**Comment by wing328** [comment]
FYI. I've filed https://github.com/OpenAPITools/openapi-generator/pull/2871 to update Groovy version to 2.5.7 (released 2 days ago)

**Comment by karismann** [comment]
Thanks!

**Comment by wing328** [comment]
I forgot to update the README. Just filed https://github.com/OpenAPITools/openapi-generator/pull/2874 to update it.

**Pull request merged**
