### PR TITLE
[Java][Feign] added 'feignHttpClient' configOption and support for ap…

### PR DESCRIPTION
**Pull request by gaetPax**
https://github.com/OpenAPITools/openapi-generator/issues/5709
Added 'feignHttpClient' configOption and support for apache feign httpClient.
Support for other feign httpClient modules can be easily added with same option.

### CODE REVIEW

**Comment by wing328** [comment]
@gaetPax thanks for the PR. Please ping me via https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM on how to move this PR forward.

**Comment by wing328** [comment]
@gaetPax as discussed, please resolve the merge conflicts when you've time. Then we'll review and merge this PR accordingly.

**Comment by wing328** [comment]
@gaetPax may I know if you've time to resolve the merge conflicts so that we can include this change in the upcoming 5.0.0-beta3 release?

**Comment by gaetPax** [comment]
Hi @wing328 , I will try to do it today

**Comment by wing328** [comment]
@gaetPax can you please resolve merge conflicts when you've time? Then please notify me via email in my Github profile to have it reviewed sooner. Thank you.

**Comment by gaetPax** [comment]
Support to better HttpClient has been added by https://github.com/OpenAPITools/openapi-generator/pull/8484 which sets OkHttp as the default feign client, which should be the most complete one (even better than ApacheHttpClient) and capable to handle most of the use cases.
[Comparison here: https://www.mocklab.io/blog/which-java-http-client-should-i-use-in-2020/]
So adding the choice of select the HttpClient implementation could be really not necessary and just adding complexity to the source code. Closing the PR.

**Pull request closed without merging**
