### PR TITLE
Update C# client dependency

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Update C# client dependency (nunit, jsonsubtypes, Newtonsoft.Json, etc)

cc @mandrean (2017/08), @jimschubert (2017/09)

### CODE REVIEW

**Comment by jimschubert** [comment]
I support upgrading!

Did you test this across supported framework versions? I recall there was an issue with newer versions of either JSON.net or the subtypes package (possibly both), which had issues with one or more of our framework options.

The errors were only presented at runtime.

**Comment by wing328** [comment]
> Did you test this across supported framework versions? 

I didn't. I only leverage the AppVeyor to test the change at the moment. Agreed with you that we need to test more thoroughly with different frameworks.

**Comment by wing328** [comment]
Tests running fine locally but in Appveyor, it couldn't find nunit dll:
```
Project "C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\Org.OpenAPITools.sln" (1) is building "C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "bin\Debug\".
  Creating directory "obj\Debug\".
ResolveAssemblyReferences:
  Primary reference "nunit.framework".
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "nunit.framework". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj]
          For SearchPath "{HintPathFromItem}".
          Considered "..\..\packages\NUnit.3.11.0\lib\nunit.framework.dll", but it didn't exist.
          For SearchPath "{TargetFrameworkDirectory}".
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\nunit.framework.winmd", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\nunit.framework.dll", but it didn't exist.
          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\nunit.framework.exe", but it didn't exist.
```

Anyone has seen something similar before?

**Comment by wing328** [comment]
NUnit 3.11 is the latest version: https://nunit.org/download/

**Comment by wing328** [comment]
@jimschubert finally I'm able to fix the issue and all tests passed.

**Pull request merged**
