### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- improve validation error message to show how to disable the validation cc @jimschubert 
- improve C++ QT5 generator's description and add Windows batch file cc @etherealjoy 
- fix the invalid spec used by the Swift generator

### CODE REVIEW

**Comment by etherealjoy** [comment]
Ok for the Qt5 server.
I plan more updates to align it with latest `C++` changes on master and to rework `class` name to highlight the framework.

**Comment by wing328** [comment]
@etherealjoy 👌 I'll send out a tweet to promote the new server generator after our improvements

**Comment by etherealjoy** [comment]
@wing328 I created #655 to address @stkrwork concerns and also added the beta tag since it will conflict after merge.

**Comment by wing328** [comment]
@etherealjoy 👌 I'll undo the C++ Qt5 server generator-related change in this PR.

**Pull request merged**
