### PR TITLE
Store operation notes as multiple lines

### PR DESCRIPTION
**Pull request by therve**
This adds an extension to store operation notes as an array, so that we can
iterate line by line and preserve line breaks from spec documentation in API
documentation.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by therve** [comment]
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch 🙇

**Comment by Zomzog** [comment]
Hi,
Does a new vendor extension is really required? Can't it just be customization like
`op.notes = formatNote(operation.getDescription());`
And the java generator handle it has it want by overriding formatNote?

**Comment by therve** [comment]
> Hi,
> Does a new vendor extension is really required? Can't it just be customization like
> `op.notes = formatNote(operation.getDescription());`
> And the java generator handle it has it want by overriding formatNote?

Even in Java generator, sometimes we want to regular `notes` object, sometimes we want multiline one. I don't think replacing the object everywhere works.

**Comment by wing328** [comment]
> This adds an extension to store operation notes as an array, so that we can
iterate line by line and preserve line breaks from spec documentation in API
documentation.

What about using code formatter/linter (e.g. prettier.io) to handles these lines in the comments that are too long?

We always recommend users to auto format the auto-generated code to meet their coding style.

**Comment by therve** [comment]
> What about using code formatter/linter (e.g. prettier.io) to handles these lines in the comments that are too long?
> 
> We always recommend users to auto format the auto-generated code to meet their coding style.

We'll probably do that, but it's nice to be able to format things directly in the spec. Code formatters will most likely break it in a different way.

**Comment by wing328** [comment]
> Code formatters will most likely break it in a different way.

This is exactly the challenge and why I think code formatter/linter is a good candidate to tackle this issue since most formatter/linter are configurable and users can have complete control (ideally in how long lines are split into shorter as well)

**Pull request closed without merging**
