### PR TITLE
 Fix a few issues with the C generator (part 1 version 2)

### PR DESCRIPTION
**Pull request by eafer**
This is a second version of the pull request from https://github.com/OpenAPITools/openapi-generator/pull/14388. The differences with the first version are:

- this version uses the existing implementation of `object_t`, as requested by @ityuhui
- the `Config.cmake.in` file was cleaned up (I think it showed up in the first place because I forgot to rebuild before running the script)
- `returnTypeIsEnum` was abandoned and replaced with `returnProperty`, following the instructions by @wing328
- the fourth patch from https://github.com/OpenAPITools/openapi-generator/pull/14379 is also included now, because it got fixed

These patches fix a few compilation errors for [this api's](https://github.com/ARM-software/avh-api/tree/master/c) generated code, but they are not enough by themselves to get it to build. More patches will be submitted later.

### CODE REVIEW

**Comment by eafer** [comment]
@zhemant @michelealbano

**Comment by wing328** [comment]
@ityuhui what do you think is the best way to proceed with this PR?

What about breaking it down into 4 smaller PRs to review and merge?

**Comment by ityuhui** [comment]
@wing328 

Since it's been a long time since my last review, I will go through this PR recently to check if it can be merged or should break down into smaller PR.

**Comment by ityuhui** [comment]
I'm just wondering why this https://github.com/OpenAPITools/openapi-generator/pull/14434/commits/a0fa76da63d6ced6e039acc13b6de1ed63326dbc should change.

@wing328 Are these 2 commits https://github.com/OpenAPITools/openapi-generator/pull/14434/commits/523e5de3d601af3ef39681bf0aabaec1f3e6aed5 and https://github.com/OpenAPITools/openapi-generator/pull/14434/commits/5a4a398fc45d96a3f825c82fa46116b00bb8fadc about `returnProperty` reviewed by you ?

I'm find with the rest of this PR.

**Comment by eafer** [comment]
Hi! Thank you for looking into this again.

> I'm just wondering why this a0fa76d should change.

Because that's how `*_parseFromJSON()` and `*_convertToJSON()` are actually called by the rest of the generated code. For instance in the `api-body.mustache` template you have the following line:

```
        elementToReturn = {{{returnBaseType}}}_parseFromJSON({{classname}}localVarJSON);
```

For our `instance_state` model, this generates:

```
        elementToReturn = instance_state_parseFromJSON(ArmAPIlocalVarJSON);
```

But the `*_parseFromJSON()` function gets declared as:

```
arm_api_instance_state__e instance_state_instance_state_parseFromJSON(cJSON *instance_stateJSON);
```

So the build will not go well, with warnings such as this one:

```
warning: implicit declaration of function ‘instance_state_parseFromJSON’; did you mean instance_return_parseFromJSON’? [-Wimplicit-function-declaration]
 4045 |         elementToReturn = instance_state_parseFromJSON(ArmAPIlocalVarJSON);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           instance_return_parseFromJSON

```

**Comment by ityuhui** [comment]
Thank you @eafer for the clarifacation.

I'm OK with this PR.

@wing328 If you agree the commits https://github.com/OpenAPITools/openapi-generator/commit/523e5de3d601af3ef39681bf0aabaec1f3e6aed5 and https://github.com/OpenAPITools/openapi-generator/commit/5a4a398fc45d96a3f825c82fa46116b00bb8fadc about `returnProperty`, I think this PR can merge now.

**Comment by ityuhui** [comment]
I'm OK with this PR.

Just wait for @wing328 to review and merge.

**Review by ityuhui — APPROVED** [review]

**Comment by eafer** [comment]
Hey @wing328, is there anything more I can do to help here?

**Comment by ityuhui** [comment]
Hi @wing328

I think this PR can merge now.

**Comment by wing328** [comment]
@eafer can you please resolve the merge conflicts when you've time?

sorry for the delay in getting it merged.

**Comment by eafer** [comment]
@wing328 I did the backmerge you requested. I'll try to look into the test schemas later, but it's been a while and I'm struggling to get things to build again.

**Comment by wing328** [comment]
updated samples via https://github.com/OpenAPITools/openapi-generator/pull/14434/commits/e3dfe904557f9a566d371758b2ad2e9c5a837f9a 
and all tests passed

**Comment by wing328** [comment]
just merged it. thanks again for the PR.

if i can find the time later, i'll update the c petstore spec to add some tests too.

**Comment by eafer** [comment]
@wing328 Thanks! I just tried some changes for the test schemas and sent a new pull request with them: https://github.com/OpenAPITools/openapi-generator/pull/20200. I hope it helps.

**Comment by wing328** [comment]
@eafer thank you. will review and get it merged shortly

**Pull request merged**
