### PR TITLE
Make frequently used IO resources autoclosable

### LINKED ISSUE #1909: [BUG][JAVA] AbstractGenerator.java leaks mustache template file handles in templateDir - blocker when using templateDir with gradle plugin due to long running gradle daemons
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
=> default petstore is perfectly fine
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
=> yes
- [x] What's the version of OpenAPI Generator used?
=> 3.3.4
- [x] Have you search for related issues/PRs?
=> yes, no match identified
- [x] What's the actual output vs expected output?
=> not related to generator output
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The problem is that AbstractGenerator.java leaves mustache template file handles open. This is fine if the generator process completes quickly and the process terminates, because operating system then closes all file handles. On the other hand, when using gradle plugin, the gradle daemon process may remain in memory and the handles remain open, preventing deletion of custom templateDir.

##### openapi-generator version

version 3.3.4, not a regression issue, seems the issue exists since the initial commit

##### OpenAPI declaration file content or url

Can use default pet store. The issue is not related to OpenAPI specs, but rather to the use of templateDir with custom templates together with gradle plugin.

##### Command line used for generation

actually, used the gradle plugin, the main point is that templateDir is used with custom templates together with the gradle plugin and gradle daemon process remains running in the background

##### Steps to reproduce

- copy default set of templates for a generator to a newly created templateDir
- run the generator using gradle plugin (gradle daemon enabled by default), passing the created templateDir
- after the generator is done, try deleting the templateDir, it cannot be done due to file locks -- the file handles are still open.
- open Windows Task Manager and kill java.exe process running gradle, the templateDir can now be deleted

##### Related issues/PRs

no PR on my part, I suggest a simple fix below, it's really a trivial thing to fix once you're aware of what it going on, please see "Suggest a fix" below

##### Suggest a fix

Culprit method: `readTemplate()`
Culprit file: `AbstractGenerator.java`
Full path: openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/AbstractGenerator.java

Lines causing the issue are commented out in the following snippet and replaced with the solution (using Java 7 try-with-resources, but can be done without it as well, could as well close the scanner in a finally block)
```
  public String readTemplate(String name) {
    try {
        Reader reader = getTemplateReader(name);
        if (reader == null) {
            throw new RuntimeException("no file found");
        }

        // BEGIN OLD LINES
        // Scanner s = new Scanner(reader).useDelimiter("\\A");
        // return s.hasNext() ? s.next() : "";
        // END OLD LINES

        // BEGIN NEW LINES
        try (Scanner s = new Scanner(reader)) {
          s.useDelimiter("\\A");
          return s.hasNext() ? s.next() : "";
        }
        // END NEW LINES

    } catch (Exception e) {
        LOGGER.error(e.getMessage());
    }
    throw new RuntimeException("can't load template " + name);
  }
```

### PR DESCRIPTION
**Pull request by agilob**
to reduce memory use and unlock them for use by operating system resource scheduler/allocator

Below you can see I run the same template manager test which opens and reads IO resources. I added extra line on debugger just to keep resources busy a bit longer for lsof to scan though them, this allows me to compare before/after results of my changes, as it would be much more difficult to automate this test inside maven, it's all manual.

List of files open by Linux checked with
```
lsof -f | grep '/home/agilob/Projects/openapi-generator/'
```

Before changes:
without change

Same test after changes:
working example

Also reduced complexity of reading dart specific keywords from external file.
Autoclose input reader from ruby error stream

I do not know what the kotlin changes are, I promise  ¯\_(ツ)_/¯

Closes #1909 and fixes a few other unreported

### CODE REVIEW

**Comment by agilob** [comment]
What does it even mean `java.nio.file.FileSystemNotFoundException`, bitrise? :hocho:

**Comment by kuhnroyal** [comment]
Hmm the Kotlin changes also break my PR :(

**Comment by agilob** [comment]
Yea, something untested got merged to master, dont worry about it.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
The kotlin samples have been updated in the master. Please merge the latest master into this branch when you've time.

**Comment by agilob** [comment]
@wing328  done!

**Comment by agilob** [comment]
@OpenAPITools/generator-core-team @wing328

**Comment by agilob** [comment]
@wing328  @jimschubert any plans to merge it?

**Comment by wing328** [comment]
Let me try to review over the weekend.

**Review by wing328 — APPROVED** [review]
Tested locally and the result is good.

**Comment by agilob** [comment]
Thanks

**Pull request merged**
