### PR TITLE
[TS-Refactor] Top-level exports for fetch & jquery

### PR DESCRIPTION
**Pull request by TiFu**
As discussed in #802, this PR moves all exported classes and objects of the refactored ts-generator to the top-level.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.

@bodograumann Did I miss anything?

### CODE REVIEW

**Comment by bodograumann** [comment]
I have a few more changes, but they might require more discussion.
When you merge this commit I will need to rebase and then I'll create another PR.

The CI is still complaining, because we forgot to run `/bin/utils/export_generators_readme.sh`.
I don't think it is necessary to update all commits in `typescript-refactor-master` with the generated readme at that point in history, but if you could add the changes here, that would be great.

**Comment by TiFu** [comment]
>  When you merge this commit I will need to rebase and then I'll create another PR.

Related to #5521 or #6027 ? 

Actually, how do you want to proceed with #5521 ? Do you want to rebase it onto `ts-refactor-master` or should I force push `ts-refactor-master` to `ts-refactor` and essentially rename `ts-refactor-master` that way?

**Comment by bodograumann** [comment]
Related to both actually. I have taken the clean up commits out of #5521 and would propose them in a separat PR.

As for the branches, I would be fine with continuing to work on `typescript-refactor-master`, as I have already rebased on it.
My hope is that we can merge an experimental version into master sooner than later and than continue working there. Would you be able to merge into master at that point?

**Comment by TiFu** [comment]
> Would you be able to merge into master at that point?

I would be fine with merging it into `master` - After we are done merging everything, I'll file a PR with the relevant changes and CC everyone required. We'll probably have to check with some of the core team members too because there are changes that touch the core system (like `DefaultCodegen`).

**Pull request merged**
