### PR TITLE
 [RUST-AXUM] fix generator not handling application/x-www-form-urlencoded request content, update for initial fix #18061 

### PR DESCRIPTION
**Pull request by denisbog**
### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the quick fix

cc @linxGnu

**Comment by linxGnu** [comment]
@denisbog 
Could you please add more integration tests? 

You can clone & modify: https://github.com/OpenAPITools/openapi-generator/blob/master/bin/configs/manual/rust-axum-petstore-with-fake-endpoints-models-for-testing.yaml 

Please pick a sample under: https://github.com/OpenAPITools/openapi-generator/tree/master/samples as the input_spec. The sample should contains `application/x-www-form-urlencoded`

**Comment by wing328** [comment]
what about creating modules/openapi-generator/src/test/resources/3_0/rust-axum/petstore.yaml based on modules/openapi-generator/src/test/resources/3_0/petstore.yaml and add more fake endpoints to cover this change?

**Comment by denisbog** [comment]
`modules/openapi-generator/src/test/resources/3_0/petstore.yaml` and `modules/openapi-generator/src/test/resources/2_0/rust-server/petstore-with-fake-endpoints-models-for-testing.yaml` already include calls for `application/x-www-form-urlencoded` - both files are part of the rust-axum tests

```
    post:
      tags:
        - pet
      summary: Updates a pet in the store with form data
      description: ''
      operationId: updatePetWithForm
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  description: Updated name of the pet
                  type: string
                status:
                  description: Updated status of the pet
                  type: string
```

**Comment by wing328** [comment]
@linxGnu are you ok with this change?

**Comment by linxGnu** [comment]
@denisbog Thank you for making the change. Just wanna confirm, did you run follow tests?

```bash
./bin/generate-samples.sh ./bin/configs/manual/*.yaml
 mvn integration-test -f samples/server/petstore/rust-axum/pom.xml
```

**Comment by denisbog** [comment]
Hi, yes I did run the tests

**Comment by linxGnu** [comment]
Thank you. LGTM.
kindly ping @wing328

**Pull request merged**
