### PR TITLE
[OCAML] Fixes cloud.drone.io ocaml-test

### PR DESCRIPTION
**Pull request by spacether**
CI tests in cloud.drone.io were failing because of ppx_deriving's dependency on unpinned ocaml-migrate-parsetree. Per this issue https://github.com/ocaml-ppx/ocaml-migrate-parsetree/issues/87
We are getting the error `ocaml-migrate-parsetree.1.4.0: Bad checksum` when using the latest version. The suggested fix is to pin to ocaml-migrate-parsetree.1.3.1
That's what this PR does

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

OCaml | @cgensoul (2019/08)

### CODE REVIEW

**Comment by spacether** [comment]
@wing328 any idea why the cloud.drone.io tests did not run?
My update turned it back on in CI/.drone.yml

**Comment by wing328** [comment]
Thanks for the PR.

We commented it out since it's failing due to the reason you mentioned above.

**Comment by wing328** [comment]
@spacether thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Comment by wing328** [comment]
Btw, I've to make minor changes to make it work: https://github.com/OpenAPITools/openapi-generator/blob/master/CI/.drone.yml#L11-L12

**Pull request merged**
