### PR TITLE
[cpp-qt-client] New `makeOperationsVirtual` option

### LINKED ISSUE #19512: [REQ] [cpp-qt-client] Make generated methods optionally virtual
### Is your feature request related to a problem? Please describe.

I use cpp-qt-client to generate code by OpenApi specs. Then this code is used by my modules. Now I want to create a unit test for my code. To do this I have to mock up generated code. I've tried to mock up web service but this approach makes my unit tests less reliable and much slower (I've tried karate-netty framework and it takes 4 seconds just to startup and the same time to stop). I would like to make it in a proper way an mock up all dependencies of testing code. To do this I could do the following: derive and mock class from xxxDefaultApi and override get/post requests and reemit results signals from this mocking class. Described [here](https://google.github.io/googletest/gmock_for_dummies.html#how-to-define-it). This should work pretty straightforward and simple.

## Describe the solution you'd like

I want to make all generated get/post/head methods virtual. And make this behavior optional and disabled by default. I don't see too much harm here, because generated xxxDefaultAPI is already derived from QObject. So all sometimes undesirable features of C++ (RTTI, vtables) are already used.

## Describe alternatives you've considered

Use another approach with templates described here: https://google.github.io/googletest/gmock_cook_book.html#MockingNonVirtualMethods
And this is not a preferable solution because moc doesn't work with templates. And then I have to trick with that and probably use handlers instead of signals in this template class.

## Additional context

Maybe a little example. You can see proposed changes in generated code for simple example [here](https://github.com/limentas/openapi-cpp-qt-example/commit/f590d8729d65e13f9dda0b549d0a8ebff007e5ee?diff=split&w=0)

I can make a PR with the implemntation. Any thoughts, ideas, concerns?

### PR DESCRIPTION
**Pull request by limentas**
This PR implements new `makeOperationsVirtual` option for `cpp-qt-client` generator. If this option has true value then generated operations become virtual. This allows to easily mock up generated code and unit test the code which uses generated classes. You can find example of generated code here as a [diff](https://github.com/limentas/openapi-cpp-qt-example/commit/f590d8729d65e13f9dda0b549d0a8ebff007e5ee?diff=split&w=0). On the left side the code how it looks like before the changes or with default value of the new option. And on the right side the code how it looks like after the changes and with the option set to true.

Fix #19512

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
@ravinikam @stkrwork @etherealjoy @martindelille @muttleyxd

### CODE REVIEW

**Review by muttleyxd — APPROVED** [review]
Looks good, I wonder if it shouldn't be set to `true` by default. Both ways are fine for me though.

**Comment by limentas** [comment]
Thanks for your review.
Talking about making the option `true` by default. My point was to not change current behavior. But I don't see any harm if it is on by default. Since *Api class already has QObject as a parent it already has virtual table. I also don't see a code that can be broken with this change as well. But maybe I'm missing something.

**Comment by MartinDelille** [comment]
Why not just adding the `virtual` keyword and without the option ?

**Comment by limentas** [comment]
My intention is to not break something. Although I don't foreseen problems I may miss something. If you guys think that we can make this behavior default. I'm all for it.

**Comment by wing328** [comment]
> My intention is to not break something. Although I don't foreseen problems I may miss something. If you guys think that we can make this behavior default. I'm all for it.

Thanks for taking consideration into backward compatibility.

Upcoming release allows breaking changes with fallbacks so please set the option to true by default and we will see if any user encounters issues with this enhancement.

**Comment by limentas** [comment]
@wing328 Thank you for your input. This totally makes sense.
I've made the new parameter `true` by default.

**Comment by wing328** [comment]
can you please update the samples (step 3) as well as we should see some changes in the c++ qt petstore client?

**Comment by limentas** [comment]
> can you please update the samples (step 3) as well as we should see some changes in the c++ qt petstore client?

Thanks for reminder. Ut turned out I've made the property `true` by default in a wrong way. I figured out and fixed the issues.

**Comment by MartinDelille** [comment]
Happy to see new contributor to the qt cpp generator! 🎉

**Pull request merged**
