### PR TITLE
[GO] fix: correctly use oneOf path parameters

### LINKED ISSUE #14028: [BUG][GO] oneOf path parameters pointer is used as path parameter in request
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When a path parameter is a oneOf the whole oneOf is serialized and not one of the set values.

image

This is caused by the `parameterToString` method which serializes the struct to a string

```go
func parameterToString(obj interface{}, collectionFormat string) string {
	var delimiter string

	switch collectionFormat {
	case "pipes":
		delimiter = "|"
	case "ssv":
		delimiter = " "
	case "tsv":
		delimiter = "\t"
	case "csv":
		delimiter = ","
	}

	if reflect.TypeOf(obj).Kind() == reflect.Slice {
		return strings.Trim(strings.Replace(fmt.Sprint(obj), " ", delimiter, -1), "[]")
	} else if t, ok := obj.(time.Time); ok {
		return t.Format(time.RFC3339)
	}

	return fmt.Sprintf("%v", obj) // <---- ## HERE ##
}
```

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

https://gist.github.com/NickUfer/e5f80d9d2173344b4b3331df83e2080e

##### Generation Details

config file:
```yml
disallowAdditionalPropertiesIfNotPresent: true
packageName: directusclient
generateInterfaces: true
structPrefix: true
enumClassPrefix: true
```

cmd:
```
generate -i /tmp/oas.yaml -g go -o "/tmp/directusclient" -c /tmp/go.yml
```

### PR DESCRIPTION
**Pull request by NickUfer**
Fixes #14028

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04)

### CODE REVIEW

**Comment by WhoLet2DogsOut** [comment]
Hi, may I ask if it would be possible to add this fix into new version of generator? OpenApi generator is not usable for us without OneOf working properly.

**Comment by NickUfer** [comment]
Well, I don't know man. Since I created this PR a lot of stuff changed again which doesn't work or wasn't properly tested and this change can't be merged because I would have to rewrite everything to this new system which outputs be `reflect.Value+value` in a query parameter... and right now rewriting this is the last thing I want to do as it is annoying

**Comment by NickUfer** [comment]
I will actually just maintain my own private fork of the version I created this PR for and add more fixes to it if I need them. I will come back in 1 or 2 years to this project and hope it is more stable. Right now there are too many problems and to see that there are actively added more problems... no thanks

**Comment by WhoLet2DogsOut** [comment]
Totally understand, thank you!

**Pull request closed without merging**
