### PR TITLE
[typescript] add http info calls to access headers

### PR DESCRIPTION
**Pull request by Robbilie**
Currently it is not possible to access response headers. Other generated clients solve this by allowing you to not only retrieve the parsed response but also a wrapper which includes the parsed response and the original request. This PR implements such a functionality in a non-destructive way.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

### CODE REVIEW

**Comment by Robbilie** [comment]
@macjohnny @amakhrov @wing328 is there anything else necessary besides running the scripts? :)

**Review by amakhrov — APPROVED** [review]
Thanks for PR @Robbilie  - looks good me!

**Review by macjohnny — COMMENTED** [review]
IIUC this is a breaking change since the method names and return types change, or am I missing something?

**Comment by amakhrov** [comment]
@macjohnny the breaking change is inside an internal class (e.g. `apis/PetApi.ts`). It's not exported outside the package.
Instead, the public interface is wrappers in `types/` (e.g. `types/PromiseApi.ts`), that are then re-exported from the main `index.ts`: https://github.com/OpenAPITools/openapi-generator/blob/c7f97f635a9ca953274829a0b76b8e4a94ff4153/samples/openapi3/client/petstore/typescript/builds/browser/index.ts#L11
And the changes in those public classes are additive - the old methods are preserved.

I'm not sure if the classes under `apis/` are supposed to be used directly by the application code. Probably not - based on how they all take the same `response: ResponseContext` argument.

**Pull request merged**
