### PR TITLE
Ktor server upgrade

### PR DESCRIPTION
**Pull request by rsinukov**
#9087 

Hi, 
I am part of the Ktor team. 
This PR updates Ktor server generator to the newest version of Kotlin and Ktor. Changes:
* Add flag to choose between using `Locations` feature or default routing
* Generate locations for `get` requests too
* Update to the latest version and fix warnings and errors
* Minor codestyle fixes

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
 ...
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee]
  @jimschubert (2017/09), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

### CODE REVIEW

**Comment by wing328** [comment]
@rsinukov thanks for the PR. Is it a breaking change with or without fallback?

**Comment by rsinukov** [comment]
I am not sure what exactly you mean by breaking change. It will generate projects with updated dependencies and update usage of Ktor to the newest API. So that generated code will be changed and users will need to update their code. In terms of the generator itself, I added one flag, that has the default value to support previous behaviour. So no breaking change here, only additive.

**Comment by wing328** [comment]
> So that generated code will be changed and users will need to update their code.

Looks like a breaking change as the users will need to update their code accordingly so this change should target 6.0.x branch instead.

I wonder if the new feature `featureLocations` can be filed with another PR separately or it has a dependency on the latest version of Ktor

**Comment by rsinukov** [comment]
> I wonder if the new feature featureLocations can be filed by another PR separately or it has a dependency on the latest version of Ktor

It can be in separate PR in theory, but to make it work as it is designed, it would still be a breaking change.

**Comment by wing328** [comment]
To move it forward, I will include it in the upcoming "minor" release 5.2.0 and created kotlin-server-deprecated generator in case users want to stick with the current version/output.

I'll merge this after the 5.1.1 release due shortly.

**Comment by rsinukov** [comment]
Ok, I'll update PR and will keep old version in `kotlin-server-deprecated`

**Comment by wing328** [comment]
Please hold on ...

**Comment by wing328** [comment]
Merged. Please file a PR to create `kotlin-server-deprecated` later when you've time.

**Comment by wing328** [comment]
@rsinukov when you've time, please also review https://github.com/OpenAPITools/openapi-generator/pull/9358 when you've time and let the author your opinion on the change.

**Comment by rsinukov** [comment]
Resolves #9087

**Comment by rsinukov** [comment]
@wing328 I just opened PR with deprecated version of the generator #9365

**Pull request merged**
