### PR TITLE
Added support for jsonb in java jaxrs spec.

### PR DESCRIPTION
**Pull request by patrikostberg**
This PR addresses: #4104
Added support for jsonb in java jaxrs spec. User can now disable Jackson and enable jsonb annotations.

### PR checklist

- [+] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [+] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [+] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [+] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [+] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608

### CODE REVIEW

**Comment by wing328** [comment]
@patrikostberg thanks for the PR. What about customizing the templates via the `-t` option instead of creating 2 more options? We tend to avoid adding too many options if possible such as customizing the templates.

**Comment by patrikostberg** [comment]
@wing328 what I understand about the template/-t option is that it is only intended for when you have your own templates. Since Jsonb is part of the JEE-specification I would expect others to want to use it (see PR related issue).
Would the PR be relevant with any changes? For example:
- Create annotationType option (instead of the 2 options created) which can be either none, jackson or jsonb.
- Making useJsonbAnnotations the only new option and if it is specified to true disable Jackson annotations.
- Make Jsonb its own library for the JavaJAXRSSpec generator. Requires no new option.

**Comment by danpfe** [comment]
@patrikostberg Hi Patrik, why did you close this? I myself am looking into this right now as I find it unnecessary to clutter code and deps with jackson-stuff when the middleware in question (like KumuluzEE, Liberty, Helidon, et cetara) in question already provides JSR-367-style annotation-support.

**Comment by bmhm** [comment]
PLEASE reopen this!! This would be sooo useful!

**Comment by aksth** [comment]
I am also in need of this. @patrikostberg @danpfe Can we reopen this?

**Comment by bmhm** [comment]
Also see
https://github.com/OpenAPITools/openapi-generator/issues/6881

**Comment by tomek-sn** [comment]
Hi, not sure if some see it :| . It it is an old thread. Is in the meanwile a solution for jsonb?

**Pull request closed without merging**
