### PR TITLE
C-libcurl cmake support specify path

### PR DESCRIPTION
**Pull request by katepangLiu**
About #11789

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR.

cc @zhemant (2018/11) @ityuhui (2019/12) @michelealbano (2020/03)

**Review by zhemant — APPROVED** [review]

**Comment by zhemant** [comment]
Thanks for the PR.

LGTM :+1:

**Review by ityuhui — APPROVED** [review]
LGTM

Thank you.

**Comment by wing328** [comment]
Tested locally and the result is good

**Pull request merged**
