### PR TITLE
Qt client handle deprecated

### PR DESCRIPTION
**Pull request by MartinDelille**
Add a `Q_DECL_DEPRECATED` declaration in front of operation or model properties according to the OpenAPI specification

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@ravinikam @stkrwork @etherealjoy @muttleyxd

### CODE REVIEW

**Comment by etherealjoy** [comment]
interesting.

**Comment by wing328** [comment]
@MartinDelille thanks for the PR. When you've time, can you please merge the latest master into your branch and regenerate the sampless?

**Comment by MartinDelille** [comment]
@wing328 Done

**Comment by wing328** [comment]
For reasons, you're still using 5.0.1-SNAPSHOT:
```
diff --git a/samples/client/petstore/cpp-qt5/.openapi-generator/VERSION b/samples/client/petstore/cpp-qt5/.openapi-generator/VERSION
index 3fa3b389a57..c30f0ec2be7 100644
--- a/samples/client/petstore/cpp-qt5/.openapi-generator/VERSION
+++ b/samples/client/petstore/cpp-qt5/.openapi-generator/VERSION
@@ -1 +1 @@
-5.0.1-SNAPSHOT
\ No newline at end of file
+5.1.0-SNAPSHOT
\ No newline at end of file
Perform git status
On branch pull/8766
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   samples/client/petstore/cpp-qt5/.openapi-generator/VERSION
```

I'll try to push a commit to this branch to fix it.

**Comment by MartinDelille** [comment]
Ok my bad: I didn't rebuild the package with `mvn clean package`.

**Review by etherealjoy — APPROVED** [review]

**Comment by wing328** [comment]
@MartinDelille thanks for the PR, which has been included in the v5.1.0 release: https://twitter.com/oas_generator/status/1373636654024380423

**Pull request merged**
