### PR TITLE
Add Elm petstore scripts to ensure-uptodate script

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Update Elm petstore client samples

cc @eriktim

### CODE REVIEW

**Comment by eriktim** [comment]
The changes we see here are caused by not enabling `elm-format` post-processing. Is there a way we can run this in the `ensure-up-to-date` script?

**Comment by wing328** [comment]
> The changes we see here are caused by not enabling elm-format post-processing. Is there a way we can run this in the ensure-up-to-date script?

Oh right. I'll try to add it to the ensure-up-to-date script.

**Comment by eriktim** [comment]
Great, thanks! One last thing: I think Elm 0.18 is tested with Travis, so that one will need `elm-format` as well.

**Comment by wing328** [comment]
> Great, thanks! One last thing: I think Elm 0.18 is tested with Travis, so that one will need elm-format as well.

The Travis does not run the elm shell script so I don't think we need to install elm-format in Travis (which passes: https://travis-ci.org/OpenAPITools/openapi-generator/builds/528494033?utm_source=github_status&utm_medium=notification)

**Comment by wing328** [comment]
I'd to comment out the elm script in the ensure-up-to-date file since it's causing errors (code not formatted correctly when running elm script in the CircleCI) while the tests passed before the merge)

**Pull request merged**
