### PR TITLE
[JAVA] fix toUrlQueryString for BigDecimal

### LINKED ISSUE #15361: [BUG][JAVA] incorrect supportUrlQuery generation for generic number map
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The Java code generated for apache-httpclient can result in incorrect code for `toUrlQueryString` method. If the openapi definition contains an object that is a dictionary with numbers as value type, without any format, the method seems to be incorrect for that object.

##### openapi-generator version

6.5.0, looks to be the case since 6.3.0.

##### OpenAPI declaration file content or url

Example OpenAPI definition resulting in incorrect code:

```yaml
openapi: 3.0.1
info:
  title: Some example
  version: 0.0.1
paths:
  /example/someMethod:
    get:
      description: get some object
      operationId: retrieveSomething
      responses:
        200:
          description: The response with results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
components:
  schemas:
    ExampleResponse:
      type: object
      properties:
        someId:
          type: number
        results:
          type: object
          additionalProperties:
            type: number
```

##### Generation Details

Using the generator-cli with something like 
```
openapi-generator-cli generate -i example.yaml -g java --library apache-httpclient -o example
```

results in ExampleResponse.java to be generated with line 234/235:

```
          joiner.add(getResults().get(_key).toUrlQueryString(String.format("%sresults%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix))));
```

Here `getResults()` returns a `Map<String, BigDecimal>`, so `toUrlQueryString` is called on BigDecimal, and this is incorrect.
When using `format: double`, the method is generated correctly.

##### Steps to reproduce

See above.

##### Related issues/PRs

Looks to be introduced with https://github.com/OpenAPITools/openapi-generator/pull/14417.

##### Suggest a fix

Had a quick look, based on https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/pojo.mustache I'd already expect it to generate appropriate code in the `{{^items.isModel}}` block? Unless the BigDecimal type causes it to end up in `{{#items.isModel}}`? And if that's the case, I wouldn't know where to start.

### PR DESCRIPTION
**Pull request by martin-mfg**
fix #15361

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
   @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. can we add a test to modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml to include another fake endpoint with query parameter of object including a bigdecimal property to. ensure the output compiles?

**Comment by martin-mfg** [comment]
Hi,
Yes, adding a test endpoint sounds good. **I am just wondering why it should be added in modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml?** The fixed problem occurs with Java native and Java apache-httpclient, but not with Java okhttp-gson.

As a quick test, I instead added a new endpoint to modules/openapi-generator/src/test/resources/3_0/java/native/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml and modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml. This covers Java native and Java apache-httpclient, but also many other generators. And with these other generators, is causes problems. I didn't check yet whether that is due to valid bugs in the other generators which need fixing, or whether I just made a mistake with test setup etc. But before I further investigate this, I wanted to clarify the above question - in which yaml files should the test endpoint be added? Indeed (only) modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml?

**Comment by martin-mfg** [comment]
@wing328 It's done.
The failing dart tests also occur in main branch, so shouldn't be caused by this PR.

**Comment by wing328** [comment]
right, please ignore the failure in the dart samples for the time being.

**Pull request merged**
