### PR TITLE
[rust] Update to modern hyper and futures crates

### LINKED ISSUE #8400: [REQ] Upgrade Hyper/packages in Rust Client
### Is your feature request related to a problem? Please describe.

The hyper package used in the rust client "rust" generator is very old, sat at version 0.11 - there was a big shift in the way it works between 0.11 and 0.12. It makes sense to upgrade this to 0.14.

## Describe the solution you'd like

Upgrade the package to a newer version beyond 0.12

## Describe alternatives you've considered

The alternative to not upgrading is a real pain, where my application relies heavily upon `hyper` so I have that package within my application - to work with an older version I'd need to import `hyper 0.11` and the `tokio_core` packages (for the handler to connect). It was easier to just use `reqwest` (1 extra library vs 2) however, it would be nice to not have to use any extra packages when I already have a newer hyper on hand.

Granted, I need to make these changes because I'm changing the default configuration of `apis` within my application, as the `Configuration` struct is immutable I'm unable to change it after the fact. Ideally, configuration should be decoupled from the http client library creation but, that's probably a larger task than it is to just upgrade the packages (also unsure how other packages are built and if `configuration + client` is a commonality)

### PR DESCRIPTION
**Pull request by softdevca**
The hyper and futures crates used by the Rust client were significantly out of date.  This pull request addresses the issue by updating futures to 0.3.* and hyper to 0.14.*. 

The newer futures crate required a breaking change in the generated APIs - the return types are now `Future<Result>` instead of `Future<Output,Error>`

The newer version of hyper is required to work with modern versions of tokio.

Fixes #8400

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05)

### CODE REVIEW

**Comment by wing328** [comment]
@softdevca thanks for the PR. Can you please PM me via [Slack](https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM) to discuss this change further?

**Comment by wing328** [comment]
Can you please resolve the merge conflicts when you've time?

Upcoming 5.3.0 release allow breaking changes without fallback so I think we can include this change if all tests are good.

**Comment by wing328** [comment]
Looks like the rebase went wrong and therefore this PR contains many commits that do not belong to you.

Can you please create a new PR by cherry-picking the commits that belong to you?

**Comment by BroderickCarlin** [comment]
@softdevca is this PR still being worked on? If this just needs a rebase + cherrypick I'm happy to help to get this pushed over the line

**Comment by softdevca** [comment]
I haven't had an opportunity.  Please feel free, and thank you!

**Comment by BroderickCarlin** [comment]
@softdevca would you be able to provide me with push permissions to your fork/branch? That should allow us to not have to open a whole new PR

**Comment by softdevca** [comment]
> @softdevca would you be able to provide me with push permissions to your fork/branch? That should allow us to not have to open a whole new PR

Invite sent - thanks again.

**Comment by BroderickCarlin** [comment]
@softdevca @wing328 the rebase was cleaned up and the PR should be ready for a final review

**Comment by wing328** [comment]
Tested with updated samples locally and the result is good
```
warning: `petstore-reqwest-async` (lib) generated 1 warning
warning: `petstore-hyper` (lib) generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 2.08s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.722 s
[INFO] Finished at: 2021-11-24T17:05:36+08:00
[INFO] ------------------------------------------------------------------------

```

I consider this a security fix to hyper (https://www.cvedetails.com/vulnerability-list/vendor_id-17878/Hyper.html) so that we can merge this into master (upcoming v5.3.1 is a patch release)

**Comment by wing328** [comment]
FYI. Samples updated via 962e8c42178

**Comment by softdevca** [comment]
Thanks for the assistance while other tasks took priority - appreciated!

**Pull request merged**
