### PR TITLE
Fix documentation - description of default Angular version

### PR DESCRIPTION
**Pull request by AGmakonts**
Documentation implies that v16 is the current default version when in reality it's only supported on v7.0.0 of openapi generator

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by AGmakonts** [comment]
@TiFu @taxpon @sebastianhaas @kenisteward  @Vrolijkx  @macjohnny @topce @akehir @petejohansonxo @amakhrov  @davidgamero  @mkusaka

**Comment by macjohnny** [comment]
The docs are valid for the corresponding release version only, so devs should refer to the docs of the older version whrn using it

**Comment by AGmakonts** [comment]
> The docs are valid for the corresponding release version only, so devs should refer to the docs of the older version whrn using it

I agree, but the current version, the latest official release is 6.6 and angular 16 is supported only in 7.0 so the docs are misleading. Either I did something horribly working and spent hours fighting with build errors without a reason or the docs are wrong. I see in the code for current release that previous version of Angular is the latest supported

**Comment by macjohnny** [comment]
If I am not mistaken, the docs in https://openapi-generator.tech/docs/generators/typescript-angular refer to the snapshot release (https://github.com/OpenAPITools/openapi-generator#11---compatibility). For the docs of a specific release, you could have a look at https://github.com/OpenAPITools/openapi-generator/blob/v6.6.0/docs/generators/typescript-angular.md.

@wing328 I think it would make sense to allow selecting the release version in https://openapi-generator.tech/docs, or at least refer to https://github.com/OpenAPITools/openapi-generator/blob/v6.6.0/docs for versioned docs, wdyt?
@AGmakonts would you like to contribute this improvement?

**Comment by AGmakonts** [comment]
Sure, just let me know which direction you prefer. Current setup is confusing, it would be better experience for developers to get the docs for the version that is installed by default. Adding simple disclaimer that the docs refer to latest snapshot would be a quick win. I will need to investigate how to add this version selector to generated docs sometime next week.

**Pull request closed without merging**
