### PR TITLE
Add support for Micronaut Client

### PR DESCRIPTION
**Pull request by andriy-dmytruk**
This PR adds support to generate Micronaut Declerative Java client by creating a new generator for that.

For more information about micronaut refer to:
* [micronaut.io](https://micronaut.io/)
* [Micronaut User Guide](https://docs.micronaut.io/latest/guide/)

I tested generation on multiple configuration files, and run all the requirements as specified when creating PR.

Java Technical committee: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)  
Micronaut creator: @graemerocher

### CODE REVIEW

**Comment by wing328** [comment]
@andriy-dmytruk thanks for the PR. What about adding `micronaut` as a library option in the existing `java` generator, which already supports Jersey 2.x, retrofit 2.x, resttemplate, resteasy, okhttp-gson and more?

**Comment by andriy-dmytruk** [comment]
@wing328 Thanks for the feedback.
Yes, it is possible to do this if it is considered a better solution than what is given here. In fact, it won't be very hard.
However, there are quite some differences. Multiple files that are added for the libraries do not really seem to be appropriate for a framework to me, so I will need to remove them there.
Also, I am planning to work on Micronaut server implementation after this. So I wonder if it is somehow possible to reuse some of the mustache files and not copy everything?

**Comment by wing328** [comment]
@andriy-dmytruk when you've time, can you please PM me via Slack to further discuss this?

https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by wing328** [comment]
Tested locally and the result is good
```
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[INFO] Replacing original artifact with shaded artifact.
[INFO] Replacing /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java-micronaut-client/target/petstore-micronaut-1.0.0.jar with /Users/williamcheng/Code/openapi-generator/samples/client/petstore/java-micronaut-client/target/petstore-micronaut-1.0.0-shaded.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.536 s
[INFO] Finished at: 2021-08-15T22:32:26+08:00
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
