### PR TITLE
[Elm] Fix not sanitizing param name

### PR DESCRIPTION
**Pull request by Qluxzz**
From the example I added, when a schema has a property with a space in it like the following example:
```yml
schema:
  type: object
  properties:
    "name with spaces":
      type: string
```
The resulting function is:
```elm
paramSanitizeTestPost : Maybe String -> Api.Request ()
paramSanitizeTestPost name with spaces =
    Api.request
        "POST"
        "/param-sanitize-test"
        []
        []
        []
        (Just <| Http.multipartBody <| List.filterMap identity [ Maybe.map (Http.stringPart "name with spaces") name with spaces ])
        (Json.Decode.succeed ())
```

Which doesn't compile since the annotation says it should take one argument, but now it takes three (name, with, and spaces). And the same issue when we try to map it to the argument here:
```elm
(Just 
    <| Http.multipartBody 
    <| List.filterMap identity [ Maybe.map (Http.stringPart "name with spaces") name with spaces ]
                                                                                  ^----^----^
)
```
This PR fixes so we sanitize/normalize the param name. And also fix so we use the paramName partial when mapping multi part body arguments, which previously just used `{{paramName}}` to add it.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@eriktim

### CODE REVIEW

**Review by eriktim — APPROVED** [review]
LGTM

**Comment by wing328** [comment]
@Qluxzz thanks for the PR

I've filed https://github.com/OpenAPITools/openapi-generator/pull/20173 instead as we usually override `toParamName` to handle other edge cases such as reserved word, better support for parameter name mapping, etc.

can you please give it a try to see if this approach works for you as well?

**Comment by wing328** [comment]
@Qluxzz when you've time, can you please PM me via Slack?

https://join.slack.com/t/openapi-generator/shared_invite/zt-2uoef5v0g-XGwo8~2oJ3EoziDSO1CmdQ

**Comment by Qluxzz** [comment]
I've reworked the solution so we now override toParamName instead of using the camelcase lambda, this required some changes in the templates where we should use `baseName` instead of the sanitized `paramName`.

I also expanded the endpoint I added for testing, so it tests the different parameter types.

**Comment by wing328** [comment]
lgtm. thanks for the PR

**Pull request merged**
