### PR TITLE
[BUG][Kotlin] Add support for collection of generic classes (Jackson / Gson)

### PR DESCRIPTION
**Pull request by trietsch**
Added support for collecting lists of objects for Jackson and Gson. ~I don't have enough knowledge about Moshi, so maybe that could be fixed by someone else in another PR.~
Support for Moshi added by @adamsz-lume, included in this PR.

### Linked issue
[[BUG][Kotlin] Generated clients cannot serialize into `List<T>`](https://github.com/OpenAPITools/openapi-generator/issues/8560)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by trietsch** [comment]
Tagging technical committee: @jimschubert, @dr4ke616, @karismann, @Zomzog, @andrewemery, @4brunum @yutaka0m

**Comment by wing328** [comment]
The CI failure has been resolved in the master. Please merge the latest master into your branch to fix the CI failures.

**Comment by trietsch** [comment]
@wing328 merged master into my branch. CI is running now.

**Comment by Mordag** [comment]
@trietsch I just had a look at the CI and there seems to be a few issues with your changes (if I am not wrong). Can you have another look at your implementation. https://app.shippable.com/github/OpenAPITools/openapi-generator/runs/27273/1/console

**Comment by trietsch** [comment]
Thanks for the mention. It's the Moshi part, so I'm tagging @adamsz-lume. Could you have a look?

**Comment by 4brunu** [comment]
I never used this feature, so it's hard for me to review it.
@Mordag since you already contributed to OpenAPI and you comment on the issue related to this, could you please help to review this PR?
Thanks

**Review by Mordag — APPROVED** [review]
Looks good to me 👍 
I will try to take care of the moshi part sometime next month.

**Comment by 4brunu** [comment]
Thanks for helping 👍

**Comment by wing328** [comment]
@trietsch thanks for the PR but looks like there are some issues with the commits (https://github.com/OpenAPITools/openapi-generator/pull/8796/commits) as it contains 200+ commits authored by the others. I've seen similar issues due to incorrect rebase of the PR.

I wonder if it would be easier to file a new one based on the latest master instead.

**Comment by trietsch** [comment]
Closing in favor of creating a new PR.

**Comment by trietsch** [comment]
@wing328 please check out the new PR, which can be found here: https://github.com/OpenAPITools/openapi-generator/pull/9918

**Pull request closed without merging**
