### PR TITLE
[Java Libraries] Jakarta Validation API support useJakartaEe flag

### LINKED ISSUE #19398: [BUG] config option useJakartaEe in java generator has no effect
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When executing a code generation for the provided specification with 7.7.0 the generated file will contain validation annotation from the package "javax.validation". When doing the same in version 7.8.0 the corresponding annotations are imported from the package "jakarta.validation", even though there is a config option "useJakartaEe" that is set to false and claims to control this behavior.

##### openapi-generator version

7.8.0 contains the issue

7.7.0 is working fine

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Test
  description: Test
paths: {}
components:
  schemas:
    test:
      type: object
      required:
        - test
      properties:
        test:
          type: string
          minLength: 19

```

##### Generation Details

Gradle plugin definition:

```
task generateTest(type: GenerateTask)
tasks.named("generateCustomerEvent").get().setProperty("inputSpec", "PutLocationOfFileHere")

tasks.withType(GenerateTask).configureEach {
  generatorName = "java"
  outputDir = "${buildDir}/generated/sources"

  configOptions = [
    performBeanValidation: "true",
    useBeanValidation: "true",
    library: "webclient",
    dateLibrary: "custom",
    useJakartaEe: "false"
  ]
  globalProperties = [
    apis: "false",
    models: ""
  ]
  typeMappings = [
    DateTime: "Instant",
    Date: "java.time.LocalDate",
    Uuid: "UUID"
  ]
  importMappings = [
    Instant: "java.time.Instant",
    UUID: "java.util.UUID"
  ]
}
```

##### Steps to reproduce

Execute the generation for the provided specification in version 7.7.0 and 7.8.0.

### PR DESCRIPTION
**Pull request by horaceli**
Fixes #19398 and #19437

For context, `useJakartaEe` previously only determined the javax/jakarta imports for validation-api, not the maven Jakarta dependency version (that only worked for annotation-api).

#18332 and #19171 aligned the validation-api to use `jakarta.*` package as a previous commit had already upgraded the validation-api version to 3.x. Unfortunately this caused a regression as end users can manually specify 2.x, in which case they would still need the `javax.*` package. This partially reverts those changes and once again makes the javax/jakarta package configurable.

This PR allows the use of `useJakartaEe` flag in the same way Jakarta annotation-api switches between `javax.*` and `jakarta.*` packages. This also switches between `jakarta.validation-api` 2 and 3 so the correct dependencies are included.

Note that it only applies to generators in `Java/libraries`

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

### CODE REVIEW

**Comment by Chrimle** [comment]
Hi, this effectively requires that the `useJakartaEe` configOption to be set to `true` to keep existing behaviour. Hence, this is a **breaking change**!

**Comment by horaceli** [comment]
This is basically a partial revert of #18332 (which caused a regression and broke Jakarta 2 validation-api).

The improvement here is it also imports the correct version in maven by default (but can easily be overridden by explicitly specifying the validation-api version)

**Comment by Chrimle** [comment]
To utilize `useJakartaEe` consistently across the templates is a much better solution! But this change should perhaps be re-labelled. `@jakarta.*` has essentially been hard-coded for a long time, so this is a breaking change. However, as pointed out, this was not the intention - but wouldn't this at least be a _bug fix_?

**Comment by wing328** [comment]
@Chrimle thanks for the feedback. Just labelled this PR as bug fixes as well.

**Pull request merged**
