### PR TITLE
[Java][Client] Support annotationLibrary=none

### PR DESCRIPTION
**Pull request by cachescrubber**
Support annotationLibrary=none

effectively removes swagger 1 from the java clients. Fallback is available using **annotationLibrary=swagger1**.

Relates to

- https://github.com/OpenAPITools/openapi-generator/pull/8801
- https://github.com/OpenAPITools/openapi-generator/issues/11555

### PR checklist
 
- [x ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

@welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02)

### CODE REVIEW

**Review by borsch — APPROVED** [review]
Java related changes looks good to me, but seems likes you did/pull some unrelated to java changes

**Comment by cachescrubber** [comment]
> but seems likes you did/pull some unrelated to java changes

This is related to https://github.com/OpenAPITools/openapi-generator/pull/12424. I had to re-generate **all** model tests because stale model test classes in the samples caused the build to fail.

**Comment by mgohin** [comment]
Any updates ?

**Comment by wing328** [comment]
Can you please resolve the merge conflicts when you've time?

**Comment by cachescrubber** [comment]
@wing328 I finally managed to bring this up to date.

**Comment by floka94** [comment]
Hey Guys, any updates here @wing328 ? Looking forward to the feature ❤️

**Comment by cachescrubber** [comment]
@wing328 I once again brought this up to date, please review.

**Comment by wing328** [comment]
Looks like lots of test files were removed, e.g. samples/client/petstore/java/jersey3/src/test/java/org/openapitools/client/JSONComposedSchemaTest.java

did you purge all the samples folders and regenerate samples?

**Comment by cachescrubber** [comment]
> did you purge all the samples folders and regenerate samples?

Yes, I purged **all** generated samples and re-created them. I did that because generated tests are never re-generated. Since I removed the swagger 1 dependency,  the tests would no longer compile.

**Comment by cachescrubber** [comment]
@wing328  See #13869. We need to sort out the generated test code issue there.

**Comment by wing328** [comment]
Will continue to work on #13869 (already pushed 2 commits to clean up java feign sample)

Closing this one for the time being.

**Pull request closed without merging**
