### PR TITLE
fix(JavaSpring): use optional datatype in generated method signature

### PR DESCRIPTION
**Pull request by quackes**
### PR checklist

- [ X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

### Description of the PR

fixes: https://github.com/OpenAPITools/openapi-generator/issues/1649

### CODE REVIEW

**Comment by cbornet** [comment]
Using `Optional` in method signature is a smell. Please read https://dzone.com/articles/using-optional-correctly-is-not-optional
Tools such as IntelliJ IDEA will also highlight this as a smell.

**Comment by quackes** [comment]
The generator uses optional for non-required parameters, but not uses it consequently, and produces compile errors. 

i tried to fix that compile errors.

**Comment by cbornet** [comment]
We should even remove completely the `useOptional` option in v4 which was a mistake from the beginning !

**Comment by cbornet** [comment]
> The generator uses optional for non-required parameters, but not uses it consequently, and produces compile errors. i tried to fix that compile errors.

OK. In that case the PR is legit. I would recommend however not to use the `useOptional` option at all.

**Comment by cbornet** [comment]
@quackes did you regenerate the samples ? It had no effect ?

**Comment by quackes** [comment]
i did regenerate the samples, and no files were changed

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
@quackes in the master, `optionalDataType` has been removed. Would that meet your need?

**Comment by wing328** [comment]
Closing this for the time being. Let us know if we should still proceed with this.

**Comment by quackes** [comment]
I‘m fine. dont using optional anymore
thanks

**Pull request closed without merging**
