### PR TITLE
chore(c): add fix compile usage template spacing

### PR DESCRIPTION
**Pull request by j-mendez**
* Fix space compile instructions start for C

Spacing issue example on the markdown for compile instructions

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.0.1) (patch release), `6.1.x` (breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@j-mendez thanks for the PR.

cc @zhemant (2018/11) @ityuhui (2019/12) @michelealbano (2020/03)

**Comment by wing328** [comment]
the sample (readme) is not up-to-date. did you run some linters on the readme (markdown)?

**Comment by j-mendez** [comment]
> @j-mendez thanks for the PR.
> 
> cc @zhemant (2018/11) @ityuhui (2019/12) @michelealbano (2020/03)



> the sample (readme) is not up-to-date. did you run some linters on the readme (markdown)?

You are welcome, I initial did not. I had `prettier` enabled and it adjusted some of the markdown extra whitespace. Just toggled off the `prettier` formatting and re-pushed and ran the commands for linters.

**Comment by ityuhui** [comment]
Hi 
I don't prefer this change.
From the official doc https://gcc.gnu.org/onlinedocs/gcc-12.1.0/gcc/Link-Options.html#Link-Options, we can see

> -llibrary
> -l library
> Search the library named library when linking. (The second alternative with the library as a separate argument is only for POSIX compliance and is not recommended.)

Both formats are correct, but the GCC documentation does not recommend the latter.

**Comment by j-mendez** [comment]
@ityuhui thank you for sharing, closing for the default recommendations.

**Pull request closed without merging**
