### PR TITLE
Adds Dart Dio generator

### PR DESCRIPTION
**Pull request by athornz**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Adds a generator for the Dart Dio library (https://github.com/flutterchina/dio)

CC @ircecho @swipesight @jaumard @nickmeinhold

### CODE REVIEW

**Comment by nickmeinhold** [comment]
Hi @athornz! 

Were you aware there's an issue for this (#3785)?  I had said I would work on it but I haven't started so there's no duplicated effort I'm aware of.  It's helpful to co-ordinate via issues though so we can avoid wasting anyone's time.

The reason I haven't gotten there (excuses, excuses) is I was working toward having Dio (and other clients) available as options rather than separate generators.  I wanted to get some testing up first (finally got that up yesterday) and do some cleaning up and improvements, there's a bunch of issues up if you're interested. Anyway, the reason for my ramble is - just wondering what your thoughts are about Dio as an option rather than a separate generator?  

Some options that spring to mind:
- merge this PR and leave it as a separate generator 
- merge this PR and someone can have a go at combining into an option later 
- work on making this PR support Dio as an option rather than a separate generator

What would be your preference?

**Comment by wing328** [comment]
I suggest the following:

> merge this PR and someone can have a go at combining into an option later

so that we can collect feedback from the users on this new generator for the time being.

**Comment by athornz** [comment]
I agree a combined generator would be great (although a lot more work). I'm using this generator for a project so thought I would create a PR.

This generator uses built_vaue rather than json_serializable - would be great to see both as an option of a combined generator as well.

**Comment by wing328** [comment]
CircleCI failure has been fixed in the master.

**Pull request merged**
