### PR TITLE
Add group parameters support to PHP templates

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

For https://github.com/OpenAPITools/openapi-generator/issues/641

Still WIP:
- async method needs to be updated
- docstring needs to be updated
- fix test cases

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko for comment/feedback

### CODE REVIEW

**Comment by ybelenko** [comment]
@wing328 How it's realated to server PHP generators? Server side api controllers usually looks like:
```php
public function testEndpointParameters($request, $response, $args)
```
I would add an option to change models constructor from classic arguments list to associative array, but we can provide both.

**Comment by wing328** [comment]
> How it's realated to server PHP generators? Server side api controllers usually looks like:

The enhancement is for PHP client at the moment and you've raised a good point about model constructors (in clients or servers) accepting associative array instead.

**Comment by wing328** [comment]
OK. I'll use `array_key_exists`

For default value, I suggest we don't include that in the client as the server (backedn) should ensure the default value ( I think Python, Ruby, etc are following this approach to not set default value in the client side)

**Comment by wing328** [comment]
@ackintosh I've updated the PR based on your feedback. Please have another look when you've time.

**Comment by ackintosh** [comment]
> For default value, I suggest we don't include that in the client as the server (backend) should enforce the default value

Oh, I get it. That makes sense. 💡

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/1337

**Pull request closed without merging**
