### PR TITLE
fix(typescript-angular): don't escape properties and operationIds

### LINKED ISSUE #1943: [BUG] Params named "default" get replaced with "_default", resulting in incompatible clients
##### Description

My api has a request object that contains a key called `default`, however when I generate client code from this spec, it gets converted to `_default`. Since my api expects `default`, the generated client code does not work. 

I'm guessing this is escaping that happens in java since `default` is a java keyword. Is there any way around this?

Expected generated:
```ts
export interface RbacAddRoleRequest {
    default?: boolean;
```
Actual generated:
```ts
export interface RbacAddRoleRequest {
    _default?: boolean;
```
##### openapi-generator version

4.0.0

##### OpenAPI declaration file content or url

https://gist.github.com/seanlaff/d2aef0244adeeea95c1396952b28d987

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v4.0.0-beta generate \
    -i /local/test.yaml \
    -g typescript-axios \
    -o /local/out/ts
```

### PR DESCRIPTION
**Pull request by eseliger**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Closes #1943 
In TypeScript, all those properties are allowed for property names and class member functions, hence the split. This should allow for the maximum amount of fields that won't need to be escaped.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07)

### CODE REVIEW

**Comment by eseliger** [comment]
Damn, you are right. Since this creates wrong interfaces and sends wrong query params, maybe it makes sense to group the parameters in a single argument object hash, then the arguments from the list would be allowed .. 🤔 Any suggestions from your side? I would volunteer to fix that.

**Comment by macjohnny** [comment]
@eseliger absolutely, collecting the parameters in one single object is good solution and avoids many naming conflicts. there is a related issue here: https://github.com/OpenAPITools/openapi-generator/issues/865

any contribution would be highly appreciated. I suggest to add an option (the typescript-fetch generator, which recently added an option to choose between the two styles https://github.com/OpenAPITools/openapi-generator/pull/3351) and simply wrap the method parameters into curly braces `{` `}` if the option is set. There is also rewrite of the typescript generators https://github.com/OpenAPITools/openapi-generator/issues/802 that might also address this issue.

**Comment by eseliger** [comment]
Okay I would go ahead now and port that solution for ts-angular as well, so we can use this separation of variables in here

**Comment by wing328** [comment]
@eseliger when this PR is ready for review, can you please resolve the merge conflicts and let us know? Thanks.

**Comment by wing328** [comment]
Closing this for the time being as there's no update. Feel free to reopen or submit a new one when it's ready for review.

**Pull request closed without merging**
