### PR TITLE
[Swift 4] add nullable support

### PR DESCRIPTION
**Pull request by 4brunu**
This PR is a continuation of https://github.com/OpenAPITools/openapi-generator/pull/3783

Add nullable (or x-nullable in OAS2) support to swift4

This will replace the unwrapRequired option.

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

### CODE REVIEW

**Comment by wing328** [comment]
As this is a breaking change with fallbacks, I've updated this PR to target 4.3.x instead.

**Comment by 4brunu** [comment]
Since the Swift 5 generator is a new generator https://github.com/OpenAPITools/openapi-generator/pull/4086 when it land on master, can it have this change already? Or it must go to 4.3.x also?

**Comment by wing328** [comment]
If it's a new generator. then it's perfectly fine to have all kinds of change (breaking, non-breaking)

**Comment by wing328** [comment]
Please resolve the merge conflicts when you've time. Thanks for this PR to fully support the nullable attribute in the spec.

**Comment by 4brunu** [comment]
@wing328 I have fixed the merge conflicts.

**Comment by wing328** [comment]
Looks like rebase failed and this PR now includes commits in the master as well: https://github.com/OpenAPITools/openapi-generator/pull/4754/commits

I would suggest you open a new one instead. Let me know if you need help on that.

**Comment by 4brunu** [comment]
@wing328 I have created https://github.com/OpenAPITools/openapi-generator/pull/4825 👍

**Pull request closed without merging**
