### PR TITLE
[PHP] Decommission "packagePath", add new option "packageName"

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- Decommission "packagePath"
- Users will need to use -o (--output) to control the destination folder instead to make it consistent with other generators
- add new option "packageName"

To close https://github.com/OpenAPITools/openapi-generator/issues/663

cc @jebentier (2017/07) @dkarlovi (2017/07) @mandrean (2017/08) @jfastnacht (2017/09) @ackintosh (2017/09) @ybelenko (2018/07)

### CODE REVIEW

**Comment by wing328** [comment]
@ybelenko what about keeping getPackagePath() or packagePath in all PHP server generators and put the following in the constructor instead?

```
        packagePath = ""; // empty packagePath (top folder)
```

so that the package path (root folder) can be changed easily by the users if they need to customize it somehow?

**Comment by ybelenko** [comment]
@wing328 It was my first approuch. I don't have full knowledge of your path generation, but this way I can generate code in a specific folder. I think we need to ask @ackintosh about that.

**Comment by wing328** [comment]
@ybelenko sure let's wait for @ackintosh to review.

Btw, the following approach is already used in other PHP server generators:
```
        packagePath = ""; // empty packagePath (top folder)
```

**Comment by ackintosh** [comment]
I think `packagePath = ""` is good idea. 💡 

It sets the destination to root folder as default and be able to change if user want.

**Comment by wing328** [comment]
@ackintosh thanks for the feedback. I'll change the rest accordingly.

**Comment by wing328** [comment]
@ybelenko @ackintosh I've decommissioned packagePath and add a new option "packageName". The samples are exactly the same as before. Please review when you've time.

**Comment by wing328** [comment]
@ackintosh good catch. Fixed via https://github.com/OpenAPITools/openapi-generator/pull/681/commits/0d45184fd8bef57ac5bfcc02653bcb6092b17f2a

**Comment by wing328** [comment]
@ybelenko can you merge it if it looks good to you? Thanks

**Comment by ybelenko** [comment]
Now I don't understand what we need `packageName` option for? We don't use it in path construction.

The only reason I can imagine for `packageName`("GeneratedPetstore" packageName as example):
```php
/**
 * FakeApi Class Doc Comment
 * PHP Version 5
 *
 * @category Class
 * @package  GeneratedPetstore
 * @author   OpenAPI Generator team
 */
class FakeApi {
```
Do we keep `packageName` option to avoid breaking changes as fallback solution?
Or do you expect that user wants to use `packageName` in mustaches somehow?

> The main package name for classes. e.g. GeneratedPetstore

If I understand this description correct, then mustache should look like:
```django
class {{packageName}}{{classname}}
```
and result:
```php
class GeneratedPetstoreFakeApi
```

In total `packageName` is a prefix to generated class names, isn't it?

**Comment by wing328** [comment]
The {{packageName}} is used in the README: https://github.com/OpenAPITools/openapi-generator/pull/681/files#diff-5763a353c6e95ff8967e09ce0e52ba53R1

**Comment by wing328** [comment]
## Upgrade Note

The `packagePath` option has been deprecated. Please use `-o` or `--output` to specify the output folder.

To specify the package name in the auto-generated README.md, please use the new option `packageName` instead.

**Pull request merged**
