### PR TITLE
[kotlin-spring] fix #9902 use coroutine Flow for arrays in delegate when reactive=true

### LINKED ISSUE #9902: [BUG] [kotlin-spring] Kotlin generator server stubs may not compile with reactive option on
##### Description

Using the maven plugin with the reactive option and the delegate pattern enabled, one of the endpoints defined in the OpenApiSpec doc requiring an input of Array<Int> doesn't compile.

The delegate class function has an input of `kotlin.collections.List<kotlin.Long>` whereas the V1Api controller class is passing through a `Flow<kotlin.Long>`

##### openapi-generator version

5.1.1

##### OpenAPI declaration file content or url

https://gist.github.com/ffffionn/bd8c8cd9fbd2edce348e3029928f621d

##### Command line used for generation

Maven plugin

##### Steps to reproduce

Generate the files and compile.

### PR DESCRIPTION
**Pull request by giveadamakick**
This PR fixes the problem described in issue [#9902](https://github.com/OpenAPITools/openapi-generator/issues/9902), which I'll summarize here:
* For the `kotlin-spring` generator, with `delegatePattern` and `reactive` set to true, the generated API file should use a Kotlin coroutine-type `Flow` when dealing with an OpenAPI `array` data type.
* For a `requestBody` parameter, it does this for a generated API class, but _not_ for a generated Delegate class. In generated Delegate classes, an array type that is the request body is generated as a `kotlin.collections.List` instead of a `Flow`.
* This is not only incorrect, it also means the generated code does not compile, as the API class is attempting to pass a `Flow` to a Delegate that is expecting a `kotlin.collections.List`.

To fix this, I have made the following changes:
* I have updated the relevant Delegate Moustache template to use a `Flow` when the `requestBody` parameter is an array.
* I've also added some unit tests to cover this case.

#### How to validate
1. Using [this OpenAPI spec](https://gist.github.com/giveadamakick/11d65b51f951eb23150937ce225f4223), and using an openapi-generator-maven-plugin config with `delegatePattern` and `reactive` set to `true` (see [this example I used](https://gist.github.com/giveadamakick/b87fac47e6076a72c22dfe6bb10eeeef)), run a `mvn install` _without_ the changes in this PR. You'll see that the generated code does not compile.
2. Repeat the above using the generator including the changes in this PR. The code now compiles, and the delegate has the correct `Flow` type for the `requestBody` parameter.

After running both `./bin/generate-samples.sh` and `./bin/utils/export_docs_generators.sh`, no extra files were generated, so nothing extra to include in this PR.

Mentioning Kotlin technical committee members: @jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by blawlor** [comment]
Looking forward to seeing this get merged - really need it! :-)

**Comment by giveadamakick** [comment]
The "node2" CircleCI tests failed. Looking at the [reason for the failure](https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/15968/workflows/d4189ab6-2195-4ea7-b700-0d407901a934/jobs/32320?invite=true#step-114-2017), it seems to be something to do with the GoGinServer project, which my PR does not touch:

```
/home/circleci/.go_workspace/src/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (go-get) on project GoGinServer: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
```

**Comment by wing328** [comment]
@giveadamakick thanks for the PR. Please ignore the CircleCI node 2 failure for the time being.

cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

**Comment by wing328** [comment]
I tested with [petstore.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml) but got the following errors:

```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.3.30:compile (compile) on project openapi-spring: Compilation failure: Compilation failure: 
[ERROR] /private/tmp/kotlin-spring2/src/main/kotlin/org/openapitools/api/PetApi.kt:[70,47] Type mismatch: inferred type is List<String> but Flow<String> was expected
[ERROR] /private/tmp/kotlin-spring2/src/main/kotlin/org/openapitools/api/PetApi.kt:[81,45] Type mismatch: inferred type is List<String> but Flow<String> was expected
[ERROR] -> [Help 1]
```

Can you please take a look when you've time?

command to test:
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g kotlin-spring -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/kotlin-spring2/ --additional-properties delegatePattern=true,reactive=true
```

**Comment by giveadamakick** [comment]
@wing328 that's strange, I can confirm that I've been able to recreate the problem you describe locally. For what it's worth, the errors you describe also happen when using `master`. Those errors are what this PR is meant to actually fix.

It looks like my changes are not being picked up when using `openapi-generator-cli.jar`. I did verify that the changes _are_ being picked up when using the Maven plugin. I'll investigate further.  Let me know if you have any idea why this would be the case in the meantime.

**Comment by giveadamakick** [comment]
@wing328 ok, I've worked out the cause of the compilation error you reported using petstore.yaml.

The sample petstore API contains endpoints that take an array as a value for a query parameter. In the API, these values are modeled as a Kotlin `List`, not as a `Flow`, and so were being passed to the delegate as a `List`. However, the change I had made meant the delegate treats _all_ array values as a `Flow`.

Initially, I tried to change the types of the array query parameters to also be a `Flow`, but Spring doesn't support this type mapping. So in the end, the best solution is to update the delegate template to only treat a parameter as a `Flow` when it's both an array, and a `bodyParam`.

I've made this change in the latest commit, just pushed.

**Comment by wing328** [comment]
@giveadamakick thanks for the prompt fix and the detailed explanation. Tested again and the result is good.

Will add some tests to CI to cover this.

Have a nice weekend.

**Pull request merged**
