### PR TITLE
[Java] Unalias type when generating default value for model property

### PR DESCRIPTION
**Pull request by zippolyte**
Follow up to #4527, this fixes the default value that gets generated.

I went with the approach of unaliasing the schema first thing in the `getTypeDeclaration`, to also fix every usage of that method anywhere else.

Also added the same tests scenario for the `toDefaultValue` method.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### CODE REVIEW

**Comment by zippolyte** [comment]
Quick bump. @jimschubert do you think this can still make it to 4.2.3 ?

**Comment by zippolyte** [comment]
@jimschubert @wing328 is this ok to merge ?

**Comment by zippolyte** [comment]
@jimschubert @wing328 bump

**Comment by jimschubert** [comment]
Hey, I never got notified of the pings from this PR.
I'm working on the merge conflict and I'll regenerate samples. Everything else looks good. I'm not sure why we weren't unaliasing previously.

**Comment by jimschubert** [comment]
I had to make a small change while merging master into your work… the unalias should honor our generate-alias-as-model functionality.  Luckily, your work broke a test at `JavaClientCodegenTest#testImportMapping` from #3589 which asserted that a private member of a generated file would be the model rather than alias type of String. That was an incorrect assertion as it should only be the case when calling `configurator.setGenerateAliasAsModel(true)`.

I think everything looks good to merge once CI is happy.

**Pull request merged**
