### PR TITLE
[typescript] Fix generation of enum models

### LINKED ISSUE #665: [typescript] support for enum
##### Description

Enum are not correctly generated in typescript client. Some investigation are requested to understand what is going wrong.

See also: https://www.typescriptlang.org/docs/handbook/enums.html

CC: @kayhuba

##### openapi-generator version

3.1.2

##### Command line used for generation

CLI to use the `typescript-node` generator.

### PR DESCRIPTION
**Pull request by bodograumann**
Due to the fact that the consolidated typescript template was forked from master so long ago, there are still some bugs left that where fixed for other typescript generators in the meantime. This is one of them.

This fixes #665 for the consolidated typescript generator. (With [sample definition](https://github.com/OpenAPITools/openapi-generator/issues/665#issuecomment-408769117))
The issue there is, that top-level enum schemas, which are not nested as attributes of other schemas are just generated as normal object schemas, which is not suited to represent the different allowed values.

Original fix for typescript-node was in PR #2266, merged as 8417c5bed0e23764dc841816c2322cf7dc4e9b0d in version 4.1.0.

CC: @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by duhseekoh** [comment]
Is there anyway I can pick this change up prior to a proper 5.0 release? im using the docker cli approach with `typescript-axios`. I tried pulling in the `openapi-generator-cli:latest` instead of v4.3.1 and it still doesn't generate types for top level enums. Any ideas?

**Comment by macjohnny** [comment]
@duhseekoh the `openapi-generator-cli:latest` should contain the changes. please check the output of the version information to make sure you are using the right version.

**Comment by duhseekoh** [comment]
I confirmed in the output i'm using 5.0.0-SNAPSHOT.

An enum outlined in the swagger.json like this, isn't having a type generated for it when using the 5.0.0-SNAPSHOT + typescript-axios.

```
"components": {
  "schemas": {
    "Color": {
        "enum": [
          "BLUE",
          "YELLOW",
          "GREEN"
        ],
        "type": "string",
        "additionalProperties": false
  }
}
```

**Comment by macjohnny** [comment]
The fix in this PR is for the new typescript generator.
Would you like to fix this for the (old) typescript-axios generator? Please open an issue with a minimal reproduction example as posted above

**Comment by duhseekoh** [comment]
Oh, is the direction to use the new typescript generator? Is typescript-axios deprecated?

**Comment by macjohnny** [comment]
@duhseekoh the `typescript-axios` generator is not deprecated, but the long-term goal would be to have all flavors of typescript generators united in the currently experimental `typescript` generator. This can happen if the community helps to port the current typescript generators.

**Comment by duhseekoh** [comment]
It turns out typescript-axios does in fact generate TS enums for top level spec enums.

What I discovered, after pulling the source for openapi-generator down and through some trial and error, is that the generator fails when it hits an enum with `additionalProperties` attribute on it. In open api generator local dev mode, it exits the process when it encounters this. When it's ran via the packaged cli, it silently ignores those enums, and thus they are never included in the script. This is on 4.3.1 and the latest 5.x snapshot.

I can create a bug if needed. But first I was curious if it was expected behavior that it should fail when including that extra attribute?

Fails
```
"components": {
  "schemas": {
    "Color": {
        "enum": [
          "BLUE",
          "YELLOW",
          "GREEN"
        ],
        "type": "string",
        "additionalProperties": false
    }
  }
}
```

Works (generates Color enum)
```
"components": {
  "schemas": {
    "Color": {
        "enum": [
          "BLUE",
          "YELLOW",
          "GREEN"
        ],
        "type": "string"
    }
  }
}
```

**Pull request merged**
