### PR TITLE
[python-nextgen] support dict query params

### PR DESCRIPTION
**Pull request by emma-campbell**
Fixes issue #14725 by adding `dict` to string conversion if block in the api_client template. Mentioning @wing328 since I see you on a lot of the next-gen work.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@emma-campbell thanks for the PR. can you please add a test or 2 for `parameters_to_url_query` in https://github.com/OpenAPITools/openapi-generator/blob/68cfd0a545b1555b7a851463d004302621a7fe88/samples/openapi3/client/petstore/python-nextgen/tests/test_api_client.py ?

**Comment by emma-campbell** [comment]
@wing328 Pushed some tests. With writing these, I started thinking about whether or not dicts need to be URL encoded. I can make those changes if needed. Let me know!

**Comment by wing328** [comment]
@emma-campbell are you looking for `deepObject` support in the query parameter instead? https://swagger.io/docs/specification/serialization/

e.g. `/users?id[role]=admin&id[firstName]=Alex`

if the `id` (dict or object) is `{"role": "admin", "firstName": "Alex"}`

**Comment by emma-campbell** [comment]
@wing328 Not necessarily? I was thinking more along the lines of actual JSON string parameters. For example, the OAuth has a state parameter that it passes back and forth (`state`) that can be a json string and I believe that [RFC 2396 sec. 2.2](https://www.rfc-editor.org/rfc/rfc2396#section-2) specifies that string values should be url encoded.

This may be a niche case but we use json strings for passing `state` values as well as some api methods that can execute aggregate queries on a mongo database, similar to the minimal spec I provided in the issue.

**Comment by emma-campbell** [comment]
I did some testing with this for our use case, and it looks like somewhere these values are actually urlencoded so there is no need to do that within the client. 

`json.dumps` works will to keep the typing within the dict, rather than converting both key and value to strings.

**Comment by wing328** [comment]
ok. let's go ahead with this change. thanks for the PR.

**Comment by wing328** [comment]
FYI. I've merged https://github.com/OpenAPITools/openapi-generator/pull/14799, which now properly encodes query parameters so the dict is now encoded as well. 

Tests updated via https://github.com/OpenAPITools/openapi-generator/commit/c70a41210eda953ba99c81b364ed5529275b91b7

Please pull the latest master to give it a try and let me know if you've any question.

Thanks again for the PR.

**Pull request merged**
