### PR TITLE
[JAXRS] use contextPath variable for RestApplication templates

### PR DESCRIPTION
**Pull request by michbeck100**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

The mustache templates for the JAXRS application define `/` in the `@ApplicationPath` annotation. This PR replaces this with `{{{contextPath}}}`, which contains the path of the server url. If no additional path is given and the server url contains no trailing / the value is an empty string. This will be replaced again with / by JAXRS.

### CODE REVIEW

**Comment by michbeck100** [comment]
@wing328 Any more comments?

**Comment by jmini** [comment]
@michbeck100: reviewing PRs take some time. This PR is also on my list...

To ease test: can you remind me how to create different values for `{{{contextPath}}}` ? I just need to generate project for a small spec with a server `http://api.something.com/` and then with a server ``http://api.something.com/v2`? In the first case I should get `@ApplicationPath("")` and `@ApplicationPath("/v2")` in the second case?

**Comment by michbeck100** [comment]
Exactly, but in the first case you will get `@ApplicationPath("/")`, but you can also omit the `/`. The JAXRS specification allows that

**Comment by wing328** [comment]
```
[main] INFO  o.o.codegen.DefaultCodegen - Skipped overwriting RestApplication.java as the file already exists in /Users/williamcheng/Code/openapi-generator/samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/api/RestApplication.java
```
@michbeck100 can you please manual remove `samples/server/petstore/jaxrs-resteasy/default/src/gen/java/org/openapitools/api/RestApplication.java` and regenerate the sample again by running `./bin/jaxrs-resteasy-petstore-server.sh`?

**Comment by michbeck100** [comment]
@wing328 This behavior exists not just for jars-resteasy. The `RestApplication.java` and `pom.xml` are only written if they don't already exist. Maybe this should be changed, as not every developer is aware of this?

**Comment by jmini** [comment]
@michbeck100:
I have the vision that the `samples/` that it should be possible to delete all the `samples/` folder and to create it with all the `bin/*.sh` scripts we have (see issues #80 and other).
But we are not there yet.

For standard usage of the generator, splitting the files into a folder that is regenerated each time `src-gen/` and a folder that you keep `src/` is great. => generation gap pattern.

For usages with our `samples/` folder, which is a sort of integration test of our generator, this is not optimal. Some bin scripts have started to add a small delete command that make the generator regenerate all items (see some of the spring scripts), but this is also not the case everywhere.

**Comment by michbeck100** [comment]
For JAXRS it's not a problem. I personally like the trailing `/` even more than an empty string.

**Comment by jmini** [comment]
> For JAXRS it's not a problem. I personally like the trailing `/` even more than an empty string. 

Glad to hear this.

Please if you can me an hint on how to test the a project generated with `jaxrs-spec` or `jaxrs-resteasy`. I would appreciate it.

**Comment by michbeck100** [comment]
A given openapi yaml like this:

```yaml
servers:
- url: http://localhost:8080/v2
paths:
  /pet:
```
would generate 
```java
@ApplicationPath("/v2")
```
Once you start the server, the url to `/pet` would be `http://localhost:8080/v2/pet`. Before the change this was `http://localhost:8080/pet` without `v2`, because the base path was fixed to `/`.

**Comment by jmini** [comment]
@michbeck100 : yes I have checked the generated code.

The part I am missing is: "Once you start the server" (this is probably a dummy Java/JackartaEE question, but what is the quickest way to start a server like a jetty with a JaxRS implementation. I have no JavaEE App server installed).

**Comment by michbeck100** [comment]
You could start a sample server with 
```bash
$ mvn package org.apache.tomee.maven:tomee-embedded-maven-plugin:7.0.5:run
```
in the root dir of the sample where the `pom.xml` is. This will start an embedded TomEE server and deploy the `war` file from `target`. After that you will see the available REST resources in the log output and you access them with postman for example.

**Comment by wing328** [comment]
> $ mvn package org.apache.tomee.maven:tomee-embedded-maven-plugin:7.0.5:run

What about adding that to an auto-generated README?

**Comment by jmini** [comment]
@wing328 already on my list.

**Comment by jmini** [comment]
> What about adding that to an auto-generated README?

PR #920

**Pull request merged**
