### PR TITLE
java-spring: Spring Boot fails to parse LocalDate query parameter

### LINKED ISSUE #2053: [BUG] Spring Boot fails to parse LocalDate query parameter
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When defining a query parameter of  `type: string` and `format: date`

```yaml

  /bla:
    get:
      parameters:
        - $ref: '#/parameters/analysisDate'
      produces:
        - application/json
      responses:
          200:
            description: 'Successful operation'

parameters:
  analysisDate:
    name: analysisDate
    in: query
    required: true
    type: string
    format: date
```
the server fails to parse a url like `/bla?analysisDate=2017-11-30`

The generated code looks like
```java
 blaGet(@NotNull @ApiParam(value = "Analysis Date", required = true) @Valid @RequestParam(value = "analysisDate", required = true) LocalDate analysisDate) 
```

##### openapi-generator version

3.3.4

##### Related issues/PRs

https://blog.codecentric.de/en/2017/08/parsing-of-localdate-query-parameters-in-spring-boot/
https://github.com/spring-projects/spring-boot/pull/9930

##### Suggest a fix

adding `@DateTimeFormat(iso = DateTimeFormat.ISO.DATE)` resolves the issue:
```java
blaGet(@NotNull @ApiParam(value = "Analysis Date", required = true) @Valid @RequestParam(value = "analysisDate", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate analysisDate)
```

### PR DESCRIPTION
**Pull request by peyerroger**
Adds the format annotation so that Spring is able to serialize OpenApi date/date-time format into LocalDate/OffsetDateTime.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fixes #2053 Spring Boot fails to parse LocalDate query parameter

Adds the format annotation so that Spring is able to serialize OpenApi date/date-time format into LocalDate/OffsetDateTime.

Introduces a test to ensure that format annotation is correctly added.

### CODE REVIEW

**Comment by peyerroger** [comment]
@jimschubert Hi Jim. Your review comments would be very appreciated. Cheers, Roger

**Comment by macjohnny** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

**Comment by cbornet** [comment]
I think it would be better to configure it globally with a WebMvcConfigurer.
See example [here](https://github.com/jhipster/generator-jhipster/blob/6871b52b2336709fde83fb0dccf7165b1e227fd2/generators/server/templates/src/main/java/package/config/DateTimeFormatConfiguration.java.ejs#L34)

**Comment by diyfr** [comment]
+1
LocalDate and LocalDatetime are java standards. OAS Generator output  must work without additional code additions

**Comment by cbornet** [comment]
We can generate the configurer. The only drawback would be for people generating only the endpoints if they didn't use openapi-generator to bootstrap the project. So maybe the annotation is better for them.

**Comment by macjohnny** [comment]
I am also in favor of the annotation

**Comment by macjohnny** [comment]
@cbornet if you agree, I merge this PR

**Comment by peyerroger** [comment]
@cbornet We exactly have this use case. We don't use the generator to bootstrap the application. We'd therefore very much appreciate the approach with the annotations.

**Comment by jimschubert** [comment]
I approve of the annotation usage.

I don't know that this is something you could configure globally, because OAS specifically defines the date formats as `full-date` and `date-time` formats of ISO 8601 (https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14). But, OAS also defines the ability to use custom `format`... so anyone who might extend the generator to support custom date formats would have to reconfigure. I don't think that's as much of a concern with the annotation. Then again, customizations would have to pull upstream template changes, so none of that might be a concern.

**Comment by wing328** [comment]
@peyerroger thanks for the PR, which has been included in the v4.1.3 release: https://twitter.com/oas_generator/status/1180123829626003456

**Pull request merged**
