### PR TITLE
[go] More idiomatic godoc comments

### PR DESCRIPTION
**Pull request by NathanBaulch**
The generated godoc comments are not idiomatic and produce ugly formatting when using the godoc tool and in popular IDEs like GoLand.

- Switch to double slash comments for single line godocs (ie, comments without `notes`)
- Remove asterisks prefix in multi-line comments
- Extra blank lines to force new paragraphs
- Indent @ prefixed metadata to ensure new line between each (these directives are not recognized in Go, but it's a start)
- Emit special "Deprecated" comment where applicable

@antihax @grokify @kemokemo @jirikuncar @ph4r5h4d

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@NathanBaulch thanks for the PR. Is there a URL to the official godoc comment guidelines?

**Comment by NathanBaulch** [comment]
[This](https://blog.golang.org/godoc) blog post is the closest I've seen to something official. It points out a few packages in the Go standard library that are exemplars of good inline docs. This, along with the official godoc utility and documentation rendered in GoLand are what I based my changes on.

**Comment by NathanBaulch** [comment]
For some reason Appveyor had an issue with the csharp generator (which I didn't touch) and I wasn't sure how to force a retry, so instead I've pushed some template readability/consistency tweaks.

**Comment by wing328** [comment]
For appveyor failure, please ignore it as we've been seeing build failures from appveyor intermittently.

**Comment by wing328** [comment]
> This blog post is the closest I've seen to something official. It points out a few packages in the Go standard library that are exemplars of good inline docs. This, along with the official godoc utility and documentation rendered in GoLand are what I based my changes on.

Thanks for the link. 

If no further feedback from anyone, I'll merge it over the weekend. Thanks again for the PR.

**Comment by NathanBaulch** [comment]
I've just added support for marking non-path operation parameter funcs deprecated. This required a change to the generator code since the parameter `deprecated` spec field was not exposed to templates.
I wasn't sure whether to name this field `isDeprecated` like `CodegenOperation` or `deprecated` like `CodegenProperty` so I just flipped a coin.

**Review by jirikuncar — APPROVED** [review]
✨ 🏅

**Comment by NathanBaulch** [comment]
Sorry for the moving target on this PR.
I've applied the same deprecated godoc changes to the Go server pieces too.

**Pull request merged**
