### PR TITLE
Update minimum supported version of python in docs

### PR DESCRIPTION
**Pull request by Huluti**
Seems to have changed since: https://github.com/OpenAPITools/openapi-generator/pull/19694/files

### CODE REVIEW

**Comment by Huluti** [comment]
And maybe this needs to be updated ?
https://github.com/OpenAPITools/openapi-generator/blob/975f4d467961dc5a1fc35e089b6a7b9ce313aff4/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java#L328

**Comment by wing328** [comment]
thanks for PR

yes i think so

**Comment by wing328** [comment]
filed https://github.com/OpenAPITools/openapi-generator/pull/20118 with updated code and samples (readme)

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/20118 in which you list as a co-author

**Pull request closed without merging**
