### PR TITLE
csharp-netcore: Replace null literals with default

### LINKED ISSUE #4343: [BUG] [csharp-netcore] Generating invalid null default values for enum parameters in API
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When using the _csharp-netcore_ generator, OpenAPI Generator will generate code that uses `null` as the default value for enum parameters. `null` is not a valid value for enums in C#.

It should instead generate `default` operator applied to the enum type, e.g., `default(MyEnum)`. This is the behavior when using the _csharp_ generator. (The `default` literal could be used, but is only available from C# 7.1.)

##### openapi-generator version

Version 4.2.0. (Also recreated in 4.1.3, 4.1.0, 4.0.3, and 4.0.0.)

##### OpenAPI declaration file content or url

https://gist.github.com/kimsey0/fe44536ff332ded4cf1346dfc0449888

##### Command line used for generation

```npx -p @openapitools/openapi-generator-cli@cli-4.2.0 openapi-generator generate -i ./nullenumbug.json -g csharp-netcore -o ./nullenumbug```

##### Steps to reproduce

1. Create a OpenAPI declaration file containing an endpoint with a parameter of type `string` with `enum` values.
2. Run OpenAPI Generator with this file as input and using the csharp-netcore generator.
3. Try to compile the output.
4. Observe the compile errors of the type:

```Error CS1750: A value of type '<null>' cannot be used as a default parameter because there are no standard conversions to type 'MyEnum' (39, 31)```

### PR DESCRIPTION
**Pull request by kimsey0**
Fixes #4343 
Same fix as applied to the csharp generator in #3537 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wiruzman** [comment]
Maybe you should make the PR to `4.2.x` branch.

**Comment by kimsey0** [comment]
@wiruzman: As I understand [the branch guidelines](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches), changes to be included in the next patch release should be made to master.

**Comment by kimsey0** [comment]
@mandrean, @jimschubert, @frankyjuang, any of you that can look at this?

**Comment by jimschubert** [comment]
Thanks for the fix!

**Comment by kimsey0** [comment]
Thanks for the quick merge. I'm looking forward to the release in a few weeks.

**Comment by wing328** [comment]
@kimsey0  thanks for the PR, which has been included in the v4.2.1 release: https://twitter.com/oas_generator/status/1195339336922759168

**Comment by kimsey0** [comment]
Thank you! We have already started using the new version.

**Pull request merged**
