### PR TITLE
Mark swift4 generator as deprecated

### PR DESCRIPTION
**Pull request by wing328**
Mark swift4 generator as deprecated

swift4 generator will be removed in the 5.x release.

cc @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by 4brunu** [comment]
Looks good to me.
But I propose that we also remove the files inside `bin/` and `samples/` related to `Swift`, `Swift2` and `Swift3`. 
Or do you prefer to do that in a separated PR?

**Comment by wing328** [comment]
> Or do you prefer to do that in a separated PR?

Yes.

**Comment by 4brunu** [comment]
So This PR looks good to me for merge.
Do you want to remove the old samples releated to old versions of swift or should I do it?

**Comment by wing328** [comment]
> Do you want to remove the old samples related to old versions of swift or should I do it?

I'll do it later.

**Pull request merged**
