### PR TITLE
Enable access token refresh

### PR DESCRIPTION
**Pull request by lisamburns**
- The client can now be optionally configured with an access token getter proc
- The proc overrides the the static access token if it is set
See: https://github.com/OpenAPITools/openapi-generator/issues/14068
ruby technical committee: @cliffano @zlx @autopp @wing328 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by lisamburns** [comment]
Hmmm, I am a first time contributor to this repo. Could someone help me troubleshoot my CI errors?
```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.0.0:repackage (default) on project openapi-camel: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:3.0.0:repackage failed: Unable to load the mojo 'repackage' in the plugin 'org.springframework.boot:spring-boot-maven-plugin:3.0.0' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/springframework/boot/maven/RepackageMojo has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.springframework.boot:spring-boot-maven-plugin:3.0.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/circleci/.m2/repository/org/springframework/boot/spring-boot-maven-plugin/3.0.0/spring-boot-maven-plugin-3.0.0.jar
[ERROR] urls[1] = file:/home/circleci/.m2/repository/org/springframework/spring-context/6.0.2/spring-context-6.0.2.jar
[ERROR] urls[2] = file:/home/circleci/.m2/repository/org/springframework/spring-aop/6.0.2/spring-aop-6.0.2.jar
```

**Comment by wing328** [comment]
@lisamburns please ignore the circleci failure (which only occurs starting a few days ago) for the time being.

**Comment by wing328** [comment]
@lisamburns thanks for the PR. Have you tested it locally to ensure it works? (we do not have a test in place for access token at the moment)

From what I know it's a backward-compatible change. Please correct me if I'm wrong.

**Comment by lisamburns** [comment]
> 

Hello @wing328. Correct, this change should be backwards compatible because clients can just figure a static `access_token` and not configure the `access_token_getter` configuration. I tested it locally by copying the configuration.mustache and using that as a user-defined template to generate the ruby client, then ensuring resulting client can be configured with access_token or access_token_getter.  Thanks for review.

**Comment by wing328** [comment]
@lisamburns thanks for the details. Let's give it a try.

**Pull request merged**
