### PR TITLE
Update go-gin-server templates to return a configurable library

### PR DESCRIPTION
**Pull request by sharkwouter**
Before this change, the user would be required to make changes in the
generated code. This makes it really hard to update the API and the
documentation at the same time. With this change, the generated code can
be imported as is and used. The user just needs to set the handler
functions for each endpoint.

Endpoints which haven't had a handler function set will give a 501 (not yet implemented) error.

Testing this can be done with the following commands:

```
./mvnw clean package
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
   -g go-gin-server \
   -o /tmp/gin
```

I'm still working on the documentation for it and making sure that the style is correct. This is why it is still a draft. I wanted to submit it anyway, because I will use this work regardless of if there is interest in this community for it, but I wanted to check if there was any. Let me know if this is something that is wanted or not.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by sharkwouter** [comment]
@ph4r5h4d I think this is ready

**Comment by sharkwouter** [comment]
The location of the custom code the user writes changes with this, but users will no longer need to partially rewrite the generated code. So I guess it is a breaking change.

**Comment by maconic** [comment]
Hi! Any plans for this? Having to modify the generated code is not a real solution imho.

**Comment by sharkwouter** [comment]
@maconic it is possible to download the template files from my branch and use them with the command line option for using a different template. Hope that helps, since there hasn't been much progress on this issue.

**Comment by wing328** [comment]
sorry for the delay. we can target 7.0.0 to include this breaking change. thanks again for the PR.

**Comment by wing328** [comment]
FYI. @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

**Pull request merged**
