### PR TITLE
Add auto-generated tests and travis config to Dart clients

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Add auto-generated tests and travis config to Dart clients

cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09)

### CODE REVIEW

**Comment by wing328** [comment]
```
➜  openapi git:(dart-travis) pub run test
00:06 +47: All tests passed!
```
Tests passed locally

**Comment by jaumard** [comment]
LGTM just not sure how it will affect jaguar generator as it extends DartClientCodegen.java

**Comment by wing328** [comment]
> LGTM just not sure how it will affect jaguar generator as it extends DartClientCodegen.java

I'll need to add it separately. Let actually do it in this PR as well. Stay tuned.

**Comment by wing328** [comment]
Actually let's merge this one first to see if the Shippable CI issue disappears

**Comment by wing328** [comment]
Still broken after merging into master. Reverted via #3001 

Will file a new PR including the auto-generated test for Dart Jaguar client as well.

**Pull request merged**
