### PR TITLE
[Kotlin][Spring] Prevent double-quoting default values #9904

### PR DESCRIPTION
**Pull request by pilzm**
Looks like the change in #8577 fixed default values for Java generators, but caused kotlin-spring to break with #9904. The kotlin generators handle default values in their own way in `org.openapitools.codegen.languages.AbstractKotlinCodegen#toDefaultValue`, so string values end up quoted twice (e.g. `defaultValue = ""id""`).

For this fix, I just reverted the relevant change to kotlin-spring in #8577. I assume this is a non-breaking change - non-string values should still be quoted like before.

To test this fix: I verified this fix with the reproducer provided in #9904, and the resulting diff is empty -> original behavior restored.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by pilzm** [comment]
@jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m (Kotlin comittee) Please have a look if this change is OK and doesn't break default query params of other, non-string, types :slightly_smiling_face:

**Comment by pilzm** [comment]
Just noticed this somewhat overlaps with #9865, feel free to close this PR once that one is merged

**Comment by wing328** [comment]
@pilzm thanks for the PR. We've merged https://github.com/OpenAPITools/openapi-generator/pull/9865 instead.

**Comment by erickvieira** [comment]
This bug is present in v5.3.1 yet

**Comment by bamapookie** [comment]
@wing328  This is still broken in 5.4.0.  #9865 did not change the queryParams.moustache file from this PR,

**Comment by wing328** [comment]
@bamapookie I wonder if you can file a PR with the fix 🙏

**Comment by bamapookie** [comment]
@wing328 Done.
https://github.com/OpenAPITools/openapi-generator/pull/11627

**Comment by paloliska** [comment]
see https://github.com/OpenAPITools/openapi-generator/issues/9904#issuecomment-1415966757

**Pull request closed without merging**
