### PR TITLE
#2956 [typescript] change accessToken name parameter to optional

### LINKED ISSUE #2956: [BUG][Typescript axios] Generated call to accessToken doesn't match type definition
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?   4.0.1#master
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?

The code generated for accessToken is :

```
// http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
```
(As per https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache)

`configuration.accessToken()` is called without parameters

Type definition for accessToken is
```
accessToken?: string | ((name: string, scopes?: string[]) => string);
```

`name` is a mandatory parameter
Typescript outputs the following error `semantic error TS2554 Expected 1-2 arguments, but got 0.`

Type definition for accessToken should probably be:
```
accessToken?: string | ((name?: string, scopes?: string[]) => string);
```

or, if the parameters are never used:
```
accessToken?: string | (() => string);
```

- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

### PR DESCRIPTION
**Pull request by blackdev1l**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

fixes #2956
Iif you generate an axios API, you get a compilation error if tsconfig is set to 'strict' 

because `configuration.accessToken()` requires name as paramater (not optional) but here in the code generated  it calls `configuration.accessToken()` without passing any parameters.

I just made name an optional parameter.
I don't know if this is the right way to solve the issue, i would like to have some feedback about this. 

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07)

### CODE REVIEW

**Comment by macjohnny** [comment]
@blackdev1l thanks for the PR. Could you please re-generate the samples?

**Comment by blackdev1l** [comment]
hey @macjohnny thanks for the review, 
i run `./bin/typescript-axios-petstore-all.sh` and committed, since it is a change only in the typescript generator,  should i run another script to re-generate all the samples ?

**Comment by macjohnny** [comment]
running `./bin/typescript-axios-petstore-all.sh` is enough

**Comment by wing328** [comment]
@blackdev1l thanks for the PR, which has been included in the 4.1.0 release: https://twitter.com/oas_generator/status/1160000504455319553

**Pull request merged**
