### PR TITLE
[Java][Spring] Add OAuth2 Preauthorize annotations based on scope 

### LINKED ISSUE #1975: [REQ] Spring Server generators should allow for adding OAuth2 Preauthorize annotations based on scope
Using OAuth JWT scopes and Spring Security's PreAuthorize annotation requires the PreAuthorize annotation to be on the same method as the Mapping related annotation.

With the current generators (Java/Kotlin), the Mapping annotation is in generated code, so manually adding the PreAuthorize annotation can't be done without modifying generated code.

It would be good if the generator had a flag for Spring Security, and would then leverage the OAuth2 security settings to add @PreAuthorize() annotations to the Controller class methods with the Mapping related annotations.

This is dependent on #392 being corrected first.

### PR DESCRIPTION
**Pull request by nhomble**
Thank you for starting this @ersinciftci.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@cbornet @wing328 
@wallie

Fixes #1975

### CODE REVIEW

**Comment by ersinciftci** [comment]
Much better than my original PR, thanks a lot! (I'll close the original PR)

**Comment by nhomble** [comment]
not totally sure on the 500 from the go test, checking to see why my added sample is failing the spring-all script

**Comment by nhomble** [comment]
@cbornet @wing328 would love some thoughts on this pr - I am a little stumped on the current break. But I see what I was looking for in the sample [PetApi](https://github.com/OpenAPITools/openapi-generator/pull/5641/files#diff-8bb39a3c2841d364eda2eb1dd6d53a42) Here's the failure
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project petstore-okhttp-gson: There are test failures.
```
but I cannot repro locally. 
```
okhttp-gson $ pwd     
..../openapi-generator/samples/client/petstore/java/okhttp-gson
okhttp-gson $ mvn test
```
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.openapitools.client.api.FakeClassnameTags123ApiTest
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 252, Failures: 0, Errors: 0, Skipped: 6
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.948 s
[INFO] Finished at: 2020-04-06T19:13:05-04:00
[INFO] ------------------------------------------------------------------------
```

**Comment by nhomble** [comment]
@wing328 sorry this hung around for a while - would love some feedback on this :)

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

**Comment by nhomble** [comment]
Hey folks, is there anything I need to do to get this feature? I'm really interested in using this :)

**Comment by nhomble** [comment]
I think I did a bad merge and I wanted to squash the commits anyway, checkout https://github.com/OpenAPITools/openapi-generator/pull/6242

**Pull request closed without merging**
