### PR TITLE
[Kotlin] Fix default value for kotlin class

### PR DESCRIPTION
**Pull request by Fs02**
- Fix possible typo on kotlin `defaultValue` in mustache template which cause default value not generated
- Validated on different project by overriding `data_class_opt_var.mustache`

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc: @jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

### CODE REVIEW

**Comment by 4brunu** [comment]
Hey, first of all, thanks for your PR.
Looks good to me.
Did you validated that you corrected all the places?
Thanks

**Comment by Fs02** [comment]
> Hey, first of all, thanks for your PR.
> Looks good to me.
> Did you validated that you corrected all the places?
> Thanks

Should be, I'm using case sensitive search to find `{{defaultvalue}}` in my editor
Thanks

**Comment by 4brunu** [comment]
Nice, thanks, let's wait for the CI 👍

**Comment by 4brunu** [comment]
Looks like the sample projects are not updated.
Could you please also fix those.

Screenshot 2021-09-16 at 09 58 14

And then run and commit the changes produced by those commands?
```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```

**Comment by Fs02** [comment]
is that search from master branch?

looks like I missed one file, updated here: https://github.com/OpenAPITools/openapi-generator/pull/10407/commits/eaf93dc5bd8cda1cee2122e49233de8c8af12d51
Thanks

**Comment by 4brunu** [comment]
Yes it was.
Thanks for the fix.
Let's wait for CI.

**Review by 4brunu — APPROVED** [review]
Looks good to me, CI failures doesn't seems to be related to this PR.

**Pull request merged**
