### PR TITLE
[Java][Client] Add CLI option to select OpenAPI annotation library

### LINKED ISSUE #7612: [REQ] Feature Request Description
Is there a way to disable the generation of Swagger documentation annotations in Java code?  OpenAPI generates documentation with Swagger UI from the OpenAPI YAML specification - not from the Swagger annotations.  This requires Swagger as a compile time dependency, essentially for a feature we won't be using.

I saw the following issue:  [#5058 ](https://github.com/OpenAPITools/openapi-generator/pull/5058)

This issue was for adding a 'useDocumentationAnnotations' option for Java Spring.  This looked like what was desired.  I added a comment asking about this.  Specifically, I am looking for this feature for Springboot WebFlux reactive.  I asked this question 5 days ago, and within the last 4 hours the issue was closed.

I'm currently using the 5.0.0-beta2 release.

Is there a timetable for when a configuration option to disable generation of the Swagger annotations will be available?

Thank you.

-Mark

### LINKED ISSUE #8719: Make it possible to disable generation of swagger annotations
We are using openapi-generator-maven-plugin to generate Java classes from swagger files. We are not using swagger but Spring rest template + jackson for triggering REST services. 

Code generation works great but unfortunately openapi-generator-maven-plugin always includes swagger annotations in the code. In order for being able to compile the code we have to use the com.google.code.maven-replacer-plugin:replacer maven plugin to get rid of the annoations - otherwise the code does not compile since we don't have any swagger dependencies included (and also can't add them for technical reasons).

Would be great if there would be an option to disable the generation of the annotations since we don't need them.

This is the workaround we are using

```
<plugin>
	<groupId>com.google.code.maven-replacer-plugin</groupId>
	<artifactId>replacer</artifactId>
	<executions>
		<execution>
			<id>removeUnusedAnnotationImports</id>
			<phase>process-resources</phase>
			<goals>
				<goal>replace</goal>
			</goals>
			<configuration>
				<basedir>${project.basedir}</basedir>
				<includes>
					<include>target/generated-sources/openapi/**/*.java</include>
				</includes>
				<regex>false</regex>
				<replacements>
					<replacement>
						<token>import io.swagger.annotations.ApiModel;</token>
						<value />
					</replacement>
					<replacement>
						<token>import io.swagger.annotations.ApiModelProperty;</token>
						<value />
					</replacement>
				</replacements>
			</configuration>
		</execution>
		<execution>
			<id>removeUnusedAnnotations</id>
			<phase>process-resources</phase>
			<goals>
				<goal>replace</goal>
			</goals>
			<configuration>
				<basedir>${project.basedir}</basedir>
				<includes>
					<include>target/generated-sources/openapi/**/*.java</include>
				</includes>
				<replacements>
					<replacement>
						<token>@ApiModel.*\)</token>
						<value />
					</replacement>
				</replacements>
			</configuration>
		</execution>
	</executions>
</plugin>				
```

### PR DESCRIPTION
**Pull request by djnalluri**
A new CLI option named "oaiAnnotationLib" can be used to select the OpenAPI annotation library used to annotate models. The current options are "none" and "swagger2". Placeholder sections have been left in the code and templates for future addition of a Microprofile option. These changes are a subset from #8716.

Fixes #8719.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Technical Committee:
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

### CODE REVIEW

**Comment by djnalluri** [comment]
CI failure is from hitting Docker Hub pull limits.

**Comment by hinrik** [comment]
Would be great to see this included, and for other Java-based clients as well. Two previous attemps seem to have been abandoned (#7612, #5058).

**Comment by GreenRover** [comment]
Hi what is the status? Get rid o the swagger annotations would be grate.

**Comment by djnalluri** [comment]
@wing328 Would you be able to take a look at this?

**Comment by wing328** [comment]
@djnalluri thanks for the PR and sorry for the delay in reviewing the change.

Do we need to update the following pojo.mustache files as well?
```
modules/openapi-generator/src/main/resources/Java//libraries/native/pojo.mustache
modules/openapi-generator/src/main/resources/Java//libraries/jersey2/pojo.mustache
modules/openapi-generator/src/main/resources/Java//libraries/microprofile/pojo.mustache 
```

**Comment by djnalluri** [comment]
I just updated the `pojo.mustache` templates in the libraries except for the one for Microprofile. It's heavily customized and already removes Swagger annotations.

**Comment by mar1ged** [comment]
I can see that this "issue" drives a lot of people and that there are multiple issues that try to provide some means of removing the annotations. (4270, 5058, 7612)

Can this PR be accepted ? I guess it will make a lot of people happy.

**Comment by cachescrubber** [comment]
FYI: The spring generator recently added the possibility to replace swagger v2 with openapi v3.

See (#9775, #11181).

See cli option to activate the change is simply `oas3: true`. It is currently not possible to skip the documentation based annotations all together, but this would be a simple change - basically the next thing on my todo list.

I would suggest to coordinate an option name and semantics that could be used for all java bases generators.

Suggestion: `apidocAnnotationLib`: `none, swagger, oas3, microprofile.`

**Comment by cachescrubber** [comment]
Please have a look at #11258. It aims to define two new additional properties, _documentaionProvider_ and `annotationProvider` available to all Java based Codegens. They should fir exactly your needs.

**Comment by cachescrubber** [comment]
Implemented in https://github.com/OpenAPITools/openapi-generator/pull/12422.

**Comment by djnalluri** [comment]
Closing as an alternative annotation name has been implemented in #13869.

**Pull request closed without merging**
