### PR TITLE
[csharp-dotnet2] Removed

### PR DESCRIPTION
**Pull request by jimschubert**
Removing deprecated generator for C# 2.0
Targets 5.0.x branch.

cc @mandrean @frankyjuang
cc @OpenAPITools/generator-core-team 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
I think it's still being used (https://github.com/OpenAPITools/openapi-generator/issues/2672) even though C# 2.0 has reached EOL.

Shall we keep it?

**Comment by jimschubert** [comment]
We'd discussed previously about asking users to create a custom generator if they do in fact need .NET 2.0 support, or asking them to continue using one of the existing 3.x or 4.x releases which will continue to exist and support .NET 2.0 and allow for template customization.

As you can see from the linked issue, the generator isn't fully featured enough for a majority of use cases, which begs the question: what would we be keeping? Searching `csharp-dotnet2` in the repository returns 14 issues and the one you've linked from April 16 is the only one specific to this .NET 2.0 generator.

We'd either need to fix it and make it usable, thus continuing to maintain a generator that most of us can't test, or we remove it and provide guidance for users who are able to build/run in an environment which targets that client.

For instance, for #2672… I don't have an environment where I can build/run the generated code, so I wouldn't be able to contribute a fix. It's been 7 months with no community contribution since that issue. What's more, dependencies for the .NET 2.0 client won't receive security fixes (it's not just the Windows EOL). This could pose a legal liability risk to maintainers for the generated code if the generator continues to consider this output "supported".

**Comment by wing328** [comment]
> We'd discussed previously about asking users to create a custom generator if they do in fact need .NET 2.0 support, or asking them to continue using one of the existing 3.x or 4.x releases which will continue to exist and support .NET 2.0 and allow for template customization.

Let's continue the discussion on the core team slack channel. I think I may not have presented all my viewpoints clearly to all core team members.

**Comment by wing328** [comment]
Previous discussion: https://github.com/OpenAPITools/openapi-generator/pull/2786

**Comment by jimschubert** [comment]
Closing this. We've discussed renaming "deprecated" generators to something like legacy or unmaintained for the 5.0 release.

We've not used "deprecated" to mean "to be removed" but rather "older generator with low maintenance or no active maintainer".

**Pull request closed without merging**
