### PR TITLE
[BugFix] [Rust*] model-name-prefix causing invalid generated code

### LINKED ISSUE #19632: [BUG] Using `model-name-prefix` with `rust-axum` results in uncompilable code due to adding the prefix twice in `server/mod.rs`
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Using `-g rust-axum` in conjunction with `--model-name-prefix=Foo` results in `models::FooFoo{Object}` in generated `server/mod.rd` and uncompilable code.

##### openapi-generator version

openapi-generator-cli 7.9.0-SNAPSHOT
  commit : eebecc8

##### OpenAPI declaration file content or url

You can use the provided test `petstore` spec (https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml)

##### Generation Details

```
openapitools/openapi-generator-cli help generate \
    -i petstore.yaml \
    -g rust-axum \
    -o /local/out \
    --model-name-prefix=Foo
```

##### Steps to reproduce

* Run the provided generation command.
* Try to compile.
* Look at line 73 in `server/mod.rs`

##### Suggest a fix

I am guessing it is connected to https://github.com/OpenAPITools/openapi-generator/blob/eebecc864660805fb2ef99b1976ec9b6a0446f45/modules/openapi-generator/src/main/resources/rust-axum/server-operation-validate.mustache#L65 which means `dataType` is getting the prefix added twice.

### PR DESCRIPTION
**Pull request by linxGnu**
Kindly ping @wing328 to review.

This PR Fixes #19632 

Integration test without problems:
```bash
./bin/generate-samples.sh bin/configs/manual/rust-axum-*
mvn integration-test -f samples/server/petstore/rust-axum/pom.xml
```

Noted: this PR update rust-axum samples properties to generate models with prefix.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by GeorgeFkd** [comment]
Can you also generate the samples for the rest of the Rust implementations? As the change you did also affects all of the rust generators. Just do `./bin/generate-samples.sh ./bin/configs/*.yaml` as indicated to be sure that all affected generators are properly generated and pass the checks.

**Comment by linxGnu** [comment]
@GeorgeFkd 
Ran `./bin/generate-samples.sh ./bin/configs/*.yaml` -> no changes -> safe

**Comment by linxGnu** [comment]
Added an sample for reqwest with model-name-prefix. PTAL @wing328 
cc @GeorgeFkd as well to review

**Comment by wing328** [comment]
lgtm. thanks for the PR

**Pull request merged**
