### PR TITLE
[Kotlin-client] Authentication support

### PR DESCRIPTION
**Pull request by armandmgt**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@jimschubert @dr4ke616 @karismann @Zomzog

### Description of the PR

Adds support for authorization via basic auth, query param, header param or bearer token.
The modifications are based on the ruby client.

Implements #3482 

PS: This PR includes some changes to samples that I guess where part of other PRs. I don't know if I should ignore them or not

### CODE REVIEW

**Comment by jmini** [comment]
Shippable CI is failing on `master` since the merge of this PR:

Error:
```
e: /root/src/github.com/OpenAPITools/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (80, 17): Type inference failed: Cannot infer type parameter V in inline operator fun <K, V> MutableM
> Task :compileKotlin FAILED
ap<K, V>.set(key: K, value: V): Unit
None of the following substitutions
receiver: MutableMap<String, String>  arguments: (String,String)
receiver: MutableMap<String, String?>  arguments: (String,String?)
can be applied to
receiver: MutableMap<String, String>  arguments: (String,String?)


FAILURE: Build failed with an exception.
```

@wing328, @armandmgt: 
Can you have a look at the file:
https://github.com/OpenAPITools/openapi-generator/blob/4898ffa/samples/openapi3/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt

And fix this issue ASAP?

**Comment by wing328** [comment]
My bad. I thought Kotlin client/server was tested in CircleCI but not Shippable.

Let me comment out the check for the time being

**Comment by wing328** [comment]
96dd31a462 to comment out the kotlin client tests.

@armandmgt can you please take a look at the error when you've time? Thanks.

**Comment by armandmgt** [comment]
I had a look and the code needs a quick fix (done [here](https://github.com/armandmgt/openapi-generator/tree/fix-auth-support)). But after this is fixed, the tests fail because of a pet that has a null value for its name... (reproduced [here](https://github.com/armandmgt/openapi-generator/tree/null-value-error))

I don't know which step to take from here. Is there a problem with this pet that has a null name or should the JSON deserialization handle null names ?

_btw, there is again some changes that don't comes from this PR, I don't know what I should do with this.._

**Comment by wing328** [comment]
Please submit a PR for https://github.com/armandmgt/openapi-generator/tree/fix-auth-support and we'll start from there.

**Pull request merged**
