### PR TITLE
[kotlin] Enum should match spec

### LINKED ISSUE #3804: [BUG] [Kotlin] Enums are generated with odd capitalization
### Description
Kotlin generator generates Kotlin enums with strange capitalization: it lower-cases the first enum item letter (e.g. generates `rED` instead of `RED`).

##### openapi-generator version

Generator Version 4.1.1
Spec Version 3.0.2

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.2"

info:
  version: "1.0.0"
  title: Testing Kotlin generation

# We only care about schemas, but this prevents codegen error: "attribute paths is missing"
paths:
  /dummy:
    get:
      responses:
        '200':
          description: OK

components:
  schemas:

    StatusColorEnum:
      description: >
        RGB.
      type: string
      enum:
        - RED
        - YELLOW
        - GREEN
```

##### Command line used for generation

`openapi-generator generate -i my-models.yml -g kotlin`

NOTE: we actually use the Gradle plugin for code generation (`org.openapi.generator` version `4.1.1`), but the above command-line tool gives the same result. However, we would like the fix to propagate to the Gradle plugin as well, so we can use in our build.

##### Steps to reproduce

Run the command above and inspect the generated `StatusColorEnum.kt`. It will look like below:

```java
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
* RGB. 
* Values: rED,yELLOW,gREEN
*/
enum class StatusColorEnum(val value: kotlin.String){


    @Json(name = "RED")
    rED("RED"),


    @Json(name = "YELLOW")
    yELLOW("YELLOW"),


    @Json(name = "GREEN")
    gREEN("GREEN");


}
```

Note the capitalization is very odd: instead of `rED` it should really be just `RED`.

##### Related issues/PRs

Not found.

##### Suggest a fix

Generate Kotlin enums with the same capitalization as given in the declaration file (do not lower case the first letter).

### PR DESCRIPTION
**Pull request by snowe2010**
- Adjust the enum generation to match what is in the spec, rather than camel-casing it.
- Regenerate docs

closes #3804

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
**I cannot find a 7... branch**
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jimschubert
@dr4ke616
@karismann
@Zomzog
@andrewemery
@4brunu
@yutaka0m
@stefankoppier

### CODE REVIEW

**Comment by tuxmachine** [comment]
Awesome! I hope to have some time next week, I'll test this in a project that's encountering this error. It's using the `typescript-fetch` generator currently.

**Comment by wing328** [comment]
@snowe2010 thanks for the PR. Can you please PM me via Slack for a few questions on this PR when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by wing328** [comment]
can you please resolve the merge conflicts when you've time?

then we will merge it. thanks again for the PR.

**Comment by gimbimloki** [comment]
Hi, LGTM! We have same problem. When will 7.4.0 be released?

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/18062

**Pull request closed without merging**
