### PR TITLE
[C#] Additional null check before doing SequenceEqual check

### PR DESCRIPTION
**Pull request by fschlag**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@mandrean @jimschubert @wing328 

### Description of the PR

This PR is a reference to #2760. I did run the shell scripts locally, but I wasn't sure if I did it correctly. Therefore I first created the issue (#2760) and @wing328 suggested to open a PR to get additional help. 

Thanks!

### CODE REVIEW

**Comment by jimschubert** [comment]
Thanks for the PR!

When you say you've run the shell scripts, are you referring to the samples, or did you also run `./bin/utils/ensure-up-to-date`? The Shippable failure is due to outputs differing from the expected outputs of the above script.

**Comment by wing328** [comment]
I could repeat the issue: https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/24199406

**Comment by wing328** [comment]
Looks like it's due to additional test cases added to fake petstore spec.

**Comment by fschlag** [comment]
@jimschubert: I've ran `bin/utils/ensure-up-to-date` and `bin/csharp-petstore-all.sh` again locally. Afterwards I have 290 changed files. For example

```diff
--- a/samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Model/AdditionalPropertiesClass.cs
+++ b/samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Model/AdditionalPropertiesClass.cs
@@ -181,41 +181,49 @@ namespace Org.OpenAPITools.Model
                 (
                     this.MapString == input.MapString ||
                     this.MapString != null &&
+                    input.MapString != null &&
                     this.MapString.SequenceEqual(input.MapString)
                 ) &&
...
```
What seems ok, but there are also changes like
```diff
--- a/samples/client/petstore/csharp/OpenAPIClientNet35/docs/AdditionalPropertiesAnyType.md
+++ b/samples/client/petstore/csharp/OpenAPIClientNet35/docs/AdditionalPropertiesAnyType.md
@@ -1,9 +1,13 @@
+
 # Org.OpenAPITools.Model.AdditionalPropertiesAnyType
+
 ## Properties

 Name | Type | Description | Notes
 ------------ | ------------- | ------------- | -------------
 **Name** | **string** |  | [optional]

-[[Back to Model list]](../README.md#documentation-for-models) [[Back to API list]](../README.md#documentation-for-api-endpoints) [[Back to README]](../README.md)
+[[Back to Model list]](../README.md#documentation-for-models)
+[[Back to API list]](../README.md#documentation-for-api-endpoints)
+[[Back to README]](../README.md)
...
```
What from my perspective looks *wrong*?!

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/2776 to fix the build issue with C# .NET core petstore client using the latest commit. After merging that PR into master, I'll merge this one.

**Comment by wing328** [comment]
Tested (with updated samples) passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/24230154

**Comment by wing328** [comment]
FYI. Filed https://github.com/OpenAPITools/openapi-generator/pull/2778 to apply a similar fix for aspnetcore generator.

**Pull request merged**
