### PR TITLE
[aspnetcore] Make the use of Swashbuckle optional

### PR DESCRIPTION
**Pull request by FantasyTeddy**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- The `sourceFolder` option was not handled properly in the ASP.NET Core server generation, which is now fixed.
- The use of Swashbuckle for documenting the server was made optional by introducing an `useSwashbuckle` option. (Default: true)

### Technical Committee
- @mandrean 
- @jimschubert

### CODE REVIEW

**Comment by jimschubert** [comment]
Thanks. I have a pretty full weekend, but I'll try to evaluate as soon as possible.

One question, though... ASP.NET Core, in both the 1.0 original version of the generator and after upgrading to 2.0, errors for me that code has to exist under `src`. Does this option work for you, or is it provided to allow users so flexibility? If you're able to compile when source folder is changed, can you share your OS and .NET Core version info so I can try?

For reference, I received the errors under OS X 10.11 (.net core 1.0), 10.13 (.net core 2.0), and Windows 10  (.net core 1.0/2.0). I'll be trying the different options in this PR, as well, I just want to ensure if I have errors that I update to the successful version.

**Comment by FantasyTeddy** [comment]
I tested my `sourceFolder` fix with Windows 10 (.NET Core 2.0) and everything seems to run as intended. (I'm no expert though...)

I also quickly checked under macOS 10.13 (.NET Core 2.0) and I didn't encounter any problems either.

**Comment by jimschubert** [comment]
Cool, thanks for checking and providing version info. I'm wondering if I had some setting causing an override. I've recently upgraded my machine, so if something is different I'd unfortunately have no insight into what changed. If the option works for others in the community, obviously it's a valuable change; we've just never had verification before that changing the source folder works for others.

The reason I had to all is that someone once opened a PR on swagger-codegen to make source folder comfortable, and when I asked the same question as above, he wasn't able to build with a custom source folder.

I _might_ be able to review this tonight. My plans for this weekend have upended and now I have more on my plate, but mostly tomorrow.

**Comment by jimschubert** [comment]
Thanks. I got some time to test this out this morning and it looks great.

Tested both options on macOS High Sierra and they work as expected.

Tested with `--additional-properties sourceFolder=asdf`:

```
dotnet msbuild Org.OpenAPITools.sln
dotnet run --project asdf/Org.OpenAPITools/Org.OpenAPITools.csproj
```

```
cd asdf/Org.OpenAPITools/
dotnet run
```

Also, tested both with JetBrains Rider and the project built and ran successfully.

Whatever issues we had previously with changing the `src` folder is obviously not an issue anymore. If anyone experiences issues, my recommendation is to use the latest version of dotnet for creating a new project.

**Comment by FantasyTeddy** [comment]
Haha, I tested with the same folder name, so I hope we did not just get lucky 😄

**Comment by theletterf** [comment]
Is this available in 4.0.0?

**Comment by jimschubert** [comment]
@theletterf this option was introduced in our first major release, 3.0.0. If you experience issues with the option, please do open a bug.

**Pull request merged**
