### PR TITLE
[typescript-angular] drop support of angular below 6.0.0

### PR DESCRIPTION
**Pull request by macjohnny**
Remove support for old angular versions below 6.0.0, allowing to clean up the code base.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### CODE REVIEW

**Comment by TiFu** [comment]
This raises a philosophical question: Do we want to fix the shortcomings of OAS2 with an implementation that tries to be smart? 

In the case that you described, what happens if a new enum value is introduced only for `Query2SortEnum` (let's say `random`)? 
Does TS still allow what you are trying to do or would this potentially cause errors totally unrelated to the actual change in the spec?

**Comment by amakhrov** [comment]
> Does TS still allow what you are trying to do or would this potentially cause errors totally unrelated to the actual change in the spec?

You will be able to assign `Query1SortEnum` values to variables of type `Query2SortEnum` but not vice versa.

>  Do we want to fix the shortcomings of OAS2

I'm not a big proponent of that approach. I mostly wanted to point out that the change in the PR can have backward-incompatible outcome without a fallback even for angular 8/9 users.

On the other hand, e.g. axios generator has never had such `stringEnum` option - it just always emits enums. We can stick to this approach for consistency across typescript generators.

**Comment by wing328** [comment]
If it's a limitation only with OAS2, then I would suggest asking users to migrate to OAS3 spec instead.

**Comment by macjohnny** [comment]
In order to minimize the breaking changes, I decided to revert the changes related to the string enums, since the functionality is already implemented and not too much of a burden.

**Pull request merged**
