### PR TITLE
[Java][Microprofile] Fix #17526: enumOuterClass missing JSON-B (de)serializer

### LINKED ISSUE #17526: [BUG] [JAVA] enumOuterClass template is missing JSON-B serializer/deserializer
##### Description

The mustache template [enumOuterClass.mustache](https://github.com/OpenAPITools/openapi-generator/blob/063865973df48aa13da473b359faf8ed5c5d2434/modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumOuterClass.mustache) does not contain the necessary serializer and deserializer for JSON-B. These are present for inner enums ([enumClass.mustache](https://github.com/OpenAPITools/openapi-generator/blob/063865973df48aa13da473b359faf8ed5c5d2434/modules/openapi-generator/src/main/resources/Java/libraries/microprofile/enumClass.mustache)). In general there are some big differences between these two templates, but I only tested JSON-B code generation.

##### openapi-generator version
OpenAPI code generator (via gradle plugin): 7.1.0

###### gradle task
```
tasks.register(taskName, org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
  generatorName = 'java'
  library = 'microprofile'
  inputSpec = file("demo.yaml").toString()
  configOptions = [
      microprofileRestClientVersion: '3.0'
  ]
}
```
###### demo.yaml
```
openapi: 3.0.3
info:
  title: Demo Webservice
  version: 1.0.0
servers:
  - url: https://test.com/api/demo
paths:
  /demo:
    get:
      operationId: getDemo
      responses:
        '200':
          description: Demo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DemoResponse'
components:
  schemas:
    DemoResponse:
      properties:
        demo:
          $ref: '#/components/schemas/DemoEnum'
    DemoEnum:
      type: string
      enum:
        - yes
        - no
        - maybe
```

###### actual output
```
/**
 * Gets or Sets DemoEnum
 */
public enum DemoEnum {
  TRUE("true"),
  FALSE("false"),
  MAYBE("maybe");

  private String value;

  DemoEnum(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DemoEnum fromValue(String text) {
    for (DemoEnum b : DemoEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}
```

###### expected output
```
@JsonbTypeSerializer(DemoEnum.Serializer.class)
@JsonbTypeDeserializer(DemoEnum.Deserializer.class)
public enum DemoEnum {

  TRUE(String.valueOf("true")), FALSE(String.valueOf("false")), MAYBE(String.valueOf("maybe"));


  String value;

  DemoEnum (String v) {
      value = v;
  }

  public String value() {
      return value;
  }

  @Override
  public String toString() {
      return String.valueOf(value);
  }

  public static final class Deserializer implements JsonbDeserializer<DemoEnum> {
      @Override
      public DemoEnum deserialize(JsonParser parser, DeserializationContext ctx, Type rtType) {
          for (DemoEnum b : DemoEnum.values()) {
              if (String.valueOf(b.value).equals(parser.getString())) {
                  return b;
              }
          }
          throw new IllegalArgumentException("Unexpected value '" + parser.getString() + "'");
      }
  }

  public static final class Serializer implements JsonbSerializer<DemoEnum> {
      @Override
      public void serialize(DemoEnum obj, JsonGenerator generator, SerializationContext ctx) {
          generator.write(obj.value);
      }
  }
}
```
##### Suggested fix
Add the missing parts in the enumOuterClass.mustache template.

### PR DESCRIPTION
**Pull request by DielN**
Fixes #17526 by adding the necessary JSON-B serializer and deserializer to the enumOuterClass template.
I added a sample/config with an outer enum (`Status`). The existing ones don't use an outer enum, so the changes weren't visible there.

I'm not sure if this is considered a breaking change since if someone was relying on the enums being (de)serialized the wrong way, this would break it for them. But it was broken in the first place, so in my opinion this is not a breaking change but a fixing change ;)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

### CODE REVIEW

**Comment by martin-mfg** [comment]
Hi @DielN, thanks for the PR!

The changes look good to me. Just one thing: Could you add the new example to `.github/workflows/samples-jdk17.yaml` please?

**Comment by DielN** [comment]
Thank you for taking a look at it – I added it to the workflow.

**Comment by martin-mfg** [comment]
Please re-generate the samples to fix the failing "samples up-to-date" check. The other failing check (java-camel samples) is not related to this PR and can be ignored.

**Comment by DielN** [comment]
Done!

**Review by martin-mfg — APPROVED** [review]

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/9829846694/job/27156407317?pr=18951

don't think this failure is related to this PR

**Pull request merged**
