### PR TITLE
Set isModel property

### PR DESCRIPTION
**Pull request by wheezil**
### PR checklist

- [ X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [NA ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X ] Filed the PR against the [master]
- [ NA] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Added an attribute **isModel** available to the mustache-based code generators. This should be set for all parameters and fields that are objects or referenced schemas.

### CODE REVIEW

**Comment by wing328** [comment]
@wheezil thanks for the PR. I'd a look and I think it' a good start. There will be some enhancements and I"ll do it after merging this PR into master.

**Comment by wing328** [comment]
@wheezil thanks for the PR. I'd a look and I think it' a good start. There will be some enhancements and I"ll do it after merging this PR into master.

**Comment by wing328** [comment]
@wheezil thanks for the PR. I'd a look and I think it' a good start. There will be some enhancements and I"ll do it after merging this PR into master.

**Comment by wing328** [comment]
@wheezil thanks for the PR. I'd a look and I think it' a good start. There will be some enhancements and I"ll do it after merging this PR into master.

**Comment by wing328** [comment]
If no further question or feedback, I'll merge it tomorrow.

**Comment by wheezil** [comment]
Thanks William.  Much appreciated because I'm using it already :-)  Let me know if I've forgotten some cases.

**Comment by wing328** [comment]
Note: this enhancement may be subject to breaking changes in the future as the enhancement is still being worked on (e.g. isModel support in Response object)

**Comment by wheezil** [comment]
Hi William.  Do you think that isModel will be replaced by something equivalent in the template?

**Comment by wing328** [comment]
I don't foresee the `isModel` tag will be removed or renamed to something else.

**Comment by wing328** [comment]
@wheezil thanks for the PR, which is included in the v3.3.2 release: https://twitter.com/oas_generator/status/1057649626101112832

**Pull request merged**
