### PR TITLE
feat(typescript-angular): add support for Angular V19

### LINKED ISSUE #20204: [REQ] Support of Angular 19 in generator typescript-angular
### Is your feature request related to a problem? Please describe.

Some dependencies in the generated package by typescript-angular generator are not compatible with the dependencies of Angular 19.

## Describe the solution you'd like

When angular version is set to 19 or higher, use the following dependencies:

    "rxjs": "^6.5.3 || ^7.4.0",
    "typescript": ">=5.5.0 <5.7.0",
    "zone.js": "~0.15.0"

## Describe alternatives you've considered

Override dependencies

### PR DESCRIPTION
**Pull request by thibaudsowa**
### Changes
Add support for Angular 19
I have replicated PR https://github.com/OpenAPITools/openapi-generator/pull/18916 for angular 19

### Technical committee

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04) @joscha (2024/10)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Review by joscha — APPROVED** [review]
Intent LGTM.

Two comments:
1. it doesn't currently generate a package.json anywhere, so we don't actually install the required angular version anywhere and check that the types work. Can you see a way to add that, so a generated sample would be picked up by https://github.com/OpenAPITools/openapi-generator/blob/master/.github/workflows/samples-typescript-typecheck.yaml and checked against an actual typescript version it is produced for and its typings.
2. It might be worth cleaning the if/else up in the Java code and use a properties file or similar to manage the `atLeast`, `tsVersion`, `rxjsVersion`, `ngPackagrVersion`  and `zoneJsVersion` combinations?

**Comment by joscha** [comment]
> 1. it doesn't currently generate a package.json anywhere, so we don't actually install the required angular version anywhere and check that the types work. Can you see a way to add that, so a generated sample would be picked up by https://github.com/OpenAPITools/openapi-generator/blob/master/.github/workflows/samples-typescript-typecheck.yaml and checked against an actual typescript version it is produced for and its typings.

another option could be to include something in the `mvn integration-test` that gets executed for the addition.

**Comment by thibaudsowa** [comment]
Hi, I don't really understand the first point, could you develop the workflow of generation check?

**Comment by joscha** [comment]
> Hi, I don't really understand the first point, could you develop the workflow of generation check?

So let's say some types change from Angluar 18 -> 19 that makes some Typescript code generated by the openapi generator invalid, then the typecheck CI step will pick that up and fail. It currently only runs on generated samples under `samples/` and ONLY if there is a `package.json`:
https://github.com/OpenAPITools/openapi-generator/blob/326f100f0e4e50f569f43fbceaa5448b407fa8f9/bin/ts-typecheck-all.sh#L34-L37

For the current typescript-angular samples like the one you just added for v19, neither is true, so they are not typechecked, meaning that CI passes even though there might be type errors. That is, unless there is something inside `mvn integration-test` which I am unsure of as of this moment.

**Comment by thibaudsowa** [comment]
Ok thanks, I will try to do this.

For the second point, will it not be more flexible to add cli options for defining `tsVersion`, `rxjsVersion`, `ngPackagrVersion` (optional with fallback on `ngVersion`) and `zoneJsVersion`?
With that, when new angular version is released, no need to wait a new version of openapi-generator, you just have to change different versions according to angular compatibility matrix.

**Comment by thibaudsowa** [comment]
> One problem with not providing a "blessed" combination is, that it could lead to a lot of bugs that are really hard to fix and/or even compete with each other, so there is some merit in having a set of clearly defined and supported combinations. WDYT?

I agree, but it could be cool to support both solution? Regular "clean" update with new release of openapi-generator or possibility to override for power user ...or impatient user ;)

I just pushed a new commit with the refactoring of Angular dependencies declaration + definition of new cli options.

What do you think?

**Comment by thibaudsowa** [comment]
Hey @joscha I just pushed one more commit to resolve your first point:

> it doesn't currently generate a package.json anywhere, so we don't actually install the required angular version anywhere and check that the types work.

Could you review it and tell me if it is good for you?

Thanks :)

**Comment by thibaudsowa** [comment]
@joscha Thanks for your comments! But I'm a bit lost with the package.json things. What is the purpose of that check?
The generated sample do not create package.json, so do I need to create it? If yes what dependencies do I need to add? Angular? OpenAPI?

What I did is generating an Angular app and importing open api sample to check if everything is fine. Which it is. Would it be more secure to check if the app compile and launch unit test for example?

@macjohnny In that PR there is the two alternatives: the "blessed versions" (refactored with clean config file) and the "tuned version" with cli options. Would you like that I remove that new extra options? Or the two possibilities can be complementary ?

**Comment by joscha** [comment]
> @joscha Thanks for your comments! But I'm a bit lost with the package.json things. What is the purpose of that check? 

It makes sure the generated Typescript compiles with the dependency versions specified and there are no type errors.

> The generated sample do not create package.json, so do I need to create it? If yes what dependencies do I need to add? Angular? OpenAPI?

It's okay, let's go with 4) for now. Nothing to do, your sample is not worse or different than all the other angular samples.

> What I did is generating an Angular app and importing open api sample to check if everything is fine. Which it is. Would it be more secure to check if the app compile and launch unit test for example?

Yes, the type check would necessarily be implicity part of that if it can be executed.

I am happy with the current state. If we improve it, we should really improve all thos samples, not only one anyway.

**Review by macjohnny — APPROVED** [review]

**Pull request merged**
