### PR TITLE
[JAVA] java.net.http.HttpClient (java native) conditionally depend on apache

### PR DESCRIPTION
**Pull request by Rattenkrieg**
#14554 followup

Exclude `org.apache.httpcomponents:httpmime` if there is no form data parameters.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @wing328 @ChristianCiach

### CODE REVIEW

**Comment by ChristianCiach** [comment]
Neat! I've only glanced over the original and this PR using my phone, so I cannot do a formal review at the moment. But conditionally including the dependency by using `hasFormParams` seems like the right thing to do.

I still wonder if we can maybe do without the added dependency, but I cannot really investigate that while being on mobile. But for the time being I think this is probably good enough and surely way better than having the unconditional dependency from before. Thanks!

**Comment by Rattenkrieg** [comment]
> I still wonder if we can maybe do without the added dependency...

Sadly, `java.net.http.HttpClient` and friends doesn't provide a handy way to deal with form data or any other complex publishers. There is api to create such though. I was just on a contra-reinvent-the-wheel side for previous PR.

**Comment by Rattenkrieg** [comment]
@wing328 `Java Client (Echo API) JDK11` test seems like a new beast to me, I've checked the last PR and there were no actions.

**Comment by ChristianCiach** [comment]
My question was more like "maybe you are only a very small part of the apache library that could easily copied by source". I have no way to check that at the moment.

Anyway, I don't think any of our APIs make use of multipart form data, so personally am fine with your fix.

**Comment by Rattenkrieg** [comment]
> Anyway, I don't think any of our APIs make use of multipart form data, so personally am fine with your fix.

Well, I was surprised when I found myself integrating with thirdparty that use form params in 2023. I was looking for a generator that would suit my needs but it turns out that there is a bug in kotlin, java native has no support for form data, others are blocking.

**Comment by ChristianCiach** [comment]
@Rattenkrieg Please have a look at https://mizosoft.github.io/methanol/multipart_and_forms/ This library is a pure work of art. It is a warooer around the native HttpClient that also *implements* the `HttpClient` and `HttpClient.Builder` interfaces.

I love to use Methanol together with the generated `native` OpenApi client, like this:

```java
Methanol.Builder methBuilder = Methanol.newBuilder();
ApiClient apiClient = new ApiClient();
apiClient.setHttpClientBuilder(methBuilder);
```

This has several advantages, like automatic gzip compression (that the vanilla HttpClient doesn't do) and *actually working* read-timeouts (that usually don't work with the `BodyHandlers.ofInputStream()` that the generated OpenApi client uses internally).

This will probably won't help you with your formdata issue, but I still wanted to take this opportunity to show you the awesomeness of Methanol (that also does multipart formdata as shown in the link above).

**Comment by Rattenkrieg** [comment]
> My question was more like "maybe you are only using a very small part of the apache library that could be easily copied by source". I have no way to check that at the moment.

There is sort of 80/20 rule: unless we need to handle files it's 10-20 lines but proper file upload requires a considerable amount of coding and test coverage.

**Comment by Rattenkrieg** [comment]
@ChristianCiach thanks I will check their source code, maybe we could _borrow_ their ford data implementation verbatim.

**Comment by Rattenkrieg** [comment]
I believe we have to introduce dedicated generator specific parameter similar to `asyncNative` i.e. `useApacheHttoForFormData`, since `hasFormParams` only available while codegening operations.

**Comment by Rattenkrieg** [comment]
Superseded by #14670

**Pull request closed without merging**
