### PR TITLE
Rust validation handling

### PR DESCRIPTION
**Pull request by ErikWegner**
### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @paladinzh @jacob-pro

#OpenAPITools/openapi-generator/issues/10546

### CODE REVIEW

**Comment by jacob-pro** [comment]
Thank you, I'm glad to see support for this feature.
Have you seen this thread though?

https://github.com/Keats/validator/issues/201#issuecomment-1167018511

May want to look at using the replacement garde instead (or maybe not if it isn't ready yet) 

https://github.com/jprochazk/garde

**Comment by ErikWegner** [comment]
The [garde crate](https://crates.io/crates/garde) works for my case, so the templates are adopted now.

**Comment by ErikWegner** [comment]
@jacob-pro Is it ok now?

**Comment by jacob-pro** [comment]
It would be good to have some samples so we can see it is working?

If you add some validation to this spec
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/rust/petstore.yaml

It should show up if you regenerate samples

**Comment by jacob-pro** [comment]
Looks good to me 👍
Up to @wing328 to approve

**Comment by ErikWegner** [comment]
@wing328 The template is changed to handle that case. Can you please run the tests again?
Btw: are those circleci failures important?

**Comment by jacob-pro** [comment]
I didn't realise this when i first looked since the title was only for Rust, but does this only apply to the "rust-server" generator and not the regular Rust generator?

If so please can you apply the same to the Rust generator? 

if so please can you ensure it applies

**Comment by ErikWegner** [comment]
Yes, this change applies to the _rust-server_ generation.

The _rust_ templates are for clients and are far more relaxed when it comes to data types and validation. My first impression was, this comes from the robustness principle: Be strict with what you send, be liberal what you accept, i.e. the server (rust-server) has strongly typed structs for sending data as described by the api specification, the client (rust) accepts many variants what a server may present, e.g. it puts dates into strings and leaves conversion to the calling code.

But the rust-server templates generate several parts that can be used independently: models, a client and a server. Therefore I would like to leave the _rust_ templates untouched.

**Comment by jacob-pro** [comment]
Ok makes sense

**Comment by ErikWegner** [comment]
What are the next steps to get this forward, @jacob-pro ?

**Comment by wing328** [comment]
> Btw: are those circleci failures important?

yup, all tests are important and those failures (not related to this change) have been fixed in the master already.

**Comment by wing328** [comment]
the rust server tests failed: https://github.com/OpenAPITools/openapi-generator/actions/runs/4912308190/jobs/8771220846?pr=15288

can you please take a look?

**Comment by ErikWegner** [comment]
I will have a look into the failures.

**Comment by ErikWegner** [comment]
The `garde` crate (for validation) has this issue: jprochazk/garde#39. What is your opinion on reverting back to the `validator` crate for now?

**Comment by wing328** [comment]
totally ok for me to use `validator`, which seems to be more popular

**Comment by jacob-pro** [comment]
Yep like I said in my original suggestion - Garde may not yet be ready for general use, feel free to switch back
Or otherwise the ideal solution would be to have a flag that allows you to choose which validation library you want

**Comment by ErikWegner** [comment]
@jacob-pro  @wing328 Now it is rewritten to use the validator crate.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
please update the samples https://github.com/OpenAPITools/openapi-generator/actions/runs/5257555438/jobs/9543332861?pr=15288

**Comment by ErikWegner** [comment]
@wing328 Here it is.

**Comment by wing328** [comment]
lgtm. let's give it a try.

**Pull request merged**
