### PR TITLE
Use $Response.Content for deserializing response

### LINKED ISSUE #17340: [BUG][POWERSHELL] Powershell client should use $Response.Content for deserializing response
#### Bug Report Checklist

- [x] ~~Have you provided a full/minimal spec to reproduce the issue?~~ Not applicable
- [x] ~~Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?~~ Not applicable
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Powershell client should use $Response.Content for deserializing response. Converting $Response to string as is replaces non-ascii characters with `?`
https://github.com/OpenAPITools/openapi-generator/blob/1b2917d69f13ea0545f755a6e2963923ff2fb367/modules/openapi-generator/src/main/resources/powershell/api_client.mustache#L191

Proof in source code of powershell: https://github.com/PowerShell/PowerShell/blob/9489629f769061e3ff40f155fd2ce9a0a6c4334a/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebResponseObject.Common.cs#L175
> `Encoding.ASCII.GetChars(Content)`

##### openapi-generator version
master

##### OpenAPI declaration file content or url

-

##### Generation Details

Generate powershell client

##### Steps to reproduce

Invoke request to api with non-uncode characters in response

Expected: character parsed correctly
Actual: Bunch of `?????` instead of character

### PR DESCRIPTION
**Pull request by Stuv7CB**
Powershell client should use $Response.Content for deserializing response. Converting $Response to string as is replaces non-ascii characters with `?`
fix #17340 

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by Stuv7CB** [comment]
@wing328 could you please review this PR

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
thanks for the PR. I'll test it

**Comment by Stuv7CB** [comment]
Thank you for pointing out that commit isn't linked to my profile. Force-pushed commit with correct author and committer

**Comment by wing328** [comment]
thanks for the PR, which has been merged into the master

**Pull request merged**
