### PR TITLE
[travis] Avoiding build timeouts

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Travis CI will timeout if there is no activity printed to stdout or
stderr for 10 minutes. Running our mvn commands with --quiet option may
hit this limit for any number of reasons (more code, network
conditions). To avoid this, we remove --quiet and adjust some other
Maven configuration options.

One, specifically, is the cached .m2/repository directory. We bind this
to a non-user home location due to the -u binding found in
run-in-docker.sh. We then provide a settings.xml and CLI option to tell
maven where to look for our cached repository directory. This should
allow both users and CI to run the script in a consistent way, but most
importantly should allow Travis to continue to cache artifacts across
builds.

### CODE REVIEW

**Comment by jimschubert** [comment]
cc @OpenAPITools/generator-core-team

**Comment by wing328** [comment]
https://travis-ci.org/OpenAPITools/openapi-generator/builds/528265655?utm_source=github_status&utm_medium=notification (Travis job) still timed out.

**Comment by jimschubert** [comment]
Summarizing discussion from chat here…

We were using `run-in-docker.sh` to integrate a sort of evaluation of that script into the build. While evaluating the script locally, I found that the .m2 repository in container wasn't setup properly for a user-bound volume. This may have been causing the dockerized build in Travis to hit the 10 minute timeout limit. This is hard to juggle with the `--quiet` option, because that option is intended to only display errors but Travis will kill the build if no stdout/stderr is written out for 10 minutes. Also, running locally I found that "Scanning for projects" sometimes took longer to succeed than it should (and this is where many Travis CI builds would freeze).

The option I've taken in this PR is to provide some options for CI which will limit _some_ logs (Slf4jMavenTransferListener=WARN) while still outputting mvn output without `--quiet`. This also introduces `MAVEN_CLI_OPTS` which is to be passed to `mvn` directly with options to hopefully make evaluating Maven build output easy to reason about.

**Comment by jimschubert** [comment]
Travis builds have succeeded, and others are unaffected by these changes, so I'll go ahead and merge this.

**Comment by jimschubert** [comment]
work was also done in #2821 to remove `run-in-docker.sh`

**Pull request merged**
