### PR TITLE
[TypeScript Fetch] Default TypeScript fetch configuration to 3.6+ true

### PR DESCRIPTION
**Pull request by szTheory**
Related to issue https://github.com/OpenAPITools/openapi-generator/issues/9973

Here is a PR that changes the default to `true`. There is one issue however. I'm not sure why it's not updating the value to `true` in the generated documentation at `docs/generators/typescript-fetch.md` as well. Any ideas?

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Tagging the technical committee for review:
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### CODE REVIEW

**Review by prince-chrismc — APPROVED** [review]

**Comment by macjohnny** [comment]
thanks for your contribution.
did you run `./bin/utils/export_docs_generators.sh`?
since this is a breaking-change with fallback, we should aim for the next minor release.

**Review by macjohnny — APPROVED** [review]
LGTM

**Review by TiFu — COMMENTED** [review]
Thank you for the PR! Code looks good to me as well.

As mentioned by macjohnny please regenerate the samples or apply the below patch to your code (`git apply copy_below_patch_into_this_file.patch`). 

Patch based on your repository & `mvn clean package; ./bin/utils/export_docs_generators.sh`

```
diff --git a/docs/generators/typescript-fetch.md b/docs/generators/typescript-fetch.md
index f8e9cd2328a..8a080239a01 100644
--- a/docs/generators/typescript-fetch.md
+++ b/docs/generators/typescript-fetch.md
@@ -26,7 +26,7 @@ These options may be applied as additional-properties (cli) or configOptions (pl
 |sortModelPropertiesByRequiredFlag|Sort model properties to place required parameters before optional parameters.| |true|
 |sortParamsByRequiredFlag|Sort method arguments to place required parameters before optional parameters.| |true|
 |supportsES6|Generate code that conforms to ES6.| |false|
-|typescriptThreePlus|Setting this property to true will generate TypeScript 3.6+ compatible code.| |false|
+|typescriptThreePlus|Setting this property to true will generate TypeScript 3.6+ compatible code.| |true|
 |useSingleRequestParameter|Setting this property to true will generate functions with a single argument containing all API endpoint parameters instead of one argument per parameter.| |true|
 |withInterfaces|Setting this property to true will generate interfaces next to the default class implementations.| |false|
 |withoutRuntimeChecks|Setting this property to true will remove any runtime checks on the request and response payloads. Payloads will be casted to their expected types.| |false|
```

**Comment by szTheory** [comment]
Thanks for reviewing this!

@macjohnny yes I did run `./bin/utils/export_docs_generators.sh`

@TiFu I followed your instructions, but after running `mvn clean package; ./bin/utils/export_docs_generators.sh` it clobbers the diff and I'm left with no changes in the git repository when I run `git diff`. Not sure what is going on. It's like the generated docs are not picking up the change from the source material somehow.

**Comment by TiFu** [comment]
@szTheory I would suggest that you just manually edit the file/apply the patch, then commit & push (i.e. skip the mvn clean package stuff). As long as the edits are committed, the tests will pass.


(If you feel like debugging this: what OS do you use? Are you using any IDE that might interfere? Are you running both clean package and export docs from a shell?)

**Comment by szTheory** [comment]
@TiFu Thanks I applied the patch and pushed the change but a few of the CI tests are still failing

**Comment by TiFu** [comment]
All of the failures seem to be unrelated - I will close & reopen this PR to rerun the tests as it looks like there were some download issues on sonatype's side.

- The maven plugin tests failed because oai-generator-maven-plugin couldn't be resolved in sonatype. 
- Gradle seems to be related - it's complaining about a missing package
- CircleCI also could not resolve some random package - caused by pkmst-microservice
- Appveyor failed due to a missing gradle dependency (same fault as above)

**Comment by TiFu** [comment]
@wing328 Can you maybe chime in here? I am a bit unsure where the errors come from, e.g. the below (from maven plugin tests)

```
Error:  Plugin org.openapitools:openapi-generator-maven-plugin:5.2.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.openapitools:openapi-generator-maven-plugin:jar:5.2.0-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
Error: Process completed with exit code 1.
```

**Comment by macjohnny** [comment]
@szTheory can you please merge the most recent master into your branch?

**Comment by szTheory** [comment]
@macjohnny I've merged master and ran the commands to build the project and update samples:

```bash
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```

**Comment by macjohnny** [comment]
sorry for the inconvenience, but can you rebase your branch onto the most recent master? I guess you started off from the 5.3 branch

**Comment by macjohnny** [comment]
@szTheory ping

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/11331

**Pull request closed without merging**
