### PR TITLE
Java importmapping 3589

### PR DESCRIPTION
**Pull request by pe-st**
Fix from @bkoziak to make `importMapping` work for Java: #3589 

All the code in this PR was contributed by @bkoziak, I did just the merging and added one unit test.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [n/a] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [n/a] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. Java: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608

### CODE REVIEW

**Comment by pe-st** [comment]
Do I need to do anything so that the PR can be merged? Should I declare the Bug #3589 as fixed now or only once this PR has been merged?

**Comment by wing328** [comment]
UDPATE: merged latest master into this branch but got the following error:
```
[main] ERROR org.openapitools.codegen.DefaultCodegen - body in fromRequestBody cannot be null!
[main] ERROR org.openapitools.codegen.utils.ModelUtils - Schema cannot be null in isFreeFormObject check
[ERROR] Tests run: 1032, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.385 s <<< FAILURE! - in TestSuite
[ERROR] modelTest(org.openapitools.codegen.python.PythonClientExperimentalTest)  Time elapsed: 0.058 s  <<< FAILURE!
java.lang.AssertionError: expected [V1beta3Binding] but found [v1beta3_binding.V1beta3Binding]
	at org.openapitools.codegen.python.PythonClientExperimentalTest.modelTest(PythonClientExperimentalTest.java:54)
```

Updated that test cases but found that python experimental petstore samples will have some changes such as
```diff
--- a/samples/client/petstore/python-experimental/petstore_api/api/fake_api.py
+++ b/samples/client/petstore/python-experimental/petstore_api/api/fake_api.py
@@ -538,7 +538,7 @@ class FakeApi(object):
                 async_req (bool): execute request asynchronously
 
             Returns:
-                outer_number.OuterNumber
+                float
                     If the method is called asynchronously, returns the request
                     thread.
             """
@@ -565,7 +565,7 @@ class FakeApi(object):
 
         self.fake_outer_number_serialize = Endpoint(
             settings={
-                'response_type': (outer_number.OuterNumber,),
+                'response_type': (float,),
```

so I need some time to figure out why there's a change to codegenOperation.returnBaseType:
```diff
-        Assert.assertEquals(codegenOperation.returnBaseType, "V1beta3Binding");
+        Assert.assertEquals(codegenOperation.returnBaseType, "v1beta3_binding.V1beta3Binding");
```

**Comment by pe-st** [comment]
> UDPATE: merged latest master into this branch but got the following error:
> 
> ```
> [main] ERROR org.openapitools.codegen.DefaultCodegen - body in fromRequestBody cannot be null!
> [main] ERROR org.openapitools.codegen.utils.ModelUtils - Schema cannot be null in isFreeFormObject check
> [ERROR] Tests run: 1032, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 36.385 s <<< FAILURE! - in TestSuite
> [ERROR] modelTest(org.openapitools.codegen.python.PythonClientExperimentalTest)  Time elapsed: 0.058 s  <<< FAILURE!
> java.lang.AssertionError: expected [V1beta3Binding] but found [v1beta3_binding.V1beta3Binding]
> 	at org.openapitools.codegen.python.PythonClientExperimentalTest.modelTest(PythonClientExperimentalTest.java:54)
> ```

I found the reason for the test failure (my branch introduced a new method in an ancestor class of the `PythonClientExperimentalCodegen` class).

I'll have a fix shortly

**Comment by wing328** [comment]
@pe-st thanks for the quick fix. All tests passed. I'll take a look tomorrow and merge if no question from me or anyone.

**Comment by wing328** [comment]
@pe-st thanks for the PR, which has been included in the 4.3.0 release: https://twitter.com/oas_generator/status/1243455743937789952

**Pull request merged**
