### PR TITLE
Add 'bin/ensure-up-to-date' script and update Shippable CI

### PR DESCRIPTION
**Pull request by jmini**
Fix for #80

### CODE REVIEW

**Comment by jmini** [comment]
Build of aa320fe3c1353fd892f2a7cad5a0bba3bf06652c now looks like the way I expect. 

> Shippable — Run 345 status is FAILED. 

With this in the logs:

```
UNCOMMITTED CHANGES ERROR
There are uncommitted changes in working tree after execution of 'bin/ensure-up-to-date'
On branch issue80_ensure_samples_up-to-date
Your branch is up to date with 'origin/issue80_ensure_samples_up-to-date'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   samples/client/petstore/ruby/docs/FakeApi.md

no changes added to commit (use "git add" and/or "git commit -a")
Please run 'bin/ensure-up-to-date' locally and commit changes
```

Now I will update the outdated sample and see if the build is green.

**Comment by jmini** [comment]
Build of 06e1a143c9b0ad96b48f734357f9d88710aac40d looks good to me:

> Shippable — Run 350 status is SUCCESS. 

And in the Logs:

```
./bin/ensure-up-to-date
# START SCRIPT: ./bin/ensure-up-to-date
IMPORTANT: this script ...
....
Git working tree is clean
```

**Comment by jmini** [comment]
Build error of f86bb022e07c799cae7be0fc32983313d044df0a
> Shippable — Run 357 status is FAILED. 

is correct. Logs:

```
UNCOMMITTED CHANGES ERROR
There are uncommitted changes in working tree after execution of 'bin/ensure-up-to-date'
HEAD detached at FETCH_HEAD
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   samples/client/petstore/kotlin/README.md
	modified:   samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/models/Order.kt
	modified:   samples/server/petstore/kotlin-server/ktor/src/main/kotlin/org/openapitools/server/models/Pet.kt

no changes added to commit (use "git add" and/or "git commit -a")
Please run 'bin/ensure-up-to-date' locally and commit changes
```

**Comment by jimschubert** [comment]
@jmini it looks like you're doing some iterative verifications on this branch. Can you create/add a WIP label if this isn't ready to merge?

**Comment by jmini** [comment]
It is ready to merge, and the CI is green.

**Comment by jimschubert** [comment]
Sounds good! I'll go ahead and merge. I wasn't sure if you were adding all generators, but I agree doing it on separate PRs.

**Pull request merged**
