### PR TITLE
#18090 Insert missing quote in clientPropertiesConfiguration.mustache for the Spring generator

### PR DESCRIPTION
**Pull request by larsenf-els**
Bug fix for #18090: [BUG] Spring generator (7.4.0): Generated ClientPropertiesConfiguration constructor gives compiler error

Insert missing quote: `{{{tokenUrl}}}"` -> `"{{{tokenUrl}}}"` in the clientPropertiesConfiguration.mustache used by the Spring Generator.

@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg (2023/08)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.5.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by MelleD** [comment]
@larsenf-els nice catch, thanks for the PR. Could you also add test for the bugfix 👍

**Comment by larsenf-els** [comment]
> @larsenf-els nice catch, thanks for the PR. Could you also add a test for the bugfix 👍

Will do. :D

**Comment by larsenf-els** [comment]
> @larsenf-els Could you also add a test for the bugfix 👍

I have now added a unit test. I tested this with and without the fix in the [clientPropertiesConfiguration.mustache](https://github.com/OpenAPITools/openapi-generator/pull/18091/files#diff-447a49f2ca78f47fe4cdaaf0a6693238af22219f778844e279493f86143114f5) file.

**Comment by MelleD** [comment]
@larsenf-els thanks

@wing328 can be merged :)

**Review by MelleD — APPROVED** [review]

**Comment by wing328** [comment]
@larsenf-els thanks for the PR but the CI tests failed. Can you please fix it when you've time?

Ping me via Slack if you need help.

**Comment by wing328** [comment]
merged via https://github.com/OpenAPITools/openapi-generator/pull/18172 with a fix in the test

**Pull request closed without merging**
