### PR TITLE
[php][symfony] Use correct JMS/Serializer annotation for Date-Fields

### LINKED ISSUE #9984: [BUG] [PHP] [Symfony] JMS-Serializer Annotation should respect `date` format
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Defining any object with a string property _and_ `date` format, the php-symfony generator creates a wrong JMS\Serializer Annotation due to https://github.com/OpenAPITools/openapi-generator/blob/e20ccd49ed4f03051ec071dd2dfa09de13caf632/modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache#L44-L51 providing no constraint, which then defaults to a full-blown ISO:8601 date-time string.

##### openapi-generator version
5.1.1 & 5.2.0

##### OpenAPI declaration file content or url

```yaml
  #...
  type: object
  properties:
    birthday:
      type: string
      format: date
  #....
```

##### Generation Details
via Docker run command, with:
```bash
    openapitools/openapi-generator-cli:latest generate \
    --additional-properties disallowAdditionalPropertiesIfNotPresent="false" \
    --additional-properties modelPackage="DTO" \
    --additional-properties legacyDiscriminatorBehavior="false" \
    --additional-properties prependFormOrBodyParameters="true" \
    --additional-properties variableNamingConvention="camelCase" \
    --additional-properties phpLegacySupport="false" \
    --generator-name php-symfony \
    --input-spec /local/openapi/spec.yaml
    --output /local/<targetpath>
```

##### Steps to reproduce

* any apispec with a date-property defined like above snippet
* generated model classes (using parameters above) will result in a  DocBlock snippet like this:
```php
    /* ....
     * @Assert\Date()
     * @Type("DateTime")
     */
     protected $birthday
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/5080

##### Suggest a fix
Update linked [template](https://github.com/OpenAPITools/openapi-generator/blob/e20ccd49ed4f03051ec071dd2dfa09de13caf632/modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache#L44-L51) above to this:
```php
    {{#isDate}}
     * @Assert\Date()
     * @Type("DateTime<'Y-m-d'>")
    {{/isDate}}
    {{#isDateTime}}
     * @Assert\DateTime()
     * @Type("DateTime")
    {{/isDateTime}}
```

This instructs the JMS\Serializer not to look for a complete datetime string, but instead on fields marked as `date` only expect a "YYYY-mm-dd" type string as per RFC3339.

### PR DESCRIPTION
**Pull request by BigBadBassMan**
Fixes #9984 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by BigBadBassMan** [comment]
Mentioning @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon as per PR Requirements

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by BigBadBassMan** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

Thanks for the hint, didn't notice I was using a company user before, fixed now.

**Review by wing328 — APPROVED** [review]
LGTM but I've not tested the fix locally.

**Pull request merged**
