### PR TITLE
[kotlin] Fix non-compilable code

### PR DESCRIPTION
**Pull request by ackintosh**
This PR fixes https://github.com/OpenAPITools/openapi-generator/issues/2979

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by ackintosh** [comment]
Diffs generated codes between before and after this PR generated from [the spec](https://github.com/OpenAPITools/openapi-generator/issues/2979#issuecomment-581907162):

```diff
$ diff ../issue2979-before/src/main/kotlin/org/openapitools/client/models/Foo.kt src/main/kotlin/org/openapitools/client/models/Foo.kt

33,36c33,36
<         @Json(name = 0) _0(0),
<         @Json(name = 1) _1(1),
<         @Json(name = 2) _2(2),
<         @Json(name = 3) _3(3);
---
>         @Json(name = "0") _0(0),
>         @Json(name = "1") _1(1),
>         @Json(name = "2") _2(2),
>         @Json(name = "3") _3(3);

```

**Comment by ackintosh** [comment]
technical committee: @jimschubert (2017/09) , @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11)

**Comment by 4brunu** [comment]
Can you please update the pet projects by running `./mvnw package && ./bin/kotlin-client-all.sh` and commit the changes? Thanks

**Comment by ackintosh** [comment]
Thanks for your comment! I've noticed that a bug due to this PR from the results of `./bin/kotlin-client-all.sh`. 💦 

```sh
$ ./mvnw package && ./bin/kotlin-client-all.sh
...
...

$ gd samples/client/petstore/kotlin-json-request-string/src/main/kotlin/org/openapitools/client/models/Order.kt

    */

    enum class Status(val value: kotlin.String){
-        @Json(name = "placed") placed("placed"),
-        @Json(name = "approved") approved("approved"),
-        @Json(name = "delivered") delivered("delivered");
+        @Json(name = ""placed"") placed("placed"),
+        @Json(name = ""approved"") approved("approved"),
+        @Json(name = ""delivered"") delivered("delivered");
    }
}
```
 (duplicate double quotes)

I'll add a commit to fix the bug.

**Comment by ackintosh** [comment]
Now there are no diffs on the result of `./bin/kotlin-client-all.sh`.

```sh
$ ./mvnw package && ./bin/kotlin-client-all.sh
...
...

$ git status
On branch fix-2979
nothing to commit, working tree clean
```

---

Again I've confirmed that [the generated code is compilable](https://github.com/OpenAPITools/openapi-generator/pull/5205#issuecomment-581962972).

**Comment by jimschubert** [comment]
Thanks @ackintosh!

**Pull request merged**
