### PR TITLE
[Java][Feign]Remove oauth related code for non secured apis

### PR DESCRIPTION
**Pull request by hugo-ma-alves**
Hello

On the previous PR https://github.com/OpenAPITools/openapi-generator/pull/8318/files I forgot to take in account the cases where the API does not have any authentication mechanism.
If we use the current version of openapi-cli to generate the client for a non secured api, we will get Oauth related code on the output but not the required dependencies on the pom.xml/gradle. 

This PR removes the unnecessary code when the api is not configured to use authentication.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
--

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

### CODE REVIEW

**Comment by TobsCore** [comment]
The previous version breaks our build, since `scribejava` was not present as a library. After adding it, the generated classes will cause compile errors, since the `OAuth` class was not present and neither was `OAuthFlow` (enum?).

Therefore this change is very welcome. We are currently stuck on v5.0.0.

**Comment by pPanda-beta** [comment]
Good one, we really need this!

@hugo-ma-alves do you know any workarounds until this PR gets released?

**Comment by hugo-ma-alves** [comment]
Hello @pPanda-beta 

A quick and dirty workaround is to delete the affected code.

On ApiClient.java
```
private RequestInterceptor buildOauthRequestInterceptor(OAuthFlow flow, String authorizationUrl, String tokenUrl, String scopes) {
    switch (flow) {
      case password:
        return new OauthPasswordGrant(tokenUrl, scopes);
      case application:
        return new OauthClientCredentialsGrant(authorizationUrl, tokenUrl, scopes);
      default:
        throw new RuntimeException("Oauth flow \"" + flow + "\" is not implemented");
    }
  }
```

And delete the following files:
- OauthPasswordGrant
- OauthClientCredentialsGrant

**Comment by wing328** [comment]
@hugo-ma-alves thanks for the PR but sorry that I missed it. I've done it via https://github.com/OpenAPITools/openapi-generator/pull/9760 instead (merged into master). Can you please pull the latest master to give it a try?

Happy to reopen this one if needed.

**Comment by hugo-ma-alves** [comment]
Thanks @wing328 
Looks good!

**Pull request closed without merging**
