### PR TITLE
[TypeScript][Node] async promises and imports

### PR DESCRIPTION
**Pull request by kpturner**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Small modifications to the typescript-node mustache template to ensure that the result will transpile.

### CODE REVIEW

**Comment by macjohnny** [comment]
cc 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)

**Comment by wing328** [comment]
Update samples via https://github.com/OpenAPITools/openapi-generator/pull/2452/commits/bffca058b56111400d15fae892914db2a363107a. Let's see if all the tests pass

**Comment by kpturner** [comment]
Blimey do they always take this long to start?

**Comment by wing328** [comment]
Not sure why the Travis job was omitted but local test result looks good:
```
Checking deserialization.
Checking serialization
Created pet with ID 18291
Updated pet using POST body
Updated pet using POST form
Uploaded image
Got pet by ID: {"id":18291,"category":{"id":18291,"name":"TS category 1"},"name":"TypeScriptDoggie","photoUrls":["http://url1","http://url2"],"tags":[{"id":18291,"name":"TS tag 1"}],"status":"pending"}
EnumValue:  pending
Typeof EnumValue: string
Res: pending
Deleted pet
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:44 min
[INFO] Finished at: 2019-03-21T22:25:45+08:00
[INFO] ------------------------------------------------------------------------
```

**Comment by kpturner** [comment]
Will this now be part of version 3 or 4 or both?  When will I be safe to reinstall with Homebrew for example?

**Comment by wing328** [comment]
This is included in the 4.x. Please refer to https://github.com/OpenAPITools/openapi-generator/issues/1790 on how to brew install the latest master.

**Comment by kpturner** [comment]
OK I did that and ended up with 4.0.0-beta but that doesn't contain this fix?

**Comment by macjohnny** [comment]
@kpturner you need to adapt the `git checkout openapi-generator-4.0.0-beta` to `git checkout master`

**Comment by kpturner** [comment]
But there is no `Formula/openapi-generator.rb` in `master`?

**Comment by macjohnny** [comment]
I corrected my comment

**Comment by kpturner** [comment]
Oh wait - you mean I used the original instructions and adapt the `rb` file?  OK will try it.

**Comment by kpturner** [comment]
When I checked out `git checkout openapi-generator-4.0.0-beta` it already contained the code that you suggested I change so unfortunately I am still no further ahead.  The only way I seem to be able to run with this fixed is from my original maven build.

**Comment by macjohnny** [comment]
you need to change the url from `https://search.maven.org/remotecontent?filepath=org/openapitools/openapi-generator-cli/4.0.0-beta/openapi-generator-cli-4.0.0-beta.jar` to `https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.0.0-SNAPSHOT/openapi-generator-cli-4.0.0-20190321.151032-428.jar`

**Comment by kpturner** [comment]
OK - and I guess the `sha256` also needs to change?

**Pull request merged**
