### PR TITLE
[Java Jersey] Update ApiClient.mustache Jersey doesn't allow entities in method DELETE 

### PR DESCRIPTION
**Pull request by eric-rolli**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by eric-rolli** [comment]
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @martin-mfg
Correction for Java Jersey2/3 generation.

**Comment by wing328** [comment]
@eric-rolli thanks for the PR

If I remember correctly, some users need send the payload in DELETE request: https://github.com/OpenAPITools/openapi-generator/pull/13457

Given that your use cases do not require sending payload in DELETE request, what about leaving the code as it's?

**Comment by eric-rolli** [comment]
@wing328 
The problem is that the jersey library enforces that the entity must be null.
See org.glassfish.jersey.client.JerseyInvocation
https://github.com/eclipse-ee4j/jersey/blob/2.x/core-client/src/main/java/org/glassfish/jersey/client/JerseyInvocation.java
https://github.com/eclipse-ee4j/jersey/blob/4.0/core-client/src/main/java/org/glassfish/jersey/client/JerseyInvocation.java

	private static Map<String, EntityPresence> initializeMap() {
		HashMap<String, EntityPresence> map = new HashMap<String, EntityPresence>();
		map.put("DELETE", EntityPresence.MUST_BE_NULL);
		map.put("GET", EntityPresence.MUST_BE_NULL);
		map.put("HEAD", EntityPresence.MUST_BE_NULL);
		map.put("OPTIONS", EntityPresence.OPTIONAL);
		map.put("PATCH", EntityPresence.MUST_BE_PRESENT);
		map.put("POST", EntityPresence.OPTIONAL);
		map.put("PUT", EntityPresence.MUST_BE_PRESENT);
		map.put("TRACE", EntityPresence.MUST_BE_NULL);
		return map;
	}

	private void validateHttpMethodAndEntity(ClientRequest request) {
		String method;
		EntityPresence entityPresence;
		boolean suppressExceptions = PropertiesHelper.isProperty((Object) request.getConfiguration()
				.getProperty("jersey.config.client.suppressHttpComplianceValidation"));
		Object shcvProperty = request.getProperty("jersey.config.client.suppressHttpComplianceValidation");
		if (shcvProperty != null) {
			suppressExceptions = PropertiesHelper.isProperty((Object) shcvProperty);
		}
		if ((entityPresence = METHODS
				.get((method = request.getMethod()).toUpperCase(Locale.ROOT))) == EntityPresence.MUST_BE_NULL
				&& request.hasEntity()) {
			if (!suppressExceptions)
				throw new IllegalStateException(
						LocalizationMessages.ERROR_HTTP_METHOD_ENTITY_NOT_NULL((Object) method));
			LOGGER.warning(LocalizationMessages.ERROR_HTTP_METHOD_ENTITY_NOT_NULL((Object) method));
			return;
		} else {
			if (entityPresence != EntityPresence.MUST_BE_PRESENT || request.hasEntity())
				return;
			if (!suppressExceptions)
				throw new IllegalStateException(LocalizationMessages.ERROR_HTTP_METHOD_ENTITY_NULL((Object) method));
			LOGGER.warning(LocalizationMessages.ERROR_HTTP_METHOD_ENTITY_NULL((Object) method));
		}
	}

But the current openapi generated code always produces a non-null Entity object, even if the body in null.
See method serialize in ApiClient.mustache
For a null Body the Entity object will contain an empty string instead of null!


The result is that DELETE methods are not usable with the code generated for the jersey library.

Would the folling modification be OK?
    } else if ("DELETE".equals(method)) {
      if ("".equals(entity.getEntity())) {
        response = invocationBuilder.method("DELETE");
      } else {
        response = invocationBuilder.method("DELETE", entity);
      }

**Comment by wing328** [comment]
> Would the following modification be OK?

I think we can give it a try

**Comment by eric-rolli** [comment]
@wing328
I made the changes to send the entity only if it is not empty

**Comment by wing328** [comment]
thanks. let's give it a try

please test it later after snapshot version published (or test it locally)

**Pull request merged**
