### PR TITLE
[dart-dio] Correctly serialize path parameters

### PR DESCRIPTION
**Pull request by szekelyisz**
If the value of a parameter in the path is something that was camelized (enum values containing dashes for example), `toString()` will just return the string representation of the camelized value, not the original, which will fail validation on the server. Thus path parameters need to be properly serialized as well, this will map camelized values back to their original value as per OAS.

Attn: @jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela 

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ahmednfwela** [comment]
@szekelyisz can you please provide a schema that has this issue as a sample ?

**Comment by szekelyisz** [comment]
> @szekelyisz can you please provide a schema that has this issue as a sample ?

@ahmednfwela Consider this schema:

```json
			"MyEnum": {
				"type": "string",
				"enum": [
					"first-value",
					"second-value"
				]
			}
```

In Dart these values will be camelized resulting in `MyEnum.firstValue` and `MyEnum.secondValue`, respectively. If you want to use these in a path parameter of the method you want to invoke, the original code will just call `toString()` on these resulting in `"firstValue"` and `"secondValue"` which are not valid values so they will fail validation on the server.

This PR serializes path parameters as well, so enum values will be converted back to their wire format.

**Review by ahmednfwela — APPROVED** [review]

**Comment by wing328** [comment]
@szekelyisz can you please resolve the merge conflicts when you've time?

**Comment by szekelyisz** [comment]
> @szekelyisz can you please resolve the merge conflicts when you've time?

Sorry for the long delay @wing328. Resolved.

**Review by kuhnroyal — APPROVED** [review]

**Comment by tomdeering-wf** [comment]
@jaumard  @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob @ahmednfwela

Any reason not to merge this fix? I ran into this problem too and found this pull sitting here open!

**Comment by ahmednfwela** [comment]
@wing328

**Pull request merged**
