### PR TITLE
python-pydantic-v1: Keep trailing commas for enum validation tuples

### PR DESCRIPTION
**Pull request by chiragjn**
It can happen that sometimes a enum just has a single member

This can result in a pydantic validator that can be incorrect 
E.g.

```
class TestClass(BaseModel):
    type: StrictStr = Field(...)  # Say this can only take a single value like "test" 

    @validator('type')
    def type_validate_enum(cls, value):
        if value not in ("test"):
            raise ValueError(...)
```

If I do some substring of "test", e.g. `TestClass(type="tes")`  this validation will not fail

Then trailing `,` in this case is required

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

can you please add a test schema (enum with a single item) in modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml ?

**Comment by chiragjn** [comment]
Tagging @multani for early feedback. Will work on adding small tests

**Comment by chiragjn** [comment]
Updated samples and added a test

**Comment by chiragjn** [comment]
Tagging other members of Python committee
@cbornet @tomplus @krjakbrjak @fa0311

**Comment by multani** [comment]
@chiragjn did you consider replacing the tuples by lists instead?

Semantically, I think it would be more "correct", and syntax-wise it would also prevent this kind of problem.

**Comment by chiragjn** [comment]
Hmm, sure I don't mind doing that
Thought tuples are faster to allocate hence didn't change
Let me know

**Comment by multani** [comment]
I'm not sure if that makes such a difference ; if this was a performance problem too, they should be created only once anyway as they are all constants in the end.

We can merge this as it is though.

**Review by multani — APPROVED** [review]
lgtm

@wing328 any preference between tuples and lists? Lists would have prevented this bug in the first place, at the expense of a slight performance penalty.

**Comment by wing328** [comment]
to me, this is more like an edge case so my take is to use tuple instead.

**Pull request merged**
