### PR TITLE
Add equals and hashCode methods to Microprofile

### LINKED ISSUE #19910: [REQ] [Java][Microprofile] Add equals() & hashCode()
### Is your feature request related to a problem? Please describe.

Comparing models is complicated when not having an equals method. Methods like (some) collection's contains() also don't work properly.

## Describe the solution you'd like

Add the equals and hashCode methods to the pojo. Maybe put them as a new .mustache template so it can easily be customized / reverted to the default behavior.

### PR DESCRIPTION
**Pull request by DielN**
Closes #19910 

Added `equals` and `hashCode` methods to the Java Microprofile generator. The methods were copied over from the Java generator. As I suggested in the issue, I added a new template for this so it is easier to customize these if needed. I decided to also put the `toString` method in there to allow for easy customization as well. So all of the pojo's `Object` method overrides are now in that template.

~~This is a draft for now as I still need to do testing.~~

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by DielN** [comment]
This is ready for review now.
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

**Review by martin-mfg — APPROVED** [review]

**Comment by wing328** [comment]
```diff
--- a/bin/configs/java-microprofile-rest-client-3.0-jackson.yaml
+++ b/bin/configs/java-microprofile-rest-client-3.0-jackson.yaml
@@ -9,3 +9,4 @@ additionalProperties:
   configKey: petstore
   microprofileRestClientVersion: "3.0"
   hideGenerationTimestamp: true
+  useReflectionEqualsHashCode: true

```

I did  a test with the above change, updated the samples but then I got errors when running `mvn integration-test -f samples/client/petstore/java/microprofile-rest-client-3.0-jackson/pom.xml`

```
ect microprofile-rest-client-3-jackson: Compilation failure: Compilation failure:
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/User.java:[15,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/User.java:[16,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Category.java:[15,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Category.java:[16,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Tag.java:[15,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Tag.java:[16,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Pet.java:[15,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Pet.java:[16,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/ModelApiResponse.java:[15,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/ModelApiResponse.java:[16,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Order.java:[15,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Order.java:[16,40] package org.apache.commons.lang3.builder does not exist
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/User.java:[272,12] cannot find symbol
[ERROR]   symbol:   variable EqualsBuilder
[ERROR]   location: class org.openapitools.client.model.User
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/User.java:[277,12] cannot find symbol
[ERROR]   symbol:   variable HashCodeBuilder
[ERROR]   location: class org.openapitools.client.model.User
[ERROR] /C:/Users/wing3/Code/openapi-generator/samples/client/petstore/java/microprofile-rest-client-3.0-jackson/src/main/java/org/openapitools/client/model/Category.java:[95,12] cannot find symbol
[ERROR]   symbol:   variable EqualsBuilder
[ERROR]   location: class org.openapitools.client.model.Category

```

Does it work for you locally?

**Comment by wing328** [comment]
please also update bin/configs/java-microprofile-rest-client-3.0-jackson.yaml with `useReflectionEqualsHashCode: true` so that we have `useReflectionEqualsHashCode` covered moving forward.

**Comment by DielN** [comment]
Good catch, I missed that. The commons-lang3 dependency was missing in the pom.

There are actually quite a lot of libraries (all except okhttp in fact) where that dependency is missing. I suppose I'll create an issue for that.

**Comment by wing328** [comment]
> There are actually quite a lot of libraries (all except okhttp in fact) where that dependency is missing. I suppose I'll create an issue for that.
> 
> The 3.0 pom is also missing the mutiny dependency, but I suggest just fixing that with the other issues in another PR

yes please 🙏

**Pull request merged**
