### PR TITLE
typescript-rxjs: fix query parameters type

### LINKED ISSUE #4159: [BUG] [typescript-rxjs] Typescript error in generated files for query parameters
##### Description

In case Typescript strict mode is on, there is typescript error in the generated code if a function has one or more query parameters.

##### openapi-generator version

4.0.3 - 4.1.3

##### OpenAPI declaration file content or url

The standard petstore yaml file that is used to generate the samples.

##### Command line used for generation

See the samples directory for the generated files.

##### Steps to reproduce

* Download the typescript-rxjs/default (or any other) sample from the github master branch
* Copy it into a project where typescript strict mode is on, or
* Just open it in Visual Code to see the error in UserApi.ts loginUser function.

Generated code:

`   const query: HttpQuery = {
            ...(requestParameters.username && { 'username': requestParameters.username }),
            ...(requestParameters.password && { 'password': requestParameters.password }),
        };`

Error message:

`Type '{} | { 'username': string; } | { 'password': string; } | { 'password': string; 'username': string; }' is not assignable to type 'HttpQuery'.
  Type '{}' is not assignable to type 'HttpQuery'.
    Index signature is missing in type '{}'.`

##### Related issues/PRs

none

##### Suggest a fix

The generated code was ok until 4.0.2. It would be good to check why the mustache files were changed to the new code.

### PR DESCRIPTION
**Pull request by macjohnny**
fixes #4159 

cc @akehir @denyo

### CODE REVIEW

**Comment by denyo** [comment]
I would have preferred the `as` operator like `as HttpQuery`.

**Comment by denyo** [comment]
Or even cleaner would be extending the definition of `HttpQuery`:
```
type HttpQuery = { [key: string]: string | number | null | boolean | Array<string | number | null | boolean> } | {};
```
Then the generated controllers would not be affected at all.

**Comment by macjohnny** [comment]
@denyo will you file a PR to make the changeS?

**Comment by denyo** [comment]
I can't before next week.

**Comment by macjohnny** [comment]
with
```typescript
type HttpQuery = { [key: string]: string | number | null | boolean | Array<string | number | null | boolean> } | {};
```
the type-safety is lost, i.e. 
```typescript
const bla: HttpQuery = { bla: new SomeObject()};
```
can be assigned without errors. See http://www.typescriptlang.org/play/index.html?ssl=13&ssc=47&pln=13&pc=1#code/C4TwDgpgBAEsxgIoFcICcRQLxQN5QG0BrCEALigGdg0BLAOwHMBdC6upqAHynuQFsARum69kAG3GjBAexniIAQ3qiAgmjSKQAHnYNGovkJE8+k6XIXKAfFAC+o3HYDcAWABQHgMYz61KGgQAI6o1AAKipr8EMDolNh4HlDJUMiU6PSK0RQA5DkANEkpYIqUlADuMmgAJrk5HnYe3r7+QRRwCCjomDhObu4+fsBQId3t8EioGAn4AHTzABSBo+GRWTFxs2kZ61AAZHt4UDnbaJnRORTLocARURtolFvpZ7t2AJT5UPOzS8E3d3WsUesxKZUqNX2h3wOTBFSq1UuAX+EFW92BTzhEOq9k+9n6g1aUxAACZxp1iQltB1Jt1rHNFtdUbc1tEMc8dtEoUcTi9zhAkUy0UDNqd+bivj8-isWejNliEdyYQqaoKUcK2fLSvDIR8vi4mu4APRGqgACxkEhx9BkwwhRGaQyggnEinJtOmvWdroo9Ag5SgADEqvwACKKYCKBbvA3uIA

**Pull request merged**
