### PR TITLE
python: Add gitlab-ci.mustache

### PR DESCRIPTION
**Pull request by LoveIsGrief**
It does the same stuff as in the .travis.yml but just for Gitlab CI: run nosetests

An example of the result can be found [here](https://framagit.org/peertube-test/apis/python/blob/gitlab-ci/.gitlab-ci.yml)

Related to #5340

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

---------------------

Tagging the python technical committee: @taxpon @frol  @mbohlool @cbornet  @kenjones-cisco  @tomplus  @Jyhess  @slash-arun  @spacether 

I see a `tox.ini` but `.travis.yml` doesn't use it, so I don't know whether nosetests is the way to go here.

### CODE REVIEW

**Comment by wing328** [comment]
> I see a tox.ini but .travis.yml doesn't use it, so I don't know whether nosetests is the way to go here.

I think tox.ini is used by the command specified in pom.xml to run python petstore tests (both 2.x and 3.x) in Travis CI.

**Comment by spacether** [comment]
Nosetests are no longer used by default. Please see the cli option useNose https://openapi-generator.tech/docs/generators/python/
Can you submit a new PR which brings this in line with the rest of our python test runners?
pytest should be used when useNose is false

**Comment by LoveIsGrief** [comment]
@spacether should I update [`travis.mustache`](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/travis.mustache) too? It doesn't use respect that option either.

**Comment by spacether** [comment]
Good catch @lovelsgrief
Yes, that travis file should also let our users swap between nose and pytest depending on the useNose input.

**Comment by LoveIsGrief** [comment]
OK. Will I need to create an issue first before creating a PR?

**Comment by wing328** [comment]
@LoveIsGrief you can open a PR directly.

**Comment by wing328** [comment]
@LoveIsGrief thanks for the PR, which has been included in the 4.3.0 release: https://twitter.com/oas_generator/status/1243455743937789952

**Pull request merged**
