### PR TITLE
[BUG][csharp-netcore] Fix Multi Files for the same FormField  (#11132)

### PR DESCRIPTION
**Pull request by joaocmendes**
Fix issue #11132

FileParameters at Request Options is a Dictionary so we weren't able to send more than one file with the same key.
Refactor FileParamerts to Multimap to enable sending more than one file with the same key.

I did the development only for csharp-netcore but it has no impacts and can be made to the others generators.

If you find it useful say it at the review.
@mandrean 
@shibayan 
@Blackclaws 
@lucamazzanti 

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
C# tests (with updates samples passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/builds/42144330 )

**Comment by joaocmendes** [comment]
I've done a force push because I follow the instructions to generate the samples and it added a lot of changes for slash replacement. I reset and commit only things related to this issue. 
I don't know why the build failed, I tried to look to logs but didn't add much.  May we re-run the job?

**Comment by wing328** [comment]
The bitrise CI failure can be ignored.

**Comment by wing328** [comment]
@joaocmendes thanks for the PR, which has been merged into master.

**Pull request merged**
