### PR TITLE
Revert "[Ruby] Client: fix base_url when no server_operation_index is…

### PR DESCRIPTION
**Pull request by ColeMurray**
… defined (#15162)"

This reverts commit 2679819694ccf8f49a61c83a52f5d9a6fed07810.

https://github.com/OpenAPITools/openapi-generator/issues/15610

### PR checklist
 
- [ x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by Confusion** [comment]
The previous version, to which this reverts, didn't work for anyone outside of @ColeMurray's use case, so reverting this change doesn't seem like the best thing for the general good. A fix that restores the behavior as I now understand it was intended would be to replace:

index = server_operation_index[operation]

by

index = server_operation_index[operation || server_index]

**Comment by ColeMurray** [comment]
> The previous version, to which this reverts, didn't work for anyone outside of @ColeMurray's use case, so reverting this change doesn't seem like the best thing for the general good. A fix that restores the behavior as I now understand it was intended would be to replace:
> 
> ```ruby
> index = server_operation_index[operation]
> ```
> 
> by
> 
> ```ruby
> index = server_operation_index[operation || server_index]
> ```

We should separate improvements from backwards incompatible changes. While I am in agreement the existing scenario (prior to this change) was not ideal, this does introduce a regression and breaks existing users. We should revert and fast follow with a patch.

The above proposed fix would not work. The existing behavior relies on the .fetch(...) of ruby returning the server_index when nothing is found. In the previous code, server_operation_index will be empty, causing it to default to server_index and select the correct server url.

A potential fix would be to update the constructor and have server_index set to nil. It is only used within this base_url generation. This would allow the expected behavior of returning the `#{scheme}...` line of code, while allowing overrides to continue to work as-is.

**Comment by ColeMurray** [comment]
@wing328 can you restart the linux test? It appears to have stalled

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/16144

Can you please pull the latest master to give it another try? (or use the snapshot version)

**Pull request closed without merging**
