### PR TITLE
[Java] Support cookie-based security schemas in Java clients

### PR DESCRIPTION
**Pull request by atsharp**
This PR provides Java support for cookie-based security schemas as described in the OpenAPI spec [here](https://swagger.io/specification/#securitySchemeObject). Where easily possible, existing clients were amended to include the addition of cookie parameters as well (which is also part of the OpenAPI spec [here](https://swagger.io/specification/#parameterObject)). 

Certain clients (such as `feign`) do not provide explicit support for cookies, in which case a `Cookie` header was included to support this feature. Likewise, certain clients (such as `native) were excluded from this PR as they appear to lack support for authentication schemas altogether.

It is likely additional changes should be introduced to provide comprehensive support for cookie-based security schemas and parameters, however, these changes should allow cookie-based security schemas to be used in the majority of Java clients.

CC: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before .
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
CI reports the following errors:
```
[ERROR] COMPILATION ERROR : 
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/ApiKeyAuthTest.java:[21,13] method applyToParams in class org.openapitools.client.auth.ApiKeyAuth cannot be applied to given types;
  required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
  found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
  reason: actual and formal argument lists differ in length
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/ApiKeyAuthTest.java:[40,13] method applyToParams in class org.openapitools.client.auth.ApiKeyAuth cannot be applied to given types;
  required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
  found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
  reason: actual and formal argument lists differ in length
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/HttpBasicAuthTest.java:[28,13] method applyToParams in class org.openapitools.client.auth.HttpBasicAuth cannot be applied to given types;
  required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
  found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
  reason: actual and formal argument lists differ in length
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/HttpBasicAuthTest.java:[39,13] method applyToParams in class org.openapitools.client.auth.HttpBasicAuth cannot be applied to given types;
  required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
  found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
  reason: actual and formal argument lists differ in length
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/HttpBasicAuthTest.java:[47,13] method applyToParams in class org.openapitools.client.auth.HttpBasicAuth cannot be applied to given types;
  required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
  found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
  reason: actual and formal argument lists differ in length
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project petstore-java-client-jersey1: Compilation failure: Compilation failure:
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/ApiKeyAuthTest.java:[21,13] method applyToParams in class org.openapitools.client.auth.ApiKeyAuth cannot be applied to given types;
[ERROR] required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/ApiKeyAuthTest.java:[40,13] method applyToParams in class org.openapitools.client.auth.ApiKeyAuth cannot be applied to given types;
[ERROR] required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/HttpBasicAuthTest.java:[28,13] method applyToParams in class org.openapitools.client.auth.HttpBasicAuth cannot be applied to given types;
[ERROR] required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/HttpBasicAuthTest.java:[39,13] method applyToParams in class org.openapitools.client.auth.HttpBasicAuth cannot be applied to given types;
[ERROR] required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] reason: actual and formal argument lists differ in length
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/jersey1/src/test/java/org/openapitools/client/auth/HttpBasicAuthTest.java:[47,13] method applyToParams in class org.openapitools.client.auth.HttpBasicAuth cannot be applied to given types;
[ERROR] required: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] found: java.util.List<org.openapitools.client.Pair>,java.util.Map<java.lang.String,java.lang.String>
[ERROR] reason: actual and formal argument lists differ in length
```

Ref: https://circleci.com/gh/OpenAPITools/openapi-generator/9622

Please take a look when you've time.

Thanks a lot for adding cookie support to all Java client generators

**Comment by atsharp** [comment]
Whoops. Will take a look. Thanks!

**Comment by atsharp** [comment]
@wing328, seems like there's some issue running Circle CI. Would you mind restarting it for me? Thanks

**Comment by wing328** [comment]
@atsharp can you please merge the latest master of the official repo to your branch as CircleCI has made some changes and we've fixed the issue by updating the config file?

**Comment by atsharp** [comment]
@wing328 is there a way to get more details on the test failures in the above build? Not seeing any failures when running locally but CI is reporting something. Thanks

**Comment by wing328** [comment]
Just restarted both. Let's see how it goes

**Comment by wing328** [comment]
@atsharp all tests passed. Nice work!

**Comment by atsharp** [comment]
Thanks :)

**Comment by wing328** [comment]
@atsharp thanks for the PR, which has been included in v4.2.0 release: https://twitter.com/oas_generator/status/1189824932345069569

**Pull request merged**
