### PR TITLE
[kotlin] add testFolder configuration for kotlin

### PR DESCRIPTION
**Pull request by fj-roman**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Description of the PR
add an testFolder property for Kotlin in general and add api_test.mustache files for kotlin-spring generator.

@jimschubert , @dr4ke616 @karismann @Zomzog

### CODE REVIEW

**Comment by fj-roman** [comment]
How to trigger the quality checks?

**Comment by karismann** [comment]
i think you should create a dedicated branch on your forked repo instead of commiting this PR directly on master

**Comment by fj-roman** [comment]
I think this dosen't help to trigger the checks! See #2975

**Comment by fj-roman** [comment]
Now it works. I continue the PR on #2975 and close this one. Sorry for confusion.

**Pull request closed without merging**
