### PR TITLE
Add compilation test to typescript-angular-v13-provided-in-root petst…

### PR DESCRIPTION
**Pull request by cghislai**
…ore sample

This adds a simple test to ensure the generated typescript-angular-v13-provided-in-root code is compilable.

This would prevent issues such as #10975, #10864, or #11172 (all duplicates) to occur.

 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by cghislai** [comment]
@amakhrov can you check this if travis builds? thanks.

**Comment by cghislai** [comment]
the error on ci/circleci: node0 does not appear to be related to this change?

**Comment by amakhrov** [comment]
@cghislai it doesn't seem related, right. However, it's suspicious that both your PRs have the same failure.

I can see 2 recently merged PRs related to spring-mvc generator (the one that fails in your PR). Is it possible that your branch is behind `master` and this causes the issue?

**Comment by cghislai** [comment]
i was lagging by 1 commit. I could generate the spring-mvc sample javadoc locally. I see there is a file encoding error, and that it is triggered when the samples input changed (and `[info] Code generation is skipped because input was unchanged` is not logged). I will look into it later, hopefully its as simple as specifying the encoding in the pom.

**Comment by cghislai** [comment]
I will wait for #11477 to be merged to fix circleci builds then rebase

**Comment by cghislai** [comment]
@[amakhrov](https://github.com/amakhrov), the build errors have been fixed. can you have another look?
Thanks

**Review by amakhrov — APPROVED** [review]
@сghislai thanks! LGTM

**Pull request merged**
