### PR TITLE
[JAVA] Add apache httpcomponts library to java clients

### LINKED ISSUE #9866: [REQ] [JAVA] Apache httpcomponents client library
### Is your feature request related to a problem? Please describe.

Support generating a java client using the apache [httpcomponents client][lib]

## Describe the solution you'd like

A new library option for the java client

## Describe alternatives you've considered

N/A

## Additional context

I am working in a project that already makes use of httpcomponents so we were interested in generating a client using that library. Have already started some work looking into this, just wanted to open an issue see if this is something that could be contributed here.

[lib]: https://hc.apache.org/httpcomponents-client-4.5.x/index.html

### PR DESCRIPTION
**Pull request by harrywhite4**
Added the option to generate a java client using the apache [httpcomponents][lib] library. Have opened against the 5.3.x branch since i thought this would not be part of a patch release, let me know if i need to change that

I did do some testing of the generated code in a separate project, wasn't sure how that could be integrated into the testing of the samples though.

Tech commitee: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch 

This closes #9866 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

[lib]: https://hc.apache.org/httpcomponents-client-4.5.x/index.html

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
You can target this change (additional support of HTTP library) to the current master.

**Comment by wing328** [comment]
I've resolved the merge conflicts and filed https://github.com/OpenAPITools/openapi-generator/pull/10218 instead so closing this one.

**Comment by harrywhite4** [comment]
Thanks for cleaning that up, i did use a different email but thats all good

**Pull request closed without merging**
