### PR TITLE
Angular 12 Support: Typescript upgrade + HttpContext

### LINKED ISSUE #9511: [REQ] [typescript-angular] Support Angular 12
### Is your feature request related to a problem? Please describe.

I want to have the API clients generated using ngVersion=12.0.0.
## Describe the solution you'd like
Update the typescript and ngpackagr dependencies if ngVersion is set to 12.
Here are the only changes required in the _package.json_ file.
Screenshot from 2021-05-24 18-40-13

### LINKED ISSUE #9957: [Request] Update Typescript and used angular to the latest version
#### Bug Report Checklist
- [X] Have you searched for related issues/PRs?

##### Description
I would like to build my whole angular project with recent package, but the package.json generated by OpenAPI still requires version 4.0.8 in the latest version.

##### openapi-generator version
5.2.0

##### Suggest a fix
Please update the typescript version to >= 4.3.5 and angular to 12

### LINKED ISSUE #10144: [BUG] TypeScript version not compatible with Angular 12
##### Description
Typescript script version is not compatible with angular version 12.1.2, giving below error while doing ng build,
× Compiling with Angular in legacy View Engine compilation mode.
The Angular Compiler requires TypeScript >=4.2.3 and <4.4.0 but 4.0.8 was found instead.bar 

##### openapi-generator version
<version>5.2.0</version>

##### OpenAPI declaration file content or url

<configuration>
                                    <inputSpec>${project.basedir}/target/openapi.json</inputSpec>
                                    <generatorName>typescript-angular</generatorName>
                                    
                                    
 
                                    
                                    <output>${project.basedir}/eap-group-services-client-angular</output>
                                    <configOptions>
 
                                        <npmName>@anthem/eap-groups-angular-client</npmName> 
                                        <npmRepository>------------</npmRepository>
                                        <providedInRoot>true</providedInRoot>
                                        <apiModulePrefix>EAPGroupsService</apiModulePrefix>
                                        <ngVersion>12.1.2</ngVersion>
                                        <stringEnums>true</stringEnums>
 
                                    </configOptions>.
  -->

##### Steps to reproduce

Open api generated package.json
 "peerDependencies": {
    "@angular/core": "^12.1.2",
    "rxjs": "^6.6.0"
  },
  "devDependencies": {
    "@angular/common": "^12.1.2",
    "@angular/compiler": "^12.1.2",
    "@angular/compiler-cli": "^12.1.2",
    "@angular/core": "^12.1.2",
    "@angular/platform-browser": "^12.1.2",
    "ng-packagr": "^11.0.2",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^6.6.0",
    "tsickle": "^0.39.1",
    "typescript": ">=4.0.0 <4.1.0",
    "zone.js": "^0.11.3"
  },

My dependencies:

// Spring Docs
implementation 'org.springdoc:springdoc-openapi-webflux-ui:1.5.10'

### LINKED ISSUE #10148: [BUG] TypeScript version not compatible with Angular 12
##### Description
Typescript script version is not compatible with angular version 12.1.2, giving below error while doing ng build,
× Compiling with Angular in legacy View Engine compilation mode.
The Angular Compiler requires TypeScript >=4.2.3 and <4.4.0 but 4.0.8 was found instead.bar 

##### openapi-generator version
<version>5.2.0</version>

##### OpenAPI declaration file content or url

<configuration>
                                    <inputSpec>${project.basedir}/target/openapi.json</inputSpec>
                                    <generatorName>typescript-angular</generatorName>
                                    
                                    
 
                                    
                                    <output>${project.basedir}/eap-group-services-client-angular</output>
                                    <configOptions>
 
                                        <npmName>@anthem/eap-groups-angular-client</npmName> 
                                        <npmRepository>------------</npmRepository>
                                        <providedInRoot>true</providedInRoot>
                                        <apiModulePrefix>EAPGroupsService</apiModulePrefix>
                                        <ngVersion>12.1.2</ngVersion>
                                        <stringEnums>true</stringEnums>
 
                                    </configOptions>.
  -->

##### Steps to reproduce

Open api generated package.json
 "peerDependencies": {
    "@angular/core": "^12.1.2",
    "rxjs": "^6.6.0"
  },
  "devDependencies": {
    "@angular/common": "^12.1.2",
    "@angular/compiler": "^12.1.2",
    "@angular/compiler-cli": "^12.1.2",
    "@angular/core": "^12.1.2",
    "@angular/platform-browser": "^12.1.2",
    "ng-packagr": "^11.0.2",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^6.6.0",
    "tsickle": "^0.39.1",
    "typescript": ">=4.0.0 <4.1.0",
    "zone.js": "^0.11.3"
  },

My dependencies:

// Spring Docs
implementation 'org.springdoc:springdoc-openapi-webflux-ui:1.5.10'

### PR DESCRIPTION
**Pull request by andrew-matteson**
This PR adds Angular 12 support to the generated client. It upgrades the dependencies in the generated library. It adds `context: HttpContext()` as an option to the methods of the generated service.

This PR:
Fixes #9511 
Fixes #9957 
Fixes #10144 
Fixes #10148 

I've used this to integrate a generated client in my own product that leverages Angular 12 and `HttpContext`s.

For users that are on Angular <= 11, this PR will require supplying the `ngVersion` to the command line. I don't consider this a breaking change, but let me know if this project does.

### PR checklist
 
- [ x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu @taxpon @sebastianhaas  @kenisteward  @Vrolijkx @macjohnny  @topce (@akehir  @petejohansonxo @amakhrov

### CODE REVIEW

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by macjohnny** [comment]
Thanks for your contribution!
Please re-generate and commit all changed samples. Since there is a fallback for the breaking change, we can include this PR in the next minor release.

**Comment by andrew-matteson** [comment]
@macjohnny Done! Thank you. LMK if you need anything further from me for this to be merged.

**Comment by soxyl** [comment]
Thanks, @andrew-matteson for implementing Angular 12 support. This helps us a lot.

I just tried the changes and generating the client works so far. Running `npm install` in the generated client the command fails though.
This is because the generated `package.json` has the following dependengies
- `"tsickle": "^0.43.0"`
- `"typescript": ">=4.2.3 <4.3.0"`

[Tsickle 0.43.0](https://github.com/angular/tsickle/blob/v0.43.0/package.json#L31) itself depends on `"typescript": "~4.3"`, which causes the dependency resolution to fail..

Is there any special reason for not allowing Typescript 4.3.0 or would it be possible to allow Typescript 4.3.0 in the generated client?

**Comment by bsreddy125** [comment]
@macjohnny Is there any release version created for ANGULAR 12 support? If not any planned release near future?

**Comment by macjohnny** [comment]
5.3.0 should be released soon, see https://github.com/OpenAPITools/openapi-generator/milestones

**Comment by macjohnny** [comment]
You can use the current snapshot release if you want to use it now

**Comment by andrew-matteson** [comment]
@soxyl Would you need `"tsickle": "^0.40.0"` or `"typescript": "<4.4.0"`? I tried to match the versions to Angular's dependencies, but clearly screwed up on `tsickle`.

Could you also show me how you're invoking the generator? I'd like to have a clean reproduction before trying to dive into this.

**Comment by andrew-matteson** [comment]
@soxyl nevermind, I understand now. I was developing this against Angular 12.0.x which had the typescript constraint. I'll update to: `"typescript": "<4.4.0"`.

**Pull request merged**
