### PR TITLE
Refactoring: Use lombok for simple getters & setters

### PR DESCRIPTION
**Pull request by Philzen**
As Lombok is available throughout the project and also used in a couple of places, we can use it to remove several thousand lines of boilerplate code. This PR applies mostly `@Getter` and `@Setter` annotations wherever feasible, while not replacing any getter or setter methods that already have annotations (which could be facilitated via the [`onX` meta-annotation](https://projectlombok.org/features/experimental/onX), however for now refraining from using it as it is still experimental).

This makes the code base and – most importantly – the cognitive complexity to work through the repo considerably smaller. Also the declarative approach has the advantage that one can see immediately if a field is exposed in the public API by just looking at the declaration annotation.

This PR also contains some Javadoc and `@Override` annotation fixes and removes identical implementations in inherited classes.

---

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by Philzen** [comment]
@wing328 This was lying dormant for over two weeks as it appears the automatically assigned reviewer is unavailable. I've now rebased everything on main – would you be able to take over for a review here?

**Comment by wing328** [comment]
thanks for the PR. overall it looks good as it simplifies the code.

can you please resolve the merge conflicts when you've time? we can definitely give it a try.

**Comment by Philzen** [comment]
> can you please resolve the merge conflicts when you've time?

@wing328 Done!

**Comment by Philzen** [comment]
@wing328 

Just re-rebased this mother of all PRs… kindly merge at your earliest convenience :)

**Pull request merged**
