### PR TITLE
[R] feat(r) : Alternate PR for serialization fixes along with WithHttpInfo method enhancement

### PR DESCRIPTION
**Pull request by Ramanth**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
This is the alternative of this [PR](https://github.com/OpenAPITools/openapi-generator/pull/3082)
Along with the addition  WithHttpInfo method for the http operation methods.

@wing328  This PR has the changes as discussed.

### CODE REVIEW

**Comment by Ramanth** [comment]
@wing328 finished making the required changes, considering the backward compatibility as discussed. Please take a look and merge accordingly. Thanks

**Comment by wing328** [comment]
I got an error when testing with [NamSor R SDK (pr_3099 branch)](https://github.com/namsor/namsor-r-sdk2/tree/pr_3099):
```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  1: api.instance$GenderGeoBatch(batch.first.last.name.geo.in = var.batch.first.last.name.geo.in) at testthat/test_personal_api.R:177
  2: self$GenderGeoBatchWithHttpInfo(batch.first.last.name.geo.in = NULL, ...)
  
  ── 2. Error: OriginBatch (@test_personal_api.R#226)  ───────────────────────────
  attempt to apply non-function
  1: api.instance$GenderBatch(batch.first.last.name.in = var.batch.first.last.name.in) at testthat/test_personal_api.R:226
  2: self$GenderBatchWithHttpInfo(batch.first.last.name.in = NULL, ...)
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 26 SKIPPED: 397 WARNINGS: 0 FAILED: 2
  1. Error: GenderGeoBatch (@test_personal_api.R#177) 
  2. Error: OriginBatch (@test_personal_api.R#226) 
  
  Error: testthat unit tests failed
  Execution halted
* checking PDF version of manual ... OK
* DONE
```

Ref: https://travis-ci.org/namsor/namsor-r-sdk2/builds/547138705

**Comment by wing328** [comment]
Also for the following:
```
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
```

Shall we use `stop` instead as 4xx, 5xx imply errors/exceptions? (that's what we do in other API clients, which may even have an ApiException class)

**Comment by Ramanth** [comment]
@wing328  i have those changes implementing the ApiException ready to be raised in another PR.
just kept them hold as once this PR gets merged ill raise those changes as well.

**Comment by wing328** [comment]
Tested via NamSor R SDK and the result is good: https://travis-ci.org/namsor/namsor-r-sdk2/builds/548573316

**Pull request merged**
