### PR TITLE
[Enhancement] added support for custom type & format mapping

### PR DESCRIPTION
**Pull request by wing328**
Based on  #4931 (credits: @ShoeBoom) but use `+` as the separator

=========================

Makes it possible to map format.

For example these args can be used to properly map the following:
```
"foo": {
    "enum": [
        "0",
        "1",
        "2"
    ],
    "type": "integer",
    "format": "byte"
}
```

`generate -i openapi.json -o out -g kotlin --type-mappings integer_byte=kotlin.Byte`

By default it would map `foo` to `Int`

this is similar to #2730

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @OpenAPITools/generator-core-team

### CODE REVIEW

**Comment by marcelstoer** [comment]
> `generate -i openapi.json -o out -g kotlin --type-mappings integer_byte=kotlin.Byte`

Shouldn't it be `--type-mappings integer+byte`?
...................................................................^...........

**Comment by wing328** [comment]
@marcelstoer yes, just corrected it. thanks for pointing it out.

**Comment by svatwork** [comment]
I'm trying to wrap my head around this, hope anyone can help me. Thanks for all the work btw.

Does this imply that I can define my own type like: 

```yaml
url:
  type: string
  format: url
  pattern: $someURLPattern
```

... and then reference this type by using the type+format syntax? I would love a solution for our workaround with YAML anchors and/or $refs where we defined a custom type.

**Comment by marcelstoer** [comment]
This is how I use "custom types" but it's unrelated to formats.

**common-types.yaml**

```yaml
components:
  schemas:
    Uuid:
      type: string
      description: |
        Canonical textual representation of the 32 hexadecimal (base-16) UUID digits, displayed in five groups
        separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters
      minLength: 36
      maxLength: 36
      pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
```

**some API contract**
```yaml
...
    Branch:
      type: object
      required:
        - id
      properties:
        id:
          $ref: 'path-to/common-types.yaml#/components/schemas/Uuid'
...
```

**Pull request merged**
