### PR TITLE
fix export_generator shell script

### PR DESCRIPTION
**Pull request by fujigon**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

`./bin/utils/export_docs_generators.sh` (and its depending `./bin/utils/export_generators.sh`) has string pattern bug.

### CODE REVIEW

**Comment by fujigon** [comment]
re-run `./bin/utils/export_docs_generators.sh` and committed all `docs/generators/*.md`

**Comment by fujigon** [comment]
@wing328 @jimschubert @cbornet @jaz-ah @ackintosh @JFCote @jmini

**Comment by wing328** [comment]
@fujigon thanks for the PR. Reviewing...

**Comment by wing328** [comment]
@fujigon I tried to trigger a build failure via https://github.com/OpenAPITools/openapi-generator/commit/8d82fc6dbd2f7d560bd48b13795cb8ad5e283beb but the build still passed: https://circleci.com/gh/OpenAPITools/openapi-generator/2853. Still investigating why...

**Comment by wing328** [comment]
I've a fix and https://circleci.com/gh/OpenAPITools/openapi-generator/2870#tests/containers/2 reported failure, which is the expected behaviour.

**Comment by wing328** [comment]
@fujigon I've pushed the fix to your branch and the circle CI build is good (shippable failure is not related to this PR). Merging this into master. Thanks again for the fix.

cc @jmini

**Comment by jimschubert** [comment]
@wing328 @fujigon I was reviewing this, but I couldn't understand how the change in this PR had any difference in sh, since the markdown outputs resulted in the same generator name outputs (only difference was the added generator properties). I think the bash syntax could be cleaned up a little more, but I wanted to understand the error that was being solved. Was the problem perhaps a `sed` portability issue?

I was testing on the `sed` shipped with Mac 10.13.6.

**Comment by jimschubert** [comment]
Sorry, I missed the `on Linux` in the PR title.  I opened another PR to move the work being done in `sed` and output redirection into the `config-help` task itself.

**Comment by fujigon** [comment]
thanks for the review and merging!
I confirmed that `./bin/utils/ensure-up-to-date` has no git diff about docs on Linux with current master.

**Pull request merged**
