### PR TITLE
unhandledException not working in combination with skipDefaultInterfa…

### PR DESCRIPTION
**Pull request by ex0b1t**
Resolved issue where unhandledException is not rendered when jdk80default0interface is false

#4393 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by ex0b1t** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

Thanks for letting me know, I have updated my commit. It should be fine now.

**Comment by ex0b1t** [comment]
Hey @wing328 can you help me get this merged? I see there is one failing check but quite sure that is not related to my change.

**Comment by gavinheaden** [comment]
@ex0b1t  Do you know if this was ever resolved? Unless I am missing something, it looks like your commit was never merged and I am still seeing this issue persist in version 5.1.0

**Comment by ex0b1t** [comment]
> @ex0b1t  Do you know if this was ever resolved? Unless I am missing something, it looks like your commit was never merged and I am still seeing this issue persist in version 5.1.0

Yea, I closed the PR without merging, eventually I gave up trying to get my change approved.

**Comment by gavinheaden** [comment]
@ex0b1t Alright, thanks for the quick update. I will just generate with skipDefaultInterface false for the time. Appreciate the effort.

**Comment by ex0b1t** [comment]
You can also just replace the template with your own, the plugin allows you to specify your own template in the resources directory. Not ideal as you don't get upgrades but it works.

**Pull request closed without merging**
