### PR TITLE
[PHP] Replace File.seperator with slashes in PHP projects #2004

### PR DESCRIPTION
**Pull request by jfastnacht**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

#2004 

@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon

### CODE REVIEW

**Comment by ybelenko** [comment]
@jfastnacht 
Maybe we should also swap `File.separator` with `/` in `AbstractPhpCodegen`?
https://github.com/OpenAPITools/openapi-generator/blob/9fe3c7655d38a430c52a6b75265cad500dab3650/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java#L57

Should I change all `File.separarator` in `PhpSlimServerCodegen` too?

**Comment by jfastnacht** [comment]
> @jfastnacht
> Maybe we should also swap `File.separator` with `/` in `AbstractPhpCodegen`?
> [openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/9fe3c7655d38a430c52a6b75265cad500dab3650/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java#L57)
> 
> Line 57 in [9fe3c76](/OpenAPITools/openapi-generator/commit/9fe3c7655d38a430c52a6b75265cad500dab3650)
> 
>  protected String apiDocPath = docsBasePath + File.separator + apiDirName; 
> Should I change all `File.separarator` in `PhpSlimServerCodegen` too?

Probably, but we should be careful due to possible side effects. I can check on Sunday or Monday, unless you want to change it yourself.

**Comment by jfastnacht** [comment]
@ybelenko I couldn't find a problematic part in `PhpSlimServerCodegen`. If you don't see any other problem it's ready to merge from my perspective.

**Comment by ybelenko** [comment]
@jfastnacht I've checked your PR again, `PhpSlimServerCodegen` works correct.

Now I do understand why we can't change `File.separator` in `apiFileFolder()` and `modelFileFolder()` methods. These values are used by codegen itself and they needs to be responsive to user OS.
We can change only codegen properties within mustaches, php scripts and docs, where forward slash is completely safe.

But... why `DefaultCodegen` contains forward slash?
https://github.com/OpenAPITools/openapi-generator/blob/8a8a18447f25064a355cfe6ff17e13895bee91ee/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L632-L646

**Comment by jfastnacht** [comment]
> Now I do understand why we can't change `File.separator` in `apiFileFolder()` and `modelFileFolder()` methods. These values are used by codegen itself and they needs to be responsive to user OS.
> We can change only codegen properties within mustaches, php scripts and docs, where forward slash is completely safe.

Yeah, that's what I'm trying to seperate.

> But... why `DefaultCodegen` contains forward slash?

Other languages might be making it differently, so I can only talk for PHP right now.

**Comment by ybelenko** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/8a8a18447f25064a355cfe6ff17e13895bee91ee/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L632-L646

@wing328  Is this correct implemetation? Seems to me that `File.separator` is more safe for `DefaultCodegen`.

**Comment by jfastnacht** [comment]
@ybelenko Can you solve this in a seperate issue? I know that this is important, but it's leaving the scope of the issue #2004 this PR was originally opened for.

**Comment by ybelenko** [comment]
@jfastnacht Totally agree with you.

I won't merge this PR until @ackintosh approved it anyway. His opinion is more relevant because PHP Client codegen is used by larger community.

**Comment by wing328** [comment]
@jfastnacht thanks for the PR.

@ybelenko thanks for reviewing the change.

If no further feedback on this PR, I'll merge it tomorrow (Tue)

cc @ackintosh

**Comment by ackintosh** [comment]
Thanks for the great job! ✨

**Pull request merged**
