### PR TITLE
Makes the maven plugin to generate Model-tests and API-tests in generated-test-sources

### LINKED ISSUE #10917: [REQ] [JAVA] maven plugin generates test in generated-test-sources
### Is your feature request related to a problem? Please describe.

Maven uses two different folders generated-sources and generated-test-sources. Test related files supose to get into generated-test-source folder. In current implementation all generated files in a single forlder - ${project.build.directory}/generated-sources/openapi by default. 

there are problems with the approach: 
 - test files go to production artifact
 - production artifact becomes dependencies (it increses dangerous in the light of recent vulnerability in logging library - the more non essential libraries in prod the likely to catch new vulnerability)

I suspect that majority of java developers just disable generating the test files

I wonder if it it possible to make mvn plugin alligned with conventional folder-structure 

## Describe the solution you'd like

The solution is to introduce additional parameter testOutput which is ${project.build.directory}/generated-test-sources/openapi by default.

## Describe alternatives you've considered

there are several workarounds:
 - copy test files after generation with another maven plugin 
 - use org.codehouse.mojo:build-helper-maven-plugin to mark the folder with test files as mvn-test-source

both of these ways have different flaws

### PR DESCRIPTION
**Pull request by feech**
The change makes the maven plugin to generate Model-tests and API-tests in generated-test-sources without changes for other generator.

Default behaviour for java generator is changing for the case when 'output' is **not** set.

Before, all model, api classes and tests for them went to 'target/generated-sources'
Now, model and api classes go to the same folder - 'target/generated-sources', but tests for them go to 'generated-test-sources'.

There is a new additional option for java generator - 'testOutput'to set desired location for test-classes.

If `output` is set and `testOutput` is not - generator puts all files in `output` directory (this will keep backward compatibility)
If `testOutput` is set the value overrides default behaviour for test files

closes #10917

### PR checklist
 
- [+] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [+] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [+] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [+] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): (`master`) 5.3.0, `6.0.x`
- [+] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by feech** [comment]
Hello

@nmuesch @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)
@wing328 @Dever4eg @zhuangheihei @jimschubert

might I draw your attention to the PR.

This PR aims to solve the open issue - https://github.com/OpenAPITools/openapi-generator/issues/10917

**Comment by feech** [comment]
CI-builds broken after merge from master
I wonder if someone could guide me what are the issues

**Comment by wing328** [comment]
@feech when you've time, can you please resolve the merge conflicts? I'll to try to review and get it merged today. Thanks.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team as it impacts Default Generator class.

**Comment by wing328** [comment]
LGTM. Thanks for the PR.

**Pull request merged**
