### PR TITLE
[KOTLIN Client] Update to latest kotlin version

### PR DESCRIPTION
**Pull request by karismann**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@jimschubert (2017/09), @dr4ke616 (2018/08)

### Description of the PR

gradle - okhttp3 - kotlintest version update
add some test case in sample

### CODE REVIEW

**Comment by karismann** [comment]
@jimschubert   i tried to had some integration test on kotlin client sample but i have this CI error i can't reproduce locally :  

> A problem occurred evaluating root project 'kotlin-petstore-client'.
> org.gradle.api.artifacts.Configuration.defaultDependencies(Lorg/gradle/api/Action;)Lorg/gradle/api/artifacts/Configuration;

https://circleci.com/gh/OpenAPITools/openapi-generator/5405?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Do you have any idea about this problem ?

Thanks

**Comment by wing328** [comment]
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/kotlin/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'kotlin-petstore-client'.
> org.gradle.api.artifacts.Configuration.defaultDependencies(Lorg/gradle/api/Action;)Lorg/gradle/api/artifacts/Configuration;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

The error also mentions about line 20 in samples/client/petstore/kotlin/build.gradle.

**Comment by jimschubert** [comment]
Weird. I rebuilt the project locally, ran the sample script to ensure samples were updated, then ran `gradle check assemble` in the sample directory without issue.

Let me check again later today. Maybe I entered the wrong sample directory by mistake...

**Comment by wing328** [comment]
Tested locally but couldn't repeat the issue.

If the circle CI issue still occurs after merging into master, we'll move the tests to other CIs instead

**Comment by wing328** [comment]
Btw, I got the following warnings when testing locally:
```
> Task :compileKotlin
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt: (48, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt: (80, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt: (112, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt: (144, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt: (176, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt: (207, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt: (240, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/PetApi.kt: (274, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt: (47, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt: (78, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt: (110, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/StoreApi.kt: (142, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt: (47, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt: (78, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt: (109, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt: (140, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt: (172, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt: (205, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt: (235, 13): 'when' is exhaustive so 'else' is redundant here
w: /Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/src/main/kotlin/org/openapitools/client/apis/UserApi.kt: (267, 13): 'when' is exhaustive so 'else' is redundant here

```
Will create a task for tracking to see if anyone has time to fix these warnings.

**Comment by karismann** [comment]
@wing328  you're right, new warnings with the recent kotlin version even if i didn't change that part of the code associated with this PR. will try to fix thoses when i'll have time

**Comment by wing328** [comment]
@karismann thanks. I've created https://github.com/OpenAPITools/openapi-generator/issues/2462 for tracking.

**Pull request merged**
