### PR TITLE
Idiomatic Rust returns for Error conversions

### PR DESCRIPTION
**Pull request by medwards**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Will fill out the PR Checklist later. Feel free to copy/pasta if you're ready to go through the process (I was looking to just make a quick contribution and will have to come back to this when I have time)

### CODE REVIEW

**Comment by bjgill** [comment]
Thanks! I'll rebase and run trough the process.

**Comment by bjgill** [comment]
OK - after a few false starts, I've now got it rebased against master, with the samples regenerated. It looks as if the samples haven't been updated in a while, so some extraneous changes have got pulled in.

This is therefore ready for review. Thanks for the contribution!

**Comment by bjgill** [comment]
@frol @farcaller - this (small) PR is ready for review. Otherwise, I'll merge this on Wednesday

**Comment by wing328** [comment]
Thanks again for the PR, which has been included in the v4.0.2 release: https://twitter.com/oas_generator/status/1141610197766426626

**Pull request merged**
