### PR TITLE
[jaxrs-spec] add Eclipse MicroProfile file based approach

### PR DESCRIPTION
**Pull request by jmini**
When using [Eclipse-MicroProfile-OpenAPI](https://microprofile.io/project/eclipse/microprofile-open-api) framework, a small specification on top of JaxRS, you have two ways of enhancing your OpenAPI document.

1. with annotations (approach similar to [`swagger-jaxrs2`](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-jaxrs2))
2. with an OpenAPI document, placed at a predetermined location.

In order to use MicroProfile, you need to select the implementation you would like to use (similar to JavaEE/Jakarta EE, several vendors implement the same spec).

---

This PR is adding some support for the second variant (OpenAPI file based) approach.

The `library` flag is used to select the desired implementation:

* Helidon
* Open-Liberty
* Quarkus
* Thorntail

### CODE REVIEW

**Comment by wing328** [comment]
Reported by CircleCI:
```
--- a/docs/generators/jaxrs-spec.md
+++ b/docs/generators/jaxrs-spec.md
@@ -46,7 +46,7 @@ sidebar_label: jaxrs-spec
 |title|a title describing the application| |OpenAPI Server|
 |useBeanValidation|Use BeanValidation API annotations| |true|
 |serverPort|The port on which the server should be started| |8080|
-|library|library template (sub-template)|<dl><dt>**&lt;default&gt;**</dt><dd>JAXRS</dd><dl>|&lt;default&gt;|
+|library|library template (sub-template)|<dl><dt>**&lt;default&gt;**</dt><dd>JAXRS spec only, to be deployed in an app server (TomEE, JBoss, WLS, ...)</dd><dt>**quarkus**</dt><dd>Server using Quarkus</dd><dt>**thorntail**</dt><dd>Server using Thorntail</dd><dt>**openliberty**</dt><dd>Server using Open Liberty</dd><dt>**helidon**</dt><dd>Server using Helidon</dd><dl>|&lt;default&gt;|
 |generatePom|Whether to generate pom.xml if the file does not already exist.| |true|
 |interfaceOnly|Whether to generate only API interface stubs without the server files.| |false|
 |returnResponse|Whether generate API interface should return javax.ws.rs.core.Response instead of a deserialized entity. Only useful if interfaceOnly is true.| |false|
Perform git status
On branch pull/3901
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   docs/generators/jaxrs-cxf-cdi.md
	modified:   docs/generators/jaxrs-spec.md

no changes added to commit (use "git add" and/or "git commit -a")
Please run 'bin/utils/ensure-up-to-date' locally and commit changes (UNCOMMITTED CHANGES ERROR)
```

Please run the following to update the doc as well

```
"./bin/utils/export_docs_generators.sh"
"./bin/utils/copy-to-website.sh"
"./bin/utils/export_generators_readme.sh"
```

**Comment by wing328** [comment]
Tested with `--library openliberty` and got the following errors:
```
[ERROR]   symbol:   class ApiParam
[ERROR]   location: class org.openapitools.api.PetApi
[ERROR] /private/tmp/jaxrs-spec4/src/gen/java/org/openapitools/api/PetApi.java:[72,6] cannot find symbol
[ERROR]   symbol:   class ApiOperation
[ERROR]   location: class org.openapitools.api.PetApi
[ERROR] /private/tmp/jaxrs-spec4/src/gen/java/org/openapitools/api/PetApi.java:[77,6] cannot find symbol
[ERROR]   symbol:   class ApiResponses
[ERROR]   location: class org.openapitools.api.PetApi
[ERROR] /private/tmp/jaxrs-spec4/src/gen/java/org/openapitools/api/PetApi.java:[96,53] cannot find symbol
[ERROR]   symbol:   class ApiParam
[ERROR]   location: class org.openapitools.api.PetApi
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jmini** [comment]
Thank you for having tried this. I could reproduce the issue.

---

During my tests, I was always testing with `useSwaggerAnnotations = false` (see https://github.com/OpenAPITools/openapi-generator/pull/813 and the discussion around this).

The Eclipse-MicroProfile-OpenAPI implementation will never support swagger-annotations, so I added a comment to enforce that useSwaggerAnnotations is set to false if one of those app server is used.

**Comment by wing328** [comment]
Looks good now :+1:

**Pull request merged**
