### PR TITLE
Move mustache template to new subfolder

### LINKED ISSUE #5541: [REQ][Handlebars] Move all mustache templates in resource folder to new mustache subfolder to better support multiple template Engines
### Is your feature request related to a problem? Please describe.

Currently all templates are located in resources folder and all languages point to them there
If choosing to run different templating engine and provide those templates would today have to live in same folder as current mustache template.
This solution would make a clutter of files for every language that has supports multiple templating engines.

## Describe the solution you'd like

make a new substructure in resources folder for mustache templates matching identifier of the templating engine
Then new templates for other templating engines can be places in parallel folder structure related to their identifier (i.e. new folder for handlebars templates)

## Describe alternatives you've considered

Add new info to Templating engine related to "folder offset" to find templates for that particular templating engine

### PR DESCRIPTION
**Pull request by lindgrenfredrik**
Move all mustache templates into subfolder called mustache (same as templateEngine identifier)
Updated so that all references to templates to point into new subfolder

fix #5541

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [NA] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).

bin/run-all-petstore reports [SUCCESS] 268 generators finished.

- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [NA] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by lindgrenfredrik** [comment]
@wing328 seems there was some timeout in ci/bitrise test job (which is linked below your user id), something I need to do to retrigger it?

**Comment by jimschubert** [comment]
I don't follow why this has been done? We don't intend to support multiple template files for built-in templates, only Mustache. The structure of the templates under the resources directory has nothing to do with the support of other engines for custom templates.

**Comment by lindgrenfredrik** [comment]
If you don't intend to support multiple template types for the same language being delivered as part of the openapi jar then this isn't needed.

My concern is related to if some language would like to setup support for both Mustache and Handlebars templates from inside the openapi jar and use the existing name conversion then templates ending with .mustache and .handlebars would have to be stored in the same folder structure.
This seemed messy and as such I saw that if the template engine name was part of the folder structure path then there would be a separation of where the different templates would be placed related to which template engine was chosen to executed

**Comment by wing328** [comment]
@lindgrenfredrik first of all, thanks for the PR. I agreed with @jimschubert that it's unlikely we will support both mustache and handlebar. We may (tentatively) target cutting over to Handlebar in 6.0 release scheduled next year as the demand for handlebar isn't huge

**Comment by lindgrenfredrik** [comment]
@wing328 thanks for feedback.
As mentioned in previous post I wasn't aware that the intention wasn't to support both template styles from inside the openapi jars, but rather only with external templates.

I'm working on a company internal project where we have already moved to handlebar templates with swagger, but we ran into other issues with their codegen not behaving correctly and those issues are not present with OpenApi codegen.

Since I saw that Handlebars was in Beta for OpenApi and got help with fix for #5320 I just assumed plan was to support both template engines in the future (from within the openapi jar) and that the separation of templates just hadn't occurred to anyone yet do to low usage of handlebars

Hence why I made this proposal.
But I'm fine with dropping it if that is not in the plan to handle this type of setup from within the openapi jars (will regardless have internal templates for the company project)

**Pull request closed without merging**
