### PR TITLE
Add map property in url params

### PR DESCRIPTION
**Pull request by agilob**
Adding map property in url params to test generation of this specific case in generators as requested in https://github.com/OpenAPITools/openapi-generator/pull/10116#issuecomment-898190912

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@wing328

### CODE REVIEW

**Comment by kuhnroyal** [comment]
Damn, I did this yesterday but didn't open a PR cause of the 5.2.1 release :)

**Comment by kuhnroyal** [comment]
Can you copy the tests from https://github.com/kuhnroyal/openapi-generator/tree/dart-dio/query-maps

**Comment by agilob** [comment]
It's hard to distil your change and find what's dart-test change you want added and what is generated, but I think I found what was missing

**Comment by kuhnroyal** [comment]
Looks about right, just needs some formatting.

**Comment by agilob** [comment]
Is that test supposed to be failing?

**Comment by kuhnroyal** [comment]
> Is that test supposed to be failing?

I think this is just a formatting failure. Can you run `dart format .` in the test project?

**Comment by agilob** [comment]
I removed the commits adding the dart tests. They are failing locally and I feel they are out of scope for this PR, as I only wanted to add spec changes without anything language specific. I'll let you add the tests as you want, I think I missed some changes from your PR...

**Review by kuhnroyal — APPROVED** [review]

**Pull request merged**
