### PR TITLE
python: remove non-async code path from the aiohttp generator

### PR DESCRIPTION
**Pull request by multani**
This removes all the non-async code from the aiohttp generator:

* all the methods that should be asynchronous are marked as `async`
* the `async_req` parameter is gone; calls are directly awaitables now
* the async calls into a thread pool are gone and the thread pool is gone too (now useless)

Closes: #15824
Closes: #5539
Related: #763
Related: #3696

The code is extracted from https://github.com/OpenAPITools/openapi-generator/pull/15878, readjusted to remove the typing changes and fixed for the aiohttp client tests to pass.

@krjakbrjak @wing328 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (7.0.1 - patch release), `7.1.x` (minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by multani** [comment]
I noticed GitHub Actions doesn't run tests for the client in https://github.com/OpenAPITools/openapi-generator/tree/master/samples/openapi3/client/petstore/python-aiohttp: I can also take a look to add a new workflow to test this specific client, just let me know.

**Comment by multani** [comment]
> I noticed GitHub Actions doesn't run tests for the client in [`master`/samples/openapi3/client/petstore/python-aiohttp](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/openapi3/client/petstore/python-aiohttp?rgh-link-date=2023-09-16T14%3A53%3A20Z): I can also take a look to add a new workflow to test this specific client, just let me know.

Or another sample client (like an aiohttp-based echo API client for instance)

**Comment by wing328** [comment]
FYI @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @arun-nalla (2019/11) @krjakbrjak (2023/02)

**Comment by wing328** [comment]
looks good to me. 

the change seems to be transparent to end uesrs consuming the python sdk as all tests still pass without any need to update the test.

**Pull request merged**
