### PR TITLE
[cpp-qt-client] Qt progress info

### PR DESCRIPTION
**Pull request by Jazzco**
When downloading larger files via the generated API I miss a possibility to get the download progress. This could be achieved by connecting to the signal QNetworkReply::downloadProgress. This is solution 1 of the request: https://github.com/OpenAPITools/openapi-generator/issues/18926

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by Jazzco** [comment]
Remark for step 3: I work on Windows where all touched files get the CR/LF which results in too many changed files. So please take over the changes.

FYI: @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

**Comment by wing328** [comment]
thanks for the PR. I've filed https://github.com/OpenAPITools/openapi-generator/pull/18956 with updated samples (some tabs are replaced with 4-space)


but some CI tests failed: https://github.com/OpenAPITools/openapi-generator/actions/runs/9558830005/job/26348400169?pr=18956

Does this change work with Qt 5.x?

**Comment by Jazzco** [comment]
> Does this change work with Qt 5.x?

Would be mystic if not. You already have similar code in [api-body:677](https://github.com/Jazzco/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/cpp-qt-client/api-body.mustache#L677)

**Comment by Jazzco** [comment]
I ran step 3 from a linux vm to complete this.

**Comment by Jazzco** [comment]
I tested the changes in a local old build of our source. It builds without errors using these changes under Qt 5.15.2 on Windows platform.

**Comment by Jazzco** [comment]
I'm not quite sure this works correctly:
- It might be necessary to create the downloadProgress for each nickname. 
- It might also be necessary to add additional connects to the other parts where `HttpRequestWorker::on_execution_finished` is connected

As I'm not the mustache specialist what do you think?   
@ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @MartinDelille (2018/03) @muttleyxd (2019/08)

**Review by MartinDelille — APPROVED** [review]
I didn't test it but it makes sense!

**Comment by Jazzco** [comment]
I changed this Pr to draft until this is discussed.

**Comment by wing328** [comment]
> Is there a possibility to add a function only when a specific flag is set, so the user can decide in the interface if the progress should be available?


yes, you can add an option to do so. https://github.com/OpenAPITools/openapi-generator/pull/18072 (for C client) is a good reference PR as a starting point.

**Comment by Jazzco** [comment]
> 
> yes, you can add an option to do so. #18072 (for C client) is a good reference PR as a starting point.

That's a huge change, can you please point me to that option? What's its name?

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/18072/files#diff-650ea35dcd5ff1dee971a524e6c1e7f1d538319357fa079c54e0a9b949fbdb92R313 to add an cli option

https://github.com/OpenAPITools/openapi-generator/pull/18072/files#diff-650ea35dcd5ff1dee971a524e6c1e7f1d538319357fa079c54e0a9b949fbdb92R325 to process it in additional properties

https://github.com/OpenAPITools/openapi-generator/pull/18072/files#diff-e5916826f6d19371fe33e8a59d2bf7a825844bc77253255ddbe69ae8c56d5cedR323 to use it in the template

to make your life easier, can you please wrap the new code block for Qt progress info in the template with `{{#addDownloadProgress}} ... {{/addDownloadProgress}}` ?

i'll then take care of the rest

**Comment by Jazzco** [comment]
This should be right now: 
- in the HttpRequest the signal and connection are permanent
- in the api head and body it's bound to the addDownloadProgress tag
- the signal in the api is just called "Progress" to fit well to many names for "nickname"

**Review by MartinDelille — APPROVED** [review]

**Comment by wing328** [comment]
> Samples cpp qt client / Build cpp qt client (5.15.2, macOS-latest) (pull_request) Fai

that test has been removed from master

can you please pull the latest master into your branch when you've time?

**Comment by MartinDelille** [comment]
@wing328 same here: could you restart the ci by hand ?

**Comment by wing328** [comment]
cpp qt tests with the download progress option enabled passed via https://github.com/OpenAPITools/openapi-generator/pull/19292

**Comment by wing328** [comment]
thanks for the PR. will add an option with a separate PR later.

**Comment by wing328** [comment]
update: option added via https://github.com/OpenAPITools/openapi-generator/pull/19297

@Jazzco thanks again for the PR

**Comment by Jazzco** [comment]
You're welcome :-)

**Pull request merged**
