### PR TITLE
Use RestOperations interface in RestTemplate Java library

### PR DESCRIPTION
**Pull request by chrylis**
Spring provides the `RestOperations` interface as the base API for the
`RestTemplate` model, and the interface should be used whenever
practical. Switching to the interface instead of the implementing class
particularly makes test integrations easier both for code consuming
the `ApiClient` and for testing server implementations through it with
MockMvc.

This improvement should apply cleanly against 3.4 and 4.0-SNAPSHOT.

The petstore generator completed successfully for `resttemplate-withxml`, but plain `resttemplate` complains about existing directories with `mkdir`; I can include all those files as well if needed but didn't want to contribute a partial set.

### CODE REVIEW

**Comment by chrylis** [comment]
The PR template requests "copying the technical committee" without explaining what that means. I'm going to guess that it's requesting a mention for each of the language members.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog

**Comment by karismann** [comment]
may i ask you to also commit updated samples, i.e. files modified when you execute ` ./bin/java-petstore-resttemplate.sh` and `./bin/java-petstore-resttemplate-withxml.sh`  ?
`samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java`
and `samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java`

**Comment by chrylis** [comment]
@karismann As mentioned, I got errors on the terminal (mkdir saying directory exists) that _might_ have been benign but I couldn't tell. Additionally, there appear to have been a couple other stray items that were a result of these samples' not having been updated after some updates to the sample schema, and the `VERSION` not getting registered appropriately. I've checked in what I think are the relevant files and rebased against current master (374427).

**Comment by chrylis** [comment]
After including those changes and digging into the CircleCI report, it looks like the generated code is also configuring some of the `InterceptingHttpAccessor` pieces; I'll take a closer look to try to separate the concerns if practical.

**Comment by wing328** [comment]
@chrylis right, we need to address these build failures before we can accept your PR:
```
[ERROR] COMPILATION ERROR : 
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java:[288,83] cannot find symbol
  symbol:   method getInterceptors()
  location: variable restTemplate of type org.springframework.web.client.RestOperations
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java:[295,30] cannot find symbol
  symbol:   method setInterceptors(java.util.List<org.springframework.http.client.ClientHttpRequestInterceptor>)
  location: variable restTemplate of type org.springframework.web.client.RestOperations
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java:[305,34] cannot find symbol
  symbol:   method setInterceptors(java.util.List<org.springframework.http.client.ClientHttpRequestInterceptor>)
  location: variable restTemplate of type org.springframework.web.client.RestOperations
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java:[334,56] cannot find symbol
  symbol:   method getMessageConverters()
  location: variable restTemplate of type org.springframework.web.client.RestOperations
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project petstore-resttemplate: Compilation failure: Compilation failure:
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java:[288,83] cannot find symbol
[ERROR] symbol:   method getInterceptors()
[ERROR] location: variable restTemplate of type org.springframework.web.client.RestOperations
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java:[295,30] cannot find symbol
[ERROR] symbol:   method setInterceptors(java.util.List<org.springframework.http.client.ClientHttpRequestInterceptor>)
[ERROR] location: variable restTemplate of type org.springframework.web.client.RestOperations
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java:[305,34] cannot find symbol
[ERROR] symbol:   method setInterceptors(java.util.List<org.springframework.http.client.ClientHttpRequestInterceptor>)
[ERROR] location: variable restTemplate of type org.springframework.web.client.RestOperations
[ERROR] /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java:[334,56] cannot find symbol
[ERROR] symbol:   method getMessageConverters()
[ERROR] location: variable restTemplate of type org.springframework.web.client.RestOperations
```

**Comment by wing328** [comment]
@chrylis let us know when it's ready for another review and we'll remove the WIP label

**Comment by wing328** [comment]
Closing this for the time being as there's no update. Please feel free to reopen or submit a new PR when it's ready.

**Pull request closed without merging**
