### PR TITLE
[typescript-fetch] Fix config getter type issue

### PR DESCRIPTION
**Pull request by badsyntax**
This change fixes a bug introduced in https://github.com/OpenAPITools/openapi-generator/pull/10072

Here's the type error:

Screenshot 2021-08-21 at 06 40 17

With this change the return type now matches the config fetchApi type. 

It would be great to get this bugfix released asap.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by badsyntax** [comment]
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

**Comment by badsyntax** [comment]
Duplicate of https://github.com/OpenAPITools/openapi-generator/pull/10200, feel free to close.

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by jakub-astrahit** [comment]
When I use @openapitools/openapi-generator-cli version 2.3.10 I can still reproduce the original issue. Am I using the correct version?

**Comment by badsyntax** [comment]
@jakub-astrahit The fix is not released yet. 

@wing328 do we have an ETA for next patch/minor release?

**Comment by macjohnny** [comment]
https://github.com/OpenAPITools/openapi-generator/milestones

**Comment by badsyntax** [comment]
Thanks @macjohnny! Pity it's still a way to go till next release.

@jakub-astrahit you're going to have to use a custom template to fix this error in the meantime.

**Comment by jakub-astrahit** [comment]
@badsyntax @macjohnny Thanks guys for your quick replies. What do you mean by a custom template? Is the ETA for the next release days, weeks or months away?

**Comment by badsyntax** [comment]
@jakub-astrahit you can provide a custom template when generating the client. the template is a directory that contains the mustache files. here's the source template: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/typescript-fetch


So I simply provide the `rutime.mustache` file as part of my template: https://github.com/badsyntax/richardwillis.info/tree/a1628f37d6f7ec566c60eaa373a7814ea926544e/src/features/api/typescript-fetch

And here's how I generate the client using my custom template:

```console
openapi-generator-cli generate -i http://localhost:1337/openapi.json -g typescript-fetch -t ./src/features/api/typescript-fetch -o ./src/features/api/strapi --additional-properties=typescriptThreePlus=true
```

**Pull request merged**
