### PR TITLE
Bump Jackson to latest v2.17.1 and sync in templates

### PR DESCRIPTION
**Pull request by Philzen**
As the title says. :top:

Also, by [adjusting the Spring Boot Jackson version import](https://github.com/OpenAPITools/openapi-generator/pull/18799/commits/e4f44f8cd718c8124ebbb49fded4cee928582991), the total number of dependencies drops by 6 (to 269 for the whole project).

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
please resolve the merge conflicts when you've time. thank you

**Comment by Philzen** [comment]
> please resolve the merge conflicts when you've time. thank you

Ready :)

**Comment by Philzen** [comment]
@wing328

Now also updated the library descriptions with version numbers (all of them) as some were completely off:

https://github.com/OpenAPITools/openapi-generator/blob/d2c068cd656fe9d77c434925cb0bbde0ea886a37/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java#L238-L252

Wonder how we could ensure this doesn't get out-of-sync the next time some dependency get's updated. Probably managing all of it in a constant, such as `JavaClientCodegen.MICROPROFILE_REST_CLIENT_DEFAULT_VERSION` already does (it is applied in the template directly).

Branch is rebased now but CI will keep failing before being rebased on #18826

**Comment by wing328** [comment]
> Wonder how we could ensure this doesn't get out-of-sync the next time some dependency get's updated

my take is to simply omit the version number or just use 5.x instead of something of 5.1.8 as we generally don't document the library version in the description in other generators (e.g. PHP, Python, etc)

**Comment by alavers** [comment]
@Philzen I noticed that with this change the `threetenbp_version` (`2.15.2`) no longer matches the `jackson_version` (`2.17.1`). Should they be kept in sync?

threetenbp is looking for jackson-core `2.15.2` anyway:

```
./gradlew dependencyInsight --dependency jackson-core
```

```
com.fasterxml.jackson.core:jackson-core:2.15.2 -> 2.17.1
\--- com.github.joschi.jackson:jackson-datatype-threetenbp:2.15.2
     \--- compileClasspath
```

I noticed this because a java project using a generated wrapper was producing compiler warnings:

```
BUILD SUCCESSFUL in 111ms
2 actionable tasks: 1 executed, 1 up-to-date
warning: unknown enum constant Include.ALWAYS
  reason: class file for com.fasterxml.jackson.annotation.JsonInclude$Include not found
warning: unknown enum constant Include.ALWAYS
... many lines like this
41 warnings
```

Those warnings disappeared when I downgraded `jackson_version` to `2.15.2` and regenerated the lib.

**Pull request merged**
