### PR TITLE
[C][Client] Convert integer/boolean to string for query parameter in request url

### PR DESCRIPTION
**Pull request by ityuhui**
If the data type of query parameter is "int" or "bool" in OpenAPI Spec, the request url will not be right generated by c-libcurl.

For example,  in the function 
```c
CoreV1API_listNamespacedPod(..., int limit ,... )
{
...
    // query parameters
    char *keyQuery_limit = NULL;
    int valueQuery_limit ;
    keyValuePair_t *keyPairQuery_limit = 0;
    if (limit)
    {
        keyQuery_limit = strdup("limit");
        valueQuery_limit = (limit);
        keyPairQuery_limit = keyValuePair_create(keyQuery_limit, &valueQuery_limit);  <-- limit is only be referred as int *
        list_addElement(localVarQueryParameters,keyPairQuery_limit);
    }

```
but in the function 
```c
char *assembleTargetUrl(char    *basePath,
                        char    *operationParameter,
                        list_t    *queryParameters) {
    if(queryParameters != NULL) {
        strcat(targetUrl, "?");
        list_ForEach(listEntry, queryParameters) {
            keyValuePair_t *pair = listEntry->data;
            replaceSpaceWithPlus(pair->key);
            strcat(targetUrl, pair->key);
            strcat(targetUrl, "=");
            replaceSpaceWithPlus(pair->value);
            strcat(targetUrl, pair->value);    <=== valueQuery_limit is not a char *, so this is wrong.
            if(listEntry->nextListEntry != NULL) {
                strcat(targetUrl, "&");
            }
        }
    }
```

If we call 

```c
CoreV1API_listNamespacedPod(...
                                           10,   /* limit */
...);

```

the targetUrl becomes:
```
"https://ip:6443/api/v1/namespaces/default/pods?limit=P.xUUU"
```

My fix is converting the parameter to string
```c
    // query parameters
    char *keyQuery_limit = NULL;
    char * valueQuery_limit = NULL;
    keyValuePair_t *keyPairQuery_limit = 0;
    if (limit)
    {
        keyQuery_limit = strdup("limit");
        valueQuery_limit = calloc(1,MAX_NUMBER_LENGTH);
        snprintf(valueQuery_limit, MAX_NUMBER_LENGTH, "%d", limit);
        keyPairQuery_limit = keyValuePair_create(keyQuery_limit, valueQuery_limit);
        list_addElement(localVarQueryParameters,keyPairQuery_limit);
    }
```

the targetUrl now is right:
```
"https://ip:6443/api/v1/namespaces/default/pods?list=10"
```

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@zhemant @michelealbano

### CODE REVIEW

**Comment by wing328** [comment]
When you've time, please merge the latest master into this branch to address the Drone.io CI failrue.

**Comment by ityuhui** [comment]
> When you've time, please merge the latest master into this branch to address the Drone.io CI failrue.

Done.

**Comment by ityuhui** [comment]
Hi @zhemant @michelealbano @wing328 

Could you please review this code change if you have time ?

Thanks

**Comment by ityuhui** [comment]
Thank you @wing328

**Pull request merged**
