### PR TITLE
[dart] Remove old dio generator (to be replaced with dart-dio-next)

### PR DESCRIPTION
**Pull request by kuhnroyal**
* remove old `dart-dio` generator which will be replaced by `dart-dio-next` in a separate PR
* remove left-over `DartJaguarClinetCodegen` class which was sunset a while ago and is unused

I will create another PR renaming `dart-dio-next` in a couple days. Just want to see a couple more open PRs merge before that.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

CC @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

### CODE REVIEW

**Comment by ahmednfwela** [comment]
do we need to provide a migration guide from old `dart-dio` to new `dart-dio` ?

**Review by agilob — APPROVED** [review]
:clap:

**Comment by kuhnroyal** [comment]
The error is from a typescript sample which was not touched here.

**Review by agilob — APPROVED** [review]

**Comment by wing328** [comment]
Samples updated via e58646a6294 in the master.

**Pull request merged**
