### PR TITLE
Remove JDK7 support from Java Spring generators

### PR DESCRIPTION
**Pull request by wing328**
Remove JDK7 support from Java Spring generators (default to JDK8+ starting in v6.0.0)

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### CODE REVIEW

**Comment by cachescrubber** [comment]
Some unit tests have to be adjusted.

**Comment by wing328** [comment]
Yup, will fix those after merging your (and other) spring-related PRs.

**Comment by cachescrubber** [comment]
@wing328 Nor sure wether we should remove the implementation in apiController.mustache. Could make migration for  spring-mvc users more straight forward - and could be a value for itself. WDYT?

**Comment by wing328** [comment]
Added back via 63a469f146c

Agreed with the direction to make the migration easier for `spring-mvc` users.

**Comment by cachescrubber** [comment]
Thx. I'll give more feedback and review throughout the day.

**Comment by wing328** [comment]
The code won't compile as it's missing those JDK7 import. Shall we add those `import` back to the controller?


```
Error:    symbol:   class User
Error:    location: class org.openapitools.api.UserApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/UserApiController.java:[156,12] cannot find symbol
Error:    symbol:   class ResponseEntity
Error:    location: class org.openapitools.api.UserApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[36,80] cannot find symbol
Error:    symbol:   class XmlItem
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[35,12] cannot find symbol
Error:    symbol:   class ResponseEntity
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[50,12] cannot find symbol
Error:    symbol:   class ResponseEntity
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[66,97] cannot find symbol
Error:    symbol:   class OuterComposite
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[65,12] cannot find symbol
Error:    symbol:   class ResponseEntity
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[65,27] cannot find symbol
Error:    symbol:   class OuterComposite
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[90,94] cannot find symbol
Error:    symbol:   class BigDecimal
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[89,12] cannot find symbol
Error:    symbol:   class ResponseEntity
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[89,27] cannot find symbol
Error:    symbol:   class BigDecimal
Error:    location: class org.openapitools.api.FakeApiController
Error:  /home/runner/work/openapi-generator/openapi-generator/samples/server/petstore/springboot/src/main/java/org/openapitools/api/FakeApiController.java:[104,12] cannot find symbol
```

Ref: https://github.com/OpenAPITools/openapi-generator/runs/5179391345?check_suite_focus=true

**Comment by cachescrubber** [comment]
Hmm, the missing imports are not jdk8 related IMO. The miss swagger.v3 and spring-web imports.

We 'll  need a flag to enable usage of the  "impl-in-controller" pattern?  Probably the switch has been implicity via the java8 toggle.

**Comment by wing328** [comment]
> Hmm, the missing imports are not jdk8 related IMO. They miss swagger.v3 and spring-web imports.

I'll try to add those import

> We 'll need a flag to enable usage of the "impl-in-controller" pattern?

I suggest we go without the flag to start with. If later that's a demand for it, we can always add one.

**Comment by wing328** [comment]
Done. CircleCI failure not related to this change.

**Comment by cachescrubber** [comment]
> I suggest we go without the flag to start with. If later there's a demand for it, we can always add one.

I think we still need to hide the code behind a flag. We should just not expose it via cli to make no commitment. As it is right now there is a code duplication between Api and Controller. Thanks for your patience anyway. Otherwise the PR looks good.

**Comment by wing328** [comment]
OK. Let's go with what we've for now as I don't want to include too many changes in this PR. We can always add the option later.

**Pull request merged**
