### PR TITLE
[Java][RestTemplate] Fix query parameter URL encoding

### PR DESCRIPTION
**Pull request by simingweng**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fix for #249.

add URL encoding to every query parameter string in case it has unsafe character before building it into the request entity.

CI test on my branch has passed.

### CODE REVIEW

**Comment by wing328** [comment]
@simingweng Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by jmini** [comment]
cc java technical committee:
@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas  (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09)  @jeff9finger (2018/01)

**Comment by jmini** [comment]
@simingweng : Thank you a lot for this contribution.

The Shippable CI job indicates that the generated samples we use as reference (under `samples/` in this repository were not updated.

On your branch, can you please run:
* `mvn verify`
* `bin/java-petstore-resttemplate.sh`
* `bin/java-petstore-resttemplate-withxml.sh`

And commit the changed files:

```
samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java
```

Please let me know if you need help.

**Comment by wing328** [comment]
@simingweng I don't think it's related to your change. I've restarted the job. Let's see how it goes.

**Comment by jmini** [comment]
**Job 545:**
> ci/circleci — Your tests failed on CircleCI

This job is unrelated:
```
sbt.ResolveException: download failed: joda-time#joda-time;2.2!joda-time.jar
```

**Job 541:**
> ci/circleci — Your tests failed on CircleCI

This job is unrelated:
```
2018-06-09 14:06:49.706:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.m.p.JettyWebAppContext@21a2bad0{/,file:/home/ubuntu/openapi-generator/samples/server/petstore/jaxrs-datelib-j8/src/main/webapp/,STARTING}{file:/home/ubuntu/openapi-generator/samples/server/petstore/jaxrs-datelib-j8/src/main/webapp/}
javax.servlet.ServletException:
Caused by: 
org.glassfish.jersey.internal.inject.ExtractorException: org.glassfish.jersey.internal.inject.ExtractorException: java.lang.NumberFormatException
Caused by: 
org.glassfish.jersey.internal.inject.ExtractorException: java.lang.NumberFormatException
Caused by: 
java.lang.NumberFormatException
```

**Comment by wing328** [comment]
https://circleci.com/gh/OpenAPITools/openapi-generator/545?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link only failed with JDK8 but not JDK7 due to failure unrelated to this change so I'll merge it into master.

**Pull request merged**
