### PR TITLE
[Spring] Support disabling ApiIgnore & Pageable imports

### PR DESCRIPTION
**Pull request by morphlne**
### Issues
To fix https://github.com/OpenAPITools/openapi-generator/issues/8360, https://github.com/OpenAPITools/openapi-generator/issues/8192, https://github.com/OpenAPITools/openapi-generator/issues/8916, https://github.com/OpenAPITools/openapi-generator/issues/8776

### Description
Support for vendor extension `x-spring-paginated` added in https://github.com/OpenAPITools/openapi-generator/pull/5022 provides non-configurable imports:

```java
import org.springframework.data.domain.Pageable;
import springfox.documentation.annotations.ApiIgnore; 
```

Both imports appears even if `x-spring-paginated` is not specified. Those imports are undesirable cause they demand additional dependencies, otherwise compilation fails.

### Suggested fix
The PR adds config option for separately disabling imports `usePageable`, `useApiIgnore`. Both options are `true` by default for backward compatibility.

### Alternative approach
On other hand, imports can be simple disabled using `{{vendorExtension.x-spring-paginated}}` without new configs, but i believe, that generator behavior should depends on generator config, not on API description.

### Tests
Added generated samples with new config options

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run 
  ```
  mvn clean package
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  to update all Petstore samples related to your fix. 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by morphlne** [comment]
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

**Comment by borsch** [comment]
make sense to add new modules to root pom like here https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L1184 (not sure which profile. maybe to all) to be sure that these new samples pass compilation

**Comment by cbornet** [comment]
We shouldn't add 2 more options just to remove imports. I'd rather have only one option to completely add/remove the support for x-spring-paginated

**Comment by morphlne** [comment]
If it's considered to have only one option for config, may be better not use options at all and apply vendor extension...
But this solution can break backward compatibility if someone use pageable & apiignore imports without x-spring-paginated. It will affect a small amount of users cause this case is very specific and relevant only to 5.0.0 & 5.0.0-beta3 versions
@cbornet what do you think about it?

@borsch agree with you, it makes sense, will add new samples as modules

**Comment by MatCyg** [comment]
Is there any workaround available already? (beside adding unnecessary imports to you project)

**Comment by morphlne** [comment]
CircleCI build blocked by https://github.com/OpenAPITools/openapi-generator/issues/8922

**Comment by morphlne** [comment]
Rebase on resolved blocker

**Comment by morphlne** [comment]
Reworked - now one property `usePagination` enable/disable both imports

Please review
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01) @wing328

**Comment by jenswet-el** [comment]
It would be great if this would be part of the 5.1 release.

**Comment by rfelgent** [comment]
> 
> 
> It would be great if this would be part of the 5.1 release.

Unfortunatley, this fix is not part of 5.1.0 :-(

**Comment by Blubb324** [comment]
This topic is still relevant and occurs in current version: openapi-generator-maven-plugin: 5.2.1

The class `import springfox.documentation.annotations.ApiIgnore;` is still generated and unused within API and should be removed - also because of dependency to springfox.

**Comment by wangq8** [comment]
This PR is not merged.
How can I get rid of this ApiIgnore manually, I don't want this annotation.

**Comment by rfelgent** [comment]
Hi @wangq8 ,

as I am not so familiar with the customization possibilities provided by openapi tool, I manipulate the source files right after its creation:

```
<plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <!-- remove this execution as soon as 
   -  https://github.com/OpenAPITools/openapi-generator/issues/8192 
   - https://github.com/OpenAPITools/openapi-generator/pull/8421 
   is resolved 
-->
          <execution>
            <id>remove-springfox-classes</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <replace dir="${project.build.directory}/generated-sources" token="import springfox.documentation.annotations.ApiIgnore;" failOnNoReplacements="true">
                  <include name="**/*.java"/>
                  <replacevalue/>
                </replace>
                <replace dir="${project.build.directory}/generated-sources" token="@ApiIgnore final" failOnNoReplacements="true">
                  <include name="**/*.java"/>
                  <replacevalue/>
                </replace>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

Maybe this helps you, too

**Comment by morphlne** [comment]
Fixed in 5.3.0, [working](https://github.com/morphlne/openapi-generator-demo) sample

**Pull request closed without merging**
