### PR TITLE
Fix: in typescript fixes additionalProperties handling when extending models

### PR DESCRIPTION
**Pull request by mvarchdev**
Previously the extending of models when instantionTypte('map') was not set for language looked like this: `class ProductData extends null<String, ProductDataBase>`, this is not correct, it should look like this? `class ProductData extends ProductDataBase`. This PR fixes that.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@sebastianhaas @mkusaka

### CODE REVIEW

**Comment by wing328** [comment]
cc 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04)

**Review by macjohnny — APPROVED** [review]
Thanks for your contribution

**Comment by andreseloysv** [comment]
For an object like this:

```yaml
Foo:
  type: object
  required:
    - id
  properties:
    id:
      type: string
  additionalProperties: {}
```

The current solution generates the following class:

```typescript
export class Foo extends any {
```

This results in a compilation error because you cannot extend from `any`. In my opinion, this issue should be addressed before closing the pull request.

**Comment by mvarchdev** [comment]
@andreseloysv Will you look at that? Basicaly it should not happen that there will be additionalProperties empty, but of course it should be handled as it is edge case.

**Comment by s-xu-wafios** [comment]
> For an object like this:
> 
> ```yaml
> Foo:
>   type: object
>   required:
>     - id
>   properties:
>     id:
>       type: string
>   additionalProperties: {}
> ```
> 
> The current solution with typescript-node generates the following class:
> 
> ```ts
> export class Foo extends any {
> ```
> 
> This results in a compilation error because you cannot extend from `any`. In my opinion, this issue should be addressed before closing the pull request.



Just to provide more information, in the previous version (7.4.0), for such an object
`
Foo:
  type: object
  required:
    - id
  properties:
    id:
      type: string
  additionalProperties: {}
`


In 7.4.0 it would generate (also not sure if it's also correct)
`
export class Foo extends null<String, any> {
`

and in 7.5.0 it generates (with compilation error)
`
export class Foo extends any {
`

**Comment by mvarchdev** [comment]
`extends null<String, any>` is not correct and will result in compilation error and linting errors. That is the reason why I implemented this. You simply cannot extend null and null does not have any type parameters. We can put check so instead of extending any we can put `Record<string, unknown>` which is correct.

**Comment by mvarchdev** [comment]
I will create new PR for that!

**Comment by mvarchdev** [comment]
Guys, followup created #18491, CC @andreseloysv @s-xu-wafios

**Comment by mvarchdev** [comment]
CC @macjohnny @wing328 followup PR craeted

**Pull request merged**
