### PR TITLE
[csharp-netcore] Fixed compiler null-check warning

### LINKED ISSUE #3693: [BUG][C#][csharp-netcore] Many warnings detected when building generated code
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When building a generated client using the csharp-netcore generator with a targetFramework of netcoreapp2.0, there are many compilation warning detected. When using the test yaml from here: https://github.com/OpenAPITools/openapi-generator/blob/v4.1.0/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml, 70 warnings are detected.

Most of the warnings are of the form:
```
PetApi.cs(713, 17): [CS0472] The result of the expression is always 'false' since a value of type 'long' is never equal to 'null' of type 'long?'
```

Expected behavior is for no warnings to be generated.

##### openapi-generator version

4.1.0

##### OpenAPI declaration file content or url

I used the test yaml here: https://github.com/OpenAPITools/openapi-generator/blob/v4.1.0/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml

##### Command line used for generation

openapi-generator generate -g csharp-netcore -i ./petstore-with-fake-endpoints-models-for-testing.yaml --additional-properties targetFramework=netcoreapp2.0 -o ./netcoreapp2.0

##### Steps to reproduce

Run the command line above and build the project. Look at the compiler warnings.

### LINKED ISSUE #4604: [BUG] [csharp-netcore] Don't check integers if they are null
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))
##### Description

The generation works fine, but I get warnings by the compiler in Visual Studio due to code like this:

>        public Org.OpenAPITools.Client.ApiResponse< CustomerExternalServicesModelCollection > GetCustomerExternalServicesWithHttpInfo (int customerId)
>         {
>             // verify the required parameter 'customerId' is set
>             if (customerId == null)
>                 throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'customerId' when calling CustomerExternalServicesApi->GetCustomerExternalServices");
> 

.....

##### openapi-generator version

4.2.1

##### OpenAPI declaration file content or url

https://leksaker.starweb.se/api/v2/openapi.json

##### Command line used for generation

npx openapi-generator generate -i https://leksaker.starweb.se/api/v2/openapi.json -g csharp-netcore -o /temp/swagger

##### Suggest a fix

Don't include null-checks against integer input parameters.

### PR DESCRIPTION
**Pull request by shibayan**
### PR detail

- Introduce `x-value-type` vendor extension
  - This property represents a C# ValueType
- Make template null check decisions respect `x-value-type`

This PR is closes #4604, closes #3693

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@mandrean @jimschubert @frankyjuang

### CODE REVIEW

**Comment by etherealjoy** [comment]
Would it make sense if we do this in the **AbstractCSharpCodegen.java** because it can then be reused across the other C# based generators?

**Comment by shibayan** [comment]
It would make sense to modify the `csharp` generator, as similar null check code is being generated. However, since the modification of the template is large, I want to modify only `csharp-netcore` first.

**Comment by wing328** [comment]
One minor suggestion: do you mind naming the vendor extensions as `x-csharp-value-type` instead to make it clear the extension is for C# only?

**Comment by shibayan** [comment]
@wing328 Thank you for feedback. I changed vendor extensions to `x-csharp-value-type`.

**Comment by JFCote** [comment]
@shibayan I currently looking to do some fix in the aspnetcore generator and stumble on a problem in the mustache file that is linked to this PR.

There are 2 vendor extensions that are named almost the same and that do not do exactly the same thing.

There is your extension that is named `x-csharp-value-type` and which makes sense to me.
There is also another extension called `x-is-value-type` that was renamed in this commit: https://github.com/OpenAPITools/openapi-generator/commit/8d6286dfae0c37d53ce9d27cd00b8e8ef87bcfe1
It was called `isValueType` before that but since version 5.0 the format changed.
`isValueType` was added in this commit, a long time ago:  https://github.com/OpenAPITools/openapi-generator/commit/aae97638a9d7decaeba270264de4c5ea6284c5c0

So, is it just me or these 2 vendor extensions are pretty dangerous and there should only be one? 
I'm pretty sure the correct one is the `x-csharp-value-type` but I would like to have advice of people here.

@wing328 
Csharp committee: @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) @Blackclaws (2021/03) @lucamazzanti (2021/05)

**Comment by JFCote** [comment]
@shibayan I've created a PR based on my previous comment. You can find it here. It removes the duplicate vendor extension and use yours by default everywhere. It fixes all previous warnings and everything compiles like before!
https://github.com/OpenAPITools/openapi-generator/pull/15547

**Pull request merged**
