### PR TITLE
[AspNetCore] Emit default values for aspnetcore 3 value types

### LINKED ISSUE #10772: [BUG] [aspnetcore] Unable to set primitive datatypes (with default spec) to the defaults of the primitive data type
##### Description
If you specify a primitive datatype model property (like boolean or number) with a default value in the OpenAPI Spec, then it is not possible to set this value to the default value of the primitive datatype.
Sounds crazy, and it drives you crazy.
For example if you specify a boolean with the default "true", you are not able to send this boolean to false. Or more confusing, if you specify a number with a default other than 0 (e.g. 12) then you can't send this number to 0 (all other values are working).

##### openapi-generator version
5.x and also 6.0.x

###### generators 
aspnetcore , maybe also other C# generators (csharp, csharp-netcore)

##### OpenAPI declaration

    components:
      schemas:
        TESTOBJECT:
          type: object
            properties:
              TESTPROP1:
                type: boolean
                description: a boolean with default true
                default: true
              TESTPROP2:
                type: number
                format: int32
                description: a number with default 12
                default: 12

##### Generation Details
    powershell docker run --rm -v %OUTPUT_DIRECTORY%:/out -v %INTERFACE_DIRECTORY%:/specs openapitools/openapi-generator-cli generate -i specs/%INTERFACE_FILE% -o /out -g aspnetcore --additional-properties aspnetCoreVersion=5.0,buildTarget=library,operationModifier=abstract,packageName=%PACKAGE_NAME%,packageVersion=%INTERFACE_VERSION%,enumValueSuffix=,removeEnumValuePrefix=false

##### Request-Json
    {
        "TESTPROP1": false,
        "TESTPROP2": 0
    }

##### Actual model values
    TESTOBJECT {
       TESTPROP1: true
       TESTPROP2: 12
    }

##### Expected model values
    TESTOBJECT {
       TESTPROP1: false
       TESTPROP2: 0
    }

##### Suggest a fix
The problem is that the generator is not handling the default values.
Actual generated TESTOBJECT class:

    [DataMember(Name="TESTPROP1", EmitDefaultValue=false)]
    public bool TESTPROP1{ get; set; } = true;
    
    [DataMember(Name="TESTPROP2", EmitDefaultValue=false)]
    public decimal TESTPROP2{ get; set; } = 12;

Per default "EmitDefaultValue=false". So there is no mapping _false_ for TESTPROP1, because _false_ is the default value for a boolean. So it is not possible to set TESTPROP1 to _false_.
Also _0_ is not mapped for TESTPROP2, because _0_ is the default value for a decimal.

The fix would be to change modle.mustache to generate:

    [DataMember(Name="TESTPROP1", EmitDefaultValue=false)]
    [DefaultValue(true)]
    public bool TESTPROP1{ get; set; } = true;
  
    [DataMember(Name="TESTPROP2", EmitDefaultValue=false)]
    [DefaultValue(12)]
    public decimal TESTPROP2{ get; set; } = 12;

So the default-value for the primitive data type is changed, and _false_ and _0_ would be mapped.
So far i can test it, it was working with .NET 5.0

###### Workaround
If it is possible to change the OpenAPI-Spec, then you can also set `nullable=true`:

    components:
      schemas:
        TESTOBJECT:
          type: object
            properties:
              TESTPROP1:
                type: boolean
                description: a boolean with default true
                default: true
                nullable: true
              TESTPROP2:
                type: number
                format: int32
                description: a number with default 12
                default: 12
                nullable: true

With this spec the current 5.x generator generates `EmitDefaultValue=true` for the properties, so that all values (default or not are always mapped). But this has the drawback, that the generated properties are then nullable:

    [DataMember(Name="TESTPROP1", EmitDefaultValue=true)]
    public bool? TESTPROP1{ get; set; } = true;
    
    [DataMember(Name="TESTPROP2", EmitDefaultValue=true)]
    public decimal? TESTPROP2{ get; set; } = 12;

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/3274
https://github.com/OpenAPITools/openapi-generator/issues/4346
https://github.com/OpenAPITools/openapi-generator/issues/9071

### PR DESCRIPTION
**Pull request by hauntingEcho**
Fixes #10772 for aspnetcore 3+, possibly #9071 as well (since the initial issue was about non-nullable numeric values)

This allows numbers to be set to zero, and booleans to be set to false.
It may make sense to port this fix to the other C# generators,
though it was partially fixed (for booleans only) in the netcore client in PR9042.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. : @mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti

### CODE REVIEW

**Comment by hauntingEcho** [comment]
An alternative option here would be to use `isRequired`

**Comment by chaniwolfson** [comment]
is this fix already released?

**Comment by flobuc** [comment]
Is nobody responsible for that topic?

**Comment by wing328** [comment]
I'll try to review it over the weekend.

Please also test it locally to see if it works for you:
```
git checkout -b hauntingEcho-aspnetcore3-default-valueTypes master
git pull https://github.com/hauntingEcho/openapi-generator.git aspnetcore3-default-valueTypes
```

**Comment by wing328** [comment]
I tested it locally with the spec reported in the issue and the output compiles without issues.

**Pull request merged**
