### PR TITLE
Update to jackson-datatype-threetenbp 2.9.10

### PR DESCRIPTION
**Pull request by joschi**
Update the Jackson datatype support for ThreeTen to the latest version working with Jackson 2.9.10.

This way, there should be only minimal differences between the generated code when when using ThreeTen backport vs. not using ThreeTen backport.

swagger-api/swagger-codegen-generators#489
swagger-api/swagger-codegen#9748

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before .
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by joschi** [comment]
@wing328 Maybe you could be so nice to tag the relevant maintainers.
I'm not feeling comfortable tagging everyone listed at https://github.com/OpenAPITools/openapi-generator#62---openapi-generator-technical-committee for Java and Kotlin.

**Comment by macjohnny** [comment]
cc 

Java | @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)
-- | --
Kotlin | @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04)

**Comment by wing328** [comment]
No expert in threeten either but the version upgrade looks reasonable to me

**Comment by wing328** [comment]
@joschi thanks for the PR, which has been included in v4.2.0 release: https://twitter.com/oas_generator/status/1189824932345069569

**Pull request merged**
