### PR TITLE
[Java][Spring] Fix for #8659 Different in-parameter types generated for api and delegate for binary (application/octet-stream)

### PR DESCRIPTION
**Pull request by EmhyrVarEmreis**
Related to #8659 

Actual api endpoint is using `org.springframework.core.io.Resource` but delegatee is using `org.springframework.web.multipart.MultipartFile`
Now both are using the second one, which is recommended by Spring (according to my latest knowledge)
Tests are passing and also generation of the following endpoint works (it does not work on plain 5.1.0)
```
post:
  operationId: setClientFile
  tags:
    - clients
  parameters:
    - $ref: '#/components/parameters/clientId'
  requestBody:
    required: true
    content:
      application/octet-stream:
        schema:
          type: string
          format: binary
  responses:
    204:
      description: No records found
    415:
      description: Invalid image type
    200:
      description: Upload successful
```

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by EmhyrVarEmreis** [comment]
@agilob
@wing328

**Comment by xross-criss** [comment]
I am waiting for this merge too. Hope you would do it quite fast :). Thanks in advance.

**Review by agilob — APPROVED** [review]

**Comment by wing328** [comment]
Tested locally and the result is good.

**Comment by apinske** [comment]
That'a a breaking change in a fix-version. I have to change my code from Resource to MultipartFile and then it doesn't even work anymore because application/octet-stream is not considered by spring's multipart resolver. So the parameter is null at run time.

**Comment by beckerjohannes** [comment]
> That'a a breaking change in a fix-version. I have to change my code from Resource to MultipartFile and then it doesn't even work anymore because application/octet-stream is not considered by spring's multipart resolver. So the parameter is null at run time.

Even more, it breaks the ability to return binary content. See #9462

**Pull request merged**
