### PR TITLE
Bump Gradle in generated Java projects to 6.7.1

### PR DESCRIPTION
**Pull request by tobymurray**
Bump the version of Gradle used in generated Java projects from 6.0.1 to 6.7.1

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

### CODE REVIEW

**Comment by tobymurray** [comment]
I can't see what's going on with the circleci failure, so I can't really fix it. If someone has access to the build, can you paste the output?

**Comment by wing328** [comment]
Restarted the job. Let's see how that goes.

**Comment by wing328** [comment]
Verified the checksum of `modules/openapi-generator/src/main/resources/Java/gradle-wrapper.jar`

**Comment by tobymurray** [comment]
Looks like it failed again - does it look like an issue with the change, or is it some difficulty with the build?

**Comment by tobymurray** [comment]
Ah, looks like I missed all the Java samples that did not follow the pattern `bin/configs/java-*`. Is there a single command you use to update all Java samples?

**Comment by wing328** [comment]
`./bin/utils/ensure-up-to-date` will update all samples.

**Comment by tobymurray** [comment]
Ah, I misunderstood `./bin/generate-samples.sh`. I read the suggestion to use `java-*` as an indication that that would generate the Java ones. Running it now with no arguments I see the changes you've added here.

> You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example ./bin/generate-samples.sh bin/configs/java*

Is the descriptiveness in the pull request checklist helpful? I.e. is there a use case for not updating all the samples? I imagine I would have run the script on all samples had I not read (and misunderstood) that. 

Thanks for fixing this up - I wasn't going to get there (especially with no build output).

**Comment by wing328** [comment]
Yup, simply run `./bin/generate-samples.sh` (called by ensure-up-to-date script) will do the job (in terms of updating samples).

**Pull request merged**
