### PR TITLE
Refactor typescript merge master

### PR DESCRIPTION
**Pull request by bodograumann**
I merged `master` into `typescript-refactor` to decrease the divergence between the two.
Most changes went through automatically. I only had to manually resolve simple conflicts in `README.md`, `docs/generators.md` and `modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java`.

Cf. #802 
CC @TiFu

### CODE REVIEW

**Comment by bodograumann** [comment]
Ok, sure, I'm on it. Seems to be taking some time.
I would have thought that running `./bin/typescript.sh` would be enough.

**Comment by bodograumann** [comment]
Curious. Seems my local build system is producing different samples than the circleci. Trying to only commit `typescript.md` now.

**Comment by bodograumann** [comment]
Looks like we are ready to go @TiFu  :slightly_smiling_face:

**Comment by TiFu** [comment]
Again, thanks for the PR which has been merged into `ts-refactor`

**Pull request merged**
