### PR TITLE
Add x-nullable (OAS2) support

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

A follow up PR to #873

### CODE REVIEW

**Comment by jmini** [comment]
The `x-nullable` can be added to parameter?

What will be the result of (OAS3 example) a parameter and a Schema not telling the same:

```yaml
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          x-nullable: false
          schema:
            type: integer
            format: int64
            nullable: true
```

Is this consistently treated?

**Comment by wing328** [comment]
Very good question. OAS3 shouldn't use/need `x-nullable` as the schema supports `nullable` already.

**Comment by jmini** [comment]
The potential conflict between `x-nullable` and `nullable` in OAS3 needs to be solved (see previous discussion). Maybe the solution is to log a warning or a validation issue when there are conflicts.

`x-nullable` for OAS2 requires a Swagger-Parser update which is planned for `3.3.0`.

My take is that with `3.2.3` the feature will be useless.

**Comment by jmini** [comment]
While I was investing, I have seen, the the conversion
* from OAS2 `x-nullable` on a paramter
* to OAS3 `nullable` in the schema of the parameter

is already correctly implemented by Swagger-Parser.

This means the code proposed by #873 will already work with OAS2 and that this PR introduces unnecessary code that can be reverted.

**Comment by jmini** [comment]
See follow up PR: https://github.com/OpenAPITools/openapi-generator/pull/930

**Pull request merged**
