### PR TITLE
Forbiddenapis check and fix

### PR DESCRIPTION
**Pull request by burberius**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

### Description of the PR

I used the forbiddenapis maven plugin with code generated by openapi codegen and it found some problems.
So I added the plugin to the openapi-generator parent pom, ran the checks there and fixed all findings.
In all java templates I also fixed the findings and generated the samples to check it.

You can read more about the found problems in this article:
https://dzone.com/articles/policemans-horror-default

### CODE REVIEW

**Comment by jeff9finger** [comment]
This seems like a good idea.

**Comment by wing328** [comment]
@burberius thanks for the PR 👍 

@jeff9finger thanks for reviewing the change.

If no further feedback or question, I'll merge it on coming Wed.

**Comment by wing328** [comment]
@burberius I wonder if you can resolve the merge conflicts and then I'll merge it into master. 

Sorry for taking a bit long to review the change.

**Comment by jmini** [comment]
I have merged develop into this branch (incl solving merge conflicts) => c73dbbb
I have fixed the new "forbiddenapis" checks introduced by changes made on master => 79f38bf

---

Because the change introduce a new check, it would be great to merge `master` into this pr before doing the "Squash and merge" to ensure that the changes on `master` are not breaking the build once this PR is "Squashed and merged".

**Comment by wing328** [comment]
@burberius thanks for the fix, which is included in the v3.2.2 stable release: https://twitter.com/oas_generator/status/1032252335131512832

**Pull request merged**
