### PR TITLE
[typescript-fetch] remove namespaces in enums

### PR DESCRIPTION
**Pull request by willianscfa**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fix behaviour of enums for typescript fetch, removing namespaces according to suggestions made in #1947.

@macjohnny

### CODE REVIEW

**Comment by willianscfa** [comment]
Because of the failing tests I just realized that I messed up with AbstractTypescriptClientCodegen that is used by all typescript clients.

Should I modify all typescript templates using namespaces or should I override the ```postProcessModels``` method on TypeScriptFetchClientCodegen ?
 
Is there any other alternatives? Thank you in advance.

**Comment by wing328** [comment]
> Should I modify all typescript templates using namespaces or should I override the `postProcessModels` method on TypeScriptFetchClientCodegen ?

Please override `postProcessModels` in TypeScriptFetchClientCodegen for the time being.

**Comment by willianscfa** [comment]
I don't know how to solve the Circle CI problem. From what I understand 'UNCOMMITTED CHANGES ERROR' refers to my branch being out of sync with some other one.

I tried pulling from upstream master, but it shows 'Already up to date'. 

Any help appreciated. 

Thanks

**Comment by macjohnny** [comment]
@willianscfa 
> I don't know how to solve the Circle CI problem. From what I understand 'UNCOMMITTED CHANGES ERROR' refers to my branch being out of sync with some other one.

this error indicates that some samples need to be re-generated as they do not correspond to newly generated samples anymore.
in this case, it is due to my revert-commit https://github.com/OpenAPITools/openapi-generator/pull/2128 that missed the examples, since they were generated in a different commit.
However, with https://github.com/OpenAPITools/openapi-generator/pull/2149 the typescript angular examples should be in sync again.

in the meantime, you can simply run https://github.com/OpenAPITools/openapi-generator/blob/master/bin/typescript-angular-petstore-all.sh to re-generate the angular samples and pass CI

**Comment by macjohnny** [comment]
@wing328 could you please re-trigger CI? the out-of-date angular typescript samples problem should have been resolved with https://github.com/OpenAPITools/openapi-generator/pull/2149

**Comment by willianscfa** [comment]
@macjohnny I did a ```git pull upstream master```, hope that triggers the CI correctly.

**Comment by macjohnny** [comment]
ok, now the Go and Kotlin samples seem to be out of sync. but it should be possible to merge this PR anyway

**Comment by macjohnny** [comment]
cc 

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)
--

**Comment by wing328** [comment]
> ok, now the Go and Kotlin samples seem to be out of sync. but it should be possible to merge this PR anyway

That has been fixed in the master.

**Comment by wing328** [comment]
## Upgrade Note

The class name is added as a prefix to the enum naming: 

Before: `StatusEnum`
After: `PetStatusEnum`

**Pull request merged**
