### PR TITLE
Tries to fix #18975 by changing how the deserializer interacts with its parent class

### LINKED ISSUE #18975: [BUG][JAVA] Generated anyOf models have deserializer that returns bad type the first time its used
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating code for models that contain `anyOf` properties, the resulting deserializers don't always return the correct response type. The first time input JSON is deserialized, the resulting instance can be of the wrong type.

##### openapi-generator version

Version 7.6.0 and before.

##### OpenAPI declaration file content or url

https://gist.github.com/qbuzzdaan/d4348d1786e4d519a60df6e3790580ed

##### Generation Details

n/a

##### Steps to reproduce

Generation files are included in the [gist](https://gist.github.com/qbuzzdaan/d4348d1786e4d519a60df6e3790580ed): the `pom.xml` defines how the `openapi-spec.yaml` is to be turned into classes, and the `DifficultTest.java` shows the issue.

##### Related issues/PRs

Couldn't find any

##### Suggest a fix

I'll push a branch with a potential fix in the generation mustache files.

### PR DESCRIPTION
**Pull request by qbuzzdaan**
Changes how an `StdDeserializer<A>` of a specific type `A` deserializes into an `A`. We noticed the static block filling the `mappings` passed to the `JSON.registerDiscriminator(A.class, "type", mappings)` was only called _after_ the first call to the deserializer, causing the first result to have an `setActualInstance` call of the wrong subtype of `A`. This is because the static block is part of `A`, while the `StdDeserializer<A>` is a static subclass of `A`. Changing the reference to `A.class` into an actual instance of `A` by the `new A().getClass()` causes the static block to be called on time.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR.

please follow step 3 to update the samples so that the CI can verify the change.

**Comment by qbuzzdaan** [comment]
First commit/PR here, trying my best to follow the steps/guidelines etc :)
Ran the commands of steps 3, there are no changes in the samples as it seems.

**Comment by wing328** [comment]
can you please share a spec to reproduce the issue?

one thing I noticed is that the anyof model template has `{{#discriminator}}` tag but oneOf (but not anyOf) can have discriminators  so looks like something may not be right

**Comment by qbuzzdaan** [comment]
I've added the `issue_18975.yaml` spec. Running step 3 again again didn't yield any changes in my repository.

**Comment by wing328** [comment]
tested locally and the output copmiles without issue. let's give it a try

i'll add a test after merging this PR

thanks again for the PR

**Pull request merged**
