### PR TITLE
Adds Collapse Spec Options to Maven Plugin

### PR DESCRIPTION
**Pull request by dchauhan-twilio**
* Adds a collapsedSpec option to the maven plugin that produces a single-file representation of the spec in the output directory.
* Adds a includeCollapsedSpecInArtifacts option to the maven plugin that adds the collapsed spec file to the maven artifacts.

### How to manually verify
1. Add the maven plugin to a project.
2. Add the `collapsedSpec` and `includeCollapsedSpecInArtifacts` options to the plugin configuration.
3. Run `mvn deploy`
4. Verify that the target directory contains the merged spec. This file name will match the `collapsedSpec` value.
5. Verify the deploy repository contains the spec where the classifier name matches that of the `collapsedSpec` value.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
> Adds a collapsedSpec option to the maven plugin that produces a single-file representation of the spec in the output directory.

i think it's doable now. 

if you use the `java` client generator, you will get `api/openapi.yaml` file which is a single file representing the spec.

**Comment by dchauhan-twilio** [comment]
> > Adds a collapsedSpec option to the maven plugin that produces a single-file representation of the spec in the output directory.
> 
> i think it's doable now.
> 
> if you use the `java` client generator, you will get `api/openapi.yaml` file which is a single file representing the spec.

I see, but looking for this capability in the maven generator as we build against poms. In our workflow, the openapi spec is committed with the java service repository.  The repository build process will then generate the service resource handlers and a java client. We now have cases where clients in other languages need to generate a client, and while we lack a swagger hub store, adding the spec to the artifact repository works as a good alternative.

**Comment by dchauhan-twilio** [comment]
@bbdouglas, @sreeshas, @jfiala, @lukoyanov, @cbornet, @jeff9finger, @karismann, @Zomzog, @lwlee2608, or @martin-mfg do one you mind reviewing this PR?

**Comment by wing328** [comment]
@dchauhan-twilio thanks for the explanation. we can give it a try.

can you please update the readme with the new option?

https://github.com/OpenAPITools/openapi-generator/tree/873094cd3477be3f753746c22a9bd9347ec1bc03/modules/openapi-generator-maven-plugin

**Comment by wing328** [comment]
CI tests failed: https://github.com/OpenAPITools/openapi-generator/actions/runs/7673305908/job/21045742400?pr=17714

can you please take a look?

**Comment by dchauhan-twilio** [comment]
> @dchauhan-twilio thanks for the explanation. we can give it a try.
> 
> can you please update the readme with the new option?
> 
> https://github.com/OpenAPITools/openapi-generator/blob/873094cd3477be3f753746c22a9bd9347ec1bc03/modules/openapi-generator-maven-plugin/README.md

Good idea, added in the last commit de1a753d53009d1b2bdf537a11b6645ec34513e1

**Comment by dchauhan-twilio** [comment]
@bbdouglas, @sreeshas, @jfiala, @lukoyanov, @cbornet, @jeff9finger, @karismann, @Zomzog, @lwlee2608, or @martin-mfg, I see you are the maintainers for this section of the repo. Can you please review?

**Comment by wing328** [comment]
tests still failed. can you please take another look?

**Comment by dchauhan-twilio** [comment]
> tests still failed. can you please take another look?

@wing328 Apologies for the delay, been a busy week struggled to replicate locally. Found the bug in the end (it was a casing issue :face_palm). I have validated the workflows pass in my fork (see https://github.com/dchauhan-twilio/openapi-generator/pull/2) so hopefully once the workflows are approved to run in this repo, it will pass here too.

**Comment by wing328** [comment]
No need to sorry. We all appreciate your contributions. Just triggered the workflow and let's see how that goes.

**Comment by dchauhan-twilio** [comment]
@wing328 looks like all the tests passed. Can this be merged?

**Comment by wing328** [comment]
looks good. let's give it a try

thanks for the PR.

**Pull request merged**
