### PR TITLE
Moved to Swagger 2 annotations as well as SpringDoc instead of Springfox

### PR DESCRIPTION
**Pull request by N4zroth**
Changed the generated annotations to Swagger 2 annotations, built the samples and verified them by hand (and maven clean compile). The only thing I can't get to work is the @Schema in springboot-reactive as it results in class=List<String>.class which is obviously incorrect. The other projects compile and seem to be correct. Would love to be corrected if need be, though :)
The underlying issue was https://github.com/OpenAPITools/openapi-generator/issues/4245

### PR checklist

- [(/)] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [(/)] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [(/)] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [(/)] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [(/)] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### CODE REVIEW

**Comment by wing328** [comment]
@N4zroth thanks for the PR. Please PM me via Slack to discuss this PR when you've time.

**Comment by alexsuperdev** [comment]
@N4zroth its realy important issue i think. Can you fix the conflicts or do you need help with it? I would like to have restdocs in the next releases of openapi-generator.

**Comment by cbornet** [comment]
I think Springfox is still far more used than Springdoc. So using v3 annotations should be an option atm.

**Comment by alexsuperdev** [comment]
> 
> 
> I think Springfox is still far more used than Springdoc. So using v3 annotations should be an option atm.

Yes, you are right. But the thing is springfox latest release was in June 2018. They don't support OpenApi 3. Yes, best case would be an option to choose between both of them.

**Comment by shred22** [comment]
Any tentative timelines when this PR will be merged?

**Comment by tan9** [comment]
It will be awesome if this MR can be included in the [5.0.0 milestone](https://github.com/OpenAPITools/openapi-generator/milestone/20).

**Comment by cbornet** [comment]
Springfox v3 has been released and it supports OASv3. So we should stick with Springfox as it's much more popular and upgrade it to v3.

**Comment by matnice** [comment]
@cbornet, 

 Can we please have the support of springdoc as well for OAS 3 ? 

 springfox is not popular for OpenAPI3. Springfox lacks of maintenance. The last release was more than two years ago.  
 The springfox new release 3.0.0 is already plenty of issues and missing a lot of fuctionnalities. You can just have a tour on the github:

 All projects since this date who needed OpenAPI 3 support in spring applications moved to springdoc.

 We really need this enhancement, and thank you for the support.

**Comment by mstroecker** [comment]
Is there any hope?

**Comment by honza-zidek** [comment]
Is there any progress please? It has been open for so long...

**Comment by RockyMM** [comment]
I am interested in this issue as well. If there is nobody else, I hope around Christmas time I could invest some time into fixing merge conflicts.

**Comment by uniquejava** [comment]
Springfox is abandoned , 3.0 is their last release and yet another year passed, please use springdoc.

**Comment by welshm** [comment]
FWIW - this may be a solution for those looking to use `oas3` and `springdoc`

https://github.com/OpenAPITools/openapi-generator/pull/9775

**Comment by cachescrubber** [comment]
@N4zroth, @wing328  since 5.4.0 springdoc is the default documentation provider for the spring generator. Please close this PR.

**Pull request closed without merging**
