### PR TITLE
[java] Updated java gson ObjectToNumberStrategy to LONG_OR_DOUBLE

### PR DESCRIPTION
**Pull request by JoshAlbrecht23**
When an endpoint response type is a set to an Object, there are issues de-serializing Long values using Gson in the generated ApiClient class because of the default objectToNumberStrategy that Gson uses. By default Gson uses ToNumberPolicy.DOUBLE. as the objectToNumberStrategy and this is problematic when trying to de-serialize a value that is larger than a double and causes inaccuracies.

**Example with current implementation:**
The following json 
```
{"value" : 7076632681529943151}
```
is de-serialized to:
```
{value=7.076632681529943E18}
```

**Validating the proposed changes:**
The following json 
```
{"value" : 7076632681529943151}
```
should de-serialize to:
```
{value=7076632681529943151}
```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

**Comment by wing328** [comment]
@JoshAlbrecht23 thanks for the PR. Is it ready for review?

**Comment by JoshAlbrecht23** [comment]
> @JoshAlbrecht23 thanks for the PR. Is it ready for review?

Hi @wing328, sorry for the delayed response on this. I converted the draft to a PR ready for review.

**Comment by wing328** [comment]
can you please review the build/test failure when you've time?

https://github.com/OpenAPITools/openapi-generator/actions/runs/4715865984/jobs/8404960320?pr=15165

**Comment by JoshAlbrecht23** [comment]
> can you please review the build/test failure when you've time?
> 
> https://github.com/OpenAPITools/openapi-generator/actions/runs/4715865984/jobs/8404960320?pr=15165

Updated the PR to fix the build/test failures

**Comment by wing328** [comment]
@JoshAlbrecht23 thanks again for the PR. 

My understanding is that this fix is NOT a breaking change. Please correct me if I'm wrong.

**Comment by JoshAlbrecht23** [comment]
@wing328 No problem!

Thanks for double checking on this. Thinking about this more, I don't think this is a passive change as we will be parsing numbers as `Long` instead of `Double`.  This would be problematic for anyone that has tests that are asserting against the deserialized values expecting `Double` values. I added a test below to demonstrate. I think we will have to rethink this approach to ensure passivity.

```
    @Test
    public void passivityTest() {
        Gson gson = new GsonBuilder()
            .setObjectToNumberStrategy(ToNumberPolicy.LONG_OR_DOUBLE)
            .create();

        List<Double> expected = Arrays.asList(100.0, 1000.0, 2000.0);
        Object actual = gson.fromJson("[100, 1000, 2000]", Object.class);

        assertEquals(expected, actual);
    }
```

**Pull request closed without merging**
