### PR TITLE
ruby client adapter for httpx

### PR DESCRIPTION
**Pull request by HoneyryderChuck**
This PR introduces support for [httpx](https://gitlab.com/os85/httpx), a modern ruby HTTP client library, as one of the possible alternatives with which to build an openapi-based SDK.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
@cliffano @zlx @autopp

**Comment by HoneyryderChuck** [comment]
@wing328 thx for the review. i think that's done already (pom.xml is already updated with a ruby-httpx entry, which points to a yaml pointing to the sample project). Or is there smth else missing?

**Comment by wing328** [comment]
@HoneyryderChuck thanks for the PR, which has been merged. Can you please PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by wing328** [comment]
FYI. I've merged https://github.com/OpenAPITools/openapi-generator/pull/16729 to add Ruby (httpx) echo API client tests.

**Comment by HoneyryderChuck** [comment]
@wing328 thx! Won't be able to today, will do it tomorrow.

**Pull request merged**
