### PR TITLE
fix for the issue, with the spec invlolving arrayschema structure with reference of another schema  for java code generation

### PR DESCRIPTION
**Pull request by ngp-star**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

fix for the issue https://github.com/OpenAPITools/openapi-generator/issues/6267
PR is against the master branch.

### CODE REVIEW

**Comment by ngp-star** [comment]
@bbdouglas  @sreeshas   @jfiala   @lukoyanov @cbornet  @jeff9finger  @karismann @Zomzog  @lwlee2608  @bkabrda 

can you please review this PR.

**Comment by ngp-star** [comment]
@bkabrda 
is there any updates on this PR?

**Comment by ngp-star** [comment]
@wing328 
can you please review this PR?

**Comment by ngp-star** [comment]
@wing328 
is there any updates on this PR?

**Comment by ngp-star** [comment]
@wing328 
are there any updates on this PR?

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
The fix looks ok. Thanks for the fix and sorry for taking a bit long to review as there are just too many PRs.

Let me know if you need help fixing the commit authorship.

**Comment by ngp-star** [comment]
Hi @wing328 
thanks for the update can you please tell for fixing the commit authorship?

**Comment by wing328** [comment]
Please have a look at https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by ngp-star** [comment]
@wing328 
sure, let me do changes and push the commit.

**Comment by ngp-star** [comment]
@wing328 
I have done the changes, which include the update of the author name on this commit can you please review this?

**Comment by wing328** [comment]
Looks good now. Thanks for the contribution.

**Comment by ngp-star** [comment]
@wing328 
you are welcome

**Pull request merged**
