### PR TITLE
Fix counting for large API solutions in generated Python README

### PR DESCRIPTION
**Pull request by languitar**
Let 2 follow 1.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run 
  ```
  mvn clean package
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  to update all Petstore samples related to your fix. 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)

### CODE REVIEW

**Comment by spacether** [comment]
Thank you for this PR. Can you fix the CI errors?

**Comment by languitar** [comment]
How am I going to fix

> anyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by languitar** [comment]
For Circle CI it seems I am not allowed to see the results?

**Comment by spacether** [comment]
Re-triggering circle-ci it failed to pull a java thing

**Comment by spacether** [comment]
Closing and re-opening to re-trigger travis. We may have a new increased limit of docker pulls.

**Comment by spacether** [comment]
Can you re-generate the python samples with:
```
mvn clean package
./bin/generate-samples.sh
```
Your readme update should be output in our sample for the python generator.

**Comment by languitar** [comment]
Now with updated samples

**Comment by languitar** [comment]
Again a connection reset error on Circle CI.

**Comment by spacether** [comment]
What if you rebase? I am seeing travis pass on other branches...

**Comment by languitar** [comment]
Next try after rebasing.

**Review by spacether — APPROVED** [review]
Thank you for your PR! This looks good.

**Pull request merged**
