### PR TITLE
5.0.0 beta3 fix dart client enum name generation

### LINKED ISSUE #7867: [BUG] [Dart] Problem with enum generation, when enum value is a symbol, like the character %
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

There is a problem with the generated dart code for enums, as those enums in the openapi.json file, where the enum value is a special character, like %, will end up in the generated dart code with the name `_`.

##### openapi-generator version

4.3.1

##### Support file contents

The openapi.json file content is shown below. The part of the specification that results in the problematic dart code is `components/schemas/PercentileUnit/enum`.

```json
{
    "openapi": "3.0.2",
    "info": {
        "title": "FastAPI",
        "version": "0.1.0"
    },
    "paths": {
        "/enum/": {
            "get": {
                "tags": [
                    "Administration"
                ],
                "summary": "Test Enum",
                "description": "Test get enum.",
                "operationId": "test_enum_enum__get",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/PercentileValue"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "PercentileUnit": {
                "title": "PercentileUnit",
                "enum": [
                    "%"
                ],
                "type": "string",
                "description": "An enumeration."
            },
            "PercentileValue": {
                "title": "PercentileValue",
                "required": [
                    "unit",
                    "value"
                ],
                "type": "object",
                "properties": {
                    "unit": {
                        "$ref": "#/components/schemas/PercentileUnit"
                    },
                    "value": {
                        "title": "Value",
                        "maximum": 97,
                        "minimum": 3,
                        "type": "number",
                        "description": "Value of the percentile."
                    }
                }
            }
        }
    }
}
```

The flutterconfig-dart.json file is the following:

```json
{
    "pubAuthor": "Agent Moo",
    "pubDescription": "Security level BBR (Burn Before Read)",
    "pubName": "PeekAMooOpenAPI",
    "browserClient": false,
    "useEnumExtension": true
}
```

The generated percentile_unit.dart model file that has an issue is the following:

```dart
part of PeekAMooOpenAPI.api;

class PercentileUnit {
  /// The underlying value of this enum member.
  final String value;

  const PercentileUnit._internal(this.value);

  /// An enumeration.
  static const PercentileUnit _ = const PercentileUnit._internal("%");

  static PercentileUnit fromJson(String value) {
    return new PercentileUnitTypeTransformer().decode(value);
  }
  
  static List<PercentileUnit> listFromJson(List<dynamic> json) {
    return json == null ? new List<PercentileUnit>() : json.map((value) => PercentileUnit.fromJson(value)).toList();
  }
}

class PercentileUnitTypeTransformer {

  dynamic encode(PercentileUnit data) {
    return data.value;
  }

  PercentileUnit decode(dynamic data) {
    switch (data) {
      case "%": return PercentileUnit._;
      default: throw('Unknown enum value to decode: $data');
    }
  }
}

```

The problem I have with the code above:

```dart
  /// An enumeration.
  static const PercentileUnit _ = const PercentileUnit._internal("%");
```

Dart code outside the generated dart package cannot reference enume value with `PercentileUnit._`. Somehow special characters, like `%` should be translated to a string, that can be used as valid parameter name in Dart, because currently the special characters are translated to an empty string. Most likely the problem is with the content of {{{name}}} in https://github.com/OpenAPITools/openapi-generator/blob/b6091571aa4a93d086f8618bdf3d12092f24d157/modules/openapi-generator/src/main/resources/dart/enum.mustache#L13 and in https://github.com/OpenAPITools/openapi-generator/blob/b6091571aa4a93d086f8618bdf3d12092f24d157/modules/openapi-generator/src/main/resources/dart/enum.mustache#L30.

##### Generation Details

The Dart code is generated on Windows with the following shell command.

```shell
java -jar openapi-generator-cli-4.3.1.jar generate -i .\openapi.json -g dart -o .\peekamoo-openapi -c flutterconfig-dart.json
```

##### Steps to reproduce

Execute shell command written above, using the support files included above, then check the generated dart code in `.\peekamoo-openapi\lib\model\percentile_unit.dart`.

##### Related issues/PRs

none

##### Suggest a fix

The content of {{{name}}} in https://github.com/OpenAPITools/openapi-generator/blob/b6091571aa4a93d086f8618bdf3d12092f24d157/modules/openapi-generator/src/main/resources/dart/enum.mustache#L13 and in https://github.com/OpenAPITools/openapi-generator/blob/b6091571aa4a93d086f8618bdf3d12092f24d157/modules/openapi-generator/src/main/resources/dart/enum.mustache#L30 should not be simply `_` when the enum value is a special character.

### PR DESCRIPTION
**Pull request by ka-zo**
This pull request fixes the issue #7867. The problem, this pull request addresses, is that the generated Dart client code included enum parameter names that were automatically generated based on enum values (see line 528 in modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java in tag v5.0.0-beta3) The problematic method can be found here: https://github.com/OpenAPITools/openapi-generator/blob/2715f1371a1bd438159e4aa79bd8f1fe172b03d9/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartClientCodegen.java#L528

However, the corresponding java code of OpenAPI Generator, mentioned above, was not ready to handle cases, where the enum value was a special character, like a % character. In such cases, the enum parameter name was a single '_' character. This pull request fixes this by converting special characters to alphanumeric strings using HTML escaping. I have checked multiple Java packages that can handle HTML escaping, and the most versatile and the most configurable one, that included the most HTML entities was the unbescape java package. Even though it was modified last time in 2018, it has too many advantages just to ignore it.

I have checked if the code is working by running `mvnw clean install` in the root of the openapi-generator repository and then generating Dart client code using the generated openapi-generator-cli.jar file in the way mentioned in issue #7867.

The branch for this fix is checked out from tag v5.0.0-beta3, in line with [How can I submit a PR for a branch (e.g. 4.2.x)?](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-submit-a-pr-for-a-branch-eg-42x).

If I did not follow the pull request procedure appropriately, please forgive me, I am ready to improve if you give me directions.

Dart technical committee: @ircecho @swipesight @jaumard @amondnet 

A couple of other contributors to Dart, who might have some influence on this PR: @wing328 @agilob 

Closes #7867

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by ka-zo** [comment]
Guys, it says **ci/circleci: build — Your tests failed on CircleCI**. I do not think it has anything to do with my modifications, as the error was related to MySQL, and my modifications have nothing to do with it.

**Comment by agilob** [comment]
String sanitation shouldn't require another library as there are already dozens of examples in openapi how to do it to follow the contract and implementation of other languages. You haven't added any test for it and example showing generated code follows practices of other generators.

This problem on a wider scale has been addressed in https://github.com/OpenAPITools/openapi-generator/pull/7711

**Comment by kuhnroyal** [comment]
You can try the master branch which now has a different fix for this and potentially close this PR.

**Comment by ka-zo** [comment]
I'll check it next week.

**Comment by wing328** [comment]
Closing this one as there's no update.

Happy to reopen if needed.

**Pull request closed without merging**
