### PR TITLE
Validate spec on generation by default

### PR DESCRIPTION
**Pull request by jimschubert**
Adds a validation parameter to CodegenConfigurator, and passes through
options from CLI, Maven Plugin and Gradle Plugin to that property.

Default is to validate the spec during generation. If spec has errors,
we will output errors as well as warnings to the user.

Option can be disabled by passing false to validateSpec (Maven/Gradle)
or --validate-spec (CLI).

This was brought up in #208.  We want to validate the spec on generation to prevent OpenAPI Spec 3.x options from creeping into OpenAPI Spec 2.0 support.  I would also consider this a bug fix, because as a user I would be surprised to find that generation succeeds when my spec is invalid by default.

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by etherealjoy** [comment]
@jimschubert Can we run a validate without generate?

**Comment by jimschubert** [comment]
@etherealjoy the CLI has a validate command. Our Homebrew formula can't be merged until the repo is 30 days old (3 days from now). I created a script that you can use to run the last snapshot: https://gist.github.com/jimschubert/ce241b0c78140e364f46914ef8ec4103

**Comment by jimschubert** [comment]
see #142

**Comment by jimschubert** [comment]
@wing328 do you have any concerns if we merge this?

**Comment by wing328** [comment]
I did some tests locally but got errors with `--validate-spec=false`:
```
➜  openapi-generator git:(jimschubert-generator-validation-option) java -jar "./modules/openapi-generator-cli/target/openapi-generator-cli.jar" generate -i /var/tmp/mapissue.yaml -g aspnetcore  -o /tmp/sam --validate-spec=false
 
Exception in thread "main" io.airlift.airline.ParseArgumentsUnexpectedException: Found unexpected parameters: [--validate-spec=false]
	at io.airlift.airline.Cli.validate(Cli.java:148)
	at io.airlift.airline.Cli.parse(Cli.java:116)
	at io.airlift.airline.Cli.parse(Cli.java:97)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58)
➜  openapi-generator git:(jimschubert-generator-validation-option) 
```
Am I doing something wrong here? (clearly I don't have enough sleep these days...)

**Comment by ackintosh** [comment]
`--validate-spec` is Boolean so it doesn't allow argument and should behave like below 💡 :

- default (omitted): false
- specified: true

How about `--skip-validation` ?

**Comment by jmini** [comment]
Changed base branch: `3.2.0-SNAPSHOT` is now on `master` branch

**Comment by jimschubert** [comment]
Thanks.
What's blocking this getting merged?

**Comment by wing328** [comment]
The AppVeyor test passed via https://ci.appveyor.com/project/WilliamCheng/openapi-generator/build/jimschubert-generator-validation-option-1682.

Shippable CI failure was not repeatable locally. Let's merge this to see if the Shippable build still occurs.

**Comment by wing328** [comment]
## Upgrade Note

The default is to validate the spec during generation. If the spec has errors,
we will output errors as well as warnings to the user.

The option can be disabled by passing false to `skipValidateSpec` (Maven/Gradle)
or `--skip-validate-spec` (CLI).

**Comment by jmini** [comment]
I think the note belongs to the migration-guide:
See https://github.com/OpenAPITools/openapi-generator/pull/683

@wing328: I think the option for Maven/Gradle is called `validateSpec`...

**Comment by wing328** [comment]
@jmini you're right. Just updated the note above.

**Pull request merged**
