### PR TITLE
[C-libcurl] fix building error when complexType is empty.

### PR DESCRIPTION
**Pull request by ityuhui**
[C-libcurl] Change "complexType" to "name" inner "isMapContainer" to fix building error when complexType is empty.

When generating k8s C-libcurl client,  there is a build error due to the duplicated List

They are generated by the below template code:
```
{{#isMapContainer}}
    list_t *{{{complexType}}}List;
...
{{/isMapContainer}} 
```
But for my case,  complexType is empty, so there are some duplicated List

```
list_t *List;
...
list_t *List;
...
list_t *List;

```
They will cause building error.

 I checked other parts inner the {{#isMapContainer}} and {{/isMapContainer}} in the same [file](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/C-libcurl/model-body.mustache), and found "complexType" should be changed to "name"

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [master](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@wing328 @PowerOfCreation @zhemant

### CODE REVIEW

**Comment by ityuhui** [comment]
Hi @wing328 

The check of Shippable always failed because "build_ci" cannot succeed. I think it's an envionment issue.

**Comment by wing328** [comment]
Right I tried to restart it a couple of times but still no luck. Let me give it a try this evening to see if we've any luck.

**Comment by wing328** [comment]
Shippable CI fixex in the master

**Comment by wing328** [comment]
The shippable error has been fixed in the master.

**Pull request merged**
