### PR TITLE
[python-nextgen] fix #16010 circular refs lead to no imports

### LINKED ISSUE #16010: [BUG] `python-nextgen` circular refs lead to no imports
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generation is successful, but for recursive models the imports are missing, when trying to generate from https://github.com/hashintel/hash/blob/main/apps/hash-graph/openapi/openapi.json you can see how in `models/filter.py` the import for `AnyFilter` is missing and how in `models/any_filter.py` the import is missing for `Filter.`

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or URL

https://github.com/hashintel/hash/blob/main/apps/hash-graph/openapi/openapi.json

##### Generation Details

        "generatorName": "python-nextgen",
        "packageName": "hash_openapi",

##### Steps to reproduce

Simply generate with the aforementioned schema

### PR DESCRIPTION
**Pull request by fa0311**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### Overview
fix #16010

Circular import seem to be skipped in the current master.

https://github.com/OpenAPITools/openapi-generator/blob/d7311cd5cd47bd51281bd41e641ca00103c162f6/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java#L937-L939

### CODE REVIEW

**Comment by fa0311** [comment]
Inherited objects are being imported unnecessarily late.
This will be corrected later.

**Comment by fa0311** [comment]
> Inherited objects are being imported unnecessarily late.
> This will be corrected later.

This I have fixed.
This was a typo on my part...

**Comment by wing328** [comment]
@fa0311 thanks for the PR but the CI tests failed: https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/24934/workflows/5d9866ce-79a9-4974-822e-100372bde560/jobs/74478

Can you please take a look when you've time?

To run the petstore server locally, please refer to https://github.com/OpenAPITools/openapi-generator/wiki/Integration-Tests

**Comment by fa0311** [comment]
> thanks for the PR but the CI tests failed

The test is failing due to an existing bug.
https://github.com/OpenAPITools/openapi-generator/issues/16151

Current PythonNextgenPetstoreTests rarely work because they do not do circular import references.

**Comment by fa0311** [comment]
Merge #16208 and the test was successful!.

**Comment by wing328** [comment]
but the tests in CI stills failed: https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/24934/workflows/5d9866ce-79a9-4974-822e-100372bde560/jobs/74478
```
___________________ ERROR collecting tests/test_store_api.py ___________________
tests/test_store_api.py:16: in <module>
    import petstore_api
petstore_api/__init__.py:20: in <module>
    from petstore_api.api.another_fake_api import AnotherFakeApi
petstore_api/api/__init__.py:4: in <module>
    from petstore_api.api.another_fake_api import AnotherFakeApi
petstore_api/api/another_fake_api.py:24: in <module>
    from petstore_api.models.client import Client
petstore_api/models/__init__.py:31: in <module>
    from petstore_api.models.circular_reference_model import CircularReferenceModel
petstore_api/models/circular_reference_model.py:88: in <module>
    from petstore_api.models.first_ref import FirstRef
petstore_api/models/first_ref.py:88: in <module>
    from petstore_api.models.second_ref import SecondRef
petstore_api/models/second_ref.py:89: in <module>
    SecondRef.update_forward_refs()
pydantic/main.py:815: in pydantic.main.BaseModel.update_forward_refs
    ???
pydantic/typing.py:554: in pydantic.typing.update_model_forward_refs
    ???
pydantic/typing.py:520: in pydantic.typing.update_field_forward_refs
    ???
pydantic/typing.py:59: in pydantic.typing.evaluate_forwardref
    ???
/opt/circleci/.pyenv/versions/3.7.12/lib/python3.7/typing.py:467: in _evaluate
    eval(self.__forward_code__, globalns, localns),
<string>:1: in <module>
    ???
E   NameError: name 'Dict' is not defined
```

looks like some fundamental sytnax errors.

can you please take a look?

**Comment by fa0311** [comment]
> but the tests in CI stills failed

My explanation was insufficient.
We are currently failing CI testing due to several potential bugs.
For this to succeed, we need to fix #16151.

I have created #16208 which fixes #16151
I merged this fix in my environment and the test succeeded.

Can I review this pull request again after the review and merge of #16208 ?
Or do I need to merge #16208 into this pull request?

**Comment by wing328** [comment]
Thanks for the explanation. I've merged your PR https://github.com/OpenAPITools/openapi-generator/pull/16208

Please merge the latest master into your branch when you've time. 

Thank you.

**Comment by fa0311** [comment]
Successful test :)

**Comment by wing328** [comment]
@fa0311 nice. will run some tests later tonight.

**Comment by wing328** [comment]
Tested locally and the result is good. will add tests via another PR.

Thanks again for the PR. Have a nice weekend.

**Pull request merged**
