### PR TITLE
[haskell-http-client] Update haskell-http-client generator to Aeson 2.x

### PR DESCRIPTION
**Pull request by mrandri19**
Due to a [denial-of-service vulnerability](https://github.com/haskell/aeson/issues/864) of `aeson-1.x`, we would like to update to `aeson-2.x`.

This PR includes the 1-line change in `Core.hs` necessary to upgrade `aeson` to the new version.

If the PR points to the wrong branch, tell me and I will fix it.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@mrandri19 thanks for the PR. Can you please file the PR against the latest master (the upcoming v6.0.0 release) instead?

cc @jonschoning

**Comment by mrandri19** [comment]
> thanks for the PR. Can you please file the PR against the latest master (the upcoming v6.0.0 release) instead?

Thanks for anwering so fast! I have changed the base branch to `master`.

**Comment by wing328** [comment]
For the CircieCI failure, please merge the latest master into branch and it should fix it.

**Comment by wing328** [comment]
@jonschoning may I know if you've time to review this change? We will release v6.0.0 in late May and include this change if possible.

**Comment by jonschoning** [comment]
sure, will review in the next couple days

**Comment by mrandri19** [comment]
> For the CircieCI failure, please merge the latest master into branch and it should fix it.

I will re-merge it in a couple days, too

**Comment by jonschoning** [comment]
udpated in https://github.com/OpenAPITools/openapi-generator/pull/12309

**Pull request closed without merging**
