### PR TITLE
[php] Fix JSON object deserialization

### LINKED ISSUE #8394: [BUG][php] json_decode missing when response is object
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I call API via generated PHP client I got encoded json string instead of decoded object. Response looks like:
```php
["{\"foobar\":\"foobaz\"}"]
```

##### openapi-generator version

`5.0.0-beta`

##### OpenAPI declaration file content or url

```yml
paths: 
  '/objects/{id}':
    parameters:
      - name: id
        in: path
        required: true
    get:
      operationId: getSingleObjectById
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FreeFormObject'
components:
  schemas:
    FreeFormObject:
      type: object
```

##### Generation Details

```console
generate -i \"spec.yaml\" -g php -o \"api-client-sdk\"

```

##### Steps to reproduce

Send request via generated SDK to staged server `/objects/1` where response is correct JSON item. The response will be json encoded string instead of object.

##### Related issues/PRs

#6566 Seems close but not really. I'm ok with response as object instead of model. It's just `json_decode` execution missed.

##### Suggest a fix

```diff
diff --git a/modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache b/modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
index 58200ac713..42fd2658d1 100644
--- a/modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
+++ b/modules/openapi-generator/src/main/resources/php/ObjectSerializer.mustache
@@ -294,6 +294,7 @@ class ObjectSerializer
         }
 
         if ($class === 'object') {
+            $data = is_string($data) ? json_decode($data) : $data;
             settype($data, 'array');
             return $data;
         }
```
I don't know why `json_decode` executes based on string check and doesn't check `Content-Type` header but it's a quick fix.

### PR DESCRIPTION
**Pull request by ybelenko**
When I call API via generated PHP client I got encoded json string instead of decoded object. Response looks like:
```json
["{\"foobar\":\"foobaz\"}"]
```

**UPD: I've checked response HTTP headers and `Content-Type: application/json` has been set correctly.**

Closes #8394 

Circle-CI fail log:
```console
09:30:50.626 [qtp2074407503-11] INFO  i.s.sample.resource.PetStoreResource - placeOrder ID 0 STATUS placed
09:30:50.628 [qtp2074407503-14] INFO  i.s.sample.resource.UserResource - createUser ID 1000 STATUS gopher
09:30:50.630 [qtp2074407503-14] INFO  i.s.sample.resource.UserResource - createUsersWithArrayInput
09:30:50.636 [qtp2074407503-14] INFO  i.s.sample.resource.UserResource - updateUser ID 1000 STATUS gopher
09:31:13.284 [qtp2074407503-22] INFO  i.s.sample.resource.PetResource - addPet ID 1611135073268 STATUS available

Too long with no output (exceeded 10m0s): context deadline exceeded
```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @renepardon

### CODE REVIEW

**Comment by thomasphansen** [comment]
Hello @ybelenko,
We maintain a fork of openapi-generator for our internal use, and crossed with this problem before (I should have presented a push request, my bad - too much work in my side... :) )
This is the solution we found: instead of fixing it in the ObjectSerializer::deserialize() method, we adjust it in the api.mustache:

around line 222, responses section:
```
            {{#dataType}}
                {{^isWildcard}}case {{code}}:{{/isWildcard}}{{#isWildcard}}default:{{/isWildcard}}
                    if ('{{{dataType}}}' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                        if ('{{{dataType}}}' !== 'string') {     // HERE
                            $content = json_decode($content);    // HERE
                        }                                        // HERE
                    }
```
and then we do the same thing around line 241, and something similar in the Async method as well.

This works because json_decode() will convert '1.2' to (float)1.2, 'true' to (bool)true and, of course, a json string to an object/array. This way, the serializer will never receive encoded data, and everything works as it should! :)

I'd recommend this change over the suggested one: the deserialize() method is recursive, and this error can only happen when it is called from the API. Adding the fix to it will make it do unnecessary checks for every recursion, while we only need to guarantee that the first call receives valid data...

Cheers! :)

**Review by thomasphansen — CHANGES_REQUESTED** [review]
Thanks for the new push! :)
But you need to replicate this change also on lines 244 and 259 :)
Cheers! :)

**Comment by ybelenko** [comment]
> Thanks for the new push! :)
> But you need to replicate this change also on lines 244 and 259 :)
> Cheers! :)

Sorry, seems like I'm not following anymore(line 259). Please, push commit yourself or give me exact diff.

**Comment by thomasphansen** [comment]
My bad, @ybelenko, I gave you the wrong line ref! :)
Here is the diff:
```
diff --git a/modules/openapi-generator/src/main/resources/php/api.mustache b/modules/openapi-generator/src/main/resources/php/api.mustache
index ffa136a44a..aa1db956fc 100644
--- a/modules/openapi-generator/src/main/resources/php/api.mustache
+++ b/modules/openapi-generator/src/main/resources/php/api.mustache
@@ -240,6 +240,9 @@ use {{invokerPackage}}\ObjectSerializer;
                 $content = $response->getBody(); //stream goes to serializer
             } else {
                 $content = (string) $response->getBody();
+                if ($returnType !== 'string') {
+                    $content = json_decode($content);
+                }
             }
 
             return [
@@ -358,6 +361,10 @@ use {{invokerPackage}}\ObjectSerializer;
                         $content = $response->getBody(); //stream goes to serializer
                     } else {
                         $content = (string) $response->getBody();
+                        if ($returnType !== 'string') {
+                            $content = json_decode($content);
+                        }
+
                     }
 
                     return [
```
Cheers!

**Review by thomasphansen — APPROVED** [review]

**Comment by ybelenko** [comment]
@thomasphansen thanks for approve, but I guess we need to wait @wing328 since he showed interest in this bugfix.

**Comment by ybelenko** [comment]
@dkarlovi didn't you face that issue with PHP client? Maybe you can take a brief look if you have time.
PR is tiny, but we can't approve it for so long.

**Pull request merged**
