### PR TITLE
[JAXRS-spec] Filter swagger annotations for OpenAPI compatibility

### PR DESCRIPTION
**Pull request by michbeck100**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

The Microprofile OpenAPI specification allows to have just a static openapi.yaml file in the application module’s root `META-INF` folder (see [here](
https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#421-location-and-format)). So this PR adds an additional property "useSwaggerAnnotations" that doesn't generate the Swagger annotations if set to false (default value is true for backward compatibility). 

This way you can easily generate code that conforms to _contract first_ and is compliant with the [microprofile openapi specification](https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc)

### CODE REVIEW

**Comment by michbeck100** [comment]
I just ran `bin/jaxrs-spec-petstore-server.sh`, my fault. How can one know which scripts to run?

**Comment by jmini** [comment]
I once generated this table: https://github.com/OpenAPITools/openapi-generator/wiki/Samples-folder#scripts (might be outdated)

I have computed the list for your by looking at the Shippable error report.

If you have time (takes some minutes), you can also run `bin/utils/ensure-up-to-date` locally.

**Comment by michbeck100** [comment]
I had to fix some missing imports in efe7014. BTW: it seems that before 82eba8d this wan't working at all. And i don't really know what this is good for.

**Comment by jmini** [comment]
Thank you a lot for this contribution

**Comment by wing328** [comment]
@michbeck100 thanks for the enhancement, which is included in the v3.2.2 stable release: https://twitter.com/oas_generator/status/1032252335131512832

**Pull request merged**
