### PR TITLE
[C-libcurl] Support setting basePath and apiKeys when creating an apiClient

### PR DESCRIPTION
**Pull request by ityuhui**
After generating a C client,  user will use apiClient_create to create an apiClient to execute REST request operation.

But for now,  apiClient_create does not accept any parameter so apiClient cannot get any user setting. 
e.g.
```c
apiClient_t *apiClient_create() {
    curl_global_init(CURL_GLOBAL_ALL);
    apiClient_t *apiClient = malloc(sizeof(apiClient_t));
    apiClient->basePath = "http://localhost";
    apiClient->dataReceived = NULL;
    apiClient->response_code = 0;
    apiClient->apiKeys = NULL;

    return apiClient;
}
```

I updated the template code, let the apiClient_create can get user settings:
```c
apiClient_t *apiClient_create(const char *basePath
, list_t *apiKeys
) {
    curl_global_init(CURL_GLOBAL_ALL);
    apiClient_t *apiClient = malloc(sizeof(apiClient_t));
    if(basePath){
        apiClient->basePath = strdup(basePath);
    }else{
        apiClient->basePath = strdup("http://localhost");
    }
    apiClient->dataReceived = NULL;
    apiClient->response_code = 0;
    apiClient->apiKeys = apiKeys;

    return apiClient;
}
```

I also updated the header file and apiClient_free.

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [X] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [X] File the PR against the [master](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@wing328 @zhemant

### CODE REVIEW

**Comment by ityuhui** [comment]
I wonder whether I need remove 
```
    {{#isApiKey}}
    if(apiClient->apiKeys) {
        list_free(apiClient->apiKeys);
    }
    {{/isApiKey}}
```
in the function 
```
apiClient_free(apiClient_t *apiClient)
```
because apiClient->apiKeys is passed by the parameter apiKeys of apiClient_create.
Users should manage(new and delete) the memory of apiKeys themselves,  apiClient_free() should not free apiClient->apiKeys because apiClient_create does not allocate memory for apiClient->apiKeys.

This may cause double-free coredump if users free apiKeys after apiClient_free is called.

**Comment by zhemant** [comment]
Yes, a deep copy is okay, as the generated code will manage the memory. But then we should mention this that we are doing a deep copy and the user has to free the memory after the function call anytime. To avoid memory leaks if happens.

same goes for basepath.

**Comment by ityuhui** [comment]
Thanks @zhemant 

I will close this PR and create a new one to deliver "deep-copy"

**Comment by wing328** [comment]
Also what about creating a new method (e.g. *apiClient_create_with_base_path_and_apikeys()) to make it backward compatible?

**Comment by ityuhui** [comment]
@wing328 

It's a good idea to create a new function to keep compibitily.

I suggest the new funcation's name as "apiClient_create_with_base_path" because "list_t *apiKeys" is generated by the template code automatically. If there is no apiKeys in OpenAPI specification,  "list_t *apiKeys" does not exist in parameter list.

```c
apiClient_t *apiClient_create_with_base_path(const char *basePath
{{#hasAuthMethods}}
{{#authMethods}}
{{#isApiKey}}
, list_t *apiKeys
{{/isApiKey}}
{{/authMethods}}
{{/hasAuthMethods}}
) {
```

Actually I will have another PR that adds a new parameter "caPath" to apiClient_create to support  SSL/HTTPS.  I think the new function's name "apiClient_create_with_base_path_and_capath" is also OK.

**Comment by wing328** [comment]
> I suggest the new funcation's name as "apiClient_create_with_base_path" because "list_t *apiKeys" is generated by the template code automatically

sounds good to me 👍

**Pull request closed without merging**
