### PR TITLE
fix: ExampleGenerator correctly produces YYYY-MM-dd format for `date` with examples

### LINKED ISSUE #17494: [BUG] [ExampleGenerator] Generated examples from String type with `date` format are in the wrong format (extra T00:00:00.000+00:00)
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When providing an example to a type `string` property with format `date`, the generated example is in the wrong format.

__Current _(undesired)_ behavior:__

Consider the following schema:
```yaml
components:
  schemas:
    DateSchema:
      type: object
      properties:
        date_with_example:
          type: string
          format: date
          example: 2024-01-01
        date_without_example:
          type: string
          format: date
```

I'd expect the generated example to look like:

```json
{
  "date_with_example" : "2024-01-01",
  "date_without_example" : "2000-01-23"
}
```

However, it currently generates the following:
```json
{
  "date_with_example" : "2024-01-01T00:00:00.000+00:00",
  "date_without_example" : "2000-01-23"
}
```

*Note: the date without example refers to the current behavior in using a default predetermined value:*

https://github.com/OpenAPITools/openapi-generator/blob/a5d3fb4f601e4bced19f39cb6d82799a71531282/modules/openapi-generator/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java#L254C10-L255

__Why is this behavior happening?__

This issue is happening because how swagger-core is handling `DateSchema` classes.

As you can see, this PR tried to solve the issue directely in swagger-core: https://github.com/swagger-api/swagger-core/pull/4046

So what's happening is that the model for a date format resolves to a `DateSchema` which gets parsed as a `java.util.Date` and gets printed using it's `toString()` method.

image

##### openapi-generator version

master a5d3fb4f601e4bced19f39cb6d82799a71531282

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
paths:
  /generate_from_response_schema_with_date_format:
    get:
      operationId: generateFromResponseSchemaWithDateFormat
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DateSchema'
components:
  schemas:
    DateSchema:
      type: object
      properties:
        date_with_example:
          type: string
          format: date
          example: 2024-01-01
        date_without_example:
          type: string
          format: date
```

##### Generation Details

Running `ExampleGeneratorTest.java`

##### Steps to reproduce

Apply the following patch which adds the test case for example generation on date format.

```patch
Subject: [PATCH] Add failing test case to ExampleGenerator for date format
---
Index: modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml b/modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml
--- a/modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml	(revision a5d3fb4f601e4bced19f39cb6d82799a71531282)
+++ b/modules/openapi-generator/src/test/resources/3_0/example_generator_test.yaml	(date 1703871594752)
@@ -26,6 +26,16 @@
               schema:
                 type: string
                 example: primitive type example value
+  /generate_from_response_schema_with_date_format:
+    get:
+      operationId: generateFromResponseSchemaWithDateFormat
+      responses:
+        '200':
+          description: successful operation
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/DateSchema'
   /generate_from_response_schema_with_array_of_model:
     get:
       operationId: generateFromResponseSchemaWithArrayOfModel
@@ -63,6 +73,16 @@
                 $ref: '#/components/schemas/ExampleSchema'
 components:
   schemas:
+    DateSchema:
+      type: object
+      properties:
+        date_with_example:
+          type: string
+          format: date
+          example: 2024-01-01
+        date_without_example:
+          type: string
+          format: date
     StringSchema:
       type: string
       example: string schema example value
Index: modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java b/modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java
--- a/modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java	(revision a5d3fb4f601e4bced19f39cb6d82799a71531282)
+++ b/modules/openapi-generator/src/test/java/org/openapitools/codegen/ExampleGeneratorTest.java	(date 1703871597569)
@@ -39,6 +39,35 @@
         assertEquals("200", examples.get(0).get("statusCode"));
     }
 
+    @Test
+    public void generateFromResponseSchemaWithDateFormat() {
+        OpenAPI openAPI = TestUtils.parseFlattenSpec("src/test/resources/3_0/example_generator_test.yaml");
+
+        new InlineModelResolver().flatten(openAPI);
+
+        ExampleGenerator exampleGenerator = new ExampleGenerator(openAPI.getComponents().getSchemas(), openAPI);
+        Set<String> mediaTypeKeys = new TreeSet<>();
+        mediaTypeKeys.add("application/json");
+        List<Map<String, String>> examples = exampleGenerator.generateFromResponseSchema(
+                "200",
+                openAPI
+                        .getPaths()
+                        .get("/generate_from_response_schema_with_date_format")
+                        .getGet()
+                        .getResponses()
+                        .get("200")
+                        .getContent()
+                        .get("application/json")
+                        .getSchema(),
+                mediaTypeKeys
+        );
+
+        assertEquals(1, examples.size());
+        assertEquals("application/json", examples.get(0).get("contentType"));
+        assertEquals(String.format(Locale.ROOT, "{%n  \"date_with_example\" : \"2024-01-01\",%n  \"date_without_example\" : \"2000-01-23\"%n}"), examples.get(0).get("example"));
+        assertEquals("200", examples.get(0).get("statusCode"));
+    }
+
     @Test
     public void generateFromResponseSchemaWithNoExample() {
         OpenAPI openAPI = TestUtils.parseFlattenSpec("src/test/resources/3_0/example_generator_test.yaml");

```

##### Related issues/PRs

https://github.com/swagger-api/swagger-core/pull/4046
https://github.com/OpenAPITools/openapi-generator/issues/15342

### PR DESCRIPTION
**Pull request by acouvreur**
When an example was specified for a property with the `date` format, it's example would be generated to something like `2024-01-01T00:00:00.000+00:00` or `Sat Jan 30 01:00:00 CET 2021`.

It's because the resolved type for a Date example is a DateSchema, and a DateSchema uses `java.util.Date` to represents the Date. Which gets printed using .toString() not in the YYYY-MM-dd format.

Fixes #17494 #15342

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by acouvreur** [comment]
Hello @wing328, any chance you can review this one ? It does not target a particular language, so unfortunately, no one to mention.

**Comment by acouvreur** [comment]
Cc @OpenAPITools/generator-core-team

**Comment by acouvreur** [comment]
Any update with this fix @wing328 ? Would really appreciate this to be merged :)

**Comment by wing328** [comment]
looks good to me. will merge once all tests pass

cc @OpenAPITools/generator-core-team

**Pull request merged**
