### PR TITLE
[Spring] Fixed mustache template for FormParams.

### PR DESCRIPTION
**Pull request by ahrytsiuk**
Fixed mustache template for FormParams. Use paramName instead of baseName for variable name.
This will fix an issue when parameter name is one of the reserved keywords
For more details look into (#7506)

@bbdouglas @sreeshas @jfiala  @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by ahrytsiuk** [comment]
Hello @wing328 @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda by any chance, did you check this PR?

Any feedback is appreciated.

**Comment by wing328** [comment]
To resolve the CI failure, can you please merge the latest master of the official repo into your branch?

**Comment by ahrytsiuk** [comment]
Hello @wing328, I rebased my branch based on the latest master. Seems issue with CircleCI is resolveed

**Comment by ahrytsiuk** [comment]
Hello @wing328, any ETA when PR could be reviewed and merged?

**Comment by ahrytsiuk** [comment]
Hello @wing328 @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda any feedback?

**Comment by wing328** [comment]
@ahrytsiuk Can you please resolve the merge conflicts when you've time? I'll then review in the coming when I can find the time.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/11580

**Pull request closed without merging**
