### PR TITLE
[BUG][PYTHON] fix setup.py when no paths are specified

### PR DESCRIPTION
**Pull request by loic-seguin**
This PR is related to this issue https://github.com/OpenAPITools/openapi-generator/issues/20090.
Looping on {{#apis}} in the setup.mustache is not needed I think because we already have the infos at the root level.
As a consequence the setup method is always present if no paths attribute is given inside the yaml.

TODO : We might need to do this also for the generator python-pydantic-v1...

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
- Mentioning @cbornet @tomplus @krjakbrjak @fa0311 @multani

### CODE REVIEW

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/11824698634/job/32968636666?pr=20098n

thanks for the PR. please follow step 3 to update the samples

**Comment by loic-seguin** [comment]
> https://github.com/OpenAPITools/openapi-generator/actions/runs/11824698634/job/32968636666?pr=20098n
> 
> thanks for the PR. please follow step 3 to update the samples

Done ;)

**Comment by wing328** [comment]
/
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by loic-seguin** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

done

**Comment by wing328** [comment]
@loic-seguin can you please review the build failure when you've time?

**Comment by loic-seguin** [comment]
will do

**Comment by wing328** [comment]
trigger tests via https://github.com/OpenAPITools/openapi-generator/pull/20339 instead

let's see how that goes

**Comment by wing328** [comment]
all tests passed.

tested locally and found the following diff against the master:
```diff
diff --git a/setup.py b/setup.py
index 22a42d0..e56366b 100644
--- a/setup.py
+++ b/setup.py
@@ -23,27 +23,3 @@ from setuptools import setup, find_packages  # noqa: H301
 NAME = "openapi-client"
 VERSION = "1.0.0"
 PYTHON_REQUIRES = ">= 3.8"
-REQUIRES = [
-    "urllib3 >= 1.25.3, < 3.0.0",
-    "python-dateutil >= 2.8.2",
-    "pydantic >= 2",
-    "typing-extensions >= 4.7.1",
-]
-
-setup(
-    name=NAME,
-    version=VERSION,
-    description="Example Hello API",
-    author="OpenAPI Generator community",
-    author_email="team@openapitools.org",
-    url="",
-    keywords=["OpenAPI", "OpenAPI-Generator", "Example Hello API"],
-    install_requires=REQUIRES,
-    packages=find_packages(exclude=["test", "tests"]),
-    include_package_data=True,
-    long_description_content_type='text/markdown',
-    long_description="""\
-    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
-    """,  # noqa: E501
-    package_data={"openapi_client": ["py.typed"]},
-)
\ No newline at end of file

```

which confirms the fix

**Pull request merged**
