### PR TITLE
[PHP] Fix sending array of files with multipart/form-data in PHP template

### LINKED ISSUE #6217: [BUG][PHP] Array is not taken into account when content is multipart/form-data
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Array is not taken into account when content is multipart/form-data (PHP client). Exception is thrown:
```
Fatal error: Uncaught RuntimeException: Unable to open Array using mode rb: fopen() expects parameter 1 to be a valid path, array given
```

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```json

"requestBody" : {
  "content" : {
    "multipart/form-data" : {
      "schema" : {
        "properties" : {
          "files": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "binary"
            },
            "description": "A list of files containing the data to import"
          }
        }
      }
    }
  }
}
```

##### Command line used for generation

Generating `php` client with
```
java -jar openapi-generator-cli-4.3.1.jar -g php
```

### PR DESCRIPTION
**Pull request by atanasiuk-hubspot**
Fix #6217 

PHP Client Technical Committee:
- @jebentier 
- @dkarlovi 
- @mandrean 
- @jfastnacht
- @ackintosh
- @ybelenko 
- @renepardon

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by atanasiuk-hubspot** [comment]
Any updates on this?

**Comment by yfaktor** [comment]
any thoughts on merging this? Thanks

**Comment by wing328** [comment]
To resolve the merge conflicts, I've cherry-pick your commit and regenerate the samples via https://github.com/OpenAPITools/openapi-generator/pull/7067

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/7067. Thanks for the contribution.

**Pull request closed without merging**
