### PR TITLE
fix(typescript-axios): Correct the content type for a list of objects in form-data when contentType is present

### PR DESCRIPTION
**Pull request by Kavan72**
Cannot pass a data-type object as an array of items in a form using Axios. It works perfectly for a normal object, but it's not working as expected for a form.

```yaml
openapi: 3.0.3
info:
  title: Backend
  version: 1.0.0
paths:
  /company:
    put:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateCompanyDetails'
            encoding:
              industry:
                contentType: application/json
      responses:
        '204':
          description: The company data successfully updated

components:
  schemas:
    UpdateCompanyDetails:
      type: object
      properties:
        name:
          type: string
          description: the name of the company
        industry:
          type: array
          items:
            $ref: '#/components/schemas/Industry'
    Industry:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the industry
        name:
          type: string
          description: The name of the industry
```

Expected:
```
localVarFormParams.append('industry', new Blob([JSON.stringify(industry)], { type: 'application/json' }))
```

Received:
```
industry.forEach((element) => {
    localVarFormParams.append('industry', element as any);
})
```

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

[Fixes](https://github.com/OpenAPITools/openapi-generator/issues/16659).

@macjohnny

### CODE REVIEW

**Comment by Kavan72** [comment]
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov @davidgamero @mkusaka

**Comment by macjohnny** [comment]
can you please update the samples?

**Comment by Kavan72** [comment]
> can you please update the samples?

Sure

**Comment by macjohnny** [comment]
@Kavan72 please run 

```
./mvnw clean package 
./bin/generate-samples.sh ./bin/configs/*.yaml
./bin/utils/export_docs_generators.sh
```

and commit the changes

**Pull request merged**
