### PR TITLE
Add group parameters support in TypeScript Fetch

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- prototype to show group parameter support in TS fetch

TODO:
- update all method signature to support x-group-parameters
- update docstring about using group parameters

### CODE REVIEW

**Comment by wing328** [comment]
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)

**Comment by topce** [comment]
@wing328 I think there is compile error in generated code 
api.ts
on line 1541 function is declared 
as 
`deleteUser(methodParameters:` any = {}, options: any = {}): FetchArgs {
with two parameters
but in line 1807
`const localVarFetchArgs = UserApiFetchParamCreator(configuration).deleteUser(username, stringGroup, booleanGroup, int64Group, options);`
it is called with 5 paramters 
so TypeScript give compile time error 
I do not use Fetch but code is not compiling

**Comment by wing328** [comment]
@topce thanks for the review. You're right that the code won't compile as I've not updated all the method signature in the mustache templates to support the group parameters. Do the following method signature and unboxing of group parameter look good?
```typescript
         /**
         * This can only be done by the logged in user.
         * @summary Delete user
         * @param {string} username The name that needs to be deleted
         * @param {number} [stringGroup] String in group parameters
         * @param {boolean} [booleanGroup] Boolean in group parameters
         * @param {number} [int64Group] Integer in group parameters
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(methodParameters: any = {}, options: any = {}): FetchArgs {
            const username: string = methodParameters['username']
            const stringGroup: number = methodParameters['stringGroup']
            const booleanGroup: boolean = methodParameters['booleanGroup']
            const int64Group: number = methodParameters['int64Group']
            // verify required parameter 'username' is not null or undefined
            if (username === null || username === undefined) {
                throw new RequiredError('username','Required parameter username was null or undefined when calling deleteUser.');
            }
```

**Comment by topce** [comment]
@wing328 
It look good but it is problem when function is called 
it expect 2 params but it is provided 5
`const localVarFetchArgs = UserApiFetchParamCreator(configuration).deleteUser(username, stringGroup, booleanGroup, int64Group, options);`

if you call it like this `const localVarFetchArgs = UserApiFetchParamCreator(configuration).deleteUser({username, stringGroup, booleanGroup, int64Group}, options);`
it should compile 
but not sure if it will work 
this Fetch code look complicated little bit to me ;-)

**Comment by wing328** [comment]
@topce I've updated all method signature to support group parameters with a dictionary and a fake endpoint (will be removed later) to illustrate the change. Please have a look and let me know if you've any question/feedback.

**Comment by topce** [comment]
hi @wing328  there are still compile type errors
on line 2168 in api.ts
`return UserApiFp(this.configuration).patchUser(username, int64Group, stringGroup, booleanGroup, options)(this.fetch, this.basePath);`
you call function with 5 argument
but function is defined with 2 argument line 1923
actually in documentation of function   it looks OK 
but not in real parameters please see bellow
so probably generated function in line 1923 has wrong parameter list 
`/**
         * for testing x-group-parameters, will be removed later
         * @summary Delete user
         * Note: the input parameter is a dictionary with the keys listed as the parameter name below
         *
         * @param {string} username The name that needs to be deleted
         * @param {number} int64Group Integer in group parameters
         * @param {number} [stringGroup] String in group parameters
         * @param {boolean} [booleanGroup] Boolean in group parameters
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchUser(methodParameters: any = {}, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = UserApiFetchParamCreator(configuration).patchUser(methodParameters, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },`

**Comment by wing328** [comment]
@topce you're right. My bad. There's still one more function call that I missed and I've just pushed out a fix. Please have another look when you've time. Thanks.

**Comment by topce** [comment]
@wing328 
You are welcome it is compiling now ;-)

Regarding code generated 
I saw that it is used type any on lot of places 
that is not good because it hides  type information.
for example 
```
export interface GroupParameter {
    int64Group: number;
    stringGroup?: string;
    booleanGroup?: boolean
}
```
this could be generated for group parameter type instead using any 

I think typescript code generated could be more TypeScript idiomatic 
for example run-time checking bellow 
could be check by TypeScript during compile time 

```
// verify required parameter 'username' is not null or undefined
            if (username === null || username === undefined) {
                throw new RequiredError('username','Required parameter username was null or undefined when calling patchUser.');
            }
            // verify required parameter 'int64Group' is not null or undefined
            if (int64Group === null || int64Group === undefined) {
                throw new RequiredError('int64Group','Required parameter int64Group was null or undefined when calling patchUser.');
            }
```

those are just suggestion for improvement and probably breaking changes 
that could be address if some bigger TypeScript refactoring is done

To discuss with other technical committee members
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09)

**Comment by macjohnny** [comment]
@wing328 I think this is superseded by https://github.com/OpenAPITools/openapi-generator/pull/3351 and can be closed

**Comment by wing328** [comment]
@macjohnny yup #3351 provides the same functionality via an additional option. I'll see if I can convince the author to use `x-group-parameters` instead

**Pull request closed without merging**
