### PR TITLE
Add support to install openapi-generator via pip

### PR DESCRIPTION
**Pull request by arun-nalla**
openapi-generator can be installed via npm this is an attempt to make the same available via pip

Code Repo: https://github.com/slash-arun/openapi-generator-cli-pip
PYPI: https://pypi.org/project/openapigenerator/

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by slash-arun** [comment]
cc: @wing328

**Comment by wing328** [comment]
@slash-arun thanks for creating the pip installer.

As discussed, there are some enhancements we would like to make the installer and we're now hosting the project under https://github.com/OpenAPITools/openapi-generator-pip

**Comment by jimschubert** [comment]
Since this is now hosted in its own repo, can this be closed?

**Comment by wing328** [comment]
There are still some pending items. @arun-nalla has been very busy with many things these days so we will pick this up again next month.

**Comment by arun-nalla** [comment]
Will take this to completion this weekend

**Comment by jimschubert** [comment]
@arun-nalla since the other repo was created, can this PR be closed?

**Comment by arun-nalla** [comment]
Sure @jimschubert

**Pull request closed without merging**
