### PR TITLE
Microprofille client cxf multipart extesion

### PR DESCRIPTION
**Pull request by Ravisankar-Challa**
Fixes the issue no: 3 reported in the issue #6028

Microprofile client shouldn't be dependent in a particular library like CXF it should be generic.

### CODE REVIEW

**Comment by wing328** [comment]
@Ravisankar-Challa when you've time, can you please resolve the merge conflicts?

**Comment by Ravisankar-Challa** [comment]
@wing328 Merge conflict has been resolved.

**Comment by Ravisankar-Challa** [comment]
@wing328  I am closing this because eclipse microprofile didn't standardized the multipart form upload https://github.com/eclipse/microprofile-rest-client/issues/261. Will take a look once it has been finalized

**Comment by asterisk360-admin** [comment]
@Ravisankar-Challa any update about this problem.
In microprofile code we need delete the import import org.apache.cxf.jaxrs.ext.multipart.*; all the time.
Any help is apreciated.

**Comment by c-koell** [comment]
We have the same problem. In which version will it be fixed ?

**Comment by asterisk360-admin** [comment]
@c-koell we fix using the template structure. 
Hope this can help u:  github.com/asterisk360/client-generator

**Comment by Kiiv** [comment]
@Ravisankar-Challa @wing328 
Hi, I don't understand why this was closed without being merged. I think it would be more usable by disabling multipart by default until the microprofile specs standardize something, isn't it ?

**Pull request closed without merging**
