### PR TITLE
[PHP-Lumen] Lumen 5.6 support

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Cherry-picking https://github.com/OpenAPITools/openapi-generator/pull/114

Credits: @Lv-Yi 

I'll update the samples tomorrow and do some tests.

### CODE REVIEW

**Comment by jimschubert** [comment]
I've added WIP label

**Comment by ackintosh** [comment]
I'll review this PR later today. 👀

**Comment by ackintosh** [comment]
Ran the sample locally and saw a following error:

```bash
$ php artisan serve

In web.php line 77:

  syntax error, unexpected '*', expecting end of file
```

web.php line 77 -> https://github.com/OpenAPITools/openapi-generator/pull/212/files#diff-e19e515da10035a7c599677e0774c708R77

It caused by `Output-Formats: [*/*]` in doc comment as `*/` means end of comment. 🤔

**Comment by ackintosh** [comment]
The error occurs also in latest master.

```
git:(master*) $ php -l samples/server/petstore/php-lumen/lib/app/Http/routes.php

Parse error: syntax error, unexpected '*', expecting end of file in samples/server/petstore/php-lumen/lib/app/Http/routes.php on line 77
Errors parsing samples/server/petstore/php-lumen/lib/app/Http/routes.php
```

**Comment by wing328** [comment]
@ackintosh thanks for testing it.

I would suggest a quick fix by removing that line for the time being to make the output functional first and then we'll deal with it later with escaping or other approaches.

**Comment by ackintosh** [comment]
@wing328 Totally agree with you. I'll work for the quick fix on master branch later.

**Comment by wing328** [comment]
@ackintosh I've just removed Output-Format from route.mustache and update the samples. Please pull the latest and run another test to see if the output looks good from your perspective.

**Comment by ackintosh** [comment]
@wing328 I've added some commits and now the samples seems work fine.

**Comment by ackintosh** [comment]
I've changed the base branch as this PR includes breaking changes.

**Comment by Lv-Yi** [comment]
just fyi. in pr#343 I'm trying to add back output format by skip * / injection.

**Pull request merged**
