### PR TITLE
Jaxrs jersey3 server

### PR DESCRIPTION
**Pull request by CDerksen**
Dear all,
as the name indicates, these are adjustments to generate server stubs for JAX-RS Jersey3 and OpenApi 3.x.

Esspecially, with the changes to OpenApi 3.x I would be glad, if somebody could have a closer look to the annotations produced, or to name some further test cases to be used for the last improvments.
For example: The api template (see ./modules/openapi-generator/src/main/resources/JavaJaxRS/libraries/jersey3/api.mustache) contains #implicitHeadersParams (ApiImplicitParams) from Swagger1. They were not used during my tests and I was not sure what to do with them (I commented this part out with my last commit).

- this PR is related to the branch and PR 'jaxrs-jersey3' from May 2022 that was not improved anymore and (most likely) might be closed. [see jaxrs-jersey3](https://github.com/OpenAPITools/openapi-generator/tree/jaxrs-jersey3)
- this PR substitutes my former pull request, where I unluckily produced rebase/merge conflicts [see Jax-RS Jersey3 Server](https://github.com/OpenAPITools/openapi-generator/pull/16317)

Overall, I hope this is a useful addition.

Best wishes,
Christian

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
@wing328, @bbdouglas, @sreeshas, @jfiala, lukoyanov, @cbornet, @jeff9finger , @karismann, @Zomzog, @lwlee2608, @martin-mfg

### CODE REVIEW

**Comment by wing328** [comment]
CI tests failed: https://github.com/OpenAPITools/openapi-generator/actions/runs/5880152735/job/16032608601?pr=16335

can you please take a look when you've time?

**Comment by CDerksen** [comment]
I think (hope), it's done now.
Sometimes one has to ask a question loudly to find the answer by itself ... ;-)

**Comment by CDerksen** [comment]
Having a look at the current test failure, I have no idea what went wrong. Is that really related to my changes?

[ERROR] Test mechanism :: null
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project scala-akka-petstore-client: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/scala-akka/target/surefire-reports for the individual test results.
[ERROR] ...

**Comment by wing328** [comment]
Can you please add `./bin/configs/jaxrs-jersey-jersey3.yaml ` with the following?

```
generatorName: jaxrs-jersey
outputDir: samples/server/petstore/jaxrs/jersey3
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
templateDir: modules/openapi-generator/src/main/resources/JavaJaxRS
library: jersey3
additionalProperties:
  artifactId: jaxrs-jersey3-petstore-server
  hideGenerationTimestamp: "true"
  serverPort: "8082"
```

and commit the new samples.

I tested with the sample but got the following errors:

```
[ERROR] /Users/williamcheng/Code/openapi-generator7/samples/server/petstore/jaxrs/jersey3/src/gen/java/org/openapitools/api/FakeApi.java:[389,1243] cannot find symbol
[ERROR]   symbol:   method defaultValue()
[ERROR]   location: @interface io.swagger.v3.oas.annotations.Parameter
[ERROR] /Users/williamcheng/Code/openapi-generator7/samples/server/petstore/jaxrs/jersey3/src/gen/java/org/openapitools/api/FakeApi.java:[389,1414] cannot find symbol
[ERROR]   symbol:   method allowableValues()
[ERROR]   location: @interface io.swagger.v3.oas.annotations.Parameter
[ERROR] /Users/williamcheng/Code/openapi-generator7/samples/server/petstore/jaxrs/jersey3/src/gen/java/org/openapitools/api/FakeApi.java:[389,1451] cannot find symbol
[ERROR]   symbol:   method defaultValue()
[ERROR]   location: @interface io.swagger.v3.oas.annotations.Parameter
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Can you please take a look when you've time?

**Comment by wing328** [comment]
FYI. I updated the samples and ran `mvn clean package` but got 
```
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[HINT] Cannot create new registration for component type class org.glassfish.jersey.media.multipart.MultiPartFeature: Existing previous registration found for the type.; source='null', [FATAL] A HTTP GET method, public jakarta.ws.rs.core.Response org.openapitools.api.FakeApi.testJsonFormData(java.lang.String,java.lang.String,jakarta.ws.rs.core.SecurityContext) throws org.openapitools.api.NotFoundException, should not consume any form parameter.; source='ResourceMethod{httpMethod=GET, consumedTypes=[application/x-www-form-urlencoded], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class org.openapitools.api.FakeApi, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@5c17a97e]}, definitionMethod=public jakarta.ws.rs.core.Response org.openapitools.api.FakeApi.testJsonFormData(java.lang.String,java.lang.String,jakarta.ws.rs.core.SecurityContext) throws org.openapitools.api.NotFoundException, parameters=[Parameter [type=class java.lang.String, source=param, defaultValue=null], Parameter [type=class java.lang.String, source=param2, defaultValue=null], Parameter [type=interface jakarta.ws.rs.core.SecurityContext, source=null, defaultValue=null]], responseType=class jakarta.ws.rs.core.Response}, nameBindings=[]}', [FATAL] No injection source found for a parameter of type public jakarta.ws.rs.core.Response org.openapitools.api.FakeApi.testQueryParameterCollectionFormat(java.util.List,java.util.List,java.util.List,java.util.List,java.util.List,java.lang.String,java.util.Map,jakarta.ws.rs.core.SecurityContext) throws org.openapitools.api.NotFoundException at index 6.; source='ResourceMethod{httpMethod=PUT, consumedTypes=[], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class org.openapitools.api.FakeApi, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@5fbe4ad3]}, definitionMethod=public jakarta.ws.rs.core.Response org.openapitools.api.FakeApi.testQueryParameterCollectionFormat(java.util.List,java.util.List,java.util.List,java.util.List,java.util.List,java.lang.String,java.util.Map,jakarta.ws.rs.core.SecurityContext) throws org.openapitools.api.NotFoundException, parameters=[Parameter [type=interface java.util.List, source=pipe, defaultValue=null], Parameter [type=interface java.util.List, source=ioutil, defaultValue=null], Parameter [type=interface java.util.List, source=http, defaultValue=null], Parameter [type=interface java.util.List, source=url, defaultValue=null], Parameter [type=interface java.util.List, source=context, defaultValue=null], Parameter [type=class java.lang.String, source=allowEmpty, defaultValue=null], Parameter [type=interface java.util.Map, source=language, defaultValue=null], Parameter [type=interface jakarta.ws.rs.core.SecurityContext, source=null, defaultValue=null]], responseType=class jakarta.ws.rs.core.Response}, nameBindings=[]}', [FATAL] A HTTP GET method, public jakarta.ws.rs.core.Response org.openapitools.api.FakeApi.testEnumParameters(java.util.List,java.lang.String,java.util.List,java.lang.String,java.lang.Integer,java.lang.Double,java.util.List,java.util.List,java.lang.String,jakarta.ws.rs.core.SecurityContext) throws org.openapitools.api.NotFoundException, should not consume any form parameter.; source='ResourceMethod{httpMethod=GET, consumedTypes=[application/x-www-form-urlencoded], producedTypes=[], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class org.openapitools.api.FakeApi, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@5fc2520c]}, definitionMethod=public jakarta.ws.rs.core.Response org.openapitools.api.FakeApi.testEnumParameters(java.util.List,java.lang.String,java.util.List,java.lang.String,java.lang.Integer,java.lang.Double,java.util.List,java.util.List,java.lang.String,jakarta.ws.rs.core.SecurityContext) throws org.openapitools.api.NotFoundException, parameters=[Parameter [type=interface java.util.List, source=enum_header_string_array, defaultValue=null], Parameter [type=class java.lang.String, source=enum_header_string, defaultValue=null], Parameter [type=interface java.util.List, source=enum_query_string_array, defaultValue=null], Parameter [type=class java.lang.String, source=enum_query_string, defaultValue=-efg], Parameter [type=class java.lang.Integer, source=enum_query_integer, defaultValue=null], Parameter [type=class java.lang.Double, source=enum_query_double, defaultValue=null], Parameter [type=interface java.util.List, source=enum_query_model_array, defaultValue=null], Parameter [type=interface java.util.List, source=enum_form_string_array, defaultValue=$], Parameter [type=class java.lang.String, source=enum_form_string, defaultValue=-efg], Parameter [type=interface jakarta.ws.rs.core.SecurityContext, source=null, defaultValue=null]], responseType=class jakarta.ws.rs.core.Response}, nameBindings=[]}']
    at org.glassfish.jersey.server.ApplicationHandler.initialize (ApplicationHandler.java:388)
    at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1 (ApplicationHandler.java:310)
    at org.glassfish.jersey.internal.Errors.process (Errors.java:292)
    at org.glassfish.jersey.internal.Errors.process (Errors.java:274)

```

**Comment by wing328** [comment]
> Within a mustache file, is there a way to determine a case for Objects like Map<String, String>?

Have you tried `isMap`?

For a list of mustache tags, please enable debugOperations. e.g.
```
./bin/generate-samples.sh ./bin/configs/jaxrs-jersey-jersey2.yaml -- --global-property debugOperations=true
```

**Comment by CDerksen** [comment]
Thanks for the helpful hints.

**Comment by CDerksen** [comment]
Is there something further I can do?

**Comment by wing328** [comment]
tested locally and the tests passed: 
```
[INFO] Started ServerConnector@3c88b82b{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
[INFO] Started Server@333674ad{STARTING}[11.0.15,sto=0] @18883ms
[INFO] 
[INFO] --- maven-failsafe-plugin:2.6:integration-test (default) @ jaxrs-jersey3-petstore-server ---
[WARNING] No test data will be captured by the Gradle Enterprise Maven Extension for 'maven-failsafe-plugin @ jaxrs-jersey3-petstore-server'. Use 'maven-failsafe-plugin' version 2.15 or higher.
[INFO] No tests to run.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.800 s
[INFO] Finished at: 2023-09-27T18:14:21+08:00
[INFO] ------------------------------------------------------------------------
[INFO] 9 goals, 9 executed
[INFO] 
[INFO] Publishing build scan...
[INFO] https://ge.openapi-generator.tech/s/jzmh73hqaxvdy
```

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/16676 with updated samples, docs and resolved merge conflicts. Let's see if all the tests pass

**Pull request closed without merging**
