### PR TITLE
[Fix #3052] Add support for optional query parameters

### LINKED ISSUE #3052: [BUG][Rust] Optional query parameters are always sent
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating a Rust client with the Reqwest library, optional query parameters are not generated as `Option<T>` and are always sent in the request. 
This is an issue for APIs which treat an empty string differently from presence of field. 

##### openapi-generator version

4.0.0

##### OpenAPI declaration file content or url

```yaml
---
openapi: 3.0.0
info:
  title: Bug Example
  version: 1.0.0
paths:
  /users:
    get:
      parameters:
        - in: query
          name: given_name
          schema:
            type: string
        - in: query
          name: family_name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
```

##### Command line used for generation

```sh
openapi-generator generate -g rust -i openapi.yaml --library reqwest -o actual/
```

##### Expected Output 

```rust
impl DefaultApi for DefaultApiClient {
    fn users_get(&self, family_name: &str, given_name: Option<&str>) -> Result<Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/users", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = given_name {
            req_builder = req_builder.query(&[("given_name", &s.to_string())]);
        }
        req_builder = req_builder.query(&[("family_name", &family_name.to_string())]);
```

##### Actual Output

```rust
impl DefaultApi for DefaultApiClient {
    fn users_get(&self, family_name: &str, given_name: &str) -> Result<Value, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/users", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("given_name", &given_name.to_string())]);
        req_builder = req_builder.query(&[("family_name", &family_name.to_string())]);
```

##### Suggest a fix

#3053

### PR DESCRIPTION
**Pull request by jonahgeorge**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Addresses #3052. 

This adds a new feature flag for the two Rust clients named `generateOptionQueryParams` which when enabled wraps any non-required query parameters in `Option<T>` and does not add them to the request if `None`.

@frol @farcaller @bjgill

### CODE REVIEW

**Comment by jonahgeorge** [comment]
```
    fn update_pet_with_form(&self, pet_id: i64, name: Option<&str>, status: Option<&str>) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/pet/{petId}", configuration.base_path, petId=pet_id);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.oauth_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        let mut form_params = std::collections::HashMap::new();
        form_params.insert("name", name.to_string());
        form_params.insert("status", status.to_string());
        req_builder = req_builder.form(&form_params);
```
Doing some more testing, it looks like this has issues due to the Option on the form parameters. Curious if anyone has input on a better way to address this: seems like I could either add the same changes to the form parameters as well or break the operation parameters into queryParams and formParams.

**Comment by bcourtine** [comment]
Hi @jonahgeorge,

IMO, this PR is a must have. I already forked it for one of my projects and it gave expected results.
Thanks a lot.

I think you forgot to regenerate and commit Rust samples (`./bin/rust.sh` and `./bin/rust-reqwest.sh`), which explain the CI failure for your PR.

**Comment by wing328** [comment]
@jonahgeorge thanks for the PR.

Instead of introducing a new option, what about using `nullable` instead? We've done that in some other clients, e.g. https://github.com/OpenAPITools/openapi-generator/blob/034064be4cba2de290877640cc097d88dba3b4eb/modules/openapi-generator/src/main/resources/ruby-client/api.mustache#L46-L62

**Comment by jonahgeorge** [comment]
@wing328 Agree that using `nullable` is a better approach. I wasn't aware that variable is exposed to the templates (besides looking at other languages, is there an easy way to see what is passed in?). 

Also, wouldn't it still be considered a breaking change to make `nullable=true` fields use `Option<T>` if they aren't right now and require a feature flag?

**Comment by wing328** [comment]
> Agree that using nullable is a better approach. I wasn't aware that variable is exposed to the templates (besides looking at other languages, is there an easy way to see what is passed in?).

You can use `-DdebugOperations`, which will show its value (boolean)

> Also, wouldn't it still be considered a breaking change to make nullable=true fields use Option<T> if they aren't right now and require a feature flag?

To me, it's more like correcting the behavior. For other languages/generators, we do not consider it as a breaking change but of course, I like your suggestion to give a proper heads-up to the user and how they can use 'nullable` (OAS3) or `x-nullable` (OAS2) to control the behavior.

**Comment by bcourtine** [comment]
Any news for this PR?

If nobody is working on it anymore, I can try to fix it…

**Comment by wing328** [comment]
@bcourtine please kindly go ahead. What about merging it into a branch (in this project) so that more people can work on it?

**Comment by jonahgeorge** [comment]
Sorry for the radio silence, I haven't had time to polish this up. 
@bcourtine if you want to take it over, go for it

**Comment by jonahgeorge** [comment]
Sorry for the radio silence, I haven't had time to polish this up. 
@bcourtine if you want to take it over, go for it

**Comment by bcourtine** [comment]
Hello @wing328 @jonahgeorge

I completed this PR and proposed a new one here: https://github.com/OpenAPITools/openapi-generator/pull/4016

IMO, it should be mergeable (hyper/reqwest sample code compiles without error).

**Comment by bcourtine** [comment]
PR #4016 (which includes and completes this one) has been merged. So this PR can be closed.

**Pull request closed without merging**
