### PR TITLE
Cpp restbed server improvements

### PR DESCRIPTION
**Pull request by LukasWoodtli**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.1.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Fix errors and add missing parts for the C++ restbed generator.
The generated code is not completely backwards compatible.

Please review (C++):
@ravinikam
@stkrwork
@etherealjoy
@martindelille
@muttleyxd

### CODE REVIEW

**Comment by wing328** [comment]
> The generated code is not completely backwards compatible.

Thanks for the heads-up. Given that 7.0.0 will be released in 2023. What about merging the change into current master (6.1.0) and if users prefer the old generator for backward compatibility, we'll create `cpp-restbed-server-deprecated` and remove it in 7.0.0 release in the future (we've adopted this approach in some other generators so as to allow faster enhancements without worrying too much about backward compatibility)

**Comment by wing328** [comment]
@LukasWoodtli can you please try to resolve the merge conflicts and we'll try to get this into the latest master (v6.1.0)?

**Comment by LukasWoodtli** [comment]
I‘ll have a look at it asap. Unfortunately my current resources to work on this are limited.

**Comment by wing328** [comment]
Tested in a linux box and all tests passed 👍

**Comment by Stokestack** [comment]
Is there documentation about using the generated code somewhere? I'm having a hard time even getting started. For example, one of my resources returns a string array. The generated code says:

```
    virtual std::pair<int, std::vector<std::string>> handler_GET(
        );
```

What is the **int** for in that pair?

Thanks for any insight.

**Comment by LukasWoodtli** [comment]
> Is there documentation about using the generated code somewhere? I'm having a hard time even getting started. For example, one of my resources returns a list of strings. The generated code says:
> 
> ```
>     virtual std::pair<int, std::vector<std::string>> handler_GET(
>         );
> ```
> 
> What is the **int** for in that pair?
> 
> Thanks for any insight.

Unfortunately there is no thorough documentation.

Did you consult the generated README file? Also have a look at the generated code. It might give you some insights.

The **int** in the returned pair is the HTTP status.

Eventually I might write a small tutorial about how to use the generated code. But currently my time to work on this project is quite limited.

My suggestion is to just try it out. Experiment with the generated code and run some request against it.

**Comment by Stokestack** [comment]
Thanks for taking the time to answer, Lukas. That snippet above is from the generated code.

**Pull request merged**
