### PR TITLE
Support multiple api keys in python example documentation

### PR DESCRIPTION
**Pull request by nmuesch**
Recent PRs to clean up the python example documentation looks to have removed support for multiple "api_keys" used for authentication. Without this PR, the last "api_key" in the schema will override any previous keys. 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Review by jirikuncar — APPROVED** [review]

**Comment by nmuesch** [comment]
Tagging technical committee 

@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)

**Comment by spacether** [comment]
> Recent PRs to clean up the python example documentation looks to have removed support for multiple "api_keys" used for authentication. Without this PR, the last "api_key" in the schema will override any previous keys.

This is a documentation update only, right?
Do we need to make any changes to python-experimental templates?
I only see the base python template being updated.

**Comment by nmuesch** [comment]
@spacether Yeah this should just impact documentation, the configuration itself already looks to work with multiple keys.
Python-experimental I believe is using this same partial file - https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/python-experimental/api_doc_example.mustache#L9 so this should be the only needed update.

**Comment by spacether** [comment]
Closing and re-opening to kick off CI tests again. The CI failure was unrelated and I am unable to restart it.
If we hit the same failure again I will ignore it.

**Review by spacether — APPROVED** [review]
Thank you for the PR! This looks good to me!

**Pull request merged**
