### PR TITLE
Sync master to 5.0.x 

### PR DESCRIPTION
**Pull request by wing328**
Merge conflicts (partial):
```
        both modified:   modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java
        both modified:   modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
        deleted by us:   modules/openapi-generator/src/main/resources/csharp-netcore/Project.mustache
        deleted by us:   modules/openapi-generator/src/main/resources/csharp-netcore/project.json.mustache
        deleted by us:   modules/openapi-generator/src/main/resources/elm/api.mustache
        deleted by us:   modules/openapi-generator/src/main/resources/elm/api018.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/customTypeDecoder.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/customTypeEncoder.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/model.mustache
        deleted by us:   modules/openapi-generator/src/main/resources/elm/modelTypeArray.mustache
        deleted by us:   modules/openapi-generator/src/main/resources/elm/modelTypePrimitive.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/recordFieldValueDecoder.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/recordFieldValueEncoder.mustache
        both modified:   modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache
        both modified:   modules/openapi-generator/src/main/resources/rust-server/models.mustache
        both modified:   modules/openapi-generator/src/main/resources/rust-server/server-mod.mustache
```

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/5968/commits/8fa76843d08cb981d8856d44797822654fc5599f resolve the merge conflicts for the following files:
```
modules/openapi-generator-cli/pom.xml
modules/openapi-generator-core/pom.xml
modules/openapi-generator-gradle-plugin/gradle.properties
modules/openapi-generator-gradle-plugin/pom.xml
modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml
modules/openapi-generator-maven-plugin/pom.xml
modules/openapi-generator-online/pom.xml
modules/openapi-generator/pom.xml
modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java
```

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/5968/commits/1574250fc6d5c0b462b16b7045c66cdf226948ad resolves merge conflicts in pom.xml

**Comment by wing328** [comment]
@eriktim when you've time, I wonder if you can help resolve the following merge conflicts when syncing master to 5.0.x branch:
```
        deleted by us:   modules/openapi-generator/src/main/resources/elm/api.mustache
        deleted by us:   modules/openapi-generator/src/main/resources/elm/api018.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/customTypeDecoder.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/customTypeEncoder.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/model.mustache
        deleted by us:   modules/openapi-generator/src/main/resources/elm/modelTypeArray.mustache
        deleted by us:   modules/openapi-generator/src/main/resources/elm/modelTypePrimitive.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/recordFieldValueDecoder.mustache
        both modified:   modules/openapi-generator/src/main/resources/elm/recordFieldValueEncoder.mustache
```

**Comment by wing328** [comment]
@richardwhiuk when you've time, I wonder if you can help resolve the following merge conflicts when syncing master to 5.0.x branch:
```
        both modified:   modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java
        both modified:   modules/openapi-generator/src/main/resources/rust-server/client-mod.mustache
        both modified:   modules/openapi-generator/src/main/resources/rust-server/models.mustache
        both modified:   modules/openapi-generator/src/main/resources/rust-server/server-mod.mustache
```

(search for `<<<` to identify the merge conflicts)

**Comment by eriktim** [comment]
@wing328 for Elm please pick all versions of the 5.0.x branch. I can also push a commit if you prefer that.

**Comment by wing328** [comment]
@eriktim please go ahead to update this branch `5.0-sync-master` directly.

**Comment by eriktim** [comment]
@wing328 I've pushed the required changes. However, due to the Rust conflicts I could not test it properly. It _should_ be fine, but please let me know if you run into issues later.

**Comment by wing328** [comment]
Thanks @eriktim 👍

**Comment by richardwhiuk** [comment]
@wing328 Yep, I'll pick up sorting out the merge conflicts - there is a fair few to get through.

**Comment by richardwhiuk** [comment]
@wing328 I've fixed up the Rust failures and regenerated the rust server samples. Looks like all the other samples need updating as well - I'll leave that to you.

**Comment by wing328** [comment]
@richardwhiuk thanks. Let me take care of that.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/6006 as there seems to be in issue triggering build in CircleCI.

**Comment by wing328** [comment]
Sorry. pressed the wrong button. Reverted the change (90dd7a0 )

**Pull request merged**
