### PR TITLE
[Java] enum space value must not be generated as underscore

### LINKED ISSUE #9607: [BUG][JAVA] Single-Space String in enum produces invalid identifier in Java 9+
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am using the `openapi-generator-maven-plugin` with a Java 14 project.  It seems that in versions of Java later than 9, a single underscore is no longer a valid identifier.  I was trying to generate classes for an API that uses enums where one of the possible values is a single space.

```json
"audio_quality": {
  "type": "string",
  "description": "Audio quality of the participant.",
  "enum": [
    " ",
    "good",
    "fair",
    "poor",
    "bad"
  ]
}
```

The Java code that is generated cannot be compiled because of that first enum value `_(" ")`.

```java
public enum AudioQualityEnum {
    _(" "),
    
    GOOD("good"),
    
    FAIR("fair"),
    
    POOR("poor"),
    
    BAD("bad");

    private String value;

    AudioQualityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AudioQualityEnum fromValue(String value) {
      for (AudioQualityEnum b : AudioQualityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
```

##### openapi-generator version

5.1.0

##### OpenAPI declaration file content or URL

Here is a minimal reproducible example.

https://gist.github.com/aelfric/9e039e971552be774b60a930818a118d

##### Generation Details
 I was using the Maven plugin with this configuration:

```xml
        <plugin>
            <groupId>org.openapitools</groupId>
            <artifactId>openapi-generator-maven-plugin</artifactId>
            <!-- RELEASE_VERSION -->
            <version>5.1.0</version>
            <!-- /RELEASE_VERSION -->
            <executions>
                <execution>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                    <configuration>
                        <inputSpec>${project.basedir}/src/main/resources/minimal.json</inputSpec>
                        <generatorName>java</generatorName>
                        <library>native</library>
                        <configOptions>
                            <sourceFolder>src/gen/java/main</sourceFolder>
                        </configOptions>
                        <skipValidateSpec>true</skipValidateSpec>
                    </configuration>
                </execution>
            </executions>
        </plugin>

```

##### Steps to reproduce

Run 
```
mvn compile
```

##### Suggest a fix

I'm not sure what the best solution is - maybe enums of this type should be named `_BLANK`.

### PR DESCRIPTION
**Pull request by svenmeier**
as this is invalid in Java 9

this closes #9607

I tried to add ' '->'SPACE' to specialCharReplacements, but regretfully the Kotlin generator uses these differently, i.e. all occurences in names are replaced.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by svenmeier** [comment]
Thanks @wing328, I've mixed up my accounts. I fixed the commits with my Github account.

**Comment by anujtewari** [comment]
Hi @wing328 , can you please review and merge the PR. We are also facing the same problem and unfortunately there is no workaround yet

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/13136

**Comment by wing328** [comment]
There's a better fix in default codegen. I'll file another PR to do that.

**Pull request closed without merging**
