### PR TITLE
Remove appendRequestToHandler

### PR DESCRIPTION
**Pull request by Rugal**
The original thought was to make generator able to add `ServerHttpRequest`, but turns out using templating way to do customization is much more easier than adding parameter, plus my previous change is not so well and not very useful

The original 2 PR are listed here, I would like to revert all my changes

1. https://github.com/OpenAPITools/openapi-generator/pull/17623
2. https://github.com/OpenAPITools/openapi-generator/pull/17158

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@wing328 @jimschubert

### CODE REVIEW

**Comment by wing328** [comment]
cc 
@dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)

**Comment by wing328** [comment]
no problem @Rugal 

thanks for the contributions.

look forward to more contributions from you.

**Comment by querwurzel** [comment]
@Rugal Can you elaborate on why exactly this isn't useful and what better alternative there is? 
I would even argue that the response object is also required in some cases.

**Comment by Rugal** [comment]
> @Rugal Can you elaborate on why exactly this isn't useful and what better alternative there is? I would even argue that the response object is also required in some cases.
> 
> Background: This change was released with 7.9.0 and now obviously breaks builds.

Response object is not enough, we need the exchange object in order to get both request and response information. To do that, simply updating the template in your configuration should work already, no need to have extra option to generate that response object solely.  

Please refer to the official site for `templating` related stuffs. It is super easy to understand and use.

**Comment by querwurzel** [comment]
> > @Rugal Can you elaborate on why exactly this isn't useful and what better alternative there is? I would even argue that the response object is also required in some cases.
> > Background: This change was released with 7.9.0 and now obviously breaks builds.
> 
> Response object is not enough, we need the exchange object in order to get both request and response information. To do that, simply updating the template in your configuration should work already, no need to have extra option to generate that response object solely.
> 
> Please refer to the official site for `templating` related stuffs. It is super easy to understand and use.

Thank you for the explanation, I will take a look into the templating section.
Im aware the exchange object refers to both req/resp and I'd like to have an option that injects it into all controller methods.

Shipping this breaking change with a minor version update is against all expectations, be it OSS or not.

**Pull request merged**
