### PR TITLE
Allow specifying/overriding the parent in the pom file for Java and S…

### PR DESCRIPTION
**Pull request by mwoodland**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
Add support for overriding/specifying the parent in the generated pom file.
issue #1131 

The run-all-petstore.cmd command did't work as some of the scripts it calls are looking for jars in swagger-codegen-cli directory - hence why I haven't checked "ran the schell script" above.

I have checked using the Spring generator while specifying none of the parent properties, all of them and one of them.

@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

### CODE REVIEW

**Comment by cbornet** [comment]
I'm not sure about the value of adding 3 more fields just to add 3 lines in a pom...

**Comment by mwoodland** [comment]
> I'm not sure about the value of adding 3 more fields just to add 3 lines in a pom...

I'm not sure how other people use the generator, but I'm using it to generate a module that the rest of my project then depends on. I'm running the generator to create the module from scratch as part of every build (so that the latest changes to the OpenAPI spec files are applied every time).

After the module is generated, we don't want to have to make any changes to that module, we just want to have implemented the interfaces that are defined in the generated module in a separate module.

Currently it sort of works having the parent define the child project as a module, but the parent not specified in the child pom. But to avoid breaking some of my builds I have to specify the modules in a specific order so that the generated module is not processed first.

**Comment by mwoodland** [comment]
Any updates on whether this pull request will be accepted? Or if there's anything else you'd like me to do?

**Comment by mwoodland** [comment]
I've done exactly that but figured I wouldn't be the only person who would want this functionality and as it's unintrusive change I thought I might as well submit a pull request. As a plus side it also means I wouldn't have to merge any changes to the template whenever I start using a new version of the generator.

**Comment by wing328** [comment]
@mwoodland as discussed, please consider using `-t` moving forward as we want to avoid adding too many options to generators.

**Comment by wing328** [comment]
I've restarted the Travis build and will merge this PR into master once the build passes.

**Pull request merged**
