### PR TITLE
[Java][Spring] Bean validation for Optional<>

### LINKED ISSUE #4221: [JavaSpring] Bean Validation with Optional data type
##### Description

When generating code from a .yaml file using bean validation, e.g. maxLength=5, and with useOptional set true the generated code results in `@Size(max=5) Optional<String> parameter` instead of `Optional<@Size(max=5) String> parameter`.

##### openapi-generator version

4.1.3

##### OpenAPI declaration file content or url

[api.yaml](https://gist.github.com/falaura/4d541192b0462002f83f9a91c190d016)

##### Command line used for generation

openapi-generator generate -g spring -i api.yaml --additional-properties=useOptional=true

##### Steps to reproduce

Generate files by using command line command. The described problem is found in generated `ThingsApi.java`

##### Suggest a fix/enhancement

Changes in the corresponding `queryParams.mustache`.

### PR DESCRIPTION
**Pull request by falaura**
To fix #4221
 
Changed a mustache file to generate output like `Optional<@Size(max=5) String> parameter` instead of `@Size(max=5) Optional<String> parameter` in the generated `*Api.Java`.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
The file `modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing_no_required.yaml` seems to be missing in this PR.

Instead of creating another fake pestore spec, what about adding the test cases (spec) to the existing https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml instead?

**Comment by falaura** [comment]
We discovered that it is not recommended using Optional as parameter. Thus, we decided to close this pull request.

**Comment by EmhyrVarEmreis** [comment]
@falaura 
@wing328 
Why it is not recommended to use Optional as parameter?
I believe that this PR should be updated and merged to solve related bug - now we cannot validate optional parameters.

**Pull request closed without merging**
