### PR TITLE
Update ExampleGenerator.java

### PR DESCRIPTION
**Pull request by javiarellanoo**
Renamed the DATE_FORMAT field in order to match the regular expression '^[a-z][a-zA-Z0-9]*$'.

### CODE REVIEW

**Comment by wing328** [comment]
it's a constant so looks like naming it as `DATE_FORMAT` is also ok, right?

**Comment by javiarellanoo** [comment]
> it's a constant so looks like naming it as `DATE_FORMAT` is also ok, right?
Since it lacks 'static' in the definition, code analysis tools do not detect it as a constant. That is why this suggestion was made.

**Comment by wing328** [comment]
can you add static to it instead?

**Comment by javiarellanoo** [comment]
> can you add static to it instead?

sure

**Comment by javiarellanoo** [comment]
> can you add static to it instead?

Taking a look at some documentation about the implications of having protected and static together I found this:

"Making a variable protected implies it will be used within the package or it will be inherited within a subclass.

Making the variable static makes it a member of the class, eliminating the intentions of inheriting it. This leaves only the intention of being used within a package, and we have package-private for that (no modifier)"  so maybe it is not the best idea to make it static, however if you say so we can try it.

**Comment by wing328** [comment]
let's go with what you've so far as dateTime is not a constant string

**Pull request merged**
