### PR TITLE
Fix #8971 Updating pubspec.yaml template for dart2 generator

### LINKED ISSUE #8971: [BUG][DART] Update Intl package version
#### Bug Report Checklist

- [ x] Have you provided a full/minimal spec to reproduce the issue?
- [ x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x ] Have you searched for related issues/PRs?
- [x ] What's the actual output vs expected output?

##### Description

When I use OpenApi Generator (5.0.1) to generate models for Flutter app it fails during app building with error:
```
Because every version of flutter_localizations from sdk depends on intl 0.17.0 and every version of core_design from path depends on intl ^0.16.1, flutter_localizations from sdk is incompatible with core_design from path.

So, because login depends on both core_design from path and flutter_localizations any from sdk, version solving failed.
```
This started to happen after upgrade to Flutter 2.0
##### openapi-generator version
I tested 5.0.1 and 5.0.0-beta2

##### Generation Details
java -jar openapi-generator-cli.jar generate -i ${OPENAPI_DRIVER_SPEC_FILE} -g dart -c open-generator-config.yaml --enable-post-process-file --global-property models,supportingFiles

config:
`# Config options for the dart-hhtp generator
pubName: model_generator
pubVersion: 0.0.1
pubDescription: <project name>
 `

##### Steps to reproduce

Generate models, run flutter pub get.

##### Suggest a fix
Upgrade intl package version to 0.17.0+

### PR DESCRIPTION
**Pull request by Nikarous**
Fix #8971 Update for pubspec.yaml tamplate for Dart2 generator so it can be used with Flutter 2.0.

### PR checklist
 
- [x ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ x] If your PR is targeting a particular programming language, @mention the [technical committee]
@swipesight @jaumard @josh-burton @amondnet @sbu-WBT @kuhnroyal @agilob (https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by agilob** [comment]
None of these changes is backwards compatible, change of dart, http and intl will require major breaking changes. `json_serializable` has different annotation syntax for `@JsonKey` so build_runner won't even compile.

The number of backwards incompatible changes means this shouldn't go in until 6.0, but @kuhnroyal is working on [another branch for NNBD](https://github.com/OpenAPITools/openapi-generator/pull/8869) for dart-dio. I haven't started working on it for dart native and dart-json_serializable. We'll resolve the issues with new feature-flag most likely or a new generator.

Moreover...

test library [has been specifically](https://github.com/OpenAPITools/openapi-generator/commit/4f4f1d4128ede19cbf6d882a9c03faccef1fdbc6) put as ` < 1.16.0 as it requires Dart 2.12.0` to freeze dependencies and prevent dependencies resolving and potential compilation error...

I fully get your frustration with it, I've spent all weekend and a few afternoons upgrading dependencies and fixing compile error in my apps, but openapi-gen isn't ready for forcing language syntax upgrade, policy of this generator is no breaking changes in minor releases, we will have to do it soon, but probably sometime in summer. Default dart generator isn't ready for this change.

These changes should either be introduced as a new generator for NNBD (like @kuhnroyal is doing) (fork of dart native, leave json_serializable for now, it hasn't been released yet anyway) or a feature flag for current generators.

For now, I did a dependency override in top-level pubspec:

```
dependency_overrides
  intl: intl: '^0.17.0'`
```
and hoping your project compiles with it...

**Comment by kuhnroyal** [comment]
Yea this needs to be hidden behind a flag, I discussed this with @wing328 for the dart-dio generator. Thats why I am introducing a completely new generator since the backwards compatible changes are just not possible to manage in the same generator/templates. And then you can also implement NNBD.

**Comment by kuhnroyal** [comment]
I also suggest you override the template locally and see where this gets you.

**Comment by Nikarous** [comment]
Hi, thanks for detailed comments and guidance. 

I am closing pull request and link the issue to PR with new generator.

If I can somehow help with speeding up its development let me know!
BR

**Pull request closed without merging**
