### PR TITLE
fix for the issue model import statement is missing in generated api class

### PR DESCRIPTION
**Pull request by ngp-star**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

fix for the issue https://github.com/OpenAPITools/openapi-generator/issues/6484
PR is against the master branch.

### CODE REVIEW

**Comment by ngp-star** [comment]
@jmini 
is there any updates on this PR?

**Comment by wing328** [comment]
@ngp-star looks like the code/change is not indented. Can you please fix it using 4-space for indentation?

**Comment by ngp-star** [comment]
@wing328 made changed for indentation but as part continuous-integration/drone/pr  testing its failing because of java11-test,  where actually it's trying get **bin/run-all-petstore: file** which is not available even in the latest code,  because of this following error is coming 
**bin/run-all-petstore: No such file or directory**
is there any fix for this?

**Comment by ngp-star** [comment]
@wing328 
chnages are made but in 
ci/circleci: build  phase I am getting the following error 
no changes added to commit (use "git add" and/or "git commit -a")
Please run 'bin/utils/ensure-up-to-date' locally and commit changes (UNCOMMITTED CHANGES ERROR)
even I have made commit latest code by using git pull --rebase upstream master to the created branch schematest.
could you please suggest any options for it?

**Comment by ngp-star** [comment]
@wing328 I have moved this PR to different new PR by  creating  new  branch  **newmaster**
 as in this PR **ci/circleci: build**  phase is failed i havecreated new branch and cloned latest code on top of it I have raised the PR 
new PR: https://github.com/OpenAPITools/openapi-generator/pull/6676
fixed checkstyle issues as well on the new PR can you please review the same.

**Comment by ngp-star** [comment]
@wing328 
is there any updates on this PR?

**Comment by wing328** [comment]
Duplicate of https://github.com/OpenAPITools/openapi-generator/pull/6676

**Pull request closed without merging**
