### PR TITLE
[kotlin-spring] Handle arrays of files correctly using MultipartFile

### PR DESCRIPTION
**Pull request by ffffionn**
This handles request parameters of arrays of files correctly, as well as changing them to use Spring's Multipart File class, as is recommended. Previously, Spring's Resource would be used as the input and the Delegate class would not recognize the array 

Fixes the following open issues for Kotlin-spring generator:
https://github.com/OpenAPITools/openapi-generator/issues/8333
https://github.com/OpenAPITools/openapi-generator/issues/15251

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by ffffionn** [comment]
I'm not sure that I did the samples properly, as they seem to have switched to Windows path separators instead.

**Comment by wing328** [comment]
thanks for the PR. i've filed https://github.com/OpenAPITools/openapi-generator/pull/20117 with updated samples.

is it correct to say that this is a breaking change as ` org.springframework.web.multipart.MultipartFile` is used instead?

**Comment by ffffionn** [comment]
@wing328   Yeah, I guess you could consider it that. All Spring documentation says to be using MultipartFile for uploads (but we still keep Resource for downloads)

**Comment by wing328** [comment]
can you please review the build failure when you've time?

https://github.com/OpenAPITools/openapi-generator/actions/runs/11868985076/job/33078813658?pr=20117

**Comment by wing328** [comment]
> @wing328 Yeah, I guess you could consider it that. All Spring documentation says to be using MultipartFile for uploads (but we still keep Resource for downloads)

ok. i'll see if i can come up with a way to fallback in case the users prefer the current implementation.

**Comment by ffffionn** [comment]
> can you please review the build failure when you've time?
> 
> https://github.com/OpenAPITools/openapi-generator/actions/runs/11868985076/job/33078813658?pr=20117

Sorry, I'm a bit of a noob on Github Actions. Maven build passes successfully when run, is there a way to run these tests locally? (should they be included in mvn test?)

**Comment by wing328** [comment]
can you run `gradle build` in `samples/server/petstore/kotlin-springboot-source-swagger1` for example?

**Comment by ffffionn** [comment]
There isn't any gradle wrapper in that directory

**Comment by ffffionn** [comment]
@wing328  I made some changes but there doesn't seem to be a good way to verify all the samples compile. I feel like this should be part of the maven build

**Comment by wing328** [comment]
fyi. updated samples via https://github.com/OpenAPITools/openapi-generator/pull/20108/commits/2c25491eb3c364980dce060a0a698ac4d4fea816

**Comment by wing328** [comment]
agreed with you that we should also test the kotlin spring project with maven as well

**Comment by robert-engel** [comment]
Is it correct that this change makes it impossible to generate a controller for non multipart fileuploads? `MultipartFile` is null if I just POST arbitrary bytes with a non multipart content-type to my endpoint.

**Comment by dhirajbadu** [comment]
Is it possible to apply this patch on 7.0.1?

**Pull request merged**
