### PR TITLE
[WIP] add support to remote files

### PR DESCRIPTION
**Pull request by ramzimaalej**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@ramzimaalej thanks for the PR.

The `-i` command line argument in the CLI already supports both local files and remote URLs so you may want to reuse the logic there.

**Comment by Catscratch** [comment]
Bump! Please merge it into master as soon as it is working.

**Comment by ramzimaalej** [comment]
using the same code as "-i" command would mean slower execution as it loads and validates the api file, unless we want to undertake a refactoring to make the code look the same. What I did here is to verify if the provided file location is valid, if yes download the file and initiate the processing in the same fashion as a local file

@wing328

**Comment by jimschubert** [comment]
@ramzimaalej it seems to me (please correct me if I'm wrong), that this doesn't handle split remote files and would in fact break this support? Also, renaming to a single local yaml file seems like this would break when the remote file is JSON.

I'm not following the benefit of including the logic here when it already exists in swagger-parser. Could you provide an example of how this adds value in this scenario?

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/3826

**Pull request closed without merging**
