### PR TITLE
[JAVA] [WebClient] Handle list of String special case in WebClient generator

### PR DESCRIPTION
**Pull request by GavinWu1991**
When describing an operation that returns an array of strings, the openapi-generator for java-webclient generates an API returning the array of strings in a single string.

> Recommended solution by Spring developers (see https://github.com/spring-projects/spring-framework/issues/22662 and https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html#webflux-codecs-jackson) is to use a Mono<List> for string arrays.

The PR contains the change that will generate the API client of the operation that returns an array of strings to Mono<List<String>> instead of Flux<String>.

Close: #7118  

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by GavinWu1991** [comment]
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

**Comment by tildedave** [comment]
As someone whose team just ran into this, we'd love to see this merged.

**Comment by wing328** [comment]
merged via https://github.com/OpenAPITools/openapi-generator/pull/16326 instead with an additional fix in api_test.mustache

**Comment by wing328** [comment]
@domizei385 @tildedave feel free to sponsor [@GavinWu1991](https://github.com/GavinWu1991) directly for this fix 🙏 

Thanks @GavinWu1991 again for the PR.

**Pull request closed without merging**
