### PR TITLE
[Play Framework] Regenerate the samples. It was very outdated

### PR DESCRIPTION
**Pull request by JFCote**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

### Description of the PR

No changes to the code. Only regenerated the samples for play framework.
It seems nobody had run the update of the samples for play framework for a while... Here they are. @wing328 we should have some test that validate the the samples are update to date from time to time.

### CODE REVIEW

**Comment by wing328** [comment]
Please add the script(s) to `./bin/util/ensure-up-to-date` so that the samples for play frameworks are always up-to-date.

**Comment by jmini** [comment]
> Please add the script(s) to `./bin/util/ensure-up-to-date` so that the samples for play frameworks are always up-to-date.

This approach is tracked as #80 (we decided to have it "opt-in", not forcing all the `samples/` to participate. From a QA point of view it is better to be on this list, but it is also more maintenance work).

**Comment by jmini** [comment]
@JFCote the CI server already reports that some samples are outdated:

```
	modified:   samples/server/petstore/java-play-framework-api-package-override/public/openapi.json
	modified:   samples/server/petstore/java-play-framework-async/public/openapi.json
	modified:   samples/server/petstore/java-play-framework-controller-only/public/openapi.json
	modified:   samples/server/petstore/java-play-framework-fake-endpoints/public/openapi.json
	modified:   samples/server/petstore/java-play-framework-no-bean-validation/public/openapi.json
	modified:   samples/server/petstore/java-play-framework-no-exception-handling/public/openapi.json
	modified:   samples/server/petstore/java-play-framework-no-interface/public/openapi.json
	modified:   samples/server/petstore/java-play-framework-no-wrap-calls/public/openapi.json
	modified:   samples/server/petstore/java-play-framework/public/openapi.json
```

Merge master into your PR branch and execute the `ensure-up-to-date` script again.

**Comment by wing328** [comment]
Taking a look too...

**Comment by jmini** [comment]
I think the serialization to json is not stable/deterministic see my issue: https://github.com/swagger-api/swagger-core/issues/2828

We have fixed it for Yaml, but we need to do the same for Json.

**Comment by jmini** [comment]
I think I have improved the JSON serialization with https://github.com/OpenAPITools/openapi-generator/pull/3763. Please do a review. Once merged I am happy to rebase this PR and generate the samples again.

**Pull request merged**
