### PR TITLE
Fix Maven repo links (incl. https instead of http)

### PR DESCRIPTION
**Pull request by chatelao**
The current URLs return a 501 due to missing https and worng url

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by spacether** [comment]
Earlier I filled an issue and PR to fix this at https://github.com/OpenAPITools/openapi-generator/pull/5012

**Comment by wing328** [comment]
@chatelao thanks for the PR, which looks good to me.

**Comment by wing328** [comment]
FYI. I've updated the badge as well: https://github.com/OpenAPITools/openapi-generator/commit/0ebdac4ffed2f43d7d2df5e8202119ac85e5df5b

**Comment by chatelao** [comment]
Thanks for.your endless Efforts for the community

**Pull request merged**
