### PR TITLE
Added a Julia client and server

### LINKED ISSUE #782: [Julia] Add a Julia client generator
##### Description

We want to add a new generator for Julia client. A good starting point is https://github.com/JuliaComputing/Swagger.jl

Ref: https://julialang.org/

##### openapi-generator version

Latest master

##### Suggest a fix/enhancement

If anyone wants to help on this, please reply to let us know.

cc @log0ymxm, @tanmaykm

### PR DESCRIPTION
**Pull request by tanmaykm**
This PR adds two new generators for the [Julia language](https://julialang.org/)
- `julia-client` to generate a client from specifications
- `julia-server` to generate a server with stubs that can be used to host a server conforming to the specifications

The generated code uses the Julia [OpenAPI.jl](https://github.com/JuliaComputing/OpenAPI.jl) package that includes support functions for both client and server.

Also fixes #782.
Similar to #1084, but uses [OpenAPI.jl](https://github.com/JuliaComputing/OpenAPI.jl) which supercedes the earlier [Swagger.jl](https://github.com/JuliaComputing/Swagger.jl) implementation.

cc: @wing328 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by tanmaykm** [comment]
Thanks @wing328 for taking a look.
I have rebased with master and added https://github.com/OpenAPITools/openapi-generator/pull/14520/commits/b4042b4ae2900d362c0ded821f070639ee227e43 to fix errors in the [last ci run](https://github.com/OpenAPITools/openapi-generator/actions/runs/4004813040/jobs/6899316793).

**Comment by tanmaykm** [comment]
Looks like I need to rebase and run `bin/utils/ensure-up-to-date` as advised in the [failure report](https://github.com/OpenAPITools/openapi-generator/actions/runs/4021187366/jobs/6928389094)?

**Comment by tanmaykm** [comment]
Done that now in https://github.com/OpenAPITools/openapi-generator/pull/14520/commits/1889ce073034145fd35896a851586fa730399c93

**Comment by wing328** [comment]
@tanmaykm thanks for the PR to add the new generator. I'll file another PR to make some minor improvements.

Can you please also PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by tanmaykm** [comment]
Thanks! Will do.

**Pull request merged**
