### PR TITLE
fixes to kotlin-server generator

### PR DESCRIPTION
**Pull request by Osthekake**
I'm not sure if these changes are valuable to others who have use cases that differ from mine.

In order to get the generated code to compile, I had to make a change to the code generation, and I also found an import that was not in use.

First, the path resources in Paths.kt need to have the @Contextual decorator on the datatypes, in order for the serialization to work properly. If I do not include this decorator, I am unable to compile the generated code.

Second, the import of ApiPrincipal in DefaultApi.kt is not needed when there are no auth methods, and can cause a compile error in some cases.

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (7.0.1 - patch release), `7.1.x` (minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
please follow step 3 to update the samples so that the CI can verify the change.

**Comment by wing328** [comment]
can you please also share a spec to reproduce the issue?

**Comment by Osthekake** [comment]
> can you please also share a spec to reproduce the issue?

The issue arises when I compile the generated code. Are there examples of tests that compile the code? I could run a test on the samples perhaps? I'm not sure if or how this is solved in other places.

**Comment by wing328** [comment]
Can you please PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by Osthekake** [comment]
I think I will decline this PR. It assumes using the Kotlin serializer plugin (which is recommended with ktor). That doesn't work without a few other imports added as well. If this were to be done properly, I would need to add that as a new serializer scheme alongside the other options (gson, jackson and moshi, if I recall). I may have a go at it during the weekend, as well as attempting to fix serialization in general.

Arguably, we could just delete the serializer option, since it complicates stuff a lot, and go with the recommended serializer. (and make that actually run) But I'm not sure what the stance is on that in the openapi community? It would be a breaking change, after all, but the current complexity appears to be unmaintainable.

**Comment by wing328** [comment]
that's ok. closing it for the time being

**Pull request closed without merging**
