### PR TITLE
JS Client: Allow dot in path parameter name

### PR DESCRIPTION
**Pull request by nitoqq**
To fix https://github.com/OpenAPITools/openapi-generator/issues/6030

### CODE REVIEW

**Comment by wing328** [comment]
Please run `./bin/javascript-petstore-all.sh` to update the petstore samples so that the CI can verify the change.

**Comment by nitoqq** [comment]
It's done, please verify

**Comment by jonathaningram** [comment]
Just a thought but should this be done in a more generic way? E.g. our API has paths based on the Google API Design resource names scheme which look like:

```
/v2/{name=accounts/*/domains/*}
```

The regexp change in this PR would not allow the above to work.

This might work? `/\{([\w-\.=\*/]+)\}/g` ?

**Comment by wing328** [comment]
CircleCI tests passed via https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator?branch=nitoqq-6030-js-client-allow-dot-in-path-param

**Comment by wing328** [comment]
@nitoqq thanks for the PR. Sorry for the delay in reviewing.

@jonathaningram  valid point. Can you please submit another PR and we'll review accordingly?

**Pull request merged**
