### PR TITLE
Fix PHP Symfony non-primitive return type being forced to be an array

### LINKED ISSUE #3514: [BUG] PHP Symfony server generator forces return type of actions to be an array
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

`php-symfony` server generator produces incorrect return type annotations for actions: for object types, it will erroneously generate an annotation for the type that is an array of these objects, which produces runtime errors on some configurations of Symfony.

For example, for a request that returns `Foo`, instead of generating type annotation as `Foo` it will generate type annotation `Foo[]`.

To demonstrate, given the default Pet Store swagger 2.0 contract, where `getPetById` operation returns a single object of type `Pet` (only relevant parts are preserved):

```yaml
swagger: "2.0"

paths:
  /pet/{petId}:
    get:
      tags:
        - "pet"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "getPetById"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Pet"

definitions:
  Pet:
    type: "object"

```

...the generated Symfony action `getPetById` will be erroneously annotated to return an array. Notice `@return OpenAPI\Server\Model\Pet[]`:

```php
/**
 * Operation getPetById
 *
 * Find pet by ID
 *
 * @param  int $petId  ID of pet to return (required)
 * @param  integer $responseCode     The HTTP response code to return
 * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
 *
 * @return OpenAPI\Server\Model\Pet[]
 *
 */
public function getPetById($petId, &$responseCode, array &$responseHeaders);
```

##### openapi-generator version

I am using npm package for 4.0.3: `"@openapitools/openapi-generator-cli": "0.0.16-4.0.3"`
But the issue is present on master and v5 branches too.

##### OpenAPI declaration file content or url

I used the Swagger 2.0 Pet Store example:
https://github.com/ivan-aksamentov/openapi-generator-symfony-array-bug-repro/blob/57c538bc7d/petstore.yml

##### Command line used for generation

```bash
openapi-generator generate -g php-symfony -i petstore.yml -o generated/

```

##### Steps to reproduce

One can reproduce this issue with this example repository:
https://github.com/ivan-aksamentov/openapi-generator-symfony-array-bug-repro

using the following steps (git, java, node and yarn are required):
```bash
git clone https://github.com/ivan-aksamentov/openapi-generator-symfony-array-bug-repro
cd openapi-generator-symfony-array-bug-repro
yarn install
yarn generate

```
After generation, inspect `generated/Api/PetApiInterface.php#L121-L133`:
https://github.com/ivan-aksamentov/openapi-generator-symfony-array-bug-repro/blob/57c538bc7d/generated/Api/PetApiInterface.php#L121-L133

##### Related issues/PRs

Could not find ones

##### Suggest a fix

The bug is in this snippet in `PhpSymfonyServerCodegen.java#L405-L415`:

https://github.com/OpenAPITools/openapi-generator/blob/dd0c2a84ee348e4142936b5666ad843e0a5f4c4a/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpSymfonyServerCodegen.java#L405-L415

Note how any non-primitive return type turns into an array:

```java
if (!op.returnTypeIsPrimitive) {
    op.vendorExtensions.put("x-commentType", op.returnType + "[]");
}
```

I submitted PR #3515 that attempts to fix this issue.

### PR DESCRIPTION
**Pull request by ivan-aksamentov**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

Dear PHP technical committee, please review this PR
@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ybelenko @renepardon

### Description of the PR

This PR attempts to fix #3514 
Short description: the return type of PHP Symfony actions is forced to be an array, while should be an object.

### CODE REVIEW

**Comment by ivan-aksamentov** [comment]
Should I commit the results of running `./bin/openapi3/php-symfony-petstore.sh`?
The produced sample is correct in terms of return types, but there are also changes that are not related to my PR, so I am hesitating. Looks like the symfony sample has not been updated for some time.

**Comment by wing328** [comment]
@ivan-aksamentov thanks for the PR. Please commit the updated samples.

**Comment by ivan-aksamentov** [comment]
@wing328 done.
My confusion with samples was due to the fact, that both Swagger 2.0 and OpenAPI 3.0 samples are written into the same directory, overwriting each other. I submitted #3531 and #3532 for that.

**Comment by wing328** [comment]
@ivan-aksamentov you're right. Thanks for filing another PR to fix the sample location

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/11810 has been merged to support Symfony 6. Please give it a try and let us know if you've any feedback or question.

**Pull request merged**
