### PR TITLE
WIP: [PHP] Symfony Server; support Symfony Framework 5.1

### PR DESCRIPTION
**Pull request by xvilo**
- Add Symfony Framework 5.1 support
- Update older Symfony Framework versions to supported versions
- Add DateTime object serialization and better validation
- Update JMS Serializer bundle version
    - Change PHP code accordingly

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
    - @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) ❤️, @ybelenko (2018/07), @renepardon (2018/12)

### CODE REVIEW

**Comment by ybelenko** [comment]
Ohhhh, I'm working on the same PR right now. We agreed with @wing328 that it will be new `php-symfony5` generator instead of upgrading the old one. @xvilo Maybe we should collaborate and you'll review my PR? I have already few questionable parts of implementation.

**Comment by xvilo** [comment]
@ybelenko this basically works, for as far as I have tested. I would love to take a look at the php code of your MR. However, I'm not the biggest Symfony expert; )

**Comment by ybelenko** [comment]
I had workable build in #6620 too, but I was disappointed with the approach itself, that's why I closed it. I'll push new PR with Symfony 5 generator soon(tomorrow).

**Comment by ybelenko** [comment]
Since we agreed not to deprecate `php-symfony`(Symfony 4) generator in `5.x` release and keep it along with new `php-symfony5`(Symfony 5) generator which I'm working on right now. I would like to hear feedback from community about this PR and #6620.

> However, I'm not the biggest Symfony expert ;)

I'm not skilled with Symfony either.

There are few parts of my implementation in #6620 that I'm not satisfied:
1. b3c340f I don't like how I overwrote `JmsSerializer` class I think there are more elegant ways, maybe we can find packages which solves this issue without custom code.
2. I think we can remove some of the classes from codegen and swap them with Packagist libraries.
3. I wrote two methods in base controller `Controller::getOutputFormat` and `Controller::isContentTypeAllowed` time ago and maybe we can solve it with other official Symfony extensions. https://github.com/OpenAPITools/openapi-generator/blob/master/samples/server/petstore/php-symfony/SymfonyBundle-php/Controller/Controller.php#L164

cc @reznikartem @FlaverSaver

**Comment by ybelenko** [comment]
@dkarlovi Wondering where you found so many issues, I would call current `php-symfony` generator as the first basic implementation. If we exclude Symfony source files from templates we'll end up with just three dynamic files which actually contains code generation(`api.mustache`, `api_controller.mustache`, `model.mustache`). And it seems to me as an advantage, because it's easier to fix small codebase.

And yes, I would agree that PHP generators are poorly implemented right now, I try my best to push `php-slim4` forward and make it useful. It's sad, but all PHP generators a far away from perfect, hands down.

**Comment by dkarlovi** [comment]
@ybelenko try to run CS fixer, PHPStan, Psalm on the code generated by `php` and `php-symfony`, you'll get loads of issues, I'm not the only one finding them, see #2273.

**Comment by ybelenko** [comment]
@ybelenko Yeah, I know. But if we're talking about coding style issues(PHP CS Fixer) then we can fix it for a day or two with just one pull request. Don't you think so?

**Comment by dkarlovi** [comment]
@ybelenko no, these are far from CS issues, these are real bugs. We can maybe discuss in that issue instead.

**Comment by ybelenko** [comment]
@dkarlovi By the way I prefer `PHP_CodeSniffer` over `PHP-CS-Fixer` because fixer still cannot implement `PSR-12` rule set. Ref to related issue https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502

**Comment by dkarlovi** [comment]
@ybelenko TBH I don't care which one is used as long as they do the job. :) I prefer CS Fixer, but wouldn't mind using the other one.

The key point is: the code style is not the (main) issue, it's the bugs in code which are left unchecked for years, my suggestion in #7284 would try to fix that from the ground up.

**Comment by ybelenko** [comment]
@ybelenko I mean you just can't produce PHP code which will pass both `PHP_CodeSniffer` and `PHP-CS_Fixer` because they doesn't have equal set of rules. And I consider it as a problem.

About bugs, I work with `php-slim4` most of the time and I didn't find a lot of bugs over there. But it's much less complicated than `symfony` and that's why it's called microframework.

Ok, I believe you, that current `php-symfony` may contain a lot of bugs not related to coding style.

**Comment by xvilo** [comment]
I'm closing this as 5.1 is out of date already.

**Pull request closed without merging**
