### PR TITLE
minor typo fix in samples : "pestore" -> petstore

### PR DESCRIPTION
**Pull request by karismann**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.

### Description of the PR

- minor typo fix in samples : "pestore" replaced by "petstore"
- add typescript rxjs in samples.json for auto-labeled bot

### CODE REVIEW

**Comment by wing328** [comment]
@karismann thanks for the PR but seems like the change breaks the build somehow:
```
 #!/bin/bash --login
./CI/circle_parallel.sh
Running node 2 to test ensure-up-to-date
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
# START SCRIPT: ./bin/utils/ensure-up-to-date
IMPORTANT: this script should be run by the CI (e.g. Shippable) to ensure that the 'samples/' folder is up to date.
Please press CTRL+C to stop or the script will continue in 5 seconds.
Executed ./bin/openapi3/ruby-client-petstore.sh successfully!
Executed ./bin/ruby-client-petstore.sh successfully!
Executed ./bin/java-petstore-all.sh successfully!
Executed ./bin/java-jaxrs-petstore-server-all.sh successfully!
Executed ./bin/java-msf4j-petstore-server.sh successfully!
Executed ./bin/openapi3/jaxrs-jersey-petstore.sh successfully!
ERROR: Failed to run ./bin/spring-all-petstore.sh
```

Ref: https://circleci.com/gh/OpenAPITools/openapi-generator/6217#tests/containers/2

**Comment by wing328** [comment]
You may need to keep the same permission for `bin/spring-all-petstore.sh` (755 instead 644)

**Comment by karismann** [comment]
> You may need to keep the same permission for `bin/spring-all-petstore.sh` (755 instead 644)

thanks ! i just fixed it

**Comment by wing328** [comment]
> thanks ! i just fixed it

Looks good to me. I'll merge it once the tests pass. Thanks again for the fix.

**Pull request merged**
