### PR TITLE
Add python-blueplanet server generator

### PR DESCRIPTION
**Pull request by jgroom33**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@jgroom33 Thanks for the new generator. Copying the Python technical committee below.

@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

**Comment by wing328** [comment]
@jgroom33 is there a website for Blue Planet language? Just want to learn more about Blue Planet before adding the generator to the project.

**Comment by jgroom33** [comment]
It's a corporate (closed source) implementation that provides an infrastructure for running containers. Technically, it isn't a language.
https://www.blueplanet.com/technology

**Comment by wing328** [comment]
@jgroom33 thanks for the info. What's the license for using Blue Planet? Does one need to acquire a license in order to use the auto-generated code for the BluePlanet framework/product?

If it's completely free, we can definitely include this generator. If it costs money, then we'll definitely need to make sure the users are aware of the cost before using it.

**Comment by jgroom33** [comment]
The code gen for this project is assumed to be open-sourced.  No license would be required to use the auto-generated code from this project.  There would be a requirement for the user of the generated to code have access to a Blue Planet server in order for it to be useful though.
This is similar to this project that provides the ui for blue planet: http://ciena-frost.github.io/

**Comment by wing328** [comment]
@jgroom33 thanks for the explanation 👍

**Pull request merged**
