### PR TITLE
[Swift5][client] try to fix JsonEncondable

### PR DESCRIPTION
**Pull request by 4brunu**
Try to fix https://github.com/OpenAPITools/openapi-generator/pull/11202#issuecomment-1031585187

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

### CODE REVIEW

**Comment by honkmaster** [comment]
I'm away from my work computer at the moment, so I tried the approach in a playground. It seems to work. What I don't like however is the constant repetition. If you search the history, you will find the code almost exactly as you have implemented it now. 

https://github.com/OpenAPITools/openapi-generator/commit/a620853216ff7fb6848760bf559aff2db1cf946f

**Comment by 4brunu** [comment]
From my tests, the repetition is necessary to make this work.
If we rely on the extension's default implementation, it encodes the string as json.

**Comment by honkmaster** [comment]
Yep. Agree. I don't mind the repetition if it works, I just think the resulting code is "unattractive".

**Comment by honkmaster** [comment]
An alternative approach would be to enhance the `encodeToJSON` in the protocol extension, e.g.:

```
extension JSONEncodable where Self: Encodable {
    func encodeToJSON() -> Any {
        if self is String || self is Double {
            return self
        }
        
        let encoder = JSONEncoder()
        guard let data = try? encoder.encode(self) else {
            fatalError("Could not encode to json: \(self)")
        }
        return data.encodeToJSON()
    }
}
```

But this would result in a rather long if statement in the beginning.

**Comment by 4brunu** [comment]
Yes, that's another option.
I think I like more the current implementation in this PR, to avoid a big if else.
What about you?

**Comment by honkmaster** [comment]
> Yes, that's another option.
> I think I like more the current implementation in this PR, to avoid a big if else.
> What about you?

Again, Matter of taste. LGTM.

**Comment by 4brunu** [comment]
@honkmaster thanks for reporting this issue and for validating that it's working

**Comment by honkmaster** [comment]
@4brunu Will this only be released in 6.0.0 or do you think there will be a 5.4.1?

**Comment by 4brunu** [comment]
According to the readme I think it will be available in 6.0.0.
https://github.com/OpenAPITools/openapi-generator#table-of-contents

**Comment by romanzhukovTB** [comment]
Hi @4brunu, can this fix be expedited? The project I'm working on is blocked by this bug. Or maybe if if there's a suggested workaround - that would be good for now.

**Comment by 4brunu** [comment]
Hi @romanzhukovTB, while there isn't a new release, I suggest that you build the project locally and use openapi through the jar file.
https://github.com/OpenAPITools/openapi-generator#14---build-projects

**Comment by honkmaster** [comment]
We reverted back to 5.3.1. Never upgrade a working system again ;).

**Comment by rhys-rantmedia** [comment]
I am now also blocked by this issue, and would really appreciate either 6.0.0, or an expedited 5.4.1 if that's at all possible 😬

**Pull request merged**
