### PR TITLE
Add parcelizeModels cli option

### PR DESCRIPTION
**Pull request by absimas**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

With cli option `parcelizeModels` (false by default) allow the use of kotlin's parcelize feature which generates all boilerplate automatically. Currently, the user will require to manually set
```
androidExtensions {
    experimental = true
}
```
but it's a small price to pay IMO.

@jimschubert @dr4ke616

### CODE REVIEW

**Comment by wing328** [comment]
@absimas Thanks for the PR. Java client generator already supports this option as follows:
```
    public static final String PARCELABLE_MODEL = "parcelableModel";
        cliOptions.add(CliOption.newBoolean(PARCELABLE_MODEL, "Whether to generate models for Android that implement Parcelable with the okhttp-gson library."));
```

Shall we name it consistently using `parcelableModel` instead?

Ref: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java#L64

**Comment by absimas** [comment]
I would disagree because parcelize is just an annotation that internally generates parcelable implementation for models.
`parcelableModel` generates the implementation itself which is not the same.

**Comment by absimas** [comment]
I understand the need but I think it's important to make the distinction here.
Since they're different there may be a need for `parcelableModel` in kotlin too.

**Comment by wing328** [comment]
@absimas I ran some tests and got errors doing `gradle test` using the option `--additional-properties parcelizeModels=true`: 
```
➜  kotlin_client gradle build

> Task :compileKotlin
Using kotlin incremental compilation

e: /private/tmp/kotlin_client/src/main/kotlin/org/openapitools/client/models/Pet.kt: (15, 8): Unresolved reference: android
e: /private/tmp/kotlin_client/src/main/kotlin/org/openapitools/client/models/Pet.kt: (16, 8): Unresolved reference: kotlinx
e: /private/tmp/kotlin_client/src/main/kotlin/org/openapitools/client/models/Pet.kt: (24, 2): Unresolved reference: Parcelize
e: /private/tmp/kotlin_client/src/main/kotlin/org/openapitools/client/models/Pet.kt: (29, 5): Unresolved reference: Parcelable
```

Spec: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v2.0/yaml/petstore-minimal.yaml

Do I need to update build.gradle to make it work?

**Comment by absimas** [comment]
As I've said in the PRs description, you need to allow experimental features by adding the following lines to your `build.gradle` file:
```
androidExtensions {
    experimental = true
}
```

**Comment by wing328** [comment]
@absimas when you've time, please have a look at the compile issue reported by the CI below:
```
$ mvn --quiet clean install
[ERROR] COMPILATION ERROR : 
[ERROR] /home/travis/build/OpenAPITools/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java:[364,14] ';' expected
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project openapi-generator: Compilation failure
[ERROR] /home/travis/build/OpenAPITools/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java:[364,14] ';' expected
[ERROR] 
```

**Comment by wing328** [comment]
@absimas can you please also run `./bin/utils/export_docs_generators.sh` to ensure the documentation is up-to-date?

**Comment by wing328** [comment]
If no further feedback/question on this PR, I'll merge it on coming Friday.

**Comment by wing328** [comment]
The CircleCI failure is due to outdated generator doc and I'll update after merging this PR into master.

**Comment by wing328** [comment]
@absimas thanks for the PR, which has been included in the v3.3.3 release: https://twitter.com/oas_generator/status/1062929948191510528

**Pull request merged**
