### PR TITLE
Add nullable annotation support to AspNetCoreServer

### PR DESCRIPTION
**Pull request by janssen92**
Since c# 8 / .net core 3.0 it is possible to add a nullable annotation to a project file. 
This allows to use the ? annotation not only on non-nullable types but on all types. 

Using this annotations can improve the readability within the code and also improves API behavior in regards to optional (nullable) properties.

The default behavior is not altered, it should stay compatible with everything.

Tests were added to ensure correct behavior.

This PR is a possible solution for:
#9190 
#9022

 @shibayan @Blackclaws @lucamazzanti 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by devhl-labs** [comment]
My pr has this switch in the abstract.

https://github.com/OpenAPITools/openapi-generator/pull/9235

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by janssen92** [comment]
@wing328   Thanks, I updated the commit :)

@devhl-labs   I adjusted my config/variable naming to be compatible with your PR #9235

**Comment by wing328** [comment]
@devhl-labs thanks for reviewing and your work on #9235 to kick-start the work on nullable annotation support.

@janssen92 thanks for PR as well as the test.

Merging this one as it has tests to cover the change.

**Comment by devhl-labs** [comment]
Isnt the switch in the wrong file though?

**Comment by janssen92** [comment]
@devhl-labs aggreed, i wanted to stay compatible to your PR. It can be moved to the abstract part at any time, so there shouldn't be a problem.

**Pull request merged**
