### PR TITLE
fix: Inline model schema's name is wrong

### LINKED ISSUE #14688: [BUG] Inline model schema's name is wrong
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
When we have 2 operations (where operation = HTTP VERB + PATH) with the same path e.g.
```
GET path/{id}
PATCH path/{id}
```

and 

1. the GET response body schema is just a reference to a well defined schema (e.g. `GenericDTO`)
2. the PATCH request body is an inline schema

you''ll have, in the openAPI's components, these 2 schemas:

1. `GenericDTO`
2. `ApiV1PathIdGetRequest`

the second schema 's name is wrong, it should instead be `ApiV1PathIdPatchRequest`

Sorry for not providing a spec to reproduce, I fixed it working against my day job's swagger.

Will try, eventually if I find the time, to create a spec in my free time.
##### openapi-generator version

6.4.0-SNAPSHOT

##### OpenAPI declaration file content or url

[JSON spec](https://gist.github.com/davidediak/e5135fbe36c9f4dd77eb8c14a5d4aa3e)

##### Generation Details

On master run
`./run-in-docker.sh mvn package `
`./run-in-docker.sh generate -i spec.json -g typescript-angular --global-property models`

You'll get 2 interfaces:
```
apiV1CustomerIdGetRequest.ts
customerResponse.ts
```

the first file name is wrong, it should be called `apiV1CustomerIdPatchRequest.ts` since it's the inline schema for the patch 's requestBody

### PR DESCRIPTION
**Pull request by davidediak**
Fixes #14688 

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the fix, can you please share a minimal spec to reproduce the issue?

i'm sure you're aware that the inline schema mapping can be customized: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#inline-schema-naming

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by davidediak** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

Sorry about that, should be ok now.

**Comment by davidediak** [comment]
@wing328 I've added spec + how to reproduce in the related linked issue.
Let me know if something is still missing.

**Comment by wing328** [comment]
tested locally to confirm the fix: 
```diff
--- a/.openapi-generator/FILES
+++ b/.openapi-generator/FILES
@@ -1,12 +1,11 @@
 .github/workflows/maven.yml
 .gitignore
-.openapi-generator-ignore
 .travis.yml
 README.md
 api/openapi.yaml
 build.gradle
 build.sbt
-docs/ApiV1CustomerIdGetRequest.md
+docs/ApiV1CustomerIdPatchRequest.md
 docs/CustomerResponse.md
 docs/DefaultApi.md
 git_push.sh
@@ -37,8 +36,6 @@ src/main/java/org/openapitools/client/auth/Authentication.java
 src/main/java/org/openapitools/client/auth/HttpBasicAuth.java
 src/main/java/org/openapitools/client/auth/HttpBearerAuth.java
 src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
-src/main/java/org/openapitools/client/model/ApiV1CustomerIdGetRequest.java
+src/main/java/org/openapitools/client/model/ApiV1CustomerIdPatchRequest.java
 src/main/java/org/openapitools/client/model/CustomerResponse.java
-src/test/java/org/openapitools/client/api/DefaultApiTest.java
-src/test/java/org/openapitools/client/model/ApiV1CustomerIdGetRequestTest.java
-src/test/java/org/openapitools/client/model/CustomerResponseTest.java
+src/test/java/org/openapitools/client/model/ApiV1CustomerIdPatchRequestTest.java
```

**Comment by wing328** [comment]
@davidediak thanks for the fix, which has been merged.

**Pull request merged**
