### PR TITLE
[java][native] fix empty response body

### LINKED ISSUE #13968: [BUG] Java generated client throws MismatchedInputException when response body is empty
##### Description

When server returns 2xx status code, generated client code tries to parse body even when Content-Length is specified 0 in header. This in turn throws "com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input".

Example of generated code:
```
public ApiResponse<Object> executeCallUsingPOST2WithHttpInfo(InvokeData data) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = executeActionUsingPOST2RequestBuilder(data);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("executeCall", localVarResponse);
        }
        return new ApiResponse<Object>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Object>() {}) // closes the InputStream
          
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }
```

##### openapi-generator version

6.2.0

##### Steps to reproduce

Make a successful API call which returns no content

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/7720

##### Suggest a fix

Don't parse response with Jackson if content length is 0.

### PR DESCRIPTION
**Pull request by Frontrider**
To fix #13968.

The issue was that the client did not check if the response was empty before trying to read it as json, but this was only a problem if the endpoint could respond with an object and an empty response as well with the most common case being a 204 response.
This bug does not affect the async client, only the sync client.

The documentation for what I did is in a comment above the change in `api.mustache`.
https://github.com/telekom/openapi-generator/blob/fix/13968/modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache#L279
I included it there, because I see that there was already a failed attempt to do it in #13993, and the reason why that code could not work is not obvious.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee]

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

### CODE REVIEW

**Comment by Frontrider** [comment]
pushed the requested fix.

**Comment by Frontrider** [comment]
I have trouble regenerating the samples, I'm getting errors.

**Comment by wing328** [comment]
can you please file a new one without updating the samples?

i'll update the samples based on your new PR

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/20334

**Pull request closed without merging**
