### PR TITLE
Update akka scala generator

### PR DESCRIPTION
**Pull request by joelvim**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

* Upgrade scala version to 2.12.8
* Upgrade Akka version
* Migrate from spray to Akka HTTP

Related to issue #2471

### CODE REVIEW

**Comment by wing328** [comment]
@joelvim thanks for the PR. Please run the scala-akka shell scripts (./bin/scala-akka*) or batch files (bin\windows\scala-akka*) to update the Petstore samples so that the CI can verify the change.

**Comment by wing328** [comment]
CircleCI failed with the following errors:
```
[ERROR] Failed to execute goal on project scala-akka-petstore-client: Could not resolve dependencies for project org.openapitools:scala-akka-petstore-client:jar:1.0.0: Could not find artifact io.spray:spray-client:jar:1.3.4 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

Please take a look when you've time.

**Comment by joelvim** [comment]
Sorry I forgot to update pom.xml. It's done now.

**Comment by wing328** [comment]
cc @clasnake (2017/07), @jimschubert (2017/09), @shijinkui (2018/01), @ramzimaalej (2018/03)

**Comment by wing328** [comment]
To close https://github.com/OpenAPITools/openapi-generator/issues/2471

**Pull request merged**
