### PR TITLE
[Java] Update version of maven-surefire-plugin

### PR DESCRIPTION
**Pull request by sebastien-rosset**
1. Upgrade version of maven-surefire-plugin
1. In case of UT failure, output logs of petstore service to help troubleshoot issue.
1. Java unit tests are modified to use the local instantiation of the petstore.

Currently, the default "okhttp-gson" library uses maven-surefire-plugin version 2.12, which is fairly old (January 2012). With maven-surefire-plugin version 2.12, the following error occurs when executing "mvn package" on the generated Java code:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12:test
(default-test) on project intersight-openapi-java-client:
Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12:test failed:
Task java.util.concurrent.FutureTask@f29353f[Not completed, task = org.apache.maven.plugin.surefire.booterclient.ForkStarter$1@889a8a8] rejected
from java.util.concurrent.ThreadPoolExecutor@36f7d7b[Running, pool size = 1,
active threads = 0, queued tasks = 500, completed tasks = 0] -> [Help 1]

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12:test
(default-test) on project intersight-openapi-java-client: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12:test failed:
Task java.util.concurrent.FutureTask@f29353f[Not completed, task = org.apache.maven.plugin.surefire.booterclient.ForkStarter$1@889a8a8]
rejected from java.util.concurrent.ThreadPoolExecutor@36f7d7b[Running, pool size = 1,
active threads = 0, queued tasks = 500, completed tasks = 0]
```
This issue occurs with relatively big OAS documents.

Changing the pom.xml to use version 3.0.0-M4 fixes the problem.

For reference, here is the bug fix in the surefire plugin:
https://git-wip-us.apache.org/repos/asf?p=maven-surefire.git;a=commit;h=b7adb745df68730e43a6e3e4711f18619513bfb0

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by sebastien-rosset** [comment]
@bbdouglas  @sreeshas @jfiala  @lukoyanov  @cbornet  @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

**Comment by wing328** [comment]
@sebastien-rosset thanks for the PR. Restarted the failed CI jobs. Let's see how it goes.

**Comment by wing328** [comment]
Likely the issue is due to corrupted data in the public petstore server.

**Comment by wing328** [comment]
Travis tests passed via https://travis-ci.org/github/OpenAPITools/openapi-generator/builds/666798662

**Pull request merged**
