### PR TITLE
fix #2022 util._deserialize throws AttributeError in Python 3.7

### LINKED ISSUE #2022: [BUG][Python][Python-Aiohttp] util._deserialize throws AttributeError in Python 3.7
##### Description

```
Traceback (most recent call last):
  File "*******/venv/lib64/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "*******/venv/lib64/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "*******/venv/lib64/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "*******/venv/lib64/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "*******/venv/lib64/python3.7/site-packages/connexion/apis/aiohttp_api.py", line 32, in oauth_problem_middleware
    response = yield from handler(request)
  File "*******/venv/lib64/python3.7/site-packages/connexion/decorators/coroutine_wrappers.py", line 23, in wrapper
    connexion_response = yield from connexion_response
  File "*******/venv/lib64/python3.7/site-packages/connexion/apis/aiohttp_api.py", line 198, in get_response
    response = yield from response
  File "*******/openapi_server/controllers/search_controller.py", line 22, in search
    search_results = SearchResults.from_dict(data)
  File "*******/openapi_server/models/search_results.py", line 56, in from_dict
    return util.deserialize_model(dikt, cls)
  File "*******/openapi_server/util.py", line 106, in deserialize_model
    setattr(instance, attr, _deserialize(value, attr_type))
  File "*******/openapi_server/util.py", line 29, in _deserialize
    elif type(klass) == typing.GenericMeta:
AttributeError: module 'typing' has no attribute 'GenericMeta'
```

* `typing.GenericMeta` is [not available](https://github.com/python/typing/issues/468) in Python 3.7
* Relying on `__extra__` is [not recommended](https://github.com/python/typing/issues/136#issuecomment-138174590)

##### openapi-generator version

4.0.0-SNAPSHOT

##### Suggested fix

In `_deserialize` in [util.mustache](modules/openapi-generator/src/main/resources/python-aiohttp/util.mustache) use [typing_inspect](https://pypi.org/project/typing-inspect/), package which [might get included](https://github.com/python/typing/issues/570) in [typing](https://docs.python.org/3/library/typing.html) anyway.

### PR DESCRIPTION
**Pull request by bejohu**

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

**Comment by wing328** [comment]
@bejohu  Is this fixing the same issue as https://github.com/OpenAPITools/openapi-generator/pull/2884 ?

**Comment by GuillaumeSmaha** [comment]
@wing328 Yes, this is the same issue.
I tried without `typing-inspect` because I saw https://github.com/ilevkivskyi/typing_inspect doesn't support python 3.5

**Comment by wing328** [comment]
@GuillaumeSmaha 👌 

@bejohu can you test https://github.com/OpenAPITools/openapi-generator/pull/2884 to see if it works for you as well?
```
git checkout -b GuillaumeSmaha-fix_python_3.7 master
git pull https://github.com/GuillaumeSmaha/openapi-generator.git fix_python_3.7
```

**Comment by wing328** [comment]
@GuillaumeSmaha to clarify, does your fix make the Python generator works with Python 3.5 for backward-compatibility?

**Comment by GuillaumeSmaha** [comment]
@wing328 Yes, I just tried and it  works for 3.5. I also fixed a dumb bug :man_facepalming:  https://github.com/OpenAPITools/openapi-generator/pull/2884/commits/b232d613ed8cd3cc307884f5c754586965f35dcd

**Comment by wing328** [comment]
@bejohu please try the latest master. Let us know if you still encounter any issue.

**Pull request closed without merging**
