### PR TITLE
Use correct relative paths

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR fixes the paths in the files. There should not be these absolute (generated) paths.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by DanielRuf** [comment]
@CodeNinjai @frol @cliffano

**Comment by DanielRuf** [comment]
Not sure which file is used for that. Can you point me to that?

**Comment by renepardon** [comment]
The examples should be generated with corresponding ./bin/*.sh files. I'm not yet sure but I think if you execute this one: https://github.com/OpenAPITools/openapi-generator/blob/master/bin/javascript-flowtyped-petstore.sh an absolute path will be inserted again. If this is the case, we should consider updating all the javascript example generator scripts.

**Comment by wing328** [comment]
Those files under lib are not auto-generated and it's definitely a good idea not to use absolute path.

**Pull request merged**
