### PR TITLE
Fix spring generator dto annotations for xml support

### PR DESCRIPTION
**Pull request by tomyy**
Fixes https://github.com/OpenAPITools/openapi-generator/issues/16915 by changing the spring-pojo template to correctly place the JacksonXmlProperty annotations.

* Modify the test added for https://github.com/OpenAPITools/openapi-generator/issues/5705 so that it checks the corrected template.
* add test to the openapi3/server/petstore/springboot-3 sample

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@cachescrubber @welshm @MelleD @atextor @manedev79 @javisst @borsch @banlevente @Zomzog @martin-mfg

### CODE REVIEW

**Comment by slogic** [comment]
Will this fix be backported to 6.x.x branch ?

**Comment by martin-mfg** [comment]
> Will this fix be backported to 6.x.x branch ?

Most probably not. 
see https://mvnrepository.com/artifact/org.openapitools/openapi-generator - There is no backporting in the OpenAPI Generator project.

**Comment by tomyy** [comment]
@wing328 when will this fix be merged? We are stuck on version 6.4 until this is merged.

**Comment by tomyy** [comment]
@wing328 the problem seems to be caused by the new "allArgsConstructor" option (https://github.com/OpenAPITools/openapi-generator/pull/18538).

I can confirm that by checking out commit 2a1b4f90 and running `mvn integration-test -f samples/openapi3/server/petstore/springboot-3/pom.xml` on that commit which on my machine also fails with the same error message.

If that new "allArgsConstructor" option is active and a model class like [`Category`](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/Category.java) doesn't have any required parameters the templates do no longer generate a no-arg constructor (which is required by Jackson Databind). The test runs successfully if I manually add a no-arg constructor to that class.

For model classes like [`Pet`](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/server/petstore/springboot-3/src/main/java/org/openapitools/model/Pet.java#L90) there are three constructors generated:
* no-args
* only the required parameters
* all parameters

The fix will need changes to the JavaSpring/pojo.mustache template, however I'm currently unsure on how to best implement it (the required conditions seem very convoluted in an already complex template)

**Comment by wing328** [comment]
@tomyy thanks for the details. Didn't realize it's broken due to the allArgsConstructor.

@jpfinne can you please review the issue when you've time? I think likely you need to update the tests.

**Comment by jpfinne** [comment]
@wing328   the no arg constructor should be fixed in #18650

**Pull request merged**
