### PR TITLE
Use yarn for website builds

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @wing328 fyi

### CODE REVIEW

**Comment by xvilo** [comment]
As this has no description whatsoever, what's the desired reason to use yarn over npm? You're now creating an extra dependency that needs to be installed too. (See the before_install).

**Comment by jimschubert** [comment]
@xvilo this has no effect on users or their processes whatsoever.

Npm doesn't support pinning dependencies in a good way, even with shrinkwrap. Our new site uses an alpha version of Docusaurus, so we don't want Travis to be randomly broken. Using Yarn is the only good way to pin versions with loose semver options.

**Comment by xvilo** [comment]
Instead you could do npm ci instead of npm install. That would probably fix your issues...

**Comment by jimschubert** [comment]
`npm ci` skips user interactivity. It doesn't change npm's poor resolution algorithm. 

Can you explain exactly what you're concerned about, and I'll try to address your concern. If you're concerned about speed, we can evaluate the time differences. However, the solution would probably be to move to yarn for everything as we've had pretty regular issues with npm on Travis.

**Pull request merged**
