### PR TITLE
[Golang][client] fix go import issue

### PR DESCRIPTION
**Pull request by anandshah05**
### PR checklist

Adding optional import for non primitive fields

### Description of the PR

https://github.com/OpenAPITools/openapi-generator/issues/1082

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
cc @antihax (2017/11) @bvwells (2017/12) @grokify (2018/07)

**Comment by anandshah05** [comment]
Please merge

**Comment by wing328** [comment]
@anandshah05 I did some tests locally and it's adding the following for the test spec you provided:
```
@@ -16,6 +16,7 @@ import (
        "net/url"
        "strings"
        "fmt"
+       "github.com/antihax/optional"
 )
```

I'm ok with the change.

**Comment by anandshah05** [comment]
Thank you!

**Comment by wing328** [comment]
@anandshah05 thanks again for the PR, which is included in the v3.3.0 minor release: https://twitter.com/oas_generator/status/1046941449609068544

**Pull request merged**
