### PR TITLE
[BUG] [Java] Client resttemplate and webclient. Form Params are badly added when they are lists 

### PR DESCRIPTION
**Pull request by jorgerod**
…when they are lists

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the technical committee to review the pull request if your PR is targeting a particular programming language. @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### Description of the PR
Addresses issue #4383 for java resttemplate and java webclient

### CODE REVIEW

**Comment by jorgerod** [comment]
Hi

Elixir tests are failing but I have not changed anything related to elixir.
Can you help me?

Thank you

**Comment by lwlee2608** [comment]
Not sure about the elixer failure. But looks like you have not updated the sample files. You can refer to this [link](https://github.com/OpenAPITools/openapi-generator/blob/master/CONTRIBUTING.md#testing) for more information

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Usually, the elixir test failure is due to failure in installing some elixir binaries/dependencies and a job restart should fix it.

We can restart the failed job before merging the PR

**Comment by jorgerod** [comment]
> Any reason why some of the `MultiValueMap` type parameters <K, V> are being removed?

Resttemplate use spring-web 4.x.x. In this version. MultiValueMap hasn´t method `addAll`. (I think you should upgrade the version)

So, the best option to insert a list, for example strings, is with the `put` method but if MultivalueMap <String, Object>, does not compile when doing `.put ("key", List <String>)`

**Comment by lwlee2608** [comment]
I see. I guess that's fine... 
Another option is to copy the list to a new `List<Object>`
```
            List<Object> enumFormObjectArray = new ArrayList<Object>(enumFormStringArray);
            formParams.put("enum_form_string_array", enumFormObjectArray);
```
This way, we can keep `MultiValueMap`'s type parameter, but it is obviously less efficient.
3rd option is to upgrade to spring 5.x.x
I'll let @wing328 decides :)

**Comment by wing328** [comment]
> 3rd option is to upgrade to spring 5.x.x

We can do that later in another PR

**Comment by wing328** [comment]
@jorgerod thanks for the PR, which has been included in the v4.2.2 release: https://twitter.com/oas_generator/status/1201432648544972800

**Pull request merged**
