### PR TITLE
cpp-tiny 3.0

### PR DESCRIPTION
**Pull request by AndersSpringborg**
This is an improvement to cpp-tiny generator. It adds support for form and query params. Thenn it improves the code quality a tiny bit.

Can someone label this with `client:cpp` .... And `hacktoberfest-accepted` if this is valid.. :)

Technical commetee
@ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

### CODE REVIEW

**Comment by michelealbano** [comment]
Any news regarding this PR? @wing328

**Comment by wing328** [comment]
Yup, we can merge it but I've not tested it locally.

**Comment by AndersSpringborg** [comment]
Cool. @wing328 can you ADD the label "hacktoberfest-accepted" 🤠

**Comment by wing328** [comment]
Done.

**Comment by AndersSpringborg** [comment]
thanks <3

**Pull request merged**
