### PR TITLE
[csharp-netcore] Add null reference types and experimental http client library

### PR DESCRIPTION
**Pull request by devhl-labs**
Adding NRT option and templates for experimental library.

The commits between the verified commits should be undone by https://github.com/OpenAPITools/openapi-generator/pull/9102/commits/5b7c5da15cea42627945a24e84a64737041239b2. Sorry for this. My fork got a bit messy because my last pr was from my master, and I had my template files in httpclient instead of httpclient-experimental folder.

@wing328  @Blackclaws 
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by devhl-labs** [comment]
@wing328 Can i get some input here? I can move this back to the other branch if that helps. I've got some other changes to make but there's quite a bit here to see.

**Comment by wing328** [comment]
@devhl-labs can you please PM me via Slack to further discuss this? Thanks again for the PR to improve the C# generators.

**Comment by lucamazzanti** [comment]
Is this PR an obsolete alternative to #9235?

**Comment by Blackclaws** [comment]
Its a more involved rewrite of the csharp client and the null reference part was split out. We'll actually need to review that.

**Pull request closed without merging**
