### PR TITLE
enable typescript unit tests

### PR DESCRIPTION
**Pull request by macjohnny**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by macjohnny** [comment]
cc 
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

**Review by akehir — APPROVED** [review]
lgtm

**Comment by macjohnny** [comment]
Unfortunately, some tests fail.
Are there some folks of the TS technical comittee willing to help out?

**Comment by macjohnny** [comment]
I recently fixed the typescript-angular unit tests (https://github.com/OpenAPITools/openapi-generator/pull/10208) and added them for angular 11 as well (https://github.com/OpenAPITools/openapi-generator/pull/10209)

**Comment by amakhrov** [comment]
@macjohnny it looks like the failed tests try to make api requests to `httpbin` - https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/typescript/tests/default/test/http/isomorphic-fetch.test.ts#L16

prob the easiest is to disable these 2 tests in the meantime, to unblock the PR?

**Pull request merged**
