### PR TITLE
[Java][Native] Fix the Content-Type and Accept headers that were forced to application/json

### LINKED ISSUE #6779: [BUG][JAVA] Content type of response seems to be ignored and always set to application/json
##### Description
The defined content type within the open api spec seems to be ignored. The generated code always contains "application/json".

##### openapi-generator version
openapi-generator-cli-4.3.1.jar

##### OpenAPI declaration file content or url
```yaml
[...]
 "200": {
            "description": "Success",
            "headers": {
              "Cache-Control": {
                "description": "Controls whether and how long response can be cached by consumers, defaults to 'no-cache, no-store'.",
                "style": "simple",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/vnd.de.db.ris+json": {
                "schema": {
                  "$ref": "#/components/schemas/BoardPublicArrival"
                }
              }
            }
          }
[...]

##### Command line used for generation

java -jar openapi-generator-cli-4.3.1.jar generate -g java -i swagger.yml --library native --api-package innoapi.api --invoker-package innoapi.invoker --model-package innoapi.model

##### Steps to reproduce
Look in the code and the accept header.
`
localVarRequestBuilder.header("Accept", "application/json");
`

##### Related issues/PRs
/

##### Suggest a fix
Content type has to evaulated for setting the accept header.

### PR DESCRIPTION
**Pull request by Paul-Etienne**
This PR intends to fix #6779. There's a bug in the native Java generator that forces the _Content-Type_ and _Accept_ headers of every endpoint of the generated client to `application/json`, even though a different media-type is specified in the spec.

I have let `application/json` as a default value in case no media-type is found for a given endpoint. I made sur the _Accept_ header contains all possible values referenced in the responses in the spec, as opposed to the _Content-Type_ header where I only selected the first media-type found in the _consumes_ array variable since this header only accepts one value, as per the HTTP standard.

I have tested this fix on a company project by using a template with `api.mustache`, which has proven to give the expected results. We are using this template to fix this bug before this gets integrated to the OpenAPI Generator project. For my tests, I used a spec which had a request using `application/xml` and were giving responses of types `application/xml` or `application/json`.

In order to validate my work, you need to use the Java generator to generate a client with the native library with a spec that has an endpoint with a request body of type different than `application/json`. Same thing for the responses of that endpoint.
You should then look for this part of the generated code:

```java
private HttpRequest.Builder endpointRequestBuilder(String body) throws ApiException {
    ...
    localVarRequestBuilder.header("Content-Type", "application/xml"); // or any other type used in the spec
    localVarRequestBuilder.header("Accept", "application/json, application/xml"); // or any other types used in the spec
    ...
    return localVarRequestBuilder;
}
```

I hope this fix fully resolves the issue.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).

**Note:** Despite running these scripts in Git BASH from Windows, it generated a lot of false positive changes with a wrong line separator (CRLF instead of LF) and with a backslash instead of slashes. So I only committed the changes that looked relevant to me. I hope I didn't miss anything.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

I'm tagging the technical committee responsible for the Java generator: @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by Paul-Etienne** [comment]
Thanks for pointing that out, I've fixed that, but it now shows a different committer other than my Github account. Do you know why? Or maybe that's not a big deal.

**Comment by Paul-Etienne** [comment]
Alright, I fixed it correctly this time. Sorry for the bother.

**Comment by wing328** [comment]
Tested locally and the result is good. Thanks for the PR.

**Pull request merged**
