### PR TITLE
[Swift 5] deprecate retry hook since its no longer needed

### PR DESCRIPTION
**Pull request by 4brunu**
This PR deprecates the retry hook since its no longer needed.

For more info on how to intercept and handle errors like authorization or retry the request, check the Wiki. https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-do-i-implement-bearer-token-authentication-with-urlsession-on-the-swift-api-client

This PR also contains some fixes on code formatting.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

### CODE REVIEW

**Comment by wing328** [comment]
@4brunu Thanks for the enhancement. Do we consider this change a breaking change with fallback?

**Comment by 4brunu** [comment]
I'm not sure if I consider this a breaking change with fallback.
Let me explain why.

The hook `taskCompletionShouldRetry` will continue to work as before with this PR.
The only thing that this PR does it to show a warning in the IDE, pointing the users the docs, so that they can migrate to the new method, when they have time.

When I created the URLSession integration, I couldn't find a better way to deal with the authentication errors, so I introduced this hook.
But now that the PR https://github.com/OpenAPITools/openapi-generator/pull/8267 was merged this hook is no longer needed.

This is just to avoid multiple ways of doing the same thing.

Also the Swift 5 generator is still marked as beta.

Having said that, is this a breaking change with fallback? 🙂

**Comment by wing328** [comment]
@4brunu thanks for the detailed explanation. Let's go with this change and see if the users consider it as a breaking change.

**Comment by 4brunu** [comment]
Thanks

**Pull request merged**
