### PR TITLE
Improve logging in Python client

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

For https://github.com/OpenAPITools/openapi-generator/issues/236

cc @taxpon @frol @mbohlool @cbornet @kenjones-cisco

### CODE REVIEW

**Comment by wing328** [comment]
@asqui the update samples need to be included in this PR so that the CI can test the changes in the Python petstore clients.

**Comment by kenjones-cisco** [comment]
LGTM! Thanks @wing328

**Comment by asqui** [comment]
@wing382 I understand that, but what I don't understand is how all those petstore example changes are at all related to your code change.

**Comment by wing328** [comment]
@asqui good question. The Python samples may not be up-to-date due to new test cases added to the test spec.

**Comment by grokify** [comment]
@asqui Would having 2 commits in this PR satisfy your concern? For example, one commit could be the client code changes and another commit could be the updated samples. This way the two commits could be viewed separately while also including the updated samples for testing.

**Comment by wing328** [comment]
The CircleCI error is not related.

**Pull request merged**
