### PR TITLE
[cli] new 'author template' command

### PR DESCRIPTION
**Pull request by jimschubert**
This new command allows users to extract templates for authoring (customization) without the complexity of finding and downloading a specific directory for their versioned artifact.

Example usage:

```
openapi-generator author template -g java --library webclient
```

This will write all templates with library-specific templates to the './out' directory relative to the current directory. The user can specify an alternative directory as well. See the doc changes in this PR for more details.

CLI will refer the user to https://openapi-generator.tech/docs/templating after generation.

This PR is supplemental to the template quality PR #6357

This PR provides the start of authoring commands detailed in #1811

cc @OpenAPITools/generator-core-team 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the work on this. I'm sure users will find it useful to begin the template customization.

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar author template -g java --library webcli
[main] INFO  o.o.codegen.cmd.AuthorTemplate - Extracted templates to 'out' directory. Refer to https://openapi-generator.tech/docs/templating for customization details.
```
I tested with an invalid library name (e.g. webcli) but got the same (correct) output. 

What about validating the library name and output a proper error message if it's invalid?

**Comment by jimschubert** [comment]
@wing328 we don't really have a way to check library names statically, especially since users can have a library on classpath by some wrapper, for instance if running via a fatjar depending on the CLI project.

It might be confusing if we write _most_ files but throw an exception, and I agree we should let them user know. How about a check at the end which evaluates if out/libraries/name exists and log a warning if it does not? The user can check spelling and rerun, this should overwrite existing files and directories.

**Comment by jimschubert** [comment]
I've updated with a warning message if the user passes an invalid or misspelled library option.

The first run in the following image is correct spelling and the second run has the library spelled incorrectly.

image

**Comment by jimschubert** [comment]
I'll go ahead and merge this. We can make any necessary improvements in a follow up PR.

**Pull request merged**
