### PR TITLE
C# - nullable string

### PR DESCRIPTION
**Pull request by gbmarc1**
Make string a nullable type.

Useful for optional query param

#9233

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by gbmarc1** [comment]
Mentioning technical committee
@mandrean @frankyjuang  @shibayan @Blackclaws

**Comment by devhl-labs** [comment]
I think it requires a bit more than what you've changed. I added an option for NRT here https://github.com/OpenAPITools/openapi-generator/pull/9235.

**Comment by gbmarc1** [comment]
@devhl-labs Do you think it would be better for me to work on this PR after your's is completed?

**Comment by devhl-labs** [comment]
Yes, of course. Or you can clone my branch and see if it helps fix your problem.

**Comment by wing328** [comment]
Closed per https://github.com/OpenAPITools/openapi-generator/pull/9234#issuecomment-820783717

**Pull request closed without merging**
