### PR TITLE
Delete unused methods in DefaultCodegen

### PR DESCRIPTION
**Pull request by ackintosh**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by jmini** [comment]
Thank you for this PR, it makes me aware of dead code.

---

Before removing those method, did we make an analysis about where they were used in swagger-generator v2?

For example #197 is about `oneOf`, maybe the method `isDiscriminatorInInterfaceTree(..)` could be useful (this is just a guess, I did not do an analysis yet).

**Comment by ackintosh** [comment]
Sounds like a good idea.

But I think that it is better to delete the codes that is not currently in use as it is difficult to predict whether or not to use that codes. (My point is making the codes in this project more simply and keep.)

Even if we need the deleted code, it is easy to copy and use it.

What do you think?

**Comment by jmini** [comment]
> But I think that it is better to delete the codes that is not currently in use as it is difficult to predict whether or not to use that codes. (My point is making the codes in this project more simply and keep.)

dead/unused/commented code is not a good thing... I totally agree with you.

**Comment by wing328** [comment]
@ackintosh thanks for the PR to clean up unused methods.

@jmini very good point about the need to understand how these methods were used before and we can always revisit these methods when we've time by checking out a particular commit.

**Pull request merged**
