### PR TITLE
fix(#1051): fix wrong matching between yaml enum value starting with a

### PR DESCRIPTION
**Pull request by tnmtechnologies**
digit and its java code (JavaJaxrs/resteasy)

The JavaJaxrs/resteasy/enumOuterClass.mustache and
JavaJaxrs/resteasy/enumClass.mustache files were not inline with those
in JavaJaxrs directory.

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.3.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

#1051 
fix wrong matching between yaml enum value starting with a digit and its java code (JavaJaxrs/resteasy)

The JavaJaxrs/resteasy/enumOuterClass.mustache and
JavaJaxrs/resteasy/enumClass.mustache files were not inline with those
in JavaJaxrs directory.

@jmini

### CODE REVIEW

**Comment by tnmtechnologies** [comment]
@jmini please could you tell me what is wrong? Thanks

**Comment by tnmtechnologies** [comment]
How can I help in order to have successfull checks?
Everything is ok on my computer.
Thanks.

**Comment by tnmtechnologies** [comment]
@jmini please, might we expect this PR in 3.3.2?

**Comment by tnmtechnologies** [comment]
@wing328 might we expect this PR in 3.3.2?

**Comment by tnmtechnologies** [comment]
@wing328  might we expect this PR in 3.3.2?

**Comment by tnmtechnologies** [comment]
@wing328  might we expect this PR in 3.3.2?

**Comment by wing328** [comment]
@tnmtechnologies are you free for a quick chat? Please reach me via the email address in my github profile.

**Comment by wing328** [comment]
To answer your question, yes I want to include your fix.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by tnmtechnologies** [comment]
Hello William,

I am sorry but I didn't succeed to do an interactive rebase in order to put
my github profile email address for my commits.
I tried with 2 versions of eclipse. I was able to update the 2 first
commits but then after that, eclipse provided a wrong commit to edit.
I also tried git bash but it failed too for other reasons.

It would be very nice from you if you could do it for me.
My github profile email address is tnmtechnologies@gmail.com and my github
profile name is TNM Technologies.

I understood that I forgot to set my user email and user name for this
repository in eclipse. The default one (the one I used at my office) was
used.
I fixed it now.

Thank you for your help.

Kind regards,

Michel Trefcon








Le mar. 23 oct. 2018 à 11:14, William Cheng <notifications@github.com> a
écrit :

**Comment by wing328** [comment]
@tnmtechnologies I've cherry-picked your commit and created https://github.com/OpenAPITools/openapi-generator/pull/1372 instead so closing this one.

**Pull request closed without merging**
