### PR TITLE
Fix Kotlin default values for strings and arrays

### LINKED ISSUE #9844: [BUG]  [Kotlin-spring] Multiple errors in model default values
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating models with default values, I have come across multiple bugs.
Arrays: default value is not respected
Strings: Is generated with &quot; instead of " (double quote), which makes it not compile
Enums: Inline enums are generated with the wrong names, which makes it not compile. Note this one has a relatively easy workaround, define enums as separate schemas.

##### openapi-generator version

openapigenerator: 5.1.1
kotlin: 1.5.10
gradle: 7.1

##### OpenAPI declaration file content or url

Minimal schema
```json
      "Test": {
        "title": "TestObject",
        "type": "object",
        "required": [  "testArray"  ],
        "properties": {
          "stringDefault": {
            "type": "string",
            "default": "test"
          },
          "testArray": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "testArrayOptional": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "testEnum": {
            "type": "string",
            "enum": [  "A", "B", "C"  ],
            "default": "C"
          }
        }
      }

```

Results

```kotlin
data class Test(

    @field:JsonProperty("stringDefault", required = true) val stringDefault: kotlin.String = &quot;test&quot;,

    @field:JsonProperty("testArray", required = true) val testArray: kotlin.collections.List<kotlin.String>,

    @field:JsonProperty("testArrayOptional") val testArrayOptional: kotlin.collections.List<kotlin.String>? = null,

    @field:JsonProperty("testEnum") val testEnum: Test.TestEnum? = TestEnumEnum.c
) {

    enum class TestEnum(val value: kotlin.String) { a("A"),  b("B"), c("C") }
}

```

##### Generation Details
Using gradle
```groovy
task generateExample(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    inputSpec = "$rootDir/test.json"
    generatorName = "kotlin-spring"
    outputDir = "$buildDir/generated/testing"
}
```

##### Related issues/PRs

Might be related to https://github.com/OpenAPITools/openapi-generator/pull/8373

### PR DESCRIPTION
**Pull request by sigand**
To close #9844
 
This PR fixes two of the three issues mentioned in the linked issue. Enum default values were not a priority, as there is a reasonable workaround. All changes were tested with a minimal spec included below.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jimschubert @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

### CODE REVIEW

**Comment by sigand** [comment]
`json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Test file",
    "version": "1"
  },
  "paths": { },
  "components":{
    "schemas": {
      "Test": {
        "title": "TestObject",
        "type": "object",
        "required": [
          "testArray", "stringDefault"
        ],
        "properties": {
          "stringDefault": {
            "type": "string",
            "default": "test"
          },
          "testArray": {
            "type": "array",
            "default": [],
            "items": {
              "type": "string"
            }
          },
          "testArrayOptional": {
            "type": "array",
            "default": ["1"],
            "items": {
              "type": "string"
            }
          },
          "testArrayInt": {
            "type": "array",
            "default": [1, 2],
            "uniqueItems": true,
            "items": {
              "type": "integer"
            }
          }
      }
    }
  }
}
`

**Comment by 4brunu** [comment]
Does this PR overlap with https://github.com/OpenAPITools/openapi-generator/pull/9849?

**Comment by sigand** [comment]
> Does this PR overlap with #9849?

Yeah, somewhat.
Same solution for the String quotation problem.  Though it is in different templates.
For the unique items, this one is concerned with default values, while the other seems to be concerned with the data type itself.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Tested kotlin-spring generator with default values for string,  array of string and the result is good.

**Comment by sigand** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

honestly, I don't care :)

**Pull request merged**
