### PR TITLE
[Go] support problem details HTTP API

### PR DESCRIPTION
**Pull request by houqp**
Based on https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00, the content-type would be `application/problem+json`

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by houqp** [comment]
@antihax @bvwells @grokify @kemokemo @bkabrda, could you help review this PR?

**Comment by kemokemo** [comment]
@houqp Thank you so much for your PR! 😄  LGTM!

**Comment by houqp** [comment]
@wing328 could you help take a look at this PR?

**Comment by wing328** [comment]
@houqp just merged. Sorry for the delay. Thanks for the contribution.

**Pull request merged**
