### PR TITLE
Fix Issue 16385

### PR DESCRIPTION
**Pull request by jimsimon-wk**
Enumeration comparison in Java using equalsIgnoreCase when String

fix https://github.com/OpenAPITools/openapi-generator/issues/16385

Pretty much a duplicate of https://github.com/OpenAPITools/openapi-generator/pull/15273, except for Java generator

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09)

### CODE REVIEW

**Comment by jimsimon-wk** [comment]
@wing328 Would you be interested in taking a look at this issue/PR?

**Review by welshm — COMMENTED** [review]
Does none of the generated code change?

I'm surprised this works without needing to update any templates

**Comment by welshm** [comment]
Looks like all relevant mustache changes are captured in https://github.com/OpenAPITools/openapi-generator/pull/15273/files

**Review by welshm — APPROVED** [review]

**Comment by jimsimon-wk** [comment]
> Looks like all relevant mustache changes are captured in https://github.com/OpenAPITools/openapi-generator/pull/15273/files

Yep, that's correct! This just passes through the config to the java generator

**Pull request merged**
