### PR TITLE
Abstraction for files (#6715)

### PR DESCRIPTION
**Pull request by MosheElisha**
1. Add a new "useAbstractionForFiles" config option that uses abstract objects instead of files where files are needed. With this option, the user will be able to use byte array or input stream instead of java.io.File.
The new config option is currently supported only by the resttemplate library.

2. Fix the dir path mentioned in the pull request template.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by MosheElisha** [comment]
Hi @wing328,

As you know this is my first PR to this project. The `ci/circleci: build` failed at the beginning but I don't think it is related to my changes. Can you please advise?

**Comment by wing328** [comment]
@MosheElisha Thanks for the PR but it looks like a rebase failure resulting in commits not authored by you included in this PR.

I would recommend open a new PR by cherry-picking the commits authored by you.

**Comment by MosheElisha** [comment]
@wing328 Yes. I saw that. I will create a new PR. Thank you.

**Comment by MosheElisha** [comment]
Replaced by https://github.com/OpenAPITools/openapi-generator/pull/6912

**Pull request closed without merging**
