### PR TITLE
[C++] Adjust the names (script, sample folder, generator) to lang option

### PR DESCRIPTION
**Pull request by ackintosh**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Related issue: https://github.com/OpenAPITools/openapi-generator/issues/138#issuecomment-394576614

This PR prefixes the scripts/sample folders/generators with `cpp-` to avoid users/contributors be confused.

### CODE REVIEW

**Comment by ackintosh** [comment]
[Technical Committee](https://github.com/openapitools/openapi-generator/#members-of-technical-committee): @ravinikam  @stkrwork  @fvarose @etherealjoy  @martindelille

**Comment by MartinDelille** [comment]
Looks good to me too! Thanks for the contribution!

**Comment by ackintosh** [comment]
Oh, I noticed that the scripts also exists under [bin/openapi3](https://github.com/OpenAPITools/openapi-generator/tree/master/bin/openapi3). 👀

**Comment by etherealjoy** [comment]
Looks good to me.

**Comment by stkrwork** [comment]
Did you also look at the restbed and pistache scripts, our C++ servers?

**Comment by ackintosh** [comment]
Oh... I didn't know that restbed and pistache is C++ generator as I'm pretty new to C++. 💦 Thanks for pointing it out. ✨

**Comment by etherealjoy** [comment]
We can do the pistache and restbed with a different PR. I also forgot.

**Comment by ackintosh** [comment]
I'll file a different PR fixes the issue. 💪

**Pull request merged**
