### PR TITLE
C additional properties fix #4289

### LINKED ISSUE #4289: [BUG][C] errors in supporting additionalProperties in C client
#### Bug Report Checklist

- [ X ] Have you provided a full/minimal spec to reproduce the issue?
- [ X ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ X ] What's the version of OpenAPI Generator used?
- [ X ] Have you search for related issues/PRs?
- [ X ] What's the actual output vs expected output?

##### Description

I tried to compile the declaration reported below. The results was:

/mnt/hgfs/shared/clientC/model/service_query_form_dto.c:25:15: error: ‘localKeyValue’ undeclared (first use in this function); did you mean ‘localMapKeyPair’?
         free (localKeyValue->key);
               ^~~~~~~~~~~~~
               localMapKeyPair

##### openapi-generator version

commit 4543c210304c25a551a6a9c50d330dfd6f3ca462 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: sullis <github@seansullivan.com>
Date:   Sat Oct 26 21:10:55 2019 -0700

##### OpenAPI declaration file content or url

https://gist.github.com/michelealbano/4ecf5b628a5d7eb305a3eea5da16ff4a

##### Command line used for generation

java -jar openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g c -i cproblems.json -o clientC --additional-properties=swaggerDocketConfig=true

##### Steps to reproduce

java -jar openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g c -i cproblems.json -o clientC --additional-properties=swaggerDocketConfig=true
cd clientC
mkdir build
cd build
cmake ..
make

##### Related issues/PRs

N/A

##### Suggest a fix

In model-body.mustache, change "localMapKeyPair" on line 258 into "localKeyValue".

### PR DESCRIPTION
**Pull request by michelealbano**
Solved #4289.

### PR checklist

- [ X ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ X ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ X ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
cc @zhemant

**Comment by wing328** [comment]
Travis CI reports the following error:
```
[ 78%] Building C object CMakeFiles/openapi_petstore.dir/api/PetAPI.c.o
[ 85%] Building C object CMakeFiles/openapi_petstore.dir/api/StoreAPI.c.o
[ 92%] Building C object CMakeFiles/openapi_petstore.dir/api/UserAPI.c.o
[100%] Linking C shared library libopenapi_petstore.so
[100%] Built target openapi_petstore
./build-and-test.bash: line 19: ./unit-manual-PetAPI: No such file or directory
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (pet-test) on project CPetstoreClientTests: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
```

**Comment by michelealbano** [comment]
> Travis CI reports the following error:
> 
> ```
> [ 78%] Building C object CMakeFiles/openapi_petstore.dir/api/PetAPI.c.o
> [ 85%] Building C object CMakeFiles/openapi_petstore.dir/api/StoreAPI.c.o
> [ 92%] Building C object CMakeFiles/openapi_petstore.dir/api/UserAPI.c.o
> [100%] Linking C shared library libopenapi_petstore.so
> [100%] Built target openapi_petstore
> ./build-and-test.bash: line 19: ./unit-manual-PetAPI: No such file or directory
> [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (pet-test) on project CPetstoreClientTests: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR] 
> ```

How can I solve this? What is unit-manual-PetAPI?

**Comment by wing328** [comment]
I think those are unit tests. I noticed that you've commented out part of the CMakefile: https://github.com/OpenAPITools/openapi-generator/pull/4292/files#diff-bc97688208c58aee3233d8e276aef6ecR67

Not sure if it's related.

**Comment by michelealbano** [comment]
I re-cloned a fresh master, mvn install is fine, when I do ./bin/c-petstore.sh the amples/client/petstore/c/CMakeLists.txt gets like win328 says, thus samples/client/petstore/c/build-and-test.bash will try to execute files that are not compiled.

I will open a bug report.

**Comment by zhemant** [comment]
I know how to fix this, I fixed it in the one merge request, but couldnt update some other stuff so it was closed. I will create another merge request with a fix

**Comment by zhemant** [comment]
#4312 should fix the issue

**Comment by michelealbano** [comment]
Thank you zhemant!

**Comment by zhemant** [comment]
@michelealbano are you on gitter? May be we could add more updated parameters support to C if you are interested in helping out.

**Comment by michelealbano** [comment]
I am very interested. I have opened an issue regarding enums, and I will submit a PR tomorrow. I should also add _with_HTTP_headers methods in the future

**Comment by zhemant** [comment]
I will also recommend modifying the values in the enum to something like {{projectName}}_{{classVarName}}_{{{value}}} which will make them unique in the complete project, because when you have two enums with the same values, C creates problem in compiling.  I have faced these issues.

**Comment by michelealbano** [comment]
There is also the matter of the enum itself, since it generates _ToString and _FromString functions. Let us talk on gitter.

**Comment by wing328** [comment]
> There is also the matter of the enum itself, since it generates _ToString and _FromString functions. Let us talk on gitter.

Please use Slack instead as we've made the switch already.

**Comment by michelealbano** [comment]
I did another pull request with a cleaner set of commits

**Pull request closed without merging**
