### PR TITLE
typescript-angular: add providedIn for Angular 9+ 

### PR DESCRIPTION
**Pull request by UnleashSpirit**
Adding new option, providedIn, for generator typescript-angular
Keep providedInRoot for backward compatibility but mark as deprecated for Angular 9+

fix: #6432

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by UnleashSpirit** [comment]
technical committee for typescript
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Review by macjohnny — APPROVED** [review]
LGTM

**Comment by macjohnny** [comment]
@UnleashSpirit thanks for your contribution!
please re-generate the samples

**Comment by UnleashSpirit** [comment]
> @UnleashSpirit thanks for your contribution!
> please re-generate the samples

Hmm ok, now I guess I need some explanation.
I just ran `bin / generate-samples.sh` and git status gives me 104 files to commit.
But none of them show any change inside?

**Comment by macjohnny** [comment]
> Hmm ok, now I guess I need some explanation.
> I just ran `bin/generate-samples.sh` and git status gives me 104 files to commit.
> But none of them show any change inside?

simply run
```
mvn clean package
bin/generate-samples.sh
```

**Comment by UnleashSpirit** [comment]
Ok I figured out why, I'm on windows and newline are a mix of  LF & CRLF currently.
Using GitBash to generate-samples gives me 334 files changes
Using WSL to generate-samples gives me 104 files changes
What do I do ? ^^

**Comment by macjohnny** [comment]
commit all changed files with WSL

**Comment by UnleashSpirit** [comment]
> commit all changed files with WSL

Ok so I changed my mind, I clone again my repo with WLS so only LF newline.
Run mvn clean package then bin/generate-samples.sh, and guess what ? Nothing change ! (except the sample related to your remark)

**Pull request merged**
