### PR TITLE
[Golang][client] fix file suffix for _test.go

### PR DESCRIPTION
**Pull request by grokify**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@antihax
@bvwells

### Description of the PR

Fixes https://github.com/OpenAPITools/openapi-generator/issues/448

Adds an extra `_` suffix to string returned by `toModelFilename` and `toApiFilename` if the suffix is `_test` resulting in a model or API file that ends in `_test.go` which is ignored by the Go compiler.

`samples/client/petstore/go/go-petstore` was rebuilt from scratch by `bin/go-petstore.sh`, aside from `samples/client/petstore/go/go-petstore/api/swagger.yaml` which is useful. May be worthwhile to have that auto-added along with `openapi.yaml`.

### CODE REVIEW

**Comment by antihax** [comment]
looks good. thanks

**Comment by grokify** [comment]
All tests passed, but not at the same time yet.

Occasionally, Shippable runs into a race condition and Travis CI times out.

Here are example messages:

**Shippable** - [Build #1192.1](https://app.shippable.com/github/OpenAPITools/openapi-generator/runs/1192/1/console)

```
[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.15.v20160210:start (start-jetty) on project spring-mvc-j8-localdatetime: Failure: ShutdownMonitorThread already started -> [Help 1]
```

**Travis CI** - [Build #1135](https://travis-ci.org/OpenAPITools/openapi-generator/builds/399806680)

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by grokify** [comment]
@antihax @bvwells @wing328 

All tests are passing with no conflicts.

**Comment by wing328** [comment]
Shippable CI error is not related to the change so merging this into master. Thanks for the enhancement.

**Pull request merged**
