### PR TITLE
Move online gen from jersey to spring boot

### PR DESCRIPTION
**Pull request by cbornet**
Move the online codegen from jersey to spring boot
The stub was generated with openapi-generator from the existing openAPI def. Some little things still  needed to be done by hand.
Command line used:
```
java -jar ../../modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -l spring -i /tmp/swagger.json --group-id org.openapitools --artifact-id openapi-generator-online -DhideGenerationTimestamp=true,delegatePattern=true
```

I need to do some polishing:
- [ ] Swagger ui description, remove references to swagger
- [ ] Cleaning ot the OAS def generated by Springfox (esp. "spec", JsonNode, File, Resource, URI, ...)
- [ ] Context path / API serving tuning
- [ ] Dockerfile
- [ ] Integrate the maven plugin to generate the endpoints from an OAS file (interfaceOnly)
- [ ] Other ?

@OpenAPITools/openapi-generator-core-team Can you test and give your feedback ?

### CODE REVIEW

**Comment by cbornet** [comment]
Removing 500+ lines of code 😎

**Comment by cbornet** [comment]
Note: the error response body have changed and are now the standard ones from Spring Boot. I believe that it's not a big issue since most clients should only use the Http status code.

**Comment by wing328** [comment]
@cbornet thanks. Let me test it out.

**Comment by wing328** [comment]
Did some tests and worked as expected. I'll add the Dockerfile in a separate PR.

**Pull request merged**
