### PR TITLE
[go] respect initialisms or acronyms in names

### LINKED ISSUE #4833: [BUG][Go] respect initialisms or acronyms in names
#### Description

Names in generated Go clients do not respect recommended [style](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

```
Url -> URL
Id -> ID
Http -> HTTP
```

##### openapi-generator version

all

##### Related issues/PRs

https://github.com/golang/go/wiki/CodeReviewComments#initialisms

##### Suggest a fix

Override `GoExperimentalCodegen.toParamName` method.

### PR DESCRIPTION
**Pull request by tomi77**
Resolved #4833

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Please PM me via Slack when you've time.

**Comment by tomi77** [comment]
@wing328 Sorry, I don't have Slack. Maybe mail/Hangout? tomasz[dot]rup[at]gmail[dot]com

**Comment by wing328** [comment]
Sure let's do it via Google Hangout tomorrow (Friday). Please ping me (wing328hk@gmail.com) when you're free. My timezone is +0800.

**Comment by displague** [comment]
Is `Exeptions` typo'd before this PR? (missing `c`)

Does this functionality, changing client APIs, need to be behind a generator user flag?

**Comment by yuki2006** [comment]
Any updates?

**Comment by wing328** [comment]
we've added name mapping support to the go generators which should allow users to address issues mentioned in this PR: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#name-mapping

please give it a try with the latest master.

**Pull request closed without merging**
