### PR TITLE
[python] client use length1 required enums

### PR DESCRIPTION
**Pull request by spacether**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

### Description of the PR

This PR will close out the issues: 
- Python client, use given values for required enums of length 1: https://github.com/OpenAPITools/openapi-generator/issues/1812 
- Date and DateTime enums do not work in many languages: https://github.com/OpenAPITools/openapi-generator/issues/2404

When a user defines a required parameter and sets a enum with length==1 value for that parameter, they are defining the constant value that that parameter should have. This PR loads that value into models and endpoints so it does not need to be explicitly passed by users of the autogenerated python libraries.

Some generators were not handling generating date or datetime enums correctly.
Those generators and mustache files have been updated to include date and datetime enums.

### CODE REVIEW

**Comment by spacether** [comment]
Java gurus: @bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)
Do you have any insight into these CircleCI and Shippable errors?
They say: `java.lang.String cannot be converted to java.util.Date`

I have looked into the code here and it is difficult to understand.
As far as I can tell for jaxrs code generators we are inheriting 5 levels of depth for the code generator class:

5. modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSCXFCDIServerCodegen.java
4. modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaJAXRSSpecServerCodegen.java
3. modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaJAXRSServerCodegen.java
2. modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
1. modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
What is the difference between typeMapping and importMapping?
Do you have any ides on how to fix this?
Do I need to add more specific typeMapping/importMappings?

**Comment by wing328** [comment]
`typeMapping` is for the mapping between OpenAPI Type (e.g. string) and language type (e.g. str)

`importMapping` is to determine what needs be imported if a certain type is used, e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/api.mustache#L12 uses the import mapping defined in the generator: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L428

(Not all language needs import mapping. Ruby client generator is a good example)

Hope this helps.

**Comment by wing328** [comment]
For the CI failure, I'll take a look when the jobs finish.

**Comment by spacether** [comment]
> For the CI failure, I'll take a look when the jobs finish.

Thanks for the description @wing328, it helped.
The issue was that I was not adding the word new when instantiating a java.util.Date. I fixed that issue and have Date and DateTime enums working in Java now. Next I need to fix Elm and csharp generators.

**Comment by spacether** [comment]
The scope of this has grown too large. I will close this and re-submit it.
The new PR will not fix date and datetime enums in other languages.

**Pull request closed without merging**
