### PR TITLE
[Kotlin][Spring]ctbarnev_bugfix-13488-remove-request-mapping-from-for-Kotlin-spring-c…

### PR DESCRIPTION
**Pull request by ctbarnev**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).

  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. @jimschubert (2017/09) [❤️](https://www.patreon.com/jimschubert), @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)

Description:
Running application with generated Feign client fails with this error:  @RequestMapping annotation not allowed on @FeignClient interfaces.

Configuration:
```
generatorName: kotlin-spring
inputSpec: ./openapi.yaml
outputDir: ./generated/spring
additionalProperties:
  library: spring-cloud
  useTags: true
  skipDefaultInterface: true
  gradleBuildFile: false
  useSpringBoot3: true
```

Currently generated interface:
```
@Validated
@RequestMapping("\${api.base-path:/api/test/v1}")
interface TestApi {
```

After this fix generated interface:
```
@Validated
interface TestApi {
```

With this fix in place it's possible to use the generated client from the Kotlin-Spring generator with library Spring-Cloud.

This fix is inspired by this MR https://github.com/OpenAPITools/openapi-generator/pull/13546 and fixes [this issue](https://github.com/OpenAPITools/openapi-generator/issues/13488) also for Kotlin-Spring instead only for Spring.

### CODE REVIEW

**Comment by ctbarnev** [comment]
@wing328 can you maybe have a look?

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
can you please merge the latest master into your branch as those CI failures already addressed in the master?

**Comment by ctbarnev** [comment]
Just merged master into my branch, however sill one test fails: https://github.com/OpenAPITools/openapi-generator/actions/runs/5409565359/jobs/9830019133

I cannot find a connection between my changes and this failing build: Nodejs.org didn't respond fast enough causing one build to fail. Can we retry somehow? Of maybe increase timeouts if this happens too often?

**Comment by wing328** [comment]
restarted and all good

**Pull request merged**
