### PR TITLE
feat(cpp-ue4): additionalproperties modelNameCamelize, modelFilenameCamelize

### PR DESCRIPTION
**Pull request by powerumc**
Issue #17981 
Following @wing328 

I added additionalProperties of `modelNameCamelize` and `modelFilenameCamelize`.

If you set `modelNameCamelize` to true, `FT1Model_HelloWorldRequest -> FT1ModelHelloWorldRequest`.
And you set `modelNameCamelize` to false, `FT1Model_HelloWorldRequest -> FT1Model_HelloWorldRequest`.

Also `modelFilenameCamelize` is similar.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR. cc @Kahncode

**Comment by wing328** [comment]
> If you set modelNameCamelize to true, FT1Model_HelloWorldRequest -> FT1ModelHelloWorldRequest.
And you set modelNameCamelize to false, FT1Model_HelloWorldRequest -> FT1Model_HelloWorldRequest.

shouldn't this be done without using the option as I assume the file name and the class name should be in Pascal Case?

**Comment by powerumc** [comment]
> > If you set modelNameCamelize to true, FT1Model_HelloWorldRequest -> FT1ModelHelloWorldRequest.
> > And you set modelNameCamelize to false, FT1Model_HelloWorldRequest -> FT1Model_HelloWorldRequest.
> 
> shouldn't this be done without using the option as I assume the file name and the class name should be in Pascal Case?

I also think it's PascalCase.
However, the source code uses the word `camelize()`.
https://github.com/OpenAPITools/openapi-generator/pull/17984/commits/52c827093c70625edfe1fd17ccf72ae374859aa4#diff-ff96727168c2b9d22928b2b69cf6fc14d0ef4d3da9e6d22459ba544c4c31f855R364

**Comment by powerumc** [comment]
> > If you set modelNameCamelize to true, FT1Model_HelloWorldRequest -> FT1ModelHelloWorldRequest.
> > And you set modelNameCamelize to false, FT1Model_HelloWorldRequest -> FT1Model_HelloWorldRequest.
> 
> shouldn't this be done without using the option as I assume the file name and the class name should be in Pascal Case?

@wing328 Did I understand and answer your question correctly?

**Comment by Kahncode** [comment]
Hello, taking a fresh look at this PR again. Out of curiosity @powerumc why do you want to change the outpout result to keep the underscores? I understand aesthetic preferences, but in this case, does it really matter? The generator attempts to follow UE's coding convention which discourage using underscores.

In general, I tend to think that less is more, and it would be impossible to adhere to all the different preferences on coding style that each project might have. The decision was made to follow unreal's guidelines and generally to treat generated code as foreign, third party APIs rather than home grown code. In that light I am generally not in favor of this change. Please note that in my project we also have different coding conventions that the generator does not produce, however this code is the closest to Unreal code I could make, which I believe provides the best for the majority of developers.

**Comment by powerumc** [comment]
@Kahncode 
I agree with your comments and the UE4 guidelines. However, I wish there were options for detailed changes. For example, `*.h` files are output in the `Public` directory, and `*.cpp` files are output in the `Private` directory. I understand that's a standard guideline, but sometimes we need the output to be in one directory. I agree with your standard guidelines and would be very happy if flexible options were provided based on those guidelines. 

Thank you for your comments on this PR, and it would be great to discuss this again in the future.

**Comment by Kahncode** [comment]
Thanks for your understanding, and I'm always happy to discuss of course.

Out of curiosity, why would you need the output files in a different
folder? Ultimately the module.cs controls it's own folder structure and
public includes via PublicIncludeFiles so the location of header files is
transparent to the code that consumes the module.

This is also what you'd expect from a third party unreal module, and what
you will often encounter. What issue is it causing in your case?


Cheers,

**Comment by powerumc** [comment]
@Kahncode 
Please understand that I cannot tell you much about our project.
Some of the various UE guidelines are followed, and there are rules and guidelines defined within the project.

Thank you again for joining the discussion.

**Pull request closed without merging**
