### PR TITLE
Elm refactoring

### LINKED ISSUE #310: [elm-client] Recursive type aliases
A recursive data structure will lead to elm code, which is not being parsed.
The main issue and how to workaround is described here: https://github.com/elm/compiler/blob/0.18.0/hints/recursive-alias.md

```json
    "tags": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
        },
        "children": {
          "type": "array",
          "items": { "$ref": "#/definitions/tags" }
        }
      }
    }
```

Will generate this:

```elm
type alias Tags =
    { id : UUID
    , children : List Tags
    }


tagsDecoder : Decoder Tags
tagsDecoder =
    decode Tags
        |> required "id" uUIDDecoder
        |> required "children" (Decode.list tagsDecoder)


tagsEncoder : Tags -> Encode.Value
tagsEncoder model =
    Encode.object
        [ ( "id", uUIDEncoder model.id )
        , ( "children", (Encode.list << List.map tagsEncoder) model.children )
        ]
```
But should be something like this, where `Decode.lazy` is used and a type definition for the recursive list:

```elm
type alias Tags =
    { id : UUID
    , children : Children
    }


type Children
    = Children (List Tags)


childrenToTags : Children -> List Tags
childrenToTags (Children tags) =
    tags


tagsDecoder : Decoder Tags
tagsDecoder =
    decode Tags
        |> required "id" uUIDDecoder
        |> required "children"
            (Decode.map Children (Decode.list (Decode.lazy (\_ -> tagsDecoder))))


tagsEncoder : Tags -> Encode.Value
tagsEncoder model =
    Encode.object
        [ ( "id", uUIDEncoder model.id )
        , ( "children", (Encode.list << List.map tagsEncoder) (childrenToTags model.children) )
        ]
```

OpenAPI spec version: 0.4.0
Generator version 3.0.1

### PR DESCRIPTION
**Pull request by eriktim**
Major refactoring of the Elm generator. See [this new guide](http://eriktim.github.io/openapi-elm) for more background.

Closes #310, #1589, #3578 and #4583.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@wing328 Can you have a look? And would it be possible to merge this without squashing?

### CODE REVIEW

**Comment by wing328** [comment]
@eriktim I've sync'd changes from master to 5.0.x and resolved some merge conflicts related to the Elm client generator. Please review the latest code in the 5.0.x branch to see if the merge looks good to you.

**Comment by eriktim** [comment]
@wing328 thanks for the heads up. I see you restored `ElmClientCodegenTest.java` but that's OK, I already removed in the PR I just created.

**Comment by wing328** [comment]
I'll remove that too in the latest 5.0.x branch as it's causing tests to fail.

**Comment by andys8** [comment]
Awesome work

**Comment by vincentnavetat** [comment]
Wonderful :D

**Pull request merged**
