### PR TITLE
[swift5] Fix Xcode 16 compilation crash with Extensions.swift generation

### PR DESCRIPTION
**Pull request by lilidotshi**
This PR aims to address https://github.com/OpenAPITools/openapi-generator/issues/19459 with the solution provided by @borsosbe.

Mentioning swift tech commitee: @dydus0x14 @4brunu @jgavris @ehyche @Edubits @jaz-ah for visibility into the issue.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by aehlke** [comment]
This is important to get merged

**Comment by borsosbe** [comment]
@lilidotshi Great, thanks!

**Review by 4brunu — APPROVED** [review]
Thanks for your PR

**Comment by 4brunu** [comment]
Hi @tcollins590 can you elaborate on the problem you are having?

**Comment by lilidotshi** [comment]
@4brunu I noticed that Xcode 16's release notes say that they have officially fixed this issue, do you see any reason to revert this PR back to its original?

**Comment by 4brunu** [comment]
If reverting this PR fixes the issue and works with Xcode 16, for me we can revert this.
Can someone try the old code with Xcode 16 to confirm that reverting this PR fixes the issue?

**Comment by r3econ** [comment]
I tried it out in the morning. The old code does not work with Xcode 16.

**Comment by 4brunu** [comment]
And what is the issue with the new code?
Can someone give more details on that?

**Comment by lilidotshi** [comment]
Also, what version are you using @tcollins590. @4brunu has a release with this patch even come out yet?

**Comment by 4brunu** [comment]
No, not yet

**Pull request merged**
