### PR TITLE
[dart][dart-dio] Enum fixes specific to Dart DIO

### PR DESCRIPTION
**Pull request by kuhnroyal**
* fix wrong escaped built_value serializer names
* prevent enum name collisions in inlined enums by prefixing the private built_value instances with the enum class name. This prevents clashes when multiple inline enums contain the same value - for example `EnumTest`.  No breaking changes here as all the changed fields/references are private and automatically re-generated with built_value.

There is still a lot wrong with enums but this is a small step.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by kuhnroyal** [comment]
FYI @agilob @josh-burton

**Comment by kuhnroyal** [comment]
CC @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12)

**Comment by agilob** [comment]
tech committee  of dart is dead, it's @sbu-WBT @agilob  and @noordawod now

and you

**Comment by kuhnroyal** [comment]
This should fix https://github.com/OpenAPITools/openapi-generator/issues/8097

**Review by josh-burton — APPROVED** [review]

**Pull request merged**
