### PR TITLE
[typescript] Adding Custom Agent Support for fetch call

### PR DESCRIPTION
**Pull request by davidgamero**
Adding `agent: http.Agent | https.Agent | undefined` instance variable on the `RequestContext` class as well as the following methods:

```
setAgent(agent: http.Agent | https.Agent)
getAgent() : http.Agent | https.Agent | undefined
```

Then, the isomorphic fetch implementation would call `getAgent()` to pass the value into the `agent` option on the `fetch` call in `isomorphic-fetch.ts`

Implements #11394

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov

### CODE REVIEW

**Review by macjohnny — COMMENTED** [review]
Thanks for the contribution, looks good.
Can you please revert the deleted files and update the samples?

**Comment by davidgamero** [comment]
yep merging master back in now

**Comment by macjohnny** [comment]
@TiFu are you fine with this change?

**Comment by davidgamero** [comment]
ended up excluding the web fetch since the lib doesn't list agent support

**Review by TiFu — APPROVED** [review]
LGTM! Thank you for the PR! :)

**Pull request merged**
