### PR TITLE
[Go-Server] Add support for DateTime Query Parameters

### PR DESCRIPTION
**Pull request by icubbon**
Add support to the Go-Server template to parse DateTime parameters in the Query and as a List in the Query.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@lwj5 @wing328

### CODE REVIEW

**Comment by lwj5** [comment]
Hi @icubbon 

Thank you for the PR. As there are currently no cases with DateTime in the generation sample, it is difficult to see how the generated files will look.

Would you be able to add a new route in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/go-server/petstore.yaml

then regenerate the code for go-server. 

Let us know if you need any help with generation

**Comment by icubbon** [comment]
> Hi @icubbon
> 
> Thank you for the PR. As there are currently no cases with DateTime in the generation sample, it is difficult to see how the generated files will look.
> 
> Would you be able to add a new route or add a datetime field somewhere in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/go-server/petstore.yaml
> 
> then regenerate the code for go-server.
> 
> Let us know if you need any help with generation

Hi @lwj5, thank you for looking at these PRs. I added an example but since the changes were done in the `router.mustache` file, the generated `api-controller` file doesn't have any meaningful change as that code should look the same.

**Comment by icubbon** [comment]
> Hi @icubbon
> 
> Thank you for the PR. As there are currently no cases with DateTime in the generation sample, it is difficult to see how the generated files will look.
> 
> Would you be able to add a new route or add a datetime field somewhere in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/go-server/petstore.yaml
> 
> then regenerate the code for go-server.
> 
> Let us know if you need any help with generation

Good call with the example! An import for `time` was missing in the `api-controller.mustache` template but was being added in my personal work setup with a call to `goimports`.
I had to re-arrange where the parsing was done as the `api-controllers.mustache` template didn't have good support for dynamic importing.

**Review by lwj5 — COMMENTED** [review]
LGTM, just need to update the above

**Comment by lwj5** [comment]
Will need your help to resolve the conflict before we can merge

**Comment by icubbon** [comment]
Conflicts resolved, looks like the generated examples have both the Enum changes and the DateTime changes as well.

**Review by lwj5 — APPROVED** [review]
Lgtm, @wing328 good to merge

**Pull request merged**
