### PR TITLE
[csharp-netcore] renamed async methods to end with async

### PR DESCRIPTION
**Pull request by devhl-labs**
Renaming the api class methods from `GetModelAsyncWithHttpInfo` to `GetModelWithHttpInfoAsync` to conform with the async suffix.  I tried using bash to run `./generate-samples.sh`, but it threw an error at line 6 `cd: $'/mnt/e/repos/openapi-generator/bin\r': No such file or directory` so I update the samples without it.  Also really not sure if it is right that there are 75 files changes, as I only made a very small change.

@mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02)

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
> to conform with the async suffix.

@devhl-labs is that based on some style guides? If yes, can you share the link?

**Comment by devhl-labs** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model

There is a heading there labeled Naming Convention that says end with
async.  Existing async methods from MS and others follow this convention.

**Comment by wing328** [comment]
@devhl-labs thanks for sharing the link.

Can you please resolve the merge conflicts when you've time?

**Comment by devhl-labs** [comment]
Yes

**Comment by wing328** [comment]
```
Api\UserApi.cs(1387,20): warning CS1571: XML comment has a duplicate param tag for 'cancellationToken' [C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
Api\PetApiTests.cs(209,31): error CS1061: 'PetApi' does not contain a definition for 'GetPetByIdAsyncWithHttpInfo' and no accessible extension method 'GetPetByIdAsyncWithHttpInfo' accepting a first argument of type 'PetApi' could be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj]
```

When you've time, can you update the tests as well to use the new method name?

**Comment by devhl-labs** [comment]
Im not sure where the test is.  I've looked for it but haven't found it yet.

**Comment by wing328** [comment]
@devhl-labs you can find it under the folder `openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj`

The subfolder and file name should be `Api\PetApiTests.cs`

**Comment by devhl-labs** [comment]
I can't find the mustache template for that generated file.

**Comment by wing328** [comment]
The template is here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp-netcore/api_test.mustache

but the test was written manually so you will need to update PetApiTests.cs directly.

**Comment by devhl-labs** [comment]
I did a clean install and update samples, and now I have untracked files.

**Comment by wing328** [comment]
Pushed https://github.com/OpenAPITools/openapi-generator/commit/57ee092abda3423fcbe28fafcafa422883526f19 to update the samples and the CI tests pass.

**Pull request merged**
