### PR TITLE
fix request.on_complete message when tempfile is nil

### LINKED ISSUE #5744: [BUG] [Ruby] client raises error on file download
##### Description

Hey! There is a method `def download_file(request)`, which should write a message to the log when request completes with tempfile path. But if request fails, there are no tempfile:

```ruby
    def download_file(request)
      # ...
      request.on_complete do |response|
        tempfile.close if tempfile
        @config.logger.info "Temp file written to #{tempfile.path}, please copy the file to a proper folder "\
                            "with e.g. `FileUtils.cp(tempfile.path, '/new/file/path')` otherwise the temp file "\
                            "will be deleted automatically with GC. It's also recommended to delete the temp file "\
                            "explicitly with `tempfile.delete`"
      end
    end
```

##### openapi-generator version

latest master 94152c4d356ab83a25861e5191902c30b0c10574

##### Steps to reproduce

1. Generate Ruby (Typhoeus or Faraday, doesn't matter) client
2. Make API, which returns error or which is unavailable
2. Try to download file with generated client

##### Suggest a fix/enhancement

Write a log message if tempfile exists. I'll make PR in a moment

### PR DESCRIPTION
**Pull request by tpltn**
Closes #5744 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by tpltn** [comment]
FYI @cliffano @zlx @autopp

**Comment by tpltn** [comment]
@autopp sorry about this. I added new samples, but build fails again, and I could not understand why

**Comment by wing328** [comment]
@tpltn the CI failure has been fixed or worked around in the master

**Comment by wing328** [comment]
@tpltn thanks for the PR, which has been merged into master.

**Pull request merged**
