### PR TITLE
Release versioning helper script(s)

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This is an attempt to make the release versioning scripts a little clearer. I've moved the scripts under `./bin/utils/release` so they can live alongside related/supplemental scripts.

Rather than requiring release engineers to specify from/to target versions, I've made `release_version_update.sh` accept one of `major`, `minor`, `build`, or `snapshot`.  This pulls the version from pom.xml. We _could_ go one step further and if version ends in `-SNAPSHOT` then default to `build` and if not default to `snapshot` for the bump version type.

If this gets merged, we'd need to update the wiki as well.

# Examples

## build
image

## minor

image

## major

image

## snapshot

image

## Docs update

image

# Options

## release_version_update.sh

```bash
$ ./bin/utils/release/release_version_update.sh -h

USAGE: ./bin/utils/release/release_version_update.sh target

  This script will convert the current version in target files to the specified 'target'
  where target is one of:

  major
  minor
  build
  snapshot

EXAMPLES:

Update to new snapshot (1.0.0 -> 1.0.1-SNAPSHOT):
    ./bin/utils/release/release_version_update.sh snapshot
Update build version (1.0.0 -> 1.0.1)
    ./bin/utils/release/release_version_update.sh build
Update minor version (1.2.3 -> 1.3.0)
    ./bin/utils/release/release_version_update.sh minor
Update major version (1.2.3 -> 2.0.0)
    ./bin/utils/release/release_version_update.sh major
```

## release_version_update_docs.sh

```bash
$ ./bin/utils/release/release_version_update_docs.sh -h

USAGE: ./bin/utils/release/release_version_update_docs.sh version target

  This script will convert the specified version in DOC target files to the 'target'
  where target is one of:

      major
      minor
      build

  or an explicitly defined version number.

NOTE:

  Files prepped by this script should never target SNAPSHOT, as the docs should refer to release artifacts.
  If intending to update to/from snapshots, please add target files to release_version_update.sh instead.

EXAMPLES:

Update build version (1.0.0 -> 1.0.1)
    ./bin/utils/release/release_version_update_docs.sh 1.0.0 build
Update minor version (1.2.3 -> 1.3.0)
    ./bin/utils/release/release_version_update_docs.sh 1.2.3 minor
Update major version (1.2.3 -> 2.0.0)
    ./bin/utils/release/release_version_update_docs.sh 1.2.3 major
```

### CODE REVIEW

**Comment by jimschubert** [comment]
cc @OpenAPITools/generator-core-team

**Comment by jimschubert** [comment]
I've updated `bump.sh` so it will display an error if a file's contents are unchanged.

See below, where 1.2.3 exists in the file but version 9.9.9 does not.

image

**Comment by wing328** [comment]
@jimschubert Please resolve the merge conflicts when you've time. We'll use it for the next release (4.0.3)

**Comment by jimschubert** [comment]
@wing328 this doesn't show me any merge conflicts. I do see a CircleCI failure which is unrelated.

What process did you follow to see merge conflicts? I'll follow the same and evaluate.

**Comment by jimschubert** [comment]
@wing328 I've merged master. I'll try to check back in a bit and see if the verification suite has passed before merging.

Here are the recommended updates to https://github.com/OpenAPITools/openapi-generator/wiki/Release-Checklist, for "File a PR" step in the "before release" section:

___


- File a PR: (e.g. [#280](https://github.com/OpenAPITools/openapi-generator/pull/280), [#588](https://github.com/OpenAPITools/openapi-generator/pull/588))
  - Set the correct version by executing `bin/utils/release/release_version_update.sh` with the target version increment (`major`, `minor`, `build`, or `snapshot`). Example:
     ```bin/utils/release/release_version_update.sh build```
  - mention the coming release in the docs. `bin/utils/release/release_version_update_docs.sh` accepts a version and the increment.  Example:
     ```bin/utils/release/release_version_update_docs.sh 3.0.2 build` ```
      See commit [9056c1e5e3](https://github.com/OpenAPITools/openapi-generator/pull/588/commits/9056c1e5e3f8bac515e676a4d8ebed0f0d4dc85b))
  - Verify or modify the updated values accordingly
     - update root `README.md`: (e.g. [167b2f5](https://github.com/openapitools/openapi-generator/commit/167b2f59b811ba6780976a6e6764c1edf75a30f7), [1029b69](https://github.com/openapitools/openapi-generator/commit/1029b692e5fcfc2600433a85613ba42e2646826d))
       - Update the release table
       - mention the last released version in Section "1.3 - Download JAR" 
     - update OpenAPI Generator Maven Plugin README (`modules/openapi-generator-maven-plugin/README.md`): mention the last release version in the xml snippet `<version>..</version>` (e.g. [9c79297]( https://github.com/openapitools/openapi-generator/commit/9c79297d6a073790a90b6efedd32e8bebd177828))
     - update version in the Maven Examples (`modules/openapi-generator-maven-plugin/examples/java-client.xml`, 
`modules/openapi-generator-maven-plugin/examples/non-java-invalid-spec.xml`, `modules/openapi-generator-maven-plugin/examples/non-java.xml` and `modules/openapi-generator-maven-plugin/examples/multi-module/java-client/pom.xml`)
     - update OpenAPI Generator Gradle Plugin README (`modules/openapi-generator-gradle-plugin/README.adoc`): mention the last release version in the `dependencies` section.
     - update the Gradle Example Plugin README (`modules/openapi-generator-gradle-plugin/samples/local-spec/README.md`): update `-PopenApiGeneratorVersion` in the `bash` snippet


---

And the snapshot preparation in the "After Release" section:

 - update versions to next SNAPSHOT version  (e.g. [#285](https://github.com/OpenAPITools/openapi-generator/pull/285)). Script `bin/utils/release/release_version_update.sh snapshot` can be used. **Be careful** this script may create changes that need to be reverted. Verify the output after running.

**Comment by jimschubert** [comment]
Merged, also updated the wiki: https://github.com/OpenAPITools/openapi-generator/wiki/Release-Checklist/_compare/04e8a2377450f7ee54022431d8806794cbb990db...7024d560fd6464df0ea4ef84e2d97222c6666ee1

**Comment by wing328** [comment]
I think this broke the release table:
```
<!-- RELEASE_VERSION -->[4.0.2](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.0.2) (latest stable release) | 20.06.2019 | Patch release (bug fixes, minor enhancements, etc)<!-- /RELEASE_VERSION -->
```

Filed https://github.com/OpenAPITools/openapi-generator/pull/3221 to fix it

**Pull request merged**
