### PR TITLE
[C#][functions] minor improvements.

### PR DESCRIPTION
**Pull request by wing328**
- minor coce format improvements
- mark generator as beta
- add copyright
- update readme

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by devhl-labs** [comment]
Did we really need a whole new generator for this instead of just a library? Now we have RestSharp and HttpClient template files copy/pasted in different generators. This will make it hard to fix and update. C# has a yearly update cadence, so this is a big problem.

**Comment by wing328** [comment]
Agreed it should be just one additional optional (ideally) and it should probably extends C# server codegen (or add the new option there) as the new generator generates server-side code.

My intention is to release early and get feedback from the users first. We can later refactor the generator later if the generator gains more and more traction from the community.

**Comment by wing328** [comment]
cc @Abrhm7786

**Comment by Abrhm7786** [comment]
@wing328 Thank you William for these changes!

I actually did originally try extending the server codegen. The problem I was getting then was that some of the models generated from the openapi spec would contain scrambled characters. It seemed easier just to take the client base which was creating the models successfully. Of course, as you say, ideally it would be extending from the server. :)

**Pull request merged**
