### PR TITLE
[PYTHON] generate code based on pydantic v2

### PR DESCRIPTION
**Pull request by fa0311**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by fa0311** [comment]
I was working on the continuation of #16549 but ran out of energy...

**Comment by wing328** [comment]
thank you 👍 

but looks like a recent rebase messed up this PR which now contains commits not authored by you.

do you mind submitting a new PR by cherry-picking the commits owned by you?

**Comment by fa0311** [comment]
> but looks like a recent rebase messed up this PR which now contains commits not authored by you.

This PR is based on #16549 and contains commits I have not made.
Should the base branch be `OpenAPITools:oshmoun-master`?

**Comment by wing328** [comment]
>Should the base branch be OpenAPITools:oshmoun-master?

yes please as I made some enhancements on top of https://github.com/OpenAPITools/openapi-generator/pull/16549

**Comment by fa0311** [comment]
This PR contains a commit to resolve a conflict with `OpenAPITools:oshmoun-master`.

**Comment by wing328** [comment]
Just PM you via Slack to further discuss this.

**Comment by multani** [comment]
Hey @fa0311 , I was doing something related in #16624: I'm not sure how much it will conflict with your changes for Pydantic v2, but I'm putting my work on hold and I'll wait for your pull request to be merged first because I will need Pydantic v2 to actually achieve what I want to do.

I'll rebase/readjust my work once your pull request has been merged, it's hard how much work it will be right now ;)

I'll keep an eye on your changes, let me know if I can help!

**Comment by wing328** [comment]
@multani I'd a discussion with @fa0311 yesterday about your PR and we would like to get your PR merged first.

**Comment by fa0311** [comment]
My environmental test was `206 passed, 2 skipped, 1 warning in 33.10s` 🎉

**Comment by wing328** [comment]
@fa0311 I'd a discussion with @multani last night and just want to share the game plan with you and get your feedback as well.

We'll create another client generator called `python-pydantic-v1` and `python` client generator will support pydantic v2 only moving forward since it's not easy to maintain both pydantic v1 and v2 in the same generator, and we can then more easily consolidate efforts to focus on pydantic v2 support.

We'll get https://github.com/OpenAPITools/openapi-generator/pull/16624 merged first (as it was tested with pydantic v2 when @multani worked on it) and then we will merge this one.

Let me know your thought as well.

**Comment by wing328** [comment]
(and looks like a rebase wasn't performed correctly as this PR contains commits not authored by you)

**Comment by fa0311** [comment]
Continue to #16655

**Pull request closed without merging**
