### PR TITLE
[Java][resttemplate] Support URL queryParams Comma encoding

### LINKED ISSUE #10499: [BUG] openapi-generator-maven-plugin version 5.2.1 not encoded comma
Hello, after upgrading **openapi-generator-maven-plugin** from **5.1.1** to **5.2.1**, we notice that comma is not encoded in urls

```
https://localhost/v1/pets/v1.0/infos?code=1234&languages=fr%2Cen
https://localhost/v1/pets/v1.0/infos?code=1234&languages=fr,en
```

The first url work very well because the comma is encoded to ` %2C`, but the second is not working because the comma is not encoded.

The question now: is this a bug, or we should to add some configuration to encode commas ?

More details
If we look at the class `ApiClient` we can easily notice that the encoded part is removed from the new version

Version 5.1.1

```
public <T> ResponseEntity<T> invokeAPI(String path, HttpMethod method, MultiValueMap<String, String> queryParams, Object body, HttpHeaders headerParams, MultiValueMap<String, String> cookieParams, MultiValueMap<String, Object> formParams, List<MediaType> accept, MediaType contentType, String[] authNames, ParameterizedTypeReference<T> returnType) throws RestClientException {
        updateParamsForAuth(authNames, queryParams, headerParams, cookieParams);

        final UriComponentsBuilder builder = UriComponentsBuilder.fromHttpUrl(basePath).path(path);
        if (queryParams != null) {
            //encode the query parameters in case they contain unsafe characters
            for (List<String> values : queryParams.values()) {
                if (values != null) {
                    for (int i = 0; i < values.size(); i++) {
                        try {
                            values.set(i, URLEncoder.encode(values.get(i), "utf8"));
                        } catch (UnsupportedEncodingException e) {

                        }
                    }
                }
            }
            builder.queryParams(queryParams);							   
        }
																  
        URI uri;
        try {
            uri = new URI(builder.build().toUriString());
        } catch(URISyntaxException ex)  {
            throw new RestClientException("Could not build URL: " + builder.toUriString(), ex);
        }

        final BodyBuilder requestBuilder = RequestEntity.method(method, uri);
        if(accept != null) {
            requestBuilder.accept(accept.toArray(new MediaType[accept.size()]));
        }
        if(contentType != null) {
            requestBuilder.contentType(contentType);
        }
```
Version 5.2.1

```
public <T> ResponseEntity<T> invokeAPI(String path, HttpMethod method, Map<String, Object> pathParams, MultiValueMap<String, String> queryParams, Object body, HttpHeaders headerParams, MultiValueMap<String, String> cookieParams, MultiValueMap<String, Object> formParams, List<MediaType> accept, MediaType contentType, String[] authNames, ParameterizedTypeReference<T> returnType) throws RestClientException {
        updateParamsForAuth(authNames, queryParams, headerParams, cookieParams);

   	    Map<String,Object> uriParams = new HashMap();
        uriParams.putAll(pathParams);
										
        String finalUri = path;

        if (queryParams != null && !queryParams.isEmpty()) {
            //Include queryParams in uriParams taking into account the paramName
            String queryUri = generateQueryUri(queryParams, uriParams);
            //Append to finalUri the templatized query string like "?param1={param1Value}&.......
            finalUri += "?" + queryUri;
        }
        String expandedPath = this.expandPath(finalUri, uriParams);
        final UriComponentsBuilder builder = UriComponentsBuilder.fromHttpUrl(basePath).path(expandedPath);

        URI uri;
        try {
            uri = new URI(builder.build().toUriString());
        } catch (URISyntaxException ex)  {
            throw new RestClientException("Could not build URL: " + builder.toUriString(), ex);
        }

        final BodyBuilder requestBuilder = RequestEntity.method(method, uri);
        if (accept != null) {
            requestBuilder.accept(accept.toArray(new MediaType[accept.size()]));
        }
        if (contentType != null) {
            requestBuilder.contentType(contentType);
        }
```

### PR DESCRIPTION
**Pull request by berlincho**
fix #10499 
Based on the description of the issue, Java resttemplate URL queryParams don't encode UTF-8 correctly.
For example,
```
https://localhost/v1/pets/v1.0/infos?code=1234&languages=fr%2Cen
https://localhost/v1/pets/v1.0/infos?code=1234&languages=fr,en
```
Add `URLEncoder` support to fix the issue with a unit test.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
CI failure already fixed in the master.

**Comment by wing328** [comment]
@berlincho thanks for the fix, which looks good to me.

**Comment by Laurens-W** [comment]
The use of a new RestTemplate in the expandPath method should not have been approved.
Instantiation of the ApiClient either happens with a provided RestTemplate or one is created.

I'm attempting to provide a PR to fix this.

**Comment by sdahlberg** [comment]
The use of DefaultUriBuilderFactory breaks compatibility with spring boot 1.x (spring 4.x). I can't find info on whether or not this should be supported, but our project started failing due to this.

**Comment by sdahlberg** [comment]
The use of DefaultUriBuilderFactory breaks compatibility with spring boot 1.x (spring 4.x). I can't find info on whether or not this should be supported, but our project started failing due to this.

**Pull request merged**
