### PR TITLE
Set swagger-parser to version 2.0.4

### PR DESCRIPTION
**Pull request by jmini**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [x] Copied the technical committee: @OpenAPITools/generator-core-team 

### Description of the PR

With #696 swagger-parser was updated to a custom version.
This PR set it to the official `2.0.2` version (see https://github.com/swagger-api/swagger-parser/issues/780)

### CODE REVIEW

**Comment by jmini** [comment]
I think we need to put this PR on hold until https://github.com/swagger-api/swagger-parser/issues/797 is solved.

**Comment by wing328** [comment]
@jmini 👌 thanks for looking into that.

**Comment by jmini** [comment]
This is "ON HOLD", we will move to `2.0.3` when it is ready.

**Comment by jmini** [comment]
When Swagger Parser `2.0.3` is published, this PR can be updated to use the new version.

**Comment by jmini** [comment]
[2.0.4](https://github.com/swagger-api/swagger-parser/releases/tag/v.2.0.4) was released. This PR use it in OpenAPI-Generator

**Pull request merged**
