### PR TITLE
[typescript] Support esbuild, second attempt

### PR DESCRIPTION
**Pull request by bodograumann**
The first try in #11298 did not work, because it broke the commonjs output.

Now I have differentiated between the two. When es6 is activated, we build an esmodule and when it is deactivated we build the classic commonjs format. For commonjs we don’t need to change our imports, because the esmodule import restrictions don’t apply to the commonjs format. For esmodule output we use a default import.

To make sure everything works, I have added a new sample that has `supportsES6` enabled. The tests for it use esbuild as bundler. (Unfortunately a bundler is needed in any case, because we include commonjs polyfills. Ideally the esmodule output could just run in the browser as-is, but that is something for another day.)

As before I have included proper typings for url-parse.
I also had to expose the `RequiredError` exception type to allow explicit casting to it, because typescript regards errors in `catch` as `unknown` these days.
Pet API tests are run against `http://localhost/v2` as base server, to prevent HSTS in the browser from forcing https.
Finally, I added more fields to `package.json` that include the module type and entry point, to improve compatibility with node and bundlers, especially when generating esmodule output.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

### CODE REVIEW

**Comment by bodograumann** [comment]
Ugh, seems pupeteer does not readily work in the pipeline:

> /home/circleci/OpenAPITools/openapi-generator/samples/openapi3/client/petstore/typescript/tests/browser/node_modules/puppeteer/.local-chromium/linux-950341/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

I have added the chromium dependencies to circleci as per the pupeteer instructions. Hope this is the way to go.

**Comment by bodograumann** [comment]
Neither `libgbm1` nor `libgbm-dev` can be installed :-|.
Is the ci base image too old @wing328 ?

**Comment by bodograumann** [comment]
Yay it works! :rocket: 

Please have another look at this PR now.

**Review by macjohnny — APPROVED** [review]
LGTM

**Pull request merged**
