### PR TITLE
Better pydantic support in python fast api server

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
To test the branch, simply run the following:
```
git clone http://github.com/openapitools/openapi-generator -b python-fastapi-pydantic
cd openapi-generator
mvn clean package -DskipTests -Dmaven.javadoc.skip=true
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g python-fastapi -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/python-fastapi/
```

**Comment by wing328** [comment]
We'll consider this PR as a bug fix (non breaking change) to the upcoming 7.x release.

**Comment by yahiaosama** [comment]
> We'll consider this PR as a bug fix (non breaking change) to the upcoming 7.x release.

Is there a timeline of when this is planned to be released?

**Comment by wing328** [comment]
@yahiaosama thanks for reviewing the testing this change.

Can you please PM me via Slack for a few quick questions if you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by jonasheschl** [comment]
These changes generate incorrect code for my usecase.

```yaml
TextTopic:
  description: foobar
  enum:
  - foo
  - bar
  title: TextTopic
  type: string
```

Turns into:

```python
class TextTopic(int, Enum):
    """
    The topic or objective of this text.
    """

    """
    allowed enum values
    """
    NUMBER_'foo' = 'foo'
    NUMBER_'bar' = 'bar'

    @classmethod
    def from_json(cls, json_str: str) -> TextTopic:
        """Create an instance of TextTopic from a JSON string"""
        return TextTopic(json.loads(json_str))
```

The same code generates correctly using #14242.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/17369 instead to support pydantic v2 in the python-fastapi generator.

please review and test that one instead.

closing this one.

**Pull request closed without merging**
