### PR TITLE
[JavaSpring] Call parent fluent setters from child

### LINKED ISSUE #16496: [BUG] [JavaSpring] Inherited properties with JsonNullable
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using JavaSpring, together with JsonNullable, generated classes for child objects does not call parent setter properly, for the fluent setters.
Parent setter takes a `JsonNullable` but child just calls the setter with actual type argument.

Instead, the fluent setter of the child, should call the fluent setter of the parent for consistency.

##### openapi-generator version

7.0.0 not a regression

##### OpenAPI declaration file content or url

https://gist.github.com/robinjhector/a6391f8df4b6d0343d9d20c808d1107c

##### Generation Details

Maven generator:

```xml
<build>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generateServerApi</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/my-api.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <packageName>com.company.api</packageName>
                            <apiPackage>com.company.generatedapi</apiPackage>
                            <invokerPackage>com.company..generatedapi.invoker</invokerPackage>
                            <modelPackage>com.company..generatedapi.model</modelPackage>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <configOptions>
                                <oas3>true</oas3>
                                <useSpringBoot3>true</useSpringBoot3>
                                <dateLibrary>java8</dateLibrary>
                                <interfaceOnly>true</interfaceOnly>
                                <delegatorPattern>false</delegatorPattern>
                                <interfaceOnly>true</interfaceOnly>
                                <useOptional>true</useOptional>
                                <performBeanValidation>true</performBeanValidation>
                                <singleContentTypes>true</singleContentTypes>
                                <unhandledException>false</unhandledException>
                                <generateApiTests>false</generateApiTests>
                                <skipDefaultInterface>true</skipDefaultInterface>
                                <useSwaggerUI>false</useSwaggerUI>
                                <documentationProvider>none</documentationProvider>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

##### Steps to reproduce

Run a generate either via cli or via maven plugin.

Parent:
Screenshot 2023-09-04 at 11 19 44
Child (The output code has compilation errors, when it tries to call the parent setter):
Screenshot 2023-09-04 at 11 19 02

##### Related issues/PRs

N/A

##### Suggest a fix

My suggestion is to use the parent fluent setter from the child class.
I am happy to submit a PR with a fix.

### PR DESCRIPTION
**Pull request by robinjhector**
This closes #16496

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (7.0.1 - patch release), `7.1.x` (minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

Ping JavaSpring committee: @javisst @borsch @banlevente @Zomzog @martin-mfg

### CODE REVIEW

**Comment by robinjhector** [comment]
Couldn't find the correct branch to target this PR towards, please advise :)

**Comment by wing328** [comment]
@robinjhector is this a breaking change?

I'll create 7.1.x and 8.0.x tomorrow.

**Comment by robinjhector** [comment]
> Looks to me the change is transparent to users consuming the auto-generated code. Please correct me if I'm wrong.

It should be transparent, that is my view as well 👍

**Comment by wing328** [comment]
👌 let's target current master.

**Comment by wing328** [comment]
LGTM. Thanks for the PR.

**Pull request merged**
