### PR TITLE
Upgrade haskell-servant generator to latest LTS

### PR DESCRIPTION
**Pull request by f-f**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Problem: the current `haskell-servant` client is based on a set of libraries (`lts` package set) from one year ago, based on the `8.0.x` release of GHC. It is typical for library writers in the Haskell community to maintain compatibility with the latest 3 major versions of the compiler. By this standard (since `8.2`, `8.4` and `8.6` are out) we are generating an outdated client. Moreover, the `servant` library itself went through several breaking versions in the meanwhile, so the code generated by this generator is not really compatible with a project started today.

This PR upgrades to the latest `lts` ([12.18 for GHC 8.4](https://www.stackage.org/lts-12.18)) and `servant` version, and adds several new features:
- optionals are now `Maybe`s
- `UUID`, `UTCTime` and `Day` are now represented with the correct types
- the configuration for the client now contains only one parameter, the `url`
- add `ToSchema` instances to generated types, so they can be re-exposed for free in the spec of the service using the client
- switch to the `tls-http-manager`, so we can connect to https urls
- add Nix support in the `stack.yaml`
- add a nicer API to call the endpoints

Note: all of this is quite breaking, so I opened the PR against the `4.x` branch

/cc @wing328

### CODE REVIEW

**Comment by wing328** [comment]
cc @jonschoning, @algas to see if they've time to do a review on the change.

**Comment by f-f** [comment]
@jonschoning thanks for the review!

1. Right, I didn't try running stack build on the petstore, good catch
2. Yes, I'll remove them

**Comment by jonschoning** [comment]
looks good to me

**Comment by wing328** [comment]
@jonschoning thanks for reviewing the change.

@f-f thanks for the enhancement, which has been merged into master.

**Comment by wing328** [comment]
@f-f thanks again for the contribution, which has been included in the 4.0.0-beta release: https://twitter.com/oas_generator/status/1079727020374806529.

Happy New Year and looking forward to more collaboration and contributions in 2019!

**Pull request merged**
