### PR TITLE
[dart] Split mustache file by serialization

### PR DESCRIPTION
**Pull request by agilob**
No functional changes only code cleanup in mustache files so each serialization has own files, removes conditions from .mustache for readability.
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@kuhnroyal

### CODE REVIEW

**Comment by agilob** [comment]
The whitespace change (removal before `fromJson()`) is only in json_serializable code which hasnt been released yet.

**Comment by kuhnroyal** [comment]
I started working on a new dio generator that would also support multiple serialization libraries here: https://github.com/OpenAPITools/openapi-generator/pull/8869
We should use the same file structure for the partials, I have a separat sub folder `serialization/built_value` with the specific mustache files.

**Comment by agilob** [comment]
ok, will change it later today

**Comment by kuhnroyal** [comment]
Looks good, probably don't need the `native/json_serializable` prefix anymore for the partials.

**Comment by agilob** [comment]
i thought so too, but it failed to find inlined enums without it

**Review by kuhnroyal — APPROVED** [review]

**Comment by agilob** [comment]
@wing328  can we get this in pls?

**Comment by kuhnroyal** [comment]
Asked in Slack for a merge

**Pull request merged**
