### PR TITLE
CircleCI comment spring-mvc-j8-localdatetime

### PR DESCRIPTION
**Pull request by jmini**

### CODE REVIEW

**Comment by jmini** [comment]
My attempt change port did not work. I now have commented `spring-mvc-j8-localdatetime`

**Comment by jimschubert** [comment]
@jmini this title is still marked as a work in progress. Is this ready to merge?

**Comment by jmini** [comment]
Lets see how CI looks like, I just merged master into this branch...

**Comment by jimschubert** [comment]
I think it's fine. do we have insight into how CircleCI runs this stuff? Are servers shared, it would bumping to a higher port solve this issue?

Could we consider modifying these settings using sed and a random port assignment function?

**Comment by wing328** [comment]
> should we comment the spring-mvc-j8-localdatetime test case in order for the CircleCI job to OK?

Please try.

In my end, I'll try upgrading the setting file to CircleCI 2.0 to see if that works out better.

Ref: https://circleci.com/blog/launching-today-circleci-2-0-reaches-general-availability/

**Comment by jmini** [comment]
> ci/circleci — Your tests failed on CircleCI 

Job 250 is failing:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: joda-time#joda-time;2.2!joda-time.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: joda-time#joda-time;2.2!joda-time.jar
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
```

**Comment by jimschubert** [comment]
@jmini does this still need to be merged?

**Comment by jmini** [comment]
No you are right. I will close this PR, it does no longer make sense.

**Pull request closed without merging**
