### PR TITLE
Updating packages version

### PR DESCRIPTION
**Pull request by iquirino**
Packages updated and obsolete calls solved.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
@iquirino thanks for the PR. There's also a `csharp-netcore` generator. Do you plan to update its dependency to the latest version as well?

**Comment by iquirino** [comment]
Hello William,

This PR is something that i need ASAP, but we can work together on another generators.

I think we need to work to add framework versions at the next steps.
Like net461, net461, ...
And for net standard, 2.0, 2.1, 2.2, 3.0, 3.1, ...
What you think about it?

**Comment by wing328** [comment]
Updated C# petstore samples via https://github.com/OpenAPITools/openapi-generator/pull/5313/commits/abdd04930cd413dbfb35942b3d2206dca138bf1a

**Comment by wing328** [comment]
> And for net standard, 2.0, 2.1, 2.2, 3.0, 3.1, ...

We'll need to support these in the `csharp-netcore` generator instead of the csharp generator.

**Comment by iquirino** [comment]
Thank you!

**Comment by iquirino** [comment]
Sorry to close it. Wrogn button.

**Comment by wing328** [comment]
CI failed with the following errors:

```
  Client\ApiClient.cs(111,26): error CS0246: The type or namespace name 'RestSharp' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ApiClient.cs(113,32): error CS0246: The type or namespace name 'FileParameter' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ApiClient.cs(110,17): error CS0246: The type or namespace name 'RestRequest' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ApiClient.cs(162,26): error CS0246: The type or namespace name 'RestSharp' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ApiClient.cs(164,32): error CS0246: The type or namespace name 'FileParameter' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ApiClient.cs(197,26): error CS0246: The type or namespace name 'RestSharp' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ApiClient.cs(199,32): error CS0246: The type or namespace name 'FileParameter' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ApiClient.cs(228,16): error CS0246: The type or namespace name 'FileParameter' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ApiClient.cs(280,35): error CS0246: The type or namespace name 'IRestResponse' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
  Client\ExceptionFactory.cs(23,67): error CS0246: The type or namespace name 'IRestResponse' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\openapi-generator\samples\client\petstore\csharp\OpenAPIClient\src\Org.OpenAPITools\Org.OpenAPITools.csproj]
    2 Warning(s)
    23 Error(s)
Time Elapsed 00:00:07.38
Command exited with code 1
```

**Comment by Bouillie** [comment]
@wing328 

I'm interested in the resolution of the PR, so I looked it up.
From version 106.0, Restsharp only supports net452 and netstandard2.0. 
So for people still using the net40 framework, we can't upgrade Restsharp. The version of Restsharp should be dependant of the target framework.

If you agree on that, I could try to commit a fix.

**Comment by Bouillie** [comment]
@wing328 @iquirino I prepared a fix but I can't push it on iquirino's repository, how can we proceed ?

**Comment by Bouillie** [comment]
[patch-fix-restsharp-version.zip](https://github.com/OpenAPITools/openapi-generator/files/4438522/patch-fix-restsharp-version.zip)

Here's my fix in a patch file. I hope you can use it and close this PR.

**Comment by wing328** [comment]
I've merged this into the `csharp-upgrade` branch.

@Bouillie I wonder if you can file the fix with a PR to the `csharp-upgrade`

**Comment by Bouillie** [comment]
I'll take care of it asap

**Comment by iquirino** [comment]
@bouillie I am not the Project owner, you will need to fork my Project, create a PR and Then i create a PR on this repo.. Or maybe you can PR this repo directly..

Tks!!

**Comment by wing328** [comment]
@iquirino @Bouillie I've filed https://github.com/OpenAPITools/openapi-generator/pull/5870 instead. Closing this one

**Pull request merged**
