### PR TITLE
Remove dollar sign from Java const name

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Remove dollar sign from Java constant name as only letters and underscore are allowed: https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

### CODE REVIEW

**Comment by jmini** [comment]
Does it works if you have 2 properties `$_type` and `type` in the same object?
=> This is a requirement we have.

---

`$` is allowed in constant names in Java.
Maybe not recommended by the linked google guidelines, but this is not the Java specification (that is hosted somewhere on the Oracle website)

**Comment by wing328** [comment]
Fair enough. I'll make an option, e.g. `googleStyleGuide`

**Comment by yue9944882** [comment]
https://docs.oracle.com/javase/specs/jls/se7/html/jls-3.html#jls-3.8

> The "Java letters" include uppercase and lowercase ASCII Latin letters A-Z (\u0041-\u005a), and a-z (\u0061-\u007a), and, for historical reasons, the ASCII underscore (_, or \u005f) and dollar sign ($, or \u0024). The $ character should be used only in mechanically generated source code or, rarely, to access pre-existing names on legacy systems.

@jmini my understanding oracle's offical site, it's not recommended to use $ in the field name intentionally. the supporting for $ is mainly for (a) generated source (b) compatibility for legacy system. considering that this repo is indeed a code-generator so the it's still complying w/ (a).. i will have a sync-up w/ kubernetes maintainers to discuss about the very issue.

**Comment by yue9944882** [comment]
the issue is that it's breaking backward compatibility when we migrate from `swagger-codegen` to `openapi-codegen`, the former has generated non-dollar fields already. let's hold this for more inputs? wdyt @wing328

**Comment by jmini** [comment]
Swagger-Codegen was not generating those constants, but it supports the valid OpenAPI Spec (its v2 counter-part of course) containing both `type` and `$_type` in the same JSON object.

I am not saying am against any change here.

I am just pointing out that this change, the way it is implemented produces a regression.

In some other places, special chars like this one are replaced with its written form.
Code that does that:

https://github.com/OpenAPITools/openapi-generator/blob/4575b3074ab6f2628837ca84ed5c287f2afaceee/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L1123-L1125

Can't we use this?

**Comment by jmini** [comment]
> Fair enough. I'll make an option, e.g. `googleStyleGuide`

I do not think that we need an other option here. Can you consider:

1. replacing `$` with `DOLLAR` in the constant name?
2. or find a way to ensure that the generated constants are unique (with a suffix like `_1`, `_2` .. in case of collision)?

Both would be acceptable for me, I prefer the first solution.

**Comment by wing328** [comment]
> Swagger-Codegen was not generating those constants

Very good point on this. We need to better understand the backward compatibility first: https://github.com/OpenAPITools/openapi-generator/issues/3191

I'll continue the discussion in https://github.com/OpenAPITools/openapi-generator/issues/3191 by asking for more information (e.g. error message) to start with

**Comment by wing328** [comment]
> I do not think that we need an other option here. Can you consider:

Personally of course I don't want another option but if someone is referencing these constant in their code, it will break if they upgrade openapi-generator to a newer version with the fix.

Let's put this PR on hold for the time being.

**Comment by jmini** [comment]
I have added the test case discussed in https://github.com/OpenAPITools/openapi-generator/pull/3676#pullrequestreview-276936294 as PR https://github.com/OpenAPITools/openapi-generator/pull/3774. 

A change as proposed in this PR would produce a test failure.

**Pull request closed without merging**
