### PR TITLE
[GoServer] Generate non-required parameters as pointers (nil-able)

### LINKED ISSUE #19169: [BUG][GO] Query parameters that are not required should be generated as pointers in go-server
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using the `go-server` generator, query parameters with `required: false` are being generated as value types. Using the example spec below, this generates a method signature like the following:
```
type DefaultAPIServicer interface { 
	RootGet(context.Context, bool) (ImplResponse, error)
}
```
Since the default value of `bool` is false, it is not possible to tell whether the client passed `false` to the parameter or simply did not provide it at all. By using a pointer instead, the parameter could be `nil` when not passed by the client. The method signature should look like the following:
```
type DefaultAPIServicer interface { 
	RootGet(context.Context, *bool) (ImplResponse, error)
}
```

##### openapi-generator version

7.7.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
security: []
info:
  description: >-
    This is a sample spec to demonstrate handling non-required boolean query parameters in the go-server generator
  version: 1.0.0
  title: Boolean sample
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /:
    get:
      summary: Sample endpoint
      description: Demonstrate handling of non-required boolean query parameters
      parameters:
        - in: query
          name: someParam
          description: a test parameter
          schema:
            type: boolean
          required: false
      responses:
        '200':
          description: Demo
          content:
            application/json:
              schema:
                type: string
```

##### Generation Details

This bug can be reproduced using the `go-server` generator with no additional settings.

##### Steps to reproduce

- Copy the above spec into a file and save at `./openapi/openapi.yaml`
- Run the generator with the command: `java -jar openapi-generator-cli.jar generate -i ./openapi/openapi.yaml -o ./server-gen -g go-server`
- Observe the generated server code in the `server-gen` directory, eg. `./server-gen/go/api.go`, note that the `RootGet` method signature takes a `bool`  rather than a `*bool` parameter.

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/pull/19149

Would appreciate the Go technical committee reviewing this issue and my suggested fix (@antihax, @grokify, @kemokemo, @jirikuncar, @ph4r5h4d, @lwj5)

### PR DESCRIPTION
**Pull request by phil-bugdahn-hs**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

This PR fixes #19169 

The problem is that, using an OpenAPI spec that specifies a non-required query param, the `go-server` generator will generate the server handler taking that parameter as a value rather than a pointer. By doing this, it is not possible to tell in the handler whether the parameter was actually passed or if it is just a default value. By using a pointer the parameter value will be `nil` if not passed by the client. This PR should fix that issue.

### CODE REVIEW

**Comment by wing328** [comment]
@phil-bugdahn-hs thanks for the PR. can you please review the test failure when you've time?

https://github.com/OpenAPITools/openapi-generator/actions/runs/9941343559/job/27462431755?pr=19149

**Comment by wing328** [comment]
cc 
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

**Comment by phil-bugdahn-hs** [comment]
Hi @wing328, thanks for your response. I think I have resolved the test issue.

**Comment by wing328** [comment]
@phil-bugdahn-hs thanks again for the PR.

Is it correct to say that this is a breaking change (without fallback)?

**Comment by lwj5** [comment]
Hi @phil-bugdahn-hs, I think the problem has been discussed in https://github.com/OpenAPITools/openapi-generator/pull/16980

you may want to review the pointers there with regards to this PR.

Is this PR trying to do what is stated in #16980?

**Comment by phil-bugdahn-hs** [comment]
Closing as per disccusion in the issue.

**Pull request closed without merging**
