### PR TITLE
[PythonClientCodeGen] Generated model for not inheriting attributes from parent

### PR DESCRIPTION
**Pull request by narenandu**
CC'ing [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee): @taxpon @frol @mbohlool @cbornet @kenjones-cisco to review the pull request if your PR is targeting python programming language.

### Description of the PR

It is kind of counter intuitive, but setting `supportsInheritance = true` is failing to get the properties from the parent when a child model inherits. Didn't dive deep in to the actual base class for the code generation, but commenting out the line from `PythonClientCodegen.java` fixed the issue.

This solves the reported issues
- https://github.com/OpenAPITools/openapi-generator/issues/453 (@poli-granot)
- https://github.com/OpenAPITools/openapi-generator/issues/623 (@emreakca)

There could be multiple reasons since I didn't go to the root cause
- First that there is no `AbstractPyCodegen.java`, which might/might not tackle the issue
- Second, we don't know if other code gen for languages like `ObjcClientCodegen` / `PhpClientCodegen` are working since, they also are using `supportsInheritence = true` in their generation code

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by narenandu** [comment]
@wing328 Thanks for pointing that out. I have followed the process as mentioned in the [Reference](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account). Hope the PR looks fine now !

**Comment by wing328** [comment]
@narenandu looks like the rebase messed up this PR as it now contains a lot of commits not authored by you. I would suggest you open a new one instead

**Comment by narenandu** [comment]
Yeah.. please close this PR ... the script didn't do the right thing. Its just a one line change. I will create a new one

**Comment by narenandu** [comment]
Created #1099

**Pull request closed without merging**
