### PR TITLE
[Python] handle discriminator inheritance for models

### PR DESCRIPTION
**Pull request by rienafairefr**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. @tomplus  @Jyhess @wing328 

### Description of the PR

related issues: #1662 #1663 
in the Python models, discriminator_value_class_map wasn't filled when the model  had a filled-up discriminator (with or without a mapping). I'm not sure about the `children` field for the model and what it corresponds, but adding the discriminator mapping in the case this field is not there seems to work.

### CODE REVIEW

**Comment by wing328** [comment]
@rienafairefr thanks for the PR. Are you free for a quick chat via https://gitter.im tomorrow (Wed)?

**Comment by rienafairefr** [comment]
Sorry @wing328 took some time to get back to you, yeah ping me up on gitter anytime :-)

**Comment by tomghyselinck** [comment]
Hi @rienafairefr,

I am testing this PR.

IMHO the `mapping` should _also_ be applied when there are `children` defined.

According to [OpenAPI Specification 3.0.2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminator-object):
* The `children` can be used for the "_schema name_" or (default) "_implicit_" mapping.
* while the `mapping` is an _additional_ mapping to identify the (_final_ or _upper-layer_) objects.

With best regards,
Tom.

**Comment by fantavlik** [comment]
This is great, thanks @rienafairefr. I do agree with @tomghyselinck that implicit mapping should also be included. To me it appears that a change to the core code is actually needed, the implicit mapping is not being captured here from what I can tell: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L1798-L1825

This is confirmed when I generate this schema:
```yaml
Thing:
  oneOf:
  - $ref: "#/components/schemas/Foo"
  - $ref: "#/components/schemas/Bar"
  discriminator:
    propertyName: kind
```

The discriminator template payload is simply:
```json
...
"discriminator" : {
  "propertyName" : "kind",
  "mappedModels" : [ ]
},
```

Ideally it would be:
```json
...
"discriminator" : {
  "propertyName" : "kind",
  "mappedModels" : [ {
    "mappingName" : "Foo",
    "modelName" : "Foo"
  }, {
    "mappingName" : "Bar",
    "modelName" : "Bar"
  } ]
},
```

**Comment by andreishappy** [comment]
I've run into this issue and would really appreciate a fix. Do you know by any chance when this could be merged? Thanks! ❤️

**Comment by spacether** [comment]
We have another PR in review which also seeks to improve the discriminator class map here
https://github.com/OpenAPITools/openapi-generator/pull/4906

**Comment by spacether** [comment]
This PR has been closed due to inactivity

**Pull request closed without merging**
