### PR TITLE
[Java] Add useTags config option support for java client code generation (#10109)

### PR DESCRIPTION
**Pull request by jekkel**
Feature request: https://github.com/OpenAPITools/openapi-generator/issues/10109

This PR adds a new configuration option "useTags" to the Java generator similar to the one that can be found e. g. in the Spring generator.
The flag defaults to true to keep backwards compatibility (despite the default for the other generators is false).
Setting it the false will prevent the generator to create one interface per tag (which might be not desirable).

There has been a similar PR before, but it has been closed without comment: https://github.com/OpenAPITools/openapi-generator/pull/10156

/cc Technical committee members @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by jekkel** [comment]
@wing328 Hey there, I believe the failed check is unrelated and maybe we can get this in before it gets outdated again?

**Comment by jekkel** [comment]
> @wing328 Hey there, I believe the failed check is unrelated and maybe we can get this in before it gets outdated again?

Too late X-)

I rebased another time, please have a look

**Comment by wing328** [comment]
@jekkel can you please PM me via slack tomorrow to discuss on this and get it merged?

**Comment by jekkel** [comment]
> @jekkel can you please PM me via slack tomorrow to discuss on this and get it merged?

I'd love to, but I don't use slack and don't really know how get in touch with you there...

**Comment by wing328** [comment]
just added you in linkedin. let's chat there.

**Comment by jekkel** [comment]
Closing in favor of https://github.com/OpenAPITools/openapi-generator/pull/14794 which fully covers the use case without having to adapt all the generators one by one.

**Pull request closed without merging**
