### PR TITLE
[Issue#392] Correct issue with OAuth scopes not propogated correctly

### LINKED ISSUE #392: [spring]: Incorrect @AuthorizationScope
##### Description
When I generate spring (java) from this api.yml:
```yaml
# API-first development with swagger
# This file will be used at compile time to generate Spring-MVC endpoint stubs using swagger-codegen
swagger: "2.0"
info:
  title: gateway
  version: 0.0.1
basePath: /rest
paths:
  /account/self:
    get:
      summary: server user information
      description: Get information about account (oauth2) currently used on server (development, debugging)
      security:
        - oAuth2NoScopes: []
      operationId: accountSelf
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: user information
          schema:
            $ref: '#/definitions/OaAccountModel'
  /account/selfSecured:
    get:
      summary: server user information
      description: Get information about account (oauth2) currently used on server (development, debugging)
      security:
        - oAuth2NoScopes:
            - registry
            - dummy
      operationId: accountSelfSecured
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: user information
          schema:
            $ref: '#/definitions/OaAccountModel'
definitions:
  OaAccountModel:
    type: object
    properties:
      userid:
        type: string
      info:
        type: string
      roles:
        type: array
        items:
          type: string
      scopes:
        type: array
        items:
          type: string
securityDefinitions:
  oAuth2NoScopes:
    type: oauth2
    description: 'keycload login TODO tp: Change realm!'
    authorizationUrl: 'https://localhost:8443/auth/realms/zap/protocol/openid-connect/auth'
    tokenUrl: 'https://localhost:8443/auth/realms/zap/protocol/openid-connect/token'
    flow: implicit
    scopes:
        registry: admin right to registry
        dummy: dummy scope
```
I've got the impression that the @AuthorizationScope generated are not appropriate. 

##### openapi-generator version
3.0.2

##### Generated AccountApi.java
```java
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.2).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.siteos.zap.web.api;

import de.siteos.zap.web.api.model.OaAccountModel;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-06-25T09:50:17.329+02:00[Europe/Berlin]")

@Validated
@Api(value = "account", description = "the account API")
public interface AccountApi {

    default AccountApiDelegate getDelegate() {
        return new AccountApiDelegate() {};
    }

    @ApiOperation(value = "server user information", nickname = "accountSelf", notes = "Get information about account (oauth2) currently used on server (development, debugging)", response = OaAccountModel.class, authorizations = {
        @Authorization(value = "oAuth2NoScopes", scopes = {
            @AuthorizationScope(scope = "registry", description = "admin right to registry"),
            @AuthorizationScope(scope = "dummy", description = "dummy scope")
            })
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "user information", response = OaAccountModel.class) })
    @RequestMapping(value = "/account/self",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<OaAccountModel> accountSelf() {
        return getDelegate().accountSelf();
    }


    @ApiOperation(value = "server user information", nickname = "accountSelfSecured", notes = "Get information about account (oauth2) currently used on server (development, debugging)", response = OaAccountModel.class, authorizations = {
        @Authorization(value = "oAuth2NoScopes", scopes = {
            @AuthorizationScope(scope = "registry", description = "admin right to registry"),
            @AuthorizationScope(scope = "dummy", description = "dummy scope")
            })
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "user information", response = OaAccountModel.class) })
    @RequestMapping(value = "/account/selfSecured",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<OaAccountModel> accountSelfSecured() {
        return getDelegate().accountSelfSecured();
    }

}
```

##### Suggest a fix/enhancement
As you can see, in both cases 
```java
            @AuthorizationScope(scope = "registry", description = "admin right to registry"),
            @AuthorizationScope(scope = "dummy", description = "dummy scope")
```
is generated. However, I only expect this on the `/account/selfSecured` path (as it declare this scopes). On the `/account/self` path this is wrong as there is an _empty_ scope definition. Hence I expect the no @AuthorizationScope is generated for the `/account/self` path.

### PR DESCRIPTION
**Pull request by mikezx6r**
If a path defined security to an OAuth type, and defined scopes, the scopes from the
components definition were still being used, rather than the (most likely shorter) list
of specific scopes for the path.

This copies all the component security information over EXCEPT for the scopes. The scopes
to be included are determined by the path's security settings.

NOTE: Modified the petstore.yaml file so the GET operations only have read:pets scope and
utilized the Kotlin server sample to verify output. Sample output updated only for this scenario

Fix #392

### CODE REVIEW

**Comment by mikezx6r** [comment]
As I'm focused on impact to Java and Kotlin Spring templates, I'm notifying you:

@jimschubert, @dr4ke616, @bbdouglas, @JFCote, @sreeshas, @jfiala, @lukoyanov, @cbornet, @jeff9finger

**Comment by wing328** [comment]
@mikezx6r thanks for the PR but the CI builds failed with the following error:
```
[ERROR] COMPILATION ERROR : 
[ERROR] /gen/modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java:[389,37] cannot find symbol
  symbol:   class Map
  location: class org.openapitools.codegen.java.JavaClientCodegenTest
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project openapi-generator: Compilation failure
[ERROR] /gen/modules/openapi-generator/src/test/java/org/openapitools/codegen/java/JavaClientCodegenTest.java:[389,37] cannot find symbol
[ERROR]   symbol:   class Map
[ERROR]   location: class org.openapitools.codegen.java.JavaClientCodegenTest
[ERROR] -> [Help 1]
```
Can you please take a look when you've time?

**Comment by mikezx6r** [comment]
@wing328 I've rebased onto latest master, and fixed up the issues. 

Travis CI timed out but the others are good.

Let me know if there's anything else I need to do.

**Comment by wing328** [comment]
@mikezx6r I've restarted the travis job.

Do you have a spec to reproduce the issue? Sorry in advance if I've missed it somewhere.

**Comment by mikezx6r** [comment]
@wing328 Sorry to bother, but it appears 4.0.0 got released, but I don't think this made it in. Any updates, or questions pending that I can answer to keep this moving?

**Comment by wing328** [comment]
Sorry for taking this long. @ybelenko has tested it and confirmed the fix works. 

The circle CI failure has been fixed in the master.

**Comment by mikezx6r** [comment]
Thank you, and no worries. I totally understand. We all get busy...

**Comment by karismann** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/1982/files#diff-efbcca2d5a6846e6f510a0b52514d81a  -> i don't know why this file has been deleted but it broke kotlin-springboot test
@wing328   any way to revert only the deleted file on the PR ?

**Comment by mikezx6r** [comment]
@karismann Sorry about that. I suspect it happened during a rebase, and I didn't look closely enough at the end commit. My apologies for that.

Thank you for fixing my mistake.

**Pull request merged**
