### PR TITLE
Generate a ruby-client sample for OpenAPI 2.0

### PR DESCRIPTION
**Pull request by meganemura**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Move output directory for bin/openapi3/ruby-client-petstore.sh
to `sample/client/petstore/ruby`
from `sample/openapi3/client/petstore/ruby-client`.

And generate ruby-client for OpenAPI 2.0 by `bin/ruby-client-petstore.sh`
to `sample/client/petstore/ruby`.

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by meganemura** [comment]
I found that the generated ruby-client for OpenAPI 2.0 has a syntax-error.
```ruby
> Regexp.new(/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$)
Traceback (most recent call last):
        1: from /Users/meganemura/.rbenv/versions/2.5.3/bin/irb:11:in `<main>'
SyntaxError ((irb):1: premature end of char-class: /^(?:[A-Za-z0-9+/)
(irb):1: syntax error, unexpected ']', expecting ')'
Regexp.new(/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A...
```

https://github.com/OpenAPITools/openapi-generator/pull/1482/files#diff-cb91f29a2d3eab894268b3e54a7df278R198
https://github.com/OpenAPITools/openapi-generator/pull/1482/files#diff-cb91f29a2d3eab894268b3e54a7df278R237
https://github.com/OpenAPITools/openapi-generator/pull/1482/files#diff-cb91f29a2d3eab894268b3e54a7df278R336

See also #1393

**Comment by meganemura** [comment]
@wing328 Would you please review this?

**Comment by wing328** [comment]
@meganemura thanks for the fix. I'll review shortly.

For the following:
> Move output directory for bin/openapi3/ruby-client-petstore.sh
to sample/client/petstore/ruby
from sample/openapi3/client/petstore/ruby-client.

I prefer putting Petstore client samples for OpenAPI v3 spec under `sample/openapi3/client/petstore/` to make it consistent with other OpenAPI v3 samples.

**Comment by meganemura** [comment]
@wing328
oops. I wrote a wrong description.
Its from/to was opposite.

This change moves ruby-client v3 from sample/client/petstore to sample/openapi3/client/petstore.

**Comment by wing328** [comment]
@meganemura PR merged into master. Thanks for the PR.

cc @cliffano (2017/07) @zlx (2017/09)

**Pull request merged**
