### PR TITLE
2745 typescript date format

### PR DESCRIPTION
**Pull request by tsiq-jeremy**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny 

Fair warning that I tested this out more thoroughly using swagger-codegen for this PR - https://github.com/swagger-api/swagger-codegen/pull/9594 - but it looks like the same exact issue.

Related to this [issue](https://github.com/OpenAPITools/openapi-generator/issues/2745). When using TypeScript Fetch and passing parameters to a "Date" field, they expect a type of "string", but then `toISOString()` is called on it, which causes the function to fail. 

Example json swagger:
```json
        "parameters": [
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "format": "date"
          }
        ]
```

in In `AbstractTypeScriptClientCodegen.java the Typings map:
```
typeMapping.put("date", "string");
typeMapping.put("DateTime", "Date");
```

template issue:
```mustache
{{#isDate}}
queryParameters['{{baseName}}'] = (requestParameters.{{paramName}} as any).toISOString();
{{/isDate}}
```
`requestParameters.{{paramName}}` can never be a Date, since it has to be a string. 

fixes https://github.com/OpenAPITools/openapi-generator/issues/2745

### CODE REVIEW

**Comment by macjohnny** [comment]
@tsiq-jeremy thanks for your PR! can you please re-generate the samples?

> Ran the shell script under ./bin/ to update Petstore sample so that CIs can verify the change. (For instance, only need to run ./bin/{LANG}-petstore.sh, ./bin/openapi3/{LANG}-petstore.sh if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in .\bin\windows\. If contributing template-only or documentation-only changes which will change sample output, be sure to build the project first.

**Comment by macjohnny** [comment]
cc @nicokoenig

**Comment by tsiq-jeremy** [comment]
Hey I just ran `./bin/typescript-axios-petstore-all.sh` and did not see any changes when running `git status`. I looked through the yaml file it runs against and it has `date-time`, but no `date` types.

**Comment by macjohnny** [comment]
@tsiq-jeremy ok, that's probably because there is no Date-query parameter in the petstore example, so everything is fine.
The CI-failure is unrelated.

**Comment by macjohnny** [comment]
@tsiq-jeremy would you like to fix the same problem in the `typescript-fetch` generator, i.e. here:

https://github.com/OpenAPITools/openapi-generator/blob/577581303155461fc4fbef4f664ddbdba2350ceb/modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache#L67-L73

**Comment by tsiq-jeremy** [comment]
Hey, let me look into that one. I'm not sure if there is a problem with `typescript-fetch` b/c in modelGeneric.mustache it has `FromJSON` and `ToJSON` that are manipulating the date type.

**Comment by macjohnny** [comment]
yes, but I think the From/ToJson functions are used for the body, not for the query parameters, so it should be the same situation

**Comment by tsiq-jeremy** [comment]
Hey I have not tested this out fully, but I think this should not be a problem with `typescript-fetch`. Used to test:

```json
        "parameters": [
          {
            "name": "date",
            "in": "query",
            "type": "string",
            "format": "date"
          }
        ]
``` 
Produced: 
```TypeScript
export interface GetOrderByIdRequest {
    date: Date;
}

   ....
    async getOrderByIdRaw(requestParameters: GetOrderByIdRequest): Promise<runtime.ApiResponse<Order>> {
       ....
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.date !== undefined) {
            queryParameters['date'] =  (requestParameters.date as any).toISOString().substr(0,10);
        }
       ...
    }
```

So it looks like that a Date object is getting passed in so that it should not produce an error when calling  `toISOString`.

**Comment by macjohnny** [comment]
Ok, alright, thanks for checking!

**Comment by wing328** [comment]
@tsiq-jeremy thanks for the PR, which has been included in the 4.1.0 release: https://twitter.com/oas_generator/status/1160000504455319553

**Pull request merged**
