### PR TITLE
[JAVA] fix several anyOf/oneOf problems

### PR DESCRIPTION
**Pull request by martin-mfg**
Fix various problems when using anyOf or oneOf. Mostly focusing on the Jersey libraries.

I separated the fixed problems into different commits in this PR:
- **commit 1**: generate more child-specific methods where possible.
   e.g. in samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/model/FakeAnyOfWIthSameErasureGet200Response.java we now also generate the method "getListInteger". Previously this was skipped due to "getListString" already being created.
   The mustache file changes also include a small simplification of the relevant template part. The Jersey anyOf*.mustache templates were a bit out of sync and needed to be aligned with their oneOf counterparts - see [here](https://github.com/OpenAPITools/openapi-generator/pull/18042#issuecomment-2033885138) for context.
- **commit 2**: When generating an anyOf/oneOf model with `useBeanValidation=true`, don't generate uncompilable code.
- **commit 3**: When generating a oneOf model which also is a map, don't generate uncompilable code.
- **commit 4**: Apply similar fixes to the Jersey anyOf*.mustache templates. As mentioned above, they were a bit out of sync.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
   @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

### CODE REVIEW

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/actions/runs/11245644264/job/31266185926?pr=19817

please update the samples when you've time

overall the change looks good.

will merge after all tests pass

thank you

**Comment by martin-mfg** [comment]
@wing328 done :)

**Comment by wing328** [comment]
looks good.

thank you.

**Comment by Csini** [comment]
can you please correct the same issue in

```
<generatorName>java</generatorName>
<library>resttemplate</library>
```

?

**Comment by martin-mfg** [comment]
Hi @Csini, I don't have the time to make the changes for `resttemplate`. Please create a PR yourself, or create a new issue describing your problem and add a bounty (like e.g. [here](https://github.com/OpenAPITools/openapi-generator/issues/10812)) to increase the chance of someone else working on it.

**Comment by kulon** [comment]
We upgraded from version 7.6.0 to 7.10.0 and found that changes between these versions break the **java-camel** generator's processing of the oneOf/anyOf definitions.

For example, the following schema generates proper code with version 7.6.0, but the generator version 7.10.0  creates a class with no fields. We are using version 3.0.3 of the OpenAPI spec.

```
"Request": {
      "type": "object",
      "properties": {
        "referenceNumber": {"type": "string", "nullable": true},
        "documentNumber": { "type": "string", "nullable": true},
        "stockNumber": {"type": "string", "nullable": true}
      },
      "oneOf": [
        {
          "required" : [ "referenceNumber" ]
        },
        {
          "anyOf": [
            {
              "required": [ "documentNumber" ]
            },
            {
              "required": [ "stockNumber" ]
            }
          ]
        }
      ]
    }
```

**Comment by kulon** [comment]
HI @martin-mfg, please take a look at this sample app:
https://github.com/kulon/code-samples/tree/main/openapi-generator-sample 

Just changing the generator's version in the pom.xml from 7.6.0 to 7.10.0 will break the app.

**Comment by martin-mfg** [comment]
The problem occurs already in OpenAPI Generator version 7.9.0, according to my tests. i.e. it is not caused by this PR. Please open a new issue for your problem (assuming no similar issue has been opened yet).

**Comment by kulon** [comment]
Created a bug report https://github.com/OpenAPITools/openapi-generator/issues/20312

**Pull request merged**
