### PR TITLE
[java][resttemplate] avoid StringIndexOutOfBoundsException on empty HttpHeaders

### PR DESCRIPTION
**Pull request by ohl-nemeses**
Fix for https://github.com/OpenAPITools/openapi-generator/issues/12319

### CODE REVIEW

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

**Comment by wing328** [comment]
Tests with updated samples passed locally.

**Comment by wing328** [comment]
FYI. Samples updated via 5867845419d

**Comment by ohl-nemeses** [comment]
[wing328](https://github.com/wing328) Thanks a lot!

**Comment by wing328** [comment]
Thanks again for the PR, which has been included in the v6.0.0 release: https://twitter.com/oas_generator/status/1529669733934841856

**Pull request merged**
