### PR TITLE
feat: [JAVA] [webclient] [#16589] Support file abstraction for WebClient responses

### PR DESCRIPTION
**Pull request by tomdeering-wf**
Implements feature https://github.com/OpenAPITools/openapi-generator/issues/16589 using the same approach taken by https://github.com/OpenAPITools/openapi-generator/pull/13168 to implement that same feature for the `resttemplate` library.

The change is a simple find/replace of:
```mustache
 {returnType}
```
with
```mustache
#isResponseFile}}{{#useAbstractionForFiles}}[org.springframework.core.io](http://org.springframework.core.io/).Resource{{/useAbstractionForFiles}}{{^useAbstractionForFiles}}{{{returnType}}}{{/useAbstractionForFiles}}{{/isResponseFile}}{{^isResponseFile}}{{{returnType}}}{{/isResponseFile
```
Same thing for `{returnBaseType}`. The test yaml configuration is the same as the one added by https://github.com/OpenAPITools/openapi-generator/pull/13168. 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (7.0.1 - patch release), `7.1.x` (minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by tomdeering-wf** [comment]
Hi Java folks and @wing328! I think this is ready for your consideration. Not breaking any new ground here, just copying the approach taken in https://github.com/OpenAPITools/openapi-generator/pull/13168.
 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

**Comment by wing328** [comment]
thanks for the PR. can you please resolve the merge conflicts when you've time?

**Comment by tomdeering-wf** [comment]
@wing328 done! What do you think about targeting this against `master`? It would _technically_ be a breaking change for folks using the `webclient` library and configuring `useAbstractionForFiles = true`, but I see that in https://github.com/OpenAPITools/openapi-generator/pull/13168 nobody noted that. Thoughts?

**Comment by Somebodyisnobody** [comment]
I applied this to one of my projects. Works fine! I don't know why java.io.File was used for this. I expect a byte array when getting my response body.

**Comment by tomdeering-wf** [comment]
@Somebodyisnobody I think `java.io.File` makes sense for passing possibly-large binary data around. I believe this (`format: byte` vs `format: binary`) would yield your expected signature with an array of bytes:

```yaml
openapi: '3.0.1'
info:
  version: 1.0.0
  title: Response file abstraction test
paths:
  /resource:
    get:
      tags:
        - resource
      description: Response file abstraction
      operationId: resourceInResponse
      responses:
        '200':
          description: Successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: byte
```

**Comment by Somebodyisnobody** [comment]
> @Somebodyisnobody Thank you for testing! I think `java.io.File` makes sense for passing possibly-large binary data around that may or may not fit in memory. I believe this (`format: byte` vs `format: binary`) would yield your expected signature with an array of bytes

Yes that's partly correct: If i specify "byte" the data are transmitted as base64 representation. But actually the service I am talking with is returning an application/pdf as raw bytes. When using the "spring" generator for the server a Spring Resource class is returned on "format: binary".

**Comment by wing328** [comment]
I did a test:
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java --library webclient -i modules/openapi-generator/src/test/resources/3_0/issue13146_file_abstraction_response.yaml -o /tmp/webclient3/ --additional-properties useAbstractionForFiles=true
```
but got the following errors when running `mvn clean package`:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /private/tmp/webclient3/src/test/java/org/openapitools/client/api/ResourceApiTest.java:[42,55] incompatible types: org.springframework.core.io.Resource cannot be converted to java.io.File
[INFO] 1 error

```
Can you please take a look when you've time?

**Comment by tomdeering-wf** [comment]
@wing328 I tried to repro what you found but I can't on my machine. I went ahead and pulled in latest master, but still everything passes. What might I be missing?

**Comment by tomdeering-wf** [comment]
_Now_ the generated test passes on my machine :smile:

**Comment by tomdeering-wf** [comment]
Hmm, that's fun. The example works now on my machine, but it appears I've broken CI with that latest commit.

**Comment by tomdeering-wf** [comment]
Well that didn't work... I notice that `resttemplate` has the same issue (the generated test file doesn't compile), so whatever the fix should be, let's apply it to both...

**Comment by tomdeering-wf** [comment]
Turns out that Markdown-style links don't compile so well in Java land :man_facepalming:. Should be fixed, great catch @wing328! I gave the generated test for `resttemplate` the same treatment. 

It looks like currently the Java codegen tests only validate that the generated Java sources can be parsed, not compiled. Could we beef up CI to catch this in the future? Or would that be too slow/expensive to compile each generated project?

**Comment by tomdeering-wf** [comment]
@wing328 @Somebodyisnobody anything else I need to look at changing?

**Comment by Somebodyisnobody** [comment]
Oh i didn't test it, i just nicked the mustache file :)

**Comment by wing328** [comment]
tested locally and the result is good:
```
[INFO] Surefire report directory: /private/tmp/webclient3/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.openapitools.client.api.ResourceApiTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.003 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 1

[INFO] 

```

will merge it and later add a test to cover this issue moving forward

thanks for fixing the issue in resttemplate as well.

**Pull request merged**
