### PR TITLE
[typescript] Make TypeScriptClientCodegen extend AbstractTypeScriptClientCodegen

### PR DESCRIPTION
**Pull request by lwj5**
In https://github.com/OpenAPITools/openapi-generator/pull/10080#issuecomment-891660281 from @wing328 

> `modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java` also has this line of fix but TypeScriptClient codegen class doesn't extends `AbstractTypeScriptClientCodegen.java` at the moment.
> 
> In the future we may consider extending TypeScriptClient class with `AbstractTypeScriptClientCodegen`

This makes it easier to maintain

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by lwj5** [comment]
These 2 functions need to be correctly merged

toEnumName
getTypeDeclaration

**Comment by macjohnny** [comment]
IIRC the typescript client codegen was meant to be a rewrite for unification of all the typescript-variants there currently are, and intentionallly did not extend the abstract typescript codegen.
@TiFu to chime in

**Comment by lwj5** [comment]
@macjohnny it might seem so, but there are so many components that are reusable from AbstractTypeScriptClientCodegen that are exact duplicates. 

By extending It, we remove over 500+ lines of duplicate code (see code changes). I don't think it defeats the purpose of the unification, as any of these methods can be overridden.

**Review by TiFu — APPROVED** [review]
Totally fine for me :) 

Given the additional work that has gone into the AbstractTSClientCodegen, let's use it. The rewrite anyway re-used a lot of what AbstractTSClientCodegen was  back then, so no harm in continuing to use it and reduce the maintenance effort.

**Pull request merged**
