### PR TITLE
[swift5 client] fix filename for binary downloads

### PR DESCRIPTION
**Pull request by gretzki**
### Problem:

When a file download is handled within URLSessionImplementations,
the filename is retrieved via the header _Content-Disposition_ part of the response.
The header is looked for an entry starting with _filename=_. 
But the search is skipped too early, since the loop is exited if the first iteration does not match.

### Example:
Try to download a file with a swift5 client for a spec like this:
```
  /PublicDocument/Download:
    get:
      tags:
        - Public Area
      description: 'Document Download for Public Documents. Login not Required'
      parameters:
        - $ref: '#/components/parameters/queryId'
      responses:
        '200':
          description: 'OK'
          content:
            application/pdf:
              schema:
                type: string
                format: binary
```

When downloading from a server, the response header could have an answer like so:

```
Content-Disposition: attachment; filename=downloaded.pdf; filename*=UTF-8''downloaded.pdf
```

There, the server says to use downloaded.pdf as filename. But the actual implementation of the swift5 client will exit after checking _attachment_ and won't find `filename=` in the next section (separated by semicolon).

### Solution:
Simply replacing _break_ with _continue_ in the matching logic inside the loop fixes the algorithm.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
@jgavris, @ehyche, @Edubits, @jaz-ah, @4brunu

### CODE REVIEW

**Comment by 4brunu** [comment]
@gretzki Thanks for your contribution.
Could you please also fix this in the AlamofireImplementations? 

https://github.com/OpenAPITools/openapi-generator/blob/1d648223e6fdc1adad8967db05d86db9fc49a581/modules/openapi-generator/src/main/resources/swift5/libraries/alamofire/AlamofireImplementations.mustache#L276-L288

And to generate the sample projects, please run and commit the changes.
```
./mvnw clean package 
./bin/generate-samples.sh bin/configs/swift5-*
```

Thanks

**Comment by gretzki** [comment]
@4brunu sure. Done and done.
I realised it's also a bug for the swift4 client codegen but didn't fix it, since it's not relevant for the above mentioned client swift5. If you think it should be handled here too, I'm happy to fix that part too.

**Comment by 4brunu** [comment]
Swift4 client is now deprecated, so I'm not sure if it's worth the effort.
I think for now I prefer to focus on the Swift5 client, unless there is still demand for the Swift4 client.

**Comment by 4brunu** [comment]
CI is failing, but it's not related to this PR.
Looks good to me this PR 🙂

**Pull request merged**
