### PR TITLE
Fix incorrect @InputFile on inputSpecRootDirectory argument

### LINKED ISSUE #16419: [BUG][GRADLE] Gradle plugin does not properly support inputSpecRootDirectory
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

See #15483. The PR fixing this issue marks the configuration option with `@InputFile` which does not work for a directory. This causes the following exception to be thrown:

```
A problem was found with the configuration of task ':openApiGenerate' (type 'GenerateTask').
  - In plugin 'org.openapi.generator' type 'org.openapitools.generator.gradle.plugin.tasks.GenerateTask' property 'inputSpecRootDirectory' file 'C:\xx\xx\xx\contracts' is not a file.
```

##### openapi-generator version

`7.0.0` and `6.6.0`, haven't tried other versions.

##### OpenAPI declaration file content or url

N/A

##### Steps to reproduce

Use the plugin to generate two yamls that are in a directory. 

see https://github.com/Luckl/openapi-gradle-with-root-directory

##### Related issues/PRs

#15483

##### Suggest a fix

Change `@get:InputFile` to `@get:InputDirectory`

### PR DESCRIPTION
**Pull request by Luckl**
To fix #16419 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (7.0.1 - patch release), `7.1.x` (minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Thanks for the PR. Can you please add tests to cover the issue moving forward?

**Comment by wing328** [comment]
Just merged. Please help test the SNAPSHOT version (which will be published shortly in 30 mins)

**Comment by monisharajan** [comment]
Hi @wing328 , can you please let me know in which plugin version I can expect this fix ? I could see that it has been merged long before but any version is not published after.

**Comment by benmaes** [comment]
> Hi @wing328 , can you please let me know in which plugin version I can expect this fix ? I could see that it has been merged long before but any version is not published after.

I'm also interested in knowing when this will be released

**Comment by cromefire** [comment]
> Just merged. Please help test the SNAPSHOT version (which will be published shortly in 30 mins)

It doesn't seem like you can properly consume the SNAPSHOT versions properly with gradle (probably only with the old hacky way of specifying it, which I don't know if it's still supported at all and doesn't work with version catalogs), since the gradle plugin isn't published at it's plugin ID `org.openapi.generator:org.openapi.generator.gradle.plugin`.

**Pull request merged**
