### PR TITLE
[FIX][WIP][CORE] Bug/golden test ignoring deleted files

### PR DESCRIPTION
**Pull request by Fjolnir-Dvorak**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

The golden tests are generating new files without cleaning up no longer used files making the tests much less usefull. This Pull Request deletes the sample directory before running "ensure-up-to-date" to create a clean golden test which no longer ignores outdated files.
For that I had to modify the typescript scripts since those were copying files manually into the samples directory without checking if that directory is even existing.

### Changes:
- Every maven module in samples/ is now regenerated in bin/utils/ensure-up-to-date
- bin/utils/ensure-up-to-date is now callable from any directory instead only from project root
- samples/* will be deleted completely on bin/utils/ensure-up-to-date
- Files which are needed for testing are located in CI/samples.ci and are copied back into samples/ after bin/utils/ensure-up-to-date finished regenerating every client.
- samples/ contains only clients which are golden-tested by CircleCI.
- Every generated project in samples has to be build by the latest generator snapshot

 
### TODOs:
- Scalaz test was turned off for further testing since it failed. Issue for Scalaz: https://github.com/OpenAPITools/openapi-generator/issues/4072
- Java client vertx test was turned off for further testing since it failed.
- C test was turned off for further testing since it failed. This should be fixed in Pull request https://github.com/OpenAPITools/openapi-generator/pull/4055. Waiting for that to be merged into master to turn the test back on again.
- if it is guaranteed that every gen-project has the latest version the versionfile should/could be removed. Each version file would have to be changed/regenerated on a new release creating a lot of changes in git.

### What is not possible:
- CI/samples.ci cannot be linked into samples/ for less disk space usage. Reasons:
- - The windows C# test has problems, even if link support is turned on for windows
- - JavaScript does not honor the directory a file is located in. It follows the symlink and fails instead of searching the current directory for dependencies / references.
- Generated projects cannot be overridden and must be deleted instead. Reason: Some clients do not regenerate files if they already exists.

### CODE REVIEW

**Comment by Fjolnir-Dvorak** [comment]
Failing commands so far:
- Travis: `mvn --quiet --batch-mode --show-version verify -Psamples`
- Drone-io dart2x-test: `/usr/drone/bin/init: 23: cd: can't cd to samples/client/petstore/dart2/petstore`
- appveyor: CSC : `error CS1566: Error reading resource 'Org.OpenAPITools.Test.linux-logo.png' -- 'Could not find file 'C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools.Test\linux-logo.png'.' [C:\projects\openapi-generator\samples\client\petstore\csharp-netcore\OpenAPIClient\src\Org.OpenAPITools.Test\Org.OpenAPITools.Test.csproj]`
- Shippable: `mvn --quiet verify -P samples.shippable -Dmaven.javadoc.skip=true`

**Comment by Fjolnir-Dvorak** [comment]
The ensure-up-to-date does not generate all projects which are defined in pom.xml
There are a lot of projects missing which are not regenerated via ensure-up-to-date:
```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.openapitools:openapi-generator-project:4.1.3-SNAPSHOT (/home/rtiersch/workspace/cloned/openapi-generator/pom.xml) has 27 errors
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/c of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/elm-0.18 of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/rust of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/php/OpenAPIClient-php/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/openapi3/client/petstore/php/OpenAPIClient-php/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/server/petstore/php-slim/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/javascript/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/javascript-es6/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/openapi3/client/petstore/javascript-es6 of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/javascript-promise/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/javascript-promise-es6/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/javascript-flowtyped of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/python/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/python-experimental of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/python-asyncio/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/python-tornado/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/openapi3/client/petstore/python/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/typescript-node/npm/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/typescript-rxjs/builds/with-npm-version/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/typescript-angular-v4/npm/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/typescript-angular-v4.3/npm/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/typescript-angular-v6-provided-in-root/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/client/petstore/typescript-angular-v7-provided-in-root/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/server/petstore/rust-server/pom.xml of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/server/petstore/python-aiohttp of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/server/petstore/python-flask of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[ERROR]     Child module /home/rtiersch/workspace/cloned/openapi-generator/samples/server/petstore/python-flask-python2 of /home/rtiersch/workspace/cloned/openapi-generator/pom.xml does not exist
[
```

Shall those be removed from the pom.xml or added to ensure-up-to-date or are there more ensure-up-to-date scripts which need to be executed to be up to date?

**Comment by Fjolnir-Dvorak** [comment]
Current issues:
- continuous-integration/appveyor/pr is not supporting relative symlinks on checkout. Windows and git both support that feature so it should be fixable somehow...
- continuous-integration/travis-ci/pr has issues with the c client test: `./build-and-test.bash: line 19: ./unit-manual-PetAPI: No such file or directory`

**Comment by Fjolnir-Dvorak** [comment]
@zhemant can it be that the c tests are failing because v4.1.3 is tested now instead of 4.0.0? If not, could you help me please to find the issue? I tried it with an isolated build where I only regenerated the c samples which failed with the same error: https://github.com/OpenAPITools/openapi-generator/pull/4043 https://travis-ci.org/OpenAPITools/openapi-generator/builds/593049600?utm_source=github_status&utm_medium=notification

**Comment by Fjolnir-Dvorak** [comment]
@mandrean (2017/08), @jimschubert (2017/09) heart @frankyjuang (2019/09)
I added `-c core.symlinks=true` to the git clone in appveyor and hoped that would fix the issue with symlinks. It looks like it is still not working. Am I doing anything wrong or have you any other Idea on how to solve this issue without copying the files instead of linking?
copying the files into the sample directory seems to be quite dirty in my opinion.

**Comment by Fjolnir-Dvorak** [comment]
ATTENTION: I removed the C tests since they are broken in openapi-generator 4.1.3-SNAPSHOT

**Comment by Fjolnir-Dvorak** [comment]
php is working now. Tested via:
`docker run -ti -v $(pwd):/openapi azul/zulu-openjdk /bin/bash`

```
apt-get install maven composer php-curl php-mbstring php-dom php-zip
cd /openapi/
cd samples/client/petstore/php/OpenAPIClient-php/
mvn integration-test
```

**Comment by zhemant** [comment]
> @zhemant can it be that the c tests are failing because v4.1.3 is tested now instead of 4.0.0? If not, could you help me please to find the issue? I tried it with an isolated build where I only regenerated the c samples which failed with the same error: #4043 https://travis-ci.org/OpenAPITools/openapi-generator/builds/593049600?utm_source=github_status&utm_medium=notification

@Fjolnir-Dvorak the c test is breaking because the files are commented out from the cmakelists.txt. I will create a merge request with uncommitted code then it should not break.

**Comment by Fjolnir-Dvorak** [comment]
Thank you @zhemant

**Comment by zhemant** [comment]
> Thank you @zhemant

@Fjolnir-Dvorak I created a merge request, this should solve the problem. #4055

**Comment by Fjolnir-Dvorak** [comment]
Next error: 

```
2019-10-05 23:19:07.325:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.maven.plugin.JettyServer@614b2512: java.net.SocketException: Permission denied
java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.MavenServerConnector.doStart(MavenServerConnector.java:120)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.maven.plugin.JettyServer.doStart(JettyServer.java:73)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:534)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:357)
	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:167)
	at org.eclipse.jetty.maven.plugin.JettyStartMojo.execute(JettyStartMojo.java:48)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224:start (start-jetty) on project openapiv3-jaxrs-jersey-petstore-server: Failure: Permission denied -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openapiv3-jaxrs-jersey-petstore-server
Exited with code 1
```

**Comment by Fjolnir-Dvorak** [comment]
#!/bin/bash --login
./CI/circle_parallel.sh

Running node 1 to test 'samples.circleci' defined in pom.xml ...
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-3~14.04-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.prokarma:pkmst-microservice: (/home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/java-pkmst/pom.xml) has 1 error
[ERROR]     'version' is missing. @ com.prokarma:pkmst-microservice:[unknown-version], /home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/java-pkmst/pom.xml, line 6, column 13
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
Exited with code 1

**Comment by jimschubert** [comment]
@Fjolnir-Dvorak I've just merged #6325 to add a `FILES` metadata file to our generated output. I have additional work in #6357 to clean up template management, and this will resolve some issues with the files list returned by the generate method. Once that's merged, I will help out with the work you've done here to delete files from previous generations so that regeneration gives us a "clean slate".

**Comment by jimschubert** [comment]
Closing in favor of #7465 please check it out when you have time.

**Pull request closed without merging**
