### PR TITLE
[C#] dependency upgrade

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @mandrean (2017/08), @jimschubert (2017/09) ❤️ @frankyjuang (2019/09) @shibayan (2020/02)

### CODE REVIEW

**Comment by wing328** [comment]
@Bouillie Shall we restore the following files (deleted)?
- samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools.Test/Client/ApiClientTests.cs
- samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools.Test/Client/ConfigurationTests.cs

**Comment by wing328** [comment]
@shibayan good point. I think you're referring to https://github.com/OpenAPITools/openapi-generator/pull/5870/files#diff-db386c4ec8dda44f0c2605ebc719fc81L170

Those changes are due to test files being deleted and regenerated again as test files are not overwritten by default.

**Comment by Bouillie** [comment]
@wing328 @shibayan Actually, I think this commit: 7af5d63f172e94cd6ef7ea582af858789f49548d should be reverted. Then re-run ./bin/csharp-petstore.sh. This way, only the project file is modified.

To achieve this commit, I actually deleted the whole directory before regenerating, which was a mistake. What I still find strange is that regenerating test files don't overwrite the existing ones.

**Comment by wing328** [comment]
@Bouillie up to you - revert the commit or just add back the deleted files

**Comment by Bouillie** [comment]
I'm on it. Should I create another PR on csharp-upgrade?

**Comment by wing328** [comment]
Yes please

**Comment by Bouillie** [comment]
Here it is: https://github.com/OpenAPITools/openapi-generator/pull/5879

**Pull request merged**
