### PR TITLE
Fix enum generation for php-symfony generator

### PR DESCRIPTION
**Pull request by renaud-twd**
@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), [@ybelenko](https://github.com/ybelenko) (2018/07), @renepardon (2018/12)

Currently, the `model generic` template is used to generate all DTO classes including enums.
This results in empty classes for enums.

This PR just make use of the existing `model enum` template to generate enum DTOs.

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
@renaud-twd thanks for the PR. Can you please merge the latest master (which includes https://github.com/OpenAPITools/openapi-generator/pull/14117 with a test for enum model) into your branch?

**Comment by renaud-twd** [comment]
@wing328 thanks for the feedback.
I rebased on top of the latest master (which includes https://github.com/OpenAPITools/openapi-generator/pull/14117).
I also regenerated samples and docs.

**Comment by renaud-twd** [comment]
hello @wing328,
is there anything else preventing this PR to be merged ?

**Comment by wing328** [comment]
Nope. Looks good. Sorry for the delay and thanks again for the PR.

**Pull request merged**
