### PR TITLE
Correct use of loggers with placeholders and remove some redundant operations

### PR DESCRIPTION
**Pull request by agilob**
1. Removed some redundant operations from `static{}` blocks, unnecessary casts, object creation and a few more.
2. Fixed use of loggers in DefaultCodegen to use object placeholders which are faster, decrease object allocation in String pool and adds nullsafety in loggers

### CODE REVIEW

**Comment by agilob** [comment]
@wing328  @jimschubert

**Comment by agilob** [comment]
Another commit replaces very frequently used `string.replace()` with pattern / matcher / replace where pattern is compiled ahead of time to reduce number of times of compiling pattern in `java.lang.String.replaceAll`. Method doing String.replace is called in loops.

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

**Comment by agilob** [comment]
No one from this list ever responds

**Review by wing328 — APPROVED** [review]
LGTM

**Comment by agilob** [comment]
Thanks

**Pull request merged**
