### PR TITLE
Fix missing import for JsonTypeName

### LINKED ISSUE #8157: [BUG] [java] [resttemplate] Generated alias models missing JsonTypeName import
##### Description
When generating client code with openapi-generator and the `generateAliasAsModel` option set to `true`, model classes generated from aliases are missing an import statement for the JsonTypeName annotation and fail to compile.

##### openapi-generator version
5.0.0-x

##### OpenAPI declaration file content or url
Example [swagger contract](https://github.com/mikesaurus/openapi-gen-alias-type-bug/blob/main/src/main/resources/swagger.json).

##### Generation Details
The code is being generated using the Maven plugin.  See [example project](https://github.com/mikesaurus/openapi-gen-alias-type-bug).

##### Steps to reproduce
1. See example project [README](https://github.com/mikesaurus/openapi-gen-alias-type-bug/blob/main/README.md).
2. Change the `openapi-generator-maven-plugin.version` in the POM file to any 5.0.0-x version and build.

##### Related issues/PRs
None.

##### Suggest a fix
Include the JsonTypeName import for both standard and alias model classes.

### PR DESCRIPTION
**Pull request by jakubskopal**
Attempt to fix #8157

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch

### CODE REVIEW

**Comment by doctau** [comment]
This PR fixes the problem for me

**Comment by Blubb324** [comment]
Hi guys,
@wing328 : Will this merged soon because the bug is still existing in version: 5.2.0 ?

**Review by wtrocki — APPROVED** [review]

**Comment by Richard-Mathie** [comment]
CI CD job errored. Dose this need a rebase?

**Comment by jakubskopal** [comment]
@Richard-Mathie dunno, what is the error? Unfortunately I don't have access to circleci.

**Comment by wing328** [comment]
CircleCI tests (with updated samples) passed via https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/12924/workflows/753aba04-265a-4460-bb2e-0a565e4f3136/jobs/26561

**Comment by wing328** [comment]
Sorry for the delay. The PR has been merged. Thanks for the contribution.

**Pull request merged**
