### PR TITLE
Implement Swift 5 support

### PR DESCRIPTION
**Pull request by Tovkal**
This implements Swift 5 support.

Not sure if I have to ask for review from the Technical Committee nor how to do it.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
cc @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @d-date (2018/03) @4brunu (2019/11)

**Comment by Tovkal** [comment]
I have noticed there are still a couple of things that need to be done. I will continue working on this today.

**Comment by 4brunu** [comment]
There is already similar PR https://github.com/OpenAPITools/openapi-generator/pull/4086.
But it's not merged.
@Tovkal can you please explain what changes did you introduced compared to Swift 4 generator?

**Comment by Tovkal** [comment]
@4brunu Didn't see that PR. Nothing really, it also just copies the Swift 4 generator. Any reason why this PR has been stale for so many months?

**Comment by 4brunu** [comment]
You can check the reasons for this in https://github.com/OpenAPITools/openapi-generator/pull/4086.
But thanks for your PR 🙂 👍

**Pull request closed without merging**
