### PR TITLE
[go] Fix issue #51, change object mapping from *interface{} to map[st…

### LINKED ISSUE #51: [go] map type object *interface{} convert problem
##### Description

Definition property "type": "object" gets converted to *interface{} which returns an error when set to a struct or pointer pointer.

##### openapi-generator version

3.0.0
##### Suggest a fix/enhancement

Instead of an *interface{} map the object to map[string]interface{}

### PR DESCRIPTION
**Pull request by ilk**
### PR checklist
- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

To fix #51  I propose the following changes:

1. map swagger object type to map[string]interface{} instead of *interface{} 
2. removing pointer since a map is already a reference type

### Technical Commitee

@antihax 
@wing328

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
cc @bvwells as well

**Comment by wing328** [comment]
@ilk Can you also please run `./bin/go-petstore.sh` or `.\bin\windows\go-petstore.bat` to update the petstore samples (tested by the CI)

**Comment by wing328** [comment]
I've resolved the conflicts locally, updated the sample and triggered a CI job to test the updated Go Petstore. The result is good: https://circleci.com/gh/OpenAPITools/openapi-generator/617 (the failure is due to Scala client downloading dependencies, not related to Go client changes).

If no one has any feedback/question, I'll merge it on coming Friday.

cc @antihax @bvwells

**Comment by jimschubert** [comment]
@wing328 bumping this. You should be able to do a 3 way merge locally and assign the author info manually, if that's cool with @ilk.

**Comment by wing328** [comment]
@jimschubert thanks. I just merge it and will send another PR to update the Go petstore sample

**Comment by bergerdenes** [comment]
This change made Map<String, Object> unmarshaling in Go impossible. :(

**Pull request merged**
