### PR TITLE
[Python] Fixed docstrings in api.mustache

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/swagger-api/swagger-codegen/issues/9630

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
@Ark-kun thanks for the PR.

We also have a new `python-experimental` client generator, which has better support for new features in OAS v3 such as oneOf, allOf, etc

You may want to give it a try and file a similar fix to the `python-experimental` client generator.

**Comment by Ark-kun** [comment]
> You may want to give it a try and file a similar fix to the `python-experimental` client generator.

Done. It's probably OK to do that in one PR.

**Comment by wing328** [comment]
Can you please also run the following to update the OAS v3 samples?

```
./bin/openapi3/python-petstore.sh
./bin/openapi3/python-experimental-petstore.sh
```

cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01) @arun-nalla (2019/11) @spacether (2019/11)

**Comment by arun-nalla** [comment]
@Ark-kun 

I have checked the documentation for sphinx (https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html)

```
:param [ParamName]: [ParamDescription], defaults to [DefaultParamVal]
:type [ParamName]: [ParamType](, optional)
```

I did not find the format that is used in this PR in the docs, please do let me know if this format is mentioned somewhere. Can we use the format that is mentioned in the doc instead ?

**Comment by spacether** [comment]
> @Ark-kun
> 
> I have checked the documentation for sphinx (https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html)
> 
> ```
> :param [ParamName]: [ParamDescription], defaults to [DefaultParamVal]
> :type [ParamName]: [ParamType](, optional)
> ```
> 
> I did not find the format that is used in this PR in the docs, please do let me know if this format is mentioned somewhere. Can we use the format that is mentioned in the doc instead ?

We did not have a standardized docstring format yet but sphinx is fine.
- Can you update the [python readme mustache template](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/README.mustache) to mention that we should use sphinx docstrings and include a link to that?
- Can you add a `Function and Class Documentation` section to [the contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md) and add a  section in python linking to the sphinx docstring info?

**Comment by spacether** [comment]
> > We also have a new python-experimental client generator, which has better support for new features in OAS v3 such as oneOf, allOf, etc
> 
> Sounds great.
> 
> > You may want to give it a try and file a similar fix to the `python-experimental` client generator.
> 
> Done. It's probably OK to do that in one PR.

@Ark-kun there are many many docstrings in python-experimental including:
- docstrings in model_utils
- docstrings in api.pi
- docstrings in every model
Also in python-experimental we use our data type to define types that python accepts
So if a model has a property that accepts list of list of str that data type in python-experimental will be [[str]]. Fixing this in python-experimental will likely require adding a new property that is stored alongside dataType, maybe documentationDataType in the java layer.

How about separating off python-experimental changes as a separate PR?

**Comment by Ark-kun** [comment]
> I did not find the format that is used in this PR in the docs, please do let me know if this format is mentioned somewhere. Can we use the format that is mentioned in the doc instead ?

I've amended my changes to comply with the doc you've linked.

Can you please take another look?

Thanks.

**Comment by Ark-kun** [comment]
> Can you please also run the following to update the OAS v3 samples?
> 
> ```
> ./bin/openapi3/python-petstore.sh
> ./bin/openapi3/python-experimental-petstore.sh
> ```

Done.

Some files there might have been stale, so they are now modified even though they are unrelated to this PR.

**Pull request merged**
