### PR TITLE
Add async native Java Client

### PR DESCRIPTION
**Pull request by UkonnRa**
### Related Issue

https://github.com/OpenAPITools/openapi-generator/issues/4715

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by UkonnRa** [comment]
@lwlee2608 Add the support of async native Java Client

**Comment by wing328** [comment]
cc @bbdouglas as it's related to Java 11 Native client.

**Comment by wing328** [comment]
Instead of adding another option. What about adding an "Async" version of the function similar to what we've done in other Java client libraries (e.g. okhttp-gson)? e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/api.mustache#L283

e.g. addPet => addPetAsync (and addPet simply calls addPetAsync and wait for the completion)

**Comment by joerg-wille** [comment]
@UkonnRa What is the status of the native async patch? Your changes look good.

**Comment by wing328** [comment]
UPDATE: I've resolved the merge conflicts, update samples and include the native async petstore client in the drone.io CI tests.

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

**Comment by wing328** [comment]
CircleCI failure due to outdated doc/samples. Will fix it in a separate commit after merging into master.

**Comment by wing328** [comment]
@UkonnRa thanks for the PR, which has been merged into master.

When you're free, I wonder if you can PM me via Slack (https://github.com/OpenAPITools/openapi-generator.git) for a quick chat (IM). Thank you.

**Pull request merged**
