### PR TITLE
Fix #6157: Updated native template to fix null async return

### LINKED ISSUE #6157: [BUG][JAVA][NATIVE][ASYNC] Java Client Native Async does not work with list
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [4.3.1-SNAPSHOT] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [No Data] What's the actual output vs expected output?

##### Description

`ListSubscriptionsResponse` is always null when calling `listSubscriptions`

This should return the real value

##### openapi-generator version

4.3.1-SNAPSHOT (No regression this a bug on a new feature)

##### OpenAPI declaration file content or url

OpenAPI Spec
[DataLake-Subscription-SwaggerDocumentation.json.zip](https://github.com/OpenAPITools/openapi-generator/files/4572560/DataLake-Subscription-SwaggerDocumentation.json.zip)

##### Command line used for generation
in `build.gradle.kts`

```
openApiGenerate {
    inputSpec.set("https://xxx.yyy.zzz")
    validateSpec.set(true)
    generatorName.set("java")
    engine.set("mustache")
    skipOverwrite.set(false)
    outputDir.set(openApiGeneratedDir)
    apiPackage.set("datalake.subscription.api")
    invokerPackage.set("datalake.subscription.invoker")
    modelPackage.set("datalake.subscription.model")
    generateApiTests.set(false)
    generateApiDocumentation.set(false)
    generateModelTests.set(false)
    generateModelDocumentation.set(false)
    configOptions.set(mapOf(
            "java8" to "true",
            "dateLibrary" to "java8",
            "library" to "native",
            "asyncNative" to "true",
            "serializationLibrary" to "jackson"
    ))
```

##### Steps to reproduce

call `listSubscriptions` after generation

The code that's generated just looks wrong, looks like it always returns null.
```
  public CompletableFuture<ListSubscriptionsResponse> listSubscriptions (String maxItems, String ownerId, String nextToken) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/";

    List<Pair> localVarQueryParams = new ArrayList<>();
    localVarQueryParams.addAll(ApiClient.parameterToPairs("max-items", maxItems));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("owner-id", ownerId));
    localVarQueryParams.addAll(ApiClient.parameterToPairs("next-token", nextToken));

    if (!localVarQueryParams.isEmpty()) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

      localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
      if (memberVarReadTimeout != null) {
        localVarRequestBuilder.timeout(memberVarReadTimeout);
      }
      if (memberVarInterceptor != null) {
        memberVarInterceptor.accept(localVarRequestBuilder);
      }
      return memberVarHttpClient.sendAsync(
              localVarRequestBuilder.build(),
              HttpResponse.BodyHandlers.ofString()).thenComposeAsync(localVarResponse -> {
          if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(new ApiException(localVarResponse.statusCode(),
                  "listSubscriptions call received non-success response",
                  localVarResponse.headers(),
                  localVarResponse.body())
              );
          } else {
              return CompletableFuture.completedFuture(
                      null
              );
          }
      });
  }
```

### PR DESCRIPTION
**Pull request by laballab**
Fixes issue: https://github.com/OpenAPITools/openapi-generator/issues/6157
@wing328 @UkonnRa @joerg-wille

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by AceHack** [comment]
I can't wait for this PR to get approved since it fixes my issue!! :). Thanks @laballab 

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

**Comment by AceHack** [comment]
How can we retest, the failing test is unrelated and seems to just be a flakey test.

**Comment by laballab** [comment]
Not sure why the Swift check failed as this this doesn't touch any Swift stuff.. 

Possible to retest?

**Pull request merged**
