### PR TITLE
[typescript][jQuery] Fix promise resolution

### PR DESCRIPTION
**Pull request by grollinger**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(Port of swagger-api/swagger-codegen#8385)

Resolves #581

### CODE REVIEW

**Comment by macjohnny** [comment]
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01)

**Comment by macjohnny** [comment]
@grollinger thanks for your PR. you could also add the `typescript-jquery` to https://github.com/ackintosh/openapi-generator-1/blob/master/bin/utils/ensure-up-to-date#L29 to have the CI check for each PR that the jquery samples have been generated correctly.

**Comment by macjohnny** [comment]
the shippable build fails because `samples/server/petstore/php-slim/phpunit.xml.dist` is not up to date. @wing328 could you update the file? then the PR should be ready to be merged.

**Comment by wing328** [comment]
> the shippable build fails because samples/server/petstore/php-slim/phpunit.xml.dist is not up to date. @wing328 could you update the file? then the PR should be ready to be merged.

Thanks for pointing it out. We will take care of that

**Comment by wing328** [comment]
@grollinger  thanks for the PR, which has been merged into master.

@macjohnny thanks for reviewing the PR.

**Pull request merged**
