### PR TITLE
Add an option to generate the alias (map, array) as model

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
> The CodegenOperation has returnBaseType = 'Map' but returnType = 'List<A>', which won't compile because class A is no longer generated. I didn't see any code below to rectify this issue.

If I understand correctly, this issue already exists in the current master so please open an issue to track it instead.

The goal of this PR is to restore the old behaviour to generate alias (map, array) as model. and I believe your use case is to set `generateAliasAsModel` to true. If the issue mentioned above still occurs, please kindly mention in the new issue created.

**Comment by demonfiddler** [comment]
Fair enough - the problem with the current behaviour can be seen as a separate issue, which I'll log in due course. In the meantime I'd be happy for the PR to proceed. Many thanks for the rapid turnaround William.

**Comment by demonfiddler** [comment]
Looks like there's a problem. I just rebased onto upstream/option_generate_alias_model and now I'm getting an NPE in my code because CodegenModel.additionalPropertiesType is no longer being set (to AttributeValue) for the alias type (AuditEvent extends Map<String, AttributeValue>).

**Comment by demonfiddler** [comment]
Thanks. With the suggested addAdditionPropertiesToCodeGenModel() override, generating from the CLI with the --generate-alias-as-model option now seems to work, and my AuditEvent (and other alias classes) are generated and referenced correctly in the API's CXF implementation class. My only question is: why is it necessary for the generator sub-class to do this in an override? For backwards compatibility shouldn't it be done automatically by DefaultCodegen? 

**However**, the \<generateAliasAsModel>true\</generateAliasAsModel> Maven plug-in configuration option has no effect. I tried it in both execution/configuration and execution/configuration/configOptions - under the debugger I can see that additionalProperties does not contain the key "generateAliasAsModel" at DefaultCodegen line 213 (```if (additionalProperties.containsKey(CodegenConstants.GENERATE_ALIAS_AS_MODEL)) { etc...```).

**Pull request merged**
