### PR TITLE
[erlang-client] Fix url path generation being passed to hackney_url

### PR DESCRIPTION
**Pull request by dweinstein**
This change is attempting (draft currently) to fix a regression in URL Paths in the erlang-client. The current pet_store sample erlang-client does not work against the real `petstore.swagger.io` because of a regression in the Path introduced in https://github.com/OpenAPITools/openapi-generator/commit/cdc00769aadb46d4617fbec35daee643e95b7926.

Currently if one makes a request for pet id `10` the api client will make a request for `%0a` instead.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date.sh
  ``` 
  Commit all changed files.
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [ ] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by dweinstein** [comment]
Looks like the change to the path generation was made in https://github.com/OpenAPITools/openapi-generator/commit/cdc00769aadb46d4617fbec35daee643e95b7926 which was trying to fix another issue perhaps.

**Comment by wing328** [comment]
@dweinstein thanks for the PR. can you please PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by wing328** [comment]
as discussed, let's move ahead with this change. i'll merge and update the samples.

**Comment by wing328** [comment]
samples updated via 6d71db3d6db

**Comment by dweinstein** [comment]
thanks @wing328 sorry that I hadn't had the chance to make the tweaks to the mustache stuff for the integer handling. It's still on my list.

**Comment by wing328** [comment]
take your time.

in other generators, we use something like `String.valueOf()` to force the input (integer, double, string, etc) into string. 

not sure if erlang has something similar.

**Pull request merged**
