### PR TITLE
[Java] parameterize formParams

### LINKED ISSUE #5782: [BUG][Java] Raw MultiValueMap instances created for formParams
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Compiler warnings are generated from Api classes as formParams is not parameterised.

##### openapi-generator version

openapi-generator-maven-plugin 4.3.0 - needs to be fixed in master

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache#L119

##### Command line used for generation

n/a - this is present in your samples: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/StoreApi.java#L88

##### Steps to reproduce

n/a - this is present in your samples: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/api/StoreApi.java#L88

##### Related issues/PRs

n/a

##### Suggest a fix

Just add the parameters: `<String, Object>`

### PR DESCRIPTION
**Pull request by jonfreedman**
fixes #5782

Fixes errorprone compiler warnings in generated code due to use of raw MultiValueMap type.  Due to generic type parameter issues with Spring's MultiValueMap I have updated the Spring dependencies to the latest 5.2.5.RELEASE version in order to pick up the `addAll` method although any version >= 5.0.0.RELEASE should work fine.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608  @bkabrda

### CODE REVIEW

**Comment by jonfreedman** [comment]
Can someone with permission please re-try the failed checks

**Comment by jonfreedman** [comment]
@wing328 could you take a look at this one too?

**Comment by wing328** [comment]
@jonfreedman can you please resolve the merge conflicts when you've time? I'll then review and merge accordingly.

**Comment by jonfreedman** [comment]
I did a merge, looks like all the scripts to re-generate clients have been removed?

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-the-samples-i-couldnt-find-the-script-under-bin-or-windows-batch-files-under-binwindows

**Comment by jonfreedman** [comment]
Ok I think we are there now, please take a look at the review

**Comment by jonfreedman** [comment]
As you can see from my final commit, whilst it's possible to re-generate samples on windows that causes the CircleCI build to fail - the path separators in each FILES listing need to be `/` not `\`

**Pull request merged**
