### PR TITLE
[Java][Spring] Add Spring pagination with vendor extension x-spring-paginated

### PR DESCRIPTION
**Pull request by david1601**
**PR detail**
By setting of x-spring-paginated: true for an operation in the yaml file at the same level as operationId this pull request add a Spring Pageable (org.springframework.data.domain.Pageable) parameter if JavaSpring is used.

The idea for the solution based on: https://github.com/swagger-api/swagger-codegen/pull/3357.

Spring Pageable: https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Pageable.html

**In yaml-file:**
operationId: findPetsByTags
x-spring-paginated: true

**Created PetApi.java:**
```
    @ApiOperation(value = "Finds Pets by tags", nickname = "findPetsByTags", notes = "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.", response = Pet.class, responseContainer = "List", authorizations = {
        @Authorization(value = "petstore_auth", scopes = {
            @AuthorizationScope(scope = "write:pets", description = "modify pets in your account"),
            @AuthorizationScope(scope = "read:pets", description = "read your pets")
            })
    }, tags={ "pet", })
    @ApiImplicitParams({
        @ApiImplicitParam(name = "page", dataType = "integer", paramType = "query",
                value = "Results page you want to retrieve (0..N)"),
        @ApiImplicitParam(name = "size", dataType = "integer", paramType = "query",
                value = "Number of records per page."),
        @ApiImplicitParam(name = "sort", allowMultiple = true, dataType = "string", paramType = "query",
                value = "Sorting criteria in the format: property(,asc|desc). " +
                        "Default sort order is ascending. " +
                        "Multiple sort criteria are supported.")
    })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Pet.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid tag value") })
    @RequestMapping(value = "/pet/findByTags",
        produces = { "application/xml", "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<List<Pet>> findPetsByTags(@NotNull @ApiParam(value = "Tags to filter by", required = true) @Valid @RequestParam(value = "tags", required = true) List<String> tags, @ApiIgnore final Pageable pageable) {
```
**PR checklist**
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under ./bin/ (or Windows batch scripts under .\bin\windows) to update Petstore samples related to your fix. This is important, as CI jobs will verify all generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run ./bin/{LANG}-petstore.sh, ./bin/openapi3/{LANG}-petstore.sh if updating the code or mustache templates for a language ({LANG}) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): master, 4.3.x, 5.0.x. Default: master.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

**Technical committee for programming language Java:**
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)

### CODE REVIEW

**Comment by david1601** [comment]
I executed the script ./bin/utils/ensure-up-to-date on my computer with no problem. The script showed “spring-all-petstore.sh successfully!”. But the check ci/circleci in the cloud showed the error “ERROR: Failed to run /home/circleci/OpenAPITools/openapi-generator/bin/spring-all-petstore.sh”. What is the reason for that?

**Comment by bilak** [comment]
@david1601 could you please rebase and run scripts?

**Comment by adavidhon** [comment]
@david1601 @wing328 do you have any news on this PR? Is the merge planned anytime in the near future?

**Review by mpraki — APPROVED** [review]

**Comment by samgurtman** [comment]
So basically you've made everyone have to use Spring Data. You should not be forcing adding additional dependencies on people to satisfy a single use case.

**Comment by patst** [comment]
This breaks our build as well because we don't use neither spring-data (therefore not have `org.springframework.data.domain.Pageable` on the classpath) nor springfox (therefore lacking `springfox.documentation.annotations.ApiIgnore`).

 Can we revert this or make it at least optional?

**Comment by mercuriete** [comment]
I have the same problem @patst 
```import org.springframework.data.domain.Pageable;```
is generated but never used.
so I think is a bug.

apart from that.... I dont want to add

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
```
because my app is not using JPA at all.

**Comment by amelnikoff** [comment]
Usually spring-data methods with Pageable support returns [Page](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Page.html) object.
Any chance this implemented too?

**Pull request merged**
