### PR TITLE
Update go-experimental petstore sample

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
CI failure:
```
PASS
ok  	_/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/go	0.625s
# _/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/go-experimental/go-petstore
go-petstore/api_fake.go:19:2: imported and not used: "reflect"
go-petstore/api_fake.go:1223:30: http.MethodPut undefined (type []string has no field or method MethodPut)
go-petstore/api_fake.go:1234:28: url.Values undefined (type []string has no field or method Values)
go-petstore/api_fake.go:1235:27: url.Values undefined (type []string has no field or method Values)
go-petstore/api_fake.go:1269:29: ioutil.ReadAll undefined (type []string has no field or method ReadAll)
FAIL	_/home/circleci/OpenAPITools/openapi-generator/samples/client/petstore/go-experimental [build failed]
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (go-test) on project GoExperimentalPetstore: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
```

@bkabrda I wonder if you can take a look when you've time.

**Comment by bkabrda** [comment]
Yeah, I can take a look later today/tomorrow.

**Comment by bkabrda** [comment]
@wing328 maybe I'm missing something, but I think you didn't actually update the templates that to add the leading underscore to the imports (you only did that on the other PR for `go/` templates, but `go-experimental/` has another set of templates where the renames were not done yet.

**Comment by wing328** [comment]
There's another PR to add the leading underscore.

This PR simply update the samples (go-experimental petstore) with the newly-added test cases (different collectFormats) but it already failed so I think this needs to be addressed first.

From what I can tell, the PR to add the leading underscore doesn't cause the CI failure.

**Comment by bkabrda** [comment]
Yeah, the problem is that the newly added testcases are the cause for the errors that you listed in your previous comment. E.g. for the error

```
go-petstore/api_fake.go:1223:30: http.MethodPut undefined (type []string has no field or method MethodPut)
```

The problem is caused by https://github.com/OpenAPITools/openapi-generator/pull/3660/files#diff-0d30a45708fbefc467b0fc5163fadd02R1125 and is solved by #3659. You'll need to merge that first and rebase this PR on top of it to make tests pass.

**Comment by wing328** [comment]
We can't merge #3659 as the tests failed: https://github.com/OpenAPITools/openapi-generator/pull/3659#issuecomment-523394360

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/3659

**Pull request closed without merging**
