### PR TITLE
Fix for issue #3397

### LINKED ISSUE #3397: [BUG] Callback request and response not being flattened to InlineObjects
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url

When trying to run codegein against the following OpenApi3 yaml snippet:
```yaml
 /ue-contexts/{ueContextId}/n1-n2-messages/subscriptions:
    post:
      summary: Namf_Communication N1N2 Message Subscribe (UE Specific) service Operation
      tags:
        - N1N2 Subscriptions Collection for Individual UE Contexts (Document)
      operationId: N1N2MessageSubscribe
      parameters:
        - name: ueContextId
          in: path
          description: UE Context Identifier
          required: true
          schema:
            type: string
            pattern: '^(5g-guti-[0-9]{5,6}[0-9a-fA-F]{14}|imsi-[0-9]{5,15}|nai-.+|imei-[0-9]{15}|imeisv-[0-9]{16}|.+)$'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UeN1N2InfoSubscriptionCreateData'
        required: true
      responses:
        '201':
          description: N1N2 Message Subscription successfully created.
          headers:
            Location:
              description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/namf-comm/v1/{ueContextId}/n1-n2-messages/subscriptions/{subscriptionId}'
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UeN1N2InfoSubscriptionCreatedData'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
      callbacks:
        onN1N2MessageNotify:
          '{$request.body#/n1NotifyCallbackUri}':
            post:
              summary: Namf_Communication N1 Message Notify service Operation
              tags:
                - N1 Message Notify
              operationId: N1MessageNotify
              requestBody:
                description: N1 Message Notification
                content:
                  multipart/related:  # message with binary body part(s)
                    schema:
                      type: object
                      properties: # Request parts
                        jsonData:
                          $ref: '#/components/schemas/N1MessageNotification'
                        binaryDataN1Message:
                          type: string
                          format: binary
                    encoding:
                      jsonData:
                        contentType:  application/json
                      binaryDataN1Message:
                        contentType:  application/vnd.3gpp.5gnas
                        headers:
                          Content-Id:
                            schema:
                              type: string
              responses:
                '204':
                  description: Expected response to a successful callback processing
                '400':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/400'
                '403':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/403'
                '411':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/503'
          '{$request.body#/n2NotifyCallbackUri}':
            post:
              summary: Namf_Communication N2 Info Notify (UE Specific) service Operation
              tags:
                - N2 Info Notify
              operationId: N2InfoNotify
              requestBody:
                description: UE Specific N2 Informaiton Notification
                content:
                  multipart/related:  # message with binary body part(s)
                    schema:
                      type: object
                      properties: # Request parts
                        jsonData:
                          $ref: '#/components/schemas/N2InformationNotification'
                        binaryDataN1Message:
                          type: string
                          format: binary
                        binaryDataN2Information:
                          type: string
                          format: binary
                    encoding:
                      jsonData:
                        contentType:  application/json
                      binaryDataN1Message:
                        contentType:  application/vnd.3gpp.5gnas
                        headers:
                          Content-Id:
                            schema:
                              type: string
                      binaryDataN2Information:
                        contentType:  application/vnd.3gpp.ngap
                        headers:
                          Content-Id:
                            schema:
                              type: string
              responses:
                '204':
                  description: Expected response to a successful callback processing
                '400':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/400'
                '411':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/503'
```
Our expected generated code should look like
```java
public interface N1n2messagesubscribeCallbackApi extends Api {
    
    public static final String BASE_PATH = "n1n2messagesubscribe-callback";
            Single<Response<Void>> n1MessageNotify(String requestURI, InlineObject1 inlineObject1, FlowContext ctx, MultiMap requestHeaders);
            Single<Response<Void>> n2InfoNotify(String requestURI, InlineObject2 inlineObject2, FlowContext ctx, MultiMap requestHeaders);

}
```

However the inline object is not defined. InlineObject become UNKNOWN_BASE_TYPE instead.
generated java code:
```java
public interface N1n2messagesubscribeCallbackApi extends Api {
    
    public static final String BASE_PATH = "n1n2messagesubscribe-callback";
            Single<Response<Void>> n1MessageNotify(String requestURI, UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE, FlowContext ctx, MultiMap requestHeaders);
            Single<Response<Void>> n2InfoNotify(String requestURI, UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE, FlowContext ctx, MultiMap requestHeaders);

}
```

##### Command line used for generation

No, using the openapi-generator-maven-plugin

##### Steps to reproduce

maven generate-sources command

##### Related issues/PRs

#372

##### Suggest a fix
in InlineModelResolver.java Include callback-operations to be flatten:
```java
    private void flattenPaths(OpenAPI openAPI) {
        Paths paths = openAPI.getPaths();
        if (paths == null) {
            return;
        }

        for (String pathname : paths.keySet()) {
            PathItem path = paths.get(pathname);
            List<Operation> operations = new ArrayList<>(path.readOperations());

            // Include callback operation as well
            for (Operation operation : path.readOperations()) {
                Map<String, Callback> callbacks = operation.getCallbacks();
                if (callbacks != null) {
                    operations.addAll(callbacks.values().stream()
                            .flatMap(callback -> callback.values().stream())
                            .flatMap(pathItem -> pathItem.readOperations().stream())
                            .collect(Collectors.toList()));
                }
            }

            for (Operation operation : operations) {
                flattenRequestBody(openAPI, pathname, operation);
                flattenParameters(openAPI, pathname, operation);
                flattenResponses(openAPI, pathname, operation);
            }
        }
    }
```

### PR DESCRIPTION
**Pull request by lwlee2608**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fix #3397 callback request and response not being flattened to InlineObjects

cc @wing328 @jimschubert @cbornet @ackintosh @jmini @etherealjoy

### CODE REVIEW

**Comment by lwlee2608** [comment]
@wing328 Hello, Can you kindly take a look at the PR please?

**Comment by ackintosh** [comment]
Thanks for this PR! I'll take a look. ✨

**Comment by lwlee2608** [comment]
Thanks!

**Comment by wing328** [comment]
@lwlee2608 thanks for the PR, which has been included in the v4.1.1 release: https://twitter.com/oas_generator/status/1165944867391860737

**Pull request merged**
