### PR TITLE
Fix parameters_to_url_query doesn't properly convert lists to string 

### PR DESCRIPTION
**Pull request by rshacham**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR.

can you please have a look at the CI failure? 
https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/27442/workflows/fb0d4a96-c1d2-49f2-b165-22d87d542fd1/jobs/86864

**Comment by wing328** [comment]
in https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/echo_api/python/tests/test_manual.py, i wonder if you can add a test for the following endpoint:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/echo_api.yaml#L284-L309

i think that should cover the issue moving forward.

**Comment by rshacham** [comment]
This a fix for #15788

@cbornet @tomplus @krjakbrjak @fa0311 @multani 

the parameters_to_url_query() function would convert the parameters to string in all cases, except for the case where we pass a list and ask to parse it in 'multi' format.

The fix was the simple change of:
`new_params.extend((k, value) for value in v)`


To:
``new_params.extend((k, str(value)) for value in v)``

**Comment by wing328** [comment]
LGTM. let's give it a try

**Pull request merged**
