### PR TITLE
[Java][OkHttp-Gson] fix: free form query parameters for okhttp-gson

### PR DESCRIPTION
**Pull request by llendi**
Fix issue https://github.com/OpenAPITools/openapi-generator/issues/19225

### CODE REVIEW

**Comment by wing328** [comment]
please add a fake endpoint in `modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml`.

then please follow step 3 to update the samples so that CI can test the change

**Comment by llendi** [comment]
Thanks for your reply.

Added the fake endpoint, fixed the mustache api and added the samples

**Comment by llendi** [comment]
Updated to make the change minimal. If anything else is missing or needs adjustment, just let me know.

**Comment by wing328** [comment]
cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

**Comment by wing328** [comment]
thanks for the fix.

let's give it a try

**Comment by wing328** [comment]
just merged.

please give it a try with the snapshot version (published in an hour or so) to confirm it's working for you.

thanks again for the PR

**Comment by llendi** [comment]
Works as intended for me. Thank you

**Comment by wing328** [comment]
FYI. Just merged https://github.com/OpenAPITools/openapi-generator/pull/20076 to suppress the cast warning

**Pull request merged**
