### PR TITLE
Make Resttemplate thread safe by using the withHttpInfo pattern used …

### PR DESCRIPTION
**Pull request by thomasJoei**
…by many other generated clients

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
This PR is just a copy of the one I just merged in the old `swagger-api/swagger-codegen` repo 
https://github.com/swagger-api/swagger-codegen/pull/9737

This PR is to make the generated RestTemplate client thread safe. Currently, we don't have any way of retrieving the response headers except by using getResponseHeaders() method which returns the latest response headers, in the case multiple threads use the ApiClient we might end up getting the headers of the response sent to another thread.

This PR purpose is to add an additional method which not only return the expected DTO but also the ResponseEntity wrapping it, so user can easily retrieve headers by inspecting the ResponseEntity. The usual methods to directly get the DTO are conserved.

This change breaks backward compatibility since (thread unsafe) attributes, statusCode and responseHeaders, are removed from ApiClient class.

Java technical committee: 
@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/ApiClient.java
	modified:   samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/AnotherFakeApi.java
	modified:   samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeApi.java
	modified:   samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/FakeClassnameTags123Api.java
	modified:   samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/PetApi.java
	modified:   samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/StoreApi.java
	modified:   samples/client/petstore/java/resttemplate-withXml/src/main/java/org/openapitools/client/api/UserApi.java
```
Please also run `./bin/java-petstore-resttemplate-withxml.sh` to update the Pestore sample

**Comment by thomasJoei** [comment]
Thanks @wing328, didn't realize my professional email was linked into my commits instead of my Github related email. 
I updated `resttemplate-withxml` samples, re-ran the tests and updated my commit to include the changes.

**Comment by wing328** [comment]
@thomasJoei thanks for the PR, which looks good to me

The Travis CI failure has been fixed in the master.

**Comment by thomasJoei** [comment]
Thanks @wing328 !

**Comment by wing328** [comment]
@thomasJoei thanks for the PR, which has been included in v4.2.0 release: https://twitter.com/oas_generator/status/1189824932345069569

**Pull request merged**
