### PR TITLE
New generator swift5

### LINKED ISSUE #699: [SWIFT4] JSON Decoding fails to parse all valid date-time values
##### Description

The OpenAPI 3.0 specification specifies that string with format: `date-time` should match the definition of `date-time` specified in 
https://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14.

The current implementation only handles date-time values that contains micro-seconds, which is per the RFC optional. The Swift 4 version of the library should support all valid date-time values.

##### openapi-generator version

3.1.2

##### OpenAPI declaration file content or url

https://gist.github.com/grEvenX/089a8c9ecf029560299523ff048cfd5b

##### Command line used for generation

docker run --rm -v $(pwd)/generated:/out openapitools/openapi-generator-cli:latest generate -I https://gist.githubusercontent.com/grEvenX/089a8c9ecf029560299523ff048cfd5b/raw/375e5a1759d3a92edab2060d08ecf0650ba8d177/example-openapi-datetime.yaml  -g swift4 -o /out/swift4

##### Steps to reproduce

1. Generate Swift4 client
2. Use the generated client with a GET request containing model with date-time format
3. Have the server/stub return a time in date-time format without microseconds (e.g. `2018-04-30T00:00:00+00:00`)
4. Run the code, the client will crash due to not being able to decode the time properly

##### Suggest a fix/enhancement

Currently there is a `CodableHelper.swift` class generated that is used in decoding JSON.
This class opens up for providing your own DateFormatter used for parsing the dates and also provides a default code if the date formatter is not set. 
The default one provided by openapi-generator should support date-time with and without microseconds, and I think we could by default set the `dataformatter` to an instance of a class that we can provide, e.g. a new class `OpenAPIDateFormatter` which can handle this case.

I've worked around this issue by specifying my own implementation of the DateFormatter with the following code:

```swift

import Foundation

class OpenAPIDateFormatter: DateFormatter {
    override init() {
        super.init()
        
        self.calendar = Calendar(identifier: .iso8601)
        self.locale = Locale(identifier: "en_US_POSIX")
        self.timeZone = TimeZone(secondsFromGMT: 0)
        self.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ"
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func date(from string: String) -> Date? {
        if let validDate = super.date(from: string) {
            return validDate
        }
        
        // first parse-attempt failed, try parsing date without micro-seconds
        let newFormatter = self.copy() as! DateFormatter
        newFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
        return newFormatter.date(from: string)
    }
}
```

### LINKED ISSUE #4842: [REQ][Swift] make Enum's conform to CaseIterable protocol
### Is your feature request related to a problem? Please describe.

It would be nice to make the enums conform to CaseIterable protocol for the Swift compiler to be able to generate a property called `allCases` that provides an array of all cases in the enum.

## Describe the solution you'd like

I will try to create a PR that makes the enum's conform to this protocol.

### PR DESCRIPTION
**Pull request by 4brunu**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @d-date (2018/03)

### Description of the PR

This PR adds basic support for Swift 5 and it lowers the barrier of any Swift 5 contribution.
It's basically a copy of the Swift 4 generator, but it adds support for Swift Package Manager (fix https://github.com/OpenAPITools/openapi-generator/issues/4057), updates the dependencies version.

***EDIT:***
I have updated this PR to introduce some new features in along side with the new Swift 5 generator.
The new features that the Swift 5 generator has, compared with the Swift 4 generator are:
- Add nullable (or x-nullable in OAS2) support. This will replace the unwrapRequired option.
- Add support for URLSession
- Date formatter add support for ISO8601 with and without milliseconds (fixes #699 and it's a continuation of #1454)
- make enums conform to CaseIterable (fixes #4842)
- Add support for Combine framework 
- cocoapods remove deprecated docset_url and add watchos deployment target
- Add ability to pass in a dedicated queue for processing network response (Fix for https://github.com/OpenAPITools/openapi-generator/issues/230)

This PR fixes https://github.com/OpenAPITools/openapi-generator/issues/2721

### CODE REVIEW

**Comment by d-date** [comment]
@4brunu Thanks for contribution but we plan to make another generator which reduce dependencies. #4086

Since Xcode 11 has officially released so I restart to work on. Sorry for late work.

**Comment by 4brunu** [comment]
@d-date No problem 🙂
Can you elaborate on which dependencies are you removing? Is is Alamofire or another one?

**Comment by wing328** [comment]
Like other generators such as Java, Ruby that are more mature, I foresee Swift 5 generators will support the `library` option for different HTTP libraries so my take is to accept this one before anyone has time to add the library option for this Swift 5 generator.

**Comment by d-date** [comment]
@wing328 I don't agree with you. IMO, all dependencies should be removed since no more maintain so many templates for response types and APIClients.
We should provide only interfaces and models.

**Comment by d-date** [comment]
@4brunu I'm try to remove all dependencies including Alamofire since this client shouldn't have any dependencies. We want to select own API Clients and response type, including Combine, by myself.

Instead, in other repository, we should provide example API Client for users so we can focus on implementing OAS itself.

We Swift developers hope to make this generator stable for reducing developing time.

**Comment by wing328** [comment]
I see what you mean. I can only share my experience working on this project. You will always find users who want to use a particular HTTP library: Java client now supports 10+ HTTP libraries: feign, okhttp, Dart supports 2 or 3 via different generators. TS supports a lot via different generators.

Besides Alamofire, there's another one by IBM: https://github.com/IBM-Swift/SwiftyRequest

I'm not surprised if we are going to see a request from the user to support SwiftyRequest in the not too distant future.

My take is to support a swappable ApiClient class from day one and leave it up to the user to choose which HTTP library they want to use.

**Comment by 4brunu** [comment]
@d-date I also prefer to reduce the number of dependencies, so it would be nice to rely on `URLSession` instead of `Alamofire` and I even considered creating a PR that removes `Alamofire`.

But on the other hand I think it would be nice to provide an optional integration with `RxSwift.

My concern with a big new Swift 5 generator is how long it will take, because we could introduce so many improvements, `Result`, `Combine`, `URLSession`, etc, that can take a long time.

This PR actually doesn't provide any value in itself, because it's the same as in Swift 4, but it will lower the barrier to anyone that wants to contribute with improvements to the Swift 5 generator.

What do you think of a more incremental approach?

By the way, I'm totally ok closing this PR 🙂

**Comment by Tovkal** [comment]
I would merge this as is. My current use case is: I am using Swagger 2 until now, with Swift 5, and want to update to Swagger 3. So I just want to update the Swagger version while keeping the rest as it is.

I understand that there is room for improvement (decoupling from networking dependencies, adding other networking options) but I too believe this should be delivered incrementally.

**Comment by wing328** [comment]
## IMPORTANT

This generator is relatively new and being actively developed. It's considered as beta/alpha and there will be breaking changes (new features, bug fixes, etc) to this generator without further notice.

**Pull request merged**
