### PR TITLE
[cpp-ue4] Added UE4.26 support, 

### PR DESCRIPTION
**Pull request by Kahncode**
Added UE 4.26 support and improved compatibility in general.
Added support for automatic retries of a request
Fixed non-quoted enums which were broken by previous changes on master
Fixed datetime parsing with higher precision than millisecond

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

**Comment by Kahncode** [comment]
Please note that the sample generation doesn't seem to work properly for cpp-ue4. But since the checks passed, I would love for this PR to be merged and the problem to be fixed in a separate PR (would also love some help for this).

**Comment by wing328** [comment]
@Kahncode I've pushed commits to update samples and remove some trailing spaces. Please have a look at the updated sample to see if it looks good to you.

**Comment by Kahncode** [comment]
@wing328 This looks great, thanks!

**Comment by wing328** [comment]
@Kahncode thanks for the PR, which has been included in the v5.1.0 release: https://twitter.com/oas_generator/status/1373636654024380423

**Pull request merged**
