### PR TITLE
[cpp-restsdk] add support for oneOf via std::variant

### PR DESCRIPTION
**Pull request by aminya**
This PR adds support for oneOf for cpprestsdk via `std::variant`. 

This is how I tested it:
```yaml
openapi: 3.0.0
info:
  title: test
  version: 1.0.0
servers:
  - url: "{test}"
    variables:
      test:
        description: test domain
        default: https://test.com
paths:
  /test:
    post:
      operationId: test
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/A"
                - $ref: "#/components/schemas/B"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: string
components:
  schemas:
    A:
      type: object
      properties:
        a:
          type: string
    B:
      type: object
      required:
        - grant_type
      properties:
        b:
          type: string
```

The code generated looks like this:

```cpp
/**
 * test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Test_request.h
 *
 * 
 */

#ifndef test_MODELS_Test_request_H_
#define test_MODELS_Test_request_H_


#include "test_client/ModelBase.h"

#include "test_client/model/B.h"
#include "test_client/model/A.h"
#include <cpprest/details/basic_types.h>

namespace test {
namespace models {


#include <variant>

class  Test_request
    : public ModelBase
{
public:
    Test_request();
    virtual ~Test_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;

    template<typename Target>
    bool fromJson(const web::json::value& json) {
        // convert json to Target type
        Target target;
        if (!target.fromJson(json)) {
            return false;
        }

        m_variantValue = target;
        return true;
    }

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;

    template<typename Target>
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) {
        // convert multipart to Target type
        Target target;
        if (!target.fromMultiPart(multipart, namePrefix)) {
            return false;
        }

        m_variantValue = target;
        return true;
    }

    /////////////////////////////////////////////
    /// Test_request members

    using VariantType = std::variant<A, B>;

    const VariantType& getVariant() const;
    void setVariant(VariantType value);

protected:
    VariantType m_variantValue;
};



}
}

#endif /* test_MODELS_Test_request_H_ */

```

```cpp
/**
 * test
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.6.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "test_client/model/Test_request.h"

namespace test {
namespace models {

const Test_request::VariantType& Test_request::getVariant() const
{
    return m_variantValue;
}

void Test_request::setVariant(Test_request::VariantType value)
{
    m_variantValue = value;
}

web::json::value Test_request::toJson() const
{
    web::json::value val = web::json::value::object();

    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
            val = web::json::value::null();
        } else {
            val = arg.toJson();
        }
    }, m_variantValue);

    return val;
}

void Test_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (!std::is_same_v<T, std::monostate>) {
          arg.toMultipart(multipart, prefix);
        }
    }, m_variantValue);
}

template bool Test_request::fromJson<A>(const web::json::value& json);
template bool Test_request::fromMultiPart<A>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool Test_request::fromJson<B>(const web::json::value& json);
template bool Test_request::fromMultiPart<B>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);


}
}



```

Related to #6726 ##11090 and potentially some reusable code for #4239 #6378 in future PRs

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by aminya** [comment]
@ravinikam @stkrwork @etherealjoy @MartinDelille @muttleyxd Tagging the C++ committee as per request.

**Comment by wing328** [comment]
thanks for the PR.

to add some test models/specs, please do the following

1. copy ` modules/openapi-generator/src/test/resources/3_0/petstore.yaml` to ` modules/openapi-generator/src/test/resources/3_0/cpp-restsdk/petstore.yaml`
2. add oneO schema(s) to `modules/openapi-generator/src/test/resources/3_0/cpp-restsdk/petstore.yaml`
3. update `./bin/configs/cpp-restsdk-client.yaml` to use the new spec
4. regenerate the samples and commit the new files

**Comment by aminya** [comment]
@wing328 Thanks for the instructions! I have added the test with `oneOf` and also fixed various deprecations and warnings that were in the code and the build system. You can run the test via:

```
./mvnw integration-test -f samples/client/petstore/cpp-restsdk/client/pom.xml
```

**Comment by wing328** [comment]
I ran `mvn integration-test -f samples/client/petstore/cpp-restsdk/client/pom.xml` but got CMake error (the source directory /home/wing328/Code/openapi-generator/samples/pestore/cpp-restsdk/client/= does not exist)

while running the same command in the master branch is fine.

can you please take a look when you've time?

**Comment by aminya** [comment]
@wing328 I tried again it works for me. I pushed a change just in case to make the cmake path absolute. Maybe try cleaning the previous remainder. I changed where CMake builds the stuff. Previously, it was just built into the source, which causes warnings and is not recommended.

**Comment by aminya** [comment]
Cmake already provides this option through -B, which is the same flag I used in the pom.xml file. This change doesn't affect the end-users. I just changed where the test builds via Maven.

I can revert that part, but it would build the test in the same directory as the test. 

Did you try cleaning up your test-dir?

**Comment by wing328** [comment]
if you run `mvn integration-test -f samples/client/petstore/cpp-restsdk/client/pom.xml` in the project's root directory, does it work for you?

i don't see any new files created/generated that need to be cleaned up during the integration tests (but still I ran `git clean -df` clean up any files not needed)

**Comment by aminya** [comment]
Yes, that's what I've been doing. If you see the logs here:
https://github.com/OpenAPITools/openapi-generator/pull/18474#issuecomment-2076323545

I'm curious to see your full log, and what mvn exactly calls (the cmake command).

**Comment by wing328** [comment]
tested in another linux and now see build errors:
```
/usr/include/boost/exception/exception.hpp:15:44: note:   ‘boost::shared_ptr’
In file included from /usr/include/c++/11/bits/shared_ptr.h:53,
                 from /usr/include/c++/11/condition_variable:43,
                 from /usr/include/pplx/pplxlinux.h:27,
                 from /usr/include/pplx/pplx.h:49,
                 from /usr/include/pplx/pplxtasks.h:61,
                 from /usr/include/cpprest/asyncrt_utils.h:17,
                 from /usr/include/cpprest/http_client.h:47,
                 from /mnt/c/Users/wing3/Code/openapi-generator/samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/ApiConfiguration.h:24,
                 from /mnt/c/Users/wing3/Code/openapi-generator/samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/ApiClient.h:22,
                 from /mnt/c/Users/wing3/Code/openapi-generator/samples/client/petstore/cpp-restsdk/client/include/CppRestPetstoreClient/api/UserOrPetApi.h:23,
                 from /mnt/c/Users/wing3/Code/openapi-generator/samples/client/petstore/cpp-restsdk/client/src/api/UserOrPetApi.cpp:13:
/usr/include/c++/11/bits/shared_ptr_base.h:319:11: note:   ‘std::shared_ptr’
  319 |     class shared_ptr;
      |           ^~~~~~~~~~
/mnt/c/Users/wing3/Code/openapi-generator/samples/client/petstore/cpp-restsdk/client/src/api/UserOrPetApi.cpp:38:87: error: expected primary-expression before ‘>’ token
   38 | pplx::task<void> UserOrPetApi::createUserOrPet(std::shared_ptr<CreateUserOrPet_request> createUserOrPetRequest) const
      |                                                                                       ^
/mnt/c/Users/wing3/Code/openapi-generator/samples/client/petstore/cpp-restsdk/client/src/api/UserOrPetApi.cpp:38:89: error: ‘createUserOrPetRequest’ was not declared in this scope; did you mean ‘createUserOrPet’?
   38 | pplx::task<void> UserOrPetApi::createUserOrPet(std::shared_ptr<CreateUserOrPet_request> createUserOrPetRequest) const
      |                                                                                         ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                                         createUserOrPet
/mnt/c/Users/wing3/Code/openapi-generator/samples/client/petstore/cpp-restsdk/client/src/api/UserOrPetApi.cpp:38:113: error: expected ‘,’ or ‘;’ before ‘const’
   38 | pplx::task<void> UserOrPetApi::createUserOrPet(std::shared_ptr<CreateUserOrPet_request> createUserOrPetRequest) const
      |                                                                                                                 ^~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-unused-lambda-capture’ may have been intended to silence earlier diagnostics
gmake[2]: *** [CMakeFiles/CppRestPetstoreClient.dir/build.make:244: CMakeFiles/CppRestPetstoreClient.dir/src/api/UserOrPetApi.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/CppRestPetstoreClient.dir/all] Error 2
```

**Comment by aminya** [comment]
Looks like your compiler is too old. These errors are usually due to parsing errors when using old compilers. `std::variant` requires C++ 17 or 20.

**Comment by wing328** [comment]
@aminya thanks again for the PR

are you familiar with the github worflow?

can we add something similar to ` .github/workflows/samples-cpp-qt-client.yaml` but for cpp-restsdk client so that we can ensure the petstore sample compiles moving forward?

**Comment by wing328** [comment]
i've setup tests via circieci and tests with this change passed via https://app.circleci.com/pipelines/github/OpenAPITools/openapi-generator/29831/workflows/0a72a198-ca5a-4cad-a395-04d4e5ec2bcd/jobs/96380

**Comment by wing328** [comment]
we've to reverted this change as it's failing in the master for some reasons.

can you please file a new PR based on the latest master instead?

**Pull request merged**
