### PR TITLE
[Kotlin-Spring] fix arrays response api after generation

### PR DESCRIPTION
**Pull request by Lezenford**
### PR checklist
 
To fix https://github.com/OpenAPITools/openapi-generator/issues/16295

### CODE REVIEW

**Comment by wing328** [comment]
please follow step 3 in the PR checklist to update the samples so that the CI can test the change.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
samples not yet up-to-date: https://github.com/OpenAPITools/openapi-generator/actions/runs/5830122867/job/15895787232?pr=16296

**Comment by wing328** [comment]
cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) @stefankoppier (2022/06)

**Comment by Lezenford** [comment]
fix other samples.

What I need to fix problem with my comment? all of them from my fork repository

**Pull request merged**
