### PR TITLE
Add C++ UE4  client generator

### PR DESCRIPTION
**Pull request by wing328**
As discussed with @Kahncode 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

### CODE REVIEW

**Comment by Kahncode** [comment]
@wing328 Hello, I have reviewed this, it looks fine for me.

**Comment by Kahncode** [comment]
@wing328 As discussed, escaping dots in symbol names could probably be moved to the abstract CPP codegen level, as well as post processing model enums

**Comment by wing328** [comment]
@Kahncode Done. I've switched it to `camelize` to handle the dots in the symbol names.

**Comment by Kahncode** [comment]
This is great, @wing328 out of curiosity why not do this in sanitizeName? This is where other wrong symbols were escaped.

Are enums still post-processed in this version?

**Comment by wing328** [comment]
Those dots are actually useful for camelize (and other string utils such as underscore), e.g. this.is.my.name => `ThisIsMyName` but if dots are removed before camelize, it will become `Thisismyname` instead

Yes, enums are still post-processed properly in this PR.

**Comment by wing328** [comment]
As discussed, we'll file separate PRs to further improve this generator.

**Pull request merged**
