### PR TITLE
[swift5] Responses also return raw response data 

### PR DESCRIPTION
**Pull request by Jonas1893**
Related issue: #13988 
This is a proposal on how to structure `Response` object for future 7.* generator versions. In addition to the already decoded type it also contains raw response data enabling more advanced use cases like e.g. logging of the raw (JSON) response.  

This could also be backported to 6.3.* by not renaming `body` and instead adding a new property `bodyData` instead, still the naming suggested here for 7.* makes more sense to me (**ymmv** of course, please share your thoughts)

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. -> @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

### Declaration
The program was tested solely for our own use cases, which might differ from yours.

### Link to provider information
https://github.com/mercedes-benz

### CODE REVIEW

**Comment by Jonas1893** [comment]
Failing test is related to old Swift version being used on CI. To fix it we could either use a different variable name in the guard to differentiate between nullable and non-nullable version of the data object. Or we could build with a later Xcode Version on CI

**Comment by 4brunu** [comment]
Hey @Jonas1893, thanks for creating this PR.
This isn't such a big thing that would require a breaking change.
I think we could go with the back-port version of this.
But this made me think in a in a bigger change to the 7.0.x version.
Instead of returning just the decoded body, should we instead return the entire Response object, that allows access to more data?
What do you think?
Thanks

**Comment by Jonas1893** [comment]
> Hey @Jonas1893, thanks for creating this PR.
> This isn't such a big thing that would require a breaking change.
> I think we could go with the back-port version of this.
> But this made me think in a in a bigger change to the 7.0.x version.
> Instead of returning just the decoded body, should we instead return the entire Response object, that allows access to more data?
> What do you think?
> Thanks

Hey @4brunu 
fair point I'll prepare the back port instead. 

Currently for each endpoint we basically already offer the possibility to easily access the `Response` object by `execute`ing the `*withRequestBuilder` method. The other generated method offers the decoded object in the `responseAs` style and this is what most of the users probably want most of the time so I would leave that as it is. I personally feel this setup is great because it is both convenient and flexible. 

I don't think offering a second convenience method returning the `Response` object already in the correct `responseAs` style would be a big enough improvement to justify adding complexity to the templates which increases maintenance effort in the future. If you ask me I would stay with the generated methods as they are and monitor user feedback closely whether this is something that people really wish for. 

And a kind of related thought:
Currently if we had multiple responses defined in the spec like 
```
HTTP 200 -> SomeObject 
HTTP 206 -> SomeOtherObject
```
I think our convenience method which returns the decoded type currently only offers the `SomeObject` response type.  With the change from this PR there is now at least the option to manually decode depending on status code from the now returned `bodyData`. Still, it would be great if generator would support this use case as well and we can add this functionality to the convenience method using e.g. a wrapped enum type like the one that is used for `oneOf` in OpenAPI 3 specs.

**Comment by Jonas1893** [comment]
Closed in favor of #14006

**Comment by 4brunu** [comment]
Hey @Jonas1893,
Thanks for explaining your point of view, makes sense to me. 👍

**Pull request closed without merging**
