### PR TITLE
[Kotlin] enumPropertyNaming UPPERCASE should separate words with _

### PR DESCRIPTION
**Pull request by lemoinem**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
/cc Kotlin: @jimschubert @dr4ke616 @karismann @Zomzog

### Description of the PR

When using `enumPropertyNaming=UPPERCASE` with the Kotlin generators, words aren't separated by `_`, as they should be.

### CODE REVIEW

**Comment by Fjolnir-Dvorak** [comment]
Could you please add a unit test for this that the next change in the code won't change it back again or does something else so it is documented how enums should be named?

**Comment by lemoinem** [comment]
@Fjolnir-Dvorak Sorry for the delay.
I've added some tests. Could you double check I did that correctly? I'm not sure if I need to do anything else.

CirleCI fails is related to "Docker Layer Caching is not available on your plan.". Not related to PR and looks like a configuration issue.

**Comment by Fjolnir-Dvorak** [comment]
yes, I will check that, thank you for that

**Comment by 4brunu** [comment]
Any news on this PR? Looking forward to it 🙂

**Comment by Fjolnir-Dvorak** [comment]
Well, I didn't meant those tests but simple unit tests but I guess that works, too. Thank you for adding some tests

**Comment by lemoinem** [comment]
@Fjolnir-Dvorak Sorry, I looked at the existing tests I could see and didn't find how or where to add such unit tests. Any advice, is welcome... Where would the unit tests be in the code? Do you have any example of existing unit tests in the repo or any doc for it?

I did have a look at the content of `openapi-generator/modules/openapi-generator/src/test/java/org/openapitools/codegen/kotlin/`, but it seemed even more complex to setup and code than the one I added and seemed hardly readable or useful to debug...

**Comment by Fjolnir-Dvorak** [comment]
If you want I will look into it when this is merged. That test is not required. It is just nice to have those, especially because those "configurations" are easy to break by other people and are actually broken in many generators.

**Comment by wing328** [comment]
Drone.io test failure already fixed in the master.

**Pull request merged**
