### PR TITLE
[Dart] Treat float as double

### PR DESCRIPTION
**Pull request by sbu-WBT**
Double gets special special treatment in the mustache to prevent some errors like `type 'int' is not a subtype of type 'double'`.

https://github.com/OpenAPITools/openapi-generator/blob/dad931a25a54d6d1500654b96499d5239240c659/modules/openapi-generator/src/main/resources/dart2/class.mustache#L75-L82

Dart has no floats so they are replaced with doubles. Before this fix, it wasn't the case inside the mustache file so the floats had the type `double` in the class, but not the code from the `isDouble` block inside the mustache because only `isFloat` was true.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12)

### CODE REVIEW

**Comment by agilob** [comment]
Can we get a test for it pls?

**Comment by wing328** [comment]
```
       {{#isDouble}} 
 {{name}} = (json['{{baseName}}'] == null) ? 
   null : 
   json['{{baseName}}'].toDouble(); 
       {{/isDouble}} 
       {{^isDouble}} 
 {{name}} = json['{{baseName}}']; 
       {{/isDouble}} 
```

What about using `{{#isNumber}} ... {{/isNumber}}` instead?

**Comment by sbu-WBT** [comment]
Good idea, but would `{{#isNumber}} ... {{/isNumber}}` return true with an int? If not, I think it's the way to go @wing328

**Comment by wing328** [comment]
`isNumber` will return false if it's integer or long.

FYI. `isNumeric` will return true if it's integer/long/double/float.

**Comment by SimonIT** [comment]
@wing328 Replaced. I think the failing CI is not my fault because the master branch is also failing

**Comment by sbu-WBT** [comment]
@wing328 Replaced. I think the failing CI is not my fault because the master branch is also failing

**Comment by wing328** [comment]
Shippable CI not related to this PR.

**Comment by wing328** [comment]
LGTM. We'll add tests after the dart2 client is ready to make the switch to use [fake petstore](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml)

**Pull request merged**
