### PR TITLE
Fix wrong variable name in LessThan and LessThanOrEqual asserts

### PR DESCRIPTION
**Pull request by reznikartem**
### PR checklist

- [+] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [+] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [+] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [+] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fix issue, that i described in https://github.com/OpenAPITools/openapi-generator/issues/3209

### CODE REVIEW

**Comment by wing328** [comment]
@reznikartem thanks for the PR, which looks good to me.

Please run `./bin/php-symfony-petstore.sh` to update the samples.

**Comment by reznikartem** [comment]
Sorry, made it now

**Comment by wing328** [comment]
cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09), @ybelenko (2018/07), @renepardon (2018/12)

**Comment by wing328** [comment]
@reznikartem thanks for the PR, which has been included in the v4.1.3 release: https://twitter.com/oas_generator/status/1180123829626003456

**Comment by reznikartem** [comment]
@wing328 thank you for your awesome project.

**Pull request merged**
