### PR TITLE
Generated methode ApiClient.parameterToPairs failed to handle empty collections #17460

### PR DESCRIPTION
**Pull request by conleos-hoppermann**
Some of the generated methode ApiClient.parameterToPairs in Java failed to handle empty collections. See #17460

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg (2023/08)

### CODE REVIEW

**Comment by martin-mfg** [comment]
Thanks for the PR!
I am wondering if it would be more correct to return a one-element list which contains `new Pair(name, "")` instead of returning an empty list. Have you considered this option?
Also, I wish you nice holidays. :)

**Comment by conleos-hoppermann** [comment]
Hi @martin-mfg,
i wanted to fix the error as in existing implementation, e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache#L891

**Comment by martin-mfg** [comment]
I see. That's a good point. 👍

Would it make sense to also apply your fix to the Java-jersey2, Java-jersey3, Java-reasteasy, Java-vertx, android (in apiInvoker.mustache) and android/volley generators?
If that would make sense from your point of view, you are of course very welcome to apply those fixes as well. Otherwise please let me know, then I can try to find the time for this task.

**Review by martin-mfg — APPROVED** [review]

**Comment by conleos-hoppermann** [comment]
Hi @martin-mfg ,

The variants you mentioned use `Object` as the type for the value parameter and handle the empty collection later and correctly: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.musta

I wish you best for the New Year.

**Comment by martin-mfg** [comment]
Oh right. :) Thanks again for your contribution. Let's wait for the project maintainer @wing328 to merge this PR.

**Pull request merged**
