### PR TITLE
Deprecate initialCaps and replace with camelize

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

cc @OpenAPITools/generator-core-team

### CODE REVIEW

**Comment by jimschubert** [comment]
Can I propose that we separate TitleCase and camelCase from `camelize` into two separate methods? I assume `initialCaps` existed because many don't realize that `camelize(value)` is title cased and `camelize(value, boolean=false)` is camelCase.

**Comment by wing328** [comment]
>  I assume initialCaps existed because many don't realize that camelize(value) is title cased and 

Based on what I recall, initialCaps was already in the code base before I added camelize and underscore a while go. The implementations of initialCaps does not fully meet our requirement as it only make the first letter upper case and that's why we want to replace it with `camelize`

> Can I propose that we separate TitleCase and camelCase from camelize into two separate methods?

Good idea. What about introducing the following methods and mark `camelize`, `underscore` as private?

- toSnakeCase
- toTitleCase
- toCamelCase
- toKebabCase

**Comment by jimschubert** [comment]
@wing328 I think the four methods you've listed would be very clear, and easily discoverable by a good IDE.

I remember looking for `titleCase` and `kebabCase` when I first started contributing, a few years ago and didn't see these options. After a short while, I realized the usage of the current methods… but I think the above would be easier for new contributors.

👍

**Comment by wing328** [comment]
@jimschubert 👌 I'll do that in a separate PR.

**Pull request merged**
