### PR TITLE
Add `ResumableTask` to `URLSessionImplementations.mustache`

### PR DESCRIPTION
**Pull request by welshm**
Add `ResumableTask` to `URLSessionImplementations.mustache`
- Makes it testable
- Implementations can return something _other_ than a URLSessionDataTask if they want to implement another request format (sockets maybe?)
- Default implementation for `URLSession` provided

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11) @dydus0x14 (2023/06)

### CODE REVIEW

**Comment by welshm** [comment]
@jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11) @dydus0x14 (2023/06)

Please review when you can - I am trying to make it a bit more testable.

Default implementation still works as-is

**Comment by 4brunu** [comment]
Hi, first of all thanks for creating this PR.
It's a nice improvement.
The idea and the implementation looks good.
I'm just not sure about the naming `URLSessionTask` -> `CancellableResumableTask` and `func dataTask(...) -> URLSessionDataTask` -> `func resumableTask(...) -> CancellableResumableTask`.
I'm not sure if we should use different names like you propose or if we should use names similar to the original like `URLSessionTask` -> `URLSessionTaskProtocol` and `func dataTask(...) -> URLSessionDataTask` -> `func dataTask(...) -> URLSessionDataTaskProtocol`.
And we already have a `URLSessionProtocol` which would be more similar to the second option.
What do you think?

**Comment by welshm** [comment]
> Looks good to me 👍

Renamed and updated! Thank you for your comments and feedback 🙏

**Comment by 4brunu** [comment]
Looks good to me, thanks for the PR 👍

**Pull request merged**
