### PR TITLE
[Protobuf-Schema] Add enum as model support

### LINKED ISSUE #10867: [REQ][Protobuf-Schema] Enum as model support
### Is your feature request related to a problem? Please describe.

Using $ref to a file with specified enum generates empty message .proto file.

```protobuf
/*
  The version of the OpenAPI document: 1.0

  Generated by OpenAPI Generator: https://openapi-generator.tech
*/

syntax = "proto3";

package Random.Namespace;


message MyNumbers {

}
```

## Describe the solution you'd like

Generate something like this.

```protobuf
/*
  The version of the OpenAPI document: 1.0

  Generated by OpenAPI Generator: https://openapi-generator.tech
*/

syntax = "proto3";

package Random.Namespace;


enum MyNumbersEnum {
  ZERO = 0;
  ONE = 1;
  TWO = 2;
}
```

## Additional context

Referenced scheme example:
```json
{
   "$schema": "http://json-schema.org/draft-06/schema#",
   "type": "string",
   "enum": [
      "ZERO",
      "ONE",
      "TWO"
   ]
}
```

### PR DESCRIPTION
**Pull request by Yurzel**
resolves #10867 

## Resources:
- Added enum.mustache
- Partial render to model.mustache.

## Codegen
- Add "protobuf-enum-index" to enumVars in model aswell (needed for field numbers)
- ~Set ClassName to match the enumName when used as CodegenProperty~

### CODE REVIEW

**Comment by Yurzel** [comment]
Had to revert ClassName modification, because name didn't match the reference in message. Model inside postProcessOperationsWithModels doesn't have isEnum set to true so I decided to go this way.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by Yurzel** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

Thanks for the info. I hope I did it properly. Did it for the other branches aswell. #10892 and #10893.

**Comment by wing328** [comment]
LGTM.

**Pull request merged**
