### PR TITLE
[Java][*] Annotate deprecated operations and schemas

### PR DESCRIPTION
**Pull request by jenseng**
Refs #3358

Ensure `deprecated` operations are annotated/documented as such on the
generated methods. Libraries updated:
  * [feign]
  * [google-api-client]
  * [microprofile]
  * [okhttp-gson]
  * [resttemplate]
  * [retrofit]
  * [retrofit/play*]
  * [webclient]
  * [vertx]

Ensure `deprecated` schemas are annotated/documented as such on the
generated classes/fields. Libraries updated:
  * [feign]
  * [google-api-client]
  * [jersey2]
  * [microprofile]
  * [native]
  * [okhttp-gson]
  * [rest-assured]
  * [resteasy]
  * [resttemplate]
  * [retrofit*]
  * [webclient]
  * [vertx]

Also fix two minor bugs to get the java sample tests working:

* Fix an invalid jackson-datatype-threetenbp version number in vertx/pom.mustache
* Fix a bad return type in webclient/api_test.mustache when uniqueItems=true

Since this commit updates petstore-with-fake-endpoints-models-for-testing.yaml,
several other samples were updated, but it's just new files to reflect the
deprecated schemas, so there should be no consequential differences. 🤞 

Relevant bits of the spec:

* https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#user-content-operationdeprecated
* https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#user-content-schemadeprecated

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. CC @bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @nmuesch

### CODE REVIEW

**Comment by cljk** [comment]
AFAIK marking Operations as deprecated is working - marking model-fields as deprecated is not

**Comment by jenseng** [comment]
@cljk can you elaborate a bit? AFAICT it's working correctly with this commit... see ObjectWithDeprecatedFields in [the schema](https://github.com/jenseng/openapi-generator/blob/improve-deprecated-support-in-java/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml#L1851) and in all the newly generated samples, for example [this one](https://github.com/jenseng/openapi-generator/blob/improve-deprecated-support-in-java/samples/client/petstore/java/resttemplate-openapi3/src/main/java/org/openapitools/client/model/ObjectWithDeprecatedFields.java#L92)

**Comment by jenseng** [comment]
And to clarify, prior to this commit "marking Operations as deprecated" was only supported for a few Java clients (jersey2, resteasy, rest-assured, some retrofit) ... this commit brings along all the other Java clients

**Comment by cljk** [comment]
Oh, I´m sorry. I completely missed out your commit / pull request. I thought this was just an open issue description.

I checked out your pull request for `5.2.0-SNAPSHOT`, regenerated my client code and can confirm that it works as it should with deprecation marking for fields AND types.
Checked: `jersey`, `native`, `resteasy`, `retrofit`

I would by glad if this would be merged and released soon.

**Comment by cljk** [comment]
I had an uneducated look in the circleci output and tried to figure out why it failed.
Perhaps I´m wrong but it looks to me like the test env. is not set up correctly - which should not have anything to do with your commit?! Missing `go` reference?!

```
  232 passing (355ms)

go: downloading github.com/gorilla/mux v1.7.3
?   	github.com/GIT_USER_ID/GIT_REPO_ID	[no test files]
?   	_/home/circleci/OpenAPITools/openapi-generator/samples/server/petstore/go-gin-api-server	[no test files]
go go: unknown command
Run 'go help' for usage.
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (go-get) on project GoEchoServer: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :GoEchoServer
2021-05-31 16:56:34.514:INFO::main: Logging initialized @136ms
2021-05-31 16:56:34.532:INFO:oejr.Runner:main: Runner
2021-05-31 16:56:34.683:INFO:oejs.Server:main: jetty-9.2.9.v20150224
May 31, 2021 4:56:38 PM com.sun.jersey.api.core.PackagesResourceConfig init
```

**Comment by jenseng** [comment]
I'll rebase and see if it behaves better now, at the time I opened the PR it seems that most builds were failing the same way, perhaps the issue has been fixed on master?

**Comment by cljk** [comment]
This time travis, also an error and also an error of the test setup - not code modifications?!

Perhaps the maintainers can tell something about that 🤷🏼‍♂️

```
docker pull swaggerapi/petstore
Using default tag: latest
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
The command "docker pull swaggerapi/petstore" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by cljk** [comment]
@wing328 
Could you (or any other) please have a look into this pull request or say if it has good chances to be merged to 5.2.0 ? 
I would really like to have this fix...

**Comment by jenseng** [comment]
Rebased and resolved conflicts around 95a11a7f5d7. Also regenerated all samples, which brought along `fake/body-with-binary` stuff from f7b93ebdf20.

**Comment by wing328** [comment]
Sorry for the delay in reviewing as there are too many PRs to review.

I tested it locally and the result is good. We may remove some newly added samples introduced in this PR while we're consolidating the test samples.

**Comment by jenseng** [comment]
Thanks @wing328!

**Pull request merged**
