### PR TITLE
[php] enhance type mapping

### PR DESCRIPTION
**Pull request by wing328**
- map decimal to float
- revise logic in getting the type
- treat `\DateTime`, `\SplFileObject` as primitive types (not models) - except `php-mezzio-ph`, `php-dt`

Tested php client locally and the result is good:

```
................................................................. 65 / 73 ( 89%)
........                                                          73 / 73 (100%)

Time: 00:02.630, Memory: 12.00 MB

OK (73 tests, 220 assertions)

```

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc @jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) ❤️, @ybelenko (2018/07), @renepardon (2018/12)

### CODE REVIEW

**Comment by wing328** [comment]
@Articus this PR results in  some changes to php-dt, mezzio samples. Can you please review to see if you're ok with these changes?

**Comment by Articus** [comment]
Treating `\DateTime` and `\SplFileObject` as primitive types breaks code generated by both `php-mezzio-ph` and `php-dt` :( In terms of PHP language these types are not scalar and generator templates were written assuming that `isPrimitiveType` and `isDateTime` are mutually exclusive flags. So now in generated code serializator is given conflicting instructions how to handle DTO fields with these types. 

I can investigate this issue further during weekend to check what else should be adjusted.

**Comment by wing328** [comment]
@Articus thanks for the review. I'll try to workaround it.

**Comment by wing328** [comment]
@Articus worked around via https://github.com/OpenAPITools/openapi-generator/pull/10457/commits/6ed7568d71e7260501c37b6f7eef9705fba7165a. Please review the latest again when you've time. Thanks.

**Comment by wing328** [comment]
Merged as I've other enhancements for the php client generator.

**Pull request merged**
