### PR TITLE
Delete fromModel(String, Schema)

### PR DESCRIPTION
**Pull request by jmini**
First step for #83

### CODE REVIEW

**Comment by jimschubert** [comment]
This rename will be a breaking change for users who consume codegen programmatically. Is this intentional? Are we not concerned about this use case?

**Comment by jmini** [comment]
Thank you for this review.

---

Yes, but I want to make them aware that this method is different than the other one. It is not just a convenience offered (a parameter is not set, let put some default value), it produces other results!

I did not check it in details, but I wonder if it can not be removed entirely. 

---

If I continue to implement #83, a lot of methods will be different in `DefaultCodegen` and in `CodegenConfig`.

Example:
```
    CodegenModel fromModel(String name, Schema schema, Map<String, Schema> allDefinitions);

    CodegenOperation fromOperation(String resourcePath, String httpMethod, Operation operation, Map<String, Schema> definitions, OpenAPI openAPI);
```

Will be:
```
    CodegenModel fromModel(String name, Schema schema, OpenAPI openAPI);

    CodegenOperation fromOperation(String resourcePath, String httpMethod, Operation operation, OpenAPI openAPI);
```

And this will be removed.

```
    CodegenOperation fromOperation(String resourcePath, String httpMethod, Operation operation, Map<String, Schema> definitions);
```

I hope it is OK to break stuff now (before our first release) in order to be able to move forward with issues and with new OAS3 use cases.

**Comment by jimschubert** [comment]
I remember debugging an issue about a year ago, and trying to understand why one method returned one set of results and the other returned something different. I'd personally like to see the coupling between the common workflow and individual generators reduced.

I vote for removing it, just as long as it's mentioned as a breaking change in the migration docs. This is because we don't have insights into who consumes the package and uses the methods programmatically.

**Comment by jmini** [comment]
As proposed by @jimschubert, I have removed the method.

I think this PR can now be merge, I will continue to work on this in a separated PR.

**Pull request merged**
