### PR TITLE
Bash optimizations for ensure script

### PR DESCRIPTION
**Pull request by jimschubert**
This is a work in progress evaluating script execution options to see if we can speed up the ensure-up-to-date process in the short term before any changes related to #6333 

Switched from a mix of `sh`, `eval`, and script execution to `/bin/bash` with stdout redirecting to `/dev/null` results in:

```
./bin/utils/ensure-up-to-date  1118.22s user 82.57s system 191% cpu 10:26.87 total
```

Switched from `/bin/bash` to `/usr/bin/env bash` and installed bash 5.0, the results were similar:

```
./bin/utils/ensure-up-to-date  1119.88s user 82.50s system 195% cpu 10:16.37 total
```

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
Minor suggestion: I notice all `*-all.sh` scripts are now redirecting standing out to /dev/null, which means users won't see anything (unless errors) in the console.

If a contributor is new to the project, he may find it weird not to see anything in the output so maybe good to output a line or two explaining that and ask the user to run "git diff" to inspect any changes in the samples after running the script.

(personally I prefer showing the output but I'm ok if you guys want to skip that)

**Comment by spacether** [comment]
My results of running this are:
current master branch version:
```
time ./bin/utils/ensure-up-to-date
real	15m10.222s
user	30m26.134s
sys	1m56.234s
```

This PR's branch:
```
time ./bin/utils/ensure-up-to-date
real	16m12.935s
user	31m14.657s
sys	2m1.649s
```
Which is pretty close for me too.
Should we merge this if there is no significant time improvement?

**Comment by jimschubert** [comment]
Let me remove the stdout redirects from the `-all` scripts and try sh rather than bash

**Comment by jimschubert** [comment]
I'm closing this since it seems to add only trivial time improvements. I'll focus on converting samples scripts to a conventional batch processor instead.

**Pull request closed without merging**
