### PR TITLE
Support x-internal in models and operations

### PR DESCRIPTION
**Pull request by wing328**
add code to skip operations, models with x-internal set to true

cc @OpenAPITools/generator-core-team 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by amaechler** [comment]
We use `x-internal` to distinguish company internal from external (published) APIs, but we still want to generate operations and models for those internal APIs.

With this added skip functionality, is there a way to continue to do so?

**Comment by wing328** [comment]
@amaechler yes, please see https://github.com/OpenAPITools/openapi-generator/pull/17734 to do so with a rule in openapi normalizer.

**Comment by amaechler** [comment]
Aw, I see. Thanks for the quick response @wing328!

**Comment by Herrick19** [comment]
@wing328 

Hi William, I just updated to 7.3 and without changing anything else, now, all my operations that are listed as x-internal=true are no longer generated.

I see this in the log for each file not generated:
[main] INFO  o.o.codegen.DefaultGenerator - Operation (get /1/object/versionhistory/getList - Versionhistory_GetList_V1) not generated since x-internal is set to true

I would expect the x-internal to be GENERATED by default, not SKIPPED by default... I've analysed your commits and documentation and unless we set the:
--openapi-normalizer REMOVE_X_INTERNAL=true

They shouldn't be SKIPPED from my understanding...

Is it possible this parameter was somehow been set to TRUE by default ?

I tried to turn the behavior OFF by using
--openapi-normalizer REMOVE_X_INTERNAL=false
without success, they are still not generated.

I haven't seen any bug report on this yet, before I open one, I was wondering if you had any idea ?

Thanks in advance

**Comment by wing328** [comment]
please use `--openapi-normalizer REMOVE_X_INTERNAL=true` to ignore x-internal.

**Comment by Herrick19** [comment]
Hi @wing328 

I confirm this works so thank you very much.

But to be honest I found counter-intuitive 2 things:
1- First, why remove internal by default. People need to generate SDK for their internal too when doing it for their backend and even for calling their own frontend. But anyway, as long as we can toggle this setting off it's good.

2- To keep x-internal you need to set "REMOVE_X_INTERNAL=true". Kind of messing with the brain... I thing the documentation on "https://openapi-generator.tech/docs/customization/" doesn't help either:
REMOVE_X_INTERNAL: When set to true, remove x-internal extension from operations and models.

It should probably say something "Set to true if you want to disable the default behavior or removing the x-internal operations and model".

For me, everything is good, but wanted to detail this in case someone finds this post.

Thanks again !

**Comment by wing328** [comment]
thanks for the feedback. i'll later revise the doc to make it clearer

**Comment by r-oleary** [comment]
Great change! (even though it broke our automation initially too) But very appreciated.

QQ - is there a way to use this to generate a NEW openapi yaml file with these calls removed? Use this as a kind of filter?

Thanks!

**Comment by wing328** [comment]
> QQ - is there a way to use this to generate a NEW openapi yaml file with these calls removed? Use this as a kind of filter?

not at the moment.

if you would like to contribute to sponsor this enhancement, please open a new issue for tracking.

**Comment by jpraet** [comment]
image

You need to set it to **true** to **disable** it? Seriously? 😕

**Pull request merged**
