### PR TITLE
[WIP] csharp-netcore HttpClient

### PR DESCRIPTION
**Pull request by devhl-labs**
This is the beginning changes to move to HttpClient. It was working for my use case before I made the ApiException generic. At the moment it requires some post processing to replace ???? to ? and ??? to ?. This can be appended to the powershell script that begins the creation process in the first place. If this is good, then there is a lot of work to be done.

https://github.com/OpenAPITools/openapi-generator/issues/6800
https://github.com/OpenAPITools/openapi-generator/issues/5375

### PR checklist
 
- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
@devhl-labs thanks for this. What about adding the `library` option and let users choose which HTTP libraries  to use? That's something we've already done in a few other generators, e.g. java, ruby.

**Comment by devhl-labs** [comment]
There is no interface on HttpClient so it's hard for me to imagine how to do that gracefully. Plus HttpClient is very versatile. Even in the RestSharp library people are asking for it to use HttpClient, though it doesn't look like it will happen.

**Comment by devhl-labs** [comment]
Also I'm guessing the changes I'm made would lead toward a mass rewrite, scrapping almost everything. That's why I put this pr here before I do such a thing. I doubt I'd migrate all the supported features since I only use a small subset.

**Comment by wing328** [comment]
I saw the changes you made and we can easily support those via library option (which uses a new set of mustache templates) instead of using `{{#isHttpLibrary}} .... {{/isHttpLibrary}}` to handle the logic in all the existing template.

I'll file a PR to add the library option and we can merge this one into that one to continue the work.

**Comment by devhl-labs** [comment]
Oh like a set of mustache files for RestSharp and a whole other set for HttpClient?  Yes that would be ideal as it wouldn't break for existing users.

**Comment by wing328** [comment]
Right. I'll try to file the PR in the afternoon and keep you posted.

**Comment by wing328** [comment]
And thanks for starting the work on this. Much appreciated.

**Comment by wing328** [comment]
I'll merge this into the branch `csharp-netcore-httpclient` to make it easier to collaborate on adding HttpClient support.

**Comment by wing328** [comment]
I've added the library option (`httpclient`) in the branch. Please have a look at https://github.com/OpenAPITools/openapi-generator/pull/8331 and let me know if you've any question.

**Pull request merged**
