### PR TITLE
[kotlin-spring] Fix inheritance compile error because of missing use-…

### PR DESCRIPTION
**Pull request by superbob**
# [kotlin-spring] Fix inheritance compile error because of missing use-site target on annotation (#3596)

This PR fixes annotation generation on kotlin interface attributes when using inheritance.

Using this example openapi spec:

```yaml
openapi: 3.0.1
info:
  title: example
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: successful operation
components:
  schemas:
    Animal:
      type: object
      properties:
        weight:
          type: number
        hasLegs:
          type: boolean
      discriminator:
        propertyName: animalType
      required:
        - animalType
        - hasLegs
    Pet:
      allOf:
        - $ref: "#/components/schemas/Animal"
        - type: object
          properties:
            name:
              type: string
```

With the existing code, it would generate the Animal class like this:

```kotlin
package org.openapitools.model

import java.util.Objects
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Email
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size
import javax.validation.Valid
import io.swagger.v3.oas.annotations.media.Schema

/**
 *
 * @param hasLegs
 * @param weight
 */

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "animalType", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = Pet::class, name = "Pet")
)

interface Animal{
                @Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "")
        val hasLegs: kotlin.Boolean

                @Schema(example = "null", description = "")
        val weight: java.math.BigDecimal?


}
```

This does not compile because the `@Schema` annotations cannot be applied on an interface field. We must specify the use-site target: `get`.  
With this commit it becomes:

```kotlin
package org.openapitools.model

import java.util.Objects
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Email
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size
import javax.validation.Valid
import io.swagger.v3.oas.annotations.media.Schema

/**
 *
 * @param hasLegs
 * @param weight
 */

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "animalType", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = Pet::class, name = "Pet")
)

interface Animal{
                @get:Schema(example = "null", requiredMode = Schema.RequiredMode.REQUIRED, description = "")
        val hasLegs: kotlin.Boolean

                @get:Schema(example = "null", description = "")
        val weight: java.math.BigDecimal?


}
```

ℹ️ The examples were generated using the KotlinSpringServerCodegenTest#useTargetOnInterfaceAnnotations() unit test and a breakpoint before performing assertions.

In this version you can see the `get` use-site specified in the interface fields.

I have written 2 unit test corresponding to this change in the `KotlinSpringServerCodegenTest` class because the issue impacts Swagger1 and Swagger2 generation and the generated annotations are different.

Thanks for reviewing this ❤️  
@jimschubert, @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files.
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
  ⚠️ **Actually there were a lot of python files marked as deleted, but I didn't change anything related to this, so it seems completely unrelated to my commit.**  
  **Also there were tests errors related to _PythonClientTest_, again I didn't change anything regarding python codegen.**
- [ ] In case you are adding a new generator, run the following additional script : 
  ```
  ./bin/utils/ensure-up-to-date
  ``` 
  Commit all changed files.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by 4brunu** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by superbob** [comment]
> Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.
> 
> Let me know if you need help fixing it.
> 
> Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

Oh, nice catch. I'll change this shortly 🙂

**Comment by superbob** [comment]
@4brunu , I updated my commit so that it corresponds to my GitHub account.  
I see a test error on CircleCI for this commit but nothing changed in the code between this one and the previous one which passed successfully. It seems to be a false positive here.

**Review by 4brunu — APPROVED** [review]
Looks good to me 👍 Lets see if CI passes

**Pull request merged**
