### PR TITLE
[Go] Fix deepObject serialization that are anyOf

### PR DESCRIPTION
**Pull request by tanmaykm**
Updates the go client generator to have the generated struct for anyOf types conform to `MappedNullable` interface. Fixes query params serialization for deepObjects that are of `anyOf` type.

Implements the suggestion in https://github.com/OpenAPITools/openapi-generator/issues/19085

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

cc: @wing328 @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

can you please review the test failure when you've time?

**Comment by tanmaykm** [comment]
Thanks @wing328 for taking a look.
The test failures are now resolved.

**Comment by tanmaykm** [comment]
Does this look good now @wing328 ?

**Comment by wing328** [comment]
can you please add a test or 2 to `modules/openapi-generator/src/test/resources/3_0/go/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml` and regenerate the samples?

**Comment by tanmaykm** [comment]
@wing328 added tests to `petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml` in https://github.com/OpenAPITools/openapi-generator/pull/19090/commits/c8b07f75ea8cc70b0a1e1f74cd9db2cd594f6021

**Comment by tanmaykm** [comment]
@wing328 is there anything else needed?

**Comment by wing328** [comment]
nope. let's give it a try

thanks for the PR

**Pull request merged**
