### PR TITLE
Fixed the generation of model properties whose data type is a composed (allOf) schema

### PR DESCRIPTION
**Pull request by rubms**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fixed issue #582. The problem came from the https://github.com/OpenAPITools/openapi-generator/commit/a897feef50989d8b0d0238c067eebaef4f7f6c70 commit in the https://github.com/OpenAPITools/openapi-generator/pull/360 pull request. After that commit, the generation of model properties whose data type is a composed (allOf) schema was broken: the data type name of the generated property was that of the first model participating in the allOf clause. 

After this fix the property data type is again as expected: the one of the composed schema and not one of its parents (models involved in an allOf clause).

cc @jmini @wing328

### CODE REVIEW

**Comment by rubms** [comment]
This affects the generation of models in every language. Should I run the generation of all the samples as well? I have done it locally and I observe that some samples were outdated and contain changes unrelated to this fix.

**Comment by wing328** [comment]
@rubms thanks for the PR. Let me take a look first.

cc the core team as well: @jimschubert @ackintosh @cbornet @JFCote @jaz-ah

**Comment by jmini** [comment]
@rubms you should run at least `./bin/utils/ensure-up-to-date` because it updates the `samples/` that are checked by Shippable CI.

Read more: https://github.com/OpenAPITools/openapi-generator/wiki/Pull-Request-Checklist#shippable-ensure-up-to-date

**Comment by jmini** [comment]
PS: As for the case of

> Shippable — Run 1917 status is FAILED. 

This is not related to this change, also the builds on `master` branch are broken with the same error.

**Comment by rubms** [comment]
Thanks @jmini. I'm on it.

**Comment by jmini** [comment]
@rubms: you can just merge `master` into your branch.

**Comment by JFCote** [comment]
Merged!

**Comment by rubms** [comment]
Thanks everyone!

**Pull request merged**
