### PR TITLE
[cpp-ue4] fix for generating formParams in json requests

### PR DESCRIPTION
**Pull request by leith-bartrich**
Issue 10175 describes a potential bug and potential remedy.  This pull request is the basic fix I referenced in the issue.

https://github.com/OpenAPITools/openapi-generator/issues/10175

Simply put:  if there is no body parameter defined, it tries to generate a json body from formParams.  If a formParam isn't required, it uses IsSet from TOptional<> before writing the parameter.

See the referenced issue for the example schema that seems to require this template fix.

To be clear, this isn't really tested against a wide array of OpenAPI schemas.  And there are further issues with the generator.  But as a first pass, this at least gets a standard Django api-token-auth to be accepted by a Django server, and doesn't ruin other end points in my sample schema.

tagging @Kahncode as requested.

I'd want some more eyes on this at the very least.  And my conceptual question from the issue still stands.  I presume this to be a template problem, rather than a generator problem.  But that might not be correct.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by Kahncode** [comment]
Looks good to me.

**Comment by wing328** [comment]
Submitted https://github.com/OpenAPITools/openapi-generator/pull/10194 to update the samples

**Comment by Kahncode** [comment]
Hello, we actually have issues created from this pull request. I'd love to discuss it further.

As far as I understood, a request cannot have body and form params at the same time. But then again, form params should never be generated as json body.

The error happens when a request has a file param, as this cannot be translated into a json body.

What is the expected behavior according to you @leith-bartrich ?

**Comment by Kahncode** [comment]
Hello @leith-bartrich. Thanks for the thorough answer.

There are very valid points here, in particular, no matter what the standard says, we have to support as many real world cases as we reasonably can. 

I fixed the issue by simply omitting the file parameters when performing the fallback to form parameters generating a json body.

I do think that, this is in fact a generator issue, as it should not give both form and body parameters in the same request, as you may either send a json payload or a binary form, and not both at the same time. But regardless, the template must handle it gracefully.

> Also, when this was written, the generated client code automatically preferred the JSON-RPC implementation when really an application should be able to choose based on application logic.

Absolutely great point. This could be made as an option in the generator, although nobody has requested it. There are also many formats such as xml that are not supported in this template.

> My question would be; do you have a schema that says the following: This endpoint only takes a JSON-RPC request, and that request contains a file parameter. If so, I wonder if that's even a legal schema endpoint?

Yes, hence the error with your change. Any RPC with a file parameter as form parameter and no body parameters would attempt to compile illegal code.

https://github.com/OpenAPITools/openapi-generator/pull/15068

I improved the template to only attempt to fill the body with the form parameters if no body parameters are defined. Alongside ignoring files (and printing an error) altogether, I believe this should solve most real world cases.

If you have the chance, please review those changes and perhaps confirm that they work with your use case, as I would not want to break anything.

https://github.com/OpenAPITools/openapi-generator/pull/15068

**Pull request merged**
