### PR TITLE
[TS] Fixes typescript-axios "File custom.d.ts not found" when building consumer TS project

### PR DESCRIPTION
**Pull request by alavkx**
Fixes https://github.com/OpenAPITools/openapi-generator/issues/4227

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07)

### CODE REVIEW

**Comment by macjohnny** [comment]
@alavkx what is the impact of removing this `custom.d.ts`?

**Comment by macjohnny** [comment]
please re-generate all typescript-axios samples with 
```
mvn clean package
https://github.com/OpenAPITools/openapi-generator/blob/master/bin/typescript-axios-petstore-all.sh
```
See https://circleci.com/gh/OpenAPITools/openapi-generator/9747#tests/containers/2

**Comment by alavkx** [comment]
> please re-generate all typescript-axios samples
Hmm 🤔 
I did that but there were no file changes, strange. I'll give it another go.

> @alavkx what is the impact of removing this custom.d.ts?
I didn't find any impact, but I also don't understand the purpose of the file in the first place.

It is a declaration file with a single module, node's "url" module. I'm assuming that this declaration was created because `@node/types` was missing the url module in an older version. I've upgraded the package responsible for the types to the latest and removed the declaration—the project compiles a-ok.

Forgive my formatter making this diff so big, I can fix it up if we decide to merge this in.

**Comment by alavkx** [comment]
Is there instructions somewhere for forking openapi-generator and building a binary to use in a fork of [the node cli](https://github.com/OpenAPITools/openapi-generator-cli)?

I understand if this takes a while to get merged in. The problem is blocking other typescript projects from consuming the client — help with a workaround would be greatly appreciated ❤️

**Comment by macjohnny** [comment]
@alavk you could also write a small script that will simply delete that file after generating code.

**Comment by wing328** [comment]
@alavkx thanks for the PR, which has been included in v4.1.2 release: https://twitter.com/oas_generator/status/1189824932345069569

**Pull request merged**
