### PR TITLE
[Go] Go Client Code generation: customise location of the generated model files

### LINKED ISSUE #12307: [Question] [Go] How could I specify the generated golang client model files in a ceratin folder?
企业微信截图_16519241735329 
As the image, there are too many model files in the generated golang client, how could I specify the model files in a certain folder for code clean?

### PR DESCRIPTION
**Pull request by gcatanese**
@antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04)

The changes allow specifying in which folder the model files should be placed during the code generation.
The default location can be overridden by passing the sub-directory in the additional properties ie --additional-properties=modelFileFolder=model

How to validate the changes?

Generate models passing --additional-properties=modelFileFolder=model

Fix #12307

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.0.1) (patch release), `6.1.x` (breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by gcatanese** [comment]
@wing328 circle-ci build is broken but I am not sure about the cause (my changes or maybe networking issue)

**Comment by gcatanese** [comment]
> @wing328 circle-ci build is broken but I am not sure about the cause (my changes or maybe networking issue)

@wing328  Please let me know (when you have time) if you have any idea/hint why the pipeline fails, and if this PR can be merged (or if further changes are necessary maybe?). Thank you.

**Comment by wing328** [comment]
@gcatanese thanks for the PR. Instead of adding an option, what about moving the model files to the new location after the code generation process completes?

**Comment by gcatanese** [comment]
> @gcatanese thanks for the PR. Instead of adding an option, what about using commands to move the model files to the new location after the code generation process completes?

@wing328 thanks for the feedback. Sorry, I am not sure I understand the option you propose. Is there a different way to do this in openapi-generator? Or do you mean do that after the codegen? Can you please elaborate? Thanks

**Comment by gcatanese** [comment]
@wing328 any further thoughts on this? I considered moving the models after the codegen, but next time I am re-generating from the specs (ie API upgrade with new/updated models) I would see the models again in the main folder (thus dropping the previous `model` folder and move the newly created ones). I still find it not great but if this is the expected behaviour please let me know and I can close the PR. Thanks for your time.

**Comment by gcatanese** [comment]
@wing328 any further thought on this? The `python-nextgen' also creates a folder for the generated models, I find this useful and elegant. Let me know if this is PR is to be considered (I can rebase/resolve conflicts) or if I should instead close it. Thanks.

**Comment by wing328** [comment]
please resolve the conflicts when you've time and i'll try to merge before the v6.3.0 release.

**Comment by gcatanese** [comment]
@wing328 Done

**Comment by wing328** [comment]
FYI. submitted https://github.com/OpenAPITools/openapi-generator/pull/14580/commits/4f4c4d5d3b13b8c5013c31619f431214bbe6b7b3 with minor fix for Windows.

**Pull request merged**
