### PR TITLE
Delete body angular

### PR DESCRIPTION
**Pull request by topce**
fix
https://github.com/OpenAPITools/openapi-generator/issues/7557
https://github.com/OpenAPITools/openapi-generator/issues/10448
fix isBodyAllow to return true in case of DELETE method
add new method isMethodPutOrPatchOrPost

fix angular typescript client to allow delete with body
if angular version  allow it use isBodyAllow in template 
otherwise use isMethodPutOrPatchOrPost
angular fix client in version12.1
change default angular version to be latest 
in this moment 12.2.12 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

technical committee:
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02)

Hi @wing328 if you have time can check this (with other maintainers) because
I change templates in other libs 
however tried not to break anything

### CODE REVIEW

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team  as the change covers CodegenOperation.java

**Comment by wing328** [comment]
LGTM

**Comment by angelaki** [comment]
Hey, I'm using openapi-generator-cli to generate my Angular code. Right now I'm strugging with DELETE not containing my body. Seams like this was pretty muched discussed - but implemented? What am I doing wrong? Isn't this fix included in the cli, yet?

docker run openapitools/openapi-generator-cli generate -i swagger.json -g typescript-angular -p=useSingleRequestParameter=true -o ./out  --skip-validate-spec

**Comment by macjohnny** [comment]
@angelaki it was reverted in https://github.com/OpenAPITools/openapi-generator/pull/10976

**Comment by angelaki** [comment]
> @angelaki it was reverted in #10976

Oh, too bad. But thank you. Is there right now any way to generate a DELETE-method containing a body? Was there a released version supporting it? And: why wasn't just the `request` method used?

**Comment by angelaki** [comment]
> @angelaki it was reverted in #10976

Sorry for bumping, but I'd really need this feature. Since I haven't found any pending issues, does this _work as expected_ right now? Can I maybe help here fixing this issue?

**Comment by macjohnny** [comment]
@angelaki sure, you can file a new PR. Please keep in mind the discussion in https://github.com/OpenAPITools/openapi-generator/pull/10976, ie a flag to enable this behavior would probably be good

**Comment by angelaki** [comment]
@macjohnny do you maybe remember the reason `request` isn't used instead of get / post / patch ...? Not just for delete but in general? So the generated code would be less dependent on Angular changes?

**Comment by macjohnny** [comment]
@angelaki unfortunately I dont remember, but maybe you can find some previous PRs where this was discussed.

**Pull request merged**
