### PR TITLE
[abstract csharp] Ensure enum dataType is not nullable string

### PR DESCRIPTION
**Pull request by devhl-labs**
This will fix a case where the enum dataType is string? instead of string resulting in code that does not compile. This simply corrects the dataType.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti

### CODE REVIEW

**Comment by devhl-labs** [comment]
Did not change 89 files. Only AbstractCSharpCodegen and CSharpModelTest changes should be considered.

**Comment by devhl-labs** [comment]
circleci failed with `02:53:46.426 [qtp2074407503-16] INFO  i.s.sample.resource.PetResource - updatePetWithForm 12830 golang` which is not related.  AppVeyor failed with `Error calling GetPetById: {"code":1,"type":"error","message":"Pet not found"}` which I don't see how that can be related.

**Comment by wing328** [comment]
I saw changes to samples (e.g. scala) not related to this change.

Can you please merge the latest master your branch and update the samples again?

**Comment by devhl-labs** [comment]
I will do that next week. Im out of town now.

**Comment by devhl-labs** [comment]
@wing328  Done

**Comment by devhl-labs** [comment]
@wing328  Now it's better. Why does did it take 18 commits to change two files 🤣

**Comment by wing328** [comment]
Gradle, maven plugin test failure already fixed in the master.

**Pull request merged**
