### PR TITLE
[php-symfony] Update to newer jsm serializer version

### PR DESCRIPTION
**Pull request by xvilo**
We've been using the library already on PHP for some time with backward compatibility to 7.4 (config platform override in composer.json). 

However, we want to fully move to PHP 8.0 and we need an updated version of JMS serializer bundle.

THIS MR IS A DRAFT AND STILL NEEDS TO BE TESTED. FEEL FREE TO GENERATE A CLIENT AND TEST IT FOR ME. 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (5.3.0), `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by xvilo** [comment]
@ybelenko maybe you can help me out with this ?

**Comment by ybelenko** [comment]
> @ybelenko maybe you can help me out with this ? 

With the code or review? Frankly, I'm Symfony newbie, never used it before in real life projects.

**Comment by xvilo** [comment]
Alright, more of a general question, can I update the generated code to just use PHP 7.0 and newer. I know 7.1 and 7.2 are already EOL'ed and 7.3 soon, but we now still support 5.4+. I'm not sure if we are bound to support certain EOL'ed versions. If not I will update this too

**Comment by ybelenko** [comment]
> Alright @ybelenko, more of a general question, can I update the generated code to just use PHP 7.0 and newer. I know 7.1 and 7.2 are already EOL'ed and 7.3 soon, but we now still support 5.4+. I'm not sure if we are bound to support certain EOL'ed versions. If not I will update this too

We don't support eol php version. About which one too choose 7.3, 7.4 or 8 we had a discussion at #9200. If you would ask me personally, I don't even think it's really important, because I always overwrite `composer.json` with custom template. Most of the users expect `php: ^7.3 || ^8.0` dependency.

**Review by dbauer97 — APPROVED** [review]

**Comment by xvilo** [comment]
We've been using these patches/changes for the past 10 days in our test set-up and have not noticed anything out of the ordinary. It would be great if these could get reviewed and approved/merged. 

@jebentier (2017/07), @dkarlovi (2017/07), @mandrean (2017/08), @jfastnacht (2017/09), @ackintosh (2017/09) ❤️, @ybelenko (2018/07), @renepardon (2018/12)

**Comment by simoneantreem** [comment]
Hi! I am using the generator in a project with php 8.1.1 and Symfony6. Here my suggested updates: https://github.com/OpenAPITools/openapi-generator/compare/master...sensorario:master. May I help you in this pull request?

**Review by dmetzner — APPROVED** [review]

**Comment by ybelenko** [comment]
@xvilo thanks for the effort. I'm closing PR without merge in favour of #11810 let's focus in the one thread.

**Pull request closed without merging**
