### PR TITLE
[Java] remove threetenbp dependency

### PR DESCRIPTION
**Pull request by hugo-ma-alves**
Hello

On this PR i removed the threetenbp dependency from java code base. I saw this change suggested on the issue #3258
Now by default the generated clients use java8 dates.

This change affected a lot of files, so it is big PR for review, fortunately most of the changes are on the samples. 

Feedback appreciated, Thanks :smiley: 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.3.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @nmuesch (2021/01)

### CODE REVIEW

**Comment by wing328** [comment]
@hugo-ma-alves thanks for the PR. When you've time, can you please resolve the merge conflicts?

cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03) as the changes cover Kotlin generators

**Comment by 4brunu** [comment]
I think we should make the java8 date to the default date library, but keep the `threetenbp` dependency and update it.
Personally I still use `threetenbp` on Android, because it has updated timezones.

**Comment by hugo-ma-alves** [comment]
@wing328  PR updated

My opinion about the removal of the threetenbp library.
The objective of the threetenbp was to backport jsr310 to java 6 and 7, but this project has removed the support for jdks <8. So I believe it doesn't make sense to keep a partial implementation of the jsr310 when we can have the "real" one.

Another point is that I think we are trying to handle 2 different problems, the api client itself and timezones. The timezones-data shouldn't be tied to a specific api client. That info should be independent of the client. For example, if tomorrow there is some change to the time-zone database you shouldn't need to regenerate the client, but only to update the timezone database.

But it is up tot he project maintainers to decide if we keep threetenbp or not.

**Comment by 4brunu** [comment]
@hugo-ma-alves I understand your point.
I'm just suggesting to keep the threetenbp library as a non default option because this will be an issue for some Android Developers, because Android has some unique problems related to fragmentations, that threetenbp helps with.
And since threetenbp integration it's done, it's not much work to keep the dependency updated.
I'm keeping the threetenbp library updated in the kotlin client.

**Comment by hugo-ma-alves** [comment]
Ok, I wasn't aware of those problems on Android.
So in this case it is a decision for the project maintainers. @wing328  In which direction the project wants to go, remove the threetenbp or keep it as an workaround for android?

This Pr has again Merge conflicts, if the objective is to merge it I can resolve them, otherwise you can close the PR.

**Comment by 4brunu** [comment]
But independently of the decision, I support make java8 dates the default option.

**Comment by wing328** [comment]
@hugo-ma-alves thanks for the PR. We've performed some cleanup of the code relate to threetenbp in the master (upcoming v6.0.0 release). Please give it a try and we'll be happy to reopen this PR if needed.

**Pull request closed without merging**
